### ISSUE TITLE
Vagrant Package with Host-Only Adapter (private_network) creates Virtualbox *.box incompatible with different configurations (Windows)

### ISSUE THREAD

**Issue by togume** [mitchellh/vagrant#2083]
Packaging a VirtualBox vagrant instance that has been created with a Vagrantfile which uses the `config.vm.network :private_network, ip: "x.x.x.x"` parameter creates a *.box with a box.ovf which is incompatible with Windows:

* Packaged a vagrant instance on OSX 10.8.4, VBox 4.2.16
* Vagrantfile included:
 * `config.vm.network :private_network, ip: "192.168.33.10"`
* Resulting box.ovf in the Vagrant Box included the `vboxnet0`
* Adding the resulting vagrant box to a windows environment causes error because it does not use the same naming convention for Host-Only Adapter

Workaround:
* Configure vagrant instance
* Before repackaging, with the instance off:
 * Open VBox manager
 * Set Network --> Adapter 2 (or Host-Only Adapter) --> Attached to: Not Attached | Uncheck "Enable Network Adapter"
* Package instance into box

Proposed solutions:
1. `vagrant package` removes interfaces to make box OS agnostic
2. `vagrant up` removes possibly problematic network settings (vboxnet0)

Let me know if this is pebkac, or if I can be of any help.

**Comment by mitchellh** [comment]
Agreed upstream :(
