### ISSUE TITLE
Passing Environment Variables through to Puppet Apply

### ISSUE THREAD

**Issue by simondean** [mitchellh/vagrant#2270]
Hi.  There seems to be no way to pass environment variables to the Puppet Apply process when using Vagrant.  Being able to do this would really help when behind a proxy server.  It's important to note that the proxy is _not_ needed to contact a Puppet master etc.; the proxy is needed for the VM to install things (and not just things from a Linux package repo).  At the minute I have to either litter my puppet modules and manifests with proxy settings or change the global config of the VM to make every process in the VM use the proxy server.  

It would be really helpful if Vagrant supported something like this (the environment property is the new bit): 

``` ruby
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "init.pp"
    puppet.environment = {
      "http_proxy": "http://proxy:8080",
      "https_proxy": "http://proxy:8080"
    }
  end
```

The great thing about this approach is that once "vagrant up" is finished, it doesn't leave any proxy config in the VM.

**Comment by phanson** [comment]
Thanks @simondean for the workaround! This is a big issue for anyone behind a proxy.

One more data point: I previously tried passing the proxy config using `puppet.options` and had no luck.

**Comment by mbrodala** [comment]
@mitchellh Can you have a look at this again? Especially considering #6688.
