### ISSUE TITLE
Ignores ansible configuration

### ISSUE THREAD

**Issue by eggsby** [mitchellh/vagrant#2302]
_Background:_

ansible supports configuration through a `ansible.cfg` file next to the playbook, or through `~/.ansible.cfg` to provide default configuration values. 

_Bug:_

All configuration options set through the ansible provisioner plugin (inventory file, host key checking, etc) currently blow away any configuration the user has provided through other means.

The most glaring case is the inventory file -- the plugin auto-generates an inventory file to use if one isn't provided, overriding the hostfile preference set in ansible.cfg.

_Use case:_

My inventory file is a script which happens to know about vagrant. I don't want to specify the path to that script in every Vagrantfile since I already specify it in my ansible.cfg

_Possible resolution:_

I think that there should be a config option like `ansible.generate_inventory = false` as an alternative to setting the inventory path.

-- Thanks,
Thomas

**Comment by gildegoma** [comment]
The usage of `ANSIBLE_CONFIG` environment variable is [documented](https://github.com/mitchellh/vagrant/commit/84eb0d972c4751844895523f7805a562e8506ca7) as of Vagrant 1.5.0.

@eggsby can we try to re-formulate together the feature request(s), maybe by closing this issue and open some new one(s).

My rough summary is:
* ability to disable some default behaviours (e.g. disable inventory generation, without having to provide a static inventory)
* ability to indicates the path to an `ansible.config_file`, and let vagrant export `ANSIBLE_CONFIG` accordingly.

I think that both features should not be coupled. 
@eggsby Do you agree on this wish list? Is there something else?

**Comment by eggsby** [comment]
@gildegoma et al,

I will close this issue as the documentation changes and existing provisioner behavior are enough to solve the original issue I encountered.

Adding the capability to configure these sorts of things through the Vagrantfile would be wonderful.

In regard to inventory generation & dynamic inventory scripts, as hinted at in the documentation I have taken to putting my scripts in `.vagrant/provisioners/ansible/inventory` which then gets merged with the vagrant generated hostgroup by ansible.

The existing functionality works well for my use case, it was just maybe a little non-obvious to come across.

Cheers,
Thomas

**Comment by gildegoma** [comment]
@eggsby glad to see your positive feedbacks, thanks for such a quick and informative reply :)

To make it clear to the user community, pull requests for the following features are very welcome (but no active development has started yet):

> * ability to disable some default behaviours (e.g. disable inventory generation, without having to provide a static inventory)
>
> * ability to indicates the path to an ansible.config_file, and let vagrant export ANSIBLE_CONFIG accordingly.

If interested, please create a new issue referencing to this comment.

**Comment by ayen-tibco** [comment]
Please re-open as Vagrant's ansible integration still overrides ansible.cfg settings for example "--timeout=30" is hard hard coded into the ansible plugin. My workaround was to specify via the raw arguments in the Vagrantfile.  Even though ansible-playbook was able to locate and read my ansible.cfg when I did a 'vagrant provision --provision-with ansible', the initial ansible-playbook launch by Vagrant contained hard coded ssh and timeout settings from the plugin.

ansible.raw_arguments = ["--timeout=30"]

**Comment by SimonWydooghe** [comment]
I can confirm this, it doesn't seem to be picking up the specified ansible.cfg file.

**Comment by gildegoma** [comment]
@ayen-tibco @SimonWydooghe Thank you for your feedbacks!

As of [Vagrant 1.9.0](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#190-november-28-2016) you can optionally specify where the `ansible.cfg` is located with the [`config_file`](https://www.vagrantup.com/docs/provisioning/ansible_common.html#config_file) provisioner option. If not specified, only an `ansible.cfg` file in the same directory as the `Vagrantfile` might be considered (in addition to user or system wide config file).

That said, the `config_file` option will not help to override some command line arguments generated  by the Ansible provisioners (e.g. the hardcoded `timeout` parameter). For these non-frequent cases, the `raw_arguments` is your friend ;-) We might improve the documentation regarding this though... All nice ideas are welcome 😻.

I'm locking this thread, but please feel free to engage discussion about new possible change requests via the Google Mailing list or with new GitHub issues.
