### ISSUE TITLE
Vagrantfile inheritance and undefine features

### ISSUE THREAD

**Issue by HariSekhon** [mitchellh/vagrant#2503]
Feature request to add Inheritance and Override features:
1. Inherit config at multiple levels to minimize Vagrantfile configuration and config duplication across large numbers of cluster nodes (having lots of different Vagrant files one per cluster is also a lot of duplication at the top layer)
2. Override and undefine options such as config.vm.provisioner :shell from a higher level where one node may differ only slightly from most of the others but you don't want to have to remove the option from base and then duplicate it in dozens or hundreds of other node defines.

Thanks

Hari

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
