### ISSUE TITLE
Ansible-Galaxy Integration

### ISSUE THREAD

**Issue by gildegoma** [mitchellh/vagrant#2718]
Sharing of Ansible Roles is now possible via https://galaxy.ansibleworks.com/ platform and a smart integration of `ansible-galaxy` CLI will be very handy.

Since it is a very new feature from AnsibleWorks, I'd like to first gather some more experience and also community feedbacks.

**Comment by gildegoma** [comment]
This will be done after #2103.

**Comment by devlucas** [comment]
Any update about that? Since #5340 seems to be untouched for a long time, I would like to pick up galaxy support to work on, please let me know if you see any problem.

**Comment by gildegoma** [comment]
Thanks @devlucas for your offer. Since galaxy support can be easily "work arounded" with the original remote `ansible` provisioner (with an own-made script, e.g. `ansible-galaxy -f ...; vagrant provision`), I'd strongly prefer to introduce this feature as part of Vagrant 1.8 and the #5340 refactoring.

@devlucas, it would be awesome if you open a pull request with `gildegoma/2103-ansible-local` as target branch. I planned to rely on the `action_hook` mechanism before the Ansible provisioners run. The idea is that this `before_provision` hook provides a good default (using `ansible-galaxy` tool), but it should be fully flexible to allow the switch to other tooling (e.g. `librarian-ansible` or to be used to execute any other pre-tasks, such as a custom Ansible installation, for instance from github source, etc). What do you think? Feel free to ping me if you want to have a live design chat session :+1:.

**Comment by gildegoma** [comment]
I plan to propose a fix for this during the week. Reviewers will be welcome as always!

**Comment by gildegoma** [comment]
Hello guys! 

I've proposed a fix for this issue (#6529) and we should be able to ship this enhancement in upcoming Vagrant 1.8 by the end of this month. For better quality assurance, it would be awesome if some of you could find a little time during this week to check it out... Many thanks in advance for your review help!
