### ISSUE TITLE
SaltStack and minion_id after changing hostname

### ISSUE THREAD

**Issue by craneworks** [mitchellh/vagrant#2776]
If SaltStack is already installed on the box and the hostname will be changed during the vagrant setup the minion_id will still stay the same.

This is more a feature request than really a bug.

**Comment by shanemhansen** [comment]
I also hit this bug in a multi-vm environment. I fixed it by editing the minion config as suggested above.

**Comment by sethvargo** [comment]
It looks like `minion_id` was added in https://github.com/mitchellh/vagrant/commit/3528af2db915c8592cc8cc7959d44f681634ace8. Thanks!
