### ISSUE TITLE
NFS export failure on Linux with space on shared folder

### ISSUE THREAD

**Issue by regilero** [mitchellh/vagrant#2799]
I saw #1471 was fixed but at leats on Linux I still had some problems for a vagrant base folder containing spaces and shared via NFS.

On the linux template quotes are added around the share name to allow for special character, but the lines obtained from the template are launched with this:

<pre>
system(%Q[sudo su root -c "echo '#{line}' >> /etc/exports"])
</pre>

So the final output is something like:

<pre>
sudo su root -c "echo '"/home/folder with space" 10.1.5.43(...stuff...)' >> /etc/exports"
</pre>

Which finally removes the double quote from the `/etc/exports` file:
<pre>
# we end up with:
/home/folder with space 10.1.5.43(...stuff...)
# instead of:
"/home/folder with space" 10.1.5.43(...stuff...)
</pre>

A simple fix, on my side (vagrant 1.3.5), was to replace this line https://github.com/mitchellh/vagrant/blob/master/templates/nfs/exports_linux.erb#L4 :
<pre>
"&lt;%= opts[:hostpath] %>" &lt;%= ip %>(&lt;%= opts[:linux__nfs_options].join(",") %>)
</pre>
With:
<pre>
\"&lt;%= opts[:hostpath] %>\" &lt;%= ip %>(&lt;%= opts[:linux__nfs_options].join(",") %>)
</pre>
( `"` ===> `\"`)

My Linux NFS server reports **wrongly** that this is unsupported, but the warning is a known bug https://bugs.launchpad.net/ubuntu/+source/nfs-utils/+bug/197499 and in fact everything works well. I did not need to replace spaces with `\040` on the guest side as the launchpad bug report may suggest. Maybe because the guest is a recent Saucy Ubuntu release, previous versions will maybe need this hack, but for saucy the mount would fail with a `gsub(' ','\\\\040')` on the client side.
<pre>
[default] Exporting NFS shared folders...
exportfs: /home/folder with space does not support NFS export
[default] Mounting NFS shared folders...
</pre>

**Comment by sethvargo** [comment]
Closing due to no response. Please open a new issue if this is still happening and include the output in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html).
