### ISSUE TITLE
docker.run args have no effect on vagrant reload --provision

### ISSUE THREAD

**Issue by mattes** [mitchellh/vagrant#3055]
Given the following example:

```ruby
  config.vm.provision "docker" do |d|
    d.run "ubuntu",
      cmd: "bash -l",
      args: "-v '/vagrant:/var/www'"
  end
```

I start the machine ``vagrant up`` and now change the ``args`` line:

```ruby
  config.vm.provision "docker" do |d|
    d.run "ubuntu",
      cmd: "bash -l",
      args: "-v '/vagrant:/var/NEW_PATH_WHATEVER'"
  end
```

I run ``vagrant reload --provision`` but the changes won't become active. 

I think the problem ist that, once the docker container has been created ([docker/client.rb#L59](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/docker/client.rb#L59)) on the initial ``vagrant up``, a following ``vagrant reload --provision`` just starts (``docker start``) the existing container ([docker/client.rb#L57](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/docker/client.rb#L57)) instead of re-creating it with ``docker run``.

**Comment by andreychernih** [comment]
Just wanted to note that the same is also actual for `ports` option. If I add some port mapping after container was already created then it does not picked up by `vagrant reload`. I guess it's docker limitation because you can only specify ports mapping in `docker run`.

**Comment by jure** [comment]
Spent a while scratching my head about this one today as well. My situation was the same as @andreychernih's, where I added `ports` to a container which previously did not have any `ports` specified, and `vagrant reload` had no effect. `docker stop` and `docker rm` followed by a `vagrant reload` worked as expected though.

I would expect `vagrant reload` to detect changes in the Vagrantfile and do the right thing, in this case, stop and remove the container, and restart it. Given the discussion here, that might be hard to do though.

**Comment by danielrhodeswarp** [comment]
A rather prickly issue this one :-/

**Comment by bkeroackdsc** [comment]
++

It would be great to get this issue fixed. Very annoying.

**Comment by jpcummins** [comment]
+1 - I was bit by this as well. Annoying.

**Comment by prepor** [comment]
+1
