### ISSUE TITLE
rsync-push and rsync-pull

### ISSUE THREAD

**Issue by p0deje** [mitchellh/vagrant#3062]
Until Vagrant 1.5 is released, I suggest to add one more feature to `vagrant rsync`. Currently, it's only possible to push local files to VM, but there is no way to pull them back. It'd be super useful for CI environments, when we need to retrieve test results and artifacts. It'd be pretty easy to implement (by changing position of `local_path remote_path` arguments).

It would also make sense to change commands to something like:

``` bash
$ vagrant rsync-push
$ vagrant rsync-pull
```

I can work on this if you think it worths.

**Comment by dmatora** [comment]
consider using http://github.com/dmatora/vagrant-unison
it does realtime bidirectional folder sync

**Comment by duro** [comment]
@dmatora I have tried your plugin in the past and found it to be a little unreliable. I see you have picked back up with development in the new year. How has it improved?

**Comment by dmatora** [comment]
it's not my plugin, i just updated it few days ago, to make it functioning and reliable :)

**Comment by create-renegr** [comment]
@dmatora thanks for updating the plugin. It is working on my win8.1 host!

@jdhiro I would have tried to use parallel, but it seems, that it is no longer available for windows.

**Comment by kylemacfarlane** [comment]
@dmatora and anyone else using Unison.

I'm finding that Unison isn't such a good solution. When used with tools like sassc and UglifyJS it starts syncing files at the start of compilation and then abandons the sync because the "source file has been modified during synchronization". Is there any way to make Unison wait until the files have finished being written?

I'm using dmatora's vagrant-unison fork.

**Comment by akostadinov** [comment]
I think important use case is to allow a number of machines to share some files while provisioning. For example one VM generates some certificates, then the rest of the machines need to pick them up somehow. This is easy with shared folders but no with rsync. Generating stuff on host might not be so trivial especially if you want to showcase things to users and don;t expect user's host machine to have all necessary tools.

**Comment by purpleidea** [comment]
On Mon, May 11, 2015 at 5:47 PM, Aleksandar Kostadinov <
notifications@github.com> wrote:

> I think important use case is to allow a number of machines to share some
> files while provisioning. For example one VM generates some certificates,
> then the rest of the machines need to pick them up somehow. This is easy
> with shared folders but no with rsync. Generating stuff on host might not
> be so trivial especially if you want to showcase things to users and don;t
> expect user's host machine to have all necessary tools.



Interesting idea, but I don't think this should be a goal, because it won't
be something that's easily replicated in prod. If you want to do this, use
config management tools to do so, instead.

**Comment by akostadinov** [comment]
@purpleidea, if I'm using another config management system, why should I use vagrant? Also reading about ansible for example I don't see any big difference - the issue remains the same. I think vagrant is mostly useful for developing, testing and demos. For production you'd have pre-generated certificates and keys. While for the former use cases you need to generate things on the fly to avoid security issues.

**Comment by purpleidea** [comment]
On Tue, May 12, 2015 at 1:56 AM, Aleksandar Kostadinov <
notifications@github.com> wrote:

> @purpleidea <https://github.com/purpleidea>, if I'm using another config
> management system, why should I use vagrant? Also reading about ansible for
> example I don't see any big difference - the issue remains the same. I
> think vagrant is mostly useful for developing, testing and demos. For
> production you'd have pre-generated certificates and keys. While for the
> former use cases you need to generate things on the fly to avoid security
> issues.



My point is that vagrant is for dev and not prod, and if you use the same
mechanism in both to distribute your files, then your dev env. will more
accurately resemble prod, and tests are more likely to accurately represent
real life.

**Comment by akostadinov** [comment]
@purpleidea, sure that might be possible **sometimes**. But you can't use your production keys and certificates in dev environment unless you want to get into trouble (assuming you even have access to the prod certificates). And I think more and more systems nowadays use some sort of certificates or keys to talk securely to each other. This use case - securely sharing data between the provisioned machines is not covered well in current vagrant when deploying non-locally.

**Comment by purpleidea** [comment]
On Tue, May 12, 2015 at 2:12 AM, Aleksandar Kostadinov <
notifications@github.com> wrote:

> But you can't use your production keys and certificates in dev environment

Use different copies of course!


> This use case - securely sharing data between the provisioned machines is
> not covered well in current vagrant when deploying non-locally.

I don't think it's supposed to be, IMO.

I think I've offered my point clearly enough. It's up to you if you want to
take these suggestions or not. I don't think it's helpful for me to discuss
this any further. Cheers!

**Comment by akostadinov** [comment]
I don't think it's supposed to be, IMO.
Why?
    I don't think it's helpful for me to discuss this any further.
Not helpful for me too unless you bring anything new to the table. Generating certificates and installing properly on all machines is often not trivial, also may depend on user preferences about number of machines, their role and certificate types. It's perfectly legitimate to allow that to happen automated within vagrant IMHO. For small projects it may not be an issue but for big projects it becomes an issue.

**Comment by rarkins** [comment]
We decided to go with unison instead of rsync, but using a manual installation instead of the plugin. I've documented the process [here](https://keylocation.sg/blog/vagrant-and-unison-without-a-plugin/) in case it helps anyone.

**Comment by nha** [comment]
@rarkins Thanks that looks useful

**Comment by rarkins** [comment]
@nha I don't have a need for that, but would guess that the simple but inefficient way is to have multiple `.prf` files and run multiple simultaneous `unison` commands. An alternative might be symlinks, as described [here](http://ubuntuforums.org/showthread.php?t=1623869)?

Also, are you sure you can't just sync your main directory and *exclude* paths within it you don't want sync'd?

**Comment by giovdk21** [comment]
+1 for two-way sync with rsync or at least an handy and reliable rsync-pull, but the former would be ideal.

**Comment by russjaguar** [comment]
We were able to get @rarkins solution working. I see there might be a way to automate the management a bit by having profiles name after the boxes... maybe... Would be nice if the plugin were to get maintained as the NFS module is hit-and-miss within the 20 or so boxes we end up working with. Can be _very_ annoying to make changes, not see them loading and thing you're doing something wrong only for them to suddenly load 1-2 minutes later.

**Comment by Perni1984** [comment]
@rarkins: Thanks, you saved my life. Unison is working great for bidirectional synching between windows and vms. Now I can develop and run symfony2 with full speed inside my vms on my windows host. For me, this works even better than vagrant-winnfsd.

**Comment by flynfish** [comment]
@dmatora:

1. does running `vagrant plugin install vagrant-unison` install your forked version? If not, how do we get yours installed?
2. Is there a way to change the ssh username to something besides 'vagrant' ?

**Comment by dmatora** [comment]
@flynfish no, it does't simple way to install it would be to download https://www.dropbox.com/s/1yu1s7pr3qlr8ag/vagrant-unison-0.0.15.gem and do vagrant plugin install vagrant-unison-0.0.15.gem
but it's currently outdated.

I'm sorry to say that guys, but i moved to using nfs_guest, i tried to use it before unison, and nfs silently failed for me. But latter i discovered than on OSX you need to have localhost in your /etc/hosts file in order for nfs to work and that saved it. With nfs_guest i don't have fs_events, but performance is close to filesystem, and i don't have and sync failures, so i don't fix those anymore. Yet CPU load is so much smaller.

**Comment by mikestaub** [comment]
I have been using the vagrant-unison2 plugin with success. I was also using NFS but ran into issues with windows and npm.

**Comment by seantcanavan** [comment]
I've seen a couple good suggestions here so far. I'm completely out of options because network-based shares don't work over VPN but our VPN client is not up for discussion which leaves openconnect out of discussion.

Rsync appears to be the only option as appallingly slow disk read and write speeds have ground our build and test processes down to a halt on the standard sync share.

But the issue with Rsync is that it only supports one way sync and of course requires cygwin to be installed as well. Bundling a two-way rsync into Vagrant would be a huge huge huge win.

It looks like there is hope though. I'm excited that this has been tagged as milestone 1.9.0 but 1.8.7 is only 33% complete as of this moment in time. An interim solution will absolutely have to be implemented.

**Comment by purpleidea** [comment]
Check out https://github.com/dustymabe/vagrant-sshfs/ /cc @dustymabe

**Comment by dustymabe** [comment]
@seantcanavan check out vagrant-sshfs - i've actually been thinking about proposing it for inclusion in vagrant itself. for now it lives pretty well on its own as a plugin.

**Comment by seantcanavan** [comment]
Thanks for the ideas @purpleidea and @dustymabe. Unfortunately the ruby gem bundler uses a custom user agent string which the corporate firewall immediately shoots down so I was hoping for a baked-in solution since it makes plugin installation impossible.

Looks like I gotta the network guys on the phone...

Cheers.

**Comment by dustymabe** [comment]
@seantcanavan can you download the gem and install them directly (i.e. install from file instead of from rubygems.org) I think for vagrant-sshfs you need win32-process and vagrant-sshfs. if you get those two gems and then install directly from file (i.e. `vagrant plugin install ./win32-process-X-X.gem && vagrant plugin install ./vagrant-sshfs-X-X.gem`) then it should work

**Comment by seantcanavan** [comment]
@dustymabe Finally got the gem files built for win32-process-0.8.3 and vagrant-sshfs-1.2.0. I put them in my project's ./gems/ directory where the vagrant file is located in ./. I executed `vagrant plugin install ./gems/win32-process-0.8.3.gem` and received the error `/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in all=': undefined method group_by' for nil:NilClass (NoMethodError)`

**Comment by dustymabe** [comment]
@seantcanavan wow - so you finally got something working?

**Comment by seantcanavan** [comment]
@dustymabe Yes!! I hope I'm not derailing and someone else will find this info useful. My last question is this: I've pulled in vagrant-sshfs from outside our firewall once and installed it locally and it works great. Now I need to package it in a gem file to add it to our source so people inside the firewall can reliably retrieve it. I found the plugin installed at `/home/username/.vagrant.d/gems/gems/vagrant-sshfs-1.2.0` but when I run `bundle install` inside the install dir I get 

[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice coming from different sources.
You specified that vagrant-sshfs (>= 0) should come from source at `.` and source at `.`
. Bundler cannot continue.

 #  from /home/lowercase/.vagrant.d/gems/gems/vagrant-sshfs-1.2.0/Gemfile:13
 #  -------------------------------------------
 #  group :plugins do
 >    gem "vagrant-sshfs" , path: "."
 #    # Add vagrant-libvirt plugin here, otherwise you won't be able to
 #  -------------------------------------------

Do you have a quick and easy way I can package your plugin to install locally via command line for future use?

**Comment by dustymabe** [comment]
@seantcanavan commenting out this line should work to fix that error: https://github.com/dustymabe/vagrant-sshfs/blob/master/Gemfile#L13

the other thing is - why not just download the gem from my releases page and use that? 
https://github.com/dustymabe/vagrant-sshfs/releases/download/v1.2.0/vagrant-sshfs-1.2.0.gem

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!

**Comment by mcandre** [comment]
Crap. I spent all this time and effort setting up Vagrant boxes in the hope of developing a suite of buildbots for cross-compiling systems language applications for different operating system kernels. And then I find out that rsync-based Vagrant synced folders--and there is no other option besides rsync-based Vagrant synced folders for the vast majority of guest operating systems--does not support bidirectional syncing. So there's little point in `vagrant ssh -c 'clang -o /vagrant/hello hello.c'` if the `hello` binary won't even be transferred to the host. :(

I have a few suggestions for implementing bidirectional rsync more quickly:

* https://github.com/deajan/osync , which claims to just depend on bash and rsync, and therefore could be easily installed automatically by Vagrant into rsync-enabled guests.
* Continue using `/vagrant` as a one-way source host->guest folder, and introduce a second folder like `/vagrant-output` that one-way syncs to the host as `<host-cwd>/vagrant-output`. When Vagrant rsyncs the `/vagrant` source folder, it should exclude `vagrant-output`.

**Comment by dustymabe** [comment]
@mcandre would vagrant-sshfs work for you?

**Comment by cromulus** [comment]
sshfs looks like it has far more dependencies, particularly FUSE, than osync.

**Comment by daks** [comment]
@mcandre I use [vagrant-scp](https://github.com/invernizzi/vagrant-scp) to retrieve artifacts from Vagrant machines.

**Comment by mcandre** [comment]
@dustymabe vagrant-sshfs is interesting. Unfortunately, it is not clear that this plugin supports bidirectional sync in a single Vagrant box configuration--the documentation seems to indicate that either guest->host syncing can be configured, xor host->guest, but not both at once.

Also, this plugin does not support Windows, which for my purposes (cross-compilation) is a no-go.

**Comment by dustymabe** [comment]
> @dustymabe vagrant-sshfs is interesting. Unfortunately, it is not clear that this plugin supports bidirectional sync in a single Vagrant box configuration--the documentation seems to indicate that either guest->host syncing can be configured, xor host->guest, but not both at once.

SSHFS is essentially a network filesystem. You can access files from the host or from inside the guest at the same time and they transparently update all locations. A longer description [here](https://github.com/dustymabe/vagrant-sshfs/issues/90#issuecomment-362859311).  

> Also, this plugin does not support Windows, which for my purposes (cross-compilation) is a no-go.

It does support windows, just not for reverse mounts (sharing guest files to a host folder), which I don't think you actually need. How about giving it a try so you'll know for sure 😃.
