### ISSUE TITLE
Allow retrying bad password for SMB mount

### ISSUE THREAD

**Issue by therobyouknow** [mitchellh/vagrant#3264]
during the `vagrant up --provider hyperv` setup, when entering SMB password
- doesn't immediately feedback wrong password entered
- doesn't allow for retry if wrong password entered
- when it does feedback, it displays the incorrect password in the terminal - I suggest that this is a security issue as it would help the correct password to be guessed an unauthorised person (this is after all the Windows login to the machine, which can be a Microsoft online account)

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
