### ISSUE TITLE
Support pointing to a manifest folder for puppet 3.5

### ISSUE THREAD

**Issue by pderaaij** [mitchellh/vagrant#3402]
In the 3.5 release of puppet the method to auto import multiple node definitions has been altered. We used to do this via the import statement, but that statement has been marked deprecated since this release. 

The release notes gives us an alternative, but this doesn't seem to be compatible with the options of vagrant. In any combination I configure the vagrantfile I get an error stating the manifest file can't be found. 

Release notes puppet:
http://docs.puppetlabs.com/puppet/latest/reference/release_notes.html#auto-import-use-a-directory-as-main-manifest

**Comment by sethvargo** [comment]
Hi @pderaaij 

I just merged support or Puppet 4 (I know, a bit late on the 3.5 here :smile:), which adds support for this as well as environments. Please let me know if you experience any issues, and I am sorry this issue sat for so long. Thanks! :smile:

**Comment by pderaaij** [comment]
Great work @sethvargo, thanks for the effort!
