### ISSUE TITLE
Can't use alphanumeric patterns for box names in ansible.groups

### ISSUE THREAD

**Issue by dflock** [mitchellh/vagrant#3539]
If I create an ansible inventory file manually, I can say this:

```ini
[zookeepers]
box[1-3]
```

if I do this inside the Vagrantfile, I can't - I have to spell it out:

```ruby
ansible.groups = {
  'zookeepers' => ['box1', 'box2', 'box3'],
}
```
which creates this output in the generated inventory file:

```ini
[zookeepers]
box1
box2
box3
```

If I change the Vagrantfile like so:

```ruby
ansible.groups = {
  'zookeepers' => ['box[1-3]'],
}
```

I just get an empty section in the generated inventory file:

```ini
[zookeepers]

```

**Comment by kamigerami** [comment]
@gildegoma does it make sense to look for pattern expressions similar to what python uses? 

the subscript patterns that are in the ansible (docs)[http://docs.ansible.com/ansible/intro_patterns.html] for example.

from the ansible code: 
```
                \[(?:                   # A [subscript] expression comprising:
                    (-?[0-9]+)|         # A single positive or negative number
                    ([0-9]+)([:-])      # Or an x:y or x: range.
                    ([0-9]*)
                )\]
                
```

and do something similar for ruby, iterating over it matching it against inventory_machines.includes?
before adding it to the inventory file?

I can do the PR however suggestions and thoughts are welcome on how to approach this :)

**Comment by gildegoma** [comment]
@kamigerami thanks for the offer :)
As already mentioned above, a PR for this improvement would be very welcome indeed!

Please note that your reference is about some different things (e.g. the handling of the `--limit` argument). The alphanumeric patterns to be supported in our case are well described at http://docs.ansible.com/ansible/intro_inventory.html#hosts-and-groups, and here is the relevant documentation excerpt:

> If you have a lot of hosts following similar patterns you can do this rather than listing each hostname:
```
[webservers]
www[01:50].example.com
```
> For numeric patterns, leading zeros can be included or removed, as desired. Ranges are inclusive. You can also define alphabetic ranges:
```
[databases]
db-[a:f].example.com
db-[a:f].example.org
```

So, the **safe approach** could be something like:

 1. detect all the `group` elements that include ":" range patterns
 1. for each pattern found: expand the related host names, exactly like Ansible will do (see also `ansible -i <inventory_name> --list-hosts <group_name>`). 
 1. write these groups into the inventory file if and only if all these host names exist in the `Vagrantfile` statements and are in [`@inventory_machines`](https://github.com/mitchellh/vagrant/blob/5659c3f2a0637fa8ad5c4fa20c4204efdafe570f/plugins/provisioners/ansible/provisioner/base.rb#L76-L78) list. Otherwise abort with an error message.

Even if I initially preferred to take the most robust way, I'd like to consider a (KISS) **weaker approach**, where the detected patterns would be roughly added to the inventory without any `Vagrantfile` sanity check... Simply letting `ansible-playbook` fail when invalid hosts are referred. This is an advanced usage, and people using it should be aware of what they are doing...

More thoughts about the best way to fix it? weak vs safe? other?

**Comment by kamigerami** [comment]
Thank you for your valuable input. The document you referred to is the one with the correct patterns indeed! 

Yes the **weaker** approach was my initial fix for it locally, (e.g. if something matched the following regex, add it to the inventory file without any other sanity checks (host names in the Vagrantfile etc.) 
:

``` 
/(\[[a-z]:[a-z]\]|\[[0-9]+?:[0-9]+?\])/  

matches 

www[01:50].example.com
db-[a:f].example.com
www[100:1000].example.com

not : db-[aaaa:zzz].example.org <-- not this 

```

I agree that it is an advanced use case (safe approach) and most likely some more code involved (expanding every pattern matched) etc.. it could also lead to some frustration for people not specifying an exact range equal to the host names that exist in inventory_machines list / Vagrantfile (error messages etc) .

Doing the weaker approach might lead to some issues when people enumerate all hosts within a group in a template file but actually only managing x number of hosts (less hosts than specified in the : range) 
which might not be that big of a deal for some.
```
#let's say that this is in a Vagrantfile 

groups = {
    "lb" => "lb-01.example.com",
    "webapp" => "webapp-0[0:500].example.com"

config.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/site.yml"
    ansible.groups = groups
end
```

and someone were to have something like this in their template file
```  
{% for host in groups['webapp'] %}
        server "{{ host }}";
        {% endfor %}

```
It would look correct inside the inventory file 

```
[lb]
lb-01.example.com

[webapp]
webapp-0[0:500].example.com
```
However the template file would have over 500 entries.


I think both are valid ways of doing it for sure with different pros / cons

**Comment by gildegoma** [comment]
> it could also lead to some frustration for people not specifying an exact range equal to the host names that exist in inventory_machines list / Vagrantfile (error messages etc).

Of course, but I think that the Ansible error messages will already help (here an example with 3 machines, but a wrong `machine[1:5]` pattern:

```
PLAY [Development] ************************************************************ 

TASK: [ping] ****************************************************************** 
fatal: [machine5] => SSH Error: ssh: Could not resolve hostname machine5: nodename nor servname provided, or not known
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
fatal: [machine4] => SSH Error: ssh: Could not resolve hostname machine4: nodename nor servname provided, or not known
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.
ok: [machine1] => {"changed": false, "ping": "pong"}
ok: [machine2] => {"changed": false, "ping": "pong"}
ok: [machine3] => {"changed": false, "ping": "pong"}

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/gildegoma/ping.retry

machine1                   : ok=2    changed=0    unreachable=0    failed=0   
machine2                   : ok=2    changed=0    unreachable=0    failed=0   
machine3                   : ok=2    changed=0    unreachable=0    failed=0   
machine4                   : ok=0    changed=0    unreachable=1    failed=0   
machine5                   : ok=0    changed=0    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I'd propose you to start to implement the weak variant, and we can iterate to improve its robustness. Another idea: Show a notice when any host pattern is detected in the `groups` option to warn that Vagrant doesn't fully check the validity of these parameters (_expect that you know what you're doing ;-)_)

**Comment by kamigerami** [comment]
Consider it done ;) 

I'll post a draft here later on and we can take it from there ;) Thnx!

**Comment by gildegoma** [comment]
@kamigerami :heart: :heart: :heart: you're awesome!

**Comment by kamigerami** [comment]
@gildegoma: a first draft! I updated the website docs as well. Feel free to edit the language as you see fit and come back with suggestions and thoughts on the code. Thanks !! :raised_hands:

**Comment by kamigerami** [comment]
needs some more testing! hold on!

**Comment by gildegoma** [comment]
@kamigerami this looks very good at first glance. Could you please rebase against master (due to recent merge of #6627 and open a PR. Hopefully, I can find some time tomorrow to take care of testing and review...

**Comment by gildegoma** [comment]
@kamigerami thanks for the PR #6639. I'll try to review it quickly :)
