### ISSUE TITLE
Box data left in `~/.vagrant.d/boxes` after removal

### ISSUE THREAD

**Issue by berendt** [mitchellh/vagrant#3570]
I removed two boxes (```alpine-2.7.5-amd64``` and ```ubuntu-14.04-amd64```), but after that there is still data left in ```.vagrant.d/boxes```. Should be removed, too.

```
% vagrant box list
berendt/devstack-ubuntu-14.04-amd64 (virtualbox, 0.1.5)
```

```
% ll .vagrant.d/boxes 
total 12
drwxr-xr-x 3 berendt users 4096 Mar 31 20:11 berendt-VAGRANTSLASH-alpine-2.7.5-amd64/
drwxr-xr-x 3 berendt users 4096 Apr 29 10:04 berendt-VAGRANTSLASH-devstack-ubuntu-14.04-amd64/
drwxr-xr-x 3 berendt users 4096 Apr  6 18:56 berendt-VAGRANTSLASH-ubuntu-14.04-amd64/
```

**Comment by ievgenp** [comment]
Hello, guys. I've been wanting to try out my skills in opensource project and have been looking for a simple issue to start with. Finally, I've found this one and it does look simple to me. And here is when I need an opinion of an experienced maintainer.

After I've played around for a while with functionality of boxes removement, I spotted that there are one potential place where lacking check can be placed. So here's my question. Would it be correct to check if there are other versions and providers of current box present on the machine, and if not — use `FileUtils` to remove whole directory of the box right after `box.destroy!` is called at `lib/vagrant/action/builtin/box_remove.rb:110`? Or should I also somehow check if there are multiple instances of vagrant running, as it was mentioned by @mitchellh ?

TIA.
