### ISSUE TITLE
There should be a way to specify a global shared folder sync type default

### ISSUE THREAD

**Issue by purpleidea** [mitchellh/vagrant#3631]
It would be particularly useful to specify in your Vagrantfile the type of shared folder sync you'd like to use. For example, vagrant-libvirt recommends you set it by doing:

        config.vm.synced_folder './', '/vagrant', type: 'rsync'

to override whatever the default is. This seems to work, however there are other synced folders which get created by providers, and it's:

1) impossible to enumerate them all
2) not stable to know where they will try and mount
3) specifying their type actually doesn't seem to work

example:

        config.vm.synced_folder './puppet/modules', '/tmp/vagrant-puppet-2/modules', type: 'rsync'
        config.vm.synced_folder './puppet/manifests', '/tmp/vagrant-puppet-2/manifests', type: 'rsync'

these still happens over NFS!

**Comment by mkuzmin** [comment]
Fixed in 1.7.3

**Comment by akaSStalkALEX** [comment]
I don't understand was this approved or not? I have this in my config "config.vm.allowed_synced_folder_types = :virtualbox", but "vagrant up" keeps asking rsync anyway.Please, explain someone.

**Comment by OrangeDog** [comment]
@mkuzmin so how do you specify the sync folder type globally?
