### ISSUE TITLE
Halting/destroying the Docker host should register Docker containers as halted too

### ISSUE THREAD

**Issue by FooBarWidget** [mitchellh/vagrant#3801]
1. Create a few Docker containers with `vagrant up --provider docker`, with `force_host_vm = true`.
2. Halt or destroy the Docker host VM.
3. Run `vagrant global-status`

Vagrant thinks the Docker containers are still running, even though they're not.

**Comment by mitchellh** [comment]
`global-status` is a cache, so we're not going to solve this in this way. We'll make the messaging clearer.
