### ISSUE TITLE
Vagrant Halt force shutdown behavior

### ISSUE THREAD

**Issue by abraithwaite** [mitchellh/vagrant#3895]
When running `vagrant halt` on vagrant 1.5.4, if the guest cannot be shutdown cleanly, a forced halt is run immediately without user intervention.

Personally, I would expect that if the guest cannot be shutdown cleanly then vagrant would simply exit non-zero with a descriptive error.

It would make more sense to me to have a non-zero exit status perhaps suggesting that the user runs `vagrant halt --force` if the guest is truly in an unrecoverable state.

Does this ring with anybody else?

**Comment by rhchristian** [comment]
>Its NOT a solution.

~~~~just a curious thing 

i had this problem when i was running a vagrant machine and i closed the prompt(normal mode), when i opened the prompt again, i switched the prompt to run as administrator so get this error, so i closed the admin prompt(run as administrator), and open another one in a normal mode, i tested the "vagrant ssh" and this problem disappeared.

**Comment by maxdeivys** [comment]
VBoxManage startvm [vm_id|vm_name] --type emergencystop

**Comment by af7** [comment]
Hello, I get the same error, when I am in **"Admin"** mode in the Console:  "VBoxManage.exe: error: Failed to assign the machine to the session"

But I do NOT get this error, when I am in **"Normal"** mode.

But then, shouldn't I be in "Admin" mode when I run `vagrant provision`? 

In general, can this be fixed to work when in "Admin" mode?

**Comment by terbooter** [comment]
Same error in Admin mode
```
C:\ubuntu>vagrant reload
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '14.04'. The latest is version '20150530.0.2'. Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "26aa704c-366d-4d7c-a6f0-14ae1df6cab6", "--natpf1", "delete", "ssh"]

Stderr: VBoxManage.exe: error: Failed to assign the machine to the session (E_FAIL)
VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component Machine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 471 of file VBoxManageModifyVM.cpp
```

It works perfect, but after PC reboot I cant up my vagrant box

**Comment by seperman** [comment]
I get this error on Win 7, Vagrant 1.6.5 when I switch between running in `admin` mode vs. `normal` mode.

**Comment by davidshq** [comment]
I also get this error, when running in normal mode, admin mode seems to fix.

If writing a fix for this isn't possible/too difficult, suggest friendly error messaging, e.g. "Please reset your console in administrative mode if running on Windows."

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
