### ISSUE TITLE
Check a path to Vagrantfile for running box

### ISSUE THREAD

**Issue by timurb** [mitchellh/vagrant#3921]
When you copy directory with `Vagrantfile` from which you have started the machine all new directories still refer to the same machine because of the data in `.vagrant`.

It would be nice if Vagrant produced a warning etc in that case.

Steps to reproduce:

``` bash
mkdir vagrant-test
cd vagrant-test
vagrant init
vagrant up
vagrant status
# Current machine states:
# default                   running
cd ..
cp -ar vagrant-test vagrant-test2
cd vagrant-test2
vagrant status                                                              
#Current machine states:
# default                   running
```

**Comment by Ferdy89** [comment]
I know this is an old issue but I think the use case is still valid. I'm fairly new to vagrant but I could work on a PR for this if it's still useful

**Comment by chrisroberts** [comment]
@Ferdy89 If this is something you'd like to tackle, that would be great. Please just give a ping here with a :+1: or :-1:. Thanks!

**Comment by Ferdy89** [comment]
@chrisroberts I'm going to try it! 👍
