### ISSUE TITLE
Ability for rsync without sudo

### ISSUE THREAD

**Issue by treyhyde** [mitchellh/vagrant#3966]
In reference to #3810, if you skip the chown then you end up with files owned by root.

Rsync is defined as   

```ruby
def self.rsync_command(machine)
  "sudo rsync"
end
```

in the various guest plugins.

If you are disabling the chown, then you really probably want to rsync as "not root", probably "vagrant" (config.ssh.username).   For me, that does exactly the right thing.  "find" is expensive and generally wrong without a lot of option manipulation, and rsync__chown: false gives root which is very wrong in my case.

**Comment by mitchellh** [comment]
Done
