### ISSUE TITLE
No graceful fail on vagrant box add

### ISSUE THREAD

**Issue by kfsone** [mitchellh/vagrant#3977]
I'm trying to add a wrapper to a vagrant project, and I want to start by making sure the appropriate box is added from a URL.

If no provider is specified, it re-downloads the box, even though there is a match for the current provider, unless you explicitly specify --provider.

When you give a full command line, e.g. vagrant box add -c --provider virtualbox trusty https://... an error is generated.

Could we get a reciprocal to '--force' which is '--quiet' to do nothing if the box is already registered?

**Comment by sethvargo** [comment]
Hi @kfsone 

Revisiting this in triage. At some point, we added the ability to specify the `box_url` in the Vagrantfile:

```ruby
config.vm.box_url = "my-custom-box-url`
```

This can be specified in a provider-specific configuration, and Vagrant will automatically download that box during `vagrant up`.

We also added a `--force` flag in https://github.com/mitchellh/vagrant/commit/96e92167d968e31b1ef1496c0bf2f7375e3d54d7. Thanks!
