### ISSUE TITLE
Add command to list winrm connection info for windows guests

### ISSUE THREAD

**Issue by keiths-osc** [mitchellh/vagrant#4016]
Vagrant provides the `ssh-config` command to list the connection information needed to connect to a VM with ssh.  It would be nice if there were a similar command that would list the connection information for winrm (and possibly also rdp) so we can let vagrant just pick a free host port and then have the ability to look up what it picked later.

**Comment by sethvargo** [comment]
Hi @keiths-osc 

Thank you for opening an issue. There doesn't seem to be a common format for listing WinRM configuration (unlike SSH config).

Vagrant 1.8.1 added a new command `vagrant port`, which you can use to detect which port was chosen if Vagrant auto-detected a port. That should solve your particular use case. To view the RDP connection file, Vagrant creates a tempfile with the RDP settings. It could log that filepath before opening the connection, allowing further customization. We would gladly review a Pull Request for that. Thanks! 😄
