### ISSUE TITLE
Allow vagrant to execute scripts on host

### ISSUE THREAD

**Issue by snowch** [mitchellh/vagrant#4040]
Some more complex vagrant environments require scripts to automate the workflow of vagrant for users.  Usually, these scripts will be created with shell and batch files.  An example bat file [here](https://github.com/snowch/stratos-vagrant-box/blob/1f613179bd1aa39b1e5befaac25bde69f834afea/new_statos_and_openstack_docker_with_desktop.bat) and example shell script [here](https://github.com/snowch/stratos-vagrant-box/blob/1f613179bd1aa39b1e5befaac25bde69f834afea/new_statos_and_openstack_docker_with_desktop.sh)

It would be great if I vagrant box providers could write scripts in ruby and use the vagrant's ruby environment to run the script.  For example;

```vagrant script setup_environment_with_desktop.rb```

or

```vagrant script setup_environment_without_desktop.rb```

Using ruby will allow vagrant box providers to use the same script on all hosts operating systems.

The script would not be part of vagrant's life-cycle.  It would purely be a mechanism for easily executing simple ruby scripts.

**Comment by sethvargo** [comment]
Hi all,

You can use Vagrant's embedded Ruby which lives at `/opt/vagrant/embedded/bin/ruby` to run scripts. For bash, bat, and other shell provisioners, unfortunately the system will just need to make that environment available. 

While we could expose this as a command, I don't think we want to encourage users to rely on Vagrant's internal language over time. While it's true that Vagrant is written in Ruby and packages a Ruby environment, I don't think we want to tie ourselves to that promise at this time. Thanks! 😄
