### ISSUE TITLE
If the box doesn't forward an SSH port, vagrant ssh will attempt to go to localhost:22

### ISSUE THREAD

**Issue by brettporter** [mitchellh/vagrant#4070]
Using Vagrant 1.6.3 and a Windows 2008 R2 box built with Packer, I was in a situation where the box had SSH installed, but did not forward the port (see https://github.com/joefitzgerald/packer-windows/pull/76 for more details).

What resulted was that `vagrant ssh` tried to connect to localhost:22, and since I have SSH enabled on my machine, I got a password prompt to login to the host instead of the vagrant box. This caused some confusion until I figured out what was going on.

It'd be good if vagrant could fail fast with an error if the box doesn't forward an SSH port, instead of trying localhost:22.

**Comment by sethvargo** [comment]
I just tried this on master and got the following:

```
    default: Guest communication could not be established! This is usually because
    default: SSH is not running, the authentication information was changed,
    default: or some other networking issue. Vagrant will force halt, if
    default: capable.
```

so I am going to close this as fixed. If this issue persists with Vagrant 1.7.3+, please open a new issue and include the complete Vagrantfile as well as the output in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html). Thanks! :smile:
