### ISSUE TITLE
Global status output / machine readable

### ISSUE THREAD

**Issue by grega** [mitchellh/vagrant#4097]
Adding `--machine-readable` to `vagrant global-status` returns nothing (Vagrant 1.6.2).

Would be really handy to have an easy-to-parse output from this command :)

**Comment by aronatkins** [comment]
+1

From http://docs.vagrantup.com/v2/cli/machine-readable.html:
> Every Vagrant command accepts a `--machine-readable` flag which enables machine readable output mode. In this mode, the output to the terminal is replaced with machine-friendly output.

The documentation is not correct & misleading in the presence of this issue.

**Comment by f3rrix** [comment]
+1 
Automating code needs to know the ID of running vagrants so it can pass the ID to other commands.  And the way to do that is with global-status, and it's not --machine-readable!  (facepalm.jpg)

**Comment by amfarrell** [comment]
+1 It also makes it easier to write tutorials for people learning vagrant because you can more easily write a test that the user has done the right thing.

**Comment by tuminoid** [comment]
:+1:

Actually surprised to see docs and reality mismatch :)

**Comment by tuminoid** [comment]
In v1.8.1 there is output for `--machine-readable`, but output looks kind of horrible. In #6237 there is comment about upcoming work to support JSON, so I guess with this output this issue too can be closed.

```
1452253445,,ui,info,id
1452253445,,ui,info,name
1452253445,,ui,info,provider
1452253445,,ui,info,state
1452253445,,ui,info,directory
1452253445,,ui,info,
1452253445,,ui,info,------------------------------------------------------------------------
1452253445,,ui,info,e9bdd8e
1452253445,,ui,info,kisakone
1452253445,,ui,info,parallels
1452253445,,ui,info,running
1452253445,,ui,info,/Users/tumi/git/mine/kisakone-dev
1452253445,,ui,info,
1452253445,,ui,info,2af2ab7
1452253445,,ui,info,sfldev
1452253445,,ui,info,parallels
1452253445,,ui,info,running
1452253445,,ui,info,/Users/tumi/git/sfl/sfl-dev
1452253445,,ui,info,
1452253445,,ui,info, \nThe above shows information about all known Vagrant environments\non this machine. This data is cached and may not be completely\nup-to-date. To interact with any of the machines%!(VAGRANT_COMMA) you can go to\nthat directory and run Vagrant%!(VAGRANT_COMMA) or you can use the ID directly\nwith Vagrant commands from any directory. For example:\n"vagrant destroy 1a2b3c4d"
```
