### ISSUE TITLE
Shell hangs when multiple vms running with SMB shared folders

### ISSUE THREAD

**Issue by photchkiss** [mitchellh/vagrant#4145]
Hi, 

I have been looking everywhere for a solution on this. I am in the process of trying to upgrade our vagrant environments to use SMB shares instead of VirtualBox default shares. I am running version 1.6.3 of vagrant and version 3 of Windows Powershell. The vagrant boxes are CentOS 6. The vagrant boxes get up and running just fine after running "vagrant up", but the problem presents itself when trying to navigate to the sync'd folder on one of the vagrant boxes. I have three vagrant boxes running simultaneously. If I run a single box at a time, changing directory to the shared folder seems to work just fine. It even appears to work fine with two vagrant boxes running at once. But once the 3rd one comes up, the command "cd /var/www/html" (my shared destination on the vagrant box) just hangs the shell. The terminal quits responding altogether. I don't know if anybody else has run into similar issues, but I'm at a bit of a loss here. 

Please let me know if I can provide additional information. 

Thanks!

Phil

**Comment by mitchellh** [comment]
Hm, I don't know enough detail about SMB to track this down. Do you know if SMB allows simultaneous mounts to the same directory? Or, if there is a flag to disable that.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the associated issue template. Thank you! 😄
