### ISSUE TITLE
Support directory destination in file provisioners

### ISSUE THREAD

**Issue by techtonik** [mitchellh/vagrant#4147]
This does't work in 1.6.3:

    conf.vm.provision :file, source: "~/.gitignore", destination:"."

Gives:

    lib/net/scp.rb:392:in `await_response_state': scp: ./.: Is a directory (RuntimeError)

**Comment by sethvargo** [comment]
Hi @techtonik 

Thank you for opening an issue. Upon further investigation (and testing), this appears to be a bug in the net-scp library that Ruby uses (http://net-ssh.github.io/scp/v1/api/classes/Net/SCP.html#M000009). The `upload!` command does not accept a remote directory as a target when the uploaded item is a file. This is not just try for things like `.` and `~`, but also any directory you specify:

```ruby
config.vm.provision :file, source: "~/.gitignore", destination: "/"
```

will also fail. I tried a few different approaches, but unfortunately there is no intelligent way to detect if the destination is a directory on the target, especially not in a cross-platform way.

**Comment by techtonik** [comment]
@sethvargo is there an upstream bug to track when it will be fixed? Unfortunately, I am not skilled in Ruby to report it myself.

**Comment by sethvargo** [comment]
@techtonik I didn't see an upstream bug report, but the net-scp project is on GitHub.
