### ISSUE TITLE
salt minion_config not copied windows box

### ISSUE THREAD

**Issue by belawaeckerlig** [mitchellh/vagrant#4152]
Hi,

when using salt as provisioner, the config file specified in the vagrantfile won't be copied to C:\salt\conf\minion.
I think the config file will be copied to C:\tmp and then copied to C:\salt\conf\minion but when installing salt, the config file will be overwritten.

I saw there is a similar bug https://github.com/mitchellh/vagrant/issues/3176 but this behaviour still occures (maybe only on windows hosts)

System information:
Host: Windows 7 x64
Vagrant 1.6.3
Box: Windows Server 2008 R2 x64

**Comment by obestwalter** [comment]
Is there any progress on that? 

This bug together with a handful of others in both projects, mean that salt + vagrant on windows is broken for about a year now. I would really like to help to get this sorted and I am trying my best on the salt side as I know my way around in the python ecosystem, but hardly in the Ruby world (yet).

**Comment by obestwalter** [comment]
I just checked on the other end and this might be fixed since the [2015.5.0 release](http://docs.saltstack.com/en/latest/topics/releases/2015.5.0.html#new-windows-installer).

Is the salt provisioner installing salt via the official windows installer?

**Comment by obestwalter** [comment]
@mitchellh I just tried with vagrant develop version and a fresh w2k8 Server R2 box. The ancient salt version 2014.1.10 is installed. How can I make sure it uses the latest Windows installer?

**Comment by sethvargo** [comment]
Fixed in https://github.com/mitchellh/vagrant/pull/5437.
