### ISSUE TITLE
Docker shell/provisioning without SSH

### ISSUE THREAD

**Issue by rasschaert** [mitchellh/vagrant#4179]
Currently, Vagrant can only provision or shell into a Docker container when it has an SSH daemon running.

Last month Docker's Jérôme Petazzoni wrote a post on the Docker blog titled ["Why you don't need to run SSHD in your Docker containers"](http://blog.docker.com/2014/06/why-you-dont-need-to-run-sshd-in-docker/). In it, he introduces a small tool called [nsenter](https://github.com/jpetazzo/nsenter), which allows you to enter the namespace of a Docker container and run a program, such as a bash shell.

In the comments, Phusion's Hongi Lai, the creator of baseimage-docker, responds to the post:
> Now, you are advocating nsenter. I am seriously considering this option. There is currently an ongoing discussion on the baseimage-docker bug tracker about replacing SSH with nsenter: https://github.com/phusion/baseimage-docker/issues/102

Baseimage-docker is one of the more popular images to use with Vagrant, and Phusion were some of the most vocal advocates in favor of running SSHd inside docker containers.

Meanwhile, upstream, [Docker is committed to creating a native mechanism](https://github.com/dotcloud/docker/issues/1228) to execute new processes in existing containers. It was slated for the 1.0 release but has since been delayed. 

It'd be nice if Vagrant would allow for other mechanisms such as nsenter to provision or shell into containers.

**Comment by SeMeKh** [comment]
`docker exec` is now a part of docker itself. Do you think it's a good idea to transparently use `docker exec` instead of ssh-ing into the container? It provides the same interface as SSH, and it shouldn't result in any incompatibility.

**Comment by thomaszbz** [comment]
SSH is just overhead here if you can just use ``docker exec`` which is provided by docker. Vagrant should be capable to use both scenarios.

**Comment by thatguystone** [comment]
Was this actually addressed in #7737?

**Comment by bogdando** [comment]
No, it seems not possible to use the docker-exec as a replacemant to the ```vm.provision :shell```

**Comment by jgillich** [comment]
This should be reopened @sethvargo

**Comment by chrisroberts** [comment]
@jgillich Hi! Closed issues are not tracked. If you are still having a problem, please open a new issue. Thanks!
