### ISSUE TITLE
"No host IP was given to the Vagrant core NFS helper" - even after attempting to disable NFS

### ISSUE THREAD

**Issue by maxlinc** [mitchellh/vagrant#4192]
We've had several users of vagrant-rackspace report that they are receiving the error:
> No host IP was given to the Vagrant core NFS helper. This is an internal error that should be reported as a bug.

See https://github.com/mitchellh/vagrant-rackspace/issues/113 and https://github.com/mitchellh/vagrant-rackspace/issues/112.

I investigated and tried to find a workaround without luck. I tried having them explicitly change the /vagrant share to use rsync and disable nfs, but the same would also need to be done with all other shares (e.g. for chef_solo). Is there a way to globally disable NFS or set RSync as the default synced_folder provider? That should at least give us a workaround.

A few notes:
- The message is "No host IP" rather than "No guest IP". From what I can tell, this means vagrant is having a problem determining the user's IP address, not the IP address of the Rackspace server.
- I noticed NFS and RSync have the same priority (5). This has made it hard for me to reproduce - RSync is selected on my machine but NFS is selected on others. My machine supports NFS - I was able to reproduce the issue by patching Vagrant to give NFS a higher priority than RSync.

Please let us know how we can disable NFS so it isn't blocking RSync, and if there's anything we need to do to have full NFS support in vagrant-rackspace.

**Comment by mitchellh** [comment]
It isn't clear but this is actually the provider's responsibility. See the VirtualBox or Docker providers and their `prepare_nfs_settings` action which does this. It is quite easy to fix once you see. :)
