### ISSUE TITLE
rsync verbose doesnt output files being sycnd

### ISSUE THREAD

**Issue by chrisan** [mitchellh/vagrant#4201]
Would it be possible for `vagrant rsync-auto` to output the files it is sending to the VM?  

There is a slight lag when rsyncing so normally I wait for a new line to show up in the output, however after a number of syncs the console is filled with the same message and no indication of when one started and the next finished

````ruby
  config.vm.synced_folder '.', '/vagrant', type: 'rsync',
    rsync__args: ["--verbose", "--archive", "--delete", "-z"],
    rsync__exclude: [".git/", ".idea/"]
````

**Comment by sethvargo** [comment]
This is fixed with `rsync__verbose`
