### ISSUE TITLE
SMB not working if user password contains a comma

### ISSUE THREAD

**Issue by moigagoo** [mitchellh/vagrant#4230]
Problem
======

Vagrant fails to mount a shared folder within a virtual machine if the Windows password contain a comma (',').

The mount command fails when it faces the comma within its argument string.

Origin
=====

This is a direct consequence of the mount.cifs spec: http://linux.die.net/man/8/mount.cifs

> Note that a password which contains the delimiter character (i.e. a comma ',') will fail to be > parsed correctly on the command line.

Since Vagrant prompts username/password and then just directly puts them as arguments to the mount command, the command obviously fails. There is no way to escape characters for the mount command.

Possible workaround
================

This could be worked around by creating a credentials file (see http://linux.die.net/man/8/mount.cifs) and pointing to it in the mount command arguments:

mount -t cifs -o credentials=/some/path/creds

I attempted to put this in the mount_options param, but did not succeed—the value is inserted *before* username/password, thus having no effect.

So, the possible solution would be to insert mount_options *after* all other params giving a user a chance to override them.

**Comment by cbrunnkvist** [comment]
Closely related bug: *SMB not working if user password is empty*

It is not possible to connect with password "" (empty string). I have not been able to verify if this is the windows file share service refusing to authenticate accounts with empty passwords, or a "mount -o" argument issue.

**Comment by hjoelr** [comment]
I experienced failure to mount when my password had an equals (=) character. I think this is because the -u command line switch of the Linux mount command separates keys from values with the equals character. I was able to successfully mount manually in the VM when I created a credentials file and passed "credentials" to the mount command as @moigagoo mentions doing. Unfortunately, the credentials file approach can be insecure if the file is left laying around in the vm.

**Comment by mitchellh** [comment]
Done, we use creds files now.

**Comment by gawbul** [comment]
Could that get documented on the website? Can't see information on how to use it here https://docs.vagrantup.com/v2/synced-folders/smb.html

**Comment by gawbul** [comment]
Ah, I think I'm misunderstanding how this is being used. I thought you were allowing a custom credentials file to be passed in using `smb_credentials` for example, but you're actually writing the credentials file yourself.
