### ISSUE TITLE
allow overriding keys_only and IdentitiesOnly

### ISSUE THREAD

**Issue by WyseNynja** [mitchellh/vagrant#4275]
I started trying to make a PR for this, but got stuck.  I don't know how to add new options to the Vagrantfile.

Here is my situation:

I have an SSH key on my local machine that allows me to connect to a vagrant

I can `vagrant up` on my local machine and everything works as expected.

I want to ssh to a remote machine (that does not have direct access to my private keys, but DOES have access to my ssh-agent) and run vagrant up there.  This does not work because 'IdentitiesOnly' and 'keys_only' are both forced to yes/true; it hangs on "Waiting for SSH"

I want to have an option in my Vagrantfile that lets me use my ssh-agent instead of a password/custom ssh key/insecure ssh key.  This seems like a simple enough request.

I hard coded the changes into my copy of vagrant and this worked.  I just don't know how to parameterize it.

```
diff --git a/plugins/communicators/ssh/communicator.rb b/plugins/communicators/ssh/communicator.rb
index 2438d74..d850909 100644
--- a/plugins/communicators/ssh/communicator.rb
+++ b/plugins/communicators/ssh/communicator.rb
@@ -293,7 +293,7 @@ module VagrantPlugins
           config:                false,
           forward_agent:         ssh_info[:forward_agent],
           keys:                  ssh_info[:private_key_path],
-          keys_only:             true,
+          keys_only:             false,
           paranoid:              false,
           password:              ssh_info[:password],
           port:                  ssh_info[:port],
diff --git a/templates/commands/ssh_config/config.erb b/templates/commands/ssh_config/config.erb
index 2cdb2db..d31cee9 100644
--- a/templates/commands/ssh_config/config.erb
+++ b/templates/commands/ssh_config/config.erb
@@ -12,7 +12,7 @@ Host <%= host_key %>
   IdentityFile <%= path %>
 <% end -%>
 <% end -%>
-  IdentitiesOnly yes
+  IdentitiesOnly no
   LogLevel FATAL
 <% if forward_agent -%>
   ForwardAgent yes
diff --git a/test/unit/plugins/commands/ssh_config/command_test.rb b/test/unit/plugins/commands/ssh_config/command_test.
index e458776..6d96aab 100644
--- a/test/unit/plugins/commands/ssh_config/command_test.rb
+++ b/test/unit/plugins/commands/ssh_config/command_test.rb
@@ -51,7 +51,7 @@ Host #{machine.name}
   UserKnownHostsFile /dev/null
   StrictHostKeyChecking no
   PasswordAuthentication no
-  IdentitiesOnly yes
+  IdentitiesOnly no
   LogLevel FATAL
       SSHCONFIG
     end
```

While this works, it also still tries to do auth with the insecure private key.  That doesn't matter too much, but it would probably be better to disable that if using the ssh-agent.

I'm willing to write the PR, I just don't know what files to modify in order to add more allowed options.

**Comment by dysinger** [comment]
Related bug which I filed on vagrant-aws https://github.com/mitchellh/vagrant-aws/issues/382

**Comment by zmt** [comment]
The --plain option to the ssh command works with an ssh-agent, but the recently merged configurability of keys_only isn't quite working for me with the ssh communicator and vagrant-aws plugin. The keys_only value is getting reset to the default true by the time Net::SSH.start is actually called (https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/ssh/communicator.rb#L389) , but I haven't yet found exactly where the override is reset to default.

**Comment by zmt** [comment]
Please re-open this issue. PR forthcoming. I found some problems with GH-7360.

**Comment by sethvargo** [comment]
Hi @zmt 

Please open a new issue. We do not triage closed issues (GitHub doesn't make it easy).

**Comment by zmt** [comment]
Will do @sethvargo. Thanks for getting the ball rolling on this issue.

I am working on adding some tests now for `ssh` and `ssh-config` commands. I am having some trouble with this unit test (I think the metadata_url is mangled or something):
```
1) VagrantPlugins::CommandBox::Command::Update execute updating specific box download options are specified passes down download options
     Failure/Error: subject.execute
     Vagrant::Errors::BoxMetadataDownloadError:
       There was an error while downloading the metadata for this box.
       The error message is shown below:
       
       A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
     # ./lib/vagrant/box.rb:135:in `rescue in load_metadata'
     # ./lib/vagrant/box.rb:139:in `load_metadata'
     # ./lib/vagrant/box.rb:160:in `has_update?'
     # ./plugins/commands/box/command/update.rb:123:in `box_update'
     # ./plugins/commands/box/command/update.rb:84:in `block in update_specific'
     # ./plugins/commands/box/command/update.rb:82:in `each'
     # ./plugins/commands/box/command/update.rb:82:in `update_specific'
     # ./plugins/commands/box/command/update.rb:43:in `execute'
     # ./test/unit/plugins/commands/box/command/update_test.rb:215:in `block (5 levels) in <top (required)>'

Finished in 44.56 seconds
2016 examples, 1 failure, 8 pending

Failed examples:

rspec ./test/unit/plugins/commands/box/command/update_test.rb:179 # VagrantPlugins::CommandBox::Command::Update execute updating specific box download options are specified passes down download options
```
I am also struggling to get the acceptance tests working on my Mac.

**Comment by sethvargo** [comment]
Hi @zmt 

Don't worry about the acceptance tests - we run them on infrastructure here. 

That unit test will always fail (fails for me too) because the version of curl that comes with OS X does not include bundled support for some flag (I think it's --capath). You can ignore it - it will pass on Travis when you submit a PR.

**Comment by zmt** [comment]
I figured the libcurl thing was something like that. I will be filing the new issue Monday, but I have to wait for official approval for my company to fork. I could not find the code to build a dev installer, so I'm wondering how to distribute our forked version internally until the 1.8.2 release comes out (assuming it gets included).

**Comment by sethvargo** [comment]
@zmt mitchellh/vagrant-installers is open source (just a different repo)
