### ISSUE TITLE
vagrant plugin install updates depencies irrelevant to the plugin being installed

### ISSUE THREAD

**Issue by Tyrael** [mitchellh/vagrant#4278]
When I was hit by https://github.com/mitchellh/vagrant/issues/3769 I noticed a strange behavior from vagrant plugin install: even installing vagrant plugins without any immediate or transitive dependency to nokogiri tries to install/update it.
This was also noticed in https://github.com/smdahlen/vagrant-hostmanager/issues/110 and @sciurus suggested to report this as a separate issue for more visibility.
Here is my original comment from https://github.com/mitchellh/vagrant/issues/3769 :

I did a little bit more digging why does vagrant try to upgrade nokogiri when installing a plugin which seemingly doesn't have any dependency for it.
It seems that we are generating a bunch of gemfiles (10 gemfile and 3 lockfile for me) on a simple plugin install (it is already reported at https://github.com/mitchellh/vagrant/issues/4103)
But based on my tests, it seems that the unnecessary plugin upgrade is caused by a lockfile, which shouldn't even be loaded according to the commit message in 
https://github.com/mitchellh/vagrant/commit/5197d3d86fc0778b789b96b51d04e8d7cf816b2a
At least non of the other gem/lockfiles generated by the plugin install command has any reference to the nokogiri 1.6.3.1 version, only to the pre-installed 1.6.2.1.

for testing/reproducing the issue, one should remove any other nokogiri gem from ~./.vagrant.d via
```
rm ~/.vagrant.d/gems/specifications/nokogiri-*.gemspec
rm -rf ~/.vagrant.d/gems/gems/nokogiri-*
```

then create a directory for the tmp files (so you don't have to look up your ruby tmpdir and tell apart the old vagrant gem/lockfiles from the ones created in this test)
```
mkdir vagrant_tmp
```

then execute a plugin install with a plugin which doesn't have nokogiri dependency, I choose vagrant-hostmanager:
```
vagrant plugin uninstall vagrant-hostmanager
TMPDIR=$PWD"/vagrant_tmp" vagrant plugin install --debug --verbose vagrant-hostmanager
```

this will trigger the nokogiri install (at least on my system), and leave behind a bunch of files in vagrant_tmp:

```
[tyrael@Ferencs-MacBook-Pro-135 ~ ]$ grep nokogiri -R vagrant_tmp/
vagrant_tmp//vagrant-gemfile20140731-13145-1nvjfol.lock:      nokogiri
vagrant_tmp//vagrant-gemfile20140731-13145-1nvjfol.lock:    nokogiri (1.6.3.1)
vagrant_tmp//vagrant-gemfile20140731-13145-1nvjfol.lock:      nokogiri (>= 1.4.0)
vagrant_tmp//vagrant-gemfile20140731-13145-1nvjfol.lock:      nokogiri (>= 1.4.0)
vagrant_tmp//vagrant-gemfile20140731-13145-1nvjfol.lock:      nokogiri (~> 1.5)
vagrant_tmp//vagrant20140731-13145-yh83sw2.lock:      nokogiri
vagrant_tmp//vagrant20140731-13145-yh83sw2.lock:    nokogiri (1.6.2.1)
vagrant_tmp//vagrant20140731-13145-yh83sw2.lock:      nokogiri (>= 1.4.0)
vagrant_tmp//vagrant20140731-13145-yh83sw2.lock:      nokogiri (>= 1.4.0)
vagrant_tmp//vagrant20140731-13145-yh83sw2.lock:      nokogiri (~> 1.5)
```

but only the vagrant-gemfile (which should be ignore according to @mitchellh's commit refers to the latest nokogiri version.

**Comment by sethvargo** [comment]
This should be fixed in the next release where we properly cleanup tempfiles. There's also another issue that discusses installing plugins in complete isolation which would completely alleviate this. Thanks! 😄
