### ISSUE TITLE
Multi-machine: Incorrect naming of provisioner's shared folders

### ISSUE THREAD

**Issue by legal90** [mitchellh/vagrant#4287]
In multi-machine configuration, when we are doing a global `vagrant up --no-provision`, Vagrant sets incorrect names for temporary shared folders in these VMs.

**Details:**
1) Let's assume, we have this multi-machine configuration: [Vagrantfile](https://github.com/rickard-von-essen/mcollective_test/blob/master/Vagrantfile)

2) When we are running  `vagrant up --no-provision`, the output confirms that the next shared folder names have been configured for the VMs:
```
/tmp/vagrant-puppet-3/*    # in the 1st VM (middleware)
/tmp/vagrant-puppet-5/*    # in the 2nd VM (server)
/tmp/vagrant-puppet-7/*    # in the 3rd VM (client)
```
So, we have different folders in each VM. I've found that it happens because of this provisioner logic: [puppet.rb](https://github.com/mitchellh/vagrant/blob/bb052366f7f9616666299a97edcceadae007394a/plugins/provisioners/puppet/config/puppet.rb#L74-L75), [counter.rb](https://github.com/mitchellh/vagrant/blob/7df5cf6c9df8357669fe54bc4154fbde2e0b1d68/lib/vagrant/util/counter.rb#L8)

3) Then, if we will try to provision each VM individually, Vagrant will expect to see only `/tmp/vagrant-puppet-3/*` in each VM. In the result, only first VM will be provisioned successfully, and last two will failed with `missing_shared_folders` error [(Link)](https://github.com/mitchellh/vagrant/blob/0c7c143ad1fd45a73de3f7ba71c6e9e142bb7a48/plugins/provisioners/puppet/provisioner/puppet.rb#L173)

**Notes**:
1) I suggest that this issue is not related to Puppet provisioner only, but also to Chef provisioner at least (because of the [similar approach](https://github.com/mitchellh/vagrant/blob/7d901912127a86739eecc5feb915d5dcfe2ab0a0/plugins/provisioners/chef/config/base.rb#L99-L100) for temporary folder's naming)

2) The multi-machine provisioning will working fine, if we'll up each VM individually, e.q. `vagrant up <machine_name> --no-provision`. In this case each VM will have `/tmp/vagrant-puppet-3/*` folders.

3) I tried to place `provision` config block inside each of  `vm.define` blocks (as recommended by https://github.com/mitchellh/vagrant/issues/3887#issuecomment-43948064), but nothing changed.

/cc: @rickard-von-essen

**Comment by sethvargo** [comment]
This has been fixed on master.
