### ISSUE TITLE
Hyper-V provider `vagrant up` error w/multiple networks

### ISSUE THREAD

**Issue by csamak** [mitchellh/vagrant#4346]
I get the following error only when I have multiple network interfaces (eth0 + eth1 and 2 adapters on Hyper-V). The VM seems fine (ssh works etc.) but vagrant up reports an error.

```
PS D:\vagrant_ubuntubase> vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...
    default: Timeout: 120 seconds
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: get_network_config.ps1
Error:

C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.6.2\plugins\providers\hyperv\scripts\get_network_config.ps1 : Cannot index into a null array.
At line:1 char:1
+ &('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.6.2\plugins\providers\hyper ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [get_network_config.ps1], RuntimeException
    + FullyQualifiedErrorId : NullArray,get_network_config.ps1

PS D:\vagrant_ubuntubase> vagrant ssh
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)
```

**Comment by borrelan** [comment]
@csamak Were you able to resolve this issue?
cmd --help
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

vagrant up --provider hyperv   
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...                                                                                                                     
    default: Timeout: 120 seconds                                                                                                                                                    
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.                 
                                                                                                                                                                                     
Script: get_network_config.ps1                                                                                                                                                       
Error:                                                                                                                                                                               
                                                                                                                                                                                     
C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyperv\scripts\get_network_config.ps1 : Cannot index into a null array.                                      
At line:1 char:1                                                                                                                                                                     
+ &('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyper ...                                                                                               
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                   
    + CategoryInfo          : InvalidOperation: (:) [get_network_config.ps1], RuntimeException                                                                                       
    + FullyQualifiedErrorId : NullArray,get_network_config.ps1

**Comment by mitchellh** [comment]
Fixed
