### ISSUE TITLE
VMware Workstation uses wrong name for host-only network: vmnet2 instead of VMnet2

### ISSUE THREAD

**Issue by stefanschererseal** [mitchellh/vagrant#4354]
I have started a multi machine Vagrantfile with Vagrant 1.6.3 and the vagrant-vmware-workstation plugin 2.5.2 and VMware Workstation 9.0.4 on a Windows 7 x64 Host machine.

I have added a private network to each of the machines in the Vagrantfile with something like this:

```ruby
    slave.vm.network :private_network, ip: "172.16.32.3"
```

The VMX file of one of the machine contains these network settings:

```
ethernet0.addresstype = "generated"
ethernet0.connectiontype = "nat"
ethernet0.present = "TRUE"
ethernet0.virtualdev = "vmxnet3"
ethernet1.addresstype = "generated"
ethernet1.connectiontype = "custom"
ethernet1.present = "TRUE"
ethernet1.virtualdev = "e1000"
ethernet1.vnet = "vmnet2"
```

But inside the guest there is no network card with this IP adress assigned.

So I opened the VMware Workstation settings and think this could be the problem:

![vmware-settings](https://cloud.githubusercontent.com/assets/8137307/3942796/4d24acba-2576-11e4-98ae-10046911bb41.png)

The VMX and the dialog on the left show `vmnet2` in lower case letters, the option menu on the right is still on the default `VMnet0` with upper case letters.

After selecting the correct network card the dialog shows this:

![vmware-settings-corrected](https://cloud.githubusercontent.com/assets/8137307/3942797/75e4acc2-2576-11e4-8a23-3733ccb9d23e.png)

Seems that the network card name are case sensitive in VMware Workstation and must begin with two upper case letters. `VMnet2` instead of `vmnet2`.

Could this be fixed?

**Comment by mitchellh** [comment]
This should be fixed now, we're more careful about what we downcase.

**Comment by StefanScherer** [comment]
Thank! My colleages will appreciate that.
