### ISSUE TITLE
"vagrant init" to work with metadata URLs

### ISSUE THREAD

**Issue by mkuzmin** [mitchellh/vagrant#4390]
At the moment `vagrant init` command works with direct box URLs only, and does not support metadata files.
Recently added `box_server_url` setting (https://github.com/mitchellh/vagrant/pull/4282) is great, but I have to add it to generated Vagrantfiles manually.
It would be helpful, if I can call a single `vagrant init http://local/company/ubuntu` command, it downloads the box metadata, and automatically populates Vagrantfile with:
```
config.vm.box = "company/ubuntu"
config.vm.box_server_url="http://local"
```

**Comment by sethvargo** [comment]
Hi @mkuzmin 

This seems to have already been available in Vagrant, but it wasn't documented well. Passing a second argument to the command is assumed to be the box url:

```
vagrant init mybox http://www.mybox.com/box.box
```

The next version of Vagrant will include an updated command signature to make this clearer: https://github.com/mitchellh/vagrant/blob/791ad7ac8eed9534d92f6bffd02f863f7c405c9d/plugins/commands/init/command.rb#L20
