### ISSUE TITLE
New action hook: shared folder sync

### ISSUE THREAD

**Issue by jugglinmike** [mitchellh/vagrant#4394]
I'm looking to build a plugin that performs a custom task when a shared folder syncs. I happen to be using the "rsync" type, but ideally this hook would be triggered regardless of synchronization mechanism.

Would a new `action_hook` like `sync` make sense for Vagrant?

**Comment by chrisroberts** [comment]
Related: #3849

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
