### ISSUE TITLE
dont create a private network IP on the same IP subnet as a NAT.

### ISSUE THREAD

**Issue by gtmtech** [mitchellh/vagrant#4430]
(Virtualbox 4.3.12)
(Vagrant 1.6.3)

I know in retrospect this was a bit dumb of me, but specifying a :private_network, with static IP address of (e.g. 10.0.2.101), when there is already a NAT adapter (vboxnet0) which by default covers 10.0.2/24, means the private_network will not work as the secondary HOSTONLY adapter wont be created, and all the routing wont work.

This took me hours of trawling the web to work out, and it seems lots of others have had this problem.

A little note in the documentation about :private_network, do not use an IP address in an existing NAT adapter subnet would be really helpful to avoid people making the same mistakes.

**Comment by mitchellh** [comment]
Fixed
