### ISSUE TITLE
[Enhancement] Document vagrantfile requirements for Windows

### ISSUE THREAD

**Issue by ferventcoder** [mitchellh/vagrant#4436]
I found where to update the communicator at https://www.vagrantup.com/blog/feature-preview-vagrant-1-6-windows.html :

```ruby
  config.vm.communicator = "winrm"
```

But I could not find it in the docs at all. Would have expected to see it here: http://docs.vagrantup.com/v2/vagrantfile/machine_settings.html

**Comment by mitchellh** [comment]
This is done
