### ISSUE TITLE
`vagrant up` fails due to vmware-networks --configure

### ISSUE THREAD

**Issue by krishicks** [mitchellh/vagrant#4451]
We're trying to `vagrant up` with vmware_workstation as a provider on a 64-bit Linux machine and are running into an issue.

The output from `vagrant up` ends in the following:

```
The VMware "vmnet" devices are failing to start. The most common
reason for this is collisions with existing network services. For
example, if a hostonly network space collides with another hostonly
network (such as with VirtualBox), it will fail to start. Likewise,
if forwarded ports collide with other listening ports, it will
fail to start.
```

Adding `VAGRANT_LOG=debug` to `vagrant up` shows us it's having difficulty configuring the vmnet devices. The call that fails is `vmware-networks --configure`:

```bash
INFO subprocess: Starting process: ["/usr/bin/vmware-networks", "--configure"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: /usr/bin/vmware-networks: unrecognized option '--configure'
Try '/usr/bin/vmware-networks --help' for more information
```

Our version of `vmware-networks` reports supporting the following:

```bash
$ vmware-networks --help
vmware-networks version: 0.1
Usage: vmware-networks [--verbose | -v] <option>
Use exactly one of these commands:
  --postinstall <component-name>,<old-version>,<new-version>
  --migrate-network-settings <location of settings file>
  --start
  --stop
  --status

Additional options:
  --help | -h
  --version
```

We've tried using all available versions of the vagrant-vmware-workstation plugin, as displayed at http://gems.hashicorp.com/ (2.4.1, 2.5.1, 2.5.2, and 3.0.0), but we saw no change in the invocation to `vmware-networks`.

We also tried different versions of VMware Workstation (9.0.4, 10.0.1, and 10.0.3), but none of the `vmware-networks` binaries across those versions supports the `--configure` flag.

Similar error seen by someone else, pasted here: http://pastebin.com/JgHkjMWN.

It's not clear to us when or under what situations --configure is expected to work, but it isn't working for us.

Cheers,

KH

**Comment by jmiller0** [comment]
Confirmed this is still an issue 

vagrant up --provider vmware_workstation --debug  2>&1 | egrep 'vmware-networks.+configure' | head -n2
DEBUG subprocess: stderr:  INFO subprocess: Starting process: ["/usr/bin/vmware-networks", "--configure"]
DEBUG subprocess: stderr: DEBUG subprocess: stderr: /usr/bin/vmware-networks: unrecognized option '--configure'

vagrant plugin list
vagrant-share (1.1.3, system)
vagrant-vmware-workstation (3.2.4)

**Comment by phinze** [comment]
Hey folks - I think with `v3.2.5` (just released) this should be fixed. See #5451 for the details, and let me know if you still see issues! :ok_hand:
