### ISSUE TITLE
Plugin installation: Add an option to only use the provided plugin source as installation source

### ISSUE THREAD

**Issue by mahnkong** [mitchellh/vagrant#4486]
We use vagrant on a variety of machines that cannot connect directly to the internet. Therefore we host all required Rubygems using an own Rubygems repository server (based on geminabox) We would like to be able to also use this repository server as the source for all vagrant plugin installations (the plugins are already present in our own gem repository) - but when trying to install a plugin with specifying the plugin source:

    vagrant plugin install vagrant-proxyconf --plugin-source http://gemrepo/

the plugin installation process also tries to connect to "https://rubygems.org" causing the plugin installation to fail. The output looks as below:

    Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
    Bundler, the underlying system Vagrant uses to install plugins,
    reported an error. The error is shown below. These errors are usually
    caused by misconfigured plugin installations or transient network
    issues. The error from Bundler is:
  
    Could not fetch specs from https://rubygems.org/
  
    Retrying source fetch due to error (2/3): Bundler::HTTPError Could not fetch specs from https://rubygems.org/Retrying source fetch due to error (3/3): Bundler::HTTPError Could not fetch specs from https://rubygems.org/

I propose to add an option (--force-plugin-source), which will be considered in *lib/vagrant/bundler.rb* when writing the gemfile inside the method *build_gemfile*. When the option is set together with the *--plugin-source* option, only the provided plugin-source will be written as a source in the created gemfile.

**Comment by xacaxulu** [comment]
+1

**Comment by jerryz1982** [comment]
+1 especially for people in China

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/pull/4738
