### ISSUE TITLE
Hyper-V provider requires user be an admin instead of requiring user has Hyper-V permissions

### ISSUE THREAD

**Issue by pvandervelde** [mitchellh/vagrant#4503]
In order to interact with Hyper-V the user needs specific permissions (normally only provided to administrators) however these permissions can be granted to other users. I have done so with my account and can access hyper-v both from the Hyper-V manager as well as through powershell without elevating to admin. Unfortunately Vagrant requires me to be an admin. It would be much better if Vagrant would verify that the user has access to Hyper-V before requiring elevation.

**Comment by lukebakken** [comment]
As a note, Windows 8.1 has a "Hyper-V Administrators" group that makes it very easy to give a regular user the correct permissions.

The hyper-v provider should attempt an operation and, if it fails, examine the returned error. If it is "access denied" then vagrant should alert the user that an elevated shell is necessary.

**Comment by am11** [comment]
@lukebakken, would be nice if you can send a PR for this. :)

**Comment by mitchellh** [comment]
I'd love to add this but I'm not familiar enough with PowerShell to figure out the right approach to this. If someone can open a PR I'd gladly merge. Until then, we'll keep requiring admin privs, sorry!

**Comment by shamakhov** [comment]
The issue is not fixed in localized Windows  versions because of translated group names. This group has name 'Администраторы Hyper-V' in Russian Windows version.

**Comment by lukebakken** [comment]
@shamakhov - you would have to determine if the current user is a [member of the group with SID `S-1-5-32-578`](https://support.microsoft.com/en-us/kb/243330). Using `net localgroup` was a "good enough" fix. I'll see about doing it the right way.
