### ISSUE TITLE
connection refused retrying and timeout

### ISSUE THREAD

**Issue by dbwhddn10** [mitchellh/vagrant#4511]
same issue https://github.com/mitchellh/vagrant/issues/4470(closed)

my OS is window7

i only execute below command.
```
vagrant init hashicorp/precise32
vagrant up
```
i got a connection refused retrying log meesage after SSH auth method: private key

and i set vagrantfile like this
```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
end
```

but i got same message..

what is solution ? 

http://stackoverflow.com/questions/25346093/vagrant-connection-refused-error 's answer is true?

my environment version info is
Virtualbox: 4.3.16
vagrant: 1.6.5

**Comment by mitchellh** [comment]
These are just warnings... as they say... it is okay.

**Comment by mitchellh** [comment]
Vagrant tries to connect to SSH VERY early, so it often gets a failure early, and then prints a warning, and retries, and makes it in. This is jsut fine.
