### ISSUE TITLE
vagrant box update does not honor insecure option nor ca-cert option

### ISSUE THREAD

**Issue by Xylakant** [mitchellh/vagrant#4533]
I have a box hosted on vagrantcloud that has the actual box file on an SSL-enabled server with a self-signed cert. I can download and install the box using `vagrant box add --insecure` but that flag is not retained, so calling `vagrant box update` fails with a cert error. The corresponding option in the Vagrantfile (`config.vm.box_download_insecure`) is not honored either.

Since `vagrant box update` does not accept the --cacert option and the corresponding option `config.vm.box_download_ca_cert` in the Vagrantfile is not honored either, it is currently impossible to update boxes from SSL-Servers with self-signed certificated.

**Comment by ibizaman** [comment]
Easy enough to patch, I'm adding those four options to `vagrant box update`:
```
--insecure
--cacert
--capath
--cert
```
Expect a PR tonight.

**Comment by mitchellh** [comment]
Just tagging #4473 so we can see the link.

**Comment by mitchellh** [comment]
Fixed by #4473
