### ISSUE TITLE
SMB mount expires

### ISSUE THREAD

**Issue by n3ziniuka5** [mitchellh/vagrant#4538]
When you have a synced folder using SMB, if the mounted directory is idle for some time, the mount is lost. Then when you try to access the mounted directory the shell freezes. reconnect option when mounting may solve the issue.

http://superuser.com/questions/748161/when-i-try-to-access-a-smb-mounted-folder-from-inside-a-vagrant-centos-virtual-b

**Comment by ErwinSteffens** [comment]
I've exact the same issue. My shell expires after some time. We're using the docker provider and when accessing the SMB shared folders the shell freezes completly. Using Windows 8.1 64-bit.

**Comment by mitchellh** [comment]
Fixed (docs)
