### ISSUE TITLE
Vagrant ignores changed box type

### ISSUE THREAD

**Issue by mperham** [mitchellh/vagrant#4540]
I wanted to change my box type from hashicorp/precise64 to chef/centos-6.5 so I edited my Vagrantfile and ran vagrant up:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'chef/centos-6.5' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
...
$ vagrant ssh
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)
vagrant@precise64:~$ exit
```

Vagrant's usually pretty awesome about showing helpful hints, could this case be detected and tell me how to install/restart the new box type?

**Comment by sethvargo** [comment]
Hi there,

This is a pretty old issue. I think we've documented `vagrant reload` pretty heavily at this point, which is the command you should run after making any changes to the VM or Vagrantfile. Thanks! 😄
