### ISSUE TITLE
DYLD_LIBRARY_PATH breaks things

### ISSUE THREAD

**Issue by aggress** [mitchellh/vagrant#4543]
If I have the DYLD_LIBRARY_PATH env var set, vagrant breaks as follows

[Richard@Ilya~]$ vagrant
/Applications/Vagrant/embedded/lib/ruby/2.0.0/openssl.rb:17:in `require': dlopen(/Applications/Vagrant/embedded/lib/ruby/2.0.0/universal-darwin12.5.0/openssl.bundle, 9): Symbol not found: _TLSv1_1_client_method (LoadError)
  Referenced from: /Applications/Vagrant/embedded/lib/ruby/2.0.0/universal-darwin12.5.0/openssl.bundle
  Expected in: /opt/mapr/hiveodbc/lib/universal/libssl.1.0.0.dylib
 - /Applications/Vagrant/embedded/lib/ruby/2.0.0/universal-darwin12.5.0/openssl.bundle
	from /Applications/Vagrant/embedded/lib/ruby/2.0.0/openssl.rb:17:in `<top (required)>'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant.rb:64:in `require'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant.rb:64:in `<top (required)>'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.3/bin/vagrant:101:in `require'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.3/bin/vagrant:101:in `<main>'
[Richard@Ilya~]$ echo $DYLD_LIBRARY_PATH
/opt/mapr/hiveodbc/lib/universal

If I unset the var, it works again

[Richard@Ilya~]$ unset DYLD_LIBRARY_PATH
[Richard@Ilya~]$ vagrant --version
Vagrant 1.6.3
[Richard@Ilya~]$

This is from having the MapR ODBC driver installed [0] and configured

[0] http://doc.mapr.com/display/MapR/Hive+ODBC+Connector#HiveODBCConnector-InstallingtheHiveODBCConnectoronMacOS

**Comment by sethvargo** [comment]
Hi there,

As of Vagrant 1.7, we do our best in the installer to set the DYLD variables correctly. Unfortunately if you are running outside of the official installer, you may need to set them yourself.

If you continue to experience issues with Vagrant 1.7.2+, please open a new issue and include the complete Vagrantfile as well as gist the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html). Thanks!

**Comment by v6** [comment]
// , I'm seeing the same error as detailed here ( https://github.com/mitchellh/vagrant/issues/5782 ) in the latest Vagrant, in a fresh installation of the latest from https://www.vagrantup.com/downloads.html to a Mac 10.10 laptop, previously un-vagranted. 

If I can verify that it has to do with the `DYLD_LIBRARY_PATH`, I will refer back to this issue and https://github.com/mitchellh/vagrant/issues/5782.

**Comment by jarmstrong-getswift** [comment]
Apparently this issue is very old but still an issue as setting the DYLD_LIBRARY_PATH (for the Tableau application in my case) breaks Vagrant.  I can unset the variable to get it working again, but it doesn't seem like there's a true fix for this out there, just workarounds.  This appears to be an issue with Virtual Box only since I don't have the problem with VM's in Parallels Desktop, although I have to retain a Virtual Box setup since Parallels has issues with Talend due to another unrelated glitch.  I'm using Vagrant 2.2.3 btw.
