### ISSUE TITLE
Option to destroy on provisioning error

### ISSUE THREAD

**Issue by Pyrolistical** [mitchellh/vagrant#4555]
The `vagrant up --destroy-on-error` only destroys the machine on fatal _vagrant_ errors.  It does not destroy the machine on provisioning errors.

The machine is useless to me if there is a provision error and would like an option to have it destroyed on provisioning error.

I propose a new option `--[no-]destroy-on-provisioning-error` and have it default to false.

**Comment by kenorb** [comment]
Posted [bounty of $50](https://www.bountysource.com/issues/4738309-option-to-destroy-on-provisioning-error) for this issue. Anybody interested can add more. So I hope it'll be resolved quicker.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
