### ISSUE TITLE
Vagrant works different when yields a VM for command by name and when yields VMs by regexp or all autoload VMs

### ISSUE THREAD

**Issue by ilucker** [mitchellh/vagrant#4556]
I like the idea to put a default provider name into my Vagrantfile: 

`````ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure('2') do |config|

	config.vm.define "docker" do |ldap|

	  ldap.vm.synced_folder '.', '/vagrant', disabled: true

	  ldap.vm.provider :docker do |docker|
	    docker.image = 'busybox'

	    docker.vagrant_vagrantfile = 'Vagrantfile'
	    docker.vagrant_machine = "host"
	  end
	end


	# Machine to host dockers for development purposes
	config.vm.define 'host', autostart: false do | host |
		host.vm.box = 'mitchellh/boot2docker'

		host.vm.provider :parallels do |prl, override|
		  override.vm.box = 'parallels/boot2docker'

		  prl.name = 'boot2docker/busybox'
		end
	end
end
`````
when i run `````>vagrant up docker````` i get error "* A box must be specified." but if i run `````>vagrant up /docker/````` everything works as expected. This is because in the latter case vagrant reads and executes my Vagrantfile before it tries to find the default provider for a box. But in the first case it does not execute  the Vagrantfile before looking for the default provider and resolves it to a different one, not to the "docker"

I'd expected vagrant should work equally independently from how we pass a box name.

**Comment by mitchellh** [comment]
This is likely true, but setting environmental variables that Vagrant uses must be done _before_ Vagrant is executed. Setting it within a Vagrantfile will result in unexpected errors and we won't consider that a bug.
