### ISSUE TITLE
Salt provisioner always uses bad options

### ISSUE THREAD

**Issue by markkimsal** [mitchellh/vagrant#4566]
I'm trying to provision a simple minion with no configuration except the IP of the master in a minion_config file.
```
  config.vm.provision :salt do |salt|
    salt.minion_config = "salt/minion"
    salt.run_highstate = true
    salt.verbose = true
  end
```
The contents of the salt/minion file
```
master: 172.17.0.121
```
The salt/minion file is uploaded to /tmp/minion by vagrant, but the configuration option to use /tmp/minion as a config file is broken.  The result is that my minion is using default configs and always looking for a salt master with a hostname of "salt".  I can see DNS queries with wireshark requesting the hostname "salt" from 8.8.8.8

```
vagrant up --provider docker --provision
...
==> default: Machine booted and ready!
==> default: Running provisioner: salt...
Copying salt minion config to vm.
Checking if salt-minion is installed
salt-minion found
Checking if salt-call is installed
salt-call found
Using Bootstrap Options:   -F -c /tmp -C
Salt binaries found. Configuring only.
Salt successfully configured!
run_overstate set to false. Not running state.overstate.
Calling state.highstate... (this may take a while)
```

The -F and -C flags are not valid parameters to salt-minion.  When I SSH into the running container, salt-minion is not running, but salt-call saltuitl.sync_all is.  Running salt-minion -c /tmp & correctly connects the minion to my master at the IP specified in the minion_config file.

```
root@36bba681a7bd:~# salt-minion -F -c /tmp/ -C
salt-minion: error: no such option: -F

root@36bba681a7bd:~# salt-minion  -c /tmp/ -C
Usage: salt-minion

salt-minion: error: no such option: -C

root@36bba681a7bd:~# salt-minion  -c /tmp/ 
... [works]
```
It seems that the -F and -C (capital C) flags are not valid for salt-minion no salt-master.

**Comment by sethvargo** [comment]
Should be fixed in 1.8.3. Thanks!
