### ISSUE TITLE
Force destroy vagrant instance that "was not found configured for this Vagrant environment"

### ISSUE THREAD

**Issue by gwagner** [mitchellh/vagrant#4579]
I guess i don't really care if it was found in the environment, i just want to destroy the box because it was made and is in the global status.  Worse is that the box is running and i can't halt it or anything.  Vagrant knows what the ID is (because it is in global-status) so it should be pretty simple.

This becomes a problem when you are actively working, do a vagrant up, change the name of the vm / add another vm and do another vagrant up.  You end up with an orphan that can not be killed (unless i manually remove all reference too it and then drop it from the VM Manager)

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue. In the next version of Vagrant, all the "regular" vagrant commands accept a global status ID in addition to a VM name, so you will be able to use `vagrant destroy ID-FROM-GLOBAL-STATUS`. Additionally, the global-status is a cache, not a true representation of the current state. You many need to run `global-status --prune`. Thanks! 😄

**Comment by franz-josef-kaiser** [comment]
Updated from 1.8.5 to 2.1.2 and this is the response:
```
==> You need a `setup.yml` file
```
