### ISSUE TITLE
winRM powershell script fails with virtualbox

### ISSUE THREAD

**Issue by damphyr** [mitchellh/vagrant#4593]
I'm running vagrant 1.6.5 and using a packer created base box. My host is Windows. The same base box for VMWare works with no problems. The VirtualBox has extensions installed and the \VBOXSVR share is available.

The Vagrantfile is 

``` ruby
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "dev" do |cfg|
    cfg.vm.hostname="pj"
    cfg.vm.box = "basebox/win7x64-pro-chef.box"
    cfg.vm.box_check_update = false
    # Port forward WinRM and RDP
    cfg.vm.network :forwarded_port, guest: 3389, host: 3380, id: "rdp", auto_correct:true
    cfg.vm.communicator = "winrm"
    cfg.vm.network :forwarded_port, guest: 5985, host: 5986, id: "winrm", auto_correct:true
    # Port forward SSH
    cfg.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct:true
    cfg.vm.provider :virtualbox do |v, override|
      v.gui = true
      v.customize ["modifyvm", :id, "--memory", 3096]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--vram", "256"]
      v.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
      v.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
    end
  end
end
```

When doing vagrant up the following error occurs

```
ERROR warden: Error occurred: The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

function Test-ReparsePoint([string]$path) {
  $file = Get-Item $path -Force -ea 0
  return [bool]($file.Attributes -band [IO.FileAttributes]::ReparsePoint)
}

$MountPoint = [System.IO.Path]::GetFullPath("/vagrant")
$ShareName = "vagrant"
$VmProviderUncPath = "\\vboxsrv\vagrant"

# https://github.com/BIAINC/vagrant-windows/issues/4
# Not sure why this works, but it does.

& net use $ShareName 2>&1 | Out-Null

Write-Debug "Attempting to mount $ShareName to $MountPoint"
if( (Test-Path "$MountPoint") -and (Test-ReparsePoint "$MountPoint") )
{
  Write-Debug "Junction already exists, so I will delete it"
  # Powershell refuses to delete junctions, oh well use cmd
  cmd /c rd "$MountPoint"

  if ( $LASTEXITCODE -ne 0 )
  {
    Write-Error "Failed to delete symbolic link at $MountPoint"
    exit 1
  }

}
elseif(Test-Path $MountPoint)
{
  Write-Debug "Mount point already exists and is not a symbolic link"
  exit 1
}

$BaseDirectory = [System.IO.Path]::GetDirectoryName($MountPoint)

if (-not (Test-Path $BaseDirectory))
{
  Write-Debug "Creating parent directory for mount point $BaseDirectory"
  New-Item $BaseDirectory -Type Directory -Force | Out-Null
}

cmd /c mklink /D "$MountPoint" "$VmProviderUncPath" | out-null

if ( $LASTEXITCODE -ne 0 )
{
  exit 1
}

if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }

Stdout from the command:

Stderr from the command:
```

**Comment by danielleshoemake** [comment]
Did you figure this one out by chance?  I'm having the same problem.  The output is exactly the same with no real stdout.  I've only narrowed it down to happening when I try to set synced folders (vm.config.synced_folder) in the vagrant file.  I don't have the problem when I use a windows 2008 r2 box, but do have it with a 2012 r2 box.

**Comment by damphyr** [comment]
@danielleshoemake Sorry, no luck with this yet. And I'm using VMWare at the moment so I'm not digging further either.

**Comment by joelwilson** [comment]
I ran into this problem after adding the following synced_folder:

    windows.vm.synced_folder 'U:/.chef', '/chef'

Pretty much the exact same error as damphyr with same vagrant and vbox versions. The vagrant synced folder and a different "custom" synced folder work though.

    // This synced folder works
    windows.vm.synced_folder '../pkg', '/pkg'

I copy & pasted the script in the output window to a powershell console on the guest, and here is what I found:

    PS C:\Users\vagrant> cmd /c mklink /D "$MountPoint" "$VmProviderUncPath" | out-null
    Cannot create a file when that file already exists.

So somehow it was already linked. I'm using berkshelf and the chef-solo provisioner - maybe one of those had already created it?

**Comment by blanoz** [comment]
If the synced filder contains a . in the name, i would also get this error.

**Comment by bollenn** [comment]
maybe it has to do with:

$VmProviderUncPath = "\\vboxsrv\vagrant"

which should be:

$VmProviderUncPath = "\\VBOXS**VR**\vagrant"

**Comment by tal5ab** [comment]
I had this issue 
And based on comments above , i found a duplication in the sync folders 
And the issue got resolved

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
