### ISSUE TITLE
Documentation of Vagrant vs Provisioner attributes

### ISSUE THREAD

**Issue by tejaycar** [mitchellh/vagrant#4603]
As indicated by https://github.com/mitchellh/vagrant/issues/4583 there are two places to add attributes when making a call to `vagrant.vm.provision`  Attributes related to Vagrant itself belong in the `provision` method call, while attributes on the provisioner belong inside the block.  This is not well documented, and is made more confusing by the one-line style provision calls which seem to blend both types of attributes.

    config.vm.provision "shell", inline: "echo foo", id: "foo"

We need some clarification regarding which attributes can go in the method call, which belong in the block, and which may work in the one-liner.  Furthermore, in places that the one-liner is used in examples, it would be good to add an additional example that has the block syntax, for clarity sake.

Finally, it would be nice to have a page dedicated to listing and explaining the attributes which can be set inside the method call (such as :id).

**Comment by mitchellh** [comment]
Update docs and the options are enumerated on the specific provisioner pages.
