### ISSUE TITLE
Network fails with Fedora 20 host

### ISSUE THREAD

**Issue by jdart** [mitchellh/vagrant#4610]
I'm trying to get a vagrant configuration from puphpet.com working, and it seems the networking fails when using Fedora 20 as a host. I've attempted to [whittle down the Vagrantfile](https://gist.github.com/jdart/993834b2322ba4c0f318) to be as small as possible.

The output of `vagrant up --debug` can be [seen here](https://gist.github.com/jdart/2d1da08de958b01b427b).

I've ensured iptables are not active, and that the mount is available by doing a `showmount -e localhost`. I'm out of ideas for debugging this issue. Any suggestions?

**Comment by sethvargo** [comment]
Hi @jdart 

Is this still an issue with the latest version of Vagrant? Would you be able to get us an updated debug log? Thanks!

**Comment by jdart** [comment]
I caved and bought a mbp, I'll close this.
