### ISSUE TITLE
Issue Converting OVA to BOX File via `vagrant package`

### ISSUE THREAD

**Issue by kevinmeredith** [mitchellh/vagrant#4634]
On Windows 7 64-bit, from [Windows.IE](https://www.modern.ie/en-us/virtualization-tools), I downloaded 4 RARs and 1 EXE file in order to build a VirtualBox VM for Windows 7 + IE 9.

Then, I imported the OVA file into VirtualBox.

Lastly, I tried to convert the OVA file into a BOX file via vagrant package ... so that I can use the BOX file in Vagrant.

Using RubyInstaller for Windows:

```
ruby -v 
ruby 1.9.3p545 (2014-02-24) [i386-mingw32]
```

I ran the following command:

```
>vagrant package --base 775f4f8c-fbd1-4829-b389-f98b93b5c438 --output WIN7IE9.box
==> 775f4f8c-fbd1-4829-b389-f98b93b5c438: Exporting VM...
==> 775f4f8c-fbd1-4829-b389-f98b93b5c438: Compressing package to: c:/path/WIN7IE9.box
```

Then, I tried to add the BOX so that I could create VM's out of it:

```
>vagrant box add WIN7IE9 c:/path/WIN7IE9.box
==> box: Adding box 'WIN7IE9' (v0) for provider:
    box: Downloading: file://c:/path/WIN7IE9.box
    box: Progress: 100% (Rate: 3692k/s, Estimated time remaining: 0:00:01)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x ./box-disk1.vmdk
```

I ran the above vagrant package ... command twice with apparent success. However, for both times, running vagrant box add ... spit out the "The box failed to unpackage ..." error.

Note - I posted this [question](http://stackoverflow.com/questions/26286787/failing-to-convert-virtualbox-ova-file-into-vagrant-box-file-with-vagrant-packa) on StackOverflow, but no one has responded.

**Comment by mitchellh** [comment]
The box is definitely invalid. It isn't a valid tar archive. Vagrant just shells out to `VBoxManage export`. I'm guessing this isn't including disks for some reason (a source VM config?). Could you investigate?
