### ISSUE TITLE
Shell Provisioning Error On Windows when using a Multi-Machine Vagrantfile

### ISSUE THREAD

**Issue by jmcneiceGE** [mitchellh/vagrant#4639]
Using Vagrant 1.6.5 on Windows Server 2012R2 I'm getting an error when trying to use shell provisioning with a multi-machine set up. The box I'm using has Windows Server 2012 installed and works correctly in a single machine set up. 

[Vagrant file and debug output for working single machine provisioning](https://gist.github.com/jmcneiceGE/242d6ab1c170b2b9a980)

[Vagrant file and debug output for erroring multi-machine provisioning](https://gist.github.com/jmcneiceGE/5dbf3c7e6f0b477ba569)

**Comment by mitchellh** [comment]
This should be fixed now
