### ISSUE TITLE
Add capability for SMB synced folders to install client utils if it can

### ISSUE THREAD

**Issue by dimbleby** [mitchellh/vagrant#4642]
This is the issue that took me to https://github.com/mitchellh/vagrant/pull/4641 - it turns out that once I had an error message I could figure out what was going on after all.

Windows host, Centos 6.5 guest.

My Vagrantfile describes a shared folder of type "smb".  The attempt to mount this was failing like this:

    mount: wrong fs type, bad option, bad superblock on //pc4296/72bd80d14b156093afd73ce3bab476ff,
           missing codepage or helper program, or other error
           (for several filesystems (e.g. nfs, cifs) you might
           need a /sbin/mount.<type> helper program)
           In some cases useful info is found in syslog - try
           dmesg | tail  or so

Repeated attempts failed in the same way.

In the end the issue seemed to be simply that the base box for the guest doesn't have the required software.  I ran `sudo yum install cifs-utils`, and after that `vagrant reload` ran fine and set up the shared folder successfully.

How's this supposed to work?  Is Vagrant expected to install `cifs-utils` automatically when it spots that it's going to need it?  Must I make sure that `cifs-utils` is in my base box?  Or is the `vagrant up`, `sudo yum install cifs-utils`, `vagrant reload` dance the only way?

**Comment by chrisrichard** [comment]
Any way to work around this for the time being?

**Comment by sethvargo** [comment]
This is fixed!
