### ISSUE TITLE
need a way to check VirtualBox version from provider block

### ISSUE THREAD

**Issue by aspiers** [mitchellh/vagrant#4649]
I have a `Vagrantfile` describing an environment which only works with VirtualBox >= 4.3.  How can I add a check to the `Vagrantfile` to enforce this?  Thanks.

**Comment by mitchellh** [comment]
As I said a year ago, this was never implemented, so closing.

**Comment by marco-m** [comment]
@aspiers did you manage to find a way ? I am exactly in the same situation, I need to enforce a minimum VirtualBox version.

**Comment by aspiers** [comment]
I'm afraid not.

**Comment by eis** [comment]
Since this feature does not exist, I've used a simple and crude workaround of just using ruby shell in the beginning of Vagrantfile. Maybe it's of help to someone:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

vbox_version=`vboxmanage --version`
vb = vbox_version.split('.').map{|s|s.to_i}
vb_min = [5,1,0]
if ((vb <=> vb_min) < 0)
	abort('virtualbox needs to be at least of version 5.1.0 for this box')
end

VAGRANTFILE_API_VERSION = "2"
# etc...
```

**Comment by ericcitaire** [comment]
Here is the code I use to get VirtualBox version:

```ruby
def virtualbox_version()
    vboxmanage = Vagrant::Util::Which.which("VBoxManage") || Vagrant::Util::Which.which("VBoxManage.exe")
    if vboxmanage != nil
        s = Vagrant::Util::Subprocess.execute(vboxmanage, '--version')
        return s.stdout.strip!
    else
        return nil
    end
end
```

Hope this helps.

**Comment by marco-m** [comment]
@ericcitaire thanks! Your snippet is cross-platform, which is what I needed!

**Comment by Raskil** [comment]
@ericcitaire Just a small update to your suggestion, Line 2::
`vboxmanage = Vagrant::Util::Which.which("VBoxManage") || Vagrant::Util::Which.which("VBoxManage.exe") || ENV['VBOX_MSI_INSTALL_PATH'] + "VBoxManage.exe"`

This will find the vboxmanage.exe on Windows, even when it's not in the path (which it is not by default). The VirtualBox Installer creates the Env-Variable.

**Comment by marco-m** [comment]
Here is yet another variant, the one I currently use to enforce a minimum VIrtualBox version. This too is cross-platform:

```
MIN_VIRTUALBOX_VERSION = Gem::Version.new('5.2.8')
version = `VBoxManage --version`
clean_version = /[0-9]+\.[0-9]+\.[0-9]+/.match(version)
if Gem::Version.new(clean_version) < MIN_VIRTUALBOX_VERSION
    abort "Please upgrade to Virtualbox >= #{MIN_VIRTUALBOX_VERSION}"
end
```
