### ISSUE TITLE
Vagrant defaults to VMWare if the VMWare plugin is installed

### ISSUE THREAD

**Issue by uchagani** [mitchellh/vagrant#4654]
Boxes were created for virtualbox and the vagrant file configures for virtualbox but because I have the vmware_workstation plugin installed, it always defaults to that.

I would think that if metadata.json specifies virtualbox and the vagrant file configures for virtualbox i shouldn't have to force vagrant up with the --provider flag.

**Comment by milosgajdos83** [comment]
I'm seeing possibly the same problem. I have the following [Vagrantfiles](https://gist.github.com/milosgajdos83/c277efc910ea71054a77).

When I try to bring up both containers via vagrant up I get:

```
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'socat'
machine. Please handle this error then try again:

The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: ubuntu/trusty64
Address: https://atlas.hashicorp.com/ubuntu/trusty64
Requested provider: ["vmware_desktop", "vmware_fusion", "vmware_workstation"]

An error occurred while executing the action on the 'pv'
machine. Please handle this error then try again:

The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: ubuntu/trusty64
Address: https://atlas.hashicorp.com/ubuntu/trusty64
Requested provider: ["vmware_desktop", "vmware_fusion", "vmware_workstation"]
```

The strangest thing is that when I try to bring up the machine using the Vagrantfile referred to in ```d.vagrant_vagrantfile``` on its own I get similar error:

```
Bringing machine 'dockerhost' up with 'vmware_fusion' provider...
==> dockerhost: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    dockerhost: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    dockerhost: Box Version: >= 0
==> dockerhost: Loading metadata for box 'ubuntu/trusty64'
    dockerhost: URL: https://atlas.hashicorp.com/ubuntu/trusty64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: ubuntu/trusty64
Address: https://atlas.hashicorp.com/ubuntu/trusty64
Requested provider: ["vmware_desktop", "vmware_fusion", "vmware_workstation"]
```

Basically, looks like when you have installed vmware fusion plugin you are doomed :-)

**Comment by xacaxulu** [comment]
+1

**Comment by xacaxulu** [comment]
@uchagani did you figure out a workaround for this?

**Comment by uchagani** [comment]
@xacaxulu you can provide the ```--provider``` flag to force a specific provider.

**Comment by ryanchapman** [comment]
@milosgajdos83, I just ran into the same thing as you... was trying to move from VirtualBox to VMware Fusion, and had the following Vagrantfile:

```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "development", autostart: false do |dev|
        dev.vm.box = "ubuntu/precise64"
        dev.vm.provider "vmware_fusion" do |v|
            v.memory = 512
        end

        dev.vm.provision "ansible" do |ansible|
            ansible.playbook = "vagrant-provision.yml"
        end
    end
end
```

Attempting to up the development machine gives:

```
$ vagrant up development
Bringing machine 'development' up with 'vmware_fusion' provider...
==> development: Box 'ubuntu/precise64' could not be found. Attempting to find and install...
    development: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    development: Box Version: >= 0
==> development: Loading metadata for box 'ubuntu/precise64'
    development: URL: https://atlas.hashicorp.com/ubuntu/precise64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: ubuntu/precise64
Address: https://atlas.hashicorp.com/ubuntu/precise64
Requested provider: ["vmware_desktop", "vmware_fusion", "vmware_workstation"]
```

Looking at the atlas site (https://vagrantcloud.com/ubuntu/boxes/precise64), I see that ubuntu/precise64 does not support the vmware_fusion provider.  Using hashicorp/precise64 (https://vagrantcloud.com/hashicorp/boxes/precise64) instead does work.  So I changed the Vagrantfile to:

```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define "development", autostart: false do |dev|
        dev.vm.box = "hashicorp/precise64"
        dev.vm.provider "vmware_fusion" do |v|
            v.memory = 512
        end

        dev.vm.provision "ansible" do |ansible|
            ansible.playbook = "vagrant-provision.yml"
        end
    end
end
```

Now `vagrant up development` works:

```
$ vagrant up development
Bringing machine 'development' up with 'vmware_fusion' provider...
==> development: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
    development: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    development: Box Version: >= 0
==> development: Loading metadata for box 'hashicorp/precise64'
    development: URL: https://atlas.hashicorp.com/hashicorp/precise64
==> development: Adding box 'hashicorp/precise64' (v1.1.0) for provider: vmware_fusion
    development: Downloading: https://vagrantcloud.com/hashicorp/boxes/precise64/versions/1.1.0/providers/vmware_fusion.box
==> development: Successfully added box 'hashicorp/precise64' (v1.1.0) for 'vmware_fusion'!
==> development: Cloning VMware VM: 'hashicorp/precise64'. This can take some time...
==> development: Checking if box 'hashicorp/precise64' is up to date...
==> development: Verifying vmnet devices are healthy...
==> development: Preparing network adapters...
==> development: Starting the VMware VM...
==> development: Waiting for machine to boot. This may take a few minutes...
    development: SSH address: XX.XX.XX.XX:22
    development: SSH username: XXXX
    development: SSH auth method: private key
    development:
    development: Vagrant insecure key detected. Vagrant will automatically replace
    development: this with a newly generated keypair for better security.
    development:
    development: Inserting generated public key within guest...
    development: Removing insecure key from the guest if its present...
    development: Key inserted! Disconnecting and reconnecting using new SSH key...
==> development: Machine booted and ready!
==> development: Forwarding ports...
    development: -- 22 => 2222
==> development: Configuring network adapters within the VM...
==> development: Waiting for HGFS kernel module to load...
==> development: Enabling and configuring shared folders...
    development: -- /Users/XXXXX/XXXX/XXXXX: /vagrant
==> development: Running provisioner: ansible...
```


Certainly not related to the original post, but thought it might help others...

**Comment by fiorix** [comment]
Yeah that works but we want trusty, not precise. I'm already regretting the vmware plugin, it's pretty much useless since most boxes are for the default vbox provider.

**Comment by chasrmartin** [comment]
I'm having similar problems.  now that I've installed the vmware provider, vagrant always wants to use vmware unless I use the --provider flag explicitly.

It'd be nice to be able to set a default provider so I do'nt go through a lot of false starts.

**Comment by stackedsax** [comment]
@chasrmartin you can set a default provider.  Just add this to your .bashrc or whatever:

export VAGRANT_DEFAULT_PROVIDER=virtualbox # chooses virtualbox as the default provider

Hope that helps.

**Comment by ijstokes** [comment]
I have solved this problem either with
```
export VAGRANT_DEFAULT_PROVIDER=virtualbox
```
environment variable or by using the CLI flag:
```
vagrant up --provider virtualbox
```
however it is very surprising to me that my `Vagrantfile` setting is not sufficient:
```
  config.vm.provider "virtualbox"
```

Can anyone comment?

**Comment by chasrmartin** [comment]
I had some success with this code fragment:

Vagrant.configure(2) do |config|

  # Prefer virtualbox,
  # see https://docs.vagrantup.com/v2/providers/basic_usage.html
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end

  # Not tested with VMWare yet. VMWare requires a vagrant plugin.
  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
  end

but didn't explore it further because I wasn't happy with Vmware anyway so
uninstalled the plugin.

**Comment by jloomb** [comment]
+1 I (guessing it wasnt intentional) used to be able to vagrant up without --provider=*. I have a complex multi machine/provider Vagrantfile which was using the defined provider?? Sorry cant recall which version I was on at the time.

**Comment by jtreminio** [comment]
If anyone has any trouble with this, add the following to the top of your `Vagrantfile`:

`ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'`

**Comment by gildegoma** [comment]
@chrisroberts I have verified (with Vagrant 1.8.7 and vagrant-vmware-fusion 4.0.14). The issue is still present: By default, the VMware provider is automatically selected (even if the base box does not support it).

**Comment by chrisroberts** [comment]
@gildegoma Okay, thanks for the confirmation! I'll have a look today and see if it's something that can be easily fixed up.

**Comment by chrisroberts** [comment]
After getting this reproduced locally, it is "partially" fixed based on expectations described within this issue. #7756 fixed the provider selection when "hinted" by the `Vagrantfile`. This means that:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = 'hashicorp/precise'
end
```

will result in a provider of `vmware`. If we hint the provider:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = 'hashicorp/precise'
  config.vm.provider :virtualbox 
end
```

this will result in `virtualbox` as the provider. This still doesn't help for a box that doesn't support the selected provider, so I'm digging into that.

**Comment by chrisroberts** [comment]
The modifications required for doing detection on the box metadata to choose a supported provider is much more intensive than the benefit gained. If anyone wants to provide a PR for it, I will be happy to help with reviews and guidance. At this point, however, the changes required are too drastic for a small gain where setting the provider explicitly via CLI flag or defaulting it via env var is easy enough. Cheers!
