### ISSUE TITLE
VMWare Plugin Breaks Vagrant Destroy

### ISSUE THREAD

**Issue by uchagani** [mitchellh/vagrant#4656]
If you bring up a VirtualBox machine with the ```--provider=virtualbox``` flag after you install VMWare Workstation plugin, ```vagrant destroy``` no longer works.  Vagrant tells you that you have to bring up a machine first before you can destroy it.

Workaround
------------------
Run ```vagrant destroy [machine name]```

**Comment by sethvargo** [comment]
I can't reproduce this either - can someone provide a minimal `Vagrantfile` that causes this to occur?

**Comment by uchagani** [comment]
So I can reproduce this at will but it is slightly different than what I originally posted.  

Vagrantfile:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.define "box1" do |box|
		box.vm.box = "ubuntu/trusty64"
	end
  
  	config.vm.define "box2" do |box|
		box.vm.box = "ubuntu/trusty64"
	end
end

```

Steps to reproduce:

```ruby 
vagrant up box1
```

```ruby
vagrant destroy -f
```

Expected Result:  Vagrant will destroy any running VMs (```box1```)

Actual Result:  Vagrant error: ```VM must be created before running this command. Run `vagrant up` first.```


```vagrant status``` produces:
```
Current machine states:

box1                      running (virtualbox)
box2                      not created (vmware_workstation)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

**Comment by uchagani** [comment]
Here's the log for the ```destroy``` command:  https://gist.github.com/uchagani/1d74aa067ab6db749ae2

**Comment by xacaxulu** [comment]
+1

**Comment by feliksik** [comment]
+1; I don't even know a workaround.

**Comment by mitchellh** [comment]
Fixed

**Comment by wisq** [comment]
Does this also fix the issue that `vagrant destroy -f` (with or without a box name) throws an error if the box is not running?  (Virtualbox instances just say "not created, moving on".)

Do I need to upgrade vagrant for this fix, or just the vmware-fusion plugin?  Or do I need to wait for the next release of one or the other?  (I just made the switch from virtualbox to vmware and this has been bugging me a lot since I do a lot of `vagrant destroy -f && vagrant up`.)
