### ISSUE TITLE
config.vm.box_download_checksum ignored since Vagrant 1.5.0

### ISSUE THREAD

**Issue by andreaso** [mitchellh/vagrant#4665]
Appear as if the config.vm.box_download_checksum Vagrantfile option has been ignored since Vagrant 1.5.0

Based on this Vagrantfile, with a fake checksum.

    config.vm.box = "anlashok/wheezy64"
    config.vm.box_url = "http://10.42.47.42/anlashok_wheezy64.box"
    config.vm.box_download_checksum_type = "sha256"
    config.vm.box_download_checksum = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

Using Vagrant 1.4.3 I get this expected failure.

    andreas@corrino:~/workdir/anlatest$ vagrant --version
    Vagrant 1.4.3
    andreas@corrino:~/workdir/anlatest$ vagrant up 
    Bringing machine 'default' up with 'virtualbox' provider...
    [default] Box 'anlashok/wheezy64' was not found. Fetching box from specified URL for
    the provider 'virtualbox'. Note that if the URL does not have
    a box for this provider, you should interrupt Vagrant now and add
    the box yourself. Otherwise Vagrant will attempt to download the
    full box prior to discovering this error.
    Downloading box from URL: http://10.42.47.42/anlashok_wheezy64.box
    Calculating and comparing box checksum...ime remaining: --:--:--)
    The checksum of the dowloaded box did not match the expected
    value. Please verify that you have the proper URL setup and that
    you're downloading the proper file.
    
    Expected: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
    Received: 31ce372eb5c238f732603343c5c5da7b4beaa9aaadf3b695ddee224c3552d28e
    andreas@corrino:~/workdir/anlatest$ 

While Vagrant 1.5.0 happily downloads and runs the imagine without caring about the checksum being wrong.

    andreas@corrino:~/workdir/anlatest$ vagrant --version
    Vagrant 1.5.0
    andreas@corrino:~/workdir/anlatest$ vagrant up 
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Box 'anlashok/wheezy64' could not be found. Attempting to find and install...
        default: Box Provider: virtualbox
        default: Box Version: >= 0
    ==> default: Adding box 'anlashok/wheezy64' (v0) for provider: virtualbox
        default: Downloading: http://10.42.47.42/anlashok_wheezy64.box
    ==> default: Successfully added box 'anlashok/wheezy64' (v0) for 'virtualbox'!
    ==> default: Importing base box 'anlashok/wheezy64'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Setting the name of the VM: anlatest_default_1413739882401_47235
    ==> default: Fixed port collision for 22 => 2222. Now on port 2202.
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
    ==> default: Forwarding ports...
        default: 22 => 2202 (adapter 1)
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2202
        default: SSH username: vagrant
        default: SSH auth method: private key
        default: Error: Connection timout. Retrying...
    ==> default: Machine booted and ready!
    ==> default: Checking for guest additions in VM...
    ==> default: Mounting shared folders...
        default: /vagrant => /home/andreas/workdir/anlatest
    andreas@corrino:~/workdir/anlatest$

This being under Ubuntu 14.10, with the following ruby version

    andreas@corrino:~/workdir/anlatest$ ruby --version
    ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
    andreas@corrino:~/workdir/anlatest$

Also reported on the mailing list by another user: https://groups.google.com/d/msg/vagrant-up/Cv_CRxciH5M/q8K8YuLhZOkJ

**Comment by simonvetter** [comment]
Any updates on this? This bug seems pretty bad.
