### ISSUE TITLE
Virtualbox NetworkDHCPAlreadyAttached error

### ISSUE THREAD

**Issue by maspwr** [mitchellh/vagrant#4692]
This is an issue in Vagrant 1.6.5.

This line, https://github.com/mitchellh/vagrant/blob/3b2e3b6a69953e5e91a8b14c76d8eaacadaec648/plugins/providers/virtualbox/action/network.rb#L328, checks to see if a DHCP server is attached with:

```ruby
if interface[:dhcp]
```

That hash seems to always exist even if the DHCP server itself is disabled. In my case DHCP is disabled, and the `interface` variable at that point in the code equals:

```ruby
{:name=>"vboxnet1", :ip=>"172.16.177.1", :netmask=>"255.255.255.0", :status=>"Up", :dhcp=>{:network=>"vboxnet1", :ip=>"0.0.0.0", :lower=>"0.0.0.0", :upper=>"0.0.0.0"}}
```

Obviously those values are bogus defaults which then causes Vagrant to raise a `NetworkDHCPAlreadyAttached` error.

I think you want to check that DHCP is actually enabled before doing this check, however I don't know where that information is available since it doesn't show up in the `interface` variable.

A workaround for anyone experience this issue is to enable the DHCP server for that network, put in valid parameters in Virtualbox for that host only network, and then disable the DHCP server again.

**Comment by mitchellh** [comment]
This is fixed

**Comment by bsholdice** [comment]
@maspwr sorry to dig this closed issue. I see this error in vagrant 1.9.2 when trying to get a virtualbox vm to bring up an interface on a pre-existing hostonlyif w/ dhcpserver. It looks like the `if interface[:dhcp]` logic sees my existing dhcpserver config but wants to overwrite it, leading to the `NetworkDHCPAlreadyAttached` error.. am I missing some way to make this happen?
