### ISSUE TITLE
Vagrant ssh translates LF to CR

### ISSUE THREAD

**Issue by staticshock** [mitchellh/vagrant#4718]
Not sure what exactly is going on here, but I'm seeing a weird behavior with newlines:

```
$ x=$(vagrant ssh -c "echo 1234"); echo "${x}ab"
Connection to 127.0.0.1 closed.
ab34
```

The guest is linux, the host is OS X. The guest `echo` ends the line with `\n`, however what's captured in `$x` is `\r`.

**Comment by sethvargo** [comment]
Hi @staticshock 

`vagrant ssh` just wraps the default system SSH to execute commands. I just tried doing the same command with straight-SSH on a mac->unix system and got the same result :frowning:. I did some googling and it looks like this is pretty common. 

Originally I thought we could fix this in Vagrant by detecting the host OS, guest OS, and then doing some magic, but I think some users might _want_ the carriage return for various reasons. Instead, we are going to encourage users to manage this manipulation on their own. Thanks!

**Comment by chino** [comment]
I'm on OSX using linux VMs and never ran into this issue before. It does not happen for me with normal ssh but does via vagrant ssh:

```
$ vagrant ssh test1 -c echo  | hexdump
Connection to 127.0.0.1 closed.
0000000 0d 0a
0000002

$ vagrant ssh-config test1 >> ~/.ssh/config

$ ssh test1 echo | hexdump
0000000 0a
0000001
```

**Comment by zen-devconsoft** [comment]
See GH-8040. Work around available by disabling creation of pseudo-tty.
`vagrant ssh -c echo -- -T | hexdump`
