### ISSUE TITLE
vagrant+dockerfile+shell  provisioning hangs up on windows 8....narrowed it down to dos2unix

### ISSUE THREAD

**Issue by Neetuj** [mitchellh/vagrant#4719]
Rhis is my `Vagrantfile`:

```ruby
Vagrant.configure("2") do |config|
  config.vm.define "app" do |app|
    app.vm.provider "docker" do |d|
      d.build_dir = "."
      d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
    end
  end
  config.ssh.username = "root"
  config.ssh.private_key_path = "insecure_key"
end
```

This is my `Dockerfile`

```
FROM phusion/baseimage:0.9.15
MAINTAINER neetu

ENV HOME /root
RUN mkdir /buzzbuild
ADD . /buzzbuild
RUN apt-get update  && apt-get install -y -q dos2unix
RUN cd /buzzbuild/ && dos2unix *.sh && chmod 777 install.sh && sh install.sh
CMD ["/sbin/my_init"]
EXPOSE 80 443 5000 15672
```

so as you can see .. 1) i am adding my buidl directory(.) to /buzzbuild 2) and am running a install script there (after i CD into that dir)

the contents of the install script are :-

```shell
#!/bin/sh
apt-get update
apt-get install -y -q git
```

when i do "vagrant up" is hangs on " building container" 
I have narrowed it to "dos2unix  *.sh"

if i don't add above ..i run into the line ending issue and the install scrip fails..

any suggestions on how to get around the line-end issue and not get stuck builindg  container? is this a bug?? any solutions

**Comment by sethvargo** [comment]
Hi @Neetuj 

Thank you for opening an issue. This seems like more of a Docker or usage-based question. Could you please ask this on the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up)?
