### ISSUE TITLE
Support for native rsync --exclude-from option

### ISSUE THREAD

**Issue by sandrokeil** [mitchellh/vagrant#4724]
I want to write my list of excluded files/directories in a file e.g. rsync_push.txt instead of using the rsync__exclude option. Other rsync options are supported but here i get the following error:

```
Error: rsync: --exclude-from "./rsync_push.txt": unknown option 
rsync error: syntax or usage error (code 1) at main.c(1443) [client=3.0.7]
```

My synced_folder definition:
```
# rsync folder
config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true, rsync__args: ["--exclude-from \"rsync_push.txt\"", "-z", "--copy-links", "--chmod=ugo=rwX", "-h", "-vv", "-r", "-p", "-t"]
```

If i call rsync manually it works fine. I used vagrant 1.6.5 in linux.

**Comment by mitchellh** [comment]
Separate the args in `__args`: `["--exclude-from", "rsync_push.txt"]`

We expect `exec()` like format.
