### ISSUE TITLE
vagrant-vmware-fusion plugin fails to chown/chmod sudo wrapper

### ISSUE THREAD

**Issue by BlakeMesdag** [mitchellh/vagrant#4728]
A recent addition which closed #2912 by using `osascript` to grant administrative privileges to chown and chmod the sudo wrapper has broken initial installation of the `vagrant-vmware-fusion` plugin over ssh for me.

Is there a way to get the command to fallback to using `sudo` for this? Currently we have a couple Mac Mini's in a server rack for testing provisioning on new systems and I've been forced to use screen sharing to install the plugin.

**Comment by phinze** [comment]
Hey folks - want to give `vagrant-vmware-fusion` 3.2.1 a try? It should have a fix for this. :+1: :zap:
