### ISSUE TITLE
Add fig provisioning

### ISSUE THREAD

**Issue by rvillars** [mitchellh/vagrant#4732]
Based on the provisioning for "docker" it would be nice to see "fig" provisioning (http://www.fig.sh/).

Instead of a manual definition of the to be created docker images in Vagrantfile, it just references a fig.yml file. Vagrant could then just parse the fig.yml and build all the defined docker images in the vagrant VM.

This would be a nice platform independent way to build up whole development infrastructures based on docker.

**Comment by mitchellh** [comment]
fig.yml is gone but will look into compose
