### ISSUE TITLE
Vagrant doesn't persist Gemfile / Gemfile.lock between invocations

### ISSUE THREAD

**Issue by aspiers** [mitchellh/vagrant#4737]
As [previously noted](https://github.com/mitchellh/vagrant/issues/4411#issuecomment-54313309), it seems that every time Vagrant runs certain subcommands, it generates a temporary file acting as a `Gemfile`, then runs `bundle install` creating another temporary file acting as a  `Gemfile.lock`.  The result is firstly that over time `/tmp` fills up with loads of temporary files:

```
$ ls /tmp/vagrant* | wc -l
2579
```

and secondly that the lack of a persistent `Gemfile.lock` (i.e. with stable name) results in [`vagrant plugin install` being unreliable](https://github.com/mitchellh/vagrant/issues/4411#issuecomment-54644314).  Couldn't Vagrant easily solve these problems by persisting `Gemfile` and `Gemfile.lock` (e.g. somewhere under `~/.vagrant.d`) ?  A nice side effect of this is that it would be possible for `vagrant plugin install` / `update` to report the changes in versions it results in.

**Comment by chrisroberts** [comment]
Related: #7793

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
