### ISSUE TITLE
Cache download and check free space before unpacking

### ISSUE THREAD

**Issue by techtonik** [mitchellh/vagrant#4741]
If Vagrant 1.6.5 fails to unpack box, it tries to redownload it again, which takes time. To repeat just leave free space just for downloaded box and run `vagrant up`.

```
> vagrant up
...
==> default: Adding box 'gratipay' (v0) for provider: virtualbox
    default: Downloading: https://downloads.gratipay.com/gratipay.box
    default: Progress: 100% (Rate: 373k/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x ./box-disk1.vmdk: Write failed
x ./box.ovf: Write failed
x ./Vagrantfile: Can't create '\\\\?\\C:\\Users\\user\\.vagrant.d\\tmp\\vagrant-box-add-temp-20141029-9652-1a1p6jv\\Vagrantfile'
bsdtar.EXE: Error exit delayed from previous errors.
```

**Comment by sethvargo** [comment]
Hi @techtonik 

Thank you for opening an issue. I'm not sure I understand your desired behavior here. If Vagrant fails to unpackage the box, it means the box file is invalid, so it has to try to redownload. What alternative behavior were you expecting?

**Comment by techtonik** [comment]
The reason in this case is that there was not enough disk space. Instead of waiting 4 hours for it to fail, it could warn about insufficient space immediately. Also the space was insufficient for unpacking, so the box file is okay.

**Comment by sethvargo** [comment]
Hi @techtonik 

In most cases, Vagrant won't know how big the file is before downloading it. _Some_ web servers might report the total file size, but that can be inaccurate. Additionally, because boxes are compressed, there's no way for Vagrant to know what the expanded file size is going to be after expansion.

**Comment by techtonik** [comment]
>  because boxes are compressed, there's no way for Vagrant to know what the expanded file size is going to be after expansion.

What? Is it the mis-feature of tar.gz? Because I believe both .zip and .7z can get this info no problem.

Anyway, "insufficient disk space" and "corrupted archive" are two different errors, and archive should not be removed and redownloaded just because there is insufficient space to unpack it.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
