### ISSUE TITLE
Plugin installation fails behind firewall

### ISSUE THREAD

**Issue by robkinyon** [mitchellh/vagrant#4748]
Because of the default sources (rubygems and gems.hashicorp), `vagrant plugin install` fails if either of those are completely unreachable, such as behind a corporate firewall. We have our own rubygems repository that we host plugins (both internally-developed and external ones we've done intake on) and we need a way of saying "Only use our source - don't use defaults".

I've submitted PR #4738 to address this.

**Comment by athingisathing** [comment]
For example... this code ignores the configuration of gem through gemrc.  In our corp environment we force gem local only and remove rubygems from sources.  So I would see and if statement that checks for .gemrc controlling gem and does not mess with gem it that is the case.

    def build_gemfile(plugins)
      sources = plugins.values.map { |p| p["sources"] }.flatten.compact.uniq

      f = File.open(Tempfile.new("vagrant").path + "2", "w+")
      f.tap do |gemfile|
        if !sources.include?("http://rubygems.org")
          gemfile.puts(%Q[source "https://rubygems.org"])
        end

        gemfile.puts(%Q[source "http://gems.hashicorp.com"])
        sources.each do |source|
          next if source == ""
          gemfile.puts(%Q[source "#{source}"])
        end

**Comment by alexpop** [comment]
+1

**Comment by tfitch** [comment]
I've seen this block plugin installation for one of my customers behind a proxy.  Would be great to see it merged.

**Comment by scottmiddleton2** [comment]
+1

**Comment by drcraig** [comment]
+1 

This is currently blocking our use of Vagrant on the most restricted part of our network. I've tried everything I can think of to make it use our internal rubygems mirror, but to no avail. 

Here's what I've tried so far:
* Setting sources in gemrc to our mirror and putting that gemrc in `~/.gemrc`, `/root/.gemrc`, and `/opt/vagrant/embedded/etc/`
* Adding our mirror and removing the others
  ```
  /opt/vagrant/embedded/bin/gem source --add https://our.mirror
  /opt/vagrant/embedded/bin/gem source --remove http://rubygems.org
  /opt/vagrant/embedded/bin/gem source --remove http://gems.hashicorp.org
  ```

* Using the `--plugin-source` option
* Installing `rubygems-mirror` like so `/opt/vagrant/embedded/bin/gem install --install-dir ~/.vagrant.d/gems/ ../rubygems-mirror-1.0.1.gem`
* Setting up a .mirrorrc file and putting it in `~/.gems/.mirrorrc` and `/root/.gems/.mirrorrc`


Nothing works. It still tries to talk to gems.hashicorp.com. Is there really no solution for this?

**Comment by athingisathing** [comment]
What i ended up doing is writing a simple find and replace in all of hashi
corp... for the two gem locations and replacing them with our url. This is
the only thing that worked because of how the code is written to ignor
gemrc and to hardcode rebygems.org. This means that even if you pass it in
a source you will fail because it will not be able to reach rubygems that
is hard coded.

hope this helps.

you can rind how the code works by looking for rebygems.org and reading the
files with that in it.

**Comment by alexpop** [comment]
@drcraig, I did it by patching lib/vagrant/bundler.rb and commenting out these lines:

```ruby
        if !sources.include?("http://rubygems.org")
          gemfile.puts(%Q[source "https://rubygems.org"])
        end

        gemfile.puts(%Q[source "http://gems.hashicorp.com"])
```

and then using --plugin-source:

```
vagrant plugin install vagrant-winrm --plugin-source https://my-rubygems-server
```

**Comment by drcraig** [comment]
@alexpop yup, that almost exactly what I ended up doing, except that I left the second puts call in, but replaced gems.hashicorp.com with my mirror URL. Felt icky, but I guess it's not much different than having to append a CA certificate to the embedded cacerts.pem file, a la https://github.com/mitchellh/vagrant/issues/5458.

**Comment by robkinyon** [comment]
Until the associated PR (or something similar) is merged, you can use the following script. It will:
0. Fetch the plugin file
0. Install all of its dependencies
0. Install the plugin file

This assumes you have all of the appropriate dependencies and the plugin gem in your gem repository behind your firewall and that `gem` has the appropriate sources set.

```ruby
#!/usr/bin/env ruby

require 'tmpdir'

plugin = ARGV.shift
abort "Must provide a plugin name" unless plugin

Dir.mktmpdir do |dir|
  Dir.chdir(dir) do
    puts "Fetching #{plugin}"
    system "gem fetch #{plugin}"
    puts "Resolving dependencies for #{plugin}"
    deps = %x{gem dependency #{plugin} -r}.split(/\n/).collect {|x|
      match = x.match(/^  ([\w-]+)\s+\(([\d.>=~< ]+)\)/)
      if match
        [ "#{match[1]} -v '#{match[2]}'" ]
      else
        nil
      end
    }.compact
    unless deps.empty?
      puts "Installing dependencies for #{plugin}"
      system "gem install #{deps.join(' ')}"
    end
    system "vagrant plugin install #{plugin}*.gem"
  end
end
```

**Comment by sethvargo** [comment]
Hi all,

There is now `--plugin-clean-sources`. Thanks!
