### ISSUE TITLE
Vagrant / VMWare Crashes on command: npm install

### ISSUE THREAD

**Issue by P-Hill-RCS** [mitchellh/vagrant#4754]
Hello!

I'm having a strange issue that I'm hoping you might be able to help me with:
I have a Vagrant (1.6.5) box based on Oracle Enterprise Linux running on a Mac: Yosemite with VMWare(7.0.1). When "npm install' is ran, the box becomes unreachable and every once in awhile I get a status of "Soft Lock". 

We've removed our npm and bower commands from our provisional steps and are now performing them manually to confirm the "npm install' command is the actual culprit, which it is.

I found a similar issue, <href url=https://github.com/mitchellh/vagrant/issues/2786>#2786</href>, relating to a VirtualBox instance that was being caused by a DNS issue. Have you had any reports of similar issues with a VMWare box?

I've added both my Vagrantfile and vagrant up --debug log to [This Gist](https://gist.github.com/P-Hill-RCS/e9bca4dd4b2c8d3f3286#file-vagrnatfile)
Any and all help you might be able to provide will be greatly appreciated as I'm not sure what else to do to try and fix this issue.

Thank You & Respectfully,
Patrick Hill

**Comment by sethvargo** [comment]
Hi there,

This is mostly likely not a bug in Vagrant and seems like an issue with your NPM/Node setup. In the future, please ask these types of questions on the mailing list and include a Vagrantfile to reproduce the issue and any debug output you may have.

**Comment by P-Hill-RCS** [comment]
My vagrantfile and debug data are in the Gist of my original comment.

**Comment by P-Hill-RCS** [comment]
For those also having this issue, if you're using rsync, try nfs, that's my next test once I get back to this project but as of right now, this issue is NOT resolved...
