### ISSUE TITLE
Packaging causes invalid state 'aborted'

### ISSUE THREAD

**Issue by salkinium** [mitchellh/vagrant#4755]
Using packer to build a VM from scratch using Ubuntu 14.04 Server on OSX 10.9.5 with VirtualBox 4.3.18 r96516 (newest to date) with some shell provisioners.
The build script is [available here](https://github.com/roboterclubaachen/rca-vm/blob/master/eurobot-vm.json).

After building I import the box into vagrant using `vagrant box add` and I am able to correctly start, suspend, stop, destroy it without hick-ups.

However, I have to do some configurations in Eclipse which cannot be scripted, and therefore I boot the machine using `vagrant up`, configure my things, and then repackage the box using `vagrant package` which works as expected.
I then reimport the new box using `vagrant box add`.

Then when I try to `vagrant up` the new box, it is imported into VirtualBox, and attempted to boot, but this is the output:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'aborted' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
```

The box is marked as `aborted` in VirtualBox too, but when I start the box using VirtualBox it simply starts without problem.
In that sense, nothing really breaks, but it is still pretty annoying, since I got used to the comfort of `vagrant up`, etc.

I was able to reproduce this problem every time, I even did a test run where I didn't change the original packer box, just `vagrant init`, `vagrant up`, `vagrant halt`, `vagrant package` without any impact on the result.
The output of running `VAGRANT_LOG=debug vagrant up` [can be found here](https://gist.github.com/salkinium/39a22f03eeeba54d94d9#file-gistfile1-txt-L2261).

I downgraded to VirtualBox 4.2.26 and tried it again but this changes nothing.
However, I could test `vagrant package` on hashicorp/precise64 which actually works as expected.
So I suspect it is some combination of our specific packer build and the manual configuration.

Ideas?

**Comment by mitchellh** [comment]
If the VM goes from starting to aborted, it  means that a setting in the VM is invalid. It is hard to tell what that is from the logs. Example: this would happen if you have 64-bit enabled and you're on a system that isn't 64-bit. That might not be it, but that is an example of what causes this. 

Please fiddle with settings on the VM and you'll get it, but its hard to figure out from here, and is likely not a Vagrant issue!
