### ISSUE TITLE
vagrant package doesn't add metadata

### ISSUE THREAD

**Issue by techtonik** [mitchellh/vagrant#4764]
`vagrant package` doesn't add metadata file for existing box that is being packaged.
```
vagrant package --output gratipay.box
```
Looking inside with `7z` I see only single `gratipay` file. `tar` shows more files - looks like something is wrong with archive format.
```
E:\p\gratipay-vagrant>tar -tvf gratipay.box
-rw-rw-rw- 0/0       392837120 2014-11-01 16:50 ./box-disk1.vmdk
-rw-rw-rw- 0/0           11614 2014-11-01 16:48 ./box.ovf
-rw-rw-rw- 0/0             516 2014-11-01 16:50 ./Vagrantfile
```

**Comment by mitchellh** [comment]
This is a feature. `vagrant package` is not used to manage metadata, it must be managed manually. 

Well, rather than a feature, this is just something that isn't supported yet and we don't plan to. The metadata is expected to be maintainted separately by something else.
