### ISSUE TITLE
[SECURITY] too easy to accidentally expose forwarded ports on the network

### ISSUE THREAD

**Issue by aspiers** [mitchellh/vagrant#4768]
I wanted to lock down my port forwards so that they were only accessible from the host machine, not other machines on the same network.

First I made the mistake of thinking that when forwarding ports, `host_ip` could be a hostname like `localhost`.  But neither Vagrant nor VirtualBox did any validation on this value, so the end result was that the ports got exposed on the network even though I thought I'd made them secure.

So I have two suggestions:

1. Make `127.0.0.1` the default for `host_ip`, in the same way that `ssh`'s `GatewayPorts` setting defaults to `no`).  I think the risk of someone accidentally exposing ports is too high to justify leaving it as is.
2. Even though VirtualBox failed to throw an error when passed a forwarding rule with an invalid value, it would be great if Vagrant could do some validation on the values.  Of course it's very easy to check that a string represents a valid IP or port number, so IMHO it makes sense to do it.

**Comment by mitchellh** [comment]
I'm in favor of option 1.

**Comment by sethvargo** [comment]
I'm in favor of 1 as well, but I think we need to point this out in the README as a potential breaking change. I can imagine a situation where user's are depending on the existing behavior, much like the old "v in front of the version" way back when. We should still change this for sure, but we just need to make sure users are aware of the change.

**Comment by mitchellh** [comment]
@sethvargo Yeah, we'll put in the backwards incompat section. There is a very reasonable use case for this non-default which is that forwarded ports historically have worked well for testing on mobile devices in the case where a public network is too heavy duty. So we need to make it clear what is happening. But nowadays there are a lot of options to work around this so I think its safe make option 1 a new default.

**Comment by mitchellh** [comment]
This was done for 1.7.x! By default SSH binds to 127.0.0.1.
