### ISSUE TITLE
Creating new machine if vagrant is used by different user

### ISSUE THREAD

**Issue by nerdbynature** [mitchellh/vagrant#4771]
vagrant files are created and run under the user test.
if you (accidentally) start your vm's as root user a new vm will be created. The old one is no longer accessible by vagrant.

If you are using Virtualbox this issue could be resolved by removing the new machine and find the UUID of the good one with VBoxmanage list vms and overwrite the id file in the .vagrant directory.

**Comment by mitchellh** [comment]
Fixed in master with an error!
