### ISSUE TITLE
Retire the old downloads page

### ISSUE THREAD

**Issue by jphalip** [mitchellh/vagrant#4773]
It looks like this page is out of date: http://downloads.vagrantup.com/

This can be confusing for some users, especially since it comes up pretty high in Google search results for queries like ["download vagrant"](https://www.google.com/search?q=download+vagrant).

I suggest either retiring that page entirely, or perhaps making it redirect it to the new page: https://www.vagrantup.com/downloads.html

**Comment by yshahin** [comment]
Shouldn't this be closed? was the download page moved?

**Comment by sethvargo** [comment]
Yup thanks
