### ISSUE TITLE
Import fails when existing VirtualBox VM contains Japanese characters. 

### ISSUE THREAD

**Issue by cstorey** [mitchellh/vagrant#4778]
Similarly to #3706, when running Vagrant 1.6.5, I'm seeing `vagrant up` fail. 

When the output of VBoxManage list VMs includes

    "Foo " {0bb1294f-a33f-49e7-a934-34c88aeb9700}
    "Bar よくわからないなにか" {e87101ee-4e9c-45ca-a23f-948754b5c36e}

Then vagrant seems to read this in as (according to VAGRANT_LOG=debug):

    "Foo " {0bb1294f-a33f-49e7-a934-34c88aeb9700}
    "Bar 

Where "Bar " is truncated. Because the newly imported VM tends to be added as the last entry in this list, Vagrant doesn't see the name listed, and assumes the import failed.

Adding a few instances of `.tap { |x| STDERR.puts x.inspect }` to `vagrant/util/io.rb`; it looks like, the non-ascii input just isn't getting read, never mind incorrectly decoded.

**Comment by mitchellh** [comment]
Vagrant currently doesn't work well with encodings and international characters. We're slowly fixing all the bugs related to this but there is a meta-issue tracking this somewhre with a fairly low issue number since it has been ongoing. Going to close this for that please use search to find it.
