### ISSUE TITLE
bundled curl doesn't use certs in Mac OS X keychain

### ISSUE THREAD

**Issue by pmenglund** [mitchellh/vagrant#4782]
I'm have a box in vagrant cloud, where only the meta data is hosted, and the box is hosted on a server with a cert signed by my own cert ca.

When I use the home brew installed `curl` it works as expected:
```
vaccine:packer englund$ curl -I https://jenkins.company.com/boxes/fb-ubuntu-14.04.box
HTTP/1.1 200 OK
Server: nginx/1.1.19
Date: Tue, 04 Nov 2014 22:50:53 GMT
Content-Type: application/octet-stream
Content-Length: 721288993
Last-Modified: Tue, 04 Nov 2014 22:25:30 GMT
Connection: keep-alive
Accept-Ranges: bytes
```

But when the bundled `curl` is used, it doesn't use the Keytool:
```
vaccine:packer englund$ /Applications/Vagrant/embedded/bin/curl -I https://jenkins.company.com/boxes/fb-ubuntu-14.04.box
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

```
vaccine:packer englund$ vagrant version
Installed Version: 1.6.5
Latest Version: 1.6.5

You're running an up-to-date version of Vagrant!
```

**Comment by sethvargo** [comment]
Hi all,

After some pretty extensive research, this is not possible. We install curl as part of Vagrant's installer and there **is no way to link that curl against the OS X keychain** (http://stackoverflow.com/questions/7439156/how-to-make-libcurl-look-in-the-mac-keychain-for-certificates). Apple uses a custom build of curl that is closed source that binds to the keychain.

In the future, we are going to move to a pure-Ruby downloader and uploader and probably remove curl from the bundle. Even in that situation, Ruby won't have access to the keychain either. In these cases, we are going to recommend users manually download the box outside of Vagrant and add it via `vagrant box add` with a filepath. Sorry!

**Comment by slushpupie** [comment]
Libcurl has had support for iOS/OSX "Secure Transport" for some time: http://daniel.haxx.se/blog/2012/06/28/darwin-native-ssl-for-curl/  You just need to compile with that instead of OpenSSL.  However, that wont address the problem if you replace curl with a pure-ruby downloader.
