### ISSUE TITLE
fpm bug causes `dpkg --verify` to error on vagrant deb packages

### ISSUE THREAD

**Issue by jordansissel** [mitchellh/vagrant#4783]
Summary:
*  fpm 0.4.42 through 1.3.0 had a bug where it incorrectly generated a deb md5sums file.
* packages built with fpm 0.4.42 through fpm 1.3.0 would, after user installation, cause `dpkg -V` package verification to fail on those packages
* a fix is released in fpm 1.3.2

I have verified the latest vagrant 64bit packages are impacted.

Details and remediation steps: https://github.com/jordansissel/fpm/wiki/FPM-1.3.2---deb-md5sums-bug-fix-notes

**Comment by mitchellh** [comment]
Will be fixed in the next release since we'll use the latest FPM
