### ISSUE TITLE
Can't load a local .box file

### ISSUE THREAD

**Issue by drocsid** [mitchellh/vagrant#4787]
From the vagrant documentation:

https://docs.vagrantup.com/v2/vagrantfile/machine_settings.html

config.vm.box_url
The URLs can also be local files by using the file:// scheme. For example: "file:///tmp/test.box"

Then, on my system:

>ls /opt/vagrant/boxes/CentOS-6.5-400.box 
`/opt/vagrant/boxes/CentOS-6.5-400.box`

>Vagrantfile
        `host.vm.box = "CentOS-6.5-400.box"
        config.vm.box_url = "file:///opt/vagrant/boxes/CentOS-6.5-400.box"`

Please update the documentation and or fix the bug regarding using local box files.

vagrant up
`Bringing machine 'nn01' up with 'virtualbox' provider...

==> nn01: Box 'CentOS-6.5-400.box' could not be found. Attempting to find and install...
    nn01: Box Provider: virtualbox
    nn01: Box Version: >= 0
==> nn01: Adding box 'CentOS-6.5-400.box' (v0) for provider: virtualbox
    nn01: Downloading: CentOS-6.5-400.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /opt/vagrant/CentOS-6.5-400.box`

**Comment by mitchellh** [comment]
This is now fixed
