### ISSUE TITLE
Syncing folder to a user directory breaks SSH

### ISSUE THREAD

**Issue by rvangundy** [mitchellh/vagrant#4791]
I've got a pretty custom setup going, so this might be outside the scope of vagrant, but I figured someone here might have some experience with this kind of thing...

I've built an Arch Linux base image. I would like to synchronize my project folder with a folder in the user's home directory, such as ```/home/vagrant/my_project```. If I mount it like this:

```
config.vm.synced_folder ".", "/home/vagrant/my_project"
```

I am no longer able to SSH in. I get the following response:

```
ssh_exchange_identification: Connection closed by remote host
```

I'm able to mount any other folder outside the user's directory just fine. The /vagrant mount works as expected.

I'm wondering if there's a security-related setting I'm missing that relates to folder permissions in a user's home directory? Since this is a vagrant-y issue, maybe others building vagrant boxes have encountered this.

**Comment by mitchellh** [comment]
Yes, @canausa is correct. We do some detection to detect this but it isn't 100%. Don't sync to your home folder. :)

**Comment by domenkozar** [comment]
Hmmm, unpleasant. Couldn't .ssh be installed/created after synced folders are mounted?

**Comment by nakulpathak3** [comment]
Ran into same issue today
