### ISSUE TITLE
Missing docker environment variables

### ISSUE THREAD

**Issue by pauldavidgilligan-msm** [mitchellh/vagrant#4793]
Installed Version: 1.6.5
Latest Version: 1.6.5
Docker version 1.2.0, build fa7b24f/1.2.0

I am running docker from vagrant and noticed both the default environment variables are missing and that also the docker -e option passed does not inject a variable too.

Do you have an example of the docker -e arument working wne provisioned from Vagrant please ?

I can't currently upgrade running centos6:latest.

**Comment by mitchellh** [comment]
This should all work now.
