### ISSUE TITLE
some hardcode error for vagrant 1.6.5 on windows 7

### ISSUE THREAD

**Issue by hick** [mitchellh/vagrant#4802]
there is no "C:/Users/Mitchell/" in my windows 7:

C:\Users\Administrator>vagrant
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
runtime.panic(0x4a6540, 0x59180a)
        C:/Users/Mitchell/code/3rdparty/go/src/pkg/runtime/panic.c:266 +0xa6
main.main()
        c:/Users/Mitchell/code/mitchellh/vagrant-installers/substrate/launcher/m
ain.go:35 +0x19d3

**Comment by sethvargo** [comment]
@hick this is not a hard-code error, just the stacktrace coming from Go. This should be fixed in Vagrant 1.7+
