### ISSUE TITLE
Network requirements that don't seem to work well with Vagrant

### ISSUE THREAD

**Issue by gkb** [mitchellh/vagrant#4805]
I'm dealing with a custom Centos box that won't work unless the first interface it's connected to is a bridged network linked to an ethernet connection as opposed to wireless.

But vagrant seems to want the first interface to be NAT. Otherwise the `vagrant ssh` command simply doesn't work. I discovered this when I tried to change the network interfaces directly through Virtualbox.

![First interface](https://dl.dropboxusercontent.com/s/cnv56sk3gk7r05s/Screen%20Shot%202014-11-09%20at%2010.16.03%20PM.png)

![Second interface](https://dl.dropboxusercontent.com/s/0ugtev47ctxtvg6/Screen%20Shot%202014-11-09%20at%2010.16.10%20PM.png)

How can I set the first interface to be the bridged network and not confuse Vagrant?

**Comment by sethvargo** [comment]
@gkb you can set the specific adapter to bridge to [as documented here](https://docs.vagrantup.com/v2/networking/public_network.html). In the future, please ask these types of questions on the Vagrant mailing list for a faster response.
