### ISSUE TITLE
NFS shared folder ownership does not change in guest OS

### ISSUE THREAD

**Issue by PaulAnnekov** [mitchellh/vagrant#4816]
I have the following Vagrantfile:

    ...
    config.nfs.map_uid = 33
    config.nfs.map_gid = 33
    
    config.vm.synced_folder "/home/test", "/home/test", type: "nfs"
    ...

After `vagrant up`, `/home/test` folder successfully mounted but uid=1000 and gid=1000 (1000 - owner of this folder on my host), are not 33. In host's `/etc/exports` everything looks good to me:

    "/home/test" 10.0.0.2(rw,no_subtree_check,all_squash,anonuid=33,anongid=33,fsid=2395053692)

**Vagrant version:** 1.6.5 

**Host OS:** Ubuntu 14.04.1 LTS 

**Guest OS:** Debian 6.0.9

It's a copy from stackexchange: http://unix.stackexchange.com/questions/167327/nfs-shared-folder-ownership-does-not-change-in-guest-os-in-vagrant

**Comment by jacobgraf** [comment]
This is affecting me too causing lots of permissions errors. Has anyone found a work-around in the meantime?

**Comment by petertornstrand** [comment]
Having the same problem.

Vagrant version: 1.4.3
Host OS: Ubuntu 14.04
Guest OS: Ubuntu 12.04

**Comment by mglaman** [comment]
Same issue, same specs as @petertornstrand

**Comment by petertornstrand** [comment]
@jacobgraf I'm using bindfs plugin for Vagrant to Sölve this issue.

**Comment by jacobgraf** [comment]
Interesting. I'll check it out. Thanks!

**Comment by petertornstrand** [comment]
https://github.com/gael-ian/vagrant-bindfs

**Comment by rmldsky** [comment]
Similar problem here. Host is **OSX 10.10**, guest is **Ubuntu 14.04**. **Vagrant 1.7.2**
```
  ## NFS Share
  config.vm.synced_folder ".", "/vagrant-nfs", type: "nfs"
  config.nfs.map_uid = 1000
  config.nfs.map_gid = 1000
```
/etc/exports on host (OSX):

```
"/Users/xxx/xxx/xxx" 192.168.33.10 -alldirs -mapall=1000:1000
```

**Comment by dominikzogg** [comment]
I am not sure, if this is the right issue, but it seems that trying to run my vagrant setup on a friends computer have similar problems. He got OSX 10.10 hosts. Some of shared files (images) got a preview on OSX finder, which doesn't work within the machine and conversely.

**Comment by mitchellh** [comment]
This is correct. it doesn't change the owner, it just changes the user that files are read/written as when they are accessed on the guest. You won't see any visible change in the guest.
