### ISSUE TITLE
Vagrant 1.6.5 requires bsdtar, not falling back to tar

### ISSUE THREAD

**Issue by h0g0f0g0** [mitchellh/vagrant#4817]
On OpenSUSE 13.1/13.2 when deploying SUSE Cloud demo vagrant fails with error:
![bsdtar_error](https://cloud.githubusercontent.com/assets/5442666/5007305/150b6bba-6a50-11e4-9615-4af973a07b7b.png)

It is supposed to fall back to tar (it is installed in /bin/tar), I guess. Process works after bsdtar package is installed.

**Comment by mitchellh** [comment]
Vagrant requires bsdtar and will not fall back to tar. The installers all include this. If you're on a system that doesn't have an official installer, you'll have to install bsdtar.
