### ISSUE TITLE
vagrant package: box contains everything except mysql data?

### ISSUE THREAD

**Issue by JeanMertz** [mitchellh/vagrant#4818]
*Maybe this is something that is documented somewhere, but so far my Google-fu has failed me.*

I have a Vagrantfile for an application that we manage at our company. We purchased some vagrantcloud.com seats for our organisation to distribute the box for this application easily.

However, when packaging the VM into a (VirtualBox) box format, I am running into an issue where the MySQL persistent data is somehow lost upon packaging.

The workflow I've tried:

* up/provision VM using a `Vagrantfile`. This file also creates and fills the database with the expected data
* log in using `mysql`, database exists and correct data is present
* use `vagrant halt` to stop machine
* use `vagrant up` to bring machine back up
* data still present as expected
* run `vagrant package --output my.box --vagrantfile Vagrantfile.box`
* use `vagrant destroy` and remove/rename current `Vagrantfile`
* use `vagrant init my.box && vagrant up`
* log in using `mysql` (on the VM), database is still present, but no tables/data exist?

Any reason why this is happening? I can't find any issue with my setup, is `box` doing something special with this data?

**Comment by sethvargo** [comment]
@JeanMertz can you please ask this question on the Vagrant mailing list? Thanks!
