### ISSUE TITLE
box lock files: two projects with the same box name cannot run operations at the same time

### ISSUE THREAD

**Issue by stelcheck** [mitchellh/vagrant#4822]
I have project 1, and project 2. Both have a box called "myInfra" defined in them. If in two separate terminal (one for each project), I try to:

```
> vagrant --version
Vagrant 1.6.5
>vagrant up myInfra
```

One of them will get locked out because the box name is the same. These lock currently seem to reside under `~/.vagrant.d/data`; shouldn't they be transferred under `[project]/.vagrant`?

**Comment by MiLk** [comment]
@sethvargo @mitchellh Do you want me to open a PR for that?
