### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication

### ISSUE THREAD

**Issue by 4eshircat** [mitchellh/vagrant#4826]
Hi there!
I'm trying to sync local folders to remote machine.
I'm running Vagrant 1.6.5 using DigitalOcean plugin on OS X 10.10 Yosemite.
And after I typed `vagrant reload` I get this message:

```
==> default: Rebooting the droplet...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

I have read this #2251 issue and also run this code:

```
vagrant plugin install --plugin-source https://rubygems.org --plugin-prerelease vagrant-vbguest
```

But I this message still appear. 
What could be the problem?

**Comment by sethvargo** [comment]
Closing due to lack of response.

**Comment by RafaelPlantard** [comment]
My environment is have a homestead to work with Laravel, but I'm using Vagrant Box, so I have this problem, the solution that I found was:

Works for me:

`vagrant reload --provision`

Inside the folder Homestead.

**Comment by Tazovsky** [comment]
I was struggling with this problem couple of days and what what helped me was:

```
rm -rf ~/.vagrant.d/
rm -rf .vagrant/
vagrant up --provider=virtualbox
vagrant plugin install vagrant-vbguest
vagrant vbguest --do install --no-cleanup
```

But I'm still not sure all steps are required and I'm not sure this will solve issue when problem occurs again...
