### ISSUE TITLE
Vagrantfile and Provisioning oddities

### ISSUE THREAD

**Issue by uchagani** [mitchellh/vagrant#4830]
This may be a provider issue but I think it's more a core vagrant problem.

##### Environment:
- Windows Host/Windows Guest
- VMWare Workstation Provider
- VirtualBox Provider (for testing purposes)

I have a PowerShell file that gets run with the shell provisioner.  This file exists in my base box location and gets copied to my project folder when I first run ```vagrant up```.  So far so good, everything working as expected.

##### VirtualBox Provider
When I edit the PowerShell script that is located in my project folder, the edited PowerShell file is ran when the machine is provisioned.  This, in my opinion, is the **correct** expected result.

##### VMWare Workstation Provider
When I edit the PowerShell script that is located in my project folder, the edited PowerShell file is **ignored** and the un-edited script from the base box location is ran instead.  This, in my opinion is a defect.  This means that in order for me to make changes to the provisioning script, I have to make the change in the base box location, which will apply to any new boxes created from the base box.  Not good.

Thoughts?

**Comment by mitchellh** [comment]
Can you show me the Vagrantfile of both the box and the system?

**Comment by uchagani** [comment]
Unfortunately I won't have time to get you want you need for this.  My steps to reproduce are clear and I can clarify anything else that you need.  Feel free to close this if you don't want to address it at this time.

**Comment by sethvargo** [comment]
Hi @uchagani 

Unfortunately without reproduction steps, we cannot debug this. If you are able to give us the Vagrantfile and the debug output, please open a new issue :smile:. Thanks and sorry!
