### ISSUE TITLE
Leaving guest path empty leads to an error

### ISSUE THREAD

**Issue by casr** [mitchellh/vagrant#4833]
From #936 it was recommended that with VirtualBox Shared Folders you could disable the auto mounting by Vagrant by blanking out the guest path. This is mentioned in the source here: 

https://github.com/mitchellh/vagrant/blob/v1.6.5/plugins/providers/virtualbox/synced_folder.rb#l54-l57

However, before we even get to that stage I'm coming up against a "guest path must be absolute" error over here:

https://github.com/mitchellh/vagrant/blob/v1.6.5/plugins/kernel_v2/config/vm.rb#l555-l557

What should I do?

(Some background: I'm trying to provision a box with Ansible. This sets up a user and I would like the Shared Folder mount to be owned by that user. So, like the referenced issue, this needs to be post the provisioning stage)

**Comment by sethvargo** [comment]
Hi @casr,

Please ask these types of questions on the Vagrant mailing list. Thank you!

**Comment by mitchellh** [comment]
Actually I think you're right this is a bug.

**Comment by mitchellh** [comment]
Fixed

**Comment by casr** [comment]
Fantastic! Thank you!
