### ISSUE TITLE
Custom Provider :parallel flag does not work for halt

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [mitchellh/vagrant#4836]
Hi,
If I write a custom provider that supports parallel actions, it works for the "vagrant up" command, but it does not work for the "vagrant halt" command. While looking at the code, I noticed that the halt command just does target_vms.each, but the up command does some additional work to enabled parallel start. 

Thanks
Anand V

**Comment by mitchellh** [comment]
This is fixed in master, will be in 1.7.3
