### ISSUE TITLE
rsync wrong folder on windows

### ISSUE THREAD

**Issue by tburschka** [mitchellh/vagrant#4837]
Hello,

EDIT:
After some time with this bug, playing around, it seems to me like a very strage bug.
Without running vagrant with debug it seems, that vagrant rsync is hanging... but it isn't...
(maybe same problem like #4819) , its syncing the wrong folder... its always using a parent folder (maybe base folder? ... i checked out project on

    /cygdrive/c/Users/Someone/Projects/myproject

and while vagran, which shows me gets the correct path!!! in rsync call, the directory

    /cygdrive/c/Users/Someone

is synced to the vm. Same on 

    /cygdrive/d/Projects/myproject

ended up in syncing

    /cygdrive/d/

I tested this with msys (git), mingw64, cygwin64 and cwrsync...

I've currently the issue, if the path given the rsync as source directory has an whitespace in it the path will be synced wrong:

    rsync --verbose --archive --delete -z --chmod=Du=rwx,Dgo=rwx,Fu=rwx,Fgo=rwx --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2200 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/Users/Some User/.vagrant.d/insecure_private_key' --exclude .vagrant/ --exclude composer.lock --exclude vendor --exclude .* /cygdrive/c/Users/Some User/Projects/myproject/public/symfony-box.local/ vagrant@127.0.0.1:/var/www

**Comment by cazzerson** [comment]
There seem to be several tickets (#5570, #6024, #6297, #4514) related to this issue. I'm having trouble creating a Vagrant machine on a network share in Windows (due mainly, I believe, to a failure to escape/covert path separators). As a start, should the bash fallback in cygwin_path() be applied to cygwin_windows_path()?

https://github.com/mitchellh/vagrant/blob/d7eaf503298014a93e1faa8da88947bc7d32ba58/lib/vagrant/util/platform.rb#L59-L92

In my case, I'm using Git Shell (PowerShell), not cygwin, on a Windows host so cygwin_windows_path() just returns the original path. bash is available, though.

**Comment by mitchellh** [comment]
I can't reproduce this anymore and I"ve been triaging a lot of rsync issues so this is likely fixed from a prior PR.
