### ISSUE TITLE
Random network drop

### ISSUE THREAD

**Issue by jakef** [mitchellh/vagrant#4838]
Howdy,

About half of my team is having a networking issue when trying to run `bundle install` from with in their development vagrant boxes. The easiest way to replicate the issue was to run `ssh github.com` which returns `ssh: Could not resolve hostname github.com: Name or service not known`. 

I can not replicate the error on my machine, but another engineer found a solution by adding `v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]` to their Vagrantfile. When I add that line, bundler throws the following warning with every gem: `warning: expected SRV RR, found RR type 1`

**Comment by sethvargo** [comment]
Hi @jakef 

Without a definite and stable reproduction case, this is very difficult to fix. It is also most likely an environmental issue on those engineer's machines. If you can get us some exact versions of Vagrant and VirtualBox to reproduce this issue and a Vagrantfile, we can re-open this to debug further.
