### ISSUE TITLE
Synced folders gone after resume

### ISSUE THREAD

**Issue by jasperreijer** [mitchellh/vagrant#4846]
My setup is a "box-cutter/centos65-desktop" box using Ansible as a provsioner. I suspended my machine. On resume the synced folder was missing. Did a reload and the folders were still gone.

**Comment by sethvargo** [comment]
@jasperreijer are you still able to reproduce this in Vagrant 1.7.2? Can you provide a Vagrantfile and any debug output please?

**Comment by sethvargo** [comment]
Closing due to no response. Please open a new issue if this is still happening and include the output in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html).
