### ISSUE TITLE
Document DNS proxy problems in common issues

### ISSUE THREAD

**Issue by techtonik** [mitchellh/vagrant#4853]
http://docs.vagrantup.com/v2/virtualbox/common-issues.html

This basically needs an explanation why `--natdnshostresolver1` is needed and why `--natdnsproxy1` may not be enough. In my case DHCP information is not refreshed with `--natdnsproxy1` when PC is brought from sleep and connected to another network.

More info:
http://serverfault.com/questions/453185/vagrant-virtualbox-dns-10-0-2-3-not-working

#4838 looks like a similar issue.

**Comment by sethvargo** [comment]
@techtonik would you like to submit a PR? The docs are all public and in this repo under `website/docs`.

**Comment by techtonik** [comment]
I am not an expert, so this needs a research on my side to provide accurate and up to date info. Given that I am researching LXC on Linux right now, this may never happen.

**Comment by mitchellh** [comment]
Fixed

**Comment by techtonik** [comment]
Awesome. =)
