### ISSUE TITLE
Vagrantfile version doesn't help to detect version compatibility problems

### ISSUE THREAD

**Issue by techtonik** [mitchellh/vagrant#4854]
Vagrant that is shipped with Ubuntu 14.04 is old 1.4+ and fails on Vagrantfiles produced with 1.6+:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings shouldn't exist: box_check_update, post_up_message
```
`Vagrantfile` version could allow previous versions of Vagrant to detect if the file is newer and propose to check and upgrade. New versions of Vagrant could propose to upgrade Vagrantfile version when they detect newer options.

**Comment by sethvargo** [comment]
@techtonik we are going to think about this, but please note that the recommend way to install Vagrant is via the official installers, not system-level packages. We do not create or maintain those packages and they quickly become out of date (causing problems such as these :smile:)

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to inactivity. Unfortunately I don't think there's much we can do in these cases (we can't backport an option that didn't exist in the past). Sorry! 😦

**Comment by techtonik** [comment]
@sethvargo Vagrantfile contains version. Vagrant should incremented this field when file uses newer features.
