### ISSUE TITLE
vagrant up --provider=docker is extremely slow

### ISSUE THREAD

**Issue by maspwr** [mitchellh/vagrant#4855]
Vagrant: `1.6.5` (also tested on dev version of `1.7.0`)

The built-in mechanism for determining when a container with ssh is ready appears to be broken. I can open another tab and `vagrant ssh` almost as soon as I see `==> app: Waiting for machine to boot. This may take a few minutes...`. However, `vagrant reload|up --provider=docker` polls for several minutes before deciding all is well.

See debug output here, https://gist.github.com/maspwr/d46a86e8fb8c1ebfc09b.

**Comment by mitchellh** [comment]
This should be fixed now
