### ISSUE TITLE
Windows Guest Doesn't Support SMB

### ISSUE THREAD

**Issue by ArtWDrahn** [mitchellh/vagrant#4857]
Running Vagrant up with the config.vm.synced_folder.  My host and guest are both Windows (host Windows 8.1, guest Server 2012 R2.  Not sure what else I can provide but I'm happy to give you anything you need.  I'm confused by this error only because the [documentation] (https://docs.vagrantup.com/v2/synced-folders/smb.html) clearly states this should work if both the host/guest are Windows (which they are)

    [4:39:32 PM] [0050] » vagrant up
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Importing base box 'kensykora/windows_2012_r2_standard'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Checking if box 'kensykora/windows_2012_r2_standard' is up to date...
    ==> default: Setting the name of the VM: windows2012_default_1416530705095_51315
    ==> default: Fixed port collision for 3389 => 3389. Now on port 2200.
    ==> default: Preparing SMB shared folders...
        default: You will be asked for the username and password to use for the SMB
        default: folders shortly. Please use the proper username/password of your
        default: Windows account.
        default:
        default: Username: tweak\tyson
        default: Password (will be hidden):
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
    ==> default: Forwarding ports...
        default: 3389 => 2200 (adapter 1)
        default: 22 => 2222 (adapter 1)
        default: 5985 => 55985 (adapter 1)
    ==> default: Running 'pre-boot' VM customizations...
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
    ==> default: Machine booted and ready!
    ==> default: Checking for guest additions in VM...
    ==> default: Mounting SMB shared folders...
    Vagrant attempted to execute the capability 'mount_smb_shared_folder'
    on the detect guest OS 'windows', but the guest doesn't
    support that capability. This capability is required for your
    configuration of Vagrant. Please either reconfigure Vagrant to
    avoid this capability or fix the issue by creating the capability.

Vagrant file:

    # The contents below were provided by the Packer Vagrant post-processor

    Vagrant.configure("2") do |config|
      config.vm.base_mac = "080027FE4F25"
    end

    # The contents below (if any) are custom contents provided by the
    # Packer template during image build.
    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    Vagrant.require_version ">= 1.6.2"

    Vagrant.configure("2") do |config|
        config.vm.define "vagrant-windows-2012-r2"
        config.vm.box = "windows_2012_r2"
        config.vm.communicator = "winrm"

        # Admin user name and password
        config.winrm.username = "vagrant"
        config.winrm.password = "vagrant"

        config.vm.guest = :windows
        config.windows.halt_timeout = 15

        config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
        config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

        config.vm.synced_folder ".", "/vagrant", type: "smb"

        config.vm.provider :virtualbox do |v, override|
            #v.gui = true
            v.customize ["modifyvm", :id, "--memory", 2048]
            v.customize ["modifyvm", :id, "--cpus", 2]
            v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
        end

        config.vm.provider :vmware_fusion do |v, override|
            #v.gui = true
            v.vmx["memsize"] = "2048"
            v.vmx["numvcpus"] = "2"
            v.vmx["ethernet0.virtualDev"] = "vmxnet3"
            v.vmx["RemoteDisplay.vnc.enabled"] = "false"
            v.vmx["RemoteDisplay.vnc.port"] = "5900"
            v.vmx["scsi0.virtualDev"] = "lsisas1068"
        end

        config.vm.provider :vmware_workstation do |v, override|
            #v.gui = true
            v.vmx["memsize"] = "2048"
            v.vmx["numvcpus"] = "2"
            v.vmx["ethernet0.virtualDev"] = "vmxnet3"
            v.vmx["RemoteDisplay.vnc.enabled"] = "false"
            v.vmx["RemoteDisplay.vnc.port"] = "5900"
            v.vmx["scsi0.virtualDev"] = "lsisas1068"
        end
    end

**Comment by sethvargo** [comment]
@johnkattenhorn @ArtWDrahn Vagrant 1.7.2 is out - does that help with this issue at all?

**Comment by ArtWDrahn** [comment]
Thanks can confirm that it's working for me!
