### ISSUE TITLE
mount_options overwrites other options

### ISSUE THREAD

**Issue by vsipuli** [mitchellh/vagrant#4858]
The Vagrant documentation on synced folders says: "mount_options (array) - A list of additional mount options to pass to the mount command." However, looking at the Vagrant code it looks like that option _overwrites_ other mount options:

```
	            if opts[:mount_options]
	              mount_opts = opts[:mount_options].dup
	            end
```

Shouldn't it append to the existing options (the documentation says "additional mount options"), instead of overwrite them as it seems to be doing above?

**Comment by mitchellh** [comment]
Docs problem, fixed.
