### ISSUE TITLE
Environment Variables and Multi-Machines

### ISSUE THREAD

**Issue by uchagani** [mitchellh/vagrant#4859]
Environment variables don't get re-sourced if you have a multi-machine environment made up of the same base box.

##### Vagrantfile:
```ruby
ENV['ADMIN_ROLES'] = "Admin"
ENV['CLIENT_ROLES'] = "Client"
adminHostname = 'blah-admin'
clientHostname = 'blah-client'

Vagrant.configure("2") do |config|
  config.vm.define "admin" do |admin|
    admin.vm.box = "MyBaseBox"
    admin.vm.hostname = adminHostname		
	ENV['OCTOPUS_ROLES'] = ENV['ADMIN_ROLES']
	
	admin.vm.provider "vmware_workstation" do |vm|	  
	  vm.name = admin.vm.hostname
	end	
  end 

  config.vm.define "client" do |client|        
    client.vm.box = "MyBaseBox"
    client.vm.hostname = clientHostname	
	ENV['OCTOPUS_ROLES'] = ENV['CLIENT_ROLES']
	
	client.vm.provider "vmware_workstation" do |vm|	  
	  vm.name = client.vm.hostname	 	  
	end
  end  
  
end
```

When the ```client``` VM is spun up, ```ENV['OCTOPUS_ROLES']``` still holds ```Admin``` when it should hold ```Client```

```ENV['OCTOPUS_ROLES']``` here is used by a shell provisioner in the Vagrantfile of the basebox.

Might be related to this warning:  

```
Warning: The inner portion of multi-machine definitions and provider overrides are lazy-loaded. This can cause issues if you change the value of a variable used within the configs. For example, the loop below does not work:
```

https://docs.vagrantup.com/v2/vagrantfile/tips.html

**Comment by mitchellh** [comment]
This is working as intended. Vagrantfiles are loaded a few times in a random order and are meant to be fairly declarative. Logic like this won't ever work as you expect. I'm not sure what you're trying to do exactly so I can't give you any suggestions for alternatives, but I'd take a step back and rethink this.
