### ISSUE TITLE
rsync__auto does not work when set to true

### ISSUE THREAD

**Issue by edvinasme** [mitchellh/vagrant#4862]
I have looked at all the similar issues, but they weren't discussing this exactly.

If you set `rsync__auto` to `true` in your config, the `vagrant rsync-auto` will only do an initial sync but will not automatically sync further changes on the folder.

Example config to reproduce:

    Vagrant.configure("2") do |config|
      config.vm.synced_folder ".", "/vagrant", type: "rsync",
        rsync__exclude: ".git/",
        rsync__auto: true,
        rsync__chown: true
    end

While this file works correctly:

    Vagrant.configure("2") do |config|
      config.vm.synced_folder ".", "/vagrant", type: "rsync",
        rsync__exclude: ".git/",
        rsync__chown: true
    end

Host: Archlinux, Vagrant 1.6.5, VirtualBox 4.3.20
Guest: Debian

**Comment by fresheneesz** [comment]
This is happening to me too. You shouldn't even have to set ti to true either, since the docs say it should be true by default.

**Comment by mitchellh** [comment]
I can't reproduce this on master so Im' going to say it is fixed. Please reopen if it persists in the next release.

**Comment by edvinasme** [comment]
Did you chek that it will sync further changes on the folder? As it was ok with the initial sync only.

**Comment by mitchellh** [comment]
Yep I changed some files and it kept syncing.

**Comment by BHSPitMonkey** [comment]
For clarification @mitchellh, were you explicitly running the `vagrant rsync-auto` process? I'm using 1.7.4 and syncing only happens for me if I have `vagrant rsync-auto` running in a terminal.

My hope was that with `rsync__auto: true` I would only need to run `vagrant up` to get everything going.

**Comment by ckubescha** [comment]
Same issue here, seems to be the default behavior for now.

**Comment by mjgreer** [comment]
Also seeing this issue.  Can either not set parameter at all, or explicitly set to true, and will only do an initial rsync

**Comment by edvinasme** [comment]
@mitchellh can you re-open this issue as it is not fixed yet?

**Comment by danh-fissara** [comment]
Not working for me either, Vagrant 2.0.1 on MacOS. Initial rsync works, but `rsync__auto = true` has no effect. Have to manually run `vagrant rsync-auto` for it to work.

**Comment by juliansuggate** [comment]
Ditto here, running Vagrant 2.1.1 on WSL. Using vagrant rsync-auto works, but not rsync__auto = true in the Vagrantfile.

**Comment by noshky** [comment]
Still not working with ``Vagrant 2.2.0``. Windows 10, Virtualbox provider, Ubuntu 16.04 box.
