### ISSUE TITLE
Keep getting error writing to file ..\mingw\share\adlocal-1.11\maintainer.mp4

### ISSUE THREAD

**Issue by bvi1998** [mitchellh/vagrant#4865]
Hi, 
I keep getting error writing to file ..\mingw\share\adlocal-1.11\maintainer.mp4 no matter what permissions actually exist. I am running Windows 8.1 as an OS that I am trying to install on. 
Can anyone help? I have tried everything...
Thanks!

**Comment by mitchellh** [comment]
This is not likely to be related to Vagrant. I'm guessingyou're seeing this in your shell. I'm not sure what other things you have installed but its really unlikely to be Vagrant.
