### ISSUE TITLE
Docker provisioner is not able to install specific version

### ISSUE THREAD

**Issue by Yserz** [mitchellh/vagrant#4871]
I'm not able to install a specific version of docker. Am I missing something? Regarding to the Docker blog 1.1.0 should be available.

Vagrantfile:
```
host.vm.provision "docker" do |d|
    ...
    d.version = "1.1.0" # Default is :latest
    ...
end
```
Stacktrace:
```
==> dev-host: Running provisioner: docker...
    dev-host: Installing Docker (1.1.0) onto machine...
==> dev-host: Vagrant is not capable of installing an specific version of Docker
==> dev-host: onto the guest machine and the latest version will be installed.
    dev-host: Configuring Docker to autostart containers...
==> dev-host: Building Docker images...
```

**Comment by mitchellh** [comment]
Thanks, this is mostly an output issue. I updated the output.

This means that Vagrant doesn't know how to install a specific version for your guest OS. If you know how to do it, we can change Vagrant!
