### ISSUE TITLE
Gem::RemoteFetcher::UnknownHostError: no such name

### ISSUE THREAD

**Issue by romspacenut** [mitchellh/vagrant#4888]
$ vagrant --version
Vagrant 1.6.5

When ever I run vagrant plugin update, I keep getting this issue:

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing vagrant-hosts (2.2.4), and Bundler cannot continue.
Make sure that `gem install vagrant-hosts -v '2.2.4'` succeeds before bundling.

Gem::RemoteFetcher::UnknownHostError: no such name (https://rubygems.org/gems/vagrant-hosts-2.2.4.gem)

Any workarounds for this? I'm also on the latest OSX Yosemite.

**Comment by mitchellh** [comment]
This looks like a DNS issue. Can you try on another network/machine? No one I've talked to has seen this or can reproduce it.

**Comment by DuncanAkello** [comment]
i have the same problem

**Comment by DuncanAkello** [comment]
but it appears to be happening to all my gems

**Comment by pcerioli** [comment]
This happens to me too, but it is because I have Little Snitch filtering the network traffic. If I turn it off, then it will complete without issues.
