### ISSUE TITLE
.curlrc ignored

### ISSUE THREAD

**Issue by slicen** [mitchellh/vagrant#4889]
Hi all,

I would like to modify Curl's behaviour in Vagrant using a custom .curlrc file. This would enable us to configure proxies as well as set client and CA certificates without requiring the user to append these options to their commands. It would also enable us to get around Issue #4494.

However, I note that the -q flag is added to the Curl subprocess at present (Windows version 1.6.5), resulting in the .curlrc file being ignored.

Could you please consider removing this flag? I believe there is benefit in allowing users to load settings from .curlrc files.

Kind regards,
Slicen

**Comment by mitchellh** [comment]
Vagrant uses `curl` as its mechanism for downloading currently, but that may not always be the case. As such, it is best to pretend curl isn't being used, and if you're looking for a specific feature, to request that directly into Vagrant.

**Comment by stardust85** [comment]
Please don't ignore curlrc. I need to share credentials for downloading boxes, so I need to enable netrc in curlrc.
