### ISSUE TITLE
ability to set mac address for hyperv

### ISSUE THREAD

**Issue by mac2000** [mitchellh/vagrant#4891]
There is way to set concrete mac address for hyper-v virtual machine in [/plugins/providers/hyperv/scripts/import_vm.ps1](https://github.com/mitchellh/vagrant/blob/master/plugins/providers/hyperv/scripts/import_vm.ps1)

All we need to do is to add:

```
+Get-VM $vm_name | Get-VMNetworkAdapter | Set-VMNetworkAdapter -StaticMacAddress "902B343FAAAA"
+
 $vm_id = (Get-VM $vm_name).id.guid
 $resultHash = @{
```

Unfortunatelly I am newbie to ruby so do not know from where to start to add mac address as vm customization or something similar, hope that @mwrock, @mitchellh or anybody who knowing what to do with this will look at this

**Comment by mitchellh** [comment]
This is done

**Comment by mac2000** [comment]
Thank you, is there related commit so I can at least determine what should be done for possible future PRs?

**Comment by mwrock** [comment]
see #6296
