### ISSUE TITLE
Support docker exec

### ISSUE THREAD

**Issue by schmunk42** [mitchellh/vagrant#4904]
From 1.3 on docker introduced `docker exec`, see also [Inject new processes with docker exec](Inject new processes with docker exec).

Would be nice if vagrant could support this.

**Comment by thomaszbz** [comment]
@sethvargo @wkolean This feature is so cool. would like to see this released soon.

**Comment by wkolean** [comment]
It's available as a plugin at https://github.com/wkolean/vagrant-docker-exec
