### ISSUE TITLE
FullyQualifiedErrorId : NamedParameterNotFound,import_vm.ps1 (Generation)

### ISSUE THREAD

**Issue by schmunk42** [mitchellh/vagrant#4910]
created new issue from https://github.com/mitchellh/vagrant/issues/4346#issuecomment-65803128

---

I have a similar error during `vagrant up`, my Vagrantfile is a standard `vagrant init hashicorp/precise64`.

```
@SRV-BASE /d/Vagrant/dockerhost-hyperv (master)
$ vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) SRV-BASE virtueller Switch WEB
    default: 2) SRV-BASE virtueller Switch
    default:
    default: What switch would you like to use? 2
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.6.5\plugins\providers\hyperv\
scripts\import_vm.ps1 : Es wurde kein Parameter gefunden, der dem
Parameternamen "Generation" entspricht.
In Zeile:1 Zeichen:1
+ &('c:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.6.5\plugins\providers\hy
per ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [import_vm.ps1], ParameterB
   indingException
    + FullyQualifiedErrorId : NamedParameterNotFound,import_vm.ps1
```

The German part in the error message translates like the following:

> Es wurde kein Parameter gefunden, der dem Parameternamen "Generation" entspricht.

There was not parameter found, which equals to the parameter name "Generation".

*Vagrant 1.6.5 on Windows Server*

**Comment by mitchellh** [comment]
What version of Windows? I'm guessing it is too old of a version.

**Comment by schmunk42** [comment]
It's a Windows 2012 Server

**Comment by jmcneiceGE** [comment]
Windows 2012 or Windows 2012 R2? I ran into a similar error when trying to use 2012 and my understanding is that only 2012 R2 is supported.

**Comment by schmunk42** [comment]
How can I check that from `CMD.exe` only? I have no Explorer, System Settings or any kind of UI available.

**Comment by jmcneiceGE** [comment]
Refer to http://en.wikipedia.org/wiki/Ver_%28command%29

**Comment by schmunk42** [comment]
I'll close this for now, since we're not running R2, will reopen if needed.

**Comment by borrelan** [comment]
@schmunk42 How were you able to resolve this issue?
cmd --help
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

vagrant up --provider hyperv   
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...                                                                                                                     
    default: Timeout: 120 seconds                                                                                                                                                    
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.                 
                                                                                                                                                                                     
Script: get_network_config.ps1                                                                                                                                                       
Error:                                                                                                                                                                               
                                                                                                                                                                                     
C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyperv\scripts\get_network_config.ps1 : Cannot index into a null array.                                      
At line:1 char:1                                                                                                                                                                     
+ &('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyper ...                                                                                               
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                   
    + CategoryInfo          : InvalidOperation: (:) [get_network_config.ps1], RuntimeException                                                                                       
    + FullyQualifiedErrorId : NullArray,get_network_config.ps1

**Comment by vitalyster** [comment]
Same here with Windows Server 2012. Is there any workaround?

**Comment by vitalyster** [comment]
Solved installing PSHyperV-Install.ZIP from http://pshyperv.codeplex.com/
