### ISSUE TITLE
RDP on Linux (Follow on from issue 3845)

### ISSUE THREAD

**Issue by TobyHFerguson** [mitchellh/vagrant#4911]
vagrant rdp on linux would be very useful. It works on Windows, so why not on Linux? This would require the following (at least for a VirtualBox provider)
+ Enabling vrde
+ Enabling a specific vrde port at boot time
+ Connecting this port to the 'rdesktop' command
+ Printing out an error message (such as 'please install rdesktop to use rdp on Linux') if there's a failure

**Comment by mitchellh** [comment]
This sounds like a good plugin, but not something we're currently planning ourselves as a first class feature for Vagrant. If you submit a PR, or start working on one, we'd be happy to provide input and eventually merge it in. Thanks!

**Comment by TobyHFerguson** [comment]
Mitchell,

thanks for the response. I'm interested but have no idea how to begin
(never programmed in Ruby). So I'll put that to one side and see if it irks
me enough to want to put some time into it.

Toby

On Mon, Jan 5, 2015 at 9:47 PM, Mitchell Hashimoto <notifications@github.com
> wrote:

> Closed #4911 <https://github.com/mitchellh/vagrant/issues/4911>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/4911#event-214515950>.
>



-- 
toby
