### ISSUE TITLE
ssh-config using remnant ip from dhcpd

### ISSUE THREAD

**Issue by johnraz** [mitchellh/vagrant#4914]
Hi there,

So my setup:
Vagrant 1.6.5
vagrant-vmware-fusion (3.1.2)
Vmware fusion 7.1.0

I did a bit of trickery in the dhcpd config of vmware to get the nat ip to be static and it is actually working nicely.
I can ssh into the box using plain ssh command using the static ip referenced in the customized dhcpd config.

But, vagrant ssh is failing, vagrant ssh-config returns the previous ip that was assigned in the dynamic ip pool of dhcpd.

Can you give me pointers wether this is a vagrant issue or a vmware cache issue somewhere ? 

For the record I rebooted the vmware dhcpd already.

Thx !

**Comment by johnraz** [comment]
Hi @sethvargo ,  I was able to test this again today and I can confirm it is not fixing the issue :/

**Comment by mitchellh** [comment]
We don't read the static IP from the machine unless it is specified in the Vagrantfile. Otherwise, we look at DHCP.
