### ISSUE TITLE
`vagrant destroy` only works when all boxes have been started

### ISSUE THREAD

**Issue by packetcollision** [mitchellh/vagrant#4930]
When using the VirtualBox provider, doing `vagrant destroy -f` on a multi-host Vagrant file destroys any machines that have been started. When using the vmware_fusion provider, it errors if any of the machines have not started, which means I end up having to destroy each machine separately.

Earliest known affected version: vagrant-vmware-fusion (3.1.2) - but I have no reason to believe this hasn't always been the behavior.

to test:
set up a multi-host Vagrantfile 

```ruby
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "box-cutter/ubuntu1404"
  (1..3).each do |i|
    config.vm.define "test-#{i}" do |node|
      node.vm.hostname = "test-#{i}"
    end
  end
end
```

run `vagrant up test-1`
run `vagrant destroy -f`

On VirtualBox, it shows:

```ruby
==> test-3: VM not created. Moving on...
==> test-2: VM not created. Moving on...
==> test-1: Forcing shutdown of VM...
==> test-1: Destroying VM and associated drives...
```

On vmware_fusion, it shows:

```ruby
VM must be created before running this command. Run `vagrant up` first.
```

Expected: the vmware_fusion provider should work the same as the VirtualBox provider.

**Comment by rfletcher** [comment]
+1

I'm working around this with an alias for now, but `vagrant status` is *very* slow in a multi-machine environment (at least with vmware_fusion), so this alias is too:

````bash
alias vagrant-destroy-all='vagrant destroy $(vagrant status | grep vmware_fusion | grep -v "not created" | awk "{ print \$1 }")'
````

You can pass `vagrant destroy` options to the alias, so `vagrant-destroy-all` or `vagrant-destroy-all --force` both work as expected.

**Comment by mitchellh** [comment]
Fixed
