### ISSUE TITLE
Linux host / Windows guest support (any provider)

### ISSUE THREAD

**Issue by maxlinc** [mitchellh/vagrant#4932]
@sneal A bit of a WinRM brain dump below. These are things I found that I was tempted to work on as part of https://github.com/mitchellh/vagrant/pull/4236, but then you'd have a massive PR to review that address more than just "Add WinRM over SSL support".

These could each turn into separate issues and/or PRs, but I figured it'd be useful to collect and discuss and overall plan first.

The basic problem: although WinRM has been in Vagrant for a little while now, I've found that using a Linux or OSX host and a Windows guest is still difficult. I thought I'd create a checklist of a few notes I've made while looking into WinRM support.

Questions/issues:
- [x] Security/SSL - Must have for cloud providers. Requires WinRM release. Implemented in https://github.com/mitchellh/vagrant/pull/4236.
- [x] Error handling - Still not sure which WinRM errors should be treated as retryable and which should fail fast. Also not sure about things like whether unexpected errors need to be wrapped in certain exception classes or just raised. Implemented in https://github.com/mitchellh/vagrant/pull/4943.
- [x] Retry settings - also related to above. The current settings have `max_retries = 20`, with a 10 second sleep and and a long timeout! This means WinRM can hang a long time (as can WinRM unit tests for retry conditions if time isn't mocked and/or defaults aren't overridden). Delay setting added in #4943.
- [x] Should we always forward networks for SSH + WinRM, or only forward the network for whichever one is the active communicator? Implemented in https://github.com/mitchellh/vagrant/pull/4236 (though it forwards both HTTP & HTTPS for WinRM even though only one will be used).
- [x] Windows guest detection... should this work OOTB if the communicator is WinRM w/out extra provider integration? Testing WinRM on vagrant-rackspace, it's assuming my boxes are Linux and trying to install rsync w/ apt-get (over WinRM!). Fixed by https://github.com/mitchellh/vagrant/pull/4996.
- [ ] Windows rsync capabilities - should windows have the capability to install rsync? It's possible (see packer-windows) but since rsync tunnels over SSH it doesn't pair well w/ WinRM communicators - you'd need to setup a second set of credentials using a different auth method.
- [x] Should there be a winrm synced folder type? It seems like it's already implemented (`VagrantPlugins::CommunicatorWinRM::FileManager`) but isn't exposed as a synced folder plugin. Implemented in https://github.com/mitchellh/vagrant/pull/4983.

A winrm synced folder plugin wouldn't be very efficient, but it's the one folder type that should always work over the winrm transport. The other types are limited by provider, platform, or capability, or require additional authentication info and/or firewall changes.

**Comment by maxlinc** [comment]
@sneal @mitchellh @sethvargo Can you review my open PRs related to Windows: #4236, #4943, #4983 and #5013? They're no longer blocked now that winrm 1.3 has been released, so I'm hoping to get them all either merged or obsoleted by other changes.

**Comment by mitchellh** [comment]
Going to mark this as done. We're basically here.
