### ISSUE TITLE
add --name aname ./aname.box doesn't work

### ISSUE THREAD

**Issue by TobyHFerguson** [mitchellh/vagrant#4959]
I'm trying to add a local box thus:

vagrant box add --force --checksum $(md5sum ol6minimal.box | awk "{ print $1 }") --checksum-type md5 --name ol6minimal ol6minimal.box

I expected that vagrant box list would give:

ol6minimal                                                     (virtualbox, 0)

but instead it gives

ol6minimal.box                                                 (virtualbox, 0)

However, if I rename the file 'ol6minimal.box' to 'package.box' and execute:

vagrant box add --force --checksum $(md5sum package.box | awk "{ print $1 }") --checksum-type md5 --name ol6minimal

(note - no reference to the local package.box file)

then I find that the new box is correctly named. i.e. vagrant box list gives:

ol6minimal                                                     (virtualbox, 0)

**Comment by sethvargo** [comment]
Closing due to no response. Please open a new issue if this is still happening and include the output in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html).
