### ISSUE TITLE
1.7.1 vagrant provision error with shared folders

### ISSUE THREAD

**Issue by biemond** [mitchellh/vagrant#4963]
I can do a vagrant up xxx but after this when I do a vagrant provision xxx it gives me this error

==> admin: Running provisioner: puppet...
Shared folders that Puppet requires are missing on the virtual machine.
This is usually due to configuration changing after already booting the
machine. The fix is to run a `vagrant reload` so that the proper shared
folders will be prepared and mounted on the VM.

vagrant reload xxx  helps after this I can do multiple times vagrant provision xxx 

cheers

**Comment by mitchellh** [comment]
Fixed
