### ISSUE TITLE
Vagrant push with Atlas strategy not working

### ISSUE THREAD

**Issue by kramos** [mitchellh/vagrant#4968]
Working on Windows 7 Enterprise.  Looking to try Atlas but getting:

```
$ vagrant push
error starting upload: upload: resource not found
```

```
$ cat Vagrantfile
Vagrant.configure(2) do |config|
   config.vm.box = "ubuntu/trusty64"

   config.push.define "atlas" do |push|
     push.app = "Markosrendell/atlas_test1"
   end
end
```

```
$ ls -a
.  ..  .git  .vagrant  Vagrantfile  Vagrantfile~
```

```
$ vagrant -v
Vagrant 1.7.1
```

I'm probably doing something stupid, but I thought it might be worth raising and getting the solution added to the wiki,

**Comment by david-sackmary** [comment]
I have the same error (and tokens match and all else above).  I'm running a Centos6.5 VM :
    centos$ vagrant push
    error starting upload: upload: resource not found

**Comment by pires** [comment]
Same thing on MacOS 10.10.

**Comment by sethvargo** [comment]
Hi there,

We have isolated and fixed the root cause of this bug on master. To get around this problem (until the next release of Vagrant), add the following to your shellrc file:

    export ATLAS_TOKEN=`cat ~/.vagrant.d/data/vagrant_login_token`

Or set that environment variable to a valid access token created via the Atlas Web UI.

**Comment by pires** [comment]
I can confirm this fixes it.

**Comment by david-sackmary** [comment]
Hi,

I added the line to my .bashrc , and got this:

$ vagrant push
error starting upload: upload: client: 500 Internal Server Error

 I'm using hashicorp/precise64.  The error happens whether vagrant is up or down.  
Is there anything helpful I could add?

**Comment by david-sackmary** [comment]
I also confirm this fixes it.

**Comment by ml** [comment]
The fix works for me too, but it'd be nice to mention this in vagrant docs or display an error message from vagrant push saying that ATLAS_TOKEN is not defined.

**Comment by sethvargo** [comment]
@ml we have fixed this on master correctly, so it will be automatic in the next release

**Comment by hyperfocus1337** [comment]
I have added this to my .profile in my user directory on Mac OSX 10.10 and it fixes the issue. Remove it after updating Vagrant to the latest version? Will it cause any trouble?

**Comment by sethvargo** [comment]
@hyperfocus1337 yea - this has been fixed in master and will be released with the next version of Vagrant. However, other Atlas products obey the `ATLAS_TOKEN` environment variable, so there is no harm having it set (like Packer and Terraform).

**Comment by dolanor** [comment]
I had this bug just today, and using the ATLAS_TOKEN fixed the upload.
The box isn't available on the web, though. Since it is my first time vagrant pushing, I don't know if it is normal.

OS: ubuntu 14.04
vagrant: 1.8.1

**Comment by gokhansengun** [comment]
Must be a regression here. Same issue and same workaround solves it.

OS: macOS Sierra 10.12.1 (16B2555)
Vagrant 1.8.7

**Comment by johnypony3** [comment]
for me it was that the organization was not created in atlas.
i.e.: {{org}}/{{artifact}}
{{org}} has to be setup, by default only the username is setup.

**Comment by mcandre** [comment]
Can `vagrant login` please be updated to integrate better with `vagrant push`? These have grown apart, especially with the de facto Atlas push strategy.

Out of the box, `vagrant login && vagrant push` fails due to:

* No longer informing the push with the traditional `~/.vagrant.d/data/vagrant_login_token` credentials file.
* Implicitly requiring that an `ATLAS_TOKEN` environment variable be set.

As a workaround, users have suggested configuring shell snippets like:

```sh
export ATLAS_TOKEN="$(cat "$HOME/.vagrant.d/data/vagrant_login_token")"
```

Though `vagrant push` then complains of a conflict between `~/.vagrant.d/data/vagrant_login_token`-defined and `$ATLAS_TOKEN`-defined credentials. Could we please fix the toolset so that login and push work better together?
