### ISSUE TITLE
1.7.1 solaris 10 to 11.2 boxes fails because of newly generated keypair

### ISSUE THREAD

**Issue by biemond** [mitchellh/vagrant#4969]
Hi, 

this keypair refresh break the usage of solaris boxes, on 10, 11 and 11.2
also I can't add a private network to solaris 11.1 and 11.2

    dbsol: this with a newly generated keypair for better security.
Vagrant is configured to generate a random keypair and insert it
onto the guest machine, but it appears Vagrant doesn't know how to do
this with your guest OS. Please disable key insertion by setting
`config.ssh.insert_key = false` in the Vagrantfile.

After doing so, run `vagrant reload` for the setting to take effect.

If you'd like Vagrant to learn how to insert keys on this OS, please
open an issue with details about your environment.

**Comment by sethvargo** [comment]
Closing now that 5290 is merged. Thanks!
