### ISSUE TITLE
vagrant up fails if `VBoxManage showvminfo' contains non-UTF8 characters.

### ISSUE THREAD

**Issue by hirayama-evolni** [mitchellh/vagrant#4978]
HostOS: Windows8.1(Japanese)
Provider: VirtualBox 4.3.20

I just upgraded vagrant from 1.6.5 to 1.7.1, then `vagrant up` fails now.

```
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/driver/base.rb:387:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
```

Full stack trace is [here](https://gist.github.com/hirayama-evolni/bc5aa8d299e9d36447b7).

This is caused by `VBoxManage showvminfo` returns non-UTF-8 text, `Shift_JIS` for my case.

Take a look at [this](https://gist.github.com/hirayama-evolni/86acc82f7af53590ac94#file-vboxmanage-exe-showvminfo-a422b326-ca31-4d5f-8acd-2e1f47644f55-machinereadable-L108).
This is of a VM not created by vagrant, and whose snapshot name is in Japanese.

I tried to apply `force_encoding("ASCII-8BIT")` on `r.stdout`, it goes well, but it may not be a good idea.

Thanks.

**Comment by mitchellh** [comment]
Unfortunatey we're not actually sure how to fix these encoding issues. There is a very old meta-issue tracking these encoding issues. We'll fix them over time.

**Comment by Danita** [comment]
Workaround for people like me who encountered this error: rename your VMs and snapshots to remove non-ASCII characters.
