### ISSUE TITLE
NFS problem on multiple machines

### ISSUE THREAD

**Issue by filipgolonka** [mitchellh/vagrant#4990]
Vagrant version: 1.7.1
VirtualBox version: 4.3.20
OS: Mac OS X

Related to #2686. I have two machines, first is backend api, second is frontend app. I'd like to set up both to use nfs.
Steps:
* I type `vagrant up` for first machine (backend),
* I type `vagrant ssh` and go to mounted directory
* I start second machine frontend - `vagrant up`
* I come back to first machine and type `ls`

Expected: I should see list of files in mounted directory
Actual: `ls: cannot open directory .: Stale NFS file handle`

This configuration is working, when one machine is mounted using nfs and second using rsync - but not when both are nfs.

**Comment by jyokyoku** [comment]
I have same problem on multi-machine (multi Vagrantfile) with `nfs` mount.
I couldn't access to first machine synced folder (nfs) after second machine `vagrant up`.

Vagrant version: 1.7.2
VirtualBox version: 4.3.26
OS: Mac OS X 10.10.3

**Comment by mitchellh** [comment]
I was able to reproduce this but it seems that it is only temporary: the NFS server restart takes some time and during that time you can get stale file handles. If you wait for it to reboot it seems fine. 

Unfortunately there doesn't seem to be a way on Darwin to update the /etc/exports without restarting NFS so this will happen.
