### ISSUE TITLE
Vagrant with VMWare on Windows not detecting port collisions

### ISSUE THREAD

**Issue by bartmeuris** [mitchellh/vagrant#4993]
This issue has been reported before as #4577 - but it was closed. However the problem still remains.

I must stress that this is NOT a firewall related issue as was suggested when closing the issue: Vagrant + VirtualBox on the same machine works just fine as you would expect, detecting port collisions and remapping them. Vagrant + VMWare however removes the conflicting ports of the VM that was started first, and redirects them to the new-one the moment you do a `vagrant up`. This is a VMWare specific issue.

This still occurs on Windows 7 Professional with Vagrant 1.7.1 on Windows with VMWare Workstation 10.0.3.

[edit] And using the vagrant-vmware-workstation version 3.1.2 plugin

**Comment by mitchellh** [comment]
The VMware plugin uses the identical code (which is in this repo, `ForwardedPortCollisionCheck` or so) to check for collisions. The only difference is that VMware doesn't have access to _all_ the forwarded ports in use like VirtualBox does, so Vagrant has to fall back to checking if a port will accept a TCP handshake. If a port is closed (nothing is listening) Vagrant assumes it is available. This leads to false negatives, but there isn't much more we can do.
