### ISSUE TITLE
chef-solo fails to find ./cookbooks after upgrading to Vagrant 1.7.0 & 1.7.1

### ISSUE THREAD

**Issue by johnclaus** [mitchellh/vagrant#4997]
I'm using Chef 11.16.4 and recently tried upgrading Vagrant from 1.6.5 to 1.7.[0,1].  Upon running ```vagrant up --provision``` using Vagrant 1.7.[0,1], chef-solo is no longer able to find my ./cookbooks directory, which is relative to my Vagrantfile.

I noticed the following info level log within my Chef run, which doesn't appear in Chef runs prior to my Vagrant 1.7.[0,1] upgrade:

```
==> centos-6: [2014-12-16T21:15:19+00:00] WARN: found a directory attributes in the cookbook path, but it contains no cookbook files. skipping.
```

Has anyone else noticed this behavior upon upgrading past Vagrant 1.6.5?

**Comment by sethvargo** [comment]
@johnclaus I cannot reproduce this - can you please supply a Vagrantfile?

**Comment by mitchellh** [comment]
Fixed
