### ISSUE TITLE
Cannot download puppetlabs Vagrant Cloud boxes without cURL cert error

### ISSUE THREAD

**Issue by AnthonyMastrean** [mitchellh/vagrant#5001]
I can't `vagrant up` or `vagrant box add` this puppetlabs Vagrant Cloud box on Ubuntu 14.04 x64 and Vagrant 1.7.1 x64 or 1.7.0 x64 (downloaded and installed the `.deb` from the Vagrant website). I get this error message from cURL.

```text
$ vagrant box add puppetlabs/centos-6.5-64-puppet --force
==> box: Loading metadata for box 'puppetlabs/centos-6.5-64-puppet'
    box: URL: https://atlas.hashicorp.com/puppetlabs/centos-6.5-64-puppet
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) virtualbox
2) vmware_desktop
3) vmware_fusion

Enter your choice: 1
==> box: Adding box 'puppetlabs/centos-6.5-64-puppet' (v1.0.0) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.5-64-puppet/
versions/1.0.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

I can download the box directly using the system cURL

```text
$ curl -O -L https://vagrantcloud.com/puppetlabs/boxes/centos-6.5-64-puppet/versions/1.0.0/providers/virtualbox.box
```

and the Vagrant embedded cURL

```text
$ /opt/vagrant/bin/../embedded/bin/curl -O -L https://vagrantcloud.com/puppetlabs/boxes/centos-6.5-64-puppet/versions/1.0.0/providers/virtualbox.box
```

I downgraded to Vagrant 1.6.5 x64 from the `.deb` on the website and tried again and it worked.

---

Here's the [command debug log](https://gist.github.com/AnthonyMastrean/23bc15b7bf9fb59c4cb4)

**Comment by brpaz** [comment]
Some problem here Was having some problems downloading base boxes from VagrantCloud as well as executing chef provisioning in some projects.
the @choffee workaround worked for me also.

**Comment by klub** [comment]
Try using this line in your vagrant file:

config.vm.box_download_insecure = true

**Comment by sethvargo** [comment]
We are released Vagrant 1.7.2 later today and it includes a new cacert bundle that fixes this issue.

**Comment by tknerr** [comment]
Can verify that this is fixed in 1.7.2 now. Thanks all!

**Comment by jdub** [comment]
Is there a corresponding bug for OS X, or is this a good issue in which to report a similar problem? I just updated to 1.7.2, and am seeing the same error.

```
jdub@slender:~/src/wang$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

You're running an up-to-date version of Vagrant!

jdub@slender:~/src/wang$ vagrant box update
==> default: Checking for updates to 'ubuntu/precise64'
    default: Latest installed version: 12.04.4
    default: Version constraints:
    default: Provider: virtualbox
There was an error while downloading the metadata for this box.
The error message is shown below:

SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by rommsen** [comment]
Same problem here on Ubuntu 14.04

```
Installed Version: 1.7.2
Latest Version: 1.7.2
 
You're running an up-to-date version of Vagrant!

vagrant box update 
==> default: Checking for updates to 'ubuntu/trusty64'
    default: Latest installed version: 14.04
    default: Version constraints: 
    default: Provider: virtualbox
There was an error while downloading the metadata for this box.
The error message is shown below:

SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

```

None of the workarounds above worked for me

**Comment by rommsen** [comment]
What worked for me was the following 

```
vagrant box add --insecure 'ubuntu/trusty64' https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
```

After this I can not use vagrant box update anymore. But at least I can start the VM:
```
vagrant box update
==> default: Checking for updates to 'ubuntu/trusty64'
    default: Latest installed version: 0
    default: Version constraints: 
    default: Provider: virtualbox
The box 'ubuntu/trusty64' is not a versioned box. The box was added
directly instead of from a box catalog. Vagrant can only
check the versions of boxes that were added from a catalog
such as from the public Vagrant Server.
```

**Comment by longthanhtran** [comment]
my vagrant 1.7.2 on Windows 7 x64 has this issue just today "SSL certificate problem: unable to get local issuer certificate" and after check, I found vagrantcloud.com using rapidssl which my local curl unable verify complete ssl chain. Just need to grab the ssl cert (pem format) from https://ssl-tools.net/certificates/nakw2x-rapidssl-sha256-ca-g3 and append this  to vagrant folder (vagrant\embedded)

**Comment by Tairy** [comment]
@longthanhtran  could you tell me how to append the pem file to vagrant folder. only copy this file to the forder? ths!

**Comment by longthanhtran** [comment]
I think the incomplete certificate chain issue is solved now so you may not need to modify the local issuer certificate file.

If you want to know which file being used by curl then you check by running (for example)
```
curl -v 'http://vagrantcloud.com'
```
to 
* check if curl can handle https request or
* find the local ca bundle file

then you can copy the content of cert file (download per previous link) and append it to current one (either _curl-ca-bundle.crt_ or _cacert.pem_ in the same folder with __curl__)

**Comment by cjw296** [comment]
I've opened #5391 as a separate issue for the Mac OS X problem.

**Comment by anjaneyaprasad** [comment]
@Ozsiix you saved me...

**Comment by miscapu** [comment]
Add in Vagrantfile, the following code:
` config.vm.box_download_insecure = true`
For more informations:
[Machine Settings Vagrant](https://www.vagrantup.com/docs/vagrantfile/machine_settings.html)

**Comment by Ozsiix** [comment]
@miscapu thats literally what i said a year ago :p

**Comment by dragon788** [comment]
Since it is a terrible practice to disable SSL verification long term,you can correct the certificate issue the right way by adding the certificate to the trust chain of the embedded Ruby and curl (painful but possible to automate) or better yet using the alternate CA path that was added to a newer Vagrant version? `config.vm.box_download_ca_cert` appears to be the new setting.

**Comment by miscapu** [comment]
@Ozsiix It's what worked for me, do you want to pay for it?
