### ISSUE TITLE
Feature request: add a global public key insertion

### ISSUE THREAD

**Issue by bartmeuris** [mitchellh/vagrant#5005]
## Intro

Since Vagrant 1.7, if it detects the insecure SSH key on a box when bringing it up, it removes the key and generates a new-one specific for that box.

Security-wise, this is a good thing, although because 99% of these boxes probably run in development environments and because vagrant environments are very volatile, security is not as high as practicality on my list of priorities. It is still important though.
## The problem

The problem with this change in 1.7.x is that it impacts practicality a lot, certainly in a Windows environment. I suspect most people won't use `vagrant ssh` there (I don't) because of the horrible Windows console with a hacky terminal emulation, where resizing (even with stuff like Console2)  brings you a world of pain. I suspect most people will fall back to PuTTY or another SSH client to connect to their boxes, and while it's not perfect, it works.

This change of removing the 'insecure' ssh key in combination with PuTTY (or any other external ssh client) becomes problematic:
- PuTTY does not understand OpenSSH keys directly, you have to convert them for each and every box.
- You have to know the path and provider of the box you're trying to connect to to load (or convert) the key if you're trying to automate this (this was my initial thought)
- external provisioning scripts using ssh (which I have for various reasons), suddenly need more info than just the port they need to connect to.
## Proposed solution

Therefor I propose the following: Add a central configuration option where you specify public keys that should be injected into the VM when it detects they are missing, just like the insecure keys are detected and new-ones are inserted.

This offers the following:
- this does not impact security any more than the current private key generation
- allows people to use their own private keys to connect to their vagrant boxes, and can easily load them in a key-agent, or configure their ssh profiles to use their own private key.
- Vagrant does not need to know the private keys, it can still use it's own privately-generated-ones to communicate with the box.

I think this offers best of both worlds, I hope this will be considered.

**Comment by ccope** [comment]
+1 for adding an option to specify an additional public key(s) to insert into the VM. Our users need to have persistent keys for their VM's, but we also cannot leave the vagrant public key due to security issues.

**Comment by nickryand** [comment]
I wanted to point out that @philr wrote a ruby library to convert OpenSSH keys to the putty format and added it to the vagrant-multi-putty for vagrant. Keys will now be converted automatically when `vagrant putty` is used.

https://github.com/nickryand/vagrant-multi-putty/commit/87532b39c48fb77fadbbf53c403d90a960deb9f0

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!

**Comment by axd1967** [comment]
If closing an unfinished issue, please consider using a label to identify such issues. This help anyone looking at the issue, and find such issues.
