### ISSUE TITLE
Vagrant does not find hieradata in 1.7.1 

### ISSUE THREAD

**Issue by scotty-c** [mitchellh/vagrant#5015]
Good morning,

I just upgraded from Vagrant 1.6.5 to 1.7.1 The issue we are seeing is now all our Hieradata is not being found when Puppet applies the module. Here is a copy of my Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby : 

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|  
  config.vm.box = "centos_puppet_rvm"

  config.vm.network :forwarded_port, guest: 80, host: 9080
  
  config.vm.network :forwarded_port, guest: 443, host: 9443

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  config.vm.hostname = "spacewalk"
  end
  
  #hack for Librarian puppet 
  config.vm.synced_folder ".", "/home/vagrant/spacewalk" 
  
        
  config.vm.provision "shell", inline: 'ln -sf /opt/puppet/bin/puppet /usr/bin/puppet'
  config.vm.provision "shell", inline: 'chkconfig iptables off && chkconfig ip6tables off && service iptables stop && service ip6tables stop' 
  config.vm.provision "shell", inline: 'hostname spacewalk'
  config.vm.provision "shell", inline: "cp /home/vagrant/spacewalk/Puppetfile /tmp"
  config.vm.provision "shell", inline: "cd /tmp &&  librarian-puppet install --verbose"
 

  
  config.vm.provision :puppet do |puppet|
    puppet.temp_dir = "/tmp"
    puppet.options = ['--modulepath=/tmp/modules', '--verbose', '--debug']
    puppet.hiera_config_path = "hiera.yaml"
  end      
end
```
Just to confirm the issue I have rolled back to Vagrant 1.6.5 and it resolved the issue. Any help would be greatly appreciated.

**Comment by visibilityspots** [comment]
Hi @scotty-c, using the vagrant-puppet provisioner together with hiera bit me many times. But I found a solution by syncing the hiera data through a vagrant synced folder.

You can find a solution overhere: https://github.com/visibilityspots/vagrant-yum-repo-server

Hope this could help you getting your vagrant updated to 1.7.2.

**Comment by scotty-c** [comment]
Good morning all,

I have this issue sorted. As of version 1.7.0 you can not use ```config.vm.synced_folder "."``` 
You have to use ```config.vm.synced_folder "./"```
