### ISSUE TITLE
IdentitiesOnly=yes ssh argument not passed by ansible provisioner

### ISSUE THREAD

**Issue by shuhaowu** [mitchellh/vagrant#5017]
Version: 1.7.1

This argument is passed in `vagrant ssh` but not `vagrant provision`. Causing issues with provisioning when the host have 5+ ssh keys.

Edit: I only observed in the ansible provisioning. Not sure about others.

**Comment by trevorr** [comment]
In this case (`config.ssh.keys_only = true`), shouldn't `ansible_ssh_common_args='-o IdentitiesOnly=yes'` also be included in the generated inventory? The current fix works for the provisioner, but not when running Ansible manually using the generated inventory.
