### ISSUE TITLE
'vagrant up' leaves VirtualBox instance in 'Aborted' state

### ISSUE THREAD

**Issue by warnergodfrey** [mitchellh/vagrant#5019]
Sometimes when I call 'vagrant up' the VirtualBox instance starts but quickly enters an 'Aborted' state.

At first the error seemed random and seemed to go away after creating a new shell. As the problem persisted, I noticed that vagrant VMs went into an 'Aborted' state most often after switching between projects that used vagrant. Given the problem seemed environmental, I compared the environment variables between a login shells that exhibited the problem and a fresh shell. The only difference I found was the presence of the $OLDPWD environment variable in the shell that exhibited the issue.

My observation is that 'vagrant up' will result in the VM entering an 'Aborted' state if OLDPWD points to a directory containing a vagrant project. I can reliably reproduce the problem using the steps below: 

1. mkdir ~/vagrant-test/v1
1. mkdir ~/vagrant-test/v2
1. cd ~/vagrant-test/v1
1. vagrant init hashicorp/precise64
1. vagrant up
  - Creates new VirtualBox instance in 'Running' state
1. cd ~/vagrant-test/v2
1. vagrant init hashicorp/precise64
1. vagrant up
  - Creates new VirtualBox instance in 'Aborted' state
  - Outputs the following error:
```
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

My environment is:
- OSX: 10.9.5
- Vagrant: 1.7.1
- Provider: virtualbox
- VirtualBox: 4.3.20 r96996
- Base Box: hashicorp/precise64
- Vagrant Plugins: vagrant-share (1.1.4, system)

**Comment by uchagani** [comment]
I've seen this same error with vmware workstation but haven't been able to reliably reproduce it.

**Comment by mitchellh** [comment]
When a VM enters the "aborted" state, it is almost always the fault of the hypervisor itself. If you can find a way for Vagrant to avoid it (working around hypervisor issues), I'd be happy to do this, but this is usually a hypervisor bug.
