### ISSUE TITLE
Vagrant 1.7 not working on ntfs on linux

### ISSUE THREAD

**Issue by suluke** [mitchellh/vagrant#5020]
I experience the same error as #79 when using vagrant on my ntfs partition.
This is because ntfs on linux usually does not support setting file permissions.
Vagrant 1.7 seems to place the `private_key` file in the `.vagrant/machines/default/virtualbox` subfolder of the `vagrant up` directory. Version 1.6 does not show this behavior, and downgrading to 1.6.5 fixed my issue.
Setting a standard fmask of 177 on the whole partition is not an option. If you know another workaround I would be glad to know.

**Comment by mitchellh** [comment]
You can set `config.ssh.insert_private_key = false` (or somethign close to that, see the docs) to avoid this behavior.

**Comment by ntwong0** [comment]
Following hint from mitchellh, 
1. Assuming you've already done your `vagrant init...`
2. Insert the following into your Vagrantfile after the line `Vagrant.configure("2") do [config]` worked for me:

        config.ssh.insert_key = false
Details on `config.ssh.insert_key` [here](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-insert_key)
