### ISSUE TITLE
Vagrant creates duplicate entries for the same synced folder

### ISSUE THREAD

**Issue by crazyh** [mitchellh/vagrant#5023]
Vagrant creates a duplicate entries for the same synced folder (at least on VM reload) for Docker provider and VirtualBox based Docker host (boot2docker). I saw the same issue with VBSF and with SMB synced folders.

It seems that Vagrant should check if particular synced folder definition already exists and skip creation of duplicate entry.

**Comment by mitchellh** [comment]
I'm not seeing this, but probably goign about it the wrong way. Can you post a Vagrantfile to reproduce it?

**Comment by crazyh** [comment]
It seems I already deleted this file. But I remember that my Vagrantfile was using custom Docker host machine and was very simple. I will check my Windows machine backups for an example.

**Comment by crazyh** [comment]
Well, I did several tests for this issue and tried to reproduce... I did not remember: was is 1.6 version or 1.7 and what actual host VM I was using, but it was very annoying. Currently I tried dduportal/boot2docker and Vagrant 1.7.2 on the same Windows system and all works OK. It is very cool. So it can be closed for now. =) Thanks for an attention.
