### ISSUE TITLE
Restrict permission of `VAGRANT_HOME` 

### ISSUE THREAD

**Issue by willdurand** [mitchellh/vagrant#5029]
`VAGRANT_HOME`  should not be entirely writable, it is especially true in restricted environments (for instance at the University where students should not have full access for anything ;-)).

Rather, writable directories should be identified and we should only require these directories to be writable. It looks like `VAGRANT_HOME/data`  must be writable.

See comments here: https://github.com/mitchellh/vagrant/commit/8652d87865eaa79cf5ecf01b2c06de7b1cd77646

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
