### ISSUE TITLE
Vagrant unable to determine the recommended name for VirtualBox VM on Windows 7

### ISSUE THREAD

**Issue by megalomono** [mitchellh/vagrant#5040]
OS: Windows 7
VirtualBox version: 4.3.20
Vagrant version: 1.7.1

My Vagrantfile is quite trivial:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise32"
end
```

After install VirtualBox and Vagrant, when I try `vagrant up` it throws an error:

```
Vagrant was unable to determine the recommended name for your
VirtualBox VM. This is usually an issue with VirtualBox. The output
from VirtualBox is shown below, which may contain an error to fix.
The best way to fix this issue is usually to uninstall VirtualBox,
restart your computer, then reinstall VirtualBox.

VirtualBox output:
```
with no output from VirtualBox. I tried to apply the proposed solution, but uninstall, restart and install again VirtualBox didn't work for me.

The log file is in https://gist.github.com/megalomono/3468cdbf3942d1c50421

Related with #4493?

**Comment by mitchellh** [comment]
Hah, can you run this command (replace the escapes/quotes/etc.):

```
 INFO subprocess: Starting process: ["C:\\Program Files\\Oracle\\VirtualBox\\VBoxManage.exe", "import", "-n", "C:/Users/Fonso/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-precise32/1.0.0/virtualbox/box.ovf"]
```

That is returning blank for some reason, but it shouldn't be.

**Comment by megalomono** [comment]
Done.

I have run this command:

    VBoxManage.exe import -n "C:/Users/Fonso/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-precise32/1.0.0/virtualbox/box.ovf"

And here is the output:

    0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    Interpreting C:\Users\Fonso\.vagrant.d\boxes\hashicorp-VAGRANTSLASH-precise32\1.0.0\virtualbox\box.ovf...
    OK.
    Disks:  vmdisk1 85899345920     -1      http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized
    box-disk1.vmdk  -1      -1
    Virtual system 0:
     0: Suggested OS type: "Ubuntu"
        (change with "--vsys 0 --ostype <type>"; use "list ostypes" to list all possible values)
     1: Suggested VM name "precise32"
        (change with "--vsys 0 --vmname <name>")
     2: Number of CPUs: 1
        (change with "--vsys 0 --cpus <n>")
     3: Guest memory: 384 MB
        (change with "--vsys 0 --memory <MB>")
     4: Network adapter: orig NAT, config 3, extra slot=0;type=NAT
     5: CD-ROM
        (disable with "--vsys 0 --unit 5 --ignore")
     6: IDE controller, type PIIX4
        (disable with "--vsys 0 --unit 6 --ignore")
     7: IDE controller, type PIIX4
        (disable with "--vsys 0 --unit 7 --ignore")
     8: SATA controller, type AHCI
        (disable with "--vsys 0 --unit 8 --ignore")
     9: Hard disk image: source image=box-disk1.vmdk, target path=C:\Users\Fonso\VirtualBox VMs\precise32\box-disk1.vmdk, controller=8;channel=0
        (change target path with "--vsys 0 --unit 9 --disk path";
        disable with "--vsys 0 --unit 9 --ignore")

**Comment by sethvargo** [comment]
Hi @megalomono 

Are you still experiencing this issue?

**Comment by megalomono** [comment]
Hi @sethvargo,

Recently I've updated my OS to Windows 8.1 and Vagrant is running now without any problem. For the record, I tried to run Vagrant on other machine with Windows 7. It worked correctly there. So I ascribe the issue to my old Windows settings, though I'm not able to specify the root cause.

**Comment by sethvargo** [comment]
Hi @megalomono 

I'm glad things are working. Since there wasn't a bunch of people chiming in on the issue saying "me too", I am inclined to agree with your assessment :smile:. I am going to close this, but if it happens again, we can always revisit :smile:

**Comment by aditya43** [comment]
I'm getting the same error on Windows 7 32bit.
`Vagrant version 2.0.0`

When I run : _**"C:/Program Files/Oracle/VirtualBox/VBoxManage.exe" --version**_
I'm getting : _5.0.40r115130_

I'm running command prompt as Administrator. Here is a complete message :
```
L:\Homestead>vagrant up
The provider 'virtualbox' that was requested to back the machine
'homestead-7' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant detected that VirtualBox appears installed on your system,
but calls to detect the version are returning empty. This is often
indicative of installation issues with VirtualBox. Please verify
that VirtualBox is properly installed. As a final verification,
please run the following command manually and verify a version is
outputted:

C:/Program Files/Oracle/VirtualBox/VBoxManage.exe --version
```
