### ISSUE TITLE
Colored output on Windows

### ISSUE THREAD

**Issue by genebean** [mitchellh/vagrant#5041]
I am trying to make colors work on Windows. Normal PowerShell doesn't show them and [Maximus5/ConEmu](https://github.com/Maximus5/ConEmu), which supports ANSI colors out of the box, doesn't show colors either. I touched base with @Maximus5 via http://serverfault.com/questions/647986/conemu-powershell-ansi-colors and he said this is was something do do with Vagrant's output. Is there something I am missing or is there some other way to make the colors work?  FWIW, this is also true with [Packer](https://github.com/mitchellh/packer).

The only way I have been able get colors is by using Git Bash and by using [adoxa/ansicon](https://github.com/adoxa/ansicon) in a regular PowerShell session.

**Comment by mitchellh** [comment]
Vagrant explicitly disables colors on Windows in many cases right now because we don't have a good way to determine if they're enabled in the shell or not. Its better to be safe than to see a bunch of control characters in the output.

**Comment by genebean** [comment]
@mitchellh - any chance you could make that a preference or able to be toggled?  Same q holds for Packer too. It sure would be nice to be able to colorize my output.  Thanks!

**Comment by felipe1982** [comment]
In my ~/.bashrc (Cygwin) I have added

    alias vagrant="vagrant --color"
    alias v="vagrant" 
    alias vus="v up; v ssh"

this adds colours, and simplifies my typing, and make logging into boxes really fast and painless
