### ISSUE TITLE
chef-solo provisioner has nil shared_folders at configure

### ISSUE THREAD

**Issue by moreandres** [mitchellh/vagrant#5043]
I'm using chef-solo as provisioner and after upgrading to Vagrant 1.7.1 I'm seeing the following error when creating a new machine.

```
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/provisioners/chef/
provisioner/chef_solo.rb:117:in `share_folders': undefined method `+' for nil:Ni
lClass (NoMethodError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/provi
sioners/chef/provisioner/chef_solo.rb:31:in `configure'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/a
ction/builtin/provision.rb:76:in `block in call'
```

I had to define shared_folders to an empty array in chef_solo.rb's configure as a workaround.

```
  @shared_folders = []
  share_folders(root_config, "csc", @cookbook_folders)
```

Great tool, I hope this helps.

**Comment by mitchellh** [comment]
Do you have a Vagrantfile that can reproduce this? I'd like to see how this is possible...

**Comment by sethvargo** [comment]
This may be related to https://github.com/mitchellh/vagrant/issues/4988, but not sure.

**Comment by mitchellh** [comment]
Fixed
