### ISSUE TITLE
Use Same Vm for all docker projects

### ISSUE THREAD

**Issue by rewiko** [mitchellh/vagrant#5051]
Hi, 

I use docker with vagrant then I have created 2 VagrantFile:
I'm under the OS Windows:
this one, named 'DockerHostVagrantfile': 
``` ruby
Vagrant.configure("2") do |config|

config.vm.provision "docker"

config.vm.define "dockerhost"
config.vm.box = "ubuntu/trusty64"
config.vm.network "forwarded_port",
guest: 8080, host: 8080
config.vm.network "forwarded_port",
guest: 9200, host: 9200

config.vm.network "forwarded_port",
guest: 80, host: 80

config.vm.provider :virtualbox do |vb|
vb.name = "dockerhost"
end

end
```

and another name 'VagrantFile':

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
DOCKER_HOST_NAME = "dockerhost"
DOCKER_HOST_VAGRANTFILE = "./DockerHostVagrantfile"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
       config.vm.define "name_defined" do |a|

       # provider
        a.vm.provider "docker" do |d|
            d.build_dir = "."
            d.build_args = ["-t=name_defined"]
            #d.image = 'image_name_defined'
            d.ports = ["8080:8080","9200:9200", "80:80"]
            d.name = "name_defined"
            d.remains_running = true
            d.volumes = ["/:/vagrant"] 
            d.vagrant_machine = "#{DOCKER_HOST_NAME}"
            d.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
        end
    end
end
```

Then it's work fine, i have a VM with double port forward: (docker and host).

However, I would like to use this VM for all my project in other directory.
If I copy these files into an other directory, change name and set up the new docker and then i run 'vagrant up', but it try to create another VM with the same name. ( Maybe because it's stored into the .vagrant into the current directory).

How can I use the same VM for all my project? 
Maybe, using the VagrantFile of the VM into a directory into the HOME PATH, created the vm with a vagrant up. 
And then into a VagrantFile for docker, set the absolute path according to the OS.

What do you think? 

Have a good day.

**Comment by mitchellh** [comment]
Please ask these questions on the mailing list. If you ask it there I have an answer for you :) Thanks!
