### ISSUE TITLE
Windows salt-minion installation not running correctly

### ISSUE THREAD

**Issue by zmingee** [mitchellh/vagrant#5052]
First of all, part of this is very similar (possibly the same) to #4152, but with another issue.

The minion_config file does not get copied to the Windows guest upon installation. Well, it "does", but it copies before the salt-minion installation and then the installation overwrites the file. So, the copy isn't doing anything, really. But, I've put a workaround in my Vagrantfile and I've hit another issue.

Workaround:
```
if cfg[:saltprovision]
  then    vm_config.vm.provision :salt do |salt|
    salt.minion_config      = "./minion.conf"
  end
end
if cfg[:saltprovision] and cfg[:osFam] == 'win'
  then
    vm_config.vm.provision :shell, inline: "Copy-Item 'C:\\tmp\\minion' 'C:\\salt\\conf\\'"
    vm_config.vm.provision :shell, inline: "Restart-Service salt-minion"
    vm_config.vm.provision :shell, inline: "C:\\salt\\salt-call state.highstate"
end
```
minion_config file:
```
master: 10.10.2.9 
file_client: remote
```

The minion_id is not defined in the minion_config file, so it should use the hostname. To determine the hostname, salt-minion runs `net config server` and then pulls the `hostname` variable. However, the output of this command is the hostname *before* the `hostname` is set by Vagrant. Below is the output of `net config server` on the Windows guest:
```
xerxes:vagrant zane$ vagrant winrm <GUEST> -c 'net config server'
Server Name                           \\WIN--0 [OLD HOSTNAME - PRE VAGRANT]
Server Comment

Software version                      Windows Server 2012 R2 Standard
Server is active on
	NetbiosSmb (WIN--0)
	NetBT_Tcpip_{1F81F14F-241F-4EF8-8085-9FBDB1C71AC6} (WIN--0)


Server hidden                         No
Maximum Logged On Users               16777216
Maximum open files per session        16384

Idle session time (min)               15
The command completed successfully.
```

It seems that the `hostname` commands that run to set the hostname on Windows guests are leaving out a registry entry or something and thus the `net config server` command returns the incorrect name.

Below is the --debug log for Vagrant. Keep in mind that this is just the `vagrant provision --debug <GUEST>` command. If you need the full `vagrant up` please let me know. 

https://gist.github.com/zmingee/faaa3e161da417c50a13

**Comment by dragon788** [comment]
Typically hostname changes on Windows require a PC reboot, this may be why you are getting the wrong name returned. There was a change tested to try and workaround this, but it was apparently unsuccessful.

**Comment by obestwalter** [comment]
@sethvargo is this fixed with https://github.com/mitchellh/vagrant/pull/5437 also? @zmingee did you come back to this?

**Comment by sethvargo** [comment]
This looks to be fixed as of https://github.com/mitchellh/vagrant/pull/5437. If it is not, please open a new issue and follow the new issue template. Thanks! 😄
