### ISSUE TITLE
Freeze or dup global state data structures

### ISSUE THREAD

**Issue by cassianoleal** [mitchellh/vagrant#5060]
For some reason, two plugins are interfering with each other in a very odd manner.

[Vagrant-Butcher](https://github.com/cassianoleal/vagrant-butcher) has a [method](https://github.com/cassianoleal/vagrant-butcher/blob/81cc73c02f17af272a870bce02ff287190768a51/lib/vagrant-butcher/helpers/config.rb#L20-L26) to check whether a chef-client provisioner is running as it's only relevant if so.

[Vagrant-Cachier](https://github.com/fgrehm/vagrant-cachier) uses a [similar method](https://github.com/fgrehm/vagrant-cachier/blob/master/lib/vagrant-cachier/cap/linux/chef_file_cache_path.rb#L9) to learn if it needs to cache Chef cookbooks.

Vagrant has recently (I reckon on 1.7.0) made changes to that object and [a fix](https://github.com/cassianoleal/vagrant-butcher/commit/81cc73c02f17af272a870bce02ff287190768a51) was put in place on Butcher, but Cachier hasn't been fixed yet.

Now, for some reason, if you have both plugins installed, Butcher never does anything. Uninstalling Cachier "fixes" the problem.

More information on this bug report: https://github.com/cassianoleal/vagrant-butcher/issues/57

I reckon the internals of one plugin should not interfere on the internals of another, and I have no idea why this is happening.

Thanks!

**Comment by mitchellh** [comment]
I'd say we'll keep this a plugin issue. It is quite rare this happens and it would be hard to track down every mutable data structure. Let's just solve it on per-issue basis.
