### ISSUE TITLE
vagrant up fails with bosh-lite VagrantFile

### ISSUE THREAD

**Issue by codemugal** [mitchellh/vagrant#5065]
I am trying to setup a local cloud foundry instance using bosh-lite on my mac laptop.

I unzipped the contents of bosh-lite-master ran the following command

see below

sh-3.2#vagrant up --provider=virtualbox

Error Message I got

Bringing machine 'default' up with 'virtualbox' provider...

==> default: Box 'cloudfoundry/bosh-lite' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 2776
The box 'cloudfoundry/bosh-lite' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/cloudfoundry/bosh-lite"]
Error: 
sh-3.2#

**Comment by mitchellh** [comment]
Looks like this is working now, was likely an issue on our side with Atlas, but works for me!

**Comment by codemugal** [comment]
https://github.com/mitchellh/vagrant/issues/3589

Please follow the above discussion.  This solved my issue
