### ISSUE TITLE
Container can not be suspended or halted on docker-vm 

### ISSUE THREAD

**Issue by isaleh** [mitchellh/vagrant#5066]
hello,

when I try to run vagrant halt or vagrant suspend on a container running docker-host on windows 7 I get error message:

$ vagrant suspend
Vagrant attempted to call the action 'suspend' on the provider
'Docker (1de2724d1f6dbe9827df9b3a32fc718817b309e048784b0d108e880bcdb5e8f4)', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this
action, and should be reported.

vagrant halt and up again works fine on Ubuntu 14.10 but vagrant suspend does not work too.

you can use this example to reproduce it:

https://github.com/RobertBerger/vagrant-phusion-baseimage

**Comment by mitchellh** [comment]
Docker doesn't support suspending. However, we should clarify the message.

**Comment by stanislav-kobylansky** [comment]
Would be good to make it working in presence of the host VM. If docker is build (build_dir is defined) and doesn't start from image file, that feature sounds like good thing to have.

**Comment by mitchellh** [comment]
Fixed
