### ISSUE TITLE
Chef provisioners have no names (only type), breaks plugins.

### ISSUE THREAD

**Issue by jperville** [mitchellh/vagrant#5069]
Named provisioners were introduced in #4700 and should be backward compatible with the existing syntax. According to the notes of the PR,

```
The syntax of config.vm.provision has changed to config.vm.provision NAME, type: TYPE.
If no type is specified, the name is assumed to be the type.
This keeps backwards compatibility.
```

The backward compatibility part seems to be broken, at least for the vagrant-proxyconf plugin, which detects the presence of supported provisioners by scanning the name attributes for each entry in `@machine.vm.provisioners` (see https://github.com/tmatilai/vagrant-proxyconf/blob/v1.4.0/lib/vagrant-proxyconf/action/configure_chef_proxy.rb#L46).

I have instrumented the above code in the vagrant-proxyconf plugin to display the value of the name (and type attribute when present), like this: `puts [:name, :type].each_with_object({}) { |meth, memo| memo[meth] = prov.public_send(meth) if prov.respond_to?(meth) }.inspect`.

On Vagrant 1.6.5 I can see `{:name=>:chef_solo}`
With Vagrant 1.7.1, I can see `{:name=>nil, :type=>:chef_solo}`
In order to preserve backward compatibility on Vagrant 1.7+, the value of the name attribute should be `:chef_solo` (the name as the type attribute) and not `nil`.

My `Vagrantfile`:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box      = 'opscode-ubuntu-14.04-chef'
  config.vm.box_url  = 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box'

  config.vm.hostname = 'single'
  config.vm.provision(:chef_solo) do |chef|
    chef.add_recipe "apt::default"
  end
end
```

I have opened tmatilai/vagrant-proxyconf#101 to report the issue and tmatilai/vagrant-proxyconf#103 to fix it on the plugin side, but I still think that this should be fixed on vagrant side because it silently breaks many plugins.

**Comment by mitchellh** [comment]
Ugh sorry about this, totally didn't think this through that it might be used by plugins. Unfortunately, this looks pretty tough to fix... since we now use the name as a way to know whether to merge something. We could fix it by introducing a lot of cruft into Vagrant core, but I don't think its worth it probably. 

Sorry about that and I'll be more careful in the future.

**Comment by tknerr** [comment]
:+1: people will find suitable workarounds here in this thread. Did not think of it being public API either.

**Comment by cassianoleal** [comment]
Perhaps it would be a good idea to create a better defined public API for plugins?

Stuff such as finding out what OS runs on the guest, or which provisioners are configured are not very straightforward, requiring the plugin developer to read through source code and/or opening objects at runtime (I use pry-debugger/byebug for that).

Of course, once you find out you abstract it into a method and it lives there -- at least until something changes in Vagrant's guts that requires you to make changes, and some times even creating ugly case..when blocks to deal with different versions.

My experience with hooks have been hit-and-miss as well, and has required me to change plugin code as Vagrant evolved.
