### ISSUE TITLE
`vagrant ssh -c <command>` does not work on Windows if <command> has spaces in it

### ISSUE THREAD

**Issue by tknerr** [mitchellh/vagrant#5073]
Noticed with Vagrant 1.7.1 on Win7 64bit: 
```
C:\Repos\_github\bills-kitchen\target\build\repo\tmp>vagrant ssh -c "echo blaaaa"
The machine with the name 'blaaaa' was not found configured for
this Vagrant environment.

C:\Repos\_github\bills-kitchen\target\build\repo\tmp>vagrant ssh -c 'echo blaaaa'
The machine with the name 'blaaaa' was not found configured for
this Vagrant environment.
```

Using a command without spaces works:
```
C:\Repos\_github\bills-kitchen\target\build\repo\tmp>vagrant ssh -c "pwd"
/home/vagrant
Connection to 127.0.0.1 closed.
```

**Comment by mitchellh** [comment]
Uhhhh thats super weird, seems like a Windows command prompt problem (it probably splits on spaces and doesn't honor strings?). 

In that case, not sure if there is anything Vagrant can _reasonably_ do here. THoughts?

**Comment by tknerr** [comment]
Quick update: seems not to be a Windows command problem by itself.

Given this `x.bat`:
```bat
echo hello %1
```

I get this output:
```
C:\Repos\tmp>x foo bar
hello foo

C:\Repos\tmp>x 'foo bar'
hello 'foo

C:\Repos\tmp>x "foo bar"
hello "foo bar"

C:\Repos\tmp>x \"foo bar\"
hello \"foo bar\"

C:\Repos\tmp>x ^"foo bar^"
hello "foo bar"
```

**Comment by tknerr** [comment]
@mitchellh ahhh forget it -- not a Vagrant issue at all. It was vagrant-wrapper which lost the double quotes and was reported by @annih just a few days ago in org-binbab/gem-vagrant-wrapper#7

**Comment by ferventcoder** [comment]
Does vagrant ssh no longer use ssh on Windows?

**Comment by mitchellh** [comment]
@ferventcoder It does, if its available (and errors if not)

**Comment by ferventcoder** [comment]
I'll file a new issue. Not sure what I'm seeing but it's not an error.
