### ISSUE TITLE
Vagrant doesn't mount SMB share on guest

### ISSUE THREAD

**Issue by hmemcpy** [mitchellh/vagrant#5080]
Vagrant 1.7.1
Host OS: Windows 8.1
Guest OS: Server 2012 R2

I'm trying to use the default command to mount my shared folder via smb:

    config.vm.synced_folder ".", "/vagrant", type: "smb", create: true

After being prompted for the username and password, everything seems to be in order, however on the VM, the resulting script doesn't seem to be mounting to a local path. Here's the contents of `vagrant_smb.auth.ps1` from the guest OS:

    New-SmbMapping -RemotePath \\192.168.1.150\43444ce3a59a02ea4354b46f0b0d270f -UserName myUserName -Password mahPassword

And it doesn't seem to contain the local path (e.g. `C:\vagrant`), so it doesn't mount.

Is there anything I'm missing? Or is this possibly a bug?

Some additional output (with `--debug`)

     INFO interface: output: C:/Vagrant ==>
     INFO interface: output: ==> default: C:/Vagrant ==>
    ==> default: C:/Vagrant ==>
     INFO interface: output: \\192.168.1.150\43444ce3a59a02ea4354b46f0b0d270f
     INFO interface: output: ==> default: \\192.168.1.150\43444ce3a59a02ea4354b46f0b0d270f
    ==> default: \\192.168.1.150\43444ce3a59a02ea4354b46f0b0d270f
     INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "&('C:\\Users\\<username>\\.vagrant.d\\gems\\gems\\vagrant-windows-hyperv-1.0.3\\lib\\vagrant-windows-hyperv\\scripts\\upload_file.ps1')", "-vm_id", "'27c5ae55-1543-433b-9f1d-5749ff46a65c'", "-host_path", "'C:\\Users\\<username>\\AppData\\Local\\Temp\\vagrant-smb-auth20141229-9040-1xqfll9.ps1'", "-guest_path", "'c:\\tmp\\vagrant-smb-auth.ps1'", "-guest_ip", "'192.168.1.178'", "-username", "'vagrant'", "-password", "'vagrant'", "-ErrorAction", "Stop"]
    DEBUG subprocess: Selecting on IO
    DEBUG subprocess: stdout: C:\Users\<username>\AppData\Local\Temp\vagrant-smb-auth20141229-9040-1xqfll9.ps1
    c:\tmp\vagrant-smb-auth.ps1
    DEBUG subprocess: stdout: ===Begin-Output===
    {
        "message":  "OK"
    }
    ===End-Output===
    DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
    DEBUG subprocess: Exit status: 0
     INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "&('C:/Users/<users>/.vagrant.d/gems/gems/vagrant-windows-hyperv-1.0.3/lib/vagrant-windows-hyperv/scripts/run_in_remote.ps1')", "-guest_ip", "'192.168.1.178'", "-username", "'vagrant'", "-password", "'vagrant'", "-command", "'schtasks /create /sc ONLOGON /tn vagrant-smb-auth /tr \\\"powershell c:\\tmp\\vagrant-smb-auth.ps1\\\"'", "-ErrorAction", "Stop"]
    DEBUG subprocess: Selecting on IO
    DEBUG subprocess: stdout: WARNING: The task name "vagrant-smb-auth" already exists. Do you want to replace it (Y/N)?
    DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31996
    DEBUG subprocess: Exit status: 0

**Comment by mitchellh** [comment]
This looks like you're using some plugin `vagrant-windows-hyperv`. Please remove that and let me know if its still happening.

**Comment by hmemcpy** [comment]
Yes, you were right, I was using the [MSOpenTech/vagrant-windows-hyperv](https://github.com/MSOpenTech/vagrant-windows-hyperv). I used it mainly because it supports specifying the adapter to use with hyper-v in the Vagrantfile.

Anyway, I removed it, but now I have a different problem: it fails with `An error occurred executing a remote WinRM command.`. Here's the `--debug` output:

     ...
     INFO interface: detail: C:/Vagrant => c:/vagrant
     INFO interface: detail:     default: C:/Vagrant => c:/vagrant
        default: C:/Vagrant => c:/vagrant
    DEBUG winrmcommunicator: Checking whether WinRM is ready...
    DEBUG winrmshell: powershell executing:
    hostname
    DEBUG winrmshell: Exit status: 0
     INFO winrmcommunicator: WinRM is ready!
    DEBUG guest: Searching for cap: mount_smb_shared_folder
    DEBUG guest: Checking in: windows
    DEBUG guest: Found cap: mount_smb_shared_folder in windows
     INFO guest: Execute capability: mount_smb_shared_folder [#<Vagrant::Machine: default (VagrantPlugins::HyperV::Provider)>, "1b8e911897c735dbb42fd93c351bc1aa", "c:/vagrant", {:type=>:smb, :create=>true, :guestpath=>"c:/vagrant", :hostpath=>"C:/Vagrant", :disabled=>false, :smb_id=>"1b8e911897c735dbb42fd93c351bc1aa", :smb_host=>"192.168.0.107", :smb_username=>"<redacted>", :smb_password=>"<redacted>", :owner=>"vagrant", :group=>"vagrant"}] (windows)
    DEBUG winrmshell: powershell executing:
    function which {
        $command = [Array](Get-Command $args[0] -errorAction SilentlyContinue)
        if($null -eq $command)
        {
          exit 1
        }
        write-host $command[0].Definition
        exit 0
    }

    function test ([Switch] $d, [String] $path) {
      if(Test-Path $path)
      {
        exit 0
      }
      exit 1
    }

    function chmod {
      exit 0
    }

    function chown {
      exit 0
    }

    function mkdir ([Switch] $p, [String] $path)
    {
      if(Test-Path $path)
      {
        exit 0
      } else {
        New-Item $path -Type Directory -Force | Out-Null
      }
    }


    cmdkey /add:192.168.0.107 /user:<redacted> /pass:<redacted>
    exit $LASTEXITCODE
    DEBUG winrmshell: Exit status: 1
    ERROR warden: Error occurred: An error occurred executing a remote WinRM command.

    Shell: powershell
    Command: cmdkey /add:192.168.0.107 /user:<redacted> /pass:<redacted>
    Message: Command execution failed with an exit code of 1
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
    ERROR warden: Error occurred: An error occurred executing a remote WinRM command.
    ...

... and so on.

Any ideas?

**Comment by mlenormand** [comment]
Reproduced with Host Windows 7 and Guest Windows 2012 R2 Core.
No error, Windows username/password provided but no shared folder is not mounted.

Any ideas ?
Any alternative to upload file to the VM for provisionning ?
