### ISSUE TITLE
Ansible provisioner should support WinRM settings

### ISSUE THREAD

**Issue by lenaten** [mitchellh/vagrant#5086]
as result "vagrant provision" doesn't work, because ansible try connect with winrm protocol on ssh port.

this occurs on windows box with both ssh and winrm port forward.

as I understand from /plugins/providers/virtualbox/provider.rb, winrm has no chance.. (@machine.config.ssh.guest_port)
 ```
# Returns the SSH info for accessing the VirtualBox VM.
      def ssh_info
        # If the VM is not running that we can't possibly SSH into it
        return nil if state.id != :running

        # Return what we know. The host is always "127.0.0.1" because
        # VirtualBox VMs are always local. The port we try to discover
        # by reading the forwarded ports.
        return {
          host: "127.0.0.1",
          port: @driver.ssh_port(@machine.config.ssh.guest_port)
        }
      end
```

**Comment by gildegoma** [comment]
Thanks @lenaten for filing this issue. The Ansible provisioner was created long before the support for [Windows was added to Ansible capabilities](http://www.ansible.com/blog/windows-is-coming). 

Of course your request is valid and accepted. It will be handy in the future to instruct/detect when the guest VM is a Windows box, and therefore apply ad-hoc WinRM connectivity at Ansible level. I updated the issue title in this way and assign it to myself, but, please @lenaten (or anyone interested), feel free to announce if you want to work on a PR for that change.

For now, I think that you should be able to work around this issue with some extra variables to force the [Windows connection settings](http://docs.ansible.com/intro_windows.html):

```ruby
config.vm.provision "ansible" do |ansible|
  ansible.playbook = "provisioning/playbook.yml"
  # ...
  ansible.extra_vars = {
    ansible_ssh_user: "Administrator",
    ansible_ssh_pass: "SecretPasswordGoesHere",
    ansible_ssh_port: 5986,
    ansible_connection: "winrm"
  }
end

Note: So far, I haven't the time to verify myself, but I'll try to setup some Windows Guest VM within the next weeks and will give you some more news then. Please post us the results of your own experiments ;-)

**Comment by lenaten** [comment]
thanks @gildegoma, in the meantime I fixed it with ugly patch.
extra_vars is not enough in my case, because I have both, windows and linux machines.  
I hope I fix it's soon with prettier code that I can share..

**Comment by gildegoma** [comment]
@lenaten good to know, that would be awesome to receive a pull request from you. 

In the meantime, can you confirm that the above workaround would work for a single Windows VM? If not, could you please share some more hints?

**Comment by mihai-satmarean** [comment]
I am also blocked by this.
Ansible extra vars do not work for some reason that I cannot tell.
Windows 7 and windows 10 guests.
Than you for looking into it!

**Comment by nirving-versent** [comment]
I too am experiencing this issue, and referenced my config in https://github.com/mitchellh/vagrant/issues/6098

**Comment by gildegoma** [comment]
A fixing PR is coming... Early testers/reviewers will be very welcome within the following days, as this should be shipped by end of the month in the Vagrant 1.8.0 release.

**Comment by nirving-versent** [comment]
Would love to test, as it is stopping a project from using Vagrant.

**Comment by gildegoma** [comment]
@nirving-versent thanks for very quick feedback :heart_eyes: I'll keep you informed!

**Comment by gildegoma** [comment]
PR created: #6576, Feedbacks **welcome**!

So far, I ran some tests with a `Vagranfile` like this:

```ruby
Vagrant.configure(2) do |config|

  config.winrm.transport = :ssl
  config.winrm.ssl_peer_verification = false

  config.vm.define 'trusty' do |machine|
    machine.vm.box = "ubuntu/trusty64"
  end

  config.vm.define 'win8' do |machine|
    machine.vm.box = "my_win_box"
    machine.vm.communicator = "winrm"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = 'playbook-5086.yml'
    ansible.groups = { "windows" => ['win8'], "linux" => ['trusty'] }
  end

end
```

And the generated ansible inventory looks something like:

```
# Generated by Vagrant

win8 ansible_connection=winrm ansible_ssh_host=127.0.0.1 ansible_ssh_port=55986 \
ansible_ssh_user='vagrant' ansible_ssh_pass='vagrant'
trusty ansible_ssh_host=127.0.0.1 ansible_ssh_port=2222 ansible_ssh_user='vagrant' \
ansible_ssh_private_key_file='/.../.vagrant/machines/trusty/virtualbox/private_key'

[windows]
win8

[linux]
trusty
```

By forcing the `ansible_connection` mode in the inventory, there is no need to change anything in the `ansible-playbook` arguments.
If you want to use a static custom inventory, then you'll have either to set `ansible_connection=winrm` in your inventory, or as via the `raw_arguments` array.

:warning: :question: Please tell me if this is enough for your desired usages...

Notes: 

Ansible 1.9 does not seem to support WinRM in `:plaintext` mode (but it's coming in Ansible 2). For a basic/unsafe `winrm-ssl` environment, I had to monkey patch my ansible installation with a custom `callback_plugins` to skip the SSL certificate validation (see ansible/ansible#10294).

:syringe: If you have more advanced examples, please share them!

**Comment by gildegoma** [comment]
@lenaten @mihai-satmarean @nirving-versent could you please confirm if you're going to check #6576 until this Friday. I need your feedback asap, because the vagrant release is planned for next Monday.

**Comment by mihai-satmarean** [comment]
I would not be able since I am not running Vagrant from checkout.
but I would use it after is released and give you feedback

Thanks a lot!.


2015-11-25 21:08 GMT+01:00 Gilles Cornu <notifications@github.com>:

**Comment by nirving-versent** [comment]
Morning,
Will try it this afternoon. Did not realise it was available for testing, my bad.
—
Nicholas Irving
Versent
Level 4, 145 Russell Street, Melbourne VIC 3000

Mob: +61 4 0007 0562
Email: nicholas.irving@versent.com.au
Web: versent.com.au<http://www.versent.com.au/>


[cid:image001.png@01D0B3EC.43F3CF90]

**Comment by nirving-versent** [comment]
Not able to test, as I am on Macintosh and when I check out your version it fails with


/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- bundler (LoadError)

from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'

from /Users/nirving/Downloads/vagrant-gildegoma-5086-ansible-winrm/lib/vagrant/bundler.rb:6:in `<top (required)>'

from /Users/nirving/Downloads/vagrant-gildegoma-5086-ansible-winrm/lib/vagrant/pre-rubygems.rb:19:in `require_relative'

from /Users/nirving/Downloads/vagrant-gildegoma-5086-ansible-winrm/lib/vagrant/pre-rubygems.rb:19:in `<main>’


Regards

—
Nicholas Irving
Versent
Level 4, 145 Russell Street, Melbourne VIC 3000

Mob: +61 4 0007 0562
Email: nicholas.irving@versent.com.au
Web: versent.com.au<http://www.versent.com.au/>


[cid:image001.png@01D0B3EC.43F3CF90]

**Comment by gildegoma** [comment]
@mihai-satmarean @nirving-versent thanks for your responses. If you don't feel comfortable to test from source, no worries (it works as I expect, and as specified in unit tests). Most important to me is to be sure that your use cases are covered (see the usage [example above](https://github.com/mitchellh/vagrant/issues/5086#issuecomment-158794738)).

**Comment by gildegoma** [comment]
After a quick glance at @nirving-versent setup (#6098), it seems to match well.
