### ISSUE TITLE
SSL error when installing plugin

### ISSUE THREAD

**Issue by thasmo** [mitchellh/vagrant#5091]
This is what happens:
```
> vagrant plugin install vagrant-triggers
> Installing the 'vagrant-triggers' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing vagrant-triggers (0.5.0), and Bundler cannot continue.
Make sure that `gem install vagrant-triggers -v '0.5.0'` succeeds before bundling.

Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/gems/vagrant-triggers-0.5.0.gem)
```

Any idea what this means?

**Comment by sethvargo** [comment]
How do you have vagrant installed? What version of Vagrant are you running (`vagrant -v`)?

**Comment by thasmo** [comment]
@sethvargo, I'm running Vagrant 1.7.1 on Windows 8.1 64-bit via Cygwin, installed using the installer from vagrantup.com.

**Comment by thasmo** [comment]
Alright - running `vagrant plugin install vagrant-triggers` on the Windows CMD shell it worked. Seems to be a Cygwin problem or even just for my environment.

**Comment by thasmo** [comment]
Could that be a problem with the ruby version installed by/within the Cygwin environment or does the embedded ruby of Vagrant has a problem running under Cygwin? How can I find out?

**Comment by mitchellh** [comment]
That is pretty weird. Vagrant should be setting the exact same environmental variables and using the same executables on both systems so it shouldn't make a difference. 

It would be very helpful to get more debugging info here, but its not easy. Basically we need to know what SSL cert bundle it is using and why it might be different...

**Comment by thasmo** [comment]
I'd love to find out what's wrong, so if anybody has hints on what to look after I'm happy for every help I can get to solve this. Is there any ENV variable I could check? Is there any magic Ruby does? Thanks!

**Comment by mitchellh** [comment]
No magic, we're setting the `SSL_CERT_FILE` environmental variable which should be picked up by OpenSSL.

**Comment by thasmo** [comment]
Do I have to set it manually for some reason maybe?
http://apple.stackexchange.com/questions/76115/where-is-ruby-looking-for-ssl-cert-file

**Comment by mitchellh** [comment]
Oh oh oh, Windows might actually execute an exe for some things and a shell script for others. Can you  try `vagrant.exe` vs `vagrant` in `C:\HashiCorp\bin` and see if that makes a difference. If one is broken, that would be very telling.

**Comment by thasmo** [comment]
Adding `echo $SSL_CERT_FILE` to the file `C:\HashiCorp\Vagrant\bin\vagrant` on line 29 and running `vagrant plugin install vagrant-cachier` results in outputtin' `/cygdrive/c/HashiCorp/Vagrant/bin/../embedded/cacert.pem` before the error occurs again, on Cygwin. Windows doesn't use that file I guess, but running the same install command let's me install `vagrant-cachier` without problems.

**Comment by thasmo** [comment]
@mitchellh, running `/cygdrive/c/HashiCorp/Vagrant/bin/vagrant.exe plugin install vagrant-cachier` on Cygwin works!

**Comment by mitchellh** [comment]
@thasmo And can you confirm the shell file doesn't work? (There isn't a batch file, right? I think we got rid of that)

**Comment by mitchellh** [comment]
If thats the case, I probably know what it is.

**Comment by thasmo** [comment]
@mitchellh, confirming that `/cygdrive/c/HashiCorp/Vagrant/bin/vagrant plugin install vagrant-cachier` throws the error.

**Comment by mitchellh** [comment]
That helps narrow it down a ton. I'll take a look and get back to you if I have any questions.

**Comment by thasmo** [comment]
Awesome. Thanks!

**Comment by mitchellh** [comment]
I think I have the fix, can you try this locally: https://github.com/mitchellh/vagrant-installers/commit/553729617d59bd215d0d52c78a9fd3a33bf729c4

**Comment by thasmo** [comment]
@mitchellh, works! Tried installing and uninstalling - works fine! I leave it to you to close it. Thanks for the fix and supporting Cygwin, super awesome!

**Comment by mitchellh** [comment]
Fantastic. Closing, will be part of 1.7.2
