### ISSUE TITLE
suexec_cmd is not inherited from base Vagrantfile

### ISSUE THREAD

**Issue by antonsmyk** [mitchellh/vagrant#5092]
I don't have `sudo` on my minimal Solaris box, so I need to tell Vagrant to use `pfexec` instead. I have this in base Vagrantfile:
```
  config.vm.guest = :solaris
  config.solaris.suexec_cmd = 'pfexec'
```
But it does not take effect! Running `VAGRANT_LOG=debug vagrant halt` indicates that `sudo` is used.

When I add the same config params to my local Vagrant file instead, it works. But some other config like `config.ssh.insert_key = false` got inherited so I suspect it is Solaris guest plugin which is broken somehow (sorry, I can't do Ruby)

Here are my files:
```
$ cat ./.vagrant/machines/default/vmware_fusion/a6d16cf2-f9f2-48a3-a0fd-a27be1180305/Vagrantfile 
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.guest = :solaris
  config.solaris.suexec_cmd = 'pfexec'
end
```

```
$ cat ./Vagrantfile                                                                                                                     
Vagrant.configure(2) do |config|
  config.vm.box = "orcsoftware/solaris10_9_10-min"
#  config.solaris.suexec_cmd = 'pfexec'
end
```

**Comment by mitchellh** [comment]
Fixed in git. will be part of 1.7.2

**Comment by antonsmyk** [comment]
Installed 1.7.2 and confirmed bug fixed. Thanks for prompt action!
