### ISSUE TITLE
"HostName unknown" in vagrant ssh-config

### ISSUE THREAD

**Issue by hakamadare** [mitchellh/vagrant#5097]
On OS X 10.10.1, VMware Fusion 7.1.0:

```text
$vagrant --version
Vagrant 1.7.1
```

```text  
$ vagrant plugin list
vagrant-hostsupdater (0.0.11)
vagrant-librarian-puppet (0.7.1)
vagrant-puppet-install (2.7.0)
vagrant-reload (0.0.1)
vagrant-share (1.1.4, system)
vagrant-vbguest (0.10.0)
vagrant-vcloud (0.4.3)
vagrant-vmware-fusion (3.1.2)
vagrant-vyatta (0.0.4)
```

```text
$ vagrant status
Current machine states:
  
default                   running (vmware_fusion)  
```

```text
$vagrant ssh-config
Host default
  HostName unknown
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
```

```text
$ vagrant ssh
ssh: Could not resolve hostname unknown: nodename nor servname provided, or not known
```
This happens repeatedly with multiple different Vagrant boxes.  Why is HostName being populated with a value of "unknown" in the SSH config?

**Comment by sethvargo** [comment]
Hi @hakamadare,

What vagrant box are you using? Can you please post your `Vagrantfile`?

**Comment by hakamadare** [comment]
Hi folks!  Any further thoughts on this issue?  Can I provide any additional information?

**Comment by phinze** [comment]
Hey @hakamadare - sorry you're hitting this. Good news - I've been able to reproduce locally! I'm still working on narrowing it down to exact repro steps, but I can tell you that vagrant relies on VMWare Fusion's `vmrun getGuestIPAddress` command, which when we get into a bad state is the thing that returns "unknown".

So it may be an upstream bug or it may be something silly we're doing. Stay tuned! :tv:

**Comment by phinze** [comment]
AHA. So you get `unknown` out of `getGuestIPAddress` when `vmtoolsd` crashes (or is just not running) in the guest.

My suspicion would be the `AUTO_KMODS_ENABLED` flag you're flipping, which makes vmware-tools attempt to build missing kernel mods on boot, might be causing a build that screws up vmtools next boot. Testing that out now.

**Comment by hakamadare** [comment]
outstanding!

so, here's the sequence of events that led me to this course of action:

1. i'm testing a Puppet module; the test involves starting with a 64-bit Vagrant box and installing 32-bit glibc packages.

2. the simplest way to do this is to upgrade 64-bit and 32-bit glibc and kernel to the latest releases, since it's pretty much guaranteed that the box i'm using will not be patched, and i need all the various package versions to be in sync.

3. new kernel -> new VMware tools modules, hence the AUTO_KMODS_ENABLED.

if the conclusion of your troubleshooting is that i need to just not upgrade the kernel on a VMware Vagrant box, that's not the end of the world.  or alternately, if there's a better-supported procedure for upgrading the kernel on such a box, i'd be happy to do that instead.

thanks for your efforts!

**Comment by phinze** [comment]
Yeah from your description it does sound like _something_ fishy is going on that is preventing vmware-tools from properly starting. :fish: I've attempted to reliably reproduce the scenario locally to no avail. My recommendation would be to ensure you have a user/password that can log in, and slap a `v.gui = true` on next time you see this. I'm going to close this for now, but if you determine there's some issue that it seems like Vagrant should be handling better, feel free to reopen! :+1:
