### ISSUE TITLE
FTPS support

### ISSUE THREAD

**Issue by herrbischoff** [mitchellh/vagrant#5103]
I was wondering if you could implement that since unencrypted FTP connections should be a thing of the past for deployments. Researching a little, I found this class that already implements it and is MIT-licensed: https://github.com/bnix/double-bag-ftps

**Comment by sethvargo** [comment]
Hi @herrbischoff 

We already have SFTP for deploying FTP securely over SSH. I am not familiar with the FTPS protocol. Vagrant Push strategies can be fully implemented as Vagrant plugins. You can write a Vagrant plugin to add support for FTPS and, if it gains traction from the community, we can add support into Vagrant core.

Please let me know if you have any questions.
