### ISSUE TITLE
vagrant ssh does nothing if you forward the ssh port and also set config.ssh.port

### ISSUE THREAD

**Issue by ferventcoder** [mitchellh/vagrant#5111]
I have the following in my config:

```ruby
  config.vm.communicator = "winrm"
  config.ssh.port = 22
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
```

It doesn't auto forward, but I think I know why now. :)

**Comment by ferventcoder** [comment]
@mitchellh Figured out my own issue, which is that I don't need config.ssh.port to be explicitly set. It causes the port forward not to work. :/

**Comment by ferventcoder** [comment]
Is this expected behavior for it not to work correctly? Explains why the debug output showed it trying to connect to port 22.

**Comment by mitchellh** [comment]
I think you're looking for `config.ssh.guest_port` ?

If you set `config.ssh.port` that tells Vagrant "no matter what, connect to this _exact_ port for SSH"

**Comment by ferventcoder** [comment]
Yep, that's probably what I was running into. I figured it was just me being dumb. Thanks :)
