### ISSUE TITLE
Introduce alias `vagrant restart`, a more self-explanatory version of `vagrant reload`

### ISSUE THREAD

**Issue by ericandrewlewis** [mitchellh/vagrant#5117]
I think restart is more self-explanatory than reload.

**Comment by sethvargo** [comment]
@ericandrewlewis there's a long discussion (I can't find the ticket right now) about reload vs restart vs up vs down vs stop, etc. We have decided that `reload` is more semantic, especially with respect to hypervisors and cloud plugins. If you would like to use `vagrant restart`, you could write an open source a simple plugin that just calls reload under the hood. Please let me know if you would like some help on that.
