### ISSUE TITLE
vagrant box issue

### ISSUE THREAD

**Issue by WYSIATI** [mitchellh/vagrant#5119]
Hi! I have virtualbox and vmware fusion 7 on my mac os 10.10.  After `vagrant box add https://atlas.hashicorp.com/hashicorp/precise64`, I have the result `precise64           (virtualbox, 0)` from `vagrant box list`. Why doesn't it have vmware fusion 7 in the box?

**Comment by sethvargo** [comment]
Hi @WYSIATI, could you please ask these types of questions on the mailing list? We try to keep the GitHub issue tracker specific to issues and pull requests and use the mailing list for questions. Thanks! :smile: 

In short, you need to specify the `--provider` flag or set your provider in the Vagrantfile and just run `vagrant up`.
