### ISSUE TITLE
Problem setting hostname with VMware provider

### ISSUE THREAD

**Issue by technolo-g** [mitchellh/vagrant#5120]
Hi,
 I am having a problem where the 6th machine in a vagrant file is fairly repetably failing on `vagrant up`, but only twice. The third time it works. The TL;DR of the process is as follows:
```
vagrant up
<dockerhost01 - dockerhost05> come up and are provisioned as expected

dockerswarm01 fails with (but the machine exists):
==> dockerswarm01: Setting hostname...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

vagrant destroy -f dockerswarm01 # removes the host
vagrant up dockerswarm01 fails with (the host does not exist)
==> dockerswarm01: Running cleanup tasks for 'ansible' provisioner...
/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/buffered_io.rb:99:in `send': Broken pipe - send(2) (Errno::EPIPE)
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/buffered_io.rb:99:in `send_pending'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/buffered_io.rb:111:in `wait_for_pending_sends'
... <truncated>

vagrant up dockerswarm01 # And everything is ok
```

I have included the pertinent info here:
https://gist.github.com/technolo-g/c6cd4e125266b993c36d

**Comment by technolo-g** [comment]
Also, this was happening with both the old and new (released yesterday) version of the VMware provider plugin.

**Comment by dragon788** [comment]
I have noticed that when upping multiple machines that the system gets very I/O constrained, is it possible there is a race condition from not enough resources?

**Comment by mitchellh** [comment]
We haven't been able to reproduce this locally. This may have been a net-ssh bug fixed upstream... perhaps. I'm not sure. Without a consistent reproduction case or digging by folks who can reproduce this, we'll have a hard time fixing this. Sorry!

**Comment by Orpere** [comment]
hi guys I also have a broken pipe please check the log bellow it look like is net-ssh and I am using fusion 8.5 and latest vagrant 
/opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:44:in `write': Broken pipe (Errno::EPIPE)
	from /opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:44:in `negotiate!'
	from /opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:32:in `initialize'
	from /opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:84:in `new'
	from /opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:84:in `initialize'
	from /opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:233:in `new'
	from /opt/vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:233:in `start'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/ssh/communicator.rb:408:in `block (2 levels) in connect'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/ssh/communicator.rb:382:in `block in connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/ssh/communicator.rb:381:in `connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/ssh/communicator.rb:82:in `block in wait_for_ready'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/plugins/communicators/ssh/communicator.rb:60:in `wait_for_ready'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
