### ISSUE TITLE
1.7.2 Puppet provisioning error puppet.rb:28:in `digest': no implicit conversion of Pathname into String

### ISSUE THREAD

**Issue by biemond** [mitchellh/vagrant#5123]
Hi 

I get this error with version 1.7.2 when I do vagrant up, I got this on vbox and vmware fusion

        /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:28:in `digest': no implicit conversion of Pathname into String (TypeError)
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:28:in `hexdigest'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:28:in `block in configure'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:27:in `each'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:27:in `each_with_index'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:27:in `configure'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:76:in `block in call'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:75:in `each'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:75:in `call'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/action/set_name.rb:50:in `call'

**Comment by mitchellh** [comment]
Fixed. I'm hotfixing 1.7.2 tonight with this, you should be able to use it tomorrow.

**Comment by joaquimserafim** [comment]
:+1:  thanks @mitchellh

**Comment by dhaines** [comment]
Can a new release be made for these hotfixes? Something like 1.7.2.1? I mean, it's not 1.7.2 anymore after the change.

**Comment by mitchellh** [comment]
@dhaines 1.7.2.1 is a good idea. Noted for the future. For now, its just already redone as 1.7.2

**Comment by ccolorado** [comment]
Same error ?
```bash
    $ vagrant -v
    Vagrant 1.7.2
    ruby-2.1.1[0]A(3:0)[ccolorado@waffle ~/dev/devbox]
    $ vagrant up
    Bringing machine 'default' up with 'virtualbox' provider...
    /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:28:in `digest': no implicit conversion of Pathname into String (TypeError)
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:28:in `hexdigest'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:28:in `block in configure'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:27:in `each'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:27:in `each_with_index'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/provisioners/puppet/provisioner/puppet.rb:27:in `configure'
    ... 30+ lines
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
            from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```

**Comment by Carpetsmoker** [comment]
> Can a new release be made for these hotfixes? Something like 1.7.2.1? I mean, it's not 1.7.2 anymore after the change.

+1 on that. Right now it's very difficult to see that something has been fixed... I *think* I'm running the latest version, but actually I'm not!

(Thank you for the quick fix btw.)

**Comment by ccolorado** [comment]
I'll go ahead and apply the patch manually for the time being as I have a feeling my package manger wont recognize that the package needs an upgrade. 
https://github.com/mitchellh/vagrant/commit/95e1c19f225ef8fc14c958f7f2bdf6c29691817a
