### ISSUE TITLE
500 error when adding box, possible docs issue

### ISSUE THREAD

**Issue by caseylang** [mitchellh/vagrant#5125]
After upgrading vagrant to 1.7.2, when I ran `vagrant up` I would get the following warning:
```
==> default: There was a problem while downloading the metadata for your box
==> default: to check for updates. This is not an error, since it is usually due
==> default: to temporary network problems. This is just a warning. The problem
==> default: encountered was:
==> default:
==> default: The requested URL returned error: 500 Internal Server Error
==> default:
==> default: If you want to check for box updates, verify your network connection
==> default: is valid and try again.
```

A similar error would occur when running `vagrant box add hashicorp/precise64 --provider vmware_fusion`
```
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: https://atlas.hashicorp.com/hashicorp/precise64
Error: The requested URL returned error: 500 Internal Server Error
```

I resolved this issue by creating an Atlas login and associating it with my machine using `vagrant login`. 

If a login to Atlas is now required for all boxes, would it be possible to update the error message letting the user know that? If nothing else, could the [docs page](https://docs.vagrantup.com/v2/getting-started/boxes.html) mention that a login is necessary?

**Comment by pearkes** [comment]
@caseylang Thanks for reporting this.

I'm having trouble reproducing this consistently, but have seen the error both in Vagrant and via curl. We're tracking it down now, thanks!

**Comment by pearkes** [comment]
Oh and wanted to add this shouldn't be affected by authentication at all – I think it's a transient error that you just didn't hit again after authenticating. But, let me know if you think that may be incorrect.

**Comment by pearkes** [comment]
We're continuing to debug this, but it seemed to be an issue affecting one web server serving JSON data for Vagrant. That machine has been replaced, so we should no longer see this at the moment. The root cause is still being investigated. Thanks!

**Comment by caseylang** [comment]
Thanks for getting to it so fast. If there is any additional information I can provide, please let me know.

**Comment by sethvargo** [comment]
@caseylang we determined this to be a bug in Vagrant. The issue is that your authentication token is not being passed to the downloader. As a workaround (until there's a proper fix in Vagrant), add the following to your .bashrc or .zshrc:

```bash
export ATLAS_TOKEN=`cat ~/.vagrant.d/data/vagrant_login_token`
```

**Comment by pearkes** [comment]
This was a separate issue – exceptions in Atlas. Normally we would be notified for exceptions of this nature but because it's cause was in a Ruby C extension, our exception tracking system was bypassed. 

Debug logs (`VAGRANT_LOG=info ...`) if you ever see it again, but we did retrieve relevant debugging information before cycling the machines. Glad you reported!

**Comment by caseylang** [comment]
aww gee... I feel so valued :blush:. Thanks for tracking it down. I'll post log info if it happens again.
