### ISSUE TITLE
Create guest synced folder path with same owner/group

### ISSUE THREAD

**Issue by maspwr** [mitchellh/vagrant#5126]
In line https://github.com/mitchellh/vagrant/blob/b2b79a4ea88a7b32e3fb055b35842b75180a20bf/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb#L36 the following code:

```ruby
# Create the guest path if it doesn't exist
machine.communicate.sudo("mkdir -p #{expanded_guest_path}")
```

will create the guest path if it doesn't already exist. However it will be owned by root. I think it makes more sense to have the directory path created chowned by `mount_oid` and `mount_gid`.

**Comment by mitchellh** [comment]
It is chowned later down.
