### ISSUE TITLE
share.html docs refer to a non-existent page

### ISSUE THREAD

**Issue by arun-gupta** [mitchellh/vagrant#5127]
https://docs.vagrantup.com/v2/getting-started/share.html talks about "It should load the index page we setup in the previous pages."

Starting the document flow from https://docs.vagrantup.com/v2/getting-started/index.html and reaching up to this point does not require setting up index.html page.

Either the instructions need to include setting up index.html page, or should be clarified accordingly.

**Comment by mitchellh** [comment]
Fixed
