### ISSUE TITLE
VirtualBox VM is created in incorrect folder when profile name contains non-ASCII characters

### ISSUE THREAD

**Issue by axtavt** [mitchellh/vagrant#5128]
VirtualBox VMs on Windows are supposed to be created in `C:\Users\${username}\VirtualBox Vms`. However, when username conains non-ASCII characters, Vagrant VMs are actually created in a different folder, with incorrectly encoded `${username}` part. In particular, it means that Vagrant fails to run without admin priviledges, because it cannot create these folders in `C:\Users`.

This behavior only appeared after upgrade to 1.7.1, and was introduced by commit 2385305f6f30d2383a82590471bba420449cac2a. If frozen strings is the only problem solved by this change, I think `map` can be used instead to solve both problems:
```
@command = @command.map { |s| s.encode(Encoding.default_external) }
```

**Comment by sethvargo** [comment]
@axtavt would you like to submit a PR for this?

**Comment by mitchellh** [comment]
Fixed
