### ISSUE TITLE
Vagrant Share issue

### ISSUE THREAD

**Issue by amirasulin** [mitchellh/vagrant#5129]
Hi,
I have followed the getting started guide to use vagrant share
please see the following output which advise to report is as a bug.
Thanks,
Amir

```
C:\>vagrant share
==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:
    default: Local HTTP port: 4567
    default: Local HTTPS port: disabled
    default: Port: 2222
    default: Port: 4567
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
    default: Share will be at: petite-fleece-7925
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
```

**Comment by sethvargo** [comment]
Hi @amirasulin,

Can you please run the share command with [Vagrant debug mode on](http://docs.vagrantup.com/v2/other/debugging.html) and gist the output?

**Comment by amirasulin** [comment]
Hi,
Managed to resolved it, looks like a firewall issue
Thanks a lot,
Amir

**Comment by sethvargo** [comment]
Hi @amirasulin 

I am glad you were able to get it figured out!

**Comment by mattPiratt** [comment]
same for me today:

DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: proxy:1426528979,log,[INFO] Restricting ports to: [3456 2200 3456]
proxy:1426528979,log,[DEBUG] proxy: Connecting to mux server at register.vagrantshare.com:8000
DEBUG helper: Proxy message: ["log", "[INFO] Restricting ports to: [3456 2200 3456]"]
DEBUG helper: Proxy message: ["log", "[DEBUG] proxy: Connecting to mux server at register.vagrantshare.com:8000"]
DEBUG subprocess: stdout: proxy:1426528979,log,[ERR] proxy: Failed to start sharing: Failed to connect to mux server: dial tcp: lookup register.vagrantshare.com: no DNS servers
DEBUG helper: Proxy message: ["log", "[ERR] proxy: Failed to start sharing: Failed to connect to mux server: dial tcp: lookup register.vagrantshare.com: no DNS servers"]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 1
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000000029926c0>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::Share::Errors::ProxyExit: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.>
ERROR vagrant: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.3/lib/vagrant-share/activate.rb:1416:in `block in execute'

**Comment by rigobcastro** [comment]
Skype uses the 80 port, change it or start Skype after of Vagrant share.
