### ISSUE TITLE
specifying a synced_folder at "." replaces the default (/vagrant) share

### ISSUE THREAD

**Issue by jheys** [mitchellh/vagrant#5131]
**vagrant**: 1.7.2
**VirtualBox**: 4.3.20r96996
**Host**: Mac OS X 10.10.1

If/when specifying a `synced_folder` entry at the project root ("."), the default `/vagrant` synced_folder no longer gets mounted. My understanding was that the /vagrant share **ALWAYS** gets mounted (unless disabled in the Vagrantfile).

I'm not sure if this is the intended result, but this is definitely a new (and potentially **breaking**) behavior. In previous versions, specifying a `synced_folder` at this location would simply result in an additional mount.

Running `vagrant up` with the Vagrantfile below will illustrate this behavior:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/foo", create: true,
    mount_options: ["dmode=777,fmode=777"]
end
```
You'll see something like this near the end of the output:
```
...
==> default: Mounting shared folders...
    default: /foo => /some/folder
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
...
```
Notice the `/vagrant` folder is not listed. The expected output (snippet) would be something like this:
```
...
==> default: Mounting shared folders...
    default: /foo => /some/folder
    default: /vagrant => /some/folder
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
...
```

As further evidence, you can call `vagrant ssh -c 'ls /vagrant'` and notice that `Vagrantfile` is not listed.

**Comment by mitchellh** [comment]
Hi! 

Perhaps this isn't well documented enough but this is working as intended. You can specify a different `id: "foo"` (replace foo with whatever you want) option to make this not happen. The reason this happen is by default it uses the host path as the ID for a synced folder, allowing you to override existing synced folders.

**Comment by jheys** [comment]
Yes, that's what I *thought* would happen. However, adding the id does not make the /vagrant folder mount as expected.

This yields the same result:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/foo", id: "foo", create: true,
    mount_options: ["dmode=777,fmode=777"]
end
```

**Comment by jheys** [comment]
Wouldn't it make more sense to use the guest path (rather than the host path) as the ID since that has to be unique?
