### ISSUE TITLE
VMWare Workstation Plugin Version 3.2.0 Breaks Vagrant

### ISSUE THREAD

**Issue by uchagani** [mitchellh/vagrant#5132]
vagrant: 1.6.5
vagrant-vmware-workstation = 3.2.0
windows server 2012 host
windows 7 guest

Bringing up a box i've been using for months starts craping out with the error:

```
 INFO interface: error: Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

Full log at: https://gist.github.com/uchagani/37df2253695cc24d1176

How do I downgrade an installed plugin???

**Comment by sethvargo** [comment]
Hi @uchagani 

I am sorry you are having problems with the new plugin. I'll look at the debug log and try to reproduce, but you can downgrade by doing the following:

```shell
vagrant plugin uninstall vagrant-vmware-workstation
vagrant plugin install vagrant-vmware-workstation --plugin-version 3.1.2
```

**Comment by uchagani** [comment]
@sethvargo it looks like an IP Address problem.  When Vagrant runs ```getGuestIPAddress``` from ```vmrun``` it gets some ```169.254.247.160```

When I run that command manually I get the correct IP Address.

**Comment by mitchellh** [comment]
I'm not sure how running that manually is different from Vagrant running it. Any ideas?

**Comment by uchagani** [comment]
The only thing I can think of is the timing of it. Version 3.20 of the plug
in is supposed to ignore bad IP. I wonder if it's doing that.

**Comment by mitchellh** [comment]
3.2 just ignores if its an invalid IP in its format. There was another bug where `getGuestIPAddress` would return strings (non-IPs) and this caused failures. This won't happen anymore. I don't think what you're seeing is related.

**Comment by uchagani** [comment]
Closing this out.  Turns out it was being caused by a secondary NIC that I was adding in the base box.  removing that fixes the issue.
