### ISSUE TITLE
specifying unique ID for synced_folder at "." does not work as expected

### ISSUE THREAD

**Issue by jheys** [mitchellh/vagrant#5133]
**vagrant**: 1.7.2
**VirtualBox**: 4.3.20r96996
**Host**: Mac OS X 10.10.1

As reported in #5131, defining a `synced_folder` in the project folder now omits the default `/vagrant` mount. However, adding an unique ID value does **NOT** make the `/vagrant` share mount as stated.

In the example Vagrantfile below, I've specified an ID of `"foo"` as suggested. If/when you `vagrant up` this file, you will notice the `/vagrant` folder does not mount as expected.

Again, in previous versions of vagrant this would have mounted both `/foo` and `/vagrant` folders in the guest OS (with or without the ID)!

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/foo", id: "foo", create: true,
    mount_options: ["dmode=777,fmode=777"]
end
```

**Comment by osroot25** [comment]
If I read the changelog correctly, this behavior was changed intentionally in 1.7.0 in https://github.com/mitchellh/vagrant/pull/4675

**Comment by sethvargo** [comment]
This is worked as intended. Please read the discussion in 4675 for more information. Thanks!
