### ISSUE TITLE
Enhanced support for CoreOS

### ISSUE THREAD

**Issue by flasheater** [mitchellh/vagrant#5135]
There are two things Vagrant could do, that would ease working with CoreOS images.

### 1. Set some CoreOS-specific stuff for providers
```
    config.vm.provider :vmware_fusion do |v, override|
      v.vmx["serial0.present"] = "TRUE"
      v.vmx["serial0.fileType"] = "file"
      v.vmx["serial0.fileName"] = serialFile
      v.vmx["serial0.tryNoRxLoss"] = "FALSE"
    end
    config.vm.provider :virtualbox do |vb, override|
      vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
      vb.customize ["modifyvm", :id, "--uartmode1", serialFile]
    end
```

These are some suggestions taken from the coreos github repo which provides a "minimal" CoreOS [Vagrantfile](https://github.com/coreos/coreos-vagrant/blob/master/Vagrantfile). 

### 2. Run a discovery service internally to easily form clusters. 

The problem with the current approach of using the [https://discovery.etcd.io/](public CoreOS discovery service) is that after every ```vagrant destry``` one needs to request a new token. Running a local discovery service is pretty trivial as one simply has to start ```etcd``` with the ```--discovery``` flag. The challenge lies in how to inject the local discovery service URL into [cloud-config](https://github.com/coreos/coreos-vagrant/blob/master/user-data.sample), a CoreOS-specific provisioner. 

One possible solution could be to add ```cloud-config``` as a supported provisioner. That way cloud-config data would be first-class in Vagrant and discovery URL injection trivial. The downside would be that right now, cloud-config is CoreOS-specific, but the same could be argued for the docker provisioner.

**Comment by mitchellh** [comment]
I'd be happy to do these. The former I think does make more sense in the Vagrantfile. I don't want to add a serial console to every machine. The 2nd I'm more curious about. If you have recommendations for how to do that in the context of Vagrant I'd be happy to.
