### ISSUE TITLE
VBoxManage error on 'vagrant destroy'

### ISSUE THREAD

**Issue by vmutu** [mitchellh/vagrant#5143]
Hello,

I am encountering the following error when using the docker provider to destroy running containers:
```
$ vagrant up --provider=docker
Bringing machine 'phusion' up with 'docker' provider...
==> phusion: Docker host is required. One will be created if necessary...
    phusion: Docker host VM is already ready.
==> phusion: Syncing folders to the host VM...
    phusion: Mounting shared folders...
    phusion: /var/lib/docker/docker_1420742725_6808 => /Users/Valeriu/Developer/crane/Test
==> phusion: Warning: When using a remote Docker host, forwarded ports will NOT be
==> phusion: immediately available on your machine. They will still be forwarded on
==> phusion: the remote machine, however, so if you have a way to access the remote
==> phusion: machine, then you should be able to access those ports there. This is
==> phusion: not an error, it is only an informational message.
==> phusion: machine, then you should be able to access those ports there. This is                                                                                                    [0/4680]
==> phusion: not an error, it is only an informational message.
==> phusion: Creating the container...
    phusion:   Name: Test_phusion_1420742727
    phusion:  Image: phusion/baseimage
    phusion:    Cmd: /sbin/my_init --enable-insecure-key
    phusion: Volume: /var/lib/docker/docker_1420742725_6808:/vagrant
    phusion:   Port: 127.0.0.1:2222:22
    phusion:  
    phusion: Container created: 40b994fdac6921f3
==> phusion: Starting container...
==> phusion: Waiting for machine to boot. This may take a few minutes...
==> phusion: Machine booted and ready!
==> phusion: Running provisioner: shell...
    phusion: Running: inline script
==> phusion: Hello from docker!
$ vagrant status
Current machine states:

phusion                   running (docker)

The container is created and running. You can stop it using
`vagrant halt`, see logs with `vagrant docker-logs`, and
kill/destroy it with `vagrant destroy`.
$ vagrant ssh 
==> phusion: SSH will be proxied through the Docker virtual machine since we're
==> phusion: not running Docker natively. This is just a notice, and not an error.
Warning: Permanently added '172.17.0.3' (RSA) to the list of known hosts.
root@40b994fdac69:~# logout
Connection to 172.17.0.3 closed.
Connection to 127.0.0.1 closed.
$ vagrant destroy
    phusion: Are you sure you want to destroy the 'phusion' VM? [y/N] y
==> phusion: Stopping container...
==> phusion: Deleting the container...
==> phusion: Running cleanup tasks for 'shell' provisioner...
==> phusion: Removing synced folders...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["sharedfolder", "add", "b0634a0b-5fbb-483b-a169-6a23f29a27de", "--name", "vagrant", "--hostpath", "/Users/Valeriu/Developer/crane/Test/docker"]

Stderr: VBoxManage: error: The machine 'docker_default_1420682398460_23604' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp
```

I am running:
Mac OS X 10.9.2
VirtualBox 4.3.20r96996
Vagrant 1.7.2

Here are my Vagrantfile's:
```
$ cat Vagrantfile
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048] # Specify how much memory the VM can use
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on", "--cpus", 4]
  end

  config.vm.define "phusion" do |v|
    v.vm.provider "docker" do |d|
      d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
      d.image = "phusion/baseimage"
      d.has_ssh = true
      d.vagrant_vagrantfile = "./docker/Vagrantfile"
    end

    v.ssh.username = "root"
    v.ssh.private_key_path = "phusion.key"
  
    v.vm.network :private_network, ip: "10.10.10.11"
    v.vm.provision "shell", inline: "echo Hello from docker!"

    v.vm.synced_folder "~/Test/", "/vagrant"
  end
end

$ cat docker/Vagrantfile 
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "centos6.4_epel"
  config.vm.provision "docker"
  config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
end
```

Note that "centos6.4_epel" is a Centos 6.4 Virtualbox box with epel yum repo installed and enabled.

Do you know what could be the cause for this error?

**Comment by mpchlets** [comment]
I get the same error - and can recreate it with as little as:

    config.vm.define "code" do |v|
      v.vm.synced_folder ".", "/home/app/code", mount_options: ["dmode=777,fmode=666"]
      v.vm.provider "docker" do |d|
        d.name = "code"
        d.image = "busybox"
        d.cmd = [ "tail", "-f", "/dev/null" ]
        d.force_host_vm = true
        d.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
      end
    end

If I build from source instead of using a docker image, this also affects reload, and gives an error at removing sync folder:

    ==> code: Stopping container...
    ==> code: Deleting the container...
    ==> code: Removing built image...
    ==> code: Removing synced folders...
    There was an error while executing `VBoxManage`, a CLI used by Vagrant
    for controlling VirtualBox. The command and stderr is shown below.
    
    Command: ["sharedfolder", "add", "229f67b0-6636-4981-928e-f9e84a56a2f2", "--name", "vagrant", "--hostpath", "/home/user/app/code"]
    Stderr: VBoxManage: error: The machine 'dockerhost' is already locked for a session (or being unlocked)
    VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee nsISupports
    VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 1002 of file VBoxManageMisc.cpp

It seems that vagrant attempts to alter the host vm vagrant mount. Even if I disable the /vagrant mount from the host machine, I get this error.

**Comment by msumme** [comment]
I am also having the same problem.

**Comment by mpchlets** [comment]
I have worked around this issue, I am pretty sure by moving my d.vagrant_vagrantfile out of the same directory that I am sharing.

**Comment by vmutu** [comment]
@mpchlets where did you place your d.vagrant_vagrantfile ?

Please note that in my original post the 2 Vagrantfiles I'm using are already in 2 different directories.

**Comment by mpchlets** [comment]
I had the d.vagrant_vagrantfile in a subdirectory, but I did also disable all the sharing of the default . directory to /vagrant, I think that helped, whereas it did not when they were in the same directory:

` config.vm.synced_folder ".", "/vagrant", disabled: true`

**Comment by dklotz** [comment]
I have the same issue (on all vagrant destroys of docker containers in a VirtualBox VM) with OS X 10.9.5, vagrant 1.7.2 and VirtualBox 4.3.20r96996. The "workaround" of disabling sharing of /vagrant completely would require all our projects to be restructured, something that I would rather not do just to work around a bug in Vagrant/VirtualBox...

**Comment by oxygen0211** [comment]
I'm currently investigating this because I'm experiencing this problem reliably on every destroy (disabling synced folders is not an option in my use case). As it looks to me, this is caused by the docker host still having the shared folders mounted when the virtualbox provider is trying to delete them.

I have a solution which unmounts and removes the container's synced folders which I will submit once it's tested enough, but this will also be caused by some provisioners (in my case Puppet). They are mounting shared folders with their modules which also seem to be still mounted when removing them on the VirtualBox layer. For this I'm still searching for a stable solution to integrate it into the code.

**Comment by schmunk42** [comment]
@oxygen0211 Do you have your `d.vagrant_vagrantfile` inside your project, usually mounted in `/vagrant` in the VM? If so, move it away, it must not be in any synced folder of the VM.

**Comment by oxygen0211** [comment]
@schmunk42 Thanks, this is a good point. In the project causing this behavior we in fact have the vagrantfile ( and the vagrant folders) in the folder synced to /vagrant. I will try if restructuring the synced folders solves all of our problems next week and see if there is still something open for me to do on this.

Can you give me some context on what happens there? As far as I have seen, there is no unmount/cleanup of the synced folders for the containers on the docker host by the docker provider, will this be handled by the virtualbox provider (I haven't had such a close look at the VB provider by now)?

**Comment by schmunk42** [comment]
@oxygen0211 I can just give you a wild guess :) Looks like the Vagrantfile for the docker host is kinda locked, when the shared folder is removed. But I don't know about any details...

**Comment by oxygen0211** [comment]
Hi, I just tried to restructure our synced folders, but that didn't help in my case. I now have the following structure: The vagrantfile is located in the project root as well as some folders which will be synced to subdirectories of /vagrant. config.vm.synced_folder ".", "/vagrant", disabled: true is activated for all VMs. The docker host (d.vagrant_vagranfile) is located in an own directory (docker-host) located on the same parent directory as the project root.

I just saw this in the output of 
```
vagrant destroy --debug
```

```
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SyncedFolders:0x3ee2510>
 INFO synced_folders: Synced Folder Implementation: virtualbox
 INFO synced_folders:   - /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513: .../docker-host/manifests => /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513
 INFO synced_folders:   - /tmp/vagrant-puppet/modules-60e3caf99ebed2a5eeb80f4b10a07c69: .../docker-host/modules => /tmp/vagrant-puppet/modules-60e3caf99ebed2a5eeb80f4b10a07c69
 INFO synced_folders:   - a5747b4840: ... => /var/lib/docker/docker_1430740726_37166
 INFO synced_folders:   - ab70688030: ... => /var/lib/docker/docker_1430740726_946
 INFO synced_folders:   - 72e3631509: ... => /var/lib/docker/docker_1430740726_33779
 INFO synced_folders:   - 368a341968: .../puppet-modules/manifests => /var/lib/docker/docker_1430740726_50610
 INFO synced_folders:   - 8df5185706: .../puppet-modules/modules => /var/lib/docker/docker_1430740726_96496
 INFO synced_folders:   - 1004fd4852: ... => /var/lib/docker/docker_1430740754_72971
 INFO synced_folders:   - 30336f324: ... => /var/lib/docker/docker_1430740762_96699
 INFO synced_folders:   - b44a649450: ... => /var/lib/docker/docker_1430740770_88906
 INFO synced_folders:   - be054d4857: ... => /var/lib/docker/docker_1430740770_91096
 INFO synced_folders:   - a55f3f5835: ... => /var/lib/docker/docker_1430740784_26887
 INFO synced_folders: Invoking synced folder prepare for: virtualbox
 INFO subprocess: Starting process: ["D:\\Programme\\virtual box\\VBoxManage.exe", "setextradata", "231b52a1-058a-4c6b-bb21-c46c37ffc505", "VBoxInternal2/SharedFoldersEnableSymlinksCreate/tmp_vagrant-puppet_manifests-a11d1078b1b1f2e3bde
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["D:\\Programme\\virtual box\\VBoxManage.exe", "sharedfolder", "add", "231b52a1-058a-4c6b-bb21-c46c37ffc505", "--name", "tmp_vagrant-puppet_manifests-a11d1078b1b1f2e3bdea27312f6ba513", "--hostpath", "
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: VBoxManage.exe: error: The machine 'docker-host_default_1430740298561_4699' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1001 of file VBoxManageMisc.cpp
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 1
ERROR warden: Error occurred: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["sharedfolder", "add", "231b52a1-058a-4c6b-bb21-c46c37ffc505", "--name", "tmp_vagrant-puppet_manifests-a11d1078b1b1f2e3bdea27312f6ba513", "--hostpath", "C:/Users/j.engelhardt/git/dt-integration-test/docker-host/manifests"]

Stderr: VBoxManage.exe: error: The machine 'docker-host_default_1430740298561_4699' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1001 of file VBoxManageMisc.cpp

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-df6e6421b269e77bfaa3c2557e34b608
 INFO environment: Released process lock: 5f2ad23d18e3054899dcdc8a0d490cc9
ERROR warden: Error occurred: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["sharedfolder", "add", "231b52a1-058a-4c6b-bb21-c46c37ffc505", "--name", "tmp_vagrant-puppet_manifests-a11d1078b1b1f2e3bdea27312f6ba513", "--hostpath", "C:/Users/j.engelhardt/git/dt-integration-test/docker-host/manifests"]

Stderr: VBoxManage.exe: error: The machine 'docker-host_default_1430740298561_4699' is already locked for a session (or being unlocked)
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Machine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 1001 of file VBoxManageMisc.cpp

 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x42c17e8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x42c1818>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
```
This raises two questions for me:

a: Why is sharedfolder add called on vagrant destroy? According to how I understood the code, this is caused by /vagrant/lib/vagrant/action/builtin/synced_folders being called which first tries to set up the synced folders and then (after the machine is set up - I'm not sure on what point in the lifecycle app.call will return to here) disable and then remove them. Did I understand that correctly or is something else happening? Shouldn't just a synced folder cleanup be called on vagrant destroy?

b: If I'm doing a vagrant destroy on the project directory (and NOT on the docker-host directory), why is it trying to remove the synced folders connected to the host (in the docker-host/.vagrant/machines/default/virtualbox/synced-folders, they don't have a docker_sfid and are non transient in virtualbox)?

**Comment by mitchellh** [comment]
Just fixed!

**Comment by mpchlets** [comment]
Mahalo! works on my setup
