### ISSUE TITLE
Start a single box that is a group of boxes

### ISSUE THREAD

**Issue by Comradin** [mitchellh/vagrant#5148]
Hello,

I've got a suggestion for a feature I haven't found yet.

I have a project with about 40 different boxes and some of them are tightly related in such a way that I need a certain box to be running before I can start the one I would like to work with. 

I would like to create a kind of meta box, that would start this group of boxes automagickally instead of the regex way *vagrant up /foo[0-3]/* as something like *vagrant up /(database_server|application_server)/*. This is kind of clumsy and it assumes that everyone knows that both machines must be started. I cannot use the autostart feature, as I have more than one these groups in the project.

Just an idea ;)

Kind regards,
Marcus

**Comment by babilen** [comment]
This would indeed be a great addition to the functionality. I am thinking of a way to statically define "nodegroups" (much like http://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html) in the Vagrantfile in terms of regular expressions that allow you to run commands on, well, groups of guests at the same time.

**Comment by sethvargo** [comment]
Hi there,

This looks to be a duplicate or very closely related to https://github.com/mitchellh/vagrant/issues/4026. Let's track that issue instead. Thanks! 😄
