### ISSUE TITLE
issue to get a box from a network share

### ISSUE THREAD

**Issue by romu70** [mitchellh/vagrant#5150]
Hi,
I'm trying to up a box which is stored on a samba nework share, from 2 PCs running Fedora 21 and W7 Pro. I've a lot of difficulties to be able to download the box from the Fedora 21 host. Both PCs run Vagrant 1.7.1.

If I put this in the Vagrantfile:
```
config.vm.box_url = file:////<nas>/boxes/ubuntu-1404-64.box
```
It works on Windows, but not on Fedora, the error is:
```
Couldn't open file //<nas>/boxes/ubuntu-1404-64.box
```

If I try this on Fedora:
```
config.vm.box_url = smb://<nas>/boxes/ubuntu-1404-64.box
```

I get:
```
Protocol smb not supported or disabled in libcurl
```

I've also tried:
```
config.vm.box_url = //<nas>/boxes/ubuntu-1404-64.box
```
And the output:
```
Couldn't open file /boxes/ubuntu-1404-64.box
```

I used to run Vagrant 1.6.5 and I'm pretty sure I got it work at least one time with this last syntax, but no way to make it work again, so I upgraded to 1.7.1, no change.

Any help? Thanks.

EDIT: This nas is in a Active Directory environment, and, from Nautilus, I do have access to the "boxes" folder.

**Comment by mitchellh** [comment]
Can you play around with using `curl` (locally, unrelated to Vagrant) to cpy that file? That is the URL structure you need to give to Vagrant.

**Comment by romu70** [comment]
I understand but what's "file:////<nas>/boxes/ubuntu-1404-64.box" if not an URL? And why does it work on Windows and not on Fedora?

**Comment by mitchellh** [comment]
It looks like a URL to me, I didn't say it wasn't! :) Vagrant uses `curl` on both Windows and Linux (its own compiled verison, but unmodified) to download and copy box files from URLs. We don't munge the URLs if they're not HTTP so I'm just saying that if you play around with cURL and figure out what the URL structure is that you need to work on Linux, then that is it.

**Comment by romu70** [comment]
Ok, I'll do this, thanks.
