### ISSUE TITLE
HyperV provider - boxes with multiple VHDs fail

### ISSUE THREAD

**Issue by gfortytwo** [mitchellh/vagrant#5152]
The [hyperv provider](https://github.com/mitchellh/vagrant/tree/v1.7.2/plugins/providers/hyperv) does not properly support boxes with multiple attached VHDs.  I am filing as a "bug" rather than an "enhancement" request because the [import_vm.ps1](https://github.com/mitchellh/vagrant/blob/v1.7.2/plugins/providers/hyperv/scripts/import_vm.ps1#L107) script _attempts_ to iterate and add every controller/disk defined in the VM, but the "Cloning virtual hard drive" of the [import.rb](https://github.com/mitchellh/vagrant/blob/v1.7.2/plugins/providers/hyperv/action/import.rb#L30) only clones the first VHD/VHDX it finds in the box's "Virtual Machines" dir.

The issue manifests on the initial `vagrant up` as `Add-VMHardDiskDrive : '_vm name_' failed to add resources` and `The disk is already connected to the virtual machine` because it tries to add the same single cloned disk to every controller defined in the VM.

**Comment by mitchellh** [comment]
Would you be able to link me to a box with multiple VHDs that I can use to test? Thanks!

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!

**Comment by sfossen** [comment]
This still happens, and I'll submit a patch for it.
