### ISSUE TITLE
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.

### ISSUE THREAD

**Issue by hanskoff** [mitchellh/vagrant#5153]
I've updated my vagrant from 1.6.3 today to 1.7.2 and started getting those prompts for vagrant password. I'm not ruby developer but installed HighLine as suggest but that doesn't help

**Comment by mitchellh** [comment]
Ah, can you attach a full debug log? 

I remember this being an issue a long time ago and I don't quite remember what causes it.

**Comment by hanskoff** [comment]
Hi, thank you for quick response. Unfortunatly I've decided to destroy that
images and create new which seem to help.
9 sty 2015 17:09 "Mitchell Hashimoto" <notifications@github.com> napisał(a):

**Comment by kgrvamsi** [comment]
#5142 this happens for a multi vm creation as well

**Comment by CharlesTBetz** [comment]
for what it's worth, I can reliably recreate this by downloading the opscode-ubuntu-14.04 image, doing an apt-get update on it, repackaging it, and attempting to use that new box. If I do not apt-get update, the new box is fine (I can do other things like install the chef client & java, etc & repackage).

**Comment by crobays** [comment]
Hi @mitchellh,
Here's a full debug log. Searching for 'Text will be echoed' will get you to the point.
[https://dl.dropboxusercontent.com/u/20146711/github/vagrant-coreos-reload-bug-log.txt]()

**Comment by crobays** [comment]
Just found out that v1.6.5 does not have this issue.

**Comment by linfan** [comment]
Could it caused by the private key change during the upgrade from Vagrant 1.6.x to 1.7.x ?
```
$ vagrant ssh-config
Host core-01
   ...
  IdentityFile /Users/flin/workspace/CoreOS/.vagrant/machines/core-01/virtualbox/private_key
  ...
```
While Vagrant 1.6.x using shared "~/.vagrant.d/insecure_private_key" file.

**Comment by crobays** [comment]
A complete reinstall of 1.7.x does not solve the problem (also removed .vagrant.d and .vagrant)

**Comment by CharlieC3** [comment]
This error pops up for me on about every 1 out of 3 `vagrant up`s. The only solution I've found it to destroy the VM and retry, which can be quite a long process in my situation.

**Comment by crobays** [comment]
@CharlieC3 Try downgrading to Vagrant 1.6.5

**Comment by fossilet** [comment]
This problem occurs when I am using the Docker provider:

```
Bringing machine 'ds' up with 'docker' provider...
==> ds: Docker host is required. One will be created if necessary...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
docker@127.0.0.1's password:
```

I apparently cannot proceed because the SSH credentials are not correctly set.

I suspect the Docker provider is broken in this aspect. For more information, the structure of .vagrant is:

```
.vagrant/
└── machines
    ├── ds
    │   └── docker
    └── vb
        └── virtualbox
            ├── action_provision
            ├── action_set_name
            ├── id
            ├── index_uuid
            ├── private_key
            └── synced_folders
```

**Comment by AlekseyKorzun** [comment]
Just tested freshly packaged box on MacOSX and Windows (CentOS 6.6). Latter failed with the message in question. No issues with MacOSX.

**Comment by AlekseyKorzun** [comment]
Possible workaround: after this message pops up during vagrant up, do  vagrant init that should trigger login prompt for root@vagrant. Enter 'vagrant' and it will begin to regenerate the key. 

You should be able to vagrant halt && vagrant up now. If you are running CentOS/RHEL, you will probably hit another bug at this point:

"ARPCHECK=no /sbin/ifup eth1 2> /dev/null"

Run vagrant ssh followed by:

"sudo rm -rf /etc/udev/rules.d/70-persistent-net.rules"

Then restart the box.

**Comment by pfiled** [comment]
I have a similar problem using the aws plugin to boot an rhel7 instance inside AWS from an rhel7 instance inside AWS that's using vagrant 1.7.2. Downgrading Vagrant to 1.6.5 solved the problem.

```
==> servername: Waiting for SSH to become available...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
ec2-user@172.nn.nn.nnn's password:==> servername: Terminating the instance...
==> servername: Running cleanup tasks for 'ansible' provisioner...
/var/lib/jenkins/.vagrant.d/gems/gems/net-ssh-2.9.2/lib/net/ssh/prompt.rb:73:in `prompt': undefined method `chomp' for nil:NilClass (NoMethodError)
```

**Comment by maxpersson** [comment]
This happens all the time for me apart from after the first up.

**Comment by karlingen** [comment]
+1

**Comment by Coffee-fan** [comment]
This is happening to me on 1.6.5 with Virtualbox 4.3.22.

**Comment by rroger** [comment]
+1 with vagrant 1.7.2 and 1.6.5

**Comment by karlingen** [comment]
Solved my problem: 
`chmod go-r ~/.ssh/id_boot2docker`

**Comment by rroger** [comment]
Thanks for the hint!


2015-03-11 15:39 GMT+01:00 Karl Metum <notifications@github.com>:

**Comment by IbnSaeed** [comment]
I am having the same issue with 1.7.2

Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.

**Comment by Coffee-fan** [comment]
Ok, I fixed my problem in this way on Windows: 
* Uninstalled Vagrant
* manually deleted ```.vagrant.d``` folder
* Ran ccleaner
* Rebooted
* Installed Vagrant - 1.7.2
* Install plugins again

As I mentioned, I am running W8.1, Mingwin/Cygwin, vagrant 1.7.2 now, Virtualbox 4.3.24

**Comment by IbnSaeed** [comment]
@Coffee-fan i did the same except for running ccleaner.

Its working fine now on windows 8.1

**Comment by Coffee-fan** [comment]
@IbnSaeed Cool :+1:

**Comment by stefancocora** [comment]
**For posterity:**

I've rid myself of this problem by uninstalling all vagrant plugins.
I had these plugins installed:
```bash
§ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
...

§ vagrant --version
Vagrant 1.7.2
...

§ vagrant plugin list
vagrant-aws (0.6.0)
vagrant-omnibus (1.4.1)
vagrant-serverspec (1.0.1)
vagrant-share (1.1.3, system)
```

After uninstalling these plugins all works well !

**Comment by Coffee-fan** [comment]
My empirical experience on this is that in general, if you are on a Linux box, you will need minor surgical changes to fix the above problem. In Windows however, things are more complex. I use Windows, Macs and Linux and I believe I have not yet encountered the problem on the Mac, but then again it may be just because I do not use it that often.

**Comment by RdeWilde** [comment]
Same problem:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

vagrant --version
Vagrant 1.6.5

vagrant plugin list
vagrant-digitalocean (0.7.4)
vagrant-docker-compose (0.0.1)

Using docker image

**Comment by wizonesolutions** [comment]
@karlingen's solution worked for me for some reason.

**Comment by Jakobud** [comment]
This bug is killing me. Everytime I package a box and `vagrant up` a new instance I get this. Even if I re-package a box that works fine from Hashicorp. Really really really annoying. How do I fix this on the guest side so that is just works when other developers first use my box?

**Comment by bezelga** [comment]
I tried all solutions listed here and none worked for me, not sure if this thread should be closed.

**Comment by logvik** [comment]
I just have typed "vagrant" on the queries of password...

**Comment by vladfr** [comment]
I had a different keyfile used in vagrant ssh-config. I simply removed that file, and now vagrant uses the correct key, and no longer asks for a password:
IdentityFile /Users/vlad/.vagrant.d/insecure_private_key

**Comment by ncerminara** [comment]
Adding this to the `Vagrantfile` might help:

```bash
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```

Seems to be some weird issues with how the box was packaged with key authentication.

**Comment by Coffee-fan** [comment]
From the looks of it, without any absolute evidence, this seems to stem from the time that the automatic replacement of vagrant insecure key was introduced. I normally forgo that by just doing:

```
  config.ssh.insert_key = false
```

As I said, I have no absolute evidence, but since I put this on my vagrant file, I do not have the problem. Regarding secure keys, what I do is at some point, where I want to turn a vagrant VM into something usable, I remove the vagrant account completely, so the authorized_keys associated with it also goes.
