### ISSUE TITLE
VagrantUp.com 'Getting Started' - 'Boxes' documentation is inaccurate

### ISSUE THREAD

**Issue by samnissen** [mitchellh/vagrant#5155]
[This page](https://docs.vagrantup.com/v2/getting-started/boxes.html) says to add a new box this way:

    vagrant box add hashicorp/precise32

However, [SO describes a different syntax](http://stackoverflow.com/a/23299093/1651458) (which is a syntax that works on my fresh install on OS X):

    vagrant box add precise32 http://files.vagrantup.com/precise32.box

Apparently this changed in 1.5:

> The syntax for the vagrant box add subcommand is changed with the version 1.5, due to the Vagrant Cloud introduction.

**Comment by mitchellh** [comment]
With 1.5, the correct syntax is the first one. The second syntax still works, however, for backwards compatibility reasons as well as for URLs that aren't hosted on Vagrant Cloud (now Atlas). 

What issue were you getting with the first syntax?

**Comment by samnissen** [comment]
Perhaps I should be filing a different bug report, then, because on OS X following the documentation does not work

    $ mkdir vagrant_getting_started
    $ cd vagrant_getting_started/
    $ vagrant init
    A `Vagrantfile` has been placed in this directory. You are now
    ready to `vagrant up` your first virtual environment! Please read
    the comments in the Vagrantfile as well as documentation on
    `vagrantup.com` for more information on using Vagrant.
    $ vagrant box add hashicorp/precise32
    This command was not invoked properly. The help for this command is
    available below.
    
    Usage: vagrant box add <name> <url>
    
        -f, --force                      Overwrite an existing box if it exists.
        -h, --help                       Print this help

If I add the name to the init command, it doesn't change anything

    vagrant init hashicorp/precise32

I can confirm the required line (as described in the documentation) is in the Vagrantfile:

    config.vm.box = "hashicorp/precise32"

**Comment by mitchellh** [comment]
Can you attach a debug log? (Use `--debug` on the box add command, then gist it).

**Comment by samnissen** [comment]
The flag didn't change the output -- am I being dumb?

    $ vagrant box --debug add hashicorp/precise32
    This command was not invoked properly. The help for this command is
    available below.
    
    Usage: vagrant box add <name> <url>
    
        -f, --force                      Overwrite an existing box if it exists.
        -h, --help                       Print this help

:[

**Comment by mitchellh** [comment]
Hm, this is weirdly all smelling like an old version of Vagrant. Can you try `vagrant --version` ?

**Comment by samnissen** [comment]
I think you are spot-on:

    $ vagrant -v
    Vagrant version 1.0.1

Thank you very much! Downloading 1.7.2 right now.

P.S. I installed with `apt-get`. Was this stupid? Would be neat if this was supported in the future...

**Comment by mitchellh** [comment]
We work with the distros when they ask to help them get things working, but the release cycle there is generally slow.
