### ISSUE TITLE
Docker: rsync-auto to only watch current vagrant folder and not all projects on proxy VM

### ISSUE THREAD

**Issue by duro** [mitchellh/vagrant#5160]
I have a setup where I am using Vagrant to spin up a Docker host using the `vagrant_vagrantfile` link and then I have multiple "projects" that are using this same Docker host. I am using rsync to get files into the Docker host, and rsync-auto to keep pushing files into the host.

What I have noticed is that when I run `vagrant rsync-auto` in on of the projects, it starts the rsync watchers across ALL projects that are using the Docker host.

I'm assuming this is because the rsync-auto command is using the shared folder settings of the host, and not just looking at the shared folder settings of the project it is in.

I am suggesting a change to that. I think it makes more sense to only start the rsync watcher for the project I am in, as a day could come when I have a dozen projects all sharing the same Docker host and watching all of them at the same time could really bog things down.

**Comment by wgrrrr** [comment]
I'm having this same issue, and I'd love it if rsync would operate on a per `config.vm.define` basis.
