### ISSUE TITLE
Rsync shared folder on windows only works when vagrant is started through cygwin

### ISSUE THREAD

**Issue by fresheneesz** [mitchellh/vagrant#5164]
If I add cygwin's bin folders to the path and start vagrant from a normal command window, it gives me the error: 

```
Error: Warning: Permanently added '[127.0.0.1]:2222' (RSA) to the list of known hosts.
rsync: change_dir "/d/billysFile/IDEAS/Tixit/backend" failed: No such file or directory (2)
FATAL I/O ERROR: dying to avoid a --delete-during issue with a pre-3.0.7 receiver.
rsync error: requested action not supported (code 4) at /usr/src/ports/rsync/rsync-3.0.9-1/src/rsync-3.0.9/flist.c(1800) [sender=3.0.9]
```

My configuration for the synced folder is:
`config.vm.synced_folder ".", "/home/vagrant/backend", type: "rsync", rsync__auto: "true"`

I read somewhere (lost the link) that there's an issue with vagrant not loading the correct filepath for "." because cygwin starts off its directories with /cygwin/ *and* that you need to update rsync for the --delete-during issue. 

Note that trying to start my existing vagrant machine through cygwin gave me all sorts of pain: 
https://github.com/mitchellh/vagrant/issues/5163#issuecomment-69438490

**Comment by osroot25** [comment]
temporary workaround: https://github.com/mitchellh/vagrant/issues/3230#issuecomment-62588180
presumably source of that bug: https://github.com/mitchellh/vagrant-installers/issues/49 (I am not familiar enough with Go, I can't fix it)

**Comment by davidski** [comment]
:+1: on both the issue and the workaround. This has been a maddening bug costing me hours of time. This problem (prior to the workaround) made vagrant almost useless for me. :frowning:

**Comment by mitchellh** [comment]
Let's track the issue on the vagrant-installers. Thanks!
