### ISSUE TITLE
Windows box freezes with vagrant 1.7.2 and WinRM communicator

### ISSUE THREAD

**Issue by Annih** [mitchellh/vagrant#5166]
Hi,

I recently installed the latest vagrant version - 1.7.2 - and I faced an issue using my Windows boxes with WinRM Communicator... it simply does not work anymore, I have to kill the "vagrant up" process, then reboot the box and everything will be find. If I don't reboot, I can't communicate with the server through winrm, even logged on the machine I can't start a powershell session, or perform a `SC QUERY`

I started to investigate my issue and found that there was an error during the "Change Hostname step":
>Set-ItemProperty : Cannot find path 'HKCU:\Volatile Environment' because it does not exist.

I found the [corresponding line](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/windows/cap/change_host_name.rb#L32) in vagrant code - it's not that much important because it fails at the penultimate statement of the script, but it's still an error.
Thanks to git blame I found that it's related to #4687 ... I'm sure a lot of people will laugh reading my sentence but ... Windows _needs_ to reboot after the rename!
You might find a lot of script on the web, that tries to hack the Registry to avoid reboot ... but if you want to rename properly your Windows you **need to reboot!** There are so many services that needs to be restarted that we can't/shouldn't even try to do it via script.

That being said, I'm OK to keep this script in vagrant code, but you:
-  [ ] need to fix it
  - the HKCU:\\Volatile Environment key is not present when setuping the box, because there is no logged user.
  -  you [shouldn't sleep](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/windows/cap/change_host_name.rb#L49) if there is no reboot

-  [ ] clean it
  - you don't need the [HKU PSDrive](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/windows/cap/change_host_name.rb#L24)
 -  you don't need to modify the current user [environment](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/windows/cap/change_host_name.rb#L33) and [volatile environment](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/windows/cap/change_host_name.rb#L32) if there is no user logged in.
-  [ ] add a setting to toggle this feature, maybe someone wants to work with unstable Windows, you should be able to enable/disable this feature according to your needs. Personnally I don't want to use it :) I'd rather wait 2 more minutes that my box reboot than having ununderstandable issues. I don't even need to rename my box.

Am I the only one encountering that kind of issue with *Windows Server 2008R2* and *Windows Server 2012R2* boxes ?
I didn't try with SSH Communicator because I don't have SSH on my boxes.

**Comment by uchagani** [comment]
hmm...so i added the PR that enabled "change hostname without reboot".  I don't seem to be seeing the issue you are.  i'll try and reproduce.

**Comment by lyrch** [comment]
I am having the same issue with the HKCU:\Volatile Environment registry key not being present. I am using vagrant 1.7.2 and Windows Server 2012.

**Comment by docwhat** [comment]
I have to agree with @Annih.  You *have* to reboot when you rename windows. All the "hacks" to not require a reboot are very brittle and don't produce a stable, reliable environment.

**Comment by bcc** [comment]
I am also seeing issues following the missing reboot, although not as bad as the OP. It does look like this will be resolved in 1.7.3 according to the changelog and PR 5261 though.

**Comment by Annih** [comment]
Yes, fixed by #5261
