### ISSUE TITLE
Chef provisioner: The chef binary was not found

### ISSUE THREAD

**Issue by windowsrefund** [mitchellh/vagrant#5167]
Vagrant 1.7.2

Vagrantfile

```ruby
...
config.vm.provision :chef_client do |chef|
  ...
  chef.binary_path = '/opt/chef/bin'
end
```
I have verfied the following:
* The VM is accessible via ssh (vagrant ssh)
* Chef Client is installed on the VM into /opt/chef

Am I missing something or is this a known issue?

**Comment by sethvargo** [comment]
@windowsrefund I am sorry you are having problems with the Chef provisioner. In general, you should not set the Chef binary path unless you have a custom Chef installation. As of Vagrant 1.7, Chef is automatically installed and managed by Vagrant, so there is no need to set that variable.

```ruby
config.vm.provision "chef_client" do |chef|
  # ...
end
```

**Comment by windowsrefund** [comment]
Adding binary_path was an attempt to overcome the same problem. Why was this closed without verifying your feedback was valid?

**Comment by windowsrefund** [comment]
Adding binary_path was an attempt to overcome the same problem. Why was this closed without verifying your feedback was valid?

**Comment by sethvargo** [comment]
@windowsrefund that's just our general policy until we have more information. Can you please post your Vagrantfile and the output of the initial Vagrant run [in debug mode](http://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by windowsrefund** [comment]
That's a poor policy if you think additional information would benefit the discussion. Wouldn't it be better to ask the question(s) rather than just close the issue?

Thanks for the debugging link. I'm going to run that and see what I see. If I can figure it out, I'll share the solution and close the issue. If I can't I'll post the output and we can go from there.

Thanks

**Comment by sethvargo** [comment]
@windowsrefund thanks for the feedback.

When you post the output, please use a service like Gist or Pastebin and just post the link there (it's going to be long).

**Comment by windowsrefund** [comment]
got it! The install.sh script leverages `which`. My docker image (centos:centos6) does not include it. Once I updated my Dockerfile to install that package via yum, all worked as expected.

I'll explore adding a test to install.sh so it can test for the binary rather than assume it exists.

Thanks for your help. Setting VAGRANT_LOG=debug was key.
