### ISSUE TITLE
Add option to specify VlanID to Network Adapter when using HyperV provider

### ISSUE THREAD

**Issue by tomassrnka** [mitchellh/vagrant#5168]
The HyperV provider lacks option to specify VlanId to Network Adapter automatically. This is pretty painful as I need each VM's Network Adapter to use VLANID100. 

Current option is to change the network adapter's settings manually in HyperV's management or through powershell.

![screenshot 2015-01-11 18 08 11](https://cloud.githubusercontent.com/assets/1406694/5696010/fa8e8a14-99bc-11e4-9436-a334443904fb.png)

**Comment by tomassrnka** [comment]
Pull request #5169

**Comment by mitchellh** [comment]
I'll wait on your PR. Thanks!
