### ISSUE TITLE
Cannot vagrant ssh after package command

### ISSUE THREAD

**Issue by mdford** [mitchellh/vagrant#5171]
I have created a new project from ubuntu/trusty64, added numerous files, packages, etc to the box that I needed and the box works fine.  I can `vagrant ssh` into the box, access nginx, etc.   

I created a new box from this via the `vagrant package` command.  I then use this new .box file as the referenced box in a new project.  My Vagrant file:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "basebox"
  config.vm.provision :shell, :inline => "apt-get update"
  config.vm.network "private_network", ip: "10.1.1.2"
  config.vm.network :forwarded_port, host: 7777, guest: 80

  # Configure VM Cpu's/Ram/Name
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "newbox"
    vb.customize ["modifyvm", :id, "--cpus","2", "--name", "new_box_name", "--memory", "4096"]
  end

end
```

However, when I `vagrant up` this new one, I get 

    default: Warning: Authentication failure. Retrying...

which will eventually get the "Timed out while waiting..." message

The strange thing is that I can get into the box by either `ssh vagrant@10.1.1.2` or by using the virtual box gui and logging in with `vagrant/vagrant`

I can also still `vagrant up` into my original box with no problems.

Can someone please shed some light onto this.  I assumed that the whole reason for creating the package command was to be able to create a base image so that the you do not have to provision boxes every time you create a new project.

Thanks in advance!

**Comment by mitchellh** [comment]
Please make sure the box meets all these guidelines: https://docs.vagrantup.com/v2/boxes/base.html

Specifically, as the error message states, I'm guessing the insecure private key is not present.

Please ask these usage questions on the mailing list in the future.
