### ISSUE TITLE
vagrant up on cygwin - connection refused

### ISSUE THREAD

**Issue by rndmh3ro** [mitchellh/vagrant#5174]
I'm using the latest cygwin version, Vagrant 1.7.2 and Virtualbox 4.3.20.
I create a new vagrant-host with `vagrant init puphpet/centos65-x64` (the provider doesn't matter), then try a `vagrant up` but it fails with:

    C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subprocess.rb:109:in `rescue in execute': Zugriff verweigert (5) (Vagrant::Util::Subprocess::LaunchError)

Full DEBUG-output here:
https://gist.github.com/anonymous/2f6be859fa3e7c3b3ab7

**Comment by sethvargo** [comment]
Hi @rndmh3ro 

That error message is coming from VirtualBox and it is "access denied". Please make sure you have permission to execute the VirtualBox process as the same user you are running Vagrant as. This might also be a VirtualBox bug, so you might try updating to the latest stable version of VirtualBox. Thanks!
