### ISSUE TITLE
Root privileges not working consistently for NFS mounts on Mac OSX, Vagrant 1.7.1

### ISSUE THREAD

**Issue by JoeReid-Korrelate** [mitchellh/vagrant#5177]
After upgrading from Vagrant 1.1 to Vagrant 1.7.1, we are running into some weird issues with the root privileges required to mount NFS volumes to guest VMs without requiring an admin password each time.

Followed the documentation posted [here](https://docs.vagrantup.com/v2/synced-folders/nfs.html), which "sort of" works.  By which I mean that it HAS worked, but it seems very inconsistent.  Sometimes it prompts for a password.  Sometimes it doesn't.   

I haven't figured out any particular pattern as to why.

**Output:**
[Vagrantfile](https://gist.github.com/JoeReid-Korrelate/c87e0b25da066e35f8e8)
[Debug log](https://gist.github.com/JoeReid-Korrelate/32831106ef4c36efcbbb) (from prompted "vagrant up")

**Versions:**
- OSX 10.9.4
- Vagrant 1.7.1
- VirtualBox 4.3.20-96996

**/etc/sudoers:** (empty or commented sections removed)
```
# Cmnd alias specification
# For vagrant NFS mounts without password.  See https://docs.vagrantup.com/v2/synced-folders/nfs.html.
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -E -e /*/ d -ibak /etc/exports
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE

# Defaults specification
Defaults	env_reset
Defaults	env_keep += "BLOCKSIZE"
Defaults	env_keep += "COLORFGBG COLORTERM"
Defaults	env_keep += "__CF_USER_TEXT_ENCODING"
Defaults	env_keep += "CHARSET LANG LANGUAGE LC_ALL LC_COLLATE LC_CTYPE"
Defaults	env_keep += "LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME"
Defaults	env_keep += "LINES COLUMNS"
Defaults	env_keep += "LSCOLORS"
Defaults	env_keep += "SSH_AUTH_SOCK"
Defaults	env_keep += "TZ"
Defaults	env_keep += "DISPLAY XAUTHORIZATION XAUTHORITY"
Defaults	env_keep += "EDITOR VISUAL"
Defaults	env_keep += "HOME MAIL"

# User privilege specification
root	ALL=(ALL) ALL
%admin	ALL=(ALL) ALL
```

**/etc/exports** is empty with no VMs provisioned.  With all three VMs up, it looks like this: 
```
# VAGRANT-BEGIN: 501 7576154c-05a0-49c8-843e-1c0427b95c4d
"/Users/jreid/repo/O2O" 33.33.33.10 -alldirs -mapall=501:20
"/Users/jreid/repo/bi" 33.33.33.10 -alldirs -mapall=501:20
"/Users/jreid/repo/chef" 33.33.33.10 -alldirs -mapall=501:20
# VAGRANT-END: 501 7576154c-05a0-49c8-843e-1c0427b95c4d
# VAGRANT-BEGIN: 501 02c4ea53-c885-4f48-859e-e43744b889e7
"/Users/jreid/repo/O2O" 33.33.33.11 -alldirs -mapall=501:20
"/Users/jreid/repo/chef" 33.33.33.11 -alldirs -mapall=501:20
# VAGRANT-END: 501 02c4ea53-c885-4f48-859e-e43744b889e7
# VAGRANT-BEGIN: 501 22c06f43-bb58-416c-94fe-901a34223d9d
"/Users/jreid/repo/O2O" 33.33.33.12 -alldirs -mapall=501:20
"/Users/jreid/repo/chef" 33.33.33.12 -alldirs -mapall=501:20
# VAGRANT-END: 501 22c06f43-bb58-416c-94fe-901a34223d9d
```

I'm not sure if this is an issue with Vagrant, with the docs, or the always possible PEBKaC.  I'd appreciate any help anybody has to offer, or a point in the right direction.  Thanks!

**Comment by JoeReid-Korrelate** [comment]
Any feedback on this, guys?

**Comment by mitchellh** [comment]
Sorry @JoeReid-Korrelate. This is a much better question to ask the mailing list, where you'll likely get a better response. We still aren't formally supporting password-less NFS. We added that section to the docs as a "maybe works, or is close to working" type example that the community has put together, but we don't routinely test it. The mailing list should have better answers here.
