### ISSUE TITLE
PR #3303 doesn't account for multiple private interfaces

### ISSUE THREAD

**Issue by clinstid** [mitchellh/vagrant#5180]
As reported by @excieve in PR #3303, the change in PR #3303 doesn't account for configurations with multiple interfaces. The problem is that each interface has its own definition surrounded by `#VAGRANT-BEGIN` and `#VAGRANT-END` like:

```
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 10.1.20.100
      netmask 255.255.255.0
#VAGRANT-END
```

The problem is when you have more than one private interface defined:

```
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 10.1.20.100
      netmask 255.255.255.0
#VAGRANT-END

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth2
iface eth2 inet static
      address 10.1.20.101
      netmask 255.255.255.0
#VAGRANT-END
```

The second sed command in `plugins/guests/debian/cap/configure_networks.rb` will print everything after the first `#VAGRANT-END` into `/tmp/vagrant-network-interfaces.post` and later concatenate that to `/etc/network/interfaces` creating a file with multiple definitions for any private interfaces beyond the first:

```
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 10.1.20.100
      netmask 255.255.255.0
#VAGRANT-END

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth2
iface eth2 inet static
      address 10.1.20.101
      netmask 255.255.255.0
#VAGRANT-END

#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth2
iface eth2 inet static
      address 10.1.20.101
      netmask 255.255.255.0
#VAGRANT-END
```

The command `/sbin/ifup` doesn't accept this as valid syntax, so you get the reported failure.

I think a good fix for this is to remove the `#VAGRANT-BEGIN` and `#VAGRANT-END` lines from the templates used to generate the interface definitions and add them explicitly to the beginning and end of the `entries` array before rendering the vagrant section of the `/etc/network/interfaces` file. Then the sed commands will work as intended: remove the existing vagrant generated interfaces and only add the newly generated interfaces.

**Comment by bsn** [comment]
hi all, any chance to have this fixed soon?

**Comment by sjevs** [comment]
It looks like the referenced commit fixes it. Correct @clinstid ?

**Comment by clinstid** [comment]
Yes, I have submitted a PR with a fix for this, but it has not been accepted. That branch is on my fork.

**Comment by mattolson** [comment]
+1 for getting this merged, we ran into this today and had to downgrade to 1.7.1.

**Comment by mkwsra** [comment]
In my case I've public networks and vagrant will work only for the very first up command! is it that same bug/issue ?

**Comment by artoodetoo** [comment]
Me too:( I was forced to downgrade Vagrant. Each halt / up loop causes an duplicate interface error.

**Comment by mkwsra** [comment]
@artoodetoo just use snapshots by VirtualBox and suspend it ( don't halt ) then resume the box each time you want to restart the machine, it's working for me now, but I'm going to destroy/up it at some point :disappointed:

**Comment by piscis** [comment]
Not sure if this is related but after removing this line from my vagrant file: 
```ruby
config.vm.network :public_network, :use_dhcp_assigned_default_route => true
```
and removing the second interface definition from `/etc/network/interfaces` it stop creating internet-definitions twice.

Using vagrant:
```bash
> vagrant -v
Vagrant 1.7.2
```

**Comment by adamwitorean** [comment]
As a Vagrant noob this was not a nice surprise for me while learning. I was wondering what was wrong with my Vagrantfile config. +1 for fix here.

**Comment by mryanb** [comment]
+1 downgraded to 1.7.1 on mac.

**Comment by samwierema** [comment]
+1. Also running multiple interfaces. Downgraded tot 1.7.1 for the time being.

**Comment by hashkool** [comment]
This is a major bug which makes 1.7.2 totally unusable for debian flavoured guests, people need to downgrade vagrant. Downloading from the website still leads to the broken 1.7.2. I think it is better to mark 1.7.1 as the latest stable?

How can we raise the priority of this bug?

**Comment by JanDC** [comment]
+1.
Downloading the latest from vagrantup.com or from the archlinux repo's using pacman results in the broken 1.7.2 package.
Please handle this issue with high priority, as our users have to downgrade and pin the package just to be able to run our vagrant setup...

**Comment by yoni-rotvel** [comment]
Happening here too, but only with Bridged Adapter ("public_network"), and only twice.
explanation: first time up everything is cool--> halt-->up-fails due to duplicate entries--halt---> up-fails but dosen't add 3rd entry. the private network isnt affected, this only happens to the public network

**Comment by AlekseyKorzun** [comment]
Same issue here, was driving me nuts. I re-packaged the box .vs using existing image back-up thinking there was a problem with the data to no avail. Downgrading to 1.7.1 and re-initializing the machine solved it.

:+1:

**Comment by sethvargo** [comment]
Fixed in https://github.com/mitchellh/vagrant/pull/5325
