### ISSUE TITLE
Vagrant chef provisioner query - does it support running chef 12?

### ISSUE THREAD

**Issue by wingZero21** [mitchellh/vagrant#5184]
Hi,

Just a quick query as we have updated chef server to version 12. 

Do you know if/when the vagrant provisioning will support running chef on version 12 with Vagrant?

**Comment by wingZero21** [comment]
Tried adding version 12.0.1 on vagrant omnibus but get the below.

Details:

Added the below to vagrantfile
```
config.omnibus.chef_version = "12.0.1"
```

Output
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vagrant-omnibus:
* '12.0.1' is not a valid version of Chef.

A list of valid versions can be found at: http://www.opscode.com/chef/install/

```

**Comment by sethvargo** [comment]
@wingZero21 I am sorry you are having problems with the Chef provisioner's auto-installer.

The Vagrant 1.7.1 Chef provision uses Chef's Omnibus downloader to install and manage Chef:

1. [Install curl](https://github.com/mitchellh/vagrant/blob/ea8de92c59102f40f942865423a0a71ffcb6bdc9/plugins/provisioners/chef/cap/debian/chef_install.rb#L9-L10)
2. [Run the Omnibus command](https://github.com/mitchellh/vagrant/blob/ea8de92c59102f40f942865423a0a71ffcb6bdc9/plugins/provisioners/chef/cap/debian/chef_install.rb#L12-L13)

The [`build_command`](https://github.com/mitchellh/vagrant/blob/ea8de92c59102f40f942865423a0a71ffcb6bdc9/plugins/provisioners/chef/omnibus.rb#L8-L29) just builds a command string like:

    curl -sL https://www.chef.io/chef/install.sh | sudo bash -s -- -v "12.0.1"

Which then gets executed on the guest.

You are currently using the [vagrant-omnibus](https://github.com/opscode/vagrant-omnibus) plugin which is a third-party plugin for installing Chef in previous versions of Vagrant. It relies on the published Rubygems versions of Chef. Vagrant does not maintain or support that plugin, so you probably want to open a ticket on that repo.

However, you do not need to use that plugin to use Chef with Vagrant 1.7+ as Vagrant will auto-install for you. Run:

    vagrant plugin uninstall vagrant-omnibus

And then remove the `config.omnibus` section from your `Vagrantfile`. You can specify the version of Chef you want to use *in* the Chef provisioner block:

```ruby
config.vm.provision "chef_solo" do |chef|
  chef.version = "12.0.3"
end
```

**Comment by vikas027** [comment]
I also faced the same error today, but it vanished after some time. Not sure what was wrong.

```bash
vagrant-omnibus:
* '12.0.1' is not a valid version of Chef.

A list of valid versions can be found at: http://www.opscode.com/chef/install/

There are errors in the configuration of this machine. Please fix
the following errors and try again:

vagrant-omnibus:
* '12.0.1' is not a valid version of Chef.
```
