### ISSUE TITLE
salt bootstrap gives false positive when it fails to install due to inability to connect to github

### ISSUE THREAD

**Issue by ryanvanoss** [mitchellh/vagrant#5185]
When unable to connect to raw.githubusercontent, the salt bootstrapper will give a false positive on its installation. The inability to connect can occur for various reasons, including, but not limited to, incorrect proxy settings and raw.githubusercontent downtime.

```bash
DEBUG ssh: stderr: 0
DEBUG ssh: stderr:      0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: stderr: c
DEBUG ssh: stderr: u
DEBUG ssh: stderr: rl: (6) Could not resolve host: raw.githubusercontent.com

DEBUG ssh: Exit status: 0
 INFO interface: info: Salt successfully configured and installed!
Salt successfully configured and installed!
```

**Comment by ryanvanoss** [comment]
Any updates on this issue?

**Comment by ryanvanoss** [comment]
Bump

**Comment by ryanvanoss** [comment]
@sethvargo, this is still an issue -- any idea if it will be addressed for the next version?

**Comment by sethvargo** [comment]
Unfortunately none of the core maintainers of Vagrant use or have experience with Salt. If someone from the Salt community or company is interested in contributing, we will gladly review and test the PRs.

**Comment by ryanvanoss** [comment]
This is a failure in Vagrant's bootstrapping of Salt, not with Salt itself. The bootstrapper fails to connect to `raw.githubuser...` yet exits with a 0 and gives a success message despite the failure: 

https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/bootstrap-salt.sh#L7
https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/provisioner.rb#L272
https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/provisioner.rb#L291

**Comment by sethvargo** [comment]
Looks like this was fixed in https://github.com/marietje/marietje/pull/7, but has not yet been released. Thanks!
