### ISSUE TITLE
Not able to start a Docker image

### ISSUE THREAD

**Issue by arun-gupta** [mitchellh/vagrant#5187]
Created a Vagrant image using the following file:

https://github.com/arun-gupta/vagrant-images/blob/master/docker-wildfly/Vagrantfile

Creating an image as:

```
vagrant up --provider=docker
```

and getting:

```
Bringing machine 'default' up with 'docker' provider...
==> default: Docker host is required. One will be created if necessary...
    default: Docker host VM is already ready.
==> default: Warning: When using a remote Docker host, forwarded ports will NOT be
==> default: immediately available on your machine. They will still be forwarded on
==> default: the remote machine, however, so if you have a way to access the remote
==> default: machine, then you should be able to access those ports there. This is
==> default: not an error, it is only an informational message.
==> default: Creating the container...
    default:   Name: docker-wildfly_default_1421283001
    default:  Image: jboss/wildfly:latest
    default: Volume: /var/lib/docker/docker_1421277277_78698:/vagrant
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: "docker" "run" "--name" "docker-wildfly_default_1421283001" "-d" "-v" "/var/lib/docker/docker_1421277277_78698:/vagrant" "jboss/wildfly:latest"

Stderr: Unable to find image 'jboss/wildfly:latest' locally
Pulling repository jboss/wildfly






2015/01/15 00:34:24 Error pulling image (latest) from jboss/wildfly, operation not supported

Stdout: 
```

Following the instructions at https://docs.vagrantup.com/v2/docker/index.html

**Comment by kikitux** [comment]
On Thu, Jan 15, 2015 at 2:18 PM, Arun Gupta <notifications@github.com>
wrote:

> jboss/wildfl


can you try without :latest ?


To downloadn an image  I use this:

config.vm.provision "docker", images: ["golang:latest"]

**Comment by fossilet** [comment]
Same problem here, no ":latest":

Command: "docker" "run" "--name" "vagrant_docker_default_1421380212" "-d" "-v" "/var/lib/docker/docker_1421380172_20534:/vagrant" "centos"

Stderr: Unable to find image 'centos' locally
Pulling repository centos

2015/01/16 03:57:19 Error response from daemon: No command specified

Stdout: 

The same command runs fine when using Boot2Docker.

**Comment by arun-gupta** [comment]
No change, now getting:

```
==> default: Creating the container...
    default:   Name: docker-wildfly_default_1421391530
    default:  Image: jboss/wildfly
    default: Volume: /var/lib/docker/docker_1421277277_78698:/vagrant
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: "docker" "run" "--name" "docker-wildfly_default_1421391530" "-d" "-v" "/var/lib/docker/docker_1421277277_78698:/vagrant" "jboss/wildfly"

Stderr: Unable to find image 'jboss/wildfly' locally
Pulling repository jboss/wildfly






2015/01/15 12:27:29 Error pulling image (latest) from jboss/wildfly, operation not supported

Stdout: 
```

**Comment by fossilet** [comment]
@arun-gupta Can you go to `~/.vagrant.d/data/docker-host`, do `vagrant ssh`, and run the command. The error is solely produced by `docker` in the Docker host.

**Comment by arun-gupta** [comment]
@fossilet This command starts logs into the host and shows:

```
docker-host> vagrant ssh
                        ##        .
                  ## ## ##       ==
               ## ## ## ##      ===
           /""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
           \______ o          __/
             \    \        __/
              \____\______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
boot2docker: 1.2.0
             3.16.1-config-file : e75396e - Fri Aug 22 06:45:30 UTC 2014
docker@boot2docker:~$ 
```

**Comment by fossilet** [comment]
@arun-gupta And run `"docker" "run" "--name" "docker-wildfly_default_1421391530" "-d" "-v" "/var/lib/docker/docker_1421277277_78698:/vagrant" "jboss/wildfly"`. You will get the same error, but you can debug and find the correct command.

**Comment by fossilet** [comment]
I think this is a bug from the Docker driver.

For my problem:

`2015/01/16 03:57:19 Error response from daemon: No command specified`

This is because the command assembled in `plugins/providers/docker/driver.rb` is not valid for `docker` in that it misses the command to run.

**Comment by arun-gupta** [comment]
The container starts up correctly with that:
```
3bc5f4b20ad606ef80cd9f91d1d25f835c49eedaba992b9e76a012648933d928
docker-host> docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                NAMES
3bc5f4b20ad6        jboss/wildfly:latest   "/opt/jboss/wildfly/   41 hours ago        Up 2 seconds        8080/tcp, 9990/tcp   docker-wildfly_default_1421391530   
```

**Comment by frapaa** [comment]
Hi, I'm running into this as well, any progress on fixing this?

**Comment by mitchellh** [comment]
If running this manually resultsin the same error ,it is probably a configuration problem with the daemon itself. I can't reproduce this with an image. If there is something Vagrant can do to avoid this, let me know and I will fix.

**Comment by bmfallon** [comment]
I am currently running into this same problem using docker as the provider in Vagrant.  I am using Vagrant 1.8 and and Docker 1.9.1

I have tried all of the solutions posted here and none of them seem to have fixed the problem unfortunately.

Does anyone have any other ideas for a fix or work around?
