### ISSUE TITLE
Chef-solo + berkshelf + vagrant-rackspace + rsync issue

### ISSUE THREAD

**Issue by trappar** [mitchellh/vagrant#5188]
Despite the long list of tools that I used to find this bug, it does appear to be a bug specifically with the chef-solo provisioner.. and so I'd assume the issue should go here. Here's what happens:

When running `vagrant up` I see the following lines in the output:

```
==> default: Rsyncing folder: /Users/trappar/Development/chef/testbook/ => /vagrant
==> default: Rsyncing folder: /Users/trappar/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150114-52105-1c4i8w7-default/ => /tmp/vagrant-chef/45ccab2ba49d3b740513bc910108d6be/cookbooks
==> default: Rsyncing folder: /Users/trappar/Development/chef/chef-server/data_bags/ => /tmp/vagrant-chef/f397084f58fed18af584ddb13a0f0f70/data_bags
==> default: Rsyncing folder: /Users/trappar/Development/chef/chef-server/environments/ => /tmp/vagrant-chef/ff430af9267b8c05c59c0a7b90675a89/environments
```

Then when running `vagrant provision` I get:

```
==> default: Rsyncing folder: /Users/trappar/Development/chef/testbook/ => /vagrant
```

The berkshelf one is quite necessary, since that's where the policy code lives and is executed from. The result of this is that I can provision correctly on vagrant up, but then any further changes to my policy code will never be synced with the server.

By poking around in debugging output I found that Vagrant is ignoring these folders [because they already exist](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/chef/provisioner/chef_solo.rb#L128-L131)

As a temporary.. but really horrible solution I've added this to my Vagrantfile

```
config.vm.provision :chef_solo do |chef|
    chef.provisioning_path = "/tmp/vagrant-chef-#{Time.now.to_i}"
end
```

By changing the provisioning path on every run, the chef-solo provisioner doesn't find any existing folders and happily rsyncs everything over.

Seems like maybe this is some conflicting code. Like the code preventing syncing is appropriate for other forms of syncing but not at all for rsync? I don't know much about vagrant or vagrant plugin internals so mostly this is just poking around and guessing.

**Comment by sethvargo** [comment]
Hi @trappar,

Unfortunately we cannot properly debug issues when third-party plugins are involved. Are you able to reproduce this issue without the vagrant-berkshelf plugin? It looks like the vagrant-berkshelf plugin just does not support rsync synced folders...

**Comment by trappar** [comment]
@sethvargo I actually haven't even been able to reproduce this issue on another computer. Either way, I can just use `vagrant rsync && vagrant provision` if it happens again. Does seem like there's a bug buried somewhere here, but with so little to go on I'm just going to close this.
