### ISSUE TITLE
Vagrant can find 'virtualbox', but not 'VirtualBox'.

### ISSUE THREAD

**Issue by GeorgeMac** [mitchellh/vagrant#5189]
I could be doing something really stupid. However, I keep getting this issue. Even with fresh installs of both vagrant and virtual box.
When I `vagrant up`, vagrant chooses to use `virtualbox` initially as a provider. It imports the base box, sorts out NATs, port forwarding... blah blah blah. Then I get the following error as it tries to provision:
```
The provider 'VirtualBox' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
```
I then try `vagrant destroy` and get the same error message. Even with `vagrant ssh` I get this error message. However, if I use `vagrant global-status` and get the vm id; I can explicitly `vagrant destroy <id>` or `vagrant ssh <id>`. 
This is a pain as every time I `vagrant up` it gets as far as provisioning with ansible and then fails because it is looking for a slightly different provider. 

I am running on OS X Yosemite if that helps as well. I am sure I have just messed up set up somehow.

**Comment by davebirch** [comment]
May be a silly question, but do you have a vm.provider block in the
Vagrantfile used for the environment you're seeing issues with, and have
you specified the provider in this block as "VirtualBox" rather than
"virtualbox"?

I might be misreading your message, does this happen for all Vagrant
instances, or just a specific file?

**Comment by GeorgeMac** [comment]
Just had a check. The provider is set to `virtualbox` lower-case. I tried with upper-case and I get the same problem :S

**Comment by GeorgeMac** [comment]
I'll look for another project to try it with :)

**Comment by GeorgeMac** [comment]
There must be something wrong with my Vagrantfile. Everything worked fine when I built vagrant project itself. I will keep looking, this is someone else project who has left our company. I'll close this issue :) Thanks @davebirch

**Comment by legal90** [comment]
@GeorgeMac have you figured out what was wrong in your Vagrantfile? 

We got the similar error report for [parallels] provider from one of our customers. He is using the valid Vagrantfile (with provider mentioned in lower case) and initial "vagrant up" is successfull. But after that he get the same error about provider in capitalized notation:

```
The provider 'Parallels' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
```

**Comment by hitsthings** [comment]
I'm also seeing this (on Windows 8.1). I can't destroy the machine either because the provider isn't recognized.

**Comment by legal90** [comment]
@hitsthings  Just look at this folder, located in your current working directoy: `.vagrant/machines/<machine_name>/VirtualBox`, and try to rename in to lower case `.vagrant/machines/<machine_name>/virtualbox` , so it should fix an issue for you.

**Comment by legal90** [comment]
I've figured out how to reproduce this issue on OS X: (the provider doesn't make sense)

1) Switch to any empty folder: 
```
mkdir /empty_folder
cd /empty_folder
```
2) Init new Vagrant environment: 
```
vagrant init chef/ubuntu-14.10
```
3) Try to run it with making a mistake in the case of provider name: 
```
vagrant up --provider=VirtualBox
```
You will see the valid message, telling that this provider does not exists.

4) Fix your mistake and run the command correctly: 
```
vagrant up --provider=virtualbox
```
The VM will be upped successfully, but there still be wrong data directory for it: `.vagrant/machines/<machine_name>/VirtualBox`

5) Now try to execute some subsequent command and see that it will be failed:
```
$ vagrant ssh

The provider 'VirtualBox' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
```

**Comment by legal90** [comment]
I've also provided a workaround here: GH-5334

**Comment by 501st-alpha1** [comment]
I can confirm that the steps provided by @legal90 to reproduce the problem are also valid on Windows. After I deleted the `.vagrant` folder and the VM, `vagrant up` (the `--provider=virtualbox` is implied by my `Vagrantfile`) worked correctly.

**Comment by brunowego** [comment]
Thanks @legal90, only need rename folder!

**Comment by gvlekke** [comment]
501st-alpha1 helps :+1:

**Comment by Midnight-Coder** [comment]
@501st-alpha1 thanks :+1:

**Comment by joelcormack** [comment]
@legal90 thank you, renaming the folder fixed it for me too

**Comment by cristianmartinez** [comment]
@legal90 Renaming the folder fixed it for me, thanks!

**Comment by andreibenhur** [comment]
@legal90 Renaming the folder fixed it for me, thanks! (2)

**Comment by prayagupd** [comment]
facing same issue with windows 7 while virtualbox is up and runnning.

**Comment by Nurdok** [comment]
I got the same problem @prayagupd reports, but with vagrant 1.8.1

**Comment by DrewRay** [comment]
same problem running on mac OS

$ vagrant --version
Vagrant 1.9.1
$ vboxmanage --version
5.0.32r112930

after reading this i removed the .vagrant directory and everything works fine again.

**Comment by gcbw** [comment]
Solution to this is to uninstall virtual box properly!

on windows and OSX, the steps are:

1. Downloaded the LATEST version of virtual box
2. Install it. (even if you think you already uninstalled, for example, deleting from Applications on OSX, you haven't! you can see by clicking the custom install button, you will see some components listed as "upgrade")
3. After you install the new version (on windows, reboot), open the instaler and run the uninstall tool! (all still from the LATEST version of virtual box)
4. now that you install+uninstall the latest version, run vagrant and let it install whatever it wants.

this will solve most of the mess discussed here.

**Comment by Romelhr9** [comment]
Only 1) copy from linux  directory: .vagrant.d/.vagrant/machines/default/virtualbox to windows directory
named on environment variable VAGRANT_HOME, by example:  D:\Virtual\.vagrant.d, in the target directory
%VAGRANT_HOME%\.vagrant\machines\default\virtualbox  2) If the virtualbox in Linux is 5.1, then uninstall the Virtual box of windows 5.2 o greater to install Virtualbox 5.1  3) Run vagrant up but if the error now u=is the creater id is 1000 and you have id 0, then edit the file   createror_uid to put the number 0. and agrin run vagrant up

**Comment by asseto** [comment]
Hi,
how to find that folder to rename?

**Comment by asseto** [comment]
How to find folder to rename?
