### ISSUE TITLE
Machine not found configured for Vagrant

### ISSUE THREAD

**Issue by romu70** [mitchellh/vagrant#5191]
hi,
I've added the darwinanalytics/trusty64 box to my computer. Created a Vagrantfile to run it, made some adjustments on the vm, etc.

Now, I want to repackage this box to create a new base box. My vm is name trusty64, and when I run:
```
vagrant package trusty64
```

I get:
```
The machine with the name 'trusty64' was not found configured for
this Vagrant environment.
```

I've to admit that I don't understand this error message. Any help? Thanks.

**Comment by zunayed** [comment]
I believe you need to run `VBoxManage list vms` to get the name of the box (if you're using virtualbox)

then running vagrant package --base "{{ name of box }}" will output the package.box you can use

**Comment by kikitux** [comment]
also, be sure to remove /etc/udev/rules.d/70-persistent-net.rule if exists

or similar name, check /etc/udev/rules.d/

**Comment by romu70** [comment]
Thanks guys.

My ```/etc/udev/rules.d/``` folder is empty (Fedora 21).

```vboxmanage list vms``` output:

```
"xp-32" {9cb651fd-8334-4e81-9e63-df869ae2540b}
"us-14.04-64" {6a05603a-ec9d-4ad6-b041-e935582a0946}
"ubuntu-1404-64" {2d68a78f-97c9-43d3-b8d0-7824bce168b4}
"trusty64" {df0b61a3-9695-434b-8e55-1a173652caf1}
```

And for @zunayed, I think there is no need to specify ```--base``` now, this raises a ```too many parameters``` error.

**Comment by lonniev** [comment]
@romu70 you need to use the long name for the VirtualBox VM instance and not vagrant's nickname for it.

For example, from:
```bash
Lonnies-MacBook-Pro:virtualbox-tasktopsync lonniev$ VBoxManage list vms
"virtualbox-tasktopsync_vb-tt-dev_1417891266928_15808" {a2e2947f-0fef-46fb-b09f-4d3fa3c20111}
```
I would vagrant package with `virtualbox-tasktopsync_vb-tt-dev_1417891266928_15808`

**Comment by romu70** [comment]
That's because I explicitely change the name of the VM in the Vagrant file. This was really helpful:
http://stackoverflow.com/questions/17845637/vagrant-default-name

**Comment by lonniev** [comment]
Interesting. @sethvargo, is there some nickname to actual name resolution for box names (like trusty64) that would fail if a user like @romu70 happens to change the name of their VM in vagrant to the nickname of one of the hashicorp nicknames?

I'm just guessing at ideas.

**Comment by mitchellh** [comment]
I'm guessing this is all fixed up as its a docs issue!
