### ISSUE TITLE
[feature] Allow declaration of static ip for use with vagrant ssh

### ISSUE THREAD

**Issue by jameskyle** [mitchellh/vagrant#5192]
We do a lot of testing of orchestration environments in vagrant. This includes pxe booting clients. It all works very well except there is no way to declare the ip of a client machine that vagrant can use to ssh.

For example, I'd like to put something like this in a config:

    config.ssh.address = "192.168.1.10"

And vagrant will use that ip for ssh.

This is different then the private_network stanza. This tries to use an existing management interface to ssh into the machine and create a new network. The desire is not to declare an access ip (most likely provided by dhcp server outside of the virtualbox or vmware one) that can be used for vagrant ssh access.

**Comment by kikitux** [comment]
have you seen this plugin?

https://github.com/tknerr/vagrant-managed-servers

**Comment by jameskyle** [comment]
That's interesting, I'll give it a whirl. But it's slightly different.

For example, in my use case you _do_ want to perform up, down, halt, and destroy actions as they are vagrant managed resources....though you're using an separate pxe provisioner.

**Comment by mikhailov** [comment]
there is an idea to bring VirtualBox DHCP server with a pool of 1 IP address only, so you can exactly know which IP address does your dhclient receive.

**Comment by mitchellh** [comment]
For this sort of advanced use case, we prefer folks to use `vagrant ssh-config` and manually configure.

**Comment by jameskyle** [comment]
@mitchellh I may be misunderstanding the purpose or use of ssh-config. But doesn't that output a ssh config file that can be used to ssh into the machine?

Though this is useful, and ssh'ing into the machine manually is perfectly workable, currently vagrant hangs continuously trying to detect the dhcp assigned address. 

If not an option to manually set the ip so the ssh attempt succeeds, perhaps a flag to disable vagrants ssh task so vagrant up exits cleanly after detecting the vm is in a running state?
