### ISSUE TITLE
[hyperv]: VM import process does not respect Secure Boot option from image

### ISSUE THREAD

**Issue by tomassrnka** [mitchellh/vagrant#5209]
The import process (which is used during first vagrant up) does not respect settings for "Secure Boot" (UEFI) from the original config file. After the machine is imported, the "Enable Secure Boot" is always set to ON. 

This results in unbootable VMs (Ubuntu 14.04 LTS tested).

The correct solution would be to get the value from the original XML config and pass the setting to the local VM.

**Comment by mitchellh** [comment]
Fixed by 21e2f33
