### ISSUE TITLE
cannot mount vboxsf synced folders

### ISSUE THREAD

**Issue by SHoar** [mitchellh/vagrant#5212]
I wanted to sync my Django 1.7.3 project folders in my vagrant ubuntu/trusty32 environment with a workspace directory on my Mac OS X 10.10.1 (/Users/myname/Documents/Workspace). Every time I 'vagrant reload' using the documented instructions for synced folders on vagrantup.com, my workspace folder disappears.  I found another article at http://jeremykendall.net/2013/08/09/vagrant-synced-folders-permissions/ that says the permissions must be granted like so:

<code>config.vm.synced_folder "/Users/myname/Documents/Workspace", "/home/vagrant/Projects/", id: "vagrant-root",
      owner = "vagrant",
      group = "www-data",
      mount_options = ["dmode=775","fmode=664"]</code>

Of course this now works, but has wiped everything in my /home/vagrant/Projects/ folder, so now I must destroy the vm and provision a new one, and start all over.  Some guidance would be helpful.

Thank you,

Sean

**Comment by mitchellh** [comment]
There must be something more going on. At a basic level, I can't reproduce this as-is. There must be some scripts or more happening. Can you please post the Vagrantfile with step-by-step repro cases? Thanks

**Comment by SHoar** [comment]
You can close this issue, it is no longer.

**Comment by mitchellh** [comment]
Thanks
