### ISSUE TITLE
Support for ubuntu/trusty64

### ISSUE THREAD

**Issue by eberon** [mitchellh/vagrant#5214]
Is there a compelling reason for using the base box the configurator wants to use? Is it just some pre-installed dependencies?

Things seem fine using ubuntu/trusty64 and I'd rather just save the disk space on my SSD.

**Comment by sethvargo** [comment]
@eberon It is unclear what you are asking here...? Could you please elaborate more?

**Comment by eberon** [comment]
Wrong tab/repo! Whoops
