### ISSUE TITLE
Guest-specific operations on an unprepared machine - Chef (apache2 recipe)

### ISSUE THREAD

**Issue by tripleplus** [mitchellh/vagrant#5215]
New to Vagrant and Chef.  I'm working on a Macbook Pro running OS X 10.10.  Vagrant version is 1.7.2.

My `provision` code:

    config.vm.provision :chef_solo do |chef|
      chef.add_recipe "apt"
      chef.add_recipe "build-essential"
      chef.add_recipe "iptables"
      chef.add_recipe "logrotate"
      chef.add_recipe "apache2"
      chef.json = { :apache => { :default_site_enabled => true } }
    end

Steps to reproduce:

- include above code in `Vagrantfile` with the (last) 2 apache-related lines commented out, i.e.
```
# chef.add_recipe "apache2"
# chef.json = { :apache => { :default_site_enabled => true } }
```
- 'vagrant up' (this works, no errors)
- uncomment the last 2 lines (`end` notwithstanding), i.e.
```
chef.add_recipe "apache2"
chef.json = { :apache => { :default_site_enabled => true } }
```
- `vagrant provision`

The following error message is displayed:

    Guest-specific operations were attempted on a machine that is not
    ready for guest communication. This should not happen and a bug
    should be reported.

`vagrant destroy` followed by `vagrant up` (without re-commenting the offending lines) executes without error.

**Comment by kikitux** [comment]
Hello,

can you try like this:

after you remove the comments

vagrant reload --provision

**Comment by mitchellh** [comment]
This is fixed in master.
