### ISSUE TITLE
unify provider names (vmware vs. vmware_desktop)

### ISSUE THREAD

**Issue by arosenhagen** [mitchellh/vagrant#5227]
I came across this more than once. Why do the provider names of the vmware provider differ between packer and vagrant? With packer we have to build the boxes with `vmware_desktop` but on vagrantcloud/atlas we use them with `vmware`.

**Comment by mitchellh** [comment]
It is all supposed to be `vmware_desktop`. The recommendation on Atlas is just incorrect.

**Comment by arosenhagen** [comment]
ok, the provider is supposed to be named `vmware_desktop`on atlas, but with vagrant I have to start it with `--provider=vmware_fusion`. So maybe the vagrant provider should be renamed?
