### ISSUE TITLE
[provisioner shell] it should be possible to run scripts on a box without uploading it

### ISSUE THREAD

**Issue by berendt** [mitchellh/vagrant#5228]
This is a feature request.

It should be possible to run scripts on a box without uploading it when using the `shell` provisioner. At the moment it is only possible to first upload a local script to a box and to run the uploaded script. I want to be able to run scripts on a box without uploading them first because the scripts are already located on the box.

**Comment by sethvargo** [comment]
Hi @berendt 

Thank you for the feature request. Is there a reason you can't just invoke your script that's already on the VM from inside an `:inline` script?

```ruby
config.vm.provision "shell", inline: "/path/to/my/script.sh"
```

Thoughts?

**Comment by berendt** [comment]
That's how I do it at the moment. In my understanding `inline` should be used to execute small scripts (all statements will be put to `inline`)  and `path` should be used to upload and execute a script. Maybe a note in the documentation in the `EXTERNAL SCRIPT` sections is enough.

**Comment by berendt** [comment]
@sethvargo what do you thing about the referenced PR?

**Comment by sethvargo** [comment]
Looks good to me!
