### ISSUE TITLE
Allow choice of behavior for 'sudo -E' option via config

### ISSUE THREAD

**Issue by donckers** [mitchellh/vagrant#5235]
The change introduced in commit 9cd9e6e55d802553fa90e63d966b302006b45de5 breaks compatibility with sudo < 1.6.9.  I'm not entirely opposed to this functionality as a default, but please give us a means to revert to using sudo without this option in config.

**Comment by sethvargo** [comment]
Hi there,

You can customize the sudo command with `config.vm.sudo_command`:

> `config.ssh.sudo_command` - The command to use when executing a command with `sudo`. This defaults to `sudo -E -H %c`. The `%c` will be replaced by the command that is being executed.

Thanks! 😄
