### ISSUE TITLE
cannot ssh into Docker provided Container

### ISSUE THREAD

**Issue by Hrishike** [mitchellh/vagrant#5236]
I am fairly new to Vagrant and Docker. Here i am trying to setup Vagrant to use the Docker provider to acquire a container and run some provisioning on it such as installing apache. 
While doing so the vagrant up process seems to be stuck at the place where it tries to ssh into the container. 

VAGRANTFILE_API_VERSION = "2"

   Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.provision :shell, inline: 'echo Hi there !!!'
   config.vm.provider :docker do |d|
   d.image ="phusion/baseimage:0.9.16"  
   d.remains_running = true
   d.has_ssh = true
   d.cmd = ["ping","www.google.com"]
   end
   end

Here is what happens when i run sudo vagrant up --provider=docker

hr1sh1@hr1sh1-Rev-1-0 ~/Documents/Learning/e2 $ sudo vagrant up --provider=docker
Bringing machine 'default' up with 'docker' provider...
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
==> default: Creating the container...
    default:   Name: e2_default_1421920372
    default:  Image: phusion/baseimage:0.9.16
    default:    Cmd: ping www.google.com
    default: Volume: /home/hr1sh1/Documents/Learning/e2:/vagrant
    default:   Port: 2202:22
    default:  
    default: Container created: f063ce8b3948119f
==> default: Starting container...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.17.0.29:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...

It keeps going on and doesnt stop.

**Comment by nspaeth** [comment]
There can be only one docker 'cmd', which is the command the container runs when it boots.
Your 'd.cmd' line replaces phusion's '/sbin/my_init --enable-insecure-key' command, which runs init scripts and starts sshd.

If you want to make an additional command run when the machine boots, you have to put it in an init script in /etc/my_init.

**Comment by Hrishike** [comment]
Wow !! I did not know that. I spend a ton of time reading and trying out stuff struggling on this. I got it working now. Thankyou !!!!
