### ISSUE TITLE
Vagrant up should not assume box URL supports resume

### ISSUE THREAD

**Issue by TobyHFerguson** [mitchellh/vagrant#5237]
A box download failed. When I tried to `vagrant up` the image again I got:
```
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

HTTP server doesn't seem to support byte ranges. Cannot resume.
```
Upon receiving this error Vagrant should (preferably) simply delete the image and retry or (probably easiest!) tell the user how they can delete the partially downloaded image, so that repeating the `vagrant up` won't run into the same error.

I resolved my immediate problem by removing the box I found in `~/.vagrant.d/tmp`, thus:
```
[Toby@XX KSplice]$ ls ~/.vagrant.d/
boxes  data  gems  insecure_private_key  rgloader  setup_version  tmp
[Toby@XX KSplice]$ ls ~/.vagrant.d/tmp/
boxee7fdaaa1b07df17bd02710349e937b6666bdb0a
[Toby@XX KSplice]$ rm ~/.vagrant.d/tmp/boxee7fdaaa1b07df17bd02710349e937b6666bdb0a
```

**Comment by squiddle** [comment]
+1

especially since binstore.hashicorp.com (where the atlas boxes come from) is not supporting Range requests.

**Comment by asagage** [comment]
+1

**Comment by nserban** [comment]
+1

**Comment by m4grio** [comment]
+1

**Comment by mitchellh** [comment]
This is now done, will be in next release

**Comment by TobyHFerguson** [comment]
Thank you!

**Comment by Har0ldB1b0y** [comment]
+1

**Comment by coldhand** [comment]
+1

**Comment by maxburto** [comment]
+1

**Comment by andyburton** [comment]
+1

**Comment by peterkinnaird** [comment]
+1
