### ISSUE TITLE
Setting files permissions on synced folders on Windows running CoreOS VM

### ISSUE THREAD

**Issue by cwallervand** [mitchellh/vagrant#5239]
Hi. I have been googleing this issues for ages and I still have not been able to find a proper answer. My  use case for Vagrant and Docker is that I have a simple node application that I would like to run in a Docker container on a Vagrant VM (CoreOS in this case) . 

The goal is for new developers to just use the command `vagrant up` and the app will be up and running and accessible from the host on say localhost:8080. Also the developers should be able to alter the code on the host machine and this changes should be reflected on the running app in the container. My problem is that when i run `docker run  -v /host/path:/container/path` to mount the shared folder the permission of the files are changed (also the user of the files) so I can not run for example `npm install`

## Computer information ##
Host: Windows 7
Vagrant version: 1.7.2

## Project structure ##
* app
     * Gruntfile.js
     * index.js
     * package.json
* Dockerfile
* Vagrantfile

## Dockerfile ##
```
# Pull base image.
FROM dockerfile/nodejs

#Add /app from host to /workspace in container
ADD /app /workspace

#Install grun cli
RUN npm install -g grunt-cli

#set working directory to be /workspace in container
WORKDIR /workspace

CMD ["/bin/bash"]
```

## Vagrantfile ##
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "yungsang/coreos"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

   config.vm.synced_folder ".", "/workspace"

  
  config.vm.define "CoreOS" do |cos|

    cos.vm.provision "docker" do |d|
      d.build_image "/workspace", args: "-t application_container"
    end

  end

end
```

Docker version on the CoreOS VM is 1.3.3, build 5dc1c5a

On the VM the info on the shared files with the host is: 
```
-rwxr-xr-x 1 core core  698 Jan 22 08:15 Gruntfile.js
-rwxr-xr-x 1 core core  381 Jan 21 14:20 index.js
-rwxr-xr-x 1 core core  643 Jan 13 14:54 package.json
```

If i run `docker run -it -p 8080:8080 application_container /bin/bash` the info on the files shared from  the VM to the container (using ADD in Dockerfile) show:
```
-rwxr-xr-x 1 root root 698 Jan 22 08:15 Gruntfile.js
-rwxr-xr-x 1 root root 381 Jan 21 14:20 index.js
-rwxr-xr-x 1 root root 643 Jan 13 14:54 package.json
```

I am at this point allowed to run both `npm install` and `grunt` which start the application. The application is accessible through localhost:8080. All good, except that I can not do changes to my code on the host and have the changes reflected on the container without restarting the container.

So, running `docker run -it -p 8080:8080 -v /workspace/app:/workspace application_container /bin/bash`should solve my problem, i.e. sync the folder on my host to the folder in the container. However, the file information is:
```
-rwxr-xr-x 1  500  500  698 Jan 22 08:15 Gruntfile.js
-rwxr-xr-x 1  500  500  381 Jan 21 14:20 index.js
-rwxr-xr-x 1  500  500  643 Jan 13 14:54 package.json
```

The user for the files have changed and running `npm install` fails (but I can see that the node_modules folder is actually created in my host folder):
```
npm ERR! Linux 3.17.2
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! path ../nopt/bin/nopt.js
npm ERR! code UNKNOWN
npm ERR! errno -1

npm ERR! UNKNOWN, symlink '../nopt/bin/nopt.js'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /workspace/npm-debug.log
```

The npm debug log can be provided if necessary. Noot sure if this is a Docker issue, an Vagrant issue or something else though. I think the problem is related to file permissions on the files in the shared folder on the VM, but I am not sure. Also chmod inside the VM does not have any effect, so I probably need to set permissions using the Vagrantfile, but I have not found a solution for this when host is Windows7 (and VM is CoreOS). Note that using CoreOS is not a requirement for me, I chose it because it allready had Docker installed

**Comment by cwallervand** [comment]
I finally managed to get this working using CentOS on Vagrant and with some cahnges to how the docker container is executed. Closing issue.

**Comment by CharlieC3** [comment]
@cwallervand: How exactly did you change the command executing the docker container? I'm having a similar issue.

**Comment by cwallervand** [comment]
@CharlieC3 I am working on a boilerplate for a Vagrant/Docker setup (running a node application with express and gulp). You can check it out [here](https://github.com/cwallervand/VagrantDockerBoilerplate)
