### ISSUE TITLE
Vagrant is crashing with Windows Guests

### ISSUE THREAD

**Issue by blairham** [mitchellh/vagrant#5240]
I have a box that works fine with vagrant 1.6.5, however when I upgrade to vagrant 1.7.2 it crashes when trying to configure network:

https://gist.github.com/blairham/7b9abe96370b80a60b9c

This box does work on vagrant 1.6.5, you should be able to see my private box on atlas "turbine/windows-2012-r2-core"

**Comment by blairham** [comment]
Here is the output of the exact same environment with Vagrant 1.6.5:
https://gist.github.com/blairham/2dcbb28f1e5a01acb41b

**Comment by uchagani** [comment]
Are you setting the hostname by any chance?  Others have reported a similar issue.

@mitchellh @sethvargo Can you back out PR #4693 

It seems like this workaround for setting the hostname without rebooting is causing a issue for people with server guests.  I can send a new PR if that would be easier.

**Comment by blairham** [comment]
Yes it does set the hostname, you can see the template in the packer-windows github repo.

**Comment by mitchellh** [comment]
This is fixed as we reverted #4693
