### ISSUE TITLE
Gems downloaded over http 

### ISSUE THREAD

**Issue by tomaszzielinski** [mitchellh/vagrant#5243]
Take a look at https://github.com/mitchellh/vagrant/blob/64f81af88999d89e9d3a53b0db03af51cfeabf90/lib/vagrant/bundler.rb#L185 - I'm not sure how often those gems are used but still using https:// would be nice.

The fix is trivial but first you need to fix the SSL certificate as at the moment https://gems.hashicorp.com/ uses a wildcard certificate issued for `*.herokuapp.com`.

Also, if it's possible, you could unconditionally rewrite http://rubygems.org as https://rubygems.org (https://github.com/mitchellh/vagrant/blob/64f81af88999d89e9d3a53b0db03af51cfeabf90/lib/vagrant/bundler.rb#L181), just to stay on the safe side.

**Comment by tomaszzielinski** [comment]
It seems that the rubygems issue is not really an issue: https://github.com/mitchellh/vagrant/issues/3610.

**Comment by mitchellh** [comment]
This shoud be fixed (we default to TLS RubyGems)
