### ISSUE TITLE
New VM on vagrant up instead of resuming already existing VM

### ISSUE THREAD

**Issue by rendler-denis** [mitchellh/vagrant#5248]
Hi guys!

I still have the issue presented here: https://github.com/mitchellh/vagrant/issues/2479
I can reproduce the issue every time. Already did 3 times before I figured out what was the issue.
I am using Win 8.1 and VirtualBox 4.3.16r95972. 
If I suspend the VM upon Vagrant up it just creates a new one.

**Comment by mitchellh** [comment]
See #5205

**Comment by rendler-denis** [comment]
Hey, Mitchell!

Sorry but the issue you mentioned has nothing to do with the problem I was referring to.
The machine is destroyed immediately upon booting and not when sending the SSH key.

I was hopping for a solution, but I guess my best bet is to look for something else.

Thanks anyways,
Denis

**Comment by mitchellh** [comment]
Errr, I think I meant #5105. Is that better?

**Comment by rendler-denis** [comment]
Hey, Mitchell!

The issues seem to be similar, but I still can't find a solution.
In my case the VM is also removed from VirtualBox.
It seems that everyone is talking about the problem but there is no solution in sight.

I will try to attach a log later today, as I can reproduce the issue every time.

Thanks,
Denis
