### ISSUE TITLE
How to docker pull?

### ISSUE THREAD

**Issue by schmunk42** [mitchellh/vagrant#5249]
I noticed that destroying a container and recreating it does not pull the latest version of an image from Docker Hub. I expected Vagrant to do so or do I need to explicitly run the Docker provisioner to pull the latest image layers?

My workaround at the moment is to SSH into the Docker host-VM and run `docker pull ...` there.

Using Vagrant 1.7.1.

**Comment by mitchellh** [comment]
Fixed
