### ISSUE TITLE
Ordering issue: extra disk attached before VM exists

### ISSUE THREAD

**Issue by carroarmato0** [mitchellh/vagrant#5250]
I have a situation where I'd like 2 "storage" vagrant boxes to have for each, an extra disk created and attached with Virtualbox.

This works for 1 VM, but with multiple ones it's different:

<pre>
  storage01_extra_disk = '/tmp/storage01_extra_disk.vdi'
  storage02_extra_disk = '/tmp/storage02_extra_disk.vdi'

  config.vm.define "storage01" do |storage01|
    storage01.vm.provider "virtualbox" do |v|
      v.name = 'gluster-storage01'
    end
    storage01.vm.hostname = "storage01"
    storage01.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "storage02" do |storage02|
    storage02.vm.provider "virtualbox" do |v|
      v.name = 'gluster-storage02'
    end
    storage02.vm.hostname = "storage02"
    storage02.vm.network "private_network", ip: "192.168.33.12"
  end

  ## Create and/or attach a secondary disk to be used for data in Gluster
  config.vm.provider "virtualbox" do |v|

    unless File.exist?(storage01_extra_disk)
      v.customize ['createhd', '--filename', storage01_extra_disk, '--size', 500 * 1024]
    end
    v.customize ['storageattach', 'gluster-storage01', '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storage01_extra_disk]

    unless File.exist?(storage02_extra_disk)
      v.customize ['createhd', '--filename', storage02_extra_disk, '--size', 500 * 1024]
    end
    v.customize ['storageattach', 'gluster-storage02', '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storage02_extra_disk]

  end
</pre>

This gives me the following issue:

<pre>
[carroarmato0:~/Work/Vagrant/Gluster] master(+28/-4) ± vagrant up 
Bringing machine 'storage01' up with 'virtualbox' provider...
Bringing machine 'storage02' up with 'virtualbox' provider...
Bringing machine 'client01' up with 'virtualbox' provider...
Bringing machine 'client02' up with 'virtualbox' provider...
==> storage01: Importing base box 'https://dumps.carroarmato0.be/vagrantboxes/centos-6.6-64b-puppet-vbox.box'...
==> storage01: Matching MAC address for NAT networking...
==> storage01: Setting the name of the VM: gluster-storage01
==> storage01: Clearing any previously set network interfaces...
==> storage01: Preparing network interfaces based on configuration...
    storage01: Adapter 1: nat
    storage01: Adapter 2: hostonly
==> storage01: Forwarding ports...
    storage01: 22 => 2222 (adapter 1)
==> storage01: Running 'pre-boot' VM customizations...
A customization command failed:

["storageattach", "gluster-storage02", "--storagectl", "IDE Controller", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "/tmp/storage02_extra_disk.vdi"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "gluster-storage02", "--storagectl", "IDE Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", "/tmp/storage02_extra_disk.vdi"]

Stderr: VBoxManage: error: Could not find a registered machine named 'gluster-storage02'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 313 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.
</pre>

It looks like right after the first VM is created, it calls the virtualbox customize stanza's, but doesn't stop with the first one.

I think it would be possible to fix this by having a conditional to see if the stanza is called within the context of a certain VM, excluding the none relevant sections.

Something like:

<pre>
unless v.name == 'gluster-storage01'
</pre>

Any idea?

**Comment by mitchellh** [comment]
This doesn't look like a bug but looks like a usage quesiton. Can you please ask this on the mailing list? You'll get a much better response there.

**Comment by carroarmato0** [comment]
Just a quick follow up:  Indeed, it was a usage issue. Got it fixed, for reference in case people stumble upon this same question, here's how I solved it:

I had to place the provider and the unless conditional within the context of the VM I wanted to create.

<pre>
  storage01_extra_disk = 'storage01_extra_disk.vdi'
  storage02_extra_disk = 'storage02_extra_disk.vdi'

  config.vm.define "storage01" do |storage01|
    storage01.vm.provider "virtualbox" do |v|
      unless File.exist?(storage01_extra_disk)
        v.customize ['createhd', '--filename', storage01_extra_disk, '--size', 500 * 1024]
      end
      v.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storage01_extra_disk]
    end
    storage01.vm.hostname = "storage01.local"
    storage01.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "storage02" do |storage02|
    storage02.vm.provider "virtualbox" do |v|
      unless File.exist?(storage02_extra_disk)
        v.customize ['createhd', '--filename', storage02_extra_disk, '--size', 500 * 1024]
      end
      v.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', storage02_extra_disk]
    end
    storage02.vm.hostname = "storage02.local"
    storage02.vm.network "private_network", ip: "192.168.33.12"
  end
</pre>
