### ISSUE TITLE
~/.vagrant.d/Vagrantfile not being loaded

### ISSUE THREAD

**Issue by joech4n** [mitchellh/vagrant#5251]
Can anyone provide any insight on why this may be happening?
    
    ~> vagrant --version                                                                                                          [21:35:10]
    Vagrant 1.7.2

    ~> vagrant up                                                                                                                 [21:35:24]
    A Vagrant environment or target machine is required to run this
    command. Run `vagrant init` to create a new Vagrant environment. Or,
    get an ID of a target machine from `vagrant global-status` to run
    this command on. A final option is to change to a directory with a
    Vagrantfile and to try again.

    ~> env |grep VAGRANT_HOME                                                                                                     [21:35:43]
    VAGRANT_HOME=/Users/username/.vagrant.d

    ~> cat ~/.vagrant.d/Vagrantfile                                                                                               [21:35:13]
    # Require YAML module
    require 'yaml'
    
    # Read YAML file with box details
    aws_config = YAML.load_file(File.expand_path("~") + "/" + ".vagrant-aws")
    
    Vagrant.configure("2") do |config|
      config.vm.box = "dummy"
    
      config.vm.provider :aws do |aws, override|
    
        # Load from config file
        aws.access_key_id = aws_config["access_key_id"]
        aws.secret_access_key = aws_config["secret_access_key"]
        aws.keypair_name = aws_config["keypair_name"]
    
        # Customizations
        aws.region = "us-west-2"
        aws.associate_public_ip = true
        aws.security_groups = ["sg-4ed6cb22", "sg-ac4b0dc9"]
        aws.subnet_id = "subnet-65c6780c"
        aws.tags = {
          "Name" => "Vagrant Dummy Box",
          "Stack" => "test"
        }
        aws.ami = "ami-3d50120d" # Ubuntu Server 14.04 LTS (HVM), SSD Volume Type
        aws.instance_type = "t2.small"
        #aws.iam_instance_profile_name = "VagrantRole"
    
        # Override config above with anything specified in config file
        aws_config.each do |key, value|
          aws.send("#{key}=",value)
        end
    
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = File.expand_path("~") + "/.ssh/id_rsa"
      end
    
    
      # Disable sync folder
      config.vm.synced_folder ".", "/vagrant", disabled: true
    
    end

Please let me know if I can provide any more info.

Thanks!

**Comment by mitchellh** [comment]
A Vagrantfile (if even blank) is still required in your cwd to launch.
