### ISSUE TITLE
Vagrant Destroy reading wrong vagrantfile

### ISSUE THREAD

**Issue by gwagner** [mitchellh/vagrant#5253]
Lets say i have Vagrantfiles in dir a/Vagrantfile b/Vagrantfile and c/Vagrantfile

Lets say i vagrant up a/ and b/.  How i have running machines from both directories.

Now i am in c/ and i do a vagrant global status and get the hash of a machine.

From inside of the c/ dir i run a vagrant destroy [hash from the a/Vagrantfiles box], Vagrant will combine the vagrantfile from a/ and c/ when running the vagrant destroy.  It wont destroy the box from the c/Vagrantfile, but if you define variables in any of the Vagrant files, it will complain that constants are being duplicated.

Output from such an operation: 

```
> vagrant destroy 18ffa83
    consul2: Are you sure you want to destroy the 'consul2' VM? [y/N] y
==> consul2: Discarding suspended state...
==> consul2: Deleting the VM...
==> consul2: Running cleanup tasks for 'hosts' provisioner...
==> consul2: Running cleanup tasks for 'shell' provisioner...
==> consul2: Running cleanup tasks for 'shell' provisioner...
==> consul2: Running cleanup tasks for 'puppet' provisioner...
a/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
c/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
a/Vagrantfile:7: warning: already initialized constant BOXNAME
c/Vagrantfile:7: warning: previous definition of BOXNAME was here
a/Vagrantfile:8: warning: already initialized constant HOSTNAME
c/Vagrantfile:8: warning: previous definition of HOSTNAME was here
```

**Comment by jfbibeau** [comment]
You can reproduce this even with only one vagrant box. If you run `vagrant global-status --prune` in the same folder as a Vagrantfile, it'll complain about the constants being duplicated:

```
$ vagrant global-status --prune
id       name   provider   state   directory                                 
-----------------------------------------------------------------------------
b0349f9  latest virtualbox running /home/build-tools/vagrant 
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
/home/build-tools/vagrant/Vagrantfile:4: warning: already initialized constant VAGRANTFILE_API_VERSION
/home/build-tools/vagrant/Vagrantfile:4: warning: previous definition of VAGRANTFILE_API_VERSION was here
```

**Comment by emcee21** [comment]
I am running into a form of this issue too.  Two separate Vagrantfiles in totally separate directories, but cloned from the same git repo.  I am seeing "already initialized constant" warnings which raises concerns that my VMs are in a corrupted state.

**Comment by ctrlaltdylan** [comment]
Experiencing this on Ubuntu 14.03 with 2 homestead instances.

**Comment by ctrlaltdylan** [comment]
Fixed by completely destroying one of the instances:

1) `vagrant global-status`
2) Identify corrupted vagrant box
3) `vagrant destroy --force {vagrant-box-id}`

**Comment by mitchellh** [comment]
I just tried on master with the exact scenario you described @gwagner and it worked fine. Also no constant redeclaration issues. I remember fixing issues around this so this might all just be working now. Sorry for that!
