### ISSUE TITLE
Unable to Set Memory for HyperV

### ISSUE THREAD

**Issue by tysonjhayes** [mitchellh/vagrant#5260]
Per the [documentation](https://docs.vagrantup.com/v2/hyperv/configuration.html) for Hyper-V I should be able to set the the memory of my virtual machine like so:

```ruby
  config.vm.define "web" do | web |
    web.vm.box = "mwrock/Windows2012R2"
    web.vm.hostname = "web"
    web.vm.guest = :windows
    web.vm.provider :hyperv do | v |
      v.ip_address_timeout = 240
      v.memory = 1024
    end
  end
```

Unfortunately this results in the error:
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Hyper-V:
* The following settings shouldn't exist: memory

This also occurs when attempting to set vmname, maxmemory, and cpus.  Am I doing something wrong here or is this functionality not actually implemented yet?

**Comment by ssugar** [comment]
Looks like this is being addressed in 1.7.3.  If you want the fix now, the commit that includes this fix is at: https://github.com/mitchellh/vagrant/commit/a9ac168b197a4f408cabf37c26ab6c3337cb8ecd

**Comment by tysonjhayes** [comment]
@ssugar thanks for the info. I'm having some trouble getting the dev environment setup on my Windows box. Is there a timeline on when this should be released?

**Comment by ssugar** [comment]
I haven't seen an official timeline for 1.7.3.  I looked around and decided that I didn't want to wait for the official release.

So if you can't wait (like me), then you can manually update using the files updated in the commit I pointed to above (these have also been merged into the master branch). 

Assuming you've installed Vagrant 1.7.2 for windows, then you can just update the following 3 files on your machine:
1. C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyperv\action\import.rb
2. C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyperv\config.rb
1. C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyperv\scripts\import_vm.ps1

You'll grab the updated file content from here:
1. https://raw.githubusercontent.com/mitchellh/vagrant/master/plugins/providers/hyperv/action/import.rb
2. https://raw.githubusercontent.com/mitchellh/vagrant/master/plugins/providers/hyperv/config.rb
3. https://raw.githubusercontent.com/mitchellh/vagrant/master/plugins/providers/hyperv/scripts/import_vm.ps1

There's probably a more official way of pulling these recent changes onto your machine, but what I did was add .bak as a file extension to the 3 files on my machine, then went to the raw pages for the updated files on GitHub in the master branch of mitchellh/vagrant, copied and pasted them into new files. 

Once that was done, I was able to successfully create VMs in hyperV with a customized vmname, memory and cpucount.

Hope that helps.

**Comment by ssugar** [comment]
BTW - I put up a gist for how to set up the Vagrant bleeding edge on Windows 8.1/2012 R2
https://gist.github.com/ssugar/284c7ed6a2cb764b3285

Let me know if that helps or not.

**Comment by tysonjhayes** [comment]
@ssugar Your notes on how to upgrade everything worked. Had some trouble with your gist but I'll open an issue there when I've had time to dive into a bit more.
