### ISSUE TITLE
Vagrant NFS with Yosemite can't write /etc/exports file

### ISSUE THREAD

**Issue by cyberkurumin** [mitchellh/vagrant#5262]
nnWhen launching vagrant with VirtualBox on a mac on Yosemite, all the process go fine, but when it tries to write modifications on the /etc/exports files in order to mount the nfs shared folders, it just say it can't find the file.

> zsh:1: no such file or directory: echo '# VAGRANT-BEGIN: 501 0f2d6acb-899c-44f1-aab6-1604e21aca1b' >> /etc/exports

And the same error for all the folders that should be shared.

Any clue how to fix it?

Thanks to everyone.

**Comment by mitchellh** [comment]
Please ask this on the mailing list. We've been running Yosemite since the beta and have never had this issue so I imagine it is environmental.
