### ISSUE TITLE
Typo in doc: Project Setup

### ISSUE THREAD

**Issue by hamishwillee** [mitchellh/vagrant#5266]
https://docs.vagrantup.com/v2/getting-started/project_setup.html

Text from:
  The first step for any project to use Vagrant is to configure Vagrant using a Vagrantfile. 

To:
  The first step for configuring any Vagrant project create a Vagrantfile. 

As an aside, your documentation looks very attractive. Middleman looks like a reasonable alternative to Jekyll, but perhaps not quite as impressive as Sphinx.

**Comment by sethvargo** [comment]
Hi @hamishwillee 

The documentation is all open source and lives in this repo (under the `website/` directory). Would you like to submit a PR? I'm happy to fix this myself, but I wanted to provide an opportunity if you'd like to contribute :smile:

**Comment by hamishwillee** [comment]
HI Seth

Sorry, but I am not going have time to set up the necessary documentation
fork etc  at this point.

Regards
Hamish

**Comment by mixpix3ls** [comment]
Changed:
The first step for any project to use Vagrant is to configure Vagrantusing a Vagrantfile.

To:
The first step in configuring any Vagrant project is to create a Vagrantfile.

**Comment by sethvargo** [comment]
Fixed in a755cf2
