### ISSUE TITLE
Discussion/Bug - Virtualbox instances build off of one box file have same MAC address

### ISSUE THREAD

**Issue by vinyar** [mitchellh/vagrant#5271]
This can lead to issues with Windows.

Particularly, if one of the boxes has been promoted to a domain controller and another one attempts to join that DC. This results in errors / warnings due to identical MAC address present on the network. 

The error originates from the MAC address hardcoded into the Vagrantfile in .vagrant.d/boxes/SomeWindowsBox/virtualbox/Vagrantfile

I was wondering if there is a particular reason why MAC address can't be randomly generated for each instance? Comparing current behavior of multiple instances having the same MAC address vs randomly generating MAC, seems that latter is a safer option with one less thing to define in Vagrantfile.

The two workarounds are to either set the address via base_mac and let vagrantfile precedence take over
```config.vm.base_mac = "1234567890AB```

or via the provider setting:
```ruby
config.vm.provider :virtualbox do |p|
  p.customize ["modifyvm", :id, "--memory", "1024", "--clipboard", "bidirectional", "--macaddress1", "1234567890AB"]
end
```

The Vagrantfile Template
```ruby
Vagrant::Config.run do |config|
  # This Vagrantfile is auto-generated by `vagrant package` to contain
  # the MAC address of the box. Custom configuration should be placed in
  # the actual `Vagrantfile` in this box.
  config.vm.base_mac = "0800279A9B64"
end

# Load include vagrant file if it exists after the auto-generated
# so it can override any of the settings
include_vagrantfile = File.expand_path("../include/_Vagrantfile", __FILE__)
load include_vagrantfile if File.exist?(include_vagrantfile)
```

Thank you

**Comment by mitchellh** [comment]
You're welcome to randomly generate them. Most boxes hardcode them because the OS requires the MAC address to not change for network interfaces in the box to work properly. If your box doesn't require this, then randomize it!

**Comment by vinyar** [comment]
I think you misunderstand me.

My point was that multiple instances generated off of the same box file will have identical mac address. I was proposing randomizing the MAC address on creation of the box to avoid network collisions.

I agree that randomizing the network address on each vagrant up would not be beneficial.
