### ISSUE TITLE
Vagrant loses track of existing VirtualBox VMs

### ISSUE THREAD

**Issue by dowlingw** [mitchellh/vagrant#5276]
We've had a number of developers have issues with Vagrant losing track of Virtualbox VMs.

Spinning up a new ticket because this differs from existing reported cases:
* Developers are not issuing a `vagrant suspend` command
* Observed across multiple platforms (Windows, OSX)
* Users are not changing the execution environment (user running vagrant command, HOME variable, etc)

As far as I can tell:
* Users are not suspending their hosts

Similar issues:
* #2479 
* #5105
* #5248 

Observed on:
* Windows 7 Profecssional, SP1, VirtualBox Version 4.3.12 r93733, Vagrant 1.6.3
* OSX 10.10.2, VirtualBox 4.3.20

Not a lot to go on, I will update this ticket with some followup information as it becomes available. If there's not enough info in this ticket, happy to close.

Viewing the other tickets, it seems that the VirtualBox API seems to be fragile to work around, so understand there is limited action we can take.

**Comment by dowlingw** [comment]
Confirmed that on both machines, the user has multiple (3 and 8) duplicate virtual machines for the same Vagrant profile.

**Comment by mitchellh** [comment]
I think #5105 is the best conversation happening there, and is explained in detail.
