### ISSUE TITLE
vagrant asks for password during operations

### ISSUE THREAD

**Issue by vadviktor** [mitchellh/vagrant#5278]
Hello,

I have a Win 8.1 host with Vmware Workstation 11, using a custom ubuntu 1404 x64 built box (that is much like the default as described in the docs). Vagrant version is 1.7.2. Whenever I boot up/suspend/halt the box I get asked for vagrant@ user's password and a message about text being echoed in clear text.

I have provisioned the box to replace the .ssh/authorized_keys with my own key (as it is also replacing the insecure key on it's own), but I don't know if that could interfere with this as to my understanding vagrant uses root with the default password (am I right?).

I have copied most of the logs in debug mode at boot up time and a small shutdown log:

https://gist.github.com/vadviktor/d99fecc3e9d8db082152

Is this a severe problem or just an annoyance for now, until the problem is identified and fixed?

Also if I can be of any help to debug/fix please instruct me :)

**Comment by vadviktor** [comment]
Tested the box with my own ssh key already added to the authorized_keys and Vagrant still asks for vagrant@ user's password on boot up. :(

**Comment by vadviktor** [comment]
Downgraded Vagrant to 1.7.1 but the issue is still there. :(

**Comment by vadviktor** [comment]
Alright I think I have tracked down my problem, which was to use my own key BUT also to tell vagrant where the private key is. Now it works like a charm.

Question: should I add a few lines to vagrant doc to warn new power users when they build their own box to take care of these settings not to get hiccups like I did?

**Comment by mitchellh** [comment]
@vadviktor I'd really appreacite a doc PR to fix this. Thanks!
