### ISSUE TITLE
Vagrant 1.7.2 breaks /etc/network/interfaces

### ISSUE THREAD

**Issue by zigomir** [mitchellh/vagrant#5279]
Getting this error

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1

Stdout from the command:



Stderr from the command:

stdin: is not a tty
/etc/network/interfaces:31: interface eth2 declared allow-auto twice
/sbin/ifup: couldn't read interfaces file "/etc/network/interfaces"
```

Looking into `/etc/network/interfaces` file I can see that `eth2` was generated twice. I'm using Debian 7.8 and my config is:

```
config.vm.network :private_network, ip: '192.168.56.10'
config.vm.network :public_network,  bridge: 'en0: Wi-Fi (AirPort)'
```

Downgrading to 1.7.1 fixes problem for me.

**Comment by sethvargo** [comment]
Hi @zigomir I think this is the same as https://github.com/mitchellh/vagrant/issues/5180, just presenting slightly different. Can you please confirm?

**Comment by zigomir** [comment]
Hi, yes, it certainly looks like so. Thanks! Closing because issue is already reported in #5180.

**Comment by sethvargo** [comment]
Thanks! I just wanted to make sure before closing it myself. You can subscribe to the other issue or just leave a comment to get updates :smile:
