### ISSUE TITLE
Why Vagrantfile is not named Vagrantfile.rb?

### ISSUE THREAD

**Issue by tklo** [mitchellh/vagrant#5281]
Renaming Vagrantfile to Vagrantfile.rb would make things easier - like syntax highlighting in text editors for instance.

**Comment by mbrodala** [comment]
I'd assume to stay in line with other similar `*files` like `Gemfile` or `Puppetfile`. And I can tell you that Sublime recognizes `Vagrantfile` as Ruby file perfectly fine once assigned. ;-)

**Comment by ju2wheels** [comment]
Rename it to whatever you want and use the `VAGRANT_VAGRANTFILE` environment variable to set the name.

**Comment by sethvargo** [comment]
The file is named `Vagrantfile` in accordance with other Ruby-file tools like mentioned above. You can name the file whatever you want and then set the `VAGRANT_VAGRANTFILE` environment variable. It is unlikely we will change this for backwards-compatability reasons.
