### ISSUE TITLE
http://downloads.vagrantup.com is out of date

### ISSUE THREAD

**Issue by reversefold** [mitchellh/vagrant#5284]
It should redirect to https://www.vagrantup.com/downloads.html

**Comment by sethvargo** [comment]
Hi there,

That downloads page houses old versions of vagrant and will be retired sometime in the future. New versions of vagrant can be downloaded from /downloads.html.

**Comment by reversefold** [comment]
Sure, but it's not obvious that it houses only old versions. If you follow
a link to that page to download vagrant (as I did recently at my job) there
is no obvious indication that 1.3.5 is not the newest version. Why not
label it an archive with a link to the newest version page at the top?

On Tuesday, February 3, 2015, Seth Vargo <notifications@github.com> wrote:

> Hi there,
>
> That downloads page houses old versions of vagrant and will be retired
> sometime in the future. New versions of vagrant can be downloaded from
> /downloads.html.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/5284#issuecomment-72787159>.
>


-- 
Justin Patrin
Developer Extraordinaire

**Comment by sethvargo** [comment]
Hi @reversefold 

The old downloads page now redirects.

**Comment by reversefold** [comment]
Thanks.

On Wed, Feb 4, 2015 at 8:02 AM, Seth Vargo <notifications@github.com> wrote:

> Hi @reversefold <https://github.com/reversefold>
>
> The old downloads page now redirects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/5284#issuecomment-72881162>.
>



-- 
Justin Patrin
Developer Extraordinaire
