### ISSUE TITLE
Changes to rsync__exclude not being detected for Virtualbox

### ISSUE THREAD

**Issue by craiga** [mitchellh/vagrant#5285]
It looks like once `rsync__exclude` has been set, it's locked to the value stored in `.vagrant/machines/default/virtualbox/synced_folders`.

My `Vagrantfile` builds a list of exclude patterns as shown:

    # Read .gitignore and build an array of file patterns to exclude
    rsync_exclude_patterns = [".git"]
    if File.readable?("my-project-source/.gitignore")
      File.open("my-project-source/.gitignore") do |f|
        f.each_line do |line|
          rsync_exclude_patterns << line.chomp
        end
      end
    end
    
    # Set up shared folders
    config.vm.synced_folder "my-project-source", "/var/my-project",
      type: "rsync",
      owner: "my-project",
      group: "my-project",
      rsync__args: ["--recursive",  "--links", "--times", "--compress", "--delete"],
      rsync__exclude: rsync_exclude_patterns

This builds a list of patterns from `.gitignore` and sends them to `rsync`.

When I change `rsync__exclude`—either by changing `.gitignore` or by setting `rsync__exclude` to something simple like `["a", "b", "c"]`—the value doesn't change.

It seems that the value is being read from `.vagrant/machines/default/virtualbox/synced_folders` and this file isn't being updated.

This worked in 1.6.5, but is broken in 1.7.2.

My workaround at the moment is to `vagrant destroy; vagrant up` every time I change this list.

**Comment by marek-saji** [comment]
> My workaround at the moment is to vagrant destroy; vagrant up every time I change this list.

Found simpler (faster than recreating whole machine) workaround:

```
vagrant halt ; rm -v .vagrant/machines/*/virtualbox/synced_folders ; vagrant up
```

File will be recreated with the next sync.

**Comment by mitchellh** [comment]
I've updated the documentation for this, but it requires a `reload`. This is working as intended.
