### ISSUE TITLE
Insufficient graphic memory for boot2docker Vbox VM when using docker provider with force_host_vm

### ISSUE THREAD

**Issue by olberger** [mitchellh/vagrant#5287]
I'm testing the docker provider using force_host_vm = true to instantiate a VirtualBox boot2docker VM on Linux (trying to test what would happen when on Windows).
It seems that the VM is created using only 8 Mb of graphic memory, which VirtualBox reports as insufficient for displaying the graphic console (tells that 9 Mb is the minimum), 
Hence, the VirtualBox gui = true won't apply and the VM stays headless, which doesn't help when vagrant ssh won't work, which renders it complex to login to the VM for debugging.

I'd suggest to change the defaults so that 9 Mb are used.

**Comment by olberger** [comment]
AFAIU, it is possible to workaround this by using a custom Vagrantfile for boot2docker, like:
```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "app" do |app|
    app.vm.provider "docker" do |d|
      d.force_host_vm = true
      d.build_dir = "."
      d.vagrant_vagrantfile = 'Vagrantfile_hostVM'
    end
  end
```
where Vagrantfile_hostVM contains:
```
 Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "mitchellh/boot2docker"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  
    vb.customize ["modifyvm", :id, "--vram", "36"]
  end
...
```

**Comment by mitchellh** [comment]
Thanks, can you please report this to the boot2docker-vagrant-box project? We can add it there.
