### ISSUE TITLE
Mistranslated Windows path with drive letter to incorrect file://drive:/ URL (during box add)

### ISSUE THREAD

**Issue by rct** [mitchellh/vagrant#5288]
Windows path with drive letter, v:\tmp\file.box, got translated into file://v:/tmp/file.box instead of file:///v:/tmp/file.box.  

The drive letter wound up in the host portion instead of the path, so it winds up being ignored.  

Manually translating the Windows path works  (file:///v:/tmp/file.box)

This might be related to #2081 (which looks like it added Windows path translation to the core)

Vagrant version 1.7.2, Windows 7, 64 bit.

```
C:\rct>vagrant box add rhel7-ws v:\tmp\download\rhel7-ws.box
==> box: Adding box 'rhel7-ws' (v0) for provider:
    box: Downloading: file://v:/tmp/download/rhel7-ws.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /tmp/download/rhel7-ws.box
```

**Comment by mitchellh** [comment]
Fixed
