### ISSUE TITLE
Use a persistent SSH connection for rsync/rsync-auto

### ISSUE THREAD

**Issue by fivetanley** [mitchellh/vagrant#5289]
It'd be neat to cut out the little bit of start up time when using the rsync synced folder strategy. I'd be willing to implement this if the maintainers of the project think it's a good idea.

http://www.revsys.com/writings/quicktips/ssh-faster-connections.html

**Comment by mitchellh** [comment]
Hm, neat. I'd be open to seeing a PR. I suppose the control files can be put into the machine data directory, which would be pretty clever. I say go for it, I'd love to see this.
