### ISSUE TITLE
Vagrant ssh -c locks locks up on background jobs

### ISSUE THREAD

**Issue by andrew-morris** [mitchellh/vagrant#5291]
This looks similar to another issue, but I think that affected a separate version. [This page](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#162-may-12-2014) claims the issue was fixed in ```1.6.2```, but I'm still seeing this behavior. System is running Ubuntu 14.04.

```
$ vagrant --version
Vagrant 1.7.2
```
```
$ time vagrant ssh -c 'timeout 5 sudo tcpdump -w /vagrant/capture.pcap' 
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
2 packets captured
2 packets received by filter
0 packets dropped by kernel
Connection to 127.0.0.1 closed.

real	0m6.662s
user	0m1.181s
sys 	0m0.342s
```
```
$ time vagrant ssh -c 'timeout 5 sudo tcpdump -w /vagrant/capture.pcap &' 
Connection to 127.0.0.1 closed.

real	0m1.702s
user	0m1.174s
sys 	0m0.334s
```

**Comment by r4v5** [comment]
Is the vagrant locked during either of these commands?
Locking in the context of that changelog entry refers to seeing the `machine_locked` message (https://github.com/mitchellh/vagrant/blob/7a006a3093f9554fc7d393299ef6866583ad8813/templates/locales/en.yml#L809) and not running those commands.

**Comment by mech** [comment]
Having this issues also.. a Vagrant 1.7.2 with fusion 7.1.1 will hang whenever using tcpdump command. My Ubuntu is 14.10.

Will required my machine to do a total reboot in order for Fusion to not have "Cannot find a valid peer process to connect to" dialog.

**Comment by mitchellh** [comment]
Background won't continue running unless you detach from the shell. I'll update the documentation for this.
