### ISSUE TITLE
Documentation clarification for Windows boxes

### ISSUE THREAD

**Issue by dabide** [mitchellh/vagrant#5294]
The documentation for Windows base boxes says that UAC should be disabled. Perhaps a note should be added that in Windows 8/8.1, it is not enough to pull the slider to "Never notify". UAC has to be disabled in the registry, for instance this way:

`reg add HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /d 0 /t REG_DWORD /f /reg:64`

Vagrant seems to work without this, but things like installing Puppet will fail, which confused me immensely.

**Comment by mitchellh** [comment]
Done, thanks!
