### ISSUE TITLE
Rsync-auto prevents writing any files in guest

### ISSUE THREAD

**Issue by msumme** [mitchellh/vagrant#5296]
I'm using cygwin and the shared folders are rsync'ed to the guest machine.

On the guest machine, I create a file in an empty directory.

rsync-auto seems to keep deleting it, because it's an empty directory on the host machine.

I don't want to make rsycnc the default type as this environment also needs to be usable on a mac.  Can I set rsync options w/o forcing the type to be rsync?

**Comment by mitchellh** [comment]
You can manually specify `rsync__args` to specify the CLI flags. By default if this isn't specified the `--delete` flag is present which is causing the behavior your'e describing.
