### ISSUE TITLE
Provide vagrant_latest_{arch}.deb for automatic download

### ISSUE THREAD

**Issue by erickeller** [mitchellh/vagrant#5299]
Hi everyone,

https://dl.bintray.com/mitchellh/vagrant/ web server could provide a link to the latest vagrant version in order to automatically grab the appropriate version without knowing the detail numbers

for example:
https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb => https://dl.bintray.com/mitchellh/vagrant/vagrant_latest_x86_64.deb

Best RegardsRegards

**Comment by gboddin** [comment]
Please check 
https://github.com/mitchellh/vagrant-installers/issues/12#issuecomment-72077009
and
https://gist.github.com/gboddin/d3fa7e386868a0862b81

Vagrant has no control on bintray, so ... as they say, deal with it ...

**Comment by mitchellh** [comment]
Sorry, but @gboddin is correct. We have a service we've written for our Go products to do this, but we haven't ported it yet for Vagrant's path. One day, but not a priority. You can use the Bintray API yourself to do this, as well, if it is critical.
