### ISSUE TITLE
running vagrant package appears to succeed, but no box is created

### ISSUE THREAD

**Issue by lmcardle** [mitchellh/vagrant#5300]
When I run vagrant package, the command appears to succeed, i.e. there are no errors thrown, but after it is complete there is no box created.  Here is a copy of my --debug output: https://gist.github.com/lmcardle/9cd91efb137dfe27fd10.

I am using vagrant version 1.7.2 and ruby version 2.1.2p95

Any thoughts on what might be causing this

**Comment by mitchellh** [comment]
Thanks! This is a dup of #4543
