### ISSUE TITLE
Official multi-provider trusty64 box

### ISSUE THREAD

**Issue by lewisl9029** [mitchellh/vagrant#5304]
I've been looking for a trusty64 vagrant box that supports all the providers that are supported on https://atlas.hashicorp.com/hashicorp/boxes/precise64, but was not able to find one.

Having such a box officially would be valuable because everyone has their own preferences for virtualization suites. Right now we're using an ugly workaround to specify a specific box using an environmental variable, which can be fairly error-prone.

**Comment by sethvargo** [comment]
Hi there,

Vagrant boxes are community-created and driven. I would recommend asking this request on the Vagrant mailing list to see if a member of the community has any recommendations on boxes.
