### ISSUE TITLE
Vagrant throws Unknown configuration section for plugins installed and executed with config extensions

### ISSUE THREAD

**Issue by hallatech** [mitchellh/vagrant#5306]
In my Vagrantfile I include checks to find and install required plugins, but if its a first time installation for a plugin and that plugin has configuration extensions Vagrant throws an error after installing the plugin.

Example: Requires vbguest and triggers
```
    #------------------------------------------------------------------------------
    #Auto install required plugins 
    #------------------------------------------------------------------------------
    required_plugins = %w( vagrant-vbguest vagrant-triggers)
    required_plugins.each do |plugin|
        system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
    end
```
Result of this statement is both plugins are installed if not available on the host - no problem. 

Later in the Vagrant file we have:
```
Vagrant.configure("2") do |config|
        config.vm.define vm_instance_name do |vm_config|
        ...
          vm_config.trigger.after [:up, :resume, :reload] do
              ...
          end    
      end
end
```

Vagrant error:
There are errors in the configuration of this machine. Please fix
the following errors and try again:
```
Vagrant:
* Unknown configuration section 'trigger'.
```

If I simply run '''vagrant up''' again it continues and works as expected.
If I pre-install the plugin before the first up, it works ok.
I've tried this with another plugin that has config extensions and the same pattern occurs.

The vbguest plugin just works under the covers without any config extension so it doesn't experience this problem, although it does prompt you for the host user password. 

So my question is, are plugins that extend configuration able to be included this way and be installed on first pass or do they always required to be pre-installed due to some Vagrant/Ruby specific parsing issue?

**Comment by sethvargo** [comment]
Hi @hallatech,

Plugins are loaded when Vagrant "boots", and their configurations and configurable are merged with Vagrant's top-level configuration. So, installing a plugin from inside the `Vagrantfile` will cause the plugin to not be loaded until the next Vagrant run as you describe.

I would generally caution you from `exec` or `system` in Vagrantfile as they run commands on the user's machine. Since some plugins can interfere with others, I recommend adding the steps to your README for installing the plugins first.

**Comment by hallatech** [comment]
Thanks for the confirmation!
