### ISSUE TITLE
Missing interpolation argument when raising Vagrant::Errors::VirtualBoxVersionEmpty

### ISSUE THREAD

**Issue by call-a3** [mitchellh/vagrant#5308]
Two problems seem to be going on here. The one that this issue is about is the first one: the missing interpolation argument that is reported.

I'm using vagrant 1.7.2 on windows 8.1 (x64) and Virtualbox 4.3.20r96997.

```
c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/config.rb:83:in `block in missing_interpolation_argument_handler': missing interpolation argument :vboxmanage in "Vagrant detected that VirtualBox appears installed on your system,\nbut calls to detect the version are returning empty. This is often\nindicative of installation issues with VirtualBox. Please verify\nthat VirtualBox is properly installed. As a final verification,\nplease run the following command manually and verify a version is\noutputted:\n\n%{vboxmanage} --version" {:_key=>:virtualbox_version_empty, :_namespace=>"vagrant.errors"} given) (I18
n::MissingInterpolationArgument)
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:29:in `call'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:29:in `block in interpolate_hash'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:21:in `gsub'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:21:in `interpolate_hash'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:17:in `interpolate'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/backend/base.rb:153:in `interpolate'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/backend/base.rb:41:in `translate'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:157:in `block in translate'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:153:in `catch'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:153:in `translate'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/errors.rb:103:in `translate_error'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/errors.rb:72:in `initialize'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/driver/meta.rb:155:in `exception'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/driver/meta.rb:155:in `raise'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/driver/meta.rb:155:in `block in read_version'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/retryable.rb:17:in `retryable'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/driver/meta.rb:140:in `read_version'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/driver/meta.rb:38:in `initialize'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/provider.rb:11:in `new'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/virtualbox/provider.rb:11:in `usable?'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:378:in `block in default_provider'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:377:in `each'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:377:in `default_provider'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:165:in `block in with_target_vms'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `call'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `each'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:74:in `block in execute'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in `tap'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in `block in batch'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in `synchronize'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in `batch'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:58:in `execute'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from c:/Program_Files/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from c:/Program_Files/HashiCorp/Vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
```

**Comment by petardudas** [comment]
I've had the same problem and I'm using : 
Windows 8.1 64bit, Virtualbox 4.3.20r96997, Vagrant 1.7.2
and I'm also ahve installed and use VMWare Player 7.0.0 build-2305329

If you suspend or halt your virtual machine sometimes vagrant doesn't kill the process. Look in your task manager and kill all Virtualbox instances and try again. That's how I solve most of the problems with Vagrant.

There is also an another issue, but I think it's from Windows updates. Sometimes I can't start the virtual machines with Virtualbox, with VMWare Player I can start them but can't access the machines  through ssh or ping to and from the machine. The solution was for me to uninstall Virtualbox and VMWare Player and install them again and everything worked just fine with both virtualisations.

Hope this helps.

**Comment by call-a3** [comment]
Virtualbox is not running at the time of the error, so there are no instances to kill. (Yes, I just checked in task manager.)

I have tried reinstalling both virtualbox and/or vagrant multiple times by now, and nothing helps. I reboot between every uninstall/reinstall to avoid any weird quirks.

**Comment by petardudas** [comment]
When did the VM with Vagrant stopped working? Can you start the VM with the Virtualbox GUI ?

**Comment by call-a3** [comment]
@petardudas The VM never worked, or rather: Vagrant never succeeded in detecting it's version. As a consequence, there is no VM to start... I can however confirm that Virtualbox works as it should, because it works fine for other tools I'm using. (SailfishOS SDK uses two virtualboxes, one for compiling and one as an emulator).

**Comment by call-a3** [comment]
Actually, @petardudas, this issue was intended to be about the interpolation error in the i18n gem, not about the fact that vagrant can't detect virtualbox properly. That's what [this other issue](https://github.com/mitchellh/vagrant/issues/5309) is about. Maybe we should continue this conversation there?

**Comment by mitchellh** [comment]
Fixed. Thanks.

**Comment by mani0070** [comment]
This same issue is happening on hyper-V as well. Any help is much appericated?
Below is the error message

==> default: Verifying Hyper-V is enabled...
C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/config.rb:83:in `block in missing_interpolation_argume
nt_handler': missing interpolation argument :name in "The box you're using with the Hyper-V provider ('%{name}')\ni
s invalid. A Hyper-V box should contain both a\n\"Virtual Machines\" and a \"Virtual Hard Disks\" folder that are\n
created as part of exporting a Hyper-V machine.\n\nWithin these directories, Vagrant expects to find the\nvirtual m
achine configuration as well as the root hard disk.\n\nThe box you're attempting to use is missing one or both of\n
these directories or does not contain the files expected. Verify\nthat you added the correct box. If this problem p
ersists,\nplease contact the creator of the box for assistance." ({:_key=>:box_invalid, :_namespace=>"vagrant_hyper
v.errors"} given) (I18n::MissingInterpolationArgument)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:29:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:29:in `block in inter
polate_hash'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:21:in `gsub'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:21:in `interpolate_ha
sh'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/interpolate/ruby.rb:17:in `interpolate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/backend/base.rb:153:in `interpolate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n/backend/base.rb:41:in `translate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:157:in `block in translate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:153:in `catch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.6.11/lib/i18n.rb:153:in `translate'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/errors.rb:103:in `translate_error'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/errors.rb:72:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/hyperv/action/import.rb:41:in
`exception'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/hyperv/action/import.rb:41:in
`raise'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/hyperv/action/import.rb:41:in
`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in fin
alize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run
'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25
:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `
call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/providers/hyperv/action/check_enabled.rb
:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run
'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 leve
ls) in run'

**Comment by call-a3** [comment]
@mani0070 This was already fixed but hasn't made it into a published version. Have you tried running vagrant from the current master branch?

**Comment by mani0070** [comment]
Not yet.. Any dates when its available for public?

--- Original Message ---

**Comment by call-a3** [comment]
I have no idea... I'm not a maintainer of this project, so I don't really
have anything to say in the matter :p

Op maandag 16 maart 2015 heeft Manimaran Chandrasekaran <
notifications@github.com> het volgende geschreven:

> Not yet.. Any dates when its available for public?
>
> --- Original Message ---
>
> From: "Adriaan Callaerts" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> Sent: 16 March 2015 08:44
> To: "mitchellh/vagrant" <vagrant@noreply.github.com
> <javascript:_e(%7B%7D,'cvml','vagrant@noreply.github.com');>>
> Cc: "Manimaran Chandrasekaran" <mani@dinventive.com
> <javascript:_e(%7B%7D,'cvml','mani@dinventive.com');>>
> Subject: Re: [vagrant] Missing interpolation argument when raising
> Vagrant::Errors::VirtualBoxVersionEmpty (#5308)
>
> @mani0070 This was already fixed but hasn't made it into a published
> version. Have you tried running vagrant from the current master branch?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mitchellh/vagrant/issues/5308#issuecomment-81507035
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/5308#issuecomment-81508302>.
>


-- 
Met vriendelijke groet,
Adriaan Callaerts

**Comment by blindpet** [comment]
Getting the same error as @mani0070 for Hyper-V on Windows 2012R2. I even went as far as installing from latest Vagrant master branch and same error (version 1.7.4).

The box i am trying is below but I have tried several and they yield the same error
vagrant init yjwong/vivid

**Comment by borrelan** [comment]
Same issue here using Windows 10 (Version	10.0.10586 Build 10586) and the latest master branch (original version 1.7.2).  Generating my own box file with this version of windows produces this error, but a previously generated box file works fine.
```
 vagrant up --provider hyperv
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Box 'blah' could not be found. Attempting to find and install...
    default: Box Provider: hyperv
    default: Box Version: >= 0
==> default: Adding box 'blah' (v0) for provider: hyperv
    default: Unpacking necessary files from: file:///D/hyperv/blah.box
    default:
==> default: Successfully added box 'blah' (v0) for 'hyperv'!
==> default: Configured Dynamical memory allocation, maxmemory is 4096
==> default: Configured startup memory is 512
==> default: Configured cpus number is 4
==> default: Configured vmname is blah
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/config.rb:92:in `block in missing_interpolation_argument_handler': missing interpolation argument :name in "The box you're using with the Hyper-V provider ('%{name}')\nis invalid. A Hyper-V box should contain both a\n\"Virtual Machines\" and a \"Virtual Hard Disks\" folder that are\ncreated as part of exporting a Hyper-V machine.\n\nWithin these directories, Vagrant expects to find the\nvirtual machine configuration as well as the root hard disk.\n\nThe box you're attempting to use is missing one or both of\nthese directories or does not contain the files expected. Verify\nthat you added the correct box. If this problem persists,\nplease contact the creator of the box for assistance." ({:_key=>:box_invalid, :_namespace=>"vagrant_hyperv.errors"} given) (I18n::MissingInterpolationArgument)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/interpolate/ruby.rb:29:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/interpolate/ruby.rb:29:in `block in interpolate_hash'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/interpolate/ruby.rb:21:in `gsub'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/interpolate/ruby.rb:21:in `interpolate_hash'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/interpolate/ruby.rb:17:in `interpolate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:152:in `interpolate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n/backend/base.rb:41:in `translate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:158:in `block in translate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:154:in `catch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:154:in `translate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/errors.rb:103:in `translate_error'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/errors.rb:72:in `initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/plugins/providers/hyperv/action/import.rb:50:in `exception'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/plugins/providers/hyperv/action/import.rb:50:in `raise'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/plugins/providers/hyperv/action/import.rb:50:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/plugins/providers/hyperv/action/check_enabled.rb:18:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
