### ISSUE TITLE
vagrant up error CoreOS

### ISSUE THREAD

**Issue by ninemind** [mitchellh/vagrant#5311]
When running vagrant up on Windows using v1.7.2 with the following Vagrantfile:

    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    $update_channel = 'alpha'

    Vagrant.configure(2) do |config|
        # Machine details
        config.vm.box = "coreos-%s" % $update_channel
        config.vm.url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json" % $update_channel
        config.vm.box_version = ">= 308.0.1"

        # Private network
        config.ssh.forward_agent = true
        config.vm.network :private_network,
            ip: '10.9.8.7'

        # Port forwarding
        config.vm.network :forwarded_port,
            guest: 80,
            host: 80
        config.vm.network :forwarded_port,
            guest: 3306,
            host: 3306

        # Shared folders
        config.vm.share_folder '~/', '/home/core/share',
            id: 'core',
            nfs: true,
            mount_options: ['nolock,vers=3,udp']

        # Fix plugin conflict
        if Vagrant.has_plugin?("vagrant-vbguest") then
            config.vbguest.auto_update = false
        end

        config.vm.provider :virtualbox do |v, override|
            v.cpus = 1
            v.memory = 512
            v.customize ['modifyvm', :id, '--cpuexecutioncap',     95]
            v.customize ['modifyvm', :id, '--natdnshostresolver1', "on"]
            v.customize ['modifyvm', :id, '--natdnsproxy1',        "on"]
        end

        config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    end

I get the following error:

	$ vagrant up
	Bringing machine 'default' up with 'virtualbox' provider...
	==> default: Box 'coreos-alpha' could not be found. Attempting to find and install...
	    default: Box Provider: virtualbox
	    default: Box Version: >= 308.0.1
	You specified a box version constraint with a direct box file
	path. Box version constraints only work with boxes from Vagrant
	Cloud or a custom box host. Please remove the version constraint
	and try again.

I noticed that there have been tickets for this in the past for older versions of Vagrant and it was fixed.

**Comment by mitchellh** [comment]
Is the JSON being sent via the `application/json` content-type? I've updated the error message to note that the metadata is not being treated as metadata.
