### ISSUE TITLE
saltstack bootstrap script is always downloaded and run on provision, regardless it is installed already or not

### ISSUE THREAD

**Issue by hongqn** [mitchellh/vagrant#5313]
I found every time I run `vagrant provision` there is a pause of output after these:

```
% vagrant provision
==> default: Running provisioner: salt...
Copying salt minion config to vm.
Checking if salt-minion is installed
salt-minion found
Checking if salt-call is installed
salt-call found
Salt binaries found. Configuring only.
```

I `vagrant ssh` to the guest machine and found it is downloading the bootstrap script:

```
[root@localhost vagrant]# ps aux | grep salt
root      5033  0.0  0.0 113116  1400 ?        S    22:52   0:00 /bin/sh - /tmp/bootstrap_salt.sh -F -c /tmp -C
root      5034  0.0  0.3 271792  6840 ?        S    22:52   0:00 /usr/bin/curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh
root      5059  0.0  0.0 107892   660 ?        S    22:52   0:00 tee /tmp/bootstrap-salt.log
root      5175  0.0  0.0 112640   956 pts/0    R+   22:54   0:00 grep --color=auto salt
```

It should not because salt is already installed (and the binary is found, according to the provision output).

The source code https://github.com/mitchellh/vagrant/blob/efd1d5e11bfc5a72c7a1d1eae294b4751d841544/plugins/provisioners/salt/provisioner.rb#L225 logs differently on whether installed or not, but behaves the same later.  Looks like a bug?

**Comment by c4milo** [comment]
I'm experiencing this issue as well.

**Comment by garrickp** [comment]
+1

Workaround for me was to copy out the config file in a separate provisioning step.

    build.vm.provision "shell", inline: "mkdir -p /etc/salt && rsync /vagrant/salt/minion /etc/salt/minion"

**Comment by obestwalter** [comment]
@hongqn is this still an issue in 1.7.4?

**Comment by displague** [comment]
This was an issue today while github.com and raw.githubusercontent.com were down.  Having a way to install salt client through the OS or defer to a vagrant included version would be beneficial.

**Comment by displague** [comment]
It looks like support for a local copy is already present:
https://github.com/mitchellh/vagrant/blob/c43e0af4d7f00028105b6f14a72d36f0bb6649a7/plugins/provisioners/salt/provisioner.rb#L212

```ruby
  config.vm.provision :salt do |salt|
    salt.bootstrap_script = 'salt/salt-bootstrap.sh'
  end
```

**Comment by sethvargo** [comment]
Hi all,

This appears to have been fixed and will be present in the next release. Thanks! 😄
