### ISSUE TITLE
Make inherited provisioning optional

### ISSUE THREAD

**Issue by varac** [mitchellh/vagrant#5314]
I have puppet provisioning configured in my global Vagrantfile. I use it to initially install packages on vms.
When i use another puppet provisioning in a project Vagrantfile, everytime i use "vagrant provision", the inherited puppet provisioning is run first, and i'd like to make this optional.

i.e.
``` 
vagrant provision --no-inherit
```
or sth like this.

**Comment by mstade** [comment]
Even better I think would be to have named provisioners, so you could do something like:

```bash
vagrant provision --provisioner x,y,z
```

Never quite understood why `--provision-with` was by type and not name.

**Comment by varac** [comment]
@mbrodala But this only works well if you want to in/exclude *every* provision script from a certain provisioner. in my case, i have two puppet provision scripts and i'd like to exclude one of them.

**Comment by mstade** [comment]
@mbrodala what @varac said. You can only say `--provision-with shell` not `--provision-with my-named-shell-script`. Hence what I meant by provisioning by type and not name, i.e. provisioner type.

**Comment by mbrodala** [comment]
@varac Yes, in that case exclusion needs to happen manually.
@mstade Since Vagrant 1.7 you can also say `--provision-with <myname>` where `<myname>` is arbitrary. See [the docs](https://docs.vagrantup.com/v2/provisioning/basic_usage.html):

> Provisioners can also be named (since 1.7.0). These names are used cosmetically for output as well as overriding provisioner settings ...
> ...
> Naming provisioners is simple. The first argument to `config.vm.provision` becomes the name, and then a `type` option is used to specify the provisioner type, such as `type: "shell"` above.

**Comment by mstade** [comment]
Wat?! No way! :o)

I stand corrected @mbrodala, and thank you immensely for it!

**Comment by mitchellh** [comment]
There is no way to disable this, since it would require special casing the Vagrantfile loading strategy quite heavily. For now, use @mbrodala's feedback. Thanks!
