### ISSUE TITLE
config.vm.synced_folder ignores "create: false" option

### ISSUE THREAD

**Issue by stongo** [mitchellh/vagrant#5317]
Vagrant Version: 1.7.2
Host: Mac OS 10.9.5
Guest: Ubuntu 14.04

Here is a sample configuration from my Vagrantfile:
```
  config.vm.synced_folder "logs/foo", "/var/log/foo", id: "foo-logs",
    owner: "foo",
    group: "foo",
    create: false
```

When I run Vagrant up, I receive this error:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mkdir -p /var/log/foo
Stdout from the command:
Stderr from the command:
sudo: no tty present and no askpass program specified
```
Seems like a bug that `mkdir -p /var/log/foo` is called when `create: false` is set. Ideally I don't want vagrant to try touching my synced folders at all. It should just try to rsync without doing anything else.

Is this expected behavior? And if it is, would you be open to a PR that would allow an option to make the synced folder "hands off"?

**Comment by mitchellh** [comment]
If you specify a blank guest path, then Vagrant won't mount it. That is the way to do it. The `create` flag only affects the host folder. I've updated the docs to make this clear.
