### ISSUE TITLE
Please provide "stable" documentation

### ISSUE THREAD

**Issue by krlmlr** [mitchellh/vagrant#5324]
I lost a bit of time today trying to teach the Hyper-V provider to set the machine name via   

```
  config.vm.provider "hyperv" do |v|
    v.vmname = "abc"
  end
```

only to learn that this option is not yet present in my (at this point most recent) v1.7.2 install. It would be helpful to have the documentation on https://docs.vagrantup.com/v2/ in sync with the latest release -- even better would be to provide versioned documentation just like e.g. [Python](https://docs.python.org/3/) does. (Of course you can also note the minimum required version for each feature...)

Thanks for considering.

**Comment by sethvargo** [comment]
Hi @krlmlr 

The docs should always correspond to the latest-released version of Vagrant. It appears that we might have accidentally deployed new Vagrant docs with unreleased features, and I apologize for that. We will try to ensure this does not happen again.

We are currently exploring a few different options for versioned documentation, but there is nothing solid in the works for implementation at this time.

**Comment by krlmlr** [comment]
Thanks. Perhaps you could display the version the documentation refers to, and upgrade this in the GitHub repo whenever a new stable version is released -- say, somewhere in [layout.erb](https://github.com/mitchellh/vagrant/blob/master/website/docs/source/layouts/layout.erb) or at least in the "Overview" page? This low-tech solution requires only minimal maintenance effort for each new release, and would work "right now".

**Comment by sethvargo** [comment]
@krlmlr the docs will always refer to the latest released version. However, as I said, it looks like we accidentally published new docs before a release. Adding the current version to the documentation would not solve this issue because there exists no version that contains that feature besides "master". Does that makes sense?

**Comment by krlmlr** [comment]
If the docs had shown their version today, I *could* have noticed a discrepancy between the version I'm using (1.7.2) and the version of the docs (post-1.7.2). I understand that this is normally not necessary, but it helps prevent confusion in case of error.

**Comment by sethvargo** [comment]
@krlmlr the docs would have said "1.7.2" though, since that's the latest version. The docs are part of this codebase.

**Comment by krlmlr** [comment]
Depends on how you organize it. The [`version.txt` file](https://github.com/mitchellh/vagrant/commits/master/version.txt) in this repo seems to be bumped using a `.dev` suffix just after release, but it says "1.7.2" now for a reason that's beyond my comprehension. (Wouldn't you rather use a branch for hotfixing a released version?)
