### ISSUE TITLE
vagrant destroy won't delete working directory due to log file

### ISSUE THREAD

**Issue by kuya1284** [mitchellh/vagrant#5330]
In Windows, when I run **vagrant destroy**, the working directory doesn't get deleted. I believe this is because of the Logs directory, which contains a log file called **VBoxStartup.log**.  I tried to find a way to disable logging, to no avail.  I'm not sure if this is specific to Windows, but either way, this is preventing me from quickly destroying and firing up a new machine.  I have to go the Default Machine Folder and manually delete the directory before I'm able to run **vagrant up** again.

**Comment by mitchellh** [comment]
What do you mean the working directory? And how is this preventing a new machine?

**Comment by kuya1284** [comment]
Hey Mitchell, thanks for getting back to me. By working directory, I'm referring to the virtual machine directory that gets created after running **vagrant up**. For example, after running that command, a directory called **toople.mysql** will get created in the VirtualBox's **Default Machine Folder** path (in my Vagrantfile, I defined my own provider name, which in this case is "toople.mysql").  Within that directory, a **Logs** file gets created, which I'm sure is automatically created by VirtualBox.

When I run **vagrant destroy**, all the files within the working directory get deleted, except for the **Logs** directory and the **VBoxStartup.log** within.  All other files inside **Logs** do get deleted.  Because of this, the next time I run **vagrant up**, Vagrant complains that another VM with the same name already exists. Here's the exact error:

> The name of your virtual machine couldn't be set because VirtualBox
> is reporting another VM with that name already exists. Most of the
> time, this is because of an error with VirtualBox not cleaning up
> properly. To fix this, verify that no VMs with that name do exist
> (by opening the VirtualBox GUI). If they don't, then look at the
> folder in the error message from VirtualBox below and remove it
> if there isn't any information you need in there.
> 
> VirtualBox error:
> 
> VBoxManage.exe: error: Could not rename the directory 'F:\Virtual Machines\VirtualBox\vagrant-ubuntu-12.04-x64-mysql_1424896576143_77491' to 'F:\Virtual Machines\VirtualBox\toople.mysql' to > save the settings file (VERR_ALREADY_EXISTS)
> VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine,  interface IMachine, callee IUnknown
> VBoxManage.exe: error: Context: "SaveSettings()" at line 2788 of file VBoxManageModifyVM.cpp

I hope this helps. I wasn't sure if this was possible, but could Vagrant recursively delete the **Logs** directory on destroy?

Thanks for taking the time to reply.

**Comment by kuya1284** [comment]
Hi Mitchell,

I was just revisiting this issue today and discovered the following ticket:

https://www.virtualbox.org/ticket/13478

Apparently, the VirtualBox team fixed this issue in 4.3.18.  I just upgraded to the latest version (4.3.28 as of this moment), and confirmed that after destroying my vagrant boxes that the working directory also gets removed since the Logs directory is also getting deleted.  Sorry, I should have suspected that this was a VirtualBox issue all along. I'm closing this ticket now.
