### ISSUE TITLE
Allow update checks of boxes on HTTPS sites with self-signed certs

### ISSUE THREAD

**Issue by ilkka** [mitchellh/vagrant#5333]
It'd be nice if `vagrant box update` et al had `--insecure` flags like `vagrant box add` has. Just tested 1.7.2 and while I can `vagrant up` from an insecure basebox HTTPS URL just fine with `config.vm.box_download_insecure = true`, updates always fail.

**Comment by ilkka** [comment]
Okay, hoo boy, this requires touching many places since Box.load_metadata would also need to pass the insecure option :| I wonder if it'd be feasible to say "make all instances of Util::Downloader be insecure henceforth".

**Comment by sethvargo** [comment]
Hi there,

At some point (I'm not sure when), we extracted all of the common box options into their own module and we include that module across all box commands. I just checked, and `box update` includes this option:

```
Usage: vagrant box update [options]

Updates the box that is in use in the current Vagrant environment,
if there any updates available. This does not destroy/recreate the
machine, so you'll have to do that to see changes.

To update a specific box (not tied to a Vagrant environment), use the
--box flag.

Options:

        --box BOX                    Update a specific box
        --provider PROVIDER          Update box with specific provider
        --insecure                   Do not validate SSL certificates
        --cacert FILE                CA certificate for SSL download
        --capath DIR                 CA certificate directory for SSL download
        --cert FILE                  A client SSL cert, if needed
    -h, --help                       Print this help
```

If this is not present in your version of Vagrant, please make sure you are on the latest version. If it's still not present, then it will be in the next release 😄
