### ISSUE TITLE
Failed: Permission denied - win 7 64bit

### ISSUE THREAD

**Issue by movie4** [mitchellh/vagrant#5335]
Hello!
Use: win 7, vagrant 1.7,2, Virtualbox 4.3.22, boot2docker 1.4.1
Run command: `vagrant up` and get error, please help solve.

    `mount -t cifs -o uid='id -u docker',gid='getent group docker | cut -d: -`
    `f3',sec=ntlm,username=UserName,pass=PAS`
    `SWORDHIDDEN //192.168.1.23/23475fb3989b4b5150a65c35404643cf`
    `/var/lib/docker/docker_1423819399_58736`
    `mount -t cifs -o uid='id -u docker',gid='id -g`
    `docker',sec=ntlm,username=UserName,pass=PASSWORDHIDDEN //192.168`
    `.1.23/23475fb3989b4b5150a65c35404643cf /var/lib/docker/docker_1423819399_58736`
    
    `The error output from the last command was:
    mount: mounting //192.168.1.23/23475fb3989b4b5150a65c35404643cf on /var/lib/docker/docker_1423819399_58736 failed: Permission denied`

vagrant file

  
    Vagrant.configure(2) do |config|
     config.vm.provision "docker"
     config.vm.synced_folder ".", "/vagrant/"
     config.vm.define "redis" do |redis|
     
     config.vm.define "redis" do |redis|
        redis.vm.provider "docker" do |docker|
           docker.vagrant_machine = "dockerhost"
           docker.image = "dockerfile/redis"
           docker.name = "db_redis"
           docker.ports = ["6379:6379"]
        end
      end
    end
      
Thanks!

**Comment by mitchellh** [comment]
Please ask these usage questions on the mailing list.
