### ISSUE TITLE
Moving to manifest.json to NAS results in "Unrecognized archive format"

### ISSUE THREAD

**Issue by thomasbeauvais** [mitchellh/vagrant#5336]
Alright, this is frustrating.  I spent hours getting a "packaged" box and versioning running locally using file URL (file://...) and it was beautiful.  Releasing a new box was as simple as updating the JSON file located next to boxes (lebowski.json).  I moved it to our local NAS (we wish to not use VagrantCloud) and now it doesn't working.  It seems to not be using the manifest.json!  Why does the location of the file change the behavior?

````
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'itonics/lebowski' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'itonics/lebowski' (v0) for provider: virtualbox
    default: Downloading: http://guest@10.10.1.6/Lebowski/VagrantBoxes/itonics/lebowski/lebowski.json
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format
````

Vagrantfile
````
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'itonics/lebowski'
  config.vm.box_url = 'http://guest@10.10.1.6/Lebowski/VagrantBoxes/itonics/lebowski/lebowski.json'

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 5601, host: 5601
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 9300, host: 9300

end
````

**Comment by thomasbeauvais** [comment]
Also, I have tried making a mini application the Content-Type as application/json and that didn't work. 

Do you have any suggestions?  We don't need a huge control application, just server a few boxes to a few developers.

**Comment by mitchellh** [comment]
Can you please attach the debug log for this?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still happening, could you please submit a _new_ issue and your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks! :smile:
