### ISSUE TITLE
Vagrant extremely slow on vagrant up ubuntu 14.10 host [virtualbox provider]

### ISSUE THREAD

**Issue by vpassapera** [mitchellh/vagrant#5345]
I have only run into this issue on my desktop, my Ubuntu 14.10 laptop does not see this issue with the same versions of the software and pretty much same packages installed.

Relevant host (desktop) Specs:
Motherboard Z97X-SOC Force
Core i7-4790 @ 3.6GHz (virtualization enabled in bios)
32GB DDR3 Ram
500GB SSD (O.S.) + 10TB LVM (Files)
2x 970GTX in SLI
Ubuntu 14.10
Virtualbox 4.3.18_Ubuntu r96516 (Not using latest because it becomes much worst)

When using the virtualbox provider it takes a tremendous amount of time to provision a box, the culprit is the following which takes place in every provision:

```
DEBUG subprocess: stderr: Interpreting /home/vpassapera/.vagrant.d/boxes/puppetlabs-VAGRANTSLASH-ubuntu-14.04-64-puppet/1.0.0/virtualbox/box.ovf...
DEBUG subprocess: stderr: OK.
DEBUG subprocess: stderr: 0%...
DEBUG subprocess: stderr: 10%...

 INFO interface: info: Progress: 10%
Progress: 10%DEBUG subprocess: stderr: 20%...

 INFO interface: info: Progress: 20%
Progress: 20%DEBUG subprocess: stderr: 30%...

 INFO interface: info: Progress: 30%
Progress: 30%DEBUG subprocess: stderr: 40%...

 INFO interface: info: Progress: 40%
Progress: 40%DEBUG subprocess: stderr: 50%...

 INFO interface: info: Progress: 50%
Progress: 50%DEBUG subprocess: stderr: 60%...70%...

 INFO interface: info: Progress: 70%
Progress: 70%DEBUG subprocess: stderr: 80%...90%...

 INFO interface: info: Progress: 90%
Progress: 90%DEBUG subprocess: stderr: 100%
DEBUG subprocess: stdout: Disks:  vmdisk1	21474836480	-1	http://www.vmware.com/interfaces/specifications/vmdk.html#streamOptimized	packer-ubuntu-14.04-x86_64-virtualbox-vagrant-puppet-1413490106-disk1.vmdk	-1	-1	
Virtual system 0:
 0: Suggested OS type: "Ubuntu_64"
    (change with "--vsys 0 --ostype <type>"; use "list ostypes" to list all possible values)
 1: VM name specified with --vmname: "packer-ubuntu-14.04-x86_64-virtualbox-vagrant-puppet-1413490106_1424169472637_63887"
 2: Number of CPUs: 1
    (change with "--vsys 0 --cpus <n>")
 3: Guest memory: 512 MB
    (change with "--vsys 0 --memory <MB>")
 4: Network adapter: orig NAT, config 3, extra slot=0;type=NAT
 5: IDE controller, type PIIX4
    (disable with "--vsys 0 --unit 5 --ignore")
 6: IDE controller, type PIIX4
    (disable with "--vsys 0 --unit 6 --ignore")
 7: Hard disk image: source image=packer-ubuntu-14.04-x86_64-virtualbox-vagrant-puppet-1413490106-disk1.vmdk, target path=/home/vpassapera/VirtualBox VMs/packer-ubuntu-14.04-x86_64-virtualbox-vagrant-puppet-1413490106_1424169472637_63887/packer-ubuntu-14.04-x86_64-virtualbox-vagrant-puppet-1413490106-disk1.vmdk, controller=5;channel=0
Successfully imported the appliance.
```

I see all of my processors rocket to 100% and my system freezes randomly. I don't see how this is possible considering that my laptop has much more limited specs, yet the configuration files are the same.

Output from kvm-ok
```
$ sudo kvm-ok 
INFO: /dev/kvm exists
KVM acceleration can be used
```

Vagrant File
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"
    config.vm.box_download_insecure = true
    config.vm.hostname = "excaliburapp.dev"
    config.vm.network :private_network, ip: "10.10.10.200"
    config.vm.synced_folder ".", "/vagrant", :nfs => { :mount_options => ["dmode=777","fmode=777"], :nfs_version => "3" }, id: "excaliburapp-root"

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.name = "excaliburapp.dev"
    end

    config.vm.provision "shell" do |shell|
        shell.path = "provision/shell/init.sh"
    end
end
```

Any ideas?

Thank you.

**Comment by sethvargo** [comment]
Hi @vpassapera 

I am sorry you are having problems with Vagrant. Just reading the issue, this looks to be a VirtualBox issue on the latest Ubuntu. Are you able to reproduce this issue using VirtualBox itself (and `vboxmanage`) without Vagrant?

It would also be very helpful if you could run the Vagrant command in debug mode and put the output in a GitHub Gist or Pastebin and link to it on this issue please.

**Comment by vpassapera** [comment]
Hi @sethvargo , I actually figured out exactly what is triggering the behavior which I wrongly diagnosed.

The actual problem is extremely high iowait (over 300%) when your Vagrantfile is in one partition and your Virtualbox VMs folder is in another partition.

When you do vagrant up from partition x, the process of creating the vmdk from the ovf kicks up the iowait for some reason. This is extremely weird behavior since the partition that I was saving the VMs is an SSD and where the vagrant project lives is in LVM HDDs (You'd think the opposite would be true).

When I put the virtualbox vms on the same partition, the importing and provisioning went wonderfully.

I still think this is worthy of investigating further since it definetely seems like strange behavior, but for anyone wondering, I hope this post saves them some time.

**Comment by vpassapera** [comment]
Is this the expected behavior? Why is the issue closed?

**Comment by mitchellh** [comment]
I apologize for closing without context. 

To do an import, Vagrant is merely shelling out to VBoxManage _without_ configuring any paths. That is, it is using the paths as configured by VirtualBox. If your box is on one partition and your data directory (for VB) is on another, then Vagrant doesn't know, doesn't care, and doesn't do anything about it either way. 

So, this issue sounds more like a VirtualBox issue itself or a VirtualBox configuration issue. But either way, Vagrant doesn't want to be involved in VB paths.

**Comment by vpassapera** [comment]
Hello,

I'm not sure what you mean by data directory. All the folders that VMware was configured to use were all on one partition, and the vagrant project was the only thing on the other partition.

If I fired up a box from Virtualbox without going through vagrant, everything ran fine....I'm still not sure how this is not an issue on the vagrant side.

Either way, interesting behavior.
