### ISSUE TITLE
CentOS machines hang on configuring network interfaces

### ISSUE THREAD

**Issue by zer0def** [mitchellh/vagrant#5348]
After taking a peek at lines 43-44: https://github.com/mitchellh/vagrant/blame/master/plugins/guests/redhat/cap/configure_networks.rb , I've found out the 'cause of my agonies.

You shouldn't be taking down **_any_** interfaces, until you're finished setting up config files for them, especially when you can't have any certainty that the interface you're putting to sleep isn't the one you're using for configuring an instance at the moment.

On top of that, ``touch`` and ``sed`` on lines 48-49 rely on the file not existing in the first place, which is simply a bad assumption, because it's being (unintentionally?) reused, eventually leading to assigning multiple values to keys.

**Comment by sethvargo** [comment]
Hi @zer0def 

Can you please give us a Vagrantfile to reproduce this issue? Thanks!

**Comment by seocam** [comment]
Isn't it a dup of #2881?

**Comment by sethvargo** [comment]
Hi @zer0def 

Could you please share your Vagrantfile so we can reproduce this issue? Thanks! :smile:

**Comment by mitchellh** [comment]
Dup of #2881, regardless of response here.

**Comment by altexdim** [comment]
possible solution https://github.com/mitchellh/vagrant/pull/7104
