### ISSUE TITLE
vagrant up

### ISSUE THREAD

**Issue by Severenit** [mitchellh/vagrant#5350]
Why i can't run vagrant?

```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
An action 'up' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
```

I don't understand what processes are running at me, and how to stop them?
I have vagrant 1.7.2 and VirtualBox 4.3.22
And Mac OS Yosemite

**Comment by sethvargo** [comment]
Hi @Severenit,

I am sorry you are having problems with Vagrant. You can inspect processes by running `ps` on the command line or opening the Activity Monitor in `Applications/Utilities`. Look for anything named `vagrant` or `ruby` and send it the kill signal.

**Comment by Severenit** [comment]
You are great! Works!

But after I run Vagrant he writes:

➜  tronic-fm git:(dev) vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: VirtualBox VM is already running.

And unfortunately does not work localhost
it's problem in configuration?

**Comment by sethvargo** [comment]
Hey @Severenit,

We like to reserve the GitHub issue tracker for bug reports or feature requests in Vagrant. For general usage questions, could you please post on the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up)? Thank you! :smile:

**Comment by bsesic** [comment]
I have the same problem as above. However I have no process like ruby or vagrant running and therefore I am not able to shut it down and fix the problem.

**Comment by kenorb** [comment]
Try either:

    killall ruby

or:

    vagrant global-status --prune

to fix the above issue.
