### ISSUE TITLE
Leverage docker build cache - at least for vagrant reload

### ISSUE THREAD

**Issue by pjoe** [mitchellh/vagrant#5353]
Docker has a pretty good way of caching build layers, but I haven't been able to find a way to make it work with vagrant's docker provider.

My use case is something like:

1. Have vagrant file using docker provider which builds container from a dockerfile
2. Edit docker file
3. Rebuilt container to check, e.g. using vagrant reload
4. Notice this always rebuilds container from scratch instead of utilizing docker's build cache 

This totally ignores the docker build cache (I think vagrant reload destroys the docker image and thus the cache), making this workflow very slow compared to just rebuilding with docker itself.

**Comment by rejinka** [comment]
+1

**Comment by sethvargo** [comment]
Hi @pjoe 

Thank you for opening an issue. This definitely sounds like a good idea. We would also welcome a community contribution if we don't get to it first :smile:

**Comment by adrianguenter** [comment]
Would it be sufficient to only nuke the image on `destroy` command, and for `up`/`reload` just let Docker's existing mechanism to invoke a manual cache bust do its thing if the [`--no-cache`](https://docs.docker.com/reference/builder/#run) flag is in the Docker provider's `build_args` array.

**Comment by pjoe** [comment]
@adrianguenter: I think that would at least solve my use case :)
