### ISSUE TITLE
Feature: On demand/explicit provisioning

### ISSUE THREAD

**Issue by mbrodala** [mitchellh/vagrant#5355]
In addition to executing provisioners `once` or `always` a third option `ondemand`/`explicit` would be useful with the following effects:
1. On machine creation `ondemand` provisioners are executed regularly. (`vagrant up`)
2. On general provision `ondemand` provisioners are **not** executed. (`vagrant up/reload --provision`, `vagrant provision`)
3. Explicitely referring to an `ondemand` provisioner allows it to execute. (`vagrant provision --provision-with my-ondemand-provisioner`)

This would allow for e.g. having a database cloned from a production system upon creating a machine but leave it untouched on general provision runs. Only upon explicit request would the database be updated again from the production system.

Opinions?

**Comment by AntonioMeireles** [comment]
:+1:

**Comment by fmaretic** [comment]
This would be great! +1

**Comment by defender** [comment]
+1

**Comment by greenmoss** [comment]
+1

**Comment by timothymschier** [comment]
+1

**Comment by famousgarkin** [comment]
workaround for the time being:

```ruby
if ARGV.include? '--provision-with'
  config.vm.provision 'db-reset', type: 'shell', inline: 'sudo mysql ...'
end
```

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
