### ISSUE TITLE
Configuration iface parameters still there after auto_config: false

### ISSUE THREAD

**Issue by mazzy89** [mitchellh/vagrant#5356]
When you boot up the box by using the following configuration

```
config.vm.network "private_network", ip: "192.168.33.100"
```

vagrant automatically adds to interfaces file on ubuntu some lines to configure the interface (usually eth1). if you use after a while

```
auto_config: false
```

and reboot the machine, those lines are still there without any uncomment

**Comment by sethvargo** [comment]
@mazzy89 when you say "reboot the machine", do you mean `vagrant reload` or manually rebooting the machine via the console? You will need to run `vagrant reload` to have the networking interfaces reconfigured.

**Comment by mazzy89** [comment]
I mean through the vagrant reload —provision command

**Comment by mitchellh** [comment]
Vagrant won't remove files it already put there, you need to have `auto_config: false` initially. I'm updating the docs for this now.
