### ISSUE TITLE
VBoxManage error in port forward code when running separate vagrant processes in parallel

### ISSUE THREAD

**Issue by davebirch** [mitchellh/vagrant#5358]
I've noticed a case related to the VirtualBox port collision handling where a race condition can occur which has been giving me some issues. I'm intermittently seeing the following error either on vagrant up, or after a vagrant snapshot go command, when it calls vagrant up:

> ==> minion1: Checking if box 'hashicorp/precise64' is up to date...
> There was an Err0r while executing VBoxManage, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["showvminfo", "a9939272-5b15-43dc-8441-44197756f6b8", "--machinereadable"]
> 
> Stderr: VBoxManage: Error: Could not find a registered machine with UUID {a9939272-5b15-43dc-> 8441-44197756f6b8}
> VBoxManage: Error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component > VirtualBox, interface IVirtualBox, callee nsISupports
> VBoxManage: Error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2611 of file VBoxManageInfo.cpp
> 

Output from info level log trace on a normal Vagrant up at around the point things are failing:

>  INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::PrepareForwardedPortCollisionParams:0x000000041f6810>
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "list", "vms"]
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "f1579f45-749d-44e6-aca3-019cf4fbe2bb", "--machinereadable"]
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "23721ced-8196-4002-a1f9-17815d462245", "--machinereadable"]
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "5e98c166-8483-4a97-b71a-65cd3418b49a", "--machinereadable"]
>  INFO warden: Calling IN action: #<Vagrant::Action::Builtin::HandleForwardedPortCollisions:0x000000041f6a90>

Essentially, it looks like the PrepareForwardedPortCollisionParams is running VBoxManage list vms, then iterating over each of the VMs and running VBoxManage showinfo <UUID> --machinereadable against it.

What I think is happening in my test environment, (where there can be many running instances having Vagrant commands run against them in multiple processes) is that between the list of VMs being generated and the showinfo being run, a destroy running in another process completes and removes one or more of the VMs found by the list vms call which is resulting in the showvminfo failing.

**Comment by mitchellh** [comment]
VirtualBox struggles when running in parallel. It is not supported. Sorry!

**Comment by tbarbette** [comment]
Is multiple VirtualBox still not supported? I get this same error from time to time when using multiple vagrant in parallel. Seems like this huge limitation should be mentioned somewhere, no?
