### ISSUE TITLE
Vagrant scp

### ISSUE THREAD

**Issue by eidge** [mitchellh/vagrant#5361]
I just realized there is no ```vagrant scp``` command, would adding it to the vagrant-cli be a useful PR?

I currently use a custom script to do so, but should be easily included in the cli.

**Comment by mitchellh** [comment]
I think this would be a decent feature. I think two commands would be great: one to copy TO the guest, one to copy FROM the guest. Vagrant could easily support both since communicators are required to be able to do both.
