### ISSUE TITLE
vmware fusion 7.1.1 puppet dies too quickly

### ISSUE THREAD

**Issue by gwagner** [mitchellh/vagrant#5362]
After update to fusion 7.1.1, the puppet provisioner [when provisioning windows server 2012r2] is dying at random points on the initial up.  After the initial up, when you run a vagrant provision, all provisioning steps run perfectly fine.

VMWare Fusion 7.1.1 is borked, 7.1.0 works perfectly

We have not tested other versions of windows other than Server 2012 R2.

Vagrant Version 1.7.2
vagrant-cachier (1.2.0)
vagrant-guestip (0.2)
vagrant-hosts (2.3.0)
vagrant-share (1.1.3, system)
vagrant-vmware-fusion (3.2.3)

**Comment by phinze** [comment]
Hi there!

That's really odd. Do you think you could [gist](https://gist.github.com) the [debug logs](http://docs.vagrantup.com/v2/other/debugging.html) from one of the times when it dies?

**Comment by gwagner** [comment]
Sure, it dies in random spots, never consistently:

https://gist.github.com/gwagner/b4f4a60790710b5ad04f

https://gist.github.com/gwagner/bd29306a37c547cce579

**Comment by gwagner** [comment]
Sorry, debug log for vagrant coming in a sec

**Comment by gwagner** [comment]
Vagrant debug log attached

https://gist.github.com/gwagner/2430fd03277911ebd111

**Comment by phinze** [comment]
Interesting... the relevant bit seems to be

```
DEBUG winrmshell: Output: {:data=>[{:stdout=>"[ ... ]"}], :exitcode=>259}
```

Looks like exit code 259 [might not be an error](http://stackoverflow.com/questions/12175430/net-stop-spooler-fails-with-exit-code-259). Will need to do a bit more investigation on this.

Thanks for the logs!

**Comment by gwagner** [comment]
Thanks for the fast response!!

**Comment by gwagner** [comment]
@phinze any update on this one?

**Comment by phinze** [comment]
@gwagner Sorry about the delay - I guess I was hoping some Windows Expert would swoop in and save the day with an explanation and a magical fix. :sparkles: 

So now that the wishful thinking option has been exhausted,  Let me see if I can reproduce this locally on a VM. :fist: :grinning:

**Comment by phinze** [comment]
Good news! I have this reproduced with a pretty minimal config:

```
Vagrant.configure(2) do |config|
  config.vm.box = "windows81"

  config.vm.provision "shell", privileged: true, inline: '
    Write-Host "hello, going to sleep"
    Start-Sleep -Seconds 120
    Write-Host "all done!"
  '
end
```

All signs so far point to a bug in the WinRM communicator when elevated privs are used. Will let you know what I find.

**Comment by phinze** [comment]
^^ Success! Here's what I'm pretty sure is the fix.
