### ISSUE TITLE
why i cannot install vagrant as gem using source code on windows?

### ISSUE THREAD

**Issue by sunstudy** [mitchellh/vagrant#5365]
E:\del\vagrant>rake
[31mThe git source https://github.com/mitchellh/vagrant-spec.git is not yet checked out. Please run `bundle install` before trying to start your application[0m

E:\del\vagrant>bundle install
Fetching https://github.com/mitchellh/vagrant-spec.git
fatal: '/cygdrive/e/del/vagrant/C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5a3ef16' does not appear to be a git
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone --no-checkout --quiet "C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5a3ef16" "C:/Ruby193/lib/r
If this error persists you could try removing the cache directory 'C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5
fatal: '/cygdrive/e/del/vagrant/C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5a3ef16' does not appear to be a git
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Retrying git clone --no-checkout --quiet "C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5a3ef16" "C:/Ruby193/lib/r
If this error persists you could try removing the cache directory 'C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5
fatal: '/cygdrive/e/del/vagrant/C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5a3ef16' does not appear to be a git
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Git error: command `git clone --no-checkout --quiet
"C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5a3ef16"
"C:/Ruby193/lib/ruby/gems/1.9.1/bundler/gems/vagrant-spec-1df5a3af81cb"` in
directory E:/del/vagrant has failed.
If this error persists you could try removing the cache directory
'C:/Ruby193/lib/ruby/gems/1.9.1/cache/bundler/git/vagrant-spec-7f2ea299b3766e9a077e5bd825aa24cac5a3ef16'

**Comment by mitchellh** [comment]
This seems like an environment issue. We can and do install from source for development on Windows, and it does work!

**Comment by sunstudy** [comment]
my git command works well, then why i failed to run rake? is there some hard link in bundle configuration?
