### ISSUE TITLE
Docker provider, Synced folders, Multi machine, yaml source issue

### ISSUE THREAD

**Issue by bezerker** [mitchellh/vagrant#5367]
I'm currently using Vagrant with Docker for creating a local development environment.  My goal is to obfuscate as much of the Vagrantfile stuff from the developers and place it into simple yaml files in a conf.d style format for their ease of use.  Currently our stack uses a few containers with some links to each other and I've managed to make this function without issue. (Vagrant had ordering issues with multi machine and links, but it's fixable within the Vagrantfile).

Here is a gist with the Vagrantfile and an example yaml: https://gist.github.com/bezerker/ad3d8bc1636e20648c52

The Issue I am having is that when I run vagrant up (machinename) it functions fine.  IE: if I run vagrant up wordpress it spins wordpress up with the proper volume mounted and shared.

If I run vagrant up --no-parallel to bring up the whole stack I run into a really strange issue.  The first container brought up will have none of the shared folders it's expected to have.  The second one will have the shared folder from the first one but not its own, and the third one will have the shared folder from the first and second machine (but not its own).  I am safely assuming here if I add more containers, this chain will continue.

I've done what I can within the vagrantfile to print some of the expected variables (in this case a hash) for each machine and each is listed correctly for its unique machine.  The only volume information printed is the one unique for that container.

This leads me to believe that something wonky is happening inside Vagrant that I cannot see as all logic placed into my Vagrantfile indicates the correct output in the expected places.  If I just define each manually without dynamically loading from yaml files, there's no issues.

This feels to me like a bug but it's possible my ruby is terrible too.

**Comment by mitchellh** [comment]
You're setting `config.vm.synced_folder` instead of `d.vm.synced_folder`

**Comment by bezerker** [comment]
Well well. That may certainly do it.  Awesome catch Mitchell. Thanks.
