### ISSUE TITLE
default provider logic changed between 1.6.5 and 1.7.0

### ISSUE THREAD

**Issue by neonstalwart** [mitchellh/vagrant#5370]
in my [Vagrantfile](https://gist.github.com/neonstalwart/4b8a47298dbfbc13ce1f#file-vagrantfile) i have some VMs using the digitalocean provider and others with no provider explicitly set.  in 1.6.5 the ones without a provider set used virtualbox but when i update to 1.7.0 or later, those VMs suddenly use digitalocean as the provider.

i've included [output of `vagrant status`](https://gist.github.com/neonstalwart/4b8a47298dbfbc13ce1f#file-shell-sh) from 1.6.5 and 1.7.2 as well as [output from 1.7.2 running `vagrant up --debug mongo elasticsearch`](https://gist.github.com/neonstalwart/4b8a47298dbfbc13ce1f#file-zzzz-sh) (both VMs have no provider defined).

i tried to determine from the changelog if anything related to my config may have been affected but i don't immediately see something obvious to me.  do i need to change my config somehow or is this an error that has been introduced?

**Comment by fgrehm** [comment]
Yup, the logic has changed, more information can be found at the "DEFAULT PROVIDER" section of https://docs.vagrantup.com/v2/providers/basic_usage.html

HTH

**Comment by neonstalwart** [comment]
thank you - i swear i looked for that earlier and did not come across it... but there it is.
