### ISSUE TITLE
VMware not respecting gui = false unless it is the last box in multi-machine setup

### ISSUE THREAD

**Issue by blomma** [mitchellh/vagrant#5373]
Vagrant 1.7.2
VMware Fusion plugin 3.2.3

If you have a multi-machine setup and one of the machines has .gui = false set, the only way for vmware to respect that is to make sure that that box is the last to be brought up.
If there is a box with .gui = true after you have brought up a box with .gui = false then upon bringing that box up it will not only open a window for that box but also for the box with .gui = false.

**Comment by mitchellh** [comment]
This is how VMware itself works. We ask it to not use a GUI, but it does if the GUI itself is already open. This is a VMware bug. Sorry!
