### ISSUE TITLE
vagrant ssh and ssh.private_key_path not working

### ISSUE THREAD

**Issue by updiversity** [mitchellh/vagrant#5374]
Here is my VagrantFile
    
    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    
    	host_vars.each do |name|
    
    		if name != "." and name != ".."
    
    			config.vm.define name do |machine|
    
    				data_host = YAML.load_file("#{dir}/../ansible/host_vars/#{name}")
    
    				machine.vm.hostname = File.basename("#{name}")
    				machine.vm.box = "ubuntu/trusty64"
    
    				machine.vm.provider "virtualbox" do |v|
    					v.name = name
    					v.memory = 2048
    					v.cpus = 2
    				end
 
    				machine.vm.network "private_network", ip: "#{data_host['ansible_ssh_host']}"
    
    				machine.ssh.forward_agent = true
    
    			    if VAGRANT_COMMAND != "up" 
    					machine.ssh.username = "#{data_allhost['default_ssh_user_info']['name']}"
    		            machine.ssh.host = "#{data_host['ansible_ssh_host']}"
                        machine.ssh.private_key_path = ["#{data_allhost['security_path']}/#{data_allhost['default_ssh_user_info']['private_authorized_keys']}"]
    				end
    
    			end
    
    		end
    
    	end
    
    	config.vm.provision :ansible do |ansible|
    	    	ansible.playbook = "../ansible/provision.yml"
    	    	ansible.verbose = "vvvv"
    		ansible.inventory_path = "../ansible/inventory/development"
    		ansible.raw_arguments = ["-u","#{data_allhost['default_ssh_user_info']['name']}"]
      	end
    
    end

I am able to succesfully execute "vagrant up", without any problems...

If I try to connect in that way :

    ssh <user>@<host ip> -i <path to private key>

This is successful and i am not requested to insert a password.

However, if I try via 

    vagrant ssh

It does not work. By checking the vagrant logs:

     INFO ssh: Invoking SSH: ["cox@192.168.33.10", "-p", "2222", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentitiesOnly=yes", "-i", "/home/updiversity/Virtualboxes/fisher/vagrant/.vagrant/machines/local.datadevserver.com/virtualbox/private_key", "-o", "ForwardX11=yes", "-o", "ForwardX11Trusted=yes", "-o", "ForwardAgent=yes"]

It is clear that vagrant is not passing to the SSH command the correct private key path, but rather provide the default one...

Is it a bug ?

**Comment by mitchellh** [comment]
Fixed!
