### ISSUE TITLE
Install into Program Files on Windows

### ISSUE THREAD

**Issue by colinbowern** [mitchellh/vagrant#5375]
For more than 10 years Program Files has been where program binaries goes yet the install insists on ignoring platform conventions.  Please update the default install path to Program Files (or Program Files (x86) if 32-bit) using the appropriate Windows Installer common path variables.

**Comment by mitchellh** [comment]
The reason we don't install into Program Files is because Ruby on Windows still has a bug when loading Vagrant (any gem, really) in a path on Windows with spaces. Therefore, we workaround it.

Trust me, we're not trying to be edgy or break the norms at all.
