### ISSUE TITLE
Vagrant Mounting Fails: Unable to Connect To Upstart on Box Using Systemd

### ISSUE THREAD

**Issue by Geraden07** [mitchellh/vagrant#5377]
I am working with an Ubuntu 14.10 box. Initially it will boot fine, no errors whatsoever.

If I install systemd and change grub to use systemd instead of upstart, then what happens is the box boots normally right up until it hits the first mount (/vagrant). Then it fails due to a non-0 command return and does not attempt any further mounts that may have been configured, nor any provisioning.

However the box is booted just fine and can be SSH'd into with no issues. Even the /vagrant mount shows up from within the VM just fine.

Doing a 'vagrant up --debug' command, I see the following at the end:
```
c:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in block (2 levels) in run'
 INFO interface: error: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant

Stdout from the command:



Stderr from the command:

stdin: is not a tty
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant

Stdout from the command:



Stderr from the command:

stdin: is not a tty
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The following SSH command responded with a non-zero exit status.\nVagrant assumes that t
his means the command failed!\n\n/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant\n\nStdout from the command:\n\n\n\nStderr from the command:\n\
nstdin: is not a tty\ninitctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused\n"]
```

Vagrant doesn't seem to know to use systemd and not upstart. I know obviously vagrant CAN use systemd just fine because I've got other centos boxes which use it by default and they work just fine.

**Comment by skozin** [comment]
I'm having the same issue. Vagrant [assumes](https://github.com/mitchellh/vagrant/search?q=initctl&type=Code) that an OS uses Upstart if `/sbin/initctl` is present. But this is not always the case, for example `systemd-sysv` Ubuntu package registers systemd as init daemon, but doesn't remove `/sbin/initctl` binary.

The first workaround I have tried is removing `upstart` and `upstart-bin` packages. This removes `sbin/initctl` binary, but also stops Upstart daemon, breaking `shutdown` (and probably other essential commands) until you hard-reboot the VM.

The second workaround is `chmod a-x /sbin/initctl`. It works, but obviously is the wrong way of doing things :)

I think Vagrant should ignore errors from this command. Unfortunately, it was copied to non-core plugins, e.g. [vagrant-parallels](https://github.com/Parallels/vagrant-parallels/blob/ee12f744584d9fad85d99445bafe7775c87d4a1a/lib/vagrant-parallels/guest_cap/linux/mount_parallels_shared_folder.rb#L83), so they need to be fixed too.

**Comment by aneeshusa** [comment]
Just ran into this today, hence the PR. If accepted, I'll look into sending similar PRs to non-core plugins as well.

**Comment by v6** [comment]
// , I also have this issue, and got the following spew from my terminal: dpaste.de/8fhp

Need I provision this machine to use Upstart instead of SystemD? 

P.S. Much hate, have I, for the SystemD. 
Maybe Snappy doesn't use it.

**Comment by mitchellh** [comment]
Fixed in master. :)

**Comment by v6** [comment]
// , Oh, yes, thank you, Mitchell!

**Comment by samuelgmartinez** [comment]
This fix breaks the "vagrant-mounted" emit in all releases prior to 14.10, since /proc/1/exe is /sbin/init, so the condition added in 49ff17b9b925e947cdc18c51ff2607613716238f is never met.

**Comment by aneeshusa** [comment]
@samuelgmartinez Whoops, you're right, I only tested 15.04 with upstart and systemd. I'm working on a fix now and should have a PR later today.
