### ISSUE TITLE
New Command: vagrant rebuild

### ISSUE THREAD

**Issue by gwagner** [mitchellh/vagrant#5378]
Right now i have an alias to `vagrant destroy --force && vagrant up` for machines that i want to tear all the way down and stand back up.  It would be nice if there was a vagrant rebuild command that can optionally take --force or a machine name (in a multi machine environment) that would destroy and up a machine in a single command.

**Comment by mitchellh** [comment]
I'm open to this idea, but I wonder if it makes more sense as a `vagrant reload` flag, such as `vagrant reload --destroy`?

/cc @sethvargo

**Comment by sethvargo** [comment]
I've admittedly thought about this a few times, to the point where I have a bash alias that does it. I named it `vnuke` and it runs destroy + up. 

I personally like adding a `--destroy` flag to reload, since I think it maps nicely to existing UXes.

**Comment by gwagner** [comment]
`vagrant reload --destroy` would work well, except i think --destroy is the wrong word to use.

`vagrant reload --full` may be a little less confusing?

**Comment by mitchellh** [comment]
@gwagner I think `--destroy` is the right word because we need to convey that we will _destroy_ your machine and therefore all data (on the machine) will be lost. I don't want someone accidentally doing this...

**Comment by ggiamarchi** [comment]
I arrive after the PR, sorry about that. I think using the `reload` command to destroy a machine and recreate can be very confusing, even with an explicit option like `--destroy`.

Why about introduce a new command `vagrant rebuild` ?

**Comment by gwagner** [comment]
@mitchellh based on that explanation, i agree with your point completely!

**Comment by fgrehm** [comment]
Any thoughts on having it as a separate command, allowing for additional customization (like rebooting with a different provider)?

I experimented with that on https://github.com/fgrehm/vagrant-pristine and would be more than happy to submit a PR bringing that functionality into core :smile:

**Comment by berendt** [comment]
At the moment the `reload` command is used to apply modifications in the `Vagrantfile` to an already running box. From my POV a `--destroy` option does not makes sense for the `reload` command. It is not longer a reload when we first destroy the instance. I think introducing a new command `rebuild` is the better way.

**Comment by sethvargo** [comment]
@fgrehm that looks _very_ interesting to me :smile:. I think that behavior and UX is what we are looking for here. `pristine` is also an interesting choice since it echos with `gem pristine`. I like it!

**Comment by berendt** [comment]
@fgrehm Do you want to bring up a PR to propose to add `vagrant-pristine` to core?

**Comment by fgrehm** [comment]
Yup, hopefully at some point this week!

**Comment by kcormier** [comment]
Hey Guys,

We took a quick stab at getting a rebuild command working before we noticed this pull request.  We were able to reuse most of the up/down commands.  Didn't know if any of this might prove useful to you guys.

https://github.com/simplisafe/vagrant-rebuild

**Comment by sethvargo** [comment]
Will be fixed by https://github.com/mitchellh/vagrant/pull/5613
