### ISSUE TITLE
Possible improvement in error message Vagrant 1.7.1 

### ISSUE THREAD

**Issue by jeremyquinton** [mitchellh/vagrant#5380]
when running 

    vagrant package 

The error message is 

    The specified file to save the package as already exists. Please remove this file or specify a different
    file name for outputting.

An error message that shows the actual filename would be nice. e.g
   
    The specified file package.box to save the package as already exists. Please remove this file or
    specify a different file name for outputting.

**Comment by mitchellh** [comment]
LGTM. Tagged.
