### ISSUE TITLE
Upgrade falls back to version 1.0.7 - Win 7

### ISSUE THREAD

**Issue by adopudi** [mitchellh/vagrant#5383]
I was on Vagrant version 1.6.5 till last night and it ran fine. I did not switched off my laptop, I hybernated it. This morning I received the following error message:

vagrant-share can't be installed without vagrant login (RuntimeError)

After playing around a bit I decided to upgrade to 1.7.2. After reboot I got the following message:

[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
Vagrant version 1.0.7.

After uninstalling, rebooting and reinstalling a couple of times I decided to try with version 1.7.1, but the result hasn't changed. Now I am sort of stuck.

**Comment by mitchellh** [comment]
That is... strange. The easiest way to clean this up will be to

1. Uninstall Vagrant
2. Make sure `C:\HashiCorp` is gone
3. Remove `%USERPROFILE%/.vagrant.d/gems` (will uninstall all your plugins)
4. Reinstall Vagrant

This just sounds like an oddly corrupt install.
