### ISSUE TITLE
internal network ignored

### ISSUE THREAD

**Issue by tcurdt** [mitchellh/vagrant#5389]
The following vagrant config does create a second network adapter

    Vagrant.configure("2") do |config|
        config.vm.hostname = 'vserver'

        config.vm.provider "virtualbox" do |v|
          v.name = "vserver"
          config.vm.network :private_network, type: "dhcp", name: "vboxnet0", adapter: 2
        end
    end

but it keeps using `vboxnet1` instead of `vboxnet0`.

The docs are very very vague on such details btw.

**Comment by jakerobinson** [comment]
change label to virtualbox, @sethvargo? :wink:

**Comment by mitchellh** [comment]
Fixed
