### ISSUE TITLE
Allow passing "--color" via environment

### ISSUE THREAD

**Issue by amosshapira** [mitchellh/vagrant#5390]
There is VAGRANT_NO_COLOR which is equivalent to "--no-color", but there is no similar way to pass "--color" via the environment.

It would be nice if there was a ```VAGRANT_COLOR=(true|false)``` option.

**Comment by sethvargo** [comment]
Hi @amosshapira 

Thank you for opening an issue. Can you explain this use case a bit more? Vagrant should default to colored output automatically. Are you seeing different behavior?

**Comment by amosshapira** [comment]
Vagrant defaults to --no-color when the output is not a TTY. I'd like to be able to force color even in this case via an environment variable.

**Comment by sethvargo** [comment]
Okay, sounds good! Tagged appropriately.
