### ISSUE TITLE
Sharing between Windows host and Darwin guest in VirtualBox

### ISSUE THREAD

**Issue by alh84001** [mitchellh/vagrant#5392]
I am trying to set-up an OS X VirtualBox box and enable it to run on Windows host (just ignore any legality issues concerning this) and I am stuck as to how to provide two way share between the host and the guest.

1. There are no VB Guest Additions for OS X so VB Shared Folders don't work
2. For the same reason, private network can't be configured and NFS (using vagrant-winnfsd) doesn't work
3. Darwin guest doesn't have mount_smb_share capability so SMB doesn't work

Is there any reason why Darwin host doesn't have the mount_smb_share capability? Since at least Lion, there is a mount_smbfs command so it seems simple to implement.

**Comment by alh84001** [comment]
Made a pull-request https://github.com/mitchellh/vagrant/pull/5647

**Comment by mitchellh** [comment]
Fixed
