### ISSUE TITLE
Allow private/public networking with Docker provider

### ISSUE THREAD

**Issue by m1keil** [mitchellh/vagrant#5394]
I tried adding the usual `vm.network` config lines but it looks like Docker provider ignores those.

I wonder if it's possible to configure additional NIC for Docker provider without creating your own custom box?

Basicly this will allow similar workflow to boot2docker, instead of the double NAT + proxy thing that's currently is in use.

**Comment by mitchellh** [comment]
I'd be open to this in a PR But don't see  astrong use case right now.
