### ISSUE TITLE
Vagrant up always fails for second virtualbox machine

### ISSUE THREAD

**Issue by gamename** [mitchellh/vagrant#5396]
I am creating a collection of boxes in my Vagrantfile.  
- My Vagrantfile brings up 2 instances, pgdb-1 and pgdb-2
- They use the same virtualbox image
- The first instance always comes up after "vagrant up".  
- The second instance always times out and asks for a password.  
- Even when the second instance times out, you can still ssh into the "failing" vagrant box without an problem.
- If the images are started individually, both will activate without any problem. That is, if you do "vagrant up pgdb-1", wait till it is up, then do "vagrant up pgdb-2", both will successfully activate.
- The vagrantfile, and diagnostic files are in this gist: https://gist.github.com/gamename/7cd9d684294be2411f6d

**Comment by sethvargo** [comment]
Hi @gamename 

Thank you for opening an issue. I just tried with Vagrant 1.7.3 and I am unable to reproduce this issue (vbox 5). I had to disable the vbguest options in your Vagrantfile:

```
    # do NOT want to check for the correct additions version when booting
    config.vbguest.auto_update = jvars['vb_auto_update']
 
    # do NOT download the iso file from a webserver
    config.vbguest.no_remote = jvars['vb_no_remote']
```

But once removed both machines were brought up successfully using `vagrant up`. 

Can you please try Vagrant 1.7.3 and Vbox 5 without the vbguest plugin and let me know if the issue persists?

**Comment by gamename** [comment]
Hi Seth,

Will do. 

-Tennis

**Comment by gamename** [comment]
Yep.  It looks good now. Closing issue. Thanks!
