### ISSUE TITLE
provisioning, run: "always" doesn't

### ISSUE THREAD

**Issue by cjw296** [mitchellh/vagrant#5397]
I'm using Vagrant 1.7.2.

As per the docs, I have a config that looks like this:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "puphpet/debian75-x64"
  config.vm.provision "shell", path: "provisioning/setup.sh"
  config.vm.provision "shell", path: "provisioning/packages.sh", run: "always"
end
```
I want setup.sh to run only when the VM is created, while I want packages.sh to run every time there's a "vagrant up", regardless of whether the VM is running or not and regardless of whether it has been provisioned or not.

https://docs.vagrantup.com/v2/provisioning/basic_usage.html suggests that run: "always" is the way to do this, but packages.sh is not run when I do "vagrant up" and only appears to be run on VM creation.

**Comment by sethvargo** [comment]
Hi @cjw296 

I am sorry you are having issues with Vagrant. Can you explain your workflow a bit more? If you have time, could you please run the `up` commands in debug mode and gist the output?

**Comment by cjw296** [comment]
@sethvargo : as I said, I want setup.sh to run only on VM creation (it does the heavyweight provisioning), while I want packages.sh to run on every "vagrant up" (it makes sure my python packages are up to date).

That's somewhat orthogonal, though, as run: "always" is not working as documented: https://gist.github.com/cjw296/092c59c29c8047c695c5

**Comment by sethvargo** [comment]
Hi @cjw296 

The reason I'm asking for clarity is because it's still unclear to me what workflow you desire. Are you turning off the machine before you run `vagrant up` (like with `vagrant stop`)?

**Comment by cjw296** [comment]
Nope, my expectation, per the docs, is that at any time I do a "vagrant up", even if the machine is up, then provisioners marked as run: "always" should run.

**Comment by sethvargo** [comment]
Ah I think I see the confusion. The issue is that `vagrant up` is a noop if the machine is already running. Can you try running `vagrant stop && vagrant up` and see if _just_ that shell script (`packages.sh`) runs please?

**Comment by cjw296** [comment]
There is no vagrant stop ;-)

vagrant suspend && vagrant up does *not* run packages.sh

vagrant stop && vagrant up *does* run packages.sh

**Comment by sethvargo** [comment]
Sorry, I meant `halt`. I think that is the intended behavior, but I agree the docs are unclear.

**Comment by dragon788** [comment]
@cjw296 I'm curious whether if you run 'vagrant reload' and you have your script set to run always, does it actually run? I'm fighting a bug I'm getting ready to file where certain scripts don't run on reload, EVEN if I specify --provision.

**Comment by jpSimkins** [comment]
I had an issue with this not running always as expected. I noticed that the order actually matters here. 

By adding the`run: "always"` provision before the normal provisions this works as expected.

**Comment by mitchellh** [comment]
@cjw296 This is intended behavior. We've been having a bigger discussion on if `vagrant up` should run provisioners even if the VM is running. At the moment, I'd say the docs are perhaps misworded since I'm not sold that `vagrant up` should do this.

However, with your config `vagrant provision` will always run the configured things. Please do that as we talk through the `vagrant up` behavior. Thanks!

**Comment by dwijnand** [comment]
@mitchellh Where is said bigger discussion? I'm interested.

**Comment by athingisathing** [comment]
The problem with the fix denoted above is that the always script needs to execute after the once script and if your reverse the order you get the wrong execution order for the provisioner scripts.

is there a way to fix this like an ordering param or something....??

**Comment by pives** [comment]
For a similar issue. I wrote a bash script that assembles my Vagrantfile  so that i can handle the ordering issue (and some other things)  

`export PROVISION_SCRIPT=bootstrap.sh
select yn in "newinstall" "reload" "forceprovision" "updateOS" "DESTROY" "Exit"; do
   case $yn in
      newinstall ) export PROVISION_SCRIPT=vagrant_install.sh; dovagrant 1; break;;
      reload ) dovagrant 2; break;;
      forceprovision ) dovagrant 3; break;;
      updateOS ) export PROVISION_SCRIPT=vagrant_install.sh;dovagrant 4; break;;
      DESTROY ) killvagrant; break;;
      Exit ) exit;;
   esac
done

function dovagrant {

    echo -e "+ ${PROVISION_SCRIPT}"

    PROVISION_SHELL_LINE="config.vm.provision :shell, :path => \"$PROVISION_SCRIPT\", run: \"always\""
    echo "writing share config to keep your repos at ${DLREPO_ROOT}";
    cat Vagrantfile.tpl > Vagrantfile
    echo -e ${PROVISION_SHELL_LINE} >> Vagrantfile
    echo -e "config.vm.synced_folder \"${DLREPO_ROOT}/userkit-api\", \"/userkit-api\"" >> Vagrantfile
    echo -e "config.vm.synced_folder \"${DLREPO_ROOT}/userkit-dashboard\", \"/userkit-dashboard\"" >> Vagrantfile
    echo -e "config.vm.post_up_message = \"Userkit API box READY! \n Make sure you have a valid secrets/ file for twilio. see secrets/example.py\"\r\n ALso, if you want to run the provisioners. you must do vagrant halt; vagrant up; if you arnet using the script!"  >> Vagrantfile
    echo "end" >> Vagrantfile
    if [ ! -z "$1" ]
    then
        case "$1" in
        1)
            vagrant up
            ;;
        2)
            echo "Reloading Vagrant"
            vagrant reload
            ;;
        3)
            echo -e "Reloading Vagrant guest with a fuLL provision"
            vagrant halt
            vagrant up --provision
            ;;

        4)
            echo -e "Reloading Vagrant with system install provision"
            vagrant halt
            vagrant up --provision
            ;;
        *)
            vagrant up
        esac
    fi
}
`
