### ISSUE TITLE
Docker provisioner: "cannot find child for ..." error

### ISSUE THREAD

**Issue by bkeroackdsc** [mitchellh/vagrant#5406]
Using the docker provisioner to pull and run containers (ubuntu/trusty64 base box, VirtualBox provider), I'm running into the following error frequently:

```
==> default: -- Container: postgresql
==> default: -- Container: maintenance
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!


          rm -f /var/lib/vagrant/cids/5b30e2c5ecb965cd571ebe6fa56b9b1db7e21ae4
          docker run --cidfile=/var/lib/vagrant/cids/5b30e2c5ecb965cd571ebe6fa56b9b1db7e21ae4 -d --name maintenance  dollarshaveclub/devbox-maintenance /sbin/my_init


Stdout from the command:

0e3f311d8a1e3e895dae6c945d1202b49051f0b77c0fa6bac50d351e3dc0ae33


Stderr from the command:

stdin: is not a tty
time="2015-02-27T22:26:48Z" level="fatal" msg="Error response from daemon: Cannot start container 0e3f311d8a1e3e895dae6c945d1202b49051f0b77c0fa6bac50d351e3dc0ae33: Cannot find child for /maintenance"
```

I'm running 9 containers in the VM, and this error happens sequentially on each (ie, initially the first container will fail, I'll do a reload and the first will run but the second will fail, etc.) so I have to run vagrant reload 8 additional times to have the box completely provisioned.

I feel this may be a race condition within the docker daemon running within the VM, so perhaps a "retry" option could be added to the docker run command in Vagrant? It's very frustrating.

**Comment by mitchellh** [comment]
This is likely a Docker bug (and may very well be fixed by now). Can you reproduce this without Vagrant?

**Comment by bkeroackdsc** [comment]
I've given up on starting containers via Vagrant and now do it via external script (with retry).

**Comment by mitchellh** [comment]
Got it, we'll close until we get a repro then. Thanks!
