### ISSUE TITLE
vagrant up fails when an unrelated non-vagrant VirtualBox machine has a missing state file

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [mitchellh/vagrant#5411]
Vagrant 1.7.2 on Windows 8.1 x64 with VirtualBox 4.3.22.

I have many virtual machines configured in VirtualBox. One of them has its image file (vdi) and its saved states on a removable drive. I only connect this removable drive when I need it. However the virtual machine configuration is not on this removable drive, the virtual machine is always present in the VirtualBox manager even if the removable drive is not present.

VirtualBox has no issue with this, all features (that are unrelated to that specific virtual machine) work fine. `vagrant up` however has issues. Vagrant seems to call `VBoxManage showvminfo` on every virtual machine that virtualbox knows about. When it comes around to that virtual machine with a missing state file, the showvminfo command spits out an error and vagrant quits:

```
Bringing machine 'default' up with 'virtualbox' provider...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "12345678-9abc-def0-1234-56789abcdef0", "--machinereadable"]

Stderr: VBoxManage.exe: error: The saved state file 'Z:\Snapshots\2015-03-01T05-24-35-433324345Z.sav' is invalid (VERR_PATH_NOT_FOUND). Dele
te the saved state and try again
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Console, interface IConsole, callee IUnknown
VBoxManage.exe: error: Context: "COMGETTER(SharedFolders)(ComSafeArrayAsOutParam(folders))" at line 2186 of file VBoxManageInfo.cpp
```

If only the harddrive image (vdi) is missing and the machine has no saved states, everything works fine.

I am assuming vagrant calls `showvminfo` to find the proper virtual machine to boot?
So perhaps vagrant should skip virtual machines that return errors? If vagrant is then unable to find any machine to boot it only then displays the errors

**Comment by mitchellh** [comment]
This is very likely a bug with VirtualBox. Vagrant only does a `showvminfo` for the machine Vagrant created, not all of them. It looks like VirtualBox doesn't let this work if there is a corrupt one.

**Comment by monsoft** [comment]
@mitchellh 
Doesn't looks like it is true as I have situation when Vagrant is looking to other non-created by Vagrant vms.

Example:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos7'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: waf-test_default_1548778731664_58049
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "199b5a00-c284-49c7-90fb-cb87624d546d", "--machinereadable"]

Stderr: 

```
Vagrant up is running "VBoxManage showvminfo 199b5a00-c284-49c7-90fb-cb87624d546d --machinereadable" on vms which is not manage/created by Vagrant.

```
$ VBoxManage list vms|egrep "99b5a00-c284-49c7-90fb-cb87624d546d|1548778731664_58049"
"WinWorkstation" {199b5a00-c284-49c7-90fb-cb87624d546d}
"waf-test_default_1548778731664_58049" {0707e3bc-c5d1-4fc6-916e-4aad1f40a060}
```

"VBoxManage showvminfo 199b5a00-c284-49c7-90fb-cb87624d546d --machinereadable"  produce error due to bug in VirtualBox 6.x https://www.virtualbox.org/ticket/18341 related to USB passthrough.

But question is why Vagrant looks to other vms ?
