### ISSUE TITLE
Hyper-V VMFirmware Cmdlets Not Supported

### ISSUE THREAD

**Issue by cjbush** [mitchellh/vagrant#5419]
When trying to launch a Hyper-V enabled machine from Vagrant Cloud, I get the following error on my Hyper-V installation on Server 2012 R2:

```text
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Configured Dynamical memory allocation, maxmemory is 2048
==> default: Configured startup memory is 512
==> default: Configured cpus number is 2
==> default: Importing a Hyper-V instance
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

Set-VMFirmware : A parameter is invalid. Generation 1 virtual machines do not
support the VMFirmware cmdlets.  Use Get-VMBios and Set-VMBios instead.
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hype
rv\scripts\import_vm.ps1:143 char:5
+     Set-VMFirmware -VM $vm -EnableSecureBoot Off
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-VMFirmware], Virtualiz
   ationInvalidArgumentException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Com
   mands.SetVMFirmwareCommand
```

Perhaps I'm missing something? It should just work, shouldn't it?

**Comment by sethvargo** [comment]
Hi @cjbush 

I believe the Hyper-V plugin is compatible on Windows 8.1 only as documented here: http://docs.vagrantup.com/v2/hyperv/index.html.

**Comment by cjbush** [comment]
Can anyone confirm that? I would think that Hyper-V on 2012 R2 and 8.1 had the same API. But who knows what Micro$oft did.

**Comment by mitchellh** [comment]
@sethvargo is correct in that on the desktop side at least 8.1+ is all that is supported. I'm not sure how that translates to Windows Server though. It could always be that the VM you're importing is a gen1 and we support gen2 only? I don't remember the minimum requirements off the top of my head currently. :(

**Comment by cjbush** [comment]
Well, theoretically at least, Server 2012 R2 is supposed to correlate to 8.1 the way 2012 did to 8, 2008 to 7, 2005 to XP, etc. I'll try creating my own basebox and see if it was a machine issue rather than an issue with Vagrant itself. I did try 2 or 3 boxes from Vagrant Cloud though, including one of the hashicorp boxes.

**Comment by cjbush** [comment]
Well, I created a simple Ubuntu 14.04 LTS basebox in Hyper-V as a Gen 2 machine and exported it and successfully re-imported it, so it looks like maybe the issue was with the boxes I was using. But now it won't boot with the "Boot Failed. EFI SCSI Device." error message. The basebox that I created it from will successfully boot into the OS. Any ideas?

**Comment by Arxisos** [comment]
I was able to create a Ubuntu 14.04 LTS box with this procedure:

- Install Ubuntu 14.04.2 on a Generation 2 VM (make sure Secure Boot is not enabled)
- Run `sudo apt-get install linux-cloud-tools-virtual linux-tools-3.16.0-30-generic linux-cloud-tools-3.16.0-30-generic` (the packages may be different for you if you have another kernel version)

Follow these instructions (copied from https://technet.microsoft.com/en-us/library/dn531029.aspx)
- Change directory to the boot EFI directory: `cd /boot/efi/EFI`
- Copy the ubuntu directory in to a new directory named boot: `sudo cp –r ubuntu/ boot`
- Change directory to the newly created boot directory: `cd boot`
- Rename the `shimx64.efi` file: `sudo mv shimx64.efi bootx64.efi`

After that create a new VM with the wizard and re-use the `vhdx` hard disk image file from the existing VM you tweaked in the steps before. Again make sure that Secure Boot is not enabled. Use this machine to create your box (ie configuring sshd etc) as usual. 

@mitchellh Maybe these instructions are more helpful if they are somewhere near the hyperv box creation documentation?

**Comment by mitchellh** [comment]
Fixed
