### ISSUE TITLE
Where is Vagrant installed in Yosemite?

### ISSUE THREAD

**Issue by RKS213** [mitchellh/vagrant#5420]
I'm trying to install Vagrant. I open the .dmg, click the .pkg, it says Successful, and after installation it doesn't have anything under Applications. What is the path for Vagrant?

**Comment by sethvargo** [comment]
Hi @RKS213 

Vagrant is in `/usr/bin/vagrant`, which is a symlink to `/opt/vagrant/bin/vagrant`. Vagrant itself is installed in `/op/vagrant`.

Older versions of Vagrant were installed in `/Applications/vagrant`, but that changed with 1.7.2. Does that answer your question?

**Comment by RKS213** [comment]
Yeah. I found it in /opt/ for some reason my find wasn't finding.
