### ISSUE TITLE
Can't mount directory with NFS on Fedora21 host

### ISSUE THREAD

**Issue by joelapatatechaude** [mitchellh/vagrant#5421]
Actually, for some mysterious reason, I can only mount my home directory.

Example:

```ruby
config.vm.synced_folder "/home/chris/MyFolder", "/home/vagrant/myfolder", create: true, :nfs => true, :mount_options => ['nolock']
```

Will timeout and fail, but

```ruby
config.vm.synced_folder "/home/chris/", "/home/vagrant/myfolder", create: true, :nfs => true, :mount_options => ['nolock']
```
Is working(and then, I can use bind mount to mount my sub dir).

**Comment by mitchellh** [comment]
Have you done an NFS sync of `/home/chris` before? Some NFS versions don't allow nested folders, and some do. Vagrant will detect a lot of these cases for you, but not all.
