### ISSUE TITLE
Ansible.extra-vars should not be prefixed with @ when it's a YAML file

### ISSUE THREAD

**Issue by ruudk** [mitchellh/vagrant#5422]
PR #2366 added the JSON/YAML option for ansible.extra_vars. 

The problem is that only JSON files should be started with @. When you reference a YAML file it should NOT be prefixed with an @.

See: http://docs.ansible.com/playbooks_variables.html#passing-variables-on-the-command-line

**Comment by sethvargo** [comment]
@gildegoma any comments here? Is this a bug?

**Comment by gildegoma** [comment]
@ruudk sorry for the response delay. I'll reject this one, because your assertion about YAML files is wrong. The "@" prefix is used by ansible for both "json" and "yaml" formats, to distinguish with json string.

@sethvargo it works fine (for me).

**Comment by sethvargo** [comment]
:+1:  thanks!
