### ISSUE TITLE
NFS faster than VMWare HGFS?

### ISSUE THREAD

**Issue by Maxim-Filimonov** [mitchellh/vagrant#5427]
I'm a bit confused by my tests NFS seems to be 2 times faster then VMware fusion HGFS. I thought it should be other way around. 

```ruby
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  $fix_vmware_tools_script = <<SCRIPT
sed -i.bak 's/answer AUTO_KMODS_ENABLED_ANSWER no/answer AUTO_KMODS_ENABLED_ANSWER yes/g' /etc/vmware-tools/locations
sed -i.bak 's/answer AUTO_KMODS_ENABLED no/answer AUTO_KMODS_ENABLED yes/g' /etc/vmware-tools/locations
SCRIPT
  config.vm.hostname = 'docker.local'

  config.vm.box = "phusion/ubuntu-12.04-amd64"
  config.vm.box_version = "2014.05.11"

  config.vm.provider "vmware_fusion" do |provider|
    provider.vmx['memsize'] = 2048
    provider.vmx['numvcpus'] = 4
  end

  # Share my entire home directory, so I can share various things with
  # individual docker containers.
  config.vm.synced_folder ENV['HOME'], "/Users/#{ENV['USER']}"

  config.vm.provision :shell, inline: <<-SHELL
    curl -sSL https://get.docker.com/ubuntu/ | sudo sh
    apt-get autoremove --purge -y

    adduser vagrant docker

    echo 'DOCKER_OPTS="-H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"' >> /etc/default/docker
    restart docker
  SHELL
  config.vm.provision "shell", inline: $fix_vmware_tools_script
end
```
Then i just run docker container with rails server inside.
Native - 230 ~ 260ms
NFS - 360 ~ 380ms (I only change sync config folder to `config.vm.synced_folder ENV['HOME'], "/Users/#{ENV['USER']}", type: "nfs"`) 
HGFS - 630~680ms 

Am I holding something wrong or is it expected?

**Comment by cspicer** [comment]
This is expected – poor IO performance is common with both Virtualbox and VMware shared folders. @mitchellh has a [blog post](http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines) outlining the various performance characteristics of both shared folders implementations compared with NFS that might be helpful for you.

**Comment by Maxim-Filimonov** [comment]
Ok then Documentation is confusing:
```
type (string) - The type of synced folder. If this is not specified, Vagrant will automatically choose the best synced folder option for your environment. Otherwise, you can specify a specific type such as "nfs".
```
According to this when type is not specified it selects "THE BEST" option. Isn't NFS the best for fusion then?

**Comment by derek-adair** [comment]
NFS is a bit more difficult to set up, whereas VMware shares work out of the box if you have VMware, same for Virtualbox.  It took me a couple days (i'm not a strong admin yet :p) of banging my head to figure out a bunch of different permissions / config issues with NFS.  Perhaps that is a reason for not picking NFS by default?

Its also possible that this documentation / code is out of date and vagrant's default config needs updating.

**Comment by dragon788** [comment]
NFS is not built into Windows, so making it the default would break on Windows systems whereas HGFS is included with Workstation/Fusion (which Vagrant treats as one provider-ish) and therefore is the default.

**Comment by Maxim-Filimonov** [comment]
@dragon788 
So Vagrant doesn't do anything special depending on host system? I would presume Vagrant can detect that NFS is installed and choose it as the best method. 
@derek-adair on Mac i just put `type: 'nfs'` and no configuration required. Vagrant does the rest :+1:

**Comment by mitchellh** [comment]
@Maxim-Filimonov We never choose NFS as the "best" method mostly due to the fact it requires user input (an admin password) that can be shocking to users. We'd like to eventually but have to iron out more issues from it.
