### ISSUE TITLE
Vagrant.has_plugin? returns true when VAGRANT_NO_PLUGINS env variable is set

### ISSUE THREAD

**Issue by splenetic** [mitchellh/vagrant#5430]
If I have VAGRANT_NO_PLUGINS set and something like this in my Vagrantfile:
```ruby
if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
end
```
I get `Unknown configuration section 'cache'.`
Would it make more sense for Vagrant.has_plugin? to return false in this case, so that the Vagrantfile does not need to be modified?

**Comment by cburyta** [comment]
+1
