### ISSUE TITLE
prompt for sudo password at start of 'vagrant up' instead of halfway through

### ISSUE THREAD

**Issue by blobhouse** [mitchellh/vagrant#5431]
Hi,

I first reported this in the vagrant-hostupdater forum, but it seems like more of a general Vagrant issue; for instance, NFS mounts also seem to require sudo for editing /etc/exports.

       https://github.com/cogitatio/vagrant-hostsupdater/issues/55#issuecomment-77111213

"We've started using this plugin with Vagrant under OS X at our office, and it works well. But one issue that keeps coming up is that some time after running "vagrant up", 'sudo' requests the user's password (in order to edit /etc/hosts) in the middle of our fairly long provisioning process. The length of that process wouldn't be an issue if a user could start it and walk away, but instead they have to wait around an indeterminate period of time before they're asked to enter their password.

I solve this by running "sudo echo foo; vagrant up" so that sudo caches my password. It would be much better if Vagrant did that internally: ask for the user's password as early in the process as possible, and let sudo cache it until it's needed."

**Comment by quater** [comment]
Would be great to have! +1

**Comment by derek-adair** [comment]
In the mean time this can be remedied by adding vagrant to your sudoers group...

# Setup sudo to allow no-password sudo for "admin"
groupadd -r admin
usermod -a -G admin vagrant
cp /etc/sudoers /etc/sudoers.orig
sed -i -e '/Defaults\s\+env_reset/a Defaults\texempt_group=admin' /etc/sudoers
sed -i -e 's/%admin ALL=(ALL) ALL/%admin ALL=NOPASSWD:ALL/g' /etc/sudoers

**Comment by derek-adair** [comment]
You can add [passwordless sudo](http://askubuntu.com/questions/406787/best-way-add-nopasswd-vagrant-user) in the mean time.

**Comment by quater** [comment]
Based on your suggested workaround, I could get the following working on Ubuntu 14.10. It's not the most secure way of dealing with it but in some circumstances this might be appropriate.

Here is goes for everyone who needs a workaround and understands the security implications of it.
```
# Enable the "user" to run sudo commands without passwords!
# Note: Replace "user" with the desired username.
$ echo %user ALL=NOPASSWD:ALL > /etc/sudoers.d/user
$ chmod 0440 /etc/sudoers.d/user
$ usermod -a -G sudo user
```

**Comment by derek-adair** [comment]
Completely agree.  A prompt up front to "run as sudo" would be perfect for minimizing this risk.  This particular issue was a fairly big PITA / hang up when learning how to build my own vagrant boxes, although, it is clearly documented [here](http://docs.vagrantup.com/v2/boxes/base.html) (mentions sudo as a requirement)

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening this issue. Coming back around and spending some time thinking about this, I do not think it's possible for Vagrant to do this in advance. First, Vagrant may _not_ need to use sudo if particular actions have already been performed, and Vagrant wouldn't know that until very late in the provisioning run. Furthermore, plugins may require sudo and Vagrant has no way of knowing that. We wouldn't want to needlessly prompt a user for sudo if it was unnecessary.

I know it sucks, but I think the best solution here is `sudo echo hello; vagrant up` or add passwordless sudo for the Vagrant user as documented in the other comments above. Sorry! 😦

**Comment by ryancastle** [comment]
What about a configuration variable which we can explicitly set as a requirement, so at least people have an option?
