### ISSUE TITLE
No real-time synced folder support for Windows host with FreeBSD guest

### ISSUE THREAD

**Issue by Vhab** [mitchellh/vagrant#5432]
After a good afternoon of wrestling vagrant, I have come to the conclusion there's currently no supported real-time shared folder option for a combination of a Windows host and a FreeBSD guest.

The documentation lists the following synced folder methods:

- NFS: Not supported on Windows hosts
- rsync: Not the desired behavior (only syncs when explicitly instructed, only goes 1-way)
- SMB: Not supported on FreeBSD guests by vagrant
- VirtualBox: Not supported on FreeBSD guests

I do understand NFS and VirtualBox Shared Folder support are currently out of the hands of Vagrant to support for this combination of OSes.

Would SMB support for FreeBSD guests be something Vagrant could support?

**Comment by Savagedlight** [comment]
Looking at "plugins/guests/linux/cap/mount_smb_shared_folder.rb", I think that code should work for FreeBSD guests as well. I can't see anything there which shouldn't work in a FreeBSD guest.

**Comment by sethvargo** [comment]
Hi @Vhab 

Could you please share any errors you have when trying to mount smb shared folders? The [debug output](http://docs.vagrantup.com/v2/other/debugging.html) would be helpful.

**Comment by Vhab** [comment]
There's not really an error as much as vagrant simply telling me it's not supported.

Looking at the freebsd guest source, the smb capability just isn't there.

But for the sake of completeness, I used the following vagrant file:

```
Vagrant.configure(2) do |config|
  config.vm.box = "chef/freebsd-10.0"
  config.vm.synced_folder ".", "/vagrant", type: "smb"
end
```

And got the following output:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'chef/freebsd-10.0'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'chef/freebsd-10.0' is up to date...
==> default: Setting the name of the VM: Vagrant_default_1433326607696_19591
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: Windows account.
    default:
    default: Username: ****
    default: Password (will be hidden):
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting SMB shared folders...
Vagrant attempted to execute the capability 'mount_smb_shared_folder'
on the detect guest OS 'freebsd', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

**Comment by sethvargo** [comment]
Thanks, re-tagged!

**Comment by mitchellh** [comment]
I'd be happy for SMB support, but it'll have to be contributed. Thanks!
