### ISSUE TITLE
Not able to Access Vagrant on lan network via ssh

### ISSUE THREAD

**Issue by hardikdangar** [mitchellh/vagrant#5438]
I have enable following settings on Vagrant instance via Vagrantfile,

```ruby
config.vm.network :public_network, bridge: "eth0", ip: "192.168.1.191"
config.ssh.forward_agent = true
```

I could ping the IP but when i try to connect to ssh like,

```text
ssh vagrant@192.168.1.191
```

i am getting,

```text
PTY allocation request failed on channel 0
Welcome to Host, Anonymous!
Connection to 192.168.1.191 closed.
```

When i Vagrant up, i get following

```text
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/panda/vm/gitlab
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.
```

My guess is vagrant somehow binds ssh to 127.0.0.1 only although i have specified public address.
Can anyone tell me i need to change any other settings to access my VM via ssh directly ?

**Comment by sethvargo** [comment]
Hi @hardikdangar 

What if you try to SSH using port 2222 instead of 22 (the default)?

**Comment by hardikdangar** [comment]
It says connection refused.

**Comment by dragon788** [comment]
If you don't need bridged mode, simply doing a vagrant up will map 22 in the guest to 2222 on your host, in which case you can ssh vagrant@localhost -p 2222 and connect.

You may need to specify the ssh port as an override, but I'm not certain that is supported via bridged networking yet, as there is always a NAT connection in order for 'vagrant ssh' to work. Is there a reason you need to access the machine via SSH without doing port forwarding via NAT or using the 'vagrant ssh' command from the system where you ran 'vagrant up'?

**Comment by hardikdangar** [comment]
I am on small Lan and i have a server in which i am using vagrant and there are people who needs to access that vm also i am running a service which can be accessed via IP so i need bridged mode.

Now i can ssh my server then access vm via sshing again but it messes lot of things in terminal like
i can't use arrow keys and lot of things don't work and i have to be very careful for running it.

**Comment by sethvargo** [comment]
@hardikdangar I believe you will want to use `vagrant share` instead. It is designed for these types of scenarios.

**Comment by hardikdangar** [comment]
My guess is vagrant share will allow access to not just via lan but via wan too right ? that would be security concern i guess ?

**Comment by sethvargo** [comment]
@hardikdangar you can use the `--once` flag to only allow a single connection: http://docs.vagrantup.com/v2/share/ssh.html

The issue is that Vagrant _needs_ a reliable SSH/WinRM connection to the VM to execute commands and inspect the VM.

**Comment by sethvargo** [comment]
Hi @hardikdangar 

Are there any other questions I can answer?

**Comment by hardikdangar** [comment]
We can close this for sure. what i found is i could access other vagrant machines but not that one. because that was closed by one of the server software in that machine.
