### ISSUE TITLE
Multi machine setup with docker - containers lose links

### ISSUE THREAD

**Issue by bubenkoff** [mitchellh/vagrant#5439]
Containers lose links if the linked container gets stopped/destroyed.

Doing vagrant up doesn't restore the links anymore.

**Comment by sethvargo** [comment]
Hi @bubenkoff 

I am unable to reproduce this with Vagrant 1.7.3, but perhaps I am doing something wrong. Could you please try Vagrant 1.7.3 and if that is not working, share your complete Vagrantfile and the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by bubenkoff** [comment]
steps are:

Part of vagrant:

```vagrant

       config.vm.define "postgres" do |v|
        v.vm.provider "docker" do |d|
          d.name = 'postgres'
          d.image = "paintedfox/postgresql"
          d.ports = ["5432:5432"]
          d.env = {
            USER: "root",
            PASS: "abcdEF123456",
            DB: "root"
          }
          d.has_ssh = false
        end
      end

       config.vm.define "mysql" do |v|
        v.vm.provider "docker" do |d|
          d.name = 'mysql'
          d.image = "library/mysql"
          d.ports = ["3306:3306"]
          d.env = {
            MYSQL_USER: "pltest",
            MYSQL_PASSWORD: "",
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes",
            MYSQL_ROOT_PASSWORD: "abcdEF123456",
            MYSQL_DATABASE: "pltest"
          }
          d.has_ssh = false
        end
      end

      config.vm.provider :docker do |d, override|
        d.name = "paylogic"
        d.cmd     = ["/sbin/my_init", "--enable-insecure-key"]
        d.has_ssh = true
        override.ssh.port = 22
        if !ENV['IMAGE_BUILD']
            d.image = "paylogic/vagrant"
            d.link("postgres:postgres")
            d.link("mysql:mysql")
        else
            d.build_dir = "." 
        end
      end
```

* vagrant up
* print mysql <- does work
* vagrant destroy mysql
* vagrant up
* vagrant ssh
* print mysql <- doesn't work

**Comment by sethvargo** [comment]
Hi @bubenkoff 

Thank you for that. Unfortunately I still do not understand the issue. What do you mean by "print mysql? If you destroy a linked container, the other containers will lose that link - that's the way Docker works (and it's the most correct behavior). If you want Vagrant to re-link after you destroy a linked container, you will need to run `vagrant reload` on the linking VM to re-create that link, since links are only created when the container is booted. Thanks! :smile:
