### ISSUE TITLE
`vagrant up` fails when setting a static IP address running via Cygwin

### ISSUE THREAD

**Issue by thasmo** [mitchellh/vagrant#5445]
In my Vagrantfile a static address is defined with `config.vm.network :private_network, ip: '192.168.100.100'`.

This runs fine when using `cmd.exe`, but when running it via Cygwin, Vagrant complains it can't find `netstat`.

Apparently or unfortunately there's no `netstat` package available for Cygwin and I was wondering if Vagrant could just use `netstat.exe` from Windows, when running from within the Cygwin environment.

**Comment by sethvargo** [comment]
Hi @thasmo 

Are you able to provide the exact output of the command please? Additionally if you could run the command in debug mode and Gist the output, that would be fantastic!

**Comment by thasmo** [comment]
Sure!
[Debug output](https://gist.github.com/thasmo/3329d0a0c8b37a8e414e) and default output:
```shell
> vagrant up
Bringing machine 'default' up with 'vmware_workstation' provider...
==> default: Checking if box 'chef/ubuntu-14.10' is up to date...
==> default: Verifying vmnet devices are healthy...
The external program used to read TCP/IP routing tables in order
to protect you against creating network collisions could not be
found. On Linux and Mac OS X, this is `netstat`. Please make sure
this is on your PATH. It is generally installed with your
operating system.
```

**Comment by thasmo** [comment]
@sethvargo, does the debug output help?

**Comment by sethvargo** [comment]
Hi @thasmo 

I just checked the source, and Vagrant is using `Vagrant::Util::Which.which("netstat")` to try to find the binary. If you look at the source for that, it checks all the values in `PATHEXT` - https://github.com/mitchellh/vagrant/blob/44ce6a4bc746c7cd2462197a290613870381b329/lib/vagrant/util/which.rb#L29

Could you see if `PATHEXT` is set in your Cygwin environment? Does netstat.exe exist there?

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
