### ISSUE TITLE
Checksum validation

### ISSUE THREAD

**Issue by gajdaw** [mitchellh/vagrant#5449]
Hi,
If I'm not misstaken cheksums still do not work.

My `Vagrantfile` contains the following code (notice the fake  checksum):

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "01234567890"
  config.vm.box = "http://boxes.gajdaw.pl/apache/apache-v0.3.3.box"
end
```

The command `vagrant up` succesfully boots VM:

```
songs-app-angularjs (checksum)$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'http://boxes.gajdaw.pl/apache/apache-v0.3.3.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'http://boxes.gajdaw.pl/apache/apache-v0.3.3.box' (v0) for provider: virtualbox
    default: Downloading: http://boxes.gajdaw.pl/apache/apache-v0.3.3.box
==> default: Successfully added box 'http://boxes.gajdaw.pl/apache/apache-v0.3.3.box' (v0) for 'virtualbox'!
==> default: Importing base box 'http://boxes.gajdaw.pl/apache/apache-v0.3.3.box'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: songs-app-angularjs_default_1425977996794_77665
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)

```

**Comment by gajdaw** [comment]
I noticed that the command:

```
vagrant box add \
    apache-v0.3.3 \
    --checksum-type sha256 --checksum 019238457 \
    http://boxes.gajdaw.pl/apache/apache-v0.3.3.box
```

works as expected producing:

```
The checksum of the downloaded box did not match the expected
value. Please verify that you have the proper URL setup and that
you're downloading the proper file.

Expected: 019238457
Received: 1e7c94c5b5ec152ca6c7fee68b830e7b07cca01b0b871f1f4da89c1408c568bb
```

I use Vagrant 1.7.2 on OS X.

**Comment by aworstell** [comment]
I can confirm that this is still not working on Windows either with the VMware provider plugin. I see on the changelog page that this should be fixed in 1.7.3:
core/cli: fix box checksum validation [GH-4665, GH-5221]

I hope this is released soon!

**Comment by mitchellh** [comment]
Fixed

**Comment by saavi21** [comment]
C:\Users\ABC\cmder\vagrant_files\project1\songs-app-django (master -> origin)
λ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'django-v1.0.0' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'django-v1.0.0' (v0) for provider: virtualbox
    default: Downloading: http://boxes.gajdaw.pl/django/django-v1.0.0.box
    default:
    default: Calculating and comparing box checksum...
The checksum of the downloaded box did not match the expected
value. Please verify that you have the proper URL setup and that
you're downloading the proper file.

Expected: 320d9bf2f41db4c80ffaa19016e4ab434f1eae0a8cc6067fde530b2cee52ccb2
Received: e4f4afbe538909581e6c5a32a3fd7f74f7ff6764f56fa0b96b84912a846f98df
