### ISSUE TITLE
Getting 'A valid license is required to run the Vagrant VMware' after a vagrant 1.7.2 fresh install

### ISSUE THREAD

**Issue by micheleorselli** [mitchellh/vagrant#5450]
I installed vagrant 1.7.2 on osx yosemite and got this error when invoking vagrant up:

```A valid license is required to run the Vagrant VMware```

a ```vagrant plugin list``` shows the plugin "vagrant-vmware-workstation" as installed, which is strange since the only provider available is virtualbox.

After removing the plugin everything started working as expected

**Comment by sethvargo** [comment]
Hi @micheleorselli 

That's strange - had you previously had Vagrant installed? Where did you download Vagrant from? Any additional information you can provide would certainly be helpful!

**Comment by micheleorselli** [comment]
Hi @sethvargo, thank you for the response
- I was upgrading vagrant from 1.6.3 to 1.7.2 both downloaded from vagrantup.com
- The target machine is an osx yosemite though version 1.6.3 was installed before upgrading
- vmware software (workstation, fusion) has never been present on the machine

Hope it can help, I can provide further details if needed

**Comment by sethvargo** [comment]
@micheleorselli that is really weird. I'm going to tag this as "installer", but I just tried both of those versions and cannot get the behavior to reproduce. Are you able to reproduce this @micheleorselli?

**Comment by micheleorselli** [comment]
Well yes, really weird: I installed vagrant a lot of times on different machines, this is the first time I experience this problem.

I'll try to reproduce it and let you know, probably will be able to look at it in a couple of days

**Comment by Funi1234** [comment]
I was getting "__No gems found matching "vagrant-vmware-fusion" "3.1.2" nil__" after a box update so i ran "__vagrant plugin install vagrant-vmware-fusion__" which installed 3.2.6 and now on _vagrant up_ I'm receiving the same message.

**Comment by sethvargo** [comment]
@Funi1234 you're message is different. The Vagrant VMware Fusion provider is a paid provider that requires a license. You cannot use vmware_desktop boxes without a valid license. If you uninstall the vagrant-vmware-fusion plugin, you should be able to use Vagrant again.

**Comment by Funi1234** [comment]
@sethvargo Thanks you. 

The box I'm using is "ubuntu/trusty64"

I'm still curious why, after doing a "__vagrant box update__", vagrant was looking for vagrant-vmware-fusion as a dependency when i tried to run vagrant up.

**Comment by sethvargo** [comment]
@Funi1234 I'm not sure, but that seems like a separate issue. Could you open a new issue with the exact steps you took to reproduce please? Thanks!

**Comment by micheleorselli** [comment]
@sethvargo regarding the original issue I wasn't able to reproduce it anymore. Uninstalling and reinstalling vagrant now works as expected

**Comment by sethvargo** [comment]
Hi @micheleorselli 

That's good to hear! I am going to close this issue for now as we do not have a way to reproduce this. We are going to work on a refactor of the installer shortly that will hopefully fix many of these strange edge cases. Thanks!

**Comment by gjohnson** [comment]
@sethvargo FWIW this happened to me too, uninstalling did not fix the problem. However, after noticing and deleting `~/.vagrant.d`, everything was okay.

**Comment by bdgeorge** [comment]
@sethvargo virtually the same thing here, after upgrading to 1.7.2 my vagrant lost it's vmware plugin license and started returning the same error. In my scenario there was a vmware machine in play, so I had re-add the license to get vagrant working again with them.

**Comment by nirvanagit** [comment]
Does not work for me too. 

I have vagrant setup and was using it for parallels.

Today, wanted to experiment with vmware fusion and got the same error.

Do we need to have a our own license to run vmware fusion with vagrant?

**Comment by irparaja** [comment]
error "A valid license is required to run the Vagrant VMware
provider. Please visit http://www.vagrantup.com to purchase
a license. Once you purchase a license, you can install it
using `vagrant plugin license`."

when i install the vagrant i got above error
