### ISSUE TITLE
`vagrant up` fails due to vmware-networks --configure

### ISSUE THREAD

**Issue by jmiller0** [mitchellh/vagrant#5451]
This is a duplicate of these issues, however I am still seeing this as an issue:
https://github.com/mitchellh/vagrant/issues/4780#event-214376210
https://github.com/mitchellh/vagrant/issues/4451

Here is my debug log:
https://gist.github.com/jmiller0/c5d54ede5b9060ae4247

vmware-networks --version
vmware-networks version: 0.1

vmware-networks --status
Bridge networking on vmnet0 is not running
DHCP service on vmnet1 is not running
Hostonly virtual adapter on vmnet1 is disabled
DHCP service on vmnet2 is not running
Hostonly virtual adapter on vmnet2 is disabled
DHCP service on vmnet8 is not running
NAT service on vmnet8 is not running
Hostonly virtual adapter on vmnet8 is disabled
Some/All of the configured services are not running

vmware-networks --configure
vmware-networks: unrecognized option '--configure'
Try 'vmware-networks --help' for more information

Product Name         Product Version     
==================== ====================
vmware-workstation   11.1.0.2496824     

vagrant plugin list                                         
vagrant-share (1.1.3, system)
vagrant-vmware-workstation (3.2.4)

**Comment by jmiller0** [comment]
So I'm not seeing any other terrors in my log.   How do I debug why the adapter is not being created or coming up?

Thanks

**Comment by phinze** [comment]
Hi there @jmiller0 - I see you've also reached out via support. We'll work out the details on that thread and I will follow up here with the results of what we figure out.

**Comment by phinze** [comment]
We finally figured this one out! `v3.2.5` of `vagrant-vmware-workstation` was just released with the fix.

Basically, we had previously assumed it was sufficient to ignore the fact that on Linux the `--configure` option was not supported, when in fact Linux has a unique snowflake of a flag to reconfigure network devices. :grinning: :snowflake: 

As of `v3.2.5` we are now properly using that option (`--migrate-network-settings`) on Linux.
