### ISSUE TITLE
Vagrant up timing out 

### ISSUE THREAD

**Issue by dgrunspan** [mitchellh/vagrant#5452]
I am using CentOS 7 VM on Google compute engine

Installed Vagrant & VirtualBox
"vagrant up" is timing out (connection timeout retrying..)
after it exit if i do "vagrant up" again its says its already running
When trying to-do "vagrant ssh" I get "connection reset by peer"

Using the hashicoro/precise32 and latest version

Thanks
Danny

**Comment by sethvargo** [comment]
Hi Danny,

Could you please try running the command in debug mode and Gist the output here?

**Comment by sethvargo** [comment]
Closing due to no response. Please open a new issue if this is still happening and include the output in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html).
