### ISSUE TITLE
Lookup Path option for CLI

### ISSUE THREAD

**Issue by Turbo87** [mitchellh/vagrant#5453]
It would be great to be able to overwrite the default [Lookup Path](http://docs.vagrantup.com/v2/vagrantfile/) with a CLI parameter. It is currently possible by overriding the `VAGRANT_CWD` environment variable, but having a CLI parameter seems more convenient to me.

Please let me know if there are any reasons against it, and/or possibly any pointers on how I could implement this.

**Comment by sontek** [comment]
+1 for this, what I would really like is a `--file` argument or something, I don't want a lookup path at all, I want to point it directly to a specific file.

**Comment by Turbo87** [comment]
@sontek that would work for me too

**Comment by sethvargo** [comment]
See comments in https://github.com/mitchellh/vagrant/pull/5468.
