### ISSUE TITLE
Feature: Vagrant browser hooks (think grunt-reload)

### ISSUE THREAD

**Issue by derek-adair** [mitchellh/vagrant#5454]
*This may be better fitted for a plugin as its fairly out of scope, just wanted to see if anyone is desiring something like this.*

Basically, I had this random thought of how Vagrant might better aide rapid iterations / development.  This feature would hook into whatever end point, API, UI, DB, ...whatever... and automatically refresh this endpoint when certain events trigger.  My primary use case would be when I write a file on my local machine, or VM, I want my browser window to refresh.  Basically granting the capabilities of [grunt-reload](https://www.npmjs.com/package/grunt-reload) to any stack.

Additionally, this could automatically map ports with auto_correct on.

**Comment by derek-adair** [comment]
If you wanna get really fancy you could pass it DOM manipulations, set GET variables, etc etc.

**Comment by sethvargo** [comment]
Hi @derek-adair 

Thank you for opening an issue. As you suspected, I think this might be better served as a plugin. If the plugin gains significantly popularity, it is very easy to migrate the plugin into Vagrant core :smile:. Please let me know if you have any questions or need any guidance!
