### ISSUE TITLE
Using override.vm.provision with puppet.synced_folder_type = 'nfs' causes infinite loop

### ISSUE THREAD

**Issue by agx** [mitchellh/vagrant#5456]
I'm using this configuration with vagrant-libvirt:

    config.vm.define :foo do |x|
        x.vm.hostname = "foo"
        x.vm.network :private_network, :ip => "192.168.3.10"

        config.vm.provider :libvirt do |libvirt, override|
          override.vm.synced_folder './', '/vagrant', type: 'nfs'
          override.vm.provision :puppet do |puppet|
              puppet.manifest_file  = "site.pp"
              puppet.module_path = [ "modules" ]
              puppet.hiera_config_path = "hiera.yaml"
              puppet.working_directory = "/vagrant"
              puppet.synced_folder_type = 'nfs'
        end
    end

and end up with:

    INFO interface: info: ==> foo: Waiting for SSH to become available...
    ==> foo: Waiting for SSH to become available...
    DEBUG ssh: Checking whether SSH is ready...
    INFO machine: Calling action: read_ssh_info on provider Libvirt (de7f31a5-83b6-4847-b176-64a6fac094c0)
    INFO runner: Preparing hooks for middleware sequence...
    INFO runner: 1 hooks defined.
    INFO runner: Running action: #<Vagrant::Action::Builder:0x000000040a9ea8>
    INFO warden: Calling IN action:
    #<Vagrant::Action::Builtin::ConfigValidate:0x000000040e08e0>
    ERROR warden: Error occurred: There are errors in the configuration of this machine. Please fix the following errors and try again:

    vm:
    * Shared folders that have NFS enabled do not support owner/group attributes. Host path: /home/agx/git/infra/manifests
    * Shared folders that have NFS enabled do not support owner/group attributes. Host path: /home/agx/git/infra/modules

This gets repeated over and over again. However if I move the
override.vm.provision part out of config.vm.provision everything works
as expected (I can't do so in a real setup though since I only want
the synced_folder_type set in case of libvirt).

I don't know if this is an error in the plugin or in vagrant's core (this is 1.7.2). Any more information I can provide?

**Comment by mitchellh** [comment]
Fixed
