### ISSUE TITLE
vagrant provision provisions non-started machines

### ISSUE THREAD

**Issue by warrenseine** [mitchellh/vagrant#5457]
*Cloning issue tknerr/vagrant-managed-servers#34 because I don't know if that's actually specific to the plugin.*

Since `vagrant up` respects `autostart: false`, I would expect `vagrant provision` to do the same and only provision `up` machines.

My use case is simple. I use a multi-machine setup to target my local environment (`virtualbox` provider, `primary: true`) and my staging environment (`managed` provider, `autostart: false`).

If I explicitly call `vagrant provision my-local-box`, only the local environment gets provisioned. Unfortunately, if I call `vagrant up` then `vagrant provision`, the staging environment will implicitly get provisioned, even if it has `autostart: false`.

**Comment by sethvargo** [comment]
Hi @warrenseine 

Thank you for opening an issue. I've tagged this as both a bug and an enhancement. It's a bug because we should document the behavior as-is, and it's an enhancement because we should probably behave as you described :smile:.

**Comment by mitchellh** [comment]
This is working as intended. The `autostart` only affects when the machine is _started_ (hence "autostart") but not when it is provisioned. If you `vagrant provision` then all machines will be provisioned.
