### ISSUE TITLE
Unable to install plugins from local corporate mirror using corporate CA certificate

### ISSUE THREAD

**Issue by drcraig** [mitchellh/vagrant#5458]
At my company we need to install Vagrant plugins from an internal mirror of rubygems.org. That is solvable with the `--plugin-source` option, but the problem is that the mirror uses an internal root CA certificate. On Linux machines, I can set the SSL_CERT_DIR environment variable to fix that (but, curiously, SSL_CERT_FILE does not work), but on Macs I'm stuck because the cert resides inside Keychain.

I see the `--cacert` option on `vagrant box`, but it only appears operable on that one command. Short of just appending the cert to `/opt/vagrant/embedded/cacert.pem`, is there any way to get Vagrant to use the cert for plugin installs?

Running Vagrant 1.7.2 on OS X 1.9.5.

**Comment by drcraig** [comment]
A very nice bonus feature would be for Vagrant to provide a way to set those options in a config file, preferably in a way that can be applied globally (i.e., not just a ~/.vagrantrc but also a /etc/vagrantrc). Or perhaps just have Vagrant respect the source options setup in gemrc files.

**Comment by rholloway** [comment]
+1 

I just spent much longer than planned trying to get around a corporate certificate MITM issue. I tried modifying a handful of things from /opt/vagrant/embedded/etc/gemrc to copying /opt/vagrant/embedded/gems/gems/bundler-*/lib/bundler/ssl_certs, but nothing worked until manually appending cert to /opt/vagrant/embedded/cacert.pem (although the error messages did get different after copying pem to the bundler ssl_certs, so not sure if that was needed or not...)

In any case, some easy way to adjust CA certificate usage for vagrant plugin installs would be great. Or, have it respect system ca certificates as well (this was my first step by adding it to ubuntu ca-certificates)

**Comment by alathers** [comment]
Agree this is highly meaningful for my use cases as well.  At least for Debian/Ubuntu systems, there exists a supported way to do this gracefully.  You could leverage something to the effect of /etc/ca-certificates/update.d/ which is passed the know set kept in /etc/ca-certificates.conf as well as locally installed /usr/local/share/ca-certficates

**Comment by sethvargo** [comment]
This was fixed https://github.com/mitchellh/vagrant-installers/commit/76d032b5c433e676855ca69f7ea72b823e800863
