### ISSUE TITLE
vagrant does not autodetect docker provider under linux

### ISSUE THREAD

**Issue by jinxcat** [mitchellh/vagrant#5459]
Under linux (seen under ubuntu 14.04), on vagrant up, vagrant does not detect the docker provider, while docker -d is up and running.

If another provider (eg. virtualbox) is present, it falls back to that one.

--provider=docker solves this.

**Comment by mitchellh** [comment]
Docker isn't currently set as a default-able provider. You can override this in your Vagrantfile with `config.vm.provider` ordering.
