### ISSUE TITLE
RDP username requires "LocalAccount" domain for Win 8+

### ISSUE THREAD

**Issue by rivy** [mitchellh/vagrant#5460]
For Windows 8+, RDP requires using the "LocalAccount" domain prefix for the username to successfully connect to the VM. This is not at all obvious and likely a pain point for many folks trying to RDP into the VM using `vagrant rdp`.

The current default behavior is to use the `winrm.username` unless the provider overrides `rdp_info` (see [`get_rdp_info()`](https://github.com/mitchellh/vagrant/blob/efd1d5e11bfc5a72c7a1d1eae294b4751d841544/plugins/commands/rdp/command.rb#L56])). But it seems that WinRM basic authorization does not honor domain (though my evidence is only based on experimentation and on this anonymous answer on StackOverflow: http://stackoverflow.com/a/17244312/43774). So, I believe, we're unable to use "LocalAccount\vagrant" as the `winrm.username`.

I may be missing something, but the only way I see to override the default RDP username is to implement a custom provider, which seems like overkill for a simple configuration string. That seems like the wrong approach to me, and I favor adding `config.rdp.username` for use within the Vagrantfile.

Thanks for the attention.

**Comment by mitchellh** [comment]
Done
