### ISSUE TITLE
VMWare Provider GUI not working

### ISSUE THREAD

**Issue by apackeer** [mitchellh/vagrant#5462]
Hi,

The v.gui = true doesn't seem to be working.

Vagrant version: 1.7.2
Vagrant-vmware-fusion: 3.2.4
Vmware Fusion Professional 7.1.1 (2498930)
Mac OSX Yosemite

I have the following minimal Vagrantfile:

```
Vagrant.configure(2) do |config|
  config.vm.box = "chef/ubuntu-14.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "vmware_desktop" do |v|
	v.gui = true
  end
end
```

Box launches fine and i can log into via `vagrant ssh`, but no longer shows VMWare Fusion console.

**Comment by mitchellh** [comment]
The provider config must be `vmware_fusion` unfortunately
