### ISSUE TITLE
File provisonner is not working with Windows guest

### ISSUE THREAD

**Issue by mlenormand** [mitchellh/vagrant#5465]
The file is not uploaded to the Windows guest when using file provisionner with Windows guest :

My config :

```
config.vm.provision "file", source: "file.txt, destination: "C:\test"
```

No error but nothing happens with vagrant up --provision : the 'test' folder is not created and file.txt is not uploaded.
The above config line is taken into account by Vagrant because if I replace 'file.txt' by a not-existing-file-name, Vagrant reports the error.

File path syntax under Windows is not well documented so I also try :"C:/test" or destination:"C:\\test".

Synced folder also does't work with this config :

```
config.vm.synced_folder ".", "C:\test"
```

No problem with Linux guest. Reproduced with Windows 2012 R2 and Windows 7 guest built with https://github.com/joefitzgerald/packer-windows.

Any help would be very appreciated.

**Comment by nscaife** [comment]
The following works for me:

```ruby
config.vm.provision "shell", inline: "mkdir c:\test"
config.vm.provision "file", source: "file.txt", destination: "C:\test\file.txt"
```

**Comment by sethvargo** [comment]
Hi @mlenormand 

I am not able to reproduce this issue with the windows box `mwrock/Windows2012R2` and Vagrant 1.7.3. Can you please update Vagrant, VirtualBox, and try again? Given that Vagrant has a large Windows audience and others have not reported this issue, I am inclined to believe this may be a local issue or perhaps an issue with the box itself. Thanks!
