### ISSUE TITLE
Should vagrant init <boxname> produce a Vagrantfile identical to the one "packaged" with the box?

### ISSUE THREAD

**Issue by derek-adair** [mitchellh/vagrant#5466]
I'm not sure if this is a bug or not, but when i do `vagrant init <boxname>` it properly inserts <boxname> as the vm.box, but not the rest of my config.

**Comment by sethvargo** [comment]
Hi @derek-adair,

Thank you for opening an issue. `vagrant init` always creates the same default Vagrantfile regardless of what box it used. Please let me know if you have any additional questions.
