### ISSUE TITLE
Run one off commands in VM from host

### ISSUE THREAD

**Issue by derek-adair** [mitchellh/vagrant#5470]
Is this possible?  I'm thinking something similar to how `docker run` works.  Maybe an overridable entrypoint / cmd to run?

**Comment by sethvargo** [comment]
Hi @derek-adair 

You can execute commands over SSH using the `-c` flag:

```text
$ vagrant ssh -c "echo hi"
```

I believe you may be interested in this third-party plugin: https://github.com/p0deje/vagrant-exec. 

Does that answer your question?

**Comment by derek-adair** [comment]
Like a charm! thanks.
