### ISSUE TITLE
Conflict in default rsync__args (specifically, --copy-links vs --archive)

### ISSUE THREAD

**Issue by jdunk** [mitchellh/vagrant#5471]
I have a broken symlink in my source rsync directory, and vagrant's `rsync` call fails when it encounters this (`symlink has no referent`) even though vagrant's default `rsync__args` include `--archive`.

This apparently has something to do with the presence of another argument, `--copy-links`.  When that argument is omitted (via `rsync__args: ["--verbose", "--archive", "--delete", "-z"]`), the rsync is successful.

(For good measure, I also tried `--copy-links` __without__ `--archive`.  The result: `rsync: --delete does not work without -r or -d`)

OS X 10.10.2 (host)
Ubuntu precise64 (guest)
Vagrant 1.7.2
GuestAdditions 4.3.24
(host) rsync  version 2.6.9  protocol version 29

**Comment by mitchellh** [comment]
You can specify `args` manually to override args. Vagrant uses the most commonly acceptable args but if it isn't working for you then you should override.
