### ISSUE TITLE
VMware mounting uses wrong "id" command to get group of user

### ISSUE THREAD

**Issue by atombender** [mitchellh/vagrant#5472]
My `Vagrantfile` has something like this:

    config.vm.synced_folder "./myapp", "/srv/myapp", owner: 'myapp', group: 'apps'

This results in the following error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -t vmhgfs -o uid=`id -u myapp`,gid=`id -g apps` '.host:/-srv-myapp' /srv/myapp

Stdout from the command:

Error: could not parse options string


Stderr from the command:

stdin: is not a tty
id: apps: no such user
```

Notice how it's using `id -g apps`, apparently to find the group. However, the `id` command from GNU Core Utilities takes a user name, not a group name.

**Comment by mitchellh** [comment]
This is fixed, we use `getent` now.
