### ISSUE TITLE
Downloading from tftp:// uses HEAD query

### ISSUE THREAD

**Issue by borgand** [mitchellh/vagrant#5477]
I'm trying to get Vagrant to automatically fetch my boxfile from build server using TFTP protocol. 

```
  config.vm.box_url = "tftp://tftp.host:/devbox.box"
```

This results in Vagrant using `HEAD` query at first which downloads the entire boxfile to STDOUT, before starting actual download.

Trying it directly with embedded `curl` works as expected:

```
/opt/vagrant/embedded/bin/curl --output /tmp/box tftp://tftp.host/devbox.box
```

But when using the same URL in Vagrantfile, it does not. DEBUG output shows this:

    INFO box_add: Downloading box: tftp://tftp.host/devbox.box => /home/laas/.vagrant.d/tmp/box2f41853e07736bc3f7ba8f307ab44f0f11e9ae47
    INFO downloader: HEAD: tftp://tftp.host/devbox.box
    INFO subprocess: Starting process: ["/opt/vagrant/bin/../embedded/bin/curl", "-I", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.7.2", "--continue-at", "-", "-H", "Accept: application/json", "tftp://tftp.host/devbox.box"]

And after that `curl` starts to output binary data.

When not in DEBUG-mode, I can `Ctrl-C` while it's waiting for the HEAD to complete and then a regular download continues and successfully adds box (then exits due to interrupt). A next `vagrant up` will then successfully create a VM.

Other than the `HEAD` query, `tftp://` protocol seems to work just fine, so could you please see why it issues this `HEAD` query.

**Comment by sethvargo** [comment]
Hi @borgand 

Vagrant needs to uses a `HEAD` request to check for the existence of a box before attempting to download.

**Comment by borgand** [comment]
Could you just skip `HEAD` in case of `tftp://` protocol as TFTP can only read and write files and nothing more. If file does not exist, `curl` would error out as it would if the transfer got interrupted.

**Comment by borgand** [comment]
Off topic, but I wouldn't look at TFTP, if I could get `scp://` URL working, but for some reason the embedded `curl` refuses to read host keys from `~/.ssh/known_hosts`  (both under Arch Linux and a different Ubuntu box). Should this be working?
