### ISSUE TITLE
Docker provider does not support Docker 1.5.0 named Dockerfiles

### ISSUE THREAD

**Issue by duro** [mitchellh/vagrant#5480]
I am trying to make use of the new Docker 1.5.0 API, which includes the ability to specify a file name for your Dockerfile.

I tried the following setup:

```
v.vm.provider "docker" do |d|
  d.vagrant_machine = ENV["DOCKER_HOST_VAGRANT_NAME"]
  d.vagrant_vagrantfile = ENV["DOCKER_HOST_VAGRANT_FILE"]
  d.build_dir = "."
  d.build_args = ['--file="Local.Dockerfile"', '--tag="duro/zg-site"']
  d.env = { :SITE_HOSTNAME => 'docker.local' }
  d.remains_running = true
  d.ports = ["8003:8003", "8383:8383", "5353:5353"]
end
```

And I keep getting the following error:

```
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: "docker" "build" "--file="\""Local.Dockerfile"\""" "--tag="\""duro/zg-site"\""" "/mnt/docker_build_94047711e92b3c58cebff8ff0211cb32"

Stderr: time="2015-03-13T21:49:23Z" level="fatal" msg="The Dockerfile (Local.Dockerfile) must be within the build context (/mnt/docker_build_94047711e92b3c58cebff8ff0211cb32)" 
```

However, when I run the following docker command manually

```
docker build -f Local.Dockerfile -t duro/zg-site .
```

Everything works just fine.

**Comment by duro** [comment]
I have done some further investigation on this. The problem is that the ``--file` flag needs an absolute path to the Dockerfile. Vagrant executes the `docker build` command outside of the mounted project root. As far as I am aware, there is no way to get the project root into those arguments.

So I would propose that an additional configuration attribute is needed on the provider itself. We need a `d.dockerfile` property that will append the mounted project root to the argument.

Thoughts?

**Comment by duro** [comment]
I have created PR #5482 for this.

**Comment by mitchellh** [comment]
Fixed by your PR. Thanks!
