### ISSUE TITLE
Vagrant SMB do nothing with admin privilege

### ISSUE THREAD

**Issue by coolfarmer** [mitchellh/vagrant#5481]
Hi,

This will make me crazy, 2 days I passed to search a solution but without success :/
My need is to mount my box with SMB because Symfony2 has too many files for basic synched folders.

When I launch my Windows prompt in admin privilege and run vagrant reload to boot my VM, these rows appear : 

```text
C:\vagrant\puphpet\vm1>vagrant reload
==> default: Checking if box 'puphpet/centos65-x64' is up to date...
==> default: A newer version of the box 'puphpet/centos65-x64' is available! You currently
==> default: have version '1.2'. The latest is version '2.0'. Run
==> default: `vagrant box update` to update.
```

![2015-03-13 20-20-25](https://cloud.githubusercontent.com/assets/4965519/6649477/5b5afe98-c9c1-11e4-8dcf-78f6ce372232.jpg)

It's all ... :(
Normally I should receive a prompt to enter my username/password ?
No error, no message, nothing to help me to fix this problem.

My vagrant version is 1.7.2 (same problem with 1.6.3).
My virtualbox version is 4.3.12.
On Windows 7.

The box work fine with basic synched folder.
Thanks if you have an idea about my weird problem.

**Comment by sethvargo** [comment]
Hi @coolfarmer 

I am sorry you are having problems with Vagrant. Can you please run the reload command with debug mode activated and send the output in a Gist?

**Comment by coolfarmer** [comment]
Hi @sethvargo,

Thanks first for your answer, it's very appreciated.
Here is my gist : https://gist.github.com/coolfarmer/8f9f17a8b35a59a75a2c

I don't have found the solution, I hope you can tell me anything I don't already see on google. :)

**Comment by mitchellh** [comment]
Hey @coolfarmer it appears that this command is hanging:

```
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "$PSVersionTable.PSVersion.Major"]
```

We made a lot of changes in 1.8 for how PowerShell is executed. Can you give this a shot with 1.8 (coming out soon) and if the problem persists please reopen. Thanks!
