### ISSUE TITLE
vagrant login not showing token option?

### ISSUE THREAD

**Issue by knappe** [mitchellh/vagrant#5489]
I'm having trouble with the token option.

```
Tylers-MacBook-Air:devbox knappe$ vagrant -v
Vagrant 1.7.2
Tylers-MacBook-Air:devbox knappe$ vagrant login -h
Usage: vagrant login

    -c, --check                      Only checks if you're logged in
    -k, --logout                     Logs you out if you're logged in
    -h, --help                       Print this help
Tylers-MacBook-Air:devbox knappe$
```

I'm not seeing the `token` option shown in the docs http://docs.vagrantup.com/v2/cli/login.html.

I've also exported the `ATLAS_TOKEN` and can't login that way either.

**Comment by sethvargo** [comment]
Hi @knappe 

We accidentally deployed the Vagrant docs too early. That option is only currently available in master. I'm really sorry about that. If you export `ATLAS_TOKEN` the vagrant login command will show you as unauthenticated, but you should be able to access private resources. Can you confirm?

**Comment by knappe** [comment]
I'm afraid not.  Even when I export the `ATLAS_TOKEN` and attempt to do a `vagrant login`, I am not able to authenticate and it tells me to export the `ATLAS_TOKEN` env var due to the 2 factor authentication I have enabled on the account.

**Comment by sethvargo** [comment]
@knappe did you create an Atlas token via the Atlas web ui? If so, you can just manually set the token until we release a new Vagrant with these fixes:

```shell
echo $ATLAS_TOKEN > ~/.vagrant.d/data/vagrant_login_token
```

Does that work for you?

**Comment by knappe** [comment]
I'll try to give this a shot later today.

Does it not work if you just setup a local environment variable?  Is it specifically looking for the token in  `vagrant_login_token`?

**Comment by knappe** [comment]
@sethvargo, no luck.  I doubled checked `~/.vagrant.d/data/vagrant_login_token` and the token is correct.

```
Tylers-MacBook-Air:~ knappe$ echo $ATLAS_TOKEN > ~/.vagrant.d/data/vagrant_login_token
Tylers-MacBook-Air:~ knappe$ vagrant login
In a moment we will ask for your username and password to HashiCorp's
Atlas. After authenticating, we will store an access token locally on
disk. Your login details will be transmitted over a secure connection, and
are never stored on disk locally.

If you do not have an Atlas account, sign up at
https://atlas.hashicorp.com.

Atlas Username: <username>
Password (will be hidden):
The Atlas server responded with an not-OK response:

Two-factor authentication is enabled! Atlas does not support creating
access tokens via the API when the user has two-factor authentication
enabled. Please create an access token using the Atlas website and store
the result in the 'ATLAS_TOKEN' environment variable.
```

**Comment by kmark** [comment]
I can confirm that the `ATLAS_TOKEN` environment variable login method is not working on Windows 7. I've set the variable both manually and through the Windows environment variables dialog. I've also set the `vagrant_login_token` file to no effect.

**Comment by mitchellh** [comment]
Fixed

**Comment by tbarbe** [comment]
Is this issue back again? Ubuntu latest 1.9.5 - I get this:

The Atlas server responded with an not-OK response:

```
Two-factor authentication is enabled! Atlas does not support creating
access tokens via the API when the user has two-factor authentication
enabled. Please create an access token using the Atlas website and store
the result in the 'ATLAS_TOKEN' environment variable.

```

I have exported the ATLAS_TOKEN var and I see it in the vagrant.d
