### ISSUE TITLE
Docker provisioning doesn't work on Windows

### ISSUE THREAD

**Issue by galkinrost** [mitchellh/vagrant#5490]
In continuation of <a href="https://github.com/mitchellh/vagrant/issues/4613">#4613</a> I created <a href="https://github.com/galkinrost/vagrant-issue">repo</a>, which allows to reproduce  error occurred on Windows

**Comment by chrisroberts** [comment]
Running `vagrant up` using the provided example repository on a windows host produced no errors and the VM was successfully provisioned using docker. As I am unable to produce the original error, I am assuming it was either resolved internally within vagrant, or within docker or the container being used.

@galkinrost If this is still an issue for you, please let me know! Thanks!
