### ISSUE TITLE
Vagrant ssh failed since the network segment changed

### ISSUE THREAD

**Issue by WilsonFpz** [mitchellh/vagrant#5491]
I am using vagrant for a long time.

Recently our office has moved to a new place, the network segment has changed from 192.168.10.x to 192.168.1.x.

Since then, the command vagrant ssh failed. And when I tried vagrant up again,

it shows

```
default: SSH address: 127.0.0.1:2222
default: SSH username: vagrant
default: SSH auth method: private key
default: Warning: Connection timeout. Retrying...
default: Warning: Connection timeout. Retrying...
default: Warning: Connection timeout. Retrying...
default: Warning: Connection timeout. Retrying...
default: Warning: Connection timeout. Retrying...
default: Warning: Connection timeout. Retrying...
default: Warning: Connection timeout. Retrying...
```
But when I turned off the wireless in my OSX. All vagrant commands works fine. And it failed again when I turned on the network.

Could some one give me some hint to solve this issue? Thanks.

**Comment by sethvargo** [comment]
Hi @WilsonFpz 

Could you please share your Vagrantfile and the result of the command when running in debug mode? Thanks!

**Comment by mitchellh** [comment]
This is very likely because the VirtualBox default network is overlapping with your office network. You can fix this by reconfiguring VirtualBox (Vagrant doesn't do this for the NAT one).
