### ISSUE TITLE
SMB issue with chef_solo

### ISSUE THREAD

**Issue by z0c** [mitchellh/vagrant#5494]
We are trying to use chef_solo to provision a windows client using the Rackspace provider but running into the following issue:
```
==> default: Mounting SMB shared folders...
We couldn't detect an IP address that was routable to this machine from the guest machine! Please verify networking is properly setup in the guest machine and that it is able to access this host.

As another option, you can manually specify an IP for the machine to mount from using the 'smb_host 'option to the synced folder.
```

The problem will be that Vagrant cant auto detect our office IP. We are able use the 'smb_host' option on synced_folders as a work around, but the chef_solo provision does no appear to support this option.

We were able to get it to work using this [commit on digital11/vagrant fork](https://github.com/digital11/vagrant/commit/ec928af12aa3bf13d1bf0d22f050a629d9656706), but wandering if there's something we are missing here

Versions are:
Vagrant 1.7.2 
Host Windows 8.1
Client Windows 2012 R2

**Comment by varundmishra** [comment]
I am having the same issue, I tried using the commit above but its not working?
Can you please elaborate how did you get it working??

**Comment by z0c** [comment]
just did the changes in the commit and then was able to add the default_host in my Vagrantfile as follow

```Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  Vagrant.require_version ">= 1.6"
  config.smb.default_host = "1.2.3.4" # Your external ip
```

**Comment by mitchellh** [comment]
This is related to a 3rd party provider. It looks like it isn't setting the SMB IP properly in the internal state. Please point them to this comment and open an issue with them!
