### ISSUE TITLE
plugin code loading on initial vagrant up

### ISSUE THREAD

**Issue by cloudnautique** [mitchellh/vagrant#5498]
In order to get something working quickly, I needed a bit of code to configure network for a new OS. I have been using Packer to build the base box and include a Vagrantfile which `require_relative 'plugin.rb'` that is also included. The box is then packaged and shipped up to Atlas. 

When I do a Vagrant up and the box is not present, meaning it has to be downloaded from Atlas, the plugin does not run. If I do a `vagrant reload` or `vagrant destroy -f && vagrant up` it works fine and as expected. 

Has anyone seen an issue like this? 

The behavior is observed on multiple machines.

**Comment by cloudnautique** [comment]
For more info:

Vagrantfile included with box:
```
require_relative "vagrant_rancheros_guest_plugin.rb"
Vagrant.configure(2) do |config|
    config.ssh.username = "rancher"

    config.vm.provider :virtualbox do |vb|
        vb.check_guest_additions = false
        vb.functional_vboxsf = false
    end
end
```

contents of downloaded box directory:
```
Vagrantfile					packer-virtualbox-iso-1426692185-disk1.vmdk
box.ovf						vagrant_rancheros_guest_plugin.rb
metadata.json
```

Project Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# To enable rsync folder share change to false
$rsync_folder_disabled = true
$number_of_nodes = 1
$vm_mem = "1024"


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box   = "rancherio/rancheros"
  config.vm.box_version = ">=0.1.2"

  (1..$number_of_nodes).each do |i|
    hostname = "rancher-%02d" % i

    config.vm.define hostname do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.memory = $vm_mem
            vb.gui = true
        end

        ip = "172.19.8.#{i+100}"
        node.vm.network "private_network", ip: ip

        # Disabling compression because OS X has an ancient version of rsync installed.
        # Add -z or remove rsync__args below if you have a newer version of rsync on your machine.
        node.vm.synced_folder ".", "/opt/rancher", type: "rsync",
            rsync__exclude: ".git/", rsync__args: ["--verbose", "--archive", "--delete", "--copy-links"],
            disabled: $rsync_folder_disabled

    end
  end
end
```

**Comment by cloudnautique** [comment]
Any ideas?

**Comment by sethvargo** [comment]
HI @cloudnautique 

Can you please share the contents of the `vagrant_rancheros_guest_plugin.rb`?

**Comment by cloudnautique** [comment]
@sethvargo the plugin source is here in [rancherio/os-vagrant](https://github.com/rancherio/os-vagrant/blob/master/vagrant_rancheros_guest_plugin.rb). 

I was trying to embed it into the Vagrantfile packaged inside the box, but had to move it out because it wasn't being sourced. Makes for a less then desirable user experience. 

Let me know if you need any other info.

**Comment by mitchellh** [comment]
Vagrant now has a hidden feature for backwards compat, but we don't intend to support this. You can specify a ".vagrantplugins" file and it will load that.
