### ISSUE TITLE
Accidentally executing vagrant commands as root in a user directory will purge .vagrant file structure

### ISSUE THREAD

**Issue by averas** [mitchellh/vagrant#5499]
Perhaps a feature rather than a bug, but sure got me a little upset..

I had a root shell open (OSX) and executed 'vagrant status' in a development directory belonging to my regular user. This purged the entire .vagrant file structure and just reported that the machine wasn't setup.

Vagrant 1.7.2 on OSX.

**Comment by sethvargo** [comment]
Tagging this as core + docs, since I think we just need to update the education surrounding this.

**Comment by derek-adair** [comment]
Where is the relevant reading on this?

**Comment by sethvargo** [comment]
@derek-adair there isn't any, that's why it's tagged docs :smile:

**Comment by derek-adair** [comment]
HA, ok i partially commented to make this a bit more visible (i'm already watching the repo).  I'm  intrigued!

**Comment by averas** [comment]
@sethvargo Do you really think documentation on the subject is enough? Personally I started looking for the documentation _after_ it happened, not before. :-)

Perhaps seems a bit odd to me that commands such as 'vagrant status' and 'vagrant ssh' can cause a complete purge, regardless of whichever user invokes them.

**Comment by derek-adair** [comment]
That's a pretty good point and why I am intrigued to look at what the reasoning behind this may be.  Seems like it would make sense to prompt for confirmation on deleting it.  Personally I treat all of my VMs as disposable so I am not affected directly by this, but i can see how this would be a major bummer.

**Comment by smw** [comment]
It's very non-intuitive that status would ever be a destructive command.

This takes quite a bit of time to recover from, as well, as the user must go manually shutdown boxes using VBoxManage and then delete the disk files to recover space.  

Either that or try to reverse engineer and manually rebuild the files in the .vagrant/ directory.

**Comment by mitchellh** [comment]
This is fixed!
