### ISSUE TITLE
Improvement on how to remove cached rsync entries

### ISSUE THREAD

**Issue by dannymacom** [mitchellh/vagrant#5502]
My steps:
1. Created a Vagrantfile with a rsync config
2. Through trial and error make changes to the rsync config 2 times
3. On the third time I got the correct path/permissions

The entry reads as:

```ruby
Vagrant.configure("2") do |config|
  config.vm.synced_folder "/Users/geneparmesean/Documents/web/super", "/var/www/html/duper",
    type: "rsync",
    owner: "nginx",
    group: "nginx",
    rsync__exclude: ".git/"
end
```

However on using vagrant rsync-auto I get this result showing the previous two attempts:

```text
DMCDERMOTT-IMAC:LANSIBLE geneparmesean$ vagrant rsync-auto
==> default: Doing an initial rsync...
==> default: Rsyncing folder: /Users/geneparmesean/Documents/web/super/ => /var/www/html/duper2
==> default:   - Exclude: [".vagrant/", ".git/"]
==> default: Rsyncing folder: /Users/geneparmesean/Documents/web/super/ => /var/www/html/duper
==> default:   - Exclude: [".vagrant/", ".git/"]
==> default: Rsyncing folder: /Users/geneparmesean/Documents/web/max/ => /var/www/html/payne2
==> default:   - Exclude: [".vagrant/", ".git/"]
==> default: Watching: /Users/geneparmesean/Documents/web/max
==> default: Watching: /Users/geneparmesean/Documents/web/super
==> default: Watching: /Users/geneparmesean/Documents/web/super
```

Obviously I can easily go into the 'synced_folders' file and delete the extra entries, but I would suggest that the code automagically remove the additional entries created upon initiating of the rsync-auto command. 

Thanks!

**Comment by sethvargo** [comment]
Hi @dannymacom 

Thank you for opening an issue. You will need to run `vagrant reload` after changing the synced folder settings and the old entires will be purged. Thanks! :smile:
