### ISSUE TITLE
WinRM Provisioning elevated_shell has a fixed 2 hour timeout

### ISSUE THREAD

**Issue by nscaife** [mitchellh/vagrant#5506]
When `privileged: false` is not specified on a shell provision, Vagrant installs a Windows scheduled task in order to execute the script with elevated permissions.  This task has a fixed timeout of two hours, which is insufficient for large provisioning processes.  Can this be made configurable?

The fixed timeout is located in [elevated_shell.ps1.erb:38](https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/winrm/scripts/elevated_shell.ps1.erb#L38).

**Comment by tkelman** [comment]
Been hitting this, upgraded to 1.7.4 recently and no change. Pretty aggravating. I guess I can split up my provisioning into a short privileged section and a long non-privileged section, but a nicer workaround would be appreciated.

**Comment by matthewcodes** [comment]
We are also seeing this issue, @jrob fix looks really useful and should be merged asap.

**Comment by mitchellh** [comment]
This is fixed in #6213
