### ISSUE TITLE
 /etc/sudoers.d/vagrant and ONBOOT=false

### ISSUE THREAD

**Issue by oculushut** [mitchellh/vagrant#5511]
Hi, I am trying to build a CentOS 7 box and finding the following behaviour:

a) After packaging, the  */etc/sudoers.d/vagrant* file which initially contained the following line:

> Defaults:vagrant !requiretty

...loses that line automatically...

b) The */etc/sysconfig/network-scripts/ifcfg-enp0s3* file which initially contained the following line:

> ONBOOT=yes

...has ONBOOT=no if somebody vagrant init/up's my package.box.

Is this normal and is it preventable?

Thanks!

**Comment by oculushut** [comment]
Here's some info on the box I was trying to build: http://www.oculushut.com/blog/janus-presence-server-part-2/  The box is downloadable on Atlas here: https://atlas.hashicorp.com/oculushut/boxes/vagrant-centOS64-oculushut

**Comment by sethvargo** [comment]
Hi @oculushut 

I am sorry you are having issues. Could you please run the command again in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html) and Gist the output?

By chance, do you have selinux enabled? I have seen this type of strange behavior when selinux is present on a machine.

**Comment by oculushut** [comment]
Output from vagrant up in debug mode, vagrantfile and selinux status here: https://gist.github.com/oculushut/377fa6b6c6ac2b873953

**Comment by oculushut** [comment]
I did a few things... not sure if this helps clarify things or clouds the issue.  Firstly, I have not tried to replicate the original problem yet (I may go back and do this later).  What I did do was:

1. Created a VM using vagrant up and requesting the box from Atlas (v0.0.1)
2. Updated SELinux setting
3.  Packaged another box and uploaded it as v0.0.2
4.  Edited vagrant file to:
<pre>
 => Constrained to version 0.0.2
=> Did not include this time: config.ssh.insert_key = false
=> GUI mode uncommented
</pre>
5.  vagrant up'd and it works seemingly without errors...

vagrantfile and successful output can be found here: https://gist.github.com/oculushut/456f2d8da529acbc5765

I'll post info back up here if I get a chance to an attempt a replication.

**Comment by mitchellh** [comment]
Vagrant shouldn't automatically remove the `requiretty`. Something else is doing that.

As for the network configs: this sounds right, Vagrant configures networks in an opinionated way. You can tell it not to by specifying `auto_config: false` on network configurations. But this requires you to manually do it (which may be what you want).
