### ISSUE TITLE
The vagrant destroy can't remove Vbox host-only adapter

### ISSUE THREAD

**Issue by Jonasyao** [mitchellh/vagrant#5529]
```
10: vboxnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.50.1/24 brd 192.168.50.255 scope global vboxnet0
       valid_lft forever preferred_lft forever
    inet 192.168.56.101/24 brd 192.168.56.255 scope global dynamic vboxnet0
       valid_lft 956sec preferred_lft 956sec
    inet6 fe80::800:27ff:fe00:0/64 scope link 
       valid_lft forever preferred_lft forever
11: vboxnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 0a:00:27:00:00:01 brd ff:ff:ff:ff:ff:ff
[pandala@localhost bad]$ sudo  VBoxManage hostonlyif remove vboxnet1
```

The vagrant destroy can't remove previous VM's network adapter if vagrant halt is not applied before vagrant destroy.

**Comment by sethvargo** [comment]
Hi @Jonasyao 

Can you please provider more information? Are you able to provide a `Vagrantfile` with a reproduction case? Can you provide any [debug output](http://docs.vagrantup.com/v2/other/debugging.html).

**Comment by mitchellh** [comment]
Closing due to lack of response. 

But this is correct: we don't remove the network because we can't reliably see who is still using it. We prune networks at other times when we know it is safe.
