### ISSUE TITLE
Cannot mount folder over NFS with VMware provider due to wrong IP

### ISSUE THREAD

**Issue by gmalkas** [mitchellh/vagrant#5530]
Hi,

I am trying to setup a shared folder over NFS with the VMware provider but I can't get it to use the correct IP for my host (OS X host, Ubuntu 14.04 guest).

Here is the network configuration from my Vagrantfile:
```ruby
config.vm.network "private_network", ip: "172.16.42.42", :netmask => "255.0.0.0"
```
Here is the host network configuration:
```
vmnet2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 00:50:56:c0:00:02 
	inet 172.0.0.1 netmask 0xff000000 broadcast 172.255.255.255
```
I've tried manually mounting the NFS folder from the guest using `172.0.0.1` and it works as expected.

After running `vagrant up --debug`, it appears vagrant uses `172.16.42.1` as the host IP when trying to mount the folder over NFS, which is obviously wrong, but I have absolutely no idea why it uses this particular IP.

Any idea?

Thank you.

**Comment by gmalkas** [comment]
It works without specifying a private network. It seems like there might be an issue with the netmask option with vmware?

**Comment by blopker** [comment]
Think I'm getting the same issue:

```bash
NFS requires a host-only network to be created.
Please add a host-only network to the machine (with either DHCP or a
static IP) for NFS to work.
```

Vagrantfile
```ruby
Vagrant.configure("2") do |config|
	config.vm.box = "chef/ubuntu-14.04"

	# Set up port forwarding. Change the host: port if you have a conflict.
	config.vm.network "forwarded_port", guest: 8000, host: 8000
	config.vm.synced_folder ".", "/vagrant", type: "nfs"

	# Run provisioning
	config.vm.provision "shell" do |s|
		s.privileged = false
		s.path = "etc/install.sh"
	end

	# Run Vagrant only provisioning
	config.vm.provision "shell" do |s|
		s.privileged = false
		s.path = "etc/vagrant.sh"
	end
end
```

**Comment by inconshreveable** [comment]
Yep, I can confirm the same issue. Seems like vagrant's vmware provider treats it as if the network mask is always 255.255.255.0.

**Comment by gmalkas** [comment]
Upgrading to the latest plugin (3.2.6) solved the issue for me. Thanks!
