### ISSUE TITLE
`vagrant package --base` fails with default insecure key

### ISSUE THREAD

**Issue by kmark** [mitchellh/vagrant#5541]
After applying the workaround in #5310 I've run into another issue when trying to package a Debian 7.8 + VirtualBox 4.3.26 instance.

Vagrant 1.7.2, Mac OS X 10.10.2 (although I can reproduced `package --base` errors on Windows 7 too)

A non-debug log:
```
Klingon:boxes kmark$ vagrant package --base debian78-x64
==> debian78-x64: Attempting graceful shutdown of VM...
    debian78-x64: 
    debian78-x64: Vagrant insecure key detected. Vagrant will automatically replace
    debian78-x64: this with a newly generated keypair for better security.
    debian78-x64: 
    debian78-x64: Inserting generated public key within guest...
    debian78-x64: Removing insecure key from the guest if its present...
    debian78-x64: Key inserted! Disconnecting and reconnecting using new SSH key...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
vagrant@127.0.0.1's password:
```

What seems to be happening is that it's connecting to the box with the insecure key I have set up. It's then replacing this key with a new one as it does for newly initialized boxes. Sometimes this part fails as well with an `RSAError` nearly identical to #5056. After the replace it reconnects to SSH. However it's still using the default insecure private key. Since it has replaced the public key on the box it can no longer connect that way, forcing me to enter a password.

From my understanding it should not be replacing the insecure key at all when packaging since Vagrant expects that key to be used when provisioning the box. It's how boxes can be quickly and automatically provisioned from public places like Atlas, if I remember correctly.

Here's a snippet of the debug log that supports my hypothesis.

**Initial Connection**
```
DEBUG virtualbox_4_3:   - [1, "Rule 1", 2222, 22]
DEBUG ssh: Checking key permissions: /Users/kmark/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 127.0.0.1
 INFO ssh:   - Port: 2222
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/Users/kmark/.vagrant.d/insecure_private_key"]
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2015-03-30T20:11:24.324027 #3199] DEBUG -- net.ssh.transport.session[805de834]: establishing connection to 127.0.0.1:2222
D, [2015-03-30T20:11:24.324997 #3199] DEBUG -- net.ssh.transport.session[805de834]: connection established
--- SNIP ---
net.ssh.authentication.methods.publickey[806120a8]: publickey succeeded

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: Exit status: 0
```

**Reconnection**
Notice the same default private key except we've already replaced the public key on the box.
```
DEBUG virtualbox_4_3:   - [1, "Rule 1", 2222, 22]
DEBUG ssh: Checking key permissions: /Users/kmark/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 127.0.0.1
 INFO ssh:   - Port: 2222
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/Users/kmark/.vagrant.d/insecure_private_key"]
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
vagrant@127.0.0.1's password:
 INFO interface: warn: Waiting for cleanup before exiting...
 INFO interface: warn: ==> debian78-x64: Waiting for cleanup before exiting...
==> debian78-x64: Waiting for cleanup before exiting...
 INFO interface: error: Exiting immediately, without cleanup!
 INFO interface: error: ==> debian78-x64: Exiting immediately, without cleanup!
==> debian78-x64: Exiting immediately, without cleanup!
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2015-03-30T20:11:25.234419 #3199] DEBUG -- net.ssh.transport.session[8056ef20]: establishing connection to 127.0.0.1:2222
D, [2015-03-30T20:11:25.235005 #3199] DEBUG -- net.ssh.transport.session[8056ef20]: connection established
--- SNIP ---
D, [2015-03-30T20:11:25.253171 #3199] DEBUG -- net.ssh.authentication.session[8050a8f4]: beginning authentication of `vagrant'
--- SNIP ---
D, [2015-03-30T20:11:25.255900 #3199] DEBUG -- net.ssh.authentication.session[8050a8f4]: allowed methods: publickey,password
D, [2015-03-30T20:11:25.255987 #3199] DEBUG -- net.ssh.authentication.methods.none[805035f4]: none failed
D, [2015-03-30T20:11:25.256074 #3199] DEBUG -- net.ssh.authentication.session[8050a8f4]: trying publickey
--- SNIP ---
D, [2015-03-30T20:11:25.257436 #3199] DEBUG -- net.ssh.authentication.methods.publickey[804fe4b4]: trying publickey
--- SNIP ---
D, [2015-03-30T20:11:25.259197 #3199] DEBUG -- net.ssh.authentication.session[8050a8f4]: allowed methods: publickey,password
D, [2015-03-30T20:11:25.259256 #3199] DEBUG -- net.ssh.authentication.session[8050a8f4]: trying password
DEBUG ssh: == Net-SSH connection debug-level log END ==
```

**Comment by kmark** [comment]
I don't know why I didn't try this before. The SSH key problems I noted above can be avoided by shutting down the VM first. I had more annoying `RSAError` issues but after reinstalling Vagrant it seemed to go away.

**Comment by eldondev** [comment]
Shutting down manually does circumvent this, but it still seems strange to have `vagrant package` explicitly replace the insecure key before shutting down the box to package it.

**Comment by tj** [comment]
+1, not sure if these are documentation issues or what, but it seems tricky to set up a base box with 1.7.x

**Comment by Jakobud** [comment]
I am still running into this issue on Windows. I took an existing box from Hashicorp (relativkreativ/centos-7-minimal), added some software to it (git, nginx, mysql, etc) then shutdown the instance `vagrant halt` then did `vagrant package`. 

I created a new instance using my new package and during bootup it says:
```
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
vagrant@127.0.0.1's password:
```

What am I doing wrong here? Why am I getting this?

**Comment by ja1979** [comment]
In my case it was resolved by removing SSH port forwarding configuration in VirtualBox.

**Comment by ja1979** [comment]
In my case it was resolved by removing SSH port forwarding configuration in VirtualBox.

**Comment by ja1979** [comment]
In my case it was resolved by removing SSH port forwarding configuration in VirtualBox for the base VM.

**Comment by mitchellh** [comment]
Fixed!
