### ISSUE TITLE
vagrant push to atlas / packer file provisioner flattens tree structure on Windows

### ISSUE THREAD

**Issue by mkdeddens** [mitchellh/vagrant#5542]
Refer my question [here](http://stackoverflow.com/questions/29363516/how-to-get-vagrant-push-packer-file-provisioning-to-respect-the-directory-stru)

I am succesfully following the [atlas getting started example](https://atlas.hashicorp.com/help/getting-started/getting-started-overview) from the help docs. But when extending the app directory with sub directories and files in them I do not see the expected end-result provisioned on my AWS AMI. Sub directories are becomming file names with backslashes in them, instead of actual directories holding the files:

Given the following structure in my app directory:

	app
	 |-- Vagrantfile
	 |-- index.html
	 |-- img
	      |-- image.jpg

Printing out a directory listing of /var/www/html at the end of the shell provisioner shows me the following:

    $ find /var/www/html -printf '%m %u\t%g\t%t\t%p\n'
    amazon-ebs: 755 www-data	www-data	Tue Mar 31 06:55:10.0513005999 2015	/var/www/html
    amazon-ebs: 644 www-data	www-data	Tue Mar 31 06:55:10.0513005999 2015	/var/www/html/index.html
    amazon-ebs: 644 www-data	www-data	Tue Mar 31 06:55:10.0513005999 2015	/var/www/html/img\image.jpg
    amazon-ebs: 644 www-data	www-data	Tue Mar 31 06:55:10.0513005999 2015	/var/www/html/Vagrantfile

It seems the `img` directory is not created as such, but the nested file `image.jpg` gets named as `img\image.jpg` and put in the root of `/var/www/html`.

This is proven by visiting `http://my-terraform-example-elb-<some ID>.eu-west-1.elb.amazonaws.com/img%5Cimage.jpg`. This renders the image as an image.

On inspecting the structure of `/tmp/app` straight after upload (by packer file provisioner, so straight after `sleep 30` in `example-template.json`), the same is appearing; no subdirectories are created, files are just named like `/tmp/app/level1\level2\file.ext`.

**example-template.json:**

	{
		"builders": [{
			"type": "amazon-ebs",
			"access_key": "<my aws key>",
			"secret_key": "<my aws secret>",
			"region": "eu-west-1",
			"source_ami": "ami-55a23a22",
			"instance_type": "t1.micro",
			"ssh_username": "ubuntu",
			"ami_name": "atlas-example {{timestamp}}"
		}],
		"push": {
		  "name": "myusername/my-example-build-conf"
		},
		"provisioners": [
			{   
				"type": "file",
				"source": "/packer/app",
				"destination": "/tmp"
			},
			{
				"type": "shell",
				"inline": [
					"sleep 30",
					"sudo apt-get update",
					"sudo apt-get -y install apache2",
					"sudo rm -r /var/www/html/*",
					"sudo cp -R /tmp/app/* /var/www/html/",
					"sudo find /var/www/html -print0 | xargs -0 sudo chown www-data:www-data",
					"sudo find /var/www/html -type d -print0 | xargs -0 sudo chmod 755",
					"sudo find /var/www/html -type f -print0 | xargs -0 sudo chmod 644",
				]
			}
		],
		"post-processors": [{
			"type": "atlas",
			"artifact": "myusername/my-example-artifact",
			"artifact_type": "aws.ami",
			"metadata": {
				"created_at": "{{timestamp}}"
			}
		}]
	}

**Vagrantfile:**

    config.push.define "atlas" do |push|
      push.app = "myusername/my-example-app"
      push.vcs = false
    end

Version info:

    $ vagrant -v
    Vagrant 1.7.2

    $ packer version
    Packer v0.7.5

    $ terraform version
    Terraform v0.3.7

Note: I am working from a Windows 8.1 machine (thats from where I run `vagrant push`, `packer push` and `terraform apply`).

**Comment by mkdeddens** [comment]
To append: I tried running this from a local packer build command with below configuration, this worked out just fine. Seems the problem is before packer file provisioner, either at vagrant push or atlas storage.

Command: `packer build example-template.json`

Result: sub directories and files created in /var/www/html/

**example-template.json**

    {
        "builders": [{
            "type": "amazon-ebs",
            "access_key": "<my aws key>",
            "secret_key": "<my aws secret>",
            "region": "eu-west-1",
            "source_ami": "ami-55a23a22",
            "instance_type": "t1.micro",
            "ssh_username": "ubuntu",
            "ami_name": "atlas-example {{timestamp}}"
        }],
        "push": {
          "name": "myusername/my-example-build-conf"
        },
        "provisioners": [
        {   
            "type": "file",
            "source": "../app",
            "destination": "/tmp"
        },
        {
            "type": "shell",
            "inline": [
                "sleep 30",
                "sudo apt-get update",
                "sudo apt-get -y install apache2",
                "sudo rm -r /var/www/html/*",
                "sudo cp -R /tmp/app/* /var/www/html/",
                "sudo find /var/www/html -print0 | xargs -0 sudo chown www-data:www-data",
                "sudo find /var/www/html -type d -print0 | xargs -0 sudo chmod 755",
                "sudo find /var/www/html -type f -print0 | xargs -0 sudo chmod 644"
            ]
        }],
        "post-processors": [
          {
            "type": "atlas",
            "artifact": "myusername/my-example-artifact",
            "artifact_type": "aws.ami",
            "metadata": {
              "created_at": "{{timestamp}}"
            }
          }]
    }

**Comment by chrisroberts** [comment]
The `atlas-upload-cli` that generates the archive and pushes the slug includes an update via one of its dependencies that properly re-formats windows path separators, fixing this issue. The latest version of vagrant should upload as expected. Thanks for the report!
