### ISSUE TITLE
Shell provisioner using file on windows host not converting CRLF to LF - documentation fix?

### ISSUE THREAD

**Issue by gmanfunky** [mitchellh/vagrant#5543]
When using a script from a file with the shell provisioner, it is not converting line endings from CRLF to LF as described in the documentation: http://docs.vagrantup.com/v2/provisioning/shell.html (see binary).

This seem extra annoying because git on windows defaults to CRLF for pulled files. 

```
config.vm.provision :shell, :path => "provision-test.sh"
```

Maybe this feature stopped working after some changes to how files are delivered to the guest?

**Comment by mitchellh** [comment]
This has been fixed!
