### ISSUE TITLE
Please push tagged versions to rubygems

### ISSUE THREAD

**Issue by hashar** [mitchellh/vagrant#5546]
Rubygems is stalled to version 1.5.0: https://rubygems.org/gems/vagrant

There are much more releases tagged https://github.com/mitchellh/vagrant/releases

In our Gemfile, we end up having to use the git repo:

    gem 'vagrant', git: 'https://github.com/mitchellh/vagrant.git', tag: 'v1.7.2'

I would rather use a version from rubygems.

**Comment by sethvargo** [comment]
Hi @hashar 

The recommended way to install Vagrant is via the official installers, and the recommended way to create plugins is by locking bundler to a tag.

I have made an internal note to push new versions to Rubygems, however, so we will try to be extra conscious of that for future releases. Thank you for bringing it to our attention.

**Comment by mitchellh** [comment]
Correct, the version in RubyGems is actually not even real: it is a stub that errors that you should use the installer.

**Comment by hashar** [comment]
We will stick to git/tag so. Thanks for the clarification.

For later reference we ended up doing:

    gem 'vagrant', git: 'https://github.com/mitchellh/vagrant.git', tag: 'v1.7.2'
