### ISSUE TITLE
s

### ISSUE THREAD

**Issue by nealstammers** [mitchellh/vagrant#5552]

**Comment by sethvargo** [comment]
Hi @nealstammers 

Could you please elaborate on your issue more please?

**Comment by derek-adair** [comment]
Man you're more patient than me, this would have been insta close/wontfix hahahaha.

**Comment by Elijen** [comment]
@nealstammers I have exactly the same issue! :)

**Comment by nealstammers** [comment]
Apologies @sethvargo - no idea I'd opened an issue (possibly the cat walking on the keyboard) :-/
