### ISSUE TITLE
Folder sharing fails from OS X host fails to Ubuntu guest: mounting failed with the error: Protocol error

### ISSUE THREAD

**Issue by marko-asplund** [mitchellh/vagrant#5553]
Mounting a host filesystem fails in the guest OS:

```
vagrant@TFB-all:~$ sudo mount -t vboxsf -o uid=1000,gid=1000,fmode=777,dmode=777 FrameworkBenchmarks /FrameworkBenchmarks/sbin/mount.vboxsf: mounting failed with the error: Protocol error
```

Here's output from starting up the guest OS with Vagrant:
```
 ✘)✭ ᐅ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8080 => 28080 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
GuestAdditions 4.3.26 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /foo/FrameworkBenchmarks/deployment/vagrant-development
    default: /FrameworkBenchmarks => /foo/FrameworkBenchmarks
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,fmode=777,dmode=777 FrameworkBenchmarks /FrameworkBenchmarks
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant`,fmode=777,dmode=777 FrameworkBenchmarks /FrameworkBenchmarks

The error output from the last command was:

stdin: is not a tty
/sbin/mount.vboxsf: mounting failed with the error: Protocol error
```

Here's my software configuration
* Mac OS X Yosemite (10.10.2).
* VirtualBox 4.3.26 r98988
* Vagrant 1.7.2
  * vagrant-share (1.1.3, system)
  * vagrant-vbguest (0.10.0)
* guest OS: Ubuntu 14.04.2 LTS (64-bit, kernel: 3.13.0-46-generic)

**Comment by suttonj** [comment]
'm getting this same error too, on OS X 10.10.3 with VirtualBox 4.3.26 r98988, using the default shared folder /vagrant (on guest machine).

Neither of the proposed solutions worked (restarting host computer or lowercasing the folder). Is there any plan to fix this, or another solution that might work?

**Comment by mitchellh** [comment]
I haven't been able to reproduce this with basic Vagrantfiles matching similar paths to above and width the same versions of things (perhaps revisions are different). In the past, when I've seen this error, it is often related to the vboxsf kernel module: it isn't loaded, it isn't valid, etc. 

Can you reproduce this with any other folders? I noticed `/vagrant` mounted but the other one didn't. 

Unfortunately I think I'm going to have to ask you to post this up on the VirtualBox issue tracker. They'll request you repro it without Vagrant, which shouldn't be too hard to do  (just show them the synced folders and the mount command).

**Comment by herks** [comment]
For what it's worth, I was getting this error when I had a symlink to /shared_folder in my home directory.  Removing the simlink solved this issue.

Virtualbox 5.0.12
Vagrant 1.81
