### ISSUE TITLE
.vagrant/machines/default/virtualbox/id gets deleted seemingly randomly

### ISSUE THREAD

**Issue by amitailanciano** [mitchellh/vagrant#5555]
I'm not sure how else to explain it, but it seems like every so often the `id` file in `.vagrant/machines/default/virtualbox/id` gets deleted. Consequently, in order to make sure any subsequent `vagrant up`'s don't try to create a whole new box, I have to run `vboxmanage list vms`, grab the id of the existing box, and paste it into a new `id` file.

I have no idea what causes this, I was hoping someone may have some insights, or at least some idea what I can do to try and debug it.

**Comment by sethvargo** [comment]
Hi @amitailanciano 

Can you please share any additional information such as your `Vagrantfile`, operating system, or any [debug output](http://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by mitchellh** [comment]
This should be fixed on master if it is what I think it is. Sorry but witout more repro cases we can't do any better. :)

**Comment by amitailanciano** [comment]
no problem, thanks for looking into it with the little information I gave
