### ISSUE TITLE
:vm cookbook path is broken

### ISSUE THREAD

**Issue by diegows** [mitchellh/vagrant#5557]
There is a feature that I think it's broken. When you specify cookbook paths using the :vm type, the code is adding "/cookbooks" at the end of the path. This breaks some things, for example, I have two paths in my list because I have cookbook and site-cookbooks in my local repository, and when I do

```
 chef.cookbooks_path = [
      [ ":vm", "/vagrant/chef/site-cookbooks" ], 
      [ ":vm", "/vagrant/chef/cookbooks" ] 
    ]
```

Vagrant is running chef using the paths /vagrant/chef/site-cookbooks/cookbooks and /vagrant/chef/cookbooks/cookbooks. I think that doesn't make any sense, if I have an option to specify the path, I don't expect it to be modified.

**Comment by mitchellh** [comment]
I just tried this locally and it worked fine: 

```
==> default: [2015-07-09T20:18:44+00:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /tmp/vagrant-chef/fcc7e8a221aaa54be011731802d9cab3, /foo/cookbooks
```

Vagrantfile:

```
# This Vagrantfile can be used to develop Vagrant. Note that VirtualBox
# doesn't run in VirtualBox so you can't actually _run_ Vagrant within
# the VM created by this Vagrantfile, but you can use it to develop the
# Ruby, run unit tests, etc.

Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-12.04"

  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = ["cookbooks", [:vm, "/foo/cookbooks"]]
    chef.add_recipe "foo"
  end
end
```

**Comment by mitchellh** [comment]
Can you show us a way to repro this? Thanks!
