### ISSUE TITLE
Vagrant SSH on windows

### ISSUE THREAD

**Issue by thenoid** [mitchellh/vagrant#5559]
Trying to use 'vagrant ssh' to ssh into virtual box, on windows 7.  Using mobaxterm (which uses a cygwin environment under the hood).

Can just use 'ssh' from inside the terminal and everything works okay.

https://gist.github.com/thenoid/060ca192a4f6e4736666

**Comment by thenoid** [comment]
Trying to unwind this error on my own, i found that it's finding the ssh binary properly in the path, but then when it hands it off to the Subprocess.execute is when it explodes.  Trying to dig into that and figure out if it spawns a new shell/cmd environment?

I only ask because I've noticed that executing the cygwin binary within cmd/powershell spawns an error about bit compatibility.


C:\Users\rocky>C:\Users\rocky\Documents\MobaXterm\slash\bin/ssh.EXE
This version of C:\Users\rocky\Documents\MobaXterm\slash\bin\ssh.exe is not comp
atible with the version of Windows you're running. Check your computer's system
information and then contact the software publisher.

**Comment by thenoid** [comment]
removing the bash bash script version of ssh.exe and moving one of the real ssh binaries to ssh.exe clears up the issue.  However changing the ssh_path inn lib/vagrant/util/ssh.rb doesn't work, produces a different 'fork' error.

putting -x in the ssh.exe bash script doesn't produce any debug output - guessing because windows cmd.exe doesn't know how to interpret the #!/bin/bash.exe

looking around - i think it might be the same as/similar to: https://github.com/mitchellh/vagrant/issues/5174

**Comment by dswitzer** [comment]
I'm using MobaXterm and seeing the same issue. Would love to get `vagrant ssh` working, so if you figure out the issue, I'd love to know the fix.

**Comment by sethvargo** [comment]
Hi @thenoid 

The recommended way for Vagrant to communicate with Windows machines is via WinRM. This is also recommended by Microsoft. Vagrant has built-in support for WinRM with the `vagrant winrm` command. Does that work for you?

**Comment by brijs** [comment]
Hi @sethvargo - I think in this case, only the host machine (not the guest machine) is running windows. So, I don't think winrm would work.

**Comment by mitchellh** [comment]
Vagrant uses a basic subprocess to execute `ssh.exe`. This will do it outside the context of your shell, typically, so it needs to be a valid Windows executable. Unfortunately the fix in this case seems to be to unwrap it. 

We'll be merging a feature soon where you can specify the SSH command to use (must be OpenSSH compatible). That should let you specify arbitrary commands (such as executing with bash)

**Comment by cybercypher** [comment]
i wrote this small bash function and added it to my bashrc to handle thism, since it was driving me nuts in mobaxterm
https://gist.github.com/cybercypher/09034406f544e040b38bdec47effc006
