### ISSUE TITLE
Support for VirtualBox 5 (beta)

### ISSUE THREAD

**Issue by Stanzilla** [mitchellh/vagrant#5560]
See https://forums.virtualbox.org/viewtopic.php?f=15&t=66904 for the release notes.

**Comment by bootstraponline** [comment]
:+1:

**Comment by Stanzilla** [comment]
https://github.com/mitchellh/vagrant/issues/5572

**Comment by petermac-** [comment]
<img class="emoji" title=":+1:" alt=":+1:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png" height="20" width="20" align="absmiddle">

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/pull/5647
