### ISSUE TITLE
File Provisioner file permissions

### ISSUE THREAD

**Issue by justechn** [mitchellh/vagrant#5561]
I am using the file provisioner but I can't figure out how to set the file permissions on the guest side.

http://docs.vagrantup.com/v2/provisioning/file.html

**Comment by jeroen94704** [comment]
You could probably do that with an inline script using the shell provisioner, like this:

```
$setpermissions = <<SCRIPT
  chmod 777 /path/to/file
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.provision "shell", inline: $setpermissions 
end
```

**Comment by mitchellh** [comment]
The above is correct.
