### ISSUE TITLE
Salt Provisioner Request: Add "local" flag to configs

### ISSUE THREAD

**Issue by garrickp** [mitchellh/vagrant#5563]
I want to be able to provision a VM with salt, either through the Salt Master, or using local files. As such, I've configured the minion to have a salt master, and I can use the `--local` flag to `salt-call` to implement local provisioning without having to stand up a separate VM.

This could potentially be implemented as:

    def get_local
        @config.local ? " --local" : ""
    end

    @machine.communicate.sudo("salt '*' saltutil.sync_all#{get_local}")
    @machine.communicate.sudo("salt '*' state.highstate --verbose#{get_local}#{get_loglevel}#{get_colorize}#{get_pillar}") do |type, data|

**Comment by PatOShea** [comment]
@garrickp, you can do this via the masterless flag which defaults to "false".  It's not in the current documentation right now, but I've created a pull request that added it.
https://github.com/PatOShea/vagrant/pull/1
