### ISSUE TITLE
undefined method `[]' for nil:NilClass in close_vsphere action

### ISSUE THREAD

**Issue by jreslock** [mitchellh/vagrant#5564]
I have encountered an issue that appears to be intermittent in nature with vagrant up --provider=vsphere and multi-machine configuration.

Here are some details plus a link to a gist for files.

vagrant version 1.7.2
vagrant-vsphere version 1.0.1
vsphere version 5.5.0
guest OS is CentOS 6.4.

Just after 'Setting hostname...' is posted to stdout I receive an error which stops the rest of the vagrant machines from being started.

```
ERROR:

INFO interface: Machine: error-exit ["VagrantPlugins::VSphere::Errors::VSphereError", "undefined method `[]' for nil:NilClass"]
```

Gist: https://gist.github.com/jreslock/a3b1ba8e3f9cc6c1af3b

I cross posted this because I don't know if it is a plugin issue or a core vagrant issue.  What else can I do to debug this further?

**Comment by jreslock** [comment]
I was able to resolve/work around this error by reverting from vagrant 1.7.2 to vagrant 1.6.4.

**Comment by dmulter** [comment]
I'm running vagrant 1.6.5 and I have the same issue. Please fix.

**Comment by sethvargo** [comment]
Hi @jreslock 

Thank you for opening an issue. According to the debug log, this is an issue with the vagrant-vsphere plugin:

```
ERROR vagrant: #<VagrantPlugins::VSphere::Errors::VSphereError: undefined method `[]' for nil:NilClass>
```

I believe this is an issue with the vagrant-vsphere plugin :smile:. Please open an issue on that repository.

**Comment by icnocop** [comment]
For reference, the new issue has been reported in the vagrant-vsphere repository [here](https://github.com/nsidc/vagrant-vsphere/issues/124).
