### ISSUE TITLE
Building isolated network

### ISSUE THREAD

**Issue by drjak** [mitchellh/vagrant#5565]
I want to achieve following scenario:

1. Have 3 separate (isolated) networks, e.g. 192.168.1.X, 192.168.2.X, 192.168.3X. Each network can contain 2-3 VMs
2. Each of those networks would have gateway VM with two interfaces, one internal 192.168.X.X and one external e.g. 10.0.1.2, 10.0.2.2, 10.0.3.2
3. Gateway is the only way traffic from inside can access external world 
4. Each gateway see remaining two gateways and puppet server (e.g 10.0.4.2)

How should look like Vagrantfile?
I noticed that private_network specified like 

```
VM1 - config.vm.network "private_network", ip: 192.168.0.3
VM2 - config.vm.network "private_network", ip: 192.168.1.3
VM3 - config.vm.network "private_network", ip: 192.168.2.3
```

are not isolated (means I can easily ping each other private network interface). I achieved isolation by adding them to bridge (brctl addif br0 vboxnet0 vboxnet1 vboxnet2), so I have:

```
bridge name     bridge id               STP enabled     interfaces
br0             8000.0a0027000000       no              vboxnet0
                                                                             vboxnet2
                                                                              vboxnet1
```

But this is where I stuck, I am facing other problems, e.g. I am able to use only one range of IP for public interfaces - so: 

```
VM1 - config.vm.network "public_network", ip: 10.0.1.2
VM2 - config.vm.network "public_network", ip: 10.1.1.2 
```

will not work (VM2 will not boot)

What would be the best solution for above scenario?

**Comment by sethvargo** [comment]
Hi @drjak 

Thank you for opening an issue. For general, usage-related questions, please ask on the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). I am sorry to push you to the mailing list, but we try to keep the Vagrant issue tracker specific to issues. 

If you find a bug in the configuration, please let us know and we will be happy to take a look. Thank you! :smile:

**Comment by 1oglop1** [comment]
this is still an issue after 3 years!
