### ISSUE TITLE
vagrant plugin development, cannot find vmware fusion license with bundler

### ISSUE THREAD

**Issue by gildas** [mitchellh/vagrant#5566]
So, here I am, taking the dive, writing my first vagrant plugin: an ISO mounter using the virtualization kits commands.
I have completed the code for Virtualbox and it runs quite smoothly.
Being a VMWare user as well (as well as Parallels, kvm, openstack, hyper-v, scvmm, but that will be for later), I decided to add the code for VMWare.

So, in my Gemfile I added the vagrant-vmware-fusion vagrant on top on the others. Found some tricks to get rgloader working (not sure I fully understand them yet) and I thought the same for the vmware-fusion license.

Alas, when I run say: bundle exec vagrant box list I get:
```sh
VMWare fusion gem is in /Library/Ruby/Gems/2.0.0/gems/vagrant-vmware-fusion-3.2.5
A valid license is required to run the Vagrant VMware
provider. Please visit http://www.vagrantup.com to purchase
a license. Once you purchase a license, you can install it
using `vagrant plugin license`.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
 ```

Note, the first line is a debug puts of mine to see where the Gem was actually found in my development environment.

Needless to say, when I run vagrant box list (i.e., outside of the dev environment), everything is good.

What am I doing wrong? Pretty please!

If needed: https://github.com/gildas/vagrant-mount, branch vmware_fusion.
I also made a gist of the debug output running the same command: [bundle exec vagrant box list error with vagrant-vmware-fusion loaded](https://gist.github.com/gildas/70a4208f8da99639b66b)

**Comment by sethvargo** [comment]
Hi @gildas 

I believe you will need to set the `VAGRANT_HOME` environment variable to a place on disk and then put your existing `license-vmware-fusion.lic` file in that directory. If that does not work, @mitchellh may have a better suggestion.

**Comment by gildas** [comment]
Hi @sethvargo,

Shoot, I already have a proper VAGRANT_HOME (mainly because I put my vagrant.d in an XDG_CONFIG structure).
When I run bundle exec vagrant box list where I puts the variable, it does show the proper value as well.

**Comment by gildas** [comment]
Even if I run it with --debug ir VAGRANT_LOG set to debug, I don't get much info as to where the license file should actually be in that scenario.

**Comment by gildas** [comment]
Hi again, FWIW, i reinstalled the vagrant and vagrant-fusion gems on another Mac, and this time it is working. I guess I will clean the current Mac and install stuff again.

Thanks for your time, Seth. Sorry to have wasted valuable time!
