### ISSUE TITLE
Url-escaped username and password in box_url are not supported

### ISSUE THREAD

**Issue by ratzinho87** [mitchellh/vagrant#5567]
When the user or password in box_url contains special characters, they need to be escaped, in order to have a valid url.
When escaping them, then the download does not work, because the credentials are stripped from the url and fed to curl exactly as they are. Curl takes its credentials unescaped.

Sample url to test: http://user:myP%40ssword@server.com/ubuntu.box

**Comment by sethvargo** [comment]
Hrm. I think maybe we are thinking about this backwards? I think perhaps Vagrant should URL _encode_ the values properly instead of decoding them. What do you think?

**Comment by ratzinho87** [comment]
The field box_url should be a valid url, right? In this case, when the password contains special characters, they should be escaped.
This would be a valid url:
     `http://user:p%40ss@foo.com/boxes/bar.box`
while this would not be:
     `http://user:p@ss@foo.com/boxes/bar.box`

Right now, basic http authentication works like this: the user and pass are stripped away from url and passed to curl in the `-u username:password` parameter. As far as I have tested, curl expects this parameter to be unencoded, so in the first case, the password is passed as exactly "p%40ss", not the decoded value "p@ss".

What do you mean by "Vagrant should encode"? Do you think curl might be able to handle encoded values?

**Comment by ratzinho87** [comment]
@sethvargo Do you need any other information? Do you have suggestions for how to better fix this?

**Comment by mitchellh** [comment]
This is fixed. You need to pass in the URL as unencoded.
