### ISSUE TITLE
Vagrant not starting up

### ISSUE THREAD

**Issue by aTei** [mitchellh/vagrant#5569]
From today (April 8) Vagrant not going further then `Bringing machine 'default' up with virtualbox' provider...`. Yesterday all was fine and nothing was changed on computer. 

I successfully tried to start up that virtual machine directly via VirtualBox.

Vagrant: 1.7.2
VirtualBox 4.3.8
Windows 7

Config
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/ubuntu-13.10"
  config.vm.box_download_insecure = true
  config.vm.box_check_update = false
  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network "public_network"
  config.vm.synced_folder "C:/Sites/", "/sites", type: "smb"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
end
```

Was there any update outside (vagrant, boxes, virtualbox...) that broken it or problem on my computer?

**Comment by aTei** [comment]
With `--debug` option, last rows are 
```
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SyncedFolderCleanup
:0x4782f18>
 INFO subprocess: Starting process: ["c:\\Windows\\System32\\WindowsPowerShell\\
v1.0\\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "$PSVersionT
able.PSVersion.Major"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 2
```

Then nothing happens

**Comment by sethvargo** [comment]
Hi @aTei 

I know this may sound stupid, but could you please restart your computer? If the issue persists, could you gist the entire debug log and link it here please? Thanks!

**Comment by aTei** [comment]
Restarted few times. Did not help. I googled about powershell, latest version for Win7 is 3, my was 2 (i think it's default ver. for Win7). So I upgraded it (https://technet.microsoft.com/en-us/library/hh847837.aspx) and Vagrant works now. Not sure, but maybe add this solution into Troubleshooting section.

**Comment by brooksbrown** [comment]
This seems to be related to https://github.com/mitchellh/vagrant/issues/3257 as well as this commit: https://github.com/mitchellh/vagrant/commit/a1d9121852c1278ecb3f9170f809ce49f7b4a24a.

It seems Windows 7 comes with PowerShell version 2 out of box and SMB synced folders requires version 3. The above commit checks for the the version, but it should probably be in the documentation as well since that commit is not released yet. 

I created a pull request with this update at: https://github.com/mitchellh/vagrant/pull/5626

**Comment by sethvargo** [comment]
Hi @aTei 

As @brooksbrown discovered, you need to update to a newer version of PowerShell. Sorry for the confusion. Please let me know if that does not fix your issue and we can revisit this :smile:!

**Comment by aTei** [comment]
As I said earlier, after update all is good :)
