### ISSUE TITLE
File provisioner fails to upload file through winrm

### ISSUE THREAD

**Issue by jeroen94704** [mitchellh/vagrant#5575]
I am having trouble getting file provisioning through WinRM to work with a VirtualBox Windows 8.1 box. Everything else seems to work, as far as I can tell. The box boots, and is accessible through rdp. I also have a couple of  shell provisioner inline scripts that run successfully. However, uploading a file from the host to the guest using the file provisioner fails. From what I understand, vagrant first copies the file from the host to a temp location on the guest in base64 encoding, and then decodes the file from the temp location to a final location on the guest. It looks like it is the first step (copying from host to temp location) that fails, since I see the following when running with loglevel info:
```
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 127.0.0.1
 INFO winrmshell:   - Port: 55985
 INFO winrmshell:   - Username: vagrant
 INFO winrm: WinRM is ready!
 INFO winrm: Uploading: V:/eswat/installers/test.txt to c:\temp\test.txt
ERROR warden: Error occurred: Failed to transfer a file between the host and guest

From: C:\Users\VAGRAN~1.ESW\AppData\Local\Temp/winrm-upload-0.19005834395708654
To: c:\temp\test.txt
Message: {:data=>[{:stdout=>"\r\n"}, {:stdout=>"\r\n"}, {:stdout=>"    Directory: C:\\\r\n\r\n\r\nMode                LastWriteTime     Length Name                              \r\n----                -------------     ------ ----                              \r\nd----         31-3-2015     16:14            temp                              \r\n"}, {:stderr=>"#< CLIXML\r\n"}, {:stderr=>"<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><S S=\"Error\">Get-Content : Cannot find path 'C:\\Users\\vagrant.ESWAT_BASEBOX\\AppData\\Local\\Te_x000D__x000A_</S><S S=\"Error\">mp\\winrm-upload-0.19005834395708654' because it does "}, {:stderr=>"not exist._x000D__x000A_</S><S S=\"Error\">At line:12 char:28_x000D__x000A_</S><S S=\"Error\">+           $base64_string = Get-Content $tmp_file_path_x000D__x000A_</S><S S=\"Error\">+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : ObjectNotFound: (C:\\Users\\vagran...0058343957086 _x000D__x000A_</S><S S=\"Error\">   54:String) [Get-Content], ItemNotFoundException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCo _x000D__x000A_</S><S S=\"Error\">   ntentCommand_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S><S S=\"Error\">Exception calling \"FromBase64String\" with \"1\" argument(s): \"Value cannot be nul_x000D__x000A_</S><S S=\"Error\">l._x000D__x000A_</S><S S=\"Error\">Parameter name: s\"_x000D__x000A_</S><S S=\"Error\">At line:13 char:11_x000D__x000A_</S><S S=\"Error\">+           $bytes = [System.Convert]::FromBase64String($base64_string)_x000D__x000A_</S><S S=\"Error\">+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : ArgumentNullException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S><S S=\"Error\">Exception calling \"WriteAllBytes\" with \"2\" argument(s): \"Value cannot be null._x000D__x000A_</S><S S=\"Error\">Parameter name: bytes\"_x000D__x000A_</S><S S=\"Error\">At line:14 char:11_x000D__x000A_</S><S S=\"Error\">+           [System.IO.File]::WriteAllBytes($dest_file_path, $bytes)_x000D__x000A_</S><S S=\"Error\">+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S><S S=\"Error\">    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException_x000D__x000A_</S><S S=\"Error\">    + FullyQualifiedErrorId : ArgumentNullException_x000D__x000A_</S><S S=\"Error\"> _x000D__x000A_</S></Objs>"}], :exitcode=>1}
```
The vagrant user does have administrator rights, but nevertheless in the winrm event logging on the guest I see a whole string of events that ends with an error saying "Sending HTTP 401 response to the client and disconnect the connection after sending the response".

I asked this question in the Vagrant Google Group, and got a reply suggesting this is, in fact, a bug, and I should raise it on GitHub. So here it is :). More information (e.g. more logging) is available if necessary.

**Comment by sethvargo** [comment]
Hi @jeroen94704 

Thank you for opening an issue. I have been unable to reproduce this, and it does not seem to be a widespread problem. (I would have expected a lot of +1s from the Vagrant community if this were widespread). Is this still happening for you? Could you please share your complete Vagrantfile as well as the output of the command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html)? Thanks!

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
