### ISSUE TITLE
Puppet Provisioner fails with Puppet 4

### ISSUE THREAD

**Issue by pcfens** [mitchellh/vagrant#5578]
When provisioning with Puppet 4, execution fails because Puppet 4 (rc2) doesn't support the `--manifestdir` option (supplied by the `manifests_path` option).

The information is still required by vagrant to sync the folder, and should be kept around for those that use puppet <=3, but (not) passed to puppet on request.

**Comment by jklippel** [comment]
See #3740 for a more detailed description and a still worked on fix.

**Comment by pcfens** [comment]
Thanks. I'll close this as a duplicate, and hopefully search better next time.
