### ISSUE TITLE
Setting config.vm.hostname randomly prevent lightdm autologin feature to work

### ISSUE THREAD

**Issue by joroy** [mitchellh/vagrant#5579]
It's seems to be a question of timing. Sometime autologin is sucessful because it's done before or after setting the hostname but most of the time, it fails because the NetworkManager is settings the hostname at the sametime that lightdm is performing is own stuff to perform the automatic login.

ex: syslog:Apr 10 14:54:17 ubuntu-12 NetworkManager[867]: <info> Setting system hostname to 'autologin' (from system configuration)

There is nothing special in the lightdm log file. From his point a view, everything is working fine even if the automatic login don't occurs.

Debug log: https://gist.github.com/joroy/cc71855edc71dfe26dbf

**Comment by mitchellh** [comment]
I'm not sure what Vagrant should do in this case. If you have a process racing Vagrant to set the hostname, then one or the other will win. Vagrant can't do a decent job of realizing that such a thing is happening. In this scenario, it may be safer to use a shell provisioner to set the hostname.

If I'm missing an obvious way to fix this, please do let me know.

**Comment by joroy** [comment]
Just to be clear, there is no race to set the hostname, only vagrant is
setting the hostname. The way I see it, vagrant should set the hostname
when the normal boot sequence is all done but it may be hard to know when
that occurs exactly.

2015-07-05 20:29 GMT-04:00 Mitchell Hashimoto <notifications@github.com>:

**Comment by mitchellh** [comment]
Yeah... that last sentence is the tricky part. :)

**Comment by joroy** [comment]
There is always the good old "rock solid" solution : Sleep 30

In other words, SSH is available, yeah, just wait 30 seconds before using
it... ;)



2015-07-09 15:09 GMT-04:00 Mitchell Hashimoto <notifications@github.com>:
