### ISSUE TITLE
bundler version restriction bundler (< 1.8.0, >= 1.5.2) ruby

### ISSUE THREAD

**Issue by saifikhan** [mitchellh/vagrant#5581]
Hi:
bundler install leads to bundler (< 1.8.0, >= 1.5.2) version restriction.

Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant (>= 0) ruby depends on
      bundler (< 1.8.0, >= 1.5.2) ruby

  Current Bundler version:
    bundler (1.9.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (< 1.8.0, >= 1.5.2) ruby', which is required by gem 'vagrant (>= 0) ruby', in any of the sources.

What is the logic behind this restriction ?

**Comment by gildas** [comment]
+1
I have the same issue, had to downgrade my bundler version in the rbenv I use.
It is just insane to have to prep a specific rbenv or rvm just for vagrant dev.

**Comment by sethvargo** [comment]
Hi @saifikhan 

I am sorry you are having issues. The recommended way to use Vagrant is via the [official package installers](http://www.vagrantup.com/downloads.html).

The reason for this restriction is because Vagrant relies on some internal APIs in Bundler core that are _not_ guaranteed to be backwards-compatible between minor version bumps (because they are internal APIs). Plugins in the Vagrant eco-system also leverage those APIs. There is [an open PR](https://github.com/mitchellh/vagrant/pull/5363) to upgrade to Bundler 1.8, but we have not had time to rigorously test the upgrade yet.

Please let me know if you have any questions.

**Comment by gildas** [comment]
@sethvargo, Yes, but if you are developing plugins, you really need to run vagrant in bundler, unless I missed something.

**Comment by sethvargo** [comment]
@gildas correct, you will need bundler and the Vagrant source. You need to install a version of bundler that matches the constraints for Vagrant:

```
gem install bundler -v '~> 1.7'
```

**Comment by gildas** [comment]
which is what I did. I was just saying, it's kinda annoying to do... a little...

**Comment by davidtrogers** [comment]
make sure you specify the patch version to stay within the bounds of the minor version:
```
$ gem install bundler -v '~> 1.7'
Fetching: bundler-1.9.4.gem (100%)
Successfully installed bundler-1.9.4
1 gem installed
$ bundler --version
Bundler version 1.9.4
$ gem install bundler -v '~> 1.7.0'
Fetching: bundler-1.7.14.gem (100%)
Successfully installed bundler-1.7.14
1 gem installed
```

**Comment by tknerr** [comment]
Tried running it with bundler 1.7.15 on ruby 2.2.1 but got this stacktrace.

Guess there is a ruby / gems 2.2 incompatibility as well?
```
C:\Repos\_github\vagrant-toplevel-cookbooks>bundle install
Your Gemfile lists the gem vagrant-toplevel-cookbooks (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Updating https://github.com/mitchellh/vagrant.git
Unfortunately, a fatal error has occurred. Please see the Bundler
troubleshooting documentation at http://bit.ly/bundler-issues. Thanks!
X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/settings.rb:175:in `normalize_uri': undefined local variable or method `mirror_source' for #<Bundler::Settings:0x00000003674988> (NameError)
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/settings.rb:54:in `block in gem_mirrors'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/settings.rb:51:in `each'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/settings.rb:51:in `inject'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/settings.rb:51:in `gem_mirrors'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/source.rb:11:in `mirror_for'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/fetcher.rb:381:in `resolve_remote_uri'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/fetcher.rb:98:in `initialize'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/source/rubygems.rb:286:in `new'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/source/rubygems.rb:286:in `block in fetchers'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/source/rubygems.rb:285:in `map'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/source/rubygems.rb:285:in `fetchers'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/source/rubygems.rb:296:in `block in remote_specs'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/index.rb:9:in `build'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/source/rubygems.rb:295:in `remote_specs'
        from X:/tools/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/bundler-1.7.15/lib/bundler/source/rubygems.rb:77:in `specs'
...
```

**Comment by mitchellh** [comment]
Fixed in master
