### ISSUE TITLE
Docker provider support for env as external file?

### ISSUE THREAD

**Issue by jbpadgett** [mitchellh/vagrant#5582]
Is is possible to use the "env" option in the docker provider referencing an external file rather than the hash the documentation mentions?
http://docs.vagrantup.com/v2/docker/configuration.html

Ideally, what I want to do is what is already available for the "build_dir" option in the docker provider.
My desired implementation might looks something like this:

```ruby
#Container 1
config.vm.define "postgres" do |v|
  v.vm.provider "docker" do |d|
    d.env = "/path/to/.myenv.db"
    d.build_dir = "./docker/db/"
    d.vagrant_vagrantfile = "./Vagrantfile.host"
  end
end
```

Thanks good sirs.

**Comment by pedrofernandezm** [comment]
+1

**Comment by sethvargo** [comment]
Hi there,

This is not something we plan to add to Vagrant ourselves. We would gladly review a PR for this, but I think a better solution is to use Ruby for this:

```ruby
d.env = JSON.parse("/myenv.db")
```

Where the JSON file contains a properly formatted environment file. Thanks! 😄
