### ISSUE TITLE
Can't ssh with root

### ISSUE THREAD

**Issue by habitullence** [mitchellh/vagrant#5586]
On the box I can change into root user with the default password but same password doesn't work with:
```
vagrant ssh -- -l root
```

**Comment by sethvargo** [comment]
Hi @habitullence 

Vagrant boxes are configured to allow access to the `vagrant` user with the credentials `vagrant:vagrant`. The vagrant user is also configured to allow passwordless `sudo` (meaning you do not need to enter a password to run sudo commands). This is why you do not need a password to run `sudo` commands as the Vagrant user (including `sudo su -`) to become the root user.

Does that make sense?

**Comment by mitchellh** [comment]
You can also use `config.ssh.username` or `vagrant ssh-config` to get the raw config.
