### ISSUE TITLE
vagrant-vbguest plugin installation failure

### ISSUE THREAD

**Issue by JoAmala** [mitchellh/vagrant#5588]
I'm trying to setup a vagrant system for rails development in Windows.

My vagrant version is Vagrant 1.4.2 and I have installed both the plugins vagrant-librarian-chef (0.1.4) and vagrant-vbguest (0.10.0).

But when I do vagrant up I get the following error.

$ vagrant up

The plugin "vagrant-vbguest" could not be found. Please make sure that it is properly installed via vagrant plugin. Note that plugins made for Vagrant 1.0.x are not compatible with 1.1+ and this error will likely continue to show when you use plugin install with a 1.0.x plugin. Bringing machine 'default' up with 'virtualbox' provider... There are errors in the configuration of this machine. Please fix the following errors and try again:

vm: * The box 'base' could not be found.

**Comment by sethvargo** [comment]
Hi @JoAmala 

Please ask usage-related questions on the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). It looks like you do not have a box named "base" - you can see the list of boxes by running `vagrant box list`. You can download new boxes online or package your own. Thanks!
