### ISSUE TITLE
All commands take several minutes to output anything

### ISSUE THREAD

**Issue by lmartins** [mitchellh/vagrant#5594]
Hi,

I've seen a few issues discussing this problem, namely https://github.com/mitchellh/vagrant/issues/5224, although in my machine it's seems to be more severe.

Any Vagrant command I try to run will take several minutes before doing anything. The shell just shows the blinking cursor during that time. This is obviously worse then the command gives itself more Vagrant commands, such has `vagrant halt` because that when it runs `==> default: Executing command "vagrant ssh -c vagrant_halt"...`will again stop for several minutes, making it effectively unusable.

Im running the latest version `Vagrant 1.7.2` in OS X 10.10 and the following plugins:
```
vagrant-hostsupdater (0.0.11)
vagrant-share (1.1.3, system)
```
Is there anything I can do about this?

**Comment by sethvargo** [comment]
Hi @lmartins 

Can you please try uninstalling the vagrant-hostupdater plugin? It would be helpful to see the output of `vagrant -v` in debug mode as well.

**Comment by lmartins** [comment]
Hey @sethvargo 

Thank you so much for helping me out with this. For now I resorted to reinstall the VM since I really needed to get things going. Let's how things go in the next few hours, i'll update this after that.

Thanks again man.

**Comment by sethvargo** [comment]
Sounds good. I am sorry you're having issues, but I'm glad you have a temporary workaround. We are definitely interested in fixing this though!

**Comment by lmartins** [comment]
I was able to work all afternoon without any hiccups thankfully. Closing this for now, will reopen if I see the issue again. Thanks again.

**Comment by lmartins** [comment]
Sadly first thing in the morning im getting the same behaviour as yesterday. 
`vagrant up` is running for a few minutes now without any response.

**Comment by lmartins** [comment]
Im not sure if this might be of any use to you, but another thing i've noticed is that even commands such as `vagrant global-status`, or event just `vagrant` take a long time to complete.

They both start by showing me data, but the freeze the terminal for a long time (several minutes) and finally complete after a while. When this happens, pressing CTRL+C doesn't kill the process, so I can only wait for it to eventually complete or kill terminal altogether which, I imagine, can get me into troubles with Vagrant.

Thank you.

**Comment by lmartins** [comment]
Anything else I can test to help figure what the problem is?
Running commands, especially those that envolve multiple vagrant commands is unbelievably slow. :(

**Comment by lmartins** [comment]
Sorry to bump this up, but can anyone help with any lead to resolve this. Should I reinstall the ruby environment or anything?

Btw, this is what I get when I run any command with Vagrant. Is starts by showing me data but the halts several minutes before handing me back control of shell again:

![vagrant ruby iterm today at 10 50 20](https://cloud.githubusercontent.com/assets/151981/7294596/995a02ac-e9a6-11e4-8775-456bfddf9327.png)

**Comment by sethvargo** [comment]
Hi @lmartins 

I am sorry for the delay in responding. Unfortunately this is not a widely reported issue and we do not have a reliable reproduction case to go of off. I believe this may be an issue with your local setup or installation, especially since we do not have other users reporting this issue :frowning:.

I realize this is not the answer you would like to hear, but unfortunately I do not know what to recommend. 

My only recommendation would be to remove all of Vagrant including the `~/.vagrant.d` directory, restart your computer, and re-install the latest version of Vagrant from the official Vagrant installers. If the issue continues to persist, then I am afraid I do not have an answer.

**Comment by lmartins** [comment]
Hey @sethvargo thank you so much for your input on this.
Guess i'll have to reinstall it then. I'll update this with the result.

Thanks.

**Comment by mitchellh** [comment]
Let us know how that goes. Also try setting the `VAGRANT_LOG=debug` environment variable. That might help us debug where it is hanging.

**Comment by lmartins** [comment]
Hi @mitchellh 
Unfortunately I ended up going for another solution, so its not easy for me to provide further feedback.
I did reinstalled Vagrant but that made no difference. I suspect the Ruby environment may have something to do with the problem though. The iTerm window seem to be stuck in the Ruby process every time I did any Vagrant command.
Thanks.

**Comment by MohammedDiab** [comment]
i'm having this issue too, after upgrading to 1.7.4. and also after updating to windows 10

**Comment by mustafamotiwala** [comment]
I am having the delayed return to shell after executing vagrant commands. Vagrant 1.7.2 on Windows.

**Comment by mustafamotiwala** [comment]
Ran vagrant with `VAGRANT_LOG=debug` and noticed that the task that was taking a long time was: `INFO runner: Running action: environment_unload`. Went through and noticed that Vagrant attempts a version update check. This of course causes issues when you don't have an active connection or are behind are proxy and your environment isn't configured. 
Think this should be raised as a bug?
