### ISSUE TITLE
Multi Machine with Groups

### ISSUE THREAD

**Issue by Hounddog** [mitchellh/vagrant#5596]
Hi, i have a heavily modified Vagrantfile and need to limit machine by groups.
In my groups i have defined how many machines of this type can be instantiated.

Instead of typing 
vagrant up development-1 development-2 development-3

I would type 
vagrant --vagrant-namespace=development up

But how can i limit this in vagrant?
I have tried adding the machine names to the ARGV but this didnt work.
Is there any environment Variable to which i can add the machine names inside the Vagrantfile?

**Comment by Hounddog** [comment]
I currently solved it with a proxy file to add the machin names to vagrant
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'


# Read YAML file with box details
servers = YAML.load_file('servers.yml')

#ARGV
skip = 0
while skip < ARGV.length

  if ARGV[skip].start_with?(arg='--vagrant-namespace=')
    v = ARGV.delete_at(skip).dup
    v.slice! arg

    namespacefilter = v.to_s  # set namespace
  else  # skip over "official" vagrant args
    skip = skip + 1
  end
end

servers.each do |servers, i|
  count = servers['count']

  (1..count).each do |i|
    h = "#{servers['namespace']}-#{i}"
    if namespacefilter == servers['namespace']
      ARGV << h;
    end
  end
end

exec 'vagrant', *ARGV
```

**Comment by conorsch** [comment]
As long as you name your hosts according to the namespace you want, you can use regex to identify boxes. This command will up all hosts matching development:

`vagrant up /development/`

This command will up "development-1" and "development-2", but **not** "development-3":

`vagrant up /development-[12]/`

See the [docs on multi-machine configurations](http://docs.vagrantup.com/v2/multi-machine/index.html). If the explanation above doesn't help, post a link to your Vagrantfile.

**Comment by robbertnoordzij** [comment]
:+1:  this would be a handy addition

**Comment by sethvargo** [comment]
Hi all,

I think this is part of a larger conversation, which is VM dependencies and how to manage them: https://github.com/mitchellh/vagrant/issues/4026. Let's track this there. Thanks! 😄 Please add your thoughts over there.
