### ISSUE TITLE
Provision with 10+ args fails

### ISSUE THREAD

**Issue by georgschlenkhoff** [mitchellh/vagrant#5597]
I cannot load more than 9 environment args. Let's say I have in my .bashrc ```export ARG1=valueofarg1``` and then in my ```Vagrantfile```:

```
config.vm.provision "shell" do |s|
    s.path = "bootstrap.sh"
    s.args = [ENV['ARG1'], ENV['ARG2'], ENV['ARG3'], ENV['ARG4'], ENV['ARG5'], ENV['ARG6'], ENV['ARG7'], ENV['ARG8'], ENV['ARG9'], ENV['ARG10'], ENV['ARG11']]
  end
```

In my bootstrap.sh script arg ```$10``` has value ```valueofarg10```.

I'd be happy to read in all args at once, such as ```ENV['SHELL_ARGS']```, but don't know how.

**Comment by ratzinho87** [comment]
Try this: 
```
  provisionArgs = "#{ENV['ARG1']} #{ENV['ARG2']} #{ENV['ARG3']} #{ENV['ARG4']} #{ENV['ARG5']} #{ENV['ARG6']} #{ENV['ARG7']} #{ENV['ARG8']} #{ENV['ARG9']} #{ENV['ARG10']} #{ENV['ARG11']}"

  config.vm.provision "shell", path: "bootstrap.sh", args: provisionArgs
```

**Comment by sethvargo** [comment]
Hi @georgschlenkhoff 

Thank you for opening an issue. There is no limit on the number of arguments you can have. Are you able to provide the complete `Vagrantfile` and the results of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by mitchellh** [comment]
Closing due to lack of response
