### ISSUE TITLE
salt.seed_master does not work

### ISSUE THREAD

**Issue by codeape** [mitchellh/vagrant#5598]
I am running vagrant version: 1.7.2. I have added three .pub files to `seed_master`. However, when i start the box the minion running on the same box fail: `Minion failed to authenticate with the master, has the minion key been accepted?`. The `/etc/salt/pki` directory looks like this:

```
/etc/salt/pki/
├── master
│   ├── master.pem
│   ├── master.pub
│   ├── minions
│   ├── minions_autosign
│   ├── minions_denied
│   ├── minions_pre
│   │   └── salt
│   └── minions_rejected
└── minion
    ├── minion.pem
    └── minion.pub

7 directories, 5 files
```

The minion salt is still in `minions_pre` and I do not see any of the other .pub files in the tree.

I have taken a look in the salt plugin provisioner code: https://github.com/mitchellh/vagrant/blob/v1.7.2/plugins/provisioners/salt/provisioner.rb
By reading that file I have concluded that my vagrant config fulfill the minimal requirements for seed_master. I have added minion ids wit key files to `seed_master` and set `install_master = true`. 

However, even if my config fulfill the requirements for `seed_master` I find this in my `vagrant up` output:

```
Using Bootstrap Options:  -D -c /tmp -M
```

Full log here: https://gist.github.com/codeape/dd45ad4fa274abe2e685 

If you read the code of provisioner.rb you expect to see this

```
Using Bootstrap Options:  -D -c /tmp -M -k /tmp/minion-seed-keys
```

I have a vagrant file that looks like this:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

VAGRANT_ROOT = File.dirname(File.expand_path(__FILE__))
fblinux_tmp = File.join(VAGRANT_ROOT, 'fblinux_tmp.vdi')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "salt_master", primary: true do |salt_master|
    salt_master.vm.box = "ubuntu/trusty64"

    salt_master.vm.hostname = "salt"
    salt_master.vm.network "private_network", ip:"192.168.0.30"

    salt_master.vm.synced_folder "salt/roots/", "/srv/"

    # Fix tty problems
    salt_master.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    salt_master.vm.provision :salt do |config|
      config.bootstrap_options = "-D"

      config.run_highstate = false

      config.verbose = true
      config.colorize = true

      config.master_config = "salt/conf/salt-master"
      config.minion_config = "salt/conf/salt-minion"

      config.no_minion = false

      config.master_key = "salt/key/salt-master.pem"
      config.master_pub = "salt/key/salt-master.pub"

      config.minion_key = "salt/key/salt-minion.pem"
      config.minion_pub = "salt/key/salt-minion.pub"

      config.install_master = true
      config.seed_master = {salt:"salt/key/salt-minion.pem", fblinux:"salt/key/fblinux.pub",spawn: "salt/key/spawn-master.pub"}
    end

    # Enable host to serve as salt master
    salt_master.vm.network "forwarded_port", guest: 4505, host: 4505
    salt_master.vm.network "forwarded_port", guest: 4506, host: 4506

    # And explicitly call the highstate on this one
    salt_master.vm.provision :shell, :inline => 'sleep 60; salt-call state.highstate'
  end

  # Below should be 2 boxed that I have commented out for now so I cut them out of this file.
end
```

**Comment by codeape** [comment]
So I have solved this my self!

I run this version of vagrant:
```
$ vagrant -v
Vagrant 1.7.2
```

I did a small check of the plugins:
```
$ vagrant plugin list
vagrant-salt (0.4.0)
vagrant-share (1.1.3, system)
```
This is wrong because vagrant-salt is built in now.

All I did then was:
```
$ vagrant plugin uninstall vagrant-salt
Uninstalling the 'vagrant-salt' plugin...
```
After that everything worked as a charm!

**Comment by codeape** [comment]
Maybe this should be documented somewhere?

**Comment by p4ali** [comment]
Somehow, the seed_master does not work for me at all. I have manually copy the keys to the /etc/salt/pki/master/minions.
