### ISSUE TITLE
File system indicator of vagrant status

### ISSUE THREAD

**Issue by joshg** [mitchellh/vagrant#5606]
We're using Vagrant to great success with local project workflow.
Many of these workflows are driven with Makefiles.
The makefiles route processing through the local vagrant instance to perform the actual processing.
It would be a great help to have a file indicator in the local filesystem reflective of the VM being up.

For example:

```
something : vagrant_instance depends_upon
     vagrant ssh -c "command_to_process_depends_upon_to_something.sh"

vagrant_instance : .vagrant/machines/mymachine/virtualbox/status.up
     vagrant up
```

Something like this would allow the up status of the vagrant instance to be transparently handled in the dependency tree.

**Comment by sethvargo** [comment]
Hi @joshg 

Thank you for opening an issue. You can check the file in `$CWD/.vagrant/machines/$name/$provider/id`. However, be aware that this only controls the state of the machine _if vagrant is the only thing controlling it_. If someone opens the vbox gui and deletes the machine, Vagrant has no way of knowing about that event, so it could be a misleading indicator :smile:.
