### ISSUE TITLE
Vagrant not installing current version of plugin (vagrant-librarian-puppet)

### ISSUE THREAD

**Issue by ErikEvenson** [mitchellh/vagrant#5610]
Is this a problem with Vagrant, or of another part of the toolchain (bundler)?:

https://github.com/mhahn/vagrant-librarian-puppet/issues/34

I am installing Vagrant via homebrew on OS X.

**Comment by sethvargo** [comment]
Vagrant uses bundler under the hood, so it might be a bundler issue. What is the output of `vagrant plugin list`?

**Comment by ErikEvenson** [comment]
Before I install vagrant-librarian-puppet:

```
vagrant-cachier (1.2.0)
vagrant-share (1.1.3, system)
vagrant-vbguest (0.10.0)
```

**Comment by sethvargo** [comment]
@ErikEvenson just for fun, can you try uninstalling all plugins and then install librarian-puppet? I wonder if there is a shared dependency that is causing bundler to issue a downgrade under certain circumstances in the dep tree.

**Comment by ErikEvenson** [comment]
Here's what I've got:

```
$ vagrant plugin list
vagrant-share (1.1.3, system)

$ vagrant plugin install vagrant-librarian-puppet
Installing the 'vagrant-librarian-puppet' plugin. This can take a few minutes...
Installed the plugin 'vagrant-librarian-puppet (0.8.0)'!

$ vagrant plugin list
vagrant-librarian-puppet (0.8.0)
vagrant-share (1.1.3, system)
```

**Comment by sethvargo** [comment]
Weird. I definitely think this is a bundler issue, but we will leave this open to investigate further.

**Comment by ErikEvenson** [comment]
Thanks.  I'm using the `--plugin-version` option as a work-around in the mean time.  Cheers!

**Comment by sethvargo** [comment]
We are going to update bundler in the next release of Vagrant, and hopefully this issue will be resolved :smile:. If not, we can re-visit this after the next release and dig in a bit more, but I'm pretty convinced this is a bundler issue.
