### ISSUE TITLE
Vagrant::Util::Platform.windows_admin? true from non-elevated command prompt

### ISSUE THREAD

**Issue by bbodenmiller** [mitchellh/vagrant#5616]
I'm running `Vagrant::Util::Platform.windows_admin?` from both an elevated and non-elevated command prompt and both appear to be returning `true`. I'm expecting this to return `false` if not an elevated command prompt. While `Vagrant::Util::Platform.windows_admin?` is not working for me, the following is.

```ruby
def running_in_admin_mode?
    (`reg query HKU\\S-1-5-19 2>&1` =~ /ERROR/).nil? 
end
```

**Comment by mitchellh** [comment]
Fixed!

**Comment by lukebakken** [comment]
@bbodenmiller - I'm curious, what were you doing that required being both in the `Administrators` group *and* in an elevated console?
