### ISSUE TITLE
config.vm.provision "chef_zero" is chef-solo not chef-client

### ISSUE THREAD

**Issue by kcd83** [mitchellh/vagrant#5619]
```
==> default: [2015-04-21T23:39:30+01:00] INFO: *** Chef 12.2.1 ***
==> default: [2015-04-21T23:39:30+01:00] INFO: Chef-client pid: 3738
..
==> default: Error expanding the run_list:
==> default: ================================================================================
==> default:
==> default: Unexpected Error:
==> default: -----------------
==> default: Chef::Exceptions::IllegalVersionConstraint: Environment cookbook version constraints not allowed in chef-solo
```

I would expect this to do what Kitchen does
```
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /tmp/kitchen/dna.json` 

```

I have read https://github.com/mitchellh/vagrant/issues/5072 but don't understand the use of `chef-solo` rather than `chef-client --local-mode`. What am I missing?

**Comment by kcd83** [comment]
Issue might be that I have both installed. If i rename chef-solo i get an error
```
[root@localhost ~]# find /usr/bin/ -name *chef*
/usr/bin/chef-apply
/usr/bin/OFFchef-solo
/usr/bin/chef-client
/usr/bin/chef-shell
```

```
==> default: Detected Chef (12.2.1) is already installed
The chef binary (either `chef-solo` or `chef-client`) was not found on
the VM and is required for chef provisioning. Please verify that chef
is installed and that the binary is available on the PATH.
```

There must be some conflict going on here

**Comment by sethvargo** [comment]
@kcd83 can you try using a box that does not have Chef pre-installed? I think you have conflicting verisons.

**Comment by kcd83** [comment]
Reproduced this on `opscode-centos-6.6` and `chef/centos-6.5`. As for your suggestion I tried `puppetlabs/centos-6.6-64-puppet` and I still hit the same problem.

**Comment by kcd83** [comment]
FYI chef-solo also fails if the environment is missing
```
  "json_class": "Chef::Environment",
  "chef_type": "environment",
```
Whereas chef-zero does not

**Comment by sethvargo** [comment]
Hi @kcd83 

Can you please share your complete Vagrantfile? Thanks!

**Comment by erichelgeson** [comment]
I came across this same issue today using boxcutter centos 65 latest. The new `audit-mode` is not in solo, but is in client, relavant info in the mailing list - http://lists.opscode.com/sympa/arc/chef/2015-04/msg00221.html

I too would expect it to be `chef-client` vs `chef-solo` for local mode.

**Comment by smudgerdan** [comment]
Taking the code from an example on the chef site in a recipe (https://docs.chef.io/data_bags.html#with-recipes):

    users = Chef::DataBag.new
    users.name("users")
    users.create

    sam = {
        "id" => "sam",
        "Full Name" => "Sammy",
        "shell" => "/bin/zsh"
    }
    databag_item = Chef::DataBagItem.new
    databag_item.data_bag("users")
    databag_item.raw_data = sam
    databag_item.save

    sam = data_bag_item("users", "sam")
    sam["Full Name"] = "Samantha"
    sam.save

I get a error when using the chef_zero provisioner:
`ERROR: Failed to load data bag item: "users" "sam"`

The folder and files are created in the data_bags folder but it seems to have an issue reading it back.  The command being called by vagrant is `chef-solo -c c:\tmp\vagrant-chef\solo.rb -j c:\tmp\vagrant-chef\dna.json --no-color` but if I change it to `chef-client -z -c c:\tmp\vagrant-chef\solo.rb -j c:\tmp\vagrant-chef\dna.json --no-color` it completes successfully.

I am hosting in Windows and the guest is Windows (in case that makes a difference)

**Comment by twisty7867** [comment]
Any ETA for a fix? I can't use this provisioner at present because of this issue - my environments specify cookbook versions, which is incompatible with chef-solo.

**Comment by dkinzer** [comment]
I'm seeing this too.

**Comment by kcd83** [comment]
Sorry guys, this was on me to supply the example.

@sethvargo finally the example https://github.com/kcd83/vagrantnotchefzero

**Comment by darkn3rd** [comment]
The `chef_zero` provisioner needs to be use chef-client, or just be purged completely as a provisioner.  It is really silly to install the chef-zero server, and then ignore it completely and run chef-solo.  That just makes no sense, and it has caused widespread community confusion for newcomers, at least using StackExchange and blogs from google searches as an indicator.

**Comment by kcd83** [comment]
Thanks Seth!
