### ISSUE TITLE
The script get_network_config.ps1 fails on Hyper-V VMs with more than one network interface

### ISSUE THREAD

**Issue by hagronnestad** [mitchellh/vagrant#5620]
The script `get_network_config.ps1` fails on Hyper-V VMs with more than one network interface. When the script fails no more configuration is done by Vagrant, which means that the `/vagrant` shared folder won't be mounted and any provisioners with the `run: "always"` flag won't run.

##### `vagrant up` output:
```
Bringing machine 'AppexSSHFS' up with 'hyperv' provider...
==> AppexSSHFS: Verifying Hyper-V is enabled...
==> AppexSSHFS: Starting the machine...
==> AppexSSHFS: Waiting for the machine to report its IP address...
    AppexSSHFS: Timeout: 120 seconds
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: get_network_config.ps1
Error:

C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyperv\scripts\get_network_config.ps1 : Cannot index into a null array.
At line:1 char:1
+ &('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.2\plugins\providers\hyper ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [get_network_config.ps1], RuntimeException
    + FullyQualifiedErrorId : NullArray,get_network_config.ps1
```

**Comment by ssugar** [comment]
I just tested this on a HyperV VM with two network adapters, and the get_network_config.ps1 script isn't failing when I run it directly.  It returns the IP address of the first network adapter.

![returns-first-interface-ip](https://cloud.githubusercontent.com/assets/7929462/7336009/5a2e3ebc-ec0e-11e4-9011-0001fd06471b.png)

I was however able to get the same "cannot index into a null array" error when the VM wasn't getting an IP address via DHCP.

What output do you get if you run the following command in powershell after you receive the "Cannot index into a null array" error?

    Get-VM -Name "name_of_your_vm" | Get-VMNetworkAdadpter

**Comment by hagronnestad** [comment]
I'll try when I get to work tomorrow. The VM I use have one adapter configured by DHCP and one configured manually. When I remove the manually configured adapter the IP of the adapter configured with DHCP is reported to vagrant with no errors.

**Comment by mitchellh** [comment]
Fixed!

**Comment by mitchellh** [comment]
https://github.com/mitchellh/vagrant/commit/b23b48a61420980e05b4319520609d25921c893c
