### ISSUE TITLE
complied software in /vagrant often failed

### ISSUE THREAD

**Issue by myplace77** [mitchellh/vagrant#5621]
When I vagrant up. I copy software source code  to the default share folder /vagrant .
Then I .configure  and make.
It was always reporting some error like "automake ** not foud" . Almost errmsgs was about  automake environment.
But I copy the souce code to /home/vagrant.  All These errors disapper and work fine.

**Comment by sethvargo** [comment]
Hi @myplace77 

I suspect this is because `/vagrant` is actually shared with your local machine. Could you please share your Vagrantfile and any output you may have?

**Comment by myplace77** [comment]
@sethvargo yes, you are right.  /vagrant is the default shared folder. I didn't found any document told me that can't compile in shared dir.
e.g.
When I compile libmcrypt, when I make:
'''shell
vagrant@homestead:/vagrant/tar/libmcrypt-2.5.6$ make
cd . && \
  /bin/bash /vagrant/tar/libmcrypt-2.5.6/missing --run automake-1.7 --foreign  Makefile
/vagrant/tar/libmcrypt-2.5.6/missing: line 46: automake-1.7: command not found
WARNING: `automake-1.7' is needed, and you do not seem to have it handy on your
         system.  You might have modified some files without having the
         proper tools for further handling them.  Check the `README' file,
         it often tells you about the needed prerequirements for installing
         this package.  You may also peek at any GNU archive site, in case
         some other package would contain this missing `automake-1.7' program.
Makefile:178: recipe for target 'Makefile.in' failed
make: *** [Makefile.in] Error 1
'''

**Comment by sethvargo** [comment]
Hi @myplace77 

What happens if you install `apt-get install automake`?

**Comment by myplace77** [comment]
@sethvargo I am sure apt-get install automake can work fine. But my company not allowed me use internet on the development PC. So I can only compile myself.  What I care about is if this case is a bug of Vagrant.  Thanks again.

**Comment by myplace77** [comment]
@sethvargo By the way. You are a great guy. ^_^

**Comment by sethvargo** [comment]
Hi @myplace77 

I do not think this is a bug in Vagrant. The error says you are missing tools you need to build (like automake, build-essential). Even if you take vagrant out of the mix, you need build tools to compile things :smile:
