### ISSUE TITLE
Publish approximate Roadmap for Releases as GitHub Milestones

### ISSUE THREAD

**Issue by lonniev** [mitchellh/vagrant#5625]
I'm desperate for your 1.7.3 release to get several of its fixes for (accursed) Windows guests.

I don't want to pester When? When? When?

So, can you publish approximate release dates here using the Milestone capability?

**Comment by ericmann** [comment]
+1

**Comment by lonniev** [comment]
@mitchellh While we await 1.7.3, could you expand the README documentation for how one should "rake install" a pre-release when they already have the package-installed full release in place--such that when the latest pre-release is released, they can update to the packaged release without fubarring their vagrant environment?

Perhaps it just works to "rake install" right over the official installation but I'm too cowardly to just try it and see.

Of course, if you are releasing 1.7.3 in the next few minutes (if not, When? When? When?) then I don't need to go through this hassle.

**Comment by lonniev** [comment]
Please advise. Especially because a simple clone of this repo followed by the sole "rake install" as indicated in the README.md does not yield happiness. Instead, it complains that rake and bundle are too new and that bundle in the [1.5.2, 1.8.0) range must be used. Current bundle is 1.9.4.

**Comment by William-Yeh** [comment]
+1 for milestone and roadmap.

**Comment by lonniev** [comment]
+1

Oh! wait, I can't upvote my own issue.

Nevertheless, is there *any* guidance on when 1.7.3 will be available?

**Comment by lonniev** [comment]
@mitchellh, my project is stalled out. Can you share an estimate for when 1.7.3 will become available?

**Comment by sethvargo** [comment]
We do not have an estimate for when the next version of Vagrant will be released at this time.

**Comment by StefanScherer** [comment]
@lonniev I use the https://github.com/aidanns/vagrant-reload plugin and do a reload as first provision step as a workaround. Perhaps this might help you in the meantime.

**Comment by lonniev** [comment]
@StefanScherer, pardon? What's the relationship of vagrant-reload here? Might be, I just miss the connection.

(I'm waiting for a bugfix in 1.7.2 for Windows guests.)

**Comment by StefanScherer** [comment]
@lonniev Probably you wait for another Windows guest fix than I ran into. I got a problem with renaming the windows guest machine's hostname without the reboot plus joining a Windows Domain. So I added the vagrant-reload as first provision step before the real provisioning kicks in.
I just wanted to share my workaround until 1.7.3 is available ;-)

**Comment by lonniev** [comment]
I missed the chance to say hello to @mitchellh but it was good to see him at GlueCon. Sorry we couldn't offer you our traditional sunshine; the cool, cloudy weather might have reminded him more of San Francisco.

**Comment by sethvargo** [comment]
Hi @lonniev 

Thank you for opening an issue. Unfortunately we do not have a public roadmap we are ready to share at this time. We hope to release a new version of Vagrant shortly with all the new features and bug fixes, but there are a number of factors that determine that release date.

The short answer is "soon", but we do not have an exact date. Sorry! :smile:

**Comment by amenophis** [comment]
Any news as Virtualbox 5.0 has been released ?
