### ISSUE TITLE
Please reopen #2614

### ISSUE THREAD

**Issue by istvan-ujjmeszaros** [mitchellh/vagrant#5627]
We still have the issue mentioned in #2614, please reopen it.

**Comment by sethvargo** [comment]
Hi @istvan-ujjmeszaros 

Thank you for opening an issue. There is a lot of conversation in #2614 and a few different issues that users have reported. Can you please open a new issue and be sure to include:

- The version of Vagrant you are running
- The operating system of the host
- The operating system of the guest
- The result of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html) (preferably in a GitHub gist)

Thanks!
