### ISSUE TITLE
Vagrant cannot SSH if the .pub file does not correspond to the private key. It should at least warn that this is happening

### ISSUE THREAD

**Issue by WyseNynja** [mitchellh/vagrant#5628]
https://gist.github.com/WyseNynja/abb84390c7ca285d671f

The key shown when running VAGRANT_LOG works for me when I ssh manually, but Vagrant just keeps on retrying forever.

What else can I try to debug?

**Comment by sethvargo** [comment]
Hi @WyseNynja 

What are the permissions on your public and private keys?

**Comment by WyseNynja** [comment]
The permissions are fine.

I figured it out. Someone made a new id_rsa, but didn't update the corresponding id_rsa.pub.  ssh doesn't care about this mismatch, but the ruby library does.

We should probably have a better error message around this

**Comment by WyseNynja** [comment]
Wait. The pubkey does match. only the comment was different. I'll investigate more and reopen if necessary

**Comment by WyseNynja** [comment]
```
-rw-------  1 uber uber   3247 Apr 12 10:18 id_rsa
-r--r--r--  1 uber uber    744 Apr 12 10:20 id_rsa.pub
```
