### ISSUE TITLE
On 64-bit Windows: %VAGRANT_HOME%/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/subprocess.rb:109:in `rescue in execute':  (193) (Vagrant::Util::Subprocess::LaunchError)

### ISSUE THREAD

**Issue by dusank** [mitchellh/vagrant#5630]
Please see:
* https://github.com/mitchellh/vagrant/issues/1483#issuecomment-95595872
* https://github.com/mitchellh/vagrant/issues/1483#issuecomment-95736570

Suggested labels: bug, core, windows

**Comment by dusank** [comment]
I've found the root cause of the problem:
* https://github.com/mitchellh/vagrant/issues/1483#issuecomment-96069983

and wold like to suggest improving the error reporting in vagrant to avoid similar issues being reported again.

=Dusan

**Comment by mitchellh** [comment]
Taking a look at #1483 again now, and will fix messaging there. Thanks for the heads up.
