### ISSUE TITLE
Error: A version of the box you're loading is formatted in a way that Vagrant cannot parse...

### ISSUE THREAD

**Issue by drmyersii** [mitchellh/vagrant#5631]
Hello!

I just recently tried to download and launch a box from atlas.hashicorp.com, but Vagrant is giving me this error:

```
A version of the box you're loading is formatted in a way that
Vagrant cannot parse: '15.04-stable'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z.
```

Details:

```
OS: Windows 8.1 Pro x64
Vagrant: 1.7.2
Box Name: ubuntu/ubuntu-15.04-snappy-core-stable
Box Url: https://atlas.hashicorp.com/ubuntu/ubuntu-15.04-snappy-core-stable
```

The issue is pretty simple, but is there any way to circumvent this? I feel like allowing <version>-stable or <version>-devel is a common practice, so why doesn't Vagrant allow versions like this?

Thanks in advance for the help!

**Comment by rcuisnier** [comment]
:+1: , I've got the same error with this one : 
https://atlas.hashicorp.com/ubuntu/boxes/ubuntu-15.04-snappy-core-edge-amd64  
> Vagrant cannot parse: '15.04-stable'  
Waiting for vagrant 1.7.3... :)

**Comment by phrozen** [comment]
You can try this one:

http://cloud-images.ubuntu.com/snappy/15.04/core/stable/current/core-stable-amd64-vagrant.box

From the official Ubuntu docs.

**Comment by sethvargo** [comment]
Hi @drmyersii 

Thank you for opening an issue. Boxes are contributed by the community. In the same way that GitHub cannot fix issue's with a user's source repository, Vagrant cannot fix issues with a third-party box. I realize this is a crappy answer, but as the other people on this thread recommended, I believe you will need to choose another box. If this is a recurring issue, we can revisit it as a bug in Vagrant, but I suspect it is a bug with that box. Thanks! :smile:
