### ISSUE TITLE
response content type header must be declared if metadata.json is hosted

### ISSUE THREAD

**Issue by hassan-k** [mitchellh/vagrant#5635]
I've noticed when you host a metadata.json file for multiple versions of vagrant boxes, the content type header must be correctly state as JSON. if it plain text, vagrant doesn't treat it as a metadata.json file.

For example, I've hosts a gist for some versions of a centos box. If I just the raw link to this file, which is provided as plain text.
```bash
$ vagrant box add https://gist.githubusercontent.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json
A name is required when adding a box file directly. Please pass
the `--name` parameter to `vagrant box add`. See
`vagrant box add -h` for more help.
```

If I provide the `--name` option as an argument it still errors out
```bash
$ vagrant box add https://gist.githubusercontent.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json --name hkhalid/centos_7.0
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format

```
When you check the response header for the url https://gist.githubusercontent.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json it provides `content-type: text/plain`

However If I use [rawgit](https://rawgit.com/) which provides the correct `content-type: application/json;charset=utf-8` Things work perfectly

```bash
$ vagrant box add https://rawgit.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json
==> box: Loading metadata for box 'https://rawgit.com/hass-isnull/e7a703dc42f0f7c9aa8e/raw/metadata.json'
==> box: Adding box 'hkhalid/centos_7.0' (v2.0.0) for provider: virtualbox
    box: Downloading: https://www.dropbox.com/s/tu0d158kbkwv1tn/centos_7.0_2.0.0.box?dl=1
==> box: Successfully added box 'hkhalid/centos_7.0' (v2.0.0) for 'virtualbox'!
```

As an improvement, I think vagrant should be able to parse the plain text version as JSON object, and error out if its broken. I know parsing can open a can worms, but being forced to use a third party service feel like jumping through an unnecessary hoop. It also puts a dependency on the availability of the third party service.

**Comment by sethvargo** [comment]
Hi @hassan-k 

Do you think this is the same issue as https://github.com/mitchellh/vagrant/issues/5413?

**Comment by hassan-k** [comment]
Hi @sethvargo,
Essentially it is the same issue. I guess the solutions suggested are different. I eventually overcame this issue by hosting the metadata file on S3 and setting the content-type header to application/json.

**Comment by mitchellh** [comment]
The reason for this is because if the URL is a box, it might be gigabytes in size. It would be really sad for Vagrant to download gigs of data just to realize that in fact, it is not JSON. The content type being JSON is a required property of the metadata.

**Comment by ibizaman** [comment]
Hi @mitchellh ,
The issue of downloading too much can be alleviated with the use of `--range` in curl, see 13872d0fd556037f3062fc9adac1f18dd9187edb and maybe https://github.com/mitchellh/vagrant/pull/5434 for more context.

**Comment by sethvargo** [comment]
@ibizaman some services don't support ranged resumes; it's up to the server to implement that, so we cannot rely on it. Vagrant _will_ try to use byte resumes, but falls back to a straight download instead.
