### ISSUE TITLE
Provide a public API for looking up the path of the original Vagrantfile

### ISSUE THREAD

**Issue by dkarlovi** [mitchellh/vagrant#5636]
I'm building a custom box which gets embedded with a Vagrantfile (repo [here](https://github.com/dkarlovi/vagrant-playground/), details [here](http://stackoverflow.com/questions/29867396/origin-vagrantfile-location-from-box-embedded-vagrantfile)) which would benefit from having the information on the location of the "origin Vagrantfile". Is there a chance of getting some sort of public API for that?

**Comment by mitchellh** [comment]
This is an interesting feature request but one we havent really had a big ask for. If we see a PR for this, I'd be happy to merge this feature, though.
