### ISSUE TITLE
Vagrant not booting after large mysql DB import

### ISSUE THREAD

**Issue by paragjagdale** [mitchellh/vagrant#5639]
I was testing my backup mysql database, so I decided to try it on my local vagrant by importing a dump of the database using the mysql command line on my vagrant machine. It took a while to import the data, and then it just hung.

I had to restart the computer. After I did, and I tried to 'vagrant up', it gave the below output.

My theory is that that MySQL starts and tries to load all it's databases. When it loads the imported database, it quickly takes up all the RAM and then the machine just won't continue loading.

How can I prevent mysql from starting in the first place?

I have data in some other databases on the same mysql install, and I'd like to get to it. That's why I'm trying to get it to work rather than creating a new one.

Here is the output and where it gets stuck:

    Bringing machine 'default' up with 'virtualbox' provider...
    [default] Clearing any previously set forwarded ports...
    [default] Fixed port collision for 22 => 2222. Now on port 2200.
    [default] Clearing any previously set network interfaces...
    [default] Preparing network interfaces based on configuration...
    [default] Forwarding ports...
    [default] -- 22 => 2200 (adapter 1)
    [default] Running 'pre-boot' VM customizations...
    [default] Booting VM...
    [default] Waiting for machine to boot. This may take a few minutes...

**Comment by sethvargo** [comment]
Hi @paragjagdale 

Can you try giving the VM more memory/cpu? You can also add `gui = true` to your Vagrantfile and VirtualBox will open the machine in gui mode and you can see if it's waiting for user input.

**Comment by sethvargo** [comment]
Closing due to no response. Please open a new issue if this is still happening and include the output in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html).
