### ISSUE TITLE
Override provision in Provider Block differing to end of Vagrant run.

### ISSUE THREAD

**Issue by thebeline** [mitchellh/vagrant#5641]
We have a Vagrantfile that executes something a little different if it is detected that the Provider is Virtual Box.  It was our hope to accomplish this via the use of `override` inside of the Provider Block, but it seems that the execution order of calls on override is a little unexpected.

Psuedo-Code:
```
Vagrant.configure("2") do |config|
  config.vm.provision :shell, inline: "echo 'BEFORE'"

  config.vm.provider "virtualbox" do |box, override|
    override.vm.provision :shell, inline: "echo 'INSIDE'"
  end

  config.vm.provision :shell, inline: "echo 'AFTER'"
end
```

Expected Output:
```
BEFORE
INSIDE
AFTER
```

Actual Output:
```
BEFORE
AFTER
INSIDE
```

Is this the expected behavior?  It would seem that any provision settings against `override` are executed at the end.  I can kind of see how this might be expected behavior, but when we expand this example to include a little more of our actual use-case:

```
Vagrant.configure("2") do |config|

  config.vm.synced_folder "./", "/var/www/#{$project}", :mount_options => ['dmode=777,fmode=777']
  
  config.vm.provider "virtualbox" do |box, override|

    # Disable the "default" Synced Folder mount (via Vagrant) in favor of VBox
    override.vm.synced_folder "./", "/var/www/#{$project}", disabled: true
    
    override.vm.provision :shell, inline: "mkdir /var/www/#{$project} -p"
	
  end
  
  # The recipes executed in here expect /var/www/#{$project} to exist,
  # but it does not.  As, while the 'synced_folder' disable is in effect, the 
  # 'mkdir' command has not executed yet.  Causing Vagrant to fail.
  config.vm.provision "chef_solo" do |chef|
    # ...
  end
end
```

Am I looking at this incorrectly, or, since the `synced_folder` override is in effect, would it not be reasonable to expect the Shell Provision to have executed at the same time as well?

**Comment by sethvargo** [comment]
Hi @thebeline 

Thank you for opening an issue. This is the expected behavior of Vagrant, so allow me to explain why. When a `Vagrantfile` is evaluated (and note that more than one Vagrantfile can be evaluated at the same time), everything is processed at once. In order to ensure overrides are actually overrides, they are applied _last_, after everything else has already been done.

Each provision block is appended to an array, so it is not possible to "override" a particular script. If you want a script that is only applied to a particular box and maintain order, you can just use the regular precedence level:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provision :shell, inline: "echo 'BEFORE'"

  config.vm.provider "virtualbox" do |box, override|
    box.vm.provision :shell, inline: "echo 'INSIDE'"
  end

  config.vm.provision :shell, inline: "echo 'AFTER'"
end
```

Does that answer your question?

**Comment by mitchellh** [comment]
I think your response is great, going to close. Should help Google-fu too.

**Comment by lionelperrin** [comment]
Hello,

I'm facing the exact same issue. Unless I'm missing something, it looks to me that
`box.vm.provision` within the provider block isn't supported anymore. 
Using a similar vagrantfile as shown in the example above, I get the following error message:
```
VirtualBox Provider:
* The following settings shouldn't exist: vm
```

**Comment by jkburges** [comment]
> it looks to me that `box.vm.provision` within the provider block isn't supported anymore

I am finding the same thing.

**Comment by mendhak** [comment]
Future searchers, use `override.`

    config.vm.provider "virtualbox" do |box, override|
        override.vm.provision :shell, inline: "echo 'INSIDE'"
    end

**Comment by shurick81** [comment]
So what you mean @sethvargo is that the block

```
Vagrant.configure("2") do |config|
  config.vm.provision :shell, inline: "echo 'BEFORE'"

  config.vm.provider "virtualbox" do |box, override|
    box.vm.provision :shell, inline: "echo 'INSIDE'"
  end

  config.vm.provision :shell, inline: "echo 'AFTER'"
end
```

will generate
```
BEFORE
AFTER
INSIDE
```

It's not what is expected though.
