### ISSUE TITLE
[1.7.2] Plugin dependency behaviour inconsistency in local vs remote installation

### ISSUE THREAD

**Issue by Temikus** [mitchellh/vagrant#5643]
I'm working on the vagrant-google provider and ran into a weird dependency issue recently.

Currently if we package the gem (bundle exec rake build) and try to install it manually into vagrant(vagrant plugin install ./pkg/vagrant-google-0.1.4.gem), we get a dependency issue (full debug log [here](https://gist.github.com/Temikus/2ea2e79dae9862315499):
```
ERROR vagrant: The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "i18n":
  In Gemfile:
    vagrant-google (= 0.1.4) ruby depends on
      google-api-client (>= 0) ruby depends on
        activesupport (>= 3.2) ruby depends on
          i18n (~> 0.7) ruby

    vagrant (= 1.7.2) ruby depends on
      i18n (0.6.11)
```
Reliance on activesupport introduced in google-api-client 0.8.0 https://github.com/google/google-api-ruby-client/commit/855c976976c98bbee406d1d394fa9941aff04363 , so this is not unexpected.
Setting the gem to 0.7.1 allows for successful plugin installation and this should be fixed by a [recent change in Vagrant](https://github.com/mitchellh/vagrant/commit/7ce6c10aa94084708c89330be0ca268e89ade8b7).

**However**, it is not released yet, so I decided to continue digging and test a couple of things out.
What I found though, was very strange.

If we simply install it by using `vagrant plugin install vagrant-google`, it **installs without any issues**.
I looked into the old version and the gemspec hasn't changed, so it installs ***along with activesupport***, but ***without*** dependency issues on i18n.

So I decided to quickly bring up my own gem server and point to it:
```
vagrant plugin install vagrant-google --plugin-source http://localhost:9292
```
Lo and behold, it installs without any issues:
```
λ vagrant plugin install vagrant-google --plugin-source http://localhost:9292
Installing the 'vagrant-google' plugin. This can take a few minutes...
Installed the plugin 'vagrant-google (0.1.4)'!
```

This is quite confusing and seems like incorrect behaviour. I suspect it may be an issue with the Bundler wrapper (/lib/vagrant/bundler.rb), however, I cannot pinpoint it exactly.

I am willing to provide any info/tests that you may need.

**Comment by Temikus** [comment]
Same happens with a newer version of our plugin, this time the conflict is with winrm-fs:
```
λ vagrant plugin install vagrant-google-0.2.0.rc1.gem
Installing the 'vagrant-google-0.2.0.rc1.gem' plugin. This can take a few minutes...
The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "logging":
  In Gemfile:
    vagrant (= 1.7.3) ruby depends on
      winrm-fs (~> 0.2.0) ruby depends on
        logging (>= 1.6.1, ~> 1.6) ruby

    vagrant (= 1.7.3) ruby depends on
      winrm-fs (~> 0.2.0) ruby depends on
        logging (>= 1.6.1, ~> 1.6) ruby

    vagrant-google (= 0.2.0.rc1) ruby depends on
      google-api-client (>= 0) ruby depends on
        googleauth (~> 0.3) ruby depends on
          logging (~> 2.0) ruby
```
As previously, no issues are experienced whatsoever when installing via rubygems:
```
λ vagrant plugin install vagrant-google --plugin-version 0.2.0.rc1                                                                                                                                                        (1)
Installing the 'vagrant-google --version '0.2.0.rc1'' plugin. This can take a few minutes...
Installed the plugin 'vagrant-google (0.2.0.rc1)'!
```

**Comment by DaedalusX** [comment]
@Temikus Have you had any success with a workaround for this? I'm on vagrant 1.7.4 and unable to install the vagrant-google plugin - experiencing that exact error regarding winrm-fs and logging version.

**Comment by Temikus** [comment]
@DaedalusX - you want to install it directly from a .gem file or are you getting the error via `vagrant plugin install`?

If it's the former, you'll need to use something like [geminabox](https://github.com/geminabox/geminabox) or `gem server` and add the gem source via `--plugin-source` to `vagrant plugin install`
Or, if you want to develop/test it - just run it via bundler (see README in our repo: https://github.com/mitchellh/vagrant-google)

If it's the latter, I cannot reproduce it:
```
λ vagrant plugin install vagrant-google
Installing the 'vagrant-google' plugin. This can take a few minutes...
Installed the plugin 'vagrant-google (0.2.1)'!
```
So, if you can, please file an issue in vagrant-google ASAP with the output of the following command attached:
```
vagrant plugin install --debug vagrant-google
```

**Comment by mitchellh** [comment]
Hi, thanks for finding this issue. This is definitely strange. Under the covers, we're just using Bundler and pointing to different paths. Vagrant itself doesn't do any of the dep resolution. I imagine this is some strange behavior with Vagrant.

For local installation, I recommend just using Bundler directly as a developer, as we document on the plugin installation page. Given that this isn't a wide spread issue since most gems are installed from repos, I'm going to close this unless we get a PR to accompany it. I'm very very sorry about this but we try to prioritize external facing issues moreso than developer issues especially if there is a workaround.
