### ISSUE TITLE
Download most recent version automated

### ISSUE THREAD

**Issue by mbrodala** [mitchellh/vagrant#5645]
While I can go to the [downloads](https://www.vagrantup.com/downloads.html) page and manually download the latest release, I'd like to have a command line option, e.g. for automated tests.

On Ubuntu the packages are usually out of date (e.g. [1.4.3 in Trusty](http://packages.ubuntu.com/trusty/vagrant)) and the RubyGem ([1.5.0](https://rubygems.org/gems/vagrant)) is apparently also not updated anymore.

So what is the suggested way to e.g. automatically retrieve the latest download URL of a package from vagrantup.com?

**Comment by fletchowns** [comment]
Maybe just scrape the directory listing and pick the last entry?

https://dl.bintray.com/mitchellh/vagrant/

**Comment by sethvargo** [comment]
@mbrodala @fletchowns our sites actually do that because Bintray doesn't have an API for "give me the latest version": https://github.com/hashicorp/middleman-hashicorp/blob/5d1edbfa4ceec20b33b501f0162e2f881afadfa9/lib/middleman-hashicorp/hashicorp.rb#L179-L218

**Comment by mbrodala** [comment]
If you want to go that way, maybe grabbing and parsing the [Github releases feed](https://github.com/mitchellh/vagrant/releases.atom) is a viable option. The `<title>` seems reliable enough to extract and use for a bintray download URI.

**Comment by fletchowns** [comment]
Might as well just use the [Github API](https://developer.github.com/v3/git/tags/) if you are gonna scrape a Github RSS feed.

**Comment by mbrodala** [comment]
True but with the feed you won't hit any rate limit.

**Comment by mitchellh** [comment]
I reocmmend using the GitHub API to fetch our tags. Those are always released versions on Bintray.
