### ISSUE TITLE
Cannot vagrant up + Virtual Box randomly - invalid state on vagrant, though GUI shows Running - Windows 8.1

### ISSUE THREAD

**Issue by arturkarczmarczyk** [mitchellh/vagrant#5646]
We are using **Vagrant** + **Virtual Box** + **puppetlabs/centos-6.6-64-puppet** box + **Windows 8.1 (x64)** for developing our projects. Almost everyday we have problems running the **vagrant up** command:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'puppetlabs/centos-6.6-64-puppet' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 443 => 8443 (adapter 1)
    default: 3306 => 3309 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'unknown' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.
```

However, the GUI says the virtual machine is just booting normally:
![image](https://cloud.githubusercontent.com/assets/12151090/7367606/d8fee14a-eda0-11e4-8054-444cb69713a8.png)

We have had this problem on several laptops, always on Windows 8.1, with various versions of VirtualBox and Vagrant. On Windows 7 it works just fine.

Here is the debug of my most recent trial to run vagrant up.

https://gist.github.com/arturkarczmarczyk/1074a22720aa5f2a9d63

And here is our Vagrantfile:
https://gist.github.com/arturkarczmarczyk/da1b00dfadaac2045f05

Sometimes after many trials it just runs okay.

Can you help us?

**Comment by witkowsky** [comment]
Hello Guys :smile: 

I have got exactly the same problem as @arturkarczmarczyk.
When We can expect resolving that bug?

**Comment by mitchellh** [comment]
This should be fixed in 1.7.3

**Comment by Carlitta87** [comment]
I am having this issue currently with vagrant 2 on windows 10. How do I resolve this?

**Comment by briancain** [comment]
@Carlitta87 - Please open a new issue and fill out the template with all of the relevant information if you are experiencing this...thank you!
