### ISSUE TITLE
Multiple Vagrant Boxes mess up the MySQL

### ISSUE THREAD

**Issue by jsmith000** [mitchellh/vagrant#5648]
I've successfully created 2 Vagrant boxes with Ubuntu 14.04 and everything seems to work fine but the MySQL (MariaDB to be exact).

I can connect to the DB through ssh but when I use a tool like HeidiSQL if I connect to the first DB I fail to connect to the second one or I connect to the first one instead (using root which got same password) :/

It seems like the localhost/127.0.0.1 mess things up?

This is my Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.hostname = "first.boxt"
  config.vm.provision :shell, :path => "provision.sh"
  config.vm.network "private_network", ip: "10.0.0.10"
  config.vm.synced_folder "db/", "/var/lib/mysql/", disabled: false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "VagrantBox1"
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50", "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
```

The 2nd box got a different hostname, IP and box name.

Any ideas what I am doing wrong? Thanks!

PS: I am trying to make 2 different boxes where 1st one will hold 5 websites that are under the same server and 2nd one 3 smaller ones which are on a small VPS.

**Comment by sethvargo** [comment]
Hi @jsmith000 

I am sorry you are having issues with Vagrant. Can you please share both complete `Vagrantfile`s?

**Comment by mitchellh** [comment]
Closing due to lack of response
