### ISSUE TITLE
Executable files are not executable

### ISSUE THREAD

**Issue by theofidry** [mitchellh/vagrant#5649]
I'm using a composer based app and after updating the dependencies, I can't run the executables (by default in `vendors/bin`. When I check the permissions, the executable permission is missing. I checked my `Vagrantfile` and I configured my sync folders as the following:

```ruby
config.vm.synced_folder ".", "/var/www/symfony-app", group: "www-data", mount_options: ["dmode=775,fmode=664"]
config.vm.synced_folder ".", "/vagrant", disabled: true
```

Obviously the `chmod` does not work and the only workaround I found is to used sudo. Aside from that, my configuration is a standard configuration using VirtualBox and Ansible. The full config file can be found [here](https://raw.githubusercontent.com/theofidry/Incipio/master/Vagrantfile).

I'm using `Vagrant 1.6.5` on `OSX 10.9.5` with `VirtualBox 4.3.20`.

**Comment by sethvargo** [comment]
Hi @theofidry 

I am sorry you are having issues with Vagrant. Are you able to try Vagrant 1.7.2 and see if the issue still persists? I am going to tag this as a bug in the meantime, but it may have been fixed in a later release.

**Comment by theofidry** [comment]
Also tested with Vagrant 1.7.2 on Ubuntu 14 and still did not work.

**Comment by mitchellh** [comment]
It appears it is because you're setting `fmode=644` which is non-executable!
