### ISSUE TITLE
Provide option for guest-to-host port-forwarding

### ISSUE THREAD

**Issue by rfkrocktk** [mitchellh/vagrant#5650]
At my company, connections to the database are tunneled over SSH. Therefore, when I want to access the database, I do something like this on my host machine:

    ssh -L 3306:localhost:3306 my.database.server.com

Great. Now I need to provide the database to my Vagrant box with an SSH remote forward:

    vagrant ssh -- -R 3306:localhost:3306

Now I've got the full chain. Local traffic on the host machine on port 3306 will be forwarded to `my.database.server.com:3306`, and I then create another remote forwarding into my Vagrant box which pushes traffic on the guest on port 3306 to the host on port 3306.

This is kind of a pain for new users. It would be really great and ease development if Vagrant could allow an option in the `Vagrantfile` to define a port forwarding from a local port on the guest to a local port on the host, basically the inverse of what it does right now for exposing guest ports to the host. 

This could be accomplished by simply having a process kick off when `vagrant up` is called which establishes a port-forwarding using SSH. Basically, in the Vagrant start phase before the provisioner is run, kick off a process like this to connect to the guest:

    ssh -R $host_port:localhost:$guest_port -P $guest_ssh_port $guest_host ... "/usr/bin/yes"

The `/usr/bin/yes` bit will keep traffic on the SSH connection to help it not get terminated. Doing the remote port forward over SSH is the easiest option, because otherwise you'll have to mess with iptables and firewall settings on both the host and guest: not good.

**Comment by acidreign** [comment]
Just curious but how does a patch to show mapped ports with `vagrant port` solve the issue of:
> It would be really great and ease development if Vagrant could allow an option in the Vagrantfile to define a port forwarding from a local port on the guest to a local port on the host, basically the inverse of what it does right now for exposing guest ports to the host.

I ran into the same issue described above and solved it using the method described above: `vagrant ssh -- -R 3306:localhost:3306`

I'd much rather have an option to do a reverse port mapping via the Vagrantfile.

**Comment by pjz** [comment]
I have the same question as @acidreign ... this should be re-opened.

**Comment by acidreign** [comment]
@pjz I was able to forward multiple ports to the vagrant box using this command: 
`vagrant ssh -- -R 33063:localhost:33063 -R 33065:localhost:33065`

Maybe it will work for your needs. 

I do think this issue should be re-opened though.

**Comment by pjz** [comment]
ssh port forwarding only works for TCP, not for UDP.  I ended up using socat to do the forwarding.
