### ISSUE TITLE
Vagrant ignores provider specified in docker.vagrant_vagrantfile

### ISSUE THREAD

**Issue by mstromb** [mitchellh/vagrant#5652]
So I have a Vagrantfile that looks like this:

```
  config.vm.define "zk1" do |zk1|
    zk1.vm.provider :docker do |d|
        d.build_dir = "foo/"
        d.force_host_vm = true
        d.vagrant_vagrantfile = "foo/1/Vagrantfile"
        d.vagrant_machine = "foo-1"
        d.name = 'foo-1'
    end
  end
```

I'm using the vagrant-openstack plugin (0.6.1) here in `foo/1/Vagrantfile`:
```
  config.vm.define "foo-1" do |zk1|
    zk1.vm.box       = 'my-openstack-box'
    zk1.vm.box_url   = 'http://path/to/my-openstack-box'
    zk1.vm.hostname  = 'foo-1'

    zk1.vm.provider :openstack do |os|
      os.username           = creds['user']
      os.password           = creds['pass']
      os.flavor             = 'GEN.cpu1.ram2G.hd50G'
      os.server_name        = 'foo 1'
    end
  end
```

When I do a `vagrant up` from inside `foo/1` things work just fine.

When I do a `vagrant up` from the root, I get this message:
```
Bringing machine 'zk1' up with 'docker' provider...
==> zk1: Docker host is required. One will be created if necessary...
    zk1: Vagrant will now create or start a local VM to act as the Docker
    zk1: host. You'll see the output of the `vagrant up` for this VM below.
    zk1:
    zk1: Box 'my-openstack-box' could not be found. Attempting to find and install...
    zk1: Box Provider: virtualbox
    zk1: Box Version: >= 0
    zk1: Adding box 'pqt-metacloud' (v0) for provider: virtualbox
    zk1: Downloading: http://path/to/my-openstack-box
    zk1: Progress: 100% (Rate: 157k/s, Estimated time remaining: --:--:--)
The box you attempted to add doesn't match the provider you specified.

Provider expected: virtualbox
Provider of box: openstack
```

As you can see, vagrant has decided to use virtualbox as the provider for the Docker host, instead of the openstack provider I configure in the `vagrant_vagrantfile`.

Setting `VAGRANT_DEFAULT_PROVIDER` to openstack for the root invocation might work, but there are required provider settings that aren't in the outer Vagrantfile, and feel like I shouldn't have to redefine them there when they're already specified in the other Vagrantfile - what if I have heterogeneous Docker hosts?

This is with version 1.7.2.
Here's the debug output: https://gist.github.com/mstromb/ac6f259987e3aaad6003

**Comment by mikedoug** [comment]
I see this using the digital_ocean provider as well.  I have multiple Virtualbox VMs defined in my Vagrantfile along with one digital_ocean vm.  Under Linux, you have to explicitly use --provider=digital_ocean when doing a vagrant up to get it to work properly.

**Comment by mitchellh** [comment]
This is fixed in master
