### ISSUE TITLE
Feature Request: Vagrant provision --provision-with=class

### ISSUE THREAD

**Issue by jtnw** [mitchellh/vagrant#5656]
Hello,

Since Vagrant 1.7 I have loved the named provisioners! In fact, before that release I had looked into the source code to see if I could do it myself as it really was a feature that I needed.

Anyway, now I am coming to a point where I could use the ability to assign a class name to     provisioners and provision with that. For example:

```ruby
config.vm.provision "bootstrap", class:"pre-setup", type: "shell" do |s|
end

config.vm.provision "setup-selinux", class:"pre-setup", type: "shell" do |s|
end

config.vm.provision "install-magento-libs", class:"install-project", type: "shell" do |s|
end

config.vm.provision "install-magento", class:"install-project", type: "shell" do |s|
end

config.vm.provision "restore-db", class:"install-project", type: "shell" do |s|
end

config.vm.provision "backup-db", class:"update-project", type: "shell" do |s|
end

config.vm.provision "update-cms-pages", class:"update-project", type: "shell" do |s|
end

config.vm.provision "generate-reports", class:"update-project", type: "shell" do |s|
end
```

Of course it is possible to unintentionally set a class equal to the type value of another provisioner. Right now, that can happen between the type and name (i.e. someone names a provisioner shell or host-shell) and I do not think it would be a big deal if it was left to the user to not have conflicts if it was documented. Alternatively, maybe the command line arguments for --provision-with could need a special character preceding the class name to distinguish.

Please let me know what you think.

**Comment by mitchellh** [comment]
We'd look at a PR for this but haven't had a big enough request to build this ourselves. There are also many workarounds that can be done (by using args to a single larger shell script for example). I think Vagrant might not be the best place for this.
