### ISSUE TITLE
Couldn't Vagrant Up the machine

### ISSUE THREAD

**Issue by harishkumar93** [mitchellh/vagrant#5659]
Hi,

When I'm trying to run the Vagrant  UP command in my terminal I'm getting the following error.

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period. This can
mean a number of things.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by sethvargo** [comment]
Hi @harishkumar93 

Thank you for opening an issue. Could you please run the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html) and gist the output here?

**Comment by CptLausebaer** [comment]
I think I have the same problem,

when I run the `vagrant up` command, vagrant will boot the machine and I get the following output: 

        Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Checking if box 'maddhatter/windows-2012r2' is up to date...
    ==> default: Clearing any previously set forwarded ports...
    ==> default: Fixed port collision for 5985 => 55985. Now on port 2201.
    ==> default: Fixed port collision for 22 => 2222. Now on port 2202.
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
        default: Adapter 2: hostonly
    ==> default: Forwarding ports...
        default: 5985 => 2201 (adapter 1)
        default: 22 => 2202 (adapter 1)
    ==> default: Running 'pre-boot' VM customizations...
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...

And then vagrant hangs and quit with the message:

    Vagrant was unable to communicate with the guest machine within
    the configured ("config.vm.boot_timeout" value) time period.
    
    If you look above, you should be able to see the error(s) that
    Vagrant had when attempting to connect to the machine. These errors
    are usually good hints as to what may be wrong.
    
    If you're using a custom box, make sure that networking is properly
    working and you're able to connect to the machine. It is a common
    problem that networking isn't setup properly in these boxes.
    Verify that authentication configurations are also setup properly,
    as well.
    
    If the box appears to be booting properly, you may want to increase
    the timeout ("config.vm.boot_timeout") value.

But the box has started normally.
I'm using Uuntu 14.04 as my host-machine and other boxes work fine. This issue appears only if I try to `vagrant up` windows as a guest.

I have create a gist with my Vagrantfile and the debug output:
https://gist.github.com/CptLausebaer/3e9e9ce8bc2e8ea94b2c

**Comment by mitchellh** [comment]
Please ask the mailing list for support. Based on the log, this isn't a Vagrant issue: SSH never becomes available in the VM. Are you installing SSH? Configuring it to start? etc.

**Comment by joycesunz** [comment]
@CptLausebaer did you solve this problem?
