### ISSUE TITLE
puppet.facter throwing errors when cumulative length of variable to pass is too long

### ISSUE THREAD

**Issue by fabio-naddafi** [mitchellh/vagrant#5660]
When trying to do a vagrant up with facter values that total to over 4000 characters, the build breaks with random errors depending on which part is curtailed.

An example error being "could not find file: /tmp/vagrant-puppet-2/mani"

This is the section from debug that is being passed through and fails if total length is too long:

Execute: FACTER_host_name='xx123' FACTER_fqdn='xx123.domain.com' FACTER_variable1='variablevalue'

**Comment by sethvargo** [comment]
Hi @fabio-naddafi 

Could you please share your Vagrantfile as well as the output of the Vagrant run [in debug mode](http://docs.vagrantup.com/v2/other/debugging.html) in a gist? Thanks!

**Comment by fabio-naddafi** [comment]
Vagrantfile: https://gist.github.com/fabio-naddafi/c8dbc079b7fb51b3d9e5

Vagrant up debug output: https://gist.github.com/fabio-naddafi/89f6172c2b73fd81c7db

**Comment by mitchellh** [comment]
This makes sense to me. We pass Facter variables in through env vars, and you probably passed the max command length. 

There is probably a better way.

**Comment by benh57** [comment]
Implemented structured facts which should fix this.

https://github.com/mitchellh/vagrant/issues/4762

I can submit a PR for this if it looks like a good solution.

**Comment by mitchellh** [comment]
@benh57 If you could submit a PR we'd love it!

**Comment by mitchellh** [comment]
I'm going to close this in favor of #4762 just fixing this.
