### ISSUE TITLE
Can't update or install plugins after upgrading Vagrant to version 1.7.2

### ISSUE THREAD

**Issue by dkinzer** [mitchellh/vagrant#5662]
When I try to update or install a plugin after updating to vagrant version 1.7.2 I get the following error:

```
Updating installed plugins...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:620:in `block in try_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:613:in `with_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:619:in `try_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1725:in `pkg_config'
	from extconf.rb:15:in `<main>'


Gem files will remain installed in /home/dkinzer/.vagrant.d/gems/gems/ffi-1.9.8 for inspection.
Results logged to /home/dkinzer/.vagrant.d/gems/gems/ffi-1.9.8/ext/ffi_c/gem_make.out
```

I am using Ubuntu 14.04 on a 64 bit machine.

```
Linux linux 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by sethvargo** [comment]
Hi @dkinzer 

Do you have build-essential installed?

**Comment by dkinzer** [comment]
I believe I do, since I can run `gem install ffi -v '1.9.8'` without issue.  Note, I am using rbenv.

**Comment by sethvargo** [comment]
Hi @dkinzer 

How have you installed Vagrant? Is it installed as a gem or via the official installer?

**Comment by dkinzer** [comment]
@sethvargo, I downloaded from vagrantup.com and ran the following command:

`dpkg -i /home/dkinzer/Downloads/vagrant_1.7.2_x86_64.deb`

Note, I did not uninstall the previous version of vagrant prior to doing this since it has not been an issue for me before.

**Comment by sethvargo** [comment]
@dkinzer okay, can you try removing (or just moving) the `~/.vagrant.d` directory and trying again?

**Comment by dkinzer** [comment]
@sethvargo Thanks! this seems to work for new installations and updates of newly installed plugins.  Should I manually re-install my old plugins?

**Comment by dkinzer** [comment]
@sethvargo  Hmm.. also, would love to be able to move my boxes over too or will this not cause issues with current running boxes, including aws provided ones?

**Comment by sethvargo** [comment]
Hi @dkinzer 

You can try re-installing old plugins, but do it one-at-a-time so we can isolate the issue if it rises again.

You can move the boxes over (they are in ~/.vagrant.d). Unfortunately I do not know about the AWS boxes - I assume it is just metadata somewhere in that directory.

**Comment by dkinzer** [comment]
@sethvargo I was able to re-install all plugins without issue.  Is it possible that the the fact the vagrant_version is specified in plugins.json is contributing to the cause of this issue?

**Comment by sethvargo** [comment]
Hi @dkinzer 

It's possible than an older version of a plugin (since the plugin re-installation pulls in the latest version) had a bad dependency constraint - that was my first guess, but instead of trying to identify that plugin, it's easier just to wipe them all and start clean. Make sense?

**Comment by dkinzer** [comment]
@sethvargo, yup.  Thanks for your help I guess this is resolved.  I'll move boxes over from old ~/.vagrand.d folder and cross my fingers that everything stays cool.
