### ISSUE TITLE
Vagrant attempted to execute the capability 'mount_nfs_folder' on the detect guest OS 'windows',

### ISSUE THREAD

**Issue by mihai-satmarean** [mitchellh/vagrant#5664]
Vagrant 1.7.2 and using windows 7 Enterprise as guest and Ubuntu 12-04 as host, the NFS is enabled in windows and it can mount using windows mount command but at vagrant up I get the following: 

```
Vagrant attempted to execute the capability 'mount_nfs_folder' on the detect guest OS 'windows',
```

**Comment by mitchellh** [comment]
The Windows guest does not know how to mount NFS folders at this time. If you know how to make this happen, please give us the steps and we can add it. Otherwise, this isn't a bug (just a missing feature).

**Comment by mihai-satmarean** [comment]
Windows 7 Enterprise and other newer windowses have a feature Sevices for NFS or sometimes called Subsystem for UNIX-based Applications. With this feature enabled the mount is pretty straigth forward 

`mount [–oOptions] ComputerName:\ShareName {DeviceName | *}` 

as explained here: https://technet.microsoft.com/en-us/library/cc754350.aspx

I would help more, but I am not a developer. 
I would gladly test watherver you can give me and tell you how it works.

Thank you!
