### ISSUE TITLE
Warn if ifconfig is not found on host (net-tools)

### ISSUE THREAD

**Issue by jevonearth** [mitchellh/vagrant#5665]
Some distros no longer ship with ifconfig (arch) and this needs to be installed (net-tools package).

When the ifconfig command is not present, vagrant does not complain, the vboxnet0 interface does not get a ip assigned. 

If would be useful if vagrant complained loudly when ifconfig is not available.

**Comment by mitchellh** [comment]
Vagrant no longer requires ifconfig for arch. Thanks!
