### ISSUE TITLE
config.vm.hostname for Ubuntu 15.04 fails

### ISSUE THREAD

**Issue by jameskyle** [mitchellh/vagrant#5673]
Error below. The hostname service is masked in ubuntu 15.04, the recommended way to control the hostname seems to be hostnamectl.

    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!
    
    service hostname start
    
    Stdout from the command:
    
    
    
    Stderr from the command:
    
    sudo: unable to resolve host ubuntu-1504
    stdin: is not a tty
    Failed to start hostname.service: Unit hostname.service is masked.

**Comment by ev0rtex** [comment]
I'm having the same issue. I just tried with 15.04 today and got this.

**Comment by matthiss** [comment]
I've tried
>sudo systemctl unmask hostname.service

it seems everything ok, no errors, but if i want to start the service, it is still masked.

Any ideas?

**Comment by jklare** [comment]
having the same issue

**Comment by devjatkin** [comment]
I got the same error message. On my Ubuntu VM ( based on image from cloud.ubuntu) I saw the next:
```shell
sudo systemctl status hostname
● hostname.service
   Loaded: masked (/dev/null)
   Active: inactive (dead)
```
```shell
ls -la /lib/systemd/system/hostname.service 
lrwxrwxrwx 1 root root 9 Apr 18 21:11 /lib/systemd/system/hostname.service -> /dev/null
```
As temporary workaround it is possible to use /etc/init.d/hostname.sh

**Comment by servomac** [comment]
+1 here

tpiza@vps173984:~/cv$ sudo service hostname restart
Failed to restart hostname.service: Unit hostname.service is masked.

**Comment by nserban** [comment]
I encounter the same problem reported by @jameskyle but on a Debian Wheezy, after an apt-get update ; apt-get upgrade .

```
root@local:~# uname -a
Linux local 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linu
```

I retested with a upgraded Debian box 7.8, the creation of the VM is working fine, but after a vagrant halt and vagrant up with this line in Vagrantfile 
```
config.vm.hostname = "local.supercool.com"
```
I encounter the same problem. 

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f

Stdout from the command:



Stderr from the command:

sudo: unable to resolve host local
stdin: is not a tty
hostname: Name or service not known
```

Here are the Vagrant Log:
```
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f

Stdout from the command:



Stderr from the command:

sudo: unable to resolve host local
stdin: is not a tty
hostname: Name or service not known

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f

Stdout from the command:



Stderr from the command:

sudo: unable to resolve host local
stdin: is not a tty
hostname: Name or service not known

 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The following SSH command responded with a non-zero exit status.\nVagrant assumes that this means the command failed!\n\nhostname -f\n\nStdout from the command:\n\n\n\nStderr from the command:\n\nsudo: unable to resolve host local\nstdin: is not a tty\nhostname: Name or service not known\n"]
```

**Comment by eckz** [comment]
It seems like the only work-around for now is

```ruby
#host.vm.hostname = "skynet"
host.vm.provision :shell, inline: "hostnamectl set-hostname skynet"
```

**Comment by thasmo** [comment]
Encountering the same on Ubuntu 15.04.

**Comment by born4new** [comment]
Same here. Can't wait to see the fix!

**Comment by majidaldo** [comment]
yup

**Comment by czerasz** [comment]
After updating to `Vagrant 1.7.4` everything works fine. Tested with [ubuntu/vivid64](https://vagrantcloud.com/ubuntu/boxes/vivid64)

**Comment by Solutron** [comment]
@czerasz version upgrade to `Vagrant 1.7.4` fixed the issue for me as well with ubuntu/vivid64

**Comment by jgoldschrafe** [comment]
This is breaking again on the Wily betas. Can we have a better fix that doesn't rely on checking the codename of one specific release?

**Comment by markwoon** [comment]
Still broken with ubuntu/wily and vagrant 1.7.4...

**Comment by luebken** [comment]
>Still broken with ubuntu/wily and vagrant 1.7.4...

+1

I saw it fixed for vivid but came up again for wily.

**Comment by rogerhu** [comment]
PR'd https://github.com/mitchellh/vagrant/pull/6470 -> avoids hard-coding Ubuntu distribution names

**Comment by rogerhu** [comment]
Closed and reopened: https://github.com/mitchellh/vagrant/pull/6471

**Comment by nubae** [comment]
Problem is also there in  16.04 (fix #6470 does not work):
root@ns399965:/tmp/ispconfig3/install# hostnamectl set-hostname ns1
root@ns399965:/tmp/ispconfig3/install# sudo systemctl status hostname
● hostname.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)
root@ns399965:/tmp/ispconfig3/install#

**Comment by nubae** [comment]
workaround:
root@ns399965:/tmp/ispconfig3/install# sh /etc/init.d/hostname.sh
root@ns399965:/tmp/ispconfig3/install# hostname -f
ns1.soulternative.eu

**Comment by reedloden** [comment]
@nubae can you file a new issue, please?

**Comment by reedloden** [comment]
@nubae actually, https://github.com/mitchellh/vagrant/issues/7288 is this, no?

**Comment by nubae** [comment]
@reedloden yup that seems to be the same issue... still need to re-file a new issue or not?

**Comment by awibmer** [comment]
@ravishtiwari Upgrading to Vagrant 1.9.1 solved this for me.

**Comment by ravishtiwari** [comment]
@awibmer - I've recently upgraded to _Vagrant 1.9.1_ will confirm if the issue is fixed for me as well. 

Thanks

**Comment by jeunito** [comment]
Upgrading to 1.8.5 solved this for me

**Comment by ravishtiwari** [comment]
@awibmer - upgrading to 1.9.1 has resolved this for me as well, thanks for your help.

**Comment by daBONDi** [comment]
Im now on vagrant 2.2.1 and have the same problem now
