### ISSUE TITLE
rsync-auto incremental copy

### ISSUE THREAD

**Issue by driskell** [mitchellh/vagrant#5674]
Currently, rsync-auto currently triggers a synchronisation of the entire folder for every small change. Is there a reason why, for modifications/additions, it should not just do a transfer of changed entries reported by listen? `rsync` can read files from stdin using `--from-file=-` argument so a list could be provided. Running some tests this seems to improve responsiveness of changes for large folders as it need not scan through thousands of files that haven't changed.

For removals, however, a full synchronisation is needed still as there's no way to tell `rsync` to delete files.

I'm working on a patch at the moment that will do this by default, and have a `--no-incremental` option to stop it. I'd like to garner some feedback on this idea.

**Comment by driskell** [comment]
Over at the listen repository there's some big work on fixing performance and consistency of the listen gem on Mac. Specifically preventing unnecessary recursion in large tree structures that can generate extremely high CPU usage, and inconsistent add/changed/removed results when sub folders are renamed.

Until the last bit of the above is completed best to not do incremental rsync as in the sub folder case it can mean the old name for the au folder still exists in the VM.

I do have a working patch though and will link it here soon for others to play with but won't raise PR till listen gem is happy :+1:

**Comment by mitchellh** [comment]
Hey @driskell. Thanks! Please do open a PR when you have it ready, you seem to have a better handle on this. We're going to continue to try to improve the rsync performance but going to close this until you have a PR since this isn't the exact thing we'll be tackling right now.
