### ISSUE TITLE
vmware_fusion; ubuntu14.04LTS box won't start

### ISSUE THREAD

**Issue by nap82** [mitchellh/vagrant#5675]
Here's the VAGRANT_LOG gist output:  https://gist.github.com/c801bff35e475a35ec43.git
I'm using VMWare Fusion v6.0.5, latest Vagrant build (just downloaded the other day) and Mac OS X 10.10.3.  When I run `vagrant up` I get the following output/feedback:

```Stderr: 
An error occurred while executing 'vmrun', a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "/Volumes/LaCie/Vagrant/.vagrant/machines/default/vmware_fusion/567e8798-09c4-45f0-a765-014aeca6a986/owz.vmx", "nogui", {:notify=>[:stdout, :stderr]}]

Stdout: Error: Cannot open VM: /Volumes/LaCie/Vagrant/.vagrant/machines/default/vmware_fusion/567e8798-09c4-45f0-a765-014aeca6a986/owz.vmx, Cannot read the virtual machine configuration file
```

**Comment by nap82** [comment]
[UPDATE] Gist location :: https://gist.github.com/nap82/c801bff35e475a35ec43

**Comment by nap82** [comment]
[UPDATE-1] --debug output
https://gist.github.com/nap82/1a7103da86a0c12514d6

**Comment by sethvargo** [comment]
Hi @nap82 

Thank you for opening an issue. I am sorry you are having issues with the Vagrant VMware Fusion provider. It looks like the permissions on the cache file may have changed. Can you please try restarting your computer and removing the `/Volumes/LaCie/Vagrant/.vagrant` directory? Thanks! :smile:

**Comment by mitchellh** [comment]
The error message out of VMware is somewhat telling. This seems like some odd permissions error. Can you check the permissions on that file as well?

Closing due to lack of response but will open with one.
