### ISSUE TITLE
Consistent crashing since upgrading to 20150422.0.1

### ISSUE THREAD

**Issue by foxx** [mitchellh/vagrant#5678]
I've raised the bug report with dmesg [here][1]. Is anyone else having similar issues?

[1]: https://www.virtualbox.org/ticket/14089

**Comment by sethvargo** [comment]
Hi @foxx 

Can you please provide additional information such as a `Vagrantfile` or [debug output](http://docs.vagrantup.com/v2/other/debugging.html)? There is not enough information here to diagnose the issue and the link you have provided is currently under maintenance mode.

**Comment by mitchellh** [comment]
Closing due to lack of response, but also I think this is an upstream.
