### ISSUE TITLE
when i use this cmd : sudo ssh-add ~/.vagrant.d/insecure_private_key Could not open a connection to your authentication agent.

### ISSUE THREAD

**Issue by ainux4mrvce** [mitchellh/vagrant#5681]

**Comment by sethvargo** [comment]
Hi @ainux4mrvce 

Thank you for opening an issue. There is not enough information here to diagnose the problem and the description does not seem to be an issue with Vagrant. You may need to run `ssh-agent sh -c 'ssh-add ...'` to ensure the agent is running.
