### ISSUE TITLE
Docker provisioner fails on Oracle Enterprise Linux 7 virtual box: usermod: group 'docker' does not exist

### ISSUE THREAD

**Issue by tkleiber** [mitchellh/vagrant#5686]
Hi!

Following should install docker and pull an image on the box, but docker install fails:

Vagrant.configure(2) do |config|
  config.vm.box = "oraclelinux-7-x86_64.box"
  config.vm.box_url = "http://cloud.terry.im/vagrant/oraclelinux-7-x86_64.box"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.name = "OEL 7.1 Development Server"
   end
  # install base docker image (Oracle Enterprise Linux 7.1)
  config.vm.provision "docker" do |d|
    d.pull_images "oraclelinux:7.1"
  end
end

The error is:

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
usermod -a -G docker vagrant
Stdout from the command:
Stderr from the command:
usermod: group 'docker' does not exist

I think the group docker should be created by the provisioner too?

Best regards
Torsten

**Comment by fabiocorneti** [comment]
It seems to have been solved in https://github.com/mitchellh/vagrant/commit/be2643d40d68c1db650175017ce8e770ce4da101; as a temporary workaround you could try creating the group  in `Vagrantfile` before the docker provisioner block:

```ruby
  config.vm.provision "shell" do |s|
    s.inline = "groupadd -f docker"
  end
```

**Comment by mitchellh** [comment]
Fixed in master
