### ISSUE TITLE
Vagrant from the source won't start 

### ISSUE THREAD

**Issue by rahsd** [mitchellh/vagrant#5688]
I compiled vagrant from the git source and I installed it.
~~~
$ bundle install
$ sudo rake install
~~~
but now I can't run vagrant. by itself vagrant command returns  not found. I searched for vagrant  and found it in gem directory.
that has a problem too:

~~~
userone1@slitaz:~/.bundler/ruby/2.2.0 $  /home/userone1/.bundler/ruby/2.2.0/bin/vagrant -v
/usr/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'vagrant' (>= 0) among 11 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/userone1/.gem/ruby/2.2.0:/usr/lib/ruby/gems/2.2.0', execute `gem env` for more information
	from /usr/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
	from /usr/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /home/userone1/.bundler/ruby/2.2.0/bin/vagrant:22:in `<main>'
~~~
please advise me on how to proceed?

**Comment by mitchellh** [comment]
Vagrant must run from its installer. It only supports source running for development.

**Comment by rahsd** [comment]
how exactly? I did it exactly as you posted in your wiki "compile from source"

**Comment by mitchellh** [comment]
Ah I'm sorry, the correct instructions are in the README. I wasn't even aware there was a wiki it must've been started by the community, but it isn't officially maintained.

**Comment by rahsd** [comment]
mitchellh;
from this https://github.com/mitchellh/vagrant/wiki/Installing-Vagrant-from-source
I did build and installed vagrant ( or I think I did). but I don't have vagrant in my $PATH on my linux system.
my linux doesn't have vagrant package in my linux epo so I have to build it.
do I have vagrant installed right now?

**Comment by mitchellh** [comment]
If you're just trying to install Vagrant and not develop it, please download a binary package from vagrantup.com 

If you're on a system where we don't provide a binary package, I apologize but Vagrant isn't currently made to run outside of the installer system. You can get it to work with some creativity but it isn't something we're interested in supporting right now.
