### ISSUE TITLE
Vagrant on Ubuntu 15.04 network interfaces.

### ISSUE THREAD

**Issue by jarrettj** [mitchellh/vagrant#5689]
Hi,

Good day.

Since upgrading to Ubuntu 15.04 the vagrant network interface does not persist when coming out of suspend.

```
Repro:
vagrant up # I use hostmanager to handle hosts file
# Browsing to test site works
vagrant suspend # Suspend environment
vagrant up # Bring out of suspended state
# Browsing to test site does not work
```

You will not be able to access your test site. The network interface is gone. You have to reload the entire environment to get to your test sites.

This happens when you suspend your system as well.

Cheers.

**Comment by ylarrivee** [comment]
I confirm this bug. All network cards gets deleted once you reload the virtual machine.

**Comment by dougmartin** [comment]
This also happens on my 15.04 system with v 1.6.5 (the stable version in the Ubuntu repos).

Here is the before and after suspend view of the interface

After suspend is resumed:

          vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:751 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:209264 (209.2 KB)

After vagrant reload:

          vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00  
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::800:27ff:fe00:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:821 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:219173 (219.1 KB)

**Comment by hackel** [comment]
This is also happening with Vagrant 1.7.2+dfsg-4.  I read another report that this was possibly related to the systemd changes in 15.04, and may be a bug in Virtualbox itself.

**Comment by hackel** [comment]
FYI, this has been reported here: https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1460750
Again, I don't believe this is a Vagrant issure, but rather specific to Virtualbox on Ubuntu 15.04 with systemd.  A simple "ifconfig vboxnet0 192.168.10.1" restores connectivity for me without restarting the guest.

**Comment by mitchellh** [comment]
Agreed upstream.
