### ISSUE TITLE
Docs clarity: config.vm.box_check_update

### ISSUE THREAD

**Issue by dogweather** [mitchellh/vagrant#5692]
I'm pretty confused by this text from the [Vagrantfile template](https://github.com/mitchellh/vagrant/blob/9c55180f6d63f6160bcc7da3bfdb56824db945ff/templates/commands/init/Vagrantfile.erb#L22):

```ruby
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user run
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false
```

I'll edit this in a PR but first need help figuring out what it means:

* When set to false, as is the default, then update checking is disabled, correct?
* The comment says that this default setting is _not recommended_. (?)

**Comment by sethvargo** [comment]
Hi @dogweather 

The default value is `true`, which tells Vagrant to ask the upstream if a new box version is available. The commented value indicates the opposite of the default value, so uncommenting would _invert_ the default behavior. Does that make sense?

**Comment by dogweather** [comment]
Ah hah! That helps. I'm used to seeing the _default_ value in commented-out form like this. E.g., Sublime Text and Rails configs. So I'd recommend changing it to follow that convention. Also, I'd submit a PR changing the text to be a bit clearer:

```
# Set to false to disable automatic box update checking. If you do this, ...
```

**Comment by sethvargo** [comment]
Hi @dogweather 

The convention in Vagrant is the opposite though, so I do not think we could change that or else it would be conflicting.

**Comment by dogweather** [comment]
Ok, makes sense.
