### ISSUE TITLE
add option to retrieve port from ssh-config subcommand

### ISSUE THREAD

**Issue by krichter722** [mitchellh/vagrant#5696]
Currently `vagrant ssh-config` prints a whole set of information, but doesn't allow to retrieve values of options, like "port", individually (at least `vagrant ssh-config -h` prints 

    $ vagrant ssh-config -h
    Usage: vagrant ssh-config [options] [name]
    
    Options:
    
            --host NAME                  Name the host for the config
        -h, --help                       Print this help

)

**Comment by mitchellh** [comment]
Please use `sed`, `awk`, etc. to do this. I don't think we need to do this directly. Alternatively, you can use the `--machine-readable` output to get this as well.
