### ISSUE TITLE
First container always exited with Exit(0)

### ISSUE THREAD

**Issue by defender** [mitchellh/vagrant#5700]
HI using Docker and Vagrant

```text
Vagrant version is  1.7.1
config.vm.provision "docker" do |d|
                        #if config.user.dockers.registry.enabled == true
                        #       d.pull_images "myd-vm00941.hpswlabs.adapps.hp.com:5000/cadvisor:1.0.0"
                        #end
d.run "cadvisor", auto_assign_name: false,
                                args: "--name=cadvisor --privileged=true  --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --volume=/cgroup:/cgroup:ro --volume=/etc/localtime:/etc/localtime:ro -p 8100:8080",
                                image: "myd-vm00941.hpswlabs.adapps.hp.com:5000/cadvisor:1.0.0"
                endt
```

After fct5 second container is exited (0)

Tried different container same behavior.
In fcase im running vagrant provision is working perfect
When vagrant shh and run docker start for the stopped container working perfect

I tried with 1.6.3 and working perfect

What was changed ?

Thanks.

**Comment by mitchellh** [comment]
Can you please show us the debug log for this? I tried with some other images and couldn't reproduce this so I'm guessing it is specific to how this image is started.
