### ISSUE TITLE
Vagrant

### ISSUE THREAD

**Issue by AdamDunlop** [mitchellh/vagrant#5703]
I'm having trouble with DevOps and installing vagrant on my PC. 
 

```
PS C:\Users\Adam> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```

Couldn't open file /Users/Adam/base

can anyone help me?

**Comment by jimklo** [comment]
This really isn't the right place, for this, but this is likely your issue:

1. You are missing a Vagrantfile. Say you want to launch the ubuntu/trusty64 from Atlas:

```vagrant init ubuntu/trusty64```

will generate a skeleton Vagrantfile.

2. Now do a `vagrant up`. The box will download and then get provisioned.

If your DevOps has given you a Vagrantfile, you should be able to use it as well (along with any other provisioning scripts that Vagrantfile depends).  Usually one stores all this in SCM like SVN or Git and you just checkout or clone that project locally and then to a `vagrant up` from the root of that checked out directory. https://github.com/scotch-io/scotch-box is an example of such a project.

**Comment by sethvargo** [comment]
Hi @AdamDunlop 

Please see the documentation and quick start guide on vagrantup.com. For usage-related questions. please use the Vagrant mailing list. Thanks!
