### ISSUE TITLE
Missing trusty64 image for VMware fusion

### ISSUE THREAD

**Issue by foxx** [mitchellh/vagrant#5705]
After spending $79 for a vmware fusion license, I have now discovered that no trusty64 box exists for vmware-fusion, instead forcing me back to precise64, which is very much outdated. Are there any known workarounds, or plans to fix this? I'd hate to request a refund, but this is almost useless to me now :/

**Comment by sethvargo** [comment]
Hi @foxx 

I am sorry you are having issues with the VMware Fusion provider. I see that you have emailed our support team. I am going to close this ticket and our support team will handle the issue. Thanks!
