### ISSUE TITLE
Vagrant, VirtualBox and Adapter 1 HostOnly - Adapter 2 NAT

### ISSUE THREAD

**Issue by nirving** [mitchellh/vagrant#5708]
I am having an issue with a deployment where it is picking up the IP Address assigned to ETH0 within a VirtualBox vm and using it as the default IP Address for its communication. I have configured a Host Only network in the Vagrantfile which gets attached to Adapter 2 and is configured in the VM as ETH1.

All I want to do is swap the order around, so that Adapter 1 is HostOnly and Adapter 2 is NAT. This way the application will pick my HostOnly IP as the default and then other hosts can communicate correctly, as currently the IP Address 10.0.2.15 of Adapter 1 is the same on all hosts. In effect when the installer tries to connect to the 192.168.x.x address it gets told the actual address to connect to is 10.0.2.15 and since this is the IP address on the client host it tries to connect to itself and fails.

In order to change this behaviour in the Installation I would need Oracle to update it and give an option to choose the listen address. I can of course try and develop a workaround. I.E install the Server application, stop it, update it configuration and restart it, but it seems a long way around when all I need to do is change the order of the adapters.

**Comment by mitchellh** [comment]
Vagrant requires adapter 1 be NAT. This is a hard requirement of Vagrant that we'd love to fix but haven't yet.
