### ISSUE TITLE
Automatic chef installation ignores system package

### ISSUE THREAD

**Issue by rsteube** [mitchellh/vagrant#5710]
The check in https://github.com/mitchellh/vagrant/commit/f232dc38c93b4f4f1e7301a595f9b8c235f82b86 expects knife to be installed to `/opt/chef/bin/knife` (Omnibus package).
An existing installation using the package provided by Ubuntu 14.04 is thus ignored and chef is reinstalled using Omnibus.

Explicitly skipping the automatic installation works, but is this the intended behaviour?
```ruby
  config.vm.provision :chef_solo do |chef|
    chef.install = false
```

**Comment by sethvargo** [comment]
Hi @rsteube 

The recommended way to install Chef is using the Omnibus system exposed by Chef Software. Installing the OS-native packages is usually outside of the recommended way to install and manage Chef. We explicitly look for `/opt/chef/bin/knife` to _ensure_ the Omnibus Chef is the one being used. We also allow you to specify a version of, which would be very difficult if we used OS-level packages, especially cross-platform.

As such, we _do intentionally_ ignore any other Chef's that may be on the system. If you would like to skip installation, you are correct in using the `chef.install = false` option. Thanks!
