### ISSUE TITLE
Inconsistant naming for VMWare provider

### ISSUE THREAD

**Issue by gjngeldenhuis** [mitchellh/vagrant#5711]
When adding and removing a box using vagrant box add this would be a typical error message:
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.

Name: mybox71
Provider: vmware_desktop

Note that the provider is called: vmware_desktop

However when referring to the same provider in the Vagrantfile you have to specify:

```
  config.vm.provider "vmware_fusion" do |vb|
    vb.gui = true
  end
```

Now the provider is suddenly called vmware_fusion. Some more consistency here would be great, in fact not having to specify provider would be even better. I mean really why should I care if it is VMWare or Virtualbox all I want to see is a console.

**Comment by sethvargo** [comment]
Hi @gjngeldenhuis 

You should use `vmware_desktop`. In the past `vmware_workstation` and `vmware_fusion` have been _different_ types, but we are working to unify them. 

You need to specify a provider because Vagrant supports multi-provider vagrantfiles (i.e. it's possible to bring up a machine with different providers). Consider the following:

```
$ vagrant box list
hashicorp/precise64 (virtualbox, 1.1.0)
hashicorp/precise64 (vmware_desktop, 1.1.0)
```

I have two boxes named "hashicorp/precise64", once for vbox, one for desktop. If I do not specify the provider in the Vagrantfile, Vagrant would not know which box to use :smile:.

Does that make sense?

**Comment by gjngeldenhuis** [comment]
@sethvargo vmware_desktop gets completely ignored when I do: 
  config.vm.provider "vmware_desktop" do |vb|
    vb.gui = true
  end

I have to have vmware_fusion for the VMWare Fusion console to appear when I do a vagrant up on the machine.

I am using VMWare Fusion 7.1.1 and Vagrant 1.7.2

**Comment by sethvargo** [comment]
@gjngeldenhuis what box are you using? The box itself declares its type. If you are using an older box, it may have declared itself as vmware_fusion, in which case unfortunately you need to specify as such. You can also do the following

```
%w(vmware_fusion vmware_workstation vmware_desktop).each do |provider|
  config.vm.provider provider do |p|
    p.gui = true
  end
end
```

**Comment by sethvargo** [comment]
Ping @gjngeldenhuis. Do you have any questions?

**Comment by gjngeldenhuis** [comment]
@sethvargo sorry for the delay. I am using my own box that has been build using packer and vmware fusion( latest version )

**Comment by sethvargo** [comment]
Hi @gjngeldenhuis 

If you specify the output type as vmware_desktop, then it will be so :smile:, but if you specify as vmware_fusion/workstation, you must specify that in the Vagrantfile. The snippet above should work for all cases (and is what we use internally) :smile: 

Please let me know if you have any questions!
