### ISSUE TITLE
Plugins cannot be installed when VAGRANT_HOME not at $HOME/.vagrant.d

### ISSUE THREAD

**Issue by jimklo** [mitchellh/vagrant#5714]
On OS X 10.10.3 using Vagrant 1.7.2.

Due to space limitations, I defined VAGRANT_HOME on an external USB 3.0 drive (HFS+ formatted) since all the box files are stored there and consume quite a bit of space.

I've discovered that in doing so, I can no longer install any vagrant plugins.  They all end up with the same error like the following:

```
$ export VAGRANT_HOME=/Volumes/Passport/.vagrant.d
$ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir': parent directory is world writable but not sticky (ArgumentError)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:510:in `try_link0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:427:in `have_devel?'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:433:in `try_do'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:549:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:502:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:549:in `try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1044:in `block in have_header'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1043:in `have_header'
	from extconf.rb:16:in `<main>'


Gem files will remain installed in /Volumes/Passport/.vagrant.d/gems/gems/ffi-1.9.8 for inspection.
Results logged to /Volumes/Passport/.vagrant.d/gems/gems/ffi-1.9.8/ext/ffi_c/gem_make.out
```

Not quite sure what to do.  It will permit me to install the plugin using sudo, but once I do that - in order to access the plugin, I must use sudo with `vagrant up`. This isn't a solution because then the provisioned VM is now owned by root.

**Comment by sethvargo** [comment]
Hi @jimklo 

I think this is actually a limitation of Ruby, not Vagrant. Ruby cannot cross-compile native extensions that live on a different drive. Can you move your entire Vagrant installation onto that drive instead?

**Comment by jimklo** [comment]
That's not exactly ideal - but I could try.  I wonder if there is a way to Monkey Patch [isolated_environment.rb](https://github.com/mitchellh/vagrant/blob/efd1d5e11bfc5a72c7a1d1eae294b4751d841544/test/unit/support/isolated_environment.rb#L211) via a plugin to add support for an external VAGRANT_BOXES env variable (where the default is VAGRANT_HOME/boxes?  I don't think boxes themselves have gems within that need compilation?

**Comment by jimklo** [comment]
Also just for testing... I tried just defining `VAGRANT_HOME=/Users/jklo/vagrant_home` and same error. There's got to be something else to this than the Ruby limitation.

**Comment by jimklo** [comment]
@sethvargo Okay I've uninstalled and reinstalled Vagrant so it's now installed in `/Volumes/Passport/opt/vagrant`.  Same problem but possibly worse?  With `VAGRANT_HOME=~/.vagrant.d` it works, but still the same error when set to `VAGRANT_HOME=/Volumes/Passport/vagrant.d` or `VAGRANT_HOME=~/.vagrant.d_test`.  I'm beginning to think this is not related to the Ruby issue, but a core Vagrant bug.  I have the same problem regardless of the volume.  Is there some way that `VAGRANT_HOME` should be initialized?

**Comment by jimklo** [comment]
@sethvargo additional info. I tried copying my `~/.vagrant.d` folder to `/Volumes/Passport/.vagrant.d_test`, then set `export VAGRANT_HOME=/Volumes/Passport/.vagrant.d_test`.  I then installed the plugin without any issues on the external volume.

So it would seem to me that vagrant is not creating the right VAGRANT_HOME structure from an empty folder perspective.

**Comment by jimklo** [comment]
Okay I think I found the problem.  This may be an issue that is OS X only.

The key line from the error is:

```
/opt/vagrant/embedded/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir': parent directory is world writable but not sticky (ArgumentError)
```

It turns out that ruby's `Dir.mktmpdir` uses the `$TMPDIR` variable on OS X for user private temp directories (which looks something like this: `/var/folders/yl/y9zbwwm951v3x6p62yn24ckw0000gn/T`).  On OS X, this directory does not have the sticky bit set.  

After setting the sticky bit on this folder using:

```
chmod +t $TMPDIR
```

I can now install plugins again into any `VAGRANT_HOME` location.  I'm wondering why did this worked previously?  Did the version of embedded Ruby or Bundler change?  This should probably be documented somewhere.
