### ISSUE TITLE
directory is already being watched

### ISSUE THREAD

**Issue by Elexy** [mitchellh/vagrant#5715]
running an symfony project inside a box and running rsync-auto causing a bunch of these errors:
```
Directory: /home/alex/dev/v3/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/public

        is already begin watched through: /home/alex/dev/v3/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/public

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **
```
the 'public' directories are symlinked in /web.
running vagrant 1.7.2
This didn't happen for the same project with an older vagrant (recent new install)

**Comment by mitchellh** [comment]
Can you show the debug log output for rsync-auto?

**Comment by peterrehm** [comment]
This problem is related to symfony and not really to vagrant. By default you have the following symlinks:

````php
➜  sf2-test git:(master) ✗ ls -lR /code/sf2-test | grep ^l
doctrine -> ../vendor/doctrine/orm/bin/doctrine
doctrine-dbal -> ../vendor/doctrine/dbal/bin/doctrine-dbal
doctrine.php -> ../vendor/doctrine/orm/bin/doctrine.php
security-checker -> ../vendor/sensiolabs/security-checker/security-checker
framework -> ../../vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Resources/public/
sensiodistribution -> ../../vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Resources/public/
````

The last two are located in /web/bundles which means you are watching the same directories twice. If you just install your assets not using symlinks the error will be gone or you just accept the error as it should be only a small issue.

**Comment by sethvargo** [comment]
As Peter pointed out, this is not a bug in Vagrant. Thanks! :smile:
