### ISSUE TITLE
Problem (in Ubuntu 14.04 lts): Time out in finish provision ssh check

### ISSUE THREAD

**Issue by lukBarros** [mitchellh/vagrant#5716]
Problem (in Ubuntu 14.04 lts): Time out in finish provision ssh check if i instaled vagrant form apt-get stable repo, if instaled via .deb packegd it is run!!!

Is problem occurred in mu Ubutun 14.04LTS in running cmd 'vagrant up'.

It error repeat in some 2 computers of 2 peaples in the my working team enginnier.

Plase, checke it, plase, relase new version in the stable repos of Ubutun 14.04LTS for natural by users linux.

**Comment by sethvargo** [comment]
Hi @lukBarros 

Can you please try using the official Vagrant installer from http://www.vagrantup.com/downloads? While we work with the owners, we do not publish official packages to the apt/yum upstreams. It would be helpful if you could tell us which version of Vagrant you are using and provide the output of Vagrant in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html). Thanks!

**Comment by lukBarros** [comment]
Hi @sethvargo cool?

I was in a hurry to solve the problem to work.

As I said: The mistake I reported only occurs if I install via apt-get install. When installed as you recommended me everything works fine.

This weekend, I will remove the vagrant installed manually via downloading from the official website and reinstall apt-get through in order to simulate the error and you report what happened as you ask me.

Thanks for listening, we will build together this!

**Comment by mitchellh** [comment]
We don't support the apt package so we unfortunately can't fix this.
