### ISSUE TITLE
vagrant ssh not work on cygwin+windows

### ISSUE THREAD

**Issue by panjie** [mitchellh/vagrant#5717]
I use vagrant(1.7.2) in cygwin under Windows7/64bit. Everything is find except that when I use `vagrant ssh`, the following will appear on the terminal(Windows or cygwin's terminal), and cannot ssh into the VM.
```
xxx@G08FNSTD121245 ~/vagrant/zealbs
$ vagrant ssh

D:\cygwin\home\xxx\vagrant\zealbs>net stop "cygwin sshd"
没有启动 CYGWIN sshd 服务。

请键入 NET HELPMSG 3521 以获得更多的帮助。
```

Meanwhile I can still use `ssh -p2222 vagrant@localhost` to login on the VM.  The output of `vagrant ssh-config` are:
```
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile C:/Users/xxx/.vagrant.d/boxes/zealbsbox/0/virtualbox/vagrant_private_key
  IdentitiesOnly yes
  LogLevel FATAL
```
I don't know why this happens. Thank forwardly for any of your help.

**Comment by sethvargo** [comment]
Hi @panjie 

I am sorry you are having issues with `vagrant ssh`. Do you have any non-ascii characters in your path (including your username)?

**Comment by panjie** [comment]
Hi @sethvargo 

There are no non-ascii characters in my path. I am justing wondering while `vagrant ssh` will invoke `net stop cygwin sshd`.

**Comment by panjie** [comment]
After re-installation, this problem disappeared. Maybe it's an environment problem. I think this issue can be closed.
