### ISSUE TITLE
Merged Vagrantfiles does not preserve plugin's config

### ISSUE THREAD

**Issue by strzibny** [mitchellh/vagrant#5720]
Hi, we made a Vagrant plugin for registering RHEL boxes (https://github.com/projectatomic/adb-vagrant-registration). The basic usage is as follows:
```
if Vagrant.has_plugin?('vagrant-registration')
  config.registration.username = 'foo'
  config.registration.password = 'bar'
end
```
It works fine. The problem is that if I move this settings from project's Vagrantfile to user's Vagrantfile (`~/.vagrant.d/Vagrantfile`), the config is lost :/. Is there a way how to deal with this? Having this kind of config in one Vagrantfile is pretty essential. Ideas?

**Comment by strzibny** [comment]
So the problem is I used `OpenStruct` instead of `UNSET_VALUE`. I though it's possible, but seems like it's not so I am setting the config variable to `OpenStruct` later (in https://github.com/projectatomic/adb-vagrant-registration/commit/7f81f9ff7975f93016ea57fd635de4b524e30b58).

The question is, is this bug or expected behaviour?

**Comment by mitchellh** [comment]
This is expected. Vagrant merge logic requires `UNSET_VALUE` to automatically work.
