### ISSUE TITLE
Problem (in Ubuntu 14.04 lts): Vagrant error pass permissions of sudo call

### ISSUE THREAD

**Issue by lukBarros** [mitchellh/vagrant#5723]
#### Problem

I run:

````
sudo vagrant up
````

and all provising is done... my vw is up. ok..

After five Minutes i run...

```
sudo vagrant halt
```

Erro!!! My VW dont exist's from the vagrant and the run localhost:8080 em my browser it is running perfetc!!!

or 

````
sudo vagrant global-status
````

This machine dont exists!

#### Solution 

Solution by my friend is, firts:

```
$ cd ~
$ chown -R myusername.myusergroup .vagrant.d/*
```

and second:

```
sudo vairtualbox
```

and find your 'lost box' of vagrant call's and remove it. Close Virtualbox (called with root).

Ony call (dont use sudo!):

```
vagrant up
```

and 

```
vagrant halt
```

and

```
vagrant global-status
```

All commads responses ok. I can UP, I can Down, I can QUERY... its REAL DONE!!!

It is a problem related or new?

**Comment by sethvargo** [comment]
Hi @lukBarros 

It is not recommended that you run Vagrant in sudo mode as it can cause strange permission issues with VirtualBox and other providers. It also makes it impossible for users on a shared system to use Vagrant. Your proposed solution is appropriate, but please do not run `sudo vagrant` or you will re-create the issue :smile:.
