### ISSUE TITLE
Vagrant fails to properly handle an updated guest ssh port in VirtualBox mid-run, unless config.ssh.port is specified

### ISSUE THREAD

**Issue by kpabijanskas** [mitchellh/vagrant#5726]
When you update guest ssh port in VirtualBox to point to a different port mid-run, Vagrant seems to fail to detect the rule completely, and ignores any port forwarding. 

```
$ vagrant ssh-config
Host control
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/kpabijanskas/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

$ VBoxManage showvminfo control --details|grep 2222
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 2222, guest ip = , guest port = 22
$ VBoxManage controlvm 'control' natpf1 delete 'ssh'
$ VBoxManage controlvm 'control' natpf1 'ssh,tcp,127.0.0.1,2222,,9022'
$ VBoxManage showvminfo control --details|grep 2222
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 2222, guest ip = , guest port = 9022
$ vagrant ssh-config
Host control
  HostName 127.0.0.1
  User vagrant
  Port 22
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/kpabijanskas/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

As you can see, the rule seems to be completely disregarded after this point, and vagrant simply falls back to ssh defaults. Updating the port forwarding via the VirtualBox GUI produced identical results. I am unable to currently test it on different providers weather it affects any one other of them

Including `config.ssh.port = PORT` directive in your Vagrantfile seems to remedy this, but this forces you to explicitly set the ssh port for every machine in multi-machine environments, rather than allowing vagrant to do it for you

**Comment by sethvargo** [comment]
Hi @kpabijanskas 

I am sorry you are having issues with Vagrant. Can you elaborate on what you mean by:

> When you update guest ssh port in VirtualBox to point to a different port mid-run

How are you updating "mid-run"? If you change ports, you will need to run `vagrant reload `to make the changes to the VM.

**Comment by kpabijanskas** [comment]
Hi @sethvargo ,

All the details are in the code block of the original poist. This is what I mean:
```
$ VBoxManage controlvm 'control' natpf1 delete 'ssh'
$ VBoxManage controlvm 'control' natpf1 'ssh,tcp,127.0.0.1,2222,,9022'
```
This is essentially the same as going to Virtualbox settings for the VM, then the network adapter settings, and then the port forwarding settings, and changing the rule to port forward 2222 => 9022, rather than 2222 => 22. You can do this via the GUI too.

As soon as this is done, the rule is NOT detected anymore. However, if I set `config.ssh.port = 2222` in my Vagrantfile, the rule is detected regardless of the change, as long as I don't change the host port. This means that if I want to update the port forwarding rule mid-run, I have to specify the host ssh port manually, rather than allowing vagrant to do it for me (which it handles perfectly well, including picking the next port if it is in use, which is more difficult to manage manually).

This is not a VirtualBox bug, as vagrant fails to detect the port forwarding rule it set itself. I'm assuming (and I have not dug through the code) that vagrant simply matches the rule completely, rather than just the name. This does not explain, however, why vagrant does not match the rule completely when `config.ssh.port` is specified.

`vagrant reload` reboots the machine, which is something I am trying to avoid. Even if I rebooted the machine, I would still need to go back to my Vagrantfile and change the guest ssh port before bringing it back up, so it would not help in any way.

**Comment by mitchellh** [comment]
You need to change `config.ssh.guest_port`. 

Vagrant detects the port based on that value, which defaults to 22. If the port isn't found, it defaulst to 22.
