### ISSUE TITLE
Issue adding box with bsdtar archive format on latest version of vagrant for Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by g2graman** [mitchellh/vagrant#5727]
Refer to the output below:
    
    $cat /etc/lsb-release
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=14.04
    DISTRIB_CODENAME=trusty
    DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
    
    $ vagrant -v
    Vagrant 1.4.3
    
    $ vagrant box add laravel/homestead https://atlas.hashicorp.com/laravel/boxes/homestead
    Downloading box from URL: https://atlas.hashicorp.com/laravel/boxes/homestead
    Extracting box...ate: 979/s, Estimated time remaining: --:--:--)
    The box failed to unpackage properly. Please verify that the box
    file you're trying to add is not corrupted and try again. The
    output from attempting to unpackage (if any):

    bsdtar: Error opening archive: Unrecognized archive format

**Comment by sethvargo** [comment]
Hi @g2graman 

Can you please share your complete Vagrantfile and the output of the command in debug mode? Please also note that the latest version of Vagrant is 1.7.2 and can be installed on the downloads page at https://vagrantup.com/downloads.html.

**Comment by g2graman** [comment]
I did not have a `Vagrantfile` in this directory. However, I get the same issue from

    vagrant init laravel/homestead https://atlas.hashicorp.com/laravel/boxes/homestead && vagrant up

Note:

    $ vagrant init laravel/homestead https://atlas.hashicorp.com/laravel/boxes/homestead && vagrant up
    A `Vagrantfile` has been placed in this directory. You are now
    ready to `vagrant up` your first virtual environment! Please read
    the comments in the Vagrantfile as well as documentation on
    `vagrantup.com` for more information on using Vagrant.
    Bringing machine 'default' up with 'virtualbox' provider...
    [default] Box 'laravel/homestead' was not found. Fetching box from specified URL for
    the provider 'virtualbox'. Note that if the URL does not have
    a box for this provider, you should interrupt Vagrant now and add
    the box yourself. Otherwise Vagrant will attempt to download the
    full box prior to discovering this error.
    Downloading box from URL: https://atlas.hashicorp.com/laravel/boxes/homestead
    Extracting box...e: 0/s, Estimated time remaining: --:--:--)
    The box failed to unpackage properly. Please verify that the box
    file you're trying to add is not corrupted and try again. The
    output from attempting to unpackage (if any):

    bsdtar: Error opening archive: Unrecognized archive format

The `Vagrantfile` that resulted:

    $ cat Vagrantfile
    # -*- mode: ruby -*-
    # vi: set ft=ruby :

    # Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
    VAGRANTFILE_API_VERSION = "2"

    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
      # All Vagrant configuration is done here. The most common configuration
      # options are documented and commented below. For a complete reference,
      # please see the online documentation at vagrantup.com.

      # Every Vagrant virtual environment requires a box to build off of.
      config.vm.box = "laravel/homestead"

      # The url from where the 'config.vm.box' box will be fetched if it
      # doesn't already exist on the user's system.
      config.vm.box_url = "https://atlas.hashicorp.com/laravel/boxes/homestead"

      # Create a forwarded port mapping which allows access to a specific port
      # within the machine from a port on the host machine. In the example below,
      # accessing "localhost:8080" will access port 80 on the guest machine.
      # config.vm.network :forwarded_port, guest: 80, host: 8080

      # Create a private network, which allows host-only access to the machine
      # using a specific IP.
      # config.vm.network :private_network, ip: "192.168.33.10"

      # Create a public network, which generally matched to bridged network.
      # Bridged networks make the machine appear as another physical device on
      # your network.
      # config.vm.network :public_network

      # If true, then any SSH connections made will enable agent forwarding.
      # Default value: false
      # config.ssh.forward_agent = true

      # Share an additional folder to the guest VM. The first argument is
      # the path on the host to the actual folder. The second argument is
      # the path on the guest to mount the folder. And the optional third
      # argument is a set of non-required options.
      # config.vm.synced_folder "../data", "/vagrant_data"

      # Provider-specific configuration so you can fine-tune various
      # backing providers for Vagrant. These expose provider-specific options.
      # Example for VirtualBox:
      #
      # config.vm.provider :virtualbox do |vb|
      #   # Don't boot with headless mode
      #   vb.gui = true
      #
      #   # Use VBoxManage to customize the VM. For example to change memory:
     #   vb.customize ["modifyvm", :id, "--memory", "1024"]
      # end
      #
      # View the documentation for the provider you're using for more
      # information on available options.

      # Enable provisioning with Puppet stand alone.  Puppet manifests
      # are contained in a directory path relative to this Vagrantfile.
      # You will need to create the manifests directory and a manifest in
      # the file laravel/homestead.pp in the manifests_path directory.
      #
      # An example Puppet manifest to provision the message of the day:
      #
      # # group { "puppet":
      # #   ensure => "present",
      # # }
      # #
      # # File { owner => 0, group => 0, mode => 0644 }
      # #
      # # file { '/etc/motd':
      # #   content => "Welcome to your Vagrant-built virtual machine!
      # #               Managed by Puppet.\n"
      # # }
      #
      # config.vm.provision :puppet do |puppet|
      #   puppet.manifests_path = "manifests"
      #   puppet.manifest_file  = "site.pp"
      # end

      # Enable provisioning with chef solo, specifying a cookbooks path, roles
      # path, and data_bags path (all relative to this Vagrantfile), and adding
      # some recipes and/or roles.
      #
      # config.vm.provision :chef_solo do |chef|
      #   chef.cookbooks_path = "../my-recipes/cookbooks"
      #   chef.roles_path = "../my-recipes/roles"
      #   chef.data_bags_path = "../my-recipes/data_bags"
      #   chef.add_recipe "mysql"
      #   chef.add_role "web"
      #
      #   # You may also specify custom JSON attributes:
      #   chef.json = { :mysql_password => "foo" }
      # end

      # Enable provisioning with chef server, specifying the chef server URL,
      # and the path to the validation key (relative to this Vagrantfile).
      #
      # The Opscode Platform uses HTTPS. Substitute your organization for
      # ORGNAME in the URL and validation key.
      #
      # If you have your own Chef Server, use the appropriate URL, which may be
      # HTTP instead of HTTPS depending on your configuration. Also change the
      # validation key to validation.pem.
      #
      # config.vm.provision :chef_client do |chef|
      #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
      #   chef.validation_key_path = "ORGNAME-validator.pem"
      # end
      #
      # If you're using the Opscode platform, your validator client is
      # ORGNAME-validator, replacing ORGNAME with your organization name.
      #
      # If you have your own Chef Server, the default validation client name is
      # chef-validator, unless you changed the configuration.
      #
      #   chef.validation_client_name = "ORGNAME-validator"
    end

**Comment by g2graman** [comment]
Hmm, updating to v `1.7.2` manually seemed to do the trick. Apologies and thank you.

**Comment by brycepj** [comment]
Same issue here, but with v `1.7.4`.

`Vagrantfile`

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "./2015-12-07-jubbr-devel.box"
  config.vm.network "forwarded_port", guest: 80, host_ip: '127.0.0.1', host: 7080
  config.vm.network "forwarded_port", guest: 8888, host_ip: '127.0.0.1', host: 8888

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/opt/jc/mod/app/", owner: 'jc', group: 'jc', create: true

  # TODO: this should come from the base image
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.gui = false
    vb.memory = "1024"
  end

  # folder too late (after init process is done)
  # TODO: see how to integrate the shared folder within
  # the init sequence and auto-mount it
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    sudo su jc -c '. $HOME/.bashrc ; rl dev'
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    # wait for db / run level to be ready
    sudo su jc -c '. $HOME/.bashrc ; until echo "\\du" | psql -qtA 2>/dev/null | cut -d "|" -f1 | grep -qF "${PGUSER}" ; do sleep 1 ; done'
    # migrate / initialize database; add test user set
    sudo su jc -c '. $HOME/.bashrc ; cd $HOME/mod/api/web/.lua ; GIN_ENV=migration gin migrate ; psql < /opt/jc/mod/app/test/devuser.sql'
  SHELL

end
```
