### ISSUE TITLE
ssh port forwarding not working correctly with ansible provisioning virtualbox provider

### ISSUE THREAD

**Issue by qkslvrwolf** [mitchellh/vagrant#5728]
I have a multi-machine vagrant file that is not properly setting the host ssh port, which is causing ansible provisioning to fail.

With the following set in my Vagrantfile:

```ruby
    stash.ssh.port = 2244
    stash.ssh.guest_port = 22
```

I get:  

```
==> stash: Forwarding ports...
    stash: 7990 => 3990 (adapter 1)
    stash: 8443 => 4443 (adapter 1)
    stash: 7999 => 3999 (adapter 1)
    stash: 80 => 8002 (adapter 1)
    stash: 443 => 8043 (adapter 1)
    stash: 22 => 2222 (adapter 1)
```

(note that the configuration does NOT have any host: 2222 guest: 22 configurations)

Same thing if I use:

```ruby
stash.vm.network "forwarded_port", guest: 22, host: 2244
```

Either way, Vagrant uses 2222 instead of 2244.  Even if I update my ansible config (which is static) to use 2222, ansible still won't correctly connect to the VM.

Vagrant 1.6.5, Ansible 1.9.1, VirtualBox 4.3.26

However, this must either be with the provider or vagrant.  Incidentally, this was all working fine one the same versions today, with no upgardes, so maybe there's a dotfile someplace storing info I just need to remove?

**Comment by qkslvrwolf** [comment]
Oh, another weird thing: vagrant ssh works fine. I can ssh to the box using the same localost settings that ansible uses.  But ansible fails because it can't send data to the box.

**Comment by sethvargo** [comment]
Hi @qkslvrwolf 

Vagrant communicates with the machine over SSH, so it needs an SSH port to communicate with. It uses 2222 by default. If you change or overwrite that port, Vagrant will not be able to connect and manage the VM. This is why `vagrant ssh` still works. Does that make sense?

**Comment by qkslvrwolf** [comment]
What if you have multiple boxes?  Why did vagrant ssh work to each of them?

**Comment by qkslvrwolf** [comment]
Also, that's not what the docs say.  From http://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html:

"config.ssh.guest_port: The port on the guest that SSH is running on. This is used by some providers to detect forwarded ports for SSH. For example, if this is set to 22 (the default), and Vagrant detects a forwarded port to port 22 on the guest from port 4567 on the host, Vagrant will attempt to use port 4567 to talk to the guest if there is no other option."

And while that's happening, it's not succeeding.

**Comment by sethvargo** [comment]
Hi @qkslvrwolf 

Can you please share your complete `Vagrantfile` and the result of the vagrant command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by mitchellh** [comment]
Closing due to lack of response, sorry.
