### ISSUE TITLE
vagrant destroy does not remove the VM in VMWare's Virtual Machine Library

### ISSUE THREAD

**Issue by gildas** [mitchellh/vagrant#5729]
When destroying a vm with `vagrant destroy`, the vm is not removed from the Virtual Machine Library in VMWare.

**Comment by sethvargo** [comment]
Hi @gildas 

Thank you for opening an issue. Unfortunately this is a known issue with VMware Fusion/Workstation itself. When removing VMs via their API, the GUI is not updated. If you quit and re-open the VMware product, the machine will no longer be present.

**Comment by gildas** [comment]
Hey Seth, thanks a lot for the explanation. Needless to say, I am less and less a fan of VMWare.... ;)
