### ISSUE TITLE
.vagrantrc -- global rules to apply to all Vagrantfile

### ISSUE THREAD

**Issue by bjori** [mitchellh/vagrant#5733]
I have several projects that bundle Vagrantfile to make it easier to get started.
This works out fantastic in most cases.

Most people have their favorite collection of dotfiles they just "cannot be without".

This is a request to create a config entry in .vagrantrc or such to specify scripts/provisioner that should always be executed.

This would allow people to have a generic Vagrantfile -- but at the same time, get their .vimrc & .vim, .gitconfig, .bashrc / .zshrc / .., .gdbinit, ...

**Comment by fgrehm** [comment]
I think this is already supported by using a `$HOME/.vagrant.d/Vagrantfile` isn't it? See the "LOAD ORDER AND MERGING" section at https://docs.vagrantup.com/v2/vagrantfile/index.html

**Comment by bjori** [comment]
I did not see that coming. This looks indeed like an excellent solution!

Thanks for the tip!
