### ISSUE TITLE
vagrant provision - no error message on simple error

### ISSUE THREAD

**Issue by TobyHFerguson** [mitchellh/vagrant#5734]
Vagrant 1.7.2. Oracle Linux 6 host.

My Vagrantfile contained:

```ruby
config.vm.define "oms" do |oms|
  oms.vm.provision "pre_oms_install", type: "shell", path: ".oms/pre_oms_install.sh", privileged: false
end
```

When I MISTAKENLY ran 'vagrant provision oms --provision-with pre_oms_install.sh' no error message was given; I simply got the shell prompt back with no error message.

**Comment by mitchellh** [comment]
This is fixed now in master!
