### ISSUE TITLE
vagrant ssh share could not be found

### ISSUE THREAD

**Issue by PanosKou** [mitchellh/vagrant#5744]
I have recently set up a vagrant ssh share, but once I tried to connect (vagrant connect –ssh share-name) I got the error below (does not seem to find the share);

The issue is similar to the one mentioned in the link below;
#4828
But it has not been resolved. it was just closed.

In console 1 I type:

```
$ vagrant share --ssh --name share-name

==> default: Your Vagrant Share is running! Name: share-name
==> default: You're sharing with SSH access. This means that another user
==> default: simply has to run vagrant connect --ssh share-name
==> default: to SSH to your Vagrant machine.
```

In console 2 the below:

```
$ vagrant connect --ssh share-name

The share 'share-name' could not be found!
Verify that the name you used is correct. If it is indeed correct,
make sure that you have permissions to view this share.
```

The log files can be found here: https://github.com/PanosKou/vagrant_debug.logs

This is on an Organization account, I am logged in with vagrant login, and I can see the share being active on https://atlas.hashicorp.com/vagrant.

Thanks for any help in advance.

**Comment by sethvargo** [comment]
Hi @PanosKou 

Can you please share the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by PanosKou** [comment]
Hi Seth,

You can find the output of both the ssh share and the connect commands in debug mode under the provided link;

https://github.com/PanosKou/vagrant_debug.logs

Thank you

**Comment by sethvargo** [comment]
Hi @PanosKou 

Can you please run `vagrant login -c` from the machine you are trying to share and the machine you are trying to connect from?

**Comment by PanosKou** [comment]
Hi @sethvargo 

The `vagrant login -c` gave the output of "You are already logged in." on both machines.

Thank you.

**Comment by PanosKou** [comment]
Hi @sethvargo,

I have managed to figure out the cause of the inability to set up ssh shares.

Apparently the base box we have been using does not allow ssh sharing. Not sure why this was tampered with but we have been using this box for a while and we have now found out that other newer boxes work where as this Centos 6.6 install does not (please note that this box was acquired from Atlas). So, it is not entirely a vagrant issue.

So after switching to a new box (also retrieved from Atlas), we were able to set up an ssh share, but when we tried to connect to it, we were able to find the share and almost connect to it when we got the same error mentioned here; https://github.com/mitchellh/vagrant/issues/3275

Is the only fix to upgrade vagrant, except from disabling firewalls etc which I've already done..?

Thanks for your help so far.

**Comment by PanosKou** [comment]
Closing even though I could not fix the issue on the main server but I was also not able to replicate it on other servers. Seems like the fix for this issue is to either upgrade vagrant or make sure your firewall and the server environment have been set up properly.
