### ISSUE TITLE
vagrant up --provider=vcenter, results in EINVAL error

### ISSUE THREAD

**Issue by ismben** [mitchellh/vagrant#5745]
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/open-uri.rb:36:in `initialize': Invalid argument - file://C:/Users/me/.vagrant.d/boxes/centos7/0/vmware_ovf/centos7.ovf (Errno::EINVAL)

vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

**Comment by sethvargo** [comment]
Hi @ismben 

I am sorry you are having issues with Vagrant. Could you please share your complete `Vagrantfile` as well as the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by mitchellh** [comment]
As the vcenter provider isn't official or built-in, we can't fix this bug unless we can track it down to Vagrant core. Closing due to lack of response but if we can track it down to that we'll fix.

**Comment by ZetCoby** [comment]
Had the same error/problem, only that the path at me was different ex : file://C:/Users/me/AppData/Temp (Errno::EINVAL), it did not have access to the Temp folder, at me the partition got corrupted and the folder could not be opened, hope this helps
