### ISSUE TITLE
The "vmware-vmx" application could not be found

### ISSUE THREAD

**Issue by andyhunne** [mitchellh/vagrant#5752]
Gist with debug output: https://gist.github.com/andyhunne/7ae7988a6e8211b6794d

I'm quite possibly an idiot and missing something obvious, but I can't figure this one out.  I have VMware workstation 11.1.0-3496824 installed on funtoo Linux.  Can't seem to get any boxes launching with "vagrant up".  Provider is set to vmware_workstation.

**Comment by sethvargo** [comment]
Hi @andyhunne 

I am sorry you are having issues with the Vagrant VMware Workstation provider. According to the debug output, it seems like the `vmware-vmx` executable is not in your path.

**Comment by andyhunne** [comment]
Thanks for the reply @sethvargo .  Trying to track down the executable and add it in.  Will let you know the results.

**Comment by andyhunne** [comment]
Well, that got me past the vmware-vmx not found - thanks.  Now my latest error is:

translation missing: en.hashicorp.vagrant_vmware_desktop.errors.vmrun_not_Found

Doing a bit of digging around to see if I can sort this one out.

**Comment by andyhunne** [comment]
I guess the error above is because my language is not set to English, but it's pointing out there's no vmrun available on my box.  Thought this was just another path issue, but after searching the machine there is no vmrun executable available. Tried creating a symlink between vmware and vmrun in my /opt/vmware/bin directory and made some progress, but the machine creation crashed.

**Comment by andyhunne** [comment]
Sorted.  I had to reinstall vmware-workstation with vix support...vmrun is now available.  Thanks for the original tip.

**Comment by ericpromislow** [comment]
I had a similar message: 

The executable '/Users/eric/work/Contents/Library/vmware-vmx' Vagrant is trying to run was not
found in the PATH variable.

Adding "/Applications/VMware\ Fusion\ 7.app/Contents/Library" to the path didn't help.

Doing `ln -s /Applications/VMware\ Fusion\ 7.app/Contents ." did

This seems very wrong. But for some reason either vagrant or the vmware adapter thinks vmware-vmx lives in "$PWD/Contents/Library/" which sure looks like a bug to me.

I'm following a colleague's instructions. Could someone else post the instructions for installing vmware fusion 7 and the vagrant provider on a new mac running Yosemite? I installed vmware from their site, and 'brew cask install vagrant" which brought in version 1.8.1
