### ISSUE TITLE
Provide a way to warn users about problems in the vagrant file in red. 

### ISSUE THREAD

**Issue by greylurk** [mitchellh/vagrant#5755]
I want to warn users who are executing my vagrantfile if items are missing from the configuration that they'll need, but I don't necessarily want to raise an error which throws a stack trace, and so forth. I'm able to warn users, but the warnings show up in grey, and they just blend in to the background. The specific use case I'm working with is:

``` ruby
if ENV.has_key?('AWS_ACCESS_KEY_ID') 
    host.vm.provision :shell, path: 'append_environment.sh', args: ['AWS_ACCESS_KEY_ID', ENV['AWS_ACCESS_KEY_ID']]
else 
    $stderr.puts 'AWS_ACCESS_KEY_ID must be set in your environment in order to successfully deploy the app'
end
```

**Comment by amosshapira** [comment]
+1, if I may vote.

**Comment by sethvargo** [comment]
I like this idea. I think we should expose something like `Vagrant.log.warn` in the Vagrantfile DSL.

**Comment by crussell52** [comment]
Any word on this particular ehancement.  It would be a fantastic addition!

**Comment by dragon788** [comment]
I'd also love to see this implemented.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
