### ISSUE TITLE
Single user mode is broken for ubuntu/trusty images

### ISSUE THREAD

**Issue by deviantintegral** [mitchellh/vagrant#5756]
1. Init a box using https://atlas.hashicorp.com/ubuntu/boxes/trusty32 or https://atlas.hashicorp.com/ubuntu/boxes/trusty64
1. Halt the box after it first boots
1. Use the VirtualBox GUI to boot the VM, press ESC during boot to get to the GRUB menu, and select recovery mode.
1. The VM will hang during boot. Strangely, CTRL-ALT-DEL works, and shows a flash of the recovery menu.

I've tested by spinning up a VM from the Ubuntu server installer, and single user mode works fine. That leads me to think that the problem is with the image or with how Vagrant creates the VM.

Also, dropping to single user mode after booting fails in a similar manner, except you see the login console instead.

This is a pain for maintaining base boxes, since zerofree require the root file system to be unmounted or in readonly mode. The only workaround I've had so far is to boot off of a recovery CD image instead.

![ubuntu-trusty32_default_1432219313175_49358 running 2015-05-26 10-51-16](https://cloud.githubusercontent.com/assets/255023/7815228/22f8471e-0395-11e5-8b00-520c72271db6.jpg)

**Comment by sethvargo** [comment]
Hi @deviantintegral 

Thank you for opening an issue. This seems like it might be a virtualbox issue though. Are you able to reproduce this without Vagrant?

**Comment by deviantintegral** [comment]
@sethvargo yes, doing an Ubuntu 14.04.2 install from the ISO without vagrant at all lets me get into single user mode without a problem.

**Comment by sethvargo** [comment]
Hrm okay. I'm going to tag this as a "bug", but I'm not sure this is a use-case we plan to support. I'll defer to @mitchellh

**Comment by mitchellh** [comment]
Vagrant creates the VM by doing a `VBoxManage import`. This is likely an issue with the image. Please report with the maintainer. But let us know if there is anything we can do.

**Comment by deviantintegral** [comment]
Where do I find the maintainer info @mitchellh ? I don't see any authoring information on https://atlas.hashicorp.com/ubuntu/boxes/trusty32

**Comment by sethvargo** [comment]
@deviantintegral The Ubuntu boxes are published by canonical
