### ISSUE TITLE
public key/private key does not match in ubuntu/trusty64 official box

### ISSUE THREAD

**Issue by jackjm** [mitchellh/vagrant#5757]
I run vagrant(1.7.2) on Mac OS(10.10.3) with [ubuntu/trusty64 official box](https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/20150521.0.0), using VirtualBox 4.3.28 as a provider.

**vagrant init ubuntu/trusty64** 
**vagrant up --provider virtualbox**

After these two commands, I was prompted a password in "vagrant ssh", the private key auth method did not work.

I compared the ~/.vagrant.d/insecure_private_key  in host(private key on Mac OS) and ~/.ssh/authorized_keys (public key on Ubuntu virtual box), turned out they are not match.

Then I generated the right public key from the private key and replace the wrong one in ubuntu box, problem solved. 

Is this a bug of the Ubuntu/trusty64(version: 20150521.0.0)?

**Comment by mitchellh** [comment]
This would be a box bug, and not Vagrant.
