### ISSUE TITLE
Use curl's "continue-at <offset>" feature within Vagrant

### ISSUE THREAD

**Issue by nojeffrey** [mitchellh/vagrant#5758]
I'm in Australia, If I try 'vagrant box add <link to box>' my average DL speed is ~200KB/s, even though I have a business grade 20/20 Mbit connection. 

If the download fails for some reason, I have to restart this download from the beginning, it's very frustrating, especially on large transfers.

If I run: 'curl -O http://example.com/somefile.deb' and it fails half way through, I can then run: 
'curl -C - -O http://example.com/somefile.deb' and it will resume from where it failed.

It would be good if vagrant could use curl's 'continue-at <offset>' feature.

**Comment by nojeffrey** [comment]
I don't know how add the 'enhancement' label.

**Comment by sethvargo** [comment]
Hi @nojeffrey 

Thank you for opening an issue. Unfortunately the solution here is not quite as simple. Vagrant already supports "resume" downloads, but our upstream hosting service does not (see https://github.com/mitchellh/vagrant/issues/5237). Not all upstream providers support downloading from a byte range, so it will cause issues if the upstream doesn't support it (which is what 5237 is reporting).

**Comment by nojeffrey** [comment]
@sethvargo 
Ah OK, I thought it may be non trivial.
