### ISSUE TITLE
Timeout of 'vagrant share' causes box to go into paused status

### ISSUE THREAD

**Issue by justicel** [mitchellh/vagrant#5762]
If I start a 'vagrant share' of a VM and leave it running until it eventually times out, the 'vagrant global-status' shows the box as in 'paused' status. The virtualbox instance is still running and you can connect to HTTP, etc. on the machine so this simply appears to be a bug in the Vagrant code after the share timeout is hit. Let me know if you need any further details.

**Comment by mitchellh** [comment]
I can't reproduce this locally. This is pretty odd. Can you give a step by step repro list and update the issue? Sorry for the inconvenience.
