### ISSUE TITLE
setting config.vm.hostname breaks winrm

### ISSUE THREAD

**Issue by epu** [mitchellh/vagrant#5764]
Using a `boxcutter/windows` virtualbox/win7x64-enterprise base box, and it rolls out ok if I don't set hostname.

If I do set config.vm.hostname from my Vagrantfile, WinRM gets stuck in a WinRMHTTPTransportError (500) during 'vagrant up' any time WinRM is used (after executing change_host_name ok).

This is using windows x64 host, vagrant 1.7.2
vagrant-share (1.1.3, system)

**Comment by epu** [comment]
Eh. Maybe it's user error (vagrant-winrm isn't supposed to be applied to vagrant 1.7.2). Testing..

**Comment by sneal** [comment]
This should be [fixed](https://github.com/mitchellh/vagrant/commit/7784ee2d09ced38434942ccb7d96a5ff2ee88758#diff-be5d7342b9c60039447a6ca3c8fc339d) in the next release. There was a change introduced in 1.7.0 that broke the Windows change_host_name capability. Alternatively you could try using Vagrant 1.6.5 until the next release.

**Comment by epu** [comment]
Great, thanks for the information.
