### ISSUE TITLE
Error on provisioning ubuntu/trusty64 with mysql-server via shell

### ISSUE THREAD

**Issue by jeroenseegers** [mitchellh/vagrant#5766]
When provisioning a new machine on OSX 10.10.3 with the `ubuntu/trusty64` box and provisioning it via shell with mysql-server Vagrant encounters an error and quits. This error also causes the terminal to behave weirdly because of the output Vagrant gives.

The Vagrantfile contains the following:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "./", "/vagrant_data"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y mysql-server
    SHELL
end
```

The output of the `vagrant up --debug` command can be found here: https://gist.github.com/jeroenseegers/ffcab7d0b2b69a25173c

The occurence of the error and breaking output is on line 130. Vagrant version is 1.7.2.

**Comment by sethvargo** [comment]
Hi @jeroenseegers,

Thank you for opening an issue. This issue is occurring because the default mysql installation expects user input which is not possible with Vagrant. You need to configure the mysql installation to not prompt. For example: http://stackoverflow.com/questions/7739645/install-mysql-on-ubuntu-without-password-prompt

Please let me know if you have any questions.
