### ISSUE TITLE
Configuration of server return for first state!

### ISSUE THREAD

**Issue by lreisoliveira** [mitchellh/vagrant#5767]
I use Ubuntu on machine with vagrant box lucid32 . I've a serious problem.

I configured my vagrant with php, mysql , apache Normally and after some days , turn on my computer When I have had a surprise : the configuration rollback for first state . All configuration that I did I lost .
Why ????

For tests I turn off the command vagrant vagrant suspend and halt the result is the same .

Ubuntu is 15.04 and vagrant is 1.7.2.

**Comment by sethvargo** [comment]
Hi @lreisoliveira 

I am sorry you are having issues with Vagrant. When you say "the configuration rollback for first state", do you mean the machine lost all the packages or that partial state was lost?

Can you please provide your complete `Vagrantfile` as well as the results of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by lreisoliveira** [comment]
Thanks Sethvargo

For example: I did a new configuration in file php.ini and new configuration file in httpd.conf of apache 1 week ago.

Today when I turn on vagrant this configuration rollback for the state 2 weeks ago! I do not know what happened. I didn't made ​​any changes or update. It's very strange.

=/

**Comment by sethvargo** [comment]
Hi @lreisoliveira 

Can you please share the `Vagrantfile` and the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? I need to see both of those to help diagnose the issue.

**Comment by mitchellh** [comment]
Closing due to lack of response
