### ISSUE TITLE
How to uninstall Vagrant from OSX

### ISSUE THREAD

**Issue by XMap** [mitchellh/vagrant#5772]
such like the title .
I have some problem with it.

**Comment by sethvargo** [comment]
Hi @XMap 

Thank you for opening an issue. Please refer to [the documentation on uninstalling Vagrant](http://docs.vagrantup.com/v2/installation/uninstallation.html) for detailed steps on how to uninstall Vagrant. Thanks!

**Comment by XMap** [comment]
: )    Wow ~Thank you very much !
