### ISSUE TITLE
New list-providers command

### ISSUE THREAD

**Issue by sschuberth** [mitchellh/vagrant#5776]
It would be nice to have a new "list-providers" command that lists all providers that are available to the current installation of Vagrant, and shows whether they are supported on the current host.

**Comment by dragon788** [comment]
In addition it would be handy in conjunction with the ability to set a default provider (which I think you can via environment variable?).

**Comment by sethvargo** [comment]
Hi @sschuberth 

The only provider Vagrant currently supports out of the box is virtualbox. All other providers are made available via plugins, so `vagrant plugin list` will give you the list of available providers on that system. Thanks!

You can use `VAGRANT_DEFAULT_PROVIDER` to set a default: https://docs.vagrantup.com/v2/other/environmental-variables.html

**Comment by sschuberth** [comment]
For once, looking at the Vagrant 1.8.1 directory structure of a fresh installation, in `embedded\gems\gems\vagrant-1.8.1\plugins\providers` I see `docker` and `hyper-v` besides `virtualbox`. So it seems `virtualbox` is *not* the only provider. However, the [docs](https://docs.vagrantup.com/v2/providers/) are [misleading](https://docs.vagrantup.com/v2/docker/index.html) about [this](https://docs.vagrantup.com/v2/hyperv/index.html).

Secondly, if I'm not mistaken `vagrant plugin list` lists *all* installed plugins, independently of whether the host actually supports them. For example, I could probably install the [vmware provider](https://www.vagrantup.com/vmware) without having Vmware installed on the host. The `list-providers` command I'm asking for would not list Vmware as a provider unless both the plugin *and* Vmware are installed on the host.

**Comment by sschuberth** [comment]
I've created a PR to address the docs issues: https://github.com/mitchellh/vagrant/pull/6753

**Comment by sschuberth** [comment]
Also, not all plugins are providers, so running `vagrant plugin list` to list usable providers is quite inconvenient.

@sethvargo since you acknowledged what you said initially was wrong by merging my PR, would you mind reopening this issue?

**Comment by sethvargo** [comment]
@sschuberth there's really no way for Vagrant to intelligently list the providers on the system, since they could be brought by an external plugin. For example, Vagrant could detect Vbox and VMware, but if the user has parallels installed, it wouldn't be detected because support for parallels is dictated by an external plugin.

Providers are such a key piece of Vagrant that fluidity between them shouldn't really matter. Vagrant will always pick the "best" provider and you can specify a specific provider using the `--provider` flag (or envvar).

**Comment by sschuberth** [comment]
@sethvargo I don't get why it would be impossible for Vagrant to intelligently list the providers on the system. Basically all it needs to do is to try to initialize all plugins that are providers. If a prerequisite for a plugin is not fulfilled (like VMware not being installed for the WMware provider plugin) the corresponding plugin would fail to initialize and should not be listed.

**Comment by sethvargo** [comment]
Hi @sschuberth 

Take Parallels for example. Vagrant doesn't "speak" parallels, the provider does. So all provider plugins would have to add a new API functionality for "detect", which does not exist. Even then, there is not guarantee that a plugin author would implement such functionality. 

I'm also having trouble understanding the use case. Providers are at the core of Vagrant, and fluidity between them is rarely wanted.

**Comment by sschuberth** [comment]
> So all provider plugins would have to add a new API functionality for "detect", which does not exist.

Exactly, that sounds like a reasonable way to implement this feature request.

> Even then, there is not guarantee that a plugin author would implement such functionality.

You could probably make implementing such a new method mandatory, by defining an interface or something.

> I'm also having trouble understanding the use case. Providers are at the core of Vagrant, and fluidity between them is rarely wanted.

IIRC, I was having trouble getting the Hyper-V provider to be used, and I wanted it to be used instead of VirtualBox as it's likely to offer better performance on Windows and does not require third-party software to be installed.

**Comment by ssbarnea** [comment]
Any update on this? For example I am wondering if there is a command that can verify if vagrant is able to talk with any provider on the current system? Having the CLI installed does not mean it can be used to provision anything.
