### ISSUE TITLE
Support configuring headless / gui mode for Hyper-V provider

### ISSUE THREAD

**Issue by sschuberth** [mitchellh/vagrant#5777]
In contrast to the [VirtualBox](http://docs.vagrantup.com/v2/virtualbox/configuration.html) and [VMware](http://docs.vagrantup.com/v2/vmware/configuration.html) provider configurations, the Hyper-V provider does not support the `gui` option to configure headless mode. It would be great if it did.

I realized this when bringing the `hashicorp/precise64` up and not seeing a gui, but setting `vb.gui = true` gives

    Hyper-V:
    * The following settings shouldn't exist: gui

**Comment by mitchellh** [comment]
We'd love to support this with a PR, but have no plans in the short term.
