### ISSUE TITLE
Vagrant not reinstalling rsync after initial vm creation

### ISSUE THREAD

**Issue by JohnBloom** [mitchellh/vagrant#5781]
I am using vagrant with a boot2docker. The image I am using is yunsang/boot2docker. I also use rsync to sync my files to the B2D host machine.

When I `vagrant up` clean with no B2D box created and ssh into the B2D host machine `rsync` is installed. If I turn the B2D machine off and `vagrant up` again `rsync` is not installed on the B2D host box and since apt-get isnt installed the only solution I have found is to delete the B2D machine and `vagrant up` again. 

Since the B2D box doesnt keep around rsync between boots and rsync was obviously installed on the initial `vagrant up` call, is there any way to get vagrant to reinstall rsync on subsequent `vagrant up` calls when the B2D box already exists?

**Comment by sethvargo** [comment]
Hi @JohnBloom 

Can you please share your complete `Vagrantfile` as well as the result of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html). Thanks!

**Comment by mitchellh** [comment]
Closing due to lack of response. Please make a new issue if you come back!
