### ISSUE TITLE
Vagrant failed to download boxes

### ISSUE THREAD

**Issue by jianghaitao** [mitchellh/vagrant#5782]
OS: OS X 10.10.3
Vagrant version: 1.7.2
VirtualBox version: 4.3.28r100309
```
$vagrant login

$ vagrant init hashicorp/precise64 
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/hashicorp/precise64"]
Error: 
```
I can curl the box file without any issue.

**Comment by sethvargo** [comment]
Hi @jianghaitao 

I am sorry you are having issues downloading that Vagrant box. Can you please try again? If the issue persists, please include the output of the vagrant run in debug mode. 

I noticed you posted on the mailing list and said your can curl the box fine. If you download the box manually, you can add it with:

```
vagrant box add /path/to/box.box
```

And then Vagrant will not attempt to download it when you run `vagrant up`.

Please let me know if you have any questions.

**Comment by jianghaitao** [comment]
Thanks for your response. 

I did try with local box since I can curl it. But still failed like following:
```
SFO1212464619A:boxes 212464619$ ls -l CentOS-6.6-x86_64-v20150426.box 
-rwxrwxrwx@ 1 212464619  1515967849  546643595 Jun  2 10:09 CentOS-6.6-x86_64-v20150426.box
SFO1212464619A:boxes 212464619$ vagrant box add --name centos-6.6 ./CentOS-6.6-x86_64-v20150426.box
==> box: Adding box 'centos-6.6' (v0) for provider: 
    box: Downloading: file:///Users/212464619/my-vagrant/boxes/CentOS-6.6-x86_64-v20150426.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```
With --debug, I found that it first error at
```
 INFO subprocess: Command in the installer. Specifying DYLD_LIBRARY_PATH...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libcups.2.dylib
  Expected in: /opt/vagrant/bin/../embedded/lib/libiconv.2.dylib
 in /usr/lib/libcups.2.dylib
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 5
 WARN downloader: Downloader exit code: 5
```
It seems that it is related to https://github.com/mitchellh/vagrant/issues/3972 ?

**Comment by jianghaitao** [comment]
OK, I think it is a valid Vagrant bug. The workaround I found is that to remove the library came with Vagrant: `libiconv.2.dylib`

After that, it seems ok
```
$ vagrant box add --name CentOS-6.6 ./CentOS-6.6-x86_64-v20150426.box 
==> box: Adding box 'CentOS-6.6' (v0) for provider: 
    box: Downloading: file:///Users/212464619/my-vagrant/boxes/CentOS-6.6-x86_64-v20150426.box
==> box: Successfully added box 'CentOS-6.6' (v0) for 'virtualbox'!
```

**Comment by wkalt** [comment]
I had the same symptoms on arch linux with vagrant 1.7.2. Reinstalling vagrant fixed the issue. The error line in the debug output was

```
DEBUG subprocess: stderr: /opt/vagrant/bin/../embedded/bin/curl: symbol lookup error: /usr/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
```

**Comment by mitchellh** [comment]
This is probably a dup of #4543

**Comment by mailkrips** [comment]
I ran into the same error. This is what worked for me:
sudo mv /opt/vagrant/embedded/lib/libiconv.2.dylib /opt/vagrant/embedded/lib/libiconv.2.dylib_
once the file was renamed, the command ran fine.

**Comment by jeremywhittington** [comment]
For me the problem was I did not have Microsoft Visual C++ Redistributable installed. I figured this out by trying to run curl and got the error “The program can’t start because MSVCR100.dll is missing from your computer.”. After installing the latest version of the c++ redist everything worked.

I was on a fresh install of windows 10, vagrant, virtualbox and the latest version of curl 64bit.

**Comment by ssoriche** [comment]
I just ran into this problem on macOS Sierra fresh install (Vagrant 1.8.7).

**Comment by ajaykagrawal** [comment]
I am also running into this issue (Vagrant 1.8.7, macOS Sierra version 10.12.1). Any workarounds?

**Comment by ssoriche** [comment]
When running with --debug I discovered that the real issue was #7970 and the work around of removing `/opt/vagrant/embedded/bin/curl`, fixed it. It's unfortunate that the error message is not more indicative of what is actually wrong.

**Comment by ajaykagrawal** [comment]
this fixed it! Thanks for the quick response!
