### ISSUE TITLE
Port Forwarding issue when running OpenBazaar on Vagrant

### ISSUE THREAD

**Issue by ahummel25** [mitchellh/vagrant#5784]
Is anyone here familiar with how to port forward your vagrant VM so that you can successfully fire up OpenBazaar on it?

I keep thinking I have it right but I keep getting these errors every time.

![image](https://cloud.githubusercontent.com/assets/12643871/7947190/3104a648-0941-11e5-977c-d8aa38e84507.png)

**Comment by sethvargo** [comment]
Hi @ahummel25 

Please open usage-related questions on the Vagrant mailing list. We prefer to keep GitHub issues reserved for bug reports and feature requests. Thanks! :smile:
