### ISSUE TITLE
liblzma shipped in /opt/vagrant/embedded does not have versioned symbols on Ubuntu

### ISSUE THREAD

**Issue by doudou** [mitchellh/vagrant#5787]
The liblzma version shipped in the debian package does not have versioned symbols. This causes problems when installing e.g. vagrant-libvirt, which depend on libraries that require these symbols

See https://github.com/mitchellh/vagrant/issues/5118 and https://github.com/pradels/vagrant-libvirt/issues/346.

Making sure that liblzma is compiled with versioned symbols would fix this compatibility problem.

**Comment by mitchellh** [comment]
Can you please contribute a solution to vagrant-installers? (https://github.com/mitchellh/vagrant-installers) Or, guide me on how to enable these. Thanks.

**Comment by doudou** [comment]
@mitchellh: I have to admit that I have simply no idea on how to enable that ... Probably the debian package build rules could be of some help ...
