### ISSUE TITLE
Any timeline for 1.7.3 release?

### ISSUE THREAD

**Issue by guanqun** [mitchellh/vagrant#5791]
Because I'm depending on the virtualbox 5.0 support.

**Comment by heyyoyo** [comment]
+1

**Comment by heyyoyo** [comment]
I just found this issue, which explains how to make it work with the actual vagrant 1.7.2:
https://github.com/mitchellh/vagrant/issues/5572

Works great for me.

**Comment by sethvargo** [comment]
Hi @guanqun 

We do not have an estimated release date yet. Please watch the Vagrant mailing list and Twitter for the release announcement. Thanks! :smile:

**Comment by guanqun** [comment]
Thank you, I'll keep an eye on that.

**Comment by emkookmer** [comment]
+1
