### ISSUE TITLE
stdin is not available in custom provisioners

### ISSUE THREAD

**Issue by lfaraone** [mitchellh/vagrant#5796]
Lets say as part of a provisioner, you want to ask a user for their full name. So, you write:
``` ruby
    def configure(root_config)
      print "What's your full name? "
      full_name = gets.strip
```

Attempting to run `vagrant provision` will bail with:
```
[…]/vagrant/lib/provisioners/my_custom_provisoner.rb:18:in `gets': No such file or directory @ rb_sysopen - provision (Errno::ENOENT)
```

**Comment by sethvargo** [comment]
Hi @lfaraone 

Provisioners are designed to be headless, since a stdin is not available on all platforms. If you want user input, you should request them in the Vagrantfile and then pass them into the provisioner's environment:

```ruby
print "What is your full name?"
foo = gets.strip

Vagrant.configure(2) do |config|
  config.vm.box = "."
  config.vm.provision "shell" do |s|
    s.args = [foo]
  end
end
```

Does that answer your question?

**Comment by mitchellh** [comment]
The UI object that provisioners have access to also has an `ask` function you can use to ask for input.
