### ISSUE TITLE
Impossible to hide ansible-playbook command details in console output

### ISSUE THREAD

**Issue by gildegoma** [mitchellh/vagrant#5803]
Follow-up of https://groups.google.com/d/topic/vagrant-up/7ECDMjBUuy8/discussion

See also [this possible workaround](https://github.com/mitchellh/vagrant/blob/gildegoma/2103-ansible-local/plugins/provisioners/ansible/provisioner/base.rb#L137-L141).

Maybe it was not a logical/good idea to mix `VAGRANT_LOG` and `ansible.verbose` as possible parametrisation, but the idea behind was to "naturally" provide this information when running in *debug mode*. To be thought and discussed again...

**Comment by sethvargo** [comment]
IMO, the ansible log level should just be a top-level configuration option and not tied to Vagrant's log.

**Comment by gildegoma** [comment]
Yup, I agree and I'll revert this "asap". Thanks @sethvargo for your feedback :)
