### ISSUE TITLE
Puppet provisioner PATH cannot be found (Puppet 4)

### ISSUE THREAD

**Issue by lmayorga1980** [mitchellh/vagrant#5806]
Using the latest master, when running puppet provisioner it fails trying to find the PATH of puppet binary file. But this works normally when using the **shell provisioner**

![screen shot 2015-06-08 at 12 42 08 pm](https://cloud.githubusercontent.com/assets/3172378/8040109/f1d63474-0ddb-11e5-8e65-2d9b1ef4d96c.png)

![screen shot 2015-06-08 at 12 42 24 pm](https://cloud.githubusercontent.com/assets/3172378/8040115/0273f532-0ddc-11e5-9a68-6871da6a8afd.png)

![screen shot 2015-06-08 at 12 42 33 pm](https://cloud.githubusercontent.com/assets/3172378/8040118/09fbda86-0ddc-11e5-8625-56042ca2f25c.png)

**Comment by sethvargo** [comment]
This is probably a bug introduced by recent changes. If you are able to track it down to a specific commit, that would be super helpful!

**Comment by ferventcoder** [comment]
@sethvargo running into a similar issue, not quite the same on the linked issue. In this case it appears that whatever is calling puppet isn't restarting the shell first. Do you know of any changes in the 1.7 series that would have changed to a longer lived-shell?

**Comment by ferventcoder** [comment]
Looks possibly like this one - https://github.com/mitchellh/vagrant/commit/3a2a9a3b948f1dc7f8dc7a49494e4c48eaf5a5e6

**Comment by benh57** [comment]
I'll fix this since i broke it :)

**Comment by lmayorga1980** [comment]
@benh57 :+1:

**Comment by mitchellh** [comment]
This is fixed in master!

**Comment by benh57** [comment]
Just tried and this doesn't appear to be fixed in Vagrant 1.7.3...

**Comment by benh57** [comment]
Submitted PR which fixes the path detection, however, vagrant now fails to provision via puppet on windows with a 'path too long' error, not sure why, investigating that.

**Comment by benh57** [comment]
Ok, it seems the path too long failure is related to facter, but puppet runs fine with no facter vars set. will file a different issue for that problem.

**Comment by ferventcoder** [comment]
@benh57 thanks for that, what issue number did you file for that one?

**Comment by ferventcoder** [comment]
@benh57 I passed this along. I am curious, what version of facter/puppet are you running into this with?

**Comment by ferventcoder** [comment]
I also proactively filed at ticket for a placeholder while we diagnose this issue - https://tickets.puppetlabs.com/browse/FACT-1127

**Comment by benh57** [comment]
Here's the facter path length issue https://github.com/mitchellh/vagrant/issues/5660  feature request: https://github.com/mitchellh/vagrant/issues/4762

**Comment by benh57** [comment]
After upgrading to puppet 2015.2.0, autodetection broke on linux again. I submitted a new PR to fix that. 

https://github.com/mitchellh/vagrant/pull/6057
