### ISSUE TITLE
Doesn't Install On OSX 10.11 Beta 1

### ISSUE THREAD

**Issue by bassrock** [mitchellh/vagrant#5807]
After upgrading to OS X 10.11 Beta the vagrant command disappeared and reinstalling has no affect. Vagrant never ends up in the /user/bin directory. 

The installer does complete successfully however.

**Comment by mitchellh** [comment]
We'll support 10.11 in due course, but generally wait a few betas since so much changes.

**Comment by bassrock** [comment]
For those that are curious. This has to do with the new system security. OS X 10.11 does not allow installing into system locations. So the installer auto-migrated them to /opt and the installer installs there too now.

**Comment by onlydole** [comment]
Thank you @bassrock! I would have been in a pickle without that info. I was successfully able to add it to my /usr/local/bin and add a path to it and circumvent any issues.

**Comment by bassrock** [comment]
Yep you will most likely have this issue with anything that installs to /usr/bin like https://github.com/chef/chef-dk

**Comment by rtorcato** [comment]
/opt/vagrant/bin/vagrant up is working for me. Just need to update PATH

**Comment by kylestev** [comment]
@rtorcato thanks, this solved my issue!

**Comment by jeroenvisser101** [comment]
@bassrock wouldn't it be nice to install to /usr/local/bin anyways?

**Comment by bassrock** [comment]
Probably but I'm not the maintainer.

**Comment by uipoet** [comment]
I agree that Vagrant should alias it's binary to `/usr/local/bin`. Virtualbox, for example, already installed there and had no issue with 10.11's new rootless scheme. Seems this change would be backwards-compatible.

Why is this issue closed?

**Comment by themccallister** [comment]
I know this issue is closed, but a REALLY quick work around to this is to add a simple alias.

I added this line to my `.zshrc`

`alias vagrant="/opt/vagrant/bin/vagrant"`

**Comment by fwartner** [comment]
I fixed by uninstalling it and install vagrant again.

**Comment by greghollowell** [comment]
Sharing this just in case anyone else runs into the same comedy of errors I did: 
After running   <code>ln -s /opt/vagrant/bin/vagrant /usr/local/bin/vagrant</code>
<code>vagrant up</code> still produced the following error: <code>There was an error while executing `VBoxManage`, a CLI used by Vagrant for controlling VirtualBox. The command and stderr is shown below.</code>

Updating and restarting VirtualBox in addition to setting up the symlink for Vagrant got me back up and/or running.

**Comment by baddox** [comment]
@greghollowell What do you mean exactly by "updating and restarting" VirtualBox? Did you just uninstall and reinstall it?

**Comment by greghollowell** [comment]
@baddox I just opened the app and it prompted me to update - I had to search for the app as I've never had to actually run it manually. It prompted me to update - if you don't get a prompt upon opening, go to VirtualBox > Check for Updates in the menu bar. From there on, it will update if necessary and restart itself in the process.

**Comment by ctessmer** [comment]
Hey Mac users,

I'm dumb. 

I didn't know how to updated/re-install virtualbox. You'd think it'd be on the downloads page at virtualbox. No. Or apparently I'm blind. Instead:

1. Go to your applications folder.  
2. Find the virtualbox app. 
3. If there is an update available, it'll show you a link. 
4. Click that. It'll download.
5. Open the download and install. 

Oh. And then you have to do the a similar thing with vagrant. But it's way easier. Just go to [this link](https://www.vagrantup.com/downloads.html) and you probably know how to do the rest. If not, that means you're more dumb than me, and you're gonna have to admit it. Don't worry. Admitting you have a problem is the first step to recovery. 

Love, 
Christian

**Comment by rtorcato** [comment]
@ctessmer you win! Yours is officially the dumbest comment I've ever read on github. Congratulations. I hope anyone that thinks of hiring you reads your comments. 

Bashing users about an old issue with beta software is the dumbest thing ever (next to paying for Windows updates)

Good luck in life (you'll need it)

**Comment by gridmaster** [comment]
None of these fixed my issue. Just needed one more step. I had to reinstall (actually upgrade was the issue) both Vagrant and VirtualBox plus I had to add opt/Vagrant/bin to my path.

export PATH=$PATH:/opt/Vagrant/bin
