### ISSUE TITLE
Document config.vm.network nic_type option

### ISSUE THREAD

**Issue by lmakarov** [mitchellh/vagrant#5812]
The **nic_type** option has been around since 2012 (https://github.com/mitchellh/vagrant/issues/690) however it was never documented in the [Networking](https://docs.vagrantup.com/v2/networking/index.html) section on https://docs.vagrantup.com/

It is often being referred to as **nictype** (no underscore), which does nothing.

**Wrong**
```
config.vm.network <other settings> :nictype => "virtio"
```

**Correct**
```
config.vm.network <other settings> nic_type: "virtio"
```

An alternative approach that always worked (and most likely was the source of this confusion) is:
```
config.vm.customize ['modifyvm', :id, '--nictype1', 'virtio']
```

**Comment by sethvargo** [comment]
Hi @lmakarov 

Thank you for pointing this out. Would you like to submit a Pull Request to update the docs? All the docs are open source and live in this repo in the `website/docs` folder.

**Comment by mitchellh** [comment]
Done
