### ISSUE TITLE
/usr/bin is not writeable on Mac OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by mathie** [mitchellh/vagrant#5816]
I wondered why vagrant had disappeared from my path this morning. In the end, I discovered that `/usr/bin` isn't writeable on Mac OS X 10.11 El Capitan -- even by root! I've worked around it by sticking a symlink in `/usr/local/bin/vagrant` pointing to `/opt/vagrant/bin/vagrant`. Perhaps the installer could be tweaked to do this automatically?

**Comment by sethvargo** [comment]
Duplicate of https://github.com/mitchellh/vagrant/issues/5807

**Comment by elikem** [comment]
@mathie Thanks a lot for your comment. It was most useful :+1:
