### ISSUE TITLE
Allow creating additional temporary/scratch VMs alongside the default machine

### ISSUE THREAD

**Issue by edmorley** [mitchellh/vagrant#5817]
Sorry if this has been filed already - I searched a bit but couldn't find anything.

Vagrant already has a multiple machine feature (http://docs.vagrantup.com/v2/multi-machine/), which is great - however it's mainly for the use case of having multiple pre-defined machine with different configurations (eg "web" and "db").

What I'm after is a way to spin up additional arbitrarily named VMs from an existing Vagrantfile, without clobbering my existing box. The use cases for this are:
* Wanting to quickly test something in a clean environment without clobbering my main box. eg reviewing a PR, or trying to work out whether an issue I'm having on the main box is due to a something I've broken in it.
* Developing multiple features over a few months, where I want each feature to have a separate environment and databases (particularly for features involving schema changes).

It is possible to create something that achieves this, by abusing the multi-machine feature (eg mozilla/treeherder#620) - however this only allows a fixed number of scratch machines and with pre-chosen names - and deviating from what's committed would require constantly updating the Vagrantfile and stashing the changes for it (since each dev would have their own feature names specified there etc).

What would be ideal is something like:
``vagrant up temp1 --create``
...which would create a new machine named `temp1` using the default Vagrantfile configuration.

This named machine would appear in `vagrant status` until destroyed, at which point it would no longer be shown there. It would also have autostart set to false unless otherwise specified.

**Comment by mitchellh** [comment]
Vagrant 1.8 supports snapshots, so this would be the ideal way to do this. (1.8 will be released soon)

**Comment by edmorley** [comment]
Ah that sounds perfect - many thanks :-)
