### ISSUE TITLE
 Shell provisioner doesnt run sed properly ?

### ISSUE THREAD

**Issue by petergdoyle** [mitchellh/vagrant#5822]
I was looking for issues related to sed and the Shell provisioner and I found  "Shell provisioner doesnt run sed properly #4611"

issuing this sed command works fine:

```
sed -i '/# User specific aliases and functions/a source aliases' /home/vagrant/.bashrc
```

when changing the default delimiter (to use url address in the expression) to something other than '/', the provisioner complains:

```
sed -i '\|# System wide functions and aliases|a export HTTP_PROXY=http://proxy.mycompany.com:8080/\nexport HTTPS_PROXY=http://proxy.mycompany.com:8080/\nexport http_proxy=http://proxy.mycompany.com:8080/\nexport https_proxy=http://proxy.mycompany.com:8080/' /etc/bashrc
```

```
==> default: sed: -e expression #1, char 1: unknown command: `|
```

in fact even if the line is commented out it complains

```
==> default: /tmp/vagrant-shell: line 14: unexpected EOF while looking for matching `''
==> default: /tmp/vagrant-shell: line 17: syntax error: unexpected end of file
```

debug info

```
 INFO interface: info: sed: -e expression #1, char 1: unknown command: `|'
 INFO interface: info: ==> default: sed: -e expression #1, char 1: unknown command: `|'
==> default: sed: -e expression #1, char 1: unknown command: `|'
```

I can provide more of the debug log - but seems like some type of an interpreter error when reading the sed command ???

If there is an alternate escape sequence that i should be using that would be fine, but i don't see one available.

**Comment by sethvargo** [comment]
Hi @petergdoyle 

I believe the issue is that you need to double-escape. The escaping syntax for Ruby is very similar to bash/sh. As such, you may need to double-escape. Alternatively, you can use an external shell script.

Please let me know if that makes sense.

Best,
Seth

**Comment by petergdoyle** [comment]
thanks. let me try and will get back to you.
appreciate the help.
peter

**Comment by petergdoyle** [comment]
I actually was not successful with the escaping (i am not a ruby programmer i guess) and i went back to the default delimiters and used environment variables. This works below (even in the comments). So I guess it still could just be a ruby escape issue (programmer error) rather than Shell provisioner:

```
export HTTP_PROXY=http://host.com:port/

sed -i "/# System wide functions and aliases/a export HTTP_PROXY=$HTTP_PROXY\\nexport HTTPS_PROXY=$HTTP_PROXY\\nexport http_proxy=$HTTP_PROXY\\nexport https_proxy=$HTTP_PROXY" /etc/bashrc

**Comment by petergdoyle** [comment]
i think this was programmer defect more than a vagrant issue
