### ISSUE TITLE
Vagrant can't mount shared folders in VirtualBox

### ISSUE THREAD

**Issue by er-net** [mitchellh/vagrant#5824]
I'm re-opening an [old issue](https://github.com/mitchellh/vagrant/issues/3341) which seems to still affect Vagrant.

I've tried several versions of VB (including 4.2.*) and nothing works. The problem keeps popping up randomly on some machines. 

For me and my team, it makes it impossible to work with Vagrant + Virtual Box, since we must sync some of our folders.

**Comment by sethvargo** [comment]
Hi @er-net 

Can you please share your complete `Vagrantfile` and the result of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by er-net** [comment]
Hey @sethvargo 

At the moment all my machines seems to work fine (after re-installing VB to the latest version today),  so I can't share the debug result, but I'm sure the problem will pop up in next few days.

Anyway, here's my [VagrantFile](http://www.pastebin.ca/30279800).
If you think the script I'm running in the provisioning is relevant then I'll attach it as well (it simply runs an Ansible playbook locally).

**Comment by npiguet** [comment]
Seems to be related to https://github.com/mitchellh/vagrant/issues/5821

**Comment by er-net** [comment]
I tried to create a new machine today with a much thinner [VagrantFile](http://pastebin.com/EEgyQs0M), and the problem occurred once again.

I captured the "vagrant up --debug" output [here](http://pastebin.com/8jM5KT60), and also the [/var/log/vboxadd-install.log](http://pastebin.com/gidyp42M) file from the guest machine.

**Comment by er-net** [comment]
@sethvargo any news with that?

**Comment by mitchellh** [comment]
@er-net Your debug log shows an error that Vagrant is getting from the VM that the `vboxsf` filesystem is simply unavailable. This is not a Vagrant issue (if this is the issue at hand): the guest needs to have that kernel module properly setup.

A common issue is that you updated the kernel. This will break that.

If there is anything more we can do to help, please let us know.
