### ISSUE TITLE
Add option to use external Docker host

### ISSUE THREAD

**Issue by ijin** [mitchellh/vagrant#5825]
When using Vagrant with the Docker Provider on a non-Linux host, a Docker host VM is first spun up, before the Docker container is launched. In the case of OS X, the boot2docker vagrant host image.

If I already have boot2docker running (via `boot2docker start`), or if I have an external Docker host running (configured by Docker Machine, for instance), then I would like Vagrant to use that Docker host without spinning up a host VM.

To my understanding, Vagrant automatically spins up a host VM regardless for non-Linux hosts.
https://github.com/mitchellh/vagrant/blob/master/plugins/providers/docker/provider.rb#L126-L129

**Comment by mitchellh** [comment]
This would be difficult to support since Vagrant also expects to be able to SSH onto that machine to do things (mount synced folders and so on). I don't think this is currently in the scope of our docker support.
