### ISSUE TITLE
Docker containers cannot be restarted after virtualised host reload

### ISSUE THREAD

**Issue by oxygen0211** [mitchellh/vagrant#5830]
When using the Docker provider with a virtualised (VBox 4.3) Docker host (on Windows, but I don't expect it to make a difference to OS X on this issue), me and my colleaques noticed, that Docker containers with synced folders won't be persistent. Here's what (I think that) happens:

In an environment with one or more Docker containers with synced folders enabled, we do a Vagrant up, everything is OK and works as expected. Then, for some reason (mostly because the User shuts down his PC), we do a halt or reload of the Docker host, everything OK so far, too. 

But when we now restart the Docker host, the synced folders won't be available on the Docker host since transient synced folders are used for syncing with the Containers which and they will not be persisted across restarts. Due to this, when the Docker deamon inside the VM starts, it won't be able to start the containers which were running after Vagrant up because it is missing the volumes mounted into them.

I think most of the problem would be solved if instead of using transient ones, the synced folders for Docker Containers would be realized using standard shared folders. Is there a reason this is done otherwise in the moment?

**Comment by mitchellh** [comment]
VirtualBox won't let you add non-transient shared folders while a VM is running. However, this still sounds like something we need to look into.

**Comment by oxygen0211** [comment]
I investigated this myself with the intent to provide a fix after opening this issue. This came to halt on exactly that point. 

I agree that there should be an improvement since this makes it very hard to use vagrant as a platform for crating longer running docker environments on non Linux machines.

To make it even harder: when restarting the VM we have the problem with the synced folder kind of the other way around. Since Docker is already installed on the Host, the Docker daemon will start after the machine is booted and will immediately try to boot start the container(s) which will then try to mount the (nonexisting) synced folders. I think this causes a high risk for race conditions.

**Comment by mitchellh** [comment]
Actually I don't think there is a strong use case to fix this. The workflow imagined was: if the host VM restarts, then the containers on the host need to be `vagrant up` again anyways (ignoring restart policies), which will fix those folders. I'd rather keep it simple that way, I can update the documentation to point it at that.
