### ISSUE TITLE
Failed to vagrant up bridged network due to enconding issue in vbox file with non-english windows 8 and vagrant 1.7.x

### ISSUE THREAD

**Issue by csiszarattila** [mitchellh/vagrant#5832]
My vagrant box stopped working after upgrading from 1.6.5 to the latest 1.7.2 vagrant. 
Virtualbox gives error that failed to run virtual machine due to not finding the network adapter.
I dug deep and find out that this error related to that:

a) I have non-english windows and my network adapter name contains non english characters.
b) in .vbox file under bridgedinterface the cards 'name' property is different between versions:

In 1.6.5:
```
<BridgedInterface name="Intel(R) 82579LM Gigabit h&#xE1;l&#xF3;zati kapcsolat"/>
```
In 1.7.2:
```
<BridgedInterface name="Intel(R) 82579LM Gigabit h&#x102;&#x17A;l&#xCB;&#x2021;zati kapcsolat"/>
```
With 1.7.2 it contains 2 byte UTF characters, and I believe thanks to that virtualbox failes to find the network adapter and cannot bring up the machine.

Any suggestion?

**Comment by sethvargo** [comment]
Hi @csiszarattila 

I think this might be a bug with Ruby (the language Vagrant is written in) as opposed to Vagrant itself. Ruby does not handle non-ASCII characters very well.

**Comment by mitchellh** [comment]
We'd love to fix our encoding issues, and we have many in Vagrant, but need some community help to do so. There is a very old issue tracking this.

**Comment by samphippen** [comment]
@mitchellh I don't know enough about the underlying Virtualisation tech to know what's going on here, shall I pop you an email?

**Comment by mitchellh** [comment]
@samphippen Vagrant queries the network adapters in various places, so this is probably causing problems. Let me show you where: https://github.com/mitchellh/vagrant/blob/3b7117b6890dee24af540bb53f726ae45f301bc5/plugins/providers/virtualbox/driver/version_5_0.rb#L410

I'm guessing this is where bad things are happening.
