### ISSUE TITLE
Support wget for box download, and prefer over curl

### ISSUE THREAD

**Issue by patcon** [mitchellh/vagrant#5833]
When the ability to resume box downloads was added, [it was noted](https://github.com/mitchellh/vagrant/pull/2518#issue-23024178) that the download percent indicator was wonky, in that resumes downloads always restarted at 0%, even when progress had been made already. This is due to underlying `curl` behaviour.

`wget --continue` doesn't suffer from this issue, as better indicates progress. Would be great to use wget when available, making the download resumption feature more obvious for those not reading output lines closely. (I just watch the progress bar, and so didn't learn for a year that this was a feature, instead preferring to download my boxes manually via wget first :)

**Comment by sethvargo** [comment]
Hi @patcon 

Thank you for opening an issue. Unfortunately this is not possible. The box hosting service does not support byte range queries or resumes. See https://github.com/mitchellh/vagrant/issues/5237 for more information.

We do not package wget with Vagrant and we will likely be switching to a pure-ruby downloader eventually (maybe).

We are thinking around better solutions here and hope to have something after the next release. Thanks!

**Comment by patcon** [comment]
Thanks for the quick repl y @sethvargo -- was just investigating, so I appreciate saving me effort.

fwiw, I'm seeing box download resumption working for `vagrant up` when using the `ubuntu/precise64` box. I haven't dug any deeper than confirming this fact via `du -s ~/.vagrant.d/tmp/box*` though

**Comment by sethvargo** [comment]
Hi @patcon 

Ubuntu boxes are self-hosted (on S3 I believe), so it's just a 301 redirect from Atlas. Other boxes are hosted by Atlas and they do not support resumes.

**Comment by patcon** [comment]
:+1: gotcha. thanks :)
