### ISSUE TITLE
vagrant up intermittently hangs on setting hostname when config.ssh.insert_key set to false 

### ISSUE THREAD

**Issue by mixja** [mitchellh/vagrant#5835]
I am using Vagrant 1.7.2 on OS X Yosemite with VMWare Fusion 7.1.1 and VMWare Fusion provider 3.2.6.  

I have `config.ssh.insert_key = false` to avoid another issue (similar to https://github.com/test-kitchen/kitchen-vagrant/issues/130) where the vagrant hostmanager plugin intermittently fails and prompts for a password on the vagrant box that never authenticates correctly.

With the above configuration I found that on a `vagrant up` if the initial SSH connection fails, then the `vagrant up` hangs on the `Setting hostname...` step:

```
==> redis: Cloning VMware VM: 'cloudhotspot/ubuntu'. This can take some time...
==> redis: Checking if box 'cloudhotspot/ubuntu' is up to date...
==> redis: Verifying vmnet devices are healthy...
==> redis: Preparing network adapters...
==> redis: Fixed port collision for 22 => 2222. Now on port 2204.
==> redis: Starting the VMware VM...
==> redis: Waiting for machine to boot. This may take a few minutes...
    redis: SSH address: 192.168.174.134:22
    redis: SSH username: vagrant
    redis: SSH auth method: private key
    redis: Warning: Connection reset. Retrying...
==> redis: Machine booted and ready!
==> redis: Forwarding ports...
    redis: -- 22 => 2204
==> redis: Setting hostname...

# vagrant up process hangs here
```

The only way to fix is to `vagrant destroy` and try again.  This also only seems to happen when running in a multi-guest vagrant environment.  Starting each guest up one by one also seems to avoid the issue (but this is a pain).

If I set `config.ssh.insert_key = true` then this issue goes away but I get the other issue I described at the top.

**Comment by mitchellh** [comment]
Can you attach a debug log of when this hangs?

**Comment by mixja** [comment]
Please see https://gist.github.com/mixja/c5cb7821660dcb8ef72b

The `vagrant up failure` is the portion of the log related to the VM that fails to come up (as per bug description above). 

The `vagrant up failure complete` is the entire log for bringing up the entire Vagrant stack.

The `vagrant up success` is log after destroying the failed VM and then executing `vagrant up repo` to recreate it successfully

**Comment by mitchellh** [comment]
Great, thanks! I'm going to take a look at this tomorrow

**Comment by sethvargo** [comment]
Hi @mixja 

Is this still an issue with Vagrant 1.7.3?

**Comment by mixja** [comment]
Yes I just upgraded and retested, same issue occurs.

**Comment by mixja** [comment]
I have published the Vagrantfile and a YAML file vagrant.yml that feeds the Vagrantfile here - https://gist.github.com/mixja/cac4dc38821e80968e9f

**Comment by feliksik** [comment]
I have the same problem using VMWare Workstation 11, Vagrant 1.7.4. It does seem to happen with the same VM in the up list. 

The hostname is actually set, as I can see in the vmware GUI. 

I do not know how to generate the debug log, but I'd be happy to help debug this issue, as Vagrant issues are costing me a lot of valuable time now :-(

**Comment by feliksik** [comment]
It turns out that VMWare is giving the same IP address to different machines, as it's leases pool is full (see /etc/vmware/vmnet8/dhcpd/dhcpd.leases )

In some cases, the hostname is then actually set on the wrong machine. Possibly this also has to do with the keygen issue as reported by @mixja . 

I ran 'vagrant destroy', deleted the machines from vmware gui, shut down vmware, deleted /etc/vmware/vmnet8/dhcpd/dhcpd.leases , started vmware, and the issue was resolved.

**Comment by mitchellh** [comment]
Thanks @feliksik for the workaround. This is a bug we've reported with VMware that the leases don't get properly cleared. It is someting we can also look into doing automatically but that is pretty sketchy since we'd have multiple processes made by different people modifying a single file. So in this scenario let's just delete the leases file.

**Comment by mwl** [comment]
@mitchellh Have there been any feedback from VMware? I'm running the latest version, _8.1.0 (3272237)_ and it still seems to be affected.
