### ISSUE TITLE
All output go to the file

### ISSUE THREAD

**Issue by snowsky** [mitchellh/vagrant#5839]
When I run the command:
```
  vagrant ssh myserver -c 'sudo cat /etc/hosts' >> /tmp/hosts
```
It is found that all the output and keyboard interaction will be written into the file /tmp/hosts, like this:
```
  running
  127.0.0.1 cdn-vm-chef-hwang localhost localhost.localdomain localhost4 localhost4.localdomain4^M
```

Is this a known issue?

**Comment by sethvargo** [comment]
Hi @snowsky 

Thank you for opening an issue. This is expected as you are opening an SSH session and then redirecting all output to `/tmp/hosts` on your local host system. If you want to copy the contents within the guest, you will need to move the quotes:

```shell
vagrant ssh myserver -c 'sudo cat /etc/hosts >> /tmp/hosts'
```

**Comment by snowsky** [comment]
@sethvargo thanks for the reply. I am going to grab the contents of /etc/hosts on remote host and save it to local file. It seems this doesn't apply.

**Comment by amosshapira** [comment]
@snowsky if you want to copy the file to the host, assuming you are using VirtualBox, then perhaps you can copy it to the shared folder (default /vagrant). Another option would be to execute "scp" together with the config file generated by "vagbrant ssh-config myserver".

**Comment by sethvargo** [comment]
Hi @snowsky 

As suggested above, you should use shared/synced folders or, simpler, use scp to copy the entire file onto your local machine.

**Comment by snowsky** [comment]
Sorry, just noticed there were replies here...
I don't want to simply copy the file, but also need to get the outputs from commands. I made you confused about that.
