### ISSUE TITLE
Virtualbox throwing errors on Windows 10 TP on vagrant up

### ISSUE THREAD

**Issue by maxxon15** [mitchellh/vagrant#5841]
The VM I was trying to run was running perfectly on a Windows 7 machine.
I had upgraded to Windows 10 and tried out the same machine (with all the same configs and vagrant boxes), uninstalled and reinstalled virtualbox several times, but it still doesn't work.

Tried making a brand new VM - that didn't work too.

Here's the error

![a18edbb4-1430-11e5-9fde-f194c241f53d](https://cloud.githubusercontent.com/assets/1046598/8207708/e98262b0-1520-11e5-8166-629a81034b05.JPG)

P.S: This is a puphpet installation and I already notified them [here](https://github.com/puphpet/puphpet/issues/1716). They told me this might be a vagrant/virtualbox issue.

**Comment by jfranciscos4** [comment]
+1

**Comment by theantichris** [comment]
I'm having this issue also.

**Comment by mitchellh** [comment]
This is an error/bug with VirtualBox. Please report it there.
