### ISSUE TITLE
Encoding Error with solution, .../io.rb:32:in `encode': "\xA2\\" from GBK to UTF-8 (Encoding::UndefinedConvers

### ISSUE THREAD

**Issue by sunfeng32** [mitchellh/vagrant#5845]
# Environment and situation
Window8.1(Chinese)
`vagrant up` when I install this repository:
https://github.com/cbumgard/nodejs-vagrant

# Error Message:
`E:/ProgramFiles/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/u
til/io.rb:32:in 'encode': "\xA2\\" from GBK to UTF-8 (Encoding::UndefinedConvers
ionError)
        from E:/ProgramFiles/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/
lib/vagrant/util/io.rb:32:in 'read_until_block'
......`

# Solution:
## change the code in the 32th line of io.rb to:
`data << io.readpartial(READ_CHUNK_SIZE).force_encoding(‘UTF-8’)`

##### This is the first time I report an issue, sorry for the typesetting.

**Comment by mitchellh** [comment]
Vagrant has a lot of encoding issues tracked by a meta encoding issue (please search I don't know it off the top of my head). We don't want to add `force_encoding` since that often causes problems for other folks. We're still looking for a good fix.

**Comment by sinojelly** [comment]
I encounter this problem too. When I use in a environment without network, it falls back to use loop back network connection, I  use Windows 10 Chinese version, the Microsoft loop back test connection name has Chinese characters,so encounter this problem. Even after  I change the network configuration in virtual box to right loopback  connection name ,after run vagrant up, it also change it to messy code.
