### ISSUE TITLE
`vagrant plugin install` doesn't check if plugin is already installed and installs it anyway

### ISSUE THREAD

**Issue by rmldsky** [mitchellh/vagrant#5848]
One would expect that running `vagrant plugin install <plugin>` will not install the plugin if it is already installed. Seems now executing the command does it every time.

Vagrant 1.7.2
OSX 10.10.3

Not a big annoyance, but just letting know/reporting.

Thanks a lot for a great job on Vagrant (and other HashiCorp tools)!

**Comment by sethvargo** [comment]
Hi @rmldsky 

This is the expected behavior because `vagrant plugin install` is also the mechanism for which you update a plugin or rollback to a specific version. Tagging as docs so we can clarify that.

**Comment by mitchellh** [comment]
Fixed
