### ISSUE TITLE
Make Salt Version configurable in Windows Guest

### ISSUE THREAD

**Issue by obestwalter** [mitchellh/vagrant#5849]
At the moment version and location are hardcoded.

https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/bootstrap-salt.ps1#L2
https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/bootstrap-salt.ps1#L26

It would be very good to decouple the lifecycles of both projects and for cross project development/debugging.

It should be possible to set the installer location to an URL or a UNC path or a local path.

To use a mapped salt develpoment version it would be good to be able to completely skip the bootstrap step if this is not already possible but to use the mapped development version instead (I don't know exactly yet if this makes sense and how it would work - I am pretty much at the beginning to start debugging and fixing problems that touch on both projects - see also [here]( https://trello.com/b/vywwuncS/ci-for-salt-vagrant-windows) and especially [here](https://github.com/obestwalter/salt-windows-dev)).

**Comment by sethvargo** [comment]
Hi @obestwalter 

We would gladly review a Pull Request for this functionality. Thanks!

**Comment by obestwalter** [comment]
Sounds good - I am neither experienced in Ruby nor in Powershell, though. And I guess changes are needed in both parts to be able to pass settings from the Vagrantfile to the PS script, like it is possible already with Linux guests. So it would be necessary to introduce this mechanism for Windows guests first. Am I correct? 

I am definitiely willing to give it a shot with a little help. So two questions:

1. Is there any documentation for contributors I should be aware of?

2. Could you point me to some documentation how I can use the development environment for ``vagrant up`` from my local dev version alongside with a regular install of vagrant, which I use for production? I followed [the contribution guide](https://github.com/mitchellh/vagrant#contributing-to-vagrant) but I am missing the step where I can say ``vagrant up`` and the dev version is used instead of the installed version. 

Thanks!

**Comment by PatOShea** [comment]
This looks to add the functionality requested: https://github.com/mitchellh/vagrant/pull/5892

**Comment by obestwalter** [comment]
@PatOShea Woohoo!!!
@sethvargo will this make it into the upcomig release?

**Comment by obestwalter** [comment]
Resolved since 1.7.4
