### ISSUE TITLE
Add --rsync option to vagrant provision

### ISSUE THREAD

**Issue by yoshiwaan** [mitchellh/vagrant#5850]
Hi,

Providers that rsync data from the local machine to a remote machine in vagrant instead of mounting, such as vagrant-aws, don't play nicely with provisioners that need to keep data up to date outside of the /vagrant directory.

As a specific example, when running vagrant-berkshelf on an instance in ec2 created using vagrant-aws, running `vagrant provision` does not update any cookbook versions on the instance. This is because the data is synced to /tmp/vagrant-chef/<hash that matches shelf>/cookbooks and is not synced when provisioning. 

When vagrant provision is run only the /vagrant directory is rsynced. It would be good to add a --rsync option to the `vagrant provision` action so that all synced folders for the instance are synced (at the point directly after the /vagrant directory is rsynced).

Here are a couple of cases related to this, as I'm not sure where the correct location for this fix is. This seemed like a good general solution:

https://github.com/berkshelf/vagrant-berkshelf/issues/281
https://github.com/berkshelf/vagrant-berkshelf/issues/284
https://github.com/mitchellh/vagrant-aws/issues/385

**Comment by beddari** [comment]
This is a long standing issue across a lot of different plugins with duplicated code so I'd very much like a solution to this as part of core. For people coming from a simple vagrant setup (virtualbox+shared folders) to a more developed one (e.g multiple external providers) the fact that provision doesn't rsync breaks expectations.

**Comment by yoshiwaan** [comment]
@sethvargo 
If I could add an extra comment on this.
Although it's more difficult to implement it might be more useful to set a flag against each synced folder to state whether it's for provisioning (in the synced folders config file), and only sync those when running provision.
I'm sure there are use cases out there where people don't want to initiate a full sync for all synced folders on each provision.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!

**Comment by PierrePaul** [comment]
> Leaving it open is unfortunately making our issue count look higher than it is.

Closing valid issues to reduce the issue count is the way forward for vagrant now?

**Comment by beddari** [comment]
@PierrePaul That comment is not warranted - you are making yourself look bad. It is clearly stated that this feature is something they'd be open to add but that they are not working on it right now.

**Comment by yoshiwaan** [comment]
Is it still on a backlog somewhere if the issue is closed?

**Comment by nschlemm** [comment]
while it is still on the backlog (somewhere?!?) a usable **workaround** is using the [vagrant-triggers](https://github.com/emyl/vagrant-triggers) plugin
```ruby
config.trigger.before :provision do
    run "vagrant rsync"
end
```

**Comment by briancain** [comment]
Hi @nschlemm - actually in the next release the trigger functionality will be a core feature of Vagrant, so you won't need the plugin at all! It should just work.

**Comment by nschlemm** [comment]
@briancain thanks for the info! while that is definitely interesting news, I also must say I'm not a fan of how this issue was handled ...

**Comment by mpictor** [comment]
> not a fan of how this issue was handled

No kidding. The person who points out issues are being closed apparently to make vagrant look better is making themselves look bad and their comment is unwarranted? 

No.

A thousand times no.

If someone dislikes being called out for doing things, then the solution is to _not do them_. If that's untenable, then they need to take the criticism.

If I am making myself look bad by following in the footsteps of PierrePaul, then please, call me out... though I'll need a more detailed explanation of how this makes _me_ look bad. And if you really want to, add me to some private or public list of bad people... as long as you also link to this discussion _verbatim_ so that those reading the list know the crime I'm guilty of.
