### ISSUE TITLE
File Provisioner should (optionally) translate line endings

### ISSUE THREAD

**Issue by paulhoule** [mitchellh/vagrant#5851]
I do my development work mostly on Windows but I deploy to Unix.

If I am not careful with the editor I use,  I can get a file that "looks" OK but fails to run on the other side.  This particularly happens when I want to install a shell file on the target machine.

Add a team and it just gets worse because somebody will insist on using an off-brand editor.

Let's add an option to the file provisioner to sanitize line endings

config.vm.provision "file", source: "~/.gitconfig", destination: ".gitconfig", type: "text"

Better yet vagrant could guess at it based on file extensions,  using the table of mime types,  etc.

**Comment by sethvargo** [comment]
Hi @paulhoule 

Thank you for the issue. I'm not 100% convinced this is a problem that should be solved by technology as opposed to process, but I'm willing to consider it. You're using Vagrant for local development, but how do you prevent those incorrect line-endings from making it into production?

Git is also smart enough to translate line endings for you if you enable it :smile:.

**Comment by mitchellh** [comment]
I agree that I don't think we should be responsible every step of the way to convert line endings. Instead, I recommend uploading via the file provisioner, and then using the shell provisioner to run a command on the file to fix line endings if you line ending issues.
