### ISSUE TITLE
FreeBSD 10 Private network DHCP issue

### ISSUE THREAD

**Issue by emve-dev** [mitchellh/vagrant#5852]
When using DHCP with private network the first `vagrant up` is ok. But after trying `vagrant reload` or `vagrant halt` and `vagrant up` i get this error:
```
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

dhclient em1

Stdout from the command:



Stderr from the command:

dhclient already running, pid: 705.
exiting.
```

Heres my Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "chef/freebsd-10.0"
  config.ssh.forward_agent = true
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.synced_folder ".", "/vagrant", type: "nfs", id: "vagrant-root"
end
```
I am still able to ssh login but my /vagrant folder is empty (shared folder wasn't mounted).
To fix this issue I edit the `/etc/rc.conf` remove these lines:
```
#VAGRANT-BEGIN
ifconfig_em1="DHCP"
#VAGRANT-END
```
And after running `vagrant reload` everything works until the next `vagrant reload` (so I need to repeat the whole `rc.conf` editing.
There is still a line in `rc.conf` which makes DHCP work:
```
ifconfig_em0="DHCP"
``` 

Full `/etc/rc.conf`
```
zfs_enable="YES"
hostname="packer-freebsd-10.0-amd64"
ifconfig_em0="dhcp"  # This makes DHCP work
sshd_enable="YES"
rpcbind_enable="YES"
nfs_server_enable="YES"
mountd_flags="-r"
vboxnet_enable="YES"
vboxguest_enable="YES"
vboxservice_enable="YES"
ifconfig_vtnet0_name="em0"
ifconfig_vtnet1_name="em1"
ifconfig_vtnet2_name="em2"
ifconfig_vtnet3_name="em3"
#VAGRANT-BEGIN
ifconfig_em1="DHCP" # This makes `vagrant up` fail
#VAGRANT-END
```

ifconfig:
```
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=9b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
        ether 08:00:27:d1:4c:66
        inet 10.0.2.15 netmask 0xffffff00 broadcast 10.0.2.255 
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=9b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM>
        ether 08:00:27:e2:7a:bf
        inet 172.28.128.5 netmask 0xffffff00 broadcast 172.28.128.255 
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128 
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3 
        inet 127.0.0.1 netmask 0xff000000 
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
```

Versions:
Vagrant 1.7.2
Oracle VM VirtualBox Manager 4.3.28
OSX 10.10.3

Any help please?

**Comment by faken** [comment]
having the exact same problem with a similar setup! 
Any progress on this bug?

**Comment by emve-dev** [comment]
I switched to different box: https://github.com/wunki/vagrant-freebsd/issues/13#issuecomment-111218160
Using Vagrantfile from this repo: https://github.com/wunki/vagrant-freebsd/blob/master/Vagrantfile
It works.

**Comment by peerst** [comment]
Having the same problem with a packer build FreeBSD 10.1 box and VMware Fusion Provider

$ vagrant --version
Vagrant 1.7.2

$ vagrant plugin list
vagrant-share (1.1.3, system)
vagrant-vmware-fusion (3.2.3)

VMware Fusion:  Professional Version 7.1.2 (2779224)

OSX: 10.10.5

**Comment by mitchellh** [comment]
This looks like a box setup issue. However, if you can guide us for how to configure Vagrant to avoid this in the future we'd be happy to do so. Thanks.

**Comment by aleks-mariusz** [comment]
not sure why this issue was closed as it hasn't been fixed

in fact, I see the same issue as well.  Here's my understanding of the issue:

To me it seems that Vagrant is erroneously trying to manually re-set-up the interface after a reload (by running dhclient manually), when it was already previously set to start automatically by virtue of having set the DHCP flag on the interface in /etc/rc.conf.

Vagrant should either a.) NOT manually run dhclient after a reload if it added that line to /etc/rc.conf, or b.) it should not add the line to rc.conf and always run dhclient manually.. it is trying to do both.

**Comment by redondo-mk** [comment]
I had the same issue on bridged interface and I made it disappear with the following vagrant configuration entry.
```ruby
config.vm.network "public_network", bridge: 'enp4s0', auto_config: false
```
