### ISSUE TITLE
Vagrant ignores rsync__exclude options in post-command

### ISSUE THREAD

**Issue by maxbucknell** [mitchellh/vagrant#5853]
I have a complicated setup with my Vagrant synced folders, that necessitates an NFS share inside a wider rsynced folder. Naturally, I have the NFS share listed in my Vagrantfile as excluded. The relevant portion of my Vagrantfile is:

```ruby
# Disable the default synced folder: we don't need it.
config.vm.synced_folder ".", "/vagrant", disabled: true

# We define two synced folders. The first will be run when we
# explicitly call `vagrant rsync`, but will not constantly update.
# reasoning behind this is that the `htdocs/` directory contains
# many symlinks, and nfs freaks hates those.
config.vm.synced_folder ".", "/var/www/magento",
  type: "rsync",
  rsync__args: ["--archive", "-z"],
  rsync__exclude: ["vendor/"]

config.vm.synced_folder "./vendor", "/var/www/magento/vendor",
  type: "nfs",
  create: true
```

Whenever I call `vagrant rsync`, I get a long list of permissions errors. Interestingly, I do not get this error when I run `vagrant up`. The permission error looks like this:

> chown: changing ownership of `/var/www/magento/vendor/steverobbins/redismanager/src/skin/adminhtml/default/default/steverobbins/redismanager/redismanager.css': Operation not permitted

I get several thousand of these. (In my current project, I get 12488, which is the number of files inside my NFS share.) If I go scroll back to the top, I find the shell line that caused the error: (formatting mine)

```bash
find '/var/www/magento' '!' \
  -type l  \
  -a '('  \
    ! -user vagrant \
    -or \
    ! -group vagrant \
  ')' \
  -print0 | \
xargs -0 -r chown vagrant:vagrant
```

[Searching for "find"][search] in the Vagrant Github repo [finds the answer][answer]: we set permissions after syncing, to whatever the synced folder configuration told us to, but we do not respect excluded directories. This issue reveals itself because it is now trying to set permissions on an NFS share. The code looks like this:

```ruby
machine.communicate.sudo(
  "find '#{opts[:guestpath]}' " +
  "'!' -type l -a " +
  "'(' ! -user #{opts[:owner]} -or ! -group #{opts[:group]} ')' -print0 | " +
  "xargs -0 -r chown #{opts[:owner]}:#{opts[:group]}")
```

Is this a bug, or is it intended behaviour, and I am (sadly) in an edge case? A patch for this would probably execute an inverted grep on a regex that starts with `#{opts[:guestpath]}` and then joins the excluded paths together with an "or" operator.

Then, perhaps we can manipulate the find command, but that seems more complex.

[search]: https://github.com/mitchellh/vagrant/search?utf8=✓&q=find
[answer]: https://github.com/mitchellh/vagrant/blob/d7eaf503298014a93e1faa8da88947bc7d32ba58/plugins/guests/linux/cap/rsync.rb#L24

**Comment by mitchellh** [comment]
We do a basic fix for this now, but it isn't 100%. If you can find a cleaner fix and submit it I'd be happy to take a look. Thanks!
