### ISSUE TITLE
Vagrant RPM did not clean up everything when removed

### ISSUE THREAD

**Issue by cbeland** [mitchellh/vagrant#5856]
I downloaded and installed vagrant_1.7.2_x86_64.rpm on Fedora (I think 19 or 20 when I started, since upgraded to 21).

Today I uninstalled it with "yum remove vagrant" since our company is moving to Docker. It failed to clean up some files and directories it had installed:
/opt/vagrant
/opt/vagrant/bin [empty]
/opt/vagrant/embedded/ [full of all sorts of things: bin/  etc/  gems/  include/  lib/  rgloader/  share/  ssl/]

**Comment by mitchellh** [comment]
This should be fixed in the next release, I believe a newer version of fpm fixes this.
