### ISSUE TITLE
Vagrant doese not support VirtualBox 5.0, but windows only support VirtualBox 5.0

### ISSUE THREAD

**Issue by netroby** [mitchellh/vagrant#5857]
Vagrant doese not support VirtualBox 5.0, but windows only support VirtualBox 5.0.
So i can not using vagrant with virtualbox on windows 10

**Comment by NickMRamirez** [comment]
Virtualbox 5.0 is still in beta. I'm not sure when Vagrant adds official support? After it comes out of beta? Windows 10 is still in preview.

**Comment by sethvargo** [comment]
Hi @netroby 

The master branch of Vagrant currently supports VirtualBox 5. We will have an official installer out soon. Thanks!

**Comment by JonathanLevi** [comment]
Yes, that would be great. Please do let us know when an official installer is out (now that Virtual Box 5.0 is officially released. https://www.oracle.com/corporate/pressrelease/oracle-vm-virtualbox-5-070915.html).

Thank you vm @sethvargo !

**Comment by netroby** [comment]
Waiting for you new official installer release

**Comment by mwarkentin** [comment]
+1 - brew cask updated to [virtualbox 5.0](https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox.rb#L2), which means that you have to use the [old version](https://github.com/caskroom/homebrew-versions/blob/master/Casks/virtualbox43691406.rb) until this vagrant update is released.
