### ISSUE TITLE
How do I set VAGRANT_DOTFILE_PATH in Windows?

### ISSUE THREAD

**Issue by simkessy** [mitchellh/vagrant#5858]
I'm trying to clear up the sync issues with dropbox and vagrant. I found the post going into `VAGRANT_DOTFILE_PATH` file changes necessary to prevent the vagrant boxes from overwriting each other. The only instructions I found relate to Linux but my desktop is running Windows. 

How would I set VAGRANT_DOTFILE_PATH=.vagrant-desktop on a widows manchine please?

**Comment by sethvargo** [comment]
Hi @simkessy 

This depends largely on what shell you are using. Are you using Powershell? CMD?

**Comment by simkessy** [comment]
Hey sorry, thought I deleted the question. I ended up trying to edit local environment variables and putting the information in there. Worked perfectly. I though it'd be more complicated then that but it wasn't . 

Thanks for getting back to me though.
