### ISSUE TITLE
add box on windows occur error "could't open the file package.box"

### ISSUE THREAD

**Issue by jiyaping** [mitchellh/vagrant#5861]
1.  place the box file package.box in c:\ 
2.  type command  `vagrant box add testbox c:\package.box`
3.  result returned like below:
```
    ==> box: Adding box 'testbox' (v0) for provider:
    box: Downloading: file://c:/package.box
    box:
    An error occurred while downloading the remote file. The error
    message, if any, is reproduced below. Please fix this error and try
    again.

    Couldn't open file /package.box
```

i found that curl could't find the file path using slash on windows. and using backslash like `file://c:\\package.box` will work fine.

**Comment by sethvargo** [comment]
Hi @jiyaping 

What happens if you use the UNC filepath instead?

**Comment by jiyaping** [comment]
hi @sethvargo 

i have using `file:\\COMPUTERNAME\box\package.box` instead. and the result not changed.

**Comment by NickMRamirez** [comment]
Is it a problem of not being able to add the box if it's in a directory other than the current one? I have been able to do:

`vagrant package --base win2012_r2_x64 --vagrantfile Vagrantfile --output win2012_r2_x64.box`
`vagrant box add win2012_r2_x64.box --name nramirez/win2012_r2_x64`

where the box file is in the current directory.

**Comment by jiyaping** [comment]
Hi @NickMRamirez 
In current directory can work fine.

**Comment by mitchellh** [comment]
This is now fixed

**Comment by drmaddy736** [comment]
error Couldn't open file /c:/my-bahmni-vagrant/package.box
