### ISSUE TITLE
Update default paths on Windows?

### ISSUE THREAD

**Issue by NickMRamirez** [mitchellh/vagrant#5862]
Should the following paths, as defined in [vagrant/plugins/provisioners/chef/config/base_runner.rb](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/chef/config/base_runner.rb) use Windows-style paths, such as C:\vagrant-chef, when provisioning Chef on a Windows guest?

```ruby
@provisioning_path = "/tmp/vagrant-chef" if @provisioning_path == UNSET_VALUE
@file_backup_path   = "/var/chef/backup" if @file_backup_path == UNSET_VALUE
@file_cache_path    = "/var/chef/cache"  if @file_cache_path == UNSET_VALUE
```

Otherwise, we get errors about Chef-client not being able to find the roles, cookbooks, etc. Also, from an aesthetic point of view, creating `tmp` and `var` directories on Windows seems un-Windows like.

Related to [https://github.com/mitchellh/vagrant/issues/4974](https://github.com/mitchellh/vagrant/issues/4974)

**Comment by NickMRamirez** [comment]
Currently, this Vagrantfile works:

```ruby
Vagrant.configure(2) do |config|

  config.vm.box = "kensykora/windows_2012_r2_standard"

  config.vm.provision 'chef_zero' do |chef|
    chef.provisioning_path = 'C:/vagrant-chef' # note forward slashes OK
    chef.file_backup_path = 'C:/chef/backup'
    chef.file_cache_path = 'C:/chef/cache'

    chef.roles_path = 'roles'
    chef.add_role 'windowsnode'
  end
end
```

But if the three paths are commented out, it fails. 

```ruby
# chef.provisioning_path = 'C:/vagrant-chef'
# chef.file_backup_path = 'C:/chef/backup'
# chef.file_cache_path = 'C:/chef/cache'
```

This is my motivation for updating the default paths for Windows.

[Demo](https://github.com/NickMRamirez/vagrant_chef_windowsguest)

**Comment by sethvargo** [comment]
@mitchellh what is the preferred way in Vagrant to do OS-path-specific things like this?

**Comment by NickMRamirez** [comment]
Fails with the same errors on Vagrant 1.7.4
