### ISSUE TITLE
Cannot re-establish 'vagrant.d' folder after reinstalled

### ISSUE THREAD

**Issue by dsngbycd** [mitchellh/vagrant#5863]
I'm currently using vagrant on my Mac with OS X 10.10.3. Yesterday when I wanna reinstalled vagrant, I followed the instruction to uninstall it, that is, running the custom uninstall tool and then remove 'vagrant.d' folder under my user menu. It is announced that the 'vagrant.d' will recover when reinstall this software, but it didn't. Now I miss this folder and cannot mount any virtual machine. I have made every effort but they didn't work. I'm in dire need of mounting a machine. If someone could figure out the issue and reply me as soon as possible, I will be gratitude.

Btw, I removed this folder with the command of 'rm -rf /mypath', will this indicate something? Is this command that prevents 'vagrant.d' folder from reestablishing?

**Comment by sethvargo** [comment]
Hi @dsngbycd 

I am sorry you are having issues with Vagrant. When you remove the `.vagrant.d` folder, it is not recoverable (without using some kind of recovery software). Can you please point me to the documentation or article that says "vagrant.d will recover when reinstall this software" so we can clarify that?

**Comment by dsngbycd** [comment]
Hi! Mr. Vargo:

By saying that ‘vagrant.d cannot recover’ I mean there doesn’t exist such a folder at all after reinstalled, (instead of recovering all customized data)

I hope aforementioned statement would clarify my attitude, because I’m not sure if my post on Github has confused you.
If what you mean is exactly that “vagrant cannot generate a new ‘vagrant.d’ folder after reinstalled”, I would reckon that the instruction is somewhat misleading here: http://docs.vagrantup.com/v2/installation/uninstallation.html <http://docs.vagrantup.com/v2/installation/uninstallation.html>

“On every platform, remove the ~/.vagrant.d directory to delete the user data.
Running Vagrant will automatically regenerate any data necessary to run, so it is safe to remove the user data at any time.”

So if vagrant cannot generate such a folder at all after reinstalled, what should I do? I need to use it, but without this library vagrant cannot run at all. Anyway, I’m not pretty sure where the problem derived from, the lacking of ‘vagrant.d’ as the trigger of mounting failure is merely a matter of speculation, too. And this is the detailed information of my issue.

**Comment by sethvargo** [comment]
Hi @dsngbycd 

When you delete that folder, Vagrant will re-generate the files required to run, but it does not re-generate user data (there would be no way for Vagrant to recover that data). You will need to re-download boxes and all state information will be lost.

When you run any `vagrant` command for the first time, it will generate the `~/.vagrant.d` folder in your home directory. When you run `vagrant up`, for example, Vagrant will re-download any boxes associated with the current `Vagrantfile` and put them back in the `~/.vagrant.d` directory. Does that make sense?

Are there any errors or debugging information you can share? Thanks!

**Comment by dsngbycd** [comment]
So that’s really weird… Could you see where the problem is? Maybe something about virtualbox?I’m sure the box file is intact and it’s successfully imported to vagrant. Perviously, there is no issue with running this machine but now that it will throw several errors. In this link you will see my operation and the error: http://youtu.be/HAzsCV3_mBI <http://youtu.be/HAzsCV3_mBI>

And this is the returned error:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/Users/Leo/.vagrant.d/boxes/sparkmooc-VAGRANTSLASH-base/0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "sparkvmbase_1435241982874_16943", "--vsys", "0", "--unit", "6", "--disk", "/Users/Leo/VirtualBox VMs/sparkvmbase_1435241982874_16943/box-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /Users/Leo/.vagrant.d/boxes/sparkmooc-VAGRANTSLASH-base/0/virtualbox/box.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the imported medium '/Users/Leo/VirtualBox VMs/sparkvmbase_1435241982874_16943/box-disk1.vmdk' (VERR_VD_VMDK_INVALID_FORMAT)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Appliance, interface IAppliance
VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 779 of file VBoxManageAppliance.cpp

**Comment by sethvargo** [comment]
Hi @dsngbycd 

That error is coming from Virtualbox. Can you please try re-installing virtualbox and restarting your machine?

**Comment by dsngbycd** [comment]
Got it! But I reinstalled and restarted for several times it still throws error. Finally I even install the software with root account login but it does’t work, either. Now that I try to re-download the box file and try it again

**Comment by mitchellh** [comment]
I've updated the docs as well to clarify that this is not user data that is recovered, just core Vagrant files.
