### ISSUE TITLE
Providing splitted sha256sum files

### ISSUE THREAD

**Issue by craneworks** [mitchellh/vagrant#5865]
Currently there is a just a single file for every release containing all checksums for different packages. This needs a little bit of logic when using automated downloads which should check the download.

Nice would be something like just adding `.sha256sum` to each file. For example:
https://dl.bintray.com/mitchellh/vagrant/vagrant_1.4.0.dmg
https://dl.bintray.com/mitchellh/vagrant/vagrant_1.4.0.dmg.sha256sum

**Comment by sethvargo** [comment]
Hi @craneworks 

All our files are now on releases.hashicorp.com. All our projects use a single shasum file with a gpg-signed verification file as well. We do not plan on having a .sha256 per-download. Thanks!
