### ISSUE TITLE
error assigning static ip (CentOS7) - BOOTPROTO=dhcp already in config

### ISSUE THREAD

**Issue by diseq** [mitchellh/vagrant#5866]
vagrant-vmware-workstation plugin is not correctly assigning static ip adresses. error is located in ifcfg-*

as you can see, it is assignes both none and dhcp bootproto.

Vagrant config:
```
node.vm.network :private_network, ip: "10.211.55.101"
```

ifcfg-ens33:
```
#Generated by dracut initrd
NAME="ens33"
DEVICE="ens33"
ONBOOT=yes
NETBOOT=yes
UUID="fdb8eeb5-b057-47d5-a069-395bb13733cf"
IPV6INIT=yes
BOOTPROTO=dhcp
TYPE=Ethernet
#VAGRANT-BEGIN
#The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=10.211.55.102
NETMASK=255.255.255.0
DEVICE=ens33


PEERDNS=no
#VAGRANT-END
```

**Comment by phinze** [comment]
Hi @diseq - thanks for the report.

If you look at the config you quoted, you'll notice that the `BOOTPROTO=dhcp` line falls above the `VAGRANT-BEGIN` comment in a section that says "Generated by dracut initrd".

It looks like the bootstrapping process for this box left an old config sitting in `/etc/sysconfig/network-scripts/` that's getting in the way here.

Are you using a self-generated box or a public one? We should be able to tweak the way the box is generated to prevent the file from leaking.

To be clear, this is code in vagrant core we're talking about - nothing specific to `vagrant-vmware-workstation` - so I'll update the title to reflect that.

**Comment by diseq** [comment]
Hi @phinze,

thanks for your reply. it has been the packer build box. I'll close it here!
