### ISSUE TITLE
vagrant ssh not run but vagrant ssh default yes

### ISSUE THREAD

**Issue by remyRetail** [mitchellh/vagrant#5867]
Hello everybody,

I would like to have a vagrant on Ubuntu 14 LTS. I found a box for that but not in Ubuntu 14 version. Only in 12. I have upgrade my OS system with command : do-release-upgrade.
That's all right. The upgrade OS goes fine because the lsb_release -d tell me Ubuntu 14 LTS.

But
Now my vagrant ssh command not run and down in SSH "Warning: Remote connection disconnect. Retrying...".
But
If I launch a vagrant ssh default command I can connect it

For information, I activate a root account in my OS with password and I add this line in my Vagrantfile config.ssh.username = 'root'
config.ssh.password = 'vagrant'
config.ssh.insert_key = 'true'
This configuration run perfectly before upgrade my OS system with a vagrant ssh command.

Can you tell me what my vagrant reload or vagrant ssh not run but vagrant ssh default run ?

Thank you for your support.

**Comment by bizmate** [comment]
I am also experiencing a similar problem on Vagrant 1.7.2. In short the problem is that my authorized keys file gets a wrong public key added after some vagrant operation, i noticed with provisioning.

>$ vagrant provision
>Running Review Me install with mode: dev
>    default: 
>    default: Vagrant insecure key detected. Vagrant will automatically replace
>    default: this with a newly generated keypair for better security.
>    default: 
>    default: Inserting generated public key within guest...
>    default: Removing insecure key from the guest if its present...
>    default: Key inserted! Disconnecting and reconnecting using new SSH key...
>==> default: Running provisioner: puppet...
>Guest-specific operations were attempted on a machine that is not
>ready for guest communication. This should not happen and a bug
>should be reported.

This operation changes my key and i am stuck out the VM again.

This (workaround)[http://stackoverflow.com/questions/22922891/vagrant-ssh-authentication-failure/30792296#30792296] is ok to readd the key but i cannot provision until this bug is checked. I ll try re-installing and check if it is ok after that

**Comment by bizmate** [comment]
Pls confirm if my fix in the workaround link works? Also this box is already available on 14.04.
Also as i noticed your changes. You are trying to ssh with the root user. The 'vagrant ssh default' just shows configuration. 

You better off using the standard vagrant user

**Comment by remyRetail** [comment]
I don't use a public/private ssh Key for connection on Vagrant. I never added a key.
I know linux and the security rules but for working with local system I want a root.

I don't find a box already Ubuntu 14 LTS. Vagrantbox.es write that box is in 14 LTS but it's wrong !

I reprovisioning my vagrant and now I must run vagrant up and I don't run a vagrant ssh default. Now my vagrant is dead...Impossible to connect on it.

**Comment by mitchellh** [comment]
Can you please add a `--debug` log to this issue via gist? I'm unable to diagnose the issue with the information available.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still an issue, could you please open a _new_ issue and include the complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks! :smile:
