### ISSUE TITLE
Vagrant/virtualbox on OSX aborted when wifi turned off

### ISSUE THREAD

**Issue by dcosson** [mitchellh/vagrant#5870]
I'm on OSX 10.10.3, Vagrant 1.7.2, Virtualbox 4.3.22 r98236

Vagrant & virtualbox will be running fine and then when I turn of the wifi (from the status bar at the top right on OSX) it immediately goes into status aborted. I can do vagrant up and it comes back up in ~10 seconds and works, but it's a bit distracting as the router I'm on is having issues and toggling the wifi on/off is the only workaround I can find.

Just wanted to check, is this normal behavior/ has anyone else noticed it or have a workaround?

**Comment by bizmate** [comment]
Are you sure it is not just an internal networking problem rather than a problem with Virtualbox killing you machine? Can you check in Virtualbox what happens? Although I am not an expert I would probably check either virtualbox or if something dodgy happens in your internal network (I mean in your laptop interfaces, i.e. eth0 etc) when something changes in your WiFi

I would not expect Vagrant to monitor your vm. Vagrant just talks to virtualbox when starting (up), modifing/configure (provision) etc. After that is done there is no monitoring ... it just ceases as it has done its job

**Comment by dcosson** [comment]
Thanks for the response. It could definitely be a Virtualbox issue but I was hoping this forum might be more active or that other vagrant users might have seen this and have a workaround. Not too sure what to look for with the networking interfaces but nothing jumps out, ifconfig output is the same after suspending gracefully as after one of these crashes.

In the logs I only see this over and over while it's booting:
```
00:24:16.551362 nspr-5   ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={480cf695-2d8d-4256-9c7c-cce4184fa048} aComponent={SessionMachine} aText={This machine does not have any snapshots}, preserve=false
00:24:16.618304 nspr-5   ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={480cf695-2d8d-4256-9c7c-cce4184fa048} aComponent={SessionMachine} aText={This machine does not have any snapshots}, preserve=false
00:24:16.689002 nspr-2   ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={480cf695-2d8d-4256-9c7c-cce4184fa048} aComponent={SessionMachine} aText={This machine does not have any snapshots}, preserve=false
```

And then when it crashes, the only additional line is:
```
00:10:45.247599 Watcher  Reaper: Pid 26820 (68c4) was signalled: 11 (0xb)
```

I have figured out a workaround for the time being though - if I launch it via `vagrant up` while the wifi is turned off, then I can toggle the wifi on and off and the VM doesn't crash. But if I launch it when the wifi is on and connected to a network, then as soon as the wifi turns off the VM crashes.

**Comment by sethvargo** [comment]
Hi @dcosson 

This definitely looks like a virtualbox issue, although I just tried to reproduce your issue and I am unable to do so (VirtualBox 4.3.26, Vagrant 1.7.2 and Vagrant master). I also could not reproduce your issue on VMware. It would be helpful if you could include `Vagrantfile` and then gist the output of the `vagrant up` command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html). Thanks!

**Comment by mitchellh** [comment]
Any transition from any state to "aborted" is almost always a VirtualBox issue. In this case it almost certainly is. Vagrant has a history of trying to work around these if we can find ways to do so, but otherwise we'll live this to Oracle.
