### ISSUE TITLE
Vagrant doesn't add bsdtar etc. to PATH when running on 64-bit MSYS

### ISSUE THREAD

**Issue by keremc** [mitchellh/vagrant#5871]
The following segment from `C:\HashiCorp\Vagrant\bin\vagrant` is supposed to add bsdtar to `PATH`:
```bash
case $OS in
        CYGWIN* | MINGW32*)
                # In Linux-like environments on Windows, we want to add the
                # Windows path to the PATH so that bsdtar and friends can
                # be found.
                export PATH="${EMBEDDED_DIR}/gnuwin32/bin:${PATH}"
                ;;
```
It, however, will not be executed on 64-bit MSYS and [Git for Windows](https://git-for-windows.github.io), since `$OS` is defined as the output of `$(uname -s 2>/dev/null)` and on these platforms `$(uname -s 2>/dev/null)` returns `MINGW64_NT-6.3`. As a result `vagrant box add` will fail as it needs bsdtar to extract Vagrant boxes.

**Comment by mitchellh** [comment]
Will be fixed in the next release
