### ISSUE TITLE
insert_public_key on OpenBSD lacks newline

### ISSUE THREAD

**Issue by double-p** [mitchellh/vagrant#5881]
The current code might leave in a situation like this in ~vagrant/.ssh/authorized_keys:
```
ssh-rsa existingkey commentssh-rsa newkey vagrant
```
instead of
```
ssh-rsa existingkey comment
ssh-rsa newkey vagrant
```
Since sshd considers empty lines as comments, a leading `\n` in the printf helps.

Vagrant-1.7.2 on OSX10.10 / OpenBSD5.8-current (guest OS is detected properly)
config.ssh.shell = "ksh -l"

Log:
```
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: printf 'ssh-rsa AAAAB....Bd02R vagrant' >> ~/.ssh/authorized_keys (sudo=false)
DEBUG ssh: Exit status: 0
```

**Comment by mitchellh** [comment]
Thanks! Added a `\n` at the end.

**Comment by double-p** [comment]
actually the newline must be in the beginning, as in before printing the key-string.
