### ISSUE TITLE
Embedded curl throws symbol lookup error

### ISSUE THREAD

**Issue by johnswanson** [mitchellh/vagrant#5883]
Running `env VAGRANT_LOG=debug vagrant up` yields:

    DEBUG subprocess: stderr: /opt/vagrant/bin/../embedded/bin/curl: symbol lookup error: /usr/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos

Running the command that vagrant is running (`/opt/vagrant/bin/../embedded/bin/curl -I -q --fail --location --max-redirs 10 --user-agent Vagrant/1.7.2 --continue-at - -H "Accept: application/json" https://atlas.hashicorp.com/hashicorp/precise64?access_token=...`) yields the same error (unsurprisingly).

Running the same command, with my system's curl instead of `/opt/vagrant/embedded/bin/curl`, yields a successful response.

Version info:

`curl --version`:

    curl 7.43.0 (x86_64-unknown-linux-gnu) libcurl/7.43.0 OpenSSL/1.0.2c zlib/1.2.8 libidn/1.30 libssh2/1.6.0
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
    Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

`/opt/vagrant/bin/../embedded/bin/curl --version`:

    curl 7.33.0 (x86_64-unknown-linux-gnu) libcurl/7.43.0 OpenSSL/1.0.1e zlib/1.2.8 libidn/1.30 libssh2/1.6.0
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
    Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SPNEGO SSL libz TLS-SRP

Not sure what to try here--let me know if I can provide any more information.

**Comment by johnswanson** [comment]
(I should note that this is not a blocker for me as I can just download the box manually--I'm just trying to figure out the root cause.)

**Comment by mitchellh** [comment]
Going to also say dup of #4543. These all seem related to library paths.
