### ISSUE TITLE
Vagrant ignores disable port forwarding for OSX guests

### ISSUE THREAD

**Issue by anthonygreen** [mitchellh/vagrant#5885]
Vagrant file

    Vagrant.configure(2) do |config|

      config.vm.define "yosemite" do |yosemite|
        yosemite.vm.box = "jhcook/osx-yosemite-10.10"
        yosemite.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
        yosemite.vm.network :forwarded_port, guest: 22, host: 2230, auto_correct: true
        fb.ssh.port = 2230
      end

    end

Virtualbox shows that port fowarding as

    | Name   | Protocol | Host IP   | Host Port | Guest IP | Guest Port |
    | ssh    | TCP      | 127.0.0.1 | 2222      |          | 22         |
    | tcp230 | TCP      |           | 2230      |          | 22         |

This causes clash with another VM instance trying to start on port 2222

**Comment by anthonygreen** [comment]
Is disabling port 2222 required for OSX?
Simplifying the configuration to 

    config.vm.define "yosemite" do |yosemite|
      yosemite.vm.box = "jhcook/osx-yosemite-10.10"
    end

creates a box with host port 2200 forwarding to guest 22

**Comment by mitchellh** [comment]
This looks like a box configuration problem. I've tried with my own box (hashicorp/precise64) and everything worked as-is. Please take a look at the box.
