### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication. On vmware

### ISSUE THREAD

**Issue by cpg1111** [mitchellh/vagrant#5886]
Hi there,  I am trying to vagrant up a few coreos boxes on vmware fusion.  I'd say roughly 1/5 times I vagrant up I successfully vagrant up one box or two but the others get to the point where they forward port 22 to another port.  When this happens I get prompt for the box's user's password, which there is none.  Then that is followed by: `Guest-specific operations were attempted on a machine that is not ready for guest communication.` Now each of these boxes have separate vagrantfiles and are in separate directories running on the same host machine.  Every once in awhile I'll also `vagrant ssh` into one of the other boxes.  These are all the same official coreos box and the only difference is in provisioning.

**Comment by mitchellh** [comment]
Can you please do the following for us to fix this:

1. Give a step by step reproduction case

2. Add a `--debug` output via gist

Thanks!

**Comment by cpg1111** [comment]
I've noticed this only happens when I try to `vagrant up` two boxes at the same time, should I just close this?

**Comment by cpg1111** [comment]
Here's the link to the Gist with the debug log and vagrantfiles that I am trying to up https://gist.github.com/cpg1111/b42c0200bf4a0205b113

**Comment by mitchellh** [comment]
This should be fixed in 1.8
