### ISSUE TITLE
vagrant package --vagrantfile <file> fails to include file in box top level.

### ISSUE THREAD

**Issue by carloslozano** [mitchellh/vagrant#5889]
#### Problem
When including a customized Vagrantfile in a box using the resulting package.box **does not** contain the Vagrantfile in the correct build order path.

#### Steps to Reproduce
For any working image, create a customized ```Vagrantfile.pkg``` file with the following content:

```
Vagrant.configure(2) do |config|
	config.vm.post_up_message = "It works!"
end
```
Execute:

1. ``` vagrant package --vagrantfile Vagrantfile.pkg ```
2. ``` vagrant box add --force --name test --provider parallels package.box```
3. ``` vagrant init test; vagrant up --provider parallels ```
  
#### Expected Result

Box is initialized and up'ed and the post_up_message ```"It works!"``` is displayed meaning the custom Vagrantfile has loaded. 

Expected package.box contents:

```
./Vagrantfile
./include/_Vagrantfile
./metadata.json
./vagrant_dev_default_box.pvm
./vagrant_dev_default_box.pvm/box-disk1.hdd
./vagrant_dev_default_box.pvm/config.pvs
./vagrant_dev_default_box.pvm/config.pvs.backup
./vagrant_dev_default_box.pvm/NVRAM.dat
./vagrant_dev_default_box.pvm/parallel.txt
./vagrant_dev_default_box.pvm/VmInfo.pvi
./vagrant_dev_default_box.pvm/box-disk1.hdd/box-disk1.hdd
./vagrant_dev_default_box.pvm/box-disk1.hdd/box-disk1.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds
./vagrant_dev_default_box.pvm/box-disk1.hdd/box-disk1.hdd.drh
./vagrant_dev_default_box.pvm/box-disk1.hdd/DiskDescriptor.xml
./vagrant_dev_default_box.pvm/box-disk1.hdd/DiskDescriptor.xml.Backup
```

#### Actual Result

Box is initialized and up'ed and the post_up_message ```"It works!"``` is **NOT** displayed meaning the custom Vagrantfile **HAS NOT** loaded. From the actual box contents we see the top-level ```./Vafrantfile``` is missing.

Actual package.box contents:

```
./include/_Vagrantfile
./metadata.json
./vagrant_dev_default_box.pvm
./vagrant_dev_default_box.pvm/box-disk1.hdd
./vagrant_dev_default_box.pvm/config.pvs
./vagrant_dev_default_box.pvm/config.pvs.backup
./vagrant_dev_default_box.pvm/NVRAM.dat
./vagrant_dev_default_box.pvm/parallel.txt
./vagrant_dev_default_box.pvm/VmInfo.pvi
./vagrant_dev_default_box.pvm/box-disk1.hdd/box-disk1.hdd
./vagrant_dev_default_box.pvm/box-disk1.hdd/box-disk1.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds
./vagrant_dev_default_box.pvm/box-disk1.hdd/box-disk1.hdd.drh
./vagrant_dev_default_box.pvm/box-disk1.hdd/DiskDescriptor.xml
./vagrant_dev_default_box.pvm/box-disk1.hdd/DiskDescriptor.xml.Backup
```

#### Environment

* OS X 10.10.x
* Vagrant 1.7.2
* Virtualbox and Parallels provider

#### Work-around

1. Unpackage box ```tar xvfz package.box <workdir>```.
2. Manually add customized file ```cp Vagrantfile <workdir>/```
3. Package box ```tar cvfz package.box <workdir>``` 

#### Misc

This is not a parallels issue. Parallels only used for example case. The same scenario can be reproduced with virtualbox provider.

**Comment by carloslozano** [comment]
Great news! Thanks!

**Comment by mitchellh** [comment]
This appears to be working, I ran it locally and it worked fine. The file is now copied directly, it is in the `_include` folder!
