### ISSUE TITLE
[help] run vagrant in virtualbox

### ISSUE THREAD

**Issue by marti1125** [mitchellh/vagrant#5891]
```
willy@willy-VirtualBox:~/aurora$ vagrant up
Bringing machine 'devcluster' up with 'virtualbox' provider...
==> devcluster: Importing base box 'ubuntu/trusty64'...
==> devcluster: Matching MAC address for NAT networking...
==> devcluster: Checking if box 'ubuntu/trusty64' is up to date...
==> devcluster: Setting the name of the VM: aurora_devcluster_1435989071183_81296
==> devcluster: Clearing any previously set forwarded ports...
==> devcluster: Clearing any previously set network interfaces...
==> devcluster: Preparing network interfaces based on configuration...
    devcluster: Adapter 1: nat
    devcluster: Adapter 2: bridged
==> devcluster: Forwarding ports...
    devcluster: 22 => 2222 (adapter 1)
==> devcluster: Running 'pre-boot' VM customizations...
==> devcluster: Booting VM...
==> devcluster: Waiting for machine to boot. This may take a few minutes...
    devcluster: SSH address: 127.0.0.1:2222
    devcluster: SSH username: vagrant
    devcluster: SSH auth method: private key
    devcluster: Warning: Connection timeout. Retrying...
    devcluster: Warning: Connection timeout. Retrying...
    devcluster: Warning: Connection timeout. Retrying...
    devcluster: Warning: Connection timeout. Retrying...
    devcluster: Warning: Connection timeout. Retrying...
    devcluster: Warning: Connection timeout. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

my vagrantfile

```ruby
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "aurora.local"
  config.vm.box = "ubuntu/trusty64"
  config.vm.boot_timeout = 100
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.ssh.insert_key = false

  config.vm.define "devcluster" do |dev|
    dev.vm.network :public_network
    dev.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    dev.vm.provision "shell", path: "examples/vagrant/provision-dev-cluster.sh"
  end
end
```

**Comment by sethvargo** [comment]
Hi @marti1125 

Can you please provider a more minimal Vagrantfile that does not modify the VM or change the boot_timeout, private key, etc, or provision the machine? Can you please also provide the output of `vagrant plugin list`? Thanks

**Comment by marti1125** [comment]
Sure @sethvargo, I am trying to run https://github.com/apache/aurora/blob/master/Vagrantfile inside virtualbox(ubuntu 14.04)
plugin list:
vagrant-share (1.1.3, system)

**Comment by StefanScherer** [comment]
@marti1125 Do I understand it right, you use vagrant in a VirtualBox VM to spin up the devcluster Vagrantfile?

AFAIK nested hypervisor is not possible with VirtualBox ( https://www.virtualbox.org/ticket/4032 ). VirtualBox is only able to spin up nested 32bit VM's if running in VirtualBox. Spinning up a 64bit VM stops with an error that no 64bit CPU could be found.

Nested hypervisor can be done eg. with VMware Fusion/Workstation on your host machine to test VirtualBox or VMware inside a clean VM. To enable nested hypervisor for VMware add `v.vmx["vhv.enable"] = "TRUE"` in the Vagrantfile to the VMware provider settings.

As a first next step you could try to add `vb.gui = true` to this Vagrantfile and see what's happening on the console window of the Vagrant box.

**Comment by marti1125** [comment]
Ok, thanks! I will try again with VMware Workstation
