### ISSUE TITLE
Encoding Issues Mega Issue

### ISSUE THREAD

**Issue by mitchellh** [mitchellh/vagrant#5896]
I'm creating this issue to just collect and keep track of all encoding issues. I'd rather have one big issue than a bunch of small ones. I'll link to them from here.
- [x] #5595
- [x] #5475 
- [x] #5605
- [x] #5832 
- [x] #5855
- [x] #6056
- [x] #6065
- [x] #6130
- [x] #6571 
- [x] #7106

**Comment by jstortz** [comment]
Team, does the new VMWare Fusion 8 release and updated vagrant vmware plugin "fix" or "help" this issue at all? I wondered if anyone that had experienced any encoding issues before had tried the new versions and could offer any update?

**Comment by sethvargo** [comment]
Hi @jstortz 

Good question. No - the encoding issues exist in Ruby (which is the language Vagrant is written in) and are independent of the VMware plugin.

**Comment by jstortz** [comment]
Roger that.  Thanks for the clarification. With that in mind is there a specific version of ruby that should be installed (an older one perhaps?) that works with Vagrant 1.7.3+?

I had 1.7.2, which worked great, then upgraded to 1.7.4 and had the encoding issue, then back to 1.7.2 which worked again.  This leads me to believe it isn't using the version I have installed, I could go look to confirm but I suspect it may use its own bundled ruby?

I fear I'm oversimplifying but, if it ships with its own ruby then cut a release with whatever version is baked into 1.7.2...it just wouldn't be that easy though or you would have done that. :)

**Comment by chrisroberts** [comment]
Closing as all referenced issues are closed
