### ISSUE TITLE
Support for VirtualBox multiattach storage

### ISSUE THREAD

**Issue by fw42** [mitchellh/vagrant#5898]
Something like this would be nice to have in vagrant: http://www.electricmonk.nl/log/2011/09/24/multiple-virtualbox-vms-using-one-base-image-copy-on-write/

We often run vagrant in a multi-machine setup with tens of VMs (for automated network test labs for example) and it's really frustrating that this requires tens of gigabytes of disk space.

VirtualBox has an option to share disk base images across VMs and use copy-on-write for the actual changes. I tried this out and it actually works with vagrant (just involves some tedious manual work). It would be awesome if this would be configurable via Vagrantfile.

Not sure how involved of a code change that would be. Any pointers would be appreciated.

cc @sirupsen

**Comment by mitchellh** [comment]
This is #4484

**Comment by fw42** [comment]
awesome
