### ISSUE TITLE
Support width and height for RDP -- support /w: and /h: parameter

### ISSUE THREAD

**Issue by mpasternak** [mitchellh/vagrant#5899]
Hi,

currently RDP opens full-screen. Or, I can type "vagrant rdp -- /w:1440 /h:900" 

Some plugins support something like this:

```
config.rdp.width  = 1440 # default: 1024
config.rdp.height = 900  # default: 768
```

I'd love to see support for resolution, defined in Vagrantfile.

**Comment by mitchellh** [comment]
Feel free to submit a PR for this, it should be quite simple. In the short term, because you can specify this on the CLI, we're not going to prioritize this. Sorry.

**Comment by mpasternak** [comment]
No need to apologize. Even if I handle smaller projects, this is my most common reply too. If you say it should be easy implementation,  I'm gonna try to submit a patch, thanks!
