### ISSUE TITLE
Default interface to bridge to setting (feature request)

### ISSUE THREAD

**Issue by sej7278** [mitchellh/vagrant#5900]
See also #655 

Basically I need a way to define the default network interface to use. Preferably in the ~/.vagrant dotfile or an environment variable, at worst some sort of automatic detection or Vagrantfile setting.

Scenario is I copy my vagrant setup from my desktop to my laptop. My laptop usually uses wlan0, but also has eth0. So on the laptop I get prompted for which interface to use each time. As eth0 doesn't have a link up or IP address, that seems a bit silly.

The alternative is using the ```bridge:``` setting in Vagrantfile, then if the interface doesn't exist then the next one should be tried - e.g. if I set it to wlan0, then move to the desktop which doesn't have wlan0, then the remaining eth0 should be used. Maybe the we could add a priority list like:

```
config.vm.network "public_network", ip: "192.168.1.44", bridge: "wlan0, eth0"
```

The hacky workaround is to define that line once for each interface, with different IP's, but then you end up with three interfaces in the VM and probably an error if the interface doesn't exist.

Realistically it should only prompt for which interface to use if you have two interfaces that are both up with an IP, otherwise it should use some logic - be that autodetection or a setting somewhere.

**Comment by mitchellh** [comment]
The way we recommend doing this is actually using some Ruby, which isn't obvious for sure but does work. If you make a Vagrantfile in `~/Vagrantfile`, it will be loaded for every project. I recommend in this file to actually _not_ set any Vagrant settings, you just Ruby variables:

```
$my_default_bridge = "wlan0"
```

Then in your real Vagrantfile, you can do this:

```
config.vm.network "public_network", ip: "192.168.1.44", bridge: $my_default_bridge
```

As this isn't a super common problem we've heard of, we recommend this. Please feel free to ask any questions!

**Comment by sej7278** [comment]
i really can't believe almost everyone isn't having this problem - doesn't everyone switch between laptops and desktops - or at least machines with different network interfaces?

do I have to use ~/Vagrantfile, can't i use ~/.vagrant or $VAGRANT_HOME/Vagrantfile (as I don't run vagrant from my home directory)?

**Comment by sej7278** [comment]
this seems to work.

in $VAGRANT_HOME/Vagrantfile:

```ruby
require 'socket'
hostname = Socket.gethostname

if hostname == "laptop"
    $default_bridge = "wlan0"
else
    $default_bridge = "eth0"
end
```

in each vm's Vagrantfile:

```
    config.vm.network "public_network", ip: "192.168.1.44", bridge: $default_bridge
```
