### ISSUE TITLE
Missing plugin (and provisioner) has terrible messaging

### ISSUE THREAD

**Issue by jwhitley** [mitchellh/vagrant#5902]
**Repro steps**

1.  Create a simple Vagrantfile that uses the `vagrant-host-shell` plugin, which implements the `:host_shell` provisioner.  Add a line to the Vagrantfile using it, ala:

    ```
    config.vm.provision :host_shell, inline: "echo 'Found backup file; loading into development database.'"
    ```
2.  *Important:* do not install the plugin yet, or uninstall it if it's already present.
3.  `vagrant up`

**Actual results**

```
>> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The '' provisioner could not be found.
```

There are two problems here.  First, the dependency on `vagrant-host-shell` is implicit.  A developer new to this project now has to hunt around to figure out what's missing.  Perhaps there's a pattern for expressing plugin dependencies in Vagrantfile, but that wasn't clear from the docs.  (And I note that an old declaration pattern was deprecated.)  For sanity, I'll now have to code something ad-hoc to provide a clear, actionable error.

Second, the messaging about the missing provider has an outright bug, in that it's not reporting that `:host_shell` was the provisioner.  (E.g. `The '' provisioner could not be found`)

**Expected results**

1.  It should be possible to declare plugin dependencies so that missing plugins can be clearly reported, enabling developers to immediately fix the problem and get back to work.
2.  The missing provisioner should be reported by the identifier used in the file, `:host_shell`.

**Related issues**

#1700, which is closed but the outsourced solution (Vundler) is long-abandoned, and never worked with Vagrant > 1.3.

**Comment by mitchellh** [comment]
Fixed

**Comment by mitchellh** [comment]
Sorry, by fixed I will clarify that I fixed the error messaging for a missing provisioner. 

Declaring plugin dependencies is tracked in another issue that is still open but can't find, but something like "local plugins".

**Comment by jwhitley** [comment]
Awesome, thanks for the quick patch.

@mitchellh the best I can find that's open is #4347, is that the one you were thinking of?

**Comment by mitchellh** [comment]
That sounds right!
