### ISSUE TITLE
Warn that synced folders permissions do not affect docker provider

### ISSUE THREAD

**Issue by rdoursenaud** [mitchellh/vagrant#5906]
Used with docker, synced folders don't have an owner nor a group set!

This makes them useless for any serious work.

vm.synced_folder owner and group directives makes no difference and seems to be ignored.

Vagrant version: 1.7.2
Docker version: 1.7.0
(Host: Arch Linux with btrfs)

Let me know if you need any more information.

**Comment by mitchellh** [comment]
For Docker synced folders, we just use the volume mounting feature of Docker, which doesn't allow us to set an owner/group, so this option is ignored. 

This may not be what you're asking. If I'm wrong, please attach a debug log and Vagrantfile of what is going wrong and I'll look into it further. Thanks!

**Comment by rdoursenaud** [comment]
Ok, so this is a docker issue. Thanks.
Maybe vagrant could issue a warning if one tries to set owner/group and maybe mount_options on a folder synced with a docker container? This would have saved me a few hours of frustration.

**Comment by sethvargo** [comment]
I think that's a good idea (and pretty simple solution). I'm going to re-open and rename this. I'm not sure this will make the next release because we are trying to focus the most on bugs. Thank you for reporting it!

**Comment by sebastianreloaded** [comment]
i think it is still not clear.
does this mean the docker provider only doesn't support owner and group but it supports  mount_options like uid, gid, dmode, fmode etc. ?

**Comment by riebling** [comment]
Agreed still not clear; does this mean a Docker guest cannot write to /vagrant AT ALL? This is what I've been experiencing, even when the folder permissions support writing, making this a show-stopper. 
```
vagrant@cec288eb7c7a:~$ touch /vagrant/biz
touch: cannot touch ‘/vagrant/biz’: Permission denied
vagrant@cec288eb7c7a:~$ ls -ld /vagrant
drwxrwxr-x 33 11432 users 4096 May  4 16:23 /vagrant
```
