### ISSUE TITLE
Network-configuration bug(?) when provisioning multiple Centos7-guests?

### ISSUE THREAD

**Issue by shejtanvrbaski** [mitchellh/vagrant#5907]
Hello,
I'm experiencing a very odd problem when trying to provision multiple Centos 7 machines with Vagrant. This happens both with bridged/public and host-only networking when using static IP-assignment. Even though the IP-addresses are being provisioned properly (which I can tell when having debugging activated + I can confirm the proper settings are present inside of network-scripts interface cfg files on the guest machines) - they won't be used by guests at the initial boot after provisioning / vagrant up. The secondary host-only/public interface on at least one of the provisioned guests will either be missing address or be using a dynamic/DHCP from the network instead.  The reboot after provisioning fixes the problem - then the guests will use the proper net-settings. The problems described (once again - only Centos7 issue) will most frequently occur if I add multiple machines in seperate config blocks, something like this (it happened few times even with a single guest-definition):

```ruby
Vagrant.configure(2) do |config|
                config.vm.define "client1" do |client1|
                client1.vm.box    = "centos7"
                client1.vm.network "public_network", ip: "192.168.1.31", bridge: "br0"
                client1.vm.hostname = "client1"
                client1.vm.provider "virtualbox" do |vb|
                        vb.customize ["modifyvm", :id, "--cpus", 1]
                        vb.customize ["modifyvm", :id, "--memory", 512]
                        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                end
        end
                config.vm.define "client2" do |client2|
                client2.vm.box    = "centos7"
                client2.vm.network "public_network", ip: "192.168.1.32", bridge: "br0"
                client2.vm.hostname = "client2"
                client2.vm.provider "virtualbox" do |vb|
                        vb.customize ["modifyvm", :id, "--cpus", 1]
                        vb.customize ["modifyvm", :id, "--memory", 512]
                        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
                end
        end
end
```

What is the deal?  This is only noticed when I'm using Centos7 boxes - I tried several of them, starting with the one I made on my own, and several others from Atlas-site - all had the same problem. 

Ubuntu 12.xx/13.xx/14.xx & Centos 6.x that I tried as well worked flawlessly, no matter if I provision a small cluster or a single guest.

I'm starting to believe this might have to do with the default (different) network interface naming scheme that Centos7 is using. Yet, the bug doesn't occur on all Centos7 guests being provisioned at the same time. 

Thanks in advance for any feedback!

**Comment by jsteel44** [comment]
Remove NetworkManager from your CentOS 7 boxes

**Comment by mainframe** [comment]
Im experiencing this too - but with CentOS 7 Atomic Host - which is based on ostree. For test I also spawned 3 centos/7 boxes and they seem to be ok. Might be different network configuration thou.
