### ISSUE TITLE
Vagrant doesn't working with Virtual Box v5

### ISSUE THREAD

**Issue by Remm** [mitchellh/vagrant#5908]
Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3

**Comment by sethvargo** [comment]
Hi @Remm 

Thank you for reporting an issue. This is already fixed on the master branch and will be available with the next release of Vagrant. Thanks :smile:

**Comment by sethvargo** [comment]
See also: #5572
