### ISSUE TITLE
Error while provisitioning and setting up new box. No such file directory.

### ISSUE THREAD

**Issue by coffeeneed** [mitchellh/vagrant#5917]
Hi. I'm totally new to Vagrant. So new that I don't have a clue whether or not I have any use for it yet, but probably will when getting Apache up and a webserver up and running.

I get a server up and running just fine with a default init and a vagrant up, but when I want to do like this guy,  I get some errors: http://www.websightdesigns.com/posts/view/how-to-configure-an-ubuntu-web-server-vm-with-vagrant

Errors from console:
    ==> default: ldconfig deferred processing now taking place
    ==> default: --2015-07-09 16:23:16--  http://www.phpmyadmin.net/
    ==> default: Resolving www.phpmyadmin.net (www.phpmyadmin.net)...
    ==> default: 37.235.106.47
    ==> default: Connecting to www.phpmyadmin.net (www.phpmyadmin.net)|37.235.106.47
    |:80...
    ==> default: connected.
    ==> default: HTTP request sent, awaiting response...
    ==> default: 200 OK
    ==> default: Length:
    ==> default: unspecified
    ==> default:  [text/html]
    ==> default: Saving to: `/vagrant/phpmyadmin/index.html'
    ==> default:
    ==> default:      0K
    ==> default:
    ==> default: .
    ==> default: .
    ==> default: .
    ==> default: .
    ==> default: .
    ==> default: .
    ==> default: .
    ==> default: .
    ==> default: .
    ==> default: .
    ==> default:
    ==> default: .
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:
    ==> default:   104M
    ==> default: =0s
    ==> default:
    ==> default: 2015-07-09 16:23:16 (104 MB/s) - `/vagrant/phpmyadmin/index.html' s
    aved [11715]
    ==> default: awk:
    ==> default: cannot open /vvagrant/phpmyadmin/index.html
    ==> default:  (No such file or directory)
    ==> default: wget: missing URL
    ==> default: Usage: wget [OPTION]... [URL]...
    ==> default: Try `wget --help' for more options.
    ==> default: tar (child):
    ==> default: /vagrant/phpmyadmin/phpMyAdmin.tar.bz2: Cannot open
    ==> default: : No such file or directory
    ==> default: tar (child):
    ==> default: Error is not recoverable: exiting now
    ==> default: tar:
    ==> default: Child returned status 2
    ==> default: tar:
    ==> default: Error is not recoverable: exiting now
    ==> default: mv:
    ==> default: cannot stat `/vagrant/myadm.localhost/config.sample.inc.php'
    ==> default: : No such file or directory
    ==> default: sed: can't read /vagrant/myadm.localhost/config.inc.php: No such fi
    le or directory
    ==> default: /tmp/vagrant-shell: line 92: /vagrant/myadm.localhost/examples/crea
    te_tables.sql: No such file or directory
    ==> default: cat:
    ==> default: /vagrant/phpmyadmin.conf
    ==> default: : No such file or directory
    ==> default: Cloning into '/vagrant/mywebsite.localhost'...
    ==> default: find:
    ==> default: `/etc/apache2/sites-available/mywebsite.localhost'
    ==> default: : No such file or directory
    ==> default: ERROR
    ==> default:  1396 (HY000)
    ==> default:  at line 1
    ==> default: : Operation CREATE USER failed for 'mysqluser'@'localhost'

----------------------------
I'm on Windows 8.1. The Vagrantfile look like this:
    # -*- mode: ruby -*-
    # vi: set ft=ruby :
    VAGRANTFILE_API_VERSION = "2"
    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "hashicorp/precise64"
    config.vm.provision :shell, :path => "bootstrap.sh"
    config.vm.network :private_network, ip: "192.168.56.101"
    config.vm.synced_folder ".", "/vagrant", id: "vagrant-root",
    owner: "vagrant",
    group: "vagrant"
    end

All the files are in the same folder as the Vagrant files:
- adddb.sh
- addwebsite.sh
- bootstrap.sh
- hostname.localhost
- importdb.sh

I don't know if I'm on the correct path or doing this right, so I hope there's something obvious for a trained eye. Any ideas on how to fix this?

Any other "boilerplate" starts I can take use of, instead this one is old and bugged? My main goal is to set up Apache, PHP, hoste some site locally and code web pages :-)

Thanks.

**Comment by mitchellh** [comment]
Based on your output, this is not a Vagrant bug, but a configuration/provisioning issue. Please ask the mailing list for usage help. The issue tracker is only for Vagrant bugs.
