### ISSUE TITLE
Add support for VirtualBox 5.x

### ISSUE THREAD

**Issue by bkonetzny** [mitchellh/vagrant#5918]
Virtualbox 5.0 was released: https://www.oracle.com/corporate/pressrelease/oracle-vm-virtualbox-5-070915.html

While expecting this to be backwards compatible, vagrant won't let me run a box with it:
```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

**Comment by yveslaroche** [comment]
VirtualBox 5.0 support was added here https://github.com/mitchellh/vagrant/pull/5647 and will be part of the next Vagrant release 1.7.3. 

https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#173-unreleased

**Comment by chantalcoolsma** [comment]
Any idea when 1.7.3 will be released?

**Comment by yveslaroche** [comment]
@chantalcoolsma https://github.com/mitchellh/vagrant/pull/5647#issuecomment-120076296

**Comment by mitchellh** [comment]
Please search issues. We'll probably release today.
