### ISSUE TITLE
Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists

### ISSUE THREAD

**Issue by dbl001** [mitchellh/vagrant#5920]
Hi,

I got this error running vagrant reload on the Numenta 'nupic' virtual box.
vagrant ssh didn't work either.

A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--controller", "IntelAHCI"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "12ca0fa0-9b7c-4808-a176-42214f5f00b8", "--name", "SATA Controller", "--add", "sata", "--controller", "IntelAHCI"]

Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1044 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.

**Comment by dbl001** [comment]
Here's the code from the 'nupic/coreos-vagrant' Vagrantfile:

     config.vm.provider :virtualbox do |vb|
        vb.gui = $vb_gui
        vb.memory = $vb_memory
        vb.cpus = $vb_cpus
        file_to_disk = "docker.vdi"
        vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--controller", "IntelAHCI"]
        unless File.exist?(file_to_disk)
          vb.customize ["createhd", "--filename", file_to_disk, "--size", 100 * 1024, "--format", "VDI"]
        end
        vb.customize ["storageattach", :id, "--storagectl", "SATA Controller", "--port", 0, "--device", 0, "--type", "hdd", "--medium", file_to_disk]
      end

**Comment by sethvargo** [comment]
Hi @dbl001 

The error you are getting is coming from VirtualBox, not Vagrant. This is most certainly a bug in VirtualBox or something with your local setup. From the output, it appears that the SATA controller is already in use. Perhaps you have another VM running that is using that device, but unfortunately this is not a Vagrant issue. If the issue persists, please open an issue on the VirtualBox bug tracker. Thanks! :smile:
