### ISSUE TITLE
Error bringing "up" vagrant box for VirtualBox on Windows 7

### ISSUE THREAD

**Issue by IT-guy** [mitchellh/vagrant#5921]
Hi, I'm using Vagrant 1.5.4 running under Windows 7. I got the error below when trying to bring up a vagrant box I downloaded for VirtualBox 4.3.16:

    D:\box>vagrant up
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Clearing any previously set network interfaces...
    There was an error while executing `VBoxManage`, a CLI used by Vagrant
    for controlling VirtualBox. The command and stderr is shown below.
    
    Command: ["hostonlyif", "create"]
    
    Stderr: 0%...
    Progress state: E_FAIL
    VBoxManage.EXE: error: Failed to create the host-only adapter
    VBoxManage.EXE: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
    VBoxManage.EXE: error: Context: "int __cdecl handleCreate(struct HandlerArg *,int,int *)" at line 66 of file VBoxManageHostonly.cpp

I am new with Vagrant and I have absolutely no idea what the problem can be. Please, any ideas on how I can go about to solve this?

PS: I tried upgrading to the most recent 1.7.2 but still got exactly the same error.

**Comment by sethvargo** [comment]
Hi @IT-guy 

This error is coming from VirtualBox. Please try re-installing VirtualBox and upgrading to the latest version. Also, I know it sounds bizarre, but please restart your computer. If the issue persists, please open an issue with Oracle.
