### ISSUE TITLE
Virtualbox 5.x support

### ISSUE THREAD

**Issue by theodorosploumis** [mitchellh/vagrant#5925]
@mitchellh 
Virtualbox has a major 5.x version now (10 July 2015). Would be nice to **know when is vagrant going to support the new 5.x version** so people can upgrade without issues. I am not asking to upgrade it just a bit information.

Thanks.

**Comment by sethvargo** [comment]
Hi @theodorosploumis 

Please search previous issues or the mailing list. We have already merged VirtualBox 5 support to master. Thanks! :smile:
