### ISSUE TITLE
VirtualBox 5.0 is available

### ISSUE THREAD

**Issue by dinamic** [mitchellh/vagrant#5926]
Yesterday Oracle announced VirtualBox 5.0.
https://blogs.oracle.com/virtualization/entry/oracle_vm_virtualbox_5_07

The documentation for Vagrant goes like:

> The VirtualBox provider is compatible with VirtualBox versions 4.0.x, 4.1.x, 4.2.x, and 4.3.x.
> Any other version is unsupported and the provider will display an error message.

Can you give some estimation on when it's going to be supported?
Thanks.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/5925

Please search previous issues and mailing list posts before opening issues in the future. Thanks! :smile:

**Comment by dinamic** [comment]
Would you fix the documentation, please?

**Comment by sethvargo** [comment]
00f1e46

**Comment by dinamic** [comment]
Thanks. :+1: 

Awaiting 1.7.3 for OS X to land for download. :)
