### ISSUE TITLE
TTY error on Cygwin in 1.7.3

### ISSUE THREAD

**Issue by epipho** [mitchellh/vagrant#5930]
After upgrading from 1.7.2 to 1.7.3 Vagrant throws the following error in cygwin when it goes to ask for credentials to the SMB shared folders.  Interestingly Vagrant::Util::Platform.cygwin? returns false inside ui.rb during the call to ask(), causing it to throw the error.

```
Vagrant is attempting to interface with the UI in a way that requires
a TTY. Most actions in Vagrant that require a TTY have configuration
switches to disable this requirement. Please do that or run Vagrant
with TTY.
```

VagrantFile being used is:

```
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "..", "/test", type: "smb"
end
```

uname -a 
```
CYGWIN_NT-6.1-WOW fish-win7 2.0.2(0.287/5/3) 2015-05-08 17:03 i686 Cygwin
```

**Comment by marcharding** [comment]
Same here.

ENV["VAGRANT_DETECTED_OS"] is empty for me on version 1.7.3, so the detection in Vagrant::Util::Platform is bound to fail.
 
On version 1.7.2 ENV["VAGRANT_DETECTED_OS"] contained "CYGWIN_NT-6.3".

I can't see any change from 1.7.2 to 1.7.3 which would cause this, maybe something with the installers ( https://github.com/mitchellh/vagrant-installers/) was changed?

**Comment by chris-pook** [comment]
I have this same issue on Vagrant 1.7.4, no prompt for SMB credentials.

VagrantFile being used is:
```
Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/var/www", type:"smb"
end
```
uname -a
```
CYGWIN_NT-6.3 chrispookredbox 2.0.4(0.287/5/3) 2015-06-09 12:22 x86_64 Cygwin
```

**Comment by vinceskahan** [comment]
Same here - 1.7.4 vagrant on cygwin.  Workaround seems to be 'vagrant halt' then 'vagrant destroy -f'

**Comment by Veritas1000** [comment]
A possible workaround if you only ever run vagrant from cygwin within windows.

I added an environment variable to replace the missing 'VAGRANT_DETECTED_OS', and set it to 'CYGWIN_NT-6.3'. That removed the TTY bug for me.

Of course, for a shorter-lived env variable (so you can still run vagrant from the normal windows command line) you can always just set it in cygwin before running vagrant:
```
export VAGRANT_DETECTED_OS=CYGWIN_NT-6.3
```
You'll need to set it in every cygwin terminal, though.

**Comment by mitchellh** [comment]
Fixed

**Comment by vinceskahan** [comment]
would it be too much to ask 'where' it is fixed and when we'll see that release ?
(it isn't fixed until the users can run the fixed product in my opinion).

thanks...

**Comment by mitchellh** [comment]
Hey @vinceskahan it is fixed in "util/platform.rb" sorry for being vague but check out the file history there. It will be in 1.8 coming out latre this month.
