### ISSUE TITLE
Error while pulling docker image from repository even when it exists in local repo

### ISSUE THREAD

**Issue by aacebedo** [mitchellh/vagrant#5932]
I am using the docker provider with vagrant.
My workflow is to commit docker images only on my local registry and build containers from these images. 
In Vagrant 1.7.2 this workflow worked flawlessly as vagrant did not try to pull the image from docker repository. 
In Vagrant 1.7.3 I am unable to do this anymore as it fails because it does not find my container name online (on purpose as it is located in the local repo).
Is it possible to tell vagrant not to pull the image if it already exists in the local registry ?

**Comment by ephemeralsnow** [comment]
+1

**Comment by phiroict** [comment]
Can confirm, in 1.7.3 vagrant docker does not look in local repo when using an image.

**Comment by jyokyoku** [comment]
I have same issue on 1.7.3.

**Comment by mitchellh** [comment]
Fixed
