### ISSUE TITLE
Unable to set hostname in 12.04

### ISSUE THREAD

**Issue by aidanhs** [mitchellh/vagrant#5934]
Broken by #5753 I assume.

Probably should be `return super unless vivid?`.

**Comment by aidanhs** [comment]
Error:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostnamectl set-hostname 'reddit'

Stdout from the command:



Stderr from the command:

stdin: is not a tty
bash: line 3: hostnamectl: command not found
```

**Comment by dhoppe** [comment]
I am facing the same issue and using `return super unless vivid?`solved the problem.

**Comment by stucki** [comment]
Happens in Ubuntu 14.04 as well, but your patch covers it too.
Still, can you please update the bug title to match that version as well? Thanks!

**Comment by aidanhs** [comment]
Updated.

**Comment by aidanhs** [comment]
Actually, not sure why it would happen on 14.04. According to #5947, "hostnamectl was introduced to ubuntu after 13.04". Re-tweaked issue title.

**Comment by stucki** [comment]
The program belongs to ```systemd-services``` which was not required until Ubuntu switched to systemd by default in 15.04. So in 14.04 the package might be missing on some systems. In my case, I'm using vagrant-lxc with the default image by @fgrehm ```fgrehm/trusty64```, which does not contain the package.

Anyway, thanks for updating the bug description!
