### ISSUE TITLE
enable port forwarding options in ssh object

### ISSUE THREAD

**Issue by sebastiang** [mitchellh/vagrant#5941]
Can we have an option on `ssh` that adds a `-L` port forwarding option to the `vagrant ssh` command? When using the AWS provider to run a development box it is convenient to construct my own `ssh` command that adds the port forwarding options so that I can continue to, for instance, browse local ports as if the VM were local. In an ideal world there would be a line like

    override.ssh.port_forwarding = true

That would take the settings accumulated in `config.vm.network` and run the forwarding while `ssh` was running. Then between `vagrant ssh` and `vagrant rsync-auto` the illusion of a local VM is nearly complete.

**Comment by sethvargo** [comment]
I suspect the option will be `forward_ports` to align with our other `forward_*` options in the SSH config, but this sounds reasonable to me.

**Comment by mitchellh** [comment]
This hasn't been a heavily requested feature, and for things like this we usually ask that you simply use `vagrant ssh-config` and run `ssh` directly. I know its not ideal, but we'd rather not implement a feature that hasn't been heavily requested at this time. Sorry.

**Comment by sebastiang** [comment]
Understood. That's what we've done.
