### ISSUE TITLE
OS X NFS mount with no password

### ISSUE THREAD

**Issue by ahmedelgabri** [mitchellh/vagrant#5942]
I have tried both solutions from the [docs](http://docs.vagrantup.com/v2/synced-folders/nfs.html) and still not able to make `vagrant up` mount without asking for password.

Here is a screenshot form `/etc/sudoers` file

![cjmgsr9wiaeonzf](https://cloud.githubusercontent.com/assets/63876/8639280/15da3e88-28d5-11e5-9995-c3aae6f66149.png)

OS X 10.10.4
Vagrant 1.7.2 (installed through brew cask)
Any idea what might be wrong?

**Comment by sethvargo** [comment]
Hi @ahmedelgabri 

I believe that feature was added in 1.7.3, but I can't seem to find it in the CHANGELOG. Can you please share your complete Vagrantfile and I will try to reproduce locally. Thanks!

**Comment by ahmedelgabri** [comment]
@sethvargo updated to 1.7.3 and it worked, thanks! I think the docs should mention this though cause it's a bit confusing.

**Comment by sethvargo** [comment]
Hi @ahmedelgabri ^ reopened and retagged as docs for 1.7.4. Thanks for the feedback!

**Comment by ahmedelgabri** [comment]
:+1:

**Comment by mitchellh** [comment]
Done
