### ISSUE TITLE
Unable to Use VMware Fusion Technical Preview 2015

### ISSUE THREAD

**Issue by brennovich** [mitchellh/vagrant#5946]
Even though setting both `VAGRANT_VMWARE_FUSION_APP` and `VAGRANT_VMWARE_FUSION_EXP`, `vagrant up` still throws:

```
This provider only works with VMware 5.x or 6.x. You have
the VMware Fusion Tech Preview. You can force Vagrant to attempt
to use the tech preview by setting `VAGRANT_VMWARE_FUSION_EXP`
to "1". Note that there may be multiple bugs in the interaction
with an unreleased version of Fusion and by using this you forfeit
any support.
```

I'm using `OS X 10.11` developer preview and latest VMware Tech Preview 2015

**Comment by topikito** [comment]
I have the same issue here

**Comment by brennovich** [comment]
@topikito yep, it's a VMWare issue, version `7.1.2` throwns kernel panic under El Capitan. Technical preview solves that ;)

**Comment by topikito** [comment]
Thanks for confirming @brennovich - Any update on how to communicate vagrant + vm plugin + vmware tech preview ?

**Comment by brennovich** [comment]
Nope :/

I stopped trying to look how to solve it, we have no access to vm-plugin code, at least I tried this on my personal machine :)

The bummer part of it is that vagrant-vmware-plugin is kinda expensive and I don't know support channel other than open source vagrant.

**Comment by drewwells** [comment]
@brennovich Yeah there is no support for the vmware plugin, you have to purchase that separately. http://www.vagrantup.com/support.html

**Comment by sethvargo** [comment]
> If you purchased the VMware Fusion provider, you're eligible for limited basic support via email by contacting support@hashicorp.com. Response times are typically within 48 hours, but can be up to a week.

Please email us! Thanks!

**Comment by mikhail-guru** [comment]
+1 for this issue.

**Comment by sethvargo** [comment]
Hi all,

I have identified this problem in the Vagrant VMware Fusion and Vagrant VMware Workstation plugins and hope to get a fix out soon.

**Comment by brennovich** [comment]
Thanks @mikhail-guru for the workaround, it worked like a charm :)

Also, thanks @sethvargo for the support ;)

**Comment by sethvargo** [comment]
Hi all,

I just wanted to follow up and say that the plugin v3.2.10 is now out and re-enables this environment variable. You can install this version by running `vagrant plugin install vagrant-vmware-fusion`.

If you continue to have issues, please open a _new_ issue and include the Vagrantfile and the output of the command in debug mode. Thanks!

**Comment by mikhail-guru** [comment]
I'm sorry I have no time to create new bugreport, so:

The binary to start VMware services could not be found. This
is required in order to modify networking files. This can be caused
by a broken Fusion installation or an invalid Fusion version.
Please report a bug.

**Comment by topikito** [comment]
@mikhail-guru Opened ticket as I'm also experiencing this. The issue this ticket was meant for has successfully been fixed: thanks @sethvargo

**Comment by BrettTrotter** [comment]
dice-blt.local ➜  cjvagrant git:(master) ls -ld /Applications/VMware\ Fusion\ Tech\ Preview.app
drwxr-xr-x@ 3 root  wheel  102 Jul  9 16:03 /Applications/VMware Fusion Tech Preview.app
dice-blt.local ➜  cjvagrant git:(master) vagrant plugin install vagrant-vmware-fusion
Installing the 'vagrant-vmware-fusion' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vmware-fusion (3.2.11)'!
dice-blt.local ➜  cjvagrant git:(master) VAGRANT_VMWARE_FUSION_EXP=1 VAGRANT_VMWARE_FUSION_APP="/Applications/VMware Fusion Tech Preview.app"  vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
The binary to start VMware services could not be found. This
is required in order to modify networking files. This can be caused
by a broken Fusion installation or an invalid Fusion version.
Please report a bug.


What am I missing?

**Comment by topikito** [comment]
@BrettTrotter Check the ticket I opened ^^^^^

https://github.com/mitchellh/vagrant/issues/6043

**Comment by BrettTrotter** [comment]
It had sounded like the updated plugin might do it, so I thought I'd check. The Hex Edit did work for now though- ugly though it may be!

**Comment by mikhail-guru** [comment]
https://www.reddit.com/r/vagrant/comments/3ie38b/hashicorp_released_vmware_plugin_for_vagrant/
