### ISSUE TITLE
v1.7.3: Setting hostname via hostnamectl without a degradation fails Ubuntu boxes version < 13.04 during the setting hostname step.

### ISSUE THREAD

**Issue by southp** [mitchellh/vagrant#5947]
According to this page: http://www.howopensource.com/2015/02/ubuntu-change-hostname/, hostnamectl was introduced to ubuntu after 13.04. Thus, using `hostnamectl` without a degradation way of setting host name causes `vagrant up` to fail during hostname setup.

My own experience of this failure was from trying to setup a `hashicorp/precise64`, and include the following line in the `Vagrantfile`:
```
config.vm.hostname = "test.local"
```

**Comment by phyber** [comment]
We're also experiencing issues with `hostnamectl` not existing on Precise (Ubuntu 12.04) while doing `vagrant up`.

**Comment by tersmitten** [comment]
We're also experiencing this issue, thanks for fixing it @aidanhs

**Comment by sethvargo** [comment]
Hi all,

I am going to close this as it has been fixed on master. I tagged it for 1.7.4 so we can track the regression on the tag release. Thanks!

**Comment by statik** [comment]
@phyber how did you modify your local install to work around the issue?

**Comment by phyber** [comment]
@statik I made the same change that was in the PR I referenced. Small change to `plugins/guests/ubuntu/cap/change_host_name.rb`
