### ISSUE TITLE
Default /vagrant shared folder fails on Virtualbox

### ISSUE THREAD

**Issue by orf** [mitchellh/vagrant#5952]
I've just upgraded to Virtualbox 5.0 and when I run `vagrant up` the following error is produced:

```shell
==> default: Mounting shared folders...
    default: /vagrant => C:/xxxx/
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:

Stderr from the command:

stdin: is not a tty
chown: changing ownership of â€˜/vagrantâ€™: Not a directory
````

If I SSH into the box and run `ls /vagrant` the following error is produced:

```shell
vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant/
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls
ls: cannot open directory .: Operation not permitted
```

This smells like an issue with Virtualbox, any hints as to how to resolve it?

Edit: I'm on Windows 7, running the latest vagrant (1.7.3).

**Comment by okinaka** [comment]
refs #5933

**Comment by orf** [comment]
Ahh sorry, I didn't see the previous discussion. I'll close this and comment there.
