### ISSUE TITLE
NFS cleanup action requires sudo for cp

### ISSUE THREAD

**Issue by kkopachev** [mitchellh/vagrant#5957]
`cp '#{tmp}/exports' /etc/exports` requires sudo:
> cp: cannot create regular file '/etc/exports': Permission denied

see #5954

Wonder if -ibak option can be replaced with -i (no suffix)

        -i[SUFFIX], --in-place[=SUFFIX]
           edit files in place (makes backup if SUFFIX supplied)

So this would solve the problem without copying file to tmp

**Comment by sethvargo** [comment]
Thanks :smile:

**Comment by kkopachev** [comment]
meh, `-i` won't work, it still creates temp file

**Comment by dominikzogg** [comment]
same here since 1.7.3 / virtualbox 5 / Ubuntu 14.04 host

**Comment by mitchellh** [comment]
Fixed
