### ISSUE TITLE
VM is not able to destory - if you change the name of parent folder

### ISSUE THREAD

**Issue by cooldharma06** [mitchellh/vagrant#5962]
i created one vm in the folder /home/sample

using vagrant up

Then i renamed the folder to /home/Sample

now vm is in running state and unable to destory the VM.

```
-> vagrant destroy 1819d20
The working directory for Vagrant doesn't exist! This is the
specified working directory:

/home/sample
```

```
-> vagrant global-status
id       name    provider   state    directory                                              
............................................................................................................                                
1819d20  puppet  virtualbox running  /home/sample
```

then i renamed the folder to Sample -> sample

```
-> vagrant destroy 1819d20
 puppet: Are you sure you want to destroy the 'puppet' VM? [y/N] y
```

Now it got destroyed.

I think after creating the folder you have to lock the path or reflect the changed path in corresponding VM also.

**Comment by mitchellh** [comment]
Unfortunately the way global status works, it'll never be able to detect that you moved your entire Vagrant environment. Renaming is in essence the same as moving the entire directory. The way global status works is that it points an ID to a directory. If you move it, it won't work.

If you run `vagrant status` within the new directory, it'll update the central status and everything will be up to date. 

I can't think of any technical way around this.
