### ISSUE TITLE
Vagant 1.7.3 /bin/systemctl restart rpcbind nfs

### ISSUE THREAD

**Issue by elvetemedve** [mitchellh/vagrant#5963]
Vagrant up command fails to start the VM dues to this error:
`bash: line 3: /bin/systemctl: No such file or directory`

Environment:
Host: 
 - OS: Arch Linux 
Guest:
 - CentOS release 6.6 (Final) <- this OS does not have SystemD installed.

**Comment by sethvargo** [comment]
Hi @elvetemedve 

This looks like a duplicate of #5948, which we will get out shortly in Vagrant 1.7.4. Sorry about the regression!

**Comment by thiagotalma** [comment]
+1
I look forward this fix. I'm not getting get up any machine to work.  :+1:
