### ISSUE TITLE
Port forwarding not working in vagrant - exporting box

### ISSUE THREAD

**Issue by cooldharma06** [mitchellh/vagrant#5968]
I created the vm with vagrant (virtualbox) and then i added port forwarding in my new Vm like for apache2 80 - 9797.

then i packed the vm (vagrant package) and i added into new box.

From the new box i tried to create vm. Now the new VM is not doing the portforwarding (80->9797).

So i think. the port forwarding rules are not reflecting; when are exporting the VM image.

Kindly have a look on this.

**Comment by sethvargo** [comment]
Hi @cooldharma06 

Could you please share your complete Vagrantfile? Thanks!

**Comment by cooldharma06** [comment]
hi @sethvargo 

please refer this link: http://pastebin.com/tGeXE2EQ

thanks,
cooldharma06

**Comment by mitchellh** [comment]
None of the Vagrant settings hold over, only the disk contents. To add settings, use the `--vagrantfile` flag.
