### ISSUE TITLE
Different pages on http://www.vagrantup.com/downloads.html and https://www.vagrantup.com/downloads.html

### ISSUE THREAD

**Issue by yhekma** [mitchellh/vagrant#5969]
It turns out that when going to https://www.vagrantup.com/downloads.html the latest version available for download is 1.7.2, while going to the page without the ssl-part (http://www.vagrantup.com/downloads.html) the version to download is 1.7.3
Because the site looks very much the same this had me stumped for a while.

I am pretty sure there is a better way of reporting this, only I cannot think of one right now...

**Comment by sethvargo** [comment]
Hi @yhekma 

I just checked and both pages list 1.7.3 as the latest download. I think your browser may have cached the page. Please try clearing your browsers cache or do a hard refresh. Thanks!
