### ISSUE TITLE
WinRM communicate.ready? raises exception on connection timeout

### ISSUE THREAD

**Issue by bheuvel** [mitchellh/vagrant#5970]
Up untill v1.7.2 WinRM Communicator communicate.ready? returned false on connection timeout (Errno::ETIMEDOUT).

This used to be caught/handled by: https://github.com/mitchellh/vagrant/blob/v1.7.2/plugins/communicators/winrm/communicator.rb#L37
```ruby
rescue Vagrant::Errors::VagrantError => e
```

But since v1.7.3 the rescue has been replaced with:
https://github.com/mitchellh/vagrant/blob/v1.7.3/plugins/communicators/winrm/communicator.rb#L104 
```ruby
rescue Errors::TransientError => e
```
which doesn't catch Errno::ETIMEDOUT, resulting in ready? returning/raising an exception.

In my case this happens as I'm using(/coding) Winrm with(/into) the Vagrant-Cloudstack plugin ([my branch here](https://github.com/bheuvel/vagrant-cloudstack/tree/winrm)).
The guest is accessed by portforwarding/firewall. Untill WinRM is available, the firewall drops the TCP connect request packets, instead of returning denied/not-available (REJECT).

So this should result in "ready?" returning false, instead of an exception, as this is normal behaviour for waiting for the server to boot up. Or at least normal for me :wink:.

**Comment by mitchellh** [comment]
Fixed by #5971
