### ISSUE TITLE
Vagrant 1.7.2 des not support VirtualBox 5.0

### ISSUE THREAD

**Issue by allentiak** [mitchellh/vagrant#5975]
Hello,

According to the official documentation, Vagrant supports VirtualBox 5.0. I have tried it with v1.7.2 (it was impossible to download v1.7.3), but it does not support it.

Tested using Vagrant 1.7.2 (both Debian's and upstream packages) and the edX VM from the course 
"CS100.1x Introduction to Big Data with Apache Spark"
(https://courses.edx.org/courses/BerkeleyX/CS100.1x/1T2015/info)

Vagrant file:
https://github.com/spark-mooc/mooc-setup/blob/master/Vagrantfile

Here's the output from using VirtualBox 5.0. With VrtuaBox 4.3, everything runs perfectly.

*********************************
$ vagrant up --provider=virtualbox
The provider 'virtualbox' that was requested to back the machine
'sparkvm' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3

**Comment by sethvargo** [comment]
Hi there,

Vagrant 1.7.3 is the only version that supports Virtualbox 5. Vagrant 1.7.2 did not have support. You can read more in the CHANGELOG for the full changeset. 

What issues were you having with downloading 1.7.3?

**Comment by allentiak** [comment]
2015-07-16 18:00 GMT+02:00 Seth Vargo <notifications@github.com>:
> Hi there,

Hi, Seth

Thanks for your quick reply.


> Vagrant 1.7.3 is the only version that supports Virtualbox 5. Vagrant 1.7.2 did not have support. You can read more in the CHANGELOG for the full changeset.

Thanks for that information.


> What issues were you having with downloading 1.7.3?

"File  not found" or something like that. In any case, I am
downloading it right now :-)

Thanks again!
Leandro

**Comment by sethvargo** [comment]
Okay thanks! I am going to close this issue, but please open a new issue if the download is not working.
