### ISSUE TITLE
puppet provisioner fails when environment dir contains dots

### ISSUE THREAD

**Issue by riuvshin** [mitchellh/vagrant#5976]
Hi, maybe this is already known issue but I'm unable to find any related.

**vagrant 1.7.3**
     config.vm.provision :puppet do |puppet|
        puppet.environment_path = "environments"
        puppet.environment = "dev.box"
     end

    ==> default: Running provisioner: puppet...
    ==> default: Running Puppet with environment dev.box...
    ==> default: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/environments.rb:38:in `get!': Could not find a directory environment named 'dev.box' anywhere in the path: /tmp/vagrant-puppet/environments. Does the directory exist? (Puppet::Environments::EnvironmentNotFound)
    ==> default: 	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application_support.rb:29:in `push_application_context'
    ==> default: 	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:337:in `run'
    ==> default: 	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:124:in `run'
    ==> default: 	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
    ==> default: 	from /bin/puppet:5:in `<main>'

but it works fine if I rename my env to **devbox**

**Comment by Mattias-** [comment]
Does it work if you ssh in to the box and run the puppet agent manually?
By looking at the output this looks like a puppet thing and not a vagrant issue.

You can find the exact command if you log in the output by running:
 `vagrant provision --provision-with=puppet --debug`

**Comment by Mattias-** [comment]
More info. Dots are not allowed!
http://docs.puppetlabs.com/puppet/latest/reference/environments_creating.html#allowed-environment-names

**Comment by sethvargo** [comment]
This definitely looks like a Puppet bug. Thanks for finding that @Mattias-!

**Comment by riuvshin** [comment]
Got it, thank you guys!
