### ISSUE TITLE
Delay to sync code changes in rails

### ISSUE THREAD

**Issue by i7webmidia** [mitchellh/vagrant#5985]
Hello.

I'm having the following problem:

I have a rails project using vagrant with ubuntu on my windows machine.

I put my project in a shared folder vagrant (/ vagrant).

When I make any change in any class, I need to wait about 40 seconds for the rails server reflects the changes, or restart the server.

PS: This problem does not occur when I change any view.

But if I copy the rails project folder out of the shared folder, any changes I make in the code of the classes, are immediately reflected by the server.

What could have caused this problem, since everything worked perfectly there two days ago?

Grateful.

**Comment by mitchellh** [comment]
Can you please ask this question in the mailing list? This is a usage question and doesn't represent a bug in Vagrant (I promise, it is a shared folder issue that Vagrant doesn't touch). Thanks! You'll get more responses there.

**Comment by i7webmidia** [comment]
ok.

Sorry,

I will ask this question in the mailing list
Thanks
