### ISSUE TITLE
persisting issue: The box failed to unpackage properly.

### ISSUE THREAD

**Issue by tensorspace** [mitchellh/vagrant#5989]
I am using mac os x 10.10.4, 64bit. Since atlas server is too slow, I downloaded the box file via a 3rd party download agent and tried to add it by command vagrant box add. After the unpack progress went to 100%, it returns:
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format
You see, the place for failed attempted package is empty. 
What is wrong with this? Could anyone help me, please? Thank you guys.

**Comment by sethvargo** [comment]
Hi @tensorspace 

It is possible that the box did not download successfully/completely. Usually this means you downloaded a box file that was not properly compressed or is not a proper vagrant box.

**Comment by sethvargo** [comment]
Hi @tensorspace 

I was just wondering if you had a chance to look at my comment.

**Comment by sethvargo** [comment]
I am going to close this due to lack of response. If this is still occurring, please open a _new_ issue share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks! :smile:

**Comment by Cybs** [comment]
@sethvargo I met the same problem. Please visit #8487
