### ISSUE TITLE
'box list' doesn't invoke Vagrantfile but 'box update' does. Why?

### ISSUE THREAD

**Issue by utdrmac** [mitchellh/vagrant#5996]
This makes no sense to little 'ol me. All I want to do is update my boxes. Why must that invoke my Vagrantfile? ```vagrant box list``` does not invoke/execute Vagrantfile so why does ```vagrant box update```?  

For that matter, out of all of the 'box' subcommands (add, list, outdated, remove, repackage, update) list is the only one that does NOT invoke the Vagrantfile.

Is there functionality in more advanced Vagrantfiles that one would need box commands to execute it?

**Comment by sethvargo** [comment]
Hi @utdrmac 

`vagrant box list` searches your local machine for which boxes have downloaded, so there is no need to evaluate the Vagrantfile. Could you explain your use case a bit more? Thanks! :smile:

**Comment by utdrmac** [comment]
@sethvargo I think there was a misunderstanding here. What I'm trying to point out is that the Vagrantfile *is* executed on most box commands and I believe it should __not__ be.

```vagrant box list``` is *correctly, not* executing my Vagrantfile.
But, all other ```vagrant box``` commands *are* executing it which is *incorrect*.

You could probably reword this issue as "Vagrantfile incorrectly executed by most box commands"

add, list, outdated, remove, repackage, update should not need to invoke the Vagrantfile but they do. This is the bug.

**Comment by kcormier** [comment]
@utdrmac I don't think this is a bug.

Specifically addressing `vagrant box update`, the default for the command will only update boxes referenced in your Vagrantfile.  For example, if you have 10 boxes installed, but are only using 2, it will only attempt to download updates for the 2 boxes you are using!  I personally thing this behavior is desirable.

If you want to update a box explicitly, you can use the --box argument which will allow the update to run without a Vagrantfile.

**Comment by mitchellh** [comment]
Agreed with @kcormier.

The reason we have to evaluate the Vagrantfile is because `vagrant box update` is asking to inspect the box that your environment is using and update it.
