### ISSUE TITLE
PuTTy support

### ISSUE THREAD

**Issue by Stanzilla** [mitchellh/vagrant#5997]
I don't know why it was removed but please add back support for using PuTTy for SSH.

**Comment by mitchellh** [comment]
It wasn't removed. You can still use PuTTy by specifying the connection information present in `vagrant ssh-config`. Since Vagrant 1.7 we generate a random key for use with SSH, but we can't generate a PuTTy key directly since there is no programmatic way to do so. However, nothing is stopping you from using PuTTy on its own using the info from `vagrant ssh-config`.

**Comment by Stanzilla** [comment]
Hrm, with 1.7.2 I was able to just do `vagrant ssh`and it worked, now it complains

```
The `ssh` executable found in the PATH is a PuTTY Link SSH client.
Vagrant is only compatible with OpenSSH SSH clients.
```

so what changed and what do I have to change to continue using it like in 1.7.2?

**Comment by mitchellh** [comment]
That's odd, but that error message has been in Vagrant since early Vagrant 1.x (years). And historically Vagrant has _never_ worked with the PuTTY Link SSH client, only OpenSSH.

**Comment by Stanzilla** [comment]
Also I thought PuTTY does OpenSSH, certainly looks like it when I look at http://www.openssh.com/windows.html

**Comment by mitchellh** [comment]
PuTTY does not accept OpenSSH keys, it can just talk to an OpenSSH serer

**Comment by Stanzilla** [comment]
I always just converted the OpenSSH key to a ppk and had it loaded in pageant (PuTTY) and that worked up until the update and/or I installed https://github.com/bmatzelle/gow which also ships a version of PuTTy. Confused. :(

**Comment by mitchellh** [comment]
I can confidently say Vagrant has never not once ever worked with PuTTy SSH directly, only OpenSSH (I'm talking about clients here), except manually via a user creating a PPK and connecting via the PuTTy GUI, so I'm also not sure what ishappening for you.

**Comment by Stanzilla** [comment]
I have friends that never used anything else than PuTTY with Vagrant/Homestead and it always worked for them, too.

**Comment by mitchellh** [comment]
I really don't know what to tell you, I'm sorry. I know Vagrant doesn't work (and has _never_ worked) passively with PuTTY.

**Comment by loostro** [comment]
I've got a related problem.

```console
> vagrant up --provision
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'puphpet/ubuntu1404-x64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: Setting the name of the VM: foobar_default_1438760106111_74385
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 5780 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```

I'm useing [scoop openssh](https://github.com/lukesampson/scoop/wiki/SSH-on-Windows#customising-ssh-settings) client. Any ideas what could be wrong and how to fix this?
