### ISSUE TITLE
Prompt once for username and password when mounting same folder using smb on multiple machines

### ISSUE THREAD

**Issue by F21** [mitchellh/vagrant#6000]
When mounting the same folder using SMB onto multiple machines, it would be nice if we're just prompted for the username and password once.

I have a vagrantfile that boots 3 VMs. These vms mounts the vagrant directory using smb:

```
config.vm.synced_folder ".", "/vagrant", type: "smb"
```

I am currently being prompted 3 times for my username and password. Prompting just once would be more user-friendly.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
