### ISSUE TITLE
VBoxManage.exe Error Shared Folder named "vagrant" already exists.

### ISSUE THREAD

**Issue by Jakobud** [mitchellh/vagrant#6001]
I'm on a Windows host and because of the 260 character path limitations in Windows, I've told Vagrant to not create the default `/vagrant` shared folder and instead I created it manually myself:

    # Disable default vagrant share
    config.vm.synced_folder ".", "/vagrant", disabled: true
    
    # Setup the shared vagrant folder, bypassing Windows 260 character limit
    config.vm.provider "virtualbox" do |v|
           v.memory = "1024"
           v.customize ["sharedfolder", "add", :id, "--name", "vagrant", "--hostpath", (("//?/" + File.dirname(__FILE__)).gsub("/","\\"))]
           v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    end
    
    # Mount the shared folder on the guest
    config.vm.provision :shell, inline: "mkdir -p /vagrant", run: "always"
    config.vm.provision :shell, inline: "mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant", run: "always"

This has worked great so far. But once I shut down the Vagrant environment and later attempted to bring it back up, I get:

    ==> default: Clearing any previously set forwarded ports...
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
        default: Adapter 2: hostonly
    ==> default: Forwarding ports...
        default: 22 => 2222 (adapter 1)
    ==> default: Running 'pre-boot' VM customizations...
    A customization command failed:
    
    ["sharedfolder", "add", :id, "--name", "vagrant", "--hostpath", "\\\\?\\d:\\vm\\
    dev01"]
    
    The following error was experienced:
    
    #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxMana
    ge`, a CLI used by Vagrant
    for controlling VirtualBox. The command and stderr is shown below.
    
    Command: ["sharedfolder", "add", "a46a4337-d5b8-4f48-a660-00cf5d072743", "--name
    ", "vagrant", "--hostpath", "\\\\?\\d:\\vm\\dev01"]
    
    Stderr: VBoxManage.exe: error: Shared folder named 'vagrant' already exists
    VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), componen
    t SessionMachine, interface IMachine, callee IUnknown
    VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostp
    ath).raw(), fWritable, fAutoMount)" at line 1008 of file VBoxManageMisc.cpp
    >
    
    Please fix this customization and try again.

Okay so I guess this means that the Vagrantfile is trying to create that shared folder again even though it's already been created and is in VirtualBox. Is there a way to conditionally create this share only if it doesn't already exist?

**Comment by drmyersii** [comment]
Hey there, @Jakobud. I'm actually the one that came up with the solution you are currently using, and here is what I've been doing:

I just comment this line out on the initial ```vagrant up```, and I uncomment it for the rest of the time I'm using the machine. It's obviously far from ideal, but it works with little effort as long as you don't need to rebuild your machine all the time.

```ruby
v.customize ["sharedfolder", "remove", :id, "--name", "vagrant"]
```

If you do need to rebuild your machine, just comment this line out again. Otherwise, VirtualBox will throw an error about the share not existing.

I'm planning on using an internal script to search for the share name based on the output of the machine's config file and conditionally mount the share, but I haven't had the time yet.

Hopefully this helps! Good luck, and happy coding!

**Comment by mitchellh** [comment]
I'm going to close this since @drmyersii posted a great solution. Thanks!
