### ISSUE TITLE
chef zero - how to add recipes depending the provider

### ISSUE THREAD

**Issue by lioramilbaum** [mitchellh/vagrant#6003]
I have two providers: virtualbox and aws
The provisioner is: chef zero

How do I add different recipes according to the provider?

For example: 

		clm.vm.provision :chef_zero do |chef|
			chef.cookbooks_path = ["./cookbooks/"]
			chef.environments_path = ["./environments/"]
			chef.environment = 'prev'
			chef.add_recipe "CLM::init"
			if provider == "aws"
			  chef.add_recipe "base::ec2"
			end
		end

**Comment by sethvargo** [comment]
Hi @lioramilbaum 

Thank you for opening an issue. Usually you do this type of switching in Chef itself, for example in your `CLM::init` cookbook, you would add the following:

```ruby
include_recipe "base::ec2" if node.key?("ec2")
```

or, if you're using Chef Sugar:

```ruby
include_recipe "base::ec2" if ec2?
```

And then let Chef handle the run_list expansion for you based on the node it's currently running.

Does that answer your question?

**Comment by lioramilbaum** [comment]
Thanks @sethvargo. It answers my question.
