### ISSUE TITLE
Look into support for xhyve as a provider on OS X

### ISSUE THREAD

**Issue by olbrew** [mitchellh/vagrant#6008]
Recently a new lightweight virtualization project, xhyve, for OS X was introduced. It uses the new built-in [Hypervisor.framework](https://developer.apple.com/library/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_10.html) from the Yosemite release.
For more info see [here](http://www.pagetable.com/?p=831).

This means it runs vastly more efficient than the traditional VirtualBox provider and Vagrant could thus also benefit from this. Is there any possibility that Vagrant could offer support for this?

I realize that it isn't a cross-platform solution like VirtualBox but considering the advantages it might be worth it. Here you can check out CoreOS which already has [experimental support](https://github.com/coreos/coreos-xhyve).

**Comment by sethvargo** [comment]
Hi @olbrew 

I think this is something we would prefer to see as a community-supported plugin first. Once it gains more traction and the hypervison matures a bit, I think it makes sense to move that into Vagrant core.

**Comment by mitchellh** [comment]
Agreed that lets see a plugin of this first.

**Comment by olbrew** [comment]
Alright. Didn't know this was possible. I will try to look into it in my free time.

**Comment by rickard-von-essen** [comment]
@olbrew Be sure to update here with a link if you get started with some code. I'm also interested in this.

**Comment by olbrew** [comment]
Sorry for the late reply, I was on vacation. Unfortunately my work situation has changed recently and I will not have time for this in the foreseeable future. I am though still interested in this, so if anyone else has more time on their hands?

**Comment by graingert** [comment]
Have a look at: https://medium.com/the-journey-of-code/creating-virtual-dev-environment-with-xhyve-fe501005fc6c

**Comment by dwijnand** [comment]
:+1: this would be great

**Comment by rickard-von-essen** [comment]
(This is a cross post from https://github.com/mitchellh/packer/issues/2711#issuecomment-172482039 )

Currently there are some problems with using xhyve/bhyve. The most important are:

- Only raw disk image supported, but qcow2 is coming. (Ongoing, see xhyve-xyz/xhyve#1)
- Using a network requires executing as super user. This is probably something that we have to live with, at least on OS X.
- Setting up network and detecting dhcp lease must be handled. This could be a interesting point to work on.

Bhyve will be much better on FreeBSD 11.0 which will be released in 2016 Q3. Xhyve development seems to have halted a bit and there is some confusion on how the project will proceed.

**Comment by darkn3rd** [comment]
Docker is swapping out Virtualbox and xhyve.

https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

**Comment by cromulus** [comment]
Looks like there's a plugin: https://github.com/oldpatricka/vagrant-xhyve

**Comment by graingert** [comment]
@eirnym https://web.archive.org/web/20150911184546/https://medium.com/the-journey-of-code/creating-virtual-dev-environment-with-xhyve-fe501005fc6c

**Comment by pcgeek86** [comment]
Could we re-open this? I would much rather use the built-in hypervisor for MacOS vs. having to install VirtualBox, similar to how Canonical's Multipass tool works.

**Comment by eirnym** [comment]
Totally agree with that. I can use docker with b/xhyve with no problems
Plugin seems to be dead and outdated.
