### ISSUE TITLE
proxy no longer a config option or I've been using it wrong

### ISSUE THREAD

**Issue by kernelsmith** [mitchellh/vagrant#6010]
I tried to ask this question on #vagrant however someone is spamming the channel and there are no chanops to stop the person.

```Ruby
config.proxy.http = "http://someproxy:8080"
```

is now failing with:

```
* Unknown configuration section 'proxy'.
```
I can't really find any documentation on any of the allowed config options, but this was working fine (or being blissfully ignored) until I upgraded to 1.7.4.  I'm not sure exactly what ver I was using prior to this, but it couldn't have been more than a few months old.  I stripped down my Vagrantfile so it only had the proxy setting and a single vm w/no provisioning (beyond network and synced_folder).  What am I missing?  I saw some recent proxy references in the changelogs but they *seem* to be unrelated.

```
$ vagrant -v && ruby -v
Vagrant 1.7.4
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64]
```

**Comment by sethvargo** [comment]
Hi @kernelsmith 

It looks like you might have been using a third-party plugin, perhaps [this one](https://github.com/tmatilai/vagrant-proxyconf)? Vagrant has never had first-class support for those options.

Can you run `vagrant plugin list`? It's possible this is a regression in plugin loading in 1.7.4.

**Comment by kernelsmith** [comment]
ah @sethvargo thanks, I'm an idiot.  That's very likely the situation.  I must have previously been using it (I nuked the plugins directories earlier in a moment of troubleshooting)
