### ISSUE TITLE
Vagrant 1.7.4 and Virtualbox 5 can't create host-only adapter

### ISSUE THREAD

**Issue by sanglt** [mitchellh/vagrant#6013]
![screen shot 2015-07-21 at 2 10 37 pm](https://cloud.githubusercontent.com/assets/128535/8794920/56f73e28-2fb2-11e5-971a-59ba06a8895e.png)
I just debug and see the latest version of vagrant can't work well with any version of Virtualbox on Windows. I test witl VirtualBox 4.xx -> 5.0

My test OS: Windows 10, also this error happen on Windows 8.1 and Linux too.
On MAC, its work fines.

**Comment by ijimmy** [comment]
I have this problem too...

**Comment by SD-Lab** [comment]
+1 Same problem too on windows 10 / VB 5.0.0 / vagrant 1.7.4

**Comment by derksacklowski** [comment]
+1 having the same problem

**Comment by cmaxo** [comment]
Looks like this may be an issue between windows 10 and virtualbox: https://www.virtualbox.org/ticket/14040

**Comment by SD-Lab** [comment]
I just updated VB to 5.0.3 (test build) and it works fine !

**Comment by mitchellh** [comment]
This is a VirtualBox bug.
