### ISSUE TITLE
Feature Request: Configurable --[no-]parallel in the VagrantFile

### ISSUE THREAD

**Issue by GavinOsborn** [mitchellh/vagrant#6014]
In a system that I am building we are making heavy use of the 

`vagrant up --no-parallel`

It would be nice to specify in the `Vagrantfile` either
 + The default behavior of `vagrant-up` with regards to `--[no-]parallel`
 + Disabling parallel altogether.

This helps scenarios such as mine where I am creating multiple docker containers from the same VagrantFile. Each docker container runs a Ruby service that use a similar set of Ruby gems.
By leveraging `--no-parallel` we don't end up downloading our dependent ruby gems multiple times.

It would be great to have this baked into the `VagrantFile`.

**Comment by wgrrrr** [comment]
This would be a great feature that I'd use as well.

**Comment by sebdah** [comment]
:+1:

**Comment by passcod** [comment]
:+1:

**Comment by iamahern** [comment]
+1

**Comment by laszlof** [comment]
+1

**Comment by LongLiveCHIEF** [comment]
+1

**Comment by laszlof** [comment]
This doesnt really solve the problem. We could easily set an alias for vagrant up to call `--no-parallel`, which is effectively the same as what the now documented `VAGRANT_NO_PARALLEL` does. Allowing it to be placed inside the Vagrantfile will enable us to distribute the package without having a caveat in the documentation that warns people to ensure they use `VAGRANT_NO_PARALLEL` or `--no-parallel`

**Comment by laszlof** [comment]
Looked this over again, and it looks like VAGRANT_NO_PARALLEL can be defined inside the Vagrantfile, which solves the issue. However, this seems like an odd way to use it. Maybe the documentation should reflect that as well.
