### ISSUE TITLE
Guest Additions install fails because of missing dependency bzip2

### ISSUE THREAD

**Issue by hectorcanto** [mitchellh/vagrant#6016]
The automated installation of Virtual Box Guest additions fails because *bzip2* is not pre-installed nor installed automatically, leaving an incomplete installation in */opt*. I'm using:
* vagrant 1.7.2
* virtualbox 4.3.30r101610
* CentOS 7 as guess

To get round pass this issue I've needed to clean the failed installation, install bzip2 and re-run the Guest Additions installation, more or less like this:

```
rm -rf /opt/VBoxGuestAdditions*
sudo yum -y install bzip2
exit
vagrant vbguest
```

I believe *bzip2* dependency is missing, some OS might have it pre-installed and others don't. 
I assume that it may be fault of the .iso script but I wanted to share it anyway, just in case.

**Comment by sethvargo** [comment]
Hi @hectorcanto 

What type of host machine are you using? I just tried this with Vagrant 1.7.4, but I could not reproduce (I am also using virtualbox 5 though). 

Could you please share your Vagrantfile and the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by hectorcanto** [comment]
Host is Ubuntu 14.04 with a 3.19 kernel.
I didn't want to use vagrant 1.7.4 and Vbox 5.0 because of an issue with NFS (#4476)
It is good to know that it is not happening with those versions, maybe I change my approach (use rsync for instance or install guest additions manually and make an image).

My Vagrantfile is https://gist.github.com/hectorcanto/14d34d59f23da84ce1fd
The Gist has a excerpt of the prompt. I won't debug it today, maybe tomorrok.

Thanks for your help!

**Comment by yangm97** [comment]
Running OS X El Capitan, VB 5, centos/7, also getting missing bzip2 error form Guest Additions.

**Comment by yloh-ewn** [comment]
Update your vagrant-vbguest to pick up this [patch] (https://github.com/dotless-de/vagrant-vbguest/commit/3107e30e2de4a705d66a9db6b5456ce42e7e402a)

**Comment by obfuscurity** [comment]
Seen with Vagrant 1.7.2 on OS X Yosemite (10.10.5) with VirtualBox 4.3.32 and CentOS 7. Updating vagrant-vbguest to 1.10.1 works for me.

**Comment by sethvargo** [comment]
Hi all,

I am still unable to reproduce this on Vagrant 1.7.4, vbox 5. I don't have a spare laptop handy to install vbox 4.x and try it out, but it sounds like the recommended workarounds are:

- Upgrade to vbox 5 and vagrant 1.7.4+
- Upgrade vagrant-vbguest to 1.10+
- Manually install bzip2

Is that correct?

**Comment by yloh-ewn** [comment]
Yeah, it seems some combination of those workarounds should get anyone through to a working system.

**Comment by mitchellh** [comment]
This is an issue with an external plugin. Please report it with them. Thanks!
