### ISSUE TITLE
Error `Invalid argument - ruby_setenv (Errno::EINVAL)` on `vagrant halt`

### ISSUE THREAD

**Issue by thasmo** [mitchellh/vagrant#6017]
Default output:
```sh
vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c /vagrant/provision/automation/backup.sh"...
==> default: C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:72:in `[]=': Invalid argument - ruby_setenv (Errno::EINVAL)
==> default:    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:72:in `init!'
==> default:    from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:23:in `<main>'
==> default: Command execution finished.
The command "vagrant ssh -c '/vagrant/provision/automation/backup.sh'" returned a failed exit code. The
error output is shown below:

C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:72:in `[]=': Invalid argument - ruby_setenv (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:72:in `init!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/pre-rubygems.rb:23:in `<main>'
```
[Debug output.](https://gist.github.com/thasmo/9169f48c409c836abac4)

**Comment by sethvargo** [comment]
Hi @thasmo 

This looks not good! Can you please share your complete Vagrantfile as well as your guest specs (I assume it's Windows, but what OS, etc)?

**Comment by thasmo** [comment]
Hey @sethvargo, [this is my Vagrantfile](https://github.com/thasmo/vagrant.box/blob/a0b7a3714a5cda0c21ad424092d5277e967093e2/Vagrantfile). My OS is Windows 8.1 64 bit using VMware Workstation 11.1.2 build-2780323.

**Comment by thasmo** [comment]
Also I'm running this via Cygwin.

**Comment by thasmo** [comment]
@sethvargo, still happens on Windows 10.

**Comment by thasmo** [comment]
@sethvargo, anything I can provide to get this fixed?

**Comment by mitchellh** [comment]
From some googling, this is caused by an environment variable value that is too long. Sigh. I'm really not sure how to work around this, since the maximum size is quite large (it is the size of all env vars combined).

The best I can do is catch these error and show a message to the user.
