### ISSUE TITLE
Atlas and caching

### ISSUE THREAD

**Issue by mjdavies** [mitchellh/vagrant#6019]
Hello everyone

Is this the right place to bring up some issues I'm having using atlas and vagrant?

I've been going round and round trying to work out what has been caching a build on my local machine, couldn't get a new build down.

I then accidentally tried to vagrant up a build of something I deleted from hashicorp, and it found it!

Does anyone know what's going on here, and also if there's a mechanism to clear my cache of what's going on in atlas?

**Comment by sethvargo** [comment]
Hi @mjdavies 

Please email support@hashicorp.com and include the name of the artifact and your username in Atlas.

Thanks,
Seth
