### ISSUE TITLE
ansible provisioner timeout problem for multi-machine setup and private networking

### ISSUE THREAD

**Issue by egroeper** [mitchellh/vagrant#6020]
I'm trying to test my ansible configstack using vagrant and the ansible provisioner.
I'm using 6 machines in a multi-machine setup using private networking and static inventory.
After calling `vagrant up` the machines get started and everything looks fine at first. But when ansible provisioner is run, usually some of the machines have connection timeouts:
```
fatal: [192.168.23.11] => SSH Error: ssh: connect to host 192.168.23.11 port 22: Connection timed out while connecting to 192.168.23.11:22
```

I had similar issues with vagrant 1.4.3 (ubuntu default), but now tried it with vagrant 1.7.4 hoping this would help.

After waiting some time and running ```vagrant provision``` again, it usually works. But there seems to be a timeout issue / race condition and i couldn't find a way to wait till all machines have working network.

Here is my debug output:
* [Vagrantfile](https://gist.github.com/egroeper/a4c140a421c631c55e0e)
* [DebugLog](https://gist.github.com/egroeper/83765932398fdf5da0be)

Unfortunately in this test run I seem to have had some wifi issues causing problem with uplink lan connectivity. But this shouldn't be related to my problems (timeout in private networking) and didn't happen in the other runs.

**Comment by egroeper** [comment]
Okay. This seems to be a problem with my VirtualBox (4.3.30) and hostonly networking.
The following workaround seems to work:
```
# startup machines without provisioning
vagrant up --no-provision
# extract hostnames from Vagrantfile and send ping to gateway (vagrant host) from each vm
# this somehow repairs/activates/revives internal (hostonly) networking
for host in `fgrep define Vagrantfile | sed -e s'/^\s*//' -e 's/\s*$//' | cut -d' ' -f 2 | tr -d '"'`; do vagrant ssh $host -c "ping -c 2 192.168.23.1"; done
# finally: provision
vagrant provision
```

Not sure if this bug belongs here anymore... Of course a real solution would be nice.
Please close, if you think this is a VirtualBox bug unrelated to vagrant.

**Comment by sethvargo** [comment]
Hi @egroeper 

We generally recommend Terraform if you are trying to bring up this many machines with orchestration instead of setting up complex private networks like this. Have you looked at Terraform?

It's difficult to tell whether this is an ansible issue or a Vagrant issue right now, and I can't use your Vagrantfile to reproduce because it links to ansible modules. Would it be possible to get a smaller reproduction case that does not use ansible or provisioning at all?

**Comment by egroeper** [comment]
I'm trying to use Vagrant to test my Ansible Configstack. So Terraform isn't an alternative here.
I will try to reproduce this without using Ansible / Provisioning.
Currently I guess it's a Virtualbox networking issue.

**Comment by mitchellh** [comment]
Please let us know if you find out anything more. At this point I agree its likely not a Vagrant issue. If you find out more just tell us and we'll reopen.
