### ISSUE TITLE
nfs service isn' detected by vagrant

### ISSUE THREAD

**Issue by majioa** [mitchellh/vagrant#6021]
Hello when I run `vagrant up` I get the error:

    It appears your machine doesn't support NFS, or there is not an adapter to enable NFS on this machine for Vagrant. Please verify that `nfsd` is installed on your machine, and try again. If you're on Windows, NFS isn't supported. If the problem persists, please contact Vagrant support.

However nfs service is being run:

    # service nfs status
    active

How to fix it?

> System: altlinux 7.0
> \# uname -a
    Linux psittaca.skr 3.14.44-std-def-alt1 #1 SMP Tue Jun 9 12:55:22 UTC 2015 x86_64 GNU/Linux
> \# vagrant -v
    Vagrant 1.7.4

**Comment by mitchellh** [comment]
Closing in favor of #6304 which appears to be a dup with hints on fixing.
