### ISSUE TITLE
Mounting nfs requires sudo, but the sudoers file given in documentation no longer works.

### ISSUE THREAD

**Issue by Mihara** [mitchellh/vagrant#6022]
After upgrading to Vagrant 1.7.4, the following sudoers file, [given in the documentation](https://docs.vagrantup.com/v2/synced-folders/nfs.html), no longer produces the desired result on Ubuntu 14.04:

```
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD_CHECK = /etc/init.d/nfs-kernel-server status
Cmnd_Alias VAGRANT_NFSD_START = /etc/init.d/nfs-kernel-server start
Cmnd_Alias VAGRANT_NFSD_APPLY = /usr/sbin/exportfs -ar
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /bin/sed -r -e * d -ibak /etc/exports
%sudo ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD_CHECK, VAGRANT_NFSD_START, VAGRANT_NFSD_APPLY, VAGRANT_EXPORTS_REMOVE
```

Running `vagrant up --debug`, unfortunately, results in no hints on what command it actually wants to run, so I find it quite difficult to figure out what do I need to do to make it work again.

It worked in 1.7.2.

**Comment by narkisr** [comment]
Confirmed on 14.10, looking at /var/log/auth.log I don't see the failing command either

**Comment by narkisr** [comment]
Iv tracked this to a series of commits done on [nfs.rb](https://github.com/mitchellh/vagrant/commits/master/plugins/hosts/linux/cap/nfs.rb) while solving [this](https://github.com/mitchellh/vagrant/issues/5957) issue, it seems that the exports remove has changed and new cp command added.

Still I'm able to produce a working sudoers entry to fix this

**Comment by narkisr** [comment]
I think that iv managed to find a working solution:

```bash
mnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_EXPORTS_COPY = /bin/cp /tmp/exports /etc/exports
Cmnd_Alias VAGRANT_NFSD_CHECK = /etc/init.d/nfs-kernel-server status
Cmnd_Alias VAGRANT_NFSD_START = /etc/init.d/nfs-kernel-server start
Cmnd_Alias VAGRANT_NFSD_APPLY = /usr/sbin/exportfs -ar
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /bin/sed -r -e * d -ibak /tmp/exports
%sudo ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD_CHECK, VAGRANT_NFSD_START, VAGRANT_NFSD_APPLY, VAGRANT_EXPORTS_REMOVE, VAGRANT_EXPORTS_COPY
```

Iv added a copy and changed the sed remote command

**Comment by Mihara** [comment]
Confirmed, it works. Thanks for figuring this one out.

**Comment by emodric** [comment]
I've tried this in 1.7.4 on Ubuntu 15.04 and sadly it doesn't work :(

**Comment by demoray** [comment]
the sed line should not need sudo privileges, as it is writing to a temp file.

**Comment by andrewmackrodt** [comment]
Thanks for your fix @narkisr, confirmed working with vagrant 1.7.4 and Ubuntu 14.04.02

**Comment by pascalmorin** [comment]
@narkisr Works for me too on Debian (Stretch).

**Comment by aosmialowski** [comment]
Weird, but @narkisr solution does not work for me on Ubuntu 14.04 LTS.

**Comment by nathanielks** [comment]
Woohoo! Thanks @sethvargo!

**Comment by dklotz** [comment]
The commands given in the documentation still do not work for me on OS X. They used to, but they stopped working (i.e. now require a password again) somewhere around 1.7.x...

**Comment by guysoft** [comment]
Not working for me on ubuntu 15.10

**Comment by karlingen** [comment]
For future googlers:
Se the section **ROOT PRIVILEGE REQUIREMENT** in the docs: [https://www.vagrantup.com/docs/synced-folders/nfs.html](https://www.vagrantup.com/docs/synced-folders/nfs.html)
