### ISSUE TITLE
Chef Zero Provisioner - Cannot specify Nodes Path

### ISSUE THREAD

**Issue by bdwyertech** [mitchellh/vagrant#6025]
After the release of Vagrant 1.7.3, the Chef Zero provisioner no longer accepts the ```nodes_path``` attribute, which would typically be a path to node objects for use in Chef Zero's Chef Server emulation.  I am unsure if this was intentional or not.

I previously used something like the below, but it no longer works.

```ruby
# Chef-Zero Configuration
  config.vm.provision "chef_zero" do |chef|
    # Specify the local paths where Chef data is stored
    chef.cookbooks_path = ["~/GIT/chef/cookbooks", "~/GIT/chef/site-cookbooks"]
    chef.roles_path = "~/.chef/CHEF/backup/roles"
    chef.nodes_path = "~/.chef/CHEF/backup/nodes"
    chef.data_bags_path = "~/GIT/chef/data_bags"

    # Add a role
    chef.add_role "alpha"
  end
```

I think https://github.com/mitchellh/vagrant/pull/5339 may have caused this

**Comment by drywheat** [comment]
I can confirm this behavior in v1.7.4 as well.
