### ISSUE TITLE
Guest machine with public network is not reachable from other computers in the same network

### ISSUE THREAD

**Issue by remss** [mitchellh/vagrant#6030]
Here a sample Vagrantfile 

    Vagrant.configure(2) do |config|
      config.vm.box = "debian/jessie64"
      
      config.vm.network "public_network", type: "dhcp"
      
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 4
      end
    end

Once the guest starts, it gets from DHCP the IP 10.17.0.101

If i ping 10.17.0.101 from the host => it works
But if i ping 10.17.0.101 from an other machine in the same networks => it fails :-(

Now, from VirtualBox, if i go in the configuration screen for this guest, stop it, then disable the network adapatater 1 (NAT), and starts the guest, now i can ping it from an other machine and it works !

Any idea?

vagrant 1.7.4 + VirtualBox 5.0.0

**Comment by sethvargo** [comment]
Hi @remss 

Are there any other IP addresses of that machine? What is the output of `ifconfig`? Please also note that you might need to update your firewall rules to allow pings from external network. If it's getting an IP address from your home router or dhcp server, that means it's connected to the network and therefore appears as a single device on the network, but your local machine's firewall may be preventing the connection from re-entering from a remote ping.

**Comment by remss** [comment]
Guest ifconfig output ...

    eth0      Link encap:Ethernet  HWaddr 08:00:27:37:3c:94
              inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
              inet6 addr: fe80::a00:27ff:fe37:3c94/64 Scope:Link
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:843 errors:0 dropped:0 overruns:0 frame:0
              TX packets:680 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000
              RX bytes:85287 (83.2 KiB)  TX bytes:85962 (83.9 KiB)

    eth1      Link encap:Ethernet  HWaddr 08:00:27:09:60:44
              inet addr:10.17.0.101  Bcast:10.17.255.255  Mask:255.255.0.0
              inet6 addr: fe80::a00:27ff:fe09:6044/64 Scope:Link
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:787 errors:0 dropped:0 overruns:0 frame:0
              TX packets:128 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000
              RX bytes:76929 (75.1 KiB)  TX bytes:24422 (23.8 KiB)

    lo        Link encap:Local Loopback
              inet addr:127.0.0.1  Mask:255.0.0.0
              inet6 addr: ::1/128 Scope:Host
              UP LOOPBACK RUNNING  MTU:65536  Metric:1
              RX packets:24 errors:0 dropped:0 overruns:0 frame:0
              TX packets:24 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0
              RX bytes:2064 (2.0 KiB)  TX bytes:2064 (2.0 KiB)

And yes, the guest is correctly connected to the network since it gets an IP from DHCP and see other network computers.

The Windows Firewall on my windows 7 host is disabled for all networks.

I don't think this is a firewall issue because when i disable the adaptater 1 (NAT) to just keep the adaptater 2 (Bridge) then it works...

**Comment by remss** [comment]
After installing VirtualBox 5.0.2 and Vagrant 1.7.4, it works now !
