### ISSUE TITLE
Docker Provider errors on Windows with Vagrant 1.7.4

### ISSUE THREAD

**Issue by alexandarp** [mitchellh/vagrant#6031]
I upgraded Vagrant to version ```1.7.4``` on my windows 7 box. When I ran ```vagrant up --no-parallel```, I got the following error:

```
Command: "docker" "build" "-t=mysql" "/var/lib/docker/docker_build_8a78c0"

Stderr: time="2015-07-23T17:01:08+02:00" level="fatal" msg="stat /var/lib/docker
/docker_build_8a78c0: permission denied"
```

A ```vagrant reload``` will throw the exact same error. I ended up downgrading back to version ```1.7.2``` and everything was working as expected. I should add that the folders seem to sync properly.

**Comment by sethvargo** [comment]
Hi @alexandarp 

Can you please share your complete Vagrantfile as well as the output of the command in debug mode as a Gist? Thanks!

**Comment by alexandarp** [comment]
@sethvargo no problem. Just confirmed that I receive the exact same error on Yosemite using Vagrant ```1.7.4```. Works fine on Vagrant ```1.7.2```.

Here is the Vagrantfile:
https://gist.github.com/alexandarp/3ec1dc451203eceef418

Here is the Debug log:
https://gist.github.com/alexandarp/4c7c1ac4a2b2ed5fe6d4

**Comment by alexandarp** [comment]
@sethvargo I ended up switching my base box from CentOS 6.6 to Ubuntu 14.04 and the problem disappeared.

**Comment by alexandarp** [comment]
For anyone else who experiences this error using a CentOS base box, add the following before the ```config.vm.provision "docker"``` line:

```
config.vm.provision "shell" do |s|
    s.inline = "groupadd -f docker"
end
```
