### ISSUE TITLE
Docker provisioner on 32 bit machines?

### ISSUE THREAD

**Issue by psychemedia** [mitchellh/vagrant#6032]
I'm trying to use the docker provisioner on a 32 bit Ubuntu box  which fails when the provisioner tries to install `E: Unable to locate package lxc-docker`.

Do I need to find myself a base box with docker already installed for 32 bit use (any idea if there are any "standard" such boxes out there somewhere?) or would it be possible to have the vagrant installer pull on a 32 bit docker package from somewhere?

**Comment by sethvargo** [comment]
I don't think [docker supports i386](https://github.com/docker/docker/issues/136), but please ask these types of questions on the Vagrant mailing list. We try to reserve the issue tracker for bug reports and feature requests. Thanks! :smile:
