### ISSUE TITLE
Adding a command in my Vagrantfile

### ISSUE THREAD

**Issue by warrenseine** [mitchellh/vagrant#6033]
I'd like to add a command to my `Vagrantfile`. I know the best practice would be to make a separate plugin, but there are cases where the command is not made to be generic.

I'm trying to add the following on top of a simple `Vagrantfile` (tried with `vagrant init`):

```ruby
module VagrantPlugins
  module MyPlugin
    class Command < Vagrant.plugin('2', :command)
      def execute
        puts "hello world"
      end
    end

    class Plugin < Vagrant.plugin('2')
      name "myplugin"

      command "test" do
        Command
      end
    end
  end
end
```

Unfortunately, running `vagrant test` shows Vagrant usage text instead of the echoed `hello world`. Is this expected to work?

**Comment by warrenseine** [comment]
Up @sethvargo @mitchellh ?

**Comment by warrenseine** [comment]
It works as expect when run in a separate plugin. I made a simple plugin [here](https://github.com/warrenseine/vagrant-hello).

Any idea why this doesn't work when hardcoded in a `Vagrantfile`?

**Comment by sethvargo** [comment]
Hi @warrenseine 

This has to do with the way Vagrant loads Vagrantfiles and recurses. In short, it is too late in Vagrant's initialization to add new plugins by the time the Vagrantfile has been evaluated.

**Comment by warrenseine** [comment]
@sethvargo `action_hook` do work at that time. See [this comment](https://github.com/dotless-de/vagrant-vbguest/issues/141#issuecomment-101071914) (tested and confirmed).

**Comment by warrenseine** [comment]
Well, apparently that's it.

I'll find another way. Maybe a https://github.com/emyl/vagrant-triggers could help.

**Comment by jontayesp** [comment]
:+1:  

I wish there were some way this could be supported.
