### ISSUE TITLE
Ordering of provider-specific provisioning

### ISSUE THREAD

**Issue by edmcman** [mitchellh/vagrant#6035]
I'm not sure if this is a bug request, a feature request, or request for help.  What I'm trying to do is have a provider-specific provisioning script run before all others.  The high-level use case for this is that some provisioning scripts are more to get a particular provider's environment set up correctly than for the my project, so the provider scripts need to run first.  One example is for AWS, to remount /tmp to an instance store.

For instance, I would like/expect the output of the following Vagrantfile to be A, B, D, C:

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "aws"
    config.vm.provider :aws do |aws, override|
      override.vm.provision :shell, inline: 'echo A'
    end
    config.vm.provision :shell, inline: 'echo B'
    config.vm.define :testing do |test|
        test.vm.provision :shell, inline: 'echo C'
    end
    config.vm.provision :shell, inline: 'echo D'
end
```

The actual output is B, D, C, A.

How can I achieve the order A, B, D, C?

(I would also be happy if someone suggested a reasonable workaround)

**Comment by sethvargo** [comment]
Hi @edmcman 

The Vagrantfile is evaluated at the top-level first, and then machine-specific provisioners take place after. In other words:

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "aws"
    # config.vm.provider :aws do |aws, override|
    #    override.vm.provision :shell, inline: 'echo A'
    # end
    config.vm.provision :shell, inline: 'echo B'
    # config.vm.define :testing do |test|
    #     test.vm.provision :shell, inline: 'echo C'
    # end
    config.vm.provision :shell, inline: 'echo D'
end
```

On the initial pass, that's what Vagrant sees. Since you can specify which machines you want to bring up (or which you don't), machine-specific provisioners are run _after_ the global provisioners, and any overrides take place _last_.

If you want to enforce a specific order, you can define all the provisioners in a single stanza:

```ruby
Vagrant.configure("2") do |config|
    config.vm.provider :aws do |aws, override|
      aws.vm.provision :shell, inline: 'echo A'
      aws.vm.provision :shell, inline: 'echo B'
      aws.vm.provision :shell, inline: 'echo C'
      aws.vm.provision :shell, inline: 'echo D'
    end
end
```

If you are sharing long scripts, you can save them to a variable outside the context of the Vagranfile, or save them to a local file and reference them in the provisioner.

Does that answer your question?

**Comment by edmcman** [comment]
Hi @sethvargo,

Thank you for the explanation -- it makes sense why the overrides are processed last now.

Your workaround works, but becomes awkward when some provisions are supposed to run with all providers.  For example:

```ruby
Vagrant.configure("2") do |config|
    config.vm.provider :aws do |aws, override|
      aws.vm.provision :shell, inline: 'echo A'
      aws.vm.provision :shell, inline: 'echo B'
      aws.vm.provision :shell, inline: 'echo C'
      aws.vm.provision :shell, inline: 'echo D'
    end
    config.vm.provider :vsphere do |vs, override|
      vs.vm.provision :shell, inline: 'echo B'
      vs.vm.provision :shell, inline: 'echo C'
      vs.vm.provision :shell, inline: 'echo D'
    end
end
```

I don't actually use inline scripts in practice; all my scripts are in files.  I can't consolidate them, though, because I have different Vagrantfiles that combine the scripts in different ways.  (Some Vagrantfiles might include A, B, C, D, some might only include A, C, D, etc.)  So working around this will make my Vagrantfiles huge and difficult to maintain.

Would be possible to add some other method of ordering to the provisioners, such as priority levels or dependencies?

**Comment by mitchellh** [comment]
We've talked about priority levels but the Vagrantfiles just become more and more complicated. We think for an advanced use case we'd rather people either duplicate the configs in each sub-machine or consolidate if possible. Thanks!
