### ISSUE TITLE
Get access to guest OS by 127.0.0.1 [Hyper-V + Ubuntu 14.04]

### ISSUE THREAD

**Issue by jarosluv** [mitchellh/vagrant#6036]
Hello!
How can I get access to guest OS by 127.0.0.1 in host OS?
I'm using Hyper-V as provider with Ubuntu 14.04.

**Comment by sethvargo** [comment]
Hi @jarosluv 

Thank you for opening an issue. Can you please ask this on the Vagrant mailing list? We try to reserve the issue tracker for bug reports and feature requests. Thanks!
