### ISSUE TITLE
CFEngine provisioner not reporting error

### ISSUE THREAD

**Issue by darkn3rd** [mitchellh/vagrant#6037]
**PROBLEM**: Script exits with error, this is not reported to the user.

**RESULTS**: Running a script that causes an error does not show any error:
```
$ vagrant provision
==> default: Running provisioner: cfengine...
==> default: CFEngine doesn't require bootstrap. Not bootstrapping.
==> default: Executing run file for CFEngine...

$ vagrant provision --debug
...
INFO ssh: Execute: /var/cfengine/bin/cf-agent -KI -f /tmp/vagrant-cfengine-file (sudo=true)
DEBUG ssh: Exit status: 0
...
```
```ruby
$ cat Vagrantfile | grep cf
  config.vm.provision :cfengine do |cf|
    cf.am_policy_hub = true
    cf.run_file = "badscript.cf"
```

**EXCPECTED RESULTS**: Running this manually on the vms system as root, I can see the error:
```
# /var/cfengine/bin/cf-agent -KI -f /tmp/vagrant-cfengine-file 
   error: Can't stat file '/var/cfengine/inputs/lib/3.7/stdlib.cf' for parsing. (stat: No such file or directory)
   error: Policy failed validation with command '"/var/cfengine/bin/cf-promises" -c "/tmp/vagrant-cfengine-file"'
# echo $?
1
```

**Comment by mitchellh** [comment]
We're just executing via SSH and that exit status is coming from SSH itself. We'll need more information to debug this since at the moment it looks like some strange system configuration issue. Can you please debug further?

**Comment by darkn3rd** [comment]
If I understand correctly, I can run ssh as a command, and should get the same results as vagrant provision?

**Comment by sethvargo** [comment]
Hi @darkn3rd,

Sorry for the delayed reply. Could you please share your complete Vagrantfile as well as the complete debug output as a GitHub gist? I'm not very familiar with CFEngine, but I will try to reproduce this.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include all of the information in the issue template. Thanks! 😄
