### ISSUE TITLE
Create API for getting list of synced folders of running Vagrant instance

### ISSUE THREAD

**Issue by tejksat** [mitchellh/vagrant#6038]
For better integration with Vagrant my company's program has to obtain list of synced folders for given Vagrant instance (in most cases which is running already). We need it to analyze which files are replicated automatically so we could map some remote files with local files on the host computer. Now we see several alternatives, each of which has its shortcomings:

1. Parse `Vagrantfile` (we use this approach now). But Vagrant instance might have been started with older version of the configuration, and we might get wrong data. Plus double work to parse this file again after Vagrant core had done it.

2. Parse `/.vagrant/machines/#{name}/#{provider}/synced_folders`. But this is an internal file and we are not sure what will it be turned into and if it is created always and etc.

3. Create a plugin, which does its job. Good one, but we need to install it somehow, so we might run into lack of privileges and we would change user environment, which seems to be slightly heavy for this task.

Please suggest a good choice or provide an API for getting list of synced Vagrant folders.

**Comment by sethvargo** [comment]
Hi @tejksat 

I would recommend 3 that does 2. You could write a plugin that parses the cache to see what folders are synced. Thanks!
