### ISSUE TITLE
Vagrant `chef.delete_node` and `chef.delete_client` issue

### ISSUE THREAD

**Issue by lukas0krupa** [mitchellh/vagrant#6039]
Hi guys,

is this actually implemented ? Options are there, but according to this (#336), it was not implemented. 

I have this
```
    chef.delete_node    = true
    chef.delete_client  = true
```

but after destroying machine client and node still present on chef server.

**Comment by sethvargo** [comment]
Hi @lukas0krupa 

Can you please share your complete Vagrantfile? Thanks!

**Comment by lukas0krupa** [comment]
Unfortunately I can't share that one, but I created one which does exactly same.

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # configure the libvirt provider
    config.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.connect_via_ssh = false
        libvirt.username = "libvirt-qemu"
        libvirt.storage_pool_name = "default"
        libvirt.memory = 1024
        libvirt.cpus = 1
    end

    # configure a vm called "default"
    config.vm.define :default do |default|
        default.vm.box = "naelyn/ubuntu-trusty64-libvirt"
        default.ssh.forward_agent = true
        default.vm.network "private_network", ip: "192.168.122.15"
        default.vm.synced_folder "", "/vagrant", type: '9p', accessmode: "mapped"
        default.vm.network "forwarded_port", guest: 3306, host: 3306
    end

    config.vm.provision "chef_client" do |chef|
        chef.chef_server_url = <chef_server_url>
        chef.validation_key_path = <path to chef-validator.pem>
        chef.validation_client_name =  <chef validator name>
        
        chef.node_name = "lukas-vagrant-not-deleting"
        
        chef.delete_node    = true
        chef.delete_client  = true
        
        chef.environment = "development"

        chef.add_recipe "java"
    end

end
```

**Comment by sethvargo** [comment]
Hi @lukas0krupa 

What version of Vagrant are you using? (`vagrant -v`)

**Comment by lukas0krupa** [comment]
Vagrant 1.7.4

Vagrant plugins (if it helps):
vagrant-libvirt (0.0.30)
vagrant-mutate (1.0.0)
vagrant-share (1.1.4, system)

**Comment by sethvargo** [comment]
Hi @lukas0krupa 

I just tried this myself and it's working for me:

```
==> default: Stopping the VMware VM...
==> default: Deleting the VM...
==> default: Running cleanup tasks for 'chef_client' provisioner...
==> default: Deleting client "lukas-vagrant-not-deleting" from Chef server...
==> default: Deleting node "lukas-vagrant-not-deleting" from Chef server...
```

I tried with VMware and Virtualbox. Since you aren't even seeing output, I suspect that the libvirt plugin is not firing cleanup hooks. Can you try with Virtualbox and see if it works for you please?

**Comment by lukas0krupa** [comment]
I tried to get Virtualbox, could get through process (ubuntu unhappy having libvirt/kvm and virtualbox on same machine), but it seems it tries to delete client and node. Looks like it have something to do with provider.

Do you suspect vagrant-libvirt to not doing `destroy` right ?

**Comment by sethvargo** [comment]
Hi @lukas0krupa 

I suspect the vagrant-libvirt provider is not invoking the cleanup tasks. Can you please open an issue on that project please? Thanks!
