### ISSUE TITLE
Binary to start VMware services could not be found

### ISSUE THREAD

**Issue by topikito** [mitchellh/vagrant#6043]
After the update from @sethvargo on ticket https://github.com/mitchellh/vagrant/issues/5946 tried to run the Technology Preview and got this message (As the https://github.com/mitchellh/vagrant/issues/5946#issuecomment-125339025) :

```bash
$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
The binary to start VMware services could not be found. This
is required in order to modify networking files. This can be caused
by a broken Fusion installation or an invalid Fusion version.
Please report a bug.
```

VMWare Fusion Technology Preview works just fine: machine can be executed with the VMWare GUI.

**Comment by sethvargo** [comment]
Hi @topikito 

You may need to specify the PATH to the binary with `VAGRANT_VMWARE_FUSION_APP`.

**Comment by stripecodahale** [comment]
That doesn’t work:

```
$ VAGRANT_VMWARE_FUSION_EXP=1 VAGRANT_VMWARE_FUSION_APP="/Applications/VMware Fusion Tech Preview.app"  vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
The binary to start VMware services could not be found. This
is required in order to modify networking files. This can be caused
by a broken Fusion installation or an invalid Fusion version.
Please report a bug.

$ file "/Applications/VMware Fusion Tech Preview.app"
/Applications/VMware Fusion Tech Preview.app: directory
```

**Comment by topikito** [comment]
Hi @sethvargo 

Thats already done:

```bash
$ export VAGRANT_VMWARE_FUSION_APP="/Applications/VMware Fusion Tech Preview.app"
```

I had previously wrongly specified the path by doing this:

```bash
$ export VAGRANT_VMWARE_FUSION_APP="/Applications/VMware\ Fusion\ Tech\ Preview.app"
```

And was getting this (Wrong binary):
```bash
The executable '/Applications/VMware\ Fusion\ Tech\ Preview.app/Contents/Library/vmware-vmx' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
```

I believe its a different situation

**Comment by brennovich** [comment]
@mikhail-guru tip still does the trick ;)

https://github.com/mitchellh/vagrant/issues/5946#issuecomment-124824660

**Comment by topikito** [comment]
Thanks @brennovich Ugly, but does the job

**Comment by sethvargo** [comment]
Hi all,

VMware Fusion 8 and VMware Workstation 12 are both available as well as updated plugins for Vagrant. Please see https://groups.google.com/forum/#!topic/vagrant-up/xm1IenmhzG0 for more information on upgrade pricing and information.

**Comment by mikhail-guru** [comment]
https://www.reddit.com/r/vagrant/comments/3ie38b/hashicorp_released_vmware_plugin_for_vagrant/
