### ISSUE TITLE
Merging Vagrantfile from box

### ISSUE THREAD

**Issue by VinothRavi-V** [mitchellh/vagrant#6048]
Hello, 

As I am writing a vagrant plugin, I am trying to hide some default variables inside the Vagrant file of the custom_box. 

```
$ cat ~./vagrant.d/boxes/test_box/0/myplugin/Vagrantfile
Vagrant.configure("2") do |config|
 config.ssh.insert_key = false
 config.my_key.value = 2
end
```

When I try to use the value of this inside the plugin code, say, `vm.cpu = config.my_key.value` 
then it doesn't pick this value up.

But instead, if I have the `config.my_key.value` set to 2, in the real Vagrantfile , 
then the code does pick this and use it for `vm.cpu`.

So, I am not able to set the default behavior of the box - instead forced to repeat everything in the real Vagrant file.

Could you kindly explain why this might be the case?

(It looks to me that, Vagrantfile is not mMerging these new variables.)

**Comment by VinothRavi-V** [comment]
I see the reason! Here is an output log as a vm is being provisioned...

"in real vagrantfile    "
Bringing machine 'vm13' up with 'myplugin' provider...
==> vm13:  -- MachineName: abcVM
==> vm13:  -- MachineIP: 192.168.10.1
"from Box's vagrant file test1"            # Printed value


So the Vagrant box file is not even parsed by the time the virtual machine starts to clone from the real Vagrantfile! 
So any provisioning that is hidden in the vagrant box's vagrantfile becomes useful because they are executed after the box is cloned!

Can anyone confirm that this is the intended behaviour?

**Comment by sethvargo** [comment]
@VinothRavi-V 

When you package the box, are you using the `--vagrantfile` option? You might also find this interesting reading: http://docs.vagrantup.com/v2/vagrantfile/index.html#load-order

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a _new_ issue. Thanks!

**Comment by vinodhfrisco** [comment]
Hey, thanks for the response, I actually did a hack to read the Vagrantfile contents in the extended plugin's clone.rb ... cheers, thanks.
