### ISSUE TITLE
Vagrant Up Hangs on Windows 8.1

### ISSUE THREAD

**Issue by admsen** [mitchellh/vagrant#6053]
Is Windows 8.1 a supported platform for Vagrant?  When I run vagrant up, the process hangs on this line:

Progress: 100% (Rate: 2001k/s, Estimated time remaining: --:--:--)

I've tried using VirtualBox and Hyper-V.  Vagrant hangs with both providers.

**Comment by PatOShea** [comment]
I'm using 8.1 Pro without issue. Do you have [debug logs](http://docs.vagrantup.com/v2/other/debugging.html) to help identity where it's hanging?

**Comment by sethvargo** [comment]
Hi @admsen 

Can you please share your complete Vagrantfile and then gist the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html) and paste the link here? Thanks!

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a _new_ issue and share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?
