### ISSUE TITLE
Support loading logging settings from a separate configuration files

### ISSUE THREAD

**Issue by electrofelix** [mitchellh/vagrant#6054]
It would be very useful for debugging with plugins if vagrant was capable of loading logging settings from a separate configuration file for log4r.

Simple use case would be

1. enabling info logging on vagrant
2. debug on vagrant-libvirt 
3. ignore all other plugins

Ignoring all others and only having info on the vagrant logging would help narrow down issues within plugins where more detail may be needed without being spammed with so much logging it's difficult to trace what is happening.

I suggest a separate file because by the time Vagrantfile has been read, in many cases the default levels of many of the logging channels have already been set based on whether '--debug' has been given on VAGRANT_LOG='...' was set. This means that if you then wish to change log level on a parent to include all such logs, log4r doesn't automatically change the log level on the children, although it will inherit the parent level at creation. Resulting in something like the following as a work around:

    logger = Log4r::Logger.new('vagrant')
    logger.outputters = Log4r::Outputter.stderr
    logger.level = Log4r::INFO
    Log4r::Logger::Repository.instance.loggers.each do |fullname, clog|
      next if not fullname =~ /#{logger.name + Log4r::Log4rConfig::LoggerPathDelimiter}/
      clog.level = logger.level
    end
    logger = Log4r::Logger.new('vagrant_libvirt')
    logger.outputters = Log4r::Outputter.stderr
    logger.level = Log4r::DEBUG
    Log4r::Logger::Repository.instance.loggers.each do |fullname, clog|
      next if not fullname =~ /#{logger.name + Log4r::Log4rConfig::LoggerPathDelimiter}/
      clog.level = logger.level
    end
    logger = nil

**Comment by electrofelix** [comment]
I've refined this a little further to use the following when debugging:

    def enable_logging(channel, level = Log4r::INFO, recursive = false)
      logger = Log4r::Logger.new(channel)
      logger.outputters = Log4r::Outputter.stderr
      logger.level = level
      # !!<var> is a hack to check if boolean true in ruby
      if !!recursive
        Log4r::Logger::Repository.instance.loggers.each do |fullname, log|
          next if not fullname =~ /#{logger.name + Log4r::Log4rConfig::LoggerPathDelimiter}/
          log.level = logger.level
        end
      end
      # and release the resources since no longer required once we've configured it.
      logger = nil
    end
    
    enable_logging('vagrant')
    enable_logging('vagrant_libvirt', Log4r::DEBUG, true)

May look to add a patch to pick up a log4r.config.{yaml,yml} file automatically under the same paths as vagrant looks for Vagrantfile's to merge and pick the one with the highest precedence, using the same override order.

Would such a mechanism be accepted?

**Comment by sethvargo** [comment]
Hi @electrofelix 

Thank you for opening an issue. This sounds like a good idea, but I'm not sure we would want to have this in Vagrant core (at least not immediately). I would recommend making this a Vagrant plugin (http://docs.vagrantup.com/v2/plugins/development-basics.html) first, and then if there is a lot of traction, we can move it into Vagrant core :smile:. Thanks!

**Comment by electrofelix** [comment]
The reason I recommended that this be added to the core, because late loading via a plugin will miss the ability to control logging levels in a consistent manner and so result in a code that is more complex than is necessary to apply a very simply logging configuration in order to correctly control the log level on both child and parent channels. This is because it would need to ensure the configuration is applied starting with parents first and then children and apply the levels recursively to ensure full capture.

> I suggest a separate file because by the time Vagrantfile has been read, in many cases the default
> levels of many of the logging channels have already been set based on whether '--debug' has been
> given on VAGRANT_LOG='...' was set. This means that if you then wish to change log level on a parent
> to include all such logs, log4r doesn't automatically change the log level on the children, although it will
> inherit the parent level at creation.

So this will also miss all the early logging events in vagrant and any other plugins loaded before it. Really seems like this can only be correctly and sanely implemented either within Vagrant or log4r itself.
