### ISSUE TITLE
Private ssh key problem windows 8.1 host ubuntu guest

### ISSUE THREAD

**Issue by vaske** [mitchellh/vagrant#6058]
Hi there I'm running into several issues last 48 hours. The last one is really specific and can not solve it so far.

On Vagrant I want to pull some code from my git repo and use my own key not Vagrant's insecure, like

```
config.ssh.private_key_path = "C:/Users/Vaske/.ssh/id_rsa"
config.ssh.forward_agent = true
```
 
My `id_rsa` have pass phrase.

Currently what I get in console when I perform `vagrant provision --debug` is

```
RSA key fingerprint is fc:59:dc:76:21:2a:cf:ca:cb:ee:8a:50:9d:31:69:81.
Are you sure you want to continue connecting (yes/no)?
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
# ...
```

**Comment by sethvargo** [comment]
Hi @vaske 

I think you _just_ want to enable SSH forwarding, not set the private key. The private key is what Vagrant uses to connect to the machine. The forward_agent will send your keys along with SSH so you can connect in the VM.

What happens if you remote the `config.ssh.private_key_path` config, but keep the `config.ssh.forward_agent`?

**Comment by vaske** [comment]
@sethvargo hey I tried that but that didn't help, after a day staring into it and trying sever work around, I officially left idea to set it up on Windows...

**Comment by mitchellh** [comment]
I believe this is fixed with later versions of net-ssh. I tried your exact Vagrantfile with Ubuntu and evreything worked. If this turns out to not be the case, please open a new issue after 1.8 is released. Thanks!

**Comment by vaske** [comment]
@mitchellh sounds good.
