### ISSUE TITLE
VirtualBox + Bridged interfaces - Status: Unknown ones?

### ISSUE THREAD

**Issue by MJPA** [mitchellh/vagrant#6061]
Not sure if this is down to updating to Windows 10 or VirtualBox 5.0 (or both, or neither!)...

Starting VMs now, I have a choice for the adaptor to bridge to yet I only have 1 that is actually up.

The VirtualBox driver only removes adapters if they have "Status: Down" - is there a reason for that? or is "Status: Unknown" a new thing?

Would it be safer to only include adapters that are "Status: Up" instead?

**Comment by mitchellh** [comment]
Fixed. Good catch thanks!
