### ISSUE TITLE
Add remove API to config.vm.provision type: "docker"

### ISSUE THREAD

**Issue by defender** [mitchellh/vagrant#6062]
Hi

We need to get ability to rm -f specified container before we are running container. Add new API remove
Use-case :

We want to replace content of our container. So will run vagrant provision provision-with XXX. Vagrant docker plugin will verify if args are changed, in our case we are not changing args -> so container will be not cleanup & rerun again. We stay with old content :(

Thanks.

**Comment by sethvargo** [comment]
Hi @defender 

Thank you for opening an issue. What kind of containers are you running that need to change on each iteration?

**Comment by defender** [comment]
Tomcat that contains app war, but I want to be able to mount my war from windows , so from containers perspective no change but from content we have new war. I need to ability to remove container and run again with new compiled war


Sent from my Samsung device


-------- Original message --------

**Comment by defender** [comment]
Hi any news about this ?

**Comment by modius** [comment]
I have a similar problem.  I want to provision boot2docker with some additional utilities, including an nginx-proxy to enable the use of hostnames.  Ideally, i want to be able to `vagrant provision` and have the container set up revert to a predefined state.

I had a shell provisioner (simplified) doing:
```
  config.vm.provision "shell", inline: <<-SHELL
    # clean up containers prior to provisioning
    docker rm --force `docker ps -qa`
    # start nginx-proxy; https://github.com/jwilder/nginx-proxy
    docker run -d -p 80:80 -v '/var/run/docker.sock:/tmp/docker.sock:ro' --name docker-proxy jwilder/nginx-proxy
  SHELL
```

This appears to work just fine on OSX but fails on Windows; the shell provisioner doesn't appear to have Docker setup in its ENV. Having the option to clear out all containers would be great for re-setting the VM when provisioned.

**Comment by sethvargo** [comment]
Hi all,

The next version of Vagrant (currently unreleased) will detect if a newer version of the container is available and automatically restart and upgrade to the newer version https://github.com/mitchellh/vagrant/commit/d8c56be5105113d99a2c84e4ac944c22bc175f00. Thanks! 😄
