### ISSUE TITLE
chef_client ignores validation_client_name

### ISSUE THREAD

**Issue by clajoie** [mitchellh/vagrant#6063]
In Vagrant 1.7.4 the chef_client provisioner seems to ignore the validation_client_name attribute.

Here's my config

```
  config.vm.provision 'chef_client' do |chef|
    chef.chef_server_url = 'https://<hostname>/organizations/test'
    chef.validation_client_name = 'test-validator'
    chef.validation_key_path = '/<path>/test-validator.pem'
    chef.delete_node = true
    chef.delete_client = true
    chef.add_recipe 'apache2'
  end
```

When bring up the host here's the error I get from the provisioner

```
==> default: Server Response:
==> default: ----------------
==> default: Failed to authenticate as 'chef-validator'. Ensure that your node_name and client key are correct.
==> default: 
==> default: 
==> default: Relevant Config Settings:
==> default: -------------------------
==> default: chef_server_url         "https://<host>/organizations/test"
==> default: 
==> default: validation_client_name  "chef-validator"
==> default: 
==> default: validation_key          "/tmp/vagrant-chef/validation.pem"
```

Note that it's using the wrong client name.

**Comment by sethvargo** [comment]
Hi @clajoie 

Can you please share your complete Vagrantfile? I just used the `validation_client_name` yesterday and it worked fine with a custom value.

**Comment by clajoie** [comment]
This was my fault.  It's related to another issue I'll report next related to option merging.  I had some chef_client privisioner setting in my ~/.vagrant.d/Vagrantfile.

Thanks Seth
