### ISSUE TITLE
chef_client provisioner not merging values as expected

### ISSUE THREAD

**Issue by clajoie** [mitchellh/vagrant#6066]
I'm using Vangrant 1.7.4.  I'm trying to keep the Vagrant file I'm including with my Chef cookbook as environmentally-agnostic as I can.  So, I'd prefer to put this in the Vagrantfile in my cookbook:

```
  config.vm.provision 'chef_client' do |chef|
    chef.add_recipe 'foo'
  end
```

and this in my ~/.vangrant.d/Vagrantfile
```
  config.vm.provision 'chef_client' do |chef|
    chef.chef_server_url = 'https://chef.example.com'
    chef.validation_client_name = 'test-validator'
    chef.validation_key_path = '/path/to/test-validator.pem'
    chef.delete_node = true
    chef.delete_client = true
  end
```

What I saw when I tried this (and what led to #6063) was that only the settings in ~/.vagrant.d/Vagrantfile were used.

What I would like is for the provisioner attributes to get merged.  I had assumed the behavior would simply be that the Vagrantfiles higher up in the search path would override those lower in the path.  But any merge logic would be okay, for my use case, as long as it was documented.

Let me be clear, I'm not suggesting this is a bug.  I don't see any documentation that suggests this would work the way I was thinking.  I had just made an assumption based on behavior in other areas.  So, please consider this a feature request.

**Comment by clajoie** [comment]
Hey Seth, any further thoughts on this?

**Comment by sethvargo** [comment]
Hi @clajoie 

This is a much larger issue around provisioner configuration merging, and unfortaunately requires a very large refactor. Given this doesn't seem like a very wide-spread use case, I'm going to say that we are not going to implement this ourselves. We would, however, gladly review a PR for this. Sorry and thanks! 😦
