### ISSUE TITLE
Use Linked Clones with VMWare boxes

### ISSUE THREAD

**Issue by keenbrowne** [mitchellh/vagrant#6067]
As described in Vagrant's VMWare box documentation:
https://docs.vagrantup.com/v2/vmware/boxes.html

Linked Clones would especially help when working with Windows VMWare boxes which, when fully loaded with compilers and dependencies are tens of gigabytes in size.

**Comment by mitchellh** [comment]
This is done. Next version of VMware does this automatically.

**Comment by PrahlM93** [comment]
@mitchellh, I updated Vagrant and it still seems to be doing full clones. Here is my Vagrant version and list of installed plugins:
```
PS C:\> vagrant -v
Vagrant 1.8.1
PS C:\> vagrant plugin list
winrm-fs (0.2.3)
vagrant-share (1.1.5, system)
vagrant-vmware-workstation (4.0.5)
vagrant-winrm (0.7.0)
```
