### ISSUE TITLE
Vagrant Windows 10 Private Network

### ISSUE THREAD

**Issue by tidytrax** [mitchellh/vagrant#6069]
Vagrant does not work on windows 10 unless private network be disable!

beyond that works fine !!

**Comment by Unforgiven-wanda** [comment]
@tidytrax  Could you please expand your answer? After searching Google I still can't figure out how to do this.

**Comment by tidytrax** [comment]
VagrantFile
comment any network configuration ( except port fowarding ) comment anyelse or
try it!
https://github.com/mitchellh/vagrant/issues/6068

Example,
#config.vm.network "private_network", ip: "192.168.50.12"

**Comment by Unforgiven-wanda** [comment]
@tidytrax Nope, still getting the same error. Here is my vagrant file
<img src="http://s29.postimg.org/u62vtq32v/image.jpg"/>

and the error I keep getting
<img src="http://s17.postimg.org/bmaocklkf/image.jpg"/>

**Comment by Ajar-Ajar** [comment]
I have the same exact problem.

**Comment by tidytrax** [comment]
OK, open virtual box, Shutdown from apci 
vagrant reload MACHINe

**Comment by Ajar-Ajar** [comment]
Say what?
What is apci?

**Comment by Unforgiven-wanda** [comment]
@Ajar-Ajar Just open VirtualBox, if your box is up and running -> right-click -> shutdown -> APCI something.

Tried it myself, still no luck. Thanks for taking the time anyway tidytrax.

**Comment by tidytrax** [comment]
And tried to up? not work?

Vbox 5 + Vagranta 1.7.4

**Comment by Unforgiven-wanda** [comment]
@tidytrax "Vbox 5 + Vagranta 1.7.4" ==> Yes.
I tried this https://www.virtualbox.org/ticket/14040 too. The box keeps waiting for Network interface to no avail.

I think we'll just have to wait for Oracle to patch this up. In the meantime, I'll go back to Wamp or Mamp personnaly. I'll keep monitoring these issues though, in case something comes up.

**Comment by tidytrax** [comment]
Another try that solve for me also was run powershell as administrator
cd C:\Users\you
vagrant up box

You can also try add new box just for test if that runs ok!

**Comment by mitchellh** [comment]
When machine states change, it is 100% a VirtualBox issue up to this point. Please try reinstalling VirtualBox. Sorry!

**Comment by hramdhani** [comment]
Still not working after reinstall virtual box to version 5.0.10
![issue](https://cloud.githubusercontent.com/assets/15197090/11834534/06cd0406-a400-11e5-818d-448689fabcde.png)

**Comment by johnnyborg** [comment]
This problem is related to VirtualBox (see @mitchellh above you). However this fix is quite easy (i've encountered it several times already). 
 
1. Uninstall VirtualBox
2. Reboot (i believe this is necessary for the network stack)
3. Run the MSI installer package with the following argument: `-msiparams NETWORKTYPE=NDIS5`

When you open the virtualbox through the GUI you'll get a detailed error message. With the error message you're able te resolve (google) it. 
**As mentioned in the error output of Vagrant.**

**Comment by cyberz** [comment]
I have the same problem with private network and it was solved after add netmask in configuration like this:
config.vm.network "private_network", ip: "192.168.1.123", netmask: "255.255.0.0"

**Comment by rrzaripov** [comment]
@hramdhani Are you trying to start stopped VM manually? This give you more explanation on error. Possible need to install [Extension Pack](http://download.virtualbox.org/virtualbox/5.0.10/Oracle_VM_VirtualBox_Extension_Pack-5.0.10-104061.vbox-extpack)?

**Comment by fairfaisal** [comment]
config.vm.network "private_network", ip: "192.168.1.123", netmask: "255.255.0.0" 
i did same and it's work
