### ISSUE TITLE
Vagrant not showing network interface after upgrade to Windows 10

### ISSUE THREAD

**Issue by diegofersan** [mitchellh/vagrant#6076]
I am having this issue after upgrading to Windows 10.

 INFO interface: info: Available bridged network interfac
 INFO interface: info: ==> default: Available bridged net
==> default: Available bridged network interfaces:
 INFO interface: ask: What interface should the network b
 INFO interface: ask:     default: What interface should
    default: What interface should the network bridge to?

**Comment by najawa** [comment]
I have the same issue:
![image](https://cloud.githubusercontent.com/assets/7543490/9139886/c574583e-3cf2-11e5-85fc-92bbb4567628.png)

**Comment by diegofersan** [comment]
@najawa, try to download last virtualbox version and run windows cmd as admin.
You can see more here: http://migre.me/r5scd

I hope this helps you.

**Comment by desertknight** [comment]
i have latest version, but problem still exists

**Comment by klmdb** [comment]
+1

**Comment by mitchellh** [comment]
This apparently is caused by VirtualBox not liking the WIndows upgrade. To fix I've heard you can reinstall VBox and restart. Sorry!

**Comment by nathan-fiscaletti** [comment]
This is still an issue on Windows 10. Running CMD as administrator didn't fix it, Upgrading VB didn't fix it, uninstalling, re-installing and restarting didn't fix it either, nor did any combination of those.
