### ISSUE TITLE
CFEngine provisioner reporting false permissions errror

### ISSUE THREAD

**Issue by darkn3rd** [mitchellh/vagrant#6077]
**SUMMARY**: Using the Vagrant file below, when I do a `vagrant provision`, I get a failure, but when I do the same command as root, I do not get a failure.

The Vagrantfile:

``` Ruby
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box      = "chef/centos-6.6" # Get Debian Wheezy From Somewhere
  config.vm.hostname = "centos6box"      # Give System a Hostname
  config.vm.provision :cfengine do |cf|
    cf.am_policy_hub = true
    cf.mode = :bootstrap
    cf.run_file = "../../bundlesofjoy/scriptbox.cf"
  end
end
```

**ACTUAL RESULTS**:  

```
INFO ssh: Execute: /var/cfengine/bin/cf-agent -KI -f /tmp/vagrant-cfengine-file (sudo=true)
DEBUG ssh: stdout:    error: File /tmp/vagrant-cfengine-file (owner 500) is writable by others (security exception)

 INFO interface: info:    error: File /tmp/vagrant-cfengine-file (owner 500) is writable by others (security exception)

 INFO interface: info:    error: File /tmp/vagrant-cfengine-file (owner 500) is writable by others (security exception)

   error: File /tmp/vagrant-cfengine-file (owner 500) is writable by others (security exception)
DEBUG ssh: Exit status: 1
```

**EXPECTED RESULTS**:  As I can do the same exact command, `/var/cfengine/bin/cf-agent -KI -f /tmp/vagrant-cfengine-file` manually and not have an error, I expect that vagrant provision would work correctly.

**FURTHER DETAILS**:
Looking into this further, see if I can get any insight.

Below is the sample CFEngine file I was using.

``` cf3
body common control
{
  bundlesequence => { "scriptbox" };
  inputs => { "$(sys.libdir)/stdlib.cf" };
}

bundle agent scriptbox
{
  vars:
      debian::
        "packages" slist => { "dash", "bash", "ksh", "tcsh", "gawk", "perl", "python", "php5-cli", "ruby", "tcl8.5"};
      redhat::
        "packages" slist => { "dash", "bash", "ksh", "tcsh", "gawk", "perl", "python", "php-cli", "ruby", "tcl"};
  packages:
      "$(packages)"
      package_policy => "addupdate",
      package_method => generic;
}
```

**Comment by darkn3rd** [comment]
There may be another issue or two issues.  I may be indeed getting  a false positive, or I have not been able to reproduce the issue as root.  I need to work on explicit steps to reproduce the expected behavior as root vs. what I am seeing in vagrant on the host.  If there is indeed an error showing up, then there's a bug in the code around `cf.run_file`, which is not setting the permissions correctly.

**Comment by FlorianHeigl** [comment]
umask maybe?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by chrisroberts** [comment]
I was referring to the original issue and subsequent comment around needing to better reproduce the issue :)
