### ISSUE TITLE
Vagrant commands are slow on my machine

### ISSUE THREAD

**Issue by oniric85** [mitchellh/vagrant#6079]
Hi all,
I don't know if it's just me but when I run any (and I mean any) Vagrant command on my machine (16GB RAM, i7 4710MQ, SSD) the command takes a lot of time. Even vagrant help takes at least 3s to finish while vagrant ssh takes 10s. I'm running Windows 8.1. What can I do to help debug the situation?
Thanks a lot.

**Comment by oniric85** [comment]
Missing information: I'm using Vagrant 1.7.4 but I noticed the problem even on previous versions.

**Comment by sethvargo** [comment]
Hi @oniric85 

How long does `vagrant --version` take?

**Comment by sethvargo** [comment]
And what is the output of `vagrant plugin list`?

**Comment by flexiblefactory** [comment]
even `vagrant --version` takes about 2 seconds

**Comment by oniric85** [comment]
I've tried running `vagrant --version`. Here is the timing using git bash. Speed is similar with cmd or powershell though.

```
$ time vagrant --version
Vagrant 1.7.4

real    0m1.047s
user    0m0.000s
sys     0m0.203s
```

Here is also `vagrant plugin list` output with timing too:

```
$ time vagrant plugin list
vagrant-hostsupdater (0.0.11)
vagrant-multi-putty (1.4.4)
vagrant-share (1.1.4, system)
vagrant-vbguest (0.10.0)

real    0m1.938s
user    0m0.000s
sys     0m0.203s
```

**Comment by ferventcoder** [comment]
I'm seeing something really similar to this on a particular 2012 machine. I've never run into it before.

**Comment by ferventcoder** [comment]
Everywhere else I use vagrant is super snappy.

**Comment by ferventcoder** [comment]
NOTES:
Same version of vagrant installed (1.6.5).

From a fast machine (Win 7 SP1):
~~~
C:\Users\rob> Measure-Command {vagrant.exe status}
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 15
Ticks             : 10157466
TotalDays         : 1.17563263888889E-05
TotalHours        : 0.000282151833333333
TotalMinutes      : 0.01692911
TotalSeconds      : 1.0157466
TotalMilliseconds : 1015.7466
~~~

From a slower machine (Windows 2012R2 Std)  :
~~~
PS C:\Windows\system32> measure-command {vagrant.exe status }
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 110
Ticks             : 51109587
TotalDays         : 5.91546145833333E-05
TotalHours        : 0.00141971075
TotalMinutes      : 0.085182645
TotalSeconds      : 5.1109587
TotalMilliseconds : 5110.9587
~~~

**Comment by ferventcoder** [comment]
I'll try to get more specifics from procmon. I'm seeing most of the time being spent in ruby loading files.

**Comment by ferventcoder** [comment]
I will upgrade and see if it is still happening.

**Comment by ferventcoder** [comment]
Vagrant 1.7.4, it's still clocking at 2s. Even cheating the path search just to execute the command.

~~~
PS C:\> Measure-Command {C:\HashiCorp\Vagrant\bin\vagrant.exe status}
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 2
Milliseconds      : 7
Ticks             : 20077044
TotalDays         : 2.32373194444444E-05
TotalHours        : 0.000557695666666667
TotalMinutes      : 0.03346174
TotalSeconds      : 2.0077044
TotalMilliseconds : 2007.7044
~~~

**Comment by ferventcoder** [comment]
This is not blocking me at all. Just wanted to provide some feedback.

**Comment by qzole** [comment]
I too have this problem.
Fresh install of Vagrant version 1.7.4, no additional plugins.
Both with my home laptop running Windows 10 and with my work laptop running Windows 7.
It's not a showstopper, but it is annoying.

Timing on my home laptop (work laptop produces similar results):
```
> time vagrant --help
...
real    0m 1.37s
user    0m 0.01s
sys     0m 0.00s
```

**Comment by mitchellh** [comment]
I have a feeling this is just an underlying Ruby issue on the newer versions of Windows. They probably won't accept a bug without a much smaller repro case, but I find it highly unlikely that OS to OS Vagrant is changing performance characteristics this much since we're using Ruby's abstractions everywhere.

Unless we can get a concrete reasoning for this, I'm going to have to close. Sorry!

**Comment by ferventcoder** [comment]
No worries. Any movement towards 2.1.7?

**Comment by mitchellh** [comment]
@ferventcoder The next version of Vagrant will run on Ruby 2.2.3 :)

**Comment by ferventcoder** [comment]
Even better
