### ISSUE TITLE
Windows 7 not installing 1.7.3 and 1.7.4 properly

### ISSUE THREAD

**Issue by firefly4268** [mitchellh/vagrant#6081]
I could be mistaken in this being a bug, but when I run the installation packages for vagrant 1.7.3 and 1.7.4 they say they install properly but there is no vagrant.exe or vagrant.bat located at C:\HashiCorp\vagrant\bin after installation and restart, in fact that file is empty. 

It does place a vagrant.bat at C:\HashiCorp\vagrant\embedded\gems\bin , however changing my path to point to  C:\HashiCorp\vagrant\embedded\gems\bin\vagrant.bat and restarting does not allow my computer to pick up the change. 

 I just switched back to the 1.7.1 vagrant and Virtualbox 4.3 combo since that works.

**Comment by sethvargo** [comment]
Hi @firefly4268 

I don't have access to Windows 7, but I just tried Windows 8, 10, and server 2012 and Vagrant is installing correctly. Do you have any anti-virus software that would prevent it from installing?

**Comment by firefly4268** [comment]
Thank you, you are correct, FireAmp quarantined both the vagrant executable for 1.7.3 and 1.7.4, I will find a way to override that.
![capture](https://cloud.githubusercontent.com/assets/13630215/9181680/e0d1f976-3f6b-11e5-996b-a0473dc28462.PNG)
