### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication on vagrant provision

### ISSUE THREAD

**Issue by mdunbavan** [mitchellh/vagrant#6082]
When trying vagrant provision I am getting the error:

```
Guest-specific operations were attempted on a machine that is not ready for guest communication on vagrant provision
```

Please can someone tell me whats going wrong here?

Here is what i am using:

- Vagrant 1.7.3
- And I am using homestead with laravel virtualbox.

I did a debug and this is what came out of it:

```
 INFO interface: error: Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
 INFO interface: Machine: error-exit ["Vagrant::Errors::MachineGuestNotReady", "Guest-specific operations were attempted on a machine that is not\nready for guest communication. This should not happen and a bug\nshould be reported."]
```

This error almost happened overnight.

**Comment by sethvargo** [comment]
Hi @mdunbavan 

Can you please share your complete Vagrantfile, gist the complete output in debug mode and paste a link here, and report the version of VirtualBox you are using please?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a _new_ issue and include your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks! :smile:

**Comment by RafaelPlantard** [comment]
My environment is have a homestead to work with Laravel, but I'm using Vagrant Box, so I have this problem, the solution that I found was:

Works for me:

`vagrant reload --provision`

Inside the folder Homestead.
