### ISSUE TITLE
Sending SIGINT twice does not exit immediately since v1.7.3

### ISSUE THREAD

**Issue by CharlieC3** [mitchellh/vagrant#6085]
Ever since Vagrant 1.7.3, sending the SIGINT to a running Vagrant process does not cause it to "exit immediately". Sending it once displays the `Waiting for cleanup before exiting...` message. Prior to 1.7.2, sending it a second time would display `Exiting immediately, without cleanup!`.

However since 1.7.3, sending the SIGINT more than once does not force Vagrant to stop. It will continue running its process until cleanup has finished (which may be minutes depending on the process).

**Comment by mitchellh** [comment]
Dup of #6248. I know that one is newer but there is more discussion there.
