### ISSUE TITLE
Warning: Connection timeout. Retrying... - ubuntu/trusty* boxes

### ISSUE THREAD

**Issue by vlad6085** [mitchellh/vagrant#6087]
When i'm trying use any box <b>ubuntu/trusty*</b> i got this:
> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty32'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty32' is up to date...
==> default: Setting the name of the VM: namivam_default_1438737430150_93449
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...

It happens as x32 as x64 boxes.
But <b>hashicorp/precise32</b> is working ok.

Is there any way to fix it?

#### My Environment:
> Linux Mint 17.2 Rafaela (x64)
> virtualbox-5.0_5.0.0-101573~Ubuntu~trusty_amd64
> vagrant_1.7.4_x86_64

If i can provide any info - let me know.

**Comment by sethvargo** [comment]
Hi @vlad6085 

Please ask these kinds of questions on the Vagrant mailing list. Thanks! :smile:
