### ISSUE TITLE
vagrant box add error

### ISSUE THREAD

**Issue by peirancao** [mitchellh/vagrant#6089]
```
G:\env\debian810>vagrant box add debian810 file:///g:\hc-download
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'debian810' (v0) for provider:
    box: Unpacking necessary files from: file:///g:/hc-download
    box: Progress: 100% (Rate: 31.4M/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar.EXE: Error opening archive: gzip decompression failed
```

**Comment by peirancao** [comment]
Vagrant 1.7.4
Oracle VM VirtualBox 5.0.0
windows 10 pro

**Comment by sethvargo** [comment]
Hi @peirancao 

Thank you for opening an issue. This looks like an issue with that specific box. Vagrant tries to un-gzip the file and that compression is failing from the bsdtar library. What happens when you try to decompess the file manually?

**Comment by peirancao** [comment]
G:\>bsdtar -xf virtualbox.box
bsdtar: Error opening archive: gzip decompression failed

**Comment by sethvargo** [comment]
@peirancao thank you.

Unfortunately that means this is not an issue with Vagrant. There is something wrong with that box format. Vagrant just runs the bsdtar command to try an extract the box. Where did you get the box from? Could you please share your Vagrantfile?

**Comment by peirancao** [comment]
@sethvargo 
may be the debian box file is corrupted.
I use the ubuntu box file it's work!

**Comment by qingjiuzhubei** [comment]
im try use homestead, and meet the problem too ~ the box url is : https://atlas.hashicorp.com/laravel/boxes/homestead/versions/0.4.4/providers/virtualbox.box
