### ISSUE TITLE
embedded/bin/file.exe Blocked by Various Enterprise Anti-Virus Clients

### ISSUE THREAD

**Issue by jon-whit** [mitchellh/vagrant#6091]
I am having an issue installing `Vagrant 1.7.4` because of common anti-virus blacklist rules. The file `embedded/bin/file.exe` cannot be copied into the installation directory because many enterprise anti-virus rules block any executable with a file name of "file". 

I have verified that this is the case with McAfee Enterprise, AVG, and Kasperskey. It would be ideal if this file was renamed to a less hazardous file name.

**Comment by sethvargo** [comment]
Hi @jon-whit 

Thank you for opening an issue. I just checked and you are right; this file is being created. Unfortunately it's coming from Ruby, so we don't have control over the naming. You might want to open an issue on the Ruby project or see if one already exists. Unfortunately we can't just "rename it" as nice as that would be. Sorry! :smile:
