### ISSUE TITLE
VirtualBox renaming error on Mac OSX Host machine

### ISSUE THREAD

**Issue by Kevinoh47** [mitchellh/vagrant#6092]
My host machine is OSX Yosemite. I had been running virtual box/vagrant for some time successfully, but now i am getting the errors described here:

http://getprotobox.com/docs/issues/vbox_rename
https://github.com/mitchellh/vagrant/issues/1809
https://github.com/mitchellh/vagrant/issues/2813

I have tried pretty much everything in the previous posts. I have run vagrant destroy, I have removed virtual box and upgraded to the latest virtual box. I have removed temporary machine folders from the virtual box folder list, i have deleted the vagrant virtual machine from the virtual box list. 

I am using the same unaltered vagrantfile that previously worked.  At this point though, I cannot get a successful vagrant machine built.

Thanks for any ideas.
Kevin

**Comment by Kevinoh47** [comment]
On a hunch I removed spaces from the name of the virtual box defined in the vagrant file.  This change allowed me to get past this error and get a virtual box set up. My guess is that it was changing the virtual box name, rather than removing the spaces, that was important, since the name had worked without issues previously.

**Comment by sethvargo** [comment]
Hi Kevin,

Did you recently upgrade Virtualbox? We have seen this when a user upgrades vbox sometimes.

**Comment by w2pc** [comment]
I get the same error after recently upgrading vbox. What is the solution?

**Comment by sethvargo** [comment]
Hi @Kevinoh47 

I'd like to follow up on this - it sounds like you were able to resolve the issue, correct?

@w2pc I am sorry this is causing you problems. Do you also have spaces in your box name? Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html). Thanks! :smile:

**Comment by w2pc** [comment]
I don't have spaces in the virtualbox name. But I don't get this issue anymore and forgot how I even got to that point.

**Comment by sethvargo** [comment]
Okay good to hear :smile: I'm glad the issue has been fixed. If it pops up again, please feel free to open a new issue
