### ISSUE TITLE
synced_folder_types unable to set :mount_options for :nfs 

### ISSUE THREAD

**Issue by Craige** [mitchellh/vagrant#6093]
With the introduction of the [synced_folder_type](https://github.com/mitchellh/vagrant/pull/5013#ref-issue-94952724) preference, it is not possible to specify :mount_options when specifying the :nfs sync type.

In the case where you previously had:

    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=777"] }

Under the new system, I would expect the following to work, but it does not:

    config.vm.allowed_synced_folder_types = [:nfs => { :mount_options => ["dmode=777","fmode=777"] }, :rsync]
    config.vm.synced_folder ".", "/var/www"

**Comment by mitchellh** [comment]
Yes, the synced folder type is just for specifying the default type, You still need to specify each option individually on the synced folders. We can do this, but we're still discussin ghow we want to expose it. For now, please copy them to each synced folder. Sorry!
