### ISSUE TITLE
VMware with vmxnet3 fails to configure interface on Solaris guest

### ISSUE THREAD

**Issue by dankimmel** [mitchellh/vagrant#6094]
When I try to boot my Solaris guest with the following Vagrant configuration:
```
Vagrant.configure(2) do |config|
  ...
  ["vmware_fusion", "vmware_workstation"].each do |vmware|
    config.vm.provider vmware do |v|
      v.vmx["ethernet0.virtualDev"] = "vmxnet3"
    end
  end
end
```
... I run into the following error:
```
==> default: Configuring network adapters within the VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sudo /sbin/ifconfig e1000g0 plumb

Stdout from the command:



Stderr from the command:

ifconfig: cannot plumb e1000g0: Could not open DLPI link
```
When I access the VM via its console, I can see only the vmxnet3 interface and no e1000g interfaces:
```
delphix@delphix:/export/home/delphix$ dladm show-link
LINK        CLASS     MTU    STATE    BRIDGE     OVER
vmxnet3s0   phys      1500   unknown  --         --
```
It seems like the command being issued should be dependent on the `v.vmx["ethernet0.virtualDev"]` configuration, rather than just assuming that all NICs are e1000g.

**Comment by tehranian** [comment]
I think there's a "device" kwarg that we can use to configure the NIC type: https://github.com/mitchellh/vagrant/blob/master/plugins/guests/solaris/config.rb#L14

**Comment by mitchellh** [comment]
I believe @tehranian is correct. This appears to be a config issue. An advanced one, for sure!
