### ISSUE TITLE
file:/// URL for base box with encoded characters creates SSH problem

### ISSUE THREAD

**Issue by efosler** [mitchellh/vagrant#6096]
I just had an odd interaction between a box that was locally cached and "vagrant ssh".

Environment:
Host: Mac OS X 10.10.4
Vagrant: 1.7.4
Guest: Ubuntu 14.04 LTS

Symptom:
```
$ vagrant ssh
percent_expand: unknown key %2
```

Hypothesis:
I had created a locally cached version of the base box and saved to a volume with a space in the name; I suspect that the URL encoding of %20 interacted badly with the ssh command, which gets the private key from the base box:

From Vagrantfile:

    config.vm.box = "file:///Volumes/Virtual%20Machines/mario-kaldi.box"

Relevant line from log file:

    INFO ssh: Invoking SSH: ssh ["vagrant@127.0.0.1", "-p", "2222", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentitiesOnly=yes", "-i", "/Users/[username]/.vagrant.d/boxes/file:-VAGRANTSLASH--VAGRANTSLASH--VAGRANTSLASH-Volumes-VAGRANTSLASH-Virtual%20Machines-VAGRANTSLASH-mario-kaldi.box/0/virtualbox/vagrant_private_key", "-o", "ForwardX11=yes", "-o", "ForwardX11Trusted=yes", "-o", "ForwardAgent=yes"]

In general, encoded URL characters will cause a problem for retrieving the private key.

**Comment by efosler** [comment]
Clearly, the workaround is to not use spaces in the URL for the moment.  But it was a bit hard to diagnose what was going on.

**Comment by sethvargo** [comment]
Hi @efosler 

What happens if you don't URL encode (i.e. just put the space in there and let Vagrant URL-encode it for you)?

**Comment by efosler** [comment]
IIRC, it broke the original build from the box because URLs can’t have spaces.  I can test it next time I destroy and rebuild from scratch.


On Aug 6, 2015, at 2:06 PM, Seth Vargo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @efosler<https://github.com/efosler>

What happens if you don't URL encode (i.e. just put the space in there and let Vagrant URL-encode it for you)?

**Comment by efosler** [comment]
I just rebuilt it; using spaces does work in Vagrant 1.7.4 (both build and ssh). It's been a while, but I think I had put the %20 in previously because the build hadn't worked with spaces in a previous version of vagrant, but I can't swear that this is the case.

**Comment by sethvargo** [comment]
@efosler okay - I think we fixed the whole "url encoding nonsense" in Vagrant 1.7.4, so I think that's the path moving forward. Sorry about the breaking change!
