### ISSUE TITLE
HTTPNotFound: No gems found matching "vagrant-vmware-fusion"

### ISSUE THREAD

**Issue by b-long** [mitchellh/vagrant#6097]
_From @b-long on July 29, 2015 14:40_

I ran into this issue while installing `vagrant-hostmanager`.  It appears to be fairly common (see tmatilai/vagrant-proxyconf#78 and berkshelf/vagrant-berkshelf#197 ).  If it helps, I was installing the  `vagrant-hostmanager` plugin right after installing Ruby and Vagrant.  Additionally, I had installed Vagrant before installing Ruby.  Other people in the other issues list simply re-running the installation of the plugin as a solution.  I've yet to test that, as I wanted to document the issue first.  Perhaps the real problem is something lower-level in Vagrant?

Information about my host : 
```shell
[root@VM-91555ebb-b039-4720-8c9e-876b83518667 ~]# cat /etc/*release |head -n 1
CentOS release 6.6 (Final)
[root@VM-91555ebb-b039-4720-8c9e-876b83518667 ~]# ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
[root@VM-91555ebb-b039-4720-8c9e-876b83518667 ~]# vagrant --version
Vagrant 1.6.5
```

Error : 
```shell
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Net::HTTPNotFound: No gems found matching "vagrant-vmware-fusion" "3.0.1" nil

```

_Copied from original issue: smdahlen/vagrant-hostmanager#158_

**Comment by b-long** [comment]
_From @seth-reeser on August 6, 2015 1:32_

Thank you for reporting this, however this is strictly an http issue. vagrant-vmware-fusion is not a dependancy of vagrant-hostmanager. Vagrant itself bootstraps every time a plugin is installed, and vagrant plugin install vagrant-vmware-fusion must have been installed at some point with your Vagrant instance - take a look at your ~/.vagrant.d/plugins.json. Your best bet is to open an issue over at https://github.com/mitchellh/vagrant

**Comment by sethvargo** [comment]
@b-long what are the contents of your plugins.json?

Please note that the latest version of Vagrant is 1.7.4 and it is not recommended that you install Vagrant as a gem.

**Comment by b-long** [comment]
@sethvargo Sorry, I'll edit the original issue text.  I actually install vagrant like this : 

`yum -y install https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.rpm`

The output above was from a giant shell / puppet installation of mine.  I must have been tired writing that issue, and didn't realize how confusing I was making the description sound.  I was trying to add the context around Ruby because I'm not as familiar with the Vagrant internals, and thought that might play a part in to root cause.  Immediately after vagrant is installed, the following runs : 

`vagrant plugin install vagrant-hostmanager` , which is where the error is being thrown.

**Comment by sethvargo** [comment]
@b-long 

Can you try deleting the `~/.vagrant.d` directory and then re-installing Vagrant please?

**Comment by tknerr** [comment]
Having the same thing every now and then.

Since it uses bundler for installing the plugins under the hood, can we configure the bundler settings somehow?

I have this in my `~/.bundle/config` but it seems not to be respected by vagrant:
```
BUNDLE_RETRY: 3
```

In general the `bundle install --retry <times>` option seems appropriate to me in order to fix this. 

What do you think?

**Comment by jantman** [comment]
I'm getting this issue intermittently in Travis CI tests against a Vagrant plugin...

**Comment by mitchellh** [comment]
Hey @tknerr that is a great idea. I'm going to add that internally. That should fix this.

**Comment by tknerr** [comment]
:+1: @mitchellh - btw seeing the "1.8" milestone label gets me a bit excited... :)

**Comment by mitchellh** [comment]
Done, retry is 3 by default now.
