### ISSUE TITLE
Vagrant installer for Solaris?

### ISSUE THREAD

**Issue by nmrony** [mitchellh/vagrant#6099]
We need to use Vagrant and Solaris as host for it. But there is no installer for Solaris. @mitchellh Do you have any plan of releasing vagrant installer for Solaris?

**Comment by sethvargo** [comment]
Hi @nmrony 

As mentioned [here](https://github.com/mitchellh/vagrant/pull/2078#issuecomment-23456643):

> There isn't an official Solaris installer and I'm not sure what the Solaris userbase is like anymore, so I'm not sure it is worth officially supporting in core yet.

I would recommend asking on the Vagrant mailing list to see if other Solaris users have made packages or have ways of installing Vagrant from source - https://groups.google.com/forum/#!forum/vagrant-up :smile:
