### ISSUE TITLE
Can I remotely control a Virtualbox using vagrant?

### ISSUE THREAD

**Issue by nmrony** [mitchellh/vagrant#6100]
My boxes are on remote machine and I can not install vagrant on that host machine. Is there any plugin or workaround so that we can remotely control virtual boxes using vagrant without installing it in host?

**Comment by sethvargo** [comment]
Hi @nmrony 

To the best of my knowledge, there is no way to control Virtualbox remotely. Vagrant works by issuing CLI commands to the Virtualbox client, so it must be installed on the same system and have permissions to execute those commands.

It may be possible to write some kind of HTTP API on top of Virtualbox that mirrors the CLI, but that is not something we plan to add to Vagrant core. Sorry!

**Comment by nmrony** [comment]
@sethvargo Thanks
