### ISSUE TITLE
DHCP leases file for the vmnet device 'vmnet8' could not be found.

### ISSUE THREAD

**Issue by ira-forman** [mitchellh/vagrant#6101]
```
C:\Users\IBM_ADMIN\Desktop\Integration Testing\Vagrant\romeo>vagrant up
Bringing machine 'csn' up with 'vmware_workstation' provider...
==> csn: Cloning VMware VM: 'chef/centos-6.6'. This can take some time...
==> csn: Checking if box 'chef/centos-6.6' is up to date...
==> csn: Verifying vmnet devices are healthy...
==> csn: Preparing network adapters...
==> csn: Starting the VMware VM...
==> csn: Waiting for machine to boot. This may take a few minutes...
The DHCP leases file for the vmnet device 'vmnet8' could
not be found.

 Vagrant requires this file to find the IP address
given by DHCP to your machine. Please report this as a bug along
with log output.
```

@sethvargo edit - moved debug log to gist: https://gist.github.com/sethvargo/880e4fdbd52008984f01

**Comment by sethvargo** [comment]
Hi @ira-forman 

- What version of the Vagrant VMware Workstation plugin are you using?
- What version of VMware Workstation are you using?
- What is the output of `vagrant plugin list`?

**Comment by ira-forman** [comment]
I am using VMware Workstation 11.

C:\Users\IBM_ADMIN>vagrant plugin list
vagrant-share (1.1.4, system)
vagrant-vmware-workstation (3.2.11)

**Comment by sethvargo** [comment]
Hi @ira-forman 

Interesting. We typically see this whenever there was something that went awry during the VMware Workstation installation. Could you please try uninstalling and re-installing VMware Workstation? Don't forget to restart your computer as well, since VMware needs to load kernel extensions.

**Comment by ira-forman** [comment]
That seems to have worked.
Thank you for your prompt action.

**Comment by sethvargo** [comment]
Hi @ira-forman 

Great! I'm glad things are working. I'm going to close this issue, but we can continue discussion if needed.
