### ISSUE TITLE
Failing to copy over authorized_keys on vagrant up Linux host FreeBSD guest

### ISSUE THREAD

**Issue by Momus** [mitchellh/vagrant#6104]
After 'vagrant up' process errors out with:
```bash
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

sed -i '/^.*ssh-rsa VERY_LONG_STRING_HERE== vagrant insecure public key.*$/d' ~/.ssh/authorized_keys

Stdout from the command:

Stderr from the command:

sed: 1: "/home/vagrant/.ssh/auth ...": invalid command code v
````

This is because BSD sed used the -i option differently than GNU sed. The -i option is not part of the [POSIX specification](http://pubs.opengroup.org/onlinepubs/009604599/utilities/sed.html).  However, there are [many possible fixes](http://unix.stackexchange.com/questions/92895/how-to-achieve-portability-with-sed-i-in-place-editing) that would render this command POSIX-compliant.

Searching the repository, there seem to be 21 lines where 'sed -i' is used.  Is that something that people would want to see fixed?  If so, I'll be glad to take a crack at it.

**Comment by sethvargo** [comment]
Hi @Momus 

Thank you for reporting this. We will take a look at fixing up all the `sed` usage to be OS-agnostic.
