### ISSUE TITLE
additional subcommands of the plugin command 

### ISSUE THREAD

**Issue by hbakhtiyor** [mitchellh/vagrant#6107]
Would be nice to add some additional subcommands (disable/enable or activate/deactivate) for the plugin
e.g.
`vagrant plugin enable/disable <name>` - Enable/disable plugin for some times, rather than comment/uncomment Vagrant files. It wouldn't be uninstalled.

**Comment by sethvargo** [comment]
Hi there,

I think we are going to rely on Vundler for this for now. We are going to revamp the plugin interface for 2.0, and this is something we will definitely keep in mind for then. Thanks! 😄
