### ISSUE TITLE
OpenBSD has no sudo anymore (5.8+)

### ISSUE THREAD

**Issue by double-p** [mitchellh/vagrant#6113]
With release 5.8 (November) there wont be any 'sudo' in the base system any longer.
One easy fix would be: do not use sudo if config.ssh.username is 'root' already.
Havent seen capabilities checks on a OS-version-number but a do-not-use sudo in hosts/bsd/cap/nfs.rb

I can hack something along that, just dont know where to put that best.

**Comment by mitchellh** [comment]
This can be configured with `config.ssh.sudo_command`
