### ISSUE TITLE
Still broken rsync-ing with Host MacOS, Vagrant, Chef-Solo, and Guest Windows

### ISSUE THREAD

**Issue by lonniev** [mitchellh/vagrant#6115]
See #4974 

The combination of MacOS, Vagrant, Chef-Solo, Windows still has, in Vagrant 1.7.4 and Chef 12.4.1, issues with rsync and Windows paths.

If I recall, it is the Windows Capabilities Rsync ruby code in core Vagrant that is responsible for getting this resolved.

```bash
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/lonniev/Vagrants/softlayer-windows-obeoteam/cookbooks/
Guest path: C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/Users/lonniev/.vagrant.d/insecure_private_key' --exclude .vagrant/ /Users/lonniev/Vagrants/softlayer-windows-obeoteam/cookbooks/ vagrant@255.255.255.255:C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks
Error: Warning: Permanently added '255.255.255.255' (RSA) to the list of known hosts.
cygwin warning:
  MS-DOS style path detected: C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks
  Preferred POSIX equivalent is: /cygdrive/c/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
rsync: change_dir#1 "/cygdrive/c/Users/vagrant//C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(631) [Receiver=3.1.0]
```

**Comment by sethvargo** [comment]
Hi @lonniev 

Can you please share your complete Vagrantfile?

**Comment by lonniev** [comment]
Sure, see https://gist.github.com/lonniev/ea4723b53583a2a9d52f

**Comment by deancsmith** [comment]
Hi @lonniev 

We use Mac OS X hosts (Vagrant 1.7.4), with Windows 2008R2 guests using rsync and, as per the ticket #4974, we us the workaround of defining the shared path prefixed with /cygdrive/.

```
config.vm.synced_folder ".", "/cygdrive/c/inetpub/wwwroot/", type: "rsync", rsync__exclude: [".git/"]
```

It would be good to not to have to include this workaround though.

**Comment by lonniev** [comment]
If I'm not mistaken, that works for folder syncing outside the provisioners' blocks. The issue I encounter is within the chef-solo's provisioning block. There, a new body of code joins the party. Overall, it is not just the cygwin path name differences but also the need to make the complete path for rsync before rsync runs.

I'm interested in @sethvargo's recommendation: he usually has good advice.

**Comment by lonniev** [comment]
I patched Vagrant 1.7.2 to resolve the lack of the mkdir -p before the rsync operation. I thought this would be in v1.7.4. Apparently, it is not. I'll try the patch shown for 1.7.4 and if it improves the situation I would reply to a "pull request" with a git pull request. (I won't push a pull request if not requested.)

![screenshot 2015-08-11 14 01 01](https://cloud.githubusercontent.com/assets/2193384/9209086/12326c28-4032-11e5-8971-3a8052ea1f08.png)

**Comment by sethvargo** [comment]
@lonniev I'm not sure how that patch changes things? The only thing that changes is the return value of the `rsync_pre` command. Is that the issue?

**Comment by lonniev** [comment]
I just tried it and it does not help. (My understanding is that it should make the complete/path/to/target for where rsync is supposed to write.) 

The error remains as follows with the DOS drive letter mashed in the path. Note that some rsyncs do succeed: those that specify the target as /target and which reference an existing directory.

rsync: change_dir#1 "/cygdrive/c/Users/vagrant//C:/vagrant-chef/f3c765f92a8356d41d4338281bc64a00/cookbooks" failed: No such file or directory (2)

**Comment by lonniev** [comment]
I gather the code in /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/provisioners/chef/provisioner/chef_solo.rb:

              # Remove drive letter if running on a windows host. This is a bit
              # of a hack but is the most portable way I can think of at the moment
              # to achieve this. Otherwise, Vagrant attempts to share at some crazy
              # path like /home/vagrant/c:/foo/bar
              remote_path = remote_path.gsub(/^[a-zA-Z]:/, "")
            end

Is where attention should turn.

**Comment by Y4Rv1K** [comment]
Similar issue with centOS, vagrant, vSphere and Windows 2008 R2 as guest. 

     There was an error when attempting to rsync a synced folder.
     Please inspect the error message below for more info.

     Host path: /home/y4rv1k/.berkshelf/vagrant-berkshelf/shelves/berkshelf20150814-6418-1c1gl40-sql2008/
    Guest path: /tmp/vagrant-chef/9651886957719b8f039a03fd6254807c/cookbooks
    Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o     StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i     '/home/y4rv1k/.vagrant.d/insecure_private_key' --exclude .vagrant/ /home/y4rv1k/.berkshelf/vagrant-    berkshelf/shelves/berkshelf20150814-6418-1c1gl40-sql2008/ vagrant@192.168.4.125:/tmp/vagrant-    chef/9651886957719b8f039a03fd6254807c/cookbooks
    Error: ssh: connect to host 192.168.4.125 port 22: Connection refused
    rsync: connection unexpectedly closed (0 bytes received so far) [sender]
    rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]

According logs: 

    Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o     StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i     '/home/y4rv1k/.vagrant.d/insecure_private_key' --exclude .vagrant/ /home/y4rv1k/.berkshelf/vagrant-    berkshelf/shelves/berkshelf20150814-6418-1c1gl40-sql2008/ vagrant@192.168.4.125:/tmp/vagrant-    chef/9651886957719b8f039a03fd6254807c/cookbooks
    Error: ssh: connect to host 192.168.4.125 port 22: Connection refused
    rsync: connection unexpectedly closed (0 bytes received so far) [sender]
    rsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]

I think that more configuration issue. Any idea? Install cyngwin? Change protocol?

**Comment by lonniev** [comment]
After injecting a little printf into chef_solo.rb

```bash
==> sl-oslc-tls: Installing Chef cookbooks with Librarian-Chef...
==> sl-oslc-tls: chef_solo.rb passing along remote_path C:/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e
==> sl-oslc-tls: chef_solo.rb passing along remote_path C:/vagrant-chef/b12b9f6bf5b75ebb5649f1944cab54bc
==> sl-oslc-tls: Rsyncing folder: /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/ => /vagrant
==> sl-oslc-tls: Rsyncing folder: /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/cookbooks/ => C:/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/cookbooks/
Guest path: C:/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/Users/lonniev/.vagrant.d/vagrants_at_sodius_id_rsa' --exclude .vagrant/ /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/cookbooks/ vagrant@184.173.75.57:C:/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks
Error: Warning: Permanently added '184.173.75.57' (RSA) to the list of known hosts.
cygwin warning:
  MS-DOS style path detected: C:/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks
  Preferred POSIX equivalent is: /cygdrive/c/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
rsync: change_dir#1 "/cygdrive/c/Users/vagrant//C:/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks" failed: No such file or directory (2)
```

Note that the remote path "passed along" by chef solo is in the "if" block and not in the "else" block. It is only in the "else" block where the crucial cleanup code is executed:

```ruby
              remote_path = remote_path.gsub(/^[a-zA-Z]:/, "")
```

So, to be confirmed, it appears that moving that substitution out of the "else" after the entire "if" statement may contribute to solving this long-running Windows rsync issue.

**Comment by lonniev** [comment]
We can't just gsub out the drive prefix, we have to swap in the "/cygdrive/C" prefix (where C is the captured actual drive letter). GNU rsync wants that form of path. This is better then. But, there remains the darn issue with rsync and mkdir.

```bash
==> sl-oslc-tls: Installing Chef cookbooks with Librarian-Chef...
==> sl-oslc-tls: chef_solo.rb passing along remote_path /cygdrive/C/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e
==> sl-oslc-tls: chef_solo.rb passing along remote_path /cygdrive/C/vagrant-chef/b12b9f6bf5b75ebb5649f1944cab54bc
==> sl-oslc-tls: Rsyncing folder: /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/ => /vagrant
==> sl-oslc-tls: Rsyncing folder: /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/cookbooks/ => /cygdrive/C/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks
==> sl-oslc-tls: Rsyncing folder: /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/roles/ => /cygdrive/C/vagrant-chef/b12b9f6bf5b75ebb5649f1944cab54bc/roles
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/roles/
Guest path: /cygdrive/C/vagrant-chef/b12b9f6bf5b75ebb5649f1944cab54bc/roles
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/Users/lonniev/.vagrant.d/vagrants_at_sodius_id_rsa' --exclude .vagrant/ /Users/lonniev/Vagrants/softlayer-windows-windchillrlia/roles/ vagrant@184.173.75.57:/cygdrive/C/vagrant-chef/b12b9f6bf5b75ebb5649f1944cab54bc/roles
Error: Warning: Permanently added '184.173.75.57' (RSA) to the list of known hosts.
rsync: mkdir "/cygdrive/C/vagrant-chef/b12b9f6bf5b75ebb5649f1944cab54bc/roles" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.0]
```

I need to check if the vagrant Capability handler for rsync uses the GNU mkdir or Windows' mkdir when told to "mkdir -p" for rsync before rsync is called.

(What a cluster-F.)

**Comment by lonniev** [comment]
Hmm, it seems very likely that there are apps with different pathname requirements in use here. The following monkey patch to chef_solo.rb works:

```ruby
            if type == :host
              # Get the expanded path that the host path points to
              local_path = File.expand_path(path, @machine.env.root_path)

              if File.exist?(local_path)
                # Path exists on the host, setup the remote path. We use
                # the MD5 of the local path so that it is predictable.
                key         = Digest::MD5.hexdigest(local_path)
                remote_path = "#{guest_provisioning_path}/#{key}"
              else
                @machine.ui.warn(I18n.t("vagrant.provisioners.chef.cookbook_folder_not_found_warning",
                                       path: local_path.to_s))
                next
              end

              @machine.communicate.tap do |comm|
                comm.execute( "mkdir #{remote_path}" )
              end

              remote_path = remote_path.gsub(/^([a-zA-Z]):/, '/cygdrive/\1')

              @machine.ui.warn( "chef_solo.rb passing along remote_path " + remote_path.to_s )
```

The idea here is that when the code creates the name of the target folder with a digest of the host's pathname, we know that the target directory doesn't yet exist -- but it will need to exist. Therefore, go ahead and ask the communicator for the machine to create it right now, not sometime later. However, the mkdir that gets called isn't the same mkdir that Cygwin rsync uses, it's some Windows one. So, we execute that mkdir with the original pathname before mangling the pathname for cygwin and rsync.

Sadly, this is all way too specific for Windows, Cygwin, and the assumption that the admin of the box image included an rsync that uses cygwin paths. One day, someone might make available an rsync app for Windows that can handle hetero-OS path formats without using crusty old cygwin.

**Comment by lonniev** [comment]
We (the community) could also hoist this mess out of chef_solo and the rsync capability and just give documentation advice that if you want to sync to Windows with rsync, your Vagrantfile has to include a shell provisioner block first that creates all necessary directory "mount points" for the chef solo stuff. Given that chef_solo is just Digest-ing the host pathnames, the shell provisioner block can do the same to create the right directories.

**Comment by lonniev** [comment]
Also, unsurprisingly, one mashed in fix busts code elsewhere. When the paths are cleaned up for rsync, they break chef_solo running later on the target. The generated solo.rb file has this kind of content:

```ruby
file_cache_path    "C:/chef/cache"
file_backup_path   "C:/chef/backup"
cookbook_path ["/cygdrive/C/vagrant-chef/5e5b4497aa57800c3fe732202ad0e04e/cookbooks"]
role_path "/cygdrive/C/vagrant-chef/b12b9f6bf5b75ebb5649f1944cab54bc/roles"
log_level :info
```

Here, the "/cygdrive/C" path prefixes are wrong because chef solo expects to find Windows style paths--or at least ones without the "cygdrive" cruft in them.

**Comment by lonniev** [comment]
That brings the focus back to the Guest::Windows::Cap::Rsync code. If it is only Windows' cygwin-encumbered rsync that has difficulties with pathnames and missing directories then it is just this code that should deal with it.

(Meanwhile, the issue above can be hacked around with a custom chef config file that sets the chef.role_path and chef.cookbook_path to something hardcoded like "c:/vagrant/roles" and "c:/vagrant/cookbooks" -- if one has already rsyched the host's "dot" directory to "c:/vagrant" on the target.

**Comment by lonniev** [comment]
And, working just in this Guest::Windows::Cap::Rsync code alone is not sufficient because the VagrantPlugins::SyncedFolderRsync::RsyncHelper code makes local copies of the values in the opts hash and passes to some code the local copies and to other code it passes the opts hash itself. Therefore, called code can't clean up the opts values for all users. rsync_pre can make the directories the right way but the code that calls the rsync command itself has already obtained the wrong value for the guest path.

**Comment by lonniev** [comment]
A working patch, involves editing the vagrant plugin files for chef_solo, windows guest, and windows rsync. I'll create a patch pull request from a modified v1.7.4 for this. It's a just a few lines of code here and there.

**Comment by lonniev** [comment]
https://github.com/mitchellh/vagrant/pull/6160

**Comment by mitchellh** [comment]
Thanks @lonniev! Closing.

**Comment by lonniev** [comment]
you’re welcome.

-- 
Lonnie VanZandt
303-900-3048

On 18 November 2015 at 21:55:50, Mitchell Hashimoto (notifications@github.com) wrote:

Thanks @lonniev! Closing.
