### ISSUE TITLE
Vagrant box add fails too late

### ISSUE THREAD

**Issue by amontalban** [mitchellh/vagrant#6119]
Hey guys,

I'm doing some tests with Packer and when adding a vagrant box that already exists it tries to import the box before checking if it exists (In my case this is a 7Gb box) so it would be great if it can fail earlier in the import process.

```
amontalban@devops:~/packer/roles/devserver-pkgs$ vagrant box add --name devserver devserver.domain.com_PKGS_20150809.box                                                                                                                   
==> box: Adding box 'devserver' (v0) for provider: 
    box: Downloading: file:///home/amontalban/packer/roles/devserver-pkgs/devserver.domain.com_PKGS_20150809.box
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.

Name: devserver
Provider: virtualbox
Version: 0
```

Thank you very much!

**Comment by sethvargo** [comment]
Hi @amontalban 

Unfortunately this is not possible. There is another closed issue with more explanation, but we need to download the entire box before we can decompress it and inspect it. Sorry about that. I know this can be frustrating, but we can't know the box metadata until after the box has been completely decompressed (which requires a complete download). 

Please let me know if you have any questions.
