### ISSUE TITLE
The host network interface could not be found on Windows 7 after VirtualBox 5 upgrade

### ISSUE THREAD

**Issue by lasselehtinen** [mitchellh/vagrant#6120]
Hi,

I decided to update my dev environment after the summer holidays. So I uninstalled working Vagrant and VirtualBox 4.x.x and installed Vagrant 1.7.4 and VirtualBox 5.0.0. I found lot of posts related to this same problem in Windows 10 and VirtualBox 5 but I am actually running Windows 7 64-bit. The [Windows 10 workaround](http://stackoverflow.com/a/31856846/4281265) does not do anything. I also tried running Vagrant as administrator. The same error happens with all existing Vagrant configurations I have, custom made, Laravel Homestead etc.

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'puphpet/centos65-x64' is up to date...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #5", "--ip", "192.168.56.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 204 of file VBoxManageHostonly.cpp
```

**Comment by spktklr** [comment]
Try the latest VirtualBox test build.
https://www.virtualbox.org/wiki/Testbuilds

**Comment by ozzyogkush** [comment]
I'm having this same issue - running virtualbox `5.0.2r102096` with latest virtualbox extensions, and vagrant 1.7.4. just installed today. running `vagrant up`, it pops up a UAC request window for VirtualBox asking for permission to run. Clicking "ok" then causes error output.

Each time I try, the number in the `VirtualBox Host-Only Ethernet Adapter #7` output increments. 

```
c:\Projects\my-project>vagrant up
Bringing machine 'db' up with 'virtualbox' provider...
Bringing machine 'web' up with 'virtualbox' provider...
==> db: Importing base box 'nrel/CentOS-6.5-x86_64'...
==> db: Matching MAC address for NAT networking...
==> db: Checking if box 'nrel/CentOS-6.5-x86_64' is up to date...
==> db: Setting the name of the VM: my-project_db_1440301108353_44730
==> db: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #7", "--ip", "10.11.22.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 204 of file
VBoxManageHostonly.cpp
```

**Comment by ozzyogkush** [comment]
Using the latest test build did seem to fix it for me though. Looks like 5.0.3 should be a good version for windows 7 users at least.

**Comment by Kimosabe** [comment]
I have the same issue with vagrant 1.7.4 and vbox 5.0.6 r103037

**Comment by bitzl** [comment]
I can confirm this issue for Vargrant 1.7.4 und 5.0.6 r103037 and Windows 10 64 Bit.

**Comment by DecodedMonkey** [comment]
Same issue. Vargrant 1.7.4 and VB 5.0.6 on Windows 10 64 Bit.

**Comment by kz** [comment]
I am experiencing this issue with Vagrant 1.7.4 and VirtualBox 5.0.8 r103449, attempting to run Laravel Homestead on Windows 10 64-bit.

**Comment by Kimosabe** [comment]
Can't reproduce with Vagrant 1.7.4 and vbox 5.0.10 r104061

**Comment by mitchellh** [comment]
VirtualBox bug, please just use the latest version as the comments say. Thanks!

**Comment by VikasBains** [comment]
Same issue with latest version of vagrant and virtual box.
D:\centos-test-server>vagrant version
Installed Version: 1.7.4
Latest Version: 1.7.4

You're running an up-to-date version of Vagrant!
AND
Virtual Box version = 5.0.10 r 104061
================
D:\centos-test-server>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'CentOS_6.6'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: centos-test-server_default_1448888774006_75878
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #6", "--ip", "192.168.33.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 205 of file VBoxManageHostonly.cpp
