### ISSUE TITLE
When I use vagrant in win10 the arrow button works fail

### ISSUE THREAD

**Issue by oska874** [mitchellh/vagrant#6121]
I use cmd or powershell in win10.WhenI use vagrant in win10 the arrow button works fail. I "vagrant ssh" log in ubuntu,and type command.Then I enter up/down/left/right buttons,the curse moves up/down/left/right,like this:
![screenclip](https://cloud.githubusercontent.com/assets/4536559/9173020/edfa6ea6-3fa9-11e5-9088-f1ef9f89847d.png)

Then I tried cygwin in win10.The arrow buttons works still wrong. Such as,I typed up,the screen shows "^[[A",enters "ctrl+c",shows "^C",like this:
![screenclip](https://cloud.githubusercontent.com/assets/4536559/9173059/2a097a36-3faa-11e5-8664-a05d987bf447.png)

And tab cannot complemented command ,it just add a tab as do in editors.
How to solve this?

**Comment by sethvargo** [comment]
Hi @quirkey 

Those are escape sequences. This is not a bug. Cygwin uses different terminal escape sequences.
