### ISSUE TITLE
On vagrant up : vagrant is trying to create an new vm always

### ISSUE THREAD

**Issue by Ansarpasha** [mitchellh/vagrant#6122]
From past 2 months vagrant up, reload and halt was working fine for me,

But yesterday when i tried vagrant up, i get below message

A VirtualBox machine with the name 'myBox' already exists.
Please use another name or delete the machine with the existing
name, and try again

Tried the below steps to fix the issue, but so far no luck

VBoxManage list vms

echo -n "uuid of myBox" > .vagrant/machines/default/virtualbox/id

vagrant up

Note/Observation : after running the vagrant up or vagrant status the id file is getting deleted from .vagrant/machines/default/virtualbox

**Comment by Ansarpasha** [comment]
Hey,
   Waiting for the reposne :(

Thanks
Ansar Pasha

**Comment by Ansarpasha** [comment]
Waiting for the response :(

**Comment by sethvargo** [comment]
Hi @Ansarpasha 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. This definitely seems like odd and unintended behavior. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html). Thanks! :smile:

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
