### ISSUE TITLE
No download links for the docs

### ISSUE THREAD

**Issue by pitchforks** [mitchellh/vagrant#6126]
I went to vagrant website and tried to find a download link for the documentation, so I could have an offline copy, but could not find any.

So far my options are to spider the site (which isn't really nice) or to clone the repo and try to build the docs myself (which is a bit overkill from an end user standpoint).

Would you mind providing a download link to a tarball containing just the docs on https://docs.vagrantup.com/v2/?

**Comment by sethvargo** [comment]
Hi @pitchforks 

The docs are all open source and in the website/docs folder of this repo. We do not have plans to publish tarballs of the docs at this time. Sorry! :smile:

**Comment by yveslaroche** [comment]
@pitchforks You could use https://kapeli.com/dash if you are on OS X or http://zealdocs.org/ on WIndows/Linux
