### ISSUE TITLE
"vagrant up" hangs on environment_unload hook

### ISSUE THREAD

**Issue by davepgreene** [mitchellh/vagrant#6127]
When I run ```vagrant up``` it hangs on ```INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000001009a5578>```. All provisioners run, ports are forwarded, and shared folders are set. However, the ```vagrant up``` run never finishes.

Log is in this gist: https://gist.github.com/davepgreene/4719fc4a9079c7b79368

I'm running Virtualbox 5 and Vagrant 1.7.4 on OSX 10.10.4 and I'm using the following plugins:

* vagrant-bindfs (0.4.2)
* vagrant-hostsupdater (0.0.11)
* vagrant-notify (0.4.0)
* vagrant-omnibus (1.4.1)
* vagrant-share (1.1.4, system)

What other information can I give to help troubleshoot?

**Comment by sethvargo** [comment]
Hi @davepgreene 

Are you able to reproduce this issue with no plugins installed?

**Comment by davepgreene** [comment]
Hi @sethvargo 

Looks like it was an issue in the vagrant-notify plugin. I'll repost on the plugin's issue tracker.

Thanks!
