### ISSUE TITLE
Error: Could not parse application options:

### ISSUE THREAD

**Issue by jeff1evesque** [mitchellh/vagrant#6128]
Recently, the [puppetlabs/centos-6.6-64-puppet](https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.6-64-puppet) box has recently upgraded puppet to `4.2.1` from `3.8.1`.  As a result, `vagrant up` from a Windows 7 host machine, generates the following error:

```bash
$ vagrant -v
Vagrant 1.7.4
$ cd web-projects/drupal-demonstration/
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
    default: vagrant-r10k: puppet_dir and/or puppetfile_path not set in config; not running
==> default: Importing base box 'puppetlabs/centos-6.6-64-puppet'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'puppetlabs/centos-6.6-64-puppet' is up to date...
==> default: Setting the name of the VM: drupal-demonstration_default_1439327008638_1084
    default: vagrant-r10k: puppet_dir and/or puppetfile_path not set in config; not running
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 => 6060 (adapter 1)
    default: 443 => 6161 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/Jeff/web-projects/drupal-demonstration
    default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => C:/Users/Jeff/web-projects/drupal-demonstration/puppet/manifests
==> default: Running provisioner: puppet...
==> default: Running Puppet with default.pp...
==> default: Error: Could not parse application options: invalid option: --manifestdir
The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.
```

My [`Vagrantfile`](https://github.com/jeff1evesque/drupal-demonstration/blob/b7e63a8223f44ffb147e5318383cdd5fa71c150c/Vagrantfile), [`default.pp`](https://github.com/jeff1evesque/drupal-demonstration/blob/2fec0fe49c1cbd8004c896c126b06622d0172064/puppet/manifests/default.pp), and [`ssl.pp`](https://github.com/jeff1evesque/drupal-demonstration/blob/a6acefd327a2763606fb3605d02624145d8a8698/puppet/manifests/ssl.pp) used to work without error, when I was implementing Vagrant `1.7.2`, and Puppet `3.8.1` (on guest machine).

**Note:** I upgraded to Vagrant 1.7.4 on the host machine, since the above error first occurred when implementing Vagrant 1.7.2.

**Comment by jeff1evesque** [comment]
The above error may have something to do with the `manifestdir` being [deprecated](https://github.com/mitchellh/vagrant/issues/3740) in vagrant 3.6.1, and finally [removed](https://github.com/mitchellh/vagrant/issues/5615) in vagrant 4.x.x.

**Comment by xraj** [comment]
Am I missing something? I thought the Puppet 4.x manifestdir issue was fixed in Vagrant 1.7.3?

**Comment by xraj** [comment]
I just went back and found issue #5615 which claimed the issue was fixed back in July.

**Comment by jeff1evesque** [comment]
@xraj, the overall issue does not pertain directly to #5615, possible a small suggestion. The overall issue has been stated, and can be reproduced given the originating [repository](https://github.com/jeff1evesque/drupal-demonstration).

**Comment by xraj** [comment]
The `Error: Could not parse application options: invalid option: --manifestdir` is definitely a Puppet 4.x issue that my read of #5615 would lead me to believe was solved. Further investigating reveals that it was solved by supporting environments; however, how it supposed to work still alludes me at the moment.

My current work around is to set `box_version = "1.0.1"` in my Vagrantfile for puppetlabs/centos-6.6 base boxes which still has Puppet 3.8.

**Comment by jeff1evesque** [comment]
I see `config.vm.box_version` forces which version of the vagrantbox, [puppetlabs/centos-6.6-64-puppet](https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.6-64-puppet) to use.  So, I implemented the suggested `config.vm.box_version = 1.0.0`, which provided me with puppet 3.7.4 on the guest Centos 6.6.  This suggested implementation did build on `vagrant up`, and avoided the `Error: Could not parse application options: invalid option: --manifestdir`.  However, it seems inconvenient to force an implementation of an older vagrantbox.

**Comment by mitchellh** [comment]
This should be fixed by #5991

**Comment by anadimisra** [comment]
This still occurs with Vagrant 1.9.2, puppet 4.5.1, Ubuntu 16.04

and the maze of issues linked here now is not helping, could we move a sort of workaround (if that is the norm) to GH page and link it here instead?

**Comment by christiansipola** [comment]
@anadimisra it seems to be working for me if puppet.environment_path and 
puppet.environment is set

**Comment by DaniloBNascimento** [comment]
I had this problem using the ubuntu / xenial64 box the solution was
Install the puppet-common package. I provisioned through shell its installation as below:

config.vm.provision "shell", path: "install-puppet.sh"

File content install-puppet.sh:

#!/bin/bash

cd /tmp
wget http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb
dpkg -i puppetlabs-release-pc1-xenial.deb
apt-get update
apt-get -y install puppet-common
echo "PATH=/opt/puppetlabs/bin:$PATH" >> /etc/bash.bashrc
echo "export PATH" >> /etc/bash.bashrc
export PATH=/opt/puppetlabs/bin:$PATH
