### ISSUE TITLE
vagrant up a Windows 10 box with VMware Fusion has problems with WinRM

### ISSUE THREAD

**Issue by StefanScherer** [mitchellh/vagrant#6131]
Host: OSX 10.10.4, Vagrant 1.7.4, VMware Fusion 7.1.2 with the following plugins:

```
$ vagrant plugin list
winrm-fs (0.2.2)
vagrant-multiprovider-snap (0.0.14)
vagrant-pristine (0.3.0)
vagrant-share (1.1.4, system)
vagrant-vmware-fusion (3.2.11)
```

I still encounter problems spinning up a Windows 10 Vagrant box created with the [boxcutter/windows](https://github.com/boxcutter/windows) repo with VMware Fusion on a Mac (`make vmware/eval-win10x64-enterprise`).

I did some testing with VirtualBox 5.0.0 in the meantime and fixed similar provisioning problem there by updating the Ruby gem winrm-fs to version 0.2.2 (see #6060).

Spinning up the box looks good, the VM starts, but at the beginning of the provisioning the following error message is shown:

```
$ vagrant up --provider vmware_fusion
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'windows_10'. This can take some time...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
```

After waiting some seconds and then running `vagrant provision` vagrant is able to connect via WinRM:

```
$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: provision.ps1 as c:\tmp\vagrant-shell.ps1
==> default: hello
```

There is no unusual long time to boot the VM, so there shouldn't be some kind of timeout there.
I have done the same with `VAGRANT_LOG=debug`.  You can find more details in this Gist:
https://gist.github.com/StefanScherer/f9f93c5b96d4ba5718ae

**Comment by StefanScherer** [comment]
Seems that the loop calling `vmrun getGuestIPAddress ...` should be more tolerant.

Interesting lines in the Gist of the `vagrant up`:

[L. 2233](https://gist.github.com/StefanScherer/f9f93c5b96d4ba5718ae#file-03-vagrant-up-provider-vmware_fusion-L2233) stdout: Error: The VMware Tools are not running in the virtual machine: /Users/stefan/code/win10/.vagrant/machines/default/vmware_fusion/4fa052b9-6817-4426-89ce-65d341b81688/packer-vmware-iso.vmx
[L. 2356](https://gist.github.com/StefanScherer/f9f93c5b96d4ba5718ae#file-03-vagrant-up-provider-vmware_fusion-L2356) stdout: Error: The VMware Tools are not running in the virtual machine: /Users/stefan/code/win10/.vagrant/machines/default/vmware_fusion/4fa052b9-6817-4426-89ce-65d341b81688/packer-vmware-iso.vmx
[L. 2620](https://gist.github.com/StefanScherer/f9f93c5b96d4ba5718ae#file-03-vagrant-up-provider-vmware_fusion-L2620) stdout: Error: The VMware Tools are not running in the virtual machine: /Users/stefan/code/win10/.vagrant/machines/default/vmware_fusion/4fa052b9-6817-4426-89ce-65d341b81688/packer-vmware-iso.vmx
[L. 2770](https://gist.github.com/StefanScherer/f9f93c5b96d4ba5718ae#file-03-vagrant-up-provider-vmware_fusion-L2770) stdout: Error: Unable to get the IP address
[L. 2923](https://gist.github.com/StefanScherer/f9f93c5b96d4ba5718ae#file-03-vagrant-up-provider-vmware_fusion-L2923) ERROR warden: Error occurred: The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.

In the Gist of the `vagrant provision`:

[L. 439](https://gist.github.com/StefanScherer/f9f93c5b96d4ba5718ae#file-04-vagrant-provision-L439)  INFO vmware_driver: vmrun getGuestIPAddress success: 192.168.254.139

So probably you have to wait a little longer until the vmrun returns a valid IP address.

**Comment by StefanScherer** [comment]
I have observed the VM while a `vagrant up` is creating and booting the VM for the first time.

```
Wed Aug 12 20:01:13 CEST 2015
Error: The VMware Tools are not running in the virtual machine: ./.vagrant/machines/default/vmware_fusion/7bcdd023-48ef-451c-877d-56705ac06394/packer-vmware-iso.vmx
Wed Aug 12 20:01:14 CEST 2015
Error: Unable to get the IP address
Wed Aug 12 20:01:15 CEST 2015
Error: Unable to get the IP address
Wed Aug 12 20:01:16 CEST 2015
Error: Unable to get the IP address
...
Wed Aug 12 20:01:44 CEST 2015
Error: Unable to get the IP address
Wed Aug 12 20:01:45 CEST 2015
192.168.254.133
```

So there is a gap of about 30 seconds in which `vmrun getGuestIPAddress packer.vmx` can't retrieve an IP address. Any ideas?

After a `vagrant reload` there is no such gap.

Perhaps this has something to do with the switch from the default network card while running the `packer build` to the [vmxnet3 card](https://github.com/boxcutter/windows/blob/master/tpl/vagrantfile-eval-win10x64-enterprise-ssh.tpl#L31) after packer had installed the VMware tools and Vagrant is able to boot the VM with the faster network card.

**Comment by StefanScherer** [comment]
No, also with the default network card there is the same gap on first boot.
My Win10 box has VMware Tools 9.9.3 installed.

It seems to me a problem with the VMware Tools or the Windows 10 support of VMware Fusion 7.1.2. But to make Vagrant more robust with these boxes I suggest to add a loop to retrieve the IP address.

Or is there a better way to fix this in the Win10 baseboxes?

**Comment by phinze** [comment]
Hey @StefanScherer,

Sorry for the trouble here. We do indeed have quite a bit of looping/retry logic around IP address retrieval, as we've found the behavior of the VMware tools can vary wildly from user to user.

We've made the IP address logic more and more robust as the Vagrant VMware plugin has mature and as we've had more reports like this.

In the latest version of the plugin, the IP address lookup logic is as follows: each "attempt" comprises (1) a query to the VMware tools via `vmrun getGuestIpAddress` and (2) a fallback to parsing the DHCP leases config. We retry this attempt up to 5 times, with a linear backoff.

What I can do is bump this up to 10 retries to see if that addresses the problem where `vagrant up` gives up too early. Unfortunately there's not much I can do about the actual time it takes to assign the IP address, as that's behavior at the VMware layer.

I'll follow up once the change has been made so you can give it a shot.

**Comment by phinze** [comment]
Okay @StefanScherer - just cut v3.2.12 - can you give that a try and let me know how it works for you?

**Comment by StefanScherer** [comment]
@phinze Thanks. Yes, I've tested both 3.2.12 and before and after 3.2.11 again.

3.2.11 always aborts:
```
$ vagrant up --provider vmware_fusion
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'windows_10'. This can take some time...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
```

3.2.12 works fine:
```
$ vagrant plugin update
Updating installed plugins...
Updated 'vagrant-vmware-fusion' to version '3.2.12'!

$ vagrant up --provider vmware_fusion
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'windows_10'. This can take some time...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 192.168.254.134:5985
    default: WinRM username: vagrant
    default: WinRM transport: plaintext
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 3389 => 3389
    default: -- 22 => 2222
    default: -- 5985 => 5985
==> default: Configuring network adapters within the VM...
==> default: Configuring secondary network adapters through VMware 
==> default: on Windows is not yet supported. You will need to manually
==> default: configure the network adapter.
==> default: Enabling and configuring shared folders...
    default: -- /Users/stefan/code/win10: /vagrant
==> default: Running provisioner: shell...
    default: Running: provision.ps1 as c:\tmp\vagrant-shell.ps1
==> default: hello
```

For all my tests I have undone my changes for #6137, but for provisioning I still had to install winrm-fs 0.2.2 (#6136).

**Comment by phinze** [comment]
@StefanScherer sounds good! Going to close this then - feel free to follow up if you have any further questions.

**Comment by carlskii** [comment]
I'm also seeing this issue: 

Vmware Fusion version: 8.0.0 (2985594)
Vmware plugin version:  4.0.1
Vagrant version: 1.7.4
