### ISSUE TITLE
Error in multi-vm env (`network': wrong number of arguments)

### ISSUE THREAD

**Issue by HWDexperte** [mitchellh/vagrant#6138]
Currently i'm setting up an Multi-Vm environment to test some software.

But as i'm creating static IP's for my boxes like described [here](http://friendsofvagrant.github.io/v1/docs/multivm.html#communication_between_vms) and [here](http://friendsofvagrant.github.io/v1/docs/host_only_networking.html), i'm getting [this](https://gist.github.com/HWDexperte/a05b5072713a6794ccbf) error.

```
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/kernel_v2/config/vm.rb:226
in `network': wrong number of arguments (2 for 1) (ArgumentError)
```

My Vagrantfile looks like [this](https://gist.github.com/HWDexperte/c3f7251a3b11418b16fe) and i'm using Vagrant version 1.7.1 on Debian

**Comment by HWDexperte** [comment]
Okay, changed to

```ruby
es1_cfg.vm.network "private_network", ip: "192.168.1.10"
```

it looks like to work now.

**Comment by sethvargo** [comment]
Hi @HWDexperte 

Sorry for the confusion. The documentation sites you listed are not the official Vagrant documentation and appear to be generated by a third-party. The official documentation is https://docs.vagrantup.com. Sorry about the confusion!
