### ISSUE TITLE
xfreerdp instead of rdesktop on centos 7 host

### ISSUE THREAD

**Issue by mihai-satmarean** [mitchellh/vagrant#6140]
accessing windows 8 + using Centos 7 and rdp is not working due to rdeskop not being distributed with the release.
Installing or compiling rdesktop does really help, as windows wants secure connection and rdesktop seems not to be able to handle.

Xfreerdp is provided and it works when invoked.

Please consider making it an option to select which rdp client shall be used.

Thank you!

**Comment by nikelmwann** [comment]
Until this is dealt with, I've been using xfreerdp successfully by modifying `rdp.rb` in `/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/hosts/linux/cap/` like so: https://gist.github.com/nikelmwann/43a51c26df2709779ccb

Ugly, but it works!

**Comment by StefanScherer** [comment]
@nikelmwann cool! Do you want to make a PR out of it?

**Comment by nikelmwann** [comment]
@StefanScherer I'd like to submit one today. I'd assume it'd be best to check for `xfreerdp` first, but leave `rdesktop` as a fallback. Other than that I'll make sure the error message that's displayed if neither is available mentions `xfreerdp` too.
