### ISSUE TITLE
url shortener option for "vagrant share"

### ISSUE THREAD

**Issue by steros** [mitchellh/vagrant#6141]
It would be nice to have an url shortener option for "vagrant share" so you don't have to input long urls like: "roary-hippopotamus-23432.vagrantshare.com" but instead just get "goo.gl/AearS" or something.
Especially on mobile devices this is a big plus.

Call "vagrant share --shortUrl" -> get:
==> default: Your Vagrant Share is running! Name: roary-hippopotamus-23432
==> default: URL: http://roary-hippopotamus-23432.vagrantshare.com
==> default: short URL: http://goo.gl/AearS

**Comment by sethvargo** [comment]
Hi @steros 

Thank you for opening an issue. We have found that the compound URL's are typically easier to remember, but I don't think short URLs are a bad idea as an option. We would gladly review a Pull Request for this functionality, but I don't think this is something we will implement ourselves. :smile:

**Comment by steros** [comment]
Yes easier to remember maybe (for English speaking users) but still a pain in the ass to type on a mobile phone.
Anyway...you wouldn't mind to point out the place in code where I would add this feature? That would help a lot!
