### ISSUE TITLE
Unable to assign static IP to additional network interface

### ISSUE THREAD

**Issue by hesco** [mitchellh/vagrant#6142]
This issue has frustrated me for days over the last couple of months.  

I have a script which can reliably rebuild a vagrant base box from a virtual box in a few minutes.  I have a Virtual Box built from the corporate blessed image, corporate blessed patches, the Guest Additions and a puppet agent.  For the next iteration I need to add a second network interface to support multi-vagrant-box integration test environments.  

Using the VirtualBox gui, I have added an additional NIC.  I've tried multiple options, but seem to think that I want either an Internal Network or a Generic Driver for this application.  By launching the vm in the VirtualBox gui, and accessing the console, I configured /etc/sysconfig/network/ifcfg-eth1 to provide a static address, and blew away the /etc/udev/rules.d/70-persistent-net.rules file, trusting that udev would rebuild it as necessary.  

`vagrant up` throws these errors:
```
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1 2> /dev/null

Stdout from the command:

    eth1      device: Intel Corporation 82540EM Gigabit Ethernet Controller (rev 02)
Starting DHCP4 client on eth1. . . . . . . .
    eth1      DHCP4 continues in background

Stderr from the command:
```

Even so, `vagrant ssh` permits be to shell out to my rebuilt base box which now finally reveals an eth1 with a static address (`ifconfig`), the one set in the Virtual Box's ifcfg-eth1.  But it fails to override that static assignment with the one requested in my Vagrantfile which includes:

```
Vagrant.configure(2) do |config|
  config.vm.box = "sles11sp3_pe_agent_v0.10.0"
  config.vm.hostname = 'v0-10-0-basebox.vagrant.local'
  config.vm.network "public_network", type: "dhcp", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.network "private_network", ip: "192.168.50.101"
  config.ssh.private_key_path = '.ssh/insecure_key'
end
```

And `ifconfig -a` (and the VirtualBox gui) now list five interfaces.  

Can anyone please suggest a way forward to the promised land here?

I want to be able to use the syntax documented for assigning static IP's on a private network so that vm's in a multi-vagrant-box environment can communicate with one another.  

Also, is there any way in Vagrantfile to explicitly instruct which nic should get which configuration?  

Thanks,
-- Hugh Esco

__UPDATE__

OK, I did this:

```
rm /etc/sysconfig/network/ifcfg-eth1 
vim /etc/udev/rules.d/70-persistent-net.rules
```
leaving only the definition for eth0 this time.  

`ifconfig` on the resultant vagrant box is now providing me a eth1 stanza, with a mac address, but with no IP, not even the one I requested in the Vagrantfile.  And `vagrant up` is still giving me dhcp errors when it tries to configure the eth1 interface.  I'm getting close, but am still unable to assign a static address from the Vagrantfile.  Can anyone please provide some help?

FYI --

```
$ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.4
```

__ADDITIONAL UPDATE__

I'm about to drop back and punt here, by writing a shell script to provision eth1 using ifconfig.  Not an ideal solution in my mind, but one which will get me back in motion.  Been at this, trying various combinations now for roughly four hours already today.  The guidance provided by 'Up and Running' seems to be woefully out of date (see error below), and the online documentation does not seem much more helpful.  I came back here to start reading the source code to see how this should really be done.  

```
* Network type 'hostonly' is invalid. Please use a valid network type.
```
OK.  Enough of the guesswork.  Found this in the code, used to validate the network type 
```
valid_network_types = [:forwarded_port, :private_network, :public_network]
```

**Comment by hesco** [comment]
Tracing the error message back through the code led me to:
./plugins/providers/virtualbox/action/network.rb 

and the type attribute is set to the :static symbol in only three methods:  bridged_network_config, hostonly_config and intnet_config.  

hostonly_config seems to be referenced only three places in the vagrant code base, once to name the above mentioned method, and the other two times as a source for parameters fed to methods whose names suggest some role with dhcp.  

The string 'intnet_config' is used only once in the vagrant code base, to name the method mentioned above.  

I read somewhere that the authors of vagrant found 'hostonly' confusing, and it would seem that with version v1.7.4-20-gcd25b82 of the project, that it has been nearly completely deprecated.  However it exists still for the virtualbox provider, and whether I use :private_network or :public_network, it always seems to result in an effort to configure my interface using a non-existent DHCP server and the ignoring of the static IP I am attempting to set for the NIC.  

I hope someone who understands the intent of vagrant development far better than I can untangle this soon, as for now I am left with ignoring the documentation and using an ugly-hack of shell provisioners to manually configure the interface, while telling my C-I server to ignore the fatal errors generated by `vagrant up` by manually invoking it for each vm in the environment and manually invoking provision for each vm as well.  

What started out as a support request is looking to me very much like a BUG in vagrant, now.

**Comment by hesco** [comment]
And in fact, it is a show stopping BUG.  

When `vagrant up` encounters errors getting a lease from a non-existent DHCP server, it bombs out immediately with a failing exit code.  Consequently it does not proceed to mount its shared file systems, nor to run its provisioners.  And attempts to provision the running and ssh-accessible vagrant box manually with `vagrant provision` results in failures related to the missing file system mounts.  

I have to conclude that this is a CRITICAL BUG and hope this ticket might soon gain the attention of the vagrant development team and some guidance on a work-around while I await an upgrade which might resolve this issue.  

In the mean time I suspect I will have to roll back to a previous version of vagrant in order to proceed with my work for my employer.  

-- Hugh Esco

**Comment by phinze** [comment]
Hi @hesco - sorry you're having trouble here.

I've just tested Vagrant 1.7.4 using a `Vagrantfile` like this:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  # also tested this box to check redhat-family guests
  # config.vm.box = "chef/centos-7.0"
  config.vm.hostname = 'v0-10-0-basebox.vagrant.local'
  config.vm.network "public_network", type: "dhcp", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.network "private_network", ip: "192.168.50.101"
end
```

In both instances, the guest gets a second interface with a bridged network IP and a third with a statically assigned IP.

It sounds like you might be adding NICs using the GUI? Vagrant takes care of this automatically for you, so it's possible that your GUI modifications are what's causing the problem. If you let Vagrant do the NIC management, does that change the behavior at all?

It's difficult to determine the cause of the issue without being able to see the script you use for basebox generation, but from my testing the issue does seem to be specific to the box you're generating.

If you still believe there's a bug in Vagrant and can give me steps to reproduce, I'd be happy to investigate further.

**Comment by hesco** [comment]
phinze:

Thanks for taking a look at this.  I rolled back to a previous version of our internal blessed image, but am still seeing spurious NIC's and show-stopping errors.  I will rebuild a version with a single NIC and test again.  In the mean time I tried the same tests with three other images, offered by you and downloaded from https://atlas.hashicorp.com/suse/boxes.  I'm curious to know if you can reproduce my experience with the suse/sles11sp3 base box.  

I have tried the following four tests -- 

  config.vm.box = "sles11sp3_employer_pe_agent_v0.9.1"
  config.vm.box = "hashicorp/precise64"
  config.vm.box = "chef/centos-7.0"
  config.vm.box = "suse/sles11sp3"

Only the ubuntu worked thoroughly.  After a small amount of time spent reviewing the code and tracing the execution I am pretty convinced that some issue may exist with the SLES, perhaps RHEL paths.  

```
Vagrant.configure(2) do |config|
  # this failed:
  # config.vm.box = "sles11sp3_employer_pe_agent_v0.9.1"
  # this worked:
  # config.vm.box = "hashicorp/precise64"
  # this failed, strange nic's created, failed to configure:
  # config.vm.box = "chef/centos-7.0"
  # this failed, nic's created, but failed to configurei, long time-out:
  config.vm.box = "suse/sles11sp3"
  config.vm.hostname = 'v0-10-0-basebox.vagrant.local'
  config.vm.network "public_network", type: "dhcp", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.network "private_network", ip: "192.168.50.101"
end
```

FAILED:  with the base box I built with the company blessed SLES images:

```
==> default: Importing base box 'sles11sp3_employer_blessed_pe_agent_v0.9.1'...

==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1 2> /dev/null

Stdout from the command:

Stderr from the command:

sandbox:test_vagrant escoh$ vagrant ssh -c "/sbin/ifconfig -a"
eth0      Link encap:Ethernet  HWaddr 08:00:27:5D:8C:82
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:882 errors:0 dropped:0 overruns:0 frame:0
          TX packets:670 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:103093 (100.6 Kb)  TX bytes:87041 (85.0 Kb)

eth4      Link encap:Ethernet  HWaddr 08:00:27:CB:E2:97
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

eth5      Link encap:Ethernet  HWaddr 08:00:27:F2:07:47
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:2 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:100 (100.0 b)  TX bytes:100 (100.0 b)

```

FAILED: with the centos image

```
==> default: Successfully added box 'chef/centos-7.0' (v1.0.0) for 'virtualbox'!

==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup enp0s8

Stdout from the command:

Stderr from the command:

Error: Timeout 90 sec expired.

sandbox:test_vagrant escoh$ vagrant ssh -c "/sbin/ifconfig -a"
vagrant@127.0.0.1's password:
enp0s3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fec3:36f0  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:c3:36:f0  txqueuelen 1000  (Ethernet)
        RX packets 640  bytes 72978 (71.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 417  bytes 61935 (60.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a00:27ff:fe30:aca6  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:30:ac:a6  txqueuelen 1000  (Ethernet)
        RX packets 27  bytes 2596 (2.5 KiB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 87  bytes 14242 (13.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s9: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::a00:27ff:fed4:6f34  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:d4:6f:34  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 2764 (2.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 0  (Local Loopback)
        RX packets 2  bytes 140 (140.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2  bytes 140 (140.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Connection to 127.0.0.1 closed.
```

FAILED: suse/sles11sp3

```
==> default: Importing base box 'suse/sles11sp3'...

    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

sandbox:test_vagrant escoh$ vagrant ssh -c "/sbin/ifconfig -a"
Password:
eth0      Link encap:Ethernet  HWaddr 00:16:3E:28:18:18
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::216:3eff:fe28:1818/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:33066 errors:0 dropped:0 overruns:0 frame:0
          TX packets:21572 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5888880 (5.6 Mb)  TX bytes:5526847 (5.2 Mb)

eth1      Link encap:Ethernet  HWaddr 08:00:27:A0:DB:B5
          inet6 addr: fe80::a00:27ff:fea0:dbb5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:55 errors:0 dropped:8 overruns:0 frame:0
          TX packets:16 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:5252 (5.1 Kb)  TX bytes:3384 (3.3 Kb)

eth2      Link encap:Ethernet  HWaddr 08:00:27:3E:8B:21
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:6 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:380 (380.0 b)  TX bytes:380 (380.0 b)

Connection to 127.0.0.1 closed.

```

**Comment by mitchellh** [comment]
Vagrant network auto-configuration is supposed to be work for the majority of cases. In some cases especially with multiple nics, Vagrant just isn't smart enough to properly configure them. Sometimes it is, sometimes it isn't. 

In these cases, since it is an advanced case, we ask users to use `auto_config: false` and just manually configure the interfaces. Please see the docs here (bottom) for how to do that: https://docs.vagrantup.com/v2/networking/private_network.html

Sorry for the subpar response, but fixing advanced networking cases takes up a disproportionate amount of time compared to bugs/enhancements that could affect many more. If you're able to open a PR to help improve Vagrant, we'd appreciate that as well. Thanks!

**Comment by bgblanch** [comment]
Hey @mitchellh, I tried the `auto_config: false` but am getting stuck after the insecure key replacement.  Vagrant isn't able to reconnect.  If I comment out the third nic it works but I need the third nic for my project.  I've included the relevant portions.

`rac.vm.box = "boxcutter/centos71"
rac.vm.hostname = "rac1.pkdev.com"
rac.vm.network "forwarded_port", guest: "1521", host: "1521"
rac.vm.network "private_network", ip: "192.168.10.25", auto_config:     "false"    
rac.vm.network "private_network", ip: "172.16.100.11", auto_config:     "false"    
rac.vm.network "private_network", ip: "192.168.10.27", auto_config    : "false"
...
config.vm.provision "shell", run: "always", inline: "ifconfig enp0s    8 192.168.10.25 netmask  255.255.255.0 up"
config.vm.provision "shell", run: "always", inline: "ifconfig enp0s    9 172.16.100.11 netmask  255.255.255.0 up"
config.vm.provision "shell", run: "always", inline: "ifconfig enp0    s10 192.168.10.27 netmask  255.255.255.0 up"`

**Comment by keltik85** [comment]
For anyone finding this issue through Google-Fu:

This is my `Vagrantfile` for an Arch-Linux Cluster, that configures static IPs on bridged interface public network:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..5).each do |i|
    config.vm.define "arch-#{i}" do |arch_i|
      arch_i.vm.box = "terrywang/archlinux"
      arch_i.vm.synced_folder "./vagrant_data_host_#{i}", "/vagrant_data_guest"
     
      # Assign the static IP
      arch_i.vm.network "public_network", bridge: "wlp2s0", ip: "192.168.178.10#{i}"
      arch_i.vm.hostname = "arch-#{i}"

      arch_i.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "256"
        vb.name = "arch-#{i}"
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
      end
      

      # Configure the proper routes, because vagrant is not intelligent enough to do it
      # (vagrant sees two nics and chooses the ethernet connection to be the right one)
      arch_i.vm.provision "shell", run: "always", inline: "ip route del 192.168.178.0/24 dev eth0 proto kernel scope link src 192.168.178.10#{i}"
      arch_i.vm.provision "shell", run: "always", inline: "ip route change 192.168.178.0/24 dev enp0s8 proto kernel scope link src 192.168.178.10#{i} metric 203"

    end
   end
end
```
