### ISSUE TITLE
Allow for seemless mode when gui = true

### ISSUE THREAD

**Issue by rothgar** [mitchellh/vagrant#6144]
The gui can be enabled in the vagrant file with

```ruby
config.vm.provider "virtualbox" do |v|
  v.gui = true
end
```
I'd like it if there were also an option for seemless mode similar to 

```ruby
config.vm.provider "virtualbox" do |v|
  v.gui = true
  v.seemless = true
end
```
If the VM only runs a single gui app this could allow for just that application to be streamed to the host computers display rather than the whole desktop window.
 
This would require the image to have the necessary guest additions but the functionallity is available in all of the major providers

 - Virtualbox (seemless)
 - VMware (unity)
 - Parallels (coherence)

I don't have links to all of the documentation to enable these features for each provider but I know for virtualbox it's just a matter of sending --seemless to the virtualbox command at runtime.

**Comment by mitchellh** [comment]
For all providers, this should be possible through the advanced customization functions (i..e. VirtualBox's customize method and VMware's VMX controls). Otherwise, this sounds like a good plugin, but not something we're interested in pursuing on our own right now.

Thanks!
