### ISSUE TITLE
Vagrant on windows 10. Protocol error

### ISSUE THREAD

**Issue by anorudes** [mitchellh/vagrant#6146]
Cannot create folder with long path in vagrant on windows 10. It is necessary for "npm install" Error: Protocol error

Screenshot: http://take.ms/T8eBB

**Comment by sethvargo** [comment]
Hi @anorudes 

Thank you for opening an issue.

This is a duplicate of https://github.com/mitchellh/vagrant/issues/4815. Please see the discussion on that ticket for more information! :smile:
