### ISSUE TITLE
BUG: git works with problem in synced-folder

### ISSUE THREAD

**Issue by billypon** [mitchellh/vagrant#6147]
When I exec "git clone" in synced-folder, I got "error: could not commit config file .git/config".
But it works fine before I up upgrade vagrant and virtualbox.

Here's my environment:
host os: win7 x64
guest os:ubuntu 12.04 x32 with VBoxGuestAdditions 5.0.0
vbox: 5.0.0
ruby: 1.9.3
git: 2.4.5

**Comment by billypon** [comment]
And before I upgrade, "npm install" will got "UNKNOWN, symlink" error.
Now I use "npm install --no-bin-link".
Is there another way to solve it?

**Comment by sethvargo** [comment]
Hi @billypon 

Thank you for opening an issue, but there is not enough information here to diagnose this issue. Can you elaborate a bit more please? Where are you running the git command? Is it in the host or guest? Can you please share the complete Vagrant output in debug mode? Can you please share a Vagrantfile? Thanks!

**Comment by billypon** [comment]
I'm running the git command in guest os.

I ran "vagrant up --debug > vagrant.log", but I only got this:
https://drive.google.com/open?id=0B0vynHsskQAgRWZtU0drTDk2Sm8

Here my Vagrantfile:
https://drive.google.com/open?id=0B0vynHsskQAgVnV5MW1DbHdxMmM

**Comment by billypon** [comment]
I have replied

**Comment by gawbul** [comment]
@sethvargo I'm having the same issue. I'm trying to provision a Vagrant VM on Windows but when I get to the `git clone` step I get the following error message:

```
Cloning into 'code'
error: could not commit config file /home/vagrant/repos/code/.git/config
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm using `git 2.4.6`. Strangely this works when using `git 1.9.1`, so I'm assuming git is doing something differently and this isn't necessarily a bug with Vagrant? Any help should be appreciated though :smile:

**Comment by billypon** [comment]
@gawbul But when I run `git clone` in guest filesystem with `git 2.4.5`, it's fine! That must be something wrong with vagrant

**Comment by gawbul** [comment]
I switched to using type: "smb" and the `git clone` step now works.

**Comment by mitchellh** [comment]
This appears to be a VirtualBox synced folder configuration problem. Please try using VirtualBox customizations to enable symlinks, or talk to the VirtualBox folks. Sorry!
