### ISSUE TITLE
-bash: vagrant: command not found

### ISSUE THREAD

**Issue by bitflipper1** [mitchellh/vagrant#6148]
I'm on the latest update of Yosemite.  Installed Vagrant and Virtual Box.  Vagrant folder is installed in usr/local/bin with symlink to opt/

**Comment by hesco** [comment]
Sounds like you need to add that path to your PATH.  
What does `which vagrant` and `locate vagrant` tell you?
Why are you speaking in relevant paths, rather than absolute paths?
What is the output of `env | grep PATH`?

**Comment by bitflipper1** [comment]
`which vagrant` returns nothing  `locate vagrant' returns 'WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.'
'env | grep PATH' returns
'PATH=/Applications/MAMP/bin/php/php5.3.6/bin:/usr/bin//usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'

**Comment by sethvargo** [comment]
Hi @bitflipper1 

This is a duplicate, but I can't find the other ticket. There is a bug in our installer that has been fixed. Please manually create `/usr/local/bin` with `mkdir -p /usr/local/bin` and re-install Vagrant. Sorry about that - it will be fixed in the next installer. :smile:
