### ISSUE TITLE
Unable to install vagrant  on windows 10 machine

### ISSUE THREAD

**Issue by shashwat51** [mitchellh/vagrant#6152]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,int,int *)" at line 66 of file VBoxManageH
ostonly.cpp
![image](https://cloud.githubusercontent.com/assets/8905588/9295231/5e4b617c-4434-11e5-8d96-4165d75d2e5c.png)

**Comment by sethvargo** [comment]
Hi @shashwat51 

This is an issue with VirtualBox, not Vagrant. Vagrant has been installed fine, but VirtualBox is unable to start the windows machine. You may need to upgrade VirtualBox, but also search some open issues tagged "host/windows" - there are bugs in VirtualBox that have documented workarounds until they are fixed upstream. Thanks! :smile:
