### ISSUE TITLE
Vagrant deletes folders containing '[' and/or ']' when creating a virtual box VM

### ISSUE THREAD

**Issue by crayfishuk** [mitchellh/vagrant#6165]
In store my VirtualBox VMs in a folder with a number of other VMware VMs.  Some of these have (had) folder names starting with '[NEW] Some vm name'.  On creating a new Vagrant VM, the renaming of the VirtualBox folder during 'vagrant up' immediately deleted ALL of those folders...

Obscure I know - but pretty damn annoying...

**Comment by mitchellh** [comment]
Can you please give repro steps for this?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
