### ISSUE TITLE
Vagrant wont start with Virtual Box 5.0.2

### ISSUE THREAD

**Issue by javiergloria** [mitchellh/vagrant#6170]
here is the error Im getting 
Failed to load VMMR0.r0 (VERR_VMM_SMAP_BUT_AC_CLEAR).

Result Code: 
NS_ERROR_FAILURE (0x80004005)
Component: 
ConsoleWrap
Interface: 
IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

downgrade to the last version of the 4.x series and worked

**Comment by dzlab** [comment]
I'm having the same error on OS X Yosemite (10.10.4), Vagrant 1.7.4, VirtualBox 5.0.2 r102096.

**Comment by sethvargo** [comment]
Hi @javiergloria and @dzlab 

Unfortunately these are issues/panics with VirtualBox itself. The best thing you can do is downgrade - Vagrant is just calling VirtualBox commands under the hood, and they are failing because VBox 5 isn't yet stable on all operating systems. Sorry about that!

**Comment by fedecz** [comment]
vagrant 1.7.4 and Virtualbox testbuild (5.0.3 r102220  https://www.virtualbox.org/wiki/Testbuilds ) did the trick for me.
