### ISSUE TITLE
Cannot move contents to home directory using tilda char ~

### ISSUE THREAD

**Issue by nitrocode** [mitchellh/vagrant#6179]
I have the following in my Vagrantfile

    zipFile = "latest.zip"
    if File.exist?( zipFile ) then
      config.vm.provision :shell, :inline => "cp /vagrant/" + zipFile + " ~/"
    end

And this will not work unless I replace the tilda ~ with the exact home directory `/home/vagrant/`

**Comment by neolytics** [comment]
Try adding `privileged: false` to your provisioner.

I've run into the same issue.  Default permissions for provisioner are root which does has a different default home directory then vagrant user `/home/vagrant`

**Comment by sethvargo** [comment]
Hi @nitrocode 

Thank you for opening an issue. As @neolytics pointed out, this is not a bug in Vagrant. By default, shell provisioners are run as "root" (or the root user), which means `~` refers to the root user's home directory, not the vagrant user's home directory. You can either add `privledged: false` to the provisioner or `/home/vagrant` in the destination path. Thanks!
