### ISSUE TITLE
Vagrant up does not wait for winrm to become available

### ISSUE THREAD

**Issue by marooou** [mitchellh/vagrant#6181]
The following message immediately finishes the execution of vagrant up command for windows boxes with winrm communicator:

```
This box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. 
Please wait for the Vagrant environment to be running and try again.
```

This is different from version 1.7.2, in which the command blocks until winrm becomes available.

I believe vagrant should still wait for that, in which case changing the base type of WinRMNotReady exception from WinRMError to TransientError will do the trick, since operations resulting in transient errors are retryable.

**Comment by mkuzmin** [comment]
This behavior depends on used provider. Which one do you use?

**Comment by chris-orchard** [comment]
We have the same problem. Using the vagrant-vsphere provider (1.7.0) and vagrant 1.8.1.

**Comment by chris-orchard** [comment]
This looks like it was previously an issue with the vsphere provider which was fixed by using the Vagrant core API: https://github.com/nsidc/vagrant-vsphere/issues/144

However this issue seems to show the core API has now changed and broken this again.

**Comment by sethvargo** [comment]
This looks to be an upstream issue in the vsphere provider. If you disagree and think this is a core bug, please let me know. Thanks! 😄

**Comment by chris-orchard** [comment]
My understanding from reading the comments on https://github.com/nsidc/vagrant-vsphere/issues/144 was that they fixed it by changing to use the core API, and something has now changed in the core API that's broken it. Is that not the case?

Both bugs related to are closed so there's nothing open in either project to address the issue.
