### ISSUE TITLE
Documentation for installing Vagrant from source outdated

### ISSUE THREAD

**Issue by obestwalter** [mitchellh/vagrant#6183]
I am trying to install vagrant from source on Ubuntu 14.04 following this guide in the wiki: https://github.com/mitchellh/vagrant/wiki/Installing-Vagrant-from-source

I did not succeed yet due to an old bundler version that is needed. I tried to create a workaround (I [documented my steps in the wiki](https://github.com/mitchellh/vagrant/wiki/Installing-Vagrant-from-source/_compare/a34e27841c337cfd3cb82f7777619c6fb09b8d5b...e6d93e2d61a4f9e1fca9b4882b36e33f90254434) right away) but finally gave up, when rake install failed with the same bundler error. Being a Python dev with close to no experice in the Ruby ecosystem, I have no idea what I am doing, so I am not even sure if that's the right road to go down.

I would also suggest that this documentation is moved into the main vagrant documentation and is referenced in the main README.md. I was searching all over the place but did not find this in the wiki (seems pretty abandoned anyway). I was expecting it in the README.md or in the main docs. What makes this even harder to find is that googling for "vagrant development" or similar queries yield a lot of posts about how great Vagrant is for development (I agree) but nothing in the way of how to get started with Vagrant development :)

**Comment by imvivekchaudhari** [comment]
agreed :+1: . I am also searching for doc currently to build vagrant from source. no luck yet :(

**Comment by imvivekchaudhari** [comment]
@obestwalter Hey, I got it working.
You need to install ruby-dev as it requires all dependencies.
The easiest way is to install rvm and do this "rvm install 2.0.0-dev".
Note: Remember you need 2.0.0 for latest vagrant.

**Comment by obestwalter** [comment]
Nice! It would be great if you could describe the steps necessary in the wiki article . My botched bundler workaround is not necessary then I guess?

**Comment by imvivekchaudhari** [comment]
Sure. I will update the wiki and pull request soon. I vote that we need to make documentation for vagrant-dev more visible.

**Comment by sethvargo** [comment]
I updated this. The instructions should be the same on windows/mac/linux.

**Comment by obestwalter** [comment]
@sethvargo thanks a lot. Looks manageable now to run against the dev version for testing purposes.
