### ISSUE TITLE
ansible.group_vars not accepting path to a yml file

### ISSUE THREAD

**Issue by jamstooks** [mitchellh/vagrant#6186]
According to the [Vagrant documentation][1],

> `ansible.extra_vars` can be used to pass additional variables (with highest priority) to the playbook. This parameter can be a path to a JSON or YAML file, or a hash.

I should be able to supply the `extra_vars` variable with a path to a yaml file. However, when I provide the following path:

    ansible.extra_vars = "group_vars/vagrant.yml"

... I get this error, which would indicate otherwise:

> * `extra_vars` for the Ansible provisioner must be a hash or a path to an existing file. Received: group_vars/vagrant.yml (as String)

  [1]: http://docs.vagrantup.com/v2/provisioning/ansible.html

**Comment by gildegoma** [comment]
@jamstooks I suppose that your `"group_vars/vagrant.yml"` path is not relative to your `Vagrantfile`.

If you still have problems, please provide a github repo that can be used to reproduce the problem.
Thanks!

**Comment by gildegoma** [comment]
Closing for now due to lack of feedback. 

@jamstooks I'd be happy to reopen if you provide more information :)
