### ISSUE TITLE
[Feature Request] Support xhyve as driver

### ISSUE THREAD

**Issue by joneslee85** [mitchellh/vagrant#6187]
[xhyve](https://github.com/mist64/xhyve) is a new virtualisation alternative on OSX platform which has smaller footprint and better performance compared to VirtualBox. Please close this ticket if supporting xhyve is not possible technically.

**Comment by sethvargo** [comment]
Hi @joneslee85 

Thank you for opening an issue. The xhyve virtualization definitely looks exciting! As a general rule, we prefer to have external providers created as a plugin first. Once they gain in popularity, we can work to make them part of the official distribution :smile:
