### ISSUE TITLE
Vagrant networking Centos 7 and ifdown

### ISSUE THREAD

**Issue by vamegh** [mitchellh/vagrant#6191]
Hi, 

Sorry not sure if I should have opened a new issue for this. I have come across an issue today with Vagrant and Centos7 vms (using virtualbox, upgraded to latest vagrant v1.7.4 host os: osx and Linux)

I get the following error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 

Stdout from the command:

Stderr from the command:

cat: /opt/custom/etc/realname: No such file or directory
cat: /opt/custom/etc/realname: No such file or directory
usage: ifdown <configuration>
```

I have run it with --debug and the interface isn't passed .. When running vagrant up after a vagrant destroy it works perfectly, its only when running vagrant up after a vagrant halt that this issue displays itself. 

The centos 7 image I am using is this one:  

https://atlas.hashicorp.com/puppetlabs/boxes/centos-7.0-64-nocm

I dont know how they have done it, but vagrant up on a clean image of the above works perfectly fine, when I try to create my own image based on that 1 above, or try and halt and bring it up, it doesnt work. 

I started reading through the code to try and work out what it possibly could be. I initially came across notes that stated it could be the regexp for working out the centos / redhat release, but this is not the case, it seems to be detecting os fine. 

within:

> $ vi ./plugins/guests/redhat/cap/flavor.rb

This calls: 

```
 require File.expand_path("../../../fedora/cap/configure_networks", __FILE__)
          ::VagrantPlugins::GuestFedora::Cap::ConfigureNetworks.
            configure_networks(machine, networks)
```

Within: 

> vi plugins/guests/fedora/cap/configure_networks.rb

We have:

```
 # Bring down all the interfaces we're reconfiguring. By bringing down
          # each specifically, we avoid reconfiguring p7p (the NAT interface) so
          # SSH never dies.
          interfaces.each do |interface|
            retryable(on: Vagrant::Errors::VagrantError, tries: 3, sleep: 2) do
              machine.communicate.sudo("cat /tmp/vagrant-network-entry_#{interface} >> #{network_scripts_dir}/ifcfg-#{interface}")
              machine.communicate.sudo("! which nmcli >/dev/null 2>&1 || nmcli c reload #{interface}")
              machine.communicate.sudo("/sbin/ifdown #{interface}", error_check: true)
              machine.communicate.sudo("/sbin/ifup #{interface}")
            end

            machine.communicate.sudo("rm -f /tmp/vagrant-network-entry_#{interface}")
          end
```

I think it is this code block, on the vm itself we have, the following:

```
root@base:~ # cat /tmp/vagrant-network-entry_
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=172.16.10.95
NETMASK=255.255.255.0
DEVICE=
PEERDNS=no
#VAGRANT-END
```

This proves that it is using the fedora code block to get interface information / biosdevname, running the various system commands it calls, they seem to work fine:

```
root@base:~ # ls /sys/class/net | egrep -v lo\|docker
enp0s3
enp0s8
root@base:~ # /usr/sbin/biosdevname -d | grep Kernel | cut -f2 -d: | sed -e 's/ //;'
enp0s3
enp0s8
root@base:~ #
```

however when running a vagrant up, it just isn't able to get the network information hence why #{interface} is not getting a value, I think 
 
If you have any ideas what is going wrong, or if I can provide any further help / information please let me know. 

The Vagrant config file itself calls the vm as follows:

```
hosts = [
  { name: 'base',  loc: 'local', plat: 'virtualbox', env: 'testing', hostname: 'base.box', ip: '172.16.10.95', memory:'256', cpu: 1, box: 'puppetlabs/centos-7.0-64-nocm', port_forward: [guest: 80, host: 8080], },
]

<cut code> ... </cut code>

      case host[:env]
       when 'testing'
          c.vm.box_url = c7_baselined_url
          c.vm.hostname = host[:hostname]
          c.vm.network :private_network, ip: host[:ip], netmask: '255.255.255.0'
          c.vm.provision :shell do |s|
            s.path = "scripts/testing-provision.sh"
            s.args = "#{host[:name]} #{host[:env]} #{host[:plat]} #{host[:loc]}"
          end
```

Kind Regards, 

Vamegh

**Comment by vamegh** [comment]
Hi Mitchellh,

So I decided to investigate this further using vagrant development directly and I have found the cause, which is as follows:

```
==> inspire-cms: Configuring and enabling network interfaces...
VH :: virtual =  false
VH :: virtual =  false
VH :: virtual =  false
VH :: virtual =  false
VH :: interface name  (not virtual)  =  ["cat: /opt/custom/etc/realname: No such file or directory"]
VH :: interface name  (not virtual)  =  ["cat: /opt/custom/etc/realname: No such file or directory"]
VH :: interface name  (not virtual)  =  ["enp0s3", "enp0s8"]
VH :: Interface CLEAR :: touch /etc/sysconfig/network-scripts/ifcfg-
VH :: Interface CLEAR :: sed -e '/^#VAGRANT-BEGIN/,/^#VAGRANT-END/ d' /etc/sysconfig/network-scripts/ifcfg- > /tmp/vagrant-ifcfg-
VH :: Interface CLEAR :: cat /tmp/vagrant-ifcfg- > /etc/sysconfig/network-scripts/ifcfg-
VH :: Interface CLEAR :: rm -f /tmp/vagrant-ifcfg-
VH :: Interface DOWN :: 
VH :: Interface DOWN :: cat /tmp/vagrant-network-entry_ >> /etc/sysconfig/network-scripts/ifcfg-
VH :: Interface DOWN :: ! which nmcli >/dev/null 2>&1 || nmcli c reload 
VH :: Interface DOWN :: cat /tmp/vagrant-network-entry_ >> /etc/sysconfig/network-scripts/ifcfg-
VH :: Interface DOWN :: ! which nmcli >/dev/null 2>&1 || nmcli c reload 
VH :: Interface DOWN :: cat /tmp/vagrant-network-entry_ >> /etc/sysconfig/network-scripts/ifcfg-
VH :: Interface DOWN :: ! which nmcli >/dev/null 2>&1 || nmcli c reload 
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 

Stdout from the command:
Stderr from the command:

cat: /opt/custom/ipc/realname: No such file or directory
cat: /opt/custom/etc/realname: No such file or directory
usage: ifdown <configuration>
```
I added some puts / debug statements to see what was going on, and as you can see there is an environment variable thats set after running puppet which doesnt exist -- but this messes up the system calls to biosdevname to get the interface names. 

This is possibly something that needs to be cleaned up in the code. I think something along the lines of:

machine.communicate.sudo("/usr/sbin/biosdevname -d | grep Kernel | cut -f2 -d: | sed -e 's/ //;' | egrep '(^en)|(^sl)|(^wl)|(^ww)|(^em)|(^p)'") do |_, result| 

should work, but I haven't tested properly  (i'll submit a patch if I get it working), the  various names possible are available here:

```
http://cgit.freedesktop.org/systemd/systemd/tree/src/udev/udev-builtin-net_id.c#n20
http://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
and 
http://linux.dell.com/files/whitepapers/consistent_network_device_naming_in_linux.pdf
```

**Comment by vamegh** [comment]
Ive added a pull request which fixes things for me: https://github.com/mitchellh/vagrant/pull/6204

**Comment by tomrogers3** [comment]
+1

**Comment by wynnw** [comment]
The #6204 pull request solved the same problem some of my coworkers mysteriously ran into after rebooting the host OS (OS X + virtualbox) without doing a vagrant halt first - so a big +1 from here too.

**Comment by vamegh** [comment]
I've pulled in and re-based my fork, it should merge cleanly against the current updates again.

**Comment by hnq90** [comment]
@vamegh 
:+1: 
Thanks for your solution.

**Comment by jfbibeau** [comment]
I also ran into the same issue with a RHEL7 guest. In my case, I had a .bashrc file with a PS1 prompt customization in it (which causes stderr to output a warning in non-TERM shells).

It was causing ifdown to fail (same issue as above, ifcfg- did not have the proper device name appended) on a vagrant reload, even though the clean image's first vagrant up worked.

My fix was to remove the line causing the stderr output, but something could still be done on the vagrant side to improve this. +1 for that PR.
