### ISSUE TITLE
vagrant-vmware-fusion plugin - should I be able to specify uuid.bios?

### ISSUE THREAD

**Issue by luciusbono** [mitchellh/vagrant#6196]
I'm try to specify an alternate uuid BIOS in a Vagrantfile using the VMWare Fusion Plugin. My Vagrantfile reads as such: 

```
#-*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
 config.vm.box = "OSX104-new"
  
  config.vm.provider "vmware_fusion" do |v|
	v.vmx["uuid.bios"] = "59 FE 42 7E A7 9A 4F 32 9B 2D 1D B8 C0 EB E5 2B"
  end
end
```

Oh noes! Now you know my secret UUID! It's okay, I can just make another one. 

Anyway, according to this [secret and mystical document](http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1002403) I should be able to just change that key in the `.vmx` file for my box and be on my way. I would expect my Vagrantfile to be able to do this for me, but when I check my .vmx file it reads:

```
uuid.action = "create"
uuid.bios = "56 4d a7 6c 37 8c ea 6d-25 92 53 39 62 f9 e8 c8"
uuid.location = "56 4d a7 6c 37 8c ea 6d-25 92 53 39 62 f9 e8 c8"
```

I, of course, tried a `vagrant reload` and whatnot. 

What am I doing wrong?

**Comment by mitchellh** [comment]
It looks like when VMware is running the machine it is setting that UUID bios. I can reproduce it but Vagrant isn't doing anything between setting it and starting the machine, it is changing on boot. Mind asking VMware (sans Vagrant) for assistance?
