### ISSUE TITLE
Synced folders state can't be updated without destroying the VM

### ISSUE THREAD

**Issue by fearlsgroove** [mitchellh/vagrant#6198]
Using rsync, I changed the path that rsync is using while a machine was already built, provisioned and running. If I change the vagrant file such that it changes the path of the rsync'd folders, the commands `vagrant rsync` and `vagrant rsync-auto` do not being using the new settings. If I `vagrant reload` or `vagrant halt`/`vagrant up`, I see the changed rsync paths reflected while the machine comes up, but even after taking these steps the rsync/rsync-auto commands continue to use the old config.

I found that removing the file  `.vagrant/machines/default/virtualbox/synced_folders` and vagrant reloading fixes the issue.

**Comment by brettdh** [comment]
I have a very similar issue, especially relating to the `vagrant rsync[-auto]`commands. I also noticed that they were using an old config, even after `vagrant reload`. I found that the `synced_folders` file contained ALL the different configurations I ever had, including paths that were no longer specified in my Vagrantfile.

Steps to reproduce:
 1. Set up a rsync'd folder `foo`. `vagrant up`.
 1. Set up a rsync'd folder `bar`. Remove `foo` from the guest. `vagrant reload`.
 1. Notice that `foo` is still synced, and that it still appears in `.vagrant/machines/.../synced_folders`.

It seems that `vagrant reload` needs to delete `synced_folders`, as the documentation indicates that it should be sufficient to update the synced folder configuration.

@fearlsgroove - I would also suggest changing the title of this issue to better reflect the fact that `vagrant reload` fails to properly update the synced folder config. After all, the docs do state that you have to run `vagrant reload` after changing the Vagrantfile config, and you don't actually have to destroy the VM, as per the workaround you mentioned.

**Comment by mitchellh** [comment]
Reproduced, taking a closer look.
