### ISSUE TITLE
9pfs folder sharing

### ISSUE THREAD

**Issue by rrva** [mitchellh/vagrant#6199]
The plan9 filesystem 9pfs, implemented at https://bitbucket.org/plan9-from-bell-labs/u9fs/ seems in some ways superior to NFS sharing, with possibly better performance for some scenarios. QEMU has implemented it for file sharing: http://wiki.qemu.org/Documentation/9psetup

Would be great if similar options was available to vagrant.

**Comment by avnik** [comment]
https://github.com/chaos/diod can be other option to use as 9pfs server implementation.

Both u9fs and/or diod can be good alternative to nfs, as them not require root permissions to operate

**Comment by sethvargo** [comment]
Hi @rrva 

Thank you for opening an issue. As a general rule moving forward, we would like to see new plugins (like custom shared folder extensions) developed as external plugins first. Once they gain in popularity, we can either merge them into Vagrant core, or package them with the official distribution :smile:
