### ISSUE TITLE
Vagrant looses its id file when the host disk gets full

### ISSUE THREAD

**Issue by charlesturner7c5** [mitchellh/vagrant#6206]
If the host disk on which the VirtualBox disk images gets to 100%, the VM freezes and Vagrant looses its association with the VirtualBox VMs on the system. A subsequent vagrant up attempts to import a brand new base box.

When my disk fills up, I have to manually recreate the "id" file to fix this problem.

**Comment by mitchellh** [comment]
Can you show output and a `VAGRANT_LOG=debug` output for when this happens? Thanks

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
