### ISSUE TITLE
Vagrant 1.7.4 more than doubles time to complete provisioning with chef-zero provisioner

### ISSUE THREAD

**Issue by dvanbuskirk** [mitchellh/vagrant#6208]
I've recently upgraded to 1.7.4 and noticed two issues with the chef-zero provisioner.

There is a noticeable pause when making a new rest client request to the local chef-zero server.

The same chef run is now taking double the time to complete.

The total time for a vagrant provision is now 10-15 minutes longer than it previously was.  When I downgrade to Vagrant 1.7.2 the chef run takes half the time and there is no odd pause for a rest client request.

Vagrant Version: 1.7.4
Chef Version: 12.3.0

```
==> ground: [2015-08-28T18:02:20+00:00] INFO: Starting Chef Run for dev-gnd.###########.com
==> ground: [2015-08-28T18:02:20+00:00] INFO: Running start handlers
DEBUG ssh: stdout: [2015-08-28T18:02:20+00:00] INFO: Start handlers complete.

 INFO interface: info: [2015-08-28T18:02:20+00:00] INFO: Start handlers complete.
 INFO interface: info: ==> ground: [2015-08-28T18:02:20+00:00] INFO: Start handlers complete.
==> ground: [2015-08-28T18:02:20+00:00] INFO: Start handlers complete.
DEBUG ssh: stdout: resolving cookbooks for run list: ["minitest-handler", "####::gnd_dev", "####", "####::devconfig"]

 INFO interface: info: resolving cookbooks for run list: ["minitest-handler", "####::gnd_dev", "####", "####::devconfig"]
 INFO interface: info: ==> ground: resolving cookbooks for run list: ["minitest-handler", "####::gnd_dev", "####", "####::devconfig"]
==> ground: resolving cookbooks for run list: ["minitest-handler", "####::gnd_dev", "####", "####::devconfig"]
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: stdout: [2015-08-28T18:05:46+00:00] INFO: Loading cookbooks [minitest-handler@1.3.2, ####@0.0.1, chef_handler@1.1.6, apt@2.6.1, ####_docker@0.0.1, hostname@0.3.0, hostsfile@2.4.5, ####_serf@0.0.1, docker@0.36.0, aufs@0.1.1, device-mapper@0.1.0, git@4.1.0, golang@1.5.0, homebrew@1.12.0, iptables@1.0.0, lxc@2.0.0, modules@0.2.0, runit@1.5.16, sysctl@0.6.2, yum-epel@0.6.0, build-essential@2.1.3, dmg@2.2.2, windows@1.36.1, yum@3.5.2, dpkg_autostart@0.1.12, polipo@0.1.0, iptables-ng@2.2.5, ohai@2.0.1]

DEBUG ssh: stdout: [2015-08-28T18:09:11+00:00] INFO: Chef Run complete in 410.558039654 seconds

 INFO interface: info: [2015-08-28T18:09:11+00:00] INFO: Chef Run complete in 410.558039654 seconds
 INFO interface: info: ==> ground: [2015-08-28T18:09:11+00:00] INFO: Chef Run complete in 410.558039654 seconds
==> ground: [2015-08-28T18:09:11+00:00] INFO: Chef Run complete in 410.558039654 seconds

Vagrant Version: 1.7.2
Chef Version: 12.3.0

Does not have the long pause mentioned above and took half the time to complete its chef run.

 INFO interface: info: [2015-08-28T21:07:46+00:00] INFO: Chef Run complete in 206.768003595 seconds
 INFO interface: info: ==> ground: [2015-08-28T21:07:46+00:00] INFO: Chef Run complete in 206.768003595 seconds
==> ground: [2015-08-28T21:07:46+00:00] INFO: Chef Run complete in 206.768003595 seconds
DEBUG ssh: stdout: [2015-08-28T21:07:46+00:00] INFO: Skipping removal of unused files from the cache
```

**Comment by sethvargo** [comment]
Hi @dvanbuskirk 

This is expected. The prior version of the Chef Zero provisioner was not actually the Chef Zero provisioner; it was chef-solo.

Chef Zero is inherently slow with the way it has to read files from disk and upload them into memory. This is further exacerbated by the slowness of synced folders at times.

If you were previously using the Chef Zero provisioner in Vagrant, you should be able to switch to Chef Solo with little effort, since the original Chef Zero provisioner was actually just Chef solo.

You can see these issues for more information:

- https://github.com/mitchellh/vagrant/issues/6159
- https://github.com/mitchellh/vagrant/issues/5972
- https://github.com/mitchellh/vagrant/issues/5619
- https://github.com/mitchellh/vagrant/issues/5072
- https://github.com/mitchellh/vagrant/pull/5339
- https://github.com/mitchellh/vagrant/pull/5916

Thanks! :smile:

**Comment by jperville** [comment]
Have posted a patch and workaround in #6285; to sum it up: chef-zero provisioner + local_mode (in a custom_config_path) + shared folder for nodes_path = behavior of old chef_zero provisioner.

**Comment by lsmolic** [comment]
@jperville I tried to implement your patch but didn't see any marked improvement. Could you post a more comprehensive example or instructions? It think more of us could use this than you'd think and are not familiar with patching chef as much as you are.

Thanks in advance!

**Comment by jperville** [comment]
Hi @lsmolic, assuming you have applied the patch from #6285 in `/opt/vagrant/embedded/gems/gems/vagrant-1.7.4`, you can follow the following steps:
 - provision your VMs with the chef_solo provisioner (eg. `vm.provision "chef_solo" do |chef|`)
 - if you are using multi-VM setup, then you should also set `chef.nodes_path = 'nodes'` (else search won't work)
 - declare a custom config path (eg. `chef.custom_config_path = "lib/vagrant-chef-solo.rb"`) and create that file which MUST enable local_mode (this is what the old chef-zero provisioner did internally)

Here is how my custom_config_path looks like:
```
# Validating ssl certificate is de-facto necessary since chef >= 11.12.0
# http://stackoverflow.com/questions/22991561/chef-solo-ssl-warning-when-provisioning
Chef::Config.ssl_verify_mode = :verify_peer

# enable local-mode to restore behavior of vagrant <= 1.7.2 chef-zero provisioner
local_mode true

# Move lockfile out of the (potentially shared) file_cache_path;
# see https://github.com/fgrehm/vagrant-cachier/issues/28
lockfile '/var/run/chef-client-running.pid'

# Set chef proxies from ENV because vagrant-proxyconf does not detect chef provisionners
# in multi-vm setups; see https://github.com/tmatilai/vagrant-proxyconf/issues/101
http_proxy ENV['http_proxy'] unless String(ENV['http_proxy']).empty?
https_proxy ENV['https_proxy'] unless String(ENV['https_proxy']).empty?
ftp_proxy ENV['ftp_proxy'] unless String(ENV['ftp_proxy']).empty?
no_proxy ENV['no_proxy'] unless String(ENV['no_proxy']).empt
```

Good luck! If you applied all the above steps correctly then you should be able to provision without spending hours uploading cookbooks to chef_zero server.

**Comment by mattdeboard** [comment]
Hi @sethvargo.

I'm curious how different the implementation of chef-zero is in Vagrant from TestKitchen, because running `vagrant provision foo` is much slower than `kitchen converge foo`. As in, the former can take 3-5 minutes while the former, using the same chef cookbooks, same disk image, takes 20-30 seconds.

This is a consistent difference across host OS, different host machines, different VMs. Do you have any insight onto why this is?
