### ISSUE TITLE
Vagrant Share error

### ISSUE THREAD

**Issue by kapersoft** [mitchellh/vagrant#6215]
Since yesterday all my Vagrant VM's get an error using Vagrant Share:

```
$ vagrant share
==> default: Detecting network information for machine...
    default: Local machine address: 192.168.33.31
    default: Local HTTP port: 80
    default: Local HTTPS port: disabled
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
    default: Share will be at: marvelous-armadillo-1896
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
```
Full debug log can be found at https://gist.github.com/kapersoft/af4d41cf3d3f916757df#file-vagrant_share_error-txt.

I tried resetting my router to avoid connection issues, disabling my firewall and reinstalling Vagrant. Does anyone has a clue what is going wrong? I am using Vagrant 1.7.4 on OSX 10.10.5 (Yosemite)

**Comment by sethvargo** [comment]
Hi @kapersoft 

Thank you for opening an issue and I am sorry you were having issues with Vagrant share. Our hosting provider terminated a few of our instances without warning yesterday, which caused an outage. Everything should be back up to normal, but you may need to restart your share. Thanks and sorry about that! :smile:

**Comment by kapersoft** [comment]
Hi @sethvargo
Thank you for your answer. What do you mean with "restart your share"? I get the same error when I execute `vagrant share`.

**Comment by sethvargo** [comment]
Hi @kapersoft 

Can you please email support (at) hashicorp.com with the output of the vagrant share command in debug mode? Thanks!

**Comment by kapersoft** [comment]
Hi @sethvargo,

I tried it again and it now all works fine. Looks like all system are back to normal :smile:
