### ISSUE TITLE
--ask-vault-pass option for ansible provisioner

### ISSUE THREAD

**Issue by nicolaspanel** [mitchellh/vagrant#6217]
It would be nice to be able to pass `--ask-vault-pass` option when provisioning with ansible.

Example:

``` sh
vagrant provision --ask-vault-pass
```

Seems that the only way to it right is  toset  `ansible.ask_vault_pass = "true"` in the Vagrantfile

**Comment by gildegoma** [comment]
I understand the wish.

More generally, it could be quite handy to give the ability to pass any raw/unchecked Ansible arguments, following the same "two hyphens" convention already provided by [`vagrant ssh`](https://docs.vagrantup.com/v2/cli/ssh.html)  command (e.g. `vagrant provision -- --tags=web --start-at-task='do this'`.

I'll check in Vagrant core and plugins codebase to see if such mechanism is already available.

@nicolaspanel are you willing to work on a pull request for this feature?

**Comment by nicolaspanel** [comment]
I'd like to help of course.

Please notice that I'm not very familiar with ruby so it could take some time.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!

**Comment by ctessmer** [comment]
Quick correction for @nicolaspanel's [great post](https://github.com/hashicorp/vagrant/issues/6217#issue-104088463). Make sure to *not* put double quotes around `true`. Otherwise Ansible won't ask you your password. Your vagrantfile should look like this:

`ansible.ask_vault_pass = true`

PS: I'm on Ansible 2.6.4 and Vagrant 2.1.5.
