### ISSUE TITLE
First machine of multimachine file doesn't have additional private_network network adapter connected with VMware Fusion provider, only once

### ISSUE THREAD

**Issue by lattwood** [mitchellh/vagrant#6221]
First machine is brought up with the NAT adapter connected, and the private_network adapter created but not connected.

Second machine is brought up with both NAT and private created and connected.

Manually connecting the first machine's private_network adapter, then running destroy & up results in both adapters being created and connected.

This only happens the first time the Vagrantfile is used with a given VMware Fusion install, on OSX. It's very reproducible, we've had it occur on every developer machine we've deployed this to. (4/4 so far)

**Comment by sethvargo** [comment]
Hi @lattwood 

Thank you for opening an issue. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html). This will help us reproduce this issue. Thanks! :smile:

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
