### ISSUE TITLE
Problem with mounting shared folders. Win 10, Hyper-V

### ISSUE THREAD

**Issue by Kamilius** [mitchellh/vagrant#6222]
Hi. I'm trying to use Vagrant for first time and I can't event finish "tutorial" successfully by following documentation. Here is box I'm trying to use - hashicorp/precise64 (https://atlas.hashicorp.com/hashicorp/boxes/precise64). Also I'm using Hyper-V provider, as VirtualBOX is not yet officially supporting Windows 10.
And here is a screenshot of an output I get while trying to get vagrant box up and running:
![default](https://cloud.githubusercontent.com/assets/3115794/9604937/c5aca7e4-50ba-11e5-9429-3607f33c92ff.PNG)

The box get's up, so I  can enter this environment by `vagrant ssh`, but project's folder is not mounted, so I can't get to any of files I need.

Any clues on how to fix this and get things properly working under Windows 10?

P.s.: project I need to get up and running is using nodejs

**Comment by ducke** [comment]
Is the ipaddress 192.168.0.7 the right one from the host?
I had the same problem, because on my host machine exists more then one nic.
My fix was to put the right ipaddress in the Vagrantfile
```
config.vm.synced_folder ".","/vagrant", type: "smb", smb_host: "192.168.0.X" 
```

**Comment by ducke** [comment]
Do you use an Microsoft Live ID Account for your login?
Add an local account to your Windows 10 Machine and put the credentials to your Vagrantfile
```
config.vm.synced_folder ".", "/vagrant", type: "smb", smb_username: "vagrant", smb_password: "<yoursecret>"
``` 
The local user must have access rights to the shared folder.

**Comment by Kamilius** [comment]
@ducke Thanks, so the thing is, that in order to normally use Vagrant under Windows 10 (don't know about previous versions), account should have password set. My account didn't had one, so I've created new local account with password specially for Vagrant.

I believe this one should be added into docs and README.md, as I think it is really important to know this simple and yet crucial thing.

Thanks for help again :) Now I'll go and experiment a bit :)

**Comment by ducke** [comment]
I think this is a normal behaivor in newer versions of Windows. You can disable password protection.
http://www.howtogeek.com/126214/how-to-create-network-file-shares-with-no-passwords-in-windows-8/
