### ISSUE TITLE
Container Link fails on Docker Provider

### ISSUE THREAD

**Issue by alexandarp** [mitchellh/vagrant#6223]
Hello,

I have been experiencing a strange problem with Docker links. When I do ```vagrant halt``` and then ```vagrant up --no-parallel``` sometimes the ```httpd``` container won't have the ```tomcat``` url in it's ```/etc/hosts``` file. I have only been able to reproduce this problem at random. Could it be that the ```tomcat``` container didn't run until after the ```httpd``` container? 

Here is my Vagrantfile:

```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
 
Vagrant.configure("2") do |config|

  config.vm.define "mysql" do |a|
    a.vm.provider "docker" do |d|
      d.image = "mysql"
      d.name = "mysql"
      d.ports = ["3306:3306"]
      d.remains_running = true
      d.vagrant_machine = ""
      d.vagrant_vagrantfile = "./DockerHostVagrantfile"
    end
  end

 config.vm.define "tomcat" do |a|
    a.vm.provider "docker" do |d|
      d.image = "tomcat"
      d.name = "tomcat"
      d.link("mysql:mysql")
      d.ports = ["8080:8080", "8009:8009"]
      d.remains_running = true
      d.volumes = ["/vagrant:/root"]
      d.vagrant_machine = ""
      d.vagrant_vagrantfile = "./DockerHostVagrantfile"
    end
  end

 config.vm.define "httpd" do |a|
    a.vm.provider "docker" do |d|
      d.image = "httpd"
      d.name = "httpd"
      d.link("tomcat:tomcat")
      d.ports = ["80:80"]
      d.remains_running = true
      d.vagrant_machine = ""
      d.vagrant_vagrantfile = "./DockerHostVagrantfile"
    end
  end
  
end
```

**Comment by sethvargo** [comment]
Hi @alexandarp 

What version of Vagrant are you using? Could you please share the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html) when this is occurring? Thanks! :smile:

**Comment by alexandarp** [comment]
@sethvargo I figured out that this occurs when I pull a new version of the tomcat container. Even though I destroy httpd, it doesn't relink to the new tomcat container. I have to delete the image inside of the VM for the changes to pick up. Is this expected behaviour?

**Comment by sethvargo** [comment]
Hi @alexandarp 

This is a bug and there is another issue tracking that. I can't find it right now, but it's something like "container looses links when updated".
