### ISSUE TITLE
Issuing vagrant halt twice subsequently destroys the box

### ISSUE THREAD

**Issue by matevarga** [mitchellh/vagrant#6224]
I've stopped a VirtualBox VM with `vagrant halt`, but then realized that it's not what I want, so pressed ctlr+c. Then I realized that it's too late so I issued `vagrant halt` again to make sure the box is stopped properly. Then on the next startup, Vagrant reimported the box and I had to start from scratch.

```
» vagrant halt              
» vagrant halt                                                                                                                                                                                  

==> default: Attempting graceful shutdown of VM...
An action 'halt' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.                                                                                                                                                                                                » vagrant up                                                                                                                                                                                      Vagrant can't use the requested machine because it is locked! This
means that another Vagrant process is currently reading or modifying
the machine. Please wait for that Vagrant process to end and try
again. Details about the machine are shown below:

Name: default
Provider: virtualbox
 » vagrant up  
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'XYZ/centos7'...
==> default: Matching MAC address for NAT networking...
```

**Comment by cordery** [comment]
You should check virtualbox and see if the machine has really been destroyed or if the id file from your .vagrant folder has been deleted (thus dissassociating that vagrant instance from the virtualmachine).  This just happened to me (again).  To restore it create a file called `id` in your `.vagrant/machines/default/virtualbox/` folder ('default' may be different for you) containing the id of the existing machine, which can be found with the command `VBoxManage list vms`

**Comment by mitchellh** [comment]
I'm having trouble reproducing this but I agree with @cordery that this is probably the case. If you can find a reproduction case that can get this to happen I would _love_ to fix it. As-is, I can't get this to repro so I'm going to have to close.

But @cordery is probably right. It is very unlikely Vagrant has actually deleted the VM, it probably disassociated.
