### ISSUE TITLE
FreeBSD/SaltStack provisioner broken after 1.7.2

### ISSUE THREAD

**Issue by bryson** [mitchellh/vagrant#6226]
Commit where breaking code was introduced: https://github.com/mitchellh/vagrant/commit/74d22069d41b35bae50e32c1c68a92a4958afebb

FreeBSD does not store configuration files for any packages in `/etc/`; only the base system configuration is stored there. All *packages* are installed to `/usr/local/` and package configuration to `/usr/local/etc/`. This naive solution breaks Salt support for any OS that doesn't pollute the global `/etc/` folder, yet only has a provision for Windows-specific directories. 

I attempted to set the `config_dir` property, but it was either ignored or overwritten.

**Comment by bsuh** [comment]
That commit is being reverted in #6073. Hopefully it gets merged soon.
