### ISSUE TITLE
vagrant poweroff all vms from the same box when destroys one of them

### ISSUE THREAD

**Issue by nickgryg** [mitchellh/vagrant#6228]
Hi,

I have vagrant multi vm environment with 4 vms each. I'm starting 3 vagrant environments in parallel from different Jenkins jobs. So I clone my Vagrant file from the same repo to different folders and do vagrant up vm1-<BUILD_NUMBER> vm2-<BUILD_NUMBER> vm3-<BUILD_NUMBER>.
For example my first job does: vagrant up vm1-100 vm2-100 vm3-100. All this Vms are in private network network-100.
Then another job starts: vagrant up vm1-101 vm2-101 vm3-101. Private network network-101.

After finishing all my tasks Jenkins destroys all vms in first job:
vagrant destroy vm1-100 --force
vagrant destroy vm2-100 --force
vagrant destroy vm3-100 --force

But after this action all vms from another job go to poweroff or abort state. They are in another folder, they have another names, they are in another private network.

ii  vagrant                             1:1.7.4
ii  virtualbox-5.0                    5.0.2-102096~Ubuntu~trusty

**Comment by nickgryg** [comment]
Fixed.

**Comment by tobyjaffey** [comment]
I am seeing exactly the same issue, how did you resolve this?

**Comment by nickgryg** [comment]
When we perform ```vagrant up```, by default virtualbox server (VBoxSVC) starts as process. So first Jenkins job performs ```vagrant up vm1-100``` that means it starts VBoxSVC process and then second job use this VBoxSVC process to up another vagrant boxes. When first job finishes, it, of course, kills all processes it started. So after first job finishes, jenkins kills virtualbox server and that is the reason of all VMs go to abort state.
So, in order to fix this you should start virtualbox server in daemon mode before start Jenkins jobs:  
```/usr/lib/virtualbox/VBoxSVC --pidfile VBoxSVC.pid```

**Comment by tobyjaffey** [comment]
Thanks, this solved the problem for me.
One extra gotcha, of course, VBoxSVC needs to run under the same user as Jenkins.

**Comment by nickgryg** [comment]
Sure, VBoxSVC should be run under the same user as Jenkins.
You are welcome!
