### ISSUE TITLE
default: Warning: Connection refused. Retrying...

### ISSUE THREAD

**Issue by RawPhunky** [mitchellh/vagrant#6230]
Windows 8.1 
VirtualBox 5.0.2
Vagrant 1.7.4
Intel i7-4700MQ CPU witch seems to have Intel® Virtualization Technology (VT-x) ‡
http://ark.intel.com/products/75117/Intel-Core-i7-4700MQ-Processor-6M-Cache-up-to-3_40-GHz

Testing default example:
$ vagrant init hashicorp/precise32
$ vagrant up

Getting error:
![0](https://cloud.githubusercontent.com/assets/2244332/9646593/ded40b26-51dd-11e5-9281-14900be8302e.png)

While VM shows:
![1](https://cloud.githubusercontent.com/assets/2244332/9646594/deec8494-51dd-11e5-9a49-753453dca45e.png)

And I can log in successfully
![2](https://cloud.githubusercontent.com/assets/2244332/9646595/defd1e76-51dd-11e5-8f7e-2c7f98e58ce8.jpg)

Firewall / Antivirus turned off.

Hyper-V is not installed
![hi](https://cloud.githubusercontent.com/assets/2244332/9646648/43a5f5d2-51de-11e5-8f2d-a3359ddf6ca8.png)

I have tried connecting via putty to 127.0.0.1 2222
![image](https://cloud.githubusercontent.com/assets/2244332/9654401/45222c96-5233-11e5-999a-6ceea32ba87a.png)

**Comment by mitchellh** [comment]
This is a fairly critical use case, so if it were more widespread we would've heard _a lot_ about this. Given that, it points towards a system configuration issue for you. Most likely there are firewall rules.

Please try completely disabling Windows firewall (temporarily) just to see if that fixes this. If it does, then re-enable the firewall and add a specific rule to fix this. 

If you find out more that this is indeed a Vagrant-specific issue, please do tell us. Thanks!

**Comment by gitressa** [comment]
I just encountered the "DEBUG ssh: Sending SSH keep-alive..."-prpbelem and the solution was to open up the firewall to the IP of the Vagrant instance.
