### ISSUE TITLE
Vagrant not deleting temp files

### ISSUE THREAD

**Issue by yr0** [mitchellh/vagrant#6231]
I'm using Vagrant with Docker as provider.

Whenever I launch vagrant with any command, the directory gets populated with four files, prefixed with 'vagrant', e.g. 'vagrant20150902-10813-1p2j0fh', and a directory, prefixed with 'd', e.g. 'd20150902-10813-14u60qc'.
Neither of those gets automatically deleted.

I traced the problem to `Vagrant::Bundler#deinit`, that is executed `at_exit`:

    def deinit
       File.unlink(ENV["BUNDLE_APP_CONFIG"]) rescue nil
       File.unlink(ENV["BUNDLE_CONFIG"]) rescue nil
       File.unlink(ENV["GEMFILE"]) rescue nil
    end

`ENV["BUNDLE_APP_CONFIG"]` is always a directory:

    # contents of Vagrant::Bundler#init!
    @appconfigpath = Dir.mktmpdir
    # ...
    ENV["BUNDLE_APP_CONFIG"] = @appconfigpath

That is why first unlink always fails, leaving temporary dir undeleted.
`ENV["GEMFILE"]` is usually nil (perhaps, `ENV["BUNDLE_GEMFILE"]` was meant to be deleted instead).

Anyway, even if `Vagrant::Bundler#deinit` worked as expected, it would still leave three temp files in directory, so I guess, there is a problem with the configuration of OS. 

I have installed Vagrant from .deb Linux x64 package, removed it with `apt-get remove --purge vagrant` and reinstalled again with problem persisting. The OS is Ubuntu 14.04.3 LTS. Linux pc 3.13.0-62-generic # 102-Ubuntu SMP Tue Aug 11 14:29:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
 
I've also tried asking the community at [stackoverflow](http://stackoverflow.com/questions/32352989/vagrant-creates-numerous-trash-config-files-and-directories).

Any help would be much appreciated!

**Comment by remram44** [comment]
I'd very much like to see this fixed, I get thousands of these `d2015*` folders. Also a `vagrant-remram` full of `vagrant2015*` files.

This is really annoying and really not the mark of professional software.

**Comment by sni** [comment]
I created a pull request, hopefully this gets fixed soon.

**Comment by evaryont** [comment]
Since #3469 was re-opened, I guess this is now a dup?
