### ISSUE TITLE
[Feature Request] autoupdates with Sparkle

### ISSUE THREAD

**Issue by hryamzik** [mitchellh/vagrant#6233]
There's a nice framework that simplifies updates on OS X, [Sparkle](https://github.com/andymatuschak/Sparkle). I believe all OS X users would be happy to find it integrated.

**Comment by sethvargo** [comment]
Hi @hryamzik 

Thank you for opening an issue. Vagrant is a mult-OS project, and implementing auto-updates is not something we have planned at this time. If we do change our mind, we will definitely take a look at Sparkle. Thanks! :smile:
