### ISSUE TITLE
Impossible to connect directly to Vagrant VM by IP

### ISSUE THREAD

**Issue by jnardiello** [mitchellh/vagrant#6238]
Hi all,
I'm experiencing a very weird behaviour since I updated virtualbox.

Machine configuration:
```
config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.8.8"
```

I used to connected directly to the Vagrant box with `ssh <user>@192.168.8.8`. This has been working for over a year. Starting today, all I get is a bad timeout. The only way to connect to the machine is using `Host 127.0.0.1:2222`.

After investigating for a while, I believe that **Vagrant networking is broken** with latest Virtualbox. Using "private_network" option isn't properly working and `NAT` (default) is left as VM networking option. 

I might be completely wrong and missing something important. Any help would be appreciated.

**Comment by sethvargo** [comment]
Hi @jnardiello 

Thank you for opening an issue. Unfortunately there is not enough information here to make a proper diagnosis. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html). Thanks! :smile:

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
