### ISSUE TITLE
sharing metadata between VMs

### ISSUE THREAD

**Issue by lioramilbaum** [mitchellh/vagrant#6239]
My application consists of two components: server and agent. I am using Vagrant to create two EC2 instances. One for each application component. First, I create the server instance and provision it with Chef. Now, I am trying to provision the agent instance. To do so, I need to download the agent deployment package from the server instance to the agent instance.

The best way is to use scp with the server instance private ip. How can I share the server private ip address with the agent provision process (Chef)?

**Comment by sethvargo** [comment]
Hi @lioramilbaum 

The best way to do this is to either hard-code the server IP address to a well-known address, or use our new tool - [otto](https://ottoproject.io), which can define project inter-dependencies. Thanks! :smile:
