### ISSUE TITLE
Google Cloud / Vagrant 1.7.2 / VirtualBox 4.3 / Centos 7.1 ssh_exchange_identification: read: Connection reset by peer error

### ISSUE THREAD

**Issue by prassawant** [mitchellh/vagrant#6241]
I have created centos box on Google cloud using vagrant but I am unable to connect using vagrant ssh , it gives me below error:

```
ssh_exchange_identification: read: Connection reset by peer
```

Below is sequence:

```
$ vagrant box add centos-6.5 http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
$ vagrant init centos-6.5
$ vagrant up
$ vagrant ssh 
```

```ruby
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos-6.5"
end
```

**Comment by sethvargo** [comment]
Hi @prassawant 

Thank you for opening an issue. I am not sure I understand the first part of your issue. You created a centos box on Google Cloud (GCE)? The code you shared uses a local VirtualBox instance.

This error message usually means there's a mismatch with the SSH ciphers. Can you please run:

```
$ vagrant ssh -- -v
```

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a _new_ issue and include the requested information. Thanks! :smile:
