### ISSUE TITLE
RDP autologon from Windows host to Windows guest

### ISSUE THREAD

**Issue by bheuvel** [mitchellh/vagrant#6247]
While it is not possible to pass the password as a parameter to the default RDP client (mstsc), the credentials CAN be saved locally which can be re-used; cmdkey

Cmdkey can save credentials, based on (target) host. If the default value (in code now) which forces prompting for credentials is dropped, this will result in autologon of the RDP session.

Created PR #6246 for this.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/commit/01369342db728a4bd08a7569afb95579a48e4d32
