### ISSUE TITLE
Releases nor checksums are signed

### ISSUE THREAD

**Issue by KwadroNaut** [mitchellh/vagrant#6250]
Currently vagrant releases and the checksums are served from a third-party download site. We can't verify if the files have been tampered with. Could you please OpenPGP-sign the checksums file, with some verifiable key so we can get a trust path to the binaries and it's updates?

Thanks,

**Comment by sethvargo** [comment]
This is fixed. Please check https://releases.hashicorp.com for all the product releases and checksums that are GPG signed.
