### ISSUE TITLE
echo -e when run within inline bash provisioning does not correctly format content

### ISSUE THREAD

**Issue by ics-brettma** [mitchellh/vagrant#6251]
### Example Vagrantfile:

    $script = <<SCRIPT
        myVariable="Line1\nLine2\Line3"
        echo -e $myVariable > /tmp/myVarOutput
        more /tmp/myVarOutput
    SCRIPT

    Vagrant.configure("2") do |config|
        config.vm.box = "centos-7-vanilla"
        config.vm.provision "shell", inline: $script
    end

### Expected output on guest OS:

    Line1
    Line2
    Line3

### Actual output on guest OS:

    Line1 Line2 Line3

**Comment by sethvargo** [comment]
Hi @ics-brettma 

Thank you for opening an issue. I see two problems.

First, you are not inserting a newline character between Line2 and Line3. I think you want:

```diff
- myVariable="Line1\nLine2\Line3"
+ myVariable="Line1\nLine2\nLine3"
```

The second issue is that bash (and most other shells) do not preserve whitespace in variables. If you change your echo to the following, it will work:

```
echo -e "${myVariable}" > /tmp/myVarOutput
```

```
==> default: ::::::::::::::
==> default: /tmp/myVarOutput
==> default: ::::::::::::::
==> default: Line1
==> default: Line2
==> default: Line3
```

I verified this works on Vagrant 1.7.4. Please let me know if you have any questions.

**Comment by ics-brettma** [comment]
@sethvargo Thank you for investigating my problem.

I think my problem was more that:

1. The output of the command is not formatted properly when executed within the provisioning script in my Vagrantfile
2. If I copy and paste the command into my running guest instance and run it locally, the output of the command is formated properly.

It appears that the versions and the behaviours of "echo" are different.

It would be good if I could understand what version of "echo" is used by the Vagrant file shell provisioner and if I can change it.
