### ISSUE TITLE
is there a virtualbox feature nat-network support in vagrant

### ISSUE THREAD

**Issue by fuco809** [mitchellh/vagrant#6252]
hi,

i tried (with virtualbox 5.0.0 on win7-64bit) to get nat-network running with a vagrant config, but could not find any documentation, is it already possible to configure and use this with vagrant?
https://www.virtualbox.org/manual/ch06.html#network_nat_service

regards,
hannes

**Comment by sethvargo** [comment]
Hi @fuco809 

This is not currently possible with Vagrant. I have tagged this as an enhancement.

**Comment by mitchellh** [comment]
In what ways are you trying to configure the NAT, out of curiosity?

**Comment by fuco809** [comment]
my use case:
i tried/tested a katello vagrant installation (https://github.com/Katello/katello-deploy) and then used this katello server installation to deploy/update some client vms. to do this i needed the nat network, which i changed/configured manually in the running virtualbox vm.
when i use vagrant to stop/start this katello server, my config changes are lost.

my workaround was, after starting katello server with vagrant: change the network settings on demand in virtualbox gui and always use virtualbox gui.

**Comment by mitchellh** [comment]
Ah. Vagrant doesn't expose NAT network configs but you can achieve similar things with the `customize` calls. I defer to this since it is sort of an edge case feature.
