### ISSUE TITLE
Provisioner ordering - run shell command after Docker instances have been booted

### ISSUE THREAD

**Issue by kevinburkeshyp** [mitchellh/vagrant#6255]
I posted a full description of the issue here: http://stackoverflow.com/q/32506879/329700. Gist of the issue is, I want to boot two Docker containers inside an Ubuntu instance, and then run a command on the Ubuntu instance that interacts with the running containers. No matter how hard I try I can't get the command to run after the Docker containers have started. Maybe the Docker `run` command is occurring after *all* provisioning steps?

If the correct answer is "works as designed" then fine with me, I will figure out another workaround. 

Thanks!

**Comment by kevinburkeshyp** [comment]
Reading further it looks like the Build action for Docker is called as part of the `action_start` block? which means yeah I'm out of luck running anything else in a provisioner, because all of the start blocks run after all of the provisioners.

**Comment by johnjelinek** [comment]
@kevinburkeshyp: :+1: 

I'm trying out http://stackoverflow.com/a/32510687/979315 to see if the `vagrant-triggers` plugin will help.

**Comment by johnjelinek** [comment]
Unfortunately that doesn't work either :'(

**Comment by sethvargo** [comment]
Hi @kevinburkeshyp 

Thank you for opening an issue. It sounds like you are interested in some orchestration, so I would suggest you take a look at [Otto](https://ottoproject.io). 

You are correct that provisioning takes place before the docker instances have booted, but I think this is the intended behavior. You could possibly inject an upstart script that ran on boot to check if the containers were running and then ran some command if they were.

**Comment by kevinburkeshyp** [comment]
Hey... we ended up just running the shell script via `vagrant ssh -c
'script'` after everything booted up... it works for us

On Sun, Nov 8, 2015 at 12:41 PM, Seth Vargo <notifications@github.com>
wrote:

> Hi @kevinburkeshyp <https://github.com/kevinburkeshyp>
>
> Thank you for opening an issue. It sounds like you are interested in some
> orchestration, so I would suggest you take a look at Otto
> <https://ottoproject.io>.
>
> You are correct that provisioning takes place before the docker instances
> have booted, but I think this is the intended behavior. You could possibly
> inject an upstart script that ran on boot to check if the containers were
> running and then ran some command if they were.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/6255#issuecomment-154868754>.
>



-- 
kevin

**Comment by johnjelinek** [comment]
Smart! I'm going to try that. Thanks @kevinburkeshyp
<https://github.com/kevinburkeshyp>.

**Comment by sethvargo** [comment]
Ah nice idea! I should've thought of that! :smile:
