### ISSUE TITLE
The provider 'virtualbox' that was requested to back the machine 'default' is reporting that it isn't usable on this system. 

### ISSUE THREAD

**Issue by desertknight** [mitchellh/vagrant#6258]
>The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

> Vagrant detected that VirtualBox appears installed on your system,
but calls to detect the version are returning empty. This is often
indicative of installation issues with VirtualBox. Please verify
that VirtualBox is properly installed. As a final verification,
please run the following command manually and verify a version is
outputted:

> C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version

I using Windows 7, latest VirtualBox 

When i start vBoxManager and start from interface, everything is fine, but from console ...

**Comment by ghanique** [comment]
I'm facing the very same issue.

**Comment by desertknight** [comment]
@ghanique my problem was a new version of ![ConEmu](https://github.com/Maximus5/ConEmu/issues/323) have some strange bugs. What software you use?

**Comment by ghanique** [comment]
Conemu... Thanks!
