### ISSUE TITLE
File corrupted by vagrant (/etc/network/interfaces)

### ISSUE THREAD

**Issue by 42antoine** [mitchellh/vagrant#6261]
When vagrant edit the file /etc/network/interfaces, it doesn't check if the EOF is stuck to another char.
Here an example :

	iface eth0 inet dhcp
	      pre-up iptables-restore < /etc/iptables.up.rules#VAGRANT-BEGIN

That fails the initialisation of eth0 interface, then it was impossible to use "vagrant ssh".

Hope this help.

The complete file :

	# This file describes the network interfaces available on your system
	# and how to activate them. For more information, see interfaces(5).

	# The loopback network interface
	auto lo
	iface lo inet loopback

	# The primary network interface
	allow-hotplug eth0
	iface eth0 inet dhcp
	      pre-up iptables-restore < /etc/iptables.up.rules#VAGRANT-BEGIN
	# The contents below are automatically generated by Vagrant. Do not modify.
	auto eth1
	iface eth1 inet static
	      address 192.168.56.101
	      netmask 255.255.255.0
	#VAGRANT-END

https://github.com/42antoine/vagrant-CSGO-server/issues/7
https://github.com/42antoine/vagrant-CSS-server/issues/5

**Comment by BohrShaw** [comment]
+1 This is urgent.
