### ISSUE TITLE
"vagrant halt" error with debian/jessie64, no systemd

### ISSUE THREAD

**Issue by neilconway** [mitchellh/vagrant#6263]
Debatable whether this is a bug, but I'll file it just in case: if you replace systemd with sysvinit on Debian jessie, "vagrant halt" fails:

```
$ vagrant halt
==> jepsen: Attempting graceful shutdown of VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

shutdown -h -H

Stdout from the command:



Stderr from the command:

Usage:	  shutdown [-akrhPHfFnc] [-t sec] time [warning message]
		  -a:      use /etc/shutdown.allow
		  -k:      don't really shutdown, only warn.
		  -r:      reboot after shutdown.
		  -h:      halt after shutdown.
		  -P:      halt action is to turn off power.
		  -H:      halt action is to just halt.
		  -f:      do a 'fast' reboot (skip fsck).
		  -F:      Force fsck on reboot.
		  -n:      do not go through "init" but go down real fast.
		  -c:      cancel a running shutdown.
		  -t secs: delay between warning and kill signal.
		  ** the "time" argument is mandatory! (try "now") **
```

It seems like the `shutdown` doesn't like both the `-h` and `-H` flags being specified.

This is using the "debian/jessie64" box. To repro, install sysvinit, sysvinit-core, and sysvinit-utils; reboot the box, then remove systemd.

**Comment by bitprocessor** [comment]
https://github.com/mitchellh/vagrant/pull/6315 should be fixing this

**Comment by bitprocessor** [comment]
@neilconway has nothing to do with systemd/sysvinit. The shutdown -h -H wasn't working for either of them ;) ; but #6315 got merged into master now. Should also fix this issue.
