### ISSUE TITLE
Windows CLI improvements

### ISSUE THREAD

**Issue by thenewguy** [mitchellh/vagrant#6266]
First off, I am not positive of every scenario in which vagrant is used on Windows.  And I have not used vagrant extensively...  but I am working on new project templates that need to work on multiple OSes and I've written two batch scripts that make it a more seamless experience on Windows.  I think it would be useful if some/all of the functionality was incorporated into the standard vagrant cli on windows.

I chose batch scripts so I didn't have to maintain a fork of vagrant and was able to target windows without any additional requirements.  The logic is very simple and could easily be implemented in any fashion.  But the result seems to work pretty well so far.

There is a vagrant wrapper batch file: [vagrant.bat](https://github.com/thenewguy/react-starter/blob/5a6895268fe11d3013c32cb71692e18f8ac21b62/vagrant.bat)

This file elevates to administrator permissions for commands that benefit from elevation if the current shell isn't already elevated.  It also makes the `vagrant-bin/ssh.bat` file available on the path during execution.  I haven't encountered any other programs that need to be wrapped like ssh but they would be simple to implement if needed.  Working with VirtualBox it has turned out that any of the commands that communicate with the virtual machine need to be elevated for symlink support (unless you dig into system permissions which seems complicated for little gain -- could be useful but not to me at this point).  It appears that the hyperv provider requires admin permissions as well, but I haven't spent time with vagrant's hyperv integration yet.  One thing I like about this approach is that you don't end up with lots of stray command windows.  Once the command finishes running it announces completion and then any input closes the prompt.  It would probably be handy to have a flag to disable elevation but I haven't needed it.  I could see such a flag being useful if the command was being run programmatically from a shell call and shouldn't be allowed to open a new cmd prompt.

And there is a ssh wrapper batch file: [vagrant-bin/ssh.bat](https://github.com/thenewguy/react-starter/blob/5a6895268fe11d3013c32cb71692e18f8ac21b62/vagrant-bin/ssh.bat)

Obviously, Windows doesn't come with a compatible ssh program built in... but pretty much every developer installs git.  However, the git installer doesn't recommend adding its compatibility programs to the path and doesn't do so by default.  So the ssh.bat file attempts to find ssh.exe on the path first, and then it attempts to find git.  If it finds git then it uses git's bundled ssh.exe.  In most cases should "just work" and not require any additional configuration.

**Comment by mitchellh** [comment]
This is really really cool. I'm going to keep an eye on it but for now we're not going to move it in. I must admit I probably don't understand the full motivations or ramifications and that itself scares me. Let's leave things as they are now but please feel free to explain further.

**Comment by thenewguy** [comment]
@mitchellh Your comment sounds like this is something that could be accepted if I follow up.  What type of explanation and/or effort/work are you expecting to see from me on this?  I've been using this for awhile and it is very helpful when using vagrant on Windows.

Right now, since it isn't part of the vagrant distribution, it takes a specific project layout to make it work so that the vagrant.bat file is found on the path before the actual vagrant executable.

When you use vagrant with virtualbox on Windows most of the commands must be run with administrator permissions (similar concept as sudo on Linux but very different implementation and much more cumbersome to integrate with non-administrator usage plus it requires a ton of clicks to enable and is buried in the windows ui).  This script makes it so that you cannot make a mistake and attempt to use vagrant with regular user permissions.  It prevents the confusion that occur when commands fail due to lack of permissions (there aren't any helpful error messages for this specific problem) since it automatically prompts the user for administrator permissions and runs the command in an elevated shell.  If this was pulled into the project it would be fairly straightforward to adjust so that it only fires when necessary.

It also makes the "vagrant ssh" command seamless (assuming git is installed) which is much nicer than having to install putty, look up the vagrant box ip address, locate the appropriate ssh keys, convert them to putty ppk files, and then ssh with putty into the box.
