### ISSUE TITLE
Embedded Ruby included with Chef is version 1.9.3p484

### ISSUE THREAD

**Issue by danapplegate** [mitchellh/vagrant#6267]
I've installed Vagrant 1.7.4 on my Mac OSx 10.10.3 (Yosemite) machine using the .dmg package provided on vagrantup.com. I selected the base precise64 Ubuntu box to build my VM, which is downloaded from http://files.vagrantup.com/precise64.box, and am using a chef-solo provisioner to configure my box.

I would like my Vagrant VM to run its recipes in an environment as closely resembling our OpsWorks Ubuntu 12.04 machines as possible. According to [this documentation](http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-ruby.html), Chef 11.10 on OpsWorks runs on an embedded ruby at version 2.0.0-p481. So, I've configured my provisioner to use 11.10:

```ruby
    web_config.vm.provision :chef_solo do |chef|
      chef.version = "11.10"
      ...
```

However, if I `vagrant ssh` into the box, I see the following:

```
$ chef-solo -v
Chef: 11.10.4
$ which chef-solo
/usr/bin/chef-solo
$ head -1 /usr/bin/chef-solo
#!/opt/chef/embedded/bin/ruby
$ /opt/chef/embedded/bin/ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

I had thought that Chef >=11.10 requires ruby 2.0.0 to run. Why is chef-solo running on 1.9.3? Is there any way I can get the embedded ruby version of Chef to match that which is used on my OpsWorks instances?

**Comment by sethvargo** [comment]
Hi @danapplegate 

Can you please share the output of the Vagrant command in debug mode?

**Comment by danapplegate** [comment]
Hi @sethvargo, thanks for responding!

[Here is the output](https://gist.github.com/danapplegate/11a8c9d8c16280e1de38) of running `vagrant up` in the working directory. This is after `vagrant destroy` has been run, and after I followed the instructions to [uninstall vagrant](https://docs.vagrantup.com/v2/installation/uninstallation.html), remove all vagrant user data in ~/.vagrant.d, and reinstalled 1.7.4.

**Comment by sethvargo** [comment]
Hi @danapplegate 

I don't think this is an issue with Vagrant. Can you please share your complete Vagrantfile? I think the issue is that the precise64 box already has an old version of Chef installed. Is there anything in `/opt/chef` on the box? What is the output of `/opt/chef/embedded/bin/chef-solo -v`?

**Comment by danapplegate** [comment]
I've added the [Vagrantfile](https://gist.github.com/danapplegate/11a8c9d8c16280e1de38#file-vagrantfile-rb) to the gist.

Here are the outputs of your queries:

```
vagrant@precise64:~$ ls -la /opt/chef
total 20
drwxr-xr-x 4 root root 4096 Sep 14 22:04 .
drwxr-xr-x 6 root root 4096 Sep 14 22:18 ..
drwxr-xr-x 2 root root 4096 Sep 14 22:04 bin
drwxr-xr-x 7 root root 4096 Sep 14 22:04 embedded
-rw-r--r-- 1 root root 1661 Feb 20  2014 version-manifest.txt
```

```
vagrant@precise64:~$ /opt/chef/embedded/bin/chef-solo -v
-bash: /opt/chef/embedded/bin/chef-solo: No such file or directory
```

Here are the contents of `/opt/chef/embedded/bin`:

```
vagrant@precise64:~$ ls -la /opt/chef/embedded/bin/
total 928
drwxr-xr-x 2 root root   4096 Sep 14 22:04 .
drwxr-xr-x 7 root root   4096 Sep 14 22:04 ..
-rwxr-xr-x 1 root root    472 Feb 20  2014 autospec
-rwxr-xr-x 1 root root    471 Feb 20  2014 bundle
lrwxrwxrwx 1 root root      3 Feb 20  2014 captoinfo -> tic
-rwxr-xr-x 1 root root   8573 Feb 20  2014 clear
-rwxr-xr-x 1 root root   4273 Feb 20  2014 c_rehash
-rwxr-xr-x 1 root root   4407 Feb 20  2014 erb
-rwxr-xr-x 1 root root    897 Feb 20  2014 gem
-rwxr-xr-x 1 root root  72961 Feb 20  2014 infocmp
lrwxrwxrwx 1 root root      3 Feb 20  2014 infotocap -> tic
-rwxr-xr-x 1 root root    328 Feb 20  2014 irb
-rwxr-xr-x 1 root root   5326 Feb 20  2014 ncurses5-config
-rwxr-xr-x 1 root root   5330 Feb 20  2014 ncursesw5-config
-rwxr-xr-x 1 root root 594395 Feb 20  2014 openssl
-rwxr-xr-x 1 root root    450 Feb 20  2014 rake
-rwxr-xr-x 1 root root    798 Feb 20  2014 rdoc
lrwxrwxrwx 1 root root      4 Feb 20  2014 reset -> tset
-rwxr-xr-x 1 root root    198 Feb 20  2014 ri
-rwxr-xr-x 1 root root    469 Feb 20  2014 rspec
-rwxr-xr-x 1 root root  11959 Feb 20  2014 ruby
-rwxr-xr-x 1 root root  18277 Feb 20  2014 tabs
-rwxr-xr-x 1 root root    308 Feb 20  2014 testrb
-rwxr-xr-x 1 root root  77897 Feb 20  2014 tic
-rwxr-xr-x 1 root root  18880 Feb 20  2014 toe
-rwxr-xr-x 1 root root  18842 Feb 20  2014 tput
-rwxr-xr-x 1 root root  29028 Feb 20  2014 tset
```

Perhaps you meant to ask what is the output of `/opt/chef/embedded/bin/ruby -v`? Here is the output of that:

```
vagrant@precise64:~$ /opt/chef/embedded/bin/ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

And here is the output from asking for the chef-solo version:

```
vagrant@precise64:~$ /opt/chef/bin/chef-solo -v
Chef: 11.10.4
```

Could it be that the base box from http://files.vagrantup.com/precise64.box has a version of chef installed that has 1.9.3 embedded, and does not allow for the installation of 11.10 to overwrite it? That was my thought as well, so I tested by creating a new project directory and running `vagrant init ubuntu/trusty64`, to use both an atlas-hosted version and an Ubuntu 14.04 base box. I got the same results as above.

Any ideas?

**Comment by sethvargo** [comment]
Hi @danapplegate 

Can you try adding this to your chef solo in the Vagrantfile:

```
chef.install = "force"
```

**Comment by danapplegate** [comment]
Hey @sethvargo,

So, adding the `chef.install = "force"` directive does seem to have had an effect. I now have two chef-solo executables, and it is now using one in /usr/bin, rather than /opt/vagrant_ruby/bin/chef-solo. However, it looks like it is still using the 1.9.3p484 version of ruby in /opt/chef/embedded/bin.

```
$ chef-solo -v
Chef: 11.10.4
$ which -a chef-solo
/usr/bin/chef-solo
/opt/vagrant_ruby/bin/chef-solo
$ head -1 /usr/bin/chef-solo
#!/opt/chef/embedded/bin/ruby
$ /opt/chef/embedded/bin/ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

Is there any way to see the contents of the precise64 box at http://files.vagrantup.com/precise64.box, to see what is present in the box before vagrant even has a chance to start a provision? Also, how does Vagrant go about installing the different versions of Chef? I can try to step through it and see if anything jumps out at me, with regards to how chef decides which ruby executable to use.

**Comment by sethvargo** [comment]
Hi @danapplegate 

So I did some research. It looks like Chef 11 uses Ruby 1.9.3: https://www.chef.io/blog/2014/11/25/ruby-1-9-3-eol-and-chef-12/. It wasn't removed until 12.0.

**Comment by danapplegate** [comment]
Ah! That would explain it. I've also discovered that [OpsWorks uses `chef-client` in local mode](http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook.html) for 11.10:

```
Stacks running Chef 0.9 or 11.4 use Chef Solo and stacks running Chef 11.10 use Chef Client in local mode.
```

So, perhaps that has something to do with why OpsWorks' Chef runs use 2.0. I'll work more with them to figure out how they did it.

In any case, thanks for your help, @sethvargo!
