### ISSUE TITLE
Initial vagrant up when nic1 not set to NAT causes error

### ISSUE THREAD

**Issue by darkn3rd** [mitchellh/vagrant#6268]
**SUMMARY**: When ***nic1*** is not set to NAT, a `vagrant up` will fail.  The system can be brought up manually (used VirtualBox GUI) without any problem.  

There's further strange behavior, once system was brought though the GUI, `vagrant ssh` worked, but then it switched the ***nic1*** to NAT.  Then shutting down the system through the GUI, and doing `vagrant up` did not produce the same result, instead it looped on "Autentiation failure.  Retrying...".  Only seems to work on initial `vagrant up`.

Once the system is brought up with VirtualBox GUI, `vagrant ssh` seems to work.

**EXPECTED RESULT**: I had hoped that `vagrant up` would bring the system up, perhaps with a ***warning*** if ***nic1*** is not set to nat.

**ACTUAL RESULT**: Doing `vagrant up` yields:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "4378e159-9b12-4e3d-87b6-cd1b7261e241", "--natpf1", "ssh,tcp,127.0.0.1,2200,,22"]

Stderr: VBoxManage: error: A NAT rule of this name already exists
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component NATEngine, interface INATEngine, callee nsISupports
VBoxManage: error: Context: "AddRedirect(Bstr(strName).raw(), proto, Bstr(strHostIp).raw(), RTStrToUInt16(strHostPort), Bstr(strGuestIp).raw(), RTStrToUInt16(strGuestPort))" at line 1708 of file VBoxManageModifyVM.cpp
```

**VAGRANTFILE**:
```ruby
Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    client.vm.box = "hashicorp/precise64"
    client.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--macaddress1", "auto"]
      vbox.customize ["modifyvm", :id, "--nic1", "hostonly"]
      vbox.customize ["modifyvm", :id, "--hostonlyadapter1", "vboxnet2"]
    end
  end
end
```

**Comment by sethvargo** [comment]
Hi @darkn3rd 

Thank you for opening an issue. I believe you are encountering an error because of the default networking that Vagrant uses. I was able to get your Vagrantfile to work with one small addition:

```ruby
config.vm.network "private_network", ip: "33.33.1.10", auto_config: false
```

The default nic (nic1) will be used for the default network, thus causing a collision when you try to edit it.

Does that answer your question?

**Comment by mitchellh** [comment]
Sorry, in addition to what @sethvargo said: Vagrant _requires_ that NIC1 is NAT. We'd like to remove this requirement one day, but at this point that is a hard requirement. This is documented in the VirtualBox boxes page.
