### ISSUE TITLE
docker: support docker-machine (a.k.a. disallow docker host vm on non-linux hosts)

### ISSUE THREAD

**Issue by benjixx** [mitchellh/vagrant#6269]
The docker folks have released ```docker-machine``` this year, which allows you to manage docker hosts on different systems like VirtualBox, VMwareFusion, DigitalOcean, Amazon Web Services, Google Compute Engine, and many more. Additionally it enables you to run your familiar docker commands right from your local command line to work with the remote docker host.

When running it manually from the command line this is how things work (on MacOS X, Linux, and Windows):

```
# this is done once to create a new docker host
docker-machine --native-ssh create --driver digitalocean --digitalocean-access-token **** dev

# inject configuration about how to securely access remote docker host
eval "$(docker-machine env dev)"

# actually run a container
docker run -ti busybox /bin/bash
```

So, ```eval "$(docker-machine env dev)"``` sets some environment variables which make subsequent ```docker``` commands talk to the defined docker machine instead of the local one. At a first glance this seems to also support running ```docker build``` without a hassle (e.g. adding local files works fine).

Currently when using ```vagrant``` with ```docker``` provider on MacOS X there is no way to disallow the use of a vagrant docker host vm, thus there is no way to force the use of the ```docker``` command line client.

This issue is proposing to allow the ```docker``` provider to support the ```docker-machine``` injected configuration, and thus effectively talking to the ```docker-machine``` configured docker host.
Probably this can be accomplished by just detecting docker-machine env, and calling out to docker in the same way as on linux hosts.

**Comment by benjixx** [comment]
Also, I'm wondering if there is a workaround available, e.g. via some customized docker host Vagrantfile!?

**Comment by daiglej** [comment]
+1

I would rely want this feature.
To bad i am not a ruby guy otherwise i would do it myself...

**Comment by azngeek** [comment]
+1 

I have the same issue at the moment. I assumed that Vagrant will be aware of the variable ```$DOCKER_HOST``` to be able to connect to docker. Did someone figured out, how Vagrant identifies the docker host?

**Comment by radeksimko** [comment]
:+1: 

Exposing the docker settings would be very helpful to make Vagrant work well with Docker Compose.

Here's how I worked around that:

```sh
$ mkdir tls
```
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = 'moszeed/boot2docker'

  # Download certs
  command = "sudo cp /var/lib/boot2docker/tls/*.pem /vagrant/tls/"
  config.vm.provision :shell, :inline => command
end
```
```sh
$ vagrant up
```
```sh
export DOCKER_HOST=tcp://127.0.0.1:2376
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=./tls
```
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

The location of certs & docker ENV vars will obviously differ based on chosen vagrant box. `hashicorp/boot2docker` at the moment listens on `2375` and doesn't use TLS (= no certs) afaik, so that may be slightly easier.

**Comment by azngeek** [comment]
It is currently also possible to use the ```docker provider``` with the ```vagrant_vagrantfile```  as commented in https://docs.vagrantup.com/v2/docker/configuration.html . However i think it is an overhead, especially for Mac-users to have several different docker-hosts running. 

As long as one docker-host is running (identified by ```DOCKER_HOST```) there should be no need to boot up another instance.

**Comment by radeksimko** [comment]
@azngeek The main problem I personally have with the current version of docker provider is that it expects you to do the initial provisioning too - hence either `build_dir` or `image` [are required](https://docs.vagrantup.com/v2/docker/configuration.html).

This probably makes sense if it's called "docker provider" - it _provides you docker container_, not docker endpoint.

I'm thinking of using Vagrant only to spin up docker daemon inside the VM & do all the hard work with port forwarding, file sharing and expose it back to host to be used by Docker Compose.

**Comment by azngeek** [comment]
@radeksimko You are right. So we want to do the same thing i guess. Vagrant boots all containers on top of the existing host, for example provided with ```docker machine```

**Comment by radeksimko** [comment]
@azngeek Nope, the other way around. Docker Machine is serving similar purpose as Vagrant - to cover differences in environments (cloud, vbox, vmware, ...). I don't want to use Docker Machine, especially because it allows no file configuration, no DSL, nothing like Vagrant.

However Docker Compose (IMO) does much better job in scheduling containers than Vagrant does today and I think there should be an easy way how to use both (Docker Compose + Vagrant) together.

**Comment by benjixx** [comment]
@radeksimko Would you mind to discuss this in a different issue then? This issue here is about using vagrant with docker provider (talking to docker host configured via docker-machine).

**Comment by radeksimko** [comment]
@benjixx Sorry for messing up this thread due to my misunderstanding.
Just submitted https://github.com/mitchellh/vagrant/issues/6600

**Comment by wizwjw** [comment]
+1,  thus, we can have only one docker host vm.

**Comment by sethvargo** [comment]
This is possible as of https://github.com/mitchellh/vagrant/commit/8c11b537ba0b691b747f8f5089229033432d257f, which will be in the next release. Thanks!
