### ISSUE TITLE
Vagrant::Plugin::V2::Plugin.action_hook needs documentation

### ISSUE THREAD

**Issue by loren-osborn** [mitchellh/vagrant#6271]
The `action_hook` method here: 

[`lib/vagrant/plugin/v2/plugin.rb:72`](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/plugin/v2/plugin.rb#L72)

allows binding of callbacks to before or after specific vagrant events, but there is no documented list of valid events, or descriptions of when these events fire. I have scraped together a list of 21 events that I think may be valid, but am not clear on exactly which one happens under which circumstances, or if I've missed any. (I believe plugins can define their own custom events which would be beyond the scope of this issue.)

I am including a list of the events I found. Please add documentation for these, and any others I may have missed, to the doc block for the `action_hook` class method, and to the Plugin documentation.

* `:authenticate_box_url`
* `:environment_load`
* `:environment_plugins_loaded`
* `:environment_unload`
* `:machine_action_boot`
* `:machine_action_config_validate`
* `:machine_action_destroy`
* `:machine_action_halt`
* `:machine_action_package`
* `:machine_action_provision`
* `:machine_action_read_state`
* `:machine_action_reload`
* `:machine_action_resume`
* `:machine_action_run_command`
* `:machine_action_ssh`
* `:machine_action_ssh_run`
* `:machine_action_start`
* `:machine_action_suspend`
* `:machine_action_sync_folders`
* `:machine_action_up`
* `:provisioner_run`

**Comment by jgonera** [comment]
+1

**Comment by tony-ten** [comment]
^1+

**Comment by ceilingfish** [comment]
+1

**Comment by loren-osborn** [comment]
Thank you... this looks very helpful.

**Comment by alpha01** [comment]
:thumbsup:
