### ISSUE TITLE
Salt Windows bootstrap minion download path needs update?

### ISSUE THREAD

**Issue by moop-moop** [mitchellh/vagrant#6274]
vagrant/plugins/provisioners/salt/bootstrap-salt.ps1

line 54:
$url = "https://docs.saltstack.com/downloads/Salt-Minion-$version-$arch-Setup.exe"
change to
$url = "https://repo.saltstack.com/windows/Salt-Minion-$version-$arch-Setup.exe"

I noticed because the most recent salt minion version is not present in the original location, but is in the latter.

**Comment by PatOShea** [comment]
@sethvargo, can this be closed?

**Comment by iamseth** [comment]
While I'm a different Seth, I can confirm this is working for me and my coworkers :)
