### ISSUE TITLE
[salt] provisioner fails to copy minion config on 1.7.4

### ISSUE THREAD

**Issue by jcockhren** [mitchellh/vagrant#6276]
Hey all! This is more than just a reproduction #5973 (which you should read for context. I won't duplicate here).

The goal of this issue is to point out problems/solutions with bootstrap script usage introduced in 1.7.3. With a fresh install of vagrant 1.7.4 (host: Trusty64), #5936 does not fix issues seemingly introduced with #5435.
### Problems
1. We need a clear and consistent way of customizing the arguments passed to the bootstrap script. This was the reason why @timoguin created #5435. The [documentation surrounding `install_args` and `bootstrap_options`](https://docs.vagrantup.com/v2/provisioning/salt.html) should properly reflect the  ~~quirks~~ behaviour of saltstack's bootstrap script.
   - `bootstrap_options` applies to the flagged options passed the the bootstrap script that are required to appear first.
   - `install_args` are for arguments such as branch name and install type (e.g. stable, git)
2. The quickest way back to a _working_ state would be to revert **both** #5936 and #5435. 
3. We need [testing around `install_args` and `bootstrap_options` anyways](https://github.com/mitchellh/vagrant/blob/master/test/unit/plugins/provisioners/salt/config_test.rb)

I'm working on all 3. PR soon.

Thoughts? @timoguin @mitchellh @cachedout @thatch45

**Comment by babilen** [comment]
Is there anything  more that the community can help with to get this issue finally resolved?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
