### ISSUE TITLE
FR - allow virtualbox private_network dhcp lower/upper limits to be specified

### ISSUE THREAD

**Issue by halberom** [mitchellh/vagrant#6277]
At present, the virtualbox vboxnet that is created has the following params hardcoded
- cidr 172.28.128.0/24
- gateway 127.28.128.1
- dhcp server 127.28.128.2
- dhcp lower 127.28.128.3
- dhcp upper 127.28.128.254

I want to be able to specify static IP addresses in the same subnet, so I would like to be able to adjust the lower/upper boundaries to e.g.

- dhcp lower 127.28.128.50
- dhcp upper 127.28.128.254

If I try and change it directly in Virtualbox, I get this
```
A host only network interface you're attempting to configure via DHCP
already has a conflicting host only adapter with DHCP enabled. The
DHCP on this adapter is incompatible with the DHCP settings. Two
host only network interfaces are not allowed to overlap, and each
host only network interface can have only one DHCP server. Please
reconfigure your host only network or remove the virtual machine
using the other host only network.
```

If there's already a way of doing this, or some nice method I've missed, then I'm happy to be educated!

**Comment by mitchellh** [comment]
I just took a look and these are in fact configurable with `dhcp_lower`, `dhcp_upper`, etc. I'm adding this to the docs now!

**Comment by richard-scott** [comment]
Which documentation did you update, I can't find any reference of this on [here](https://www.vagrantup.com/docs/networking/private_network.html)?
