### ISSUE TITLE
chef provisioner is incompatible with chef <11.0

### ISSUE THREAD

**Issue by Tyrael** [mitchellh/vagrant#6278]
since 4b1847acf30c8ef46d499c41ed54736277f232aa we always add --force-formatter to the chef_arguments but that's only available since chef 11.0.
as chef 10 is EOL I think it is ok for vagrant to drop support for it, but it would be better if we would simply check the version and bail out with a meaningful error message that you should either upgrade your chef install in the box or downgrade your vagrant version.

**Comment by kisPocok** [comment]
+1

**Comment by Tyrael** [comment]
:bow:
