### ISSUE TITLE
Vagrant hyper-v provisioning

### ISSUE THREAD

**Issue by Mykolaichenko** [mitchellh/vagrant#6279]
Hi all!
I think I have a bug report. Firs of all, I setup new environment using this config: 

Vagrant.configure(2) do |config|
  config.vm.box = "ericmann/trusty64"
  config.vm.provider "hyperv" do |v|
          end
end

All was ok, after that I destroy VM. After destroying I make vagrant up VM. And have trouble: 

C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.4\plugins\providers\hyperv\scripts\get_vm_status.ps1 : Unable to fi
nd type [Microsoft.HyperV.PowerShell.VirtualizationOperationFailedException].
At line:1 char:1
+ &('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.4\plugins\prov ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Hyper...FailedException:TypeName) [get_vm_status.ps1], Runt
   imeException
    + FullyQualifiedErrorId : TypeNotFound,get_vm_status.ps1

It problem 100% reproduced. 

Thanks for all,
Oleg.

**Comment by yooakim** [comment]
This is probably the same as issu #6117

**Comment by Mykolaichenko** [comment]
@yooakim Maybe. Thanks!
