### ISSUE TITLE
No colored output in the latest Vagrant release?

### ISSUE THREAD

**Issue by joth** [mitchellh/vagrant#6281]
I'm on Windows 7 using Cygwin. I just updated to Vagrant 1.7.4 and no longer get any colored output. Has something changed to encourage this behavior?

**Comment by maoueh** [comment]
Duplicate of https://github.com/mitchellh/vagrant/issues/6026. Workaround it to define environment `VAGRANT_DETECTED_OS` and set to `cygwin`.

You add this to your `~/.bash_profile`:

    export VAGRANT_DETECTED_OS=cygwin

Please close the issue, thanks.
Matt

**Comment by joth** [comment]
Thanks!
