### ISSUE TITLE
Hosts file reset on vagrant up

### ISSUE THREAD

**Issue by alexbowers-tecmark** [mitchellh/vagrant#6284]
If i make a change to my hosts file, and then halt and up my box, the /etc/hosts file resets itself to the following state;

```
127.0.0.1 hostname hostname
127.0.1.1 hostname
# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```

**Comment by alexbowers** [comment]
It should be noted i think this is because I am defining a hostname in the Vagrantfile

**Comment by sethvargo** [comment]
Hi @alexbowers 

Thank you for opening an issue. This is not an issue with Vagrant; this is how hostnames work on linux. The `hostname` command is only valid for the current session. To persist the value, you need to edit `/etc/hostname`. Thanks!

**Comment by alexbowers** [comment]
@sethvargo The issue is with Vagrant. 

If i dont define a hostname in the vagrantfile, the hosts file does not reset itself.

I'll try to create a demonstration of the issue.

**Comment by sethvargo** [comment]
@alexbowers Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by alexbowers** [comment]
Okay. I seem to be unable to reproduce this anymore.

When this was originally an issue, I believe i was on version 1.6.x so perhaps going to 1.7 (which my home mac is on) has fixed it?

Either way. this can be closed.

Thanks.
