### ISSUE TITLE
VMware Fusion plugin: vagrant destroy should instantly turn off the VM

### ISSUE THREAD

**Issue by StefanScherer** [mitchellh/vagrant#6294]
Working with some Windows VM's I wish that the `vagrant-vmware-fusion` plugin would be faster doing a `vagrant destroy -f`.
The current behaviour is that the VM is shut down normally. This sometimes includes waiting for "Please do not turn off your computer, Windows Updates will be installed..." before throwing away the VM ;-)

But instead the VM could be just powered off in case of the `destroy` command. I think the VirtualBox provider already does this and makes the "vagrant destroy -f + vagrant up" feedback loop much faster.

My current version is: `vagrant-vmware-fusion (4.0.1)`

**Comment by jszakmeister** [comment]
+1.  I'd like to see this as well.

**Comment by mitchellh** [comment]
This is fixed now, in the next release of the plugin.

**Comment by StefanScherer** [comment]
Great! Thanks!
