### ISSUE TITLE
Vagrant replaces public key when shutting down a VM to be repackaged

### ISSUE THREAD

**Issue by carroarmato0** [mitchellh/vagrant#6295]
Vagrant 1.7.4

When repackaging an already existing VM while it is running, Vagrant will shutdown the VM first.

During the shutdown, it detects the insecure public key in /home/vagrant/.ssh/authorized_keys and replaces it with a host specific generated one for better security.

This results in a repackaged base box not containing the default insecure public key and the box not being usable by other people.

Workaround:  Shut down the VM first before repackaging to avoid Vagrant replacing the insecure public key.

Possible suggested solutions:   as part of the repackaging command, do not replace the key (or in fact, force the insecure one).  Or, depending on the provider, use the provider's API to send a shutdown signal.

More fan of the first option as Vagrant could perform some sterilization of the box before shutting it down and repackaging it.

**Comment by joth** [comment]
+1. `config.ssh.insert_key = false` is ignored

**Comment by mitchellh** [comment]
This is fixed!
