### ISSUE TITLE
Get cwRsync Working With Vagrant On Windows

### ISSUE THREAD

**Issue by connerbw** [mitchellh/vagrant#6297]
Hi.

Getting cwRsync to work with Vagrant on Windows is a pain.

This issue is a follow up to: #3230 and #4586

### Reading comprehension 101:

cwRsync is a standalone version of rsync for Windows that doesn’t require Cygwin to be installed. I don’t have Cygwin installed because Git For Windows includes Git Bash and this is “good enough.” With a regular standalone cwRsync installation Cygwin will never be in the PATH and Vagrant will never add the required /cygdrive prefix.

### Feature request

Following the advice (hacks) in the aforementioned tickets I was able to get it working, but it's not ideal. Looking at the Vagrant source it seems like it's trying to be too clever by detecting the environment when really all we need is some customization options. Specifically, ability to set drive prefix.

### More info:

http://kizu514.com/blog/get-cwrsync-working-with-vagrant-on-windows-10/

Thanks

**Comment by mitchellh** [comment]
This should all work very easily out of the box now! (with cwRsync on the PATH)
