### ISSUE TITLE
All Downloads are 403 Forbidden

### ISSUE THREAD

**Issue by Miserlou** [mitchellh/vagrant#6298]
This link is currently 403: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4.dmg

Maybe switch to GitHub for static binaries?

**Comment by tdheff** [comment]
All downloads are down, not just osx

**Comment by Miserlou** [comment]
Updated title.

GitHub is probably far more stable for releases these days.

**Comment by sethvargo** [comment]
Hi there,

Our upstream download provider is currently experiencing issues: https://status.hashicorp.com. We are working with them to resolve the issue. We appreciate your patience in this matter. The downloads will be available shortly.

**Comment by Miserlou** [comment]
Anybody have a mirror? I need this like.. literally right now.
