### ISSUE TITLE
Remove 

### ISSUE THREAD

**Issue by Idealien** [mitchellh/vagrant#6299]
From https://docs.vagrantup.com/v2/networking/private_network.html - Disable Auto Configuration

"If you already started the Vagrant environment before setting auto_config, the files it initially placed there will stay there. You'll have to remove those files manually or destroy and recreate the machine."

Could you provide more details on which files need to be manually removed?

I've got a VM which every time I run vagrant up on Windows host creates a new (duplicate) virtual host-only adapter. I can remove via the Device Manager but would prefer fix w/o recreating the machine and all DB entries of sites within it.

Relevant part of vagrantfile:

```ruby
Vagrant.configure(2) do |config|
     config.vm.network "private_network", ip: "127.0.0.1", auto_config: false
end
```

**Comment by mitchellh** [comment]
Done
