### ISSUE TITLE
download access forbidden

### ISSUE THREAD

**Issue by mohae** [mitchellh/vagrant#6300]
When trying to dowload Vagrant, https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4.msi, I get:
`forbidden!`

This happens with all links on https://www.vagrantup.com/downloads.html

**Comment by Giblin** [comment]
I was just going to post something about this.  I did some digging and if you go to: https://dl.bintray.com/mitchellh/vagrant/ every link on that page gives you the same forbidden message.

**Comment by sethvargo** [comment]
Hi there,

Our upstream download provider is currently experiencing issues: https://status.hashicorp.com. We are working with them to resolve the issue. We appreciate your patience in this matter. The downloads will be available shortly.

Best,
​Seth
