### ISSUE TITLE
Vagrant download gives 403 "Forbidden!"

### ISSUE THREAD

**Issue by troxler** [mitchellh/vagrant#6303]
e.g. https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4.dmg

**Comment by sethvargo** [comment]
Hi there,

Our upstream download provider is currently experiencing issues: https://status.hashicorp.com. We are working with them to resolve the issue. We appreciate your patience in this matter. The downloads will be available shortly.

Best,
​Seth
