### ISSUE TITLE
Shell is freezing

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#6320]
Not sure what's the problem, but my [VM](https://github.com/mycognitive/drupal-sandbox) is freezing very often, e.g.:

	vagrant@vagrant:/vagrant$ ll
	rm ^C^C^C^C^C
	^C^C^C

	^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C

	^Z^Z^Z^Z^Z^Z^Z^Z^Z
	(after few minutes it unfreeze it-self)
	vagrant@vagrant:/vagrant$ 

So the shell (bash) reacts on the keystrokes, but it's just delaying commands, or even when typing them in the middle.

The top stats in VM are fine, so nothing takes CPU:

	top - 08:43:03 up  1:12,  3 users,  load average: 0.14, 0.33, 0.19
	Tasks:  84 total,   1 running,  83 sleeping,   0 stopped,   0 zombie
	%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
	KiB Mem:   2048976 total,   587660 used,  1461316 free,    26220 buffers

This also include my host which has low load.avg as well.

Sometimes could happen when pressing Tab, but not always. If this would take few seconds so it wouldn't be an issue, but sometimes it takes minutes. Then I'm trying another session in new window, then the same happens after a short time. Even `cd /vagrant` sometimes takes 20-30 seconds to run.

In addition Apache is freezing as well, when go to the host address, it's saying: `ERR_CONNECTION_REFUSED`, then restarting Apache helps. 

This happens randomly, so it's difficult for me to reproduce it.

I'm using VBox 5.0.0r101573 and Vagrant 1.7.4

And my vm.box is `ubuntu/vivid64`.

Here is my [Vagrantfile](https://github.com/mycognitive/drupal-sandbox/blob/fc28ea9d8d689fe7b3f7c255da9b753fc87e504c/Vagrantfile).

**Comment by sethvargo** [comment]
Might be related to https://github.com/mitchellh/vagrant/issues/6248

**Comment by mitchellh** [comment]
Once the VM is running, Vagrant as a process isn't running at all. At that point, it is just your hypervisor. This is _very_ likely an issue with the hypervisor. However, if you can find a way for Vagrant to configure it to avoid this, please let us know and we will incorporate it.
