### ISSUE TITLE
Option for checksum when using remote shell provisioner

### ISSUE THREAD

**Issue by howardroark** [mitchellh/vagrant#6323]
Hey!

It would be great if a source hash could be supplied when using a remote file as the path of the shell provision option.

Is this something that the core team thinks would be a worthwhile addition?

Thanks!

**Comment by sethvargo** [comment]
Hi @howardroark 

Thank you for opening an issue. It is unclear what you mean by "remote file as the path of the shell provision option", but I presume you mean something like this:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "/path/to/the/script/already/on/the/guest.sh"
end
```

The recommended way to specify the shell is to either add a shebang to the file that you upload the guest, or specify the runner:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provision "shell",
    inline: "/bin/sh /path/to/the/script/already/on/the/guest.sh"
end
```

Does that answer your question?

**Comment by howardroark** [comment]
Basically you can specify a URL for the `path` option of the `shell` provisioner.  It would be nice if you could also specify a hash like md5 to verify the integrity of the downloaded file before running it.

**Comment by sethvargo** [comment]
Oh I see - you want a checksum attribute. Sounds like a reasonable thing.

**Comment by howardroark** [comment]
Yeah!  I guess that was a bit confusing :P  It is really handy to load "bootstrap" scripts direct from GitHub's servers.  Checking a sum would make it a little more secure.  

Thanks!
