### ISSUE TITLE
Why is Vagrant 1.7.4 insisting on having vagrant-windows installed when it's deprecated?

### ISSUE THREAD

**Issue by pjscopeland** [mitchellh/vagrant#6326]
Here's what I'm doing, on Ubuntu Trusty:

```bash
$ vagrant -v
Vagrant 1.7.4
```
```bash
$ vagrant init -fm opentable/win-7-professional-amd64-nocm
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
```
```bash
$ vagrant up --provider virtualbox
vagrant-windows missing, please install the vagrant-windows plugin!
Run this command in your terminal:
vagrant plugin install vagrant-windows
```
```bash
$ vagrant plugin install vagrant-windows
Installing the 'vagrant-windows' plugin. This can take a few minutes...
The plugin(s) can't be installed due to the version conflicts below.
This means that the plugins depend on a library version that conflicts
with other plugins or Vagrant itself, creating an impossible situation
where Vagrant wouldn't be able to load the plugins.

You can fix the issue by either removing a conflicting plugin or
by contacting a plugin author to see if they can address the conflict.

Vagrant could not find compatible versions for gem "winrm":
  In Gemfile:
    vagrant (= 1.7.4) ruby depends on
      winrm (~> 1.3) ruby

    vagrant (= 1.7.4) ruby depends on
      winrm-fs (~> 0.2.0) ruby depends on
        winrm (~> 1.3.0) ruby

    vagrant-windows (>= 0) ruby depends on
      winrm (~> 1.1.1) ruby
Vagrant could not find compatible versions for gem "vagrant":
  In Gemfile:
    vagrant-windows (>= 0) ruby depends on
      vagrant (~> 1.0.3) ruby

    vagrant (= 1.7.4) ruby
```

And everything I see on `vagrant-windows` says it's not needed any more as of 1.6. So why is Vagrant insisting on having it? And more to the point, how do I stand up my VM?

**Comment by jladage** [comment]
I have the same issue, running on El Capital with a fresh install

**Comment by pjscopeland** [comment]
I also posted this issue to [vagrant-windows](https://github.com/WinRb/vagrant-windows/issues/202).

As a result of their second answer, I ended up commenting out the lines in the box's Vagrantfile (at `~/.vagrant.d/boxes/[box]/[version]/virtualbox/Vagrantfile`) that threw the error. If I remember rightly, I did not have to unpackage or repackage anything.

**Comment by sethvargo** [comment]
Hi @pjscopeland 

Thank you for opening an issue. I can definitely sense your frustration, so please let me first apologize that this issue has bitten you.

When Vagrant evaluates a `Vagrantfile`, it does so recursively. You can read more about that here if you are interested: https://docs.vagrantup.com/v2/vagrantfile/. Part of that recursive evaluation is to look for a Vagrantfile embedded in the box. The box you are using has an old Vagrantfile that references and tries to install the plugin. This is not a bug in Vagrant, just an old Vagrantfile :smile: 

[As Sean said](https://github.com/WinRb/vagrant-windows/issues/202#issuecomment-143456693), you have three options:

1. Use a different box. One that doesn't check for vagant-windows.
1. Unpackage the box, remove the offending line in the Vagrantfile and repackage.
1. Downgrade to an older version of Vagrant and use vagrant-windows.

Please let me know if you have any questions, and again, I'm sorry you were hit with this issue! :smile:
