### ISSUE TITLE
Error when trying to start vagrant

### ISSUE THREAD

**Issue by ericramirez** [mitchellh/vagrant#6330]
I'm getting the following error when typing "vagrant up"

> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.

> Command: ["sharedfolder", "add", "6a1009af-c43b-4737-a25e-664602fbf401", "--name", "", 
> "--hostpath", "/home/eric/Documents/Laravel-projects"]

> Stderr: VBoxManage: error: Missing argument to '--name'

**Comment by sethvargo** [comment]
Hi @ericramirez 

Thank you for opening an issue. Unfortunately there is not enough information here to make an adequate diagnosis. That error is coming from Virtualbox, which may mean you have an outdated version of Vagrant or Virtualbox. To better diagnose this issue could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by ericramirez** [comment]
I managed to solve it (I don't remember how for the time being) but I had to reinstall my OS again, so... I lost all the logs. I'll have this in mind for the next time. Thanks @sethvargo
