### ISSUE TITLE
Enhancement: Vagrant commandline

### ISSUE THREAD

**Issue by lightningboss** [mitchellh/vagrant#6334]
I have an idea for a lot of vagrant commands: Whenever there is ONLY ONE virtual machine running, the command should notice that and apply that for that command.

For example: vagrant ssh
In my vagrant-machine directory I do "vagrant ssh" and it knows where to ssh in.
It is the only machine that is running.
Now I am in another folder and try "vagrant ssh". There is an error. I do "vagrant global-status" to get the ID of that virtual machine and do "vagrant ssh [ID]". (old workflow)
My suggestion: only do "vagrant ssh" and it knows where to ssh in (the machine that is running).

Whenever there are more than one virtual machines running, I'd do it like this: If you are in a vagrant-folder, you ssh into that machine. If not, you ssh into the last machine by doing (example!) "vagrant ssh -l" or "vagrant ssh --last".

**Comment by mitchellh** [comment]
Thanks for the enhancement request. This is an interesting idea, but not one we're interested in pursuing at the moment. This would make for a good plugin though so feel free to do that. Sorry!
