### ISSUE TITLE
Unable to `vagrant share`

### ISSUE THREAD

**Issue by robwilkerson** [mitchellh/vagrant#6335]
Myself and other team members are having issues using `vagrant share`. Every time we try to connect, we get the following:

    $ vagrant share                                                                                                                           19s
    ==> default: Detecting network information for machine...
        default: Local machine address: 192.168.33.10
    /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
      from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:878:in `open'
      from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
      from /opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
      from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:877:in `connect'
      from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
      from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:851:in `start'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:206:in `transmit'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:68:in `execute'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:35:in `execute'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/abstract_response.rb:82:in `follow_redirection'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/abstract_response.rb:41:in `return!'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:269:in `process_result'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:212:in `block in transmit'
      from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:206:in `transmit'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:68:in `execute'
      from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:35:in `execute'
      from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share/activate.rb:535:in `block (2 levels) in http_url?'
      from /opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
      from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share/activate.rb:534:in `block in http_url?'
      from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/retryable.rb:17:in `retryable'
      from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share/activate.rb:533:in `http_url?'
      from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.4/lib/vagrant-share/activate.rb:342:in `block (2 levels) in detect_forwarded_ports'

This just started happening for me over the weekend. It worked in the morning and then by the afternoon I was getting this. 

We all seem to be getting it at this point, so I don't _think_ this is a me problem, but I don't see anyone else mentioning it anywhere so maybe it's a me problem in some way I just haven't identified yet. Hoping someone here can help.

**Comment by ebray** [comment]
Just got this error message:
usxxbrayem2:project_one braye$ vagrant share
==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:  
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:  
    default: Local HTTP port: 4567
    default: Local HTTPS port: disabled
    default: Port: 2222
    default: Port: 4567
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
    default: Share will be at: subtle-shrew-4892
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.

**Comment by robwilkerson** [comment]
For whatever it's worth, I've gotten some kind of synchronization error once or twice as well, but I can't reproduce that one. The `getaddrinfo` is the one I've seen 99% of the time starting last weekend.

**Comment by robwilkerson** [comment]
Is anyone else seeing this? it's been going on for over 2 weeks now. If it's on my end, any ideas what it might be? I'm completely stuck here...

**Comment by ebray** [comment]
Sorry robwilkerson.  Mine was a "me" problem. ID10T error.  Haven't come across it since.  Had to do with my VPN settings.

**Comment by robwilkerson** [comment]
Care to elaborate? My issue may be similarly ID10T-worthy and I'm just not seeing it. I am able to share at least 1 other Vagrant project, so it's definitely a me issue.

**Comment by ebray** [comment]
Wish I could.  One of those "It's not working and I don't why.  Now it's working and I don't know why" moments.  vpn has been fussy in the past.  Reinstalled it.

**Comment by robwilkerson** [comment]
Alas, no VPN to blame it on here. :-) Thanks for following up.

Anyone else have any idea what could be generating this error? I've looked at working `Vagrantfile` content and I've tried commenting out almost all port forwarding. Similarly, all output up to the point of the error looks about the same.

**Comment by robwilkerson** [comment]
Turns out my Nginx config wasn't open enough. It wasn't answering to requests on the IP address which created the error, it seems.
