### ISSUE TITLE
vagrant always creates dot directories when VAGRANT_DOTFILE_PATH is set

### ISSUE THREAD

**Issue by erikj** [mitchellh/vagrant#6336]
When `VAGRANT_DOTFILE_PATH` is set, running any `vagrant` command in any directory w/ write privilege, including directories that don't include `Vagrantfile`s and commands that aren't `init`, *etc.*, results in a dot directory being added the current directory, which doesn't seem like should be the case and results in a lot of clutter of `vagrant` dot directories where there should be none.

```bash
$ unset VAGRANT_DOTFILE_PATH
$ mkdir demo
$ cd demo
$ vagrant --help
# ... helpful output
$ ls -a
./  ../
$ export VAGRANT_DOTFILE_PATH='.vagrant-demo'
$ vagrant --help
# ... helpful output
$ ls -a
./             ../            .vagrant-demo/
```

`vagrant` is an amazing tool that I enjoy using every (work) day, thank you for its development and support!

**Comment by mitchellh** [comment]
Ah, good catch! Working on this now.
