### ISSUE TITLE
Problem with rsync when vagrant sync chef-solo folders

### ISSUE THREAD

**Issue by psimonovsk** [mitchellh/vagrant#6337]
Hi.
I am working on provisioning of Linux (RHEL) boxes at AWS , using Vagrant with chef-solo provisioner.
Problem occurs at step, when Vagrant attempts to sync chef cookbooks folder.
________________________________________________________________________

```
Host path: /c/DevOps/cookbooks/
Guest path: /tmp/vagrant-chef/f8fe0df38f5a1a717e0cad4d37d84de3/cookbooks
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-pat
h sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'c:/DevO
ps/.vagrant/machines/dummy_l/aws/private_key' --exclude .vagrant/ /c/DevOps/cookbooks/ vagrant@<GUEST_>:/tmp/vagran
t-chef/f8fe0df38f5a1a717e0cad4d37d84de3/cookbooks
Error:
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.
```
________________________________________________________________________

When I drilled down to source of problem with our IT - it seems to be in option, that Vagrant passes to rsync:

```
-i 'c:/DevOps/.vagrant/machines/dummy_l/aws/private_key'
```

PRoblem is - that our corporate brandmauer prohibit outgoing SSL connections with private key. Only permited connections are - with user/password. 

I have customized my base AMI And it accepts SSH connections with user/password.So - it is not a problem. But , it seems that Vagrant aws plugin always build rsync command line - to connect with private key. And I do not find any option to change it... Is there any way to bypass those issue , without intervening in aws plugin source code?

**Comment by sethvargo** [comment]
Hi @psimonovsk 

Thank you for opening an issue. Unfortunately this looks like a bug in the vagrant-aws provider. Could you please open an issue [on that repo](https://github.com/mitchellh/vagrant-aws)? Thanks! :smile:

**Comment by psimonovsk** [comment]
Ok - I will do
