### ISSUE TITLE
this package required php 5.5.9

### ISSUE THREAD

**Issue by BardiaAfshin** [mitchellh/vagrant#6340]
I'm installing vagrant just so I don't have to modify my systems php version, however when I try to install via

```bash
composer install
```

I get the following error(s)
```
 Problem 1
    - This package requires php >=5.5.9 but your PHP version (5.4.43) does not satisfy that requirement.
  Problem 2...
```

So, this means I have to run my `composer install` command from within the vagrant box? How else would I bring in the vendor directory (without checking it into git).

the solution isn't apparent, it's catch 22 scenario.

**Comment by sethvargo** [comment]
Hi @BardiaAfshin 

Thank you for opening an issue, but this is not a Vagrant issue. That error is coming from Composer/PHP. Please open an issue on those repos for tracking. Thanks! :smile:

**Comment by BardiaAfshin** [comment]
thanks, gonna leave this closed, quick working solution on mac is to do
```bash
brew php-version
```

it'll allow multiple versions of PHP to be used, very similar to rvm package management for ruby world, without the gemsets and such.
