### ISSUE TITLE
Symlinks issue on Mac OS X (virtual box, vagrant, node, npm, binaries)

### ISSUE THREAD

**Issue by killmenot** [mitchellh/vagrant#6341]
#### Environment 
* Host: Mac OS X
* Guest: Centos 6
* VirtualBox:  5.0.4 r102546
* Vagrant: 1.7.4

I have a simple node app that has bower in dependencies. So during `npm install` I expect to see symlink at `./node_modules/.bin/bower`. However,  here is the error I got

```
==> default: npm ERR! Linux 2.6.32-358.el6.x86_64
==> default: npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
==> default: npm ERR! node v0.12.7
==> default: npm ERR! npm  v2.11.3
==> default: npm ERR! path ../mime/cli.js
==> default: npm ERR! code EPROTO
==> default: npm ERR! errno -71
==> default:
==> default: npm ERR! EPROTO, symlink '../mime/cli.js'
==> default: npm ERR!
==> default: npm ERR! If you need help, you may report this error at:
==> default: npm ERR!     <https://github.com/npm/npm/issues>
==> default:
==> default: npm ERR! Please include the following file with any support request
```

It seems the issue was introduced when I upgraded to the latest version of VirtualBox because it was without any issues on VB 4.3.x

Here is a ticket https://www.virtualbox.org/ticket/14563 that explain the issue. There is a link to test build  5.0.5r102721

**Comment by killmenot** [comment]
Closing this issue because just wanted to share information with community

**Comment by aronwoost** [comment]
Thanks!
