### ISSUE TITLE
X11 forward does not work with provisionner

### ISSUE THREAD

**Issue by kri5** [mitchellh/vagrant#6344]
Launching an X11 app using the shell provisionner doesn't work, but using vagrant ssh then launching the X11 app works.

Is there any difference between the way the provisionner connects to the machine and the way vagrant ssh does?

**Comment by sethvargo** [comment]
Hi @kri5 

They used to be different, but this was fixed in https://github.com/mitchellh/vagrant/pull/5928, which will be present in the next release! :smile:
