### ISSUE TITLE
Vagrant does not use domain\user when creating a scheduled task in windows

### ISSUE THREAD

**Issue by csharris** [mitchellh/vagrant#6345]
I'm running into the following error running "vagrant up" on a Windows guest:

```
==> default: Exception calling "RegisterTaskDefinition" with "7" argument(s): "The parameter
==> default:  is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))"
==> default: At C:\tmp\vagrant-elevated-shell.ps1:58 char:31
==> default: + $folder.RegisterTaskDefinition <<<< ($task_name, $task, 6, $username, $passwo
==> default: rd, 1, $null) | Out-Null
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : ComMethodTargetInvocation
==> default:  
==> default: Exception calling "GetTask" with "1" argument(s): "The system cannot find the f
==> default: ile specified. (Exception from HRESULT: 0x80070002)"
==> default: At C:\tmp\vagrant-elevated-shell.ps1:60 char:35
==> default: + $registered_task = $folder.GetTask <<<< ("\$task_name")
==> default:     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
==> default:     + FullyQualifiedErrorId : ComMethodTargetInvocation
==> default:  
==> default: You cannot call a method on a null-valued expression.
==> default: At C:\tmp\vagrant-elevated-shell.ps1:61 char:21
==> default: + $registered_task.Run <<<< ($null) | Out-Null
==> default:     + CategoryInfo          : InvalidOperation: (Run:String) [], RuntimeExcept 
==> default:    ion
==> default:     + FullyQualifiedErrorId : InvokeMethodOnNull
==> default:  
```

Here's my setup:
Host: Ubuntu Linux 15.04
Guest: Windows Server 2008 x64
Vagrant 1.7.4

My vagrantfile is pretty basic, I'm just trying to run the "chef_solo" provisioner. I'm assuming first that there is something wrong with my setup, so I pulled the Vagrant source code and looked at "plugins/communicators/winrm/scripts/elevated_shell.ps1". I tried to use the same code to create a scheduled task through powershell and received the same error as above. What did end up working was changing the "username" variable to be fully qualified ie: vagrant\vagrant. After doing this, the scheduled task is successfully created. 

Unfortunately, I do not see a way to set the username variable to "vagrant\vagrant" in the vagrantfile without messing up WinRM. Would anyone care to assist me? Thanks!

EDIT: Does not seem to be an issue when using Vagrant 1.7.2

**Comment by hernad** [comment]
this works:
It works like user winrm.user = user@domain:
<pre>
 config.winrm.username = "vagrant@vagrant"
 config.winrm.password = "vagrant"

  config.vm.guest = :windows
  config.windows.halt_timeout = 15

  config.vm.provision "shell", inline: "dir c:\\"
</pre>

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
