### ISSUE TITLE
provision docker install an old version of docker

### ISSUE THREAD

**Issue by casertap** [mitchellh/vagrant#6351]
In the stack it says downloading the last version of docker but it is not.

**Comment by sethvargo** [comment]
Hi @casertap 

Thank you for opening an issue. Unfortunately there is not enough information here to make an adequate diagnosis and reproduction case. What output do you see? What output do you expected? Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks! :smile:

**Comment by sethvargo** [comment]
Closing in favor of #6376, which has a little bit more information.
