### ISSUE TITLE
Vagrant share not working if connected to VPN or corporate network

### ISSUE THREAD

**Issue by rajeshbijja** [mitchellh/vagrant#6353]
Hi, 
I am using virtualbox(4.3.30) provider, with the image: kikitux/oracle65-1disk, version: 0.1
Vagrant Installed Version: 1.7.4
My host http port: 4567 is forwarded to the guest port: 80. Apache Http Server is running in the vm on port 80.
I am getting below error while trying vagrant share. Can you please help in resolving this issue.

```
==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:
    default: Local HTTP port: 4567
    default: Local HTTPS port: disabled
    default: Port: 2222
    default: Port: 4567
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
    default: Share will be at: decrepit-peccary-5165
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
```

**Comment by rajeshbijja** [comment]
Can anyone help me on this issue.
Please note that vagrant share works if I am not connected to our corporate network.
This issue is seen only when I am connected to VPN or corporate network.

**Comment by sethvargo** [comment]
Hi @rajeshbijja 

Thank you for opening an issue. Unfortunately this is occurring because your corporate network is not allowing Vagrant share to receive traffic back into the network (likely a firewall). You will need to work with your corporate IT team to get exemptions in place. Sorry! :frowning:
