### ISSUE TITLE
Windows host :Use existing host only adapter to allow non-admin usage

### ISSUE THREAD

**Issue by TomBZombie** [mitchellh/vagrant#6355]
I want non-administrative users to be able to run virtual boxes on a private network. Currently, when running `vagrant up` this brings up a "Enter admin password" prompt to create the adapter

I can add a host-only-network inside VirtualBox Preferences as an administrator and then use it as a non-admin user. Is there any way to force vagrant to use this adapter? And more importantly, will this allow non-admin users to use networking inside vagrant?

Apologies, I realise this isn't a bug report but it's not clear from the documentation if or how I can achieve this.

**Comment by sethvargo** [comment]
Hi @TomBZombie 

It is possible to force Vagrant to use a particular adapter (I believe its with the `virtualbox__inet` configuration option), but this will not necessarily allow non-admin users to utilize Vagrant. Virtualbox has, historically, required admin-level permissions to perform many operations on the system.

We can definitely discuss this more on the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up) if you'd like! :smile:
