### ISSUE TITLE
Slow commands

### ISSUE THREAD

**Issue by vsalaman** [mitchellh/vagrant#6357]
Hi:

I noticed that my commands were terribly slow to execute, so I started to try and figure out why. After a lot of work, I decided to build from source onto a clean RVMd 2.0.0. To my surprise, on my machine, the locally built copy runs at roughly twice the speed from the vagrantup.com supplied installable.

Any idea why this is happening?

*NOTE*: I've opted to create a script that replicates the launcher's functionality to present the case.

## Running environment

- OS: Mac OSX El Capitan
- Vagrant Version: 1.7.4
- Local version: built from git HEAD (a152045f81e3433c76640cae449a359de2c311bb)

## Plugins

 INFO global: Plugins:
 INFO global:   - bundler = 1.10.5
 INFO global:   - mime-types = 1.25.1
 INFO global:   - rest-client = 1.6.9
 INFO global:   - vagrant-share = 1.1.4

##  Debug output diff
```
--- l1.txt	2015-10-04 19:30:53.000000000 -0400
+++ l2.txt	2015-10-04 19:30:43.000000000 -0400
@@ -1,6 +1,6 @@
  INFO global: Vagrant version: 1.7.4
  INFO global: Ruby version: 2.0.0
- INFO global: RubyGems version: 2.0.14
+ INFO global: RubyGems version: 2.4.8
  INFO global: VAGRANT_DEFAULT_PROVIDER="virtualbox"
```
## Local version
``` bash
[salaman:~/work/vag/bin] $ time ./local-vagrant version
Installed Version: 1.7.4
Latest Version: 1.7.4

You're running an up-to-date version of Vagrant!

real	0m1.497s
user	0m1.295s
sys	0m0.181s
```
## Normal Vagrant
``` bash
[salaman:~/work/vag/bin] $ time ./prod-vagrant version
Installed Version: 1.7.4
Latest Version: 1.7.4

You're running an up-to-date version of Vagrant!

real	0m2.922s
user	0m2.701s
sys	0m0.198s
```

## Script: local-vagrant
``` bash
#!/bin/bash
BASE=/opt/vagrant
EMB=$BASE/embedded
VGEM=$EMB/gems/gems/vagrant-1.7.4
RPATH=~/.rvm/rubies/ruby-2.0.0-p647
export PATH=$RPATH/bin:$PATH
export CPPFLAGS=-I$EMB/include
export GEMRC=$EMB/etc/gemrc
export GEM_HOME=$EMB/gems
export GEM_PATH=$EMB/gems
export LDFLAGS=-L$EMB/lib
export SSL_CERT_FILE=$EMB/cacert.pem
export VAGRANT_EXECUTABLE=$VGEM/bin/vagrant
export VAGRANT_INSTALLER_EMBEDDED_DIR=$EMB
export VAGRANT_INSTALLER_ENV=1
export VAGRANT_INSTALLER_VERSION=2
ruby $VGEM/lib/vagrant/pre-rubygems.rb $@
```

## Script: prod-vagrant
``` bash
#!/bin/bash
BASE=/opt/vagrant
EMB=$BASE/embedded
VGEM=$EMB/gems/gems/vagrant-1.7.4
RPATH=$EMB
export PATH=$RPATH/bin:$PATH
export CPPFLAGS=-I$EMB/include
export GEMRC=$EMB/etc/gemrc
export GEM_HOME=$EMB/gems
export GEM_PATH=$EMB/gems
export LDFLAGS=-L$EMB/lib
export SSL_CERT_FILE=$EMB/cacert.pem
export VAGRANT_EXECUTABLE=$VGEM/bin/vagrant
export VAGRANT_INSTALLER_EMBEDDED_DIR=$EMB
export VAGRANT_INSTALLER_ENV=1
export VAGRANT_INSTALLER_VERSION=2
ruby $VGEM/lib/vagrant/pre-rubygems.rb $@
```

**Comment by mitchellh** [comment]
Vagrant executes Vagrant twice due to how our plugin system works. We're hoping to fix this in a future version but until then thats probably what you're seeing. We're focusing our speedup efforts into [Otto](https://ottoproject.io) right now (not nearly as stable as Vagrant but will get there). 

We're looking for big wins in Vagrant and swapping out the plugin system will gain us that: probably a double speedup. We'll be doing that like I said in a future version. Sorry!
