### ISSUE TITLE
vagrant ssh agent forwarding doesn't work on 1.7.4 but does on 1.7.2

### ISSUE THREAD

**Issue by gaffo** [mitchellh/vagrant#6362]
On mac yosemite I was unable to get ssh forwarding to show identities on the guest box, however when I reverted to 1.7.2 it worked without issue or config change.

**Comment by sethvargo** [comment]
Hi @gaffo 

Thank you for opening an issue, and I am sorry that you've experienced a regression with SSH forwarding. Unfortunately there is not enough information here to diagnose or reproduce this issue. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
