### ISSUE TITLE
Filesystem does not respond when composer creates the autoloader

### ISSUE THREAD

**Issue by PhillippOhlandt** [mitchellh/vagrant#6363]
Hey,

I have some issues when composer tries to create the autoloader. It happened on the installation of bolt.cm right before the installation.

First I thought it's a bolt.cm issue so I opened an issue there (https://github.com/bolt/bolt/issues/4219) but they told me it's the Vagrant filesystem that does not respond. 

I use a Macbook Pro (SSD) with El Capitan.

**Comment by sethvargo** [comment]
Hi @PhillippOhlandt 

Thank you for opening an issue, and I am sorry you are having issues with composer and autoloader. Are you using Vagrant? I don't see any mention of Vagrant in your post. If you are using Vagrant, could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html) so we can try to reproduce this issue?

**Comment by PhillippOhlandt** [comment]
Hey,

I use Laravel Homestead with Vagrant. After switching to NFS filesync, everything worked as it should.
