### ISSUE TITLE
If VAGRANT_HOME is not accessible, don't attempt to create it

### ISSUE THREAD

**Issue by cjke** [mitchellh/vagrant#6366]
Given the following, non-existing, export path:

    ## ~/.bash_profile
    export VAGRANT_HOME="/Users/me/v-test/v-home"

    ## terminal
    ls  /Users/me/v-test/v-home
    ls: /Users/me/v-test/v-home: No such file or directory

If I run an `vagrant up` vagrant will create the directory, see:

    ## terminal 
    vagrant up
    # output
    Vagrant failed to initialize at a very early stage:

    The home directory you specified is not accessible. The home
    directory that Vagrant uses must be both readable and writable.

    You specified: /Users/me/v-test/v-home

The output from vagrant is correct, and the home directory is not accessible. This is fine. However, re-running the above `ls`:

    ## terminal
    ls /Users/me/v-test/v-home
    boxes  data  gems (etc etc)

This is important because running vagrant off an external drive will create a `/Volumes/external-drive-path/vagrant-home-path/`if the drive isn't plugged in, and vagrant is up'ed. Then when you actually plug in the external drive, the actual drive gets mounted as `/Volumes/external-drive-path \1/`.

I'm not a ruby dev, but I suspect it has something to do with this line:
https://github.com/mitchellh/vagrant/blob/2c936b2e3722a84ca703e335e8cb2f19c09d670f/lib/vagrant/environment.rb#L726

Thank you for your ongoing awesome work with Vagrant

**Comment by sethvargo** [comment]
Hi @cjke 

Thank you for opening an issue. This is definitely a strange one... I think the issue is that `mkdir_p` is able to create _some_ of the files, but not all of them, which then fails. Would removing the files in the event of an error work for you?

**Comment by cjke** [comment]
I think either removing the files could work. Obviously you would need to do some pretty serious checking before you start clearing out a set of files (I don't know nearly enough about vagrant/ruby to comment on the approach). 

Could you do a simple directory exists check prior to even writing the files at all? And exit out early if it doesn't?

**Comment by sethvargo** [comment]
Hi @cjke 

The problem with that is that Vagrant _should_ try to create the directory if it doesn't exist - I think that's the correct behavior, but it's failing to do so. What we really need is database transactions for linux :smile:

**Comment by cjke** [comment]
Ah gotcha. Hmm tricky one... It's almost like the check should be if the parent exists, then try to create - but then it becomes very specific and a tad fragile.

**Comment by mitchellh** [comment]
Ah, yes, this is really tricky. I agree that what we want is some transaction style approach, ideally. Given we don't have that we can attempt a rollback of the files that it created but like you said it is really dangerous because imagine Vagrant has folders created alongside real data.

I actually think the safest approach here is to ignore the edge case. While it'd be better to have 100% perfect behavior, the downside of introducing code paths that might nuke important data is way too frightening. What do you think?

**Comment by cjke** [comment]
No worries. Thanks for keeping this (the github issue tracker as a whole) a very positive conversation. You guys are doing fantastic work
