### ISSUE TITLE
Installer won't go away for cDock 2

### ISSUE THREAD

**Issue by lloyd1981** [mitchellh/vagrant#6370]
Running 10.11 Beta (15A279b) v 8 Developer on two partitions and the full Release version on two others. Upon booting into each, cDock2 auto-installed, moved itself to the Applications folder, opened, and performed very well.

Problem is that every boot brings up the installer. Can either enter password and it goes away or simply click on cancel for original and two successive appearances and the installer finally closes and the dock features are released and reformat the dock.

For the previous version, constantly prompting okay for Start Up addition, I simply opened the package and moved the Helper to the desktop and the problem went away. With cDock2, I opened the package and moved the Installer app to the desktop. Stopped the constant reloading and the dock featured load without incidence during the normal boot course.

**Comment by sethvargo** [comment]
Hi there,

This appears to be opened on the wrong repo, since it has no mention of Vagrant. If this is an error, please open a new issue and include the Vagrantfile as well as the output of the command in debug mode. Thanks! :smile:
