### ISSUE TITLE
"Connection Timeout.Retrying..." On Centos platform

### ISSUE THREAD

**Issue by gilkedar** [mitchellh/vagrant#6371]
Hi:) I installed Vagrant on my centOS 6.7 (VirtualBox 5) but when i try to vagrant up i receive this message after creating the VM. i am using the centos6-build Vagrantfile.
I tried "vagrant init bentos/centos6.5" and other boxes and vagrantfiles relevant to centos but i still cant complete the vagrant up properly. the only time it worked for me was with the "vagrant init hashicorp/precise32" Vagrantfile and Box. 

Is there a specific problem with Vagrantfile? is there a recommended box to use? maybe compatability issues?

**Comment by gilkedar** [comment]
now i cant even get the precise32 box to get up. please i am desperate

**Comment by sethvargo** [comment]
Hi @gilkedar 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. Unfortunately there is not enough information here to diagnose or reproduce the issue. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

There were known issues with the initial release of VirtualBox 5 and rhel-based guests. Please make sure you upgrade to the latest Virtualbox as well.

**Comment by gilkedar** [comment]
Hi sethvargo.
Thank you very much for your response. 
I updated my Virtualbox and it actually seems to help:)
still, i can only connect to hashicorp/precise32
However, I am using Centos 6.7 and thus i need a compatible box.
i tried puphpet/centos65-x64 but it doesnt work.
My defauly centos, rhel6 vagrant directories dont work( using the updated 1.7.4)
Is there a stable centos box? do you have an idea how to fix the default Vagrantfiles to work? 
Thank you so much:)

**Comment by gilkedar** [comment]
Hi sethvargo.
Thank you very much for your response.
I deleted and reinstalled the updated virtualbox and vagrant.
It did help, since i could finally connect to hashicorp/precise32 box consistently, and the boxes were a little more updated.
However, precise64 and all the other default boxes, still failed with connection timeout. 
I am exhausted. I only need a good Centos box, but nothing works(i tried puphpet, etc...)
please help :( 
this is my vagrantfile:

![1](https://cloud.githubusercontent.com/assets/14829279/11038402/81d21310-870b-11e5-9eba-8571df0b4af0.JPG)

**Comment by gilkedar** [comment]
i successfully connected to another 32bit server: boxcutter/centos64-i386
and then i noticed this message:
![2](https://cloud.githubusercontent.com/assets/14829279/11040078/454da23a-8713-11e5-9cb3-2e7b99ecfb79.JPG)

Is this a Salt related problem? has to do with salt_bootstrap
Still, why cant i connect to the default centos6-build box?

**Comment by sethvargo** [comment]
Hi @gilkedar 

In the future, could you please paste your Vagrantfile as plain text using [GHFM](https://help.github.com/articles/github-flavored-markdown/) instead of a screenshot? It makes debugging and reading much easier.

The screenshots definitely look like issues with Salt. I also don't understand why you are changing the SSH forwarded port - Vagrant will automatically manage that.

**Comment by mitchellh** [comment]
Agreed with @sethvargo that this appears to be error output generated by Salt. Can you please report it upstream. You should be able to isolate it without Vagrant by running the command directly (within Vagrant).
