### ISSUE TITLE
MOUNTPOINT is empty

### ISSUE THREAD

**Issue by promethe42** [mitchellh/vagrant#6375]
Hi,

I'm using an upstart script to start some node services when the machine starts.
The code for those services is on a shared folder, so I'm using the "vagrant-mounted" upstart event.
I have multiple shared folders, so I'm also checking the $MOUNTPOINT env var to make sure the right folder has just been mounted (cf https://serverfault.com/questions/568026/how-can-i-get-vagrant-to-start-the-server-on-startup).

It doesn't work. Using echo I can see that $MOUNTPOINT is actually empty.

The expected behavior is to have $MOUNTPOINT set to the actual mounted shared folder dir (ex: "/vagrant").

Ubuntu Server 14.04
Vagrant 1.7.4
VirtualBox 5.0

I'm guessing the following log might be relevant:

```
INFO ssh: Execute: mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group www
-data | cut -d: -f3`,dmode=775,fmode=664 srv_minko-server /srv/minko-server (sud
o=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: chown `id -u vagrant`:`getent group www-data | cut -d: -f3`
/srv/minko-server (sudo=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: test -x /sbin/initctl && test 'upstart' = $(basename $(sudo
readlink /proc/1/exe)) (sudo=false)
DEBUG ssh: Exit status: 1
```

Regards,

**Comment by warrenseine** [comment]
Any idea?

I can see that the code is still [there](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb#L85) and hasn't really changed in a long time.

Just to be sure: the environment variable should be available in both `pre-start` and `start` scripts, shouldn't it?

**Comment by sethvargo** [comment]
Hi @promethe42 

Thank you for opening an issue. As @warrenseine said, that code is still present and remains unchanged. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by warrenseine** [comment]
We've finally found out that the correct syntax should be:
```
start on vagrant-mounted MOUNTPOINT=/path/to/mountpoint
```

We initially thought the environment variable would be available in the script to be checked for, but that's not the case. Specifying the variable in the `start` stanza guarantees the script will only trigger for that mount point.
