### ISSUE TITLE
Not the last version of docker

### ISSUE THREAD

**Issue by casertap** [mitchellh/vagrant#6376]
adding 
````
config.vm.provision :docker 
````
to a Vagrantfile install a version of Docker on the machine.
In the log it says (latest version) but it is far from being the latest version of docker that is installed on the VM.
The version 1.7.1 is installed but the last release is currently the 1.8.1.
Docker is a very active project and still very young.
I hope many bugs are corrected in the new release so how can I configure vagrant to use the last version of Docker?

(same thing for docker-compose)

**Comment by sethvargo** [comment]
Hi @casertap 

Thank you for opening an issue. Unfortunately there is not enough information here to make an adequate diagnosis and reproduction case. What output do you see? What output do you expected? Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks! :smile:

**Comment by mitchellh** [comment]
Closing due to lack of response. Sorry! Please reopen a new issue if you have a response to the above.
