### ISSUE TITLE
Is there a work around or a fix for the npm install issue on VirtualBox 5.x?

### ISSUE THREAD

**Issue by Tomson124** [mitchellh/vagrant#6380]
I want to upgrade to VB 5.0.6 but last time I upgraded to VB 5.x there was a issue with npm install and windows host as the paths were to long... 
Is this still a issue?

**Comment by sethvargo** [comment]
Hi @Tomson124 

Thank you for opening an issue. Unfortunately I am not familiar with the `npm` issue you are referring to. Do you have a link to an issue? I searched github issues but did not find anything.

**Comment by Tomson124** [comment]
Unfortunately most of the issues I refer to are already closed as this problem was fixed in Vagrant 1.7.3 but then reverted in 1.7.4, it was the UNC Path thing added to Windows hosts but in VB 5.x.x this option didn't worked at all.
This would be an issue adressing the problem: https://github.com/mitchellh/vagrant/issues/6409

**Comment by sethvargo** [comment]
Cool thanks! Let's track that issue :smile:
