### ISSUE TITLE
Allow override of proxied SSH for Docker containers running under a host VM

### ISSUE THREAD

**Issue by mgriego** [mitchellh/vagrant#6381]
If I forward a container's SSH port to the host VM (ie boot2docker), I can override the config.ssh settings for that Vagrant host to point to the correct hostname and port, but that's not enough to get it working.  Even with those setting in place, Vagrant will attempt to proxy the SSH connection through the host VM's ssh.  This appears to be due to a fault in the PrepareSSH class.  It forces the proxying if a host VM is in use, even if I have ports forwarded.  It would be nice to be able to override the use of the proxy if I've set up the config.ssh settings for the forwarded port.

On a related note, while I was trying to track this down, I was confused as to why the Docker provider doesn't just use the `ProxyCommand` functionality that's already baked in.  The Docker provider could use a default ProxyCommand if the user didn't override it that would create the tunnel through to the container.

I discovered this while trying to set up Unison to sync files from a host directly into an SSH-capable Docker container running under a host VM.

**Comment by mgriego** [comment]
The reference is line 11 in prepare_ssh.rb:

```
return @app.call(env) if !env[:machine].provider.host_vm?
```

If it could also use a configuration override to determine whether it should use direct SSH, that would definitely solve this issue.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
