### ISSUE TITLE
Multiple Windows boxes up

### ISSUE THREAD

**Issue by davidobrien1985** [mitchellh/vagrant#6388]
Not sure if this is a layer 8 issue or actual Vagrant problem.

I have two Vagrant environments configured (2 Vagrant files). They are completely seperate, but sometimes I need to have both up at the same time, because I'm doing multiple things at the same time.

Both environments have Windows boxes in them.

I'm using Virtualbox (latest version).

I start the first Vagrant environment and all is fine.

As soon as I start a second Vagrant environment that has a Windows machine configured it doesn't work because the winrm port has a conflict.

Here are my two Vagrantfiles:
```ruby
Vagrant.configure(2) do |config|

  config.vm.box = "ws2012r2ps5wazuremodule"
  config.vm.communicator = "winrm"
  config.vm.guest = :windows
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.network "forwarded_port", guest: 3389, host: 12356, auto_correct: true
  config.ssh.insert_key = false

end
```
```ruby
Vagrant.configure(2) do |config|

  config.vm.box = "ws2012r2ps5wazuremodule"
  config.vm.communicator = "winrm"
  config.vm.guest = :windows
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.vm.network "forwarded_port", guest: 3389, host: 12263, auto_correct: true
  config.ssh.insert_key = false

end
```

The error message I am getting when calling the second Vagrant up:
```ruby
➜  teamcity git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 55985 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 5985, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
```

Of course I could add all Windows into the same one Vagrantfile, but that would get messy over time and by that I couldn't seperate projects from each other.

I tried using forwarded_port already, but had no luck.

Thanks for you help!

**Comment by kikitux** [comment]
@danielbachhuber 

In the way way you are forwarding the port for RDP, you should do WinRM.

From documentation:
https://docs.vagrantup.com/v2/vagrantfile/winrm_settings.html
config.winrm.guest_port - The port on the guest that WinRM is running on. This is used by some providers to detect forwarded ports for WinRM. For example, if this is set to 5985 (the default), and Vagrant detects a forwarded port to port 5985 on the guest from port 4567 on the host, Vagrant will attempt to use port 4567 to talk to the guest if there is no other option

**Comment by davidobrien1985** [comment]
@kikitux are you sure? I am not changing the winrm port on my guest. The guest is still listening on 5985 or 5986. 

I have just configured this in a Windows box's Vagrantfile:
config.winrm.guest_port = '1111'

Vagrant up still gives me the same error.

**Comment by Faxmachinen** [comment]
Try setting config.winrm.port and config.winrm.guest_port as well as forwarding the ports in questions, e.g.:

`config.vm.network "forwarded_port", guest: 5985, host: 1111, id: "winrm", auto_correct: true
config.vm.network "forwarded_port", guest: 5986, host: 1112, id: "winrm_ssl", auto_correct: true
config.winrm.port = 1111
config.winrm.guest_port = 5985`
