### ISSUE TITLE
Local Host connection issue

### ISSUE THREAD

**Issue by Iasha102** [mitchellh/vagrant#6392]
Had some issue on connection local-host adapters. Connection failed every time. 
Found that will work if disable ipv6 in network manager. 
Vagrant 1.7.4
VirtualBox Version 5.0.6_OSE r103037
Arch linux 
Linux SomePC 4.1.10-2-lts #1 SMP Wed Oct 7 21:57:44 CEST 2015 x86_64 GNU/Linux

**Comment by mitchellh** [comment]
This appears to be an Arch configuration issue? I'm not sure how Vagrant is supposed to manage this. Please advise. Thanks!
