### ISSUE TITLE
Graceful shutdown never works for Debian Jessie on OS X

### ISSUE THREAD

**Issue by razvanphp** [mitchellh/vagrant#6393]
Hello,

After waiting for some time, eventually the machines is forcefully shutdown.

Running `sudo shutdown -h now` inside de VM works, and also sending ACPI shutdown signal from VirtualBox.

Debug log attached, seems it's stuck in a loop running `VBoxManage showvminfo`
http://pastebin.com/A2GHqADK

Thank you!

**Comment by dominikzogg** [comment]
https://github.com/mitchellh/vagrant/pull/6315

**Comment by mitchellh** [comment]
Fixed now
