### ISSUE TITLE
Vagrant Ignoring Provisioner Directives

### ISSUE THREAD

**Issue by spyderdyne** [mitchellh/vagrant#6397]
This is a duplicate of Issue #4375 disable virtualbox provider

This isnt working for me.  I have tried multiple ways of doing this and cannot seem to make it use the libvirt provisioner.  I was originally using Virtualbox and ran into some issues with it.  I then removed it, removed and reinstalled Vagrant (after deleting the ~/.vagrant.d folder and its contents,) and installed the libvirt components.  

```
cat /etc/issue
Ubuntu 14.04.3 LTS \n \l
```

```
vagrant --version
Vagrant 1.4.3
```

```
if [ $(dpkg-query -W -f='${Status}' vagrant 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  apt-get install -y vagrant
  vagrant plugin install vagrant-kvm
fi

if [ $(dpkg-query -W -f='${Status}' libvirt 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  apt-get install -y libvirt libirt-dev;
fi

if [ $(dpkg-query -W -f='${Status}' qemu-utils 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  apt-get install -y qemu-utils;
fi
```

I am getting this error now:

```
Creating Medusa Gorgon (server) Image
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

Creating Medusa Serpent (slave) Image
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

Medusa Image Creation Completed...
```

From the docs: https://docs.vagrantup.com/v2/providers/basic_usage.html

1.  I am setting the VAGRANT_DEFAULT_PROVIDER (2) in my image creation script here:

http://bazaar.launchpad.net/~openstack-tailgate/openstack-tailgate/trunk/view/head:/mythos/images/create-images.sh

It is ignored...

I am setting the provider in the Vagrantfile with config.vm.provider (3) here:

http://bazaar.launchpad.net/~openstack-tailgate/openstack-tailgate/trunk/view/head:/mythos/images/server/Vagrantfile

It is also ignored...

The only thing I have not tried is using the --provisioner (1) flag, but I shouldnt have to.  Am I using the wrong style of Vagrantfile or something?

Thanks.

**Comment by spyderdyne** [comment]
It would appear that my box only supports Virtualbox.  Need to Vagrant Mutate it to make it usable.  Using the nice instructions posted here:

https://www.djouxtech.net/posts/vagrant-with-libvirt/

**Comment by spyderdyne** [comment]
I believe the only issue I have now lies with vagrant list boxes not seeing them.  Off to the mailing list.

Thanks.

**Comment by sethvargo** [comment]
Hi @spyderdyne 

Thank you for opening an issue. It appears you are using a _very_ old version of Vagrant (1.4.3). The latest version is 1.7.4, and many things have changed. Please note that the packages provided by distros are heavily outdated and you must download the latest packages from releases.hashicorp.com. 

If you continue to experience issues after upgrading, please do let me know and we can revisit this! :smile:

**Comment by briancain** [comment]
@bvkin - the libvirt plugin is not officially supported by HashiCorp. Please open an issue with the libvirt project instead, thanks!
