### ISSUE TITLE
Low-latency rsync-auto

### ISSUE THREAD

**Issue by dkarlovi** [mitchellh/vagrant#6399]
When using `rsync` sync method with`rsync-auto`, I've noticed that there's quite a delay if the synced folder contains lots of files (say, 30k). By tracking the logon logs in my VM, I see that each sync event consists of this:

    Oct 13 14:26:26 app sudo:  vagrant : TTY=unknown ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/bash -l
    Oct 13 14:26:26 app sshd[14976]: Accepted publickey for vagrant from 10.0.2.2 port 33261 ssh2
    Oct 13 14:26:26 app sshd[14976]: pam_unix(sshd:session): session opened for user vagrant by (uid=0)
    Oct 13 14:26:26 app sudo:  vagrant : TTY=unknown ; PWD=/home/vagrant ; USER=root ; COMMAND=/usr/bin/rsync --server -vlDtprze.iLsfx --delete . /vagrant
    Oct 13 14:26:27 app sshd[14978]: Received disconnect from 10.0.2.2: 11: disconnected by user
    Oct 13 14:26:27 app sshd[14976]: pam_unix(sshd:session): session closed for user vagrant

This means that, for each file change, we need to:
  1. detect the change via FS event
  2. connect to Vagrant machine via SSH
  3. run the rsync process (on the whole monitored folder? not sure here)
  4. disconnect from Vagrant machine

Would it be possible to speed up the process by:
  1. creating a persistent SSH connection when running the initial `rsync-auto`
  2. detect the change via FS event
  3. run the rsync process **just on the file(s) that changed** (so it should scale well, no matter the file count)
  4. disconnect from SSH only when stopping `rsync-auto`

This should provide a near-instant file-sync experience, even with loads of files.

**Comment by nuncanada** [comment]
If I am correctly understanding what PathControl does, it is simply to speed up rsync connections, that is not the problem we are having. It isn't the rsync connection.

The problem we have in this ticket is that our filesystem tree is too big, ANY rsync to copy all the tree will take a minute or more...

The solution we want is to control what files and directories are changed at the host and issue the rsync ONLY for the changed files, not for the whole tree.

**Comment by dkarlovi** [comment]
@mitchellh, @nuncanada is correct. While faster SSH connections will resolve the connection problems, I feel that rsync itself is too slow for this use-case with large codebases, much of the time is spent finding the changes in the first place.

We can completely avoid this step as we KNOW which files changed via FS monitoring, I feel like doing a simple `scp` would be enough here.

**Comment by dkarlovi** [comment]
@sethvargo @mitchellh has the partial fix been merged in 1.8? Also, do you think some remedy might be possible for the second part (sync only what you know has changed).
