### ISSUE TITLE
Failure to mount vmhgfs with vmware_workstation provider on boot2docker

### ISSUE THREAD

**Issue by segfly** [mitchellh/vagrant#6402]
Using box https://vagrantcloud.com/codekitchen/boxes/boot2docker
On windows 8.1 with VMWare workstation 12.0.0 build-2985596
I receive the following error:

`vagrant init codekitchen/boot2docker; vagrant up`
```
 INFO ssh: Execute: mount -t vmhgfs -o uid=`id -u docker`,gid=`id -g docker` '.host:/-vagrant' /vagrant (sudo=true)
DEBUG ssh: stderr: mount: mounting .host:/-vagrant on /vagrant failed: Invalid argument

DEBUG ssh: Exit status: 255
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -t vmhgfs -o uid=`id -u docker`,gid=`id -g docker` '.host:/-vagrant' /vagrant

Stdout from the command:



Stderr from the command:

mount: mounting .host:/-vagrant on /vagrant failed: Invalid argument

 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::HandleForwardedPortCollisions:0x24cc348>
```

I only have the issue with boot2docker.iso. I created my own box using boot2docker 1.8.2 and experience the same issue. Once the VM is up, I can login to the shell and manually run `` mount -t vmhgfs -o uid=`id -u docker`,gid=`id -g docker` '.host:/-vagrant' /vagrant `` and all is fine. So I'm not sure what the issue is when using `vagrant up`.

When using a different box like ubuntu/trusty64 I do not have this issue. I tried to trouble shoot the issue quite extensively but because the vmware_workstation provider is obfuscated, I can't find exactly where or why the issue is occurring.

**Comment by kikitux** [comment]
@segfly 

Can you share a gist to:

`vagrant halt`
`VAGRANT_LOG=debug vagrant up`

**Comment by segfly** [comment]
@kikitux 

Not sure if you specifically needed vagrant halt for some reason. Because I have another problem where I can't bring up machines halted with vagrant. Vagrant is no longer able to login to the shell. You can see this here:
https://gist.github.com/segfly/adb95936af70d6d4a019

So, I also ran vagrant destroy / vagrant up --debug for you to see the mount problem:
https://gist.github.com/segfly/3d33f2fe5e29a6e84555

**Comment by segfly** [comment]
With the help of @kikitux it is clear that the vagrant mount operation is using a non-login shell, which in the boot2docker image does not have the path set to find `mount.vmhgfs`. The solution is to ensure that the PATH `includes /usr/local/sbin` for non-login shells. This will require a change to the box packer script generating this box to ensure the PATH is correctly set for non-login shells.

Thanks @kikitux!

**Comment by kikitux** [comment]
I have submitted a PR to fix this. 
Have a look at:
https://github.com/codekitchen/boot2docker-vagrant-box/pull/3
