### ISSUE TITLE
Vagrant started box correctly, but in VirtualBox it's shutted down

### ISSUE THREAD

**Issue by Nitaco** [mitchellh/vagrant#6405]
Hi,
I have got a problem with vagrant. When I start a vagrant machine it looks like, that the machine was booted correctly, but in VirtualBox it's still shutted down. 

$ vagrant ssh works!

$ ping 10.1.1.10 doesn't work!

request http://localhost:8090 works

request http://10.1.1.10 doesn't work 

connect via ssh in the git bash 
$ ssh vagrant@10.1.1.10 
doesn't work

When I was setting up the machine for the first time, it works perfect. After a reboot the problematic was there..

![schnappschuss_101715_085220_pm](https://cloud.githubusercontent.com/assets/15015252/10560626/f50ce5ba-7510-11e5-9a78-81193669d73b.jpg)
![schnappschuss_101715_085249_pm](https://cloud.githubusercontent.com/assets/15015252/10560631/0748b5a6-7511-11e5-9158-53581aece26c.jpg)

**Comment by sethvargo** [comment]
Hi @Nitaco 

Thank you for opening an issue. Unfortunately there is not enough information here to make an adequate diagnosis. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

Please note that, by default, the machine is not accessible on the ports you'd expect. For example, if you look at the output above, your webserver is running on port 8090, no 80. SSH runs on 2200, not 22, etc. Depending on what type of networking you specified, you may or may not be able to address the machine by IP.

**Comment by Nitaco** [comment]
Hi @sethvargo,
it happend once in a while. I will try to reproduce this issue next time and post my Vagrantfile in this issue ticket. Basically my machine works and I'm forwarding my ports to access the default ports. webserver, mysql e.g.

**Comment by sethvargo** [comment]
Hi @Nitaco 

That's great to hear. Without a reproduction case, it's hard for us to do anything though. I'm going to go ahead and close this issue. If it happens again, please open a new issue and include the debug output and Vagrantfile. Thanks! :smile:
