### ISSUE TITLE
Website broken in firefox on ubuntu 14.04

### ISSUE THREAD

**Issue by InsomniacSabbir** [mitchellh/vagrant#6411]
The menu bar is not working properly( in the sense of visual not functional). The menu bar is supposed to be on top. but come over the articles.

**Comment by sethvargo** [comment]
Hi @InsomniacSabbir 

Thank you for opening an issue. Could you please share a screenshot of the behavior?

**Comment by InsomniacSabbir** [comment]
Yes. Thank you.
I am attaching one.
![vagrant-problem](https://cloud.githubusercontent.com/assets/5733224/11070021/87a2559a-8803-11e5-8514-4e527541c8cf.png)

**Comment by sethvargo** [comment]
@captainill - could you take a look at this please?

**Comment by captainill** [comment]
@sethvargo can do!

**Comment by sethvargo** [comment]
This has been fixed. Thanks!
