### ISSUE TITLE
vagrant fails to reload a machine

### ISSUE THREAD

**Issue by ittayd** [mitchellh/vagrant#6414]
==> sparkvm: Setting hostname...
==> sparkvm: Mounting shared folders...
    sparkvm: /vagrant => C:/Users/idror/sparkvagrant
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chown `id -u vagrant`:`id -g vagrant` /vagrant

Stdout from the command:

Stderr from the command:

stdin: is not a tty
chown: changing ownership of ���/vagrant���: Not a directory

**Comment by sethvargo** [comment]
Hi @ittayd 

Thank you for opening an issue. This was a bug in Vagrant and it has been fixed. See https://github.com/mitchellh/vagrant/issues/5933.
