### ISSUE TITLE
many file IO operations failed

### ISSUE THREAD

**Issue by billypon** [mitchellh/vagrant#6416]
when I use vbox 4.x and old version vagrant(sorry, I forgot the version number), everything are fine.
after I update to vbox 5.0.0 and vagrant 1.7.4, many file IO operations are failed
such as "Operation not permitted", "Protocol error", "No such file or directory" when I copied or move directory

**Comment by sethvargo** [comment]
Hi @billypon 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. Unfortunately there is not enough information here to reproduce or diagnose the issue. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by billypon** [comment]
@sethvargo when I ran "vagrant up --debug > vagrant.log", I see more and more output infomation, but can't save in vagrant.log. My host os is win

**Comment by sethvargo** [comment]
Hi @billypon 

I am sorry you are having issues. What do you mean you can't save in `vagrant.log`? Do you get an error? Unfortunately I cannot help diagnose the issue if we do not have log output.

**Comment by billypon** [comment]
@sethvargo I mean debug info only print at screen, not save in vagrant.log. So I can't show you the log.

**Comment by sethvargo** [comment]
Hi @billypon 

What shell are you using?

**Comment by billypon** [comment]
@sethvargo I'm using cmd shell, command is `vagrant up --debug > vagrant.log`

**Comment by sethvargo** [comment]
Hi @billypon

Unfortunately without the debug logs, we are unable to provide assistance, and this does not appear to be a widespread Vagrant issue, or else we would see many other users experiencing similar issues. As such, I suspect this is something isolated to your local environment. I'm going to ask that you completely uninstall and re-install Vagrant, and if the issue persists, please open a _new_ issue and follow our new issue template. Thanks! :smile:
