### ISSUE TITLE
How to access running python in vagrant from host machine browser ?

### ISSUE THREAD

**Issue by mlotfi2005** [mitchellh/vagrant#6420]
Hi,
I installed Vagrant in windows, now I have a virtual ubuntu , I run a python script :

    vagrant@precise32:/vagrant/FlaskMysql/FlaskApp$ ls
    app.py  static  storedPro.txt  templates
    vagrant@precise32:/vagrant/FlaskMysql/FlaskApp$ python app.py
    * Running on http://127.0.0.1:5002/ (Press CTRL+C to quit)

I tried to access the above address from the browser in my window, but nothing happened, it was a blank page.

THanks.

**Comment by alexm92** [comment]
Hi @mlotfi2005 ,

First of all this is not an issue.
You can configure you VM with an specific IP that you can access from you local browser and in order to see the webapp you should run the application on 0.0.0.0 instead of 127.0.0.1

Good luck ;)

**Comment by sethvargo** [comment]
Hi @mlotfi2005 

Thank you for opening an issue. As another user already pointed out, this is not an issue with Vagrant. Please use the Vagrant mailing list for usage-based questions. We like to reserve the issue tracker for bugs and feature requests. Thanks! :smile:
