### ISSUE TITLE
using NFS shared directory on CentOS 6.6

### ISSUE THREAD

**Issue by sepetrov** [mitchellh/vagrant#6425]
I checked if an open issue about this exists and the only one similar to the problem here is https://github.com/mitchellh/vagrant/issues/5948.

Host OS: Mac OS El Capitan (version 10.11)
Guest OS: CentOS release 6.6 (Final)
VirtualBox: 5.0.8 r103449 

Vagrant log: https://gist.github.com/sepetrov/4dea153ae82a9028a70c

**Comment by sethvargo** [comment]
Hi @sepetrov 

Thank you for opening an issue. Can you please share your `Vagrantfile` as well?

**Comment by Akasurde** [comment]
@sepetrov  Could you please share `Vagrantfile` so that we can reproduce this issue ?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
