### ISSUE TITLE
No escaping for ssh-config

### ISSUE THREAD

**Issue by remram44** [mitchellh/vagrant#6428]
If I'm running Vagrant from a path that contains special characters, I expect Vagrant to escape them in the ssh-config output. Currently:
```
Host default
  HostName 127.0.0.1
  User vagrant
  ...
  IdentityFile "/private/tmp/test of "vagrant" plugin/.vagrant/machines/default/virtualbox/private_key"
```

**Comment by remram44** [comment]
Relevant code: [plugins/commands/ssh_config/command.rb#L49](https://github.com/mitchellh/vagrant/blob/b721eb62cfbfa93895d0d4cf019436ab6b1df05d/plugins/commands/ssh_config/command.rb#L49).

**Comment by mitchellh** [comment]
Can we escape it with `\"` ? I actually can't find any docs on this.

**Comment by sethvargo** [comment]
FYI, this broke some things, so going to revert: https://github.com/mitchellh/vagrant/issues/6929

**Comment by remram44** [comment]
This is annoying but I agree a consensus should probably be reached for the SSH config format before Vagrant can implement it.

Is there another way I can get the correct key filename?

FYI this is only a problem on Mac, since on Linux the key is in $HOME/.vagrant.d/ whereas Mac uses a path under the project path for some reason (which therefore has to be relatively sane for Vagrant not to crash).

Or perhaps the key could be put in a fixed location on Mac like it is on Linux?
