### ISSUE TITLE
Vagrant within VirtualBox

### ISSUE THREAD

**Issue by dzenanz** [mitchellh/vagrant#6434]
I am running VirtualBox 5.0.4 on Win7 x64, and I created an Ubuntu VM. Within that VM I tried to start a virtual machine using vagrant, but it fails. What is wrong?

```
dzenan@girderizer:~$ vagrant init hashicorp/precise64`
A \`Vagrantfile\` has been placed in this directory. You are now
ready to \`vagrant up\` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
\`vagrantup.com\` for more information on using Vagrant.
`dzenan@girderizer:~$ vagrant up`
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'hashicorp/precise64' could not be found.

```

```
dzenan@girderizer:~$ uname -a
Linux girderizer 3.19.0-31-generic #36~14.04.1-Ubuntu SMP Thu Oct 8 10:21:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shopblocks** [comment]
Does that machine has the box installed? If not you need to do a `vagrant box add hashicorp/precise64`

**Comment by dzenanz** [comment]
If it is not installed by default, then no. Trying these commands produce error messages:

`vagrant box add hashicorp/precise64`
This command was not invoked properly.

`vagrant box add hashicorp/precise64 https://atlas.hashicorp.com/hashicorp/boxes/precise64`
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format

**Comment by sethvargo** [comment]
Hi @dzenanz 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. Unfortunately there is not enough information here to make a diagnosis or reproduction. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by dzenanz** [comment]
Vagrantfile:
```
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
end
```
The command `dzenan@girderizer:~$ VAGRANT_LOG=debug vagrant up &>~/vagrant.txt` produces this output: https://pastebin.com/RxZcH3ns

**Comment by sethvargo** [comment]
Hi @dzenanz 

That error is different than your originally-reported error. You need to specify a box in your `Vagrantfile`:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
end
```

**Comment by dzenanz** [comment]
That Vagrantfile was a reworked example. When using
```
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
end
```
the output is this:
https://pastebin.com/91rQZUvx

**Comment by sethvargo** [comment]
@dzenanz you are using Vagrant 1.4.3. This is a _very_ old version of Vagrant. You can download the latest version of Vagrant from https://www.vagrantup.com/download.html

**Comment by dzenanz** [comment]
Well, I followed some tutorial about how to install Vagrant, VirtualBox etc and executed commands like `sudo apt-get install vagrant`. Since I never used Vagrant before, I didn't know that version of Vagrant which comes with the latest LTS Ubuntu is totally outdated.

With updated Vagrant, I run into another problem: VirtualBox does not work properly: `VT-x is not available (VERR_VMX_NO_VMX).` I guess that VM within VM is not a supported use-case.

Thanks for your help

**Comment by sethvargo** [comment]
Hi @dzenanz 

Virtualbox does not support nested virt.
