### ISSUE TITLE
Providers prune each others' entries in /etc/exports

### ISSUE THREAD

**Issue by erictrue** [mitchellh/vagrant#6439]
I'm writing a Vagrant provider for our cloud computing platform, and noticed that whenever I bring up a VirtualBox machine with nfs synced folders, it removes the entries for my provider's machines, and vice versa. This is probably because the provider's PrepareNFSValidIds action only knows about its own machines.

Is there a workaround for this? It appears that the vagrant-aws provider doesn't attempt to clean up its /etc/exports entries, but if we do the same, then ~~`vagrant resume` fails because mount returns an error: "mount.nfs: /synced is busy or already mounted".~~ doing a `vagrant up` of one provider's VM will result in "Stale NFS file handle" errors on the other provider's running VMs.

**Comment by spazquest** [comment]
Oops ... I've conflated two separate issues. Corrected the description.

**Comment by daiglej** [comment]
I experienced the same issue using some docker containers ... 
Here's the workaround i came up with ...

Hope that helps anyone..

   # Original Conatainer
    config.vm.define 'elasticsearch' do |container|
        container.vm.synced_folder '.', '/vagrant', disabled: true
        container.vm.provider 'docker' do |d|
        d.vagrant_vagrantfile = File.join(VAGRANTFILE_PATH, 'boot2docker/Vagrantfile')
        d.image = 'elasticsearch:1.7'
        end
    end

    #And the fix : 
   # WORKAROUND FOR https://github.com/mitchellh/vagrant/issues/6439
  # Back up the /etc/exports before it's get clubbed.
  config.trigger.before :ALL, :vm => ['elasticsearch', 'retail_catalog_search'] do
    info 'Backing up /etc/exports thats is about to be clubbed (WORKAROUND FOR ISSUE : https://github.com/mitchellh/vagrant/issues/6439)'
    info 'sudo /bin/cp -p /etc/exports /etc/exports.boot2docker.bak'
    system('sudo /bin/cp -p /etc/exports /etc/exports.boot2docker.bak')
  end

  # WORKAROUND FOR https://github.com/mitchellh/vagrant/issues/6439
  # Restore the /etc/exports after it got clubbed.
  config.trigger.after :ALL, :vm => ['elasticsearch', 'retail_catalog_search'] do
    info 'Restoring clubbed file : /etc/exports (WORKAROUND FOR ISSUE : https://github.com/mitchellh/vagrant/issues/6439)'
    info 'sudo /bin/cp -p /etc/exports.boot2docker.bak /etc/exports'
    system('sudo /bin/cp -p /etc/exports.boot2docker.bak /etc/exports');
  end

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
