### ISSUE TITLE
Upgrade the version for ubuntu 14.04

### ISSUE THREAD

**Issue by sonaliswetapadma** [mitchellh/vagrant#6441]
Hi I am using the ubuntu version 14.04
I want to upgrade the version of vagrant 1.4.3 to 1.5.0 or more than that.
Please suggest how to upgrade this.

**Comment by shopblocks** [comment]
For us, upgrading was simply downloading the latest version from vagrantup.com and then running through the installation.

After that, I had to close terminal and reopen and vagrant was there fine again.

This was on a mac, so may differ, but I imagine it is a similar process for ubuntu.
