### ISSUE TITLE
Debian and Ubuntu guest plugins don't leave localhost entries in /etc/hosts

### ISSUE THREAD

**Issue by charlieok** [mitchellh/vagrant#6446]
Before calling change_host_name:

/etc/hostname:
```
localhost
```

/etc/hosts:
```
127.0.0.1       localhost
```

After calling change_host_name:

/etc/hostname:
```
newhostname
```

/etc/hosts:
```
127.0.0.1 newhostname.fqdn.com newhostname
```

What we want instead for the new state of /etc/hosts is something more like:
```
127.0.0.1 localhost
127.0.1.1 newhostname.fqdn.com newhostname
```

This could be a common scenario for a VM template that doesn't know what its eventual hostname will be, and so starts out with the name 'localhost' (this is what I am currently working with).

When `change_host_name` is run, `@current_hostname` is set to the initial value in `/etc/hostname`. Later, when `update_etc_hosts` is run, that initial value is used in a search and replace in `/etc/hosts`. The comment on the `update_etc_hosts` method shows the intent:

```
        # /etc/hosts should resemble:
        # 127.0.0.1   localhost
        # 127.0.1.1   host.fqdn.com host.fqdn host
```

The authors and users of `update_etc_hosts` are expecting the second line to get updated or added but in this case we end up modifying the first line instead, destroying the association between `localhost` and the loopback address, which is almost certainly not what we intended.

Likely a related issue with the Fedora plugin, but that is another plugin so I don't consider it part of this issue: https://github.com/mitchellh/vagrant/issues/6202

Related discussion on StackOverflow (also Fedora): http://stackoverflow.com/questions/33117939/vagrant-do-not-map-hostname-to-loopback-address-in-etc-hosts

**Comment by johnoooo** [comment]
This also happens on CentOS 6 and CentOS 7

**Comment by johnoooo** [comment]
Is this a good thread to discuss this "feature"? In my opinion, this implicit mangling of /etc/hosts is not a good idea at all. 

First, binding global DNS names to a localhost interface is somehow a contradiction itself (global names vs local-only interface). I have never seen this before and doubt that it makes real sense.

Except of this "not-seen-before" ... at least this hosts-mangling is not implemented in a sufficiently generic way by only having the most basic networking model with one private network interface in mind. 

For the case with a private and a public network interface, e.g., in a multi-machine setup, the things go completely wrong
```
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network :public_network, ip: "192.168.99.99", netmask: "255.255.255.0", bridge: "eno1"
  config.vm.hostname = "test.mydomain"
end
```

This results in a /etc/hosts file of
```
127.0.0.1   test.mydomain test localhost localhost.localdomain localhost4 localhost4.localdomain4
::1       
```
completely ignoring the public network interface. Here, I would assume that the hostname should be bound to the public IP address. In the implemented Vagrant version, harm occurs when the hostname is used by any application to determine the IP address to which they bind to. In this case, such applications will not be visible on the public network interface.

So my suggestion would be: keep the fingers off from /etc/hosts! If needed, i.e., when it is not sufficient to use "localhost" to point to the local interface, the users should do the modifications to /etc/hosts on their own. I guess the possible network models are too complex to be handled by a generic method.

**Comment by charlieok** [comment]
For what it's worth, I wasn't going into any great consideration over what the "right" approach is -- just fixing a bug that was actively getting in my and my team's way.

**Comment by johnoooo** [comment]
yes, it is the wrong place to discuss this topic here.
I will make it an issue of its own.
Sorry.

**Comment by johnoooo** [comment]
done .... see #7263
