### ISSUE TITLE
Public network configuration doesn't work on OSX, El Capitan.

### ISSUE THREAD

**Issue by jinhoyoo** [mitchellh/vagrant#6448]
I'm using vagrant 1.7.4 on Mac OSX El Capitan 10.11.1. I configured public network like below. 

```
  config.vm.network "public_network", :bridge => 'en0: Wi-Fi (AirPort)', ip:"192.168.18.31"
```
 But I found it doesn't work on my mac but work on PC.  I cannot access VM with 192.168.18.31 from other real computer.  I'm using virtual box 5.0.8 r103449.  Also I turned off firewall too.

**Comment by sethvargo** [comment]
Hi @jinhoyoo 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. Unfortunately there is not enough information here to reproduce or diagnose the issue. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by jinhoyoo** [comment]
@sethvargo, here the log file that I run vagrant with debug option. I think OS X blocks the incoming connection of Vagrant. So I think we can solve if I open the incoming connection of vagrant. But I cannot assign the execution file of vagrant on the configuration of firewall in OS X.

**Comment by mitchellh** [comment]
This is fixed in master I believe. We just merged stuff to do more advanced networking on Darwin.
