### ISSUE TITLE
vagrant halt and reload unable to find shutdown command in RedHat guest

### ISSUE THREAD

**Issue by gawbul** [mitchellh/vagrant#6449]
I have been attempting an auto-reboot using the vagrant-vbguest plugin. I have also tried using the vagrant-reload plugin, as well as manually issuing a `vagrant reload` and `vagrant halt` command from my host. In all cases I get the following error:

```
$ vagrant halt
==> default: Attempting graceful shutdown of VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

shutdown -h now

Stdout from the command:



Stderr from the command:

/bin/bash: line 3: shutdown: command not found
```

I'm using a rhel7-workstation image as the base box. The shutdown command is located at `/usr/sbin/shutdown` in the guest.

**Comment by gawbul** [comment]
I've fixed this by adding the 'halt' 'guest_capability' to 'plugin.rb' in the 'plugins/guests/redhat' directory, and adding a 'halt.rb' file under the 'cap' subdirectory that calls '/usr/sbin/shutdown -h now'.

**Comment by gawbul** [comment]
I tried modifying the default linux `halt.rb` to run a `\`which shutdown\` -h now`

**Comment by gawbul** [comment]
Seems related to https://github.com/mitchellh/vagrant/pull/6415

**Comment by sethvargo** [comment]
Hi @gawbul 

I just tried a few different RHEL 7 boxes and I am unable to reproduce this issue. The `shutdown` command is in the `PATH` by default. Do you have a specific box you are using? I think it may be a bug with that box and not necessarily a bug in Vagrant.

**Comment by gawbul** [comment]
@sethvargo I'm using a custom rhel7 box that we've uploaded to Atlas (though not publicly available). Its running `Red Hat Enterprise Linux Server release 7.1 (Maipo)`. We created it using Packer from the rhel7 iso I believe? We use Chef for provisioning, so I should probably check that some files/environment variables aren't being modified.

The fact that this is occurring at all though, means the current method of assuming that shutdown is available in the `$PATH` is unstable in some circumstances (hence the ability to add the halt guest_capability), which required me to modify the Vagrant source. I think hard coding the PATH into the default linux halt script will mean not having to create halt scripts for individual guests in the future? Is there any reason that wouldn't be a better option?

**Comment by sethvargo** [comment]
Hi @gawbul 

> assuming that shutdown is available in the $PATH is unstable in some circumstances

This is a very safe assumption. I'm going to add this to the documentation to make it clearer, but Vagrant cannot possibly search every possible path to find a shutdown command. A base RHEL 5, 6, and 7 all have the proper $PATH set, so I believe there is something in your provisioning that is altering that PATH from its default value.

Each linux distro has their own take on where they put their shutdown script. Sometimes it's in `/bin`, `/sbin`, `/usr//bin`, `/usr/sbin`, etc. Vagrant could attempt to guess and prepend a PATH option for all these "common" places, but there will always be an edge case.

> I think hard coding the PATH into the default linux halt script will mean not having to create halt scripts for individual guests in the future?

I tried a number of different guests (I have a least 30 different red hat and centos boxes downloaded locally to test this), and I'm unable to reproduce. Additionally, Vagrant is a very large project; we would have expected multiple users to have reported this issue if it were truly a bug. Instead, I think the PATH on your custom box is being modified from the default value, breaking Vagrant's capability.

**Comment by gawbul** [comment]
@sethvargo Thanks for the update, and apologies for any inconvenience. This was using a vanilla rhel7 iso, which is what initially threw me off, but I guess there must be something occurring in the provisioning stages that is doing something weird to the PATH? I'll investigate further my end.

I personally still think that prepending a PATH variable with a list of common default locations to the `machine.communicate.sudo` method call would reduce the need to implement custom halt guest capability modifications for a number of distributions, and make it easier to manage in the long-term, but I understand you have to prioritise your efforts.

**Comment by codecowboy** [comment]
Also getting this error on a Centos 6.7 vagrant box.

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
```
shutdown -h now

Stdout from the command:

Stderr from the command:

/var/tmp/sclQJJcO1: line 8: -E: command not found
```

Did anyone get to the bottom of this?

**Comment by gawbul** [comment]
Editing `/opt/vagrant/embedded/gems/gems/vagrant-1.8.0/plugins/guests/linux/cap/halt.rb` (change `vagrant-1.8.0` to reflect your installed vagrant version) and changing the `machine.communicate.sudo` line to `machine.communicate.sudo("PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin shutdown -h now")` worked for me.

**Comment by gawbul** [comment]
@codecowboy Out of interest, what centos image were you using for this?

**Comment by codecowboy** [comment]
https://vagrantcloud.com/box-cutter/boxes/centos67
