### ISSUE TITLE
FTPPWD not working on my Vagrant Machine

### ISSUE THREAD

**Issue by bgayathri** [mitchellh/vagrant#6454]
One of my shell scripts running in my Vagrant Box uses ftppwd command.

However the command is not working from my Vagrant machine.

I have used a precise64-ubuntu virtual box.

Can anyone please help.

Error:
vagrant@dev-hadoop:~$ ftppwd
ftppwd: command not found

I have below packages installed,

vagrant@dev-hadoop:~$ whereis ftp
ftp: /usr/bin/ftp /usr/bin/X11/ftp /usr/share/man/man1/ftp.1.gz
vagrant@dev-hadoop:~$ whereis linux
linux: /usr/include/linux
vagrant@dev-hadoop:~$ whereis sftp
sftp: /usr/bin/sftp /usr/bin/X11/sftp /usr/share/man/man1/sftp.1.gz

**Comment by kikitux** [comment]
Hello,

We try to keep github issue for issues that impact Vagrant.

We have the mailing list for general questions.

Per log it seems the command you are trying to run is not on the path or not installed.

Happy to follow up over the mailinglist

Alvaro

**Comment by bgayathri** [comment]
Okay, it would be great if someone can help me or guide me in getting the required package installed for getting ftppwd working.

Thank you!!

**Comment by kikitux** [comment]
@bgayathri have you sent your email to the mailing list? Waiting there for that.
