### ISSUE TITLE
Issues while installing librarian-chef on windows 

### ISSUE THREAD

**Issue by ynagarjuna1995** [mitchellh/vagrant#6455]
```
vagrant plugin install vagrant-librarian-chef
Installing the 'vagrant-librarian-chef' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing chef (12.0.3), and Bundler cannot continue.
Make sure that `gem install chef -v '12.0.3'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    rake RUBYARCHDIR=C:/Users/Nagarjuna/.vagrant.d/gems/gems/chef-12.0.3-x86-mingw32/lib RUBYLIBDIR=C:/Users/Nagarjuna/.vagrant.d/gems/gems/chef-12.0.3-x86-mingw32/lib
checking for windmc... yes
checking for windres... yes
checking for gcc... yes
windmc chef-log.man
windres -i chef-log.rc -o resource.o
gcc -o chef-log.dll -shared resource.o
rake aborted!
Errno::EIO: Input/output error - RegCreateKeyEx
C:/Users/Nagarjuna/.vagrant.d/gems/gems/win32-eventlog-0.6.1/lib/win32/eventlog.rb:224:in `add_event_source'
C:/Users/Nagarjuna/.vagrant.d/gems/gems/chef-12.0.3-x86-mingw32/ext/win32-eventlog/Rakefile:44:in `block in <top (required)>'
Tasks: TOP => default => register
(See full trace by running task with --trace)


Gem files will remain installed in C:/Users/Nagarjuna/.vagrant.d/gems/gems/chef-12.0.3-x86-mingw32 for inspection.
Results logged to C:/Users/Nagarjuna/.vagrant.d/gems/gems/chef-12.0.3-x86-mingw32/ext/win32-eventlog/gem_make.out
```

I have tried installing chef gem manually . it gives error as shown below 

```
gem install chef -v '12.0.3'
ERROR:  Could not find a valid gem 'chef' (= 12.0.3), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```

**Comment by DonMartin76** [comment]
Experiencing exactly the same issue.

**Comment by DonMartin76** [comment]
I found this which describes similar problems (which are said to be resolved):

https://github.com/chef/chef/issues/3125

And alas, running the DOS box as administrator seems to resolve this.

**Comment by ynagarjuna1995** [comment]
@DonMartin76  I have tired running with administrative privileges  but no use Still experiencing same issue

**Comment by sethvargo** [comment]
Hi @ynagarjuna1995 

What terminal are you using (powershell, git-bash, cwgwin)?

**Comment by ynagarjuna1995** [comment]
@sethvargo 

I have tried command Prompt,Git Bash,Power shell  with administrative permissions in Windows 10

BUt in all cases I am encountering same issues ..

Problem with POSIX.rb file everytime.

**Comment by ynagarjuna1995** [comment]
@sethvargo 

Kindly look at this Vagrant `Chef` plugin needs `chef 12.0.3` but I am encountering problems while installing it ..Please take a look below  I was able to install latest chef without any issues but case is different for `chef 12.0.3`
    
   PS C:\Users\Nagarjuna> gem install chef
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed chef-12.5.1-universal-mingw32
Parsing documentation for chef-12.5.1-universal-mingw32
Done installing documentation for chef after 29 seconds
1 gem installed
PS C:\Users\Nagarjuna> gem install chef -v '12.0.3'
Fetching: win32-eventlog-0.6.1.gem (100%)
Successfully installed win32-eventlog-0.6.1
Fetching: win32-mmap-0.4.0.gem (100%)
Successfully installed win32-mmap-0.4.0
Fetching: win32-service-0.8.2.gem (100%)
Successfully installed win32-service-0.8.2
Fetching: win32-process-0.7.3.gem (100%)
Successfully installed win32-process-0.7.3
Fetching: win32-mutex-0.4.1.gem (100%)
Successfully installed win32-mutex-0.4.1
Fetching: win32-event-0.6.1.gem (100%)
Successfully installed win32-event-0.6.1
Fetching: win32-dir-0.4.5.gem (100%)
Successfully installed win32-dir-0.4.5
Fetching: win32-api-1.5.1-universal-mingw32.gem (100%)
Successfully installed win32-api-1.5.1-universal-mingw32
Fetching: windows-api-0.4.2.gem (100%)
Successfully installed windows-api-0.4.2
Fetching: ffi-yajl-1.4.0.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed ffi-yajl-1.4.0
Fetching: hashie-2.1.2.gem (100%)
Successfully installed hashie-2.1.2
Fetching: chef-zero-3.2.1.gem (100%)
Successfully installed chef-zero-3.2.1
Fetching: ohai-8.4.0.gem (100%)
Successfully installed ohai-8.4.0
Fetching: chef-12.0.3-x86-mingw32.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing chef:
        ERROR: Failed to build gem native extension.

    C:/RailsInstaller/Ruby2.1.0/bin/ruby.exe -rubygems C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/chef-12.0.3-x86-mingw32 RUBYLIBDIR=C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/chef-12.0.3-x86-mingw32
checking for windmc... yes
checking for windres... yes
checking for gcc... yes
windmc chef-log.man
windres -i chef-log.rc -o resource.o
gcc -o chef-log.dll -shared resource.o
rake aborted!
Errno::EIO: Input/output error - RegCreateKeyEx

Tasks: TOP => default => register
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/chef-12.0.3-x86-mingw32 for inspection.
Results logged to C:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0/chef-12.0.3-x86-mingw32/gem_make.out

**Comment by sethvargo** [comment]
Hi @ynagarjuna1995 

Please open an issue on the Chef repo if you are having problems installing Chef. This is the Vagrant repository. When you run `gem install`, that is installing into your system ruby, not Vagrant's ruby. What version of Vagrant are you running? Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by mitchellh** [comment]
Closing due to lack of response. Sorry! Please reopen a new issue if you have a response to the above.
