### ISSUE TITLE
'vagrant box add" fails to handle metadata.json when loading from url

### ISSUE THREAD

**Issue by JoergFiedler** [mitchellh/vagrant#6457]
Hi,

maybe I am using it wrong, but I can not add a box which is described within a `metadata.json` when this file is downloaded from any url. If I use a local version of the same file, everything works fine. 

The `metadata.json` file in question can be found here: https://raw.githubusercontent.com/JoergFiedler/freebsd-box/master/metadata.json.

If I use a local copy of this file and run 

```
vagrant box add --name JoergFiedler/freebsd-box  metadata.json --provider virtualbox
```

everything works as expected, but when I execute

```
vagrant box add --name JoergFiedler/freebsd-box  https://raw.githubusercontent.com/JoergFiedler/freebsd-box/master/metadata.json  --provider virtualbox
```

the command fails with the following output.

    ==> box: Box file was not detected as metadata. Adding it directly...
    ==> box: Adding box 'JoergFiedler/freebsd-box' (v0) for provider: aws
        box: Downloading: https://raw.githubusercontent.com/JoergFiedler/freebsd-box/master/metadata.json
    The box failed to unpackage properly. Please verify that the box
    file you're trying to add is not corrupted and try again. The
    output from attempting to unpackage (if any):

    bsdtar: Error opening archive: Unrecognized archive format

The same error occurs when I use the url for `vm.box_url` within a Vagrantfile. Am I doing something wrong?

**Comment by pdxfixit** [comment]
+1

**Comment by mitchellh** [comment]
The issue is that the content type that server is returning is `text/plain`. Vagrant's metadata protocol requires an `application/json` response.

**Comment by pdxfixit** [comment]
Thanks, @mitchellh. Will Vagrant also follow 30x HTTP redirects in this scenario?  I'm currently having problems when our server responds w/ a 303.

**Comment by mitchellh** [comment]
@pdxfixit It already should be, we use redirects heavily with Atlas URLs so it must be working. Vagrant will follow up to 10 redirects.

**Comment by JoergFiedler** [comment]
Thanks … everthing works as expected with the following URL [https://cdn.rawgit.com/JoergFiedler/freebsd-box/master/metadata.json](https://cdn.rawgit.com/JoergFiedler/freebsd-box/master/metadata.json)

**Comment by po2go-jessica** [comment]
I Could not find the file. Do you have a new URL for it?
