### ISSUE TITLE
Couldn't fetch specs from gems.hashicorp.com

### ISSUE THREAD

**Issue by ynagarjuna1995** [mitchellh/vagrant#6462]
![image](https://cloud.githubusercontent.com/assets/5663901/10844528/4b70a738-7f26-11e5-830a-3156357e9586.png)

But I was able to install `vagrant plugin install vagrant-vbguest` properly with out any issues 

as you can see in the below picture
![image](https://cloud.githubusercontent.com/assets/5663901/10844601/bc4a934c-7f26-11e5-89f8-a85330e4be91.png)

I am trying to use this vagrant [box](https://github.com/Riverside-Ruby/vagrant-chef-rails4) for that I need chef for provisioning.

Again I have tried to install `vagrant plugin install vagrant-librarian-chef`

![image](https://cloud.githubusercontent.com/assets/5663901/10844660/5f56f5ee-7f27-11e5-86a5-03ae32565dc8.png)
 This time it asks me to install `gem install windows-pr '1.2.2' `Since I have faced issues while installing I have downloaded the gem file and installed manullay but still I am keep on getting these same errors in a cycle

**Comment by ynagarjuna1995** [comment]
I have tried running `vagrant up` 

this is error I am getting

PS C:\Users\Nagarjuna\vagrant\vagrant-chef-rails4> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty32'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: vagrant-chef-rails4_default_1446208578788_46849
==> default: Clearing any previously set forwarded ports...
==> default: Installing Chef cookbooks with Librarian-Chef...
==> default: Destroying VM and associated drives...
==> default: Running cleanup tasks for 'chef_solo' provisioner...
==> default: Running cleanup tasks for 'shell' provisioner...
C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/posix.rb:29:in `which!': cannot find git (Librarian::Error)
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/source/git/repository.rb:20:in `bin'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/source/git/repository.rb:122:in `bin'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/source/git/repository.rb:134:in `run!'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/source/git/repository.rb:48:in `clone!'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/source/git.rb:82:in `cache!'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/source/local.rb:22:in `manifest_search_paths'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/source/local.rb:31:in `found_path'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/local.rb:65:in `expect_manifest!'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/local.rb:53:in `fetch_manifest_data'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/local.rb:49:in `manifest_data'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/local.rb:28:in `fetch_version'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/manifest.rb:121:in `fetch_version!'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/manifest.rb:113:in `fetched_version'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/manifest.rb:59:in `version'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/manifest.rb:97:in `satisfies?'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/dependency.rb:121:in `satisfied_by?'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:103:in `block in check_manifest'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:104:in `each'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:104:in `find'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:104:in `check_manifest'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:63:in `block in recursive_resolve'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:70:in `block in recursive_resolve'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:70:in `block in recursive_resolve'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:154:in `block (3 levels) in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:187:in `block in scope_checking_manifest'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:186:in `scope_checking_manifest'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:153:in `block (2 levels) in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:211:in `block in map_find'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `each'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:210:in `map_find'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/vagrant-librarian-chef-nochef-0.2.0/lib/vagrant-librarian-chef/action/librarian_chef.rb:52:in `resolve_and_install_cookbooks'
        from C:/Users/Nagarjuna/.vagrant.d/gems/gems/vagrant-librarian-chef-nochef-0.2.0/lib/vagrant-librarian-chef/action/librarian_chef.rb:16:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/match_mac_address.rb:16:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/import.rb:32:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/customize.rb:40:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
PS C:\Users\Nagarjuna\vagrant\vagrant-chef-rails4>

**Comment by sethvargo** [comment]
Hi @ynagarjuna1995 

The first issue you are experiencing looks like a transient networking issues. That is the correct IP address, and the server does not respond to ping (so that is the expected output). I just tried and I am able to install gems from gems.hashicorp.com without issue.

The second error is coming from the vagrant-librarian plugin. Please open an issue on that plugin's repository. Thanks! :smile:
