### ISSUE TITLE
NFS + OS X Sudoers file no longer works for 1.7.4

### ISSUE THREAD

**Issue by nathanielks** [mitchellh/vagrant#6463]
I'm experiencing the same problem as #6022, but for OS X. I Downgraded to 1.7.3 and 1.7.2, and those don't work either. Unfortunately I don't remember when this _did_ work. Anyone else experiencing the same issues?

**Comment by sethvargo** [comment]
Hi @nathanielks 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. Unfortunately there is not enough information here to diagnose or reproduce the issue. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by nathanielks** [comment]
Sho nuff! Sorry, this apparently got buried in my inbox. I'll get that as soon as I can :+1:

**Comment by nathanielks** [comment]
[Here](https://gist.github.com/nathanielks/0aac34053ca33facbd54) you are!

**Comment by mitchellh** [comment]
Thanks, let's keep the discussion over in #6022

**Comment by nathanielks** [comment]
Adjusted my `/etc/sudoers` per #6022 (realizing that those instructions were for linux, but hey) and it still doesn't resolve the permissions for OS X.

**Comment by erikfrerejean** [comment]
@sethvargo, @nathanielks 

I'm seeing the same issue on OS X *(10.11.1)*. The linux instructions in #6022 do not resolve the issue. This appears to be a separate issue.

**Comment by dklotz** [comment]
I'm also still seeing this on OS X (10.10.5), with the current sudoers configuration from the current vagrant documentation. So this is most definitely not fixed for OS X.

**Comment by dklotz** [comment]
@mitchellh can you re-open this, as people still seem to have this issue on OS X (I think three people is enough confirmation)?

**Comment by stephen-liu-sherpaa** [comment]
I believe the issue is that the "tee" command for modifying the exports file doesn't use the full path of /usr/bin/tee but is just "tee". A full path is needed from all the literature I've seen on sudoers files. Not sure how this worked previously--or maybe it's a new security enhancement in OS X.

See: https://github.com/mitchellh/vagrant/blob/v1.8.1/plugins/hosts/bsd/cap/nfs.rb#L114

I modified the command to /usr/bin/tee and tested that it works on OS X (10.11.4)

**Comment by dklotz** [comment]
@stephen-liu-sherpaa that's a good hint, for me it wasn't a replacement for /usr/bin/tee but /usr/bin/sed that I had installed from homebrew. Modifying the sudoers entry to include the version from /usr/local/bin fixed it for me.

**Comment by nathanielks** [comment]
@stephen-liu-sherpaa aha! that fixed it for me as well! Good thinking 👍
