### ISSUE TITLE
Certificate verify failed when vagrant plugin install

### ISSUE THREAD

**Issue by chenww** [mitchellh/vagrant#6464]
Ubuntu 14.10
$ vagrant -v
Vagrant 1.7.2
$ gem -v
1.8.23
$ vagrant plugin install vagrant-openstack-plugin --plugin-version 0.11.1
Installing the 'vagrant-openstack-plugin --version '0.11.1'' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing CFPropertyList (2.3.2), and Bundler cannot continue.
Make sure that `gem install CFPropertyList -v '2.3.2'` succeeds before bundling.

Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/gems/CFPropertyList-2.3.2.gem)

**Comment by chenww** [comment]
It seems timing issue of the machine. After synched with NTP server, no issue now.

**Comment by amfarrell** [comment]
@chenww , I'm also running into this issue when trying to install a different vagrant plugin. Are you saying you synced the host with an NTP server? If so, how did you do this?

**Comment by amfarrell** [comment]
This error went away after an hour, so I suspect it was a transient error with rubygems. See https://gist.github.com/amfarrell/2878d416412b7cd10dc2
