### ISSUE TITLE
cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by newtonianb** [mitchellh/vagrant#6465]
I have a PHP Application (using laravel) that I setup on homestead (vagrant) at ``my.app`` Within this laravel app I installed the ''guzzle client library'' https://github.com/guzzle/guzzle.

I now developed a laravel command script that uses guzzle to send API requests to various API endpoints at ``my.app``

The problem I keep getting error ``cURL error 6: Could not resolve host``

It looks like something is funky with the host through vagrant. I tried to debug through the library but didn't gain much. How can I debug this more?

I am on Windows 8.1

https://github.com/guzzle/guzzle/issues/1293

**Comment by sethvargo** [comment]
Hi @newtonianb 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. At first sight, this appears to be a system-level problem. What are your DNS settings? Are you using IPv4 or IPv6? This [Stackoverflow post](http://stackoverflow.com/questions/24967855/curl-6-could-not-resolve-host-google-com-name-or-service-not-known) may be able to help.

**Comment by mitchellh** [comment]
Closing due to lack of response. Sorry! Please reopen a new issue if you have a response to the above.
