### ISSUE TITLE
Add a command or command option to query which box and box version an environment is using

### ISSUE THREAD

**Issue by emddudley** [mitchellh/vagrant#6469]
I create Vagrant boxes in a continuous integration environment and so I am frequently switching back and forth between box versions. I would like to be able to query which box version my environment is currently using.

When I run a `vagrant update` I do get a nice printout of the current version, but this has the unwanted side effect of updating my box.

I think adding the box version to the `vagrant status` and `vagrant global-status` output might make sense. The output could look like the example below, if that's consistent with Vagrant's design:

    C:\Users\me\Desktop\mybox>vagrant status
    Current machine states:

    default                   poweroff        mybox (virtualbox, 66)

    The VM is powered off. To restart the VM, simply run `vagrant up`

    C:\Users\me\Desktop\mybox>vagrant global-status
    id       name    box   provider   version state    directory
    --------------------------------------------------------------------------
    4141106  default mybox virtualbox 66      poweroff C:/Users/me/Desktop/mybox

**Comment by sethvargo** [comment]
Hi there,

This looks very similar to https://github.com/mitchellh/vagrant/issues/6184, so I 'm going to close this as a duplicate :smile:
