### ISSUE TITLE
Rename misleading CLI options

### ISSUE THREAD

**Issue by amirbehzad** [mitchellh/vagrant#6476]
I have been confused with some of the options in Vagrant's CLI, and I noticed I'm not alone on this, i.e.  #4772.

The above ticket explains that when "Down" was introduced in Vagrant, it caused confusion, so it's now renamed to "halt".  While this might have addressed a group of users, it might cause confusion to another group of users.

Replacing *down* with *halt* does not completely address the confusion problem. Perhaps Up-Down combo shouldn't been used in the first place. Intuitively, when up translates to start, down is expected to initiate shutdown.

I have some suggestion:

1) Git provides a hint when user makes a typo. For example, try git stat, and you'll get this:
```
$ git stat
Did you mean one of these?
	status
	stage
	stash
```
In a similar way, vagrant's CLI could print a hint when user mistakenly types "down".

2) VirtualBox as a reference
Since VirtualBox is quiet familiar for most of the users, we could borrow some ideas from it's menu items.

3) Random suggestions
Just as an average user, I'd suggest start/shutdown, as in *start/reload/suspend/resume/shutdown** ?
or create/destroy or build/destroy or new/delete instead of init/destroy ?

**Comment by sethvargo** [comment]
Hi @amirbehzad 

Thank you for opening an issue. We will take these suggestions into consideration as we continue to improve Vagrant! Thanks :smile:
