### ISSUE TITLE
core/environment: Locks don't work with parallel run of multi-machine env

### ISSUE THREAD

**Issue by legal90** [mitchellh/vagrant#6478]
There is `Environment#lock` method which acquires a process-level lock. It works fine in multi-process mode, for example when we run some "vagrant" commands in different terminals.
https://github.com/mitchellh/vagrant/blob/c17efbed755df621d6571742e163e8dff61dd119/lib/vagrant/environment.rb#L501

But since it is a process-level lock, it doesn't work with parallel run in multi-machine environment, for example: `vagrant up vm_name_1 vm_name_2`. Both machines are managed by the single process and they are related to the same `Environment` instance.

Due to this line, the second machine will ignore the lock acquired by the first one:
```ruby
# ...
      return yield if @locks[name] || opts[:noop]
```
https://github.com/mitchellh/vagrant/blob/c17efbed755df621d6571742e163e8dff61dd119/lib/vagrant/environment.rb#L508

The request is: please add to Vagrant core the possibility to create a lock not only on the process level, but on the class (machine?) level as well. 

I found some examples in the Vagrant source code where authors tried to achieve it with class-wide mutex. But... it looks like a smell code, I would be glad to use some appropriate core method for that.
```ruby
@@lock = Mutex.new
#...
@@lock.synchronize do
  # ...
end
```
https://github.com/mitchellh/vagrant/blob/b721eb62cfbfa93895d0d4cf019436ab6b1df05d/plugins/synced_folders/nfs/synced_folder.rb#L79

Or please, give me an advice how should I do such locks in my custom plugin. Thanks.

cc: @mitchellh @sethvargo

**Comment by mitchellh** [comment]
Hey Mikhail,

Within the provider itself within process we defer synchronization to you. Setting class-level locks is the right way to do this. We do this because the provider itself should be able to do more fine-grained, cheaper locks. 

Does this make sense?

**Comment by legal90** [comment]
> Does this make sense?

Yes, thank you. 
So, I guess that class-level locks should be added close to each environment lock (at least for `virtualbox` provider).
