### ISSUE TITLE
Rsync default behaviour

### ISSUE THREAD

**Issue by stepanzarubin** [mitchellh/vagrant#6480]
I think default behaviour should be:

When we run `rsync` it should do full rsync
When we run `rsync-auto` it should first do full rsync and then watch for modified only.

This should affect all the plugins that are using Vagrant rsync internals.

Thanks.

**Comment by nuncanada** [comment]
For big directory structures that are common for a lot of projects, even more for development workbenchs, this is the difference between a usable vs non-usable rsync solution.

**Comment by sethvargo** [comment]
Oops - looks like a duplicate of https://github.com/mitchellh/vagrant/issues/6399 actually. Thanks!
