### ISSUE TITLE
Consistent errors Connection timeout

### ISSUE THREAD

**Issue by brittainmedia** [mitchellh/vagrant#6481]
Windows 8 Intel i5 8GB RAM

Warning: Connection timeout. Retrying... (Consistent and normally fails after many tries)

Please advise

**Comment by sethvargo** [comment]
Hi @brittainmedia 

As I said on your previous issues, there is not enough information here to make a diagnosis. Please open a new issue and include:

- The version of Vagrant you are using
- The `Vagrantfile`
- The output of the command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)
