### ISSUE TITLE
Consistent errors SSH connect error

### ISSUE THREAD

**Issue by brittainmedia** [mitchellh/vagrant#6482]
Windows 8 Intel i5 8GB RAM

- SSH exited with a none zero status

Please advise

**Comment by sethvargo** [comment]
Hi @brittainmedia 

As I said on your previous issues, there is not enough information here to make a diagnosis. Please open a new issue and include:

- The version of Vagrant you are using
- The `Vagrantfile`
- The output of the command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)
