### ISSUE TITLE
[Vagrant 1.7.4 and Virtualbox 5.0.8] can't start vm anymore after update

### ISSUE THREAD

**Issue by c4pone** [mitchellh/vagrant#6484]
OS X Yosemite: v10.10.5 
Virtualbox: Version 5.0.8 r103449
 
Error:
```bash
c4pone@404~/workspace/vm $ vagrant -v
Vagrant 1.7.2
c4pone@404~/workspace/vm $ vagrant up
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

**Comment by varun06** [comment]
Got same error today: 
OS X Yosemite: v10.10.5 
Virtualbox: Version 5.0.8 r103449
Vagrant: 1.7.2

**Comment by chrisatthestudy** [comment]
I notice that you are both using Vagrant 1.7.2. As the error message says, this version only supports versions 4.0, 4.1, 4.2, and 4.3 of VirtualBox.

Upgrading to Vagrant 1.7.4, which supports VirtualBox 5.0.8, should fix the problem. Vagrant is quite sensitive about which versions of VirtualBox it uses.

**Comment by sethvargo** [comment]
VirtualBox 5 support was not added until Vagrant 1.7.4. Please upgrade to Vagrant 1.7.4 - https://releases.hashicorp.com/vagrant/1.7.4
