### ISSUE TITLE
Vagrant box add fail when the box is on another drive

### ISSUE THREAD

**Issue by chevdor** [mitchellh/vagrant#6495]
OS: Windows 10
```
c:>vagrant box add test d:\vagrant-images\win10ent.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'test' (v0) for provider:
    box: Unpacking necessary files from: file://d:/vagrant-images/win10ent.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /vagrant-images/win10ent.box
```
I copy the folder d:\vagrant-images to c:\vi and try the same thing again:

```
c:>vagrant box add test c:\vi\win10ent.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'test' (v0) for provider:
    box: Unpacking necessary files from: file://c:/vi/win10ent.box
    box: Progress: 100% (Rate: 453M/s, Estimated time remaining: --:--:--)
==> box: Successfully added box 'test' (v0) for 'virtualbox'!
```

**Comment by dragon788** [comment]
@chevdor Can you perform this operation with the debug log enabled? I'd be really interested to see what the actual error message that was thrown looks like.
We use the VAGRANT_HOME environment variable to add boxes via metadata URL on C:\D:\E: drives and haven't had any trouble. I've also downloaded box files to a secondary disk and added them to a VAGRANT_HOME located on my primary disk, so I'm not sure what is causing the issue.

**Comment by chrisroberts** [comment]
@chevdor If this is still an issue, can you please provide debug output of the error? Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
