### ISSUE TITLE
Synced Folder Disabled by Default with Centos/7

### ISSUE THREAD

**Issue by darkn3rd** [mitchellh/vagrant#6497]
The vagrant folder is no longer mounted, at least with `centos/7` image.  

```Ruby
Vagrant.configure("2") do |config|
  config.vm.define "devbox", primary: true do |dev|
    dev.vm.box = "centos/7"
  end
end
```

**ACTUAL BEHAVIOR**:  The rsync feature seems to be used instead:

```
==> devbox: Rsyncing folder: /Users/joaquin.menchaca/projarea/scrap01/ => /home/vagrant/sync
```

**EXPECTED BEHAVIOR**: As per [documentation](https://docs.vagrantup.com/v2/synced-folders/index.html) at the time of writing this issue:

> By default, Vagrant will share your project directory (the directory with the Vagrantfile) to /vagrant.

**NOTES**: 

* Added a line to tell vagrant not to auto disable this feature, e.g.   dev.vm.synced_folder '.', '/vagrant', disabled: false.  But then vagrant freezes for a while and notes that `vboxsf` is unavailable. 
* Does not reproduce with `ubuntu/trusty64` image, seems to be a *feature* with `centos/7`.

**CONFIGURATION (HOST):**
```bash
$ vboxmanage --version
5.0.6r103037
$ vagrant --version
Vagrant 1.7.4
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F27
```

**Comment by darkn3rd** [comment]
If this is the expected behavior, i.e. no guest editions, fall back to rsync, should there be an warning or something that vboxsf failed or not used, and rsync favored, or some indication that the default behavior is altered?  

In my case (use case), shell provisioning scripts relied on existence of `/vagrant`.

**Comment by sethvargo** [comment]
Hi @darkn3rd 

This is the expected behavior. You can read more here: https://docs.vagrantup.com/v2/synced-folders/basic_usage.html

> - `type (string)` - The type of synced folder. If this is not specified, Vagrant will automatically choose the best synced folder option for your environment. Otherwise, you can specify a specific type such as "nfs".

If you want to force a particular type, you can specify that in your mount:

```ruby
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
end
```

**Comment by vhosakot** [comment]
When I did `vagrant up` with the box `centos/7 (virtualbox, 1703.01)`, `==> default: Rsyncing folder: /root/ => /vagrant` was stuck for me too, and adding
`config.vm.synced_folder '.', '/vagrant', disabled: true`
in Vagrantfile resolved the issue for me and rsync did not happen.
