### ISSUE TITLE
Provision with mounted file - `path` for shell provisioner does not exist on the host system

### ISSUE THREAD

**Issue by trompx** [mitchellh/vagrant#6499]
Hello,

I would like to mount a script folder that I share among multiple boxes and provision the box with one of the script but it seems that the provisionning happens before mounting as I get the error :
```
shell provisioner:
* `path` for shell provisioner does not exist on the host system: C:/path/scripts/my_script.sh
```

Is there a way to force the provision to happen after the scipts folder has been synced to avoid having to copy the script on each box ?

Thanks

**Comment by sethvargo** [comment]
Hi @trompx 

I am sorry you are having issues with Vagrant. Unfortunately there is not enough information here to reproduce or diagnose the issue. Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by mitchellh** [comment]
Closing due to lack of response. Sorry! Please reopen a new issue if you have a response to the above.
