### ISSUE TITLE
Getting Error Creating Container

### ISSUE THREAD

**Issue by aldrienht** [mitchellh/vagrant#6504]
```
==> docker: Creating the container...
docker:   Name: docker_for_infomix_docker_1447037720
docker:  Image: a7f57a3417c6
docker: Volume: /root/share/docker_for_infomix:/vagrant
docker:   Port: 8080:80
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "run", "--name", "docker_for_infomix_docker_1447037720", "-d", "-p", "8080:80", "-v", "/root/share/docker_for_infomix:/vagrant", "--privileged", "a7f57a3417c6", {:notify=>[:stdout, :stderr]}]

Stderr: Error response from daemon: operation not supported


Stdout:
![error message](https://cloud.githubusercontent.com/assets/10846020/11028847/91a80390-8705-11e5-9483-056675ed39af.png)
```

I'm getting the above error after running:

```
$ docker import http://xxx.yyy.zzz/webdav/centos-65.tar.xz skyarch:centos6.5
$ vagrant up
```

I can solve this by running vagrant reload from the host computer.
Then vagrant up again from guest container.

But how can I solve this issue, for me to have smooth installation with having to restart (vagrant reload). ?

**Comment by sethvargo** [comment]
Hi @aldrienht 

Thank you for opening an issue. Could you please share your complete `Vagrantfile` as well as the output of the Vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks

**Comment by mitchellh** [comment]
Closing due to lack of response. Sorry! Please reopen a new issue if you have a response to the above.
