### ISSUE TITLE
--plugin-source not recognized on Windows

### ISSUE THREAD

**Issue by kbarlett001** [mitchellh/vagrant#6505]
OS Version: Windows 7 x64 SP1
Vagrant version: 1.7.4

Gem sources below (there are none):

`chef exec gem list sources`

*** LOCAL GEMS ***

I have no Gemfile but when I run `vagrant plugin install` with `--plugin-source' I receive the following error(s).

buser@VM-B39SCL4RJEAR ~
$ vagrant plugin install vagrant-wimrm --plugin-source https://Buser:password@artifactory.internalcorp.com/artifactory/api/gems/rubygems/ -vv
Installing the 'vagrant-wimrm' plugin. This can take a few minutes...
Warning: this Gemfile contains multiple primary sources. Using `source` more tha
n once without a block is a security risk, and may result in installing unexpect
ed gems. To resolve this warning, use a block to indicate which gems should come
 from the secondary source. To upgrade this warning to an error, run `bundle con
fig disable_multisource true`.
Warning: this Gemfile contains multiple primary sources. Using `source` more tha
n once without a block is a security risk, and may result in installing unexpect
ed gems. To resolve this warning, use a block to indicate which gems should come
 from the secondary source. To upgrade this warning to an error, run `bundle con
fig disable_multisource true`.
Fetching source index from http://gems.hashicorp.com/
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from http://gems.hashicorp.com/

    I have set the disable_multisource to true, but encounter the same issue.

    I am behind a firewall but can access artifactory with no issue.  Couple of questions:

    1.  Why is vagrant defaulting to the  http://gems.hashicorp.com/ address when the gem sources is empty or a non-default source is specified (such as my artificatory address).

    2.  Why is vagrant complaining about multiple sources when the source list is empty? There is no Gemfile here.

Thanks in advance for any assistance.

**Comment by xacaxulu** [comment]
+1, I've experienced the same on Windows. Can't reproduce on OSX.

**Comment by mitchellh** [comment]
In the next version of Vagrant you can use the advanced feature `--plugin-clean-sources` to delete all sources, then use `--plugin-source` to manually add sources that work through your proxy. I recommend doing this in your scenario.

**Comment by martinmosegaard** [comment]
`--plugin-clean-sources` doesn't work for me (in an environment without Internet access, I want to download from a local repository).

```
λ vagrant plugin install vagrant-winrm --plugin-clean-sources --plugin-source http://myartifactory/api/gems/rubygems/
Installing the 'vagrant-winrm' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-share (> 0)'

λ vagrant plugin install vagrant-share --plugin-clean-sources --plugin-source http://myartifactory/api/gems/rubygems/
Installing the 'vagrant-share' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  timed out (https://api.rubygems.org/specs.4.8.gz)

Source: https://rubygems.org/
```

**Comment by martinmosegaard** [comment]
What _does_ work for me is if I have the vagrant plugin as a gem file:

```
vagrant plugin install minitar-0.5.4.gem
vagrant plugin install vagrant-winrm-0.7.0.gem
```

I would just like to be able to point to a repository so I don't need to do manual dependency resolution.
