### ISSUE TITLE
Ruby Exception `parse': 757: unexpected token at '' (JSON::ParserError)

### ISSUE THREAD

**Issue by csogilvie** [mitchellh/vagrant#6507]
I've developed a Vagrantfile on my OSX machine, where it works perfectly, and am now trying to test it on a Windows machine. However, every time I run it, I receive an error about JSON::ParseError. 

With the way that Windows works, I seem to be unable to grab the entire output of the --debug command line, so have pasted what little I can to a gist - https://gist.github.com/csogilvie/7d14f2c157dcb6ced956; if you need other data, please let me know. 

I am using Windows 7, fully up to date.
I am using Vagrant 1.7.4 (downloaded and installed today).
I am using Virtualbox 5.0.8 (downloaded and installed today).

Thanks
Colin

**Comment by sethvargo** [comment]
Hi @csogilvie 

Thank you for opening an issue. Can you please share your Vagrantfile as well?

**Comment by csogilvie** [comment]
Hi, the vagrant file is at https://gist.github.com/csogilvie/24fa3915ba3c012eaa49

Note that this has a block for AWS in it as well, but this is *not* being used in this case.

**Comment by sethvargo** [comment]
I think you're hitting this: https://github.com/mitchellh/vagrant/pull/6404

**Comment by csogilvie** [comment]
OK, good - any ideas when this may be fixed and released?

**Comment by sethvargo** [comment]
@csogilvie we are aiming by the end of the year :smile:
