### ISSUE TITLE
chef_zero provisioner appends `localhost.dev` cumulatively to the end of the node json until it can't write the file anymore

### ISSUE THREAD

**Issue by timvisher** [mitchellh/vagrant#6509]
I'm using

```
🐆  VBoxManage -v; vagrant -v; chef -v
5.0.8r103449
Vagrant 1.7.4
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

I have the `chef_zero` provisioner set up for the box and it works great for several consecutive runs but eventually the hostname gets so long that it can't write it the file system and thus can't provision the box. `destroy`ing the box and then reupping appears to reset the state but it's needlessly costly.

[This gist](https://gist.github.com/timvisher/3c94bb4f3311d3a3a9d5) contains a running log of reprovisions `grep`ed down to just the growing hostname and a final run with `--debug` output turned on.

I've tried reading through the source code but I can't find where it's building that filename. If it's a bug I'd be happy to submit a patch but I'd need some help figuring out where to get started. :)

My Vagrantfile might be awkward to post but if I need to I can.

**Comment by sethvargo** [comment]
Hi @timvisher 

I checked the Vagrant source code and no where do we append ".dev" to a host. It looks like the logs are coming from Chef (they say "generated by Chef"). Could you take a look at that?

**Comment by timvisher** [comment]
@sethvargo Do you have an idea where to start?

**Comment by sethvargo** [comment]
@timvisher I would take a look at your chef code for `>> /etc/hosts`, since that's happening somewhere. Then trace upward to see how that is being called.

**Comment by timvisher** [comment]
@sethvargo Isn't this happening well before my chef code takes over?

**Comment by sethvargo** [comment]
Hi @timvisher 

Can you please share your Vagrantfile?

**Comment by timvisher** [comment]
@sethvargo I'll try. :)

**Comment by timvisher** [comment]
hope this helps. https://gist.github.com/timvisher/3c94bb4f3311d3a3a9d5#file-vagrantfile-redacted

**Comment by sethvargo** [comment]
@timvisher wow haha. That's... large. Unfortunately I don't have access to your chef cookbooks/repo. Are you able to reduce this to a vanilla Vagrantfile?

I'm still not convinced this is happening in Vagrant, but rather something Chef is doing. I'm not familiar with boxcutter, but it would be great if you could remove the Chef bits and show the reproduction.

**Comment by timvisher** [comment]
@sethvargo I can try to give that a go. And I did say it would be awkward. :P

**Comment by timvisher** [comment]
@sethvargo I definitely can't reproduce this with [this configuration](https://github.com/mitchellh/vagrant/issues/6110#issuecomment-155559635). It's strange to me how early it happens. I'll try to thin things down and see where it stops.

**Comment by timvisher** [comment]
@sethvargo It's looking like this is a bad interaction between https://supermarket.chef.io/cookbooks/hostname and perhaps the way the chef client command is built?

> based on its chef node name (which is provided on chef-client first run's command line

Where is that built here?
