### ISSUE TITLE
--provision-with by name

### ISSUE THREAD

**Issue by romulodl** [mitchellh/vagrant#6512]
Not an issue, a suggestion (I don't know if is actually possible or even if someone else already suggested.)

I split my provisioning steps with names (bootstrap, database, etc) but they are all `shell` provisioners, is it possible to run `--provision-with` using the name of the provisioner instead of the type?

Thanks :)

**Comment by mitchellh** [comment]
This is done!

**Comment by romulodl** [comment]
Thanks!

The website docs is also updated! But the command `vagrant provision --help` still not bringing this info:

```
➜  vagrant provision --help
Usage: vagrant provision [vm-name] [--provision-with x,y,z]
        --provision-with x,y,z       Enable only certain provisioners, by type.
    -h, --help                       Print this help
```
