### ISSUE TITLE
Poor scroll performance of vagrantup.com

### ISSUE THREAD

**Issue by narqo** [mitchellh/vagrant#6520]
I hate to say that, but vagranup.com is a very unresponsive website. It almost impossible to use/read documentation sections, as scrolling (at least in blink-based browsers, e.g. Chrome) is extremely slow and yanky.

The most awkward thing that makes performance suffer is background picture that is visible behind the sidebar. It's huge and it's fixed. Just switching it off makes things much better and responsive.

**Comment by narqo** [comment]
Here I've recorded a small screencast that shows the problem: https://yadi.sk/i/Ful75v_2kTczY

**Comment by mitchellh** [comment]
Hi! Thanks. The website is completely open source. If you're comfortable with web design, please give it a shot if you have time. Otherwise, we've never heard this for any other user, so we're going to mark as "nofix" for now. Sorry!
