### ISSUE TITLE
No Guest IP was given to the Vagrant core NFS helper

### ISSUE THREAD

**Issue by imkarrer** [mitchellh/vagrant#6523]
Error from vagrant up:

```
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
```

Vagrantfile

```
  config.vm.network "private_network", type: "dhcp"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4
```

I have tried

```
  config.vm.network "private_network", ip_address: "192.168.10.2"
```

Which gets rid of the above message, but the share is still not mountable on the guest system

```
mount -t nfs -o 'vers=4,udp' '192.168.10.1:/Users/admin/vagrant/mountainlion' '/vagrant'
```

Results in:

```
mount_nfs: no usable addresses for host: 192.168.10.1
mount_nfs: no usable addresses for host: 192.168.10.1
mount_nfs can't mount /Users/admin/vagrant/mountainlion from 192.168.10.1 onto /vagrant: No such file or directory
```

Host: El Capitan 10.11.1
Guest: MountainLion 10.8
Provider: Virtualbox 5.0.10 r104061

**Comment by dominikzogg** [comment]
https://github.com/boxcutter/centos/issues/30

**Comment by dominikzogg** [comment]
@mitchellh any news on this?

**Comment by petegore** [comment]
Hi guys, did you solve this. 
This problem came today on my Vagrant machine after : 
- updated vbox to version 5
- update my debian/jessie vagrant box

But I think it's clearly due to virtualbox5

**Comment by richard-scott** [comment]
Did you re-install the extra's pack into VirtualBox after the upgrade?

Have you tried checking the vboxnet0 interface in VirtualBox is configured correctly?
DHCP IP comes from VirtualBox not Vagrant.

Maybe try deleting the vboxnet interfaces and re-run vagrant up to re-create them.

**Comment by petegore** [comment]
Well, after reinstalling my whole distribution (Ubuntu 15.04) ; Virtualbox5 ; Vagrant 1.8.1... It still didn't work !
But I solved this : I had some symlinks into a folder, and the base Rsync done by the vagrant up failed. I don't know why it worked before and not anymore... But now that's fine.
Thx

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
