### ISSUE TITLE
REQ: add support to list forwarded ports in vBox VMs 

### ISSUE THREAD

**Issue by bitprocessor** [mitchellh/vagrant#6546]
Would be nice if there would be a vagrant command to list the forwarded ports in vBox environments. Right now (if I'm not mistaken), the ports are only shown during "up"?

I hacked together something in python, which is working if you run it in the folder where the .vagrant file is located.

https://github.com/bitprocessor/py-vagrant-ports

Might take a look into porting this to Ruby in the future, but might come in handy or serve as a basis for someone else to add this functionality ;)

**Comment by sethvargo** [comment]
I'll append this to https://github.com/mitchellh/vagrant/issues/6184. Thanks!
