### ISSUE TITLE
automatically halt VMs on shutdown

### ISSUE THREAD

**Issue by nostalgicdodo** [mitchellh/vagrant#6547]
can vagrant tap into the shutdown routine of the OS and automatically halt all running VMs?

**Comment by sethvargo** [comment]
Unfortunately this is not possible. Vagrant doesn't have a background process (it is only running when you run a command), after that, the virtualization level takes over. Most hypervisors (including vbox) will shutdown the VM on machine shutdown.

**Comment by nostalgicdodo** [comment]
So I have to figure out how to do this in VirtualBox?
thanks.
