### ISSUE TITLE
Vagrant Exit Code on Shell Provisioner with PowerShell file is Always 0 unless explicit exit 1

### ISSUE THREAD

**Issue by ferventcoder** [mitchellh/vagrant#6549]
I thought I was going crazy, but it appears that even though Chocolatey reports it is going to exit 1, on Windows Hosts Vagrant still exits with a zero exit code.

Intentionally returning a non-zero exit code from a PowerShell shell execution still results in a zero exit code.

I've included my Vagrantfile, the powershell file I'm running and DEBUG output in the gist below.
https://gist.github.com/ferventcoder/720de80549dfa8e3ab12 

More information:
- Vagrant 1.7.4
- VirtualBox 4.3.28
- Windows Server 2012 R2 x64

**Comment by ferventcoder** [comment]
Maybe. I'm diving a bit deeper now.

**Comment by ferventcoder** [comment]
I think the exit code is coming from Chocolatey in this case, but it doesn't appear to be passed through to Vagrant.

![image](https://cloud.githubusercontent.com/assets/63502/11272523/263d7334-8e93-11e5-9a43-053895d3770a.png)

**Comment by ferventcoder** [comment]
So it could be I just need to check the exit code in the PowerShell script and then return appropriately for Vagrant to pick up on it.

**Comment by ferventcoder** [comment]
Checking now.

**Comment by ferventcoder** [comment]
Actually it appears if I check and force the exit code, it works appropriately.

**Comment by ferventcoder** [comment]
@sethvargo closed, but no fixes?

**Comment by ferventcoder** [comment]
or is the fix noted somewhere in the commits?

**Comment by ferventcoder** [comment]
Oh wait - my bad. I suggested it closed.

**Comment by ferventcoder** [comment]
I have a repo at https://github.com/chocolatey/chocolatey-test-environment

**Comment by ferventcoder** [comment]
It's possible that if a PowerShell function fails, it will exit with non-zero, but if a call to a command fails, it exits with zero.

I also don't get anything in the output for the error related to stdout/stderr.

**Comment by ferventcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/63502/12276869/cea58dc0-b93d-11e5-9b5b-d9afb19f2012.png)


This is with the explicit check and exit 1 on $LASTEXITCODE.

**Comment by chrisroberts** [comment]
I do believe that is the case and you will need to explicitly exit with an exit code assigned. If you find that is not the case and Vagrant is not handling the result correctly, please feel free to reopen this issue. Thanks!
