### ISSUE TITLE
Switch to recommended Ansible 2.x arguments with backwards compatible aliases

### ISSUE THREAD

**Issue by gildegoma** [mitchellh/vagrant#6570]
- `ask_become_pass` (aliased as `ask_sudo_pass`)
- `become` (aliased as `sudo`)
- `become_user` (aliased as `sudo_user`)
- some parameters in the generated inventory (`ansible_user`, `ansible_host` and `ansible_port`)

Deprecation warnings should also be activated for all these aliases.

Notes:
- The "become" parameters were completely introduced in Ansible 1.9
- The "not ssh specific" parameters (e.g. `ansible_user`) were introduced in Ansible 2.0
- The legacy parameters (e.g. ansible_ssh_user) will probably be removed in Ansible 2.2+.

Open Questions:
- Introduce a "strict" mode, where deprecated parameters are rejected. In such mode, all the settings behind the scene are following Ansible 2+ recommendations (e.g. inventory settings like `ansible_host` instead of `ansible_ssh_host`)
- The "strict" mode could be implemented with a "compatibility_level" option, which for now would support two values: `ansible-1.8` and `ansible-2.0`

Possible Roadmap:
1. Vagrant 1.8.x: backwards compatible introduction of new behaviors (with deprecation warnings)
2. Vagrant 1.9.0: breaking change 1: switch the `compatibility_level` default value to "ansible-2.0" to encourage users to upgrade.
3. Vagrant 2.0.0 (or 1.10.0): breaking change 2: fully remove support of "ansible-1.8" compatibility level

Note: Depending on the situation (ansible 1.9 and 2.x adoption and evolution by the time of releasing Vagrant 1.9), we also could consider introducing the two breaking changes at the same time (i.e. directly in Vagrant 1.9.0)

**Comment by gildegoma** [comment]
issue description updated after #6927 report.

**Comment by gildegoma** [comment]
I confirm that I'll provide a fix for this within the next weeks. The roadmap will be following:

* Vagrant **1.9.0** will introduce
 * A new `compatibility_mode` option, set by default to "Version 1.x" for backward compatibility. A warning will encourage to explicitly set this option in `Vagrantfile` in case compatibility with Ansible .1x is required.
 * New options `sudo`, `sudo_user` and `ask_become_pass` (with backwards compatible aliases for now deprecated `sudo`, `sudo_user` and `ask_sudo_pass` options).
* Vagrant **1.10.0** (or 2.0.0) will then introduce some breaking changes
 * Switch the `compatibility_mode` default to "Version 2.x"
 * Removal of the three deprecated options/aliases.

Questions to @chrisroberts:
* Can I assign your to review this upcoming feature pull request?
* Do you already have an ETA for Vagrant 1.9.0?

**Comment by chrisroberts** [comment]
@gildegoma Hi! Yes, feel free to assign me when it's ready for review. The 1.9.0 release will be happening shortly, so I'm going to move this into the 1.9 bucket and will pull it into the 1.9.1 milestone once it's created.

**Comment by schlueter** [comment]
I'm still seeing the sudo deprecation error with Vagrant 1.9.1: 
```
$ vagrant --version
Vagrant 1.9.1
$ vagrant provision
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
[DEPRECATION WARNING]: The sudo command line option has been deprecated in
favor of the "become" command line arguments.
This feature will be removed in
version 2.6. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

**Comment by gildegoma** [comment]
The PR #8913 will hopefully soon be merged to resolve the changes requested here.

@vagrant-ansible-community: If you're interested in these additions, please have a look at the [upcoming documentation](https://github.com/mitchellh/vagrant/blob/gildegoma/6570-ansible-compatibility-mode/website/source/docs/provisioning/ansible_common.html.md#shared-ansible-options). Feedbacks are still welcome, but any "major change" proposal needs to be reported within the next days since the next release is around the corner. 

Thank you for sharing your thoughts in this thread of the [Vagrant mailing list](https://groups.google.com/d/msg/vagrant-up/ilrun_TouSc/j2aFDR4qAgAJ) instead of this GitHub issue.
