### ISSUE TITLE
Vagrant failed to bridge an interface whose name contains special characters.

### ISSUE THREAD

**Issue by micaelbergeron** [mitchellh/vagrant#6571]
I added a *public_network* to my vagrant file.
During the _vagrant up_, it prompts me for the interface to bridge, which in my case, contains special characters.

The interface correct name is **Connexion réseau Intel(R) 82579LM Gigabit**

Here is the vagrant output:
![Vagrant output](http://i.imgur.com/IJTV0p2.png)

And the virtual box, after the process:
![VirtualBox manager](http://i.imgur.com/RTf1Yzc.png)

Specifying the interface in the Vagrantfile doesn't work either, as vagrant cannot find the specified interface.

**Comment by mitchellh** [comment]
Dup #5896 

Thanks!

**Comment by micaelbergeron** [comment]
Thank you for the follow up.

**Comment by InfinityWebMe** [comment]
@mitchellh I use last version of vagrant and virtualbox and i have the same issue.

Any idea how i can resolve this ?

**Comment by briancain** [comment]
@InfinityWebMe - please open a new issue on vagrant and fill out the template information, thanks!
