### ISSUE TITLE
Fail to install vagrant-parallels 

### ISSUE THREAD

**Issue by lijian** [mitchellh/vagrant#6573]
Hi,

I've got error when installing vagrant-parallels, posted issue to parallels team and looks vagrant core issue please refer : (https://github.com/Parallels/vagrant-parallels/issues/231) if needed.

Environment: Mac OS El Capitan (10.11.1)

Error Message: 
Installing the 'vagrant-parallels' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing childprocess (0.5.8), and Bundler cannot continue.
Make sure that gem install childprocess -v '0.5.8' succeeds before bundling.

Attached the full log file :
[debug.log](https://gist.github.com/lijian/957c5557eabdbe1c5a33#file-vagrant-debug-log)

Thanks,
Lijian

**Comment by sethvargo** [comment]
@legal90

**Comment by legal90** [comment]
@sethvargo Yes, the author have already reported it to us: https://github.com/Parallels/vagrant-parallels/issues/231
But seems like it is a rare case - I could't reproduce it and plugin installation works fine for other users of "vagrant-parallels".

Seth, could you please take a look at the attached log-file? Do you have any idea about what actually happens?

**Comment by sethvargo** [comment]
Hi @lijian 

I just tried to install the parallels plugin on el capitan and it worked without errors. I don't see anything strange in the logfile. How did you install Vagrant? Did you try @legal90's suggestion of re-installing Vagrant after clearing out the plugins directory?

**Comment by lijian** [comment]
Hi @sethvargo,

Yeah, I've cleaned up by following the steps @legal90 suggested, and re-install vagrant-parallels, same problem.

Following command can successful execute:
```shell
gem install childprocess -v '0.5.8',
```
Not understand why if still complain the gem when install vagrant-parallels, any approach I can install the gem manually for vagrant?

**Comment by lijian** [comment]
Hey @sethvargo, 

Update: it is my environment issue, seems my network blocks https://rubygems.org (but not http://rubygems.org), I've tryed add the insecure one into my gem source so I can install gems successful, but vagrant still using the https one, so it always fail, after using a proxy, I can install vagrant-parallels successful.

Thanks for all of you!

**Comment by segaura** [comment]
I solved a similar issue by setting the correct GEM_HOME environment variable value to match the vagrant installation gems folder, as explained here:  http://stackoverflow.com/questions/33490258/failed-to-install-vagrant-cachier-plugin-on-windows

Before this I solved other issues with proxy configuration, too, althougth with small differences.
