### ISSUE TITLE
Vagrant log stops when Windows firewall is disabled

### ISSUE THREAD

**Issue by stefanaj** [mitchellh/vagrant#6578]
vagrant 1.7.4
puppet 3.8.1
windows 7 x64 Enterprise

During puppet provisioning, when firewall is disabled, the command line log of vagrant just stops outputting info. Running in debug mode does not yield further information.

I have experienced this situation when using the following puppet module:
https://github.com/puppet-community/puppet-windows_firewall

I also experience it when using the following commands for msiexec: FW_DISABLE=1

No errors occur during provisioning, and i can see the provisioning process continue and complete on the guest.

**Comment by sethvargo** [comment]
Hi @stefanaj 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. Vagrant communicates with the VM over SSH during provisioner, so I'm guessing that your puppet script is provisioning the VM without permitting that connection. Thus Vagrant is trying to send commands and read output, but the firewall is blocking it. Does that make sense?

**Comment by stefanaj** [comment]
That would make sense to me, if the firewall is active, but the firewall is being disabled.. I should maybe also mention that it is when the change to the firewall is performed that th

**Comment by sethvargo** [comment]
@stefanaj I'm going to guess that a _change_ in the firewall state is terminating existing connections or something. Can you send a Vagrantfile that reproduces? What is your host OS?

**Comment by stefanaj** [comment]
Host OS is windows 10, and i use winrm. I'll see if i can find some time to create a simple Vagrantfile to reproduce the situation.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
