### ISSUE TITLE
After vagrant package, VM can't be reached.

### ISSUE THREAD

**Issue by whatda** [mitchellh/vagrant#6579]
I start my Ubuntu VM (based on "Scotchbox") with `vagrant up`. Then (maybe after some work, but it's not necessary to reproduce this issue) I halt it with `vagrant halt` and export it with `vagrant package`. If I now restart the VM with `vagrant up`, it can't be reached (webserver, ping) from the host machine.

I'm using Vagrant 1.7.4 and Windows 10 as host. Virtualbox 5.0.10 with matching guest additions.

I've tried ipconfig /renew and ipconfig /flushdns, both without success. Only a *host* restart helps.

**Comment by sethvargo** [comment]
Hi @whatda 

Can you please share your Vagrantfile and the output of the command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by dragon788** [comment]
@whatda I believe a vagrant package might reset some network settings when performing the package operation, I would suggest doing like seth recommended and capturing a log of both your up and halt and package operations to see what is happening under the hood.

**Comment by whatda** [comment]
Hi,

sorry for the late reply. I don't think I'll be able to post the log, since it may contain confidential data. But I'll try to post the Vagrantfile after vacation (although there's nothing special in there). If you need to know certain things of the log, I might be able to help, though.

**Comment by sethvargo** [comment]
Hi @whatda 

It would be helpful if you could try upgrading to Vagrant 1.8.1. Unfortunately, without a Vagrantfile or debug logs, it is very difficult to reproduce this on our end.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
