### ISSUE TITLE
Expose docker configuration from Vagrant (allow Docker Compose integration)

### ISSUE THREAD

**Issue by radeksimko** [mitchellh/vagrant#6600]
Splitting from https://github.com/mitchellh/vagrant/issues/6269#issuecomment-159601687 originally.

I'm thinking of using Vagrant only to spin up docker daemon inside the VM & do all the hard work with port forwarding, file sharing and expose it back to the host to be used by Docker Compose.

**Comment by cweagans** [comment]
IMO, even better would be to let the Docker provider pull container info directly from a docker-compose.yml file. When you run `vagrant up`, you get the Docker host if necessary, and then any containers specified in your Docker Compose file.

That said, this is already possible - just set your DOCKER_HOST env var to the IP of the vagrant box. If the docker port is reachable, it should work just fine.

**Comment by radeksimko** [comment]
> IMO, even better would be to let the Docker provider pull container info directly from a docker-compose.yml file.

I'm not against the idea, but I don't see much benefit in vagrant being able to parse `docker-compose.yml` and building something on top of it.

> That said, this is already possible - just set your DOCKER_HOST env var to the IP of the vagrant box. If the docker port is reachable, it should work just fine.

It is possible, whether it's convenient is another story though.

Compared to `docker-machine` it is not very convenient.
I would expect something like `vagrant env` that would simply spit out something like

```sh
export DOCKER_HOST=tcp://127.0.0.1:2376
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH="`pwd`/tls"
```

so then I could do `eval $(vagrant env)` for example.

But environment variables are just a smaller part of the problem I think.

The difficulty I see lies in differences between "`dockerd` providers" - this can be boot2docker, CoreOS or any conventional Linux distribution and on top of that you may have different versions of docker - and we need to get the values for the environment variables from those somehow.

**Comment by cweagans** [comment]
>  I don't see much benefit in vagrant being able to parse docker-compose.yml and building something on top of it.

The benefit is that on large teams of developers, you have a bunch of different configurations you have to deal with. Having a single `vagrant up` command to get a local env up and running is obviously very valuable, and people are used to Vagrant.

That said, maybe parsing the file isn't the way to go there. Just run docker-compose inside the VM with the docker-compose.yml specified in your vagrantfile.

> Compared to docker-machine it is not very convenient.

Docker Machine isn't very flexible though. Being able to customize the FS mount options in my Vagrantfile, for instance, has made local dev with docker not suck. Using compose on the host with a Vagrant VM is probably not very convenient, but remember that that's not really what vagrant was built for. The env is supposed to be kind of self contained.

> The difficulty I see lies in differences between "dockerd providers" 

There's not really a lot of differences between providers in a Vagrant box. This should work for most cases for local environments:

```
export DOCKER_HOST=tcp://$(vagrant ssh b191d89 -c "ip address show eth0" | grep 'inet ' | awk -F"/24" '{print $1}' | awk -F"inet " '{print $2}')
unset DOCKER_TLS_VERIFY
unset DOCKER_CERT_PATH
```

but again, I'd probably lean toward just running things inside the VM.

**Comment by radeksimko** [comment]
> The benefit is that on large teams of developers, you have a bunch of different configurations you have to deal with. Having a single vagrant up command to get a local env up and running is obviously very valuable, and people are used to Vagrant.

Yes, what I meant is that I don't see much point in adding `docker-compose`-specific logic into Vagrant when that can be just one tool that deals with this problem. This would suddenly get a much wider problem, unless you want to be disadvantaging other tools.

> Docker Machine isn't very flexible though.

I absolutely agree, docker machine doesn't even provide way to codify the settings to start with.

> Using compose on the host with a Vagrant VM is probably not very convenient, but remember that that's not really what vagrant was built for. The env is supposed to be kind of self contained.

While I agree the env should be self contained I also think it should not necessary prevent users from using it with other tools. After all [otto](https://github.com/hashicorp/otto) is built on top of vagrant.

Having said that, I see more traction in Otto in these days and also my Go skills are better than Ruby, so I'll probably try and come up with a solution in Otto.

**Comment by chrisroberts** [comment]
Closing via #8576

**Comment by weynhamz** [comment]
@chrisroberts How does #8576 solves this issue, I have went through the commits and test it myself, it seems it just converts Dockerfile to a docker-compose.yml file and run it with docker-compose, I thought the original idea is to allow run with an existing docker-compose.yml on a Linux host or boot2docker on Mac/Win.

**Comment by chrisroberts** [comment]
@weynhamz Running with an existing docker-compose.yml introduces a number of edge cases. If you want to create a new issue / PR with an enhancement proposal for how usage with an existing docker-compose.yml file should behave, I'd be happy to review it.

Cheers!

**Comment by weynhamz** [comment]
I have tried the current compose driver, encountered couple of issues which I will report later on, besides that, I think the current compose driver approach is a more Vagrant way, which is to let the Vagrant do the orchestration, the only downsides is that I have to maintain a separate orchestration in Vagrantfile again.

If just delegate the orchestration work to docker-compose, I don't see the value of use Vagrant, it serves not difference with the docker machine, it can totally be replaced by docker-compose on Linux or docker-toolbox on Win/Mac.

If We just want to ease the effort to maintain the a Vagrantfile and a docker-compose.yml, do you think it is feasible to parse the existing docker-compose.yml by Vagrant so that Vagrant awares of the orchestration, then we can use Vagrantfile to additionally overrides some of the configuration to suit the local development, then generates a docker-compose.yml file and run it through the compose driver, make sense?
