### ISSUE TITLE
request: ability to force provision in any state

### ISSUE THREAD

**Issue by avdd** [mitchellh/vagrant#6604]
If I know the state of the VM, I can force a (re-)provision:
- destroyed: `up`
- halted: `up --provision`
- suspended: `resume; provision` (`up --provision` does not provision!)
- running: `provision` (`up --provision` does nothing)

If I want to script this, I could parse the output of `status`, but that's sloooow.

It would be nice to have some way of forcing a provision from any state.  Ideally `up --provision` would always work, but perhaps for backwards compat a flag could be added to `provision` to ensure the VM is running, e.g. `provision --up`

**Comment by TomyLobo** [comment]
````bash
if vagrant resume; then
    vagrant provision
else
    vagrant provision || vagrant up --provision
fi
````

Could possibly be shortened to:
````bash
vagrant resume; vagrant provision || vagrant up --provision
````

Another way:
````bash
vagrant up --no-provision; vagrant provision
````

**Comment by chrisroberts** [comment]
See #7979 for notes on next implementation

**Comment by TomyLobo** [comment]
Why not just fix `up --provision` to provision no matter the previous state of the machine?
In fact, that's exactly what you implemented as the new "provision --up" command.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
