### ISSUE TITLE
File provisioner is active even when explicitly excluded with --provision-with

### ISSUE THREAD

**Issue by evarga** [mitchellh/vagrant#6613]
Here is the scenario to reproduce the issue:

1. Create a Vagrantfile with a File and Shell provisioner. The File provisioner just needs to copy some file from the host into the VM
2. Make the source file inaccessible for the File provisioner
3. Provision the VM only with the Shell provisioner by issuing: ```vagrant provision --provision-with=shell```

The File provisioner will anyhow complain about the missing file. Here is the sample output:

```
[evarga@platform-automation]$ vagrant provision --provision-with=shell
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file /Users/evarga/Projects/platform-automation/provision/data/dummy.txt must exist
```

P.S. I have not tested whether this is only a special case for the File provisioner, or a general problem.

**Comment by sethvargo** [comment]
Hi there,

I took at a look at why this is happening, and it's because this validation is done as part of the configuration, not part of the actual provisioning. It affects all provisioners, not just file. I'm going to open a larger issue for this. Thanks!
