### ISSUE TITLE
Problem with chef-client provisioning

### ISSUE THREAD

**Issue by matjanin** [mitchellh/vagrant#6617]
When running `vagrant up`, `vagrant up --provision`, `vagrant reload --provision`, vagrant gets to the point:

```
==> client: Running provisioner: chef_client...
==> client: Detected Chef (latest) is already installed
==> client: Creating folder to hold client key...
==> client: Uploading chef client validation key...
Generating chef JSON and uploading...
==> client: Running chef-client...
PS C:\VM_chef>
```

And nothing happens... Sometimes it throw an exception saying:

```
Exception calling "Run" with "1" argument(s): "Could not load file or assembly 'Microsoft.PowerShell.Commands.Utility' or one of its dependencies. The system cannot find the file specified." At C:\tmp\vagrant-elevated-shell.ps1:61 char:1
```

Is it a vagrant-winrm problem or chef provisioner problem? Any ideas why it doesn't work properly?

I am using:

- Vagrant 1.7.4
- Virtualbox 4.3.28
- node: Windows server 2012 r2
- Vagrantfile (had to change to txt - couldn't upload it without file extention)
[Vagrantfile.txt](https://github.com/mitchellh/vagrant/files/47308/Vagrantfile.txt)

Updated Virtualbox to 5.0 - no effect :(
here's a log from running vagrant provision --debug: 
[debug.txt](https://github.com/mitchellh/vagrant/files/47336/debug.txt)

**Comment by sethvargo** [comment]
Hi @matjanin 

Thank you for opening an issue. The most common cause for that error is because the box you are using has not been configured to allow loading powershell remotely (see http://stackoverflow.com/questions/13799260/powershell-runtime-exception-could-not-load-file-or-assembly). I would recommend trying another base box or enabling remote powershell execution. This is not a Vagrant bug.

Please let me know if that works for you :smile:

**Comment by matjanin** [comment]
Thanks for such a fast reply :)

One question: How come the shell provisioner (powershell scripts) run on the guest vm and chef-client provisioner does not?
It's just odd.
Maybe it's a problem of the host machine? I'm running on Windows 7 SP1 64-bit
I'll try with another base box to see what'll come out of that.

**Comment by sethvargo** [comment]
All provisioners run on the guest VM

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
