### ISSUE TITLE
Vagrant try to provision a file leading to a crash deployment on CoreOS.

### ISSUE THREAD

**Issue by ArKam** [mitchellh/vagrant#6618]
Hi team :D

I do play a bit with CoreOS and Vagrant and found a really strange bug.
I did created a vagrant box on ATLAS providing a CoreOS Stable image, but when a try to vagrant up this image, I've got the following error message:

>DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG ssh: Uploading: /var/folders/f6/fbwv2yzn0gb87_sz0mvk7hv40000gn/T/vagrant20151130-12293-caykyx to /tmp/etcd-cluster.service
DEBUG ssh: Re-using SSH connection.
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: mv /tmp/etcd-cluster.service /media/state/units/ (sudo=true)
DEBUG ssh: stderr: mv: cannot move '/tmp/etcd-cluster.service' to '/media/state/units/': No such file or directory
DEBUG ssh: Exit status: 1
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mv /tmp/etcd-cluster.service /media/state/units/
Stdout from the command:
Stderr from the command:
mv: cannot move '/tmp/etcd-cluster.service' to '/media/state/units/': No such file or directory

Unfortunately I don't want Vagrant to do so as I'm not using ETCDv1 but v2 instead and have my own cloud-config file provisioned later on the box through a vagrant provisioning process.

This behavior lead vagrant to stop interpreting the vagrantfile and then do not use the provisioner.

Step to reproduce:
Build a base box on ATLAS or LOCALLY using packer using my metadata.json: https://gist.github.com/ArKam/f42dac1e94090744c32b
Launch a VM using vagrant up from my vagrantfile: https://gist.github.com/ArKam/fd0e507cea4d5f228929

If you want the box to load correctly and don't have issue with it, just comment the networking part of the vagrantfile at the end.

So it seems to be related to the way Vagrant try to provision Network informations on CoreOS when not using three interfaces (NAT / BRIDGE / HOSTONLY) instead of NAT Only.

I'm using Vagrant 1.7.4 on MacOS X 10.11

**Comment by ArKam** [comment]
Hi team, any update on this issue???

**Comment by sethvargo** [comment]
Hi @ArKam 

I just tried this using a few different CoreOS boxes on Atlas and I could not reproduce. I did get a few other errors which I'm trying to identify if are core bugs or bugs in the box itself, but I do not think this issue is present any more. 

If this issue persists, could you please open a new issue and follow the associated issue template? That will help us collect all the required information for a reproduction case. Thanks and sorry for the delayed response! 😄

**Comment by ArKam** [comment]
Hi @sethvargo for sure! I'll be more than happy to test again and see any improvement on this topic.
Then, if I still face the error I'll open an other issue with the proper template and a backlink on this one for history purpose.
