### ISSUE TITLE
ansible: Please allow generating group variables in the dynamic inventory.

### ISSUE THREAD

**Issue by chenz** [mitchellh/vagrant#6619]
The docs state:
> The generation of group variables blocks (e.g. [group1:vars]) are intentionally not supported, as it is not recommended to store group variables in the main inventory file. A good practice is to store these group (or host) variables in YAML files stored in group_vars/ or host_vars/ directories in the playbook (or inventory) directory.

There are use cases where you want to set variables that are specific to the inventory, so they naturally should be put into the inventory file. 

If Ansible allows it, so should Vagrant IMO. I don't think it should be Vagrant's job to enforce Ansible *preferred* practices as mandatory.

**Comment by gildegoma** [comment]
@chenz thanks for reporting your improvement request. This limitation is not here as an enforcement, but as the result of code+usage simplification. Here a quick summary about why we so far decided to not support this Ansible feature:

* Ansible documentation itself doesn't recommend to use inventory variables. See http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data.
* The Ansible provisioner does not aim at supporting every single feature from Ansible, but to cover Vagrant user needs. See also https://github.com/mitchellh/vagrant/issues/3396#issuecomment-66905405 about our support guidelines.

> use cases where you want to set variables that are specific to the inventory

Can you please elaborate a little more about that point (e.g. with an example) ?

**Comment by chenz** [comment]
My specific use case is a subnet definition that I need to share between hosts. The subnet definition depends on the network addresses assigned to the hosts in the Vagrantfile, so it is is highly specific to the inventory defined by Vagrant.

When make the setting outside of the Vagrantfile (static inventory or group_vars), I am losing the convenience of the dynamic inventory, as well as spreading these closely related settings (address and subnet) across two separate files.

**Comment by gildegoma** [comment]
@chenz The "DRY" reuse of the `Vagrantfile` content is a very good point indeed :+1: 

Now, let's try to figure out how this should be implemented. All the "inventory vars" capabilities should be supported:
* [host variables](http://docs.ansible.com/ansible/intro_inventory.html#host-variables)
* [group varialbes](http://docs.ansible.com/ansible/intro_inventory.html#group-variables)

@chenz first question: are you interested to work on a PR for this addition?

**Comment by chenz** [comment]
I can give it a go. It should be trivial for the group variables, since Vagrant basically already does it. I think the syntax from the negative example in the docs

    ansible.groups = {"mygroup:vars" = > {...}}
should be used, since it is consistent with the other group options. For the host variables, a new field would be required though. Maybe something like:

    ansible.host_vars => {"host1" => {...}, "host2" => {...}}
