### ISSUE TITLE
request for feature: Possibility to use grouping feature on VirtualBox provider

### ISSUE THREAD

**Issue by ArKam** [mitchellh/vagrant#6622]
Hi Team,

On provider VirtualBox, starting from v5.0 you can logically group your VMs, it would be cool if vagrant could integrate this feature parameter on the Vagrantfile description.

If I just don't correctly RTFM nevermind my request ;-)

Cheers!

**Comment by sethvargo** [comment]
Hi @ArKam 

Thank you for opening an issue. This seems like a good idea, but it's pretty virtualbox specific. As such, I think we would like to see this as a community plugin before we move something like this into Vagrant core. Additionally, we would want to give Virtualbox 5.0 more time to sink into the ecosystem :smile:. We will definitely keep this in mind though! Thanks! :smile:

**Comment by ArKam** [comment]
You're welcome, no problem ;-) for sure I do understand that.
