### ISSUE TITLE
Ubuntu 14.04 have a problem connecting to atlas.hashicorp.com:443

### ISSUE THREAD

**Issue by Oloremo** [mitchellh/vagrant#6628]
Vagrant 1.7.4
Ubuntu with lates updates.

```
# vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error: Unknown SSL protocol error in connection to atlas.hashicorp.com:443
```

Same with system curl
```
curl -v https://atlas.hashicorp.com/
* Hostname was NOT found in DNS cache
*   Trying 52.0.120.138...
* Connected to atlas.hashicorp.com (52.0.120.138) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to atlas.hashicorp.com:443
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to atlas.hashicorp.com:443
```

Not sure if it's vagrant related or Ubuntu related.

**Comment by sethvargo** [comment]
Hi @Oloremo 

Thank you for opening an issue. How did you install Vagrant? Have you changed your certificate chain on your machine? Can you please gist the debug logs and attach a link to this issue? Thanks! :smile:

**Comment by Oloremo** [comment]
1) How did you install Vagrant?
Downloaded deb from the off site & dpkg -i
All plugins installed via vagrant plugin install

```
# vagrant plugin list
vagrant-hostmanager (1.6.1)
vagrant-libvirt (0.0.32)
  - Version Constraint: >= 0.0.31
vagrant-share (1.1.4, system)
```
2) Have you changed your certificate chain on your machine?
No, it's basicly fresh setup + aptitude safe-upgrade and vivid kernel

I'm aware of bug with cert chain in 1.7.2 but it's not looks like it. 
3) Can you please gist the debug logs and attach a link to this issue?
How can I produce debug log? I'm kinda new to vagrant.

**Comment by sethvargo** [comment]
https://docs.vagrantup.com/v2/other/debugging.html

**Comment by Oloremo** [comment]
Thank you,

https://gist.github.com/Oloremo/a4406c4a22fd36940266

**Comment by sethvargo** [comment]
Hi @Oloremo,

I just tried to reproduce this with Vagrant 1.8.1 on an Ubuntu 14.04 host, and I was unable to do so. Is there any additional information you can supply to help us debug the issue?

**Comment by Oloremo** [comment]
@sethvargo Im sorry, I didnt post update, it was a networking problem in datacenter, so, you could close this issue.
