### ISSUE TITLE
Hyperv losing provisioning after a couple of hours

### ISSUE THREAD

**Issue by borrelan** [mitchellh/vagrant#6629]
First of all I wanted to thank the developers of vagrant for creating an awesome tool that has become a crutial part of my development process.  My issues all started after the last windows upgrade.

My issue is I can't seem to keep a hyperv box provisioned (daily occurrence).  Vagrant keeps losing track of the provisioned box (default in this case).

````
λ vagrant reload
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

==> default: VM not created. Moving on...
````

I installed from source because the default vagrant uses an extremely outdated version of ruby and the misc powershell issues with multiple interfaces and whatnot (which have been fixed recently - thanks!).

I'm currently on master branch (as of 20151202) which reports vagrant as v1.7.2 and my windows version is 10.0.10586 Build 10586 on a x64-based PC.

Although this would be annoying at best, since it takes hours to provision this box using salt and since I'm unable to use a presalted image because of this issue (https://github.com/mitchellh/vagrant/issues/5308), I've essentially lost my development environment.  For the time being I will see if I will get lucky with @knightsamar workaround as described here: https://github.com/mitchellh/vagrant/issues/1082#issuecomment-139504098

**Comment by sethvargo** [comment]
Hi @borrelan 

The master branch should report 1.8.0.dev. Please follow the instructions in the wiki for installing from source. Please note that installing from source is not officially supported, but we will do our best to try and help you debug. Vagrant 1.8 official will be launching very shortly.

**Comment by borrelan** [comment]
Upgrading to vagrant 1.8.0.dev appears to have resolved the above issue.

**Comment by shotah** [comment]
Having this issue on vagrant 1.8.5.

**Comment by tschlich** [comment]
also having this issue on Windows 10 using vagrant 1.8.5
