### ISSUE TITLE
Support etcd2.0  on Vagrant Using vm.provider plugin

### ISSUE THREAD

**Issue by gustavo-hp** [mitchellh/vagrant#6630]
The major problem was run etcd 2.* using vagrant, that require new parameters after the image on docker command
    e.g. docker run -d -p 4001:4001 ARGS {etcdCoreOsimage} -newArgs
We need to setup a string with new args at the end of docker run command call.
    
Follow this example that initiate a docker image with etcd 2.* https://coreos.com/etcd/docs/latest/docker_guide.html

I appreciate your attention.

Regards, Gustavo Cagnin

**Comment by sethvargo** [comment]
Hi @gustavo-hp 

Please take a look at the [Docker provider documentation](https://docs.vagrantup.com/v2/docker/configuration.html). You can use the `create_args` command to pass arguments as well as `cmd`.

**Comment by gustavo-hp** [comment]
Hi @sethvargo 

Create_args put the arguments before the image name and cmd runs the command internally docker using ssh.

Is it possible put those newArgs after the docker image name?

codeGeneratedFromVagrant: docker run -d -p 4001:4001 {create_args} {DOCKER_IMAGE} -newArgs

I already checked the documentation, and also code itself which is located is here https://github.com/mitchellh/vagrant/blob/master/plugins/providers/docker/driver.rb


Thanks

**Comment by sethvargo** [comment]
Hi @gustavo-hp 

If I understand correctly, you are trying to specify a value for `newArgs` in your example above. You can use the `cmd` flag for this:

```ruby
p.cmd = ["-arg"]
```

**Comment by gustavo-hp** [comment]
Take a look at the following file and, when I ran # vagrant up etcd the code was not generated properly
https://gist.github.com/gustavo-hp/14dfd1f6f2d3e670b7b2

vagrant need to generate the following docker command to so etcd can run ok 
docker run --name etcd  -p 4001:4001  quay.io/coreos/etcd:v2.2.2  -advertise-client-urls http://127.0.0.1:2379,http://127.0.0.1:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001

**Comment by sethvargo** [comment]
This is the command Vagrant is running:

```
docker run --name etcd -d --expose 4001 -p 4001:4001 -v /var/lib/docker/docker_1449161995_2291:/vagrant -h etcd quay.io/coreos/etcd:v2.2.2 -advertise-client-urls http://127.0.0.1:2379,http://127.0.0.1:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
```

That looks correct to me?

**Comment by gustavo-hp** [comment]
That's correct but the issue itself is regarding Vagrantfile don't generate that command, you could try use p.cmd=[""] or p.create_args=[""], but those arguments don't provide a sufix arguments that are set after image name in our example after "quay.io/coreos/etcd:v2.2.2" .

Regards,
Gustavo.

**Comment by sethvargo** [comment]
@gustavo-hp that's the command it's generating (I copied it from the Vagrant output)... What error are you getting?

**Comment by gustavo-hp** [comment]
@sethvargo  I don't understand are you using vm.provider or vm.provision?
could you please paste your vagrantfile so I can check if I'm doing wrong, thanks!

**Comment by sethvargo** [comment]
@gustavo-hp I copied your Vagrantfile exactly and ran it locally with Vagrant 1.7.4. What error are you getting?

**Comment by gustavo-hp** [comment]
I'm using 1.7.4-3 with Linux gustavo-hp 4.2.5-1-ARCH 
After you run "vagrant up etcd" using the vagrantfile try to do "docker logs -f etcd"
or better check if etcd is running on port 4001. "curl http://localhost:4001/version" which is surprisingly not :) .  
I already clone the vagrant repository and made the change by myself, we need to put extra arguments after the image name. Can I submit this branch to you so you'll better understand.

**Comment by sethvargo** [comment]
Hi @gustavo-hp 

You can submit a pull request, but I still don't fully understand your issue. The command I provided above is the command that Vagrant is running, and the arguments are after the image name.

**Comment by gustavo-hp** [comment]
Hi @sethvargo 

Try to run docker logs -f etcd, that command will expose what's happened on etcd. If your etcd is running fine, I suppose my environment are different than yours, please try to execute that command, maybe vagrant is generating the command but not executing it properly.

**Comment by gustavo-hp** [comment]
Everything went OK so I was able to start etcd using Env Vars,  d.env = { 
       ETCD_NAME:"etcd0",
       ETCD_ADVERTISE_CLIENT_URLS: "http://127.0.0.1:2379,http://127.0.0.1:4001",
       ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379,http://0.0.0.0:4001",
       ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://127.0.0.1:2380",
       ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380",
       ETCD_INITIAL_CLUSTER_TOKEN:"etcd-cluster-1",
       ETCD_INITIAL_CLUSTER: "etcd0=http://127.0.0.1:2380",
       ETCD_INITIAL_CLUSTER_STATE: "new",
      }

Using this, everything worked fine, but the feature haven't implemented yet using vagrant with docker provider plugin. THANKS !
