### ISSUE TITLE
rsync error after update box

### ISSUE THREAD

**Issue by desertknight** [mitchellh/vagrant#6631]
Why i get error like this:

```
"rsync" could not be found on your PATH. Make sure that rsync
is properly installed on your system and available on the PATH.
```

when updated box debian/jessie64 to 8.2.2?
When downgrade box version to 8.2.1, error message disappear o.O

Vagrant version is 1.7.4, running on Windows 7 (cygwin is not installed).

**Comment by sethvargo** [comment]
Hi @desertknight 

What command are you running when you get that error? Is it possible that the updated box does not have rsync installed?

**Comment by desertknight** [comment]
Sorry, after 
`vagrant up` 
I never installed rsync, or cygwin. But why debian/jessie64 version 8.2.1 not use rsync and start, without any problems? That's happen only on latest version 8.2.2.

**Comment by sethvargo** [comment]
Hi @desertknight 

Both the host (your windows machine) and the guest (debian) must have rsync installed in order to use rsync synced folders. It's possible that debian/jessie64 had rsync installed by default, but the new version does not. Could you please share your Vagrantfile and the output of the `up` command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by desertknight** [comment]
Thanks for help @sethvargo , here is my [vagrant file and output debug log](https://gist.github.com/desertknight/885ab67e7b57e5b7fa15). It's not all debug info, but if you think is mistake, i will copy all.

**Comment by sethvargo** [comment]
@desertknight do you have rsync installed on your windows machine? That error is occurring on the _host_ machine, not the guest.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/4073#issuecomment-161708579

**Comment by desertknight** [comment]
[No](https://github.com/mitchellh/vagrant/issues/6631#issuecomment-161543211), i don't have rsync, neither a host or guest machine (if come with new version on debian/jessie65, i don't know). But that's my question, why newer version give me that error?.

**Comment by sethvargo** [comment]
Hi @desertknight,

You must have rsync installed on the host in order to use the rsync capability. I'm not sure why it worked with the previous box.

**Comment by desertknight** [comment]
Hi @sethvargo ,thanks again for the asnwers :)
I have installed [msysgit](https://www.vagrantup.com/blog/feature-preview-vagrant-1-5-rsync.html), and maybe there is "my" rsync on host, just because i don't have any problem till now.
For now, i just downgrade my debian box, but .. that's so nasty solution :)

**Comment by LondonAppDev** [comment]
I am experiencing this exact problem. All was working fine until I updated my debian vagrant box, now I get the folloing when doing `vagrant up`:

```
"rsync" could not be found on your PATH. Make sure that rsync
is properly installed on your system and available on the PATH.
```

**Comment by LondonAppDev** [comment]
Now I know why this issue occurs on the latest version of the box. The last update was: `virtualbox: switch to rsync as default method for synced folders, because vboxfs requires contrib or non-free packages` (https://atlas.hashicorp.com/debian/boxes/jessie64).

I tried installing rsync with cygwin and now I get this error when trying to load my vagrant box:
```
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /c/Users/mark/Workspace/SaltStatesDev/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/mark/Workspace/SaltStatesDev/.vagrant/machines/deploy1/virtualbox/private_key' --exclude .vagrant/ /c/Users/mark/Workspace/SaltStatesDev/ vagrant@127.0.0.1:/vagrant
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
dup() in/out/err failed
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```

**Comment by chriscollinsboxuk** [comment]
I'm seeing the same problem. Windows 10 host machine running a VirtualBox Centos 6 box was fine with a synced_folder set up that worked correctly. We've just changed the box to centos/7 and now I'm getting the following when running vagrant up:

```
==> web: Importing base box 'centos/7'...
==> web: Matching MAC address for NAT networking...
==> web: Checking if box 'centos/7' is up to date...
==> web: Setting the name of the VM: client-name_web_1450355973246_19905
"rsync" could not be found on your PATH. Make sure that rsync
is properly installed on your system and available on the PATH.
```

I did not have rsync installed. After installing cwRsync and making it available on my path, I'm seeing the following error instead when running vagrant up:

```
 web: Rsyncing folder: /d/www/client-name/windows-ansible-vm/ansible-project/app-name/ => /home/vagrant/sync
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /d/www/client-name/windows-ansible-vm/ansible-project/app-name/
Guest path: /home/vagrant/sync
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/Users/chrisc/.vagrant.d/insecure_private_key' --exclude .vagrant/ /d/www/client-name/windows-ansible-vm/ansible-project/app-name/ vagrant@127.0.0.1:/home/vagrant/sync
Error: cygwin warning:
  MS-DOS style path detected: C:/Users/chrisc/.vagrant.d/insecure_private_key
  Preferred POSIX equivalent is: /Users/chrisc/.vagrant.d/insecure_private_key
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
rsync: change_dir "/d/www/client-name/windows-ansible-vm/ansible-project/app-name" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1165) [sender=3.1.1]
```

**Comment by mhotchen** [comment]
Same issue on Windows 7 with the 8.2.2 debian64 image. The documentation says that virtualbox is the default, but there doesn't seem to be any way of changing a synced_folder back to using virtualbox so now it seems I'm stuck using rsync, nfs, or samba, even though virtualbox was the only one that worked consistently across platforms without additional setup.

I don't mind the change itself but I think adding instructions for how to change a synced_folder to use virtualbox and making sure that rsync isn't a required external package would be necessary.

**Comment by F21** [comment]
Seeing the same issue here with the `debian/wheezy64` image with Vagrant 1.8.1, VirtualBox 5.0.12 on Windows 8.1 64-bit while trying to run the consul demo image (rsync sycned folders were not enabled):

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT

echo Installing dependencies...
sudo apt-get update
sudo apt-get install -y unzip curl

echo Fetching Consul...
cd /tmp/
wget https://releases.hashicorp.com/consul/0.6.0/consul_0.6.0_linux_amd64.zip -O consul.zip

echo Installing Consul...
unzip consul.zip
sudo chmod +x consul
sudo mv consul /usr/bin/consul

sudo mkdir /etc/consul.d
sudo chmod a+w /etc/consul.d

SCRIPT

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/wheezy64"

  config.vm.provision "shell", inline: $script

  config.vm.define "n1" do |n1|
      n1.vm.hostname = "n1"
      n1.vm.network "private_network", ip: "172.20.20.10"
  end

  config.vm.define "n2" do |n2|
      n2.vm.hostname = "n2"
      n2.vm.network "private_network", ip: "172.20.20.11"
  end
  
  config.vm.define "n3" do |n3|
      n3.vm.hostname = "n3"
      n3.vm.network "private_network", ip: "172.20.20.12"
  end
end
```

**Comment by LondonAppDev** [comment]
@mhotchen yes I agree that it would be great to have a way to switch back to the VirtualBox synced folders. The documentation seems to suggest you can (https://docs.vagrantup.com/v2/synced-folders/virtualbox.html) however it doesn't describe how.

**Comment by synaesthesia** [comment]
The new box probably does not have the guest addon installed. Login into the guest OS with virtualbox (without using vagrant, user/pass: vagrant), and try:

> sudo modprobe vboxadd
or
> sudo modprobe vboxvfs
or
> lsmod | grep -i vbox

I have just tested the box centos/7 and no guest addon pre-installed inside. 

@LondonAppDev

> it would be great to have a way to switch back to the VirtualBox synced folders ... however it doesn't describe how

like you said previously:

> The last update was: virtualbox: switch to rsync as default method for synced folders, because vboxfs requires contrib or non-free packages

Virtualbox addon is no more pre-installed. So, it's not possible to switch back to the default sync folder without installing virtualbox addon. You must install it if you want to use it.

**Comment by LondonAppDev** [comment]
@synaesthesia oh yes that makes sense. Didn't realize they actually removes guest additions. Do you know what `type` it should be on the `synced_folder` to make it use VirtualBox if I install it manually?

**Comment by tomahoax** [comment]
@LondonAppDev After some searches I've found that type value should be "virtualbox"

**Comment by LondonAppDev** [comment]
@tomahoax I thought that but it doesn't work, however as @synaesthesia mentions above, it won't work without the VirtualBox Guest Additions being installed first, and as they removed it from this Debian image I'll need to manually install it.

**Comment by tomahoax** [comment]
@LondonAppDev Prior to launching the `vagrant up` command I've proceeded with the install of `vagrant plugin install vagrant-vbguest` wich caused the automatic install of the VirtualBox Guest Additions on first boot this solved the issue for me you should give a try ;)

**Comment by dgtombs** [comment]
For those of you trying to use CentOS, the [Bento Project](http://chef.github.io/bento/) provides CentOS boxes with the guest additions installed (e.g., [bento/centos-7.1](https://atlas.hashicorp.com/bento/boxes/centos-7.1)).

**Comment by LondonAppDev** [comment]
@tomahoax worked perfect. Genius workaround. Thank you!

**Comment by MarcinOrlowski** [comment]
While installing `vagrant-vbguest` may be drop-in solution for some,  in my case I had also edit `C:\Users\<USER>\.vagrant.d\boxes\debian-VAGRANTSLASH-jessie64\8.3.0\virtualbox\Vagrantfile` and alter `type` in

     config.vm.synced_folder \
          ".",
          "/vagrant",
          type: "rsync"

to be `virtualbox`

**Comment by sethvargo** [comment]
Hi all,

This appears to be an issue with the debian box, and not a widespread Vagrant issue. Without the vbox guest additions installed, synced folders will not work. As such, I would recommend using the Bento project boxes (under the `bento` namespace), since they include the guest additions and have been known to work well across multiple operating systems. Thanks! :smile:

**Comment by desertknight** [comment]
F*ck ... i will use just use older version :( f*ck

**Comment by mhotchen** [comment]
Thanks @sethvargo, I'll do exactly that!

**Comment by amoe** [comment]
Want to point out that `debian/contrib-jessie64` exists in Atlas since February.   You can just switch to this box and shared folders will start working, if you're indifferent to the licensing issues.

**Comment by desertknight** [comment]
Also, you can throw an eye on desertknight/debian8-x64, which i did and add 50gb storage space.

**Comment by buckeyesid** [comment]
Thanks @MarcinOrlowski  .. I did  <config.vm.synced_folder ".", "/vagrant", disabled: true> and it worked perfectly.

**Comment by buckeyesid** [comment]
`I did`

**Comment by buckeyesid** [comment]
Thanks @MarcinOrlowski   I did

**Comment by brutzman** [comment]
Running on windows 7 enterprise using cygwin... added rsync via cygwin setup, then worked fine.

**Comment by sebkouba** [comment]
I tried a lot of stuff and finally @MarcinOrlowski had a working solution for me. I'm on Vagrant 1.9.0 with Git Bash shell installed. The other hacks editing the ruby library file didn't work for me...

**Comment by lukasojd** [comment]
+1 it worked for me config.vm.synced_folder ".", "/vagrant", disabled: true
