### ISSUE TITLE
Support etcd2.0 on Vagrant Using vm.provider plugin 

### ISSUE THREAD

**Issue by gustavo-hp** [mitchellh/vagrant#6637]
Hi all,

Regarding the issue I had open #6630 . @sethvargo closed but I'm a little bit confused.
Create_args put the arguments before the image name and cmd runs the command internally docker using ssh.

Is it possible put those newArgs after the docker image name?

codeGeneratedFromVagrant: docker run -d -p 4001:4001 {create_args} {DOCKER_IMAGE} -newArgs

I already checked the documentation, and also code itself which is located here https://github.com/mitchellh/vagrant/blob/master/plugins/providers/docker/driver.rb

Thanks

**Comment by sethvargo** [comment]
Hi @gustavo-hp 

We check both open and closed issues. I'll respond on the original issue to keep everything in one place. Thanks! :smile:
