### ISSUE TITLE
No host IP was given to the Vagrant core NFS helper. 

### ISSUE THREAD

**Issue by stephencooke** [mitchellh/vagrant#6638]
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug

we got this message after installing the vagrant-managed-servers plugin and attempting to use the rackspace provider.

it would seem that "vagrant provision --provider=rackspace" isnt a valid commandline and setting via 

VAGRANT_DEFAULT_PROVIDER environment variable didnt work.  we had to remove the "vagrant-managed-servers" plug completly before vagrant started to work with rackspace again

not sure if this is bug in vagrant not allowing multiple providers or an issue with the "vagrant-managed-servers": plugin.  I also raised this on their gitlab page

**Comment by sethvargo** [comment]
Hi @stephencooke 

Unfortunately we cannot not debug third-party plugin. If the plugin author deems this is a problem with Vagrant, we can gladly revisit it. Thank you for reporting! :smile:
