### ISSUE TITLE
`vagrant up` error on MacOS

### ISSUE THREAD

**Issue by phecho** [mitchellh/vagrant#6642]
```shell
hello@localhost Homestead (php-7)]$ vagrant up
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3

```

virtualbox version 5.0.10

**Comment by kamigerami** [comment]
Hello,

It seems you are not running the latest version of vagrant which supports virtualbox 5.0 => 

You might be running 1.7.3 or older.

What version are you on?

**Comment by sethvargo** [comment]
Hi @phecho 

As @kamigerami said, you must upgrade to Vagrant 1.7.4 or higher. You can download Vagrant from here: https://www.vagrantup.com/downloads.html. Thanks! :smile:
