### ISSUE TITLE
Vagrant SSH suspend is "hanged"

### ISSUE THREAD

**Issue by AnthonyWC** [mitchellh/vagrant#6645]
I tried using the usual ssh escape/suspend sequence with ~/Ctrl-Z combo in Vagrant SSH but even through it does suspended the SSH it doesn't go back to my original shell like in a regular openSSH session.

This is on Vagrant 1.7.4

**Comment by sethvargo** [comment]
Hi @AnthonyWC 

Thank you for opening an issue. Unfortunately there is not enough information to diagnose the issue. First, what is your host and guest operating system (your local machine and the vagrant box). Which escape sequences did you send - there are 5 possible SSH escape sequences.

Vagrant uses Ruby's net/ssh under the hood, so it's possible that net/ssh does not support the particular escape sequence you've sent.

**Comment by modelm** [comment]
I've got the same issue. I'm using Vagrant 1.7.4 on OS X 10.10.5 and I sent tilde followed by ctrl-z. My prompt now looks like this and the only way I've found to get out of it is by ctrl-c:

    vagrant@hostname:~/$ ~^Z [suspend ssh]

**Comment by sethvargo** [comment]
Hi all,

There was a bug in Vagrant 1.7 in our launcher where signals were not being sent to the underlying process. That has now been fixed. Thanks! :smile:
