### ISSUE TITLE
WinNFSd Error

### ISSUE THREAD

**Issue by Ciloe** [mitchellh/vagrant#6651]
Hi, 

I'm using vagrant all days but since few days, I have a problem with WinNFSd. This is the error message : 

```shell
=====================================================
WinNFSd v2.0
Network File System server for Windows
Copyright (C) 2005 Ming-Yang Kao
Edited in 2011 by ZeWaren
Edited in 2013 by Alexander Schneider (Jankowfsky AG)
Edited in 2014 2015 by Yann Schepens
=====================================================
Path #1 is: C:\wamp\www, path alias is: /C/wamp/www
Portmap daemon started
NFS daemon started
Mount daemon started
Local IP = 192.168.217.87
Type 'help' to see help

Path C:\wamp\www with path alias  /C/wamp/www already known
```

If I use the url project.dev which is connect to vagrant, it will never finish. If I go in vagrant ssh and I use 

```shell
cd /var/www
```

It will never finish too....

How can I correct that ?

I'm using :

 - Vagrant 1.7.2
 - Plugins :
    * vagrant-cachier
    * vagrant-omnibus
    * vagrant-librarian-chef-nochef
    * vagrant-vbguest
    * vagrant-winnfsd
 - VirtualBox 4.3.34

Thank you.

**Comment by Ciloe** [comment]
I'm using : 

- Vagrant 1.7.2
- Plugins : 
    * vagrant-cachier
    * vagrant-omnibus
    * vagrant-librarian-chef-nochef
    * vagrant-vbguest
    * vagrant-winnfsd
- VirtualBox 4.3.34

**Comment by Ciloe** [comment]
Any idea ?

**Comment by sethvargo** [comment]
Hi @Ciloe 

Thank you for opening an issue. Can you please try upgrading to the latest version of Vagrant (1.8.1) and uninstalling all plugins before continuing to debug? Thanks!

**Comment by Ciloe** [comment]
Hi @sethvargo 

Thank you for your reply.

I'm using :
* Windows 7 Enterprise
* Vagrant 1.8.1
* vagrant-cachier (1.2.1)
* vagrant-librarian-chef-nochef (0.2.0)
* vagrant-omnibus (1.4.1)
* vagrant-share (1.1.5)
* vagrant-vbguest (0.11.0)
* vagrant-winnfsd (1.1.0)

I must to disable all plugins ?

If I comment this line in Vagrantfile : 

```
    # Synced folders
    config.vm.synced_folder "C:/wamp/www", "/var/www", type: "nfs"
```

I haven't plroblem....

I'm ready to debug,

Thanks !

**Comment by sethvargo** [comment]
Hi @Ciloe 

Does the shared folder already exist on the guest? The error you are getting from NFS is "I cannot share this folder because a folder already exists at the share path".

**Comment by Ciloe** [comment]
Hi @sethvargo 

I have launch my vagrantup without the synced folder line. I haven't the "/var/www" path, so I think it didn't already exist. I don't know what append but I have search whe NFS cache file to delete the known line but I haven't find it...

Any idea ?

**Comment by sethvargo** [comment]
Hi @Ciloe 

Given this is working for other members of your team, I am inclined to believe this is a local environment issue, and not a bug in Vagrant. Can you compare the list of software and versions installed on your machine with a teammate?

**Comment by Ciloe** [comment]
Hi @sethvargo 

The computers are cloning with the same master. We have the same version of Software and plugins.

Thank you

**Comment by sethvargo** [comment]
Hi @Ciloe 

Unfortunately I have been unsuccessful in reproducing this issue. At this point, I would recommend destroying the vagrant box, removing the metadata directory, and starting from scratch :frowning: 

```
$ vagrant destroy -f
$ rm -rf .vagrant
```
