### ISSUE TITLE
vagrant_ansible_inventory missing from path

### ISSUE THREAD

**Issue by rynomster** [mitchellh/vagrant#6666]
When I try to provision my box, it runs my ansible playbook on localhost instead of on the vagrant box:

```
==> default: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_NOCOLOR=true ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --user=vagrant --connection=ssh --timeout=30 --limit='default' --inventory-file=/opt/vagrant/dev/.vagrant/provisioners/ansible/inventory --extra-vars={"vagrant":false,"jamdbpass":"password","m4jamdbpass":"password"} -v /home/rynomster/dev/ansible/main.yml
```
my Vagrantfile looks like so:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.2.100"
  config.vm.synced_folder "/opt/vagrant/data", "/data"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "/home/rynomster/dev/ansible/main.yml"
#    ansible.inventory_path = ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"
#    ansible.inventory_path = "vagrant_ansible_inventory_default"
    ansible.extra_vars = {
      create_vagrant_box: false,
      jamdbpass: "password",
      m4jamdbpass: "password",
    }
  end
end
```

I don't know if this is intentional, but it seems in `ship_generated_inventory` in the vagrant plugin, the actual file name never gets appended to the directory.

**Comment by rynomster** [comment]
According to this site, http://allandenot.com/devops/2015/01/16/ansible-with-multiple-inventory-files.html, it should load the inventory files from the directory. I'm not sure why mine is running on localhost rather than on the vagrant box

**Comment by gildegoma** [comment]
@rynomster up to Vagrant version [1.7.4](https://github.com/mitchellh/vagrant/blob/v1.7.4/plugins/provisioners/ansible/provisioner.rb), only the `ansible` _host-based_ provisioner is available.

Ansible _guest-based_ provisioning capabilities will come with Vagrant 1.8 (and its new `ansible_local` provisioner). Please check the current [documentation](https://docs.vagrantup.com/v2/provisioning/ansible.html) and the project [changelog](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md).
