### ISSUE TITLE
docker network support for docker provider

### ISSUE THREAD

**Issue by modius** [mitchellh/vagrant#6667]
Is there an ETA for `docker network` support for the Docker provider?

> While links are still supported in this limited capacity, you should avoid them in preference of Docker networks. The link feature is expected to be deprecated and removed in a future release.

https://docs.docker.com/engine/userguide/networking/dockernetworks/

**Comment by bogdando** [comment]
Very good point!
For now, I have to deal with w/a like to create a network manually, like this:
# docker network create -d bridge --internal --ip-range=a.b.c.0/24 --subnet=a.b.c.0/24 foo

and then I'm expecting this example be working (but it is not):
config.vm.provider :docker do |d|
  d.image = "bar/qux"
  d.name = n1
  d.has_ssh = true
  d.cmd = ["/usr/sbin/sshd", "-D"]
  args = "-i -t --net=foo"
end

Then, expected command is like
# docker run -i -t  --net=foo --name ... snip ... -h n1 bar/qux
But something goes wrong and the container goes to the default "bridge" network, which defaults is 172.17.0.2/16 ... Note, that the expected command, if issued manually does exactly what wanted and puts the container to the foo network with the a.b.c.0/2 based IP!

So, would nice to have this implemented in a working and more friendly way :)

**Comment by teohhanhui** [comment]
Use Docker Compose? :)

**Comment by modius** [comment]
Aye.  Been working on some scripts to set up docker-machine and docker-compose to emulate the provisioning we currently do in Vagrant.

**Comment by bogdando** [comment]
But emulating is only a w/a, I have one for my case as well. But that is not a fix.

**Comment by teohhanhui** [comment]
You can use Docker Compose with Vagrant (that's what I do). Someone even made a plugin to simplify things :)

https://github.com/leighmcculloch/vagrant-docker-compose

**Comment by bogdando** [comment]
@teohhanhui it is the provisioner. It cannot configure networks for the docker *provider*

**Comment by teohhanhui** [comment]
Uhh I gave up pretty quickly the first time I tried the Docker provider (I need a cross-platform solution anyway, so a good-old VM it is)

**Comment by chrisroberts** [comment]
Closing via #8576
