### ISSUE TITLE
Docker provider attribute name

### ISSUE THREAD

**Issue by amarcinkowski** [mitchellh/vagrant#6669]
Hi,

it's rather not strictly a bug or an issue, but:

in config (vagrant/plugins/providers/**docker**/config.rb) there's a plural name:
```
attr_accessor :build_args
```
whether in https://docs.docker.com/engine/reference/commandline/build/ the name is in singular form:

```
--build-arg=[]                  Set build-time variables
```

It might be confusing during development.

Regards

**Comment by sethvargo** [comment]
Hi @amarcinkowski 

Thank you for opening an issue. I don't think changing the name is worth breaking the backwards compatibility promise, and the documentation is very clear. I don't think we aim for 1-1 parity with the Docker CLI :smile:. Thanks!
