### ISSUE TITLE
Configurable Display Monitor Count: VirtualBox

### ISSUE THREAD

**Issue by hodiapa** [mitchellh/vagrant#6670]
Is there a way to increment the Display Monitor Count in Virtualbox using the Vagrantfile. Currently the default is set to 1 display monitor.

**Comment by sethvargo** [comment]
Hi @hodiapa 

There is no high-level configuration option, but you can use the [customize](https://docs.vagrantup.com/v2/virtualbox/configuration.html) stanza with the `modifyvm` command. You can find the option in the VirtualBox documentation. Thanks! :smile:

**Comment by hodiapa** [comment]
Just for anyone else who might be refering to this issue. Solution is:
 
config.vm.provider "virtualbox" do |vb|
  	vb.customize ["modifyvm", :id, "--monitorcount", "2"]
  end
