### ISSUE TITLE
Reduce number of attempts to mount virtualbox shared folder

### ISSUE THREAD

**Issue by robnagler** [mitchellh/vagrant#6676]
The binary backoff algorithm in 
[mount_virtualbox_sharted_folder](https://github.com/mitchellh/vagrant/blob/82f620ed133cd37df967b5a1212d78bf6d3bb2c2/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb#L62) 
tries too many times so that a box without guest additions will hang on boot for 60 seconds unnecessarily. It already knows that guest additions are not installed (or out of date) so 
it should simple fail and move on.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
