### ISSUE TITLE
Fusion Pro not forwarding ports

### ISSUE THREAD

**Issue by nfloersch** [mitchellh/vagrant#6678]
This morning I updated to the latest update from Apple for OSX El Capitan - 10.11.2

I also updated to the latest patch from VMWare for Fusion Pro - 8.1.0 (3272237)

Since then I have been having no luck with my previously working Vagrant port forwards.

The "vagrant up" appears to work with no errors.

My Vagrant is running Windows Server 2012 R2. The firewall is turned off and it has generally worked fine regarding port forwards to let me access a Grunt-served web app, or the Postgres database. I have not recently updated Windows on the Vagrant, to be clear.

I rebooted the machine, and checked my settings through-and-through. I really did not change anything, aside from applying those two updates, before I noticed the problem with the port forwards.

Here is some output from the "vagrant up":

```
vader:vtag45 nick$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 0:5985
    default: WinRM username: vagrant
    default: WinRM transport: plaintext
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 3389 => 3389
    default: -- 22 => 2222
    default: -- 9000 => 9000
    default: -- 3000 => 3000
    default: -- 5432 => 5433
    default: -- 3001 => 3001
    default: -- 8888 => 8888
    default: -- 5985 => 55985
    default: -- 5986 => 55986
==> default: Configuring network adapters within the VM...
==> default: Configuring secondary network adapters through VMware 
==> default: on Windows is not yet supported. You will need to manually
==> default: configure the network adapter.
==> default: Rsyncing folder: /Users/nick/VMs/vtag45/ => /vagrant
==> default:   - Exclude: [".vagrant/", ".git/", "vtag/app/css/"]
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: vagrant-gatling-rsync is starting the sync engine because you have at least one rsync folder. To disable this behavior, set `config.gatling.rsync_on_startup = false` in your Vagrantfile.
==> default: Doing an initial rsync...
==> default: Rsyncing folder: /Users/nick/VMs/vtag45/ => /vagrant
==> default:   - Exclude: [".vagrant/", ".git/", "vtag/app/css/"]
==> default: Watching: /Users/nick/VMs/vtag45
==> default: Rsyncing folder: /Users/nick/VMs/vtag45/ => /vagrant
==> default:   - Exclude: [".vagrant/", ".git/", "vtag/app/css/"]
==> default: 05:10:52 PM: The rsync operation completed in 14804.824999999999 milliseconds.
```

In the past this has worked fine. Opening the web browser on the host machine and pointing it to "localhost:3000" would connect to Grunt's web server. Likewise, on the host I could run "ssh localhost -p2222" and connect to the SSH server on the Vagrant (yes, my Windows Vagrant has an SSH server). Now though, it looks like it is getting setup, but it is not.

All firewalls on the host and Vagrant are turned off. I disabled anti-virus. I tried changing the network adapter configuration, even. Previously the Vagrant was connecting to a private NAT VMNet. I switched it to bridged to see if it would help. It didn't. Funny how when it is bridged, the startup text about the WinRM address changes to a "0:5985" rather than the full address. But, yes it does get a full address that can be seen when logged into the VM.

Here is a Gist for the debug log:

https://gist.github.com/nfloersch/93613a102a93bf898bcf

**Comment by sethvargo** [comment]
Hi @nfloersch 

Thank you for the bug report. We tried to warn users (https://twitter.com/hashicorp/status/675043948566609920), but there is a major bug in Fusion 8.1 (https://communities.vmware.com/message/2561728#2561728). Unfortunately there is nothing Vagrant can do here, but the good news is that you can downgrade until VMware fixes the issue. Sorry!

**Comment by nfloersch** [comment]
Thanks @sethvargo - sorry I missed your announcements.
