### ISSUE TITLE
Windows 10 build 10586: Guest machine entered an invalid state

### ISSUE THREAD

**Issue by jazzfog** [mitchellh/vagrant#6679]
Yesterday my Windows 10 auto-updated to build 10586 and vagrant VMs do not start anymore

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20150609.0.10'. The latest is version '20151211.1.0'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: Test VM-2
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
```

It looks like it happens when I specify VM IP

`config.vm.network "private_network", ip: "192.168.100.100"`

- Windows 10.0.10586
- Vagrant version 1.7.4
- Virtualbox - latest stable version 5.0.10, also tested on test build 104721

So far I do not see any way to make it work.

**Comment by iomdesign** [comment]
Not a definite answer, but something I'd suggest worth checking. I had the same issue occurring and after much hair pulling discovered that VirtualBox wasn't able to boot up a basic test VM built via the VirtualBox GUI. 

Look in Control Panel >> Network and Sharing Center >> Change Adapter Settings

In there you should see a VirtualBox Host-Only connection. Right click on it and select Properties. 

In the info window you'll see a list of services and drivers. This is where I found that 'VirtualBox NDIS6 Bridged Networking Driver' was unchecked. This is the only driver available for VirtualBox I could find (used to offer option of NDIS5 as well). Anywho simply checking this resolved the issue for me and got things running again.

I assume that a change in Windows 10 latest version has caused an issue for VirtualBox. As I say it may be a bit of a red herring but still something to eliminate as the problem.

Obviously this doesn't fix the issue. Create another host only network connection in Virtualbox and the same problem occurs for me in my new adapter, but it gives a solution to resolve it.

Hope it helps.

**Comment by jazzfog** [comment]
Thanks for the idea, the checkbox actually was unchecked but checking it, unfortunately, didn't help.

**Comment by jazzfog** [comment]
I managed to resolve my issue: Not sure where the problem was but complete uninstall of Virtualbox and Vagrant and then install the same version back - helped.
