### ISSUE TITLE
Could not find a storage controller named 'SATA Controller'

### ISSUE THREAD

**Issue by NikosAlexandris** [mitchellh/vagrant#6686]
__Cloning the taiga-vagrant repository__
`git clone https://github.com/taigaio/taiga-vagrant.git`

__Attempt to provision__
`vagrant up` 

The instructed provision scripts, don't run. Thus, the end result is only a VBox with the pre-defined base box (ubuntu trusty64 currently). Here is the debug log: https://gist.github.com/NikosAlexandris/524394a2f5b5fc68c62c

I asked about this in #vagrant at Freenode.  And I was pointed that it could be likely a VirtualBox issue. Some of the debug lines, repeated multiple times in the log, are:
```
1801  INFO subprocess: Starting process: ["/opt/bin/VBoxManage", "modifyvm", "91c6e6e0-4f1a-4102-9aaf-0d70ac600950", "--natpf1", "ssh,tcp,127.0.0.1,2222,,22", "--natpf1", "tcp8000,tcp,,8000,,8000", "--natpf1", "tcp9001,tcp,,9001,,90     01"]
1802 DEBUG subprocess: Selecting on IO
1803 DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
1804 DEBUG subprocess: Exit status: 0
1805  INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SetHostname:0x007f294030c260>
1806  INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::SaneDefaults:0x007f294030c238>
1807  INFO subprocess: Starting process: ["/opt/bin/VBoxManage", "storagectl", "91c6e6e0-4f1a-4102-9aaf-0d70ac600950", "--name", "SATA Controller", "--hostiocache", "on"]
1808 DEBUG subprocess: Selecting on IO
1809 DEBUG subprocess: stderr: VBoxManage: error: Could not find a storage controller named 'SATA Controller'
1810 VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component SessionMachine, interface IMachine, callee nsISupports
1811 VBoxManage: error: Context: "GetStorageControllerByName(Bstr(pszCtl).raw(), ctl.asOutParam())" at line 1151 of file VBoxManageStorageController.cpp
1812 DEBUG subprocess: stderr: VBoxManage: error: Couldn't find the controller with the name: 'SATA Controller'
1813 DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
1814 DEBUG subprocess: Exit status: 1
1815  INFO retryable: Retryable exception raised: #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
1816 for controlling VirtualBox. The command and stderr is shown below.
1817 
1818 Command: ["storagectl", "91c6e6e0-4f1a-4102-9aaf-0d70ac600950", "--name", "SATA Controller", "--hostiocache", "on"]
1820 Stderr: VBoxManage: error: Could not find a storage controller named 'SATA Controller'
```

Any hint highly appreciated. Apologies for cross-posts.

**Comment by sethvargo** [comment]
Hi @NikosAlexandris 

This looks like a bug in the taiga-vagrant Vagrantfile. Can you please open an issue on that project?

**Comment by NikosAlexandris** [comment]
But, it works in other computers, other than in my laptop.  And, yes, there was already an issue but I closed it since it appears to be attached to my own setup... (?). Any other hints?

see https://github.com/taigaio/taiga-vagrant/issues/21

**Comment by NikosAlexandris** [comment]
Some hint from #vbox at Freenode:
> Vagrant is running 'VBoxManage storagectl' for a VM and tries to change settings for a storage controller called "SATA Controller". The VM in question doesn't have one.

Could it be a vagrant issue, after all?  An issue with a specific version of vagrant? I use version 1.4.3 (under Funtoo-Linux).

**Comment by sethvargo** [comment]
The latest version of Vagrant is 1.7.4. Please install Vagrant from the official downloads page: https://www.vagrantup.com/downloads.html.

**Comment by NikosAlexandris** [comment]
Thank you, I will try. I'd be nice if could make use of an ebuild (for Gentoo/Funtoo-Linux).  Or build one for myself.  Though I am not sure I have the time (and experience) to build it properly.

**Comment by NikosAlexandris** [comment]
I got to the latest vagrant version (for Gentoo/Funtoo) through angry_vincent in #funtoo at Freenode. It's available at http://data.gpo.zugaina.org/johu/app-emulation/vagrant-bin/. And it works! Finally.
