### ISSUE TITLE
Rsync fails because rsync-path option isn't quoted

### ISSUE THREAD

**Issue by wimnat** [mitchellh/vagrant#6690]
I'm running latest Vagrant on Windows 10 and I've been having big problems trying to get rsync to work.

My rsync command looks like this

```
 rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'id_rsa' --exclude .vagrant/ --exclude .git/ /cygdrive/c/codebase/bla/ ec2-user@54.200.144.186:/opt/codebase/bla
```

If I execute this myself manually then it fails with:

```
sudo: invalid option -- '-'
```

This is because the rysnc-path option isn't quoted properly.  The rync path and the follow -e ssh options all need to be quoted as such:

```
rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path "sudo rsync -e \"ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'id_rsa'\"" --exclude .vagrant/ --exclude .git/ /cygdrive/c/codebase/bla/ ec2-user@54.200.144.186:/opt/codebase/bla
```

Once quoted, rsync works as expected.

I can't figure out how to work around this though because even if i specify explicitly "sudo rsync" as my rsync path in my Vagrantfile, Vagrant still just adds all the unquoted options anyway. So the only thing i can do is manually rsync once the box is up.

**Comment by wimnat** [comment]
I've done a little further work on this.  I edited helper.rb for rsync to insert the quotes in the right places.  However, it still doesn't work.  I now get...

```
Error: rsync  version 3.1.1  protocol version 31
...full rsync syntax help...
```

But if i copy and paste the rsync command that is now displayed with quotes, it works perfectly.  Vagrant must be doing something under the hood that is causing rsync to fail.

**Comment by cnadeau** [comment]
PR https://github.com/mitchellh/vagrant/pull/7579

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/7580
