### ISSUE TITLE
[1.7.4] symlink don't work properly(puppet apply) linux guests (windows is fine)

### ISSUE THREAD

**Issue by lmayorga1980** [mitchellh/vagrant#6692]
I have the following Puppet Module structure.

```
/development/manifests/site.pp
/development/modules(symlink to root as [my-puppet-module])
/manifests(local puppet module development)
/modules(third-party modules)
Vagrantfile
...
```
The `puppet apply` provisioner looks good when running under Windows guests but fails under Linux Guests.

VirtualBox Version: **5.0.10 r104061**

**Comment by sethvargo** [comment]
Hi @lmayorga1980 

Thank you for opening an issue. Unfortunately there is not enough information here to diagnose the issue. Can you please share your complete Vagrantfile, the output of the command in debug mode as a GitHub Gist, and what provider you are using?

**Comment by lmayorga1980** [comment]
@sethvargo It actually does not break but the symbolic link does not work on linux guest.

https://gist.github.com/lmayorga1980/e4d2f05e97724a409862 (Vagrantfile)

The following structure is a puppet module that installs ruby on different platforms and we use r10k to bring down third-party dependencies.

![screen shot 2015-12-22 at 9 39 08 am](https://cloud.githubusercontent.com/assets/3172378/11957461/e4524ad2-a88f-11e5-9637-971a774cabd1.png)

It seems that it cannot find the ruby class.

```
==> centos6: Error: Evaluation Error: Error while evaluating a Resource Statement, Could not find declared class ruby at /tmp/vagrant-puppet/environments/development/manifests/site.pp:22:5 on node localhost.va.nreca.org
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

After vagrant-ssh i could see that the symbolic link did not work within the VM.

![screen shot 2015-12-22 at 9 45 55 am](https://cloud.githubusercontent.com/assets/3172378/11957633/d97ba7e2-a890-11e5-877e-21aed899774e.png)

**Comment by sethvargo** [comment]
Hi @lmayorga1980 

Again, there is not enough information here for us to reproduce the issue. Can you please share your complete Vagrantfile and relevant Puppet scripts?

The error(s) you described in your response all seem to be coming from Puppet, not Vagrant.

**Comment by lmayorga1980** [comment]
You are correct there is no crash from Vagrant but the same works on Windows Guest OS which is a little strange. I will provide more debugging information but i think the puppet provisioner that works on windows guest should also work on linux guest.

**Comment by sethvargo** [comment]
Hi @lmayorga1980 

I agree that the Puppet provisioner should work correctly on all operating systems, but please understand that we are not in your head. I've read this issue a number of times now, and it is still very unclear to me what the root issue is or how to reproduce it.

I don't see where a symlink is being created via Vagrant, which means Puppet is creating the symlink. Is it possible that the guest OS's filesystem does not support symlinks?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
