### ISSUE TITLE
vagrant parallels provider fails to bring up new machine

### ISSUE THREAD

**Issue by stevs986** [mitchellh/vagrant#6694]
OS X Version: El Capitan 10.11.2
Vagrant version: 1.7.4
Vagrant parallels plugin version: vagrant-parallels (1.5.1)

Vagrant file is really simple:
```
Vagrant.configure(2) do |config|
  config.vm.box = "parallels/ubuntu-14.04"
end
```

I got this error:
`/Users/[]/.vagrant.d/gems/gems/vagrant-nfs_guest-0.1.7/lib/vagrant-nfs_guest/providers/parallels/cap/nfs_settings.rb:7:in `nfs_settings': undefined method `provider' for nil:NilClass (NoMethodError)`

**Comment by sethvargo** [comment]
Hi @stevs986 

Thank you for opening an issue. This is a bug in the parallels provider. Please open an issue on that project. Thanks!

**Comment by stevs986** [comment]
@sethvargo Thanks!
