### ISSUE TITLE
Vagrant 1.8 fails on several commands using cmd.exe or Cygwin

### ISSUE THREAD

**Issue by thasmo** [mitchellh/vagrant#6697]
`vagrant status`, `vagrant help` etc. fail for Vagrant 1.8 on Windows 10, using cmd.exe or Cygwin:
```sh
# vagrant help
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

The RubyEncoder loader is not installed. Please visit the http://www.rubyencoder.com/loaders/ RubyEncoder site to download the required loader for 'mingw' and unpack it into 'C:/HashiCorp/Vagrant/embedded/rgloader' directory to run this protected script.
```
Do I need to follow the instructions and install the RubyEncoder manually?

**Comment by mitchellh** [comment]
Ouch, I tested on Windows so this is a bit of a surprise. Let me take a look, this is an installer issue.

**Comment by thasmo** [comment]
FYI, I did not remove Vagrant 1.7.x before installing 1.8.

**Comment by mitchellh** [comment]
Ah, I think I see the issue. Hunting it down now.

**Comment by thasmo** [comment]
And, in `C:\HashiCorp\Vagrant\embedded\rgloader` there are several files:
```sh
loader.rb
rgloader20.darwin.bundle
rgloader20.freebsd.so
rgloader20.freebsd.x86_64.so
rgloader20.linux.so
rgloader20.linux.x86_64.so
rgloader20.mingw.so
rgloader20.mingw.x64.so
rgloader20.mswin.so
```

**Comment by mitchellh** [comment]
Okay for some reason the published Windows installer doesn't have the latest rgloader files. I'm updating now, should take at most an hour if all goes well.

**Comment by thasmo** [comment]
Nice, thanks!

**Comment by pcfens** [comment]
I'm assuming they're related, but not sure if the fix will catch them both - I'm getting the same error on Ubuntu 64-bit:

```
$ vagrant init ubuntu/trusty64
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

The RubyEncoder loader is not installed. Please visit the http://www.rubyencoder.com/loaders/ RubyEncoder site to download the required loader for 'linux' and unpack it into '/opt/vagrant/embedded/rgloader' directory to run this protected script.
```

**Comment by mitchellh** [comment]
Okay, I found the issue on all platforms (other than OS X). Since this relesae was completely broken, I'm going to re-release 1.8.0 for those platforms shortly. There is zero code difference in Vagrant itself, just installesr.

**Comment by mitchellh** [comment]
Release is out!

**Comment by in-in** [comment]
Now it works on Ubuntu 14.04. Thanks.

**Comment by shochdoerfer** [comment]
Just for the record, even after using the fixed version vagrant was not able to start on my box:
```
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
```

Problem was that I had quite an old version of the vagrant-vmware-workstation plugin installed. Uninstalling and re-installing the plugin fixed the problem, the plugin update command did not work.

**Comment by jarpy** [comment]
Is this the fixed version for Ubuntu 64?

```
$ sha1sum ~/vagrant_1.8.0_x86_64.deb
b5db90d92d94e67d2630fdb85522141b4be23831  /home/toby/vagrant_1.8.0_x86_64.deb
```
I still have the issue with this deb package.
Thanks.

**Comment by mitchellh** [comment]
It is as is confirmed above, you may have an outdated plugin?

**Comment by jarpy** [comment]
Sorry. Where is it confirmed? The hash I haven't doesn't match: https://releases.hashicorp.com/vagrant/1.8.0/vagrant_1.8.0_SHA256SUMS
Is that file up to date?

**Comment by jarpy** [comment]
Cool. Downloaded a couple more times, and now have:
```
$ sha256sum ~/vagrant_1.8.0_x86_64.deb
57ead32cf4dedf783e066d6fa8a9a9957322a53996873abdfe0f5e5a56337143  /home/toby/vagrant_1.8.0_x86_64.deb
```
CDN cache not invalidated for a while?

Thanks. Out.

**Comment by mitchellh** [comment]
@jarpy That is up to date, you may be hitting a cache... hash of my local file: `57ead32cf4dedf783e066d6fa8a9a9957322a53996873abdfe0f5e5a56337143`

We sent a purge to all the CDN edges so I'm not sure, I'll send another purge now!

**Comment by jarpy** [comment]
All good. Thanks Mitchell!

**Comment by krizzna** [comment]
is it fixed for windows? i still got error on windows 10.

![2015-12-22](https://cloud.githubusercontent.com/assets/265179/11946607/de21a122-a88e-11e5-9834-a85bfd961e87.png)

**Comment by mitchellh** [comment]
@krizzna I believe you're hitting a cache.

@sethvargo do you know how to clear the cache for the files themselves? it looks liek our release tool only purges the index.

**Comment by sethvargo** [comment]
I just purged the caches.

**Comment by krizzna** [comment]
all good now. Thanks :+1:

**Comment by biemond** [comment]
Did you also make a new build for mac osx , I still got this bug with vmware fusion

**Comment by stedwick** [comment]
Doesn't work for me on Mac OS X

vagrant up
up
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit

**Comment by sethvargo** [comment]
Hi @biemond @stedwick,

Update to the latest Vagrant VMware plugin:

    $ vagrant plugin update vagrant-vmware-fusion

**Comment by biemond** [comment]
didn't work 

vagrant plugin update vagrant-vmware-fusion
Updating plugins: vagrant-vmware-fusion. This may take a few minutes...
All plugins are up to date.

**Comment by shochdoerfer** [comment]
@biemond uninstall and install the plugin. Update did not work for me either. No clue why.

**Comment by richardboydii** [comment]
I'm in the same boat as @biemond and @shochdoerfer. Getting error code 7 when trying to vagrant up. All plugins are up to date according the CLI and updating VMWare fusion just says that it's still up to date.

**Comment by stedwick** [comment]
Updating the plug-in worked for me on mac os x. (other people say to uninstall and reinstall the plug-in)

In the future, it would be nice if this was automated, or if there was some documentation during the install, other than running it and getting a mysterious "error code 7"

But thanks for fixing it so quickly.

**Comment by richardboydii** [comment]
vagrant plugin uninstall vagrant-vmware-fusion and vagrant plugin install vagrant-vmware-fusion got it working for me on Mac OS 10.11.12 (El Capitan).

**Comment by biemond** [comment]
it works for me too.

had to uninstall the vmware plugin and re-install it

**Comment by thasmo** [comment]
@mitchellh, I've installed the newly compiled Vagrant 1.8.0 now, gettin' this error:
```sh
# vagrant status
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
```
Reinstalling the plugin doesn't fix it. (I'm using the Workstation plugin version 3.2.12.)
Will #6712 also fix this for the Workstation plugin?

**Comment by todd-dsm** [comment]
@mitchellh sorry to re-open an old wound but this is still a problem. I noticed this yesterday on an F23 system after a  fresh upstream install:

```
$ vagrant -v
Vagrant 1.8.1

$ vagrant init ubuntu/trusty64; vagrant up --provider virtualbox
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit


$ vagrant plugin list
vagrant-share (1.1.5, system)
vagrant-vmware-workstation (3.0.0)

$ vagrant plugin uninstall vagrant-vmware-workstation
Uninstalling the 'vagrant-vmware-workstation' plugin...

$ vagrant plugin list
vagrant-share (1.1.5, system)

$ vagrant plugin install vagrant-vmware-workstation
Installing the 'vagrant-vmware-workstation' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vmware-workstation (4.0.8)'!
```

It looks like that vagrant-vmware-workstation (3.0.0) is still lingering out there.

This started with the fedora-provided package. Removed that, installed the upstream version:
https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.rpm

Checked the docs to make sure some small process hadn't changed. Tried un/re-install the vmware plugin as suggested and - back in business.

I have debug output if you would like to see it.
