### ISSUE TITLE
Vagrant Folder not found on '/Application' folder

### ISSUE THREAD

**Issue by yanlinaung30** [mitchellh/vagrant#6701]
I have installed vagrant via vagrant_1.8.0.dmg file.
But I cannot find vagrant folder on 'Applications' folder.
Where did vagrant install on OSX?

**Comment by mitchellh** [comment]
It installs into `/opt/vagrant` and is added to your PATH automatically.

**Comment by yanlinaung30** [comment]
Thank you!

**Comment by yanlinaung30** [comment]
This should be updated too, I think.
https://docs.vagrantup.com/v2/installation/uninstallation.html
