### ISSUE TITLE
vagrant 1.8.0 up error on vmware fusion, One of the parameters was invalid

### ISSUE THREAD

**Issue by biemond** [mitchellh/vagrant#6710]
vagrant 1.8.0 with vmware fusion Version = 8.1.0 (3272237), plus uninstall /install vmware plugin

vagrant init puppetlabs/centos-7.0-64-puppet

A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

vagrant up --provider vmware_fusion
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'puppetlabs/centos-7.0-64-puppet'. This can take some time...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["clone", "/Users/edwin/.vagrant.d/boxes/puppetlabs-VAGRANTSLASH-centos-7.0-64-puppet/1.0.1/vmware_desktop/packer-centos-7.0-x86_64-vmware-vagrant-puppet-1424820024.vmx", "/Users/edwin/tmp/.vagrant/machines/default/vmware_fusion/53332886-3802-4efc-b921-faa7bb78c28f/packer-centos-7.0-x86_64-vmware-vagrant-puppet-1424820024.vmx", "linked", {:notify=>[:stdout, :stderr]}]

Stdout: Error: One of the parameters was invalid

Stderr:

    INFO warden: Calling IN action: HashiCorp Background Check: End
     INFO logger: Cleaning up background activation thread...
     INFO warden: Calling OUT action: HashiCorp Background Check: End
    ERROR vagrant: Vagrant experienced an error! Details:
    ERROR vagrant: #<HashiCorp::VagrantVMwarefusion::Errors::VMRunError: An error occurred while executing `vmrun`, a utility for controlling
    VMware machines. The command and output are below:

    Command: ["clone", "/Users/edwin/.vagrant.d/boxes/puppetlabs-VAGRANTSLASH-centos-7.0-64-puppet/1.0.1/vmware_desktop/packer-centos-7.0-x86_64-vmware-vagrant-puppet-1424820024.vmx", "/Users/edwin/tmp/.vagrant/machines/default/vmware_fusion/c353ac39-dc2c-467c-90b3-2354bcd92dd7/packer-centos-7.0-x86_64-vmware-vagrant-puppet-1424820024.vmx", "linked", {:notify=>[:stdout, :stderr]}]

    Stdout: Error: One of the parameters was invalid

    Stderr: >
    ERROR vagrant: An error occurred while executing `vmrun`, a utility for controlling
    VMware machines. The command and output are below:

    Command: ["clone", "/Users/edwin/.vagrant.d/boxes/puppetlabs-VAGRANTSLASH-centos-7.0-64-puppet/1.0.1/vmware_desktop/packer-centos-7.0-x86_64-vmware-vagrant-puppet-1424820024.vmx", "/Users/edwin/tmp/.vagrant/machines/default/vmware_fusion/c353ac39-dc2c-467c-90b3-2354bcd92dd7/packer-centos-7.0-x86_64-vmware-vagrant-puppet-1424820024.vmx", "linked", {:notify=>[:stdout, :stderr]}]

    Stdout: Error: One of the parameters was invalid

    Stderr:
    ERROR vagrant: /Users/edwin/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.4/lib/vagrant-vmware-fusion/driver.rb:616:in `block (2 levels) in vmrun'

**Comment by sethvargo** [comment]
Hi @biemond 

This has been fixed in the latest version of the VMware plugin. Please uninstall and re-install the vagrant-vmware-fusion plugin:

```
vagrant plugin uninstall vagrant-vmware-fusion
vagrant plugin install vagrant-vmware-fusion
```

Sorry about that!

**Comment by biemond** [comment]
already did this and got the latest version.  it solved #6699 but this is a new error

    vagrant plugin list
    vagrant-share (1.1.5, system)  
    vagrant-vmware-fusion (4.0.4)

**Comment by sethvargo** [comment]
@biemond do you have vmware fusion or vmware fusion pro? Linked clones only work in fusion pro

**Comment by biemond** [comment]
vmware fusion normal edition. It makes sense.

Do I need to disable this and probably this should be the default.

**Comment by sethvargo** [comment]
@biemond the default in 1.8.1 will be "off" and it will be opt-in. Sorry about that!

**Comment by biemond** [comment]
@sethvargo 

can you release a new vmware fusion plugin where this in the meantime is disabled
the vmware doc said that linked cloning is not yet supported https://docs.vagrantup.com/v2/vmware/boxes

**Comment by biemond** [comment]
:+1:  I see you silently update the vmware plugin to 4.0.5

it works. Thanks for the great work
