### ISSUE TITLE
Vagrant 1.8.0 w/Fusion: "error code: '7'"

### ISSUE THREAD

**Issue by tehranian** [mitchellh/vagrant#6712]
Hi there,

I'm hitting this consistently w/Vagrant 1.8.0 & VMware Fusion since upgrading. I was using Fusion 7.x. Also tried upgrading to Fusion 8.1 w/o any improvement. Also made sure that all of my Vagrant plugins are up to date.

```
$ v up
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
```

Debug logs: https://gist.github.com/tehranian/ded47b74024a77bc3252

**Comment by sethvargo** [comment]
Hi @tehranian 

This will be fixed in Vagrant 1.8.1: https://github.com/mitchellh/vagrant/issues/6699.

**Comment by yves-vogl** [comment]
The problem also occures with Vagrant 1.8.1 and VMWare Fusion Professional Version 7.1.3 (3204469) on Mac OS X 10.11.1 (15B42)

**Comment by rauhryan** [comment]
> The problem also occures with Vagrant 1.8.1 and VMWare Fusion Professional Version 7.1.3 (3204469) on Mac OS X 10.11.1 (15B42).
> 
> It's fixed by reinstalling the VMware Fusion plugin:
> 
> vagrant plugin install vagrant-vmware-fusion

Confirmed this just fixed my issue as well, thank you!
