### ISSUE TITLE
Shared folder doesn't work

### ISSUE THREAD

**Issue by DanielAdrian** [mitchellh/vagrant#6715]
Shared folder doesn't work on Vagrant 1.8.0, but worked on 1.7.4.

Host:  Windows 7
Guest: Ubuntu 15.04
Vagrant 1.8.0
VirtualBox 5.0

```config.vm.synced_folder ".", "/home/ubuntu"```

In the virtualbox shared folder I can see some strange charters in the path:
![bug_vagrant](https://cloud.githubusercontent.com/assets/379899/11966817/ced47796-a8c3-11e5-8e6c-9feafc9e1dcf.png)

**Comment by mitchellh** [comment]
Are you on the latest version of VirtualBox? This was tested and verified prior to release. There was a bug with VirtualBox 5.0.x where they had a regression, but they fixed it in a newer release.

**Comment by DanielAdrian** [comment]
You are correct, with the latest version 5.0.12 it works. 
Might want to add it to the change log :)
