### ISSUE TITLE
VM instance is re-imported into Hyper-V after running vagrant up when vmms service was down

### ISSUE THREAD

**Issue by dautzenb** [mitchellh/vagrant#6719]
provider:Hyper-V
vagrant version: 1.7.4.
OS: Windows 8.1
Because I needed to attach my external HDD, on which I have some VMs, I stopped the "hyper-v virtual machine management" service. Then I however forgot to start the service again. I executed the command vagrant up, which gave this output:

```
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Configured startup memory is 6144
==> default: Configured cpus number is 4
==> default: Configured vmname is ESWF_SP2013
==> default: Importing a Hyper-V instance
There are no virtual switches created for Hyper-V! Please open
the Hyper-V Manager, go to the "Virtual Switch Manager", and create
at least one virtual switch.

A virtual switch is required for Vagrant to create a Hyper-V
machine that is connected to a network so it can access it.

For more help, please see the documentation on the Vagrant website
for Hyper-V.
```

Then I started the "hyper-v virtual machine management" service again and performed the vagrant up command again. Now I noticed that the VM was re-imported, due to the duration.
These were the messages:

```
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Configured startup memory is 6144
==> default: Configured cpus number is 4
==> default: Configured vmname is myhost
==> default: Importing a Hyper-V instance
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
```

Now my original VM is erased :(

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
