### ISSUE TITLE
Translation missing: en.docker_provider.status.preparing

### ISSUE THREAD

**Issue by josephfrazier** [mitchellh/vagrant#6723]
Vagrant 1.8, on a `vagrant global-status`. I think it belongs [here](https://github.com/mitchellh/vagrant/blob/v1.8.0/templates/locales/providers_docker.yml#L113), but I'm not sure what it should say.

EDIT:

Actually, according to [plugins/providers/docker/provider.rb](https://github.com/mitchellh/vagrant/blob/v1.8.0/plugins/providers/docker/provider.rb#L169-L172), `preparing` is a pseudo-state, so maybe it doesn't have a user-meaningful translation?

**Comment by mitchellh** [comment]
Eh, even if its not useful, I added a translation which is better than seeing the mssage you were seeing. :)
