### ISSUE TITLE
Adding a local box via "box add" fails with v1.8.0, succeeds with v1.7.4

### ISSUE THREAD

**Issue by i-am-david-fernandez** [mitchellh/vagrant#6725]
Attempting to add a local box to vagrant via `box add` (i.e., `vagrant box add --name foobar ./blah.box`) fails using Vagrant 1.8.0 with no specific error message other than the leader: 

```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```

The exact same attempt using Vagrant 1.7.4 succeeds without issue.

A debug trace of the success with 1.7.4 can be found [here](https://gist.github.com/i-am-david-fernandez/db1ff61b36541483e56b), and a similar trace of the failure with 1.8.0 can be found [here](https://gist.github.com/i-am-david-fernandez/0db0c5b54ea7ad2ec7e7).

My environment is Windows 10, primarily via a Cygwin bash shell, but the error also occurs using the native `cmd.exe` shell. Vagrant is installed to the default location (`C:\HashiCorp\Vagrant`). I have tried many uninstall/install cycles switching between 1.7.4 and 1.8.0 (originally using `C:\Program Files (x86)\HashiCorp\Vagrant` as the install path) in an attempt to debug, each time with the same result.

I have tried with two different local box files and both fail in 1.8.0 and succeed in 1.7.4.

While the local box file is located on a different drive/partition to Vagrant (Vagrant on `C:`, boxfile on `D:`), this doesn't appear to be related to #6495 as I don't get the same error message ("Couldn't open file ...").

**Comment by maonx** [comment]
I spent much time to find a solution to fix an error about 
```
vagrant box add name /path/to/box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```
but no ideas.
When I see this issue,I downloads vagrant1.7.4 , and  box add success 
thank you

**Comment by jstortz** [comment]
OSX 10.11.2
Vagrant: 1.8.1
VMWare Fusion 8.0.2

I can add boxes successfully. I downloaded a box from atlas.hashicorp.com and added and removed it several times to make sure. I can't comment on how this works when running on windows. But adding boxes appears to work with Vagrant 1.8.1 on OS X.

**Comment by ofcwork** [comment]
Yes its true, its not possible to add box with vagrant 1.8.0 and 1.8.1 in windows as im getting errors.
 so im using now vagrant 1.7.4. thank you people for posting this issue. i have used VBOX 5.0.12.

**Comment by ecirtap** [comment]
Workaround: as an alternative to "vagrant box add", one can still add a local box using the vm.box_url setting within the box definition in the Vagrantfile AND use another workaround described in https://github.com/mitchellh/vagrant/issues/6754 (missing DLLs).

Eg:

    config.vm.define 'sandbox' do |box|
      box.vm.box = 'ubuntu-14-04-64'
      box.vm.box_url =  "file://c:/boxes/ubuntu-14-04-64.box" 
      ...

**Comment by jamesvl** [comment]
Sorry to just add a "me too", but I'm still hitting the same issue on Win 10 x64, Vagrant 1.8.1.

**Comment by kurron** [comment]
I'm also having this issue on a clean install of Windows 10 x64.

**Comment by jamesvl** [comment]
I did find a solution - it's referenced in #6754 and mentioned above, but I missed it:

Install the [VC++ 2010 redistributable](http://www.microsoft.com/en-us/download/details.aspx?id=8328) _and_ re-install Vagrant. Mine worked (both importing and downloading) after doing that.

**Comment by waqariz** [comment]
Just installing [Visual C++ 2010](https://www.microsoft.com/en-us/download/details.aspx?id=8328) solved my problem with win 8.1

**Comment by Jayflux** [comment]
Going to...
http://landinghub.visualstudio.com/visual-cpp-build-tools

Downloading the Visual C++ build tools and installing (then restarting) fixed it for me.
Click custom installation and select win 10 or win 8.1

**Comment by chrisroberts** [comment]
Confirmed that solution referenced in https://github.com/mitchellh/vagrant/issues/6754#issuecomment-168856576 via https://github.com/mitchellh/vagrant/issues/6725#issuecomment-223733553 (2010 version) correctly fixes embedded rsync startup by installing missing `msvcr100.dll`.

:+1:

**Comment by chrisroberts** [comment]
Fixed in vagrant-installers.

**Comment by jvreeken** [comment]
I just had a simillar error on osx 10.12.1 and vagrant 1.8.7
Error was:
```
default: Downloading: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
```
I installed vagrant 1.8.6 and it worked...

**Comment by belaoulidris** [comment]
I just had a similar error on osx 10.12.1 and vagrant 1.8.7
had to downgrade to 1.8.6

**Comment by wchen9911** [comment]
+1, using 1.8.7, going to downgrade to 1.8.6

**Comment by PierreMage** [comment]
+1, using 1.8.7, max osx 10.11.6
Succeeds with 1.8.6

**Comment by footearth** [comment]
+1, using 1.8.7, max osx 10.12.1

**Comment by jstortz** [comment]
same

+1, using 1.8.7, max osx 10.12.1

**Comment by iBcker** [comment]
same

+1, using 1.8.7, max osx 10.12.2 beta2

**Comment by johnypony3** [comment]
+1, using 1.8.7, osx 10.12.2 Beta 
reverting back to 1.7.4 fixed it.

**Comment by nesheep5** [comment]
same

+1, using 1.8.7, osx 10.11,6

**Comment by DGulshan** [comment]
+1
macOS 10.12.1
1.8.7 didn't work, downgraded to 1.8.6 and it works.

**Comment by breadmj** [comment]
+1

same using vagrant 1.8.7, macOS 10.12.1

**Comment by JohnsonMikeJ** [comment]
+1
mac OS X 10.11.6
1.8.7 didn't work for me either (local or remote box), downgraded to 1.8.6 and it worked just fine.

**Comment by nwqsshi** [comment]
+1
mac OS X 10.12.1 
1.8.7 local or remote box can't work,use 1.8.6 it worked.

**Comment by bionara** [comment]
Same as above - downgrading to 1.8.6 and it works fine. Adding the following [error] for anyone googling this problem:
vagrant box add 
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Comment by dan-nl** [comment]
mac os x 10.11.6
`vagrant box add` 
vagrant 1.8.7 reproduces the error mentioned by the original issue
vagrant 1.8.6 runs without issue

**Comment by johnypony3** [comment]
hi, are there any news regarding this error?

**Comment by pascaloliv** [comment]
Same issue, I've downgraded my vagrant to 1.8.6 and it works !
https://releases.hashicorp.com/vagrant/1.8.6/

**Comment by byends** [comment]
Same issue, I've downgraded my vagrant to 1.8.6 and it works !

1.8.7 has a big bug.....

**Comment by klancaster** [comment]
FWIW, same issue. Downgrading to 1.8.6 fixed the issue. Running OS X 10.12

**Comment by johnypony3** [comment]
This is resolved with the newest version: 1.9.0.
Previous work had 1.8.6 pinned locally.
I updated to 1.8.7 was again able to reproduce.
I updated to 1.9.0 error went away.

**Comment by aclarkd** [comment]
mac 10.11.3 - this worked for me in vagrant 1.8.7

sudo rm -rf /opt/vagrant/embedded/bin/curl

https://github.com/DelightedD0D comment in https://github.com/mitchellh/vagrant/issues/7997

**Comment by voronianski** [comment]
had the same issue on OS X Yosemite and vagrant 1.8.7, then updated to vagrant 1.9.0 - issue is fixed! 🎉

**Comment by johnypony3** [comment]
Petition to close this issue?

**Comment by santoshhkumarr** [comment]
run this command "vagrant box add hashicorp/precise64".
