### ISSUE TITLE
'public_address' capability does not work in VirtualBox

### ISSUE THREAD

**Issue by mkuzmin** [mitchellh/vagrant#6729]
In https://github.com/mitchellh/vagrant/issues/5978 I asked for `:public_address` capability implemented in VirtualBox provider, and @sethvargo did it in https://github.com/mitchellh/vagrant/commit/7b89ecc230942c66e59d740552f6b7cf2f02d2c6.

The change works great, if I start Vagrant by `bundle exec`, but fails in binary release of 1.8: the call returns `nil`.

I suspect, this issue is caused by `vagrant-share` plugin bundled with Vagrant installer: the capability is implemented in both plugins, and share's implementation takes precedence over virtualbox one.

Just in case, here is a [debug log](https://gist.github.com/mkuzmin/79d85a3b66217f97fe82).

**Comment by mitchellh** [comment]
Hm, I'm confused as to why you think the vagrant-share "conflict" may be causing this to return nil? The implementation is identical in both.

**Comment by mkuzmin** [comment]
It's just my guess. As I cannot debug `share` plugin, I don't know reasons for sure.
The only pattern I see: the code starts working correctly right after I delete `vagrant-share` gem.

**Comment by cemo** [comment]
+1

**Comment by cornfeedhobo** [comment]
It would be great if this was solved.
Even better if `:private_address` was added :-)

**Comment by J0WI** [comment]
This is still marked for the already released 1.8.1 milestone, but I think there won't be a release between 1.8.1 and 1.8.2.

I have to use a workaround with ```vagarnt ssh -c``` to simulate the `vagrant-address` functionality, but this performs quite bad and also requires the `vagrant-triggers` extension.

**Comment by mkuzmin** [comment]
>  The only reason someone need's their box's ip is if they are explicitly setting networks, at which point localhost is of little use.
Don't be so strong. This feature is valid for remote providers like `vagrant-aws` or `vagrant-vsphere`.
If you need an additional feature, better create a separate issue.

**Comment by mkuzmin** [comment]
> I have to use a workaround with `vagarnt ssh -c`

Yes, I used this approach before, but it slow, and does not work with Windows guests.

**Comment by cornfeedhobo** [comment]
> Don't be so strong
You are right. I updated my comment for accuracy.

**Comment by sethvargo** [comment]
I don't think you can see it, but:

<img width="513" alt="screen shot 2016-06-01 at 11 52 33 am" src="https://cloud.githubusercontent.com/assets/408570/15718092/57566b2e-27ef-11e6-86fb-1f2bf585d6b8.png">

**Comment by mkuzmin** [comment]
Thank you!
