### ISSUE TITLE
Windows 10, Vagrant 1.8.1, Virtualbox 5.0.12 fails on vagrant up on all boxes

### ISSUE THREAD

**Issue by illepic** [mitchellh/vagrant#6733]
No Vagrant projects I have access to can successfully `vagrant up` on the following setup:

1. Windows 10
2. Vagrant 1.8.1
3. Virtualbox 5.0.12
4. Ruby 2.2.3

I have attempted the default Vagrant box found in the [Drupal VM 2.1.2](https://github.com/geerlingguy/drupal-vm/tree/2.1.2) project as well as various simple boxes built at [PuPHPet](https://puphpet.com).

Attempting to `vagrant up` on a simple PuPHPet box that includes just Ubuntu 14.04 and PHP 7 [results in the following debug output](https://gist.github.com/illepic/62930ae1813558b2c037).

I am running all Windows commands through the [cmder](http://cmder.net/), launched as Administrator. Please let me know if I can provide any other information.

Edit: Noting here that the first ERROR in the debug output is:

```shell
vcpenabled="off"
vcpscreens=0
vcpfile="C:\Users\chris\VirtualBox VMs\local.puphpet\local.puphpet.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "8b96327c-6e95-49f8-9a3e-3d65d40c9951", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
ERROR warden: Error occurred: The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
```

And the final output is:

```shell
INFO interface: Machine: error-exit ["Vagrant::Errors::VMBootBadState", "The guest machine entered an invalid state while waiting for it\nto boot. Valid states are 'starting, running'. The machine is in the\n'poweroff' state. Please verify everything is configured\nproperly and try again.\n\nIf the provider you're using has a GUI that comes with it,\nit is often helpful to open that and watch the machine, since the\nGUI often has more helpful error messages than Vagrant can retrieve.\nFor example, if you're using VirtualBox, run `vagrant up` while the\nVirtualBox GUI is open.\n\nThe primary issue for this error is that the provider you're using\nis not properly configured. This is very rarely a Vagrant issue."]
```

**Comment by illepic** [comment]
Noting here that I'm starting to get successful `vagrant up`s a again via: 

1. Uninstalling both Vagrant 1.8.1 and VirtualBox 5.0.12
2. Then a Windows restart
3. Then reinstalling Vagrant VirtualBox 5.0.12 and Vagrant 1.8.1
3. Then a Windows restart

This was the first time I've uninstalled/reinstalled on a Vagrant update before, so hadn't immediately thought to do that. I'm testing the other boxes on the system to see how they do.

**Comment by qivittoq** [comment]
Have the same problem on Arch Linux.
Virtualbox 10.0.12
Vagrant 1.8.1

It gets the box successfully and starts to set it up. The box shows up in virtualbox, but disappears still going through the setup.

**Comment by blair55** [comment]
Had the same problem on Windows 10, Vagrant 1.8.1, Virtual Box 5.0.12

Rolled back Virtual Box to 5.0.10, restarted, all is well again.

`choco upgrade virtualbox -version 5.0.10.104061 --allow-downgrade`

**Comment by qivittoq** [comment]
@blair55 that fixed it, thanks

**Comment by fratuz610** [comment]
Solution that worked for me

http://superuser.com/questions/1002160/failed-to-start-virtual-device-in-oracle-virtual-box/1002243#1002243

No need to downgrade anything, nor restart but I did have to tick the VirtualBox NDIS checkbox on 2 adapters (ethernet and Host only), not only one

**Comment by chrisroberts** [comment]
This looks like a configuration error fixed as described https://github.com/mitchellh/vagrant/issues/6733#issuecomment-173453961

If you still experience this issue, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new)

Cheers!
