### ISSUE TITLE
Vagrant 1.8.1 throws error "The plugins failed to load properly."

### ISSUE THREAD

**Issue by thasmo** [mitchellh/vagrant#6734]
I'm using the `vagrant-vmware-workstation` plugin, version `3.2.12` on Windows 10 using VMware Workstation `11.1.3 build-3206955`. When running `vagrant` or any other command like `vagrant help` or `vagrant status` I get the following output:

```sh
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
```
[Debug Output](https://gist.github.com/thasmo/7c8c791046862f933bef)

Uninstalling the plugin fixes the problem, but I need it for running my VMware Workstartion boxes.

**Comment by sethvargo** [comment]
Hi @thasmo 

Can you please try upgrading to the latest version of the vmware workstation plugin (4.0.5)? Thanks!

**Comment by thasmo** [comment]
@sethvargo, that means I'd have to upgrade my license, yes? Doesn't the 3.x branch get updates anymore?

**Comment by thasmo** [comment]
Oh, nevermind. Upgrading the license is only needed if I want to use VMware Workstation 12, I guess. Works like a charm! Thanks!

**Comment by johnnyferguson** [comment]
I am getting the same error. I ran the plugin update but it is not 4.0.5 - what s up?

vagrant-share (1.1.5, system)
vagrant-vmware-workstation (3.2.5)
