### ISSUE TITLE
ansible_local: install git/hg as well

### ISSUE THREAD

**Issue by bborysenko** [mitchellh/vagrant#6735]
The `ansible-galaxy` has capabilities for installing roles from private repos. For the moment we have to use shell provisioner to setup git/hg at first, but I suppose it should be installed automatically with ansible.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
