### ISSUE TITLE
Vagrant doesn't use linked clones while using latest Vmware Fusion and Virtualbox

### ISSUE THREAD

**Issue by jgeusebroek** [mitchellh/vagrant#6737]
## Environment

OS: 10.11.2
Provider: Virtualbox 5.0.10/ Vmware fusion 8.10
Vagrant: 1.8.0 / 1.8.1

Vmware has VAGRANT\_VMWARE\_CLONE\_DIRECTORY pointing to a symlinked directory on a different drive as the Vagrantfile.
VirtualBox has it's default VM directory also set to a different drive from the Vagrantfile, but it is NOT a symlink.

### Vagrantfile

	# -*- mode: ruby -*-
	# vi: set ft=ruby :
	
	Vagrant.configure(2) do |config|
	  config.vm.box = "boxcutter/debian82"
	
	  config.vm.define "test1" do |test1|
	  end
	
	  config.vm.define "test2" do |test2|
	  end
	
	end

### Expected result

Vagrant up for the second box should be (much?) faster because it can use a linked clone.
	
### Actual result

Linked clones are not used, the second box it's boottime is the same. 

**Sidenote**: Vmware booting is a bit slower then Virtualbox. Probably because Vmware boxes are inherently bigger. Vmware would therefore benefit the most from linked clones.

	➜  time vagrant up test1
	Bringing machine 'test1' up with 'vmware_fusion' provider...
	==> test1: Cloning VMware VM: 'boxcutter/debian82'. This can take some time...
	==> test1: Checking if box 'boxcutter/debian82' is up to date...
	==> test1: Verifying vmnet devices are healthy...
	==> test1: Preparing network adapters...
	==> test1: Starting the VMware VM...
	==> test1: Waiting for machine to boot. This may take a few minutes...
	    test1: SSH address: 192.168.148.166:22
	    test1: SSH username: vagrant
	    test1: SSH auth method: private key
	    test1:
	    test1: Vagrant insecure key detected. Vagrant will automatically replace
	    test1: this with a newly generated keypair for better security.
	    test1:
	    test1: Inserting generated public key within guest...
	    test1: Removing insecure key from the guest if it's present...
	    test1: Key inserted! Disconnecting and reconnecting using new SSH key...
	==> test1: Machine booted and ready!
	==> test1: Forwarding ports...
	    test1: -- 22 => 2222
	==> test1: Configuring network adapters within the VM...
	==> test1: Waiting for HGFS kernel module to load...
	==> test1: Enabling and configuring shared folders...
	    test1: -- /Volumes/SSD-Storage/Users/jeroeng/test: /vagrant
	vagrant up test1  13.74s user 2.45s system 42% cpu 38.218 total
	
	➜  time vagrant up test2
	Bringing machine 'test2' up with 'vmware_fusion' provider...
	==> test2: Cloning VMware VM: 'boxcutter/debian82'. This can take some time...
	==> test2: Checking if box 'boxcutter/debian82' is up to date...
	==> test2: Verifying vmnet devices are healthy...
	==> test2: Preparing network adapters...
	==> test2: Fixed port collision for 22 => 2222. Now on port 2201.
	==> test2: Starting the VMware VM...
	==> test2: Waiting for machine to boot. This may take a few minutes...
	    test2: SSH address: 192.168.148.167:22
	    test2: SSH username: vagrant
	    test2: SSH auth method: private key
	    test2:
	    test2: Vagrant insecure key detected. Vagrant will automatically replace
	    test2: this with a newly generated keypair for better security.
	    test2:
	    test2: Inserting generated public key within guest...
	    test2: Removing insecure key from the guest if it's present...
	    test2: Key inserted! Disconnecting and reconnecting using new SSH key...
	==> test2: Machine booted and ready!
	==> test2: Forwarding ports...
	    test2: -- 22 => 2201
	==> test2: Configuring network adapters within the VM...
	==> test2: Waiting for HGFS kernel module to load...
	==> test2: Enabling and configuring shared folders...
	    test2: -- /Volumes/SSD-Storage/Users/jeroeng/test: /vagrant
	vagrant up test2  14.60s user 2.40s system 44% cpu 38.371 total
	
	➜  time vagrant up test1 --provider=virtualbox
	Bringing machine 'test1' up with 'virtualbox' provider...
	==> test1: Importing base box 'boxcutter/debian82'...
	==> test1: Matching MAC address for NAT networking...
	==> test1: Checking if box 'boxcutter/debian82' is up to date...
	==> test1: Setting the name of the VM: test_test1_1451127065407_22894
	==> test1: Clearing any previously set network interfaces...
	==> test1: Preparing network interfaces based on configuration...
	    test1: Adapter 1: nat
	==> test1: Forwarding ports...
	    test1: 22 (guest) => 2222 (host) (adapter 1)
	==> test1: Booting VM...
	==> test1: Waiting for machine to boot. This may take a few minutes...
	    test1: SSH address: 127.0.0.1:2222
	    test1: SSH username: vagrant
	    test1: SSH auth method: private key
	    test1: Warning: Remote connection disconnect. Retrying...
	    test1:
	    test1: Vagrant insecure key detected. Vagrant will automatically replace
	    test1: this with a newly generated keypair for better security.
	    test1:
	    test1: Inserting generated public key within guest...
	    test1: Removing insecure key from the guest if it's present...
	    test1: Key inserted! Disconnecting and reconnecting using new SSH key...
	==> test1: Machine booted and ready!
	==> test1: Checking for guest additions in VM...
	==> test1: Mounting shared folders...
	    test1: /vagrant => /Volumes/SSD-Storage/Users/jeroeng/test
	vagrant up test1 --provider=virtualbox  4.63s user 1.98s system 21% cpu 31.293 total
	
	➜  time vagrant up test2 --provider=virtualbox
	Bringing machine 'test2' up with 'virtualbox' provider...
	==> test2: Importing base box 'boxcutter/debian82'...
	==> test2: Matching MAC address for NAT networking...
	==> test2: Checking if box 'boxcutter/debian82' is up to date...
	==> test2: Setting the name of the VM: test_test2_1451127114131_97322
	==> test2: Fixed port collision for 22 => 2222. Now on port 2201.
	==> test2: Clearing any previously set network interfaces...
	==> test2: Preparing network interfaces based on configuration...
	    test2: Adapter 1: nat
	==> test2: Forwarding ports...
	    test2: 22 (guest) => 2201 (host) (adapter 1)
	==> test2: Booting VM...
	==> test2: Waiting for machine to boot. This may take a few minutes...
	    test2: SSH address: 127.0.0.1:2201
	    test2: SSH username: vagrant
	    test2: SSH auth method: private key
	    test2: Warning: Remote connection disconnect. Retrying...
	    test2:
	    test2: Vagrant insecure key detected. Vagrant will automatically replace
	    test2: this with a newly generated keypair for better security.
	    test2:
	    test2: Inserting generated public key within guest...
	    test2: Removing insecure key from the guest if it's present...
	    test2: Key inserted! Disconnecting and reconnecting using new SSH key...
	==> test2: Machine booted and ready!
	==> test2: Checking for guest additions in VM...
	==> test2: Mounting shared folders...
	    test2: /vagrant => /Volumes/SSD-Storage/Users/jeroeng/test
	vagrant up test2 --provider=virtualbox  4.93s user 1.93s system 21% cpu 31.572 total

**Comment by jgeusebroek** [comment]
It works with virtualbox when adding this:

	config.vm.provider "virtualbox" do |v|
	  v.linked_clone = true
	end

Apparently it is necessary  to add this? I am confused because the blog / release notes say:
Linked cloning will happen automatically if your system supports it.

Vmware however is still not working for me.

**Comment by jstortz** [comment]
OS: 10.11.2
Vagrant 1.8.1
Provider: VMWare Fusion 8.0.2

I *think* the linked-clone part would only be happening in this part of your entire timed process:

```
Cloning VMware VM: 'boxcutter/debian82'. This can take some time...
```

Meaning, timing the whole startup process doesn't really tell you too much about the linked-cloning does it? For me, the part I outlined above (Cloning VMware...) happens almost instantly, certainly less than a second. I've not added anything to my Vagrantfile. For example, I did not add v.linked_clone = true. I have not tried or testing anything with Virtualbox, only VMWare and that appears to be working for me.

When I first installed Vagrant 1.8 I had to uninstall the vagrant-vmware-fusion plugin and reinstall it.  Make sure your version of that plugin has been updated.

```
$ vagrant plugin list
vagrant-hostmanager (1.6.1)
vagrant-share (1.1.5, system)
vagrant-vmware-fusion (4.0.5)
```

-Jason

**Comment by jgeusebroek** [comment]
Thanks Jason, 

I tried removing the vagrant.d directory, and then reinstalled the plugin (and license). I had the same result.

	vagrant-share (1.1.5, system)
	vagrant-vmware-fusion (4.0.5)

When using Virtualbox now, the output is a little bit different, and the time it takes to start the box is faster.

	➜  vagrant up test1 --provider virtualbox
	Bringing machine 'test1' up with 'virtualbox' provider...
	==> test1: Box 'boxcutter/debian82' could not be found. Attempting to find and install...
	    test1: Box Provider: virtualbox
	    test1: Box Version: >= 0
	==> test1: Loading metadata for box 'boxcutter/debian82'
	    test1: URL: https://atlas.hashicorp.com/boxcutter/debian82
	==> test1: Adding box 'boxcutter/debian82' (v2.0.4) for provider: virtualbox
	    test1: Downloading: https://atlas.hashicorp.com/boxcutter/boxes/debian82/versions/2.0.4/providers/virtualbox.box
	==> test1: Successfully added box 'boxcutter/debian82' (v2.0.4) for 'virtualbox'!

	==> test1: Preparing master VM for linked clones...
	    test1: This is a one time operation. Once the master VM is prepared,
	    test1: it will be used as a base for linked clones, making the creation
	    test1: of new VMs take milliseconds on a modern system.

	==> test1: Importing base box 'boxcutter/debian82'...
	==> test1: Cloning VM...
	==> test1: Matching MAC address for NAT networking...
	==> test1: Checking if box 'boxcutter/debian82' is up to date...
	==> test1: Setting the name of the VM: test_test1_1451327926777_43485
	==> test1: Clearing any previously set network interfaces...
	==> test1: Preparing network interfaces based on configuration...
	    test1: Adapter 1: nat
	==> test1: Forwarding ports...
	    test1: 22 (guest) => 2222 (host) (adapter 1)
	==> test1: Booting VM...
	<SNIP>

And then starting the second box:

	➜  time vagrant up test2 --provider=virtualbox
	Bringing machine 'test2' up with 'virtualbox' provider...
	==> test2: Cloning VM...
	==> test2: Matching MAC address for NAT networking...
	==> test2: Checking if box 'boxcutter/debian82' is up to date...
	==> test2: Setting the name of the VM: test_test2_1451328064810_56199
	==> test2: Fixed port collision for 22 => 2222. Now on port 2200.
	==> test2: Clearing any previously set network interfaces...
	==> test2: Preparing network interfaces based on configuration...
	    test2: Adapter 1: nat
	==> test2: Forwarding ports...
	    test2: 22 (guest) => 2200 (host) (adapter 1)
	==> test2: Booting VM...
	==> test2: Waiting for machine to boot. This may take a few minutes...
	    test2: SSH address: 127.0.0.1:2200
	    test2: SSH username: vagrant
	    test2: SSH auth method: private key
	    test2: Warning: Remote connection disconnect. Retrying...
	    test2:
	    test2: Vagrant insecure key detected. Vagrant will automatically replace
	    test2: this with a newly generated keypair for better security.
	    test2:
	    test2: Inserting generated public key within guest...
	    test2: Removing insecure key from the guest if it's present...
	    test2: Key inserted! Disconnecting and reconnecting using new SSH key...
	==> test2: Machine booted and ready!
	==> test2: Checking for guest additions in VM...
	==> test2: Mounting shared folders...
	    test2: /vagrant => /Volumes/SSD-Storage/Users/jeroeng/test
	vagrant up test2 --provider=virtualbox  4.82s user 2.00s system 28% cpu 24.036 total

That's +- 7 seconds faster then before (without linked clones). This is where 'time' comes in handy :)
I figure Vmware would benefit even more if I get it to work.

**Comment by sethvargo** [comment]
Hi @jgeusebroek 

We had to revert that behavior because linked clones are only available in VMware Fusion/Workstation Pro, and that was causing breaking changes for some people, so now it's opt-in. A future version of Vagrant will intelligently detect if your provider supports linked clones though.

I'm unable to reproduce your issue on VMware though. Do you have the latest VMware plugin? Can you please run `vagrant plugin update vagrant-vmware-fusion` to be sure? Thanks!

**Comment by jgeusebroek** [comment]
thanks @sethvargo, that explains the change in behavior.

I do have the the latest `vagrant-vmware-fusion` plugin installed, and even tried with a clean slate (completely delete `~/.vagrant.d`).

Also I'm using the latest VMware Fusion Professional. I can use linked clones within the VMware Gui.

I tried the Vagrant debug log, but I can't seem to find a message that says it will or will not use linked clones. Anything in particular I might be able to search for in de debug log?

**Comment by jgeusebroek** [comment]
I'm not sure when in the process it suddenly started working, but all of a sudden it is! I think it might be working since I deleted ~/vagrant.d and reconfigured Vagrant

The console doesn't note that it's using a linked clone, might this be a suggestion?
This can be closed though, thanks for the help!
