### ISSUE TITLE
Windows 8.1. Ansible local provisioner error. `playbook` does not exist on the guest

### ISSUE THREAD

**Issue by char16t** [mitchellh/vagrant#6740]
`vagrant provision` output:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible local provisioner:
* `playbook` does not exist on the guest: C:/vagrant/playbook.yml
```
Working directory: `C:\Users\user\Desktop\RoR`

Environment:
 * Windows 8.1
 * Vagrant 1.8.1
 * Vagrant was installed in `C:\HashiCorp\Vagrant`
 * VirtualBox 5.0.10

Vagrantfile (`C:\Users\user\Desktop\RoR\Vagrantfile`)
```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

playbook.yml (`C:\Users\user\Desktop\RoR\playbook.yml`)
```
---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
```

**Comment by gildegoma** [comment]
@char16t thanks for reporting this bug. See more comments on your PR #6741 ...

**Comment by drozzy** [comment]
When is a release with this coming to windows?

**Comment by dpad** [comment]
For a work-around until the next release, this older plugin (https://github.com/vovimayhem/vagrant-guest_ansible) appears to work on Windows and accomplishes pretty much the same.

**Comment by den-is** [comment]
Same here. Appends "C:"
```
`playbook` does not exist on the guest: C:/vagrant/config/provision.yml
```
windows10x64 Pro
vagrant 1.8.1
Works fine on linux hosts.
if someone wants to test here is project: https://github.com/den-is/devvagrant

**Comment by Nurdok** [comment]
This bug still exists (end of May). Is there an ETA for this?

**Comment by DmitryRomanenko** [comment]
Still exists.
`ubuntu/xenial32`, Windows 10.

Works good with `geerlingguy/ubuntu1604`

**Comment by gildegoma** [comment]
@DmitryRomanenko this is a different issue, I suppose that your `/vagrant` synced directory could not be successfully mounted with your `ubuntu/xenial32` base box (while it worked well with `geerlingguy/ubuntu1604`. Please double check, and eventually create a new issue if you think that the problem is in Vagrant itself.

I'm locking the conversation here (please file new issue, using the provided template). Thanks!
