### ISSUE TITLE
VirtualBox: Vagrant does not recover if master VM for linked clones is deleted

### ISSUE THREAD

**Issue by fabriziopandini** [mitchellh/vagrant#6742]
Step to repeat:

- Create a vagrantfile with 
```ruby
config.vm.provider "virtualbox" do |vb|
  ...  
 vb.linked_clone = true
end
````
- run `vagrant up`: 
  - master VM for linked clones is created
  - new VM linking to master VM is created
- run `vagrant destroy`:
  - only VM linking to master VM is deleted
- manually delete master VM for linked clones in virtual box  
- run again `vagrant up` 

you get an error because vagrant still search for the previously created master VM for linked clone (I suppose the uuid of the VM is stored somewhere...).

How can I recover from this situation?
It is possible to improve Vagrant support to Virtual box linked clone in order to recover automatically from such situation?
It is possible to improve Vagrant support to Virtual box in order to allow giving a human readable name to the master VM for linked clones 

Environment:
Vagrant 1.8.1
VirtualBox  5.0.10 r104061
Osx 10.11.2

**Comment by jwadolowski** [comment]
Just encountered exactly the same issue. ID of your master VM is stored in `~/.vagrant.d/boxes/<box
_name>/<box_version>/virtualbox/master_id`. Once this file is removed `vagrant up` will work as expected again, however this issue should be addressed somehow in Vagrant itself.

`vagrant destroy` doesn't remove the master VM automatically and, as you've pointed out, the only way to get rid of it is a manual action. With this in mind, I think that Vagrant should fallback to regular import if master VM cannot be found.

**Comment by fabriziopandini** [comment]
Thanks. 
The workaround worked just fine and now i'm using linked clones again.

If you agree, I leave this issue open as a reminder for implementing "fallback to regular import if master VM cannot be found."

**Comment by aplc0r** [comment]
This is also a problem if you repackage a box that is attached to a linked clone. The master_id file will be packaged into the new box, which causes it to be initially unusable for other users who add the box.

**Comment by lgeinert** [comment]
Should there a way to force it to pull a new master vm via attribute or something similar to give you control when an update has been made?

**Comment by sethvargo** [comment]
Hi @fabriziopandini 

I think falling back to a regular import if the clone does not exist makes sense (provided we also output this via the UI message). However, please note that the following is really outside of Vagrant's domain:

> manually delete master VM for linked clones in virtual box

Changes that occur to a VM's lifecycle outside of Vagrant are impossible for Vagrant to manage.

**Comment by lgeinert** [comment]
@sethvargo What about a kitchen destroy action or kitchen pre_create_command to remove clone master?

**Comment by sethvargo** [comment]
Hi @lgeinert 

I'm not sure how Test Kitchen is involved in this context.

**Comment by fabriziopandini** [comment]
@sethvargo 
+1 to  falling back to a regular import + UI message if the clone does not exist .

I agree that "manually delete master VM for linked clones in virtual box" is out of vagrant domain, but handling this situation better than with a generic message error will help vagrant users too :-)

**Comment by antweiss** [comment]
Just hit this when playing with otto. Took me about half an hour to analyze where this is coming from.

**Comment by gasparch** [comment]
Why not to add option to vagrant destroy to destroy also link to master? Avoiding job of finding thread with this discussion and manually running shell command :)
