### ISSUE TITLE
VirtualBox: Vagrant does not manage provider settings in multi-machine scenario 

### ISSUE THREAD

**Issue by fabriziopandini** [mitchellh/vagrant#6743]
step to repeat:

- create a vagrant file with:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "fp/centos:7"

  config.vm.define "node1" do |node|
    config.vm.provider "virtualbox" do |vb|
      vb.name = "node1"
    end
  end

  config.vm.define "node2" do |node|
    config.vm.provider "virtualbox" do |vb|
      vb.name = "node2"
    end
  end
end
```
- run `vagrant up`

The first VM is created in virtual box, but named wrongly `node2` (with the name of the last node).
`==> node1: Setting the name of the VM: node2`

Consequently, when the second VM is created, the following error is generated:
`A VirtualBox machine with the name 'node2' already exists.` 

Environment:
Vagrant 1.8.1
VirtualBox 5.0.10 r104061
Osx 10.11.2

**Comment by fabriziopandini** [comment]
Solved by myself:

Vagrant 1.8.1 is more strict about vagrant exact syntax in defining blocks (while in previous versions some "errors" were somehow interpreted as expected).

The working vagrantfile is:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "fp/centos:7"

  config.vm.define "node1" do |node|
    node.vm.provider "virtualbox" do |vb|
      vb.name = "node1"
    end
  end

  config.vm.define "node2" do |node|
    node.vm.provider "virtualbox" do |vb|
      vb.name = "node2"
    end
  end
end
```

:-)

**Comment by jonashaag** [comment]
Thanks! I hit the same issue.
