### ISSUE TITLE
vagrant up entirely failing to connect on windows 8.1, windows 10

### ISSUE THREAD

**Issue by lachy-xe** [mitchellh/vagrant#6744]
Hello!
I have been having trouble with running `vagrant up` on my windows 8.1 x64 box using the following Vagrantfile. I am running vagrant 1.8.1 with ruby 2.2.3, and the version of virtualbox that vagrant installed, which is 5.0.10 r104061. However, this issue persists with both the latest release of vb 5.x and the most recent release of 4.x. Additionally both vagrant and virtualbox have been entirely uninstalled and the system restarted, then vagrant was reinstalled and allowed to install virtualbox itself.
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/vivid64'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
  end
end
```
I have git installed and all its utils on the path, so there is access to ssh. This is the default log level info that gets printed to the console:
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/vivid64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/vivid64' is up to date...
==> default: Setting the name of the VM: vagabond_default_1451132671119_3855
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```
The full debug stacktrace can be found [here](https://gist.github.com/lachy-xe/00786e9c01ccae56d71c). Looking at the virtualbox gui the machine *is* booting correctly, far before `vagrant up` ends, as it gets to a login screen. From this screen I am successfully able to login with user/pass 'vagrant' 'vagrant', and gain access to the system.

I would appreciate any possible assistance with this issue. Thank you!

**Comment by snird** [comment]
+1 on windows 10, with `ubuntu/vivid64` box

**Comment by lachy-xe** [comment]
Good to know it's not just my machine being wonky! Just to clarify, this issue has occurred with every box I've tried (the `hashicorp/precise32` plus a number of various 32 and 64 bit ubuntus), and isn't just an issue with `ubuntu/vivid64`.

**Comment by oakfire** [comment]
When I started the guest(ubuntu/trusty64) on the  VirtualBox GUI, I found the port forwarding and the net bridge both failed. I have no idea why it happened.
With Window 10, Vagrant 1.8.1, VirtualBox 5.0.12 .

**Comment by lachy-xe** [comment]
Okay, I checked the virtualbox logs and the following lines seem to shed some light on this situation, at least in my case:
```
00:00:03.025890 NAT: set redirect TCP host 127.0.0.1:2222 => guest 10.0.2.15:22
00:00:03.040864 supR3HardenedErrorV: supR3HardenedScreenImage/LdrLoadDll: rc=VERR_LDRVI_NOT_SIGNED fImage=1 fProtect=0x0 fAccess=0x0 \Device\HarddiskVolume2\Windows\System32\MSAFDLsp.dll: Not signed.
00:00:03.041028 supR3HardenedErrorV: supR3HardenedMonitor_LdrLoadDll: rejecting 'C:\WINDOWS\system32\MSAFDLsp.dll' (C:\WINDOWS\system32\MSAFDLsp.dll): rcNt=0xc0000190
00:00:03.041060 NAT: failed to redirect TCP 127.0.0.1:2222 => 10.0.2.15:22
```
Not sure what the purpose of this DLL is, or the reason that it's not signed, but I'll do a bit of digging. I found that if I configured bridged networking within virtualbox as the only adapter I could ssh in using the guest's ip given from `ifconfig`, so it seems a little strange that this would work while NAT would not.

My next step is to test the NAT adapter without using vagrant at all, and see if the issue persists.

**Comment by lachy-xe** [comment]
Okay, issue solved! Running the following commands in an elevated command prompt and restarting fixed all of the issues I was having with vagrant et al.

Some commands that will reinitialize various network states:
Reset WINSOCK entries to installation defaults : `netsh winsock reset catalog`
Reset TCP/IP stack to installation defaults : `netsh int ip reset reset.log`
Flush DNS resolver cache : `ipconfig /flushdns`
Renew DNS client registration and refresh DHCP leases : `ipconfig /registerdns`
Flush routing table : `route /f`

courtesy of [this superuser answer](http://superuser.com/questions/495759/why-is-ping-unable-to-resolve-a-name-when-nslookup-works-fine#508057). :smiley:
