### ISSUE TITLE
Incorrect version info

### ISSUE THREAD

**Issue by rbatllet** [mitchellh/vagrant#6750]
I've just installed the last version (1.8.1) but It shows the 1.8.0 as the latest version.

```
$ vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.0
```

**Comment by jstortz** [comment]
I can confirm the same. Installed 1.8.1 early this morning, been using it (fine no issues). Ran vagrant version and got same result as @rbatllet

**Comment by sethvargo** [comment]
Fixed
