### ISSUE TITLE
Can't download boxes on Windows 10

### ISSUE THREAD

**Issue by kacpersaw** [mitchellh/vagrant#6754]
Hello,

I have problem with vagrant on fresh Windows 10.
I create vagrant file with `vagrant init ubuntu/trusty64`
Now when i run vagrant with `vagrant up`
I got this:
```

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
default: Box Provider: virtualbox
default: Box Version: >= 0
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:
URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error:
```
This problem is not only for ubuntu/trusty64 when I init vagrant with `hashicorp/precise32` I get the same error :(
I have virtualbox and cygwin installed.

Thanks for help :)

**Comment by sethvargo** [comment]
Hi @kacpersaw 

Thank you for opening an issue and I am sorry you cannot download boxes. Can you please share your Vagrantfile and the version of Vagrant you are using?

**Comment by megheaiulian** [comment]
@sethvargo 
I have the exact same problem with Vagrant 1.8.1.

**Comment by jeremywhittington** [comment]
For me the problem was I did not have Microsoft Visual C++ Redistributable installed. I figured this out by trying to run curl and got the error “The program can’t start because MSVCR100.dll is missing from your computer.”. After installing the latest version of the c++ redist everything worked.

I was on a fresh install of windows 10, vagrant, virtualbox and the latest version of curl 64bit.

**Comment by megheaiulian** [comment]
curl is embedded by vagrant and is placed at "C:\\HashiCorp\\Vagrant\\embedded\\bin/curl.EXE" but I still get a error.
Here's a screenshot of output after running  VAGRANT_LOG=info vagrant box add ubuntu/trusty64:
https://i.imgur.com/jVZciFA.png

**Comment by kacpersaw** [comment]
@sethvargo I have Vagrant 1.8.1 but I installed Microsoft Visual c++ Redistributable (x86 it's very important because with x64 it's not working but you can have x64 and x86 installed) like @jeremywhittington said and now it's working!

**Comment by ztrange** [comment]
FYI the VC++ needed is the 2010 version. here is the link:

http://www.microsoft.com/en-us/download/details.aspx?id=8328

**Comment by rombanimal** [comment]
@ztrange many thanks, it save a lot of time to me!

**Comment by xinity** [comment]
just having the issue , installed VC++ 2010 (x86 and x86_64) solved the issue.

shoot !!!

**Comment by daniel1943** [comment]
+1 wasted few hours searching for solution before found this :) VC++ 2010 fixed it.

**Comment by bboykov** [comment]
+1 for ztrange and xinity  fixed it for me as well.

**Comment by vbabak** [comment]
Vagrant 1.8.1, windows 10
For me  installing VC++ 2010 (x86 and x86_64) and reinstalling vagrant DID NOT SOLVE the issue with curl.exe
Will try to downgrade vagrant.

**Comment by rad8329** [comment]
@ztrange many thanks, +1

**Comment by amiytg** [comment]
Installing VC++ redist solved my problem as well

**Comment by iboinas** [comment]
Installing VC++ 2010 x86 did the work! (on windows 10 64bit)

Thank you!

**Comment by WebPropelled** [comment]
I'm another that the VC++ install fixed it for. Thanks @jeremywhittington, after hours of banging my head against the wall trying to get things running on this laptop this has brought me a lot of relief!

**Comment by karlbunch** [comment]
Just spent a couple hours banging my head against this myself today.

Another horrible workaround if you're using [git bash](https://git-for-windows.github.io/):

```bash
cp /mingw64/bin/curl.exe /c/HashiCorp/Vagrant/embedded/bin/curl.exe
```

I hope there will be a better solution in the actual installer in a future release.

**Comment by JonidBendo** [comment]
+1 for @ztrange your information was exactly what was missing in my setup.
