### ISSUE TITLE
Segmentation fault On Centos5.6

### ISSUE THREAD

**Issue by lbp0200** [mitchellh/vagrant#6755]
run   /opt/vagrant/bin/vagrant -v
out   Segmentation fault

vagrant version is vagrant_1.8.1_x86_64.rpm.
maybe an older version will be ok ?

**Comment by sethvargo** [comment]
Hi @lbp0200 

Can you please share the trace? Thanks!

**Comment by lbp0200** [comment]
VAGRANT_LOG=debug /opt/vagrant/bin/vagrant -v
Segmentation fault
the same result,or I will try to build install vagrant from source
