### ISSUE TITLE
ansible_local: provide way to only install Ansible

### ISSUE THREAD

**Issue by rndmh3ro** [mitchellh/vagrant#6758]
I'd like to use the ansible_local provisioner to only install ansible on the guest host, not to run playbooks as I do have other means to do this.
This could be done e.g. with a variable (`install_only= true`) or if you omit the `playbook`-variable inside the provisioner option:
`config.vm.provision "ansible"`

What do you think?
As a workaround one could create a dummy-playbook that does nothing.

**Comment by gildegoma** [comment]
To me it sounds quite an "unusual" usage, and I'd recommend to simply use the `shell` provisioner to specify your Ansible installation.

More generally, the purpose of an "x" provisioner (e.g. `ansible_local`) is to mainly execute the provisioning phase with tool "x", and I don't think that such "install_only" behavior can be found in other provisioners.

Being curious (sorry ;-): could you please give more information about your _other means_ to run `ansible-playbook`... maybe it can help to give some improvement ideas :yum: (and pull you to fully adopt it).

**Comment by rndmh3ro** [comment]
Thanks for your answer, @gildegoma! I can understand that this is rather unusual and not wanted in vagrant!

My other means to run ansible-playbook is test-kitchen with the [kitchen-ansible](https://github.com/neillturner/kitchen-ansible) provisioner. This provisioner can install ansible as well but does so with a rather hacky bash-script (https://github.com/neillturner/omnibus-ansible). That's why I'd like to use vagrant's cleaner approach on installing ansible.
Ultimately I'm searching for the fastest and most reliable way to install ansible and run playbooks/roles on multiple different operating systems. ansible_local is a good catch there!

**Comment by gildegoma** [comment]
@rndmh3ro thank you for bringing more details on the table :)

For now, I mark this issue with a "thinking" tag, to first investigate how Test Kitchen, Vagrant and Ansible communities could collaborate at best. Feedbacks and wild ideas are welcome!

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
