### ISSUE TITLE
#6598 hasn't been completely fixed

### ISSUE THREAD

**Issue by hiephm** [mitchellh/vagrant#6761]
The issue https://github.com/mitchellh/vagrant/issues/6598 (which included in 1.8.1 release) hasn't  been completely fixed

Please take a look at the suggestion by @PeterMosmans here https://github.com/mitchellh/vagrant/issues/6598#issuecomment-167481979

Thanks.

**Comment by vilcans** [comment]
This patch fixed Vagrant 1.8.4 for me.

**Comment by chrisroberts** [comment]
Fixed via #6765
