### ISSUE TITLE
Windows installer does not include MSVCP100.dll so curl does not work and so breaks vagrant

### ISSUE THREAD

**Issue by ChristopherHackett** [mitchellh/vagrant#6764]
Hi

vagrant version : 1.8.1
windows version : 10 Home 64 bit

Just done a clean OS install on my Windows laptop. I installed Windows 10 along with a bunch of other stuff including vagrant. When I came to use vagrant If found ``box add`` command failed with this 

```
C:\Users\chris>vagrant box add laravel/homestead
The box 'laravel/homestead' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/laravel/homestead"]
Error:

C:\Users\chris>
```

on investigation I found curl located in ``C:\HashiCorp\Vagrant\embedded\bin`` complained of 

```
The program can't start because MSVCP100.dll is missing from your computer. 
```

The dll is provided by [ MS Visual C++ 2010 x86 Redistributables](https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555) - something I had on my old install for another program. Installing it makes vagrant work.

If I was less knowledgeable on this matter I probably would have given up looking for a fix. 

If you are installing the Redistributable Package then maybe something is going wrong, If you are not including it for any reason then you should or provide some helpful message to the user they need it.

**Comment by tangfastics2014** [comment]
thanks for the fix

**Comment by claymullis** [comment]
Thank you so much it took me forever to find this fix.  Apparently most of the top google results for that error are just people who typed their vagrant commands incorrectly.  This is a pretty annoying bug considering the debugging necessary to solve it.  Hopefully a future version could work with a version of curl that doesn't have that dependency, or at least direct you to a download link.

**Comment by adambadu** [comment]
@ChristopherHackett  Thanks for finding this.

The same happens for me on Windows 7 Pro and Vagrant versions >= 1.8.0.

I have just checked that Vagrant 1.7.4 does not have this issue.

**Comment by alexandrubau** [comment]
Thank you very much @ChristopherHackett for the fix. I had exactly the same problem.

**Comment by brynnb** [comment]
Another thanks here @ChristopherHackett , same problem as others!

**Comment by diegoguemes** [comment]
You saved my day @ChristopherHackett

**Comment by anubhawsharma30** [comment]
Thank you for saving time.

**Comment by vitalnikonov** [comment]
Thank you!!!

**Comment by atay** [comment]
thank you, it works!

**Comment by nhanduong91** [comment]
Thanks so much

**Comment by ZombieBunny** [comment]
This helped me get to the bottom of the problem, everything works now :smile:

**Comment by niktsanov** [comment]
Thank you very much! I've almost given up trying to fix this, as I've tried a lot of things.

**Comment by vincekovacs** [comment]
I found this issue on windows 10.

I found out that the `MSVCP100.dll` exists in `C:\Windows\sytem32` directory, but curl did not find it.

**Comment by jideokus** [comment]
Thanks. Works like a charm. This was driving me a bit crazy.

**Comment by StefanScherer** [comment]
I've sent a PR to include the DLL in the Vagrant installer https://github.com/mitchellh/vagrant-installers/pull/78

**Comment by TuyenGa** [comment]
thanks verymuch

**Comment by jideokus** [comment]
Yeah good call.

On Sat, Apr 9, 2016 at 10:21 PM, Vuong Quang Tuyên <notifications@github.com
> wrote:

> thanks verymuch
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/6764#issuecomment-207921420>
>



-- 
Babajide J. Okusanya

**Comment by alnutile** [comment]
Thank!
https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555

**Comment by arubacao** [comment]
There is a even simpler solution for this problem:

1. Install an working `curl.exe` [Download](https://curl.haxx.se/download.html#Win64)
2. Make `curl` available for the whole system (PATH system-variable) [short tutorial](http://stackoverflow.com/a/20773224)
3. Delete or rename the unfunctional curl.exe in `C:\HashiCorp\Vagrant\embedded\bin`

Therefore you don't have unnecessary stuff installed, but a working `curl` executable with in my opinion is mandatory anyway :)

**Comment by StefanScherer** [comment]
There is a PR https://github.com/mitchellh/vagrant-installers/pull/78 to add the DLL to the Vagrant installer. Seems nobody has noticed that. 
@sethvargo PTAL ?

**Comment by amontalban** [comment]
I can confirm that @StefanScherer PR fixes the issue in 1.8.4 on Windows.

Looking forward to get this pushed to new version, thanks!

**Comment by StefanScherer** [comment]
https://github.com/mitchellh/vagrant-installers/pull/78 got merged. So next version of Vagrant should have a solution out-of-the-box for that.

**Comment by hauthorn** [comment]
In what version is this included? Running Vagrant 1.8.5 on a fresh Windows 10 Pro install, and I had to manually install the redistributable.

**Comment by AzeredoGabriel** [comment]
The solution that our  friend @arubacao said it worked for me :)

**Comment by hauthorn** [comment]
@StefanScherer What version is that?

**Comment by StefanScherer** [comment]
@hauthorn I thought after the PR has been merged the fix would be part of the installer of the next version. I just have checked Vagrant 1.8.5 and the DLL is still missing. So maybe this will be fixed for the next Vagrant installer?

**Comment by HyeKyoZ** [comment]
Thanks!

**Comment by Its-rahulG** [comment]
The most easy and simple ans is, just user ```vagrant 1.7+ and virtual box 5.1+``` .... and run command ```vagrant box add laravel/homestead``` .

**Comment by manuepeva** [comment]
Thank You so much!!! this run perfect for me ! I have been working on this bug for a while and I was just about to lose my mind.

**Comment by wojcikm** [comment]
Unfortunately this solution does not work for me. Error stays where it was. Actually Im runnning out of ideas what do to next. Reinstalled many times everysthing, tried different versions. What is interesting, Curl itself works (when i type in cmd curl "www.google.com" it gives a respond), but still throwing that error of login.

**Comment by huguenin** [comment]
I love you @ChristopherHackett - uninstalling my existing 2010 Redistributable (apparently "a newer version") and installing the one you suggested solved all of my Vagrant problems! Thank you so much :)

**Comment by samdizon** [comment]
Got the same error. still unable to be fixed. Tried all those stuff.

**Comment by lubosdz** [comment]
On windows 10 it might be a permission issue - this helped me:
https://superuser.com/questions/478631/dll-could-not-be-run-for-msi-installers/526480#526480
