### ISSUE TITLE
Chef provisioner should default to install from 'stable' channel

### ISSUE THREAD

**Issue by Chili-Man** [mitchellh/vagrant#6767]
In 1.7.4, when the install option for the chef provisioner was set, it would always install from the stable channel by default because the channel option was not explicitly specified:
https://github.com/mitchellh/vagrant/blob/v1.7.4/plugins/provisioners/chef/omnibus.rb#L8-L27

However, with 1.8.1, the default channel is now set to 'current', which implicitly causes the nightly version  of Chef to be installed. I ran into an issue with this because I specified Chef 12.4.3 to be installed, but it was actually downloading the nightly version of 12.4.3 (it was specifically downloading this one: https://opscode-omnibus-packages-current.s3.amazonaws.com/ubuntu/14.04/x86_64/chef_12.4.3%2B20151006083011-1_amd64.deb)

which after it was installed, the chef-client reported that it was version 12.5.0 which then caused vagrant to error out with: 

```
    default: Installing Chef (12.4.3)...
Vagrant could not detect Chef on the guest! Even after Vagrant
attempted to install Chef, it could still not find Chef on the system.
Please make sure you are connected to the Internet and can access
Chef's package distribution servers. If you already have Chef
installed on this guest, you can disable the automatic Chef detection
by setting the 'install' option in the Chef configuration section of
your Vagrantfile:

    chef.install = false
````
because it couldn't find chef 12.4.3 since 12.5.0 was being installed. 

I propose that the default chef install should come from the 'stable' channel instead of the 'current' channel.

**Comment by sethvargo** [comment]
Hi @Chili-Man 

Thank you for opening an issue. The difference between Vagrant 1.7 and 1.8 is that we use the omnitruck APIs directly instead of the omnibus API. The result is that the user must choose from which channel to download and install Chef. Since Vagrant is primarily a development tool, and many users wanted the ability to use ChefDK (which is only available in `current`), we opted to default to the current channel. You can still specify the `stable` channel by passing in the `channel` option to the chef configuration block in the Vagrantfile.

Does that make sense?

**Comment by Chili-Man** [comment]
hey @sethvargo, thanks for the quick response. It makes sense why it was defaulted to the `current` channel,  however I was a little bit surprised of this behavior because I didn't see a mention of this change in the Changelog for 1.8.

**Comment by sethvargo** [comment]
Hi @Chili-Man 

The PR that added this functionality is https://github.com/mitchellh/vagrant/pull/6557, which was mentioned in the CHANGELOG. Perhaps the verbage could be made better, but the `channel` option is documented along with the new `product` option.

**Comment by Chili-Man** [comment]
Agreed, the wording could have been better. The changelog does mention the feature, but it did not mention that  the default channel was changed from `stable` to `current`. I didn't think to look at the documentation until digging a little deeper into the problem I was having.  I appreciate your help though @sethvargo , thanks.
