### ISSUE TITLE
use_dhcp_assigned_default_route with debian start multiple DHCP clients

### ISSUE THREAD

**Issue by mattiaslundberg** [mitchellh/vagrant#6768]
When creating a vagrant box with debian/ubuntu using `use_dhcp_assigned_default_route` the box starts multiple DHCP clients. This can cause boxes to switch IP address unexpectedly and creates noise on the network.

Example Vagrantfile:

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64" # or "ubuntu/trusty64"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
end
```

This reliably starts at least one extra DHCP client (the last one in the output is a duplicate):

``` sh
vagrant@debian-jessie:~$ ps aux | grep dhclient
root       427  0.0  0.3  25388  7844 ?        Ss   08:56   0:00 dhclient -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
root      8258  0.0  0.3  25388  7708 ?        Ss   08:58   0:00 dhclient -v -pf /run/dhclient.eth1.pid -lf /var/lib/dhcp/dhclient.eth1.leases eth1
root      8276  0.0  0.3  25388  7860 ?        Ss   08:58   0:00 dhclient eth1
```

It seems like the issue arises from the line https://github.com/mitchellh/vagrant/blob/b721eb62cfbfa93895d0d4cf019436ab6b1df05d/templates/guests/debian/network_dhcp.erb#L10 that explicitly starts new dhclient processes.
Using `pre-up` to remove the default route on eth0 and removing the line starting dhclient seems to work in my environment.

Tested with Vagrant 1.8.1 and Virtualbox 5.0.10 on Arch linux. Vagrant 1.7.4 and Virtualbox 4.3.32 on  Debian jessie.

**Comment by sethvargo** [comment]
Hi @mattiaslundberg 

Can you please explain what you mean by:

> Using pre-up to remove the default route on eth0 and removing the line starting dhclient seems to work in my environment.

**Comment by mattiaslundberg** [comment]
**Using `pre-up` to remove the default route on `eth0`**
Would be to add a `pre-up` rule to the network_dhcp.erb template, that removes the default route on interface `eth0`. I think that needs to replace the line https://github.com/mitchellh/vagrant/blob/b721eb62cfbfa93895d0d4cf019436ab6b1df05d/templates/guests/debian/network_dhcp.erb#L9
The updated line would read:
```
pre-up route del default dev eth0 || true
```
And remove the line `post-up dhclient $IFACE` in the same file.

**seems to work in my environment**
It works in one specific case where I tested, not sure about implications for other uses. Can't see any cases where the change would break anything.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
