### ISSUE TITLE
cURL on Windows isn't using the bundled cacert

### ISSUE THREAD

**Issue by joefreeman** [mitchellh/vagrant#6770]
I installed VirtualBox and Vagrant on a fresh Windows machine, and found that `vagrant up` failed with the following output:

```
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error:
```

By adding the `--debug` flag I was able to see the command that `subprocess` was calling:

```
Starting process: ["C:\\Program Files (x86)\\HashiCorp\\Vagrant\\embedded\\bin/curl.EXE", "-I", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.8.1 (+https://www.vagrantup.com; ruby2.2.3)", "--continue-at", "-", "-H", "Accept: application/json", "https://atlas.hashicorp.com/ubuntu/trusty64"]
```

When I try to run this from a command prompt I get this error from cURL:

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

I noticed that there's a `cacert.pem` file in the `embedded` directory, but I think the bundled cURL executable isn't picking this up.

As a workaround I copied this `cacert.pem` file into my working directory (which is [apparently](http://curl.haxx.se/docs/sslcerts.html) one of the places cURL looks), and this seems to allow me download the box. Maybe an alternative would be to set the `CURL_CA_BUNDLE` - it looks like this is being done by `downloader` ([here](https://github.com/mitchellh/vagrant/blob/5fe4b6d877bb046d84ee541ff36e6028d16bb93f/lib/vagrant/util/downloader.rb#L245)), but only when `Vagrant.in_installer?`.

**Comment by RayOei** [comment]
Pem file in working directory didn't work for me.
But this did: 
Add in your Vagrant file:

config.vm.box_download_insecure = true

(Thanks to @klub)

**Comment by drtomiks** [comment]
I had this same problem on Windows 10 Pro and only the @RayOei work around allowed me to proceed.

**Comment by jamieburchell** [comment]
Any updates on this?

According to the manpage:

> curl recognizes the environment variable named 'CURL_CA_BUNDLE' if it is set, and uses the given path as a path to a CA cert bundle. This option overrides that variable.

> The windows version of curl will automatically look for a CA certs file named ´curl-ca-bundle.crt´, either in the same directory as curl.exe, or in the Current Working Directory, or in any folder along your PATH.

> If curl is built against the NSS SSL library, the NSS PEM PKCS#11 module (libnsspem.so) needs to be available for this option to work properly.

I've tried setting the environment variable, putting the cacert.pem bundled with Vagrant in to a directory in the path, and in the bin directory curl is in. Only forcing insecure works, which kinda defeats the point of SSL.

**Comment by Jakauppila** [comment]
+1 to this.

Setting CURL_CA_BUNDLE does not appear to work for curl.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
