### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by mitulispace** [mitchellh/vagrant#6773]
I got  Public Access Key  and Private Access Key  but  not work  SSL error How  to Solve 

![ssl](https://cloud.githubusercontent.com/assets/16436069/12061510/3571e66e-afae-11e5-8e76-297befcb9995.png)

**Comment by sethvargo** [comment]
This is not an issue with Vagrant. Please open an issue on the magento project.

**Comment by Cruiser13** [comment]
I guess that it could be a similar problem like the one described here: http://suchmaschinenplatzierer.de/blog/piwik-problem-curl-exec-ssl-certificate
Maybe the shipped SSL certificates do not contain the ones needed for Magento.
