### ISSUE TITLE
Rsync Synced Folder does not work when `requiretty' is enabled

### ISSUE THREAD

**Issue by kissge** [mitchellh/vagrant#6780]
Even if I set `config.ssh.pty = true` (#1482), the rsync function does not properly work.

```
==> default: Rsyncing folder: /home/****/****/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/****/****/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/home/****/****/****.pem' --exclude .vagrant/ /home/****/****/ ec2-user@**.**.**.**:/vagrant
Error: Warning: Permanently added '**.**.**.**' (ECDSA) to the list of known hosts.

sudo: sorry, you must have a tty to run sudo
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]


Command "vagrant up --provider=aws" exited with 1
```

The reason is `--rync-path sudo rsync`.
In the guest environment `sudo` cannot be invoked without tty.
If the options for opening shell session (`rsync -e ...`) can be configured properly (e.g., `ssh -tt`) the problem is supposed to be resolved, but those options are fixed and cannot be modified.
(cf. https://github.com/mitchellh/vagrant/blob/master/plugins/synced_folders/rsync/helper.rb#L74)

Does anyone know workaround for this problem?

**Comment by sethvargo** [comment]
Hi @kissge 

I am sorry you are having issues with Vagrant. Can you please share your Vagrantfile, host OS, guest OS, and the output of the command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html) as as github gist? Thanks! :smile:

**Comment by apancutt** [comment]
I'm having the same issue, specifically with the **Amazon Linux AMI 2015.09.1** image.

Host: OS X 10.11.2
Vagrant: 1.8.1

    Vagrant.configure("2") do |config|

        config.vm.box = "dummy"

        config.vm.provider :aws do |aws, override|

            aws.access_key_id = "***"
            aws.secret_access_key = "***"
            aws.keypair_name = "foo"
            aws.ami = "ami-60b6c60a" # Amazon Linux AMI 2015.09.1

            override.ssh.pty = true
            override.ssh.username = "ec2-user"
            override.ssh.private_key_path = "~/.ssh/foo.pem"

        end

    end

Output:

    ==> default: Rsyncing folder: /Users/apancutt/workspace/vagrant/ => /vagrant
    There was an error when attempting to rsync a synced folder.
    Please inspect the error message below for more info.

    Host path: /Users/apancutt/workspace/vagrant/
    Guest path: /vagrant
    Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22 -o ControlMaster=auto -o ControlPath=/var/folders/f6/63j1_6111vv6cfnvd5gxbhww0000gn/T/ssh.331 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/Users/apancutt/.ssh/foo.pem' --exclude .vagrant/ /Users/apancutt/workspace/vagrant/ ec2-user@***:/vagrant
    Error: Warning: Permanently added '***' (ECDSA) to the list of known hosts.
    sudo: sorry, you must have a tty to run sudo
    rsync: connection unexpectedly closed (0 bytes received so far) [sender]
    rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]

**Comment by mandeepbal** [comment]
:+1: I'm getting this same issue

```
==> default: Rsyncing folder: /Users/Documents/CodeRepos/chef-configure/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/Documents/CodeRepos/chef-configure/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i '/keys/dev.pem' --exclude .vagrant/ /Users/Documents/CodeRepos/chef-configure/ ubuntu@10.206.144.69:/vagrant
Error: Warning: Permanently added '10.206.144.69' (ECDSA) to the list of known hosts.
packet_write_wait: Connection to 10.206.144.69: Broken pipe
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/io.c(453) [sender=2.6.9]

```

**Comment by bryanwb** [comment]
hey folks, this might help you. You need to disable the requirement for tty in your sudoers configuration

You need something like the following in your instance userdata
```
#!/bin/bash                                                        
echo 'Defaults:root !requiretty' > /etc/sudoers.d/aws
echo 'Defaults:vagrant !requiretty' >> /etc/sudoers.d/aws
```

**Comment by kissge** [comment]
Yes, it is an option.
But as far as I tested it does _not always_ work well.
It seemed that it is unpredictable whether the script runs before or after vagrant tries to connect the server via ssh. If it runs before vagrant, then it works; otherwise it fails.

And besides, that solution only works with Amazon EC2 instances.
After all improving vagrant seems a better solution to me.

**Comment by OptiverTimAll** [comment]
I'm not familiar with Ruby, but it seems like if [the code that built the rsync rsh command](https://github.com/mitchellh/vagrant/blob/2ffcadc7b89cc079e547243941766244955913d0/plugins/synced_folders/rsync/helper.rb#L74) were updated to respect `config.ssh.pty`, that should fix things nicely.

**Comment by sethvargo** [comment]
We did some refactors. Can anyone confirm if this is still an issue with Vagrant 1.8.4?

**Comment by aseering** [comment]
I am hitting this issue with Vagrant 1.8.4.

**Comment by ayen-tibco** [comment]
+1 same issue here with Vagrant 1.8.5 and vagrant-aws (0.7.2).

**Comment by gianarb** [comment]
I have the same problem with vagrant 1.8.5 and vagrant-aws (0.7.2) like @ayen-tibco

**Comment by kenorb** [comment]
Same here when using custom AMI.

However it works with:

    config.ssh.pty = true

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Comment by vhosakot** [comment]
When I did `vagrant up` with the box `centos/7 (virtualbox, 1703.01)`, `==> default: Rsyncing folder: /root/ => /vagrant` was stuck for me too, and adding
`config.vm.synced_folder '.', '/vagrant', disabled: true`
in Vagrantfile resolved the issue for me and rsync did not happen.
