### ISSUE TITLE
Vagrant box add fails with local file

### ISSUE THREAD

**Issue by GinoPane** [mitchellh/vagrant#6783]
I just followed this tutorial: https://blog.engineyard.com/2014/building-a-vagrant-box and finally faced this issue:

"h:\VagrantBoxes>vagrant box add test-server32 file:///H:/VagrantBoxes/package.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'test-server32' (v0) for provider:
    box: Unpacking necessary files from: file:///H:/VagrantBoxes/package.box
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again."

I use Windows 10 x64, Vagrant 1.8.1, VirtualBox 5.0.12.

Similar problem was listed here: http://stackoverflow.com/questions/34556929/vagrant-box-add-fail, but the solution does not work for me.

**Comment by GinoPane** [comment]
Ok, can be closed, problem fixed. I checked the problem with curl which needed Visual C++ Redistributable for Visual Studio 2015 installed. Now it works.

**Comment by X0o0Z** [comment]
Hey, man, I have the same question to you. However I use vagrant on Mac. Your os is windows, So how can I do to fix this problem?
