### ISSUE TITLE
Why does the vagrantup.com site require www?

### ISSUE THREAD

**Issue by dragon788** [mitchellh/vagrant#6785]
I can hit most of the other Hashicorp product sites without www in the URL, not sure why if I'm typing https://vagrantup.com it doesn't resolve properly, but hitting the www site without http redirects to the https with www.

**Comment by sethvargo** [comment]
Hi @dragon788 

For various reasons, we are unable to serve the apex domain over SSL. You can browse to https://www.vagrantup.com and other domains. We will fix this when we migrate to our new static site deployments.
