### ISSUE TITLE
vagrant 1.8.1 error

### ISSUE THREAD

**Issue by Oscarteg** [mitchellh/vagrant#6786]
I keep getting an error with vagrant 1.8.1 on my Mac OSX 10.11.2. I don't get this error if I use vagrant 1.7.4. I'm not sure if this is a vagrant issue. 

This is the error i get with every vagrant command.
```
/Users/Oscar/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:13:in `require': incompatible library version - /Users/Oscar/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext/parser.bundle (fatal)
	from /Users/Oscar/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:13:in `<module:Ext>'
	from /Users/Oscar/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:12:in `<module:JSON>'
	from /Users/Oscar/.vagrant.d/gems/gems/json-1.8.3/lib/json/ext.rb:9:in `<top (required)>'
	from /Users/Oscar/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:58:in `require'
	from /Users/Oscar/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:58:in `<module:JSON>'
	from /Users/Oscar/.vagrant.d/gems/gems/json-1.8.3/lib/json.rb:54:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:55:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:55:in `<top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `require'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `<main>'
```

**Comment by jeffhertzler** [comment]
Same issue on OSX 10.10.5. Downgrade back to Vagrant 1.7.4 fixed for me as well.

**Comment by unitsche** [comment]
Removing my ```.vagrand.de``` directory solved this issue in my case

**Comment by deancsmith** [comment]
I had the same error going from 1.7.4 to 1.8.0 and did the following to make 1.8.0 work on El Capitan. Note: you will have to reinstall your plugins.

> rm -Rf ~/.vagrant.d/gems/ && rm ~/.vagrant.d/plugins.json

**Comment by Oscarteg** [comment]
That fixed it for me as well!

Issues closed.

**Comment by will666** [comment]
Same here, that worked, thanks unitsche

**Comment by toby-griffiths** [comment]
@deancsmith thanks for the tip.  Worked for me too.

**Comment by bighappyface** [comment]
+1 for `rm -Rf ~/.vagrant.d/gems/ && rm ~/.vagrant.d/plugins.json`

**Comment by metaarts** [comment]
thanks a lot
