### ISSUE TITLE
Unable to start a machine on El Capitan copied from Yosemite

### ISSUE THREAD

**Issue by codecowboy** [mitchellh/vagrant#6789]
I have tried copying over a vagrant box from a Yosemite install to a clean El Capitan install.

The procedure I used was this:

Copied vagrant.d to the new user folder
Added machine to virtualbox manually
Changed Virtualbox VM's directory in preferences (to a path which exists and contains all my old VMs, incuding the vagrant ones)

If I issue ```vagrant up```, vagrant imports the original base box (Centos in my case) and then creates a new box which I can see in Virtualbox. What I want is for vagrant to use the exact box I had before so that all my customisations are there.

In any case, the vagrant up command fails with the following error:

```
A customization command failed:

["modifyvm", :id, "--name", "local.puphpet"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "86fbe0b0-c119-4553-84b3-4596a7934e62", "--name", "local.puphpet"]

Stderr: VBoxManage: error: Could not rename the directory '/Volumes/Data/Users/myuser/VirtualBox VMs/kickasscentos_default_1451911861767_76796' to '/Volumes/Data/Users/myuser/VirtualBox VMs/local.puphpet' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "SaveSettings()" at line 3016 of file VBoxManageModifyVM.cpp
>

Please fix this customization and try again.
```

The suggestions here - https://github.com/mitchellh/vagrant/issues/6092 - have not worked for me.

**Comment by sethvargo** [comment]
Hi @codecowboy 

Thank you for opening an issue. There are a number of reasons why this may not work:

1. The user who originally owned the `.vagrant.d` directory may not have the same UID/GID as the new user (note that having the same username is not the same as having the same uid).
2. I don't know what you mean by "added the machine to virtualbox manually"

The error you are seeing is coming from Virtualbox, not Vagrant. It looks like you have a permissions issue (which leads me to believe me assumption above is correct). I'll try to help as much as possible, but this is outside the scope of what Vagrant can manage :smile:

**Comment by codecowboy** [comment]
Thanks Seth!. Do you know of any way to work around the uid issue?  I'm not sure I understand what implication this problem has in the virtualbox / vagrant context. When is this checked by virtualbox?

By adding manually I mean launching Virtualbox and using the gui to add the machine from the files in the virtualbox vms folder - that is on a disk which was previously mounted on the old osx install so what you are saying about UIDs makes sense. A number of 'guides' online suggest doing this.

**Comment by sethvargo** [comment]
@codecowboy it's not "checked" by virtualbox - it's just basic file permissions :frowning:. If the old box was owned by UID 6034 but the new box is owned by UID 6033, then vbox won't have permissions to manage the file. You might want to `chown -R $(whoami) $HOME/.vagrant.d` and the same for the path to your virtualbox images too.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
