### ISSUE TITLE
Import box even when provider doesn't match

### ISSUE THREAD

**Issue by ankon** [mitchellh/vagrant#6791]
I was trying to build travis-ci/travis-build on Fedora 23, with both libvirt & virtualbox installed. The instructions where:
~~~~
vagrant up
vagrant ssh
...
~~~~

On the first command I got this:
~~~~
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'ubuntu/precise64' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'ubuntu/precise64' (v0) for provider: libvirt
    default: Downloading: http://files.vagrantup.com/precise64.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: libvirt
Provider of box: virtualbox
~~~~
Now, that error sounds reasonable, and there's two ways forward: figure out why it used the specific box, or try to modify the provider for the run. 

I changed the first command to `vagrant up --provider=virtualbox`, and now expected that the command would just work, and *would not download the box again* (which does take quite some time). Unfortunately that seems not to be the case, and vagrant started the download again. 

It would be really nice if the download could be avoided here, for example by trying to register the box for all available providers.

**Comment by sethvargo** [comment]
Hi @ankon 

The first `vagrant up` did not download the box at all. It attempted to search the metadata, but did not find a matching box. The result is that nothing but some json data was downloaded. Are you experiencing different behavior?

**Comment by ankon** [comment]
My first `vagrant up` did download the box - at least it told me things about how long it takes, how much kb/s it is currently loading, etc. I have no idea where it would keep that data though, so I cannot tell you what exactly it downloaded there. As the second command took as long, and printed the exact same progress information, I have to assume that it did indeed download the box file.

FWIW: Vagrant 1.7.4, installed from Fedora repositories:
~~~~
$ rpm -qa|grep vagrant
vagrant-registration-1.1.0-2.fc23.noarch
vagrant-libvirt-0.0.30-5.fc23.noarch
vagrant-libvirt-doc-0.0.30-5.fc23.noarch
vagrant-lxc-1.1.0-8.fc23.noarch
vagrant-1.7.4-2.fc23.noarch
~~~~

**Comment by sethvargo** [comment]
Hi @ankon 

Ahh, you are correct. There is no way for Vagrant to know what kind of box before it downloads it. Just like you can't know the contents of a zip file until you download the entire blob, Vagrant boxes are the same way unfortunately :frowning:.
