### ISSUE TITLE
Vagrant 1.8.1 / Fusion: problem spinning up an OSX VM: missing nic_mac_addresses provider capability

### ISSUE THREAD

**Issue by StefanScherer** [mitchellh/vagrant#6792]
I'm running Vagrant 1.8.1 with VMware Fusion 7.1.3 (non-pro) and vagrant-vmware-fusion 4.0.5 plugin on OSX 10.11.2 and have a problem spinning up an OSX Vagrant box that worked fine with Vagrant 1.7.4.

Vagrant 1.8.1 aborts with the following error:

```
ERROR vagrant: #<Vagrant::Errors::CantReadMACAddresses: The provider you are using  ('vmware_fusion') doesn't support the
"nic_mac_addresses" provider capability which is required
for advanced networking to work with this guest OS. Please inform
the author of the provider to add this feature.

Until then, you must remove any networking configurations other
than forwarded ports from your Vagrantfile for Vagrant to continue.>
ERROR vagrant: The provider you are using  ('vmware_fusion') doesn't support the
"nic_mac_addresses" provider capability which is required
for advanced networking to work with this guest OS. Please inform
the author of the provider to add this feature.

Until then, you must remove any networking configurations other
than forwarded ports from your Vagrantfile for Vagrant to continue.
```

Here is the debug output of the `vagrant up` with Vagrant 1.8.1: https://gist.github.com/StefanScherer/b1851fbbfaf8f8f678f9#file-vagrant-1-8-1-up

The `vmware.log` of this command: https://gist.github.com/StefanScherer/b1851fbbfaf8f8f678f9#file-vmware-log

My Vagrantfile does not contain network configurations:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "osx1011-desktop"
  config.ssh.forward_agent = true
  config.ssh.insert_key = false

  config.vm.provision "shell", path: "scripts/enable-hidpi.sh", privileged: false
  config.vm.provision "shell", path: "scripts/set-german.sh", privileged: false
  config.vm.provision "shell", path: "scripts/disable-sleep.sh", privileged: false
  config.vm.provision "shell", path: "scripts/install-brew-cask.sh", privileged: false

  config.vm.provision "shell", path: "scripts/install-resources.sh", privileged: false
  config.vm.provision "shell", path: "scripts/install-chrome.sh", privileged: false
  config.vm.provision "shell", path: "scripts/install-node.sh", privileged: false
  config.vm.provision "shell", path: "scripts/install-atom.sh", privileged: false
  config.vm.provision "shell", path: "scripts/install-cucumber.sh", privileged: false

  config.vm.provision "shell", path: "scripts/install-virtualbox.sh", privileged: false
  config.vm.provision "shell", path: "scripts/install-docker.sh", privileged: false

  # config.vm.provision "shell", path: "scripts/install-packer.sh", privileged: false
  # config.vm.provision "shell", path: "scripts/install-vagrant.sh", privileged: false

  config.vm.hostname = "mac-dev-box"

  config.vm.provider "vmware_fusion" do |v|
    v.gui = true
    v.vmx["memsize"] = "6196"
    v.vmx["numvcpus"] = "2"
    # enable nested hypervisor
    v.vmx["vhv.enable"] = "TRUE"
    # enable HiDPI / Retina
    v.vmx["gui.fitguestusingnativedisplayresolution"] = "TRUE"
    # enable sound
    # v.vmx["sound.startconnected"] = "TRUE"
    # v.vmx["sound.present"] = "TRUE"
    # v.vmx["sound.autodetect"] = "TRUE"
    v.enable_vmrun_ip_lookup = false
  end
end
```

I have downgraded to Vagrant 1.7.4 and tested again also with the `vagrant-vmware-fusion` 4.0.5 plugin and it worked fine.

The debug output of the working `vagrant up` with Vagrant 1.7.4 is here: https://gist.github.com/StefanScherer/b1851fbbfaf8f8f678f9#file-vagrant-1-7-4-up

**Comment by luciusbono** [comment]
I am also having this issue. Got reaaaallly excited about the linked clone functionality that 1.8.1 added, but I'm not able to use my OSX VMs.

**Comment by bdwyertech** [comment]
:+1:

**Comment by bdwyertech** [comment]
Might have something to do with this commit https://github.com/mitchellh/vagrant/pull/6386

**Comment by escobarj** [comment]
I'm also getting this error. 

- Mac OS X 10.11 host
- Mac OS X (10.9/10.10/10.11) guests 
- vagrant 1.8.1
- vagrant-vmware-fusion 4.0.3
- VMware Fusion 8.1.0

The box does come up for me and I can `vagrant ssh` just fine, but I don't get the `/vagrant` share.

```
The provider you are using  ('vmware_fusion') doesn't support the
"nic_mac_addresses" provider capability which is required
for advanced networking to work with this guest OS. Please inform
the author of the provider to add this feature.

Until then, you must remove any networking configurations other
than forwarded ports from your Vagrantfile for Vagrant to continue.
```

**Comment by iamdefn** [comment]
Three guest operating systems depend on the "nic_mac_addresses" provider capability, which the VMware Fusion provider does not support.

The reason why VMware Fusion fails for OS X is because the Darwin guest plugin's network configure fails early when detecting the lack of "nic_mac_addresses" capability.  This occurs before any checks for advanced networking, so removing advance networking won't allow your guest to proceed.

So are the other two guest operating systems impacted (windows and nixos)?  I don't think so; the windows guest plugin will warn and skip advanced networking; the nixos guest plugin degrades gracefully, too.

The fix here is probably have the darwin guest plugin warn and skip any advanced networking configuration.

See the windows warning here https://github.com/mitchellh/vagrant/blob/master/plugins/guests/windows/cap/configure_networks.rb#L19

Need to add something like that to the darwin guest plugin to replace this https://github.com/mitchellh/vagrant/blob/master/plugins/guests/darwin/cap/configure_networks.rb#L14

**Comment by StefanScherer** [comment]
@iamdefn Thanks for the pointer. Especially the windows guest warning. I did not know that is part of vagrant and not of the vagrant-vmware-workstation plugin. So it seems there is a way to add something for #5000 there? But that's another story ;-)

**Comment by iamdefn** [comment]
I hope the VMware workstation plugin goes get the nic_mac_addresses capability, though being a closed source product, not sure where I'd file an issue for that.  At least we can fix the guest OS plugins.

**Comment by bdwyertech** [comment]
Removing #6386, all works well again with OS X and Windows again under VMware.  It seems only the Virtualbox provider has the `nic_mac_addresses` capability  Maybe #6386 needs to be reverted?  Seems like a regression @sethvargo

**Comment by iroller** [comment]
Same issue here after upgrading.
@legal90 ^^

**Comment by legal90** [comment]
In #6386 I've mentioned that `nic_mac_addresses` provider capability should be implemented in all providers which are going to run Darwin guests, so the error message tells about that in explicit.

I'm sorry, I didn't know that `vmware_*` providers don't support it because they are not open-sourced. :cry: 
So, I hope that it's possible to implement `nic_mac_addresses` cap for `vmware_*` providers in order to fix that issue.

**Comment by phinze** [comment]
Hey folks,

Sorry about the trouble on this. I just checked and it looks like the VMware configuration files contain enough information for us to be able to implement `nic_mac_addresses`. Just need to work on an implementation. I'll keep this thread posted!

**Comment by wegotoeleven** [comment]
Hey all,

Any news on this? 

Thanks!

**Comment by phinze** [comment]
Hello again!

I've just cut v4.0.8 of the `vagrant-vmware` plugins which should address this issue. Please take it for a spin and let me know if you still have any trouble!

To upgrade, just re-issue the install command, for example:

```
vagrant plugin install vagrant-vmware-fusion
```

**Comment by casibbald** [comment]
Phew! Twitchy bottom for me over the last week over this!

**Comment by StefanScherer** [comment]
@phinze Thanks!!! I'll try that tomorrow as I have to update Vagrant as well for that. (Or can I run Vagrant in Docker on my Mac - oh, weird world)

**Comment by wegotoeleven** [comment]
I can confirm this has fixed the issue when spinning up a Mac OS X El Capitan box with Vagrant. 

Thanks!

**Comment by rmanly** [comment]
re-updated to 1.8.1 and new plugin.

all good here now.

thanks!

**Comment by escobarj** [comment]
4.0.8 fixed the issue for me. Thanks.

**Comment by casibbald** [comment]
This fixes the issue for me as well.

Thanks!

**Comment by StefanScherer** [comment]
Back to Mac in Mac with Vagrant 1.8.1 + Fusion plugin 4.0.8. Thanks!
