### ISSUE TITLE
Add to doc trick how to define locale for SSH session in Vagrant file

### ISSUE THREAD

**Issue by michaldo** [mitchellh/vagrant#6794]
I had problem that my host locale was propagated to guest on SSH session. Some commands (f.e.  **locale**) failed when called though `vagrant ssh` but was working when called within Virtualbox

I finally invented a solution and I would like to share it with others.

**Comment by mbrodala** [comment]
Unfortunately this doesn't work to fix the notorious `Could not evaluate: invalid byte sequence in US-ASCII` bug in Puppet with files containing non-ASCII characters. See #2270
