### ISSUE TITLE
(contributing to vagrant) bundler 1.11.2 not supported on master

### ISSUE THREAD

**Issue by kylegibson** [mitchellh/vagrant#6798]
Following the instructions here: https://github.com/mitchellh/vagrant#contributing-to-vagrant

Checked out master (d1d493c3230822db658fdfd6fdf05edf81b40dee). 

```
$ git describe --tags
v1.8.1-12-gd1d493c
```

`vagrant up` followed by `gem install bundler` results in incompatible bundler being installed:

```
vagrant@vagrant:/vagrant$ gem install bundler
Fetching: bundler-1.11.2.gem (100%)
Successfully installed bundler-1.11.2
Parsing documentation for bundler-1.11.2
Installing ri documentation for bundler-1.11.2
Done installing documentation for bundler after 3 seconds
1 gem installed
vagrant@vagrant:/vagrant$ bundle install
Fetching https://github.com/mitchellh/vagrant-spec.git
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant was resolved to 1.8.2.dev, which depends on
      bundler (<= 1.10.6, >= 1.5.2)

  Current Bundler version:
    bundler (1.11.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (<= 1.10.6, >= 1.5.2)', which is required by gem 'vagrant', in any of the sources.
```

This issue can be worked around by doing `gem install bundler -v 1.10.6` instead.

**Comment by gMagicScott** [comment]
The bundler version constraints are noted in the gemspec and on the wiki https://github.com/mitchellh/vagrant/wiki/Installing-Vagrant-from-Source

**Comment by kylegibson** [comment]
Thank you for the reply. I wasn't building or installing vagrant from source. I was following the instructions as documented here: https://github.com/mitchellh/vagrant#contributing-to-vagrant. Those instruction say: 

> To hack on Vagrant, you'll need bundler which can be installed with a simple `gem install bundler`.

Unfortunately, that does not work.
