### ISSUE TITLE
Vagrant 1.8.1 ssh error in windows 10

### ISSUE THREAD

**Issue by akaSStalkALEX** [mitchellh/vagrant#6799]
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'centos/7' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 5432 (guest) => 54320 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating

**Comment by gocanto** [comment]
same error here... any solution?

**Comment by akaSStalkALEX** [comment]
I just recreated box and this error has gone, but there is still present problem of long time execution of vagrants commands. I think problem was inside my centos box. Something got broken during yum updating.

**Comment by gocanto** [comment]
I am running Vagrant in Yosemite OS along with homestead but for some reason after I updated the vagrant and my homestead, The error started appearing.. any clue?
