### ISSUE TITLE
Vagrant chef auto install no proxy

### ISSUE THREAD

**Issue by gimler** [mitchellh/vagrant#6804]
I find out that the chef installation via vagrant see https://docs.vagrantup.com/v2/provisioning/chef_common.html doesn't use the proxy configuration.

vagrant 1.8.1
vagrant-proxyconf (1.5.2)

im not shure how to access the proxy configuration and pass it to `machine.communicate.sudo` in `plugins/provisioners/chef/cap/redhat/chef_install.rb:16`

can anybody help me then i would open a PR ;)

**Comment by sethvargo** [comment]
Hi @gimler 

The `_proxy` variables on that page are the configuration options for the Chef Client itself, not the installer. 

The vagrant-proxyconf plugin should automatically setup the VM to use the specified proxy. Specifically, it sets `http_proxy`, which curl should be using. If you're not experiencing that behavior, please open an issue on that project. Thanks! :smile:
