### ISSUE TITLE
Profile Name change causes download failure

### ISSUE THREAD

**Issue by cappetta** [mitchellh/vagrant#6807]
I updated my user name / profile from enemy-of-the-state to cappetta and vagrant is trying to download the cappetta box yet pointing to the old enemy-of-the-state in the URL.  

>vagrant box add https://atlas.hashicorp.com/cappetta/boxes/centos-7.1_kernel-devel-fixed
>==> box: Loading metadata for box 'https://atlas.hashicorp.com/cappetta/boxes/centos-7.1_kernel-devel-fixed'
==> box: Adding box 'cappetta/centos-7.1_kernel-devel-fixed' (v1.0.0) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/enemy-of-the-state/boxes/centos-7.1_kernel-devel-fixed/versions/1.0.0/providers/virtualbox.box
==> box: Box download is resuming from prior download progress
    box: Progress: 0% (Rate: 0curl:/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Comment by sethvargo** [comment]
Hi @cappetta 

Thank you for opening an issue. I am sorry, but I am having trouble understanding what your issue is. Did you change your local username on the host machine or your username in HashiCorp's Atlas?

Can you please share the complete output of the command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html) as a github gist?

**Comment by cappetta** [comment]
Hey it was my username in Atlas.  I've got a few things going on but will get you some debug out as soon as I can.  Appreciate the inquiry for information. 

~Cappetta

**Comment by sethvargo** [comment]
Hi @cappetta 

If you change your username in Atlas, you will also need to update the box name in the Vagrantfile.

```diff
- config.vm.box = "enemy-of-the-state/mybox"
+ config.vm.box = "cappetta/mybox"
```

Does that makes senes?

**Comment by cappetta** [comment]
Correct & that was done.  The previously pasted output shows the attempt to download the new box yet it compiles a url with the old acct (enemy-of-the-state) name.  

I'm not sure if there was a caching issue but when I changed my user name back to enemy-of-the-state (from Cappetta) the box downloaded as expected (because URL is valid again)

**Comment by cappetta** [comment]
Not sure how to update the waiting-reply label but let me know if you need any more info...

**Comment by sethvargo** [comment]
Hi @cappetta 

Sorry for the delayed reply. I think I know what is going on here... 

When you download a box from Atlas, it's "identifier" is the slug. This identifier is actually how the box gets stored locally (if you look in `~/.vagrant.d/boxes`, you'll see what I mean), and I think that's the "caching" you're talking about.

Could you try renaming the box in that folder? You may also need to delete the `.vagrant` directory at the root of your project.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to inactivity. If this is still occurring, please open a new issue and follow the associated issue template. Thanks! 😄

**Comment by cappetta** [comment]
Thanks for closing.  I no longer have access to the machine that experienced that issue but appreciate the research and feedback.
