### ISSUE TITLE
Vagrant up fail on synced_folder (samba)

### ISSUE THREAD

**Issue by julestruong** [mitchellh/vagrant#6808]
Hello, 

Here is my config :
Vagrant 1.8.1
VirtualBox 5.0.10
Windows 10
VM is ubuntu trusty

here is my log when i run `vagrant up` :

```
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o uid=`id -u PASSWORDHIDDEN`,gid=`getent group PASSWORDHIDDEN | cut -d: -f3`,sec=ntlm,credentials=/etc/smb_creds_f1095df519d0667424505ecb4339f787 //10.10.10.1/f1095df519d0667424505ecb4339f787 /var/www/julio
mount -t cifs -o uid=`id -u PASSWORDHIDDEN`,gid=`id -g PASSWORDHIDDEN`,sec=ntlm,credentials=/etc/smb_creds_f1095df519d0667424505ecb4339f787 //10.10.10.1/f1095df519d0667424505ecb4339f787 /var/www/julio

The error output from the last command was:

stdin: is not a tty
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

I don't understand what is happening there, when i use basic synced_folder its working, it only fails when i use samba mode.

Here is a part of my Vagrantfile :

`config.vm.synced_folder "templates", "/tmp/vagrant-puppet/templates"
  config.vm.synced_folder "../", "/var/www/julio", type: "smb"``

Also if you could explain how to use mount_options on smb and other options like smb_password  smb_username, the documentation gives no example and i have no clue for the syntax

**Comment by Perni1984** [comment]
For smb to work you have to run Vagrant in a console with Administrator rights. Hold down `ctrl-shift` when clicking on your console, so you run it in Administrator mode. After that run `vagrant up` and make sure you provide username and password of your local administrator account (typically your local login user).

**Comment by sethvargo** [comment]
Hi @julestruong 

Could you please try @Perni1984's suggestion and see if that fixes your issue?

**Comment by amirkoklan** [comment]
I have exactly the same problem and I did try to run command line as Administrator, but no success.

Windows 8.1 Pro
Vagrant 1.8.1
vmware Workstation 12

**Comment by julestruong** [comment]
@sethvargo 
No it didn't work.

**Comment by joth** [comment]
Windows 7 Enterprise
Vagrant 1.8.1
Virtualbox 5.0.12

**Comment by ghola** [comment]
The problem exists because Vagrant mounts using the credentials param `credentials=/etc/smb_creds_f1095df519d0667424505ecb4339f787` instead of the username, password and domain. Not sure why they decided to change it like this.

To fix it you must install cifs-utils in your VM as per [this question](http://askubuntu.com/questions/1836/problems-mounting-an-smb-share-in-my-fstab).

**Comment by chrisroberts** [comment]
This looks to be like a guest setup issue missing the cifs-utils (or related) package. If that is not the problem, please feel free to reopen this issue. Thanks!

**Comment by erichmusick** [comment]
The issue is reproing for me as well. In the credentials file, Vagrant seems to split my username (user@domain.com) into separate `username` and `domain` properties -- `user` and `domain.com`, respectively. If I ssh to the box, modify the smb_creds file to switch `username` back to user@domain.com, remove `domain`, and run the command manually, the share mounts.

Windows 10.0.14393 Build 14393
Vagrant 1.9.1
Hyper-V
Running from Administrator PowerShell window.

VM is running Ubuntu  14.04. I've installed cifs-utils on my VM:

```
erichmusick@app1-musickbox2:/etc$ sudo apt-get install cifs-utils
Reading package lists... Done
Building dependency tree
Reading state information... Done
cifs-utils is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
```

**Comment by chaospixel** [comment]
I get the same issue with the hashicorp/precise64 box too...
Vagrant 2.0.4 (downgraded from 2.1.1 to see if it might resolve the issue)

**Comment by fernandogmo** [comment]
To anybody else facing this exact `mount error(13): Permission denied` error, this is what helped me:

1. The username being asked for is the one you get when you run `$Env:USERNAME` in PowerShell.
2. The password being asked for is the one you would use for login into the **current Windows user account** on that host machine. This _may_ differ from your Microsoft account password if you have recently changed that one (this is the case for me).

A fairly simple fix (in my case) so I hope this helps!
