### ISSUE TITLE
Could not find gem 'vagrant-triggers;vagrant error! How to fix ??

### ISSUE THREAD

**Issue by mountin** [mitchellh/vagrant#6810]
Hello! Vagrant tells me:

Could not find gem 'vagrant-triggers;vagrant (>= 0) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine

I dont know how to fix it?
I've tried different version of installer, i deleted all information from registry file, i restarted my PC several times.
Nothing helps !! this is terrible!!
![vaggrr](https://cloud.githubusercontent.com/assets/8074477/12130875/ccea96aa-b416-11e5-986a-2698bf6ed179.png)

Screenshot is attached!

Help me please!!
I use Win7 and Oracle Virtual Box!

**Comment by sethvargo** [comment]
Hi @mountin 

Thank you for opening an issue, and I am sorry you are having issues installing the vagrant-triggers plugin. Could you please share the output of the plugin install command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html) in a github gist/

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
