### ISSUE TITLE
.vagrant folder files are getting deleted

### ISSUE THREAD

**Issue by pradeeptesco** [mitchellh/vagrant#6813]
sometimes when the VM is shut down manually or aborted, files from ".vagrant\machines\default\virtualbox" location are getting deleted. due to which next vagrant up is creating new VM from scratch. Vagrant version is 1.7.2. Kindly suggest the solution. Thanks in advance.

**Comment by sethvargo** [comment]
Hi @pradeeptesco 

Thank you for opening an issue. Unfortunately there is not enough information here to reproduce the issue. The latest version of Vagrant is 1.8.1, which may resolve this issue for you.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
