### ISSUE TITLE
All vagrant commands are slow (taking at least 2s to run)

### ISSUE THREAD

**Issue by carlosefr** [mitchellh/vagrant#6814]
On my laptop running Mac OS X Mavericks, almost all vagrant commands take at least **2 seconds** to run, from `vagrant help` to `vagrant box list` and others. The only exception to this is `vagrant --version`, taking about 500ms on average.

For example, `vagrant help` takes almost exactly 2 seconds to run, every time, with a variation of just a few milliseconds, which seems very fishy to me (stuff like these usually smell of some sort of timeout, but I'm unsure on how to help debug this).

By prefixing commands with `VAGRANT_LOG=debug`, I see that the bulk of the wait seems to happen before any output starts being produced.

The laptop has an SSD and I can reproduce this on clean installs of both vagrant 1.7.4 and 1.8.1. Running the bundled ruby interpreter by itself is almost instantaneous.

**Comment by carlosefr** [comment]
I looked briefly into this today: it takes about 0.5 seconds until `/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant` is executed and then inside it most time seems to be spent here (about 1 second):
{{{
require "bundler"
begin
  $vagrant_bundler_runtime = Bundler.setup(:default, :plugins)
}}}
Other `require` statements seem to take about another 0.25 seconds or so.

**Comment by sethvargo** [comment]
Hi @carlosefr 

What is the output of `vagrant plugin list`?

**Comment by carlosefr** [comment]
Hi,

Just whatever's installed by default:
```
$ time vagrant plugin list
vagrant-share (1.1.5, system)

real    0m1.914s
user    0m1.768s
sys     0m0.132s
```

**Comment by chrisroberts** [comment]
Related: #7793

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
