### ISSUE TITLE
Environment support for Chef Solo

### ISSUE THREAD

**Issue by yairfr** [mitchellh/vagrant#6817]
hi ,
i am trying to test my chef cookbook with the environment setting in the environment json file .
i am working with chef-12.6.0
                            vagrant 1.7.2
my vagrant file looks like that - 

    ....

    config.vm.provider "virtualbox" do |vb|

       vb.customize ["modifyvm", :id, "--memory", "1024"]

    end

    config.omnibus.chef_version = :latest

    config.vm.provision :chef_solo do |chef|

     chef.log_level = :debug

     chef.nodes_path = "../test-config/chef-repo/nodes/cx"

     chef.cookbooks_path = [
          '../cookbooks/testing/shared',
          '../cookbooks/common/shared',
      ]

     chef.environments_path = "../test-config/chef-repo/environments"

     chef.environment = "my-staging"

    chef.add_recipe 'kibana4'
      ....
     ....

i get the error -
 "Environment cookbook version constraints not allowed in chef-solo"
i tried to use chef-zero instead but with no success too .
from what i read there should be support to the environment in the chef-solo ,
why it doesn't work ?

**Comment by sethvargo** [comment]
Hi @yairfr 

Thank you for opening an issue. The error you are getting is coming from Chef, not Vagrant. Vagrant is just executing Chef under the hood. The error you are getting seems to indicate that, while environments are supported in Chef Solo, some features of environments (like cookbook version constraints) are not supported. This makes sense given that the Chef Solo just receives a tarball of cookbooks and does not download from some external server where versioning exists.

I would recommend posting on the Chef mailing list. Unfortunately this is not an issue with Vagrant. Thanks! :smile:
