### ISSUE TITLE
rsync-auto is very slow on big projects

### ISSUE THREAD

**Issue by nuncanada** [mitchellh/vagrant#6821]
We are trying to use the rsync-auto feature with a project we have, but it takes 82 seconds for rsync to run without any changes, just for it to figure out that both file trees are equal.

rsync is able to work only over a list of files/directories thru the --files-from option, all that is needed is to capture the list of changed files/directories and feed to rsync with this option.

**Comment by nuncanada** [comment]
@dkarlovi opened another issue that better represents the problem we are having trying to use rsync folders with big trees.

**Comment by nuncanada** [comment]
@dkarlovi For now, I have created the vagrant-rsync-only-changed plugin to test the solution where only the changed files are sent for rsync to synchronize. If you could help test it, I am willing to make a PR with the changes needed.

**Comment by dkarlovi** [comment]
@nuncanada sure I'll test it, just point me to the right repo. :+1:

**Comment by nuncanada** [comment]
Just vagrant plugin install vagrant-rsync-only-changed should install it
and make it used if there is any synced folder of the "rsync" type.

Seems to be working for me, with a Windows host. I need to go home to test
it with a Linux host.

**Comment by nuncanada** [comment]
Repository: https://github.com/nuncanada/vagrant-rsync-only-changed

**Comment by dkarlovi** [comment]
@nuncanada great, I'll test it tommorow and let you know. Thanks!

**Comment by dkarlovi** [comment]
Tested it quite a bit, it works great, you should create a PR for this.

**Comment by chrisroberts** [comment]
Closing this as covered by other open issues
