### ISSUE TITLE
Adding `.gui = true` causes `vagrant up` to fail

### ISSUE THREAD

**Issue by cpitclaudel** [mitchellh/vagrant#6823]
The following Vagrantfile works fine on my machine (Linux Mint 17.2):

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/vivid64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
```

But this one fails:

```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/vivid64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
end
```

The error is:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "b2b28f24-331a-41ad-a951-2af0cabbf2fc", "--type", "gui"]

Stderr: VBoxManage: error: Could not launch a process for the machine 'vagrantfile_default_1452204402102_33423' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component Machine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 592 of file VBoxManageMisc.cpp
```

```
$ VBoxManage -v
4.3.34_Ubuntur104062
$ vagrant -v
Vagrant 1.7.2
```

Please let me know if I can provide more info!

**Comment by cpitclaudel** [comment]
Installing `virtualbox-qt` solved the problem. Should this be in the docs?

**Comment by sethvargo** [comment]
Hi @cpitclaudel 

Thank you for opening an issue. May I ask how you installed Virtualbox? The latest version of VirtualBox for linux is 5.0.12 at this time. Usually we see this kind of behavior when you install VirtualBox via a package manager instead of via the official installers on virtualbox.org.

**Comment by cpitclaudel** [comment]
Indeed, I installed it via the Ubuntu package manager.

**Comment by sethvargo** [comment]
Hi @cpitclaudel 

Would you mind uninstalling virtualbox and virtualbox-qt and try installing via the official package installer to see if that solves the issue? Then I can add that to the docs.

**Comment by cpitclaudel** [comment]
Sorry, but I'm not a big fan of installing stuff from elsewhere than my package manager; it makes it much harder to keep things up to date. Feel free to close this use though; its existence will point people to the solution :)

**Comment by sethvargo** [comment]
Hi @cpitclaudel 

:smile: Well I would like to confirm that installing via the official installer truly mitigates the issue, and unfortunately I do not have access to Linux Mint on a desktop.

**Comment by cpitclaudel** [comment]
Seems to work :)

**Comment by sethvargo** [comment]
Great, thanks!
