### ISSUE TITLE
--module_path support in Ansible provisioner

### ISSUE THREAD

**Issue by akshaymankar** [mitchellh/vagrant#6824]
It'd be great if we could have something like:

`ansible.module_path = "ansible/modules"`

If one has to achieve this now, they'll have to use raw_arguments.

**Comment by gildegoma** [comment]
See also #1674 for the records about module_path support requests so far.

I think for now that raw_arguments is enough for this kind of "advanced usage" (or even better an ansible.cfg file if you have to deal with other environments than the vagrant development context).

Keeping it open though, for community feedbacks gathering 😃.

**Comment by gildegoma** [comment]
Closing as "won't fix". I think there is already enough easy ways to set the Ansible module_path. See also upcoming #7918 for better flexibility regarding `ansible.cfg` file location.
