### ISSUE TITLE
1.8.1 : cannot create a shared folder with root disk on Windows

### ISSUE THREAD

**Issue by magnetik** [mitchellh/vagrant#6826]
Hi,

Using Vagrant 1.8.1 on Windows 7 x64 Pro, when trying to configure a shared folder like this:

    config.vm.synced_folder "W:\\", "/home/vagrant/myShare", type: "", mount_options: [ "dmode=0700,fmode=0600 " ], create: true

Gives error:

```
C:\Users\User\Documents\myBox>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Preparing SMB shared folders...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["sharedfolder", "add", "51629afd-8b31-4e76-8319-d5ce89b54d02", "--name", "home_vagrant_myShare", "--hostpath", "W:\\"]

Stderr: VBoxManage.exe: error: Shared folder path 'W:"' is not absolute
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component SharedFolderWrap, interface ISharedFolder, callee IUnknown
VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostpath).raw(), fWritable, fAutoMount)" at line 1020 of file VBoxManageMisc.cpp
```

It was working with vagrant 1.7.4. 

On Windows, W:\\ is a TrueCrypt disk. I've tried `W:\\` and `W:`.

**Comment by marekmueller** [comment]
Hello,
I have identical problem with Vagrant 1.8.1 on Windows 7 Home Premium x64.

**Comment by sethvargo** [comment]
Hi everyone,

I did some research, and this is a bug in VirtualBox, not Vagrant. Here is the upstream ticket: https://www.virtualbox.org/ticket/7941. Unfortunately there is very little Vagrant can do to work around core hypervisor bugs like this :frowning:

**Comment by magnetik** [comment]
Hi,

I've found this ticket, but I'm not quite sure that this is the problem : it was working with the same version of Virtualbox (5.0.12) with Vagrant 1.7.4. 

But indeed it looks similar.
