### ISSUE TITLE
Vagrant attempted to execute the capability 'chef_install' on the detect guest OS 'linux', but the guest doesn't support that capability.

### ISSUE THREAD

**Issue by wilddog64** [mitchellh/vagrant#6829]
Hi, after upgrade to vagrant 1.8.1, for some reason I ran into this problem.  Here's a portion of debug output,

```
RROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::GuestCapabilityNotFound: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.>
ERROR vagrant: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/guest.rb:45:in `rescue in capability'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/guest.rb:43:in `capability'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/chef/installer.rb:32:in `ensure_installed'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/chef/provisioner/base.rb:54:in `install_chef'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/chef/provisioner/chef_solo.rb:48:in `provision'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:473:in `hook'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:121:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:121:in `block in call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:103:in `each'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:103:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/chengkai.liang/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/upload.rb:23:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/chengkai.liang/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/install.rb:19:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/chengkai.liang/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/save.rb:21:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/chengkai.liang/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/chengkai.liang/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/share.rb:28:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/chengkai.liang/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/load.rb:30:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/env_set.rb:19:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/Users/chengkai.liang/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/check.rb:18:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
/opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
 INFO interface: error: Vagrant attempted to execute the capability 'chef_install'
```

It seems this problem happened before, I wonder if this is a regression bug?

**Comment by sethvargo** [comment]
Hi @wilddog64 

Thank you for opening an issue. Can you please share your Vagrantfile?

**Comment by wilddog64** [comment]
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

$LOAD_PATH.unshift( File.expand_path( File.dirname( __FILE__ ) ) )
require 'local-machines'
require 'aws'

include LocalMachines

aws_config = Aws.new( '~/.aws', 'mgmt' )

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.hostname = 'dbl-java-berkshelf'

  # Set the version of chef to install using the vagrant-omnibus plugin
  # NOTE: You will need to install the vagrant-omnibus plugin:
  #
  #   $ vagrant plugin install vagrant-omnibus
  #
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = '12.5.1'
  end

  # Every Vagrant virtual environment requires a box to build off of.
  # If this value is a shorthand to a box in Vagrant Cloud then
  # config.vm.box_url doesn't need to be specified.
  config.vm.box = 'chef/centos-7.0'


  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  if Vagrant.has_plugin?( 'vagrant-auto_network' )
    config.vm.network :private_network, :auto_network => true
  else
    config.vm.network :private_network, type: 'dhcp'
  end

  config.ssh.pty = true
  if Vagrant.has_plugin?( 'vagrant-aws' )
    config.vm.box     = 'dummy'
    config.vm.provider :aws do | aws, override |
      aws.access_key_id             = aws_config.aws_access_key_id
      aws.secret_access_key         = aws_config.aws_secret_access_key
      aws.region                    = aws_config.region
      aws.keypair_name              = 'dblOps'
      aws.instance_type             = 'm3.large'
      aws.iam_instance_profile_name = 'mgmt'
      aws.ami                       = 'ami-a2a12eca'    # amzn
      aws.tags                      = { 'Name' => 'test-dbl_java', }
      aws.security_groups           = [ 'production_management' ]
      user_data = File.read( 'combined.txt' )
      aws.user_data = user_data
      override.ssh.pty              = true
      override.ssh.private_key_path = File.expand_path( '~/.ssh/dblOps.pem' )
      override.ssh.username         = 'ec2-user'
    end
  end

  # if vagrant-berkshelf plugin is installed, then provide some configuration values here
  if Vagrant.has_plugin?( 'vagrant-berkshelf' )
    config.berkshelf.berksfile_path = './Berksfile'
    config.berkshelf.enabled        = true
  end


  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # The path to the Berksfile to use with Vagrant Berkshelf
  # config.berkshelf.berksfile_path = "./Berksfile"

  # Enabling the Berkshelf plugin. To enable this globally, add this configuration
  # option to your ~/.vagrant.d/Vagrantfile file
  config.berkshelf.enabled = true

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to exclusively install and copy to Vagrant's shelf.
  # config.berkshelf.only = []

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to skip installing and copying to Vagrant's shelf.
  # config.berkshelf.except = []

  config.vm.provision :chef_zero do |chef|
    chef.json = {
    }
    chef.environments_path = './environments'
    chef.environment = 'stage2'

    chef.run_list = [
      'recipe[dbl_java::default]'
    ]
  end
end

**Comment by sethvargo** [comment]
Hi @wilddog64 

Are you able to reproduce this issue with no plugins? I just tried a simple Vagrantfile with the chef_zero provisioner and I'm not seeing this error. Can you please try removing the vagrant-omnibus and vagrant-berkshelf plugins?

**Comment by wilddog64** [comment]
I will try minimal vagrant config to see if I can repo this

**Comment by wilddog64** [comment]
If I strip out all the plugins that I used, and use chef/centos-7.0, it works smoothly.  I suspect it could related to test-kitchen that I setup.  I have .kitchen.yml in my repo as,

---
driver:
  name: ec2
  aws_ssh_key_id: dblOps
  user_data: ./combined.txt 
  tags:
    Name: 'kitchen-test-instance'
  iam_profile_name: mgmt
  instance_type: m3.large
  region: us-east-1
  availability_zone: us-east-1e
  security_group_ids:
    - sg-9748f9ff  # security group name: production_management

transport:
  ssh_key: <%= File.expand_path( '~/.ssh/dblOps.pem' ) %>
  username: ec2-user
  connection_timeout: 10
  retries: 15

provisioner:
  name: chef_zero

platforms:
  - name: amazon-linux
    driver:
      image_id: ami-a2a12eca


suites:
  - name: default
    run_list:
      - recipe[dbl_java::default]
      - recipe[chef::dump_attributes]
    attributes:
      chef:
        dump:
          file: /tmp/chef/node.json

I can successfully execute this with kitchen test for the first time.  But after that, when I execute vagrant up it will first complain I need to have nodes_path setup.  This also afect other cookbook that don't have .kitchen.yml setup.  Can this be related?  How does kitchen configuration affect vagrant?

**Comment by sethvargo** [comment]
Hi @wilddog64 

Unfortunately that seems like a problem with Test Kitchen then. If you open an issue on that repo, that TK team should be able to help though! :smile:

**Comment by petems** [comment]
@sethvargo This is actually a live issue with Vagrant itself, not a plugin, reproducible with this Vagrant file:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provision :chef_solo do |chef|
    #
  end

  config.vm.provider :aws do |aws, override|
    aws.region = "eu-west-1"
    aws.ami = "ami-31328842"

    override.ssh.username = "ec2-user"
  end
end
```

No plugins installed except the `vagrant-aws` to show the problem exists with Amazon Linux. 

### Problem

The problem is that Amazon Linux doesn't get detected by the Vagrant code, so when it tries to run the `install_chef` provisioner, it's guest detection just says 'Linux', so it errors out because there is no default installer for Linux. 

### Workaround 

In the mean time, use a basic one liner provisioner:

```ruby
config.vm.provision :shell, :inline => "curl -L 'https://omnitruck.chef.io/install.sh' | sudo bash"
```

Or use the https://github.com/chef/vagrant-omnibus

### Proper Fix
Add Guest detection for Amazon Linux, requiring most of the RedHat specific gues actions, as most of it still applies (eg. yum install, network script location)

**Comment by petems** [comment]
Amazon Linux PR: https://github.com/mitchellh/vagrant/pull/7254
