### ISSUE TITLE
Allow file provisioner to process file through templating engine

### ISSUE THREAD

**Issue by dusek** [mitchellh/vagrant#6840]
Hello,

I am dealing with a situation where I need to provision 2 nearly identical files to the VM, differing only in one line. Best would be for this if vagrant allowed using e.g. ERB or similar templating engine to upload a file not literally, but after processing it through a templating engine.

E.g., I need to upload `config-cs.ini`:
```
language=cs
[20 lines]
```
to path "AppData\...\config-cs.ini"

and `config-en.ini`:

```
language=en
[20 same lines]
```

to path "AppData\...\config-en.ini".

Right now, I have to have both files separately on disk in git.

If I could just create `config.ini.erb`:

```
language=<%= @language %>
[20 lines]
```

and then use:

```
    win.vm.provision "file", source: "config.ini.erb", template: "erb", destination: "AppData/.../config-cs.ini", vars: { :language => "cs" }
    win.vm.provision "file", source: "config.ini.erb", template: "erb", destination: "AppData/.../config-en.ini", vars: { :language => "en" }
```

I would be saved :-)

Obviously the `template` argument would default to something like `nil` if not specified, i.e. no templating engine.

This would also provide a nice way and and enhance the ability to customize the behavior through environment variables: now that they can be passed also to the "shell" provisioner in vagrant 1.8 and customize executing of shell scripts, they could easily be used in the `vars` hash of a templated "file" provisioner to customize the files uploaded.

**Comment by sethvargo** [comment]
Hi @dusek 

Thank you for opening an issue. This is a really interesting idea, but it's not currently on the roadmap for the core team. If someone from the community implemented this functionality, I think we would gladly accept it, but there are easy workarounds for now, for example:

```ruby
require "erb"
b = binding
File.open("/tmp/config.es.ini", "wb") do |f|
  @language = "es"
  f.write(ERB.new(File.read("config.ini.erb")).result(b))
end

File.open("/tmp/config.es.ini", "wb") do |f|
  @language = "en"
  f.write(ERB.new(File.read("config.ini.erb")).result(b))
end

# ...
config.vm.provision "file", source: "/tmp/config.es.ini", destination: "..."
config.vm.provision "file", source: "/tmp/config.en.ini", destination: "..."
```
