### ISSUE TITLE
Trisquel guest plugin not available

### ISSUE THREAD

**Issue by velocity303** [mitchellh/vagrant#6842]
There currently is not a Trisquel guest plugin available. Since this is derived as just a fully free version of Ubuntu, the code is entirely the same just with a slight modification needed for detection of the Trisquel distribution from the lsb_release file. For this reason inheritance seems to work fully. I am happy to submit a pull request with a new plug-in. I am currently using version 1.8.1.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/pull/6843
