### ISSUE TITLE
VBoxManage.exe: error: Code E_NOINTERFACE (0x80004002) - No such interface supported (extended info not available)

### ISSUE THREAD

**Issue by mlgiter** [mitchellh/vagrant#6849]
I am trying to start VirtualBox (versions 5.1, 4.3.4, 4.16) in Windows 7 SP1 x64 Ultimate via Vagrant 1.7.4 command

    'vagrant up'

and i am getting error

    Bringing machine 'default' up with 'virtualbox' provider... There was an error while executing VBoxManage, a CLI used by Vagrant for controlling VirtualBox. The command and stderr is shown below. Command: ["list", "hostonlyifs"] Stderr: VBoxManage.exe: error: Failed to create the VirtualBox object! VBoxManage.exe: error: Code E_NOINTERFACE (0x80004002) - No such interface supported (extended info not available) VBoxManage.exe: error: Most likely, the VirtualBox COM server is not running or failed to start.

It looks like vagrant handles DCOM in a bad way. I've added Group "Distributed COM Users" to VBoxSVC.exe, but no luck. The group has both Local Access and Remote Access Permissions.

How could i fix it?

I do enabled access to VirtualBox to everyone as well as for Distributed COM users, but nothing works - i am still have

    Watcher ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={c28be65f-1a8f-43b4-81f1-eb60cb516e66} aComponent={VirtualBox} aText={The object is not ready}, preserve=false

in VirtualBox log when i try to

    vagrant up

But VirtualBox GUI just runs different VMs at the same time.

**Comment by sethvargo** [comment]
Hi @mlgiter 

Thank you for opening an issue, and I am sorry you are having problems with Vagrant. Are you running Vagrant as an administrator? Usually when we see these errors it is because Vagrant is unable to properly drive the VirtualBox drivers.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
