### ISSUE TITLE
Vagrant Up fails with VMware Workstation 12 on Win 7

### ISSUE THREAD

**Issue by twehptg** [mitchellh/vagrant#6851]
Windows 7 64bit
VMWare Workstation 12
vagrant 1.8.1

```
C:\...>vagrant up
c:/users/twe/.vagrant.d/gems/gems/virtualbox-0.8.6/lib/virtualbox/com/ffi/util.r
b:93: warning: duplicated key at line 107 ignored: "io"
Bringing machine 'default' up with 'vmware_workstation' provider...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Skipping vmnet device verification, verify_vmnet is set to false.
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "C:/Users/twe/vagrantTest/.vagrant/machines/default/vmware_wo
rkstation/f561daef-edbe-4d84-b4a2-87f9a86bba6a/precise64.vmx", "nogui", {:notify
=>[:stdout, :stderr], :timeout=>45}]

Stdout: Error: The operation was canceled

Stderr:
```

**Comment by sethvargo** [comment]
Hi @twehptg 

Thank you for opening an issue. Unfortunately that error is coming from the VMware software, not Vagrant. As you can see, it ran the following command:

```
vmrun start C:/Users/twe/vagrantTest/.vagrant/machines/default/vmware_wo
rkstation/f561daef-edbe-4d84-b4a2-87f9a86bba6a/precise64.vmx nogui
```

and for some reason VMware Workstation reported that operation as canceled. Are you able to launch VMs via VMware Workstation manually?

**Comment by cobracmder** [comment]
I'm seeing the same thing (bento/centos-6.7):

Windows 10 Pro 64 bit (OS 10586.63)
VMWare Workstation 12 Pro
Vagrant 1.8.1

I'm able to create VMs manually via the Workstation GUI.

**Comment by ottboy4** [comment]
I am seeing this same issue.

Ubuntu 14.04 LTS (host)
VMWare Workstation 12.1.0 Pro
Vagrant 1.8.1

Vagrant 1.7.x works for me with Workstation 12, 1.8.1 does not (even with the same vmware version).

Is there a vmware forum link that discusses the issue that we can put into this github issue as well?

**Comment by sethvargo** [comment]
Hi all,

I'm going to close this due to lack of response from the original author. @ottboy4 since you're experiencing this recently, could you please open a _new_ issue and complete the issue template that pops up? This will help us get a reproduction case together to get the issue fixed as quickly as possible :smile:. Thanks!
