### ISSUE TITLE
Error: SSL certificate problem: self signed certificate in certificate chain during vagrant up

### ISSUE THREAD

**Issue by mleva-bnet** [mitchellh/vagrant#6853]
ubuntu 14.04
vagrant 1.8.1

'vagrant up' logs: https://gist.github.com/82090288d91114ac0c2d

i turned off the secure option in curl via /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/downloader.rb, and then got a metadata malformed error when downloading the file. logs: https://gist.github.com/b126cc727dd7d67c781b

**Comment by sethvargo** [comment]
Hi @mleva-bnet 

Thank you for opening an issue. I just tried Ubuntu 14.04 and I am unable to reproduce this issue. The fact that you're getting a cert error and _then_ malformed metadata leads me to believe you are behind some kind of corporate proxy or firewall that is altering the connection data. Could you please look into that? You may need to configure Vagrant to use a proxy.

**Comment by mleva-bnet** [comment]
yes, youre right - this was happening at work. i tried from home and had no issues. for now, will just manually download the box in chrome (which works for some reason) and vagrant up from there. you may close this, thanks!
