### ISSUE TITLE
vagrant 1.8 cannot detect ansible 2.10 

### ISSUE THREAD

**Issue by mintwax** [mitchellh/vagrant#6858]
```
$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: C:/Users/molee1/AppData/Local/Temp/vagrant-shell20160112-3012-gvfb55.sh
==> default: /tmp/vagrant-shell: Ansible is already installed
==> default: Running provisioner: ansible_local...
The Ansible software could not be found! Please verify
that Ansible is correctly installed on your guest system.

If you haven't installed Ansible yet, please install Ansible
on your Vagrant basebox, or enable the automated setup with the
`install` option of this provisioner. Please check
https://docs.vagrantup.com/v2/provisioning/ansible_local.html
for more information.

$ vagrant --version
Vagrant 1.8.1
```

I'm using git bash on windows 7.  The guest is centOS 7 base box.  And I'm using ansible_local to provision.  Everything was working before with ansible 1.9.4 on the guest.  I just installed ansible 2.10 from github after creating the rpm.   I have a bootstrap script that does a yum install ansible-2.10 from my local repo.

The problem is in vagrant in how it detects whether ansible is installed:

/c/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/provisioners/ansible/provisioner/guest.rb
```
    # Check that ansible binaries are well installed on the guest,
          @machine.communicate.execute(
            "ansible-galaxy --help && ansible-playbook --help",
            :error_class => Ansible::Errors::AnsibleNotFoundOnGuest,
            :error_key => :ansible_not_found_on_guest)

```

If I run ansible-galaxy --help on the VM it will return an error which causes vagrant to think that ansible is not installed.  

```

[vagrant@propel ~]$ ansible-galaxy --help
Usage: ansible-galaxy [delete|import|info|init|install|list|login|remove|search|setup] [--help] [options] ...

Options:
  -h, --help     show this help message and exit
  -v, --verbose  verbose mode (-vvv for more, -vvvv to enable connection
                 debugging)
  --version      show program's version number and exit
ERROR! Missing required action
[vagrant@propel ~]$ echo $?
5
```

I changed that line in guest.rb to add an action (setup)
```
ansible-galaxy setup --help && ansible-playbook --help
```

and everything works again and vagrant can detect ansible.

**Comment by gildegoma** [comment]
@mintwax thanks for reporting this problem! However, I'm closing it because it duplicates #6793. Please follow this issue for further updates, thanks!

**Comment by mintwax** [comment]
@gildegoma Thanks for addressing this issue in 1.8.2.
