### ISSUE TITLE
Vagrant calling wrong NFS script for centos 7

### ISSUE THREAD

**Issue by mrvkino** [mitchellh/vagrant#6864]
When vagrant is configuring the NFS for my centos 7 guest OS it is using the wrong script. Centos 7 is using systemd, but vagrant try to use init.d. It seems it does not detect the availability of systemd correctly. If I look at (https://github.com/mitchellh/vagrant/blob/master/plugins/guests/redhat/cap/nfs_client.rb), it seems it has the wrong result.

I am able to connect by ssh and mount my NFS folder by hand. The only thing I can see that could cause any problem is the line "Defaults    requiretty" I commented in /etc/sudoers (visudo) to make ssh work with pty.

I based my centos box on this guide: (https://blog.engineyard.com/2014/building-a-vagrant-box)

Host: OSX 10.11.2
Guest: CENTOS 7.2
Vagrant: 1.8.1

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Running triggers before up...
==> default: Executing [:up, :resume] action on the VirtualBox tied VM...
==> default: Executing command "vboxmanage startvm license_server --type headless"...
==> default: Waiting for VM "license_server" to power on...
==> default: VM "license_server" has been successfully started.
==> default: Command execution finished.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/etc/init.d/rpcbind restart; /etc/init.d/nfs restart

Stdout from the command:



Stderr from the command:

bash: line 2: /etc/init.d/rpcbind: No such file or directory
bash: line 2: /etc/init.d/nfs: No such file or directory
```

**Comment by mrvkino** [comment]
I think I found the problem. In my ~/.bash_profile I had a command that started fish shell automatically
```bash
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin

export PATH
export DISPLAY=:0
fish
```
When I remove it it works. I had the same thing on my Linux Mint Guest OS and it was working since vagrant was not doing the same test for the nfs restart.

To reproduce the behaviour, start fish at the end of the .bash_profile or simply use by default for user vagrant a shell that will fail on this command (fish or other):
```bash
"test $(ps -o comm= 1) == 'systemd'"
```

It might be good to tell people to set a default compatible shell (bash, dash, or tcsh) or test for the type of shell or run test command in a known sub shell.

**Comment by chrisroberts** [comment]
Closing this as it looks to be a local configuration issue.
