### ISSUE TITLE
Proposal: add support of Policyfile for Chef provisioner

### ISSUE THREAD

**Issue by legal90** [mitchellh/vagrant#6865]
Chef Software have introduced a new feature - Policyfile. In few words it allows to manage cookbook dependencies, node attributes and run lists using the single file. More details: https://github.com/chef/chef-dk/blob/master/POLICYFILE_README.md
It is still in active development, but the idea is really good so far.

The Policyfile support in the Vagrant will be really useful for those who already use this new feature in their production environments with Chef. It would be nice to use same `Policyfile.rb` (and/or `Policyfile.lock.json`) to provision the dev environment in the Vagrant.

At this moment we should keep both of Policyfile and Berksfile in order to manage cookbook dependencies. The first one - for production envs & tests via TestKitchen, and the second one - for local dev environments by Vagrant.

Policyfile is already supported in the TestKitchen, where it is implemented via additional provider, `policyfile_zero`: https://github.com/chef/chef-dk/blob/master/lib/kitchen/provisioner/policyfile_zero.rb

@sethvargo, what do you think about that? Is it reasonable to implement this feature in the Vagrant core, or it should be done via 3rd-party plugin, like `vagrant-berkshelf`? 
Is it better to implement it as an additional provisioner (`policyfile_zero`, `chef_policyfile`, etc?) or just by  extending the existing `chef-zero` provisioner?

**Comment by sethvargo** [comment]
Hi @legal90 

I think this should be done with an external plugin first and then potentially moved into core later :smile:

**Comment by legal90** [comment]
Okay... :)

**Comment by sethvargo** [comment]
@legal90 to explain a little bit more, especially for new and evolving things, there is a much higher velocity (release cycle) to plugins than Vagrant core.

**Comment by fletchowns** [comment]
Just wanted to chime in and say that it would be great to be able to use policies inside a Vagrantfile.

> The first one - for production envs & tests via TestKitchen, and the second one - for local dev environments by Vagrant.

This is the same spot we're in. @legal90 did you ever find a better solution?

**Comment by simoninkin** [comment]
Hi, are there any updates on this? It's been a year now...

**Comment by jugatsu** [comment]
Any updates guys?

@legal90 Did your find any solution?

**Comment by legal90** [comment]
@jugatsu No, I stopped using plain Vagrant for bootstrapping dev and test environments provisioned by Chef. 
I switched to TestKitchen (with vagrant driver) instead. It has its own implementation of provisioners and Policyfiles are supported there out-of-box.

**Comment by jugatsu** [comment]
@legal90 thx for response.

How do your handle vagrant up/halt/reload using test-kitchen?

**Comment by legal90** [comment]
Since TeskKitchen CLI is not designed for managing long-living persistant instances, it's not so convenient as plain Vagrant CLI.

- `vagrant up` -> `kitchen converge` (or `kitchen create && converge` if the VM is created but powered off)
- `vagrant halt` -> no way. I just stop the VM manually from the hypervisor GUI window.
- `vagrant reload` -> usually I don't need that. But in case I do, I would just run two previous steps - stop the VM manually an then `kitchen create`.

**Comment by fletchowns** [comment]
> How do your handle vagrant up/halt/reload using test-kitchen?

@jugatsu test kitchen generates a Vagrantfile under the hood so you can do something like:
```
$ kitchen converge whatever-redhat-74
$ cd .kitchen/kitchen-vagrant/kitchen-whatever-centos-74
$ vagrant halt/up/etc
```

**Comment by jugatsu** [comment]
@legal90 
As a workaround we can use `chef_client` provisioner.
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.provider 'virtualbox' do |v|
    v.linked_clone = true if Gem::Version.new(Vagrant::VERSION) >= Gem::Version.new('1.8.0')
  end

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision "chef_client" do |chef|
    chef.chef_server_url = "https://chef.example.com/organizations/gf"
    chef.validation_key_path = "~/Dropbox/devops/gf_infra/chef/.chef/gf-validator.pem"
    chef.validation_client_name = "gf-validator"
    chef.channel = "stable"
    chef.version = "13"
    chef.delete_node = true
    chef.delete_client = true
    chef.json = {
      "policy_name": "socks5-server",
      "policy_group": "stage",
    }
  end
end
```

```bash
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Running provisioner: chef_client...
==> default: Detected Chef (13) is already installed
==> default: Creating folder to hold client key...
==> default: Uploading chef client validation key...
==> default: Generating chef JSON and uploading...
==> default: Warning: Chef run list is empty. This may not be what you want.
==> default: Running chef-client...
==> default: [2018-05-12T09:38:17+00:00] INFO: Forking chef instance to converge...
==> default: [2018-05-12T09:38:17+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 13.9.1
==> default: [2018-05-12T09:38:17+00:00] INFO: *** Chef 13.9.1 ***
==> default: [2018-05-12T09:38:17+00:00] INFO: *** Chef 13.9.1 ***
==> default: [2018-05-12T09:38:17+00:00] INFO: Platform: x86_64-linux
==> default: [2018-05-12T09:38:17+00:00] INFO: Platform: x86_64-linux
==> default: [2018-05-12T09:38:17+00:00] INFO: Chef-client pid: 15545
==> default: [2018-05-12T09:38:17+00:00] INFO: Chef-client pid: 15545
==> default: [2018-05-12T09:38:17+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
==> default: [2018-05-12T09:38:17+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
==> default: Using policy 'socks5-server' at revision '0ae5f2fda27d10f076b328e56b37c39c7dfaa5327baf839ccd33e8053ddba168'
```
