### ISSUE TITLE
Please document that `sudo visudo` should be used to edit `/etc/sudoers`.

### ISSUE THREAD

**Issue by theengineear** [mitchellh/vagrant#6872]
The documentation on [NFS Synced Folders](https://docs.vagrantup.com/v2/synced-folders/nfs.html) is awesome. However, there's no mention of how to edit that `/etc/sudoers` file.

I didn't know about the `visudo` command and went ahead and edited the file. What I entered had a syntax error and fixing it took a really long time because I lost the ability to `sudo` at all.

I'm sure using `visudo` is obvious to those who know. But I'm also certain that no one who knows about `visudo` will think twice before editing that file by another means.

If you can point me to where documentation can be added, I'd be happy to make a PR.

**Comment by sethvargo** [comment]
Hi @theengineear 

The documentation lives in the `website` folder of the Vagrant repo
