### ISSUE TITLE
Getting "is not a block device" error when NFS-mounting rsynced_folder

### ISSUE THREAD

**Issue by flaugher** [mitchellh/vagrant#6875]
When I try to share a local folder to the guest VM using NFS, I'm getting the following error:

````
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'debian/jessie64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 443 (guest) => 8443 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
GuestAdditions 5.0.12 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /Users/smith/playbooks/site1/ => /vagrant
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
The following SSH comand responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,upd' 192.168.33.1:'/Users/smith/playbooks/site1/website' /srv/http/site1.com

Stdout from the commmand:

Stderror from the command:

stdin: is not a ttyp
mount: /home/vagrant/192.168.33.1:/Users/smith/playbooks/site1/website is not a block device
````

Here is my Vagrantfile:

````
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "website/", "/srv/http/site1.com", nfs: true
end
````

This error does not occur the first time I bring a box up nor does it occur during any subsequent vagrant ups or reloads.  It only occurs if I unmount the file system from my Ansible playbook and then try to remount it via the playbook.  When I run my playbook, I get the following error:

````
Error mounting 192.168.33.1:/Users/smith/playbooks/site1/website: mount.nfs: remote share not in 'host:dir' format
````

Here's the playbook:

````
- name: Remount code directory
  hosts: web
  sudo: True
  tasks:
    - name: unmount website
      mount:
        name: /srv/http/site1.com
        src: srv_http_site1.com
        fstype: nfs
        state: unmounted
    - name: remount website
      mount: name="192.168.33.1:/Users/smith/playbooks/site1/website" src="srv_http_site1.com" fstype=nfs state=mounted
````

If I do a vagrant up or reload after encountering the Ansible playbook error, I get the "is not a block device" error shown above.  I can see why the mount command says "/home/vagrant/192.168.33.1:/Users/smith/playbooks/site1/website" isn't a block device, I just don't know how to get Vagrant and Ansible to figure out what the correct block device designation should be.

I tried adding this line to my guest's /etc/hosts file and then replaced the IP address in my mount task with "laptop":

````
192.168.33.1   laptop
````

Unfortunately this didn't fix the problem.  Does anyone have any ideas on what might be causing this error or what I might to do resolve it?

My local host is running OS X 10.9.5, NFS 3, VirtualBox 5.0.12 r104815, Vagrant 1.8.1, and Ansible 1.9.2. I also have installed the plugins vagrant-share 1.1.5 and vagrant-vbguest 0.11.0.

Thanks.

**Comment by sethvargo** [comment]
Hi @flaugher 

Thank you for opening an issue, and I am sorry this is causing you trouble. I think this is working as intended, albeit the error message is not the friendliest. That error is actually coming from Virtualbox, not Vagrant, and it's occurring because you're trying to mount to an already-mounted volume. I would recommend either removing the synced folder (as nfs) and let ansible do the mounting, or use a variable in ansible to control the mounting when ansible runs. Sorry! :frowning:
