### ISSUE TITLE
Setting up a GUI in Ubuntu breaks vagrant ssh

### ISSUE THREAD

**Issue by cpitclaudel** [mitchellh/vagrant#6877]
Hi folks,

Vagrant is looking great. I'd like to use it to set up a reproducible environment for my research. I'm using the ubuntu/vivid64 base box.

Provisioning works great, but after logging in and running `apt-get install lubuntu-desktop` and rebooting, I can use `vagrant ssh` anymore:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant

Stdout from the command:



Stderr from the command:

initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
```

Starting the box VM the VirtualBox UI wroks great, and does take me to the Ubuntu desktop.

**Comment by kikitux** [comment]
I think the installation of that package is interfering with the kernel module of the vbox mount point.

A simple way will be use a Vagrant box that is close to what you need:
`https://atlas.hashicorp.com/boxes/search?utf8=%E2%9C%93&sort=&provider=&q=lubuntu`

I don't believe this is a vagrant issue, and should be better handled in the mailing list:
`https://groups.google.com/forum/#!forum/vagrant-up`

Do you mind if we follow up this there?

**Comment by cpitclaudel** [comment]
Thanks for the pointer. The mailing list might be a better place for this discussion indeed.
