### ISSUE TITLE
A VirtualBox machine with the name already exists

### ISSUE THREAD

**Issue by winchendonsprings** [mitchellh/vagrant#6878]
I run into this error while booting a vagrant box

```
A VirtualBox machine with the name 'oct22_vlad' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```

I have checked and I don't see another box with that name. I have also grepped via ag my home dir for the box in question's id

```
~ ag "96396630-1eb7-4f8a-9bd5-9a50f58f2a18" ~
/home/ry/VirtualBoxes/oct22_vlad/oct22_vlad.vbox
9:  <Machine uuid="{96396630-1eb7-4f8a-9bd5-9a50f58f2a18}" name="oct22_vlad" OSType="Ubuntu_64" snapshotFolder="Snapshots" lastStateChange="2016-01-14T20:58:57Z">

/home/ry/VirtualBoxes/oct22_vlad/oct22_vlad.vbox-prev
9:  <Machine uuid="{96396630-1eb7-4f8a-9bd5-9a50f58f2a18}" name="oct22_vlad" OSType="Ubuntu_64" snapshotFolder="Snapshots" lastStateChange="2016-01-14T20:58:57Z">

/home/ry/VirtualBoxes/oct22_vlad/Logs/VBox.log
1005:01:00:41.340395 GUI: UIMediumEnumerator: Machine (or snapshot) event received, ID = 96396630-1eb7-4f8a-9bd5-9a50f58f2a18
1009:01:00:41.640717 GUI: UIMediumEnumerator: Machine (or snapshot) event processed, ID = 96396630-1eb7-4f8a-9bd5-9a50f58f2a18
1023:01:01:09.732578 GUI: UIMediumEnumerator: Machine (or snapshot) event received, ID = 96396630-1eb7-4f8a-9bd5-9a50f58f2a18
1027:01:01:09.733480 GUI: UIMediumEnumerator: Machine (or snapshot) event processed, ID = 96396630-1eb7-4f8a-9bd5-9a50f58f2a18
~ 
```
I'm out of ideas. I cannot boot the box. I need to access files within the box. 

Is there any other ways to check if another box has the same name? Or force boot the box anyway?

**Comment by sethvargo** [comment]
Hi @winchendonsprings 

Can you look in the Virtualbox GUI? That error is coming from Virtualbox, not Vagrant, so this is not specifically a Vagrant issue, but we can try to help you debug it.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
