### ISSUE TITLE
vagrant 1.8 + under emacs shell or sub-proceess always immediatly exits with 255

### ISSUE THREAD

**Issue by ian-kelling** [mitchellh/vagrant#6880]
Ubuntu 12.04, GNU Emacs 25.0.50.1

Testing without avoid any user configuration,

```
    emacs -Q
    # C-x e the following commands
    (shell-command "vagrant")
    # messages buffer says:
    (Shell command failed with code 255 and no output)
    255 (#o377, #xff, ?ÿ)
    (setq shell-file-name "sh")
    (shell)
    # in the new buffer
    vagrant
    # no output
    echo $?
    255
    gnome-terminal
    vagrant
    # no output
    echo $?
    255
```

Outside of emacs or emacs subprocesses, it works fine, outputing help text when running just vagrant.

**Comment by grubernaut** [comment]
Hi @ian-kelling,

I'm unable to reproduce this with Emacs 24.5.1, I'll update to 25.0.50.1 and try again. 
However, there shouldn't be any output from the `vagrant` command in the messages buffer. The `shell-command` command in elisp directs output to a new buffer, `Shell Command Output`. The exit code that I'm returning from running `vagrant` is `1` as well.

However, even calling the shell from elisp, leaves me with successful output from running the `vagrant` command, so I'm leaning towards this being a bug in Emacs 25.0.50.1. 

Also, could you verify that emacs is using the correct `PATH` environment variable? 

```
(getenv "PATH")
(shell-command "which vagrant)
# The output of the shell-command should be in a new buffer
```


I'll update my emacs version shortly and verify.

**Comment by grubernaut** [comment]
Rebuilt emacs from source, leaving me with the following version:
```
$ emacs --version
GNU Emacs 25.1.50.1
```

Still unable to reproduce your error using emacs built from source. 
<img width="609" alt="screen shot 2016-01-19 at 11 03 27 am" src="https://cloud.githubusercontent.com/assets/3082319/12424032/58d5bde0-be9c-11e5-85ba-f4daa1eaa650.png">

I'm also launching emacs via `emacs -Q` to remove any potential user configuration. 

Running `(shell-command "which vagrant")` also leaves me with `/usr/bin/vagrant`

**Comment by ian-kelling** [comment]
I tried on a different computer with debian testing debian, didn't repro. And the latest emacs sources don't compile due to an older gcc version. Seems like it's not a vagrant bug. Thanks for trying to repro. Closing this.
