### ISSUE TITLE
HyperV `VirtualizationException` TypeNotFound in get_vm_status.ps1

### ISSUE THREAD

**Issue by illuminus86** [mitchellh/vagrant#6882]
Using Vagrant 1.8.1 on Windows 8.1.

Running `vagrant up` immediately fails:

```
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: get_vm_status.ps1
Error:

C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.1\plugins\providers\hyperv\scripts\get_vm_status.ps1 : Unable to find type
[Microsoft.HyperV.PowerShell.VirtualizationException]. Make sure that the assembly that contains this type is loaded.
At line:1 char:1
+ &('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.1\plugins\providers\hyper ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Hyper...zationException:TypeName) [get_vm_status.ps1], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,get_vm_status.ps1
```

Reproduction steps:
1. Run `vagrant up`
2. Use Hyper-V manager to delete VM instead of `vagrant destroy`
3. Run `vagrant up` again - error occurs

Workaround:
If I manually edit `get_vm_status.ps1` to catch exception type `Exception` instead of `Microsoft.HyperV.PowerShell.VirtualizationException`, `vagrant up` appears to work normally.

**Comment by tomfanning** [comment]
+1 me too, intermittently, when running many vagrant ups in parallel

**Comment by PierrickI3** [comment]
+1. Happened after I ran `vagrant destroy -f` followed by a `vagrant up`

**Comment by blanoz** [comment]
This should be fixed in https://github.com/mitchellh/vagrant/pull/7487
