### ISSUE TITLE
bash: line 3: xit: command not found

### ISSUE THREAD

**Issue by garethahealy** [mitchellh/vagrant#6884]
I have a vagrant image [1] that creates 3 VMs. The last one succeeds [2], but reports an error back.

Am not 100% sure if this is a vagrant issue or something wrong with my setup, so thought i'd raise an issue.

[1] https://github.com/garethahealy/vagrant-files/tree/master/jboss_on/jboss_on_33
[2] https://github.com/garethahealy/vagrant-files/blob/master/jboss_on/jboss_on_33/bootstrap-jon-agent.sh#L28

```
==> jonagent: + ./rhq-agent-wrapper.sh status
==> jonagent: RHQ Agent                      (pid 16473  ) is running
==> jonagent: bash: line 3: xit: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

```
localhost:garethah$ vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1
You're running an up-to-date version of Vagrant!
```

```
localhost:garethah$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50
```

**Comment by sethvargo** [comment]
Hi @garethahealy 

Thank you for opening an issue. This does not look like an issue; I think this is coming from "exit" (xit) and looks related to this bug:

https://cygwin.com/ml/cygwin/2002-09/msg00368.html

That's for cygwin (obviously), but it looks suspiciously similar.

Please check all the line endings and character encodings in your script.

**Comment by awesomescot** [comment]
I'm having the exact same issue.  I'm getting this at the end of my bootstrap.sh, everything in the file looks like it ran correctly, this just gets thrown at the very end.

bash: line 3: xit: command not found

I've checked line endings, and searched for 'xit'.  I also tried putting exit 0 at the end of the file.  No luck.  Anyone have any suggestions?

**Comment by garethahealy** [comment]
@awesomescot: No, i've not been able to see whats wrong either within my files.

**Comment by sethvargo** [comment]
Hi everyone,

I do not think this is an issue with Vagrant. If it were a widespread issue, we would see many more comments and +1's on this issue. Unfortunately I think it's something with the local environment. I am happy to help debug this, but I think the solution is going to lie outside of Vagrant. Thanks! :smile:
