### ISSUE TITLE
Vagrant can't handle automatically 443 port/https access on MacOSX

### ISSUE THREAD

**Issue by cfrancois7** [mitchellh/vagrant#6890]
I was testing a docker container through vagrant VM in my MacOSX which needs a "https" access (port 443).
But the problem is the port 443 isn't open on MacOSX and the vagrant "VM" doesn't handle the port 443 redirection between the local browser and the container.
It could be nice to have much more information about that in the documentation.

See [this blog](http://salferrarello.com/mac-pfctl-port-forwarding/) which presents a solution with pf.

For example, redirect HTTPS port (443) to 8443 port

```
echo "
rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443
" | sudo pfctl -ef -
```

And define the port config in vagrantfile (here, example with docker provider:

```ruby
config.vm.define "my_container" do |a|
 a.vm.provider "docker" do |d|
   # ...
   d.ports = [8443:443]
 end
end
```

An another solution is to use the trigger plugin.

```ruby
config.trigger.after [:up, :reload, :provision], :stdout => true do

system('echo "
rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443
" | sudo pfctl -ef - >/dev/null 2>&1; echo "Add Port Forwarding (80 => 8080)\nAdd Port Forwarding (443 => 8443)"')
end
```

**Comment by sethvargo** [comment]
Hi @cfrancois7 

Thank you for opening an issue, and I am sorry this is causing you problems. Just to make sure I understand the issue correctly, could you please share your complete Vagrantfile and the commands you are running?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄
