### ISSUE TITLE
public + private network

### ISSUE THREAD

**Issue by jostra** [mitchellh/vagrant#6895]
Hi 
I have a problem with setup 3 private and 1 public network for one box. Does vagrant support mix setup? 

my config:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :manager do |mng_config|
      mng_config.vm.box = "geerlingguy/centos7"

      mng_config.vm.network "private_network", ip: "192.168.33.10"
      mng_config.vm.network "private_network", ip: "192.168.43.20"
      mng_config.vm.network "public_network", ip:"10.9.170.21", :netmask => "255.255.0.0", bridge: "enp65s1"
      mng_config.vm.network "public_network", bridge: "enp65s1"
      mng_config.vm.hostname = "manager"
      mng_config.vm.usable_port_range= 2800..2900
      mng_config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
  end

  # default router
  config.vm.provision "shell",
    run: "always",
    inline: "route add default gw 10.19.32.1"
end
```

vagrant up just stay at ==> manager: Configuring and enabling network interfaces...  for infinity.

**Comment by jostra** [comment]
sorry one typo just:

mng_config.vm.box = "geerlingguy/centos7"

  mng_config.vm.network "private_network", ip: "192.168.33.10"
  mng_config.vm.network "private_network", ip: "192.168.43.20"
  mng_config.vm.network "public_network", ip:"10.9.170.21", :netmask => "255.255.0.0", bridge: "enp65s1"
  mng_config.vm.hostname = "manager"
  mng_config.vm.usable_port_range= 2800..2900
  mng_config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

**Comment by nextrevision** [comment]
I have a very similar issue when using a RHEL 7 box and specifying multiple private (hostonly) networks. The problem seems to occur when configuring the first of the additional interfaces, in my case `eth1`. Commenting out the additional network statements causes the box to come up just fine. I believe I only started experiencing this after upgrading Virtualbox from 4.3.34 to 5.0.14 on a trusty box.

**Comment by sethvargo** [comment]
Hi @jostra 

Can you please run the command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html) and put the output in a GitHub Gist? Thanks! :smile:

**Comment by nextrevision** [comment]
Rebuilding the vagrant box with packer and stopping and disabling NetworkManager in the build process seemed to do the trick for me. Don't want to hijack the issue, but here are the debug logs from my tests: https://gist.github.com/nextrevision/63ffb35eaf83c879d7bf.

**Comment by jostra** [comment]
It's look like that if I use only 2 NIC one for public and one private then work, but if I use 3 NIC -2 for private and 1 for public it fails. 


it will not work:
      mng_config.vm.network "private_network", ip: "192.168.33.10"
      mng_config.vm.network "private_network", ip: "192.168.43.20"
      mng_config.vm.network "public_network", ip:"10.9.170.223", :netmask => "255.255.0.0", bridge: "enp65s1"


it will work:
      mng_config.vm.network "private_network", ip: "192.168.33.10"
      mng_config.vm.network "public_network", ip:"10.9.170.223", :netmask => "255.255.0.0", bridge: "enp65s1"

I'm using VirtualBox-5.0-5.0.14_105127_el7-1.x86_64 and vagrant-1.8.1-1.x86_64 

In debug logs
[debug.log.tar.gz](https://github.com/mitchellh/vagrant/files/108805/debug.log.tar.gz)
 there is:
[jost@jostr vagrant-debug]$ tar tvf debug.log.tar.gz
-rw-r--r-- jost/jost    998480 2016-01-28 20:56 debug-log-2nic.txt  --> this work
-rw-r--r-- jost/jost   1051695 2016-01-28 20:47 debug-log-3nic.txt  --> this doesn't work I just use Ctrl+C to stop.

Hope this helps!

**Comment by jostra** [comment]
Any solution for that problem?

**Comment by sethvargo** [comment]
Hi all,

In my research, this appears to be a Virtualbox issue, not a Vagrant issue. Could you please open an issue on that projects tracker? Thanks! :smile:
