### ISSUE TITLE
vagrant share error

### ISSUE THREAD

**Issue by jmerritt** [mitchellh/vagrant#6896]
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.

What other information is needed?

**Comment by simendsjo** [comment]
I get she same issue. `vagrant share` just outputs the help and a status code of `1`. `vagrant help share`, `vagrant share --help` etc gives the same behavior.

I'm using version 1.8.1 on Arch Linux.

**Comment by sethvargo** [comment]
Hi @jmerritt 

Can you please share your complete Vagrantfile, guest OS, and host OS please?

**Comment by simendsjo** [comment]
Guest OS: `Linux vagrant-ubuntu-trusty-64 3.13.0-76-generic #120-Ubuntu SMP Mon Jan 18 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Host OS: `Linux simendsjo-macbook 4.3.4-1-ck #1 SMP PREEMPT Sat Jan 23 08:43:49 EST 2016 x86_64 GNU/Linux`

Vagrantfile:

```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y fsharp
    sudo apt-get install -y nginx
  SHELL
end
```

**Comment by twomasz** [comment]
I get also help output and exit code `1` after `vagrant share`.

Vagrant.configure(2) do |config|
  config.vm.box = "debian/contrib-jessie64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
end

Host OS: `Linux tomas-Latitude-E4200 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

Guest: `Linux contrib-jessie 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux`

I had the same with "debian/jessie64" as guest today.

**Comment by twomasz** [comment]
I finally installed an original one from [Vagrant](https://www.vagrantup.com/downloads.html). Now it's ok.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
