### ISSUE TITLE
Vagrant halt is failing with syntax error near unexpected token `||'

### ISSUE THREAD

**Issue by saptarshidebnath** [mitchellh/vagrant#6900]
***Vagrant is not able to halt / reload after the initial vagrant up*** (ie the one where the vm is provisioned). The initial vagrant up completes correctly, however after that I am not able to do the vagrant halt or reload.

The error message that I am getting is:

```
==> default: Attempting graceful shutdown of VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

shutdown -h now

Stdout from the command:

Stderr from the command:

stdin: is not a tty
bash: line 2: syntax error near unexpected token `||'
bash: line 2: `export SSH_AUTH_SOCK=                ||     ||'
```

List of vagrant plugin I am using:

- vagrant-proxyconf (1.5.2)
- vagrant-share (1.1.5, system)

Vagrant version is 1.8.1
Virtualbox [provider] version 4.3.34r104062
Host OS : Windows 7 Enterprise

I have tried re-installing, all the components, destroying the VMs, deleting the config files [ie c:\Userrs\<username>\.VirtualBox & c:\Userrs\<username>\.vagrant.d].

**Comment by sethvargo** [comment]
Hi @saptarshidebnath 

Can you please share your complete Vagrantfile and the output of the vagrant halt command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html)? Thanks!

**Comment by saptarshidebnath** [comment]
@sethvargo My host system is windows and I am not able to capture debug information.

I am running the following command 

```
vagrant halt --debug > debug.log
````
and the only thing that got captured is 
```
Found HTTP_PROXY_USER envar: saptarshi
Found HTTP_PROXY_PWRD envar: ***********
Found HTTP_PROXY_HOST envar: example.proxy.com
Found HTTP_PROXY_PORT envar: 8080
[1m==> default: Attempting graceful shutdown of VM...[0m
```
I googled a little bit but couldn't figure out a way to capture the debug log to a file. 

Any help will be a appreciated

**Comment by saptarshidebnath** [comment]
@sethvargo The vagrant corrected itself when i reset the code base from the repo. Thanks for the assistance,
