### ISSUE TITLE
Chef Solo provisioner not running recipes 

### ISSUE THREAD

**Issue by bazmecode** [mitchellh/vagrant#6902]
I'm using the Windows Server 2012 R box from https://github.com/joefitzgerald/packer-windows.
I have added the chef-solo provisioner in my Vagrant file as follows:

```ruby
config.vm.provision :chef_solo do |chef|
  chef.add_recipe "apache2"
  chef.json = { :apache => { :default_site_enabled => true } }
end
```

However, on executing:

```
vagrant provision
```

I get the following message, without the recipe being run.

```
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
==> default: Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: VERBOSE: Installation started...
==> default: Success Restart Needed Exit Code      Feature Result
==> default: ------- -------------- ---------      --------------
==> default: True    No             NoChangeNeeded {}
==> default: VERBOSE: Installation succeeded.
```

**Comment by sethvargo** [comment]
Hi @bazmecode 

Can you please share your complete Vagrantfile as well as the output of the vagrant command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html)?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
