### ISSUE TITLE
SMB synced folder support for linux

### ISSUE THREAD

**Issue by varac** [mitchellh/vagrant#6904]
https://github.com/mitchellh/vagrant/issues/1749 was about SMB support in general, and the windows part has been integrated. It should not be too hard to implement it on linux as well.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
