### ISSUE TITLE
Detect which command has been invoked from Vagrantfile / plugin

### ISSUE THREAD

**Issue by marcofranssen** [mitchellh/vagrant#6905]
Hi,

I want to know which command has been invoked from the Vagrantfile to do some custom ruby code. Once finished I also want to move this code into a plugin.

I hope someone can tell me how to access that information from the Vagrantfile.

**Comment by sethvargo** [comment]
Hi @marcofranssen 

It is not possible to access the command that was run, because the Vagrantfile is loaded multiple times through Vagrant's initialization process. If you explain your use case, I might be able to suggest an alternative approach.

**Comment by marcofranssen** [comment]
As we use a personal webserver with basic authentication I want to ask for the credentials.

```
  $stdout.print "    login: "
  cloud_user = $stdin.gets.chomp
  $stdout.print "    password: "
  cloud_password = $stdin.noecho(&:gets).chomp
  $stdout.print ""

  config.vm.box_url = "http://#{cloud_user}:#{cloud_password}@#{cloud}/#{config.vm.box}/"
```

But I only want to do so when vagrant actually tries to check for updates.

So on `vagrant up` for example, but not on `vagrant provision`.

**Comment by sethvargo** [comment]
Hi @marcofranssen 

I would recommend using environment variables for this instead.
