### ISSUE TITLE
SMB shares do not work with passwords containing dollar signs

### ISSUE THREAD

**Issue by LachlanArthur** [mitchellh/vagrant#6906]
If the SMB password contains a dollar sign ($), the password is not saved correctly and CIFS fails to authenticate.

The saved password in `/etc/smb_creds_xxx` is missing all dollar signs as well as the characters following the dollar signs.

If the dollar sign is escaped with a backslash when entering the password on `vagrant up`, then the smb_creds file contains the dollar sign twice which seems to work.

Vagrant version 1.8.1

**Comment by LachlanArthur** [comment]
Also, as an added bonus, I guess using a backslash in your password would also cause an error, seeing as the backslash typed into the console to escape the dollar sign doesn't get escaped itself.

**Comment by LachlanArthur** [comment]
The issue can be fixed by turning off parameter substitution in the heredoc used to generate the SMB creds file. This is done by quoting the opening limit string (`EOF` in this case).

Edit the file
`Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/linux/cap/mount_smb_shared_folder.rb` on line 51 from

    cat <<EOF >/etc/smb_creds_#{name}

to

    cat <<"EOF" >/etc/smb_creds_#{name}

This will fix issues with the following characters in passwords:

    `$\

**Comment by sethvargo** [comment]
Hey @LachlanArthur 

Good find! Thanks!
