### ISSUE TITLE
BSD host's NFS exports editing uses tee from $PATH

### ISSUE THREAD

**Issue by antifuchs** [mitchellh/vagrant#6913]
I am running Vagrant 1.7.3 on OS X 10.11 with gnu coreutils from homebrew (using the `gnubin` $PATH hack), and was wondering why my sudoers entries from the Vagrant documentation were not having an effect: I was still prompted despite having the exact /etc/sudoers entries from the documentation on my system.

Console.app however reveals that Vagrant is picking the wrong `tee` program:

```
1/22/16 12:04:28.489 AM sudo[24588]:      asf : TTY=ttys001 ; PWD=/Users/asf/Hacks/mytool ; USER=root ; COMMAND=/usr/local/opt/coreutils/libexec/gnubin/tee -a /etc/exports
```

(my `$PATH` with the gnubin hack is `/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`)

 this doesn't seem optimal, and in the worst case could also lead to a silly code-exec situation where a downloaded malicious Vagrantfile overrides `$PATH` to point to their own `tee` and then runs programs as root on a local machine when the oblivious user enters their password at the prompt (this seems far-fetched, but still ... ugh).

I believe the fix would be to specify an explicit path on https://github.com/mitchellh/vagrant/blob/master/plugins/hosts/bsd/cap/nfs.rb#L114, so `/usr/bin/tee` (as specified in the docs). Happy to submit a pull request if you agree (:

**Comment by briancain** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BSD host's NFS exports editing uses tee from $PATH](https://trello.com/c/Jtz1d3Ru/22-bsd-hosts-nfs-exports-editing-uses-tee-from-path)
