### ISSUE TITLE
Vagrant/VBox breaks when websense is installed.

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#6914]
This error happens when trying to run `vagrant`,

	$ vagrant
	fatal error: runtime: bsdthread_register error

	runtime stack:
	runtime.throw(0x162640, 0x21)
		/Users/mitchellh/code/3rdparty/go/src/runtime/panic.go:527 +0x90 fp=0x7fff5fbffbb0 sp=0x7fff5fbffb98
	runtime.goenvs()
		/Users/mitchellh/code/3rdparty/go/src/runtime/os1_darwin.go:73 +0x8d fp=0x7fff5fbffbd8 sp=0x7fff5fbffbb0
	runtime.schedinit()
		/Users/mitchellh/code/3rdparty/go/src/runtime/proc1.go:60 +0x83 fp=0x7fff5fbffc20 sp=0x7fff5fbffbd8
	runtime.rt0_go(0x7fff5fbffc58, 0x1, 0x7fff5fbffc58, 0x0, 0x0, 0x1, 0x7fff5fbffd48, 0x0, 0x7fff5fbffd50, 0x7fff5fbffd6c, ...)
		/Users/mitchellh/code/3rdparty/go/src/runtime/asm_amd64.s:109 +0x132 fp=0x7fff5fbffc28 sp=0x7fff5fbffc20

Environment:
> VBox 5.0.14, vagrant 1.8.1, OS X Yosemite v10.10.5 (Intel Core i7)

This suppose to be fixed, as per #6293, however it's still happening. See also: golang/go/issues/12238

I believe this could be related to websense extension which breaks it (and can't be removed as per company policy).

	$ kextstat | grep -e sense -e virtual
	  131    1 0xffffff803dc31a00 0x1a0      0x1a0      com.websense.endpoint.process.kpi (7.7.0)
	  132    1 0xffffff7f8387d000 0x14000    0x14000    com.websense.endpoint.process (8.0) <131 7 5 4 1>
	  133    0 0xffffff7f83891000 0x22000    0x22000    com.websense.endpoint.dlp (8.0) <132 5 4 3 1>
	  149    3 0xffffff7f838f7000 0x60000    0x60000    org.virtualbox.kext.VBoxDrv (5.0.14) <7 5 4 3 1>
	  150    0 0xffffff7f83957000 0x8000     0x8000     org.virtualbox.kext.VBoxUSB (5.0.14) <149 102 51 7 5 4 3 1>
	  151    0 0xffffff7f8395f000 0x5000     0x5000     org.virtualbox.kext.VBoxNetFlt (5.0.14) <149 7 5 4 3 1>
	  152    0 0xffffff7f83964000 0x6000     0x6000     org.virtualbox.kext.VBoxNetAdp (5.0.14) <149 5 4 1>

**Comment by sethvargo** [comment]
Hi @kenorb 

Please see this google thread for more information, but this is an issue with Golang, not Vagrant: https://groups.google.com/forum/#!topic/golang-nuts/HtcZc3wO-rw. Thank you for opening an issue, but unfortunately there's nothing Vagrant can do in this situation. There may be some solutions in that thread, but unfortunately websense is causing the process to crash. Does that make sense?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!

**Comment by narJH27** [comment]
I am facing this issue as well. OSX 10.10.5, Vagrant 1.8.1 and Virtualbox 5.0.12. I have also faced the problem with Virtualbox 5.0.16. Is there a known resolution or workaround to this problem?
