### ISSUE TITLE
Salt provisioner ignores run_highstate setting in masterless mode

### ISSUE THREAD

**Issue by siccrusher** [mitchellh/vagrant#6915]
On vagrant 1.8.1 i am experiencing issues when trying to bring up a masterless minion without running highstate. The relevant snippet from my config looks like this:

    salt.masterless = true
    salt.run_highstate = false

My expectation is that i end up with an installed salt-minion and that no highstate call is made during provisioning. After taking a look at the relevant [code](https://github.com/mitchellh/vagrant/blob/v1.8.1/plugins/provisioners/salt/provisioner.rb#L336) its quite obvious that the [call_masterless method] (https://github.com/mitchellh/vagrant/blob/v1.8.1/plugins/provisioners/salt/provisioner.rb#L323) silently ignores the run_highstate setting. From my point of view this is wrong or should (if there are reasons for this behaviour) be at least documented and an information passed back to the user like it happens for other "senseless" stuff like [calling orchestrate on a minion] (https://github.com/mitchellh/vagrant/blob/v1.8.1/plugins/provisioners/salt/provisioner.rb#L377).

If there are no reasons and this is simply a bug i would like to fix this behaviour.

**Comment by siccrusher** [comment]
I provided a PR for this.

https://github.com/mitchellh/vagrant/pull/6924

**Comment by msiebeneicher** [comment]
+1

**Comment by codekoala** [comment]
+1
