### ISSUE TITLE
Vagrant share fails to detect http port the first time it's run

### ISSUE THREAD

**Issue by rlifshay** [mitchellh/vagrant#6916]
I have a private network defined in my vagrantfile. The network works fine and the web server on it is accessible on port 80. The first time I run vagrant share after starting the vm, vagrant always fails to detect the http port. If I repeat the same command again, it detects it with no issues. I am currently on version 1.8.1 but it has never worked correctly for me. On earlier versions (I don't recall when it changed), it didn't detect the http port even if I ran share repeatedly. I would always have to manually specify the port.

Here is the port detection section of the log. You can see it finds the correct ip address and tries the correct port. For some reason it fails to detect the port as open but does not log a connection error like the other ports it tries.

```
 INFO interface: detail: Local machine address: 192.168.33.100
 INFO interface: detail:     main: Local machine address: 192.168.33.100
    main: Local machine address: 192.168.33.100
DEBUG share: No HTTP port set. Auto-detection will be attempted.
DEBUG helper: Trying: http://192.168.33.100:80/
DEBUG helper: Trying: http://192.168.33.100:22/
DEBUG helper: Trying: http://192.168.33.100:4567/
DEBUG helper: Trying: http://192.168.33.100:80/
DEBUG helper: Trying: http://192.168.33.100:8000/
DEBUG helper: Trying: http://192.168.33.100:8080/
DEBUG helper: Trying: http://192.168.33.100:3000/
 INFO retryable: Retryable exception raised: #<Errno::ECONNREFUSED: Connection refused - connect(2) for "192.168.33.100" port 4567>
 INFO retryable: Retryable exception raised: #<Errno::ECONNREFUSED: Connection refused - connect(2) for "192.168.33.100" port 8000>
 INFO retryable: Retryable exception raised: #<Errno::ECONNREFUSED: Connection refused - connect(2) for "192.168.33.100" port 8080>
 INFO retryable: Retryable exception raised: #<Net::HTTPBadResponse: wrong status line: "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3">
 INFO retryable: Retryable exception raised: #<Errno::ECONNREFUSED: Connection refused - connect(2) for "192.168.33.100" port 3000>
DEBUG helper: Not an HTTP URL: http://192.168.33.100:22/
DEBUG helper: Not an HTTP URL: http://192.168.33.100:80/
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000001febf40>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::Share::Errors::DetectHTTPCommonPortFailed: Vagrant was unable to detect an HTTP port for your machine.
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
