### ISSUE TITLE
atlas.hashicorp.com does not support resume

### ISSUE THREAD

**Issue by virgo47** [mitchellh/vagrant#6918]
I'm plagued by `SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054`, my internet is good, but not good enough to download big images. When this happened 98% of `mwrock/Windows2012R2` and `vagrant up` did not resume I had to be really strong not to break something.

This makes downloading some images real mission impossible. :-( I have to download them differently and add the box manually, which is far from `vagrant up` you hear about in any post or book. Resuming is absolute must when we consider the size of images.

Version 1.8.1

**Comment by sethvargo** [comment]
Hi @virgo47 

Thank you for opening an issue. There is another issue tracking box download resumes (sorry - I do not remember the number offhand). Vagrant itself supports box resumes, and we have upstream issues in atlas to add support there. Thanks! :smile:
