### ISSUE TITLE
Vagrant SSH on Windows 7 Path and other issues

### ISSUE THREAD

**Issue by GTMAN** [mitchellh/vagrant#6919]
Vagrant SSH on windows 7 throw and error that it can't find the executable. I have GIT installed and when I browse to the bin directory I see that the executable is named sh.exe NOT ssh.exe. I renamed the file and now I'm getting this:

/usr/bin/bash: vagrant@127.0.0.1: No such file or directory

I also installed Cygwin64 and it also has sh.exe and not ssh.exe.?

Thanks in advance for any help.

**Comment by COleo** [comment]
sh.exe is the bash shell and ssh.exe the ssh client. They should be both in the bin directory of git. If not it seems your git installation is not complete.

Have you included "c:\Program Files\git\usr\bin" in your PATH, or allowed Cygwin to extend your PATH?

In a cmd window you can check with:  `set %PATH%`

The good news, I run vagrant on Windows7 successfully. So there should be a way

**Comment by impr0t** [comment]
My solution is to simply use the Git Bash Prompt from the standard Git install settings.  You still have access to your Windows path, but you gain a few useful tools along the way (like ssh).

For the future, I would not recommend renaming any binaries.  You're just asking for trouble.

**Comment by chrisroberts** [comment]
Closing this as it was an ssh installation problem. Other issues are already open around embedded ssh client. Cheers!
