### ISSUE TITLE
ansible_ssh_user is deprecated in Ansible 2

### ISSUE THREAD

**Issue by jeffwidman** [mitchellh/vagrant#6927]
`ansible_ssh_user` is used several times in the code and docs. 

However, it's deprecated in Ansible 2 in favor of `ansible_user`. 

Not sure how you want to handle--switching over completely would force people onto Ansible 2 when they might prefer to stick with 1.9. According to the Ansible docs,  `ansible_ssh_user` won't be actually removed until Ansible 2.2.

**Comment by gildegoma** [comment]
@jeffwidman thank you for reporting this. This issue (among other Ansible 2+ deprecated aspects) is actually tracked by #6570 (still in :construction: brainstorming). I'm thus closing this one to centralize the ideas in this single thread, but please feel free to add yours there :)
