### ISSUE TITLE
vagrant up multi-machine / regex doesn't work in 1.8.1

### ISSUE THREAD

**Issue by ageis** [mitchellh/vagrant#6928]
Let's say I have two machines defined called `app-staging` and `mon-staging` and they are in a group together. This scheme is from the [SecureDrop development environment](https://docs.securedrop.org/en/latest/development/getting_started.html), [Vagrantfile here](https://github.com/freedomofpress/securedrop/blob/develop/Vagrantfile).

I want to provision and bring them both up at the same time by running `vagrant up /staging$/` per your [multi-machine documentation](https://www.vagrantup.com/docs/multi-machine/). I get the following error:
```
The machine with the name '/staging$/' was not found configured for
this Vagrant environment.
```
This is a bug, as this absolutely worked in previous versions of Vagrant, but now it doesn't. I didn't find anything in the CHANGELOG that would indicate what changed or broke this.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/6828
