### ISSUE TITLE
When I run fabric command on virtual env ,can not get the IdentityFile vagrant 1.8.1 virtualbox 5.0.14

### ISSUE THREAD

**Issue by zsjohny** [mitchellh/vagrant#6929]
/Users/Johny/.vagrant/machines/default/virtualbox/private_key"'

```
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile "/Users/Johny/.vagrant/machines/default/virtualbox/private_key"
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardX11 yes
```

ls the file is exist and vagrant ssh also success

**Comment by sethvargo** [comment]
Hi @zsjohny 

Thank you for opening an issue. Unfortunately I do not understand the problem you are having.

- What is your expected behavior/output?
- What behavior/output are you getting?
- Can you please share your complete Vagrantfile as well as the command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html)?

Thanks! :smile:

**Comment by zsjohny** [comment]
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 8000, host: 8001
  config.vm.network :private_network, ip: "192.168.33.20"

  config.ssh.forward_x11 = true

  config.vm.synced_folder "salt/salt-master/", "/srv", type: "nfs"
  config.bindfs.bind_folder "/home/vagrant/workspace", "/home/vagrant/workspace", create_as_user: true
  config.vm.synced_folder "../youlun", "/home/vagrant/workspace/youlun", type: "nfs"
  config.bindfs.bind_folder "/home/vagrant/workspace/youlun", "/home/vagrant/workspace/youlun", create_as_user: true
  config.vm.synced_folder "../locale", "/home/vagrant/workspace/locale", type: "nfs"
  config.bindfs.bind_folder "/home/vagrant/workspace/locale", "/home/vagrant/workspace/locale", create_as_user: true
  config.vm.synced_folder "../devops", "/home/vagrant/workspace/devops", type: "nfs"
  config.bindfs.bind_folder "/home/vagrant/workspace/devops", "/home/vagrant/workspace/devops", create_as_user: true
  config.vm.synced_folder "../mobileui", "/home/vagrant/workspace/mobileui", type: "nfs"
  config.bindfs.bind_folder "/home/vagrant/workspace/mobileui", "/home/vagrant/workspace/mobileui", create_as_user: true
  config.vm.synced_folder "../ui", "/home/vagrant/workspace/ui", type: "nfs"
  config.bindfs.bind_folder "/home/vagrant/workspace/ui", "/home/vagrant/workspace/ui", perms: "u=rwx:g=rwx:o=rx" , create_as_user: true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096", "--cpus", "2"]
  end

  # Install python-git for allowing salt masterless to use external formulas(for example ntp-formula)
  config.vm.provision :shell, path: "gitpython.sh"

  # Provisioning with Salt
  config.vm.provision :salt do |salt|

    salt.install_type = "git"
    salt.install_args = "v2015.5.3"
    salt.minion_config = "salt/vagrant/minion"
    salt.bootstrap_options = "-D -P"
    salt.run_highstate = false
    salt.log_level = "debug"
    salt.verbose = true
    salt.colorize = true

  end

end

**Comment by zsjohny** [comment]
[localhost] local: vagrant status
[localhost] local: vagrant ssh-config | grep IdentityFile
[localhost] local: vagrant ssh-config | grep Port
[localhost] local: vagrant ssh-config | grep HostName
[INFO] Connecting to Vagrant with key="/Users/Andre/yl/devops/.vagrant/machines/default/virtualbox/private_key"
[127.0.0.1:2222] Executing task 'uname'
[INFO] >>> uname -a
[127.0.0.1:2222] run: uname -a
[INFO] Connected (version 2.0, client OpenSSH_6.6.1p1)
[ERROR] Failed command=uname -a error=[Errno 2] No such file or directory: '"/Users/Andre/yl/devops/.vagrant/machines/default/virtualbox/private_key"'

**Comment by sethvargo** [comment]
Hi @zsjohny 

I apologize, but I still do not understand your issue.

- What is your expected behavior/output?
- Can you please share your complete Vagrantfile as well as the command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html)?

I just ran your Vagrantfile with the salt and synced folders commented out (since I don't have those folders), and the VM is starting as expected:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20151117.0.0'. The latest is version '20160120.0.1'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: foo_default_1453912993867_77826
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8000 (guest) => 8001 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.10
    default: VirtualBox Version: 5.0
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/sethvargo/Desktop/foo
```

**Comment by zsjohny** [comment]
@sethvargo   vagrant up is normal .
but you can try :
```
from fabric.api import run

@task()
def host_type():
    run('uname -s')
```

**Comment by sethvargo** [comment]
Hi @zsjohny 

I am not familiar with Fabric, but if `vagrant up` and `vagrant ssh` are working as intended, this is not a bug in Vagrant. I would recommend opening an issue with Frabric or try posting on the Vagrant mailing list. Sorry!

**Comment by AlexAmyago** [comment]
I guess this is vagrant issue. I was faced with the same problem few days ago.
The problem is the path to IdentityFile is in double quoutes which was not true for Vagrant 1.7.4.
The same problems happens on pycharm IDE when I try ssh.
