### ISSUE TITLE
Tried upgrading to vagrant 1.8.1 and VirtualBox 5.13 - could not boot into my boxes

### ISSUE THREAD

**Issue by wwendorf** [mitchellh/vagrant#6931]
I tried all the suggestions I found online, and after hours of working on the problem was unable to resolve.  I wound up having to go back to VirtualBox 4.3 and Vagrant 1.7.1 to solve the problem.  I'm happy to provide more information, but the crux of the problem was that it was unable to connect via ssh no matter what I did.

Something MAJOR changed from 1.7.1 thru 1.8.1.  I tried every version with each version of VirtualBox until I got my work machines up and running again.

I would love to upgrade, but not at the risk of this happening again.

I am running on Windows 7.  I would really like to get curent, but can't get any of my machines to work if I do so.

Help!
Wade

**Comment by sethvargo** [comment]
Hi @wwendorf 

Could you please share your complete Vagrantfile?

**Comment by wwendorf** [comment]
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.ssh.insert_key = false
    config.vm.box = "ubuntu/trusty32"
	
    config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty32"
    
    config.vm.network :forwarded_port, host: 80, guest: 80, auto_correct: true
    config.vm.network :forwarded_port, host: 443, guest: 443, auto_correct: true
    config.vm.network :forwarded_port, host: 3306, guest: 3306, auto_correct: true
    config.vm.network :forwarded_port, host: 6379, guest: 6379, auto_correct: true
    config.vm.network :forwarded_port, host: 9200, guest: 9200, auto_correct: true

    config.vm.network :private_network, ip: "192.168.33.12"
  
    config.vm.provision :shell, :path => "install.sh"

    config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=777", "fmode=666"]

    # If true, then any SSH connections made will enable agent forwarding.
    # Default value: false
    # config.ssh.forward_agent = true

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"
    
    # uncomment and create the following directories in the c:\engage\ root folder if you need these locally as well
    config.vm.synced_folder "../html5-chat", "/agent", :mount_options => ["dmode=777", "fmode=666"]
    config.vm.synced_folder "../Config", "/config", :mount_options => ["dmode=777", "fmode=666"]
	config.vm.provider :virtualbox do |v|
		v.memory = 1024
	end
end
```

**Comment by sethvargo** [comment]
Hi @wwendorf 

I just tried your Vagrantfile, and, commenting out the provisioner, it worked fine for me on Vagrant 1.8.1. Can you please run the command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html) and share the output as a GitHub Gist?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
