### ISSUE TITLE
How to enforce copy of private_key file when using box with secure key?

### ISSUE THREAD

**Issue by COleo** [mitchellh/vagrant#6933]
Is there a way to enforce the copy of the private_key file of a box to the machne configuration within the VAGRANT_DOTFILE_PATH?

Using the ansible_local provider I use a static inventory file and reference to the private_key file with the ansible_ssh_private_key_file leyword, like `ansible_ssh_private_key_file=/vagrant/.vagrant/machines/node2/virtualbox/private_key`. (see also: https://github.com/mitchellh/vagrant/pull/5765 )

This works fine with newly generated keys due to an unsecure key in the imported box.

But using a box already including a secure key, `vagrant ssh-config` shows the private_key file in the local box cache is used and no private_key file is placed in the machine configuration within the VAGRANT_DOTFILE_PATH.

Copying the private_key file is done when using the "config.ssh.password" option. But how can I advice vagrant to copy the key file when using the private key auth method?

**Comment by sethvargo** [comment]
Hi @COleo 

Thank you for opening an issue. You can copy the private key onto the box by either putting it into the shared folder (which defaults to the same directory as the Vagrantfile) or by using the [file provisioner](https://www.vagrantup.com/docs/provisioning/file.html). Thanks! 😄
