### ISSUE TITLE
NFS mount log output does not detail individual folders, unlike VirtualBox

### ISSUE THREAD

**Issue by davidgiesberg** [mitchellh/vagrant#6934]
It would be useful if NFS mounts were enumerated on `vagrant up`, the same way they are for VirtualBox shared folders:

```
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> default: Mounting NFS shared folders...
==> default: Mounting shared folders...
    default: /mnt/data => /Users/david/src/galley/data
    default: /Users/david/src/galley => /Users/david/src/galley
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
```

(The above snippet shows folders being shared via NFS and VirtualBox)

**Comment by sebfek** [comment]
That worked!

I thought that is a bug that there no mount will be established only for /vagrant to the Vagrantfile folder. But how I see now it works, but not listed anymore, think that's a new bug introduced in Vagrant 1.8.1 or so

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for almost a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!

**Comment by medmek** [comment]
this is fairly important, for example in my case, I spent too much time thinking my folders wasn't mounted, in fact it was but vagrant did not tell
