### ISSUE TITLE
Changing directory causes connection closed

### ISSUE THREAD

**Issue by cbare** [mitchellh/vagrant#6936]
I don't know what bad juju has infected my "sample_data" directory but when I try to cd to it, `vagrant ssh` disconnects. I'm guessing this isn't strictly a Vagrant issue, but I'm filing it here in case others stumble across it.
```
vagrant@vagrant-ubuntu-trusty-64:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls -alph
total 32K
drwxr-xr-x  1 vagrant vagrant  442 Jan 27  2016 ./
drwxr-xr-x 23 root    root    4.0K Jan 26 06:39 ../
drwxr-xr-x  1 vagrant vagrant  170 Jan 26 20:30 build/
drwxr-xr-x  1 vagrant vagrant  510 Jan 26 18:10 .git/
-rw-r--r--  1 vagrant vagrant  266 Oct 15 20:11 .gitignore
-rw-r--r--  1 vagrant vagrant  957 Oct 15 20:11 LICENSE.rst
drwxr-xr-x  1 vagrant vagrant  578 Jan 26 20:04 mhealthx/
-rw-r--r--  1 vagrant vagrant 1.6K Jan 26 04:07 README.rst
drwxr-xr-x  1 vagrant vagrant  170 Jan 26 23:34 sample_data/
-rwxr-xr-x  1 vagrant vagrant 1.9K Jan 26 04:07 setup.py
-rwxr-xr-x  1 vagrant vagrant 7.6K Jan 26 21:12 setup.sh
drwxr-xr-x  1 vagrant vagrant  102 Jan 26 06:29 .vagrant/
-rw-r--r--  1 vagrant vagrant  115 Jan 26 06:29 Vagrantfile
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ cd mhealthx/
vagrant@vagrant-ubuntu-trusty-64:/vagrant/mhealthx$ cd ..
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ cd sample_data
Connection to 127.0.0.1 closed.
```

```
$ vagrant --version
Vagrant 1.7.4

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1605

$ vboxmanage --version
5.0.4r102546
```

The directory in question was created from the host OS while the vagrant virtual box was running. Doing `vagrant reload` and `vagrant ssh`ing back in seems to have solved the problem.

**Comment by sethvargo** [comment]
Hi @cbare 

Thank you for opening an issue. I just tried to reproduce this and cannot. Additionally, given the size of Vagrant's userbase, I would expect many other users to be +1ing this issue if they were experiencing it. As such, I believe this is an issue with your local environment. Perhaps you have something that is hooking into the `cd` call (like rvm) that is causing the machine to close, but without being on your system, it's very hard to debug.

The easiest way to confirm this is to create another user, install Vagrant and Virtualbox, and see if the issue persists on that user.

**Comment by cbare** [comment]
Hi @sethvargo, Thanks for looking into it. I can't repro either after restarting.
