### ISSUE TITLE
rsync-auto doesn't see new changes. No errors. Windows 10.

### ISSUE THREAD

**Issue by slavajacobson** [mitchellh/vagrant#6941]
When I run rsync-auto, it syncs the folder initially, but ignores any new changes. 

The host is Windows 10, Cygwin with rsync and openssh installed. Vagrant 1.8.1 and the guest machine is Ubuntu.

```
$ vagrant rsync-auto
==> default: Doing an initial rsync...
==> default: Rsyncing folder: /cygdrive/c/Users/Pixelcarve/Documents/rails-dev-box/ => /vagrant
==> default: Watching: C:/Users/Pixelcarve/Documents/rails-dev-box
```

I just tried using this plugin: https://github.com/smerrill/vagrant-gatling-rsync

And it works! Strange that the default vagrant rsync-auto doesn't work though.

**Comment by kitsunde** [comment]
There's 2 different people with their own computers in my team that both have rsync-auto working in my company on Windows 10 host and ubuntu guest.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
