### ISSUE TITLE
'reload' with Docker provider does not pull new image

### ISSUE THREAD

**Issue by chris-redekop** [mitchellh/vagrant#6942]
My team uses Vagrant to run a prebuilt Docker image.  We use the Docker provider and our  Vagrantfile refers to the image with the provider's **image** configuration parameter.  This works well.

When the image is updated, I expect a `vagrant reload` to stop the existing container and run the new image.  But `vagrant reload` just restarts the old container without pulling the new image.

I have tried this with

1. the old and new images tagged as **latest**,
2. the old image tagged as **X.1** and the new image tagged as **(X + 1).1**, and
3. with and without the Docker provider's **pull** parameter.

This looks like a bug to me, but maybe I misunderstand the intent of `vagrant reload` in this case.  Would you please let me know the expected/designed behaviour here and if there is anything I can do to fix/workaround the issue in my Vagrantfile?

I am using Vagrant 1.8.1, Windows 8.1, VirtualBox 5.0.14, and https://atlas.hashicorp.com/chris-redekop/boxes/boot2docker (with Docker 1.7.1).

**Comment by sethvargo** [comment]
This will be fixed in 1.8.3!
