### ISSUE TITLE
Using Vagrant with Bamboo fails with Vagrant is attempting to interface with the UI in a way that requires a TTY.

### ISSUE THREAD

**Issue by karnold** [mitchellh/vagrant#6943]
I have some tests scripts that require vagrant to provision AWS servers to run successfully.  When I run vagrant from my shell it runs just fine, but if i run it as an agent in bamboo it fails with the following error when it attempts to run the build:

```
28-Jan-2016 14:24:05	Vagrant failed to initialize at a very early stage:
28-Jan-2016 14:24:05	
28-Jan-2016 14:24:05	Vagrant is attempting to interface with the UI in a way that requires
28-Jan-2016 14:24:05	a TTY. Most actions in Vagrant that require a TTY have configuration
28-Jan-2016 14:24:05	switches to disable this requirement. Please do that or run Vagrant
28-Jan-2016 14:24:05	with TTY.
```

**Comment by sethvargo** [comment]
Looks like a duplicate of https://github.com/mitchellh/vagrant/issues/6194. Can you try the solutions there please?

**Comment by karnold** [comment]
Yup, looks like
```
export VAGRANT_DETECTED_OS=cygwin
```
Did the trick....thanks!
