### ISSUE TITLE
`vagrant provision` creating issues with virtualbox

### ISSUE THREAD

**Issue by tsturzl** [mitchellh/vagrant#6944]
When I issue `vagrant provision`, in this case my box was running, it would return `VM not created moving on`. Then if I issue `halt`, `up`, `ssh`, or `destroy` it will output the same error. When I look at the status, it says not created. When I look in virtualbox, the box still exists and is running. This is really irritating because I just pushed an update to our ansible provision for the box, and now everyone is having to completely reset their dev environments. We develop in OS X and Ubuntu environments.

I'm uncertain if I'm just doing something wrong. Someone mentioned to me that `vagrant provision` is the same as `vagrant up --provision` and told me that's likely why its not working. But then the vagrant environment becomes corrupt, it seems to not recognize the virtualbox. It seems like this must be a bug, as I'd assume if I wasn't supposed to run `vagrant provision` on a running box that vagrant would tell me such instead of breaking.

**Comment by sethvargo** [comment]
Hi @tsturzl 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. Unfortunately I'm having a difficult time understanding the order of operations you took to arrive in this bad state. Could you please:

1. Share your complete Vagrantfile
2. Host OS
3. Guest OS
4. Vagrant version
5. Commands you took to get here

It would really help us in reproducing this issue. Thanks!

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄
