### ISSUE TITLE
Can't add logical drive different from C as shared folder since Vagrant 1.8 upgrade

### ISSUE THREAD

**Issue by schwipps** [mitchellh/vagrant#6947]
After upgrading Vagrant to 1.8 on my Windows 7 host, I tried to start my Vagrant box, and got this error message :

> There was an error while executing VBoxManage, a CLI used by Vagrant
>     for controlling VirtualBox. The command and stderr is shown below.
> Command: ["sharedfolder", "add", "4891......62", "--name", "bY33sdqfjGvO2", "--hostpath", "D:\"]
> 
> Stderr: VBoxManage.exe: error: Shared folder path 'D:"' is not absolute
> VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component SharedFolderWrap, interface ISharedFolder, callee IUnknown
> VBoxManage.exe: error: Context: "CreateSharedFolder(Bstr(name).raw(), Bstr(hostpath).raw(), fWritable, fAutoMount)" at line 1020 of file VBoxManageMisc.cpp

I know this has something to do with the way I declare my drive, but I couldn't find the right syntax.
I've tried many combinations with slashes, backslashes, doubled or not, before or after the letter, colons

What's the correct way to declare another drive ?

Thanks !

**Comment by schwipps** [comment]
Am I the only one to face this issue ? Or may be should I connect my disk an other way ?

**Comment by sethvargo** [comment]
Hi @schwipps 

Thank you for opening an issue. I think you need to use `\d` notation and not `D:\` notation. The best (and fastest) way to get these types of questions answered is on the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). Thanks and sorry for the delay! 😄
