### ISSUE TITLE
Vagrant 1.8.1 can't run VMware on Ubuntu

### ISSUE THREAD

**Issue by pascalwacker** [mitchellh/vagrant#6953]
I have purchased the VMware Workstation plugin a while back. It is activated, and I have worked with it using `Vagrant 1.7.4` without any issues. After an update to `Vagrant 1.8.1`, I can't start any machine any more. Host is a Ubuntu 15.10 64bit.

    pascal@Lenovo2013:~/VM/foo$ vagrant up
    An unexpected error occurred while loading the Vagrant VMware
    provider. Please contact support with the following
    error code: '7'.
    Vagrant failed to initialize at a very early stage:
    
    The plugins failed to load properly. The error message given is
    shown below.
    
    exit
    pascal@Lenovo2013:~/VM/foo$

**Comment by sethvargo** [comment]
Hi @pascalwacker 

Thank you for opening an issue, and I am sorry you are having problems with the Vagrant VMware plugin. Could you please run the following:

```
$ vagrant plugin uninstall vagrant-vmware-workstation
$ vagrant plugin install vagrant-vmware-workstation
```

Thanks!

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. The instructions above helped many other users resolve the issue. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
