### ISSUE TITLE
Vagrant 1.8.1 have issue to run on new VertualBox Version 5.0.14 r105127 and shoe error!

### ISSUE THREAD

**Issue by IrinaMax** [mitchellh/vagrant#6954]
I try to install Vargant today, but ufter i run `vargant up` in terminal it come as error...
`
irinamacbookpro:myvagrant irinamahmudjanova$ vagrant -v
Vagrant 1.8.1
irinamacbookpro:myvagrant irinamahmudjanova$ ls
Vagrantfile		mooc-setup-master	mooc-setup-master.zip
irinamacbookpro:myvagrant irinamahmudjanova$ vagrant up
Bringing machine 'sparkvm' up with 'virtualbox' provider...
==> sparkvm: Importing base box 'sparkmooc/base2'...
==> sparkvm: Matching MAC address for NAT networking...
==> sparkvm: Checking if box 'sparkmooc/base2' is up to date...
==> sparkvm: Setting the name of the VM: sparkvm
==> sparkvm: Clearing any previously set network interfaces...
==> sparkvm: Preparing network interfaces based on configuration...
    sparkvm: Adapter 1: nat
==> sparkvm: Forwarding ports...
    sparkvm: 8001 (guest) => 8001 (host) (adapter 1)
    sparkvm: 4040 (guest) => 4040 (host) (adapter 1)
    sparkvm: 22 (guest) => 2222 (host) (adapter 1)
==> sparkvm: Booting VM...
==> sparkvm: Waiting for machine to boot. This may take a few minutes...
**The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant _**issue.**_**  
`
Its very frustrating and I try to destroy and install VB again and even version but hopeless :(  actually extention pack not working on the VB too :(
Anybody can help me??

**Comment by pbojinov** [comment]
I came across the same scenario with Vagrant 1.8.1 and VirtualBox 5.0.14 r105127. It hangs when trying to do a `vagrant up`
