### ISSUE TITLE
Vagrant: The guest operating system of the machine could not be detected!

### ISSUE THREAD

**Issue by umamallika** [mitchellh/vagrant#6956]
While running vagrant using vagrant-aws i am getting the error, Vagrant: The guest operating system of the machine could not be detected!.Vagrant requires this knowledge to perform specific tasks such
as mounting shared folders and configuring networks. Please add
the ability to detect this guest operating system to Vagrant
by creating a plugin or reporting a bug.

i deleted the host in .vagrant folder and i again tried. It worked. May i know the reason for this issue,
it occurs intermitantly

**Comment by sethvargo** [comment]
Hi @umamallika 

Are you able to reproduce this bug without the vagrant-aws plugin? If so, can you please share your complete Vagrantfile and the output of the command in debug mode? Thanks! :smile:

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity and because we are only able to support vagrant core on this issue tracker. If this is still occurring, please open a _new_ issue on the vagrant-aws plugin or try to reproduce the issue with virtualbox.
