### ISSUE TITLE
Many messages « Command not in installer, restoring original environment... » with /usr/local/bin/VBoxManage subprocess

### ISSUE THREAD

**Issue by harobed** [mitchellh/vagrant#6957]
Hi,

I've many many message like this : 

```
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "a349298a-1f9a-42af-8606-40b491a8409b", "--machinereadable"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
```
More log : https://gist.github.com/harobed/a6218e932cf5e56d4442

When I execute manually :

```
$ /usr/local/bin/VBoxManage showvminfo a349298a-1f9a-42af-8606-40b491a8409b --machinereadable
name="openshift-ansible_master_1454341130777_40230"
groups="/"
ostype="Red Hat (64-bit)"
UUID="a349298a-1f9a-42af-8606-40b491a8409b"
...
```

Then I don't understand Vagrant message !

It's a bug ?

**Comment by harobed** [comment]
Ok, it's not a bug, I've looked in a source code.

**Comment by isaiahvita** [comment]
hi, how did you fix this?

**Comment by jiv-e** [comment]
I have the same problem. Any ideas how to fix this?

**Comment by woss** [comment]
i've been seeing this message for long time, most of the time is super irritating. I still don't get how to get rid of it, usually i reinstall vagrant and vbox.

**Comment by jasperf** [comment]
I do get this message every now and then too. And it seems to happen on particular networks like at my favorite coffee place. At home the vagrant boxes boot just fine. So I tend to think it is router or network related.

```
GuestAdditionsVersion="5.0.26 r108824"
GuestAdditionsFacility_VirtualBox Base Driver=50,1478421153250
GuestAdditionsFacility_VirtualBox System Service=50,1478421155054
GuestAdditionsFacility_Seamless Mode=0,1481702264707
GuestAdditionsFacility_Graphics Mode=0,1481702264707
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "a1ca9c55-44f2-43f0-920f-038be1806592", "--machinereadable"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="ianua.dev"
groups="/"
ostype="Ubuntu (64-bit)"
UUID="a1ca9c55-44f2-43f0-920f-038be1806592"
CfgFile="/Users/jasperfrumau/VirtualBox VMs/ianua.dev/ianua.dev.vbox"
```

**Comment by jon-rtr** [comment]
This kept popping up for me when I enabled INFO level logging, and I wanted to dig into why "it's not a bug". The code states:

    # If we're in an installer on Mac and we're executing a command
    # in the installer context, then force DYLD_LIBRARY_PATH to look
    # at our libs first.

otherwise

    # If the command that is being run is not inside the installer, reset
    # the original environment - this is required for shelling out to
    # other subprocesses that depend on environment variables (like Ruby
    # and $GEM_PATH for example)

    @logger.info("Command not in installer, restoring original environment...")
    jailbreak(process.environment)

so it's nothing to worry about. Everything is operating as expected.

https://github.com/hashicorp/vagrant/blob/7b8ab871dc9e4826bfcf5c738190bf6902510b31/lib/vagrant/util/subprocess.rb#L94-L129
