### ISSUE TITLE
Vmware Fusion

### ISSUE THREAD

**Issue by jmakanjuola** [mitchellh/vagrant#6959]
The Vagrant VMware provider requires a valid license
to run. The license provided is invalid. Please make sure you
downloaded the proper license. If you believe you're seeing
this message in error, please contact support.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

Here is my Vagrantfile:

```ruby
# Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "hasicorp/precise64"
  config.vm.box_url = "http://hashicorp-files.hashicorp.com/precise64_vmware.box"
```

**Comment by sethvargo** [comment]
Hi @jmakanjuola 

The Vagrant VMware provider is a commercial product that requires a license. You can purchase a license here: https://www.vagrantup.com/vmware/#buy-now. FAQ can be found here: https://www.vagrantup.com/vmware/#faq. Instructions here: https://www.vagrantup.com/docs/vmware/installation.html

**Comment by jmakanjuola** [comment]
Thanks! My issue has be resolved
