### ISSUE TITLE
Inconsistent usage of string vs int for configuration version

### ISSUE THREAD

**Issue by edmorley** [mitchellh/vagrant#6961]
The docs use both an int and a string for the configuration version:
https://www.vagrantup.com/docs/vagrantfile/version.html

ie:
`Vagrant.configure(2) do |config|`
  vs
`Vagrant.configure("2") do |config|`

The output from `vagrant init` uses an int.

Which is the canonical form? (I'm happy to open a PR to make everything consistent)
I'm guessing it's a string, given the cast here?
https://github.com/mitchellh/vagrant/blob/95ffde0938b53f2fe8cc31a561b047eea9e3b7c4/lib/vagrant/config.rb#L38

**Comment by sethvargo** [comment]
@edmorley they actually both work, but I'll run through everything to make it consistent. Thanks for reporting!

**Comment by edmorley** [comment]
Many thanks :-)
