### ISSUE TITLE
Incorrect option with `vagrant box` resulted in version info not usage text

### ISSUE THREAD

**Issue by edmorley** [mitchellh/vagrant#6964]
**STR:**
1. Run a `vagrant box update`, and so now have an old version you need to delete.
2. Run `vagrant box remove ubuntu/trusty32 --version 20160120.0.1` (because you use the feature infrequently so can never remember the correct version syntax).

**Expected:**
```bash
Unknown option '--version'

Usage: vagrant box remove <name>

Options:

    -f, --force                      Destroy without confirmation.
        --provider PROVIDER          The specific provider type for the box to remove
        --box-version VERSION        The specific version of the box to remove
        --all                        Remove all available versions of the box
    -h, --help                       Print this help
```

**Actual:**

```bash
[~/src/treeherder]$ vagrant box remove ubuntu/trusty32 --version 20160120.0.1
Vagrant 1.8.1
```

**Comment by sethvargo** [comment]
Hi @edmorley 

Unfortunately `--version` and `--help` are special flags that we catch very early in the cycle to prevent Vagrant from completely loading before giving helpful output. I understand this might be frustrating, but changing it would require loading the entire vagrant environment for version output, which can take up to 5s on windows boxes, so we've opted to optimize that UX. Thank you for reporting nonetheless, but I think we have to choose the lesser of two evils here :smile:

**Comment by edmorley** [comment]
I agree it's good to not load Vagrant in its entirety when someone uses `vagrant --version`, however the argument parser should not catch it when other options are provided IMO. This is doable without loading all of vagrant :-)

**Comment by edmorley** [comment]
For example the conditional here could also check that the number of arguments was one:
https://github.com/mitchellh/vagrant/blob/217b0c9eaa378e2beba09ab9e9f3322ff0799dcc/bin/vagrant#L17-L21
