### ISSUE TITLE
Handle HTTP 401 + authorization headers

### ISSUE THREAD

**Issue by marcofranssen** [mitchellh/vagrant#6967]
Hi,

Currently I'm using following [plugin](https://github.com/igorbonadio/vagrant-http-basic-authentication) to handle authentication to my HTTP Basic protected vagrant cloud.

The downside of this plugin is that it asks you for username and password on every single vagrant command. I think it would be a great feature if vagrant can deal with a 401 response in order to ask for username and password only when it is trying to access the vagrant cloud.

It will be a huge improvement to the user experience.

A second addition would be to have the credentials cached in the currently opened shell, so you only have to fill out the credentials once for every shell.

Is there already another plugin that does this? Can this be added to vagrant?

**Comment by sethvargo** [comment]
Hi @marcofranssen 

The `vagrant box add` command supports basic auth, so I'm not sure why your plugin is needed. Additionally, if you are using Atlas (formerly Vagrant cloud), you can run `vagrant login` and the credentials will be cached.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this issue due to inactivity. If this is still occurring, please open a _new_ issue and follow the accompanying template so we can reproduce and fix this as quickly as possible. Thanks!
