### ISSUE TITLE
The synced folder type 'nfs' is reporting as unusable... with Linux Host / Vagrant 1.8.1

### ISSUE THREAD

**Issue by erSitzt** [mitchellh/vagrant#6968]
Hi,

im getting this error:

```
The synced folder type 'nfs' is reporting as unusable for
your current setup. Please verify you have all the proper
prerequisites for using this shared folder type and try again.
```

Looking at the debug output of `vagrant up` im not sure what the problem is...
The vm ist a host-vm for the docker provider

Debug and Vagrantfile:

https://gist.github.com/erSitzt/783e09435da76c075a7c
https://gist.github.com/erSitzt/cd7dccd948a228498e75

OS is Linux Mint 17.3 ( Ubuntu 14.04 based )
Vagrant 1.8.1
Virtualbox 5.0.4_LinuxMintr102546

**Comment by sethvargo** [comment]
Hi @erSitzt 

In order to use the NFS provider, both the host (your machine) and the guest (the vagrant box) must support NFS. Looking at the debug log, the guest you've chosen does not appear to support NFS. I'm also not sure if Linux Mint supports NFS. Does that make sense?

**Comment by erSitzt** [comment]
Linux Mint is basically just an Ubuntu 14.04... nfs-kernel-server and nfs-common packages are installed.
The boot2docker image that is used as a guest should support nfs mounts...

It would help if vagrant would log the cause it thinks nfs is not usable...
I will test mounting nfs manually from the guest and see what happens.

**Comment by erSitzt** [comment]
After some testing i can say that the error occurs before the boot2docker host-vm is spun up.
It gets registered in virtualbox an then the error is logged.

So it should be something Vagrant is checking on the host itself.

**Comment by erSitzt** [comment]
I've got it working now.

I need these options:
```
  config.nfs.functional = true
  config.vm.synced_folder "/linuxFreigaben", "/linuxFreigaben", type: "nfs", nfs_version: 4, nfs_udp: false
```
and i needed to change https://github.com/mitchellh/vagrant/blob/master/plugins/guests/linux/cap/mount_nfs.rb#L29 from mount to mount.nfs

NFSv3 does not seem to work.

**Comment by erSitzt** [comment]
Nevermind... i tried it

#6977
