### ISSUE TITLE
'selinux' not supported in vagrant VM (Centos / Redhat 7.x)

### ISSUE THREAD

**Issue by jeff1evesque** [mitchellh/vagrant#6970]
I have a centos 7.2 instance, and attempted to change the [system context](https://wiki.centos.org/HowTos/SELinux#head-0f6390ddacfab39ee973ed8018a32212c2a02199) on the mounted `vagrant/` directory, in order to allow `httpd` to serve php based pages.  The motivation for this, is because I have repointed the document root, via `/etc/httpd/conf/httpd.conf` to `/vagrant/webroot`, from the default `/var/www/html`.

**Note:** this issue is predicated on [drupal-demonstration](https://github.com/jeff1evesque/drupal-demonstration), with selinux manually enabled, since the default vagrant box implemented, has it disabled.

Before proceeding I reviewed the system context of my local project root:

```bash
[root@localhost /]# ls -lZ /vagrant
drwxrwxrwx. vagrant vagrant system_u:object_r:vmblock_t:s0   log
drwxrwxrwx. vagrant vagrant system_u:object_r:vmblock_t:s0   puppet
drwxrwxrwx. vagrant vagrant system_u:object_r:vmblock_t:s0   src
-rwxrwxrwx. vagrant vagrant system_u:object_r:vmblock_t:s0   vagrant
-rwxrwxrwx. vagrant vagrant system_u:object_r:vmblock_t:s0   Vagrantfile
drwxrwxrwx. vagrant vagrant system_u:object_r:vmblock_t:s0   webroot
```

So, I attempted to recursively change the system context on the `vagrant/` directory:

```bash
[root@localhost /]# chcon -R -t httpd_sys_content_t vagrant
chcon: failed to change context of ‘COMMIT_EDITMSG’ to ‘system_u:object_r:httpd_sys_content_t:s0’: Operation not supported
chcon: failed to change context of ‘config’ to ‘system_u:object_r:httpd_sys_content_t:s0’: Operation not supported
chcon: failed to change context of ‘description’ to ‘system_u:object_r:httpd_sys_content_t:s0’: Operation not supported
...
```

**Note:** we terminated the above `chcon` command, while it was running, because there are a lot of files nested in the `vagrant/` directory.

Since, I am unable to change the system context on the `vagrant/` directory, if I delete, or move `/etc/httpd/conf.d/welcome.conf`, I get the following `403` error:

![403](https://cloud.githubusercontent.com/assets/2907085/12793104/dfe65c7c-ca7c-11e5-804e-052da7ae4004.PNG)

**Note:** though, this was attempted on Centos 7.x, it probably applies to Redhat 7.x.

**Comment by jeff1evesque** [comment]
Is this solution possible within vagrant, or should I try to customize selinux, such that, any mounted directory defaults to the system context of `httpd_sys_content_t`.  Once I get that working, then try to be more specific, such that only the `vagrant/` directory defaults to the `httpd_sys_content_t` context?

**Comment by jeff1evesque** [comment]
Perhaps the following needs to be incorporated either within vagrant, or manually provisioned via puppet (or equivalent):

```bash
$ mount /dev/sda2 /vagrant/ -o defcontext=system_u:object_r:httpd_sys_content_t:s0"
```

**Note:** the above command was attained from Redhat 7 [documentation](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/SELinux_Users_and_Administrators_Guide/sect-Security-Enhanced_Linux-Working_with_SELinux-Mounting_File_Systems.html) on *Mounting File Systems*.

**Comment by jeff1evesque** [comment]
We may be able to implement the vagrant [`mount_options`](https://www.vagrantup.com/docs/synced-folders/basic_usage.html#mount_options), with respect to the above Redhat / Centos `mount` command:


>jeffreylevesque: anyone familiar with `mount server:/export /vagrant -o context="system_u:object_r:httpd_sys_content_t:s0"`?
jeffreylevesque: does the `server:/export` argument follow a certain convention?

>billings: jeffreylevesque: that's an NFS mountpoint
billings: jeffreylevesque: most liekly you'll use something like this
billings: https://www.vagrantup.com/docs/synced-folders/basic_usage.html#mount_options

>...

>jeffreylevesque: so, `mount /vagrant -o context="system_u:object_r:httpd_sys_content_t:s0"` to be incorporated into vagrant `mount_options`?

>billings: no
billings: mount -t vboxsf -o context="system_u:object_r:httpd_sys_content_t:s0" sharename /path/to/mountpoint
billings: and, the mount_options would just be context="system_u:object_r:httpd_sys_content_t:s0"

>jeffreylevesque: is `sharename` some arbitrary name I want to create?  And, so I can ignore most of the `mount` command for the `mount_options` you have outlined?

>billings: I have no idea
billings: I've never used vagrant
billings: you need to look at the documentation and make sure the mount options include the context option.

**Comment by jeff1evesque** [comment]
We will try the following syntax, within our `Vagrantfile`:

```
...
  config.vm.synced_folder './', '/vagrant'',
    owner: 'vagrant',
    group: 'www-data',
    mount_options: ['dmode=775,fmode=664']
...
```

**Comment by jeff1evesque** [comment]
We tested the following within our `Vagrantfile`, which simply sets permission, and ownership (doesn't fix overall apache not rendering drupal webpage), and completes without error:

```
...
  ## set general project ownership, and permission
  config.vm.synced_folder './', '/vagrant',
    owner: 'nccoe_web',
    group: 'nccoe_web',
    mount_options: ['dmode=755', 'fmode=664']

  ## set permission for drupal 'settings*.php'
  config.vm.synced_folder './src/default', '/vagrant/webroot/sites/default',
    owner: 'nccoe_web',
    group: 'apache',
    mount_options: ['dmode=775', 'fmode=444']

  ## allow 'sites/default/files/' to be writeable for drupal install
  config.vm.synced_folder './webroot/sites/default/files', '/vagrant/webroot/sites/default/files',
    owner: 'nccoe_web',
    group: 'apache',
    mount_options: ['dmode=775', 'fmode=775']
...
```

However, if we adjust the above to the following:

```
...
  ## set general project ownership, and permission
  config.vm.synced_folder './', '/vagrant',
    owner: 'nccoe_web',
    group: 'nccoe_web',
    mount_options: ['dmode=755', 'fmode=664']

  ## set general project ownership, and permission
  config.vm.synced_folder './webroot', '/vagrant/webroot',
    owner: 'nccoe_web',
    group: 'apache',
    mount_options: ['dmode=755', 'fmode=664','context=system_u:object_r:httpd_sys_content_t:s0']

  ## set permission for drupal 'settings*.php'
  config.vm.synced_folder './src/default', '/vagrant/webroot/sites/default',
    owner: 'nccoe_web',
    group: 'apache',
    mount_options: ['dmode=775', 'fmode=444']

  ## allow 'sites/default/files/' to be writeable for drupal install
  config.vm.synced_folder './webroot/sites/default/files', '/vagrant/webroot/sites/default/files',
    owner: 'nccoe_web',
    group: 'apache',
    mount_options: ['dmode=775', 'fmode=775']
...
```

we get the following traceback, upon `vagrant reload`:

```bash
$ vagrant reload
==> default: vagrant-r10k: Building the r10k module path with puppet provisioner module_path "puppet/environment/development/modules". (if module_path is an array, first element is used)
==> default: vagrant-r10k: Beginning r10k deploy of puppet modules into /path/to/drupal-demonstration/puppet/environment/development/modules using /path/to/drupal-demonstration/puppet/environment/development/Puppetfile
==> default: vagrant-r10k: Deploy finished
==> default: Attempting graceful shutdown of VM...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
vagrant@127.0.0.1's password:myVagrantUserPassword
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
vagrant@127.0.0.1's password:myVagrantUserPassword
==> default: Clearing any previously set forwarded ports...
==> default: vagrant-r10k: Building the r10k module path with puppet provisioner module_path "puppet/environment/development/modules". (if module_path is an array, first element is used)
==> default: vagrant-r10k: Beginning r10k deploy of puppet modules into /path/to/drupal-demonstration/puppet/environment/development/modules using /path/to/drupal-demonstration/puppet/environment/development/Puppetfile
==> default: vagrant-r10k: Deploy finished
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 => 8333 (adapter 1)
    default: 443 => 8334 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: password
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
vagrant@127.0.0.1's password:
    default: Warning: Connection timeout. Retrying...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
vagrant@127.0.0.1's password:myVagrantUserPassword
==> default: Machine booted and ready!
GuestAdditions 5.0.12 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /path/to/drupal-demonstration
    default: /vagrant/webroot => /path/to/drupal-demonstration/webroot
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group apache | cut -d: -f3`,dmode=755,fmode=664,context=system_u:object_r:httpd_sys_content_t:s0 vagrant_webroot /vagrant/webroot
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g apache`,dmode=755,fmode=664,context=system_u:object_r:httpd_sys_content_t:s0 vagrant_webroot /vagrant/webroot

The error output from the last command was:

```

**Comment by jeff1evesque** [comment]
I checked to see if guest additions are properly installed:

```bash
$ vagrant ssh
==> default: The machine you're attempting to SSH into is configured to use
==> default: password-based authentication. Vagrant can't script entering the
==> default: password for you. If you're prompted for a password, please enter
==> default: the same password you have configured in the Vagrantfile.
Enter passphrase for key '/path/to/.ssh/id_rsa':
vagrant@127.0.0.1's password:
Last login: Thu Feb  4 13:53:20 2016 from gateway
[vagrant@localhost ~]$ lsmod | grep -i vbox
vboxsf                 39741  1
vboxvideo              12658  0
vboxguest             297222  2 vboxsf
drm                   349210  2 vboxvideo
```

**Comment by jeff1evesque** [comment]
I forgot to mention (i fixed the main issue body), that I have repointed the document root, via `httpd.conf` as `/vagrant/webroot`.  Reestablishing `/var/www/html` as the document root, and adding a trivial `index.html`, with just `<div>hello world</div>` prints out to the page.  I may consider symlinking from `/vagrant/webroot` into `/var/www/html`, if no other solution is present.

**Comment by jeff1evesque** [comment]
We may consider using the [audit2allow](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Security-Enhanced_Linux/sect-Security-Enhanced_Linux-Fixing_Problems-Allowing_Access_audit2allow.html) module, to create custom policies.

We will attempt to allow [apache access](https://github.com/cronkeep/cronkeep/wiki/Developer-Guide#allow-apache-access-to-vmblock_t-through-a-custom-policy-module) to `vmblock_t` though a custom policy:

- access https://localhost:8334/, so denied calls would get logged to `/var/log/audit/audit.log`
- see the `audit.log` in human-readable format:

>`$ audit2allow -w -a`

- to see what rules would allow access:

>`audit2allow -a`

- create policy based on the above generated rules, with respect to `vmblock_t`:

>`$ grep vmblock_t /var/log/audit/audit.log | audit2allow -M httpd_vboxsf`

Now, a *Type Enforcement* file, `httpd_vboxsf.te`, and a policy package file, `httpd_vboxsf.pp`, have been generated in the current working directory.  So, we proceed to install the new policy module as follows:

>`$ semodule -i httpd_vboxsf.pp`

**Comment by jeff1evesque** [comment]
We performed the above, and received a `Server Error`:

![server-error](https://cloud.githubusercontent.com/assets/2907085/12848079/9c305478-cbe5-11e5-80be-5a964a004838.PNG)

**Comment by jeff1evesque** [comment]
When I run `sudo audit2allow -w`, one of the many entries include:

```bash
type=AVC msg=audit(**********.***:****): avc:  denied  { getattr } for  pid=****
 comm="httpd" path="/vagrant/webroot/index.php" dev="vboxsf" ino=** scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:vmblock_t:s0 tclass=file
        Was caused by:
                Unknown - would be allowed by active policy
                Possible mismatch between this policy and the one under which the audit message was generated.

                Possible mismatch between current in-memory boolean settings vs. permanent ones.
```

**Comment by jeff1evesque** [comment]
We attempted to create our own *Type Enforcement rule*:

```bash
[vagrant@localhost webroot]$ sudo audit2allow -a


#============= httpd_t ==============
allow httpd_t vmblock_t:file getattr;

#============= unconfined_t ==============
allow unconfined_t init_t:service { enable disable };
[vagrant@localhost webroot]$ sudo audit2allow -a -M httpd_t
******************** IMPORTANT ***********************
To make this policy package active, execute:

semodule -i httpd_t.pp

[vagrant@localhost webroot]$ sudo semodule -i httpd_t.pp
[vagrant@localhost webroot]$ sudo audit2allow -a


#============= httpd_t ==============
allow httpd_t vmblock_t:file read;

#!!!! This avc is allowed in the current policy
allow httpd_t vmblock_t:file getattr;

#============= unconfined_t ==============

#!!!! This avc is allowed in the current policy
allow unconfined_t init_t:service { enable disable };
```

**Comment by jeff1evesque** [comment]
We will disable the selinux policy, then remove the corresponding file:

```bash
[vagrant@localhost webroot]$ semodule -d httpd_t
[vagrant@localhost webroot]$ rm httpd_t.pp httpd_t.te
```

Then, we'll set selinux to permissive mode:

```bash
[vagrant@localhost webroot]$ sudo setenforce permissive
[vagrant@localhost webroot]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28
```

This will allow us to let the httpd stack run through its motions, before we create the policy from the logged AVCs.

**Comment by jeff1evesque** [comment]
We created our policy, loaded it, then enabled it:

```bash
[vagrant@localhost webroot]$ sudo grep httpd_t /var/log/audit/audit.log | audit2allow -M httpd_t
[vagrant@localhost webroot]$ sudo semodule -i httpd_t.pp
[vagrant@localhost webroot]$ sudo semodule -e httpd_t
```

The big trivial take-away, remember to enable the policy rule created via `sudo semodule -e httpd_t`

**Comment by jeff1evesque** [comment]
We'll end up creating puppet scripts to run the selinux file, containing our custom policy rule.

**Comment by sethvargo** [comment]
Hi @jeff1evesque 

Thank you for opening an issue. I read through the thread, and it sounds like you were able to get things enabled, and it looks like the issue was related to selinux and httpd, not Vagrant. Is that correct?

**Comment by jeff1evesque** [comment]
Hi @sethvargo,

Yes sir.  I wasn't sure initially, where this issue would lead me.  Thank you!

**Comment by zawnaningtun-frobom** [comment]
Finally, How to solve this error.I also have 403 forbidden error .
