### ISSUE TITLE
vagrant add doesn't 

### ISSUE THREAD

**Issue by jbeaudoin11** [mitchellh/vagrant#6973]
I'm new to vagrant and wanted to give it a try for a project with my friend.

So I installed it on my Windows machine and everything was super easy. When i tried on my friend's laptop we have an error :

	C:\Users\Jérémy>vagrant box add ubuntu/trusty64
	==> box: Loading metadata for box 'ubuntu/trusty64'
		box: URL: https://atlas.hashicorp.com/ubuntu/trusty64
	The box 'ubuntu/trusty64' could not be found or
	could not be accessed in the remote catalog. If this is a private
	box on HashiCorp's Atlas, please verify you're logged in via
	`vagrant login`. Also, please double-check the name. The expanded
	URL and error message are shown below:

	URL: https://atlas.hashicorp.com/ubuntu/trusty64
	Error: Failed writing body (0 != 4272)

We tried every "fix" we found on the subject... and nothing is working
We tried to manually add the box (`vagrant box add b.box`) and it doesn't work either.. There is an error talking about unable to unpackge..

So I'm here to have some help !
thanks

**Comment by sethvargo** [comment]
Hi @jbeaudoin11 

Thank you for opening an issue. This is almost certainly due to the fact that your friend has special characters in his username (Jérémy). Ruby, the underlying language to Vagrant, does not handle special characters very well.

**Comment by jbeaudoin11** [comment]
So what do we do now ?

Is there a way to install it in the Public folder of Users ?

**Comment by sethvargo** [comment]
Hi @jbeaudoin11 

You can try setting the `VAGRANT_HOME` environment variable to a path that does not have special characters to see if that fixes the issue.

**Comment by jbeaudoin11** [comment]
Can't do it now. Will give you an update later.
There is no `VAGRANT_HOME` variable on my pc so if it's the case do i need to create it ?

**Comment by sethvargo** [comment]
Hi @jbeaudoin11 

It's an environment variable - you set it via CWD or Powershell

**Comment by jbeaudoin11** [comment]
Alright everything is working fine now. We just had a problem with ssh cmd doesn't exist but i installed Openssh and added it in PATH

So cool and thanks !
