### ISSUE TITLE
Call a custom capabilities conditionally

### ISSUE THREAD

**Issue by blackms** [mitchellh/vagrant#6982]
Hello, 
I'm trying to call a custom defined capabilities (do disable requiretty on centos), only if the guest is a redhat or centos, but I didn't found any documentation about it.

Can someone point me in the right direction?

Thanks

**Comment by sethvargo** [comment]
Hi @blackms 

You can check if the capability is defined first using `capability?` and then execute with `capability!`. See here: https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/chef/installer.rb

**Comment by blackms** [comment]
HI @sethvargo,
thanks for the reply, what I would like to do is call a capability in case of OS detected is CentOS.
Who is that call rsync_install capability? I need to call a cap before that one. Is there a way?
