### ISSUE TITLE
validate Ruby

### ISSUE THREAD

**Issue by AlennGK** [mitchellh/vagrant#6986]
Hello I just bought new SSD | moved Windows X to it and after that all worked fine.
Next step that I've done was change of the TEMP file to my HDD drive.
I am using cmder | portable git | composer | all PATH set
After the ruby & gem instalation some of the errors changed but stil it is not working.

When I run C:\1_Programy\Vagrant\embedded\msys.bat it's working, so what it the problem? local instalation or /o\

```
 ▲▼▲ > vagrant
C:/1_Programy/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:23:in `build': D:/06_DoźasnŘ/Temp/vagrant20160205-80-arlf3j2 not found (Bundler::GemfileNotFound)
        from C:/1_Programy/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler.rb:155:in `definition'
        from C:/1_Programy/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler.rb:123:in `setup'
        from C:/1_Programy/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:71:in `<main>'
```

**Comment by sethvargo** [comment]
Hi @AlennGK 

The error is almost certainly related to the fact that you have special characters in your path "06_DoźasnŘ". Ruby, the underlying language Vagrant is written in, does not handle special characters quite so well and produces very obtuse errors.

Additionally, the Vagrant installer links against things absolute on the filesystem, so you cannot just "move" things into a new location unfortunately. I would recommend completely removing Vagrant and then re-installing from the official installers on www.vagrantup.com/downloads.html.

**Comment by AlennGK** [comment]
/o\ my new temp dir thx =)
