### ISSUE TITLE
eventmachine.so not found after upgrade Vagrant 1.7.4 -> 1.8.1

### ISSUE THREAD

**Issue by rct** [mitchellh/vagrant#6987]
After upgrading Vagrant from 1.7.4 to 1.8.1 on Windows 7/64 bit. trying to run `vagrant` fails due to eventmachine.so 

Notes:
* Uninstalling and  reinstalling, or repair install doesn't fix the problem.
* Had to delete `~/.vagrant.d`  (Windows path  `C:\Users\me\.vagrant.d`
* Any invocation of `vagrant` failed, using either Cygwin Terminal (MinTTY) or CMD.EXE
* the error mentioned a missing `.so` even though it was running on Windows.

Error message
```
$ vagrant
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

126: The specified module could not be found.   - C:/Users/rct/.vagrant.d/gems/gems/eventmachine-1.0.9.1/lib/rubyeventmachine.so
```

**Comment by sethvargo** [comment]
Hi @rct 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. I just booted up my windows 7 and did a fresh install and cannot reproduce this issue. Can you please try the following:

1. Completely uninstall Vagrant
2. Remove the c:/hashicorp or c:/vagrant directories
3. Remove the ~/.vagrant.d directory

And try again? Sorry!

**Comment by rct** [comment]
That info was in the original message, sorry if it wasn't clear.  Deleting `~/.vagrant.d/` (C:\Users\rct\.vagrant.d\) resolved the problem. 

Reinstalling vagrant (C:\Hashicorp) did not fix the problem.  I tried:
* Re-running the installer, which only gave the option of "Repair" installation
* Uninstall Vagrant (using the windows installed) and re-install.

Actually, I renamed ~/.vagrant.d/ so I still have it for inspection.   There was a eventmachine gem in that directory.  I'm not sure what caused it to be installed.

**Comment by sethvargo** [comment]
Hi @rct 

Are you able to provide any additional details on how to reproduce this? Unfortunately this issue does not appear to be widespread, and I am unable to reproduce it myself. As such, I think it might be a local environment issue. That doesn't mean it's not a bug in Vagrant, it just means it's very difficult for us to fix without a reproduction case.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄
