### ISSUE TITLE
Feature request: Make vagrant run provsion when `vagrant up --provisioon` executed.

### ISSUE THREAD

**Issue by tioteath** [mitchellh/vagrant#6988]
Current behavior:
  When box is already up, vagrant skips running provision when executed  with `vagrant up --provision`.

Expected behavior:
  When box is up, vagrant reports but keeps running provision.

P.S. 
  Actually, any option that allows silently spin up a host (without error messages) and apply provisioning would be nice to have. Vagrant is mostly testing tool, so the host state is not that important to fail execution.

**Comment by sethvargo** [comment]
Hi @tioteath 

Thank you for opening an issue, and I am sorry the Vagrant UX is not as you expect. We have had similar issues before. You can use the `vagrant up` command to bring any machine that is "down" or "unstarted" into the up state and use the `--provision` flag to enforce provisioning. You can also use the `vagrant provision` command to provision a machine that is already "up". Please let me know if you have any questions.

**Comment by tioteath** [comment]
What command should use if case I'd like to apply `provision` on box with unknown state?

**Comment by sethvargo** [comment]
You can use something like:

```
(vagrant status | grep -i "not created" && vagrant up --provision) || vagrant provision
```
