### ISSUE TITLE
Vagrant does not recognise vmware-workstation plugin but only on Homestead

### ISSUE THREAD

**Issue by rjsargeant** [mitchellh/vagrant#6995]
I have successfully installed the vmware-workstation plugin and used it on another vagrant box, However Vagrant gives the error message "The provider 'vagrant-vmware-workstation could not be found ..." in response to the 'vagrant up --provider vagrant-vmware-workstation' command.  I have followed previous suggestions and changes the provider property in the yaml file to 'vmware-workstation' and amongst other permutations changed the folder name under .vagrant.d/boxes/... but all without success.

Appreciate your thoughts.

**Comment by sethvargo** [comment]
Hi @rjsargeant 

Please open an issue on the homestead project. This is not a bug in Vagrant.
