### ISSUE TITLE
Can't get eth0 IP address to stick when using Vagrant+VMware Fusion

### ISSUE THREAD

**Issue by wchrisjohnson** [mitchellh/vagrant#6997]
I have a question about the way that vagrant+fusion works when a VM is created with "vagrant up". eth0 is the internal NIC that vagrant uses (seemingly controls, more accurately) for SSH access to the VM. Each time I create a new VM, this IP gets its 4th octet incremented. So, if that nic is using the 172.16.255.x range, the first time it will come up as 172.16.255.128. If I destroy that initial VM and create a new one via "vagrant up", it will get an eth0 IP of 172.16.255.129, the next time 172.16.255.130, and so on.

I'm using Ansible to provision my devstack/openstack work. Ansible expects a file to exist that includes in that file the IP address to use to SSH to the VM. My ansible inventory exists at ansible/inventory/dev and looks like this:

```
[devstack]
default ansible_ssh_host=172.16.255.128 ansible_ssh_port=22
```

I would like to be able to count on that IP address being the SAME every time I create the VM via "vagrant up". If not, I have to manually update that file every time the VM gets created. Manual updates inevitably introduce error and confusion, especially when a new user attempts to use my devstack install process.

I tried to use this in the Vagrantfile:

```
config.vm.network "private_network", ip: "172.16.255.128", auto_config: false
```

but no luck.

It doesn't appear that vagrant or Fusion is going to allow me to "stick" that IP address. If all else fails, I suppose I will have to auto detect and regenerate my Ansible inventory file every time I provision my VM, but I'd really prefer being able to just set it and forget it in my configuration.

Thanks in advance for any background I'm missing here.

Chris

**Comment by sethvargo** [comment]
Paging @phinze

**Comment by phinze** [comment]
Hi @wchrisjohnson - thanks for the report!

Have you tried leaving `auto_config` off of the private network options?

This `Vagrantfile` seems to be working for me in local testing:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", ip: "172.16.255.128"
end
```

(Note: I recommend upgrading [to the fresh release I just cut today](https://github.com/hashicorp/vagrant-plugin-changelog/blob/master/vagrant-vmware-changelog.md#407-february-8-2016), which has a fix for a bad option default that was release in 4.0.6.)

**Comment by wchrisjohnson** [comment]
Thanks @phinze - I just upgraded to 4.0.7. Unfortunately, it still seems to be incrementing that IP address after a "vagrant destroy" and a fresh "vagrant up". Here's my log of that:

`
webapps/devstack - [master●] » vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'puphpet/ubuntu1404-x64'. This can take some time...
==> default: Checking if box 'puphpet/ubuntu1404-x64' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.16.255.130:22
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 80 => 8888
    default: -- 3333 => 3333
    default: -- 5000 => 5000
    default: -- 8000 => 8000
    default: -- 8004 => 8004
    default: -- 8080 => 8080
    default: -- 8773 => 8773
    default: -- 8774 => 8774
    default: -- 8776 => 8776
    default: -- 9292 => 9292
    default: -- 9696 => 9696
    default: -- 35357 => 35357
    default: -- 22 => 2222
==> default: Setting hostname...
==> default: Configuring network adapters within the VM...
==> default: Waiting for HGFS kernel module to load...
==> default: Enabling and configuring shared folders...
    default: -- /Users/wchrisjohnson/src/webapps/devstack: /vagrant
    default: -- /Users/wchrisjohnson/src/vagrant_data: /vagrant_data
`

Could this be an issue with the box I'm using?

Here's my Vagrantfile as well:

`
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "puphpet/ubuntu1404-x64"
  config.vm.hostname = "trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.network "forwarded_port", guest: 3333, host: 3333
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 8004, host: 8004
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8773, host: 8773
  config.vm.network "forwarded_port", guest: 8774, host: 8774
  config.vm.network "forwarded_port", guest: 8776, host: 8776
  config.vm.network "forwarded_port", guest: 9292, host: 9292
  config.vm.network "forwarded_port", guest: 9696, host: 9696
  config.vm.network "forwarded_port", guest: 35357, host: 35357
  config.vm.network "private_network", ip: "172.16.255.128" #, auto_config: true
  config.vm.network "private_network", ip: "172.16.40.128" #, auto_config: true
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.vm.synced_folder "/Users/wchrisjohnson/src/vagrant_data", "/vagrant_data"
  config.vm.provider "vmware_fusion" do |v|
    # Boot option: true = GUI, false = headless
    v.gui = false
    v.vmx["memsize"] = "8192"
    v.vmx["numvcpus"] = "2"
    v.vmx["vhv.enable"] = "TRUE"
  end
end
`

**Comment by wchrisjohnson** [comment]
Ok, more info to share on this. 

I added an Ansible provision block to the Vagrantfile like so:

```
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/apache2.yml"
    ansible.verbose = "vv"
    ansible.sudo = true
  end
```

The next time I "vagrant up" to create a VM, it runs the Ansible provisioner and I see this:

```
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --connection=ssh --timeout=30 --limit='default' --inventory-file=/Users/wchrisjohnson/src/webapps/devstack/.vagrant/provisioners/ansible/inventory --sudo -vv ansible/apache2.yml
```

Note the reference to an inventory file in that command. Behind the scenes, it looks for a local inventory file, `ansible/inventory/dev` (which I conveniently deleted). When it doesn't find one, it GENERATES a new one in the above location. So I no longer have to worry about generating an inventory file such that my inventory file matches my vagrant configuration file.

The only thing I would still like to resolve is the "stickiness" of the IP address of the NIC used to SSH to the VM. It might not matter, in that eventually I'll hit the upper limit of the address range, i.e. it will go from x.x.x.128 up to x.x.x.256. At that point, as long as it rolls back over to x.x.x.1 or x.x.x.128, then I should be fine. At the very least, it would be good to understand if that is the case.

**Comment by phinze** [comment]
@wchrisjohnson Ah I apologize I misread the original issue. You can definitely _add_ private interfaces with static IP addresses and use those to communicate with your VM, but Vagrant really wants `eth0` to be a DHCP host-only adapter for its internal use.

The IP Address keeps changing because VMware's internal DHCP is granting a new lease to the machine each time it boots, and therefore a new IP address. I believe you could get your VM to pick up the same lease by fixing its mac address with something like the following:

```ruby
  config.vm.provider 'vmware_fusion' do |v|
    v.vmx["ethernet0.generatedAddress"] = nil
    v.vmx["ethernet0.addressType"] = "static"
    v.vmx["ethernet0.address"] = "00:0c:29:ac:f3:50"
  end
```

But generally speaking you can rest assured that the DHCP interface will do its job and pick up an IP - if you need static IPs to be able to communicate with your machine, you can add them as additional interfaces and use those IPs directly to talk to the VM.

Hope this helps! Let me know if you have any further questions here.

**Comment by wchrisjohnson** [comment]
Nope @phinze - given what I've discovered about how Vagrant can autogenerate the inventory file, I can live with this solution. It's clean (no manual intervention required) and straightforward. Thanks for the help.
