### ISSUE TITLE
VMware synced folders with vmhgfs-fuse

### ISSUE THREAD

**Issue by vadviktor** [mitchellh/vagrant#6999]
Since the VMware plugin is proprietary (or is it?), I'd like to suggest the vmhgfs-fuse way to be available when one would decide to install the open sourced Vmware client tools known as open-vm-tools.
It could be a new synced folders type. This is a gist of how one would use it to mount a shared folder:

https://gist.github.com/vadviktor/5aa034bbee6e53d26b70

The old (deprecated) client tools makes Vagrant to look for the HGFS kernel module and that stops me to easily just mount the shared folders defined in the Vagrantfile by a shell script.

I'd see an option to disable the check for the HGFS module viable too, that would open the gates to at least manually mount those shares.

The best would be if one could create this synced folder type. Is it tied to the vmware plugin or could (even me) someone help in creating it?

Thanks!

**Comment by sethvargo** [comment]
Hi @vadviktor 

I think the best option for you is to create a plugin (https://www.vagrantup.com/docs/plugins/development-basics.html). If the plugin gains in popularity, we will consider merging it into Vagrant's core. Thanks! :smile:

**Comment by vadviktor** [comment]
Hehe :smiley_cat: challenge accepted.
