### ISSUE TITLE
SMB synced folders teardown

### ISSUE THREAD

**Issue by vadviktor** [mitchellh/vagrant#7000]
I'd have a suggestion to ease the tearing down of the shared folders through Windows Shared folders (SMB/CIFS):

could we receive an post message of with the command(s) to use to delete the windows shares created for the machine?

E.G. I created two shares and Vagrant mapped them to 'xyz' and 'abc'. When one would halt the machine, the post message would say:

```
NOTICE!
Please use the following command(s) to remove the shared folder links created by Vagrant:

net share abc /delete
net share xyz /delete
```

Clumsy, immature, but for now it'd help a lot for those who has more of these folders attached. :smile: 

Any opinion or any info about someone already working on the cleanup method?

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for almost a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
