### ISSUE TITLE
Vagrant ssh internal output messes with stdout

### ISSUE THREAD

**Issue by jalkanen** [mitchellh/vagrant#7004]
I'm trying to run a script on the guest using vagrant ssh as a part of a host-side script.  However, Vagrant ssh's own output goes to stdout, so it messes the result.  Specifically, I'm trying to run

```
for i in $(vagrant ssh -c 'ls -1 ${HOME}')
do
     <do something with files>
done
```

However, this does not seem to be trivially possible, since two first lines to stdout are always "Using VM hostname" and "Using ssh key".

Using "-c", three first lines go to stdout. Last line is stderr (the connection closed one):

```
[jalkanen@Ingata:~/vm/ios]% vagrant ssh -c "echo foo"           
Using VM hostname: iostest.Ingata
Using ssh key: /Users/jalkanen/.ssh/vagrant
foo
Connection to 192.168.111.129 closed.
```

Using "--", three lines go to stdout. 

```
[jalkanen@Ingata:~/vm/ios]% vagrant ssh -- "echo foo"
Using VM hostname: iostest.Ingata
Using ssh key: /Users/jalkanen/.ssh/vagrant
foo
```

Trying to shut up Vagrant with the use of VAGRANT_LOG:

```
[jalkanen@Ingata:~/vm/ios]% VAGRANT_LOG=error vagrant ssh -c "echo foo"
Using VM hostname: iostest.Ingata
Using ssh key: /Users/jalkanen/.ssh/vagrant
foo
Connection to 192.168.111.129 closed.
```

Unsure whether this is a feature request or a bug, but at any rate:
- vagrant ssh should respect VAGRANT_LOG-level for the "Using XXX" -lines
- The "Using XXX" -lines should go to stderr, not stdout.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
