### ISSUE TITLE
Vagrant reload fails to mount the default shared folder /vagrant

### ISSUE THREAD

**Issue by Loyalsoldier** [mitchellh/vagrant#7006]
I vagrant init the VM `chef/centos7`. Everything was okay the first time the vm booted.

But when running `vagrant reload` or `vagrant halt` then `vagrant up` again, the vm fails to mount the default shared folder `/vagrant`. And I found the owner and group of the `/vagrant` folder in the CentOS 7 have changed to `root` both while they were `vagrant` at first time booting.

**My OS environment:** Windows 10 Pro 64 bit
**VirtualBox version:** v5.0.14
**Vagrant version:** v1.8.1

**This is the CLI error output:**

```
PS D:\dev\centos7> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.14
    default: VirtualBox Version: 5.0
==> default: Mounting shared folders...
    default: /vagrant => D:/dev/CentOS7
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant

The error output from the last command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

**Comment by Loyalsoldier** [comment]
I think I find the problem.

If I don't run `yum update`, everything is great.
After running `yum update', `vagrant up` and `vagrant reload` couldn't mount the default shared folder `/vagrant` both.

**Comment by sethvargo** [comment]
Hi @Loyalsoldier 

What package(s) are being updated from yum?

**Comment by Loyalsoldier** [comment]
I remembered there were almost 250 packages...

Every time I installed a CentOS 7, I would first run `yum update` to update all packages to the newest versions.

**Comment by sethvargo** [comment]
@Loyalsoldier 

I'm willing to bet one of them is nfs and it's messing with the existing folder mounts. Can you check if nfs (or similar) is in the list?

**Comment by Loyalsoldier** [comment]
@sethvargo Yeah. I find `nfs-utils` in the update list. But I finally found that the packages named after kernel were the sins.

I ran `sudo yum -x kernel* update` to avoid updating those packages named after `kernel` then everything was great!
