### ISSUE TITLE
vb.customize malfunction

### ISSUE THREAD

**Issue by vdksystem** [mitchellh/vagrant#7007]
We have two lines in Vagrantfile with folowing content

```ruby
vb.customize ["sharedfolder", "add", :id, "--name", "work", "--hostpath", "/home/user/work", "--automount"]
vb.customize ["sharedfolder", "add", :id, "--name", "mysql", "--hostpath", "/home/user/mysql", "--automount"]
```

after vagrunt up we are expecting on two automount folders, but getting only one automount.
screenshot - http://screencloud.net/v/s9hE

```
host system - Linux master 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:        8.2
Codename:       jessie
```

virtualbox - http://screencloud.net/v/qoxZ

**Comment by sethvargo** [comment]
Hi @vdksystem 

Thank you for opening an issue. This looks like a bug in Virtualbox, not Vagrant. Please try upgrading to virtualbox 5 and if the issue persists, please raise a ticket with the vbox team. Thanks! :smile:

**Comment by vdksystem** [comment]
Thanks for quick response. 
If it's important, when I execute "vboxmanage sharedfolder add ... --automount" from console, it doesn't look like a virtualbox bug, because it works as expected.

**Comment by sethvargo** [comment]
Hi @vdksystem 

Does it work as expected when you run _both_ of those commands?

**Comment by vdksystem** [comment]
When I sow this problem, i solved it with "vboxmanage sharedfolder add" cli command for every folder I need.
If I use in my Varantfile options above 
`vb.customize ["sharedfolder", "add", :id, "--name", "work", "--hostpath", "/home/user/work", "--automount"]
vb.customize ["sharedfolder", "add", :id, "--name", "mysql", "--hostpath", "/home/user/mysql", "--automount"]`
i get all this folders shared, but only one (first in Vagrantfile list) with automount flag.

**Comment by sethvargo** [comment]
Hi @vdksystem 

Thank you for that. When you run those commands directly (without Vagrant), are you seeing both folders are mounted with the automount option?

**Comment by vdksystem** [comment]
I apologise, but it's my fault.
I was confused with `config.vm.synced_folder` option. I didn't find how to create automount folder with this option so in addition used `vb.customize` - it was mistake.
I'm sorry for wasting your time.
