### ISSUE TITLE
vagrant unable to mount UNC path in 1.8 or 1.8.1

### ISSUE THREAD

**Issue by vinceskahan** [mitchellh/vagrant#7011]
In short, how do we mount a shared folder on a Windows host if we specify with a UNC path ala \some.server.here\path ?   This worked under versions prior to 1.8, but fails with 1.8 and 1.8.1 under Windows.

Sorry for the cross-post (I'll edit the text in if you want), but there is a full problem description and examples here.

[crosspost from google group for vagrant](https://groups.google.com/forum/?hl=en&fromgroups=#!topic/vagrant-up/aOQl4Gg7HNQ)

**Comment by arnoudhgz** [comment]
bump

**Comment by vinceskahan** [comment]
Does anybody read these things ?

I opened the google groups question the day 1.8 came out (12/23/15) and this one a month ago.  Not even crickets chirping in response...

**Comment by vinceskahan** [comment]
will this ever be worked ?

**Comment by vinceskahan** [comment]
another month of no feedback - is there a way to get this to a human to look at ?

**Comment by rossi-fi** [comment]
It looks like this was broken while solving other issues somewhat heavy handedly in 1.7.4. Please see #5495. Basically every path got converted into a UNC path with by adding ```\\?\``` prefix, to solve long file paths causing protocol errors.  

Directly mounting a UNC share is therefore no longer possible although VirtualBox supports it.

Lots of fun around this topic:

- #5933
- #6493
- #6598

As a user I would expect all of the below to be valid notation while keeping support for long network names:

    vm.synced_folder 'C:', '/some/path'
    vm.synced_folder 'C:/', '/some/path'
    vm.synced_folder 'C:\', '/some/path'
    vm.synced_folder 'C:\path\to\somewhere', '/some/path'
    vm.synced_folder 'C:/path/to/somewhere', '/some/path'
    vm.synced_folder '\\server\share', '/some/path'
    vm.synced_folder '\\server\share\folder', '/some/path'

**Comment by vinceskahan** [comment]
I read some of the responses re: why this bug still exists and have to
respond with (a) huh - not fixed because there aren't any windows boxes for
the dev to test against - I thought Hashi was a Corp.  This is a $400
problem with a couple Intel NUCs....and (b) don't you have 'any' regression
testing ?  I'm beyond amazed that there's apparently no shared folders
mounting tests for Windows, ala Markus's suggestions.


On Tue, Jul 12, 2016 at 9:42 AM, Markus Rossi <notifications@github.com>
wrote:

> It looks like this was broken while solving other issues somewhat heavy
> handedly in 1.7.4. Please see #5495
> <https://github.com/mitchellh/vagrant/pull/5495>. Basically every path
> got converted into a UNC path with by adding \\?\ prefix, to solve long
> file paths causing protocol errors.
>
> Directly mounting a UNC share is therefore no longer possible although
> VirtualBox supports it.
>
> Lots of fun around this topic:
>
>    - #5933 <https://github.com/mitchellh/vagrant/issues/5933>
>    - #6493 <https://github.com/mitchellh/vagrant/pull/6493>
>    - #6598 <https://github.com/mitchellh/vagrant/issues/6598>
>
> As a user I would expect all of the below to be valid notation while
> keeping support for long network names:
>
> vm.synced_folder 'C:', '/some/path'
> vm.synced_folder 'C:/', '/some/path'
> vm.synced_folder 'C:\', '/some/path'
> vm.synced_folder 'C:\path\to\somewhere', '/some/path'
> vm.synced_folder 'C:/path/to/somewhere', '/some/path'
> vm.synced_folder '\\server\share', '/some/path'
> vm.synced_folder '\\server\share\folder', '/some/path'
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/7011#issuecomment-232104341>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAk2KptAAPQqOpBJYCIijNwtJHIWiypfks5qU8PdgaJpZM4HXgtq>
> .
>



-- 
-----  vinceskahan@gmail.com ----

**Comment by rossi-fi** [comment]
I [tried removing the restrictions](https://github.com/rossi-fi/vagrant/commit/c64062ec0796498a04586e052e0684167dfedbae) preventing UNC paths from being configured. The shares were now added to the guest but they were not functional either on Linux or Windows guests. 

From Linux guest boot:

    ==> default: Mounting shared folders...
        default: /vagrant => C:/path/to/vagranthome
        default: /uncslashes => //servername/sharename
    Failed to mount folders in Linux guest. This is usually because
    the "vboxsf" file system is not available. Please verify that
    the guest additions are properly installed in the guest and
    can work properly. The command attempted was:
    
    mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` uncslashes /uncslashes
    mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` uncslashes /uncslashes

    The error output from the last command was:


I also unsuccessfully tried to add a UNC network share directly using VirtualBox console. I'm currently on VirtualBox 5.0.24.

@vinceskahan are you currently able to add a functioning UNC network share to a VirtualBox guest, either via VirtualBox console or with the vboxmanage command? If yes, which VirtualBox version?

Currently I'm having to resort to mount a subdirectory of a mapped network drive. When GH-6765 makes it into a release we'll be able to map just the drive letter.

**Comment by vinceskahan** [comment]
I went back to 1.7.4 after trying 1.8 and 1.8.1 which both have the issue.
  Folks have had 1.7.4 work in all known configs up to and including
Virtual Box 5.0.18 r106667 (what I run).  I haven't looked at anything
newer myself.

I can only spend a limited number of cycles removing/reinstalling/testing
on my work computer as I have actual work to do, and since this one seems
to have nobody actually caring on the Vagrant side.  Unfortunately I have a
bunch of developers who need this kind of basic stuff to 'just work' with
no hacking or patching required so we're sticking with the devil we know in
terms of versions at this point until we see folks report there's a Vagrant
version that works again unpatched.



On Wed, Jul 13, 2016 at 3:57 AM, Markus Rossi <notifications@github.com>
wrote:

> I tried removing the restrictions
> <https://github.com/rossi-fi/vagrant/commit/c64062ec0796498a04586e052e0684167dfedbae>
> preventing UNC paths from being configured. The shares were now added to
> the guest but they were not functional either on Linux or Windows guests.
>
> From Linux guest boot:
>
> ==> default: Mounting shared folders...
>     default: /vagrant => C:/path/to/vagranthome
>     default: /uncslashes => //servername/sharename
> Failed to mount folders in Linux guest. This is usually because
> the "vboxsf" file system is not available. Please verify that
> the guest additions are properly installed in the guest and
> can work properly. The command attempted was:
>
> mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` uncslashes /uncslashes
> mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` uncslashes /uncslashes
>
> The error output from the last command was:
>
> I also unsuccessfully tried to add a UNC network share directly using
> VirtualBox console. I'm currently on VirtualBox 5.0.24.
>
> @vinceskahan <https://github.com/vinceskahan> are you currently able to
> add a functioning UNC network share to a VirtualBox guest, either via
> VirtualBox console or with the vboxmanage command? If yes, which VirtualBox
> version?
>
> Currently I'm having to resort to mount a subdirectory of a mapped network
> drive. When GH-6765 <https://github.com/mitchellh/vagrant/pull/6765>
> makes it into a release we'll be able to map just the drive letter.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/7011#issuecomment-232323009>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAk2Ki15abah4-92wnPr-8UgvbFM4fN-ks5qVMSdgaJpZM4HXgtq>
> .
>



-- 
-----  vinceskahan@gmail.com ----

**Comment by vinceskahan** [comment]
Any movement on this one from the vagrant team ?  Will there be any movement on this ?  Six months is a long time to hear nothing for functionality that is so core to users on the Windows platfom.....

**Comment by Spamme1** [comment]
It took me one day to understand why it wasn't working! Nice that this bug is open since 6 months and nobody solved it. Hard coded features are always nice, they are the best way to break something!
In any case if somebody is looking for a work around, this worked for me:
```ruby
config.vm.provider "virtualbox" do |vb|
  vb.customize ["sharedfolder", "add", :id, "--name", "share", "--hostpath", "\\\\ServerName\\share"]
end
````

**Comment by daniel3d** [comment]
on WIndows updating to Virtual box Version 5.1.2 r108956 fixes the issue the folders are still showing the with the \\? prefix but at least is working \\?\C:\Homestead

**Comment by vinceskahan** [comment]
This is still not fixed completely.

I updated to current vagrant 1.9.0 and current virtualbox 5.1.10 r112026 on windows7 and the same problem exists, this time pointing to line 1020 in VBoxManageMisc.cpp in the error message.

The 'workaround' of mapping a host drive letter, assuming the host os has previously mounted the desired UNC path to a drive letter, works ok for me.

I ran the excellent test cases in Markus' July-12-2015 note above with the following results, all from a cygwin shell if that matters any:

- mapping "S:" works
- mapping "S:\" fails, you need to escape the backslash
- mapping "S:\\" works
- mapping "S:/somepath" works
- mapping "S:\somepath" fails, you need to escape the backslash
- mapping "S:\\somepath" works
- mapping "\\\\server\\share" fails with the original error reported a year ago
- mapping "//server/share" fails the same way, vagrant constructs the same "\\\\?\\\\\\my.fqdn.com\\share" string the example above tries to do, which fails to work

So I can't find a combination that will mount a UNC path.  Original bug is 'not' fixed.

**Comment by chrisroberts** [comment]
Hi there. I'm going to close this as fixed. The previous comment (https://github.com/mitchellh/vagrant/issues/7011#issuecomment-263952842) provides a nice list of paths that work and paths that fail. For the paths that need the backslash escaped, there is no way around that. It is simply a syntax thing and must be addressed by the user when creating the file. For the last two paths that reference a `server`, these are unsupported by virtualbox and should not be expected to work.

If you do find that you are still encountering problems, please either reopen this ticket or create a new one. Thanks!

**Comment by vinceskahan** [comment]
Disagree - I fail to see how something that used to support mapping \\server\share mappings for 'years' that doesn't support it as of vagrant-1.8 can be considered 'fixed' under any circumstances.

It used to support all syntaxes, properly escaped of course.  It does not as of vagrant-1.8 which is ancient now.  How could this possibly be considered 'fixed' ?

please - seriously - tell us the magic incantation  that permits a UNC path to mount again.  Really.

**Comment by chrisroberts** [comment]
@vinceskahan Thanks for the feedback. Vbox maintainers have commented that remote unc paths should not be expected to work. However, if given a path that is already in unc format, it shouldn't be adjusted. See #8504 for fix to that situation. Cheers!
