### ISSUE TITLE
What should permissions be on .vagrant directories and files?

### ISSUE THREAD

**Issue by yb66** [mitchellh/vagrant#7018]
Hello,

I just had the error `warning: Insecure world writable dir /Users/yb/.vagrant.d/gems in PATH, mode 040777`. It has an [issue (closed for it](https://github.com/mitchellh/vagrant/issues/2185), but as I was inspecting the permissions to fix them, I realised I've no idea what I should be setting them to.

The last response on that issue is "Change the permissions to something more reasonable and the error should go away. " but it would be good if the expected/acceptable permissions for all .vagrant directories and files were documented somewhere. Not only would it be easier to write a script to set them automatically, it would allow changes to be noticed too.

I'll set them as I think is "reasonable" but this info would be helpful, in my opinion.

Thanks
iain

**Comment by sethvargo** [comment]
700 is usually a good bet

**Comment by yb66** [comment]
Thanks @sethvargo, but there are differences in permissions between some of the sublevel files and dirs, so could that be applied recursively? i.e  `chmod -R 700`

**Comment by sethvargo** [comment]
The short answer is that "it varies". Files should probably be 644 and directories can be 700

**Comment by yb66** [comment]
Thank you @sethvargo, much appreciated. If anyone is looking at this, these commands will work for bash/zsh to set those permissions:

    find ~/.vagrant.d -type d -exec chmod 700 {} +

    find ~/.vagrant.d -type f -exec chmod 644 {} +

Just replace `~/.vagrant.d` with the correct path if yours is different.

Regards,
iain

**Comment by tidiosky** [comment]
Thank you @yb66, these commands work for me.
