### ISSUE TITLE
box for wrong provider is not saved

### ISSUE THREAD

**Issue by ijstokes** [mitchellh/vagrant#7021]
I have vmware fusion installed, but I rarely use it.  Despite having `virtualbox` specified in my `Vagrantfile` as so:

```
  config.vm.provider "virtualbox" do |v|
    v.name = "6-trialbox"
  end
```

The only way I can properly bring up a box with VirtualBox (my preferred hypervisor) is by doing:

```
vagrant up --provider virtualbox
```

(the part above is a recap of #7020)

THE PROBLEM: When I forget to add `--provider virtualbox`, and if it is the first time bringing up a VM using a `Vagrantfile` that has `box_url` specified inside of it, Vagrant will download the entire VM (sometimes this takes a few hours for big ones), and **then** it will realize that it has a box for VirtualBox and not one for VMWare Fusion, and it will bork out.  Subsequent `vagrant up` commands will also just download the same stupid VM **again** even though it pulled it down once already.  It doesn't make sense to me that it tries to download the box again.  Why doesn't it just get the one from the cache? (it should) Or under this situation is it not saved to the cache (it definitely should do this, if it isn't)

**Comment by sethvargo** [comment]
Hi @ijstokes 

Vagrant will automatically pick the "best" provider for your system. You can export the VAGRANT_DEFAULT_PROVIDER environment variable to avoid needing the --provider flag each time.

**Comment by ijstokes** [comment]
@sethvargo that is not what I was reporting as the problem: the problem is that it has already downloaded the VM, I've waited an hour or more for that to happen, but then it says it can't use it (because I forgot to specify `--provider virtualbox`).  I correct the command, adding the option, and instead of using the VM that was just downloaded **vagrant starts downloading the same VM again**.  That is the bug.

**Comment by LongLiveCHIEF** [comment]
I have the same, or very similar issue, in that `vagrant up` thinks one of my machines is the incorrect provider.  I have a multi-vm, with the first VM being a `virtualbox` provider, and the last two are `docker` providers.  I have a setting on the global scope within the vagrantfile that tells the docker provider to use the first vm as the host, and then I up the whole thing with the `--no-parallel` flag.

The first time I upped, everything worked. It used virtualbox for machine 1, and the docker for the other 2, using the first machine as the `docker-host`.

However, at some point, something changed.  When I run `vagrant status`, it tells me all 3 machines are `docker` machines, and the `vagrant up` fails, with the message `you are attempting to use a provider that is not supported for this box`.

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "docker-host" do |docker|

    docker.vm.box = "LongLiveCHIEF/minimal-centos-7"
    docker.vm.network "private_network", ip: "192.168.39.39"

    docker.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
    end

    docker.vm.provision "file",
      source: "vagrant/docker.repo",
      destination: "/tmp/docker.repo"

    docker.vm.provision "shell",
      path: "vagrant/docker.sh",
      privileged: true

  end

  config.vm.provider "docker" do |dock|
      dock.vagrant_vagrantfile = "./Vagrantfile"
      dock.vagrant_machine = "docker-host"
  end

  config.vm.define "ldap-server" do |ldap|
      ldap.vm.provider "docker" do |docker|
        docker.image = "nickstenning/slapd"
      end
  end

  config.vm.define "rethink" do |rethink|
    rethink.vm.provider "docker" do |docker|
      docker.image = "rethinkdb:2.2"
    end
  end

end
```
