### ISSUE TITLE
Snapshots don't reapply network settings when restoring

### ISSUE THREAD

**Issue by danielcompton** [mitchellh/vagrant#7029]
## Intro

I ran into a confusing bug over the last few days. I had set my VM up to a certain point, snapshotted it, then continued tweaking my Ansible config and Vagrantfile port forwarding. What I was finding was that the port forwarding was only being applied after I had reloaded a Vagrant VM that had been restored from a snapshot.
## Steps to reproduce:
1. Create a Vagrantfile and setup port forwarding for 80 => 8080
2. `vagrant snapshot save mysnap`
3. Add another port forwarding for 443 => 4443 in the Vagrantfile
4. Run `vagrant snapshot restore mysnap`
## Expected results

Vagrant VM is started with ports 80 and 443 forwarded
## Actual results

Vagrant VM is started with port 80 forwarded. After running `vagrant reload`, port 443 will also be forwarded.

I'm using Virtualbox 5.0.12 r104815, and Vagrant 1.8.1.

**Comment by chrisroberts** [comment]
I believe this is the expected behavior. The restore will return to the state of the snapshot, which does not include the newly added forwarded port. A reload would be required at that point to forward the new port. Cheers!

**Comment by danielcompton** [comment]
Hi Chris, my (incorrect?) assumption was that the settings in the Vagrantfile are applied to a VM every time it starts up. That doesn't seem to be the case when restoring snapshots? Is that the desired behaviour?

I think possibly my mistake was that I assumed a snapshot captured just the state of the disk, but it sounds like it also captures the running state of the VM?
