### ISSUE TITLE
vagrant does not install correctly on Win 7.1 64

### ISSUE THREAD

**Issue by kklepper** [mitchellh/vagrant#7034]
vagrant_1.8.1.msi, 2 attempts, no folders created, no errors. 

In 

    Computer\HKEY_LOCAL_MACHINE\SYSTEM\VirtualRoot\MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\Folders

are all the subfolders of my first attempt

    C:\HashiCorp\

and all the subfolders of my second attempt

    C:\xampp\Vagrant\

listed in absolute perfection. I don't have either folders on my disk, however.

I do have working folders in C:\xampp\HashiCorp\Vagrant\ from my previous attempt in 2014, when I worked my way through Docker back then without problems (Vagrant was installed in C:\HashiCorp\ on my precursor machine).

Interestingly I had the same symptom with DockerToolbox-1.10.0.exe (no errors, no folders). Previously I had installed the latest version of VirtualBox, but as an attempt of remedy deinstalled it and let Docker install it instead, to no avail.

I never had these problems before. Just to be sure, I installed some minutes ago -- as a test -- MuseScore-2.0.2.msi without problems. Folders exist, program works.

Any idea anyone?

**Comment by sethvargo** [comment]
Hi @kklepper 

Thank you for opening an issue. This definitely seems like a local environment issue and not a widespread Vagrant bug. We prefer to keep the issue tracker reserved for issues and feature requests. Could you please post on the Vagrant mailing list instead? Thanks! :smile:
