### ISSUE TITLE
rsync options shared between multiple shared folder definitions

### ISSUE THREAD

**Issue by siddharthist** [mitchellh/vagrant#7036]
The configuration for `rsync` options can become shared between two different specified synced folders (at least if they share the same path). Steps to reproduce:
1. Create a shared folder with rsync based syncing that excludes `file2`
2. Create a new rsync shared folder configuration that includes `file2` and specifies `--ignore-existing`
3. Bring your box up
4. Change `file1` and `file2`
5. `vagrant rsync`
6. SSH into your machine, view `file1`, `file2`. The contents of both haven't changed!

The expected behavior is that `vagrant` executes `rsync` twice, with different options. Looks like it only gets executed once right now.  

The use case is that the vagrant provisioning step changes `file2` and we want to preserve those changes across `rsync`s. 

```
$ vagrant --version
Vagrant 1.8.1
```

Example Vagrantfile:

``` ruby
Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "centos/7"
  # Centos has an extra default shared folder
  config.vm.synced_folder ".", "/home/vagrant/sync", disabled: true

  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__exclude: ["test2.txt"]

  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__args: [
      "--verbose", "--archive", "-z", "--copy-links", # defaults
      "--ignore-existing", "--include=test2.txt", "--exclude='*'"
  ]
end
```

Log of this bug in action shown below:

```
$ echo "" > test{1,2}.txt
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' is up to date...
[...]
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Rsyncing folder: /home/siddharthist/Dropbox/code/asteris/vagrant-bug/ => /vagrant
==> default:   - Exclude: [".vagrant/", "test2.txt"]
$ vagrant ssh
[vagrant@localhost ~]$ cat /vagrant/test*


[vagrant@localhost ~]$ exit
logout
Shared connection to 127.0.0.1 closed.
$ echo "changed" > test{1,2}.txt
$ vagrant rsync
==> default: Rsyncing folder: /home/siddharthist/Dropbox/code/asteris/vagrant-bug/ => /vagrant
==> default:   - Exclude: [".vagrant/", "test2.txt"]
$ vagrant ssh
Last login: Sun Feb 14 16:54:51 2016 from 10.0.2.2
[vagrant@localhost ~]$ cat /vagrant/test*


[vagrant@localhost ~]$ exit
logout
Shared connection to 127.0.0.1 closed.
```

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
