### ISSUE TITLE
SSH input lag

### ISSUE THREAD

**Issue by mark-obrien** [mitchellh/vagrant#7037]
Every time I ssh into a vagrant box there is a lag from when I start typing until the command/input is finally displayed in the terminal. This issue only happens on my Windows desktop. It does not affect Mac users. I'm not sure if it is a Vagrant issue or VB issue.

Vagrant - 1.8.1
VirtualBox - 5.0.14
Windows 10
CLI - Git Bash and Windows Command Prompt

Anybody else experiencing this?

**Comment by sethvargo** [comment]
Hi @mark-obrien 

This is likely a virtualbox issue. Once you are SSHed into the machine, it's all local networking to the vb instance and Vagrant is no longer in the mix. Thanks! :smile:
