### ISSUE TITLE
vagrant reload stuck after host ubuntu resumes

### ISSUE THREAD

**Issue by aberope** [mitchellh/vagrant#7048]
### Vagrant version

Vagrant 1.7.4
### Host operating system

Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
### Guest operating system

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
### Vagrantfile

``` ruby
# By aberope [at] github.
VAGRANTFILE_API_VERSION="2"
PROJECT_NAME = "vagrant-php7"
PRIVATE_IP = "10.10.10.8"
SHARE_TYPE = "nfs"
BINDFS_OWNER = "33" #www-data
BINDFS_GROUP = "33" #www-data

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define PROJECT_NAME do |lb_config|
    lb_config.vm.box = "http://vagrant.localhost/ubuntu-trusty64.box"
    lb_config.vm.network "private_network", ip: PRIVATE_IP
    lb_config.vm.network "public_network", bridge: "wlp5s0"
    lb_config.ssh.forward_agent = true
    lb_config.vm.hostname = PROJECT_NAME + ".local"
    lb_config.vm.synced_folder '.', '/vagrant', disabled: true, type: SHARE_TYPE
    lb_config.vm.synced_folder 'rootfs', '/vagrant', disabled: false
    lb_config.vm.synced_folder 'htdocs', '/var/www/html', disabled: false, type: SHARE_TYPE
    lb_config.bindfs.bind_folder '/var/www/html', '/var/www/html', :owner => "33", :group => "33"
    lb_config.nfs.map_uid = Process.uid
    lb_config.nfs.map_gid = Process.gid
    lb_config.vm.synced_folder 'dbs', '/dbs', disabled: false, type: SHARE_TYPE
    lb_config.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", PROJECT_NAME]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--vram", 64]
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    end
    lb_config.vm.provision "bootstrap", type: "shell" do |s|
      s.inline = <<-SCRIPT
        /vagrant/bin/vagrant-bootstrap
      SCRIPT
    end
    lb_config.vm.provision "host_rootfs", run: "always", type: "shell" do |s|
      s.inline = <<-SCRIPT
        rsync-rootfs
      SCRIPT
    end
  end
end
```
### Debug output

```
$ vagrant reload
==> vagrant-php7: Attempting graceful shutdown of VM...
^C==> vagrant-php7: Waiting for cleanup before exiting...
^C==> vagrant-php7: Exiting immediately, without cleanup!
$ ./vbox-kill 
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
```
### Expected behavior

The expected behaivor is to get the machine ready after every host system resume.
### Actual behavior

When the system gets in suspend mode and the vagrant is running, and then I resume host system, I try to connect to my apache2' service but it's stuck on loading. 
Then I run `vagrant reload` and it stops for undefined time in `Attempting graceful shutdown of VM...`

The only way I have to be able to reload the machine is to use my script `vbox-kill`:
`#!/bin/sh`
`VBoxManage controlvm vagrant-php7 poweroff`

Finally after last command I can reload the machine.
### Steps to reproduce
1. `vagrant up`.
2. suspend and resume host.
3. try to connect to apache2 service.
### References

There're no issues.

**Comment by sethvargo** [comment]
Hi @aberope 

Thank you for opening an issue. Is there a process on that machine that prevents it from shutting down? Vagrant attempts to shutdown the machine gracefully (like `sudo shutdown`), but if the machine is not responding to that command, it will just hang. Can you please try starting the VM and then running the shutdown command manually over an SSH connection to see what happens?

I don't have access to the Vagrant box you are using, or I'd do it myself.

**Comment by aberope** [comment]
Hello @sethvargo , sorry for the waiting I was working hard on another poject this week.

It's okay for opening the issue. I think there's no process. I am sure if I don't suspend the laptop it won't become freezed. I hadn't know it, I just thought Vagrant used VirtualBox (my provider) to send some ACPI shutdown. Yeah, I will try it on monday or tomorrow. Now I adquired a Mac and the process is working fine after suspend. The vagrant responses to anything.

Some interesting thing about the issue I described, is that if you open an ssh before suspend the laptop, after resume of the operating system (ubuntu) the session still remains, but vagrant is not accepting (maybe connections) `vagrant halt` or `vagrant reload`.

I can pass you the vagrant.box (base image file) I am using. Will speak soon, and maybe a link. It's about 700-800MB weight :)

Thanks!

**Comment by aberope** [comment]
Hello @sethvargo, I uploaded the base box to my google's drive. Here is the link https://drive.google.com/file/d/0B6bNcfUwchuiRWN3RVdGdTU2eEk/view?usp=sharing

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
