### ISSUE TITLE
Add support for the XDG Base Directory Specification

### ISSUE THREAD

**Issue by SShrike** [mitchellh/vagrant#7051]
You can find the specification [here](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

This [blog post](https://ploum.net/207-modify-your-application-to-use-xdg-folders/) lists the advantages of using the XDG Base Directory Specification as follows:
- `$HOME` is a lot less cluttered.
- Backups are a lot more safer and easier (you know that creating a backup of your `$XDG_DATA_HOME` along with your files is enough).
- A lot easier to reset a default configuration if you want/need it (and without any risk of loosing information).
- Avoid some strange bugs that happen because you had a old version of some configuration file.
- It is a lot more flexible and portable because no paths are hard-coded. You can use the XDG library that does the job for you _or_, if you don’t want the dependency, implementing the XDG specification is only a few lines of code.

**Comment by sethvargo** [comment]
Hi @SShrike 

Thank you for opening an issue. This is not something we plan to implement ourselves, but would gladly review a PR. Thanks! :smile:

**Comment by SShrike** [comment]
@sethvargo I could try and work on it, could you give me some pointers towards what part of the code I should look at?

**Comment by kwbr** [comment]
As a temporary solution one could override the default path by setting `VAGRANT_HOME`.

`export VAGRANT_HOME=$XDG_DATA_DIR/vagrant`

**Comment by jleclanche** [comment]
@SShrike Still want to work on it?

This needs to be modified here:

https://github.com/mitchellh/vagrant/blob/1f2616a03cbd018dd06d2379f4d0c532991554a7/lib/vagrant/shared_helpers.rb#L95-L110

You will also need to potentially update this:
https://github.com/mitchellh/vagrant/blob/6c83743980bb34dfe713769957a80d763cf442cf/lib/vagrant/util/platform.rb#L328-L362

And finally, if that happens, updating bash completions would be useful:
https://github.com/mitchellh/vagrant/blob/258a58bcae266ccce66f3ac41f4e35a4f29bb220/contrib/bash/completion.sh#L66-L71

I don't think this would be a big PR to do.

**Comment by SShrike** [comment]
@jleclanche I don't currently use Vagrant, but perhaps when I have some free time I could take a stab at it.

**Comment by jleclanche** [comment]
That'd be great! It's such an annoyance (and a shame the issue was closed :().
