### ISSUE TITLE
[error] vagrant ssh timeout on debian

### ISSUE THREAD

**Issue by ghost** [mitchellh/vagrant#7057]
`vagrant 1.8.1`
`debian 8.3 amd64` - host
`ubuntu trusty 32` - guest

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"
end
```
### Expected behavior

boxed `bash` session started
### Actual behavior

timeout error
### Steps to reproduce
1. vagrant init ubuntu/trusty32
2. sudo vagrant up
3. sudo vagrant ssh

**Comment by sethvargo** [comment]
Hi @a93ushakov 

Thank you for opening an issue. Are you able to reproduce this using the `hashicorp/precise64` box? I'm trying to understand if this is a box-issue or a Vagrant issue. Thanks!

**Comment by a93ushakov** [comment]
Thanks for reply, @sethvargo .

My laptop have not hardware virtualization support - so, I can use inly 32 bit boxes.

I had try to up & ssh to `hashicorp/precise32` and I got this output
```sh
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: VirtualBox VM is already running.
ssh_exchange_identification: read: Connection reset by peer

$ sudo vagrant up --provider virtualbox ; sudo vagrant ssh                                         
Bringing machine 'default' up with 'virtualbox' provider...
==> default: VirtualBox VM is already running.
ssh_exchange_identification: read: Connection reset by peer
```
and nothing happened.

**Comment by ajford** [comment]
I'm experience the same problem on Debian 7.6.

I've had the same problem using Vagrant 1.6.5 with vbox 4.3.32  (4.3.32-dfsg-1+deb8u2). I upgraded both, and am experiencing it with Vagrant 1.8.1 and Vbox 5.0.14 (5.0.14-105127~Debian~wheezy). 

I've used `puppetlabs/centos-7.2-64-nocm`, `boxcutter/centos72`, and `box-cutter/centos64-i386`. I used the centos64 box with no trouble back in Oct 2014, but attempting to `vagrant up` the box causes the same ssh timeout problem. 

I'm currently downloading `hashicorp/precise64` to test it out, and will update when it's done.

**Comment by a93ushakov** [comment]
I upgrade `virtualbox` to 5.0.14 - the same error:
```sh
a93ushakov@debian:~/vagrant$ vagrant up && vagrant ssh
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty32' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty32'
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty32
==> default: Adding box 'ubuntu/trusty32' (v20160224.0.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty32/versions/20160224.0.0/providers/virtualbox.box
==> default: Successfully added box 'ubuntu/trusty32' (v20160224.0.0) for 'virtualbox'!
==> default: Importing base box 'ubuntu/trusty32'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty32' is up to date...
==> default: Setting the name of the VM: vagrant_default_1456912569835_68476
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by a93ushakov** [comment]
I found the solution - but it doesn't deny `vagrant` bug.
https://gist.github.com/a93ushakov/d245f7c6fe51462416e9

**Comment by chrisroberts** [comment]
Gist is no longer available as user is deleted. Will try and repro this, but if anyone has more information on this, that would be great.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
