### ISSUE TITLE
Test for updated box before importing

### ISSUE THREAD

**Issue by jmnavarrol** [mitchellh/vagrant#7062]
Running vagrant 1.7.4 on Debian 7 "Wheezy".

As of now, when running `vagrant up [box]`, vagrant first imports it and then checks if there's any newer version for the box.

Given that big windows guests can take quite a long time to be imported, just to discover there's a new version avaliable, I suggest testing for updates first and asking what to do in case of new version found.  i.e.:

```
$ vagrant up myvm
==> myvm: have version '1.0.0'. The latest is version '1.0.1'
    myvm: Do you want me to Continue, update, abort? [C/u/a]
```

I don't think stopping the process for asking what to do is too cumbersome since you can alwasy set config.vm.box_check_update to FALSE to avoid it.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for almost a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
