### ISSUE TITLE
chef provovisioners node_name does not default to hostname

### ISSUE THREAD

**Issue by b-dean** [mitchellh/vagrant#7063]
The [Vagrant documentation about chef provisioners node_name](https://www.vagrantup.com/docs/provisioning/chef_common.html#node_name) states:
> By default this will be your hostname.

It does _not_ actually default to the node name.

### Vagrant version
1.8.1

### Host operating system
Ubunut 14.04

### Guest operating system
CentOS 6.7

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  config.vm.define :foo do |c|
    c.vm.box = 'bento/centos-6.7'
    c.vm.hostname = 'foo.example.com'
    c.vm.provision :chef_zero do |chef|
      # add recipes and whatnot
    end
  end
end
```

### Expected behavior
`/tmp/vagrant-chef/client.rb` should have 
```ruby
node_name "foo.example.com"
```

### Actual behavior
`/tmp/vagrant-chef/client.rb` has
```ruby
node_name "vagrant-9ec453db"
```

### Steps to reproduce
1. `vagrant up`
2. `vagrant ssh`
3. `cat /tmp/vagrant-chef/client.rb`

### References
@sethvargo, @mitchellh It seems like mitchellh/vagrant#6555 causes the `node_name` to be generated randomly. I don't know if it ever set this correctly from the `hostname`, but it certainly doesn't now.  

A workaround is to just specify the node name in the provisioner: 

```ruby
c.vm.provision :chef_zero do |chef|
  chef.node_name = "foo.example.com"
  # add recipes and whatnot
end
```
This is particularly important for multi-vm Vagrantfiles where you may have recipes that use node searches to find information about other nodes by node name.

**Comment by nulogyian** [comment]
Thanks for flagging this, @b-dean  
One of my colleagues ran into the same behaviour - it was nice to quickly find a confirmation.
