### ISSUE TITLE
Problem with curl in windows server 2012

### ISSUE THREAD

**Issue by marranz** [mitchellh/vagrant#7065]
Hi

Here running vagrant cmd in windows 2012 (Don't ask why, i'm not happy with the solution)

The thing is that when trying to init a box, i got errors when trying to download the box.

> $ vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
>     default: Box Provider: virtualbox
>     default: Box Version: >= 0
> The box 'hashicorp/precise64' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Atlas, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> 
> URL: ["https://atlas.hashicorp.com/hashicorp/precise64"]
> Error:

When running curl.exe from the cmd line there is an appcrash.

I tried to use cygwin to debug the problem. When running curl.exe with cygwin:

> C:/HashiCorp/Vagrant/embedded/bin/curl.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

I Solved the problem copying the curl.exe installed by cygwin (/usr/bin/curl.exe) to the Hashicorp\Vagrant\embedded\bin directory.

**Comment by sethvargo** [comment]
Hi @marranz 

Thank you for opening an issue. There is another issue tracking curl problems in Vagrant 1.8 on Windows. I can't find it right now, but it's marked to be fixed for the next release.
