### ISSUE TITLE
Default Sync Disabled When Rsync Enabled

### ISSUE THREAD

**Issue by darkn3rd** [mitchellh/vagrant#7069]
Using Rsync seems to disable default `/vagrant` mount using Vbox tools.  This behavior seems new in 1.8.1, and doesn't seem to reproduce on 1.7.4.

### Use Case

Why I need both? My provisioning shell scripts source the original private key, so that systems can easily ssh into each other with the `vagrant` account.   As the keys may not be there yet due to the order in which systems are created.  I generate a ssh config with a path that uses `/vagrant`, so that I can access the keys that are available at a later point.

Normally, I would stay with that solution, but some node libraries require symlinks, which don't work on the mounted directory in WIndows, so I have to rsync the source code, then build on a local Linux file system that supports symlinks.

### Vagrant version
* Vagrant 1.8.1

### Host operating system
* OS X 10.11 El Capitan

### Guest operating system
* Ubuntu 14 Trusty Tahr - current `ubuntu/trusty64`

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

time = Time.now.strftime("%Y%m%d%H%M%S")

#### FETCH HASH OF IPADDRESSES
begin
   file = open("configVagrant/global.json")
 rescue StandardError=>e
   puts "Error: #{e}"
 else
   json = file.read
   nodes = JSON.parse(json)['ipaddr']
end

Vagrant.configure("2") do |config|
  nodes.each do |nodename, ipaddr|
    config.vm.define nodename do |node|
      node.vm.box = "ubuntu/trusty64"
      node.vm.hostname = "#{nodename}"
      node.vm.network "private_network", ip: ipaddr
      node.vm.provider("virtualbox") { |vbox| vbox.name = "#{nodename}_#{time}" }

      case nodename
      when /postgres/
        node.vm.network "forwarded_port", guest: 5432, host: 5432
      when /bloodhound/
        node.vm.network "forwarded_port", guest: 3004, host: 3004
         node.vm.synced_folder ".", "/home/vagrant/bloodhound", type: "rsync",
           rsync__exclude: [".git/", "node_modules/", "logs/", "npm-debug.log"],
           rsync__args: ["--verbose", "--rsync-path='sudo rsync'", "--archive", "--delete", "-z"]
      end

      # Provision
      node.vm.provision "shell", path: "configVagrant/setup-all.sh"  # ssh convenience
      node.vm.provision "shell", path: "configVagrant/postgres.sh"  if nodename =~ /postgres/
      node.vm.provision "shell", path: "configVagrant/bloodhound.sh"  if nodename =~ /bloodhound/
    end
  end
end
```

```javascript
{
  "ipaddr": {
    "postgres": "192.168.50.2",
    "bloodhound": "192.168.50.3"
  }
}
```

### Debug output

Can gist it if needed, prefer to keep details of code repo (sync'd files icognito).

### Expected behavior
The VBox guest editions should mount `.` to `/vagrant` in the guest.  This is what happens with Vagrant 1.7.4.  It seems that rsync disables the default behavior.

### Actual behavior
The default directory `.` is not mounted as `/vagrant`.

**Comment by den-is** [comment]
+1
Running Vagrant 1.8.1 on Fedora 23x64 with virtualbox provider
no /vagrant folder synced
because of that have to indicate `ansible.provisioning_path = "/home/vagrant/sync/config"`

Vagrantfile
```ruby
# -*- mode: ruby -*-
# # vi: set ft=ruby :

HOSTNAME = "devbox"
Vagrant.configure(2) do |config|
  
  config.vm.define HOSTNAME do |node|
    config.vm.box = "centos/7"
    node.vm.hostname = HOSTNAME

    config.vm.provision "shell" do |sh|
      sh.inline = "yum install -y -q -e0 -d0 epel-release"
    end

    config.vm.provision "ansible_local" do |ansible|
      ansible.provisioning_path = "/home/vagrant/sync/config"
      ansible.playbook = "provision.yml"
    end

  end

end
```

**Comment by darkn3rd** [comment]
I doubt that because when I add the following below, shared folders work in addition to rsync:

```ruby
         node.vm.synced_folder ".", "/vagrant", disabled: false
```

**Comment by sethvargo** [comment]
Hi @darkn3rd 

Thank you for opening an issue, and I'm sorry this is causing you problems. Unfortunately this was actually a bug in Vagrant in the past that was _fixed_, but it looks as though you might have been depending on the broken behavior for your use case. Sorry about that :frowning:. Since this is the intended behavior, my recommendation is to add this to you Vagrantfile:

```ruby
config.vm.synced_folder ".", "/vagrant", disabled: false
```

If you have a lot of Vagrantfiles, you can put this in a ~/.vagrant.d/Vagrantfile and it will get picked up with merge ordering. Thanks! :smile:

**Comment by vhosakot** [comment]
When I did `vagrant up` with the box `centos/7 (virtualbox, 1703.01)`, `==> default: Rsyncing folder: /root/ => /vagrant` was stuck for me too, and adding
`config.vm.synced_folder '.', '/vagrant', disabled: true`
in Vagrantfile resolved the issue for me and rsync did not happen.
