### ISSUE TITLE
Vagrant box is taking old username after changing username directory

### ISSUE THREAD

**Issue by sdavara** [mitchellh/vagrant#7071]
### Vagrant version
1.7.4

### Host operating system
OS X Yosemite

### Guest operating system
Using homestead box (https://atlas.hashicorp.com/laravel/boxes/homestead)

### Debug output
```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'laravel/homestead'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/Users/shailesh/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "homestead_1456301914083_23136", "--vsys", "0", "--unit", "8", "--disk", "/Users/kirtirupapara/VirtualBox VMs/homestead_1456301914083_23136/box-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /Users/bhumika/.vagrant.d/boxes/laravel-VAGRANTSLASH-homestead/0/virtualbox/box.ovf...
OK.
0%...
Progress state: VBOX_E_IPRT_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the directory '/Users/sd/VirtualBox VMs/homestead_1456301914083_23136' (VERR_ACCESS_DENIED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component Appliance, interface IAppliance
VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 779 of file VBoxManageAppliance.cpp
```

### Expected behavior
It should run without any problem as I've installed vagrant and virtualbox again after renaming user name.

### Actual behavior
I don't understand where does it take old username value

### Steps to reproduce
1. create a new user in your system
2. delete already running user
3. use existing files of previous user by renaming it to current new user name

I've already removed boxes and virtual boxes in existing systems. Also, updated code of homestead box, generated homestead.yaml new etc.

**Comment by sethvargo** [comment]
Hi @sdavara 

It is not currently possible to "move" Vagrant VMs. The internal state (in the `.vagrant` directory) contains absolute paths, and, unfortunately, we cannot use relative paths for various reasons. 

Can you try deleting the `.vagrant` directory in your project root and run `vagrant up` again?

**Comment by sdavara** [comment]
hi @sethvargo,

I tried deleting all files of .vagrant folder, but I'll try your suggestion of deleting that folder.

**Comment by sethvargo** [comment]
Hi @sdavara 

Please report back.

**Comment by sdavara** [comment]
hi @sethvargo

It didn't work.

**Comment by sethvargo** [comment]
Hi @sdavara 

Upon further investigation, this appears to be an issue with Virtualbox (https://www.virtualbox.org/ticket/10785). Unfortunately there's nothing that Vagrant can do here :frowning:

**Comment by dahousecat** [comment]
Update the file ~/.config/VirtualBox/VirtualBox.xml with your new username.

**Comment by Radioreve** [comment]
> Update the file ~/.config/VirtualBox/VirtualBox.xml with your new username.

Been looking for this for hours, thank you so much!
