### ISSUE TITLE
Docker provisioner doesn't allow provisioning when container name is specified

### ISSUE THREAD

**Issue by davidharrigan** [mitchellh/vagrant#7074]
When I run `vagrant provision` on my Vagrantfile which runs docker provisioner, docker raises an error saying the container name already exists. 

When taking a look at the [source code](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/docker/client.rb), it looks like it’s failing on `container_exists?` call - which calls `lookup_container` and tries to create a new one every time.  I tried the bash command that it tries to call - one of the flags is using `-notrunc`, which has changed to `—no-trunc` and I’m suspecting that’s why it’s failing.

### Vagrant version
```
Vagrant 1.8.1
```

### Host operating system
```
OS X El Capitan (10.11.2) 
```

### Guest operating system
ubuntu/trusty64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

DIR = File.dirname(__FILE__)


Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "ubuntu-vm"
    config.vm.network :private_network, ip: "192.168.100.120"

    config.vm.provider "virtualbox" do |v|
        v.gui = false
        v.customize ["modifyvm", :id, "--memory", "1024"]
        v.customize ["modifyvm", :id, "--cpus", 1]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    config.vm.provision "docker" do |docker|
        image = "cassandra:2.1"
        container_name = "cass"
        run_args = "-p 7000:7000 -p 7001:7001 -p 9042:9042 -p 9160:9160"

        docker.run container_name, image: image, args: run_args
    end
end
```

### Debug output
https://gist.github.com/davidharrigan/5dd77783acd352dac6ae

### Expected behavior
Remove existing container and create a new one.

### Actual behavior
Provision fails because container with the same name already exists.

### Steps to reproduce
1. vagrant up
2. vagrant provision

**Comment by kamigerami** [comment]
I am not able to consistently reproduce this issue (tested on Vagrant 1.8.1 and 1.8.2 (El capitan OSX) )

**Comment by davidharrigan** [comment]
Thank you @kamigerami!
