### ISSUE TITLE
[Enhancement] lining up vagrant commands

### ISSUE THREAD

**Issue by ynk** [mitchellh/vagrant#7077]
Hi,

It seems the basic commands of vagrant are doing many things together, which is great for ease etc ; but a thiner control should be available imho.

Today we have : `vagrant up` which does `import`, `start`, `provision` ; only the `provision` command is available separately, which means there's no way to run the deploy process of vm instance base files separately. The same way, there is no `vagrant down` which could combine `vagrant halt` and `vagrant destroy`. **I'd like to know if filling the voids would make sense.**

_Creation lifecycle_ :

import | start |        provision          |   shortcut
---------|--------|---------------------------|-----------------
    ø    |    ø    | `vagrant provision` |  `vagrant up`

_Destruction lifecycle_ :

cleanup |       halt          |         destroy         |                  shortcut
-----------|-------------------|-------------------------|------------------------------------------
     ø      | `vagrant halt` | `vagrant destroy` | `vagrant destroy -f` (somehow)

The todo would be :

- `vagrant import` (replace `vagrant init` ?) : Create base files into VM manager _only_
- `vagrant start` (`vagrant boot` ?) : Boot-up the VM instance _only_
- `vagrant cleanup` : do the cleanup tasks for provisioners _only_

Hope my 2 cents will be appreciated.

Julien

PS : this actually feeds a purpose in a task i'm coding ; i use vagrant-triggers to insert script during vagrant lifecycle and would need to insert one *after* creating the base files and *before* booting up the box as for using `vboxmanage` to create and mount rawdisk to my vm.

**Comment by sethvargo** [comment]
Hi @ynk 

Thank you for opening an issue. There are a number of closed issues around `vagrant down` you can search where we explain why we've avoided the command. In short - everyone's interpretation of "down" is slightly different, and "destroy" already encapsulates "halt". It is very unlikely we will add a "down" command, and it's not possible to "destroy" a machine without first stopping it.

Cleanup tasks are a real thing, and they are being tracked here: https://github.com/mitchellh/vagrant/issues/2538.

- "vagrant import" is "vagrant box add". In most providers, it's not possible to _just_ import a box without starting it (think AWS for example)
- "vagrant start" is "vagrant up", but it also intelligently downloads and imports the box if it does not already exist
- "vagrant cleanup" will likely not be its own command, but it will be executed when the linked ticket above is implemented.

Finally, keep in mind that Vagrant drives more than just VMs - it can drive AWS instances, etc. As a result, we have to choose verbs that also match those use cases. For your use case in particular, I do not think it's possible to insert files onto a VM before it's booted. You can mount them in a shared folder pre-boot, but Vagrant already has that functionality.

Thank you for the detailed feedback - we will definitely keep this in mind as we continue to improve the UX of Vagrant, but we are not ready to make this kind of sweeping API change yet. As such, I'm going to close this issue, but we are happy to continue the discussion. If there are action items we can do to enhance your particular use case, please let us know. Thanks and have a great day! :smile:
