### ISSUE TITLE
cannot upgrade Vagrant on Windows when previous kit is missing

### ISSUE THREAD

**Issue by sorin-costea** [mitchellh/vagrant#7080]
I cannot uninstall Vagrant 1.7.2 on Windows 7 (thus cannot upgrade - as it does an uninstall first) because I don't have the old kit anymore and the uninstall routine mandates it.
This is not usual on a Windows platform - uninstall is expected to uninstall, by using information from the MSI database, registry or the application's own folders (aka - no old kit should be needed).

**Comment by sethvargo** [comment]
Hi @sorin-costea 

Thank you for opening an issue. Unfortunately I talked with the team and we are confused by your question. What "kit" are you referring to? You can upgrade Vagrant by simply re-running the installer (it does not uninstall the old version, it just overwrites it).

**Comment by sorin-costea** [comment]
Here are my steps (Windows 7 x64):
-installed a version some months ago
-deleted the installation kit from the download dir
-last week decided to upgrade, so downloaded the latest installation kit
-started the installation, it detected there's an older install and asked
for the old installation kit (the one downloaded a while back)
Try yourself the upgrade but FIRST remove the old kit.
Maybe it's a problem of the old kit, now fixed?

**Comment by sethvargo** [comment]
Hi @sorin-costea 

Thank you for your reply. What do you mean by "kit"? Vagrant does not have a kit. Are you downloading the installer from https://www.vagrantup.com/downloads.html?

**Comment by sorin-costea** [comment]
Yes, that one.
How should I call the MSI (for Windows) or RPM (for RedHat Linux) etc, if
not installation kits?

**Comment by sethvargo** [comment]
Hi @sorin-costea 

The installer should not be asking for an old installer version. Everything is backwards compatible. Could you please try upgrading and send me a screenshot of the error you're seeing?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄

**Comment by sorin-costea** [comment]
You're right to close it. Something was broken with my Windows MSI database - ALL uninstalls were behaving the same so I did some admin cleanup and all was fine. 
Thank you for your patience!

**Comment by amadeus-chuot** [comment]
I'm experimenting the same issue. Cannot upgrade vagrant since the old .msi is missing.
How did you fixed the issue?
