### ISSUE TITLE
chef-zero privisioner weird result

### ISSUE THREAD

**Issue by kzw** [mitchellh/vagrant#7087]
Despite the Vagrantfile at the bottom, I am getting cookbook not found error (for inhouse cookbooks).  It only works when I symlink cookbooks path like this

`ln -s /path/to/cookbooks /where/vagrantfile/is/located`

Other stuff like `enironments`, `roles` do not need this hack

# Vagrantfile
```
Vagrant.configure(2) do |config|
  config.vm.box = "file://~/peloton-vagrant.tgz"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.base_mac = "080027A84C38"
  config.berkshelf.enabled = true
  chef_repo = '~/chef-repo'
  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = File.join(chef_repo, 'cookbooks')
    chef.data_bags_path = File.join(chef_repo, 'data_bags')
    chef.environment = 'build'
    chef.environments_path = File.join(chef_repo, 'environments')
    chef.roles_path = File.join(chef_repo, "roles")
    chef.encrypted_data_bag_secret_key_path = '/Users/kzwin/.chef/encrypted_data_bag_secret'
    chef.add_role "jenkins-api"

  end
end
```

**Comment by sethvargo** [comment]
Hi @kzw 

It looks like you are using the vagrant-berkshelf plugin. Can you please uninstall all plugins and try to reproduce this issue without the berkshelf plugin?

**Comment by kzw** [comment]
@sethvargo I can confirm this does not happen if vagrant-berkshelf plugin is removed.  So is it chef or vagrant that is now confused about where to get home made cookbooks?

**Comment by sethvargo** [comment]
Hi @kzw 

Unfortunately I do not know the root cause, but it appears to be related to vagrant-berkshelf, not Vagrant. I would recommend opening an issue there or perhaps posting on the Chef mailing list. Thanks! :smile:
