### ISSUE TITLE
Better CLI commands

### ISSUE THREAD

**Issue by macx** [mitchellh/vagrant#7094]
Whenever I want so start or stop vagrant, I have to use the cli commands `up` and `halt` and not the commands I have in mention: `start`and `stop`. Why no providing alias commands?

![2016-03-02 at 12 02 pm](https://cloud.githubusercontent.com/assets/84112/13458744/65b81144-e06f-11e5-8064-fa3897810b03.jpg)

Using: 1.8.1

**Comment by sethvargo** [comment]
Hi @macx 

There are a number of closed issues you can search through that explain the reason Vagrant uses these verbs. In short, the notion of "stop" has multiple meanings in the context of VMs (do you want to save the VMs current state and release its resources or do you want to terminate the VM and all resources), whereas "halt" has a very clear meaning. Thank you for opening an issue, but this is not something that we plan to change in Vagrant. Thanks! :smile:
