### ISSUE TITLE
Networking connectivity broken after 'vagrant reload'

### ISSUE THREAD

**Issue by ericpromislow** [mitchellh/vagrant#7096]
### Vagrant version
Vagrant 1.8.1 - same version on both hosts

### Host operating system
Both: Linux 
Linux matador 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

OSX: OSX 10.11.3

### Guest operating system
This is the operating system you run in the virtual machine.
Linux hcf-vagrant 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.network "private_network", ip: "192.168.77.77"

  config.vm.provider "virtualbox" do |vb, override|
    override.vm.box = "https://on.a.private.network.net:PORT/..."
    # Customize the amount of memory on the VM:
    vb.memory = "6144"
    vb.cpus = 4
    override.vm.synced_folder ".x/.y", "/home/vagrant/.y"
    override.vm.synced_folder ".", "/home/vagrant/z"
  end

  unless OS.windows?
    config.vm.provision "shell", inline: <<-SHELL
        if [ ! -e "/home/vagrant/z/src/w/.git" ]; then
          echo "Looks like the w submodule was not initialized" >&2
          echo "Did you run 'git submodule update --init --recursive'?" >&2
          exit 1
        fi
    SHELL
  end

  config.vm.provision :reload

  config.vm.provision "shell", inline: <<-SHELL
    set -e

    # Configure Docker things
    sudo /home/vagrant/z/bin/docker/configure_docker.sh /dev/sdb 64 4
    /home/vagrant/z/bin/docker/setup_network.sh "172.20.10.0/24" "172.20.10.1"

    # Install development tools
    /home/vagrant/z/bin/dev/install_tools.sh

    mkdir -p /home/vagrant/tmp

    chown vagrant /home/vagrant/bin
    chown vagrant /home/vagrant/bin/*
    chown vagrant /home/vagrant/tools
    chown vagrant /home/vagrant/tools/*
    chown vagrant /home/vagrant/tmp
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    set -e
    echo 'source ~/z/bin/.x' >> .profile
    echo 'source ~/z/bin/.runrc' >> .profile

    echo 'export PATH=$PATH:/home/vagrant/z/bin/' >> .profile
    echo "alias z-status-watch='watch --color z-status'" >> .profile
  SHELL

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    # Start a new shell to pick up .profile changes
    set -e
    cd /home/vagrant/z
    make copy-compile-cache

    echo -e "\n\nAll done - you can \e[1;96mvagrant ssh\e[0m\n\n"
  SHELL
end

module OS
  def OS.windows?
      (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
  end
end

```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. Do NOT paste the debug
output in the issue, just paste the link to the Gist.

There's no output. A step that was supposed to download blobs from s3 was doing nothing.
It might help that this step was run from a docker container running on the vagrant box.  Its main process was something like 'bash -l "rbenv global 2.2.3 && bosh create release ..."'. When I docker-execed
in ps showed '[bosh] <defunct>' and the bash step was sleeping waiting for something (namely the bosh process, which was sleeping for what looked to be forever.

### Expected behavior
Many blobs happily get downloaded.

### Actual behavior
What actually happened?
See !-2.

### Steps to reproduce
Create a docker image that runs a script that downloads large files from S3.  Do 'docker run' on that in a new vagrant VM.  Now try in a vagrant-reloaded VM. If you can reproduce this bug, the first try works and the second fails.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
None that I found.

**Comment by sethvargo** [comment]
Hi @ericpromislow 

Thank you for opening an issue. Unfortunately there is not enough information here to reproduce the issue. The Vagrantfile you have provided is incomplete and we cannot bring up a similar environment without access to the scripts and box. Additionally, there is always debug output. If you follow the steps linked in the issue template, you can enable debug mode and gist that output. Finally, there are many moving pieces here, and I am not convinced the issue is coming from Vagrant itself. You have Docker, Bosh, Vagrant, Virtualbox, and your local network as variables all in the mix. Are you able to reduce this to just a vanilla Vagrantfile?

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a _new issue_ and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
