### ISSUE TITLE
Multi-machine, multi-vm Vagrantfile

### ISSUE THREAD

**Issue by brianbruggeman** [mitchellh/vagrant#7097]
I'm using vagrant 1.7.2

I have something like the following Vagrantfile:

    ...
    Vagrant.configure(2) do |config|
        ...
        config.vm.define "app" do |app|
            # setup app here
            ...
            config.vm.provider :virtualbox do |vbox, override|
                # setup virtualbox for app vm here
                ...
            end
            ...
            config.vm.provider :aws do |aws, override|
                # setup aws for app vm here
                ...
            end
        end
        ...
        config.vm.define "pg" do |pg|
            # setup postgres here
            ...
        end
    ...
    end

The thing is, I only want the 'app' on EC2, and I want to simulate both app and postgres on my local box.

How do I do that?

**Comment by sethvargo** [comment]
Hi @brianbruggeman 

Thank you for opening an issue. We prefer to keep the issue tracker reserved for bug reports and feature requests. For usage-related questions, please use the Vagrant mailing list or IRC channels: https://www.vagrantup.com/community.html. Thanks! :smile:

**Comment by brianbruggeman** [comment]
At a minimum, wouldn't my question warrant more documentation?
