### ISSUE TITLE
Unable to setup laravel/homestead with vagrant - ==> default: stop: unknown instance

### ISSUE THREAD

**Issue by ShahnawazAli93** [mitchellh/vagrant#7100]
Unable to setup laravel/homestead with vagrant
Error ==> default: stop: unknown instance
and then I can't visit the application.dev in browser but the is able to ping the machine

### Vagrant version
1.8.1

### VirtualBox version
5.0.14

### Host operating system
MS Windows 10

### Guest operating system
Ubuntu (64 bit)

### Homestead Box Version
0.3.0 (also tried with 0.2.7 and 0.4.x)

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

path = "#{File.dirname(__FILE__)}"

require 'yaml'
require path + '/scripts/homestead.rb'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  Homestead.configure(config, YAML::load(File.read(path + '/Homestead.yaml')))
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
end
```

### Debug output
windows host file: https://gist.github.com/ShahnawazAli93/d38ee2cda6875d608ff2
homestead.yaml: https://gist.github.com/ShahnawazAli93/70baded8d6645b4f39a1
ssh key files: https://www.dropbox.com/s/vjbwsn6oc37t4ni/ssh%20files.png?dl=0
vagrant up output: https://www.dropbox.com/s/vhbulmqj4kl51yk/vagrant%20up%20-%20output.png?dl=0

### Expected behavior
After running 'vagrant up', the machine should have properly setted up and the host can open application.dev in browser
- in my host file, I have added the following line
192.168.10.10 application.dev

### Actual behavior
I am unable to open application.dev in my browser but I can ping 192.168.10.10

**Comment by sethvargo** [comment]
Hi @ShahnawazAli93 

Thank you for opening an issue. Unfortunately we are unable to support homestead because we are not experts on that plugin. Are you able to reproduce this issue with a generic Vagrantfile (no homestead)?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄
