### ISSUE TITLE
upgrade vagrant 1.8.1 fails on windows 10 x64

### ISSUE THREAD

**Issue by langdead** [mitchellh/vagrant#7106]
Hi,
I got following error after upgrading vagrant from 1.7.4 to 1.8.1.

```
d:\work\coreos-vagrant>vagrant up
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:59:in `require': cannot load such file -- childprocess (LoadError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:59:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `<main>'

d:\work\coreos-vagrant>vagrant -v
Vagrant 1.8.1
```

Steps I tried:
- executing the install package from vagrant download page. Assuming it will do the upgrade properly, but `vagrant up` broke.
-  uninstall the vagrant from program panel, then install again. Still the same.

Don't know whether this relates to [https://github.com/mitchellh/vagrant/issues/648] as it reported childprocess issue. I didn't debugger further as I have no ruby installed directly and have few ruby experience.

**To update:**
- downgrading to vagrant 1.8.0 has the same problem on my laptop.
- reverting to vagrant 1.7.4 breaks with following error. If I remembered correctly, this was the reason why I started to upgrade to 1.8.*. Before the error appeared suddenly last week, vagrant already worked without problem on my laptop for several months. I tried different projects' Vagrantfile, getting the same problem. So it would not be caused by my local corrupted Vagrantfile.

```
d:\work\github\flynn\demo>vagrant up
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:225:in `inspect': inspected result must be ASCII only or use the same encoding with default external (Encoding::CompatibilityError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:225:in `inspect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:225:in `inspect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:225:in `inspect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:225:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/up/command.rb:74:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:275:in `tap'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:275:in `block in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:274:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:274:in `batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/up/command.rb:58:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'

d:\work\github\flynn\demo>vagrant -v
Vagrant 1.7.4
```

Thanks very much in advance!

Regards
Langdead

**Comment by sethvargo** [comment]
Possible related to #5896

**Comment by sethvargo** [comment]
Hi @langdead 

Thank you for opening an issue. Could you please share your complete Vagrantfile and the output of the command's [debug output](https://www.vagrantup.com/docs/other/debugging.html) in a gist? Thanks!

**Comment by langdead** [comment]
Hi @sethvargo 
Thanks for your response! Please check the debug log at https://gist.github.com/langdead/3049cfe24298464c2425

The Vagrantfile is the standard https://github.com/coreos/coreos-vagrant

In the debug log, the encode changed from ANSI to UTF-8. ANSI encoding shows my Chinese name correctly before line 360, while UTF-8 encoding shows it as expected after line 360.
Thanks in advance! And nice day!

**Comment by sethvargo** [comment]
Ah. Definitely an encoding issue then. Tagging in #5896.

We bumped the Ruby version between those Vagrant releases.

**Comment by langdead** [comment]
I see. Then I'll try changing my laptop's language to UNICODE to see whether vagrant works...

Good luck! You'll be appreciated if all the bunch of issues can be fixed asap. :)

**Comment by vinyar** [comment]
I found that installing `vagrant-azure` (or simply having it present prior to upgrade) triggers this for me.
deleting plugins.json is the only thing needed to fix this `mv ~/.vagrant.d/plugins.json ~/.vagrant.d/plugins.json_old `

**Comment by langdead** [comment]
Hi @vinyar, thx for your reply!
Unfortunately,trial showed that it didn't work for my case here.

**Comment by chrisroberts** [comment]
@langdead Can you confirm if you are still experiencing this behavior on the latest release of Vagrant? If so, can you please provide a gist of the `--debug` output. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
