### ISSUE TITLE
[Windows] [Installer] No icon in the Programs and Features Control Panel

### ISSUE THREAD

**Issue by Stanzilla** [mitchellh/vagrant#7111]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

-> 1.8.1
 
### Host operating system
This is the operating system that you run locally.

-> Windows

### Expected behavior
What should have happened?

-> There should be an icon and link to the website

### Actual behavior
What actually happened?

-> There is nothing

### Steps to reproduce
1. Install
2. Vagrant
3. On Windows

![explorer_2016-03-07_03-27-16](https://cloud.githubusercontent.com/assets/75278/13559443/8f15a314-e414-11e5-828f-6e2d7bcb40a8.png)

**Comment by sethvargo** [comment]
Hi @Stanzilla 

Thank you for opening an issue. This is actually a bug in the [vagrant installers](https://github.com/mitchellh/vagrant-installers). I've opened an issue over there to cross-link. Thanks!
