### ISSUE TITLE
Adding `.gui = true` causes `vagrant up` to fail`

### ISSUE THREAD

**Issue by juancferrer** [mitchellh/vagrant#7113]
The following Vagrantfile works fine on my machine (Windows 10):

```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
```

But this one fails:

```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
end
```

The error is:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "961dece0-12a2-4271-84b8-1595e8ec2f31", "--type", "gui"]

Stderr: VBoxManage.exe: error: Could not launch a process for the machine 'ruckit-dev-box' (VERR_UNRES
OLVED_ERROR)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface
IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.as
OutParam())" at line 589 of file VBoxManageMisc.cpp
```

```
> C:\Program Files\Oracle\VirtualBox\VBoxManage.exe' -v
5.0.16r105871
> vagrant -v
Vagrant 1.7.4
```

Notice how it's an almost copy of the referenced ticket below, except that i'm running a windows 10 HOST with a linux GUEST.  It was mentioned in the ticket to install the package `virtualbox-qt` in order to fix the issue.  But I'm running on a windows 10 HOST, and there's no package manager.  I just installed virtualbox by downloading the exe file from the virtualbox/oracle website.
### References
- GH-6823

**Comment by juancferrer** [comment]
Upgrading to vagrant 1.8.1 has made no difference.  same error.

**Comment by sethvargo** [comment]
Hi @juancferrer 

Thank you for opening an issue, and thank you so much for using the supplied issue template - it is very helpful for us. Unfortunately I am unable to reproduce this on my Windows 8 machine (I don't have handy access to a Windows 10 machine, but I will try to upgrade later).

To be clear, that error message is coming from Virtualbox, not Vagrant. After looking at some forums on the Internet and the vbox ticket tracker, it seems that one of the most common causes for this error is when the $PATH that contains the VM or PWD contains non-Roman characters. Is it possible that you are working in a directory that contains special characters (including spaces, parenthesis, or accents on your username)? This has traditionally been an issue with virtualbox on Windows.

For sanity sake, are you able to start a VM in GUI mode in vbox without Vagrant? This will help us narrow down if this is a Vagrant problem or a vbox problem. If it does reveal that additional packages or requirements are needed to use gui mode on Windows, we will gladly update the website and requirements. Thanks! :smile:

**Comment by juancferrer** [comment]
Hi @sethvargo 

I figured it was virtualbox.  The $PATH where I'm running the vagrant up command is `C:\Users\juanc\Documents\ruckit` no weird characters or anything, so I doubt it's that

Also, using the normal virtualbox interface, i can launch any VM I want with a GUI.  VMs that I've created myself, and even the ones that vagrant has created.  I can choose normal start, or headless, or detachable, and they all seem to work, I can click on stuff, etc...

```
C:\Users\juanc\Documents\ruckit [develop +0 ~1 -0]> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8000 (guest) => 8000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "961dece0-12a2-4271-84b8-1595e8ec2f31", "--type", "gui"]

Stderr: VBoxManage.exe: error: Could not launch a process for the machine 'ruckit-dev-box' (VERR_UNRESOLVED_ERROR)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 589 of file VBoxManageMisc.cpp

C:\Users\juanc\Documents\ruckit [develop +0 ~1 -0]> pwd

Path
----
C:\Users\juanc\Documents\ruckit
```

If I run vboxmanage with --type gui  directly I get the same errors:
```
C:\Program Files\Oracle\VirtualBox> .\VBoxManage.exe startvm 961dece0-12a2-4271-84b8-1595e8ec2f31 --type gui
VBoxManage.exe: error: Could not launch a process for the machine 'ruckit-dev-box' (VERR_UNRESOLVED_ERROR)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 589 of file VBoxManageMisc.cpp
```

And then I look here for the other allowed values for the type: https://www.virtualbox.org/manual/ch08.html#vboxmanage-startvm

And I try to use sdl, also same sort of error
```
C:\Program Files\Oracle\VirtualBox> .\VBoxManage.exe startvm 961dece0-12a2-4271-84b8-1595e8ec2f31 --type sdl
Waiting for VM "961dece0-12a2-4271-84b8-1595e8ec2f31" to power on...
VBoxManage.exe: error: The VM session was closed before any attempt to power it on
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface ISession
C:\Program Files\Oracle\VirtualBox> .\VBoxManage.exe startvm 961dece0-12a2-4271-84b8-1595e8ec2f31 --type gui
VBoxManage.exe: error: Could not launch a process for the machine 'ruckit-dev-box' (VERR_UNRESOLVED_ERROR)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MachineWrap, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 589 of file VBoxManageMisc.cpp
```

But if I try to run as headless, then it all works:
```
C:\Program Files\Oracle\VirtualBox> .\VBoxManage.exe startvm 961dece0-12a2-4271-84b8-1595e8ec2f31 --type headless
Waiting for VM "961dece0-12a2-4271-84b8-1595e8ec2f31" to power on...
VM "961dece0-12a2-4271-84b8-1595e8ec2f31" has been successfully started.
```

So yeah, maybe it's something to forward to the Virtualbox project??

**Comment by marcoacm** [comment]
Same problem here. Did you figure this out?

**Comment by chrisroberts** [comment]
This looks to be an upstream bug within VirtualBox. More information can be found here:

https://www.virtualbox.org/ticket/13187

Cheers!

**Comment by Danya2** [comment]
the same  error here  , do you solve this problem?

**Comment by travddm** [comment]
I've been getting the same exact error. Oddly, running VBoxManage.exe as Administrator works.

**Comment by inammathe** [comment]
Thanks @travddm , @ anyone running this via vscode terminal (user installation) I had to run the exe as admin for this to work. Found here usually: "C:\Users\you\AppData\Local\Programs\Microsoft VS Code\_\Code.exe"
