### ISSUE TITLE
private_key_path = $SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by pmoody-** [mitchellh/vagrant#7115]
Is it possible to add a feature to vagrant to allow it to use a key loaded onto an ssh agent rather than looking for a private key on disk?

We have a setup were we utilize keys that are only accessible via an ssh-agent on $SSH_AUTH_SOCK and I'd like to be able to use these keys with vagrant.

running Vagrant 1.8.1 on OSX 10.11.3 creating debian jessie and ubuntu precise ec2 instances.

Cheers,
peter

**Comment by sethvargo** [comment]
Hi @pmoody- 

Thank you for opening an issue. You can specify the `private_key_path` in the Vagrantfile (https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html), and since the Vagrantfile is just ruby, you can shell out to the system or use an envvar:

```ruby
config.ssh.private_key_path = ENV["PRIVATE_KEY_PATH"]
config.ssh.private_key_path = `ssh-agent...`
```

**Comment by pmoody-** [comment]
sorry for the late reply. what I'm actually trying to do is get vagrant to use an existing ssh-agent rather than spawn a new one. is this possible?
