### ISSUE TITLE
`vagrant box outdated` does not use exit codes

### ISSUE THREAD

**Issue by danielhoherd** [mitchellh/vagrant#7117]
`vagrant box outdated` does not use exit codes, which is non-standard and makes it slightly more difficult to interact with in shell scripts.

### Vagrant version
Vagrant 1.8.1

### Host operating system
OS X 10.11.3

### Debug output
https://gist.github.com/danielhoherd/7422f1814fc066798ead

### Expected behavior
Expect to have a non-zero return when the box is outdated for use with operators. EG: `vagrant box outdated || vagrant update`

### Actual behavior
Observed exit 0 for both outdated and non-outdated boxes which makes shell interpretation less canonical and more complex.

**Comment by sethvargo** [comment]
Hi @danielhoherd 

Thank you for opening an issue. While I understand how this could be confusing, I also think it would be confusing for other UXs. For example, let's say the `vagrant box outdated` command is unable to talk to the Internet. In that case, it _will_ return a non-0, but that result does not necessarily mean the box is outdated. As such, I think it's best if you use machine-readable output or just grep the result for keywords to script this. Does that make sense?

**Comment by danielhoherd** [comment]
@sethvargo That does make sense, but having a variety of exit codes is not unheard of. eg: nagios checks. I don't think exit codes and human readable output should be conflated, or that exit codes should be abandoned altogether. If we are going to require parsing of string output instead of relying on exit codes then we should have a machine readable status like `--json`.

**Comment by sethvargo** [comment]
Hi @danielhoherd 

All of Vagrant supports machine readable output: https://www.vagrantup.com/docs/cli/machine-readable.html

**Comment by danielhoherd** [comment]
@sethvargo oh, awesome! Even though I think exit codes would be great, this solves the issue. Many thanks for your responsiveness.
