### ISSUE TITLE
Folders not properly mounted - guest specific operations failed

### ISSUE THREAD

**Issue by sasos90** [mitchellh/vagrant#7125]
Hi guys!

I already posted the issue but since I couldn't reproduce the error, the issue was closed. Now I finally got the error back (unfortunately) which says like: "Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported."
The vps is working fine, but the folders are not properly mounted, so I can't mount them properly from my local.

Here is the issue template filled out.

### Vagrant version
Vagrant 1.8.1

### Host operating system
Linux Mint

### Guest operating system
Ubuntu Trusty 64bit

### Vagrantfile
http://laravel.io/bin/REMEe#

### Debug output
https://gist.github.com/sasos90/69918c5045f054db693a

### Expected behavior
It should mount the folder to /var/www in the VPS. Because it is not, mounted, my nginx can't find the path and it throws 404.

### Actual behavior
/var/www is empty.. because it is not mounted properly.

### Steps to reproduce
1. Just normal 'vagrant up' (or reload)

Thank you!

**Comment by sethvargo** [comment]
Hi @sasos90 

Thank you for opening an issue and completing the template. Unfortunately I'm still unable to use this to reproduce the issue. Laravel is a separate project that uses Vagrant under the hood. The file you supplied as a Vagrantfile is not a Vagrantfile, but instead a special laravel file that also links to configuration unavailable to me. 

Can you try the following Vagrantfile:

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/var/www"
end
```

**Comment by sasos90** [comment]
Hi @sethvargo !

I am not sure what do you mean about Laravel file? Don't be confused about laravel link. It's only a pastebin where my content of Vagrantfile is stored.

**Comment by sasos90** [comment]
Ok your Vagrantfile config works. So it should be something with my Vagrantfile perhaps.
What do you think it could be?

**Comment by sethvargo** [comment]
Hi @sasos90 

The file you linked to is not a Vagrantfile. A Vagrantfile should resemble the sample code I sent above. You are using laravel, which only drives Vagrant under the hood. There is probably something misconfigured in your YAML for laravel. Please open an issue on that project or use the community resources there.

**Comment by sasos90** [comment]
I would then say that it is the problem of puphpet generator or?

Thanks
