### ISSUE TITLE
Fix Rspec Tests

### ISSUE THREAD

**Issue by jjulien** [mitchellh/vagrant#7127]
`Rake.application.last_comment` was removed in Rake version 11 which came out today.
https://github.com/ruby/rake/commit/e76242ce7ef94568399a50b69bda4b723dab7c75#diff-53e46efb0e8e7ddcaa1826b1c508c756

The current version of `rspec` still uses `last_comment` but a PR has been merged to update to the newer `Rake.application.last_description`.
https://github.com/rspec/rspec-core/pull/2197

To get builds working we should pin to a rake version `< 11.0` until `rspec` can catch up.

**Comment by sethvargo** [comment]
Hi @jjulien 

Thank you for opening an issue. It looks like these are both upstream issues and the builds on travis are currently green, so it was either fixed upstream or currently a non-issue. Thanks :smile:
