### ISSUE TITLE
rsync__auto not working on windows 10 with freebsd 10.2 release guest.

### ISSUE THREAD

**Issue by happyme9** [mitchellh/vagrant#7128]
### Vagrant version

1.8.1
### Host operating system

Windows 10
### Guest operating system

freebsd/FreeBSD-10.2-RELEASE
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "freebsd/FreeBSD-10.2-RELEASE"
  config.vm.guest = :freebsd
  config.vm.synced_folder ".", "/vagrant", type: "rsync", 
    rsync__exclude: ".git/", 
    rsync__auto: true
  config.ssh.shell = "sh"
  config.vm.base_mac = "080027D14C66"
  config.vm.provision "shell", inline: <<-SHELL
     pkg upgrade -y
     pkg install -y wget gmake unrar gcc gdb git vim jansson mariadb55-server
  SHELL
end
```
### Expected behavior

Should sync automatically
### Actual behavior

Does not sync automatically nor give a confirmation that rsync__auto worked
### Steps to reproduce

1.Use my vagrant file on windows 10
2. change the local files or put a new file
3. check the changes on the guest via vagrant ssh
### References

Are there any other GitHub issues (open or closed) that should be linked here?
https://github.com/mitchellh/vagrant/issues/4862

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Comment by katin-dev** [comment]
@chrisroberts I still have this issue with `Windows 10`  and `vagrant  1.9.5` . I use `babun` to launch `vagrant`.

My `Vagrantfile` looks like
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.10.21"
  config.vm.synced_folder ".", "/var/www/dostavista", type: "rsync", rsync__exclude: [".git", ".idea"]
end
```

`vagrant rsync-auto` commad works well
