### ISSUE TITLE
Add validation_key_path to error message

### ISSUE THREAD

**Issue by clajoie** [mitchellh/vagrant#7131]
### Vagrant version

1.8.1
### Host operating system

OS X 10.11.3
### Guest operating system

bento/centos-6.7
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|

  config.vm.box = 'bento/centos-6.7'

  config.vm.provision 'chef_client' do |chef|
    chef.chef_server_url = 'https://example.com/organizations/development'
    chef.validation_client_name = 'development-validator'
    chef.validation_key_path = '/Users/clajoie/workspaces/chef-repo-dev/.chef/development-validator.pem'
    chef.delete_node = true
    chef.delete_client = true
    chef.node_name = 'test'
    chef.environment = 'development'
    chef.add_recipe 'test'
  end

end
```
### Debug output

https://gist.github.com/clajoie/f5f6bbfcc2899b70c987
### Actual behavior

The error message says the chef_client provisioner isn't able to find the validation key.  However the path to the key in the given Vagrantfile is accurate and readable.  While I can't find any other Vagrantfile in the search order, I'm wondering if there is something, somewhere, that is overriding this Vagrantfile and that's why I'm getting this error.

So, my request is that the error message be updated to also include the path the provisioner is using.

**Comment by clajoie** [comment]
I guess, in addition, another thing that would be nice (and maybe I'm just missing it in the debug output) would be to say exactly which Vagrantfile(s) are being used.

**Comment by clajoie** [comment]
So, on a lark, I tried changing from an absolute path to the key and a relative path.  That worked.

So, I guess the bug here is that validation_key_path can no longer accept absolute paths.

**Comment by sethvargo** [comment]
Hi @clajoie 

I just tested this a number of times, and it works each time. We use `File.file?` to check if the validation key file exists. I tried absolute and relative paths, and they all work fine.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
