### ISSUE TITLE
Vagrant resume always run provisioners

### ISSUE THREAD

**Issue by ifraixedes** [mitchellh/vagrant#7133]
I usually suspend my vagrant box; since I've updated it to version 1.8.x (I've tested with 1.8.0 and 1.8.1), each time that I resume the machine (`vagrant resume`), vagrant reload all the provisioners, when I was using 1.7.x I never had that issue and I tried to downgrade vagrant and still working as expected, so it looks that the changes in my machine shouldn't produce that different behaviour between 1.7.x and 1.8.x

I observed that if I resume the machine using `vagrant up`, then the provisioners aren't run; after I discovered that I can use `vagrant up` the issues is not very important, however now that I have more information about this expected behaviour, I thought that it may help to figure out what it's happening or may help to find other related issues.

Vagrant Version: Vagrant 1.8.1
Host OS: OSX El Capitan 10.11.13
Virtual Machine: Ubuntu server x64 Wily cloud image over VirtualBox (v5.0.16 r105871)
Vagrantfile: https://gist.github.com/ifraixedes/201a6f4e6dfdb85b6fcf

What should have happened? Not to run the provisioning each time I execute `vagrant resume`
What actually happened? It execute over and over the provisioning each time that I execute `vagrant resume`

**Comment by markpeek** [comment]
This looks like a dup of #6787 and should be fixed with PR #7059.

**Comment by ifraixedes** [comment]
@markpeek I think that you're right, it's the same issue, my only difference is that I can run `vagrant up` without any flag and it doesn't run any provisioner as I would expect of `vagrant suspend`.

I've closed it to stick the issue in the previous issue #6787 

Thanks.
