### ISSUE TITLE
Misleading error message for PSRemoting in a PSRemote Session

### ISSUE THREAD

**Issue by FloMcFly** [mitchellh/vagrant#7136]
Hi,

this is not exactly a bug, but when I run a PowerShell Remote Session to another machine (1), on which I run a vagrant machine, I got a misleading error message for "vagrant powershell"

![image](https://cloud.githubusercontent.com/assets/14224047/13729278/85b7ab88-e931-11e5-8aa0-05714d540e11.png)

The behaviour is expected (it is not possible to run a PSRemote Session in a PSRemote Session), but the Message should be like that:

![image](https://cloud.githubusercontent.com/assets/14224047/13729312/43867414-e932-11e5-82f6-d2a4bfd7e2f7.png)

### Vagrant version
1.8.1

### Host operating system
Windows 7 SP1 (x64)

### Guest operating system
Windows Server 2016 TP4 (Nano) ; VirtualBox VM

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "mwrock/WindowsNano"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", 
  #     inline: "Get-Service"
  #end
end

```

### Steps to reproduce
1. Machine1: Enter-PSSession Machine2
2. Machine2 (PSSession): vagrant powershell

**Comment by sethvargo** [comment]
Hi @FloMcFly 

Thank you for opening an issue. I think this might be a bug in WinRM, since the error messages are coming from WinRM and not Vagrant /cc @mwrock

**Comment by mwrock** [comment]
@FloMcFly would you ,mind providing a gist with the output of `vagrant powershell --debug` ? This should produce a stacktrace that will make it easier to track down the source of the error so we can provide better messaging in the correct place.

**Comment by FloMcFly** [comment]
@mwrock Sure, I will do.

**Comment by FloMcFly** [comment]
@mwrock https://gist.github.com/FloMcFly/fa819c6790d47ada31fc

**Comment by mwrock** [comment]
Thanks for that info @FloMcFly! It looks like this error is genuinely a case of being unable to determine the IP address of the vagrant box. It occurs before any WinRM connection is attempted while the communicator is trying to figure out what IP or hostname to point to.

I realized I can actually easily reproduce this in my own lab (should have realized that earlier before asking you to gather the output). If I am RDP'd into the vagrant host, everything works fine as you would expect.

If i ps remote to the vagrant host, I get the same result as you. What is interesting is that via RDP, `vagrant status` shows the vagrant box as running. Vis ps remoting, `vagrant status` reports the vagrant box is `powered off`. 

I don't necessarily think this is a bug in vagrant. VBoxManage itself states the machine is poweredoff from the `showvminfo` command. Of course the box actually is running. I'm guessing that something about the remote environment makes VBoxManage *think* the machine is not running. And if the machine is seen as not running, we cant find its IP.

**Comment by FloMcFly** [comment]
You're right, @mwrock . I saw the same output regarding the state of the vm. In this case the error message by vagrant is 100% correct: as you say, he cannot obtain the address, so he is not able to connect to the machine.
Thanks for your input :+1:
