### ISSUE TITLE
vagrant up displays error: SSH not up: An error occurred in the underlying SSH library that Vagrant uses

### ISSUE THREAD

**Issue by KurtRMueller** [mitchellh/vagrant#7141]
### Vagrant version

```
kurtr@DESKTOP-V7F3K9I ~/repos/vagrancy
$ vagrant -v
Vagrant 1.8.1
```

### Host operating system

``
Windows 10
cygwin64 terminal
``

### Guest operating system

```
# I have tried the following:
ubuntu/trusty64
hashicrop/precise64
centos/7
```
### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'

  config.vm.provider :virtualbox
  config.vm.synced_folder "~/repos", '/repos', type: 'virtualbox'

  config.vm.provision 'chef_solo' do |chef|
    chef.add_recipe 'yum'
    chef.add_recipe 'git'
    chef.add_recipe 'rvm'
    chef.add_recipe 'nodejs'
    chef.add_recipe 'python'

    chef.add_recipe 'tmux'
    chef.add_recipe 'vim'

    chef.json = {
      rvm: {
        user_installs: [{
          user: 'vagrant',
          default_ruby: '2.3.0',
          global_gems: [{
            name: 'bundler'
          }]
        }]
      }
    }
  end
end
```
### Debug output

https://gist.github.com/KurtRMueller/462fa795520b25e92449

Here's a **brief** excerpt:

```
INFO ssh: SSH not up: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.
```

### Expected behavior

I should be able to boot up vm and provision it with chef solo.

### Actual behavior

I used to be able to spin up a vm and provision it with chef solo. Now however, no dice :(. Running `vagrant up` will cuz the vm boot to time out. `vagrant provision` will spit out the errors linked in the gist.

### Steps to reproduce

Doing any # of things will cause either booting the vm to hang or provisioning to fail.

1. vagrant up
2. vagrant reload --provision
3. vagrant provision

Thank you for any and all help.

Kurt

**Comment by KurtRMueller** [comment]
Another relevant part of the log:

```
ERROR warden: Error occurred: Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

**Comment by budhrg** [comment]
Any idea what is the solution for this bug? I am also able to reproduce it but without guest additions.

**Comment by chrisroberts** [comment]
@KurtRMueller can you see if you experience the same behavior with latest vagrant release and one of the bento centos 7 boxes? That error is _generally_ the ssh connection being unexpectedly terminated. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
