### ISSUE TITLE
Feature request: rsync content of /vagrant to project directory after vagrant destroy

### ISSUE THREAD

**Issue by vinhdizzo** [mitchellh/vagrant#7144]
Hi,

I'm using vagrant-google, and would like to [request](https://github.com/mitchellh/vagrant-google/issues/129) that vagrant rsync the content of `/vagrant` back to the project directory (local host) after `vagrant destroy`.  Currently, vagrant rsyncs to the server with `vagrant up`, so hoping that `destroy` would make it go the other way.  Thanks!

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over six months with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
