### ISSUE TITLE
100gb disk size

### ISSUE THREAD

**Issue by gp1** [mitchellh/vagrant#7147]
How can i make my vagrant boxes 100gb instead of 40gb?

**Comment by sethvargo** [comment]
Hi @gp1 

Thank you for opening an issue. You can do something like this:

```ruby
v.customize 'pre-boot', ['modifyhd', :id, '--resize', '15360']
```

**Comment by gp1** [comment]
Hi sethvargo, thank you for the reply. can i do this for the existing VMs  or just when creating the new ones.

**Comment by deancsmith** [comment]
@gp1

Are you using VirtualBox? If so then you will likely need to resize your existing machine by doing something like [this](http://www.howtogeek.com/124622/how-to-enlarge-a-virtual-machines-disk-in-virtualbox-or-vmware/).
