### ISSUE TITLE
hosts updater fails with EACCESS

### ISSUE THREAD

**Issue by thany** [mitchellh/vagrant#7156]
When halting a vagrant box, about 50% of the times I get an error that summarizes to:

```
.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:98:in `initialize': Permission denied @ rb_sysopen - C:/WINDOWS/system32/drivers/etc/hosts (Errno::EACCES)
```

It looks fairly obvious what's going on: no permission to modify my hosts file. Since it works fine about half the time, and it always works a charm when starting a vagrant box, it really looks like a bug. Perhaps vagrant needs to request elevated permissions.

### Vagrant version
Vagrant 1.8.1

### Host operating system
Windows 10 (mainstream release 10586)

### Guest operating system
Ubuntu 14.04.4 LTS

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

vagrant_dir = File.expand_path(File.dirname(__FILE__))

# Check for hostsupdater plugin
if !Vagrant.has_plugin?('vagrant-hostsupdater')
  puts "Hostsupdater vagrant plugin missing, run the following: "
  puts
  puts "vagrant plugin install vagrant-hostsupdater"
  puts
  exit
end

# Check if the XperienCentral SDK is available
if !File.file?(vagrant_dir + '/webmanager/settings.xml') and !File.file?(vagrant_dir + '/webmanager/GX_WebManager_10.10.0_SDK/settings.xml')
  puts "XperienCentral SDK missing, please make sure it is unzipped in the webmanager folder!"
  puts
  exit
end

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3072"]
  end

  config.vm.network :private_network, ip: "192.168.3.101"
  config.vm.hostname = "ontw.yarden.siteworkers.nl"
  config.hostsupdater.aliases = ["redactie.ontw.yarden.siteworkers.nl"]

  # Workaround for annoying 'default: stdin: is not a tty' message
  config.vm.provision "shell" do |s|
      s.privileged = false
      s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

  config.vm.provision "shell", path: "bootstrap/provision.sh", args: "launched-from-vagrant"
end 
```

### Debug output
https://gist.github.com/thany/4f1e35565cd8aba36626

### Expected behavior
No error, hosts file modified if neccesary, and asks for elevated permission if neccesary

### Actual behavior
An error, and unable to modify the hosts file (well, looking at the error). I'm not getting any weird problems or side-effects, since the hosts file is probably already good, so being unable to remove and re-add the vagrant entry isn't going to be a practical problem. But it might become a problem when I add a new box.

### Steps to reproduce
1. `vagrant up`
2. `vagrant halt`
3. If no error, rinse and repeat

**Comment by sethvargo** [comment]
Hi @thany 

Thank you for opening an issue. Unfortunately this looks like a bug in the vagrant-hostupdater plugin. Vagrant itself does not modify the hostsfile (except for nfs on osx), so I believe this is a plugin issue. Are you able to reproduce the issue without that plugin?

**Comment by thany** [comment]
I'm not 100% sure. I removed hostupdater stuff from the Vagrantfile and uninstalled the plugin as well (just to be sure). The issue doesn't seem to surface now. But the plugin is neccesary so that everyone at the office can access their vagrant box in the same way...

So yes, it might indeed be a bug in the hostupdater plugin.

**Comment by sethvargo** [comment]
Hi @thany 

If the issue does not reproduce with that plugin, that's probably a bug in the plugin. Please report an issue there. Thanks! :smile:
