### ISSUE TITLE
ansible_local - galaxy_role_file does not work with yml file format

### ISSUE THREAD

**Issue by COLABORATI** [mitchellh/vagrant#7160]
It looks like the ansible_local provisioner does not parse a .yml file correctly, I get this error
```
    default: Installing Ansible...
    default: Running ansible-galaxy...
ansible-galaxy install --role-file=/vagrant/requirements.yml --roles-path=/vagrant/roles --force
 downloading role 'install-docker', owned by -%20src%3A%20amidos
Sorry, - src: amidos.install-docker was not found on galaxy.ansible.com.
```

with a very simple requirements.yml file that looks like this: 
```
# install role from galaxy
- src: amidos.install-docker
```

this file works fine when I execute the ansible-galaxy command: 
```
$ ansible-galaxy install --role-file=requirements.yml --roles-path=roles-test
- downloading role 'install-docker', owned by amidos
- downloading role from https://github.com/meAmidos/ansible-install-docker/archive/master.tar.gz
- extracting amidos.install-docker to roles-test/amidos.install-docker
- amidos.install-docker was installed successfully
```

However ansible_local works fine with the simple role file format like described in 
http://docs.ansible.com/ansible/galaxy.html#installing-multiple-roles-from-a-file

**Comment by gildegoma** [comment]
@COLABORATI based on your more recent comments in #7166 and #7167, I guess that you first hit a Galaxy API compatibility issue while running a rather old Ansible 1.x version (apparently auto-installed by the vagrant ansible_local provisioner). Can you please confirm?

**Comment by gildegoma** [comment]
@COLABORATI without additional feedback, I'm going to close this issue.

**Comment by sethvargo** [comment]
@gildegoma go ahead and close this
