### ISSUE TITLE
Check for docker-machine settings in environment variables

### ISSUE THREAD

**Issue by iondulgheru** [mitchellh/vagrant#7164]
### Vagrant version

$ vagrant -v
Vagrant 1.8.1
### Host operating system

MAC OSx EL Capitan

I am using vagrant in MAC OSX, and I also use docker with docker-machine, but I am using a CentOS machine with a generic provider for docker-machine.
It would be nice if I could use vagrant with docker without using boot2docker image, but my CentOS machine, exposed through **_docker-machine_**.
If I run in command line the "eval $(docker-machine env centos-play)" a DOCKER_HOST variable will be setup, and also the certificate path. In this case, centos-play is the virtual machine I use for docker.

It would be nice if vagrant could look in the environment for the variable DOCKER_HOST, and use this host as a docker server. If it doesn't find this variable, only then it will try to setup a docker environment with boot2docker.

Thank you

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for almost a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
