### ISSUE TITLE
Mounting NFS on Ubuntu 16.04 host - systemd output issues

### ISSUE THREAD

**Issue by luispabon** [mitchellh/vagrant#7165]
### Vagrant version

[development@localhost ~/P/t/phpdocker] vagrant --version
Vagrant 1.8.1
### Host operating system

Ubuntu 16.04
### Guest operating system

blinkreaction/boot2docker
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "blinkreaction/boot2docker"

    # Network config & shared folders
    config.vm.network "private_network", ip: "192.168.33.201"
    config.vm.synced_folder "..", "/home/docker/php-70", id: "php-70-dev", nfs: true
    config.vm.synced_folder "~/.composer/", "/home/docker/.composer", id: "php-70-composer", nfs: true

    # VM definition
    config.vm.provider "virtualbox" do |vb|
        vb.name = "PHP 70"
        vb.memory = 1024
        vb.cpus = 1
    end

    # Bring up containers
    config.vm.provision "shell", run: "always", inline: "cd /home/docker/php-70/phpdocker && docker-compose up -d 1>&2"

    # Redirect webserver port down 80, etc
    config.vm.provision "shell", run: "always", inline: "/usr/local/sbin/iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 7000 1>&2"

    # Disable guest additions auto update as it won't work on boot2docker, and slows vm boot down boot
    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
    end
end
```
### Debug output

https://gist.github.com/luispabon/fbd51a23aa6730cb421a
### Expected behavior

No systemd output, mounts correctly
### Actual behavior

Spurious systemd buffered output stopping NFS provisioning; if ctrl+c then it also stops vagrant provisioning and mounts don't finish. If pressing Q, systemd buffer finishes correctly and mounts mount.
### Steps to reproduce
1. Install Ubuntu 16.04 from daily cd image+ latest vagrant + nfs kernel server
2. Try run that vagrantfile
3. Voila

**Comment by kamazee** [comment]
I've stubmled upon a similar issue recently.
Could you try adding `SYSTEMD_PAGER=cat` in front of `vagrant up` and see if it works?

**Comment by sethvargo** [comment]
Hi @luispabon 

The link you provided is not the debug output. Please follow the instructions for [generating debug output](https://www.vagrantup.com/docs/other/debugging.html) and provide a link to that. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
