### ISSUE TITLE
Allow to select the version of the auto-installed Ansible

### ISSUE THREAD

**Issue by COLABORATI** [mitchellh/vagrant#7167]
It does not seem to be possible to set the version of the auto-installed ansible version. If I have one role that requires ansible v2 the whole world explodes. Combined with #7166 these two bugs trigger the collapse of the whole universe - I am crying on my knees as three days of work are just melting in front of my eyes - please tell me that I am doing something wrong and that there is a nice way to run ansible_local with v2, thank you very much for your attention!

**Comment by gildegoma** [comment]
So far, the `ansible_local` provisioner relies on the operating system package system to install the latest packaged version (without the possibility to select the version as mentioned in the [docs](https://www.vagrantup.com/docs/provisioning/ansible_local.html)).

For more flexibility, it is also planned (see #6654) to add the ability to select the Ansible version to install. I probably won't have time to work on this very soon, but community contribution are always welcome, and hopefully we can it into Vagrant 1.8.2 ;-)

@COLABORATI  Which Vagrant basebox (or operating system) are you using for your guest? If I understand well, the `ansible_local` auto-setup still install an ansible 1.x there...

**Comment by gildegoma** [comment]
Issue title reworded to better express this _feature request_

This will be probably resolved via #6654 (setup via pip), but maybe an installation from git (for full code state flexibility) will be appreciated...

**Comment by gildegoma** [comment]
Install from pip will be available as of Vagrant 1.8.2, with `version` selection.

In a next iteration, I plan to add the ability to install from source, but still via pip by generating commands like `pip install git+https://github.com/ansible/ansible.git@stable-2.1`
