### ISSUE TITLE
Docker provisioner: add ability to import a .tar image

### ISSUE THREAD

**Issue by carminexx** [mitchellh/vagrant#7168]
(using vagrant 1.8.1 on Mac OS X 10.11)

I'm using the Docker provisioner, and I think it would be a really useful feature the ability to use a .tar image (via `docker import`) , instead of having to build the image from a Dockerfile and/or using Docker Hub via `docker pull`.

Is the feature (maybe) already present but not documented; or listed in the future roadmaps?

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for almost a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
