### ISSUE TITLE
404 Not Found When trying to use a newly built box with Packer on Atlas

### ISSUE THREAD

**Issue by iroller** [mitchellh/vagrant#7170]
### Issue

I've just built a new box using remote building with Packer on Atlas. Now I'm trying to use it in my local Vagrant and it can not find it. I don't have any custom stuff in Vagrantfile, it's a default one. The box is a vanila Ubuntu Trusty box.

```
$ vagrant login --check
You are already logged in.

$ vagrant box remove -f 'my_user/ubuntu-trusty' --all
The box you requested to be removed could not be found. No
boxes named 'my_user/ubuntu-trusty' could be found.

$ vagrant box add 'my_user/ubuntu-trusty'
...
The requested URL returned error: 404 Not Found

$ vagrant up
...
    default: Downloading: https://atlas.hashicorp.com/my_user/boxes/ubuntu-trusty/versions/0.2/providers/vmware_fusion.box
...
The requested URL returned error: 404 Not Found
```

### Vagrant version
1.8.1 + vmware_fusion

### Host operating system
MacOSX El Capitan

### Guest operating system
Ubuntu Trusty

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "my_user/ubuntu-trusty"
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/iroller/b1c04e8fe7fd397e4f7e

### Expected behavior
Expected Vagrant to download a box from Atlas and set it up.

### Actual behavior
Got 404 not found

### References
- https://github.com/mitchellh/vagrant/pull/7158
- https://github.com/mitchellh/vagrant/issues/6776#issuecomment-199843657

cc @sethvargo

**Comment by sethvargo** [comment]
Hi @iroller 

Thank you for opening an issue. Can you confirm the box is "released" in Atlas? It would be helpful if you could share an Atlas screenshot of the box version.

**Comment by iroller** [comment]
Yeah it's released.

<img width="1067" alt="screen shot 2016-03-22 at 11 11 49" src="https://cloud.githubusercontent.com/assets/338294/13958676/002db1d4-f01f-11e5-8671-aa0cad9cf93e.png">

**Comment by sethvargo** [comment]
Hey @iroller 

Can you try this:

```
$ curl -H"X-Atlas-Token:$ATLAS_TOKEN" https://atlas.hashicorp.com/anton_koldaev/boxes/ubuntu-trusty-tadalist/versions/0.2/providers/vmware_fusion.box
```

and replace ATLAS_TOKEN with your Atlas token?

**Comment by iroller** [comment]
Sure:
```
{"errors":["Not found"],"success":false}%
```

**Comment by sethvargo** [comment]
@iroller okay, that's kinda helpful. That tells us it's not an issue with Vagrant at least :smile: 

Can you double check everything is spelled correctly and then verify your Atlas token is correct and authorized to access that resource?

**Comment by iroller** [comment]
I did re-create the token a couple times, also `vagrant login --check` says it's ok.

**Comment by iroller** [comment]
Could be related to the recent changes to atlas and the fact that it's saying `Trial ends in 6 months` in my account?

**Comment by iroller** [comment]
I can access https://atlas.hashicorp.com/anton_koldaev/boxes/ubuntu-trusty-tadalist/versions/0.2/ in the browser, but https://atlas.hashicorp.com/anton_koldaev/boxes/ubuntu-trusty-tadalist/versions/0.2/providers is giving 404

**Comment by sethvargo** [comment]
Could be - I just activated a 30-day Vagrant trial. Could you please try now and see if it works?

**Comment by iroller** [comment]
Nope, still the same issue. Should I click `Create a new provider` maybe and create vmware_fusion there?

**Comment by sethvargo** [comment]
Try vmware_desktop instead of vmware_fusion

**Comment by iroller** [comment]
Just tried. All the same issue. curl doesn't work for the newer released version with vmware_desktop.
Same for vagrant:
```
...
==> default: Adding box 'anton_koldaev/ubuntu-trusty-tadalist' (v0.3) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/anton_koldaev/boxes/ubuntu-trusty-tadalist/versions/0.3/providers/vmware_desktop.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

**Comment by sethvargo** [comment]
Hi @iroller 

I did some digging, and I don't think this is a Vagrant issue. If it were a Vagrant issue, we would have a lot of users opening issues, but it only appears to be affecting this use case. I just added you to an internal private box named "hashicorp/otto-go". Can you try to download that one and see if it works?

**Comment by iroller** [comment]
Hey @sethvargo 
It fails too.
```
✗ vagrant box add 'hashicorp/otto-go'
The box 'hashicorp/otto-go' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/hashicorp/otto-go"]
Error: The requested URL returned error: 404 Not Found
```

However I can download a private VM from my another organization:
```
vagrant box add --force 'basecamp/vmware-osx-10.10'
==> box: Loading metadata for box 'basecamp/vmware-osx-10.10'
    box: URL: https://atlas.hashicorp.com/basecamp/vmware-osx-10.10
==> box: Adding box 'basecamp/vmware-osx-10.10' (v0.0.1) for provider: vmware_desktop
    box: Downloading: https://atlas.hashicorp.com/basecamp/boxes/vmware-osx-10.10/versions/0.0.1/providers/vmware_desktop.box
    box: Progress: 0% (Rate: 97485/s, Estimated time remaining: 25:12:15)^C==> box: Waiting for cleanup before exiting...
==> box: Box download was interrupted. Exiting.
^C==> box: Exiting immediately, without cleanup!
```

**Comment by handlers** [comment]
Hi @iroller, just letting you know that I'm looking into this from the Atlas side!

**Comment by iroller** [comment]
@sethvargo  figured the issue with hashicorp/otto-go, it's granted to my "iroller" account which I'm not using. I'll look into it later tonight once again.

**Comment by iroller** [comment]
So the `hashicorp/otto-go` works fine when I'm using the proper atlas token for it.
However `anton_koldaev/ubuntu-trusty-tadalist` still doesn't work.

I noticed the following output in packer on atlas:
```
==> amazon-ebs: Stopping the source instance...
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating the AMI: packer-tadalist 1458686463
    amazon-ebs: AMI: ami-4c141826
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
==> amazon-ebs: Running post-processor: atlas
    amazon-ebs (atlas): Uploading artifact (0 bytes)
==> amazon-ebs: Running post-processor: atlas
    amazon-ebs (atlas): Uploading artifact (0 bytes)
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:

us-east-1: ami-4c141826
--> amazon-ebs: anton_koldaev/ubuntu-trusty-tadalist/amazon.image (v6)
--> amazon-ebs: anton_koldaev/ubuntu-trusty-tadalist/vagrant.box (v5)
```

`0 bytes` makes me think there was some issue. Thoughts?

**Comment by iroller** [comment]
Ok I figured it was a non-complete Packer configuration. I didn't actually have builders and post-processors properly configured and this caused the vagrant image not to be created.

Thanks for your help Seth and Sam.

**Comment by handlers** [comment]
Hey @iroller, I am glad you were able to figure it out. Please let us know if you have any questions! :smile:
