### ISSUE TITLE
winrm-config lists wrong rdpport when forwarding

### ISSUE THREAD

**Issue by wstaples** [mitchellh/vagrant#7174]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Windows 7 64-bit

### Guest operating system
Windows Server 2012 R2

### Vagrantfile
```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "maddhatter/windows-2012r2"
  c.vm.box_url = "maddhatter/windows-2012r2"
  c.vm.communicator = "winrm"
  c.vm.network(:private_network, {:type=>"dhcp"})
  c.vm.network(:forwarded_port, {:guest=>3389, :host=>3389, :host_ip=>"127.0.0.1", :auto_correct=>true, :id=>"rdp"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "D:/chef_cookbooks/geiger_consul", "/vagrant", nil
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "2048"]
    p.customize ["modifyvm", :id, "--cpus", "2"]
  end
end
```

### Debug output
https://gist.github.com/wstaples/ee20fc506edd5773263e

### Expected behavior
I have forwarded port 3389 (RDP) and set auto correct to true. When I run vagrant winrm-config it correctly recognizes that the winrm port has been forwarded. It does not recognize that the RDP port has been forwarded. no matter what it always outputs RDPPort 3389. I'm using test-kitchen which in turn runs `vagrant winrm-config` to determine what port to use. I would expect that when port 3389 is "auto corrected" for example to 2213 that winrm-config would output that information just like it does for the winrm port. 

### Actual behavior
````
Host default
  HostName 127.0.0.1
  Port 2213
  User vagrant
  Password vagrant
  RDPPort 3389
```

**Comment by sethvargo** [comment]
Hi @wstaples 

I believe you will need to use the `vagrant port` command to get the auto-correct port. Can you please try that?

**Comment by wstaples** [comment]
The command `vagrant port` does seem to return the correct forwarded port however it does not appear to be labeled. Does this mean its an issue with test kitchen?

**Comment by sethvargo** [comment]
Hi @wstaples 

Thank you for your reply. What do you mean by "labeled"?

**Comment by wstaples** [comment]
vagrant port output looks like:
```
The forwarded ports for the machine are listed below. Please note that
these values may differ from values configured in the Vagrantfile if the
provider supports automatic port collision detection and resolution.

  3389 (guest) => 2212 (host)
  5985 (guest) => 2213 (host)
  5986 (guest) => 2214 (host)
```

I know off the top of my head that 3389 is RDP but how would a program know thats the RDP port? especially if the creator of the vagrant box changed the RDP settings to use a non-standard port.

**Comment by sethvargo** [comment]
Hi @wstaples 

Ports in Vagrant are never "labeled", i.e. there's no way to know what was the "RDP" port because that's not something that's internally trackable.

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a _new issue_ and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
