### ISSUE TITLE
Why saltstack version can be specified only on Windows minions?

### ISSUE THREAD

**Issue by Hinidu** [mitchellh/vagrant#7177]
Hello!
I've encountered a problem which is caused by the fact that Vagrant installs saltstack 2015.5.3, but my problem was fixed only in 2015.8 branch. I want to use `postgres_user.present` but it doesn't work with PostgreSQL 9.5 in saltstack 2015.5 branch.
I found that we can set version of saltstack [only for Windows guests](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/provisioner.rb#L239-L242). So the question is why? Could we remove this restriction?
Thank you in advance.

**Comment by sethvargo** [comment]
Hi @Hinidu 

Thank you for opening an issue. As you can see from the backlog, there are a few open salt issues; the reason for this is that we have no maintainer for that component of Vagrant. I've tagged this, but the Vagrant core team is not very familiar with Salt, so it's unlikely we will be able to fix this ourselves. Instead, we would look to a community contribution for this. Thanks! :smile:

**Comment by Hinidu** [comment]
Hi @sethvargo 
Thank you for the honest answer :laughing: I hope I will find some time to fix this myself.
Btw thank you for the great tool!

**Comment by rrzaripov** [comment]
@Hinidu can you give vagrant version you are using and more information about guest OS?

**Comment by Hinidu** [comment]
@rrzaripov Vagrant 1.8.1, box [deb/wheezy-amd64](https://atlas.hashicorp.com/deb/boxes/wheezy-amd64).

**Comment by rrzaripov** [comment]
@Hinidu Vagrant's salt provisioner plugin using salt-bootstrap script for salt-minion installation ([source](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/bootstrap-salt.sh)). This script using [saltstack debian repository](http://debian.saltstack.com/debian/dists/) for getting packages. For Wheezy latest version is 2015.5, and how I know this repo will no updated in near future.

**Comment by rrzaripov** [comment]
@sethvargo this is not Vagrant bug, please close this issue.
