### ISSUE TITLE
Is it possible to bring up VMs across multiple physical machines?

### ISSUE THREAD

**Issue by 14msitaqadeer** [mitchellh/vagrant#7178]
Suppose i want to bring up 5 VMs with vagrant and i dont have enough resources on one physical machine, is there anyway that i can distribute my VMs across 2 or 3 physical machines?
If yes, then please guide me how could this be accomplished?

**Comment by sethvargo** [comment]
Hi @14msitaqadeer 

This is not possible with Vagrant, and it's not the designed use case. We make two other open source projects that satisfy your use case:

- Terraform (https://terraform.io), which can spin up infrastructure and manage machines
- Nomad (https://nomadproject.io), which can schedule VMs (and containers) across multiple hosts

Thanks! :smile:

**Comment by 14msitaqadeer** [comment]
@sethvargo 
This can be done as a workaround on different hosts in a private network, allowing hosts and VMs to communicate with each other
