### ISSUE TITLE
Ansible provisioner hangs when using --step

### ISSUE THREAD

**Issue by dlyle65535** [mitchellh/vagrant#7187]
### Vagrant version
Vagrant 1.8.1

### Host operating system
OSX 10.11.3 

### Guest operating system
Centos 6.7 from bento/centos-6.7

### Vagrantfile
```ruby
hosts = [{
    hostname: "node1",
    ip: "192.168.66.121",
    memory: "8192",
    cpus: 4,
    promisc: 2  # enables promisc on the 'Nth' network interface
}]

Vagrant.configure(2) do |config|

  # all hosts built on centos 6
  config.vm.box = "bento/centos-6.7"
  config.ssh.insert_key = "true"

  # enable the hostmanager plugin
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  # host definition
  hosts.each_with_index do |host, index|
    config.vm.define host[:hostname] do |node|

      # host settings
      node.vm.hostname = host[:hostname]
      node.vm.network "private_network", ip: host[:ip]

      # vm settings
      node.vm.provider "virtualbox" do |vb|
        vb.memory = host[:memory]
        vb.cpus = host[:cpus]

        # enable promisc mode on the network interface
        if host.has_key?(:promisc)
          vb.customize ["modifyvm", :id, "--nicpromisc#{host[:promisc]}", "allow-all"]
        end
      end
    end
  end

  # provisioning
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./playbook.yml"
    ansible.sudo = true
    ansible.raw_arguments = "--step"
  end
end
```

### Debug output
https://gist.github.com/dlyle65535/3964eda9a0ce4d71664378fec5ea8620

### Expected behavior
After typing y or c at prompt, provisioning should have continued.

### Actual behavior
Provisioning hangs.

### Steps to reproduce
1. git clone https://github.com/dlyle65535/vagrant-ansible-step
2. cd vagrant-ansible-step && vagrant up
3. Hangs after answering y to Perform task: TASK: setup (y/n/c): y 

### References
None.

**Comment by sethvargo** [comment]
Hi @dlyle65535 

Thank you for opening an issue. I'm sorry this is causing you behaviors, but I think this is the expected behavior. Interactive applications/provisioners are generally not supported because Vagrant, by default, does not allocate a PTY.

Can you try [try enabling pty](https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html) fixes the issue?

**Comment by dlyle65535** [comment]
Hi @sethvargo,

Thanks for the quick reply. config.ssh.pty = true did not help. Testing that out did get me thinking about alternate ways to achieve the same aim.

In my use case, I only need to --skip once something in provisioning has failed in order to troubleshoot. We use the hostmanager plugin and we have an inventory file, so it becomes a simple matter of running ansible-playbook outside of Vagrant e.g. 

`ansible-playbook -i inventorydir playbook.yml --step -u vagrant --ask-pass`

So, now that I understand that interactive provisioning is not supported by Vagrant and I have a workaround, I'll go ahead and close this issue.

Thanks again!

-David...
