### ISSUE TITLE
Add support for Custom Facter .rb when using Puppet Apply[Windows]

### ISSUE THREAD

**Issue by lmayorga1980** [mitchellh/vagrant#7189]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

1.8.1
### Host operating system

Osx 10.x
### Guest operating system

Any Windows Guest
### Vagrantfile

``` ruby
   srv.vm.provision :puppet do |puppet|
        puppet.environment = "development"
        puppet.environment_path = "."
        puppet.options = "--verbose"
        puppet.facter = {
        "somefact" => "somevalue"
        }
```
### Expected behavior

Vagrant Puppet Apply provisioner works as expected using external facts but when creating lib/facter/<fact>.rb custom facts then those are not executed but they are loaded.
### Steps to reproduce
1. Create a Puppet Module with some Custom Facts
2. Run the Puppet Apply Provisioner
3. The values inside the lib/facter are not executed

**Comment by szymonrychu** [comment]
+1

**Comment by lmayorga1980** [comment]
any way to workaround this guy?

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for almost a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!

**Comment by lmayorga1980** [comment]
@chrisroberts The workaround was to run the vagrant shell provisioner for windows guest where custom facts need to be executed.
