### ISSUE TITLE
Pinning Bundler to an older version makes plugin development and CI difficult

### ISSUE THREAD

**Issue by jgonera** [mitchellh/vagrant#7193]
I use Rbenv to manage Rubies. I have the latest Bundler installed by default. I can't run `bundle install` for a Vagrant plugin because I get:

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant was resolved to 1.8.2.dev, which depends on
      bundler (<= 1.10.6, >= 1.5.2)

  Current Bundler version:
    bundler (1.11.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (<= 1.10.6, >= 1.5.2)', which is required by gem 'vagrant', in any of the sources.
```

This is problematic not only for development. Some CI systems also just run the latest version of Bundler and downgrading is tricky.

**Comment by sethvargo** [comment]
Hi @jgonera 

Thank you for opening an issue. If you search closed issues, you'll find a number of places where we've explained the reason for the tight bundler constraint. We depend on internal APIs that are not guaranteed to be stable between even minor or patch releases, and these have historically caused breaking changes in releases of Vagrant. Unfortunately you will need to use gemsets or downgrade your local bundler version of plugin development. I definitely feel your pain about CI systems as well. Unfortunately this is an area where we have to optimize the general user experience over the plugin development experience. Sorry! :frowning:

**Comment by jgonera** [comment]
@sethvargo Could we add a section in [the docs](https://www.vagrantup.com/docs/plugins/development-basics.html) saying that this is the preferred way of working around this problem? I saw other issues but they mostly seemed to be related to running Vagrant out of a git repo clone.

I couldn't find any official guidelines for plugin development and I saw people doing things like forking Vagrant and bumping Bundler version in the fork and using that fork... That definitely doesn't seem like the right way to go.

**Comment by kenorb** [comment]
This page mentioning that requirements: [Installing Vagrant from Source](https://github.com/mitchellh/vagrant/wiki/Installing-Vagrant-from-Source)

> Ensure you have installed a version of Bundler that is compatible with Vagrant*

> * The bundler constraint is a floating requirement in Vagrant. You will need to inspect the vagrant.gemspec to determine the version when you are compiling from source. For example, if the gemspec says < 0.10.0, you will need to install a version of Bundler that is lower than 0.10.0:

**Comment by jgonera** [comment]
@kenorb It's not part of the plugin development docs and it's not obvious that I should follow those instructions when developing a plugin.
