### ISSUE TITLE
ansible_local - location of ansible.cfg

### ISSUE THREAD

**Issue by yves-vogl** [mitchellh/vagrant#7195]
### Vagrant version

Vagrant 1.8.1
### Host operating system

Mac OS X 10.11.3 (15D21) El Capitan
Darwin 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
### Guest operating system

CentOS Linux release 7.2.1511 (Core) 
Linux 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = 'jhcook/centos7'

  config.ssh.insert_key = false

  config.vm.synced_folder '.', '/vagrant'

  config.ssh.pty = true

  config.vm.provision 'ansible_local' do |ansible|
    ansible.verbose = 'v'
    ansible.playbook = 'site.yml'
  end
end
```
### Expected behavior

The statement in the [documentation](https://www.vagrantup.com/docs/provisioning/ansible_intro.html) says that

> ansible-playbook never looks for ansible.cfg in the directory that contains the main playbook file.
### Actual behavior

In fact ansible-playbook looks for ansible.cfg in the current directory which also could contain the main playbook file.

Additionally I cannot find a way to set ANSIBLE_CONFIG for ansible_local to point to another ansible.cfg instead.
### Steps to reproduce
1. Setup folder syncing where ansible.cfg and the main playbook file are on the same directory
2. Set `ask_pass = true` in ansible.cfg and fire vagrant up
3. ansible-playbook will ask for the ssh password

```
[vagrant@centos7-vbox vagrant]$ PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook --limit='default' --inventory-file=/tmp/vagrant-ansible/inventory -v site.yml
SSH password: 

[vagrant@centos7-vbox vagrant]$ ls
ansible.cfg  CHANGELOG.md  group_vars  host_vars  inventories  README.md  roles  site.yml  Vagrantfile
```
### References

[Official ansible documentation](http://docs.ansible.com/ansible/intro_configuration.html#configuration-file).

**Comment by gildegoma** [comment]
@yves-vogl cdafc63 is an attempt to make the documentation a bit clearer, feedbacks welcome :)

Now about the other point you raised:

> Additionally I cannot find a way to set ANSIBLE_CONFIG for ansible_local to point to another ansible.cfg instead.

I suppose that you probably found some convention to help your project developers to enable the correct `ansible.cfg` file, depending on which environment they're running.

For full flexibility, we of course could [consider adding the ability in Vagrant to export a custom `ANSIBLE_CONFIG` environment variable](https://github.com/mitchellh/vagrant/issues/2302#issuecomment-70053612), with the introduction of an `ansible.config_file` option for the two Ansible provisioners. I must say that I am not sure that the need for this feature is very important, but please let me know if you're interested to work on a pull request to add it...

**Comment by chrisroberts** [comment]
Is this still a desired feature? No reply seen on last comment. Thanks!

**Comment by gildegoma** [comment]
Hey Chris! Thanks for pinging. I actually started to work on a patch for this in last June, but forgot to finish it since then. I'll try my best to bring this in the next release.

**Comment by yves-vogl** [comment]
It's a desired feature. I'll try to spend some time the next days.

**Comment by chrisroberts** [comment]
Okay, great. Just give me a ping when it's getting close and we can assign it a target version milestone to land in. Thanks!

**Comment by gildegoma** [comment]
@yves-vogl My work was quite advanced already. I'll create a pull request and would appreciate a lot if I can ask you for review+polishing?

**Comment by yves-vogl** [comment]
@gildegoma Great. I'll wait for a trigger and would be happy to assist you :-)

**Comment by gildegoma** [comment]
@yves-vogl I have created the PR #7918. I would appreciate a lot if you can test and review it before merging it. Many thanks in advance!
