### ISSUE TITLE
Fully automated install on OSX El Capitan

### ISSUE THREAD

**Issue by aragnon** [mitchellh/vagrant#7196]
You do distribute a dmg, but you don't supply an option to install this dmg non-interactively via the command line. I would like to see such an option.

**Comment by ilyapoz** [comment]
can you use homebrew?

**Comment by sethvargo** [comment]
Hi @aragnon 

You can manually mount the DMG and execute the package using pkgutil. [Here are some instructions](http://apple.stackexchange.com/questions/73926/is-there-a-command-to-install-a-dmg). Untested, but it should look something like this:

```
curl -o vagrant.dmg https://releases.hashicorp.com/...
sudo hdiutil attach vagrant.dmg
sudo installer -package /Volumes/Vagrant/Installer.pkg -target /
sudo hdiuti detach /Volumes/Vagrant
```

Thanks!
