### ISSUE TITLE
inventory_file is null on Ubuntu 14.04 host machine

### ISSUE THREAD

**Issue by robwilkerson** [mitchellh/vagrant#7201]
### Vagrant version
1.8.1

### Host operating system
Ubuntu 14.04

### Guest operating system
Ubuntu 14.04

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "api"
  config.vm.box_url = "https://s3.amazonaws.com/my/manifest.json"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: "192.168.33.10"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/opt/www/api", type: "nfs"

  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = 'ansible/vagrant'
    ansible.extra_vars = {
      # Override the usual "ubuntu" user for vagrant envs.
      remote_user: 'vagrant',
    }
    ansible.ask_vault_pass = true
    ansible.playbook = "ansible/vagrant.yml"
  end

  # Tail the API logs for immediate insight
  config.vm.provision :shell,
    inline: "sleep 2 && sudo tail -f /var/log/upstart/api.log",
    run: "always"
end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. Do NOT paste the debug
output in the issue, just paste the link to the Gist.

### Expected behavior
On an OS X host, the `inventory_file` variable holds the same value as the `inventory_path` value in my Vagrantfile. 

### Actual behavior
On the Ubuntu host, the `inventory_file` variable is `null`. I have an Ansible tasks that should run only...

```
    when: 'vagrant' not in inventory_ifle
```

### Steps to reproduce
1. Set up Vagrant to be provisioned via Ansible as shown above.
1. Create a `./vagrant/inventory` file with the following content:

        # Change IP below to match your config, as req'd
        default ansible_ssh_host=192.168.33.10

1. Create a playbook that simply debugs the `inventory_file` and run that playbook from your `Vagrantfile`:

```
        ---
        - name: Provision the server
          hosts: all
          gather_facts: false
          tasks:
            - debug:
                var: inventory_file
```

1. Run `vagrant up` on an OS X machine to see that `inventory_file` is the same as the `inventory_path` value..
1. Run `vagrant up` on an Ubuntu 14.04 box to see a null value.

### References
No known references.

**Comment by robwilkerson** [comment]
For whatever it's worth, I just found out that it works as expected if I explicitly identify the inventory file in my `Vagrantfile`:

    ansible.inventory_path = 'ansible/vagrant/inventory'

**Comment by sethvargo** [comment]
Ping @gildegoma - is this intended behavior or a bug? I didn't know, so I'll leave up to you to tag :heart:

**Comment by gildegoma** [comment]
This sounds more like an Ansible issue in my opinion, I've checked that

Ansible 1.9.4 will
* correctly set the `inventory_file` variable when a path to **a directory** is provided
* correctly set the `inventory_file` variable when a path to **a file** is provided

while Ansible 2.0.2.0 (`stable-2.0 9cf43ce17f`) will
* **not** set the `inventory_file` variable when a path to **a directory** is provided (`inventory_file` variable is `null`)
* correctly set the `inventory_file` variable when a path to **a file** is provided

@robwilkerson 
* Can you please check the Ansible versions that you're using on your OS X and Ubuntu systems?
* as you commented, if you only have a single inventory file, your `ansible.inventory_path = 'ansible/vagrant/inventory'` will work fine with all Ansible versions.

**Comment by gildegoma** [comment]
@robwilkerson can you please confirm that this is an Ansible issue (and close). If not please provide more information that demonstrate that the issue is only present on Ubuntu with the same Ansible Version (and Vagrant 1.8.1)...

**Comment by robwilkerson** [comment]
My apologies for the delay. I think you're right that it's on the Ansible end of things. Thanks for looking into it.
