### ISSUE TITLE
/etc/machine-id is the same

### ISSUE THREAD

**Issue by ChristopheSchmitz** [mitchellh/vagrant#7211]
/etc/machine-id is meant to be unique to a machine.
When running a a debian machine (or a debian multi machine), they all get systematically the same uuid in /etc/machine-id, which is not good for services that rely on the uniqueness of this id.
I don't know if it is a Vagrant issue with this specific debian distribution, or if it is more general to Virtualbox.

### Vagrant version
Vagrant 1.7.4

### Host operating system
Fedora release 22 (Twenty Two)

### Guest operating system
debian/jessie64 8.2.2

### Expected behavior
/etc/machine-id is unique and random whenever I am creating a new VM.

### Actual behavior
/etc/machine-id has systematically the same value

### Steps to reproduce
1. provision a debian machine
2. provision another debian machine
3. check the value of /etc/machine-id

Alternatively, provision a debian cluster (2 nodes), and check /etc/machine-id

**Comment by sethvargo** [comment]
Hi @ChristopheSchmitz 

Thank you for opening an issue. Vagrant doesn't do anything special to set the machine-id; I'm guessing it's generated by the kernel similar to a mac address based on some psuedo-random value. As such, it's most likely virtualbox providing a consistent value that's causing the machine-id to be consistent. Can you try to reproduce this without Vagrant (just create two debian machines in virtualbox). 

>   The machine ID is usually generated from a random source during system installation and stays constant for all subsequent boots. Optionally, for stateless systems, it is generated during runtime at early boot if it is found to be empty.

I grepped Vagrant's codebase, and there's no interaction with `/etc/machine-id` (or any similarly named file). 

What do you think?

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to inactivity. If this is still occurring, please open a new issue and follow the associated issue template.
