### ISSUE TITLE
Cannot Start VirtualBox

### ISSUE THREAD

**Issue by anonRegions** [mitchellh/vagrant#7212]
This morning, the vagrant up command yielded this:

```
Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg*)" at line 71 of file VBoxManageHostonly.cpp
```

### Vagrant version
Vagrant 1.7.4

### Host operating system
Ubuntu 14.04

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/anonRegions/21f5d6ef141252f986c3054e25ddc87e

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1. vagrant up

### References
- GH-1671

**Comment by sethvargo** [comment]
Hi @anonRegions 

Can you please try running:

```
sudo /Library/StartupItems/VirtualBox/VirtualBox restart
```

This is not really a Vagrant issue; something became out of sync in Virtualbox's internal cache. Restarting it usually does the trick. :smile:

**Comment by anonRegions** [comment]
Seth--

This is what I get when I run that command:

"sudo: /Library/StartupItems/VirtualBox/VirtualBox: command not found"

Please advise.

Thanks.

Ethan

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by sethvargo** [comment]
Hi @anonRegions 

Do you have Virtualbox installed? If so, at what version? The debug output you pasted only includes one line of output.

**Comment by anonRegions** [comment]
Seth--

Attached is a file containing the logging info from my terminal, which
should give you the information you seek. (I don't know where the
VirtualBox error logs are stored. I can send them to you if you help me
figure out where they reside.)

Please let me know if you need anything else.

Thanks.

Ethan

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by anonRegions** [comment]
Seth--

Here's the VBoxLog.

HTH,

Ethan


<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by anonRegions** [comment]
Seth--

The current version of VirtualBox is 5.0.16 r105871.

Thanks.

Ethan

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by sethvargo** [comment]
Hi @anonRegions 

There is nothing attached. You cannot send attachments to GitHub. Please follow the instructions on https://www.vagrantup.com/docs/other/debugging.html which explain how to generate debug output to a file. Put the contents of the file into a GitHub Gist and send the link here. Thanks!

**Comment by anonRegions** [comment]
Seth--

I'm completely confused about gists (never created one before). At the
Create a New Gist window, I entered a message title, "Error Message When
Attempting VVV Startup," then entered a filename (vagrant.log), pasted the
content copied from my CLI into the window below the title & filename, and
clicked "Create secret gist." The result was an error message saying,
"Contents can't  be empty."

I'm at a loss. Please advise.

Thanks.

Ethan

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by anonRegions** [comment]
Cancel previous transmission--stupid user error.

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by anonRegions** [comment]
Seth--

Here's the URL to the gist:

https://gist.github.com/anonRegions/e02a31fa0a4834904d87d96f33849c80

Thanks.

Ethan

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by sethvargo** [comment]
Hi @anonRegions 

Can you try the following? (You need to find the launch agent on your machine):

```
sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart
```

Here are a few posts to help:

- http://stackoverflow.com/questions/18149546/vagrant-up-failed-dev-vboxnetctl-no-such-file-or-directory
- https://bbs.archlinux.org/viewtopic.php?id=167854

**Comment by DevNaga** [comment]
thats a ubuntu 14.04...

the `sudo apt-get install virtualbox` would have already gotten the virtualbox setup. If not this error might appear. 

Probably pasting the error output of `/etc/init.d/vboxdrv setup` might be helpful..

**Comment by anonRegions** [comment]
Seth--

I tried this:

sudo launchctl load /Library/LaunchDaemons/org.virtualbox.startup.plist
>

and got this error message:

"sudo: /Library/Application
> Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh: command not found"


I'm able to bring up the Oracle VM VirtualBox Manager, but I then get a
prompt for a password within VB & whatever it is, I don't know it
(evidently, it's not my logon password, unless I have to preface it with
sudo).

Please advise.

Thanks.

Ethan




<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by anonRegions** [comment]
I'm not sure about the error output, but I copied the contents of vboxdrv &
the file is attached.

Please advise.

Thanks.

Ethan


<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by sethvargo** [comment]
Hi @anonRegions 

Thank you for your reply. Please understand that you cannot attach files to your email replies. If you look on https://github.com/mitchellh/vagrant/issues/7212 (where this thread is), you will see that there are no attachments.

As I said above, you need to restart the Virtualbox daemon. This varies between operating systems. Can you please try @DevNaga's suggestion:

```
sudo /etc/init.d/vboxdrv restart
```

**Comment by anonRegions** [comment]
Seth--

Trying

sudo /etc/init.d/vboxdrv restart


yields this message:

Stopping VirtualBox kernel modules ...done.

Starting VirtualBox kernel modules ...failed!

  (modprobe vboxnetflt failed. Please use 'dmesg' to find out why)


 I'm not sure where to add 'dmesg' to the command to get the info referred
to above.

Thanks.

Ethan

>


<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by sethvargo** [comment]
Hi @anonRegions 

You may need to install the generic headers:

```
sudo apt-get install linux-headers-generic build-essential
```

Please note, we are willing to help you debug this issue, but this is no longer a Vagrant issue. The issue you are experiencing is entirely with Virtualbox.

Refs: http://ubuntuforums.org/showthread.php?t=1098946

**Comment by anonRegions** [comment]
Seth--

Given that this is a VirtualBox issue, can you point me to anyone over
there who can help me? Their website doesn't seem to list any kind of
support that I could find.

Here's what I've tried since I got your email above:

I ran this command:

$ dmesg | grep VirtualBox

getting this result:

[ 5067.037574] warning: `VirtualBox' uses 32-bit capabilities (legacy
support in use)


Then I ran

sudo modprobe -v vboxdrv

which did absolutely nothing after I entered the password at the prompt:

$ sudo modprobe -v vboxdrv
[sudo] password for selfspunwebs:

Trying this:

$ sudo apt-get install linux-headers-generic build-essential

got me this:

Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
linux-headers-generic is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Then I tried this:

sudo depmod -a

and then modprobe again:

sudo modprobe -v vboxdrv

which again yielded nothing.

Please advise.

Btw, I really appreciate your help.

Thanks!

Ethan

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by sethvargo** [comment]
Hi @anonRegions 

Are you on a 32-bit system or are you trying to run Virtualbox inside another virtualization layer? 

https://www.virtualbox.org/wiki/Community

**Comment by anonRegions** [comment]
I'm on a 64-bit machine. I noticed that entry, too & wondered about it
because I was under the distinct impression that I'd installed the 64-bit
version of VirtualBox. Weird...

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by sethvargo** [comment]
Hi @anonRegions 

As this is not a Vagrant issue, I'm going to close this. I posted a link to the VirtualBox resources above. Thanks!

**Comment by anonRegions** [comment]
Thank you, Seth!

<beyondtheframe@gmail.com>

Ethan Rips
beyondtheframe@gmail.com
https://www.linkedin.com/in/ethanrips

**Comment by kelvinkyaw** [comment]
Same experience with iOS 12 with VB 5.2.6. Remove old VB version and download new version of VB (5.2.18). Work perfectly.

**Comment by ederrafo** [comment]
In macOS Mojave, simple update virtualbox , if use vagrant also update it, your vm not will suffer change
