### ISSUE TITLE
SSH Failures when provisioning multiple boxes in parellel

### ISSUE THREAD

**Issue by BonsaiDen** [mitchellh/vagrant#7218]
We're evaluating use of Vagrant in our CI process in order to remove cruft from the actual jenkins slave and keep everything project related inside the VMs.

However, we're running into really hard issues related to SSH, once two or more jobs get started in parallel the provisioning process randomly fails with: `SSH connection unexpected closed. Assuming reboot or something.`

I've already spent half of this week trying to figure out what's going on, but I still haven't figured out what causes these issues. The drops happen completely at random, in the error log below SSH failed right after the start of the 4th provisioning script, but this can also happen in the middle / at the end of any of the scripts.

We're forwarding SSH into the machines in order to clone private repositories, vagrant is launched like this:

`ssh-agent sh -c 'ssh-add && vagrant up --debug'`

The first provisioning script also takes care of adjusting the SSH configuration inside the box and restarts the ssh daemon:

```
ServerAliveInterval 300
ServerAliveCountMax 2

ClientAliveInterval 300
ClientAliveCountMax 5
```
Running a single box in isolation works completely fine, but as soon as 2 or more are running in parallel there is a 90% chance of at least one of them failing.

### Vagrant version

Vagrant 1.8.1

### Host operating system

Ubuntu 14.04

### Guest operating system

Ubuntu 14.04

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|

    config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024 
    end 

    config.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync_exclude: ['.git', '.vagrant', 'node_modules']

    config.vm.provision "shell", path: "./ci/0.ssh.sh"
    config.vm.provision "shell", path: "./ci/0.system.sh"
    config.vm.provision "shell", privileged: false, path: "./ci/1.user.sh"
    config.vm.provision "shell", privileged: false, path: "./ci/2.build.sh"
    config.vm.provision "shell", privileged: false, path: "./ci/3.doc.sh"
    config.vm.provision "shell", privileged: false, path: "./ci/4.deploy.sh"

end
```

### Debug output

https://gist.github.com/BonsaiDen/2139235fcfb13c0700b1da34e4e0d077

### Expected behavior

Provisioning any number of boxes in parallel should just work.

### Actual behavior

SSH connections randomly drop once one or more machines are running in parallel.

**Comment by sethvargo** [comment]
Hi @BonsaiDen 

Thank you for opening an issue. Are you running inside a virtualized environment on CI or are you on bare metal? These types of issues tend to occur when you have doubly-nested hypervisors

**Comment by timbuchwaldt** [comment]
I happen to know that we run inside a VCenter here (I operate the CI Server :P).
Is there any known solution to this apart from switching to bare metal?

**Comment by sethvargo** [comment]
Hi @timbuchwaldt 

Doubly-nested virtualization is something that is generally not supported, because typically you encounter issues in the hypervisor around networking and performance. I think that's what you're hitting here, unfortunately. This is not a Vagrant issue, it's just he nature of doubly-nested virt.
