### ISSUE TITLE
Provide extra options for filtering the list for vagrant global-status.

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#7220]
I've Vagrant 1.8.1.

My goal is to list all ids of running machines and the current `vagrant global-status ` is in very bad format.

I may try to list the list of machines by:

    vagrant global-status | egrep -o "^[0-9a-f]+"

or even better for only running machines, like:

    vagrant global-status | awk '/running/{print $1}'

however ideally would be if `vagrant` command can provide out-of-box.

So my suggestions for extra options are:

- add `--no-header`, to avoid printing extra header and notes, so all lines consist list of machines,
- add `--state=<state>` which can filtered e.g. by `running` only,
- add `--ids-only` to return list of ids based on already filtered list

**Comment by sethvargo** [comment]
Hi @kenorb 

Almost all commands in Vagrant produce `machine-readable` output:

https://www.vagrantup.com/docs/cli/machine-readable.html

Thanks!

**Comment by kenorb** [comment]
I think the machine format is even more difficult to parse in shell, since lines are printed on separated lines and aren't tied up (they're the same apart of the ending), e.g.

		460144340,cheshire-east,metadata,provider,virtualbox
		1460144340,,ui,info,id       
		1460144340,,ui,info,name          
		1460144340,,ui,info,provider   
		1460144340,,ui,info,state  
		1460144340,,ui,info,directory                                               
		1460144340,,ui,info,
		1460144340,,ui,info,-------------------------------------------------------------------------------------------------
		1460144340,,ui,info,9492f1e  
		1460144340,,ui,info,default       
		1460144340,,ui,info,virtualbox 
		1460144340,,ui,info,saved  
		1460144340,,ui,info,/Users/Foo/_VM              
		1460144340,,ui,info,
		1460144340,,ui,info,4008d7f  
		1460144340,,ui,info,cheshire-east 
		1460144340,,ui,info,virtualbox 
		1460144340,,ui,info,saved  
		1460144340,,ui,info,/Users/Foo/Bar

After running: `vagrant global-status --machine-readable | cut -d, -f5`, is difficult to distinguish which are running instances:

		virtualbox
		id       
		name          
		provider   
		state  
		directory                                               

		-------------------------------------------------------------------------------------------------
		9492f1e  
		default       
		virtualbox 
		saved  
		/Users/kenorb/Foo/_VM              

		4008d7f  
		cheshire-east 
		virtualbox 
		saved  
		/Users/kenorb/Sites/config

So it's much easier to parse the normal format, since you can grep the lines by state name and print the 1st column.
