### ISSUE TITLE
Please add Synced Folders / unison

### ISSUE THREAD

**Issue by cnkcb** [mitchellh/vagrant#7224]
[unison](https://www.cis.upenn.edu/~bcpierce/unison/) is an alternative to rsync; 

> Unison is a file-synchronization tool for OSX, Unix, and Windows. It allows two replicas of a collection of files and directories to be stored on different hosts (or different disks on the same host), modified separately, and then brought up to date by propagating the changes in each replica to the other.

**Comment by sethvargo** [comment]
Hi @cnkcb 

Thank you for opening an issue. Our general policy with new Vagrant features like this is to suggest their development as a plugin first. Once the plugin gains in popularity, we can discuss moving the plugin into Vagrant core. Thanks! :smile:

**Comment by pbowyer** [comment]
@cnkcb Please see https://github.com/mitchellh/vagrant/issues/7124 for a prior discussion on this.
