### ISSUE TITLE
Your VM has become "inaccessible". Over 10 VM's disappeared?

### ISSUE THREAD

**Issue by gRoberts84** [mitchellh/vagrant#7225]
### Vagrant version
Vagrant 1.8.1

### Host operating system
OSX El Capitan - `Darwin Kernel Version`

### Guest operating system
Ubuntu Precise 64 (multiple)

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Provision
  config.vm.provision :shell, :path => "bootstrap.sh"

  # To access a website running on port 8000, we can open a web browser
  # on our workstation and go to http://localhost:8000
  config.vm.network "private_network", ip: "192.168.33.250"

  # Shared folder
  config.vm.synced_folder "./src", "/home/vagrant/leadr", :mount_options => ["dmode=777", "fmode=666"]
end
```
**Bootstrap.sh**
```shell
#!/usr/bin/env bash

apt-get update

# install python
apt-get install python-dev python-pip -q -y
```

### Debug output
https://gist.github.com/gRoberts84/3571678cda49d0ad8ff596c498427db0

### Expected behavior
Vagrant box should have started

### Actual behavior
```
Your VM has become "inaccessible." Unfortunately, this is a critical error
with VirtualBox that Vagrant can not cleanly recover from. Please open VirtualBox
and clear out your inaccessible virtual machines or find a way to fix
them.
```

**Note:** After updating to 1.8.1 today, I now have two folders:

* VirtualBox VMs
* virtualbox_vms

The VM I'm trying to up, I used on Friday and suspended without any issues. My machine has been off over the weekend, so can only attribute it to the update?

Two VM's were running at the time and they still exist within `VirtualBox VMs` where as everything else exists within `virtualbox_vms`.

### Steps to reproduce
N/A

### References
N/A

**Comment by sethvargo** [comment]
Hi @gRoberts84 

Thank you for opening an issue, and I am sorry this is causing you issues. If you look in the debug output, you'll see that Vagrant is looking for a VM here:


    Config file:     /Users/gavin_roberts/VirtualBox VMs/Project_default_1459761108215_15869/Project_default_1459761108215_15869.vbox

Does that file exist on your filesystem? Are you running a case-sensitive file system?

Unfortunately, as the error says, this is not really a Vagrant issue. VirtualBox is throwing the error, which is usually an indication of a flawed or corrupted install of the VirtualBox software.

**Comment by gRoberts84** [comment]
Hey @sethvargo 

Turns out there are two folders, `VirtualBox VMs` and `virtualbox_vms`. 

All of my VM's that were halted/stopped had been moved to `virtualbox_vms` but the two still running were kept within `VirtualBox VMs`. The `VirtualBox.xml` file still referenced `VirtualBox VMs` so after changing those paths and restarting the boxes, they all came back to life.

Not entirely sure what could have caused that to happen? VirtualBox hasn't updated as of yet, so can't see it being a post update process of that?

I'm back up and running now (worried I had lost my machines) however thought you should know just in case it was related to the update?

Thanks :smile:

**Comment by sethvargo** [comment]
Hi @gRoberts84 

Thank you for your reply, I definitely understand how that could be confusing, but there's actually nothing in Vagrant's core that would cause that. It's possible that you have another tool that moved the VM (the old docker-machine had issues like this), or VirtualBox just flaked out. Given the size of Vagrant's user-base plus this being the first encounter of an issue like this, I'm included to believe it's something external :smile: 

We can definitely always revisit this if we get a solid repro case though. Thanks!

**Comment by gentlelynn** [comment]
Hello, I have the same problem but I have solved it .Just delele the original virtual box and install it again .And now it's working~

**Comment by marcnewton** [comment]
Had a similar issue, In my case the `<vm-name->.vbox` file had vanished but there was a ...vbox-tmp and ...vbox-prev copy of it in the directory. 

`\Users\<user_name>\VirtualBox VMs\<vm-name>\<vm-name>.vbox` **- Missing**

Renamed `...\<vm-name>.vbox-tmp` to `...\<vm-name>.vbox` solved my issue.

**Comment by CastixGitHub** [comment]
Had similar issue, In my case it was just that I didn't mount my external drive (where my VAGRANT_HOME is)
