### ISSUE TITLE
Installing chef is the longest process

### ISSUE THREAD

**Issue by kpietrzak-web** [mitchellh/vagrant#7231]
Process `default: Installing Chef (latest)` absorbs most amount of time, more than all other actions.

Can I cache it or shorten this time on some other way?

**Comment by sethvargo** [comment]
Hi @kpietrzak-web 

Thank you for opening an issue. This is not a bug in Vagrant, but there are a number of things you can do to cache the package. You can use third-party plugins like `vagrant-cachier` to help with this. Thanks!
