### ISSUE TITLE
Cannot force provision with vagrant up

### ISSUE THREAD

**Issue by Steiny69** [mitchellh/vagrant#7232]
I am using the shell provisioner and no matter whether I set `run: "always"` or provide the `--provision` option Vagrant does not run the provisioner when running `vagrant up`.
### Vagrant version

1.8.1
### Host operating system

Windows 10 Pro
### Guest operating system

CentOS 6.5
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "puphpet/centos65-x64"

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    touch $(date +%s)
  SHELL
end
```
### Debug output

https://gist.github.com/Steiny69/73769d5c3df7d202110a23cfde8c73ca
### Expected behavior

The shell script provisioner should have been run.
### Actual behavior

The shell script provisioner was not run.
### Steps to reproduce
1. Create a new directory with the Vagrantfile above
2. Run `vagrant up`
3. Run `vagrant up --provision`

**Comment by chrisroberts** [comment]
I believe this to be the expected behavior. The `vagrant up` command will create or start the VM and then provision it if instructed. If the VM is currently running, then there is nothing for it to do. After the VM is up, subsequent provisions should be performed with the `vagrant provision` command.

Cheers!

**Comment by dnadle** [comment]
Then why have the --provision option at all?

**Comment by chrisroberts** [comment]
The option defaults to on and allows for bringing the VM up _without_ provisioning it via:

```
$ vagrant up --no-provision
```

**Comment by dnadle** [comment]
The online documentation for vagrant up is: 

--[no-]provision - Force, or prevent, the provisioners to run.

The option doesn't default to on. It defaults to nothing,
