### ISSUE TITLE
Windows file provisioner fails with directories that have spaces

### ISSUE THREAD

**Issue by rgl** [mitchellh/vagrant#7234]
### Vagrant version

Vagrant 1.8.1
### Host operating system

Windows 10.
### Guest operating system

Windows 2012r2
### Vagrantfile

``` ruby
config.vm.provision "file", source: "etc/org.jenkinsci.plugins.MsTestBuilder.xml", destination: "C:\\Program Files (x86)\\Jenkins\\"
```
### Debug output

```
==> jenkins: Running provisioner: file...
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir (x86) -force
```
### Expected behavior

It should properly escape the `destination` (and `source`) parameter.

**Comment by sethvargo** [comment]
Hi @rgl 

Thank you for opening an issue. This is a known issue, and I swear there's another issue tracking it, but I cannot find it right now. Thank you for reporting.
