### ISSUE TITLE
Vagrant fail to initialize after Docker plugin installation

### ISSUE THREAD

**Issue by elarbi** [mitchellh/vagrant#7235]
Hi,

After installing Docker plugin on Vagrant 1.8.1 I have the following error when launching vagrant up or even vagrant status:

```
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- pty
```
If I uninstall the Docker plugin I get:

> vagrant up
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: build-env_default_1460797577798_14760
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: You are trying to forward to privileged ports (ports <= 1024). Most
==> default: operating systems restrict this to only privileged process (typically
==> default: processes running as an administrative user). This is a warning in case
==> default: the port forwarding doesn't work. If any problems occur, please try a
==> default: port higher than 1024.
==> default: Forwarding ports...
    default: 3306 (guest) => 3306 (host) (adapter 1)
    default: 27017 (guest) => 27017 (host) (adapter 1)
    default: 8080 (guest) => 8180 (host) (adapter 1)
    default: 8787 (guest) => 8787 (host) (adapter 1)
    default: 9990 (guest) => 9990 (host) (adapter 1)
    default: 80 (guest) => 800 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
```
Any idea ?

Thanks

**Comment by elarbi** [comment]
VirtualBox version = 5.0.2

**Comment by elarbi** [comment]
I still have the same pb with VirtualBox 5.0.16

**Comment by sethvargo** [comment]
Hi @elarbi 

Thank you for opening an issue. Which plugin did you install? Can you please share the output of the Vagrant command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html) as a GitHub Gist?

**Comment by elarbi** [comment]
Sure: https://gist.github.com/elarbi/8e4191e2ab2552811c28ad16d0700eb8

> vagrant plugin list
docker (0.3.1)
vagrant-share (1.1.5, system)

**Comment by sethvargo** [comment]
Hi @elarbi 

It looks like you have somehow installed the docker gem into Vagrant's plugin environment. Could you please uninstall that plugin:

```
$ vagrant plugin uninstall docker
```

And then re-run the commands?

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by MartinSGill** [comment]
@sethvargo I think part of the problem might be that `vagrant plugin install` seems to just install any old gem.

I had this same issue just now; where I installed `vagrant plugin install docker-compose` expecting to get the docker compose plugin. What I actually got was the docker-compose gem.

It might be nice if some form of validation could take place, as this is not the result "of least surprise", and took me a while to figure out and resolve.

**Comment by Hipposterous** [comment]
`vagrant plugin install docker`
Installing the 'docker' plugin. This can take a few minutes...
Installed the plugin 'docker (0.3.1)'!

`vagrant --help`
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- pty
