### ISSUE TITLE
fs_real_path causes Vagrant crashes in some environments by demanding access to "/"

### ISSUE THREAD

**Issue by themasterchef** [mitchellh/vagrant#7236]
I'm building a Swift based OS X native app which executes Vagrant commands using NSTask under the covers to get its work done. Unfortunately Vagrant is not playing nice with the app sandbox - but in an unexpected way...

### Vagrant version

1.8.1

### Host operating system

Mac OS 10.11.4

### Guest operating system

Not applicable (didn't get that far before Vagrant crashed!)

### Vagrantfile

Not applicable (was just trying to run `vagrant global-status`)

### Debug output

https://gist.github.com/themasterchef/6e3a9302f519a777918e275993a0f1ae

### Expected behavior

Vagrant successfully runs the global-status command inside the sandboxed NSTask invocation.

### Actual behavior

The sandbox kills the Vagrant process when it tries to access "/" on the host OS, so the command cannot complete successfully.

### Steps to reproduce

1. Execute `vagrant global-status` from inside an Xcode Mac app with sandbox switched on.
2. Observe sandbox blocking access to "/", with an error like `lib/vagrant/util/platform.rb:163:in `open': Operation not permitted @ dir_initialize - / (Errno::EPERM)`
3. Put a temporary exception in the app entitlements to give read-write access to ".vagrant.d", then re-run the command.
4. Observe that it still gets killed by the sandbox at the same place.
5. Use a temporary exception to give read-write access to "/" (whole drive) *as the current user*.
6. Observe that *even with near root level FS privileges* it still gets killed by the sandbox at the same place.

### Musings on the cause

I fully expect Vagrant to want access to the ~/.vagrant.d working folder, and there are nice user intent driven ways to grant access to that folder which play nicely with the app sandbox. However the problem seems to be in the exact method used to resolve that folder.

My suspicion is that the fs_real_path method in Vagrant's utilities - specifically, the code around line 163 in lib/vagrant/util/platform.rb - recursively steps through the directory structure specified by VAGRANT_HOME to build up a path to the Vagrant home directory. Unfortunately, the first component in that URL is "/" - which is owned by root (at least on my Mac). This means that even the last ditch "god" access to the whole drive provided by the temporary exception is not enough, as the app is only given access to the file system as the current (non-root) OS X user.

Is there any other way to achieve what this fs_real_path routine is being used today to achieve? Its current approach seems like overkill when its purpose seems to be just to expand a path.

**Comment by themasterchef** [comment]
Quick n' dirty first draft of a fix:

It turns out that when you execute Vagrant with the app sandbox turned on, the path variable set at the top of fs_real_path contains just 1 string: an absolute path to a .vagrant.d folder inside the App Containers Data directory.

In other words `/Users/[me]/Library/Containers/[myapp]/Data/.vagrant.d`

Now if the app doesn't need to share a .vagrant.d folder with any other app, maybe we can just return this value at this point, before the Dir.entries line is hit.

Code looks like this:

```ruby
def fs_real_path(path, **opts)
  path = Pathname.new(File.expand_path(path))

    # TODO turn into a vagrant variable
    # maybe an environment variable
    # or maybe it should be inferred from the path name - discuss
    is_app_sandboxed = true

    if is_app_sandboxed
        # The path, by default, is the Vagrant working folder
        # inside the Library Containers Data directory
        # e.g. "~/Library/Containers/[myapp]/Data/.vagrant.d"
        #
        # Also the sandbox will kill Vagrant if it tries to operate
        # on folders owned by root - like / - so for this use case
        # we must avoid the loop that uses Dir.entries below.
        return path
    end

  if path.exist? && !fs_case_sensitive?
    # If the path contains a Windows short path, then we attempt to
    # expand. The require below is embedded here since it requires
    # windows to work.
    if windows? && path.to_s =~ /~\d(\/|\\)/
      require_relative "windows_path"
      path = Pathname.new(WindowsPath.longname(path.to_s))
    end

    # Build up all the parts of the path
    original = []
    while !path.root?
      original.unshift(path.basename.to_s)
      path = path.parent
    end

    # Traverse each part and join it into the resulting path
    original.each do |single|
      Dir.entries(path).each do |entry|
        if entry.downcase == single.encode('filesystem').downcase
          path = path.join(entry)
        end
      end
    end
  end

  if windows?
    # Fix the drive letter to be uppercase.
    path = path.to_s
    if path[1] == ":"
      path[0] = path[0].upcase
    end

    path = Pathname.new(path)
  end

  path
end
```

**Comment by sethvargo** [comment]
Hi @themasterchef 

Thank you for opening an issue. Vagrant requires root-level access to the filesystem and root-level permissions to perform some operations. Additionally Virtualbox (the most common provider for Vagrant) requires root permissions in order to interaction with the kernel's virtualization layer. Vagrant is not really designed to be distributed as an "app", and I do not think this is something we plan to implement ourselves. Sorry and thank you for all the research! 😄
