### ISSUE TITLE
Vagrant running on OS X in Vagrant managed VMware instance fails to download box

### ISSUE THREAD

**Issue by schlueter** [mitchellh/vagrant#7242]
### Vagrant version
1.8.1 On both primary host and on secondary host/first guest

### Host operating system
OS X 10.11 on both primary host and on secondary host/first guest

### Guest operating system
OS X 10.11 on first guest
Attempting to use Ubuntu trusty64 (ubuntu/trusty64 from atlas) on second, inner guest

### Vagrantfile
On primary host (using vagrant-vmware-fusion (4.0.8)):
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "osx1011"
end
```
The *osx1011* box is a custom OS X base box, as default as possible with modifications only as needed to be a Vagrant base box and to run virtualbox within it.

On secondary host:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
end
```

### Debug output
https://gist.github.com/schlueter/e5d838fd216e033acb944752632c11b0

### Expected behavior
Vagrant running on a VMware instance managed by Vagrant should have downloaded the ubuntu/trusty64 base box.

### Actual behavior
The attempted download of the base box fails with `curl: (56) Recv failure: Connection reset by peer`.

Admittedly, I suspect this may be a VMware issue and not a Vagrant one, but I thought y'all might have some insight or potential fixes involving network configuration of the OS X instance.

Also, the failure tends to occur later during the download, but has occurred even during the download of Virtualbox. I was able to reproduce with the ubuntu/trusty64 box (though I also successfully downloaded it once), but in my complete use case, I'm downloading a ~5GB pre provisioned base box, so the error effectively always occurs.

### Steps to reproduce
1. Create an OS X 10.11 base box with VMware with default settings except for selecting `Enable hypervisor applications in this virtual machine` in the *Processors & Memory* settings.
2. Bring up and ssh into a bare instance created with the OS X base box.
3. Install Vagrant
4. Create a Vagrant instance with `mkdir test && cd test && vagrant init --minimal ubuntu/trusty64 && vagrant up`
5. Failure occurs either during Virtualbox installation or box download.

**Comment by sethvargo** [comment]
Hi @schlueter 

Thank you for opening an issue. As I understand correctly, you're running virtualbox inside of vmware? Unfortunately this doubly-nested virtualization is not supported. Usually there are transient network issues (like you're experiencing using curl) and significant performance problems. Unfortunately this isn't even a VMware bug - this is just the nature of nested hypervisor performance. Please let me know if you have any questions.

**Comment by StefanScherer** [comment]
@schlueter You can automate step 1 to enable nested hypervisor for VMware Fusion/Workstation in your Vagrantfile with

```
    ["vmware_fusion", "vmware_workstation"].each do |provider|
      config.vm.provider provider do |v, override|
        v.gui = true
        v.vmx["memsize"] = "4096"
        v.vmx["numvcpus"] = "2"
        v.vmx["vhv.enable"] = "TRUE"
      end
    end
```

I'm using nested hypervisor a lot testing Vagrant and Docker in a clean "host" w/o touching my real host machine 😃 Here is my [Vagrantfile](https://github.com/StefanScherer/mac-dev-box/blob/master/Vagrantfile).

So it seems that you only have a network/DNS problem inside your VM. I had a look at your gist, it downloaded parts of the box, so probably only a temporary issue with network timeouts? Just try it again.

<img width="1440" alt="bildschirmfoto 2016-04-19 um 08 27 47" src="https://cloud.githubusercontent.com/assets/207759/14629694/bba0d2f8-0608-11e6-94a6-0366996fecda.png">

**Comment by schlueter** [comment]
@sethvargo, thanks for the response, I was somewhat expecting that to be the case. I  suppose I'll just have to drop to bare metal for the test I'm building.

@StefanScherer, thanks for that too, I was wondering what options to vmx were available, but I hadn't gotten around to looking yet.

**Comment by StefanScherer** [comment]
@schlueter The vmx settings are the keys of the *.vmx file, so you can have a look there, eg. to turn on audio, etc.
