### ISSUE TITLE
invalid NFS exports

### ISSUE THREAD

**Issue by xunxky** [mitchellh/vagrant#7243]
### error environment: 
- vagrant version 1.8.1 
- setting up average (any) puphpet box (with debian wheezy)
- virtual box provider
- only default shared folder type => virtual box shared folders 

### error description: 
Pruning invalid NFS exports. Administrator privileges will be required...

problem here is that there are several reports of this happening but no viable solution 
again: no nfs folders are used

**Comment by sethvargo** [comment]
Hi @xunxky 

Thank you for opening an issue. Unfortunately there is not enough information here for our team to take any action. Please open a _new issue_ and follow the supplied issue template which includes providing a sample Vagrantfile, commands run, and the debug output.

**Comment by xunxky** [comment]
yea, for anyone also running in that issue: 
vagrant has changed the way it cleans up nfs folders. 
if only the old way is supported by your sudoers config, one execution of a nfs box is enough to "poison" your status 

in my case only a downgrade and running an unrelated box solved the issue, as we do not have the privileges to change sudoers. 

so it was an layer 8 or rather 9 issue.
