### ISSUE TITLE
Vagrant 1.8.1 fails to run: EINVAL from user_interaction.rb on Windows 8.1

### ISSUE THREAD

**Issue by coldacid** [mitchellh/vagrant#7247]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

`vagrant -v` won't work; as seen in Programs control panel version is 1.8.1
### Host operating system

Windows 8.1 (build 9600)
### Guest operating system

N/A
### Vagrantfile

N/A
### Debug output

https://gist.github.com/coldacid/9acbd8b1374df3e4a4fe3eb74434a202
### Expected behavior

Vagrant should run appropriately for any command given to it.
### Actual behavior

Regardless of command line used to execute Vagrant, it always immediately terminates with the error & stack trace from the debug output gist above.
### Steps to reproduce
1. Run `vagrant up`, or
2. Run `vagrant -v`
### Notes

It appears that user_interaction.rb expects `ENOENT` on line 689, but Windows returns an `EINVAL` error code instead. By adding a second `rescue` line for `EINVAL` between lines 689 and 690, Vagrant works as expected.

**Comment by sethvargo** [comment]
Hi @coldacid 

I'm sorry you are having problems. May I ask - how did you install Vagrant, and which version?

**Comment by coldacid** [comment]
@sethvargo: I installed Vagrant 1.8.1 via Chocolatey (package version 1.8.1.20160318). Turns out that this is an issue between Rubygems and Windows that is currently being tracked at https://github.com/rubygems/rubygems/pull/1588

**Comment by sethvargo** [comment]
Hi @coldacid 

I love package manages, but could you please try the official installer from https://www.vagrantup.com/downloads.html and see if it persists?

**Comment by coldacid** [comment]
@sethvargo The Chocolatey package for Vagrant actually downloads the official installer and runs it. The current version of the package applies https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1.msi to the system.

**Comment by chrisroberts** [comment]
@coldacid Can you confirm if you are still experiencing this behavior in latest release of Vagrant? Thanks!

**Comment by coldacid** [comment]
Last I checked, I still was, but I haven't needed to use Vagrant in months and I don't think I even installed it on my current work machine. So long as Rubygems for the integrated Ruby distribution is up to date (which for 1.8.1 "out of box" is not the case) there is no problem.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
