### ISSUE TITLE
vagrant up with "rsync" should either warn the user or do rsync-auto

### ISSUE THREAD

**Issue by dkarlovi** [mitchellh/vagrant#7248]
If you're using the `rsync` method, you might forget to run `vagrant rsync-auto` after `vagrant up`. This might lead to some confusion with new users.

I propose to allow for running `rsync-auto` automatically (ideally, allowing for switching the behaviour on or off via the `Vagrantfile`) and emitting a warning at the end of `vagrant up`'s output if it's off.

Thanks.

**Comment by brianmorton** [comment]
This is essentially the same functionality as the plugin `gatling-rsync-auto` for OSX, which I am a fan of.

**Comment by sethvargo** [comment]
Hi @dkarlovi 

I looked into this, and, unfortunately, it's not technically possible without writing our own init and management system. Once Vagrant exits, it's job is done, whereas the rsync-auto is a foreground process that only stops when the user terminates it. Thank you for understanding!
