### ISSUE TITLE
nokogiri (LoadError) on Windows 7 with AWS provider

### ISSUE THREAD

**Issue by peterbaumgarten** [mitchellh/vagrant#7250]
### Vagrant version
1.8.1

### Host operating system
Windows 7

### Guest operating system
Amazon Linux 2015.09

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "Peter Baumgarten"
    aws.ami = "ami-f36a7799"
	aws.aws_dir = ENV['HOME'] + "\\.aws\\"
	aws.aws_profile = "default"
	aws.availability_zone = "us-east-1"
	aws.instance_type = "t2.micro"
	aws.security_groups = "AMI BASE ACCESS"
	aws.subnet_id = "subnet-a7c8bb8c"
	aws.tags = {
	           "Name" => "Peter Baumgarten",
			   "Creation Method" => "Vagrant"
	}
	override.ssh.username = "ec2-user"
	override.ssh.private_key_path = "C:\\Users\\pbaumgar\\putty\\openssh_private"
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/peterbaumgarten/fe255dea2e1cd4d358f792595137fa1a

### Expected behavior
a normal vagrant up using the aws provider

### Actual behavior
A crash with an error message about nokogiri being unable to load
https://gist.github.com/peterbaumgarten/3d21fd32ecbc1db5363b513118602da9

### Steps to reproduce
1. vagrant up using aws provider on windows 7 using latest vagrant

Let me know if there is other information I can add

**Comment by peterbaumgarten** [comment]
vagrant with virtualbox provider works fine. It seems to be only with the aws provider

**Comment by sethvargo** [comment]
Hi @peterbaumgarten 

This seems to be a bug with the aws provider. Could you please open an issue on that plugin? Thanks!

**Comment by peterbaumgarten** [comment]
In case anyone is interested: https://github.com/mitchellh/vagrant-aws/issues/460
