### ISSUE TITLE
Guru Meditation -306 (VERR_MORE_DATA) ubuntu/xenial64 

### ISSUE THREAD

**Issue by basictheprogram** [mitchellh/vagrant#7259]
Not a bug in Vagrant, but posting the VirtualBox issue here so people can find it here and get linked to the issue open at Virtualbox.

https://www.virtualbox.org/ticket/15345

Close this issue if you feel that's appropriate.

**Comment by sethvargo** [comment]
Thanks!

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/7257
