### ISSUE TITLE
Error when using uninstall.tool: invalid argument `+2w' to `-mtime'

### ISSUE THREAD

**Issue by behrangsa** [mitchellh/vagrant#7262]
```
...

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
find: invalid argument `-1d' to `-mtime'
Deleting expired sessions...find: invalid argument `+2w' to `-mtime'
none found.
```

**Comment by sethvargo** [comment]
Hi @behrangsa 

Thank you for opening an issue. Unfortunately there is not enough information here to understand the issue. Would you mind completing the full issue template that appears when you open the issue? Thanks!

**Comment by behrangsa** [comment]
Hi @sethvargo,

No worries. Give me some time and I'll add more details.

Cheers,
Behrang

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄

**Comment by nizmogtr** [comment]
This happens when gnu find is in the path
