### ISSUE TITLE
Vagrant not honoring galaxy_roles_path when looking for galaxy modules

### ISSUE THREAD

**Issue by pfremm** [mitchellh/vagrant#7269]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.8.1

### Host operating system
Mac OS X 10.11
### Guest operating system
Cent 7
### Vagrantfile
Ansible is honoring my requirements.yml and installing the roles in the specified directory and I'm specifying role location like:
ansible.galaxy_role_file = "./roles/requirements.yml"

When running playbook it's not honoring 
          ansible.galaxy_roles_path = "./ansible-kubernetes/galaxy"
The ansible output from when the playbook fails shows it's not even looking in the specified directory
### Expected behavior
Reference galaxy roles in specified path of galaxy_roles_path

### Actual behavior
Playbook fails as it's unable to find the roles
### Steps to reproduce
1. Run vagrant up with glaxay roles path specified

**Comment by gildegoma** [comment]
@pfremm thank you for reporting this bug. I tag it to be fixed for the next vagrant version, most probably by setting the `ANSIBLE_ROLES_PATH` environment variable for the `ansible-playbook` command when `galaxy_roles_path` option is defined.
