### ISSUE TITLE
vagrant plugin update fails

### ISSUE THREAD

**Issue by richard-scott** [mitchellh/vagrant#7271]
### Vagrant version
```
$ vagrant -v
Vagrant 1.8.1
$ vagrant plugin list
vagrant-share (1.1.5, system)
vagrant-triggers (0.5.3)
vagrant-vbguest (0.11.0)
```

### Host operating system
```
$ cat /etc/redhat-release
Scientific Linux release 7.2 (Nitrogen)
```

### Guest operating system
Not a Guest OS problem.

### Expected behavior
Running this should work:
```
$ vagrant plugin update
```

### Actual behavior
I got this:
```
$ vagrant plugin update
Updating installed plugins...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing multi_json (1.11.3), and Bundler cannot continue.
Make sure that `gem install multi_json -v '1.11.3'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: (null) (https://rubygems.global.ssl.fastly.net/gems/multi_json-1.11.3.gem)
```
And after a bit of digging found this error with the 'gem' command:

```
$ gem install multi_json -v '1.11.3'
ERROR:  Could not find a valid gem 'multi_json' (= 1.11.3), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: (null) (https://rubygems.global.ssl.fastly.net/specs.4.8.gz)
```

**Comment by richard-scott** [comment]
It seels this site does not work anymore:

[https://rubygems.global.ssl.fastly.net/specs.4.8.gz](https://rubygems.global.ssl.fastly.net/specs.4.8.gz)

If I remove the SSL and go here:

http://rubygems.global.ssl.fastly.net/specs.4.8.gz

I get blocked by my ISP with this warning:

This site has been blocked by Web Safe. It's listed as having content that’s inappropriate for children, involving either pornography, hate, crime, drugs, violence, hacking, self harm or suicide.

**Comment by sethvargo** [comment]
Hi @richard-scott 

The issue you are experiencing is coming from Ruby, the underlying programming language for Vagrant, and your internal firewall.

**Comment by richard-scott** [comment]
@sethvargo you are correct, it looks like VirginMedia's web filter is what's blocking this ;-(
