### ISSUE TITLE
Silent failure on `vagrant box repackage` with insufficient disk space

### ISSUE THREAD

**Issue by tabrindle** [mitchellh/vagrant#7273]
### Vagrant version
1.8.1

### Host operating system
OSX 10.11.4

### Guest operating system
OSX 10.11.4

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "jhcook/osx-elcapitan-10.11"
end
```
### Debug output
No output

### Expected behavior
- Error message explaining that disk space was insufficient
- Delete partially repackaged *.box file, temp files

### Actual behavior
- No error message
- Partial & corrupt *.box file left in target directory

### Steps to reproduce
1. vagrant init jhcook/osx-elcapitan-10.11; vagrant up --provider virtualbox
2. Ensure disk space is insufficient to repackage (Less than size of box * 2?)
2. vagrant box repackage jhcook/osx-elcapitan-10.11 virtualbox 10.11.4 

### References
None.

This issue will be especially prevalent on hosts with small drives, or are using a large guest OS. In this case, the final size of the guest OS was > 20GB (OSX + Xcode, Android sdk, build tools, etc) The only indication that the process had failed was that the final product .box file was only 7GB not the 20GB that was expected.

**Comment by sethvargo** [comment]
Hi @tabrindle 

Could you please share the debug output? If you run Vagrant in [debug mode](https://www.vagrantup.com/docs/other/debugging.html) there will be a ton of output.

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a _new issue_ and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by tabrindle** [comment]
Sorry, lot's of backlog - once my disk fills up, Ill open up a new ticket with more verbose logging. Thanks!
