### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication

### ISSUE THREAD

**Issue by AbdenourAchab** [mitchellh/vagrant#7274]
This is similar to the ticket #2251, but 2251 is closed. So, I am filing it as a new one.

I get the error
"Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported."

Here is how to reproduce the problem on Ubuntu 16.04 LTS, assuming the relevant stuff (docker, vagrant, npm, etc.) is already installed on your computer:

`$ npm install -g yo`
`$ npm install -g https://github.com/activelamp/generator-drupalal.git`
`$ yo drupalal`

The above will try to create a skeleton web site for you. It will ask you a couple of questions, then, among other things, will try to use Vagrant. At that point, you will get the "Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported." error message.

You can try to delete ~/.vagrant.d and restart from scratch (including removing the contents of the directory to which you imported stuff with the yo command), and you will still get the same error message.

It would be great if you could get this fixed by the end of 2016.

**Comment by AbdenourAchab** [comment]
While waiting for the Vagrant bug to be fixed, I am looking for a workaround for my problem.

I have done some more investigating. Vagrant/Docker successfully create the drupal-container, then fails at starting the same container with the "Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported." error message.

Yet, less than a minute after it fails, I successfully started the same container manually by typing "docker start <container id="">. I did verify with "docker ps" that the container is running.

So, if there is a way to make drupalal wait a minute or so, after it creates the container, before starting it, the above mentioned error message should go away.

How do I make drupalal wait a minute before trying to start the container ? Is there some sleep command I can put somewhere in some file ? If so, what's the command, which file should I put it into, and at which line ?

Thanks in advance.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
