### ISSUE TITLE
Allow host_vm for Docker provider to be disabled on non-Linux hosts

### ISSUE THREAD

**Issue by hunterboerner** [mitchellh/vagrant#7277]
On non-Linux hosts Vagrant will create a host_vm to run docker containers in. Normally this is fine, however if the user has something like [dlite](https://github.com/nlf/dlite), they may wish to use that instead (a single VM can be used for many docker containers, which is _much_ faster than starting multiple Virtualbox VMs and does not have the concurrency issues that VBox has).

The method which determined whether a host_vm is necessary: https://github.com/mitchellh/vagrant/blob/cdafc63a61f091793dfde164b38561c1e9bdb197/plugins/providers/docker/provider.rb#L130-L133

Are you open to adding a config parameter to allow overriding this?

**Comment by faxioman** [comment]
+1!!!
We love docker-machine created with xhyve so no needs for a vagrant host.

**Comment by till** [comment]
@faxioman @hunterboerner #7298 — does this work for you? I just wanted a quick thing to test this after I received my Docker for Mac invite.

Here's a small wrapper to run vagrant from the source:

```
#!/bin/bash

actual_dir=$PWD
log_level=warn

cd /Users/till/Documents/workspaces/till/vagrant # this needs to be adjusted
VAGRANT_LOG=$log_level VAGRANT_CWD=$actual_dir bundle exec vagrant "$@"
```

Put this into my path as `vagrant-src` and then `vagrant-src up --etc-pp`.

**Comment by faxioman** [comment]
@till yes, with that fix vagrant correctly creates the container using my docker-machine powered by xhyve... anyway, after running the container vagrant waits for ssh until the timeout exception is raised. Is vagrant starting the container with privileged attribute? Without the privileged attribute the openssh server can't start...

**Comment by faxioman** [comment]
(is it possible to test xhyve with docker without waiting for the 2.0 docker beta release. Using brew it's really simple to create an xhyve powered docker machine)

**Comment by till** [comment]
@faxioman I am playing with it also. I am trying to use `phusion/baseimage` in order [to get SSH working](https://github.com/phusion/baseimage-docker#login_ssh). They have a few work-arounds to enable `sshd`. I honestly know too little about Docker itself to get started. E.g. just learned that I need a long running process inside my container. ;))

To see what vagrant itself does, I suggest to set the `log_level` variable inside my script to debug. If you pipe that to `less`, like, `vagrant-src up --provider docker | less`, you can search the output for anything `docker` right away.

**Comment by hunterboerner** [comment]
@faxioman yes, I mentioned [dlite](https://github.com/nlf/dlite) in my original post.
