### ISSUE TITLE
VM does not pick up specified IP address (Ubuntu 16.04)

### ISSUE THREAD

**Issue by jazzfog** [mitchellh/vagrant#7278]
### Vagrant version
1.8.1

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16.04 xenial xerus

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.105.203"
end
```

### Debug output
http://pastebin.com/dURTXNA1

### Expected behavior
Server should start without errors

### Actual behavior
- Very long login ("default: Warning: Remote connection disconnect. Retrying..." messages)
- Error message
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
/sbin/ifdown eth1 2> /dev/null
Stdout from the command:
Stderr from the command:
sudo: unable to resolve host ubuntu-xenial
mesg: ttyname failed: Inappropriate ioctl for device
```
- The server is not responding on specified IP address
```
ping 192.168.105.203

Pinging 192.168.105.203 with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
```

### Steps to reproduce
Use `vagrantfile` above to create server on specified versions of software.

- When I use `ubuntu/trusty64` everything works as expected
- If I comment `config.vm.network "private_network", ip: "192.168.105.203"` line everything works as expected

**Comment by ugsite** [comment]
+1

**Comment by franko-franicevich** [comment]
Having the exact same problem at the moment with ubuntu/xenial64 with a similar vagrant file. 
A google search to try find a solution lead me to this defect report. Only difference is host operating system is MacOS X, also running vagrant 1.8.1;  and vm provider is virtualbox 5.0.16 r105871.  Upgraded virtual box to the latest (as of now)  5.0.20 r106931, and the problem still occurs.
