### ISSUE TITLE
private_key_path = $SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by pmoody-** [mitchellh/vagrant#7282]
I tried re-opening https://github.com/mitchellh/vagrant/issues/7115, but it doesn't appear that I can. What I'm looking to do is get vagrant to use a key on an existing ssh-agent process (which can be accessed via the env variable $SSH_AUTH_SOCK) rather than spawning a new ssh-agent or reading a key off disk.

Is this possible? can I get vagrant to just forward all ssh auth requests to an ssh-agent? if so, how would I do that.

all the other details from that previous issue should be the same.

**Comment by sethvargo** [comment]
Hi @pmoody- 

This is not possible. Vagrant needs to fully manage the SSH agent, and it doesn't look like there's a way to specify an agent in the Ruby bindings to openssh. As such, there would need to be an upstream language change to support this. Sorry1 😦
