### ISSUE TITLE
Unable to set hostname on Ubuntu 16.04 box

### ISSUE THREAD

**Issue by joseluisbolos** [mitchellh/vagrant#7288]
I am using the ubuntu/xenial64 box from here: https://atlas.hashicorp.com/ubuntu/boxes/xenial64

In my vagrantfile, I have:

`config.vm.hostname = "xenial1234"`

After booting up, setting the hostname fails:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -f

Stdout from the command:



Stderr from the command:

sudo: unable to resolve host ubuntu-xenial: Connection timed out
mesg: ttyname failed: Inappropriate ioctl for device
hostname: Temporary failure in name resolution
```

Changing to trusty64 fixes the problem.

### Vagrant version
Vagrant 1.8.1

### Host operating system
OS X 10.11.4

### Guest operating system
Ubuntu 16.04 Xenial Xerus

### Virtualisation software
VirtualBox 5.0.20

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "xenial1234"
end
```

### Debug
https://gist.github.com/joseluisbolos/889e7925a23d7fa0f19b4ae920b081e9

### References
This seems to be similar (but not necessarily the same) to: #4784 #5947 #6577 #6616

**Comment by macnibblet** [comment]
I have the same issue, pretty much blocking my development 👎

**Comment by krzysbaranski** [comment]
```
  # fix hosts ubuntu/xenial
  echo 127.0.0.1 `hostname` |sudo tee -a /etc/hosts

  # fix network ubuntu/xenial
  # disable Predictable Network Interface Names
  ip a show dev eth1 > /dev/null
  if (($? > 0)); then
    echo "#### eth1 not exists (eth1 and eth2 is expected by vagrant)"
    echo "#### turning off Predictable Network Interface Names"
    grep -q "net.ifnames=0" /etc/default/grub
    if (($? > 0)); then
      echo "GRUB_CMDLINE_LINUX=\"net.ifnames=0"\" | sudo tee -a /etc/default/grub
      sudo update-grub
      echo "#### restart box to disable Predictable Network Interface Names"
    fi
  fi
```

**Comment by joseluisbolos** [comment]
Hi @krzysbaranski, thanks to your comment I've realised there are even more issues that this one is related to. For future reference: #7155 #7241

**Comment by jaraco** [comment]
> temporary fix:

How does one implement this temporary fix? I tried adding the code to the provisioning script, but `vagrant up` still fails with the reported error. Does the workaround need to be applied to the box first?

**Comment by krzysbaranski** [comment]
@jaraco you have to run this manually (`vagrant ssh`) after failed provision and reload box with provisioning

**Comment by macnibblet** [comment]
I'm not having any success with the workaround. Anyone have any ideas on the main issue ?

**Comment by nhojpatrick** [comment]
I'm seeing the same issue from the box provided by ubuntu.

https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box

**Comment by landam** [comment]
I have also the same issue with the latest box provided by ubuntu...

**Comment by krzysbaranski** [comment]
You can try this proposed fix https://github.com/mitchellh/vagrant/pull/7318

**Comment by nhojpatrick** [comment]
That patch is for Debian not Ubuntu.

**Comment by nhojpatrick** [comment]
Looking at the ubuntu files I think the fixes for Vivid also need to be done for Wily and Xenial. Will look into do a patch.

**Comment by nhojpatrick** [comment]
The file (plugins/guests/ubuntu/cap/change_host_name.rb) already in master fixes host name change for ubuntu vivid, wily and also xenial as it now uses systemd. I also believe it needs the #7318 patch applied as well.

**Comment by awesomebing1** [comment]
There's a patch (#7253) that fixed this for me. It takes a little bit more to start up boxes on the first time you start up a box (further `vagrant up`'d boxes won't have this problem).

**Comment by mowings** [comment]
I realize it's a bit late for this, but if you are having issues with setting hostname on xenial, you can install libnss-myhostname in the container. This may prove useful if you don't want to upgrade vagrant to a later version. 

You may also want to unlink /lib/systemd/system/hostname.service (in the container) -- this will re-enable the hostname service so that you older versions of vagrant can properly set the hostname on xenial.
