### ISSUE TITLE
LXD provider

### ISSUE THREAD

**Issue by techtonik** [mitchellh/vagrant#7292]
### Vagrant version
1.8.1

### Host operating system
Linux.

### Guest operating system
Linux.

### Expected behavior
What should have happened?

Create lightweight LXD container.

### Actual behavior
What actually happened?

Don't know how to do that with Vagrant.

### Steps to reproduce
1. Open https://www.vagrantup.com/docs/providers/
2. Try to find available plugins (`vagrant list` doesn't work for remotes)
3. Get frustrated

### References
https://github.com/lxc/lxd

**Comment by sethvargo** [comment]
Hi @techtonik 

Thank you for opening an issue. With regard to new providers and features, we generally prefer to see these types of things implemented as plugins before building them into Vagrant core directly (see vagrant-aws, vagrant-digitalocean, vagrant-parallels, for examples). Thanks!

**Comment by techtonik** [comment]
https://github.com/mitchellh/vagrant/wiki/Available-Vagrant-Plugins

**Comment by georghopp** [comment]
Hi,
I know this is dead and buried but google still brings this up pretty early when you search for vagrant and lxd, so I add a post here to announce that I have written a provider plugin for lxd.
It is still pretty alpha, but does what I needed. Maybe this is of some help.
It is available via rubygems, so vagrant plugin install vagrant-lxd works. The source as well as some example boxes can be found here on github. These example boxes are also available on atlas. You may search for boxes from user ghopp.
Best regards,
    Georg

**Comment by techtonik** [comment]
@georghopp better post a link to those sources and the next time somebody tries to find it, Google may sent to the correct page.

**Comment by georghopp** [comment]
The sources can be found here:
https://github.com/georghopp/vagrant-lxd

**Comment by candeira** [comment]
There's now a plugin developed by Catalyst:

https://gitlab.com/catalyst-it/vagrant-lxd
