### ISSUE TITLE
[question] tag a new release

### ISSUE THREAD

**Issue by Ma27** [mitchellh/vagrant#7294]
the last release has been tagged last year according to the release list (https://github.com/mitchellh/vagrant/releases)
There are some very important bugfixes like the one which helps to support baseboxes containing the new ``ubuntu xenial 16.04`` (https://github.com/mitchellh/vagrant/issues/7155) and I'd love to see them in a stable release.

**Comment by sethvargo** [comment]
Hi @Ma27 

Thank you for opening an issue. We will release a new version shortly. Thanks!

**Comment by Ma27** [comment]
ok, great!
