### ISSUE TITLE
misleading Vagrantfile provisioning boilerplate

### ISSUE THREAD

**Issue by aogier** [mitchellh/vagrant#7295]
Hi, it seems that default boilerplate in `templates/commands/init/Vagrantfile.erb` is a little misleading:

    # config.vm.provision "shell", inline: <<-SHELL
    #   sudo apt-get update
    #   sudo apt-get install -y apache2
    # SHELL

sudo usage suggest that lines get executed as vagrant user, but they are indeed executed by root so no provilege escalation is needed (in some case, a shed would).

Did not found any clue on that on documentation either, found it via a painfully trial process.

Hope this helps, ciao

**Comment by sethvargo** [comment]
Hi @aogier 

This is because tasks run as "privileged" by default (https://www.vagrantup.com/docs/provisioning/shell.html#privileged). We can probably remove the sudo to make this clearer.

**Comment by aogier** [comment]
Hi Seth, thank you for your reply ! Sorry I did not found this on manual, I was misled by that sudo I think... I could produce a trivial merge request on Vagrantfile's erb but that would be really trivial, let me know if I can help in any way or otherwise close this issue.

thank you again, ciao
