### ISSUE TITLE
Windows 2008 R2 Virtual server on Windows 8.1

### ISSUE THREAD

**Issue by apramitbarik** [mitchellh/vagrant#7300]
Hi,

I am new to vagrant. I wanted to install Win2008R2 in virtual box to create a base box package.

Once the base package has been created the another script to install JRE and Apache Solr into WIN2008R2 server using vagrant.

So far i have install Win2008R2 in oracle virtual box and created base package and also tested.

But not able to install JRE8 and Solr. Can you please give any sample how to do that?

Thank you

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
