### ISSUE TITLE
Skip VT-x with VirtualBox

### ISSUE THREAD

**Issue by techtonik** [mitchellh/vagrant#7302]
### Vagrant version
$ vagrant -v
Vagrant 1.8.1

### Host operating system
$ lsb_release -d
Description:	Ubuntu 16.04 LTS

### Guest operating system
Debian Jessie 64-bit?

### Expected behavior
How to skip VT-x requirement for running VirtualBox? I am getting this error:
```
Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```
https://github.com/techtonik/rainforce/issues/35#issuecomment-218059167

Is there any way to disable that VT-x?

**Comment by sethvargo** [comment]
Hi @techtonik 

Can you please share your complete Vagrantfile as well as the debut output? Please note that Ubuntu 16.04 is not fully supported at this time.

**Comment by techtonik** [comment]
I already changed my setup to run with `libvirt` - it all started here - https://github.com/sandstorm-io/sandstorm/issues/1959

**Comment by techtonik** [comment]
Generated Vagrantfile - http://paste.ubuntu.com/16367977/

**Comment by sethvargo** [comment]
Hi @techtonik 

What plugins do you have installed? The vagrant-vbguest plugin is no longer required and has been known to cause issues like these.

**Comment by techtonik** [comment]
At the time the error appeared I had only `mutate` installed. Now it is:
```
$ vagrant plugin list
mutate (1.0.0)
vagrant-libvirt (0.0.33)
```

**Comment by sethvargo** [comment]
Hi @techtonik 

We typically ask users to uninstall all plugins to narrow down if the issue in a plugin or vagrant core.

**Comment by techtonik** [comment]
@sethvargo the problem is in VirtualBox - https://www.google.com/search?q=VERR_VMX_NO_VMX

**Comment by techtonik** [comment]
But Vagrant could detect if machine doesn't have VT-x installed.

**Comment by garrettr** [comment]
@techtonik Unless you have a very old machine, your processor should support the VT-x extensions. You might need to enable them in your BIOS: http://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/.

**Comment by techtonik** [comment]
@garrettr it is Pentium D with 8 Gb memory. I don't know if it is old, but it works fine.

**Comment by techtonik** [comment]
And yes, it doesn't support VT-x.

**Comment by sethvargo** [comment]
Hi all,

It appears this is an upstream issue and/or a misunderstanding of the supported features. Can we close this out?

**Comment by techtonik** [comment]
Vagrant is user facing interface, so I believe it should catch this error and make it user friendly.

**Comment by sethvargo** [comment]
Hi @techtonik 

We would gladly review a pull request to improve that error message. Thanks! 😄

**Comment by techtonik** [comment]
Chances are low, because I don't use Ruby and I switched to libvirt since then.
