### ISSUE TITLE
Configurable download command

### ISSUE THREAD

**Issue by richard-scott** [mitchellh/vagrant#7307]
It would be great if we can specify a command to use when downloading boxes from the Internet.

I believe that currently Vagrant uses 'curl' to do the grunt work, but it would be great to be able to reconfigure this to use 'wget' or 'axel' etc.. actually any command of our choosing would be great :-)

My vote would be for axel, as it has some great tuning capabilities:
```
# axel --help
Usage: axel [options] url1 [url2] [url...]

--max-speed=x           -s x    Specify maximum speed (bytes per second)
--num-connections=x     -n x    Specify maximum number of connections
--output=f              -o f    Specify local output file
--search[=x]            -S [x]  Search for mirrors and download from x servers
--header=x              -H x    Add header string
--user-agent=x          -U x    Set user agent
--no-proxy              -N      Just don't use any proxy server
--quiet                 -q      Leave stdout alone
--verbose               -v      More status information
--alternate             -a      Alternate progress indicator
--help                  -h      This information
--version               -V      Version information

Visit http://axel.alioth.debian.org/ to report bugs
```

**Comment by milhaus** [comment]
Also, would be nice if one of the console bittorrent clients would be an option. And for atlas to provide relevant links.

**Comment by faddat** [comment]
Metalink = bittorrent + HTTP/s + FTP 

....ftw in vagrant?

**Comment by tersmitten** [comment]
+1

**Comment by sethvargo** [comment]
Hi @richard-scott 

Thank you for opening an issue. I spent some time investigating this today. In short, this would require a fairly massive refactor of Vagrant's downloader and may not be possible at all. We would some how need to maintain a map of all the correct command line flags to pass to all the different downloaders, and that's just not sustainable. We are exploring other options for faster box downloads, but I do not think it's going to be a puggable downloader. Sorry! Have a great day.

**Comment by richard-scott** [comment]
Thanks for trying,  all I was after was a "download_cmd" option to change the download tool used... It's up to me to make it work :-)

That way I could set "download_cmd='axel' in my Vagrantfile and vagrant call '$download_cmd $url', if it works great, if it doesn't then its up to me to fix my 'download_cmd' settings.

**Comment by rulatir** [comment]
Just specify the subset of curl's command line interface that the download tool must implement, and ALLOW people to write adapters for other download tools. And people WILL write adapters, because curl's SSSSSSLLLLLLOOOOOOWWWWWWNNNNNNEEEEEESSSSSS is KILLING projects that use vagrant!!!
