### ISSUE TITLE
Unclear error when disconnected from the Internet

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [mitchellh/vagrant#7309]
### Expected behavior
I should have been informed that Vagrant cannot function without a connection to the Internet,

### Actual behavior
    > vagrant up
    There was an error loading a Vagrantfile. The file being loaded
    and the error message are shown below. This is usually caused by
    a syntax error.

    Path: /Users/ec/Documents/vagrant_test/Vagrantfile
    Line number: 0
    Message: SocketError: getaddrinfo: nodename nor servname provided, or not known

### Steps to reproduce
1. Disconnect from the network entirely,
2. attempt to `vagrant up` a brand-new Vagrant environment

> Vagrant version: **Vagrant 1.8.1**
> Host operating system: **Mac OS X 10.11.3**
> Guest operating system: **CoreOS 1032.1.0**
> Vagrantfile: [coreos-vagrant](https://github.com/coreos/coreos-vagrant/issues/new)

**Comment by sethvargo** [comment]
Hi @ELLIOTTCABLE 

```
$ cat Vagrantfile
Vagrant.configure(2) do |config|
 config.vm.box = "hashicorp/precise64"
end

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
   default: Box Provider: virtualbox
   default: Box Version: >= 0
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/hashicorp/precise64"]
Error: Could not resolve host: atlas.hashicorp.com
```

As the error indicates, it appears you have an error in your Vagrantfile. If you are attempting to make an HTTP request as part of your Vagrantfile, you could see this error, but that error is coming from Ruby. Vagrant did it's best to wrap the underlying error, but there's not much we can do in this case. Sorry!
