### ISSUE TITLE
Error code 7

### ISSUE THREAD

**Issue by randycasburn** [mitchellh/vagrant#7314]
OSX El Capitan
Vagrant: Fresh update to 1.8.1 (worked perfectly prior to update)
VMWare Fusion: Version 8.1.0 (3272237)
Vagrant fails to start with following error:

> An unexpected error occurred while loading the Vagrant VMware
> provider. Please contact support with the following
> error code: '7'.
> Vagrant failed to initialize at a very early stage:
> 
> The plugins failed to load properly. The error message given is
> shown below.
> 
> exit
> 
>

**Comment by sethvargo** [comment]
Hi @randycasburn 

Please uninstall and re-install the vagrant plugin and this error will go away. Best and sorry!
