### ISSUE TITLE
Waiting for machine to boot instantly returns SSL_connect error on Windows guest

### ISSUE THREAD

**Issue by rodion-goritskov** [mitchellh/vagrant#7317]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Debian 8 x86_64

### Guest operating system
Windows 7 x86_64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Windows machine configuration
Vagrant.configure(2) do |config|
  # Downloading required box from shar
  config.vm.box = "autoqa/windows7_x64"

  # WinRM settings
  config.vm.communicator = "winrm"
  config.winrm.username = "tc"
  config.winrm.password = "324012"
  config.winrm.transport = :ssl
  config.winrm.ssl_peer_verification = false

  # Creating bridged interface
  config.vm.network "public_network", bridge: [
  "br1",
  "eth0",
  ]

  # Provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     # Customize the amount of memory on the VM:
     vb.memory = "4096"
     # Customize CPU number:
     vb.cpus = 2
   end
end
```

### Debug output
https://gist.github.com/rodion-goritskov/0c5a99b25bcde4d59af1503f063588c1

### Expected behavior
Machine boots without any errors.
This vagrantfile together with same Windows image WAS working some time ago. It seems to be problem with Virtualbox version.
**This seems to be a Virtualbox 5.0.20 regression. On Virtualbox-4.3.38 everything is working flawlessly**

### Actual behavior
Error on waiting machine to boot:
An SSL error occurred while connecting to WinRM. This usually
occurs when you are using a self-signed certificate and have
not set the WinRM `ssl_peer_verification` config setting to false.

Message: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
However, when machine boots (windows desktop appears) I can successfully connect with winrm vagrant plugin.
VirtualBox is used as provider, version 5.0.20 r106931

### Steps to reproduce
1. Run vagrant up and wait

**Comment by sethvargo** [comment]
Hi @rodion-goritskov 

Thank you for opening an issue. There is another issue tracking this (https://github.com/mitchellh/vagrant/issues/7306), and I think the author has opened the correct channels with VirtualBox upstream. Let's track that. Thanks! 😄

**Comment by embusalacchi** [comment]
I know this is an old thread but did you ever figure out what this was happening?  I am seeing the same issue.
