### ISSUE TITLE
rsync exclude not excluding file patterns

### ISSUE THREAD

**Issue by laggingreflex** [mitchellh/vagrant#7320]
I'm using Vagrant Synced Folders in RSync mode and trying to exclude certain filetypes. 

The folders (.git, node_modules*) are excluded as expected, but the files (*.lnk, *.sublime*) are not. 

My config is like this:

```
config.vm.synced_folder '.', '/home/vagrant/app',
  type: 'rsync',
  rsync__exclude: [
    '.git*', 'node_modules*',
    '*.lnk', '*.cmd', '*.sublime*', '*.sh'
  ],
  rsync__verbose: true
```

Here's the log of the sync:

```
    default: VirtualBox Version: 5.0
==> default: Rsyncing folder: /cygdrive/c/web/project/ => /home/vagrant/app
==> default:   - Exclude: [".vagrant/", ".git*", "node_modules*", "*.lnk", "*.cmd", "*.sublime*", "*.sh"]
==> default: Showing rsync output...
==> default: rsync[stderr] -> Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
==> default: rsync[stdout] -> sending incremental file list
==> default: rsync[stdout] -> ./
==> default: rsync[stdout] -> Project.sublime-workspace   << "*.sublime*" should've been excluded
==> default: rsync[stdout] -> project.chrome.lnk          << "*.lnk"
==> default: rsync[stdout] -> query.js
==> default: rsync[stdout] -> project.sql
==> default: rsync[stdout] -> vagrant.bootstrap.sh
==> default: rsync[stdout] -> vagrant.load.cmd            << "*.cmd"
==> default: rsync[stdout] -> client/
==> default: rsync[stdout] -> client/.babelrc
==> default: rsync[stdout] -> client/.eslintrc
==> default: rsync[stdout] -> client/client.sublime-project
...
```

It's copying the files that are supposed to be excluded.

---
### Vagrant version

Vagrant 1.8.1
### Host operating system

Windows 10
### Guest operating system

Ubuntu trusty64
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder '.', '/home/vagrant/app',
    type: 'rsync',
    # rsync__verbose: true,
    rsync__exclude: [
      '.git*', 'node_modules*',
      '*.log', '*.lnk', '*.cmd', '*.sh',
      '*.sublime*',
    ]
end
```
### Debug output

https://gist.github.com/laggingreflex/98c6c6d07561fcbacc66a2770aeb3530
### Expected behavior

I wanted to exclude some file types (*.lnk, *.cmd, *.sublime*, *.sh). They should **not** have been copied. 
### Actual behavior

The files got copied regardless the exclude rule. 
### Steps to reproduce
1. Setup vagrant with rsync and exclude some filetypes with `rsync__exclude:['*.log']`
2. See if the files are actually copied
### References

[Question on stackoverflow](http://stackoverflow.com/questions/37255453/vagrant-rsync-exclude-not-excluding-some-file-patterns)
this issue might be related: #4069

**Comment by laggingreflex** [comment]
[This seems to fix it](https://github.com/mitchellh/vagrant/pull/7321)

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
