### ISSUE TITLE
Unable to prepare context: unable to evalute symlinks in Dockerfile path

### ISSUE THREAD

**Issue by zhshqzyc** [mitchellh/vagrant#7323]
**Vagrant version**
1.8.1

**Host operating system**
Windows 7 pro.

**Guest operating system**
Virtualbox 5.0.20.

**Vagrantfile**

```
  Vagrant.configure(2) do |config|
  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.define "docker1", primary: true do |docker1|
    docker1.vm.hostname = "docker1-dev"
    docker1.vm.box = "puppetlabs/centos-7.0-64-puppet"
    docker1.vm.network "private_network", ip: "172.28.128.4"
    docker1.vm.network "public_network"
  end

  config.vm.define "docker2" do |docker2|
    docker2.vm.hostname = "docker1-dev"
    docker2.vm.box = "puppetlabs/centos-7.0-64-puppet"
    docker2.vm.network "private_network", ip: "172.28.128.5"
    docker2.vm.network "public_network"
  end
 end
```

I have a script for building two docker images.

```
echo 'Copying RSA Key'
cp /vagrant/id_rsa /home/vagrant/.ssh/id_rsa
cp /vagrant/id_rsa.pub /home/vagrant/.ssh/id_rsa.pub
echo 'Setting permissions on Key'
chmod 600 /home/vagrant/.ssh/id_rsa
eval `ssh-agent`
echo 'Starting SSH Agent'
#ssh-agent /bin/bash
echo 'Adding SSH Key'
ssh-add /home/vagrant/.ssh/id_rsa
ssh-keyscan bitbucket.org >> /home/vagrant/.ssh/known_hosts
echo 'Cloning repository'
git clone git@bitbucket.org:me/microservices.git /home/vagrant/microservices
eval `ssh-agent -k`
docker build -f /home/vagrant/microservices/DeviceConfig/Docker/Dockerfile.release -t deviceconfig "/home/vagrant/microservices/DeviceConfig"
docker run -d -it -p 5000:5000 --name deviceconfig-spiderman deviceconfig

docker build -f /home/vagrant/microservices/BandwidthRestriction/Docker/Dockerfile.release -t bandwidthrestriction "/home/vagrant/microservices/BandwidthRestriction"
docker run -d -it -p 5005:5005 --name bandwidth-panda bandwidthrestriction

```

**Debug output**
The first docker image and container were successful. 
But the second one failed. The error is 

> Unable to prepare context: unable to evalute symlinks in Dockerfile path.

![1](https://cloud.githubusercontent.com/assets/7240266/15370575/9bb3a3bc-1d05-11e6-9f19-c27d3d1c271b.PNG)
Thanks for help.

**Comment by erSitzt** [comment]
We have the same problem when specifying a different Dockerfile than the default one, like `d.dockerfile = "Dockerfile.vagrant"`
We have two Dockerfiles one for vagrant and local testing and the other for building the container during CI/CD.

If i remove the line to specify the Dockerfile it works ( both Dockerfiles are the same for this test)

My complete Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

appconfig = YAML.load_file("./config/vagrant.config.yml")
config = YAML.load_file(appconfig['base']['dir'] + "/config.yml")
dnsip = config['neo']['dns']['ip']
#currentdir = File.dirname(__FILE__)
currentdir = appconfig['app']['dir']


load appconfig['base']['dir'] +'/osdetect.rb'

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.8.1"
VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "docker" do |d|

    # boot2docker hostvm
    d.force_host_vm = true
    d.vagrant_vagrantfile = appconfig['base']['dir'] +"/hostvm/Vagrantfile"

    d.build_dir = "."
    d.build_args = ["-t=dumm"]
    d.ports = ["80:80"]
    d.dockerfile = "Dockerfile.vagrant"
    d.name = appconfig['app']['name']
    d.create_args = [
    "--hostname="+appconfig['app']['hostname'],
    "--dns=#{dnsip}",
    "--dns-search=service.consul"
    ]
    d.env = {
        "http_proxy": "http://proxy.domain.de:8080",
        "https_proxy": "http://proxy.domain.de:8080",
        "SERVICE_NAME": appconfig['app']['name'],
        "SERVICE_TTL": "30",
        "SERVICE_TAGS": appconfig['app']['tags'],
        "PORT0": appconfig['app']['port']
    }
    d.volumes = ["/linuxFreigaben/:/linuxFreigaben"]
    d.remains_running = true

    if OS.windows?
        d.host_vm_build_dir_options = {
            owner: "www-data", group: "www-data", smb_username: "www-data", smb_password: "www-data", type: "smb"
        }
    end

    if OS.linux?
        d.host_vm_build_dir_options = {
            type: "rsync"
        }
    end
    if OS.mac?
        d.host_vm_build_dir_options = {
            type: "rsync"
        }
    end

  end
end
```

**Comment by rrafal** [comment]
I see the same error message whenever I use `dockerfile` setting. The same errors shows when `dockerfile` is set to its default value: "Dockerfile". I believe this is a bug on the following line, which incorrectly quotes an argument. Unfortunately I'm not a Ruby developer and it's hard for me to test and verify this bug:
[args.push("--file=\"#{dockerfile_path}\"")](https://github.com/mitchellh/vagrant/blob/1f88a9737369eda3dede0d3aeb30928adf82a9f7/plugins/providers/docker/action/build.rb#L46)

**Comment by erSitzt** [comment]
yes, that seems to be the problem.
Removing the escaped quotes solved it for me.

**Comment by erSitzt** [comment]
`args.push("--file=#{dockerfile_path}")`

**Comment by redmcg** [comment]
Ran in to this problem too. @erSitzt suggested fix worked for me, even when I changed the docker file path to include a ' ' (space) and an '=' (equals sign). Tested on both Linux (with Docker running locally) and Windows (with Docker running within a VirtualBox)

**Comment by erSitzt** [comment]
Still not fixed, some colleagues ran into this problem with v1.9.1 again.

**Comment by briancain** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unable to prepare context: unable to evalute symlinks in Dockerfile path](https://trello.com/c/yWxGJcFA/24-unable-to-prepare-context-unable-to-evalute-symlinks-in-dockerfile-path)

**Comment by briancain** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
