### ISSUE TITLE
Enhancement: Vagrant Share should default to --https 443

### ISSUE THREAD

**Issue by ionas** [mitchellh/vagrant#7325]
```
 $ vagrant -v
Vagrant 1.8.1
```
The subject basically says it all. If I just use vagrant share my box won't be reachable through https://whatever.vagrantshare.com.

However as HTTPS is on the rise (google will soon downrank things, let's encrypt) I want to do demos directly in HTTPS by default, out of the box.

Instead there should be --no-https option to disable the default. --https should stay to specify a different port if required.

The console output of vagrant share should always print https://... unless --no-https is specified.

**Edit**: for backwards compatibility one could argue that the console should show both, http and https links in case you don't have HTTPS setup in your vagrant box (e.g. access through HTTP should still / always be possible - just not endorsed and default)

**Comment by sethvargo** [comment]
Hi @ionas 

Thank you for opening an issue. This is a really good idea, but Vagrant's backwards compatibility promise would require that we cannot do this until Vagrant 2.0. If you would like to submit a PR, we would gladly review it, keeping in mind that we can't break anything until Vagrant 2.0. Thanks! 😄

**Comment by jhli** [comment]
Add it as another comnad then, vagrant share-https
