### ISSUE TITLE
Red Text Colour Terminal Printout for Non-error Texts

### ISSUE THREAD

**Issue by byteknacker** [mitchellh/vagrant#7326]
### Vagrant Version 
1.8.1

### Host OS: 
Mac OS X 10.11.5

### Guest OS: 
Ubuntu 14.04, minimal/trusty64 on Atlas

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Start with base vagrant box. This one is only 271 MB in size.
    config.vm.box = "minimal/trusty64"

    # Create forwarding ports for client-guest machine access via localhost.
    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.vm.network :forwarded_port, guest: 6000, host: 6000

    # Add the tty fix as mentioned in issue 1673 on vagrant repo
    # To avoid 'stdin is not a tty' messages
    # vagrant provisioning in shell runs bash -l
    config.vm.provision "fix-no-tty", type: "shell" do |s|
        s.privileged = false
        s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
    end

    # Provision the virtual machine.
    config.vm.provision :shell, :path => "provision.sh"
end

```

### Debug output
https://gist.github.com/byteknacker/f9dc438c82cc50f2a5c8b349c5b408ae

### Expected behaviour:
There shouldn't be any red colored texts during provisioning. Expecting green texts since there are no errors. 

### Actual Behaviour: 
There are some red coloured texts during provisioning and this happens mainly for installation of PostgreSQL.

### Steps to Reproduce

1. git clone: https://github.com/byteknacker/fcc-python-vagrant
2. vagrant up
3. Observe the red text printouts in the terminal

These steps should work on Mac OS and any Linux based systems. Windows are also tested and should work but may be less stable compared to the former two.

<img width="894" alt="1__developer__vagrant__and_vagrantfile_explained__setting_up_and_provisioning_with_shell" src="https://cloud.githubusercontent.com/assets/10653912/15396161/1fe5c4dc-1ddb-11e6-82ba-a9a4fb497211.png">

<img width="661" alt="1__developer__vagrant_" src="https://cloud.githubusercontent.com/assets/10653912/15396171/25779bfa-1ddb-11e6-960c-fee484796210.png">

<img width="777" alt="1__developer__vagrant_" src="https://cloud.githubusercontent.com/assets/10653912/15396182/2c3f28b8-1ddb-11e6-9573-03af68247787.png">

**Comment by sethvargo** [comment]
Hi @byteknacker 

Thank you for opening an issue. This is happening because those tools write their debug messages to stderr, which Vagrant then interprets as an error and prints in red. You can disable colored output entirely or pipe the stderr of those commands to a file or /dev/null. Unfortunately there's not much Vagrant can do here because there's no easy way to distinguish a debug message printed to stderr from a real error. Thanks! 😄

**Comment by paulfurley** [comment]
How about a way to customize the output colour? Just setting it to yellow would be a win for me.
