### ISSUE TITLE
The ruby-libvirt gem fails to compile in Vagrant's environment

### ISSUE THREAD

**Issue by ignisf** [mitchellh/vagrant#7330]
### Vagrant version

Vagrant 1.8.2.dev
Vagrant 1.8.1
### Host operating system

Linux clarity 4.6.0-1-ARCH # 1 SMP PREEMPT Mon May 16 20:36:53 CEST 2016 x86_64 GNU/Linux
### Debug output

https://gist.github.com/ignisf/96172de76a4cdbb05117634570dc5beb
### Expected behavior

vagrant-libvirt should have been installed
### Actual behavior

A build error for the ruby-libvirt gem
### Steps to reproduce
1. `vagrant plugin install vagrant-libvirt`
### References

https://github.com/vagrant-libvirt/vagrant-libvirt/issues/497

**Comment by ignisf** [comment]
It's worth being noted (though it may not be related) that I was only able to compile vagrant from git after setting `NOKOGIRI_USE_SYSTEM_LIBRARIES=1`. Before that the build was failing with the following:

```
/usr/bin/ld: warning: libiconv.so.2, needed by /opt/vagrant/embedded/lib/libxml2.so, not found (try using -rpath or -rpath-link)
/opt/vagrant/embedded/lib/libxml2.so: undefined reference to `libiconv'
/opt/vagrant/embedded/lib/libxml2.so: undefined reference to `libiconv_close'
/opt/vagrant/embedded/lib/libxml2.so: undefined reference to `libiconv_open'
collect2: error: ld returned 1 exit status
```

**Comment by ignisf** [comment]
Also, the gem installs fine with my rbenv Ruby.

**Comment by ignisf** [comment]
Worked around the issue by following https://wiki.archlinux.org/index.php/Vagrant#vagrant-libvirt

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
