### ISSUE TITLE
Vagrant up/reload --provision chef-solo issue on linux Ubuntu 16

### ISSUE THREAD

**Issue by LucasMaliszewski** [mitchellh/vagrant#7331]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Ubuntu 16+

### Guest operating system
Ubuntu/trusty64

### Vagrantfile
```ruby
  config.vm.provider "virtualbox" do |vb|
    # Set the name that appears in VirtualBox Manager
    vb.name = PROJECT_NAME
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", VM_RAM]
    vb.cpus = VM_CPU
  end
	config.berkshelf.enabled = true
	config.berkshelf.berksfile_path = "../cookbook/Berksfile"
  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
	config.vm.provision "chef_solo" do |chef|
		chef.cookbooks_path = "../cookbook"
		chef.environment = "local"
		chef.environments_path = "../cookbook/environments"
		# chef.roles_path = "../my-recipes/roles"
		chef.data_bags_path = "../cookbook/data_bags"
		chef.add_recipe "craft"
		# chef.add_recipe "craft::elasticsearch"
		chef.roles_path = "/tmp/vagrant-something"

		chef.json = {
			"default" => {
				"docroot" => DEFAULT_PATH,
				"hostname" => DEFAULT_HOSTNAME,
				"server_aliases" => DEFAULT_ALIASES,
				"cert_path" =>    DEFAULT_CERT_PATH,
				"key_path" =>     DEFAULT_KEY_PATH,
				"ca_cert_path" => DEFAULT_CA_PATH,
				"database_file"=>DATABASE_LOCATION,
				"database_table" => DATABASE_TABLE
			}
		}
		if defined? ALT_HOSTNAME
			chef.json["alt"] = {
				"hostname" => ALT_HOSTNAME,
				"server_aliases" => ALT_ALIASES,
				"docroot" => ALT_PATH
			}
		end
	end

end
```

This works fine on windows and OS X, but not Ubuntu 16+ or the latest copy of Debian. Here is the output: http://pastebin.com/ZXkYP9yT

**Comment by sethvargo** [comment]
Hi @LucasMaliszewski 

Can you try creating a `nodes` folder where your chef data is?

**Comment by LucasMaliszewski** [comment]
Unfortunately I have, and bummed to say that does not change the end results.

**Comment by LucasMaliszewski** [comment]
Looks like apache2 is not being installed or set-up correctly.

berksfile.lock

DEPENDENCIES
  apache2 (~> 3.1.0)
  craft
    path: .
    metadata: true
  elasticsearch
    git: https://github.com/elastic/cookbook-elasticsearch.git
    revision: ecf3032c035e6f87383eba31a363c199bab5bc61
    tag: v1.2.0
  java (~> 1.36.0)
  mysql
  php (~> 1.7.0)

GRAPH
  apache2 (3.1.0)
  apt (3.0.0)
  ark (1.0.1)
    build-essential (>= 0.0.0)
    seven_zip (>= 0.0.0)
    windows (>= 0.0.0)
  build-essential (4.0.0)
    mingw (>= 0.0.0)
    seven_zip (>= 0.0.0)
  chef-sugar (3.3.0)
  chef_handler (1.4.0)
  compat_resource (12.9.1)
  craft (0.1.0)
    apache2 (>= 0.0.0)
    elasticsearch (~> 1.2.0)
    java (~> 1.36.0)
    mysql (~> 6.0)
    php (>= 0.0.0)
  curl (2.0.1)
  elasticsearch (1.2.0)
    apt (>= 0.0.0)
    ark (>= 0.0.0)
    chef-sugar (>= 0.0.0)
    curl (>= 0.0.0)
    yum (>= 0.0.0)
  iis (4.1.7)
    windows (>= 1.34.6)
  java (1.36.0)
    apt (>= 0.0.0)
  mingw (1.0.0)
    compat_resource (>= 0.0.0)
    seven_zip (>= 0.0.0)
  mysql (6.1.3)
    smf (>= 0.0.0)
    yum-mysql-community (>= 0.0.0)
  php (1.7.2)
    build-essential (>= 0.0.0)
    iis (>= 0.0.0)
    mysql (>= 6.0.0)
    windows (>= 0.0.0)
    xml (>= 0.0.0)
    yum-epel (>= 0.0.0)
  rbac (1.0.3)
  seven_zip (2.0.0)
    windows (>= 1.2.2)
  smf (2.2.8)
    rbac (>= 1.0.1)
  windows (1.41.0)
    chef_handler (>= 0.0.0)
  xml (2.0.0)
    build-essential (>= 0.0.0)
    chef-sugar (>= 0.0.0)
  yum (3.10.0)
  yum-epel (0.7.0)
    yum (>= 3.6.3)
  yum-mysql-community (0.2.0)
    yum (>= 3.2)

**Comment by cigoe** [comment]
I just ran into this as well with a new vagrant box on CentOS. The solution was to login to the VM and downgrade to an older version of chef which did not have this issue via the installer `curl -L https://chef.io/chef/install.sh | sudo bash`. It only seems to affect newer versions of chef as 12.10.40 seems to work fine.

Affected versions that did not work for me which were automatically installed by vagrant:
12.11.3 (installed yesterday)
12.11.4 (installed ~ 1 hour ago)

Not an ideal fix but it allowed me to bootstrap the VM with chef-solo.

**Comment by sethvargo** [comment]
@lamont-granquist @thommay any ideas why this would start breaking with 12.11..4?

**Comment by nckturner** [comment]
I ran into this issue also (see #7333) and it was fixed downgrading chef-client on the VM to 12.10.24 from 12.11.1

**Comment by thommay** [comment]
@sethvargo the PR from me you merged last week fixes this - it's because we flipped chef-solo to be local mode by default in 12.10.40something (on mobile, hard to check), and the default solo.rb that vagrant generates has a nodes path that is nil.

**Comment by sethvargo** [comment]
Sweet thanks! We will just wait for the release then. Thanks Thom!
