### ISSUE TITLE
Local-Exec doesn't work in Windows 10

### ISSUE THREAD

**Issue by octoxan** [mitchellh/vagrant#7336]
### Vagrant version
1.8.1

### Host operating system
Windows 10 Pro x64

### Guest operating system
hashicorp/precise64

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network :forwarded_port, guest: 80, host: 4567

  config.push.define "local-exec" do |push|
    push.inline = <<-SCRIPT
      cp -r . /var/www/website
    SCRIPT
  end
end
```

### Debug output
https://gist.github.com/octoxan/039a299335a89c3d31a077fb52d3cff0

### Expected behavior
It should push, and copy the project to /var/www/website

### Actual behavior
Throws error

### Steps to reproduce
1. Install Vagrant
2. Install Ruby
3. Run this demo https://www.vagrantup.com/docs/push/local-exec.html

**Comment by sethvargo** [comment]
Hi @octoxan 

I think this is the expected behavior here. I do not thing `cp` is a valid command on Windows, is it?

Of note - you do not need to install Ruby. Vagrant comes with its own Ruby environment.

**Comment by octoxan** [comment]
It's not a valid Windows command, but I do have Git for Windows installed
in the manner where it replaced a lot of windows commands with Unix ones. I
can open the cmd and do cp or ls or cd..I'm guessing this only affects the
cmd though then?

I wonder if there's anyway to have vagrant use something like cygwyn or the
cmd with Unix tools added.

**Comment by sethvargo** [comment]
Hi @octoxan 

If you run Vagrant under cygwin, it will run the commands in that subshell. If you run from cmd/ps, it will run under that subshell. Can you please share the complete [debug output](https://www.vagrantup.com/docs/other/debugging.html) as a gist?

**Comment by octoxan** [comment]
I updated the link at the top to include the debug output. 
https://gist.github.com/octoxan/039a299335a89c3d31a077fb52d3cff0

Same error for if I try to use cygwin or cmd/ps. And cp -r . var/www/website works from cygwin on it's own, which is all that my vagrant push tries to do.

**Comment by sethvargo** [comment]
Hi @octoxan 

I did some research and exit code 193 indicates that the command `cp` is not a valid application.

> [193 - %1 is not a valid Win32 application](http://www.symantec.com/connect/articles/windows-system-error-codes-exit-codes-description)

**Comment by octoxan** [comment]
Weird I wonder why cp works in cygwin...

**Comment by sethvargo** [comment]
Hi @octoxan 

Is it `cp` or `cp.exe`?

**Comment by sethvargo** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
