### ISSUE TITLE
Box versions containing minus sign are not properly validated and cause runtime errors

### ISSUE THREAD

**Issue by sergeijakovlev** [mitchellh/vagrant#7341]
Box versions must be in a X.Y.Z format. If X.Y.Z-W version is used (e.g. 1.2.3-456789), it is not rejected by version number validation. The box addition causes NoMethodError, but the box gets added. The box cannot be launched or removed.

Note that versions given as X.Y.Z+W or X.Y.Z_W are properly filtered and an appropriate error message is shown.

### Vagrant version
```
$ vagrant -v
Vagrant 1.8.1
```

### Host operating system
```
$ uname -a
Linux host 4.5.0-1-amd64 #1 SMP Debian 4.5.1-1 (2016-04-14) x86_64 GNU/Linux
```

### Ruby version
```
$ ruby -v
jruby 1.7.22 (1.9.3p551) 2015-08-20 c28f492 on OpenJDK 64-Bit Server VM 1.8.0_91-8u91-b14-2-b14 +jit [linux-amd64]
```

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
The box with an invalid version is not added and an appropriate error message is shown.

#### Box addition:
```
[...]
default: Calculating and comparing box checksum...
/usr/lib/ruby/vendor_ruby/vagrant/action/builtin/box_add.rb:361:in `box_add': undefined method `name' for nil:NilClass (NoMethodError)
```

#### Box removal:
```
$ vagrant box remove some_box
/usr/lib/ruby/vendor_ruby/vagrant/action/builtin/box_remove.rb:81:in `block in call': undefined method `in_use?' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/box_remove.rb:75:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/box_remove.rb:75:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/plugins/commands/box/command/remove.rb:52:in `execute'
	from /usr/share/vagrant/plugins/commands/box/command/root.rb:61:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
	from /usr/bin/vagrant:173:in `<main>'
```

### Steps to reproduce
1. Create a box.
2. Create a JSON file for the box with an invalid version containing minus sign.
3. Try to add and then remove this box.

**Comment by sethvargo** [comment]
Hi @sergeijakovlev 

How did you install Vagrant? It looks like you might be using a non-standard installation method? Vagrant should be installed in `/opt/vagrant`.

**Comment by sergeijakovlev** [comment]
Hi, @sethvargo!

Vagrant was installed from Debain Stretch repositories (https://packages.debian.org/stretch/vagrant). The package seems to be installed into `/usr/lib/ruby/vendor_ruby/vagrant` directory.

```
$ dpkg -s vagrant
Package: vagrant
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 2466
Maintainer: Antonio Terceiro <terceiro@debian.org>
Architecture: all
Version: 1.8.1+dfsg-2
Depends: bsdtar, bundler, curl, openssh-client, ruby-childprocess (>= 0.3.7), ruby-erubis (>= 2.7.0), ruby-i18n (>= 0.6.0), ruby-listen, ruby-log4r (>= 1.1.9), ruby-net-scp (>= 1.1.0), ruby-net-sftp, ruby-net-ssh (>= 1:2.6.6), ruby-rest-client, ruby-nokogiri, ruby-rb-inotify, ruby
Suggests: virtualbox (>= 4.0)
Description: Tool for building and distributing virtualized development environments
 This package provides the tools to create and configure lightweight,
 reproducible, and portable virtual environments.
 .
 Vagrant uses Oracle’s VirtualBox to create its virtual machines and then
 uses Chef or Puppet to provision them.
Homepage: http://vagrantup.com/
Ruby-Versions: all
```

Do you think this is an issue with packaging rather than Vagrant and/or Ruby version?

PS: Sorry for a late response — I forgot to enable email notifications.

**Comment by sethvargo** [comment]
Hi @sergeijakovlev 

Just to eliminate that possibility, can you please uninstall the debian package (with --purge) and install the official package from vagrantup.com?

**Comment by sergeijakovlev** [comment]
Hi, @sethvargo!

Instead of reinstalling Vagrant, I just created a separate VM to test this. I used the debian/jessie64 box (https://atlas.hashicorp.com/debian/boxes/jessie64) and installed the 64-bit Vagrant Debian package downloaded from https://www.vagrantup.com/downloads.html. Vagrant in this case is indeed installed in `/opt/vagrant` (see http://pastebin.com/raw/DHZiMCZC for a listing of installed files). I also installed VirtualBox from Debian Jessie Contrib repository.

Then I created the following JSON file (note the invalid version number):

```
{
    "name": "x-box",
    "description": "X",
    "versions": [{
        "version": "1.2.3-4",
        "providers": [{
                "name": "virtualbox",
                "url": "url-of-an-existing-box",
                "checksum_type": "md5",
                "checksum": "md5-of-an-existing-box"
        }]
    }]
}
```

Then I added this box:

```
vagrant@debian-jessie:~/x-box$ vagrant box add x-box.json 
==> box: Loading metadata for box 'x-box.json'
    box: URL: file:///home/vagrant/x-box/x-box.json
==> box: Adding box 'x-box' (v1.2.3-4) for provider: virtualbox
    box: Downloading: url-of-an-existing-box
    box: Calculating and comparing box checksum...
==> box: Successfully added box 'x-box' (v1.2.3-4) for 'virtualbox'!
```

**In this case, I was able to add, run and remove the box.**

```
vagrant@debian-jessie:~/x-box$ vagrant box remove x-box
Removing box 'x-box' (v1.2.3-4) with provider 'virtualbox'...
```

Although it seems to be working in this case, this still is not the expected behavior, is it?

**Comment by sethvargo** [comment]
Hi @sergeijakovlev 

This is the expected behavior. The version you specified is a valid version. I believe the Vagrant you installed via apt was just buggy. Thanks! 😄

**Comment by sergeijakovlev** [comment]
Hi, @sethvargo!

Thank you for your reply. In this case, perhaps it would make sense to update the documentation? https://www.vagrantup.com/docs/boxes/versioning.html seems to be a bit confusing:

> Please note that, while the semantic versioning specification allows for more than three points and pre-release or beta versions, Vagrant boxes must be of the format X.Y.Z where X, Y, and Z are all positive integers.

Good luck and apologies for submitting an inconsequential bug report.

**Comment by dolph** [comment]
If vagrant crashing is the expected behavior, then perhaps vagrant shouldn't automatically download broken versions from hashicorp? Or perhaps hashicorp should not allow boxes with broken versions to be published in the first place? Or perhaps vagrant should supply a error message instead of dumping random stack traces?

"Good luck" is right.

$ vagrant init concourse/lite
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'concourse/lite' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'concourse/lite'
    default: URL: https://atlas.hashicorp.com/concourse/lite
==> default: Adding box 'concourse/lite' (v2.5.1-rc.33) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/concourse/boxes/lite/versions/2.5.1-rc.33/providers/virtualbox.box
/usr/lib/ruby/vendor_ruby/vagrant/action/builtin/box_add.rb:361:in `box_add': undefined method `name' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/box_add.rb:266:in `add_from_metadata'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/box_add.rb:104:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
        from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/handle_box.rb:82:in `handle_box'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/handle_box.rb:42:in `block in call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/handle_box.rb:36:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
        from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:53:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
        from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:224:in `action_raw'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:199:in `block in action'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:527:in `lock'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:185:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:185:in `action'
        from /usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by sergeijakovlev** [comment]
Hello, @dolph 

In my case the problem was specifically in the version of Vagrant available from Debian repositories. @sethvargo confirmed that Vagrant should support versions containing minus sign (not that Vagrant should crash, as version available from Debian repository did, unfortunately). This also does not seem to be an issue on other distributions. With that in mind, the versions of the boxes available from Atlas should be OK.

Unfortunately, I did not bother to report a bug to the maintainer of the Debian vagrant package as we solved the problem differently and I did not have an installation exhibiting that behavior any more. Perhaps you could report this issue to the maintainer of vagrant package in Debian repositories?
