### ISSUE TITLE
config.vm.synced_folder id option is not documented

### ISSUE THREAD

**Issue by BHSPitMonkey** [mitchellh/vagrant#7343]
The `config.vm.synced_folder` Vagrantfile directive accepts an optional `id` parameter, but it is not present in the documentation or explained anywhere.

Relevant documentation directory: [website/source/docs/synced-folders](https://github.com/mitchellh/vagrant/tree/master/website/source/docs/synced-folders)

Relevant StackOverflow question: http://stackoverflow.com/q/28620054/109989

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/pull/7349
