### ISSUE TITLE
There was an error while executing `VBoxManage`, a CLI used by Vagrant for controlling VirtualBox. The command and stderr is shown below.

### ISSUE THREAD

**Issue by CodeDreamfy** [mitchellh/vagrant#7344]
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "dfc125c3-7b2a-449a-a8d0-b3183a946ec0", "--type", "headless
"]

Stderr: VBoxManage.exe: error: The virtual machine 'work_default_1464244911123_7
7308' has terminated unexpectedly during startup with exit code -1073741819 (0xc
0000005).  More details may be available in 'C:\Users\codedreamfy\VirtualBox VMs
\work_default_1464244911123_77308\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap,
 interface IMachine
```

### Vagrant version
$ vagrant -v
Vagrant 1.8.1

### Host operating system
precise64.box

**Comment by sethvargo** [comment]
Hi @CodeDreamfy 

Thank you for opening an issue. Could you please follow the provided issue template? It asks for your complete Vagrantfile as well as the output of the command in debug mode linked as a GitHub gist. Without that information, we will be unable to assist.

**Comment by sethvargo** [comment]
Looks like a Virtualbox bug: https://forums.virtualbox.org/viewtopic.php?f=6&t=68869

**Comment by CodeDreamfy** [comment]
@sethvargo  many thanks, i have already fixed the problem. I removed the previous virtualbox and installed a new version (4.3.12), after that, I restart the vagrant and everything is fine.

**Comment by maxiaoan** [comment]
`vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "28429b58-52ad-4e1c-a3b1-0cadb910d646", "--type", "headless"]

Stderr: VBoxManage.exe: error: Could not open the medium 'E:\centos-7-1-1.x86_64_1524449919929_78394\centos-7-1-1.x86_64.vmdk'.
VBoxManage.exe: error: VD: error VERR_PATH_NOT_FOUND opening image file 'E:\centos-7-1-1.x86_64_1524449919929_78394\centos-7-1-1.x86_64.vmdk' (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MediumWrap, interface IMedium

`

My host infomation  like this:
win7 64bit
vagrant 2.0.4
virtualbox 5.2.8
