### ISSUE TITLE
Running rsync-auto while the machine is booting prompts the user to report a bug

### ISSUE THREAD

**Issue by kitsunde** [mitchellh/vagrant#7345]
Open two terminals. Run `vagrant up` in the second terminal run `vagrant rsync-auto`:

```bash
$ vagrant rsync-auto
==> default: Doing an initial rsync...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

Prompting the user to report a bug seems like a bug. 😉

**Comment by sethvargo** [comment]
Hi @kitsunde 

Can you please share your complete Vagrantfile?

**Comment by kitsunde** [comment]
Pretty sure any Vagrantfile with rsync would cause this. But here's an example:

```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.synced_folder '.', '/vagrant', type: "rsync"
end
```

Here's a screen recording:

![vagrant-rsync-prompt](https://cloud.githubusercontent.com/assets/48965/15628527/ab560516-2535-11e6-8ee8-e2ceb5edc7c7.gif)

Basically while the VM is booting rsync-auto cannot communicate with the VM (naturally), but the error message prompts the user to submit a bug report.

**Comment by sethvargo** [comment]
Hi @kitsunde 

I cannot reproduce this on the master branch of Vagrant locally:

<img width="1423" alt="screen shot 2016-05-28 at 3 28 49 pm" src="https://cloud.githubusercontent.com/assets/408570/15629535/e08dd044-24e8-11e6-9cdc-2c9fdbd37913.png">

I get this message when I try to start `rsync-auto` while the machine is booting:

```
==> default: New synced folders were added to the Vagrantfile since running
==> default: `vagrant reload`. If these new synced folders are backed by rsync,
==> default: they won't be automatically synced until a `vagrant reload` is run.
There are no paths to watch! This is either because you have no
synced folders using rsync, or any rsync synced folders you have
have specified `rsync_auto` to be false.
```

I tried this with both the ubuntu/trusty64 and hashicorp/precise64 boxes. 

As such, I think this has been fixed at some point between the last release and now. Thanks!
