### ISSUE TITLE
Extreme slowing down because of git

### ISSUE THREAD

**Issue by ssalam1** [mitchellh/vagrant#7346]
### Vagrant version
Vagrant 1.8.1
### Host operating system
This is the operating system that you run locally.
Windows 10 Preview 

### Guest operating system
This is the operating system you run in the virtual machine.
Ubuntu 1404

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "geerlingguy/ubuntu1404"

  # Create a private network, which allows host-only access to the machine using a specific IP.
  config.vm.network "public_network", ip: "192.168.33.22"

	config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
	  v.cpus = 2
	end
  # Share an additional folder to the guest VM. The first argument is the path on the host to the actual folder.
  # The second argument is the path on the guest to mount the folder.
  config.vm.synced_folder "./", "/var/www", type: "nfs"

  # Define the bootstrap file: A (shell) script that runs after first setup of your box (= provisioning)
  config.vm.provision :shell, path: "script.sh"

 config.vm.network :forwarded_port, guest: 80, host: 4567
```

### Debug output

If any command is used it takes a lot of time for complete execution.

If crtl-z is pressed then   

```
[1]-  Stopped                 git diff --no-ext-diff --quiet --exit-code

[2]+  Stopped                 git diff-index --cached --quiet HEAD --

```
During that CPU usage is given below:--
```
Tasks: 101 total,   1 running, 100 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us, 25.0 sy,  0.0 ni, 75.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:   2048916 total,   450200 used,  1598716 free,    17852 buffers
KiB Swap:   524284 total,        0 used,   524284 free.   209176 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2112 vagrant   20   0   18500   3940   3076 D  61.1  0.2   0:03.62 git
 1831 vagrant   20   0  103580   4264   3208 S  30.5  0.2   0:01.74 sshd
 1874 vagrant   20   0   24824   2924   2488 R  30.5  0.1   0:04.63 top
    1 root      20   0   33624   4124   2660 S   0.0  0.2   0:03.18 init
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:00.04 ksoftirqd/0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:+
    7 root      20   0       0      0      0 S   0.0  0.0   0:00.93 rcu_sched
```

Thanks in advance...

**Comment by sethvargo** [comment]
Hi @ssalam1 

Thank you for opening an issue. Are you running these `git` commands on the host or on the guest? What are you trying to diff?

**Comment by ssalam1** [comment]
Thanks for your response @sethvargo 

Slow behavior is only observed on the guest (i.e.Ubuntu) only ...
Any command is getting slowed down if it is ran inside that folder (where .git is present)
For example :--
    ls command show the complete list but gets stuck after a very long time (10 seconds) it gets completed.....During that  time if ctrl-z is pressed many times then it shows the following .
  
[1]-  Stopped                 git diff --no-ext-diff --quiet --exit-code

[2]+  Stopped                 git diff-index --cached --quiet HEAD --

.git folder is larger (about 20mb)

**Comment by sethvargo** [comment]
Hi @ssalam1 

I do not think this is a bug in Vagrant. Are you sure you are not accidentally adding a very large file with Git? What is the `ls -alh` of the directory where you are running git from?

**Comment by ssalam1** [comment]
output of ls -alh in that directory
```

**Comment by sethvargo** [comment]
Hi @ssalam1 

Sorry, but I am not understanding the issue. Why are you pressing ctrl + z?

**Comment by ssalam1** [comment]
Because after showing the list it gets stuck.

**Comment by sethvargo** [comment]
Hi @ssalam1 

I am still not understanding. I do not see where you are running any git commands, yet they are shoing up when you ctrl + z. Note that ctrl + z moves the process to the background - it does not stop it like ctrl + c.

**Comment by ssalam1** [comment]
Hi @sethvargo  ...
 Sorry for sounding confusing .....
Problem is that it doesn't matter whichever command I am running but after running it the terminal gets stuck then after pressing crtl-z a few times you get 
```
[3]-  Stopped                 git diff --no-ext-diff --quiet --exit-code

[4]+  Stopped                 git diff-index --cached --quiet HEAD --
```
Probably because some git command runs in the background. And that is causing for the slow down.

**Comment by apsolut** [comment]
What are you using for Console? (run as admin) ? 
- Antivirus? (Avira default settings will slow down a whole vagrant, they scan files as they are accessed..)
VirtualBox - dedicated ram?
SSD or HDD?

**Comment by ssalam1** [comment]
hey @apsolut  thanks for your comment ..
I am not using any Antivirus (Just Windows Defender)

**Comment by apsolut** [comment]
@ssalam1 any way that your box is out-dated? (--provision) ?
From experience as Win user - I had 60% speed-up after switching to SSD...
-- Could you disable Defender and Firewall = just to test without it - to be sure its not them?

**Comment by ssalam1** [comment]
@apsolut Thanks I'll try that out

**Comment by sethvargo** [comment]
Hi @ssalam1 

This is where I'm confused - **Vagrant does not run any git commands**. You keep saying that these git commands are running in the background, but Vagrant doesn't have any knowledge of git, nor does it run git for you. You also keep pressing ctrl + z multiple times, but ctrl + z likely isn't the behavior you want if you are trying to terminate a running application - you probably want ctrl + c as I said above. ctrl + z is only going to background the process. Can you please do this:

1. Create a blank directory with the following `Vagrantfile`:

    ```ruby
    Vagrant.configure(2) do |config|
      config.vm.box = "bento/ubuntu-14.04"
      config.vm.network "public_network", ip: "192.168.33.23"
      config.vm.network :forwarded_port, guest: 80, host: 4567
      config.vm.synced_folder "./", "/var/www", type: "nfs"
    end
    ```

2. Run `vagrant up`

3. Run `vagrant ssh` when the machine is up

4. Run `ls` and tell me if it is slow.

**Comment by ssalam1** [comment]
@sethvargo  I am really really sorry for not responding earlier ...

I tried on another system it worked smoothly.
Probably there was some problem on my Windows 10 installation or something else.

**Comment by sethvargo** [comment]
Okay thank you for the reply. I'm going to close this out as a local environment issue, but we can always revisit it in the future. Thanks!

**Comment by ivesdebruycker** [comment]
For future reference, git is executed in background for displaying git-info in the Bash prompt:
```
echo $PS1
\u@\h \w (\[\e[32m\]${__git_ps1_branch_name}\[\e[0m\] \[\e[31m\]*\[\e[0m\]=) \$
```

`git diff` was probably slow because it ran in a synced_folder.
