### ISSUE TITLE
ubuntu/xenial64: SSH auth method: password ONLY?

### ISSUE THREAD

**Issue by basictheprogram** [mitchellh/vagrant#7350]
I do not know if this is a vagrant issue or a "ubuntu/xenial64" box issue. 

### Vagrant version
Vagrant 1.8.1

### Host operating system
OS X 10.11.5

### Guest operating system
ubuntu/xenial64 

### Vagrantfile
```ruby
  config.vm.define "testing_xenial64" do |testing_xenial64|
    testing_xenial64.vm.box = "ubuntu/xenial64"
    config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", auto_config: true

    testing_xenial64.vm.provider "virtualbox" do |vb|
      vb.name = "testing_xenial64"
      vb.memory = 2048
    end

    config.vm.provision "bootstrap", type: "shell" do |s| 
      s.path = "testing_xenial64/bootstrap.sh"
    end

    config.vm.provision "ansible", type: "ansible" do |ansible|
      config.ssh.username = "vagrant"
      config.ssh.forward_agent = true
      config.ssh.insert_key = false
      ansible.extra_vars = { remote_user: "vagrant" }
      ansible.playbook = "../playbooks.git/testing-ubuntu64.yml"
    end
  end   # testing_xenial64
```

### Debug output
Regardless of what I set in my Vagrantfile the VM will only use password auth, https://gist.github.com/basictheprogram/94e2980b7460a9b9a57a7096ade0a233 (had to control-C vagrant to stop it)

```
INFO interface: detail: SSH address: 127.0.0.1:2222
 INFO interface: detail:     testing_xenial64: SSH address: 127.0.0.1:2222
    testing_xenial64: SSH address: 127.0.0.1:2222
 INFO interface: detail: SSH username: vagrant
 INFO interface: detail:     testing_xenial64: SSH username: vagrant
    testing_xenial64: SSH username: vagrant
 INFO interface: detail: SSH auth method: password
 INFO interface: detail:     testing_xenial64: SSH auth method: password
    testing_xenial64: SSH auth method: password
```

### Expected behavior
vagrant ssh testing_xenial64 should let me into the VM using key authentication

### Actual behavior
```
$ vagrant ssh testing_xenial64
==> testing_xenial64: The machine you're attempting to SSH into is configured to use
==> testing_xenial64: password-based authentication. Vagrant can't script entering the
==> testing_xenial64: password for you. If you're prompted for a password, please enter
==> testing_xenial64: the same password you have configured in the Vagrantfile.
vagrant@127.0.0.1's password:
```

### Steps to reproduce
1. vagrant init ubuntu/xenial64
2. vagrant up --provider virtualbox
3. vagrant ssh testing_xenial64

**Comment by basictheprogram** [comment]
Looking more like it's a Box issue.  

I forgot to add that I cannot authenticate via password either.

**Comment by basictheprogram** [comment]
https://bugs.launchpad.net/cloud-images/+bug/1565985
https://bugs.launchpad.net/cloud-images/+bug/1567259

**Comment by sethvargo** [comment]
Hi @basictheprogram 

Are you confirming this is an upstream issue?

**Comment by basictheprogram** [comment]
Yes, confirming it's upstream issue.

**Comment by sethvargo** [comment]
Okay great. I'm going to close this since it looks to be upstream. The search engines have already gotten ahold of it, so it's searchable and findable on the interwebs. Thanks again for reporting! 😄

**Comment by toddlers** [comment]
I solved this via

```
    config.vm.provision "shell", inline: <<-SHELL
      echo "ubuntu:ubuntu" | sudo chpasswd
    SHELL
```

**Comment by nntoan** [comment]
@toddlers What if I'm using a different ssh username?
