### ISSUE TITLE
Plugin name is not validated in "vagrant plugin update <plugin_name >"

### ISSUE THREAD

**Issue by amit82github** [mitchellh/vagrant#7362]
### Vagrant version

Installed Version: 1.8.1
### Host operating system

Fedora release 23 (Twenty Three)
### Guest operating system

NA
### Vagrantfile

NA
### Debug output

NA
### Expected behavior

[amit@dhcp35-153 has]$ vagrant plugin update dsfr134DF
Updating plugins: dsfr134DF. This may take a few minutes...
All plugins are up to date.

The above command should give at least a warning/error message of the plugin "dsfr134DF" is not available.
### Actual behavior

[amit@dhcp35-153 has]$ vagrant plugin update dsfr134DF
Updating plugins: dsfr134DF. This may take a few minutes...
All plugins are up to date.
### Steps to reproduce
1. Install the latest vagrant and all vagrant plugins 
2. Execute the command "vagrant plugin update dsfr134DF" 
3. Check the output
### References

NA

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
