### ISSUE TITLE
vagrant up yields Too many open files - getcwd plus stack trace

### ISSUE THREAD

**Issue by hesco** [mitchellh/vagrant#7375]
I have many times today gotten an intermittent error and stack trace looking like the gist linked below, complaining:  

```
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/safe_chdir.rb:25:in `chdir': Too many open files - getcwd (Errno::EMFILE)
```

Full stack trace at:
https://gist.github.com/hesco/28846bed57876e7e4471e0ab08c1b776#file-0100-stack-trace-on-vagrant-up  

Version: Vagrant 1.8.1
Host: OS-X 10.10.5
Guest: SLES11sp4

### Vagrantfile
```ruby
grep -v '#' Vagrantfile | grep -v ^$
Vagrant.configure(2) do |config|
  config.vm.box = "sles11sp4_adp_pe_agent_v0.11.2"
  config.ssh.private_key_path = '.ssh/insecure_key_adp'
  config.vm.synced_folder ".", "/vagrant"
end
```

I expected a vagrant box launch to successfully complete, permitting me to log in to the box.  Instead, I got an aborted `vagrant up`, ending with a `vagrant destroy` and a stack trace, provided in the linked gist.  

### Steps to reproduce
1.  cd $WORKDIR
2.  vagrant up 

### References
none.

**Comment by sethvargo** [comment]
Hi @hesco 

Thank you for opening an issue, and I am sorry this is causing you problems. Can you please:

```
cd $TMPDIR
rm -rf vagrant-*
``

If you do not have a value for $TMPDIR, it's `/tmp`. This will clear some of the temporary files.

The next version of Vagrant has a lot of improvements around tempfile detection and cleanup and should be released soon.

In the meantime, you could increase the max file descriptors or try some of the suggestions in the linked post. Thanks!

- https://github.com/mitchellh/vagrant/issues/2435
- http://stackoverflow.com/questions/18808540/error-when-running-vagrant-up-too-many-open-files-getcwd-errnoemfile
