### ISSUE TITLE
vagrant share fails to return an URL

### ISSUE THREAD

**Issue by hjchin** [mitchellh/vagrant#7390]
### Vagrant version

1.8.1
### Host operating system

windows 7
### Guest operating system

ubuntu 
### Expected behavior

vagrant share cmd should returns a public accessible URL
### Actual behavior

Message below was returned.
"The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue."
### Steps to reproduce
1. vagrant login
2. vagrant share

Thanks.

**Comment by sethvargo** [comment]
Hi @hjchin 

Thank you for opening an issue. Could you please include a link to the [debug output](https://www.vagrantup.com/docs/other/debugging.html) as described in the issue template? You can use GitHub Gist or pastebin. Thanks!

**Comment by hjchin** [comment]
hi @sethvargo 

Thanks for the reply. Without changing anything, the URL is now accessible. Do you still need my log? I thought, it would be something at the service provider end.

**Comment by hjchin** [comment]
hi @sethvargo 

UPDATE: the URL is inaccessible again. Browser returns message "You have browsed from an unrecognized IP address. The proxy therefore denied access to this site or page:"
 
Here is the [debug output](<script src="https://gist.github.com/hjchin/69d9c15111642de9cc5288d09020a562.js"></script>). Thanks!

**Comment by sethvargo** [comment]
Hi @hjchin 

The Vagrant Share URLs are not valid forever: https://www.vagrantup.com/docs/share/security.html. Sessions expire in one hour.

**Comment by hjchin** [comment]
Hi @sethvargo 

I do aware that the session will expires in one hour but it is those messages are not related to expired URL.

**Comment by chrisroberts** [comment]
@hjchin Are you still experiencing this issue?

**Comment by hjchin** [comment]
@chrisroberts I have stop using vagrant share, I used local IP with port to resolve the problem.

**Comment by chrisroberts** [comment]
Okay, thanks for the reply!
