### ISSUE TITLE
unable to up VM machine on Hyper-V Host is Windows Server 2012

### ISSUE THREAD

**Issue by dhirajdp** [mitchellh/vagrant#7391]
### Vagrant version

1.8.1
### Host operating system

Windoes Server 2012
### Guest operating system

Windows10 32 bit
### Debug output

```
C:\Users\Administrator\Desktop\hyperv_Creation>vagrant up --provider=hyperv
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.1\plugins\providers\hyperv\
scripts\import_vm.ps1 : A parameter cannot be found that matches parameter
name 'Generation'.
At line:1 char:1
+ &('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.1\plugins\providers\hy
per 
    + CategoryInfo          : InvalidArgument: (:) [import_vm.ps1], ParameterB
   indingException
    + FullyQualifiedErrorId : NamedParameterNotFound,import_vm.ps1
```
### Expected behavior

VM machine should be up.
### Actual behavior

error prompts output written in Debug section
### Steps to reproduce
1. add vagrant box.
2. open command prompt with admin right and execute vagrant up command

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
