### ISSUE TITLE
make all ssh code paths in vagrant able to use keys from local SSH_AUTH_SOCK (without requiring a key on the local filesystem)

### ISSUE THREAD

**Issue by zmt** [mitchellh/vagrant#7397]
### Vagrant version
Vagrant 1.8.1

### Host operating system
OS X El Capitan Version 10.11.5 (15F34)

### Guest operating system
ubuntu precise and debian jessie

### Vagrantfile
```ruby
redacted
```

### Expected behavior
The various vagrant commands are able to use a key from the local SSH_AUTH_SOCK with no key in the search path on the local filesystem.

### Actual behavior
Various errors due to checks for private key, public key, and failure to authenticate to the guest host.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-4275
- GH-7360

**Comment by sethvargo** [comment]
Hi @zmt 

Thank you for opening an issue. I would like to better understand the use case here - why do you want to use the local SSH agent? Vagrant distributes an insecure keypair and then replaces that key on boot.

**Comment by zmt** [comment]
@sethvargo 
We use short-lived ssh certificates that are injected directly to the ssh-agent on users' workstations/laptops to access nodes in aws via the vagrant and the vagrant-aws provider plugin. This eliminates the overhead of managing thousands of individuals' ssh keys in thousands of known_hosts files on thousands of nodes (along with security benefits of using short-lived ssh certificates). We are also leveraging the ProxyCommand support which has been in vagrant for some time in conjunction with this change to enhance the security of our cloud environments managed in part through vagrant.

**Comment by zmt** [comment]
I would like to point out that the default behavior of vagrant remains unchanged in the related PR. Perhaps warnings in documentation that setting `keys_only => false` is an advanced feature/option will suffice? It would be really awesome to get this into 1.8.2. Without that, we will be forced to run off our fork, which isn't technically supported, won't be easy, and makes me cringe. We need this urgently.

**Comment by pmoody-** [comment]
Hey Seth,

this is related to https://github.com/mitchellh/vagrant/issues/7115 and https://github.com/mitchellh/vagrant/issues/7282. @zmt actually went an implemented the feature that I was asking about (and there was much rejoicing).

Let me know if you have any questions about ssh certs, etc. oh god I could probably talk for hours about them at this point.

**Comment by zmt** [comment]
I figured out how to get the dev gem working inside the installer environment, so I am less worried about how to distribute our forked version relatively stably. See https://gist.github.com/zmt/e6e23c1866ffdffe5f9f5b23a7033f20

**Comment by chrisroberts** [comment]
Closing due to: #7703
