### ISSUE TITLE
Allow vagrant provisioners to run, even though ssh isn't available

### ISSUE THREAD

**Issue by craigedmunds** [mitchellh/vagrant#7399]
Vagrant reports "Provisioners will not be run since container doesn't support SSH."; it should be possible for provisioners to run, even if SSH isn't available, leaving it to the user to make it happen?

### Vagrant version
1.8.1

### Host operating system
Mac

### Guest operating system
Ubuntu

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|

  config.vm.define "docker" do |docker|
    
    docker.vm.provider "docker" do |d|

     ...etc...

    end
    
  end

   config.vm.provision "shell", inline: "echo Hello, World"
end
```

### Debug output
$ vagrant up
Bringing machine 'docker' up with 'docker' provider...
==> docker: Docker host is required. One will be created if necessary...
    docker: Docker host VM is already ready.
==> docker: Syncing folders to the host VM...
...
==> docker: Logging in to Docker server...
==> docker: Warning: When using a remote Docker host, forwarded ports will NOT be
==> docker: immediately available on your machine. They will still be forwarded on
==> docker: the remote machine, however, so if you have a way to access the remote
==> docker: machine, then you should be able to access those ports there. This is
==> docker: not an error, it is only an informational message.
==> docker: Creating the container...
...
    docker: Container created: e84e1c209631569d
==> docker: Starting container...
==> docker: Provisioners will not be run since container doesn't support SSH.

### Expected behavior
Vagrant provisioner should echo "Hello, World"

### Actual behavior
Vagrant reports "Provisioners will not be run since container doesn't support SSH."

**Comment by sethvargo** [comment]
Hi @craigedmunds 

Thank you for opening an issue. Without SSH access, Vagrant cannot actually run the provisioner, as it has to access the machine itself in order to run the provisioners. Even with docker, there is a host VM in between, so without SSH, it's just not possible. Sorry! 😦

**Comment by craigedmunds** [comment]
Thanks. My point is that I want the command to run on the host, rather than the target VM, like a local provisioner.

**Comment by ravisanwal** [comment]
what if host is a linux? and we want to run chef-zero provisioner using docker_driver? It should be runnable in this case. chef-client -z, using docker_driver works fine, so why can't this?
