### ISSUE TITLE
Configuring and enabling network interfaces hang when provisioning Centos7 with multiple private_network IP addresses.

### ISSUE THREAD

**Issue by MikeParkin** [mitchellh/vagrant#7401]
### Vagrant version
```
vagrant -v
Vagrant 1.8.1
```

### VirtualBox version
```
VirtualBox 5.0.20
```

### Host operating system
```
OS X El Capitan
10.11.3 (15D21)
```
### Guest operating system
```
bento/centos-7.1 (latest version)
```

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.define "server" do |server|
        server.vm.box = "bento/centos-7.1"
        server.vm.network :private_network, ip: "172.16.2.2"
        server.vm.network :private_network, ip: "172.16.2.3"
        server.vm.network :private_network, ip: "172.16.2.4"
    end
end
```

### Debug output
https://gist.github.com/MikeParkin/f8f204c3404e12edfe0882d8c648d01d

### Expected behavior
Expected box provisioning to complete.

### Actual behavior
Hung unable to connect

### Steps to reproduce
1. copy vagrant file
2. vagrant up

**Comment by sethvargo** [comment]
Hi there,

This will be fixed in 1.8.3. We redid all off the guest capabilities in https://github.com/mitchellh/vagrant/pull/7393, which will be released this week or next. Thanks!
