### ISSUE TITLE
Release 1.8.2

### ISSUE THREAD

**Issue by karlkfi** [mitchellh/vagrant#7402]
It's been several months since 1.8.1 was released and many bugs have been fixed in the mean time, some that involve plugins and can't easily be used with a source-built vagrant. 

Can we get a 1.8.2 release cut soon and the remaining milestone issues pushed to 1.8.3?

**Comment by sethvargo** [comment]
This week or early next. It's already scheduled. See:

<img width="83" alt="screen shot 2016-06-07 at 1 33 34 pm" src="https://cloud.githubusercontent.com/assets/408570/15868154/6f323042-2cb4-11e6-8fc3-5c12501cdf3f.png">

**Comment by zmt** [comment]
I just get an image trying to follow the link above: `screen shot 2016-06-07 at 1 33 34 pm`.

**Comment by karlkfi** [comment]
https://github.com/mitchellh/vagrant/milestones

![screen shot 2016-06-07 at 12 10 43 pm](https://cloud.githubusercontent.com/assets/3980984/15871338/e4d7a964-2ca8-11e6-9235-ab10cc0a8ab2.png)

Do you have releases scheduled somewhere else?

**Comment by sethvargo** [comment]
@zmt - it is an image... it's a picture of my calendar.

We do not publish our release schedule publicly.

**Comment by thasmo** [comment]
@sethvargo, was there no 1.8.2 release?

**Comment by sethvargo** [comment]
No
