### ISSUE TITLE
VMware guest started by Vagrant has no connectivity

### ISSUE THREAD

**Issue by gtirloni** [mitchellh/vagrant#7407]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Windows 10 64-bit

### Guest operating system
Fedora 23 and 24

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "gtirloni/fedora24"
end
```

### Debug output
https://gist.github.com/gtirloni/62d00e1ac966a706f52948e69482167a

### Expected behavior
After booting, the Vagrant box has connectivity (e.g. can ping 8.8.8.8)

### Actual behavior
The box has an IP address, as assigned by VMware's DHCP server, but no communication happens. It's necessary to reboot the machine from within and then it has connectivity (and `vagreant ssh` works too).

If the box is halted (`vagrant halt`) and started again (`vagrant up`), it shows the same problem.

If the box's VMX file is load from VMware Player or Workstation Pro and started, it works fine on the first boot. I think this is the critical information.

### Steps to reproduce
1. vagrant up -> no connectivity

**Comment by gtirloni** [comment]
```
> vagrant plugin list
vagrant-share (1.1.5, system)
vagrant-vmware-workstation (4.0.9)
```

**Comment by sethvargo** [comment]
Hi @gtirloni 

Thank you for opening an issue. This is likely a bug in the base box you are using. Can you please try `hashicorp/precise64` and see if that box has connectivity? If so, this is a bug in the box itself which will need to be reported to the box maintainer. Thanks!

**Comment by gtirloni** [comment]
hashicorp/precise64 worked fine! oh, the troubleshooting continues then. I'll keep digging and maybe update this issue if I'm able to find what was wrong with this box in particular.

Thanks for the prompt reply.
