### ISSUE TITLE
Give a better error when vbox found, but wrong verion

### ISSUE THREAD

**Issue by zippy1981** [mitchellh/vagrant#7410]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Windows 10

### Guest operating system
Ubuntu

### Debug output
```
C:\Users\zippy\Documents\Vagrant Configs>vagrant up
==>  Provider 'virtualbox' not found. We'll automatically install it now...
     The installation process will start below. Human interaction may be
     required at some points. If you're uncomfortable with automatically
     installing this provider, you can safely Ctrl-C this process and install
     it manually.
==>  Downloading VirtualBox 5.0.10...
     This may not be the latest version of VirtualBox, but it is a version
     that is known to work well. Over time, we'll update the version that
     is installed.
```
### Expected behavior
I have vbox 51 installed. I modified [these steps](https://github.com/mitchellh/vagrant/issues/5572) to make it work However, it would be nice if vagrant said "You have an unsupported version of Virtualbox installed Only Virtualbox version 4.0 to 5.0 are supported"

**Comment by sethvargo** [comment]
Hi @zippy1981 

As I said in the previous issue, I'm not sure where you acquired VirtualBox 5.1. The official download version if 5.0.20.

**Comment by yveslaroche** [comment]
VirtualBox 5.1 is still in beta https://forums.virtualbox.org/viewtopic.php?f=15&t=78053

**Comment by zippy1981** [comment]
@sethvargo its an official beta. You can look on the home page to see a link to download it.

**Comment by sethvargo** [comment]
Hi @zippy1981 

It is our general policy that we do not add support for the beta versions until they are officially released. It is very common for the betas to have bugs or broken functionality that is resolved before the final release. Vagrant often gets blamed for these bugs, so it's our policy to not add support until the release is made official. I'll keep this issue open until then. Thank you for understanding!

**Comment by sethvargo** [comment]
GH-7574

**Comment by apetresc** [comment]
@sethvargo I think you might be misinterpreting this issue. The reporter wasn't complaining that version 5.1 wasn't supported – I think he knew it was beta. He's complaining that the error message Vagrant throws when a driver doesn't exist for that particular VB version doesn't distinguish between "I can't find Virtualbox at all" and "I see Virtualbox 5.1 but I only go up to 5.0".

This issue still exists even if 5.1 is supported now.

**Comment by zippy1981** [comment]
@sethvargo yes, @apetresc nailed it. I had a version of virtual box. It was a beta. If vagrant tole me it wouldn't support the beta version, it would be much more intuitive.
