### ISSUE TITLE
Support Virtualbox 5.1

### ISSUE THREAD

**Issue by zippy1981** [mitchellh/vagrant#7411]
I'm not on a machine I can send a PR from, but [these exact steps](https://github.com/mitchellh/vagrant/issues/5572) with the obvious modifications work.

I looked briefly at the release notes and I don't think there are any new configuration options worth tweaking the driver over.

**Comment by sethvargo** [comment]
Hi there,

Vagrant already supports VirtualBox 5.0. I just looked and there does not seem to be downloads for VirtualBox 5.1 yet: https://www.virtualbox.org/wiki/Downloads

**Comment by jfilip** [comment]
@sethvargo FWIW you can download the current beta from this forum post: https://forums.virtualbox.org/viewtopic.php?f=15&t=78053

**Comment by zippy1981** [comment]
@sethvargo there is a beta. there have actually been two 5.1 beta releases.

**Comment by sethvargo** [comment]
Hi @zippy1981

It is our general policy that we do not add support for the beta versions until they are officially released. It is very common for the betas to have bugs or broken functionality that is resolved before the final release. Vagrant often gets blamed for these bugs, so it's our policy to not add support until the release is made official. I'll keep this issue open until then. Thank you for understanding!

**Comment by gtirloni** [comment]
Vagrant 1.8.4 works fine with VirtualBox 5.1 BETA3 (5.1.0_BETA3r108118), after modifying the code manually. Tested bidirectional clipboard, synced folders and port forwarding on a Fedora 24 box.

**Comment by Stanzilla** [comment]
5.1 is now final

**Comment by dominikzogg** [comment]
Add version in:

embedded/gems/gems/vagrant-1.8.4/plugins/providers/virtualbox/driver/meta.rb:64
embedded/gems/gems/vagrant-1.8.4/plugins/providers/virtualbox/plugin.rb:58

Copy file:

embedded/gems/gems/vagrant-1.8.4/plugins/providers/virtualbox/driver/version_5_0.rb =>
embedded/gems/gems/vagrant-1.8.4/plugins/providers/virtualbox/driver/version_5_1.rb

Replace the version in the copied file

**Comment by thom-nic** [comment]
FYI: Official VBox 5.1 release announcement is on the HN frontpage, this issue is linked in comments so it will probably get a lot more attention soon.

**Comment by d-ph** [comment]
When could we expect vagrant 1.8.5 to be released?

**Comment by sethvargo** [comment]
@d-ph look at the milestone 😄

**Comment by infabo** [comment]
Can anyone provide a vagrant build to be used with VB 5.1, please? I'm on Windows Insider Preview and 5.0 is broken like hell (5.1 runs well).

**Comment by gtirloni** [comment]
@infabo you have to either make the changes to Vagrant manually, wait for the 1.8.5 milestone or go back to VirtualBox 5.0.22.

You can also built from source with [these](https://www.vagrantup.com/docs/installation/source.html) instructions.

**Comment by infabo** [comment]
Ok. thanks. VB 5.0.22 is not working for me (Host-only adapter issue).

**Comment by d-ph** [comment]
@sethvargo Thanks. So the 1.8.5 is do to be released in September 1, 2016. 

It's great that this project's release plan is so organised. Could this be possible to backport #7574 to 1.8.4 and release a patch release 1.8.4.1? This would make so many people around the world a little bit happier :)

Thanks.

**Comment by Jalle19** [comment]
Wait what? I'll have to run a custom build with scary warnings for two months because no one dared to copy-paste a file and change a version number a month ago when the betas started getting attention? Come on! A 1.8.4.1 release would indeed be nice.
