### ISSUE TITLE
Vagrant 1.8.1 Windows 7 Centos 7

### ISSUE THREAD

**Issue by AgentCormac** [mitchellh/vagrant#7412]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Win7

### Guest operating system
Centos 7

### Vagrantfile
```ruby
ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"
FORWARD_DOCKER_PORTS='true'
Vagrant.configure(2) do |config|
  config.vm.provision "docker"
 
  # The following line terminates all ssh connections. Therefore
  # Vagrant will be forced to reconnect.
  # That's a workaround to have the docker command in the PATH
  
  #Clear any existing ssh connections
  ####NOTE: ps aux seems to give variable results depending on run -> process number can be ####first #or second causing provision to fail!!!
  config.vm.provision "clear-ssh", type: "shell", inline:
        "ps aux | grep 'sshd:' | awk '{print $1}'  | xargs kill"
#        "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
 
 
  config.vm.define "dockerhost"
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port",guest: 8080, host: 8080
    config.vm.provider "virtualbox" do |vb|
	      vb.name = "dockerhost"
   end
end
```

### Debug output
```
Could not find the X.Org or XFree86 Window System, skipping.
[  OK  ]
==> dockerhost: Checking for guest additions in VM...
==> dockerhost: Rsyncing folder: /cygdrive/c/dev/vagrant/centos-mysql/host/ => /home/vagrant/sync
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/c/dev/vagrant/centos-mysql/host/
Guest path: /home/vagrant/sync
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/Users/HIGGIN~1/AppData/Local/Temp/ssh.697 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/dev/vagrant/centos-mysql/host/.vagrant/machines/dockerhost/virtualbox/private_key' --exclude .vagrant/ /cygdrive/c/dev/vagrant/centos-mysql/host/ vagrant@127.0.0.1:/home/vagrant/sync Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```

### Expected behavior
Machine started correctly

### Actual behavior
Machine started but no rsync of folders. When using as a docker host, containers not started

### Steps to reproduce
Vagrant up

**Comment by sethvargo** [comment]
Hi @AgentCormac 

Thank you for opening an issue. Can you please share the complete [debug output](https://www.vagrantup.com/docs/other/debugging.html) as a GitHub Gist?

**Comment by AgentCormac** [comment]
No problem. 

Vagrant log at:

https://gist.github.com/AgentCormac/d81105907a80d8761cbcec608dc0c844

Let me know if you need anything else.

**Comment by sethvargo** [comment]
Hi @AgentCormac 

Does your user have permission to execute rsync on the guest? https://forum.synology.com/enu/viewtopic.php?t=92627

**Comment by AgentCormac** [comment]
No idea. This is using the standard Centos7 image from Atlas:
[https://atlas.hashicorp.com/centos/boxes/7](url)

What user is Vagrant running as on the host during start up?

Checking the vagrant user home directory reveals that the sync folder that it is trying to rsync is owned by root. Is this correct?

[vagrant@east00101306v01 ~]$ whoami
vagrant
[vagrant@east00101306v01 ~]$ pwd
/home/vagrant
[vagrant@east00101306v01 ~]$ ls -al
total 28
drwx------. 4 vagrant vagrant 4096 Jun 10 10:47 .
drwxr-xr-x. 3 root    root    4096 Apr  4 18:08 ..
-rw-r--r--. 1 vagrant vagrant   18 Nov 20  2015 .bash_logout
-rw-r--r--. 1 vagrant vagrant  193 Nov 20  2015 .bash_profile
-rw-r--r--. 1 vagrant vagrant  231 Nov 20  2015 .bashrc
drwx------. 2 vagrant vagrant 4096 Jun 10 10:44 .ssh
drwxr-xr-x. 2 root    root    4096 Jun 10 10:47 sync
[vagrant@east00101306v01 ~]$

**Comment by sethvargo** [comment]
Hi @AgentCormac 

Thank you for your reply. There are no "standard" boxes on Atlas - boxes are namespaced by user, just like code on GitHub. Those boxes just happen to be published by a user with the username "centos". Could you please try one of the boxes under the `bento` namespace

**Comment by AgentCormac** [comment]
My apologies, sorry to have wasted your time. I though I was using an "official" Centos image. Switching to bento/centos-7.2 has sorted out the issue. I think using centos/7 as a username/image name is quite confusing (sneaky) for a newb like myself.

I now just need to get PostgreSQL running in a docker container and accessible from the host windows machine. I didnt have any joy using the boot2docker image, hence the switch to a Centos image (which mirrors my live environment).

Thanks for your help.
