### ISSUE TITLE
vagrant rsync on smartos fails

### ISSUE THREAD

**Issue by brimworks** [mitchellh/vagrant#7414]
To reproduce:

Run a smartos virtual machine, then run `vagrant rsync` to sync some shared folders (obviously you need to use the rsync shared folders feature).

Error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

pfexec find '/vm/shared/folder/location' '(' ! -user vagrant -or ! -group vagrant ')' -print0 | pfexec xargs -0 chown vagrant:vagrant

Stdout from the command:



Stderr from the command:

chown: missing operand after 'vagrant:vagrant'
Try 'chown --help' for more information.
```

The fix is simple (I'm on a Mac):

Modify `/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/guests/smartos/cap/rsync.rb` so the `self.rsync_post` method passes the `-r` option to `xargs`:

```
        def self.rsync_post(machine, opts)
          machine.communicate.execute("#{machine.config.smartos.suexec_cmd} find '#{opts[:guestpath]}' '(' ! -user #{opts[:owner]} -or ! -group #{opts[:group]} ')' -print0 | " +
              "#{machine.config.smartos.suexec_cmd} xargs -0 -r chown #{opts[:owner]}:#{opts[:group]}")
        end
```

**Comment by brimworks** [comment]
To more easily reproduce this, here is my Vagrantfile:

```ruby
Vagrant.configure(2) do |config|

   config.vm.box = "livinginthepast/smartos-base64"
    config.vm.communicator = 'smartos'
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.network "private_network", ip: "192.168.50.4"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
        vb.gui = false
    end

    config.global_zone.platform_image = 'latest'
    config.zone.name = 'base-multiarch'
    config.zone.brand = 'joyent'
    config.zone.image = '7fe47316-0c91-11e6-9a11-73388d2105ea'
    config.zone.memory = 1536
    config.zone.disk_size = 5
end
```

Once the system is up and running, make a change to a file that already exists (and therefore has the right ownership), then run ```vagrant rsync```.

**Comment by sethvargo** [comment]
Hi @brimworks 

Would you like to submit a PR for this change?

**Comment by brimworks** [comment]
Sounds good to me :)

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
