### ISSUE TITLE
Support for custom CLI arguments.

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#7416]
I'm using Vagrant 1.8.1 and I'd like to define my own command-line arguments, however it's not possible, because vagrant fails with:

```
$ vagrant up --provider=aws --keypair-name=Testing
An invalid option was specified. The help for this command is available below.
Usage: vagrant up [options] [name]
...
```

My code in Vagrantfile is like:

```
require 'getoptlong'

# Parse CLI arguments.
opts = GetoptLong.new(
  [ '--provider',     GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--keypair-name', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--foo',          GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--bar',          GetoptLong::OPTIONAL_ARGUMENT ]
)

provider='virtualbox'
keypair_name=ENV['KEYPAIR_NAME']
begin
  opts.each do |opt, arg|
    case opt
      when '--provider'
        provider=arg
      when '--keypair-name'
        keypair_name=arg
      when '--foo'
        foo=arg
      when '--bar'
        bar=arg
    end # case
  end # each
  rescue GetoptLong::InvalidOption => invalid_option
    puts invalid_option
    exit
end

# Vagrantfile API/syntax version.
Vagrant.configure(2) do |config|

  config.vm.define "default-#{provider}"

  config.vm.provider :aws do |aws, override|
    aws.ami = "ami-7747d01e"
    aws.instance_type = "m3.medium"
    aws.keypair_name = keypair_name
  end

  # ...
end
```

Is there any way to force `vagrant` to ignore the parameter validation, so I can provide my own?

**Comment by sethvargo** [comment]
Hi @kenorb 

You'll need to `dup` and `unshift` args, but that's more of a Rubyism than a Vagrant issue. The problem is that CLI flags are _already parsed_ by the time they get to the Vagrantfile parsing, so the error is going to raise prior to Vagrant.

If you want custom CLI flags, I would recommend authoring a custom plugin command instead. Thanks!

**Comment by kenorb** [comment]
Ok, I actually manage to make it working (as shown [here](http://stackoverflow.com/a/31070025/55075)), my mistake was that the parameter was in the wrong place, this should be:

    vagrant --keypair-name=Testing up --provider=aws

So basically the custom parameter works only when specified before the vagrant command (e.g. `up`).
