### ISSUE TITLE
VBoxManage.exe: error: Invalid NIC number

### ISSUE THREAD

**Issue by cdreier** [mitchellh/vagrant#7417]
any help is much appreciated!

### Vagrant version
Vagrant 1.8.3

### Host operating system
windows 10 

### Guest operating system
tried diffrent boxes, ubuntu and mint 

### Vagrantfile
default vagrant file, with vagrant init

### Debug output
```
$ $ vagrant.exe up
==> default: Checking if box 'janihur/ubuntu-1404-desktop' is up to date...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "60a76137-2c0e-46ab-a50e-7a37a6865051", "--nic2", "none", "--nic3", "none", "--nic4", "none", "--nic5", "none", "--nic6", "none", "--nic7", "none", "--nic8", "none", "--nic9", "none", "--nic10", "none", "--nic11", "none", "--nic12", "none", "--nic13", "none", "--nic14", "none", "--nic15", "none", "--nic16", "none", "--nic17", "none", "--nic18", "none", "--nic19", "none", "--nic20", "none", "--nic21", "none", "--nic22", "none", "--nic23", "none", "--nic24", "none", "--nic25", "none", "--nic26", "none", "--nic27", "none", "--nic28", "none", "--nic29", "none", "--nic30", "none", "--nic31", "none", "--nic32", "none", "--nic33", "none", "--nic34", "none", "--nic35", "none", "--nic36", "none"]

Stderr: VBoxManage.exe: error: Invalid NIC number 9
VBoxManage.exe: error: Invalid NIC number 10
VBoxManage.exe: error: Invalid NIC number 11
VBoxManage.exe: error: Invalid NIC number 12
VBoxManage.exe: error: Invalid NIC number 13
VBoxManage.exe: error: Invalid NIC number 14
VBoxManage.exe: error: Invalid NIC number 15
VBoxManage.exe: error: Invalid NIC number 16
VBoxManage.exe: error: Invalid NIC number 17
VBoxManage.exe: error: Invalid NIC number 18
VBoxManage.exe: error: Invalid NIC number 19
VBoxManage.exe: error: Invalid NIC number 20
VBoxManage.exe: error: Invalid NIC number 21
VBoxManage.exe: error: Invalid NIC number 22
VBoxManage.exe: error: Invalid NIC number 23
VBoxManage.exe: error: Invalid NIC number 24
VBoxManage.exe: error: Invalid NIC number 25
VBoxManage.exe: error: Invalid NIC number 26
VBoxManage.exe: error: Invalid NIC number 27
VBoxManage.exe: error: Invalid NIC number 28
VBoxManage.exe: error: Invalid NIC number 29
VBoxManage.exe: error: Invalid NIC number 30
VBoxManage.exe: error: Invalid NIC number 31
VBoxManage.exe: error: Invalid NIC number 32
VBoxManage.exe: error: Invalid NIC number 33
VBoxManage.exe: error: Invalid NIC number 34
VBoxManage.exe: error: Invalid NIC number 35
VBoxManage.exe: error: Invalid NIC number 36
```

### Expected behavior
box should start

### Actual behavior
a lot of invalid NIC numbers

### Steps to reproduce
1. vagrant init choose/abox
2. vagrant up

### References
https://github.com/mitchellh/vagrant/issues/6125
https://github.com/cambridge-healthcare/hi_sinatra-docker/issues/5

**Comment by sethvargo** [comment]
Hi @cdreier 

Thank you for opening an issue. Could you please share the complete [debug output](https://www.vagrantup.com/docs/other/debugging.html) as a GitHub gist? What version of VirtualBox are you using?

**Comment by cdreier** [comment]
Hi @sethvargo

thanks a lot for your fast response!

i use a fresh install from virtual box, version 5.0.20 r106931

and my complete debug output: https://gist.github.com/cdreier/9b5beb38473e9221dfe71ad04b58f73b

also i tried the git bash, cmd and cmd as admin, everywhere the same issue

**Comment by apestov** [comment]
Confirm probled is observed with Windows10/Vagrant 1.8.3/VirtualBox 5.0.20 and with `hashicorp/precise64` box.

Looks like is caused by recent change "Set maximum network adapters to 36 [GH-7293, GH-7286]". Indeed if change back `max_network_adapters` from 36 to 8 at `C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.3\plugins\providers\virtualbox\driver\base.rb` it starts successfully.

**Comment by jasongerard** [comment]
@apestov This fixed my issue as well.

**Comment by cdreier** [comment]
thanks a lot for you fast help! everything is working again :-)

**Comment by Steve-MP** [comment]
@apestov Wow, thanks for finding a solution so quickly! I had the same problem on the same setup as you and your solution corrected it.

**Comment by AndreasElia** [comment]
I started a fresh environment this morning and came across this issue. I'm afraid the fix @apestov provided left me with another error. https://gist.github.com/AndreasElia/dd8e57ed56894445b40ab731c0f3885b

**Comment by alexcwatt** [comment]
@apestov Thanks! I am just getting started with Vagrant today and ran into this issue too. It's great to have it working!

**Comment by zhenkyle** [comment]
@apestov Thanks! It's working for me.

**Comment by hyamamoto** [comment]
@apestov thanks, my problem on win10 also went away after changing a value of `max_network_adapters`.
- virtualbox 5.0.20 r106931
- vagrant 1.8.3

**Comment by rthideaway** [comment]
same problem with ubuntu/xenial64 and other boxes as well, the update of vagrant totally killed our workflow, we needed to downgrade immediatelly for the time being

**Comment by majkinetor** [comment]
I  confirm that changing from 36 to 8 does the job - Win7, vagrant 1.8.3, vbox 5.0.20

**Comment by gregruth** [comment]
Fixed on Win10 for me too

**Comment by Namax0r** [comment]
@apestov your solution fixed the issue for me on:
Windows 7
Vagrant 1.8.3
VirtualBox-5.0.20 r106931

**Comment by virgofx** [comment]
Please release new version

**Comment by kushal25** [comment]
The fix worked for me too. Thanks!!

**Comment by apestov** [comment]
@sethvargo Thank you for the prompt Vagrant 1.8.4 release with that issue fixed!

**Comment by vmartsen-amplify** [comment]
Worked for me! Thanks a lot!

**Comment by vitaliy-zinchenko** [comment]
It helped me. Thanks!

**Comment by rthideaway** [comment]
many many many thanks for new release! it fixed all the issues! even nfs mounting under windows working again!

**Comment by Bodom78** [comment]
Ran into this issue after a fresh install of Windows. Changing max_network_adapters to 8 fixes this issue for me as well.

**Comment by kalapakim** [comment]
Worked for me, thanks!!

**Comment by ingoplath** [comment]
I ran into this problem with vagrant 1.8.5 in Virtual Box 5.1.2 and a Windows 7 client.

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "dfa8296c-2696-4659-a616-4a3c1f85e1da", "--nic1", "nat", "--nic2", "hostonly", "--hostonlyadapter2
", "VirtualBox Host-Only Ethernet Adapter #2", "--cableconnected2", "on", "--nic3", "hostonly", "--hostonlyadapter3", "V
irtualBox Host-Only Ethernet Adapter #3", "--cableconnected3", "on", "--nic4", "hostonly", "--hostonlyadapter4", "Virtua
lBox Host-Only Ethernet Adapter #4", "--cableconnected4", "on", "--nic5", "hostonly", "--hostonlyadapter5", "VirtualBox
Host-Only Ethernet Adapter #5", "--cableconnected5", "on", "--nic6", "hostonly", "--hostonlyadapter6", "VirtualBox Host-
Only Ethernet Adapter #6", "--cableconnected6", "on", "--nic7", "hostonly", "--hostonlyadapter7", "VirtualBox Host-Only
Ethernet Adapter #7", "--cableconnected7", "on", "--nic8", "hostonly", "--hostonlyadapter8", "VirtualBox Host-Only Ether
net Adapter #8", "--cableconnected8", "on", "--nic9", "hostonly", "--hostonlyadapter9", "VirtualBox Host-Only Ethernet A
dapter #9", "--cableconnected9", "on"]

Stderr: VBoxManage.exe: error: Invalid NIC number 9
VBoxManage.exe: error: Invalid NIC number 9
VBoxManage.exe: error: Invalid NIC number 9

vagrant -v
Vagrant 1.8.5
