### ISSUE TITLE
Punctuation on URL's confusing text editor

### ISSUE THREAD

**Issue by mcrmonkey** [mitchellh/vagrant#7423]
This is _really minor_ but it annoyed me enough to make a change...

Documentation URL's present in Vagrantfile generated with `vagrant init` have a period/fullstop at the end.

This confuses some text editors in GUI envionments that wrongly include this when the URL is activated sent to the browser leading to a 404

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/pull/7424
