### ISSUE TITLE
Bundler issue when installing plugin on Windows 7/10 

### ISSUE THREAD

**Issue by lazarmarkov** [mitchellh/vagrant#7429]
### Vagrant version 
1.8.3

### Host operating system
Occurs both on Windows 10 x64 & Windows 7 x64

### Debug output
https://gist.github.com/lazarmarkov/2910674579a830393e24f8381fce76f5

### Expected behavior
Should have installed vagrant-omnibus plugin.

### Actual behavior
Bundler exception:
```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Checksum of /versions does not match the checksum provided by server! Something is wrong.
```

=======================================================

I also tried installing `vagrant plugin install vagrant-ohai` plugin to discern if the problem is specific to `vagrant-omnibus` but the issue persisted. 

### Steps to reproduce
1. Install Vagrant 1.8.3
2. run `$ vagrant plugin install vagrant-omnibus`

**Comment by sethvargo** [comment]
Dupe #7422
