### ISSUE TITLE
ssh_exchange_identification: read: Software caused connection abort

### ISSUE THREAD

**Issue by stefda** [mitchellh/vagrant#7431]
With vagrant 1.8.3 installed, cygwin and functional openssh, `vagrant up` runs without any errors but `vagrant ssh` errs with "ssh_exchange_identification: read: Software caused connection abort".

I have tried with previous versions of vagrant (1.8.1 and 1.8.0) - all the same.

After `vagrant reload`, the process gets stuck on "default: Warning: Remote connection disconnect. Retrying...". I found out by running VirtualBox that this is because the box prompts for login. Using vagrant/vagrant for user/password gets me in (inside the VirtualBox terminal) at which point the `vagrant up` command fails.

My [Vagrantfile](https://gist.github.com/stefda/d818f5b83c5c8cd24bf0aec0f7d8dbc5) and the output from [`vagrant ssh --debug`](https://gist.github.com/stefda/bfe6d65286d7762cc0ada222b55e0622).

What is the culprit?

EDIT: Virtualisation is enabled.

**Comment by sethvargo** [comment]
Hi @stefda 

Thank you for opening an issue. This is likely a local environment issue, since we have not seen reports of it before. Do you have an SSH agent installed on your machine? SSH error 255 means a general SSH error occurred, so it's likely an issue with the locally installed agent.

**Comment by stefda** [comment]
Yes, I'm using Cygwin's install of openssh (`OpenSSH_7.2p2, OpenSSL 1.0.2h  3 May 2016`). I can ssh into my other servers and I have an ssh-agent running with my presonal key added.

I suspect it is an environment issue but don't know how to fix it. Any help in addressing this is appreciated!

**Comment by sethvargo** [comment]
Hey @stefda 

With the box running, can you run:

```
$ ssh vagrant@127.0.0.1 -p 2222 -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i C:/Users/stefda/sandbox/citypantry/vagrant/.vagrant/machines/default/virtualbox/private_key
```

If that works, great. If not, can you try removing arguments until you get something that works?

**Comment by stefda** [comment]
Sadly that doesn't work  - getting the same error no matter what arguments I remove/add.

I just tried to bring up another clean machine simply by running `vagrant init ubuntu/trusty64`. I could then `vagrant ssh` into the box no problem.

Could the error ebove be related to using SMB shared folders? I will play with the Vagrantfile a bit to see if I can get it running but it's very tedious - if I `vagrant reload` or `up` an already provisioned machine with this Vagrantfile then I don't even get to the point where I can try to ssh into it. The reload gets stuck on "default: Warning: Remote connection disconnect. Retrying...".

**Comment by sethvargo** [comment]
Hi @stefda 

It could be related to SMB - SMB shared folders can mess with the configuration.

**Comment by stefda** [comment]
All right, after a lengty trial-error process I managed to pin the issue down - our provisioning Puppet script was setting the ssh inside the box exclusively to port 2223.

Thanks you for the tips, @sethvargo, hope this helps someone in the future.

**Comment by shihongwei** [comment]
get the same problem

**Comment by snnsnn** [comment]
Closing current terminal and starting a new one worked for me.

**Comment by oliver-dungey** [comment]
I got this error after rebooting my host Windows O/S without shutting down my vagrant VM's. Running ```vagrant reload``` fixed the issue for me.
