### ISSUE TITLE
Vagrant does not sync folder to guest using VMWare Plugin

### ISSUE THREAD

**Issue by austinlparker** [mitchellh/vagrant#7434]
Vagrant 1.8.1 (VMWare Plugin v 4.0.9)
Host: MacOS X 10.11.5
Guest: CentOS 6.7

Vagrantfile
```ruby
config.vm.define "lin" do |linux|
    linux.vm.box = 'bento/centos-6.7'
    linux.vm.hostname = 'lin'
    linux.vm.network 'private_network', ip: '172.16.0.12'
    linux.vm.provider :virtualbox do |vb|
      vb.name = 'lin'
      vb.memory = 1024
    end

	# Install specific version of chef to avoid omnibus retrieval errors
linux.vm.provision "shell", run: "always", path: "./config/linux/install_chef.sh"

    linux.vm.provision 'chef_solo' do |chef|
      chef.version = '12.10.24'
      chef.cookbooks_path = ['chef/cookbooks/berks-cookbooks', 'chef/cookbooks']
      chef.json = {
        'linux_generic' => {
          'hostname' => 'lin',
          'loadmanagerip' => '172.16.0.10',
          'loadmanagerhostname' => 'dc'
        }
      }
      chef.add_recipe "linux_generic::centos6"
    end
  end
```

Debug Output: https://gist.github.com/austinlparker/762dcc4924dc06b7df5d18c18b20bb1d

I expected the VM to mount the shared folder correctly, however, I encountered the following error - 
```
 INFO ssh: Execute: vmhgfs-fuse -o uid=`id -u vagrant`,gid=500,allow_other '.host:/-vagrant' /vagrant (sudo=true)
DEBUG ssh: Exit status: 255
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

vmhgfs-fuse -o uid=`id -u vagrant`,gid=500,allow_other '.host:/-vagrant' /vagrant

Stdout from the command:



Stderr from the command:

```

I'm unable to attempt to reproduce this issue as I do not have another system of the same sort around.

This issue only began to present itself last week - I have been able to bring up this box successfully before then. I thought the problem might be the shell provisioner to install chef, but even removing that from the Vagrantfile results in the same behavior. I've deleted the machine from the .vagrant folder, and that didn't seem to resolve the issue either.

**Comment by austinlparker** [comment]
I suspect this is a box issue actually - I switched to a different one and I'm not seeing the same error. (puhpet/centos65-x64)

**Comment by sethvargo** [comment]
This is an issue with that box. Please update vagrant, vagrant-vmware-fusion, and the latest version of the bento box and it should go away. Thanks! 😄
