### ISSUE TITLE
NFS mount broken on osx

### ISSUE THREAD

**Issue by ol0lll** [mitchellh/vagrant#7443]
Since vagrant version 1.8.3 mount_nfs on linux guests is not raising retryable exceptions when NFS Server is not ready, therefore nfs mount command is not retried.
Commit 837713c2d13139c8741607ee089dcc9fd25470f2 is joining commands which seems to break exception handling, I was able to mitigate this problem executing each command seperately:

https://gist.github.com/ol0lll/2822039f0492ee3ddddd45d3b9965ce7
in plugins/guests/linux/cap/mount_nfs.rb

**Comment by sethvargo** [comment]
Hi @ol0lll 

Thank you for opening an issue. The reason we moved the mount to a single command is that it's _significantly_ faster. Is there an easy way to force the mount to fail so I can test the retry logic?

**Comment by ol0lll** [comment]
Hi @sethvargo,

thank you for your quick reply. I am not exactly sure why nfs is slow in my setup, for testing I think you could just leave the mount_options array empty, which causes the mount command to fail on the guest.

`config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: []`

This raises the exception when commands run separately.
{% gist c818e00213a3ce0cd600a25ed2f741d2 %}

**Comment by mathewpeterson** [comment]
Please let me know if there's anything that I could help out with. We are unable to use Ubuntu 16.04 boxes with Vagrant 1.8.1 so this is a fairly big issue for us.
