### ISSUE TITLE
Incorrect last version?

### ISSUE THREAD

**Issue by rbatllet** [mitchellh/vagrant#7444]
The last version is not yet the latest:

```
$ vagrant version
Installed Version: 1.8.4
Latest Version: 1.8.3
```

**Comment by nickwright80** [comment]
try `rm ~/.vagrant.d/data/checkpoint_cache`?

**Comment by rbatllet** [comment]
Now it seems ok:

```
$ vagrant version
Installed Version: 1.8.4
Latest Version: 1.8.4
```

**Comment by nickwright80** [comment]
Same issue here on OS X 10.11.5 – persisted even after uninstalling/reinstalling:

```
Installed Version: 1.8.4
Latest Version: 1.8.1
```

It seems to me there are two things contributing to this issue:

1. `~/.vagrant.d/data/checkpoint_cache` is not updated after initial creation
2. The uninstaller tool (included in the .dmg) leaves `~/.vagrant.d/data/checkpoint_cache` intact

**Comment by sethvargo** [comment]
Im going to open a bug in our checkpoint library internally to track this. Thanks!
