### ISSUE TITLE
WinRM::HTTP::HttpNegotiate::WinRMWebServiceError

### ISSUE THREAD

**Issue by majkinetor** [mitchellh/vagrant#7446]
### Vagrant version

1.8.3
### Host operating system

Windows 7 x64, Powershell 5
### Guest operating system

Windows 2012 R2 Core
### Output

```
==> server-web-core: Configuring and enabling network interfaces...
An error occurred executing a remote WinRM command.

Shell: run_powershell_script
Command: # Get network connections
$networkListManager = [Activator]::CreateInstance([Type]::GetTypeFromCLSID([Guid]"{DCB00C01-570F-4A9B-8D69-199FDBA5723B}"))
$connections = $networkListManager.GetNetworkConnections()

# Set network location to Private for all networks
$connections | % {$_.GetNetwork().SetCategory(1)}

if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
Message: uninitialized constant WinRM::HTTP::HttpNegotiate::WinRMWebServiceError
```

After this error server works normally, I can access it using powershell remoting or vagrant rdp and access its web server from local machine.

**Comment by majkinetor** [comment]
This is my Vagrant file:

 ```ruby
Vagrant.configure("2") do |config|

    config.vm.communicator = "winrm"
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.windows.halt_timeout = 15
    config.windows.set_work_network = true

    config.vm.guest = :windows
    config.vm.boot_timeout = 600
    config.vm.network :forwarded_port, guest: 3389, host: 33389, id: "rdp", auto_correct: true
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
    config.vm.synced_folder "..", "/vagrant_data"

    config.vm.define "server-web-core", autostart: false do |c|
        c.vm.box      = "coz-server-web-core"
        #c.vm.hostname = c.vm.box
        c.vm.box_url  = get_box_url c.vm.box
        c.vm.network "private_network", ip: "192.168.0.11"
    end

```

Commented line `c.vm.hostname = c.vm.box` creates this problem when active.

**Comment by mwrock** [comment]
The actual error message here is a bug in the WinRM gem however, the fix for that bug would only give you a better error message basically saying that it cant decrypt the athentication token from the server.

It looks like your port forwarding is not configured for winrm (just ssh and rfp), you might try adding:
```
config.vm.network :forwarded_port, guest: 5985, host: 55985, id: "winrm", auto_correct: true
```
to your Vagrantfile.

**Comment by majkinetor** [comment]
Thanks, I will try it ? But.... what all that has to do with a server name ?

**Comment by mwrock** [comment]
oh boy...I totally missed the last line of your original message. Well that is gonna determine how the winrm communicator forms the winrm endpoint URL. The box name is very likely not resolvable on your network.

**Comment by mwrock** [comment]
well that is odd. Could you provision with `--debug` and provide a gist with the output? That should allow us to see the exact winrm endpoint uri being used.

**Comment by majkinetor** [comment]
OK, I will do it later. I think its worth mentioning few more things:

- On one windows ISO (2012 R2) changing the name of the core machine resulted in "out of memory" as soon as you enter the machine. See https://github.com/majkinetor/posher/issues/1. Vagrant never complains.
- On another which is reported here there is no memory error but vagrant complains as described.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
