### ISSUE TITLE
Cannot get status of VM in HyperV provider on Windows Server 2012R2 & Windows 8.1

### ISSUE THREAD

**Issue by interdev** [mitchellh/vagrant#7447]
### Vagrant version
1.8.3
Visual check of code has same issue in 1.8.4

### Host operating system
Windows 8.1 & Windows Server 2012R2

### Guest operating system
Windows Server 2012R2

### Vagrantfile
N/A provider issue affecting all Vagrantfiles

### Expected behaviour

**Only For HyperV provider**
Should have detected HyperV VM status

### Actual behavior

Failed due to use of dynamic testing of exception type which is not supported on the platform.

### Steps to reproduce
1. vagrant up for anything with hyperV provider on named platforms results in the error

```
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.4\plugins\providers\hyperv\scripts\get_vm_status.ps1:21 char:8
+ } catch $ExceptionType {
+        ~
The Catch block is missing its statement block.
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.4\plugins\providers\hyperv\scripts\get_vm_status.ps1:21 char:24
+ } catch $ExceptionType {
+                        ~
Unexpected token '{' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingCatchHandlerBlock
```

**Comment by blanoz** [comment]
It does not work on win 10 either .. This is critical, as it renders the hyper-V provider useless

**Comment by simonp22** [comment]
Also having this issue,

Realted to https://github.com/mitchellh/vagrant/commit/0a7c20a93a7fb80ddfc8d37474bec4805ccd87ae

**Comment by codekaizen** [comment]
The above pull request also changes what is used to determine which exception type is thrown. On Windows Server 2012, even with Powershell 5, the wrong exception type is thrown; it depends on Hyper-V version.
