### ISSUE TITLE
Add a setting to specify HGFS driver

### ISSUE THREAD

**Issue by ccope** [mitchellh/vagrant#7449]
Related to #6775, now all of my shared folders (except /mnt/hgfs) are being mounted with vmhgfs-fuse. However, it is buggy and crashes for my users. I still have the vmhgfs kernel module built and loaded, so can you add a setting to configure which driver to use?

Vagrant version: 1.8.1
Host operating system: Mac OS X El Capitan
Guest operating system: Ubuntu 12.04 with kernel 3.16
### Expected behavior

`git pull` on a large repository should update the checkout
### Actual behavior

`Transport disconnected`, write fails, have to reboot the VM

**Comment by chrisroberts** [comment]
Using: `mount_strategy: "kernel"` will cause the plugin to not use vmhgfs. Cheers!

**Comment by ccope** [comment]
Awesome!
