### ISSUE TITLE
vagrant version reports 1.8.3 as latest with 1.8.4 installed

### ISSUE THREAD

**Issue by zmt** [mitchellh/vagrant#7451]
### Vagrant version
```
$ vagrant -v
Vagrant 1.8.4
```
### Host operating system
OS X El Capitan Version 10.11.5 (15F34)

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
```
$ vagrant version
Installed Version: 1.8.4
Latest Version: 1.8.3
```

### Expected behavior
Installed Version == Latest Version == 1.8.4

### Actual behavior
See above

### Steps to reproduce
1. Install vagrant 1.8.4
2. run `vagrant version`
3. observe output pasted above

### References
Are there any other GitHub issues (open or closed) that should be linked here?
N/A

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/7444
