### ISSUE TITLE
IPv4 Forwarding Required on Guest

### ISSUE THREAD

**Issue by karlkfi** [mitchellh/vagrant#7452]
I don't have a minimal example, but I wanted to post in case other people are seeing this.

It is regularly reproducible using https://github.com/dcos/dcos-vagrant/ in the following environments:
### Environment
- Vagrant 1.8.3 & 1.8.4
- VirtualBox 5.0.20
- Host OS: Mac OS 10.10, 10.11, and Ubuntu 16
### Provisioning

I have a Centos (7.2) box built with packer for VirtualBox (5.0.20). 
Guest VM provisioning includes starting a few docker (1.11) containers.

My [Vagrantfile](https://github.com/dcos/dcos-vagrant/blob/master/Vagrantfile) gives the VM a specific IP on a host-only private network: https://github.com/dcos/dcos-vagrant/blob/master/Vagrantfile#L217
### Expected behavior

On Vagrant **1.8.1**, the containers come up and are **reachable** on IPv4, and reachable from guests/host via docker-exposed ports on the IP of the VM.
### Actual behavior

On Vagrant **1.8.3 & 1.8.4**, the containers come up, but are **unreachable** on IPv4 from guests/host via docker-exposed ports on the IP of the VM.
### Workarounds

Two workarounds fix IPv4 forwarding: 
1) Enable IPv4 forwarding with `sysctl -w net.ipv4.ip_forward=1`
2) Reboot docker daemon with `service docker restart`

What changed in Vagrant 1.8.3 that makes this required? Is it a regression or purposeful?
### Box Image Setup

The following network related setup is performed by packer when building the box image:
- IPv6 is disabled: https://github.com/dcos/dcos-vagrant-box/blob/master/bin/docker.sh#L43
- SELinux is disabled: https://github.com/dcos/dcos-vagrant-box/blob/master/bin/docker.sh#L39
- Firewalld is disabled: https://github.com/dcos/dcos-vagrant-box/blob/master/bin/dcos-deps.sh#L23
- Network interfaces are cleaned: https://github.com/dcos/dcos-vagrant-box/blob/master/bin/cleanup.sh#L17

**Comment by karlkfi** [comment]
Workaround code in packer provisioning to survive reboots:

```
function systctl_set() {
  key=$1
  value=$2
  config_path='/etc/sysctl.conf'
  # set now
  sysctl -w ${key}=${value}
  # persist on reboot
  if grep -q "${key}" "${config_path}"; then
    sed -i "s/^${key}.*$/${key} = ${value}/" "${config_path}"
  else
    echo "${key} = ${value}" >> "${config_path}"
  fi
}

echo '>>> Enabling IPv4 Forwarding'
systctl_set net.ipv4.ip_forward 1
```

Added to https://github.com/dcos/dcos-vagrant-box/blob/master/bin/docker.sh

**Comment by karlkfi** [comment]
This is not using the docker provider. It's using VirtualBox, but deploying a VM with docker on it.

**Comment by sethvargo** [comment]
What is your guest?

**Comment by karlkfi** [comment]
Centos 7.2 guest, as the report says.

**Comment by karlkfi** [comment]
Specifically this box: https://downloads.dcos.io/dcos-vagrant/dcos-centos-virtualbox-0.7.0.box

**Comment by sethvargo** [comment]
Hi @karlkfi 

I see a number of plugins including hostmanager and vbguest in that Vagrantfile which have traditionally been known to cause problems related to networking. Are you able to reproduce this issue with a vanilla Vagrantfile and no plugins installed?

The reason I ask is that I personally tested every major guest for the Vagrant 1.8.3 release with a Vagrantfile that had forwarded ports, private IPs, and public IPs, and did not see this issue. I did not try the DCOS box (I used the boxes under `bento` on Atlas), but it would be helpful if you could uninstall all plugins and remove their configuration from the Vagrantfile and see if the issue reproduces.

**Comment by guanpu** [comment]
Hi @sethvargo , your comment really helps! I met similar problem( vagrant 1.8.7, VirtualBox 5.1.8, Host OS OracleLinux7, guest OS OracleLinux7), and find net.ipv4.ip_forward=0.
After remove the usage of hostmanager in Vagrantfile -- no need to uninstall this plugin in your host OS -- ipv4.ip_forward is enabled by default.

**Comment by chrisroberts** [comment]
It seems the original cause of the issue was related to installed plugins. If this behavior is persistent without plugins installed, please reopen this issue or create a new one. Thanks!
