### ISSUE TITLE
insert_private_key only works once

### ISSUE THREAD

**Issue by karlkfi** [mitchellh/vagrant#7455]
Commit https://github.com/mitchellh/vagrant/commit/e2b7e28082a4b5e546655526773477e8df833bdd#diff-715ea9eefd185460afff2f7cf7eb0c3b broke `insert_private_key` on linux such that insertions do not append with a newline.

I ran into this using a custom provisioner that adds a common key for all VMs. Inserting after the key that vagrant inserts means that only the first key works for login, not the 2nd key.

**Comment by jonnywilliamson** [comment]
I have wasted a full day with this bug and was in the midst of tracing through the code when I happened to spot your Bug report.

I've sent a PR to show a workable fix, but I expect someone to come up with a neater linux command line solution.

It does work/fix this problem however.

**Comment by karlkfi** [comment]
Fixed by #7456
