### ISSUE TITLE
Vagrant doesn't support scp protocol for config.vm.box_url

### ISSUE THREAD

**Issue by erikfercak** [mitchellh/vagrant#7457]
Hi,

we want to distribute our box to off-site developers securely and with as little hassle as possible. They already have their SSH keys so we thought we would use scp to do it. I couldn't find a mention of scp as a supported protocol in the official documentation but Vagrant should have scp support according to GH-1041 and http://chase-seibert.github.io/blog/2014/05/18/vagrant-authenticated-private-box-urls.html.

### Vagrant version
1.8.4.

### Host operating system
OS X El Capitan 10.11.5

### Guest operating system
Debian 8.4

### Virtualbox version
5.0.20

### Vagrantfile
https://gist.github.com/erikfercak/ebb1f6b9375edc4889b3a0d78c976476#file-vagrantfile

### Debug output
https://gist.github.com/erikfercak/ebb1f6b9375edc4889b3a0d78c976476#file-vagrant-up-debug

### Expected behavior
Vagrant should download box via scp protocol.

### Actual behavior
Got an error message `Protocol "scp" not supported or disabled in libcurl`

### Steps to reproduce
1. Create an empty dir
2. Copy the Vagrantfile from gits into it
3. Run `vagrant up`

### References
I've tried to follow http://chase-seibert.github.io/blog/2014/05/18/vagrant-authenticated-private-box-urls.html but without success. Vagrant uses embedded curl:
```
$ /opt/vagrant/embedded/bin/curl -V
curl 7.45.0 (x86_64-apple-darwin12.6.0) libcurl/7.45.0 OpenSSL/1.0.2d zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

**Comment by erikfercak** [comment]
Any progress with the issue?

**Comment by chrisroberts** [comment]
@erikfercak this will be resolved in the next release. thanks!
