### ISSUE TITLE
ansible_local: `playbook` does not exist on the guest: /vagrant/dev.yml

### ISSUE THREAD

**Issue by DmitryRomanenko** [mitchellh/vagrant#7463]
### Vagrant version
Vagrant 1.8.4

### Host operating system
Windows 10

### Guest operating system
Box `ubuntu/xenial64` is up to date.
That's the latest LTS version of most popular Linux distro.

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "dev.yml"
  end
end
```

### Debug output
https://gist.github.com/DmitryRomanenko/ce4c70a75aa0c782c45f36bc74b9f052

### Expected behavior
`dev.yml` is executed (near `Vagrantfile`)

### Actual behavior
``` `playbook` does not exist on the guest: /vagrant/dev.yml ```

### Steps to reproduce
1. Create `dev.yml` with any content and `Vagrantfile`
2. `vagrant up`

### References
- https://github.com/mitchellh/vagrant/issues/7155
- https://github.com/mitchellh/vagrant/issues/6740

**Comment by gildegoma** [comment]
@DmitryRomanenko 

I guess you're hitting a bug in this `ubuntu/xenial64` base box. See for instance https://bugs.launchpad.net/cloud-images/+bug/1565985

As you reported in https://github.com/mitchellh/vagrant/issues/6740#issuecomment-226535042, the same steps work fine with an other base box (`geerlingguy/ubuntu1604`).
I haven't catched any specific warning or error in your `vagrant.log` gist, but I'm pretty sure that the `/vagrant` shared directory is not mounted in the failing case.

Can you first please login into the `ubuntu/xenial64` machine (via `vagrant ssh`) and manually verify the presence of `/vagrant/dev.yml` file?

You can also give a try with `ubuntu/trusty64` to compare...

**Comment by DmitryRomanenko** [comment]
Yes, it works with `geerlingguy/ubuntu1604` or `ubuntu/trusty64`

**Comment by gildegoma** [comment]
Closing as this is problem is specific to the current state of `ubuntu/xenial64` and `ubuntu/xenial32` base boxes.

----

The `ansible_local` provisioner assumes that all the required files are available on the guest system, usually by relying a shared directory between the Vagrant host and guest. See also the `provisioning_path` option in https://www.vagrantup.com/docs/provisioning/ansible_local.html.

**Comment by semiosis** [comment]
FYI for anyone interested, I proposed a fix for ubuntu.  You can follow in [the launchpad bug](https://bugs.launchpad.net/cloud-images/+bug/1565985).

**Comment by sethvargo** [comment]
Or you could just use the `bento/ubuntu-16.04` boxes which work much better 99% of the time 😄

**Comment by semiosis** [comment]
The [latest ubuntu xenial box](https://cloud-images.ubuntu.com/xenial/20160907/) fixes this problem.
