### ISSUE TITLE
Problems with upgrading to 1.8.4

### ISSUE THREAD

**Issue by Shelob9** [mitchellh/vagrant#7464]
### Vagrant version
1.8.1

### Host operating system
Ubuntu 16.04 

### Guest operating system
n/a

### Vagrantfile
n/a

### Expected behavior
Install version 1.8.4

### Actual behavior
Installing using apt-get installed 1.8.1, not 1.8.4

Ubuntu's installer does not work with the package that is downloaded from the site, no error given. GDepi provides error `Error: Wrong architecture 'amd64'` Made me think I had wrong file, but it is the file `vagrant_1.8.4_x86_64.deb`

### Steps to reproduce
`sudo apt-get install vagrant` this installs 1.8.1 not 1.8.4

or

Download `https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb`

### References
n/a

**Comment by sethvargo** [comment]
Hi @Shelob9 

Thank you for opening an issue. We do not maintain the apt/yum repositories, so I cannot comment on their accuracy.

Are you running a 32-bit version of Ubuntu 16.04 or are you already in a virtualized environment? If you could run the following commands and share the output, it would be greatly appreciated:

```
curl -o vagrant.deb https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_x86_64.deb
sudo dpkg -i vagrant.deb
```

**Comment by Shelob9** [comment]
@sethvargo 

I am using a 32-bit version of Ubuntu 16.04 as my host OS. I do not yet have a virtualized environment built. 

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 72.7M  100 72.7M    0     0  2685k      0  0:00:27  0:00:27 --:--:-- 2600k
```

**Comment by sethvargo** [comment]
Hi @Shelob9 

If you are using 32-bit ubuntu, you need to download the 32-bit package:

    https://releases.hashicorp.com/vagrant/1.8.4/vagrant_1.8.4_i686.deb

Please let me know if you have any questions.

**Comment by Shelob9** [comment]
Ooops. Didn't realize I was on the 32bit version until you had me look.
Sorry for the derpie issue.

--
JoshPress.net <http://joshpress.net/>
CalderaWP.com <http://calderawp.com/>
IngotHQ.com
@Josh412 <http://twitter.com/Josh412>
