### ISSUE TITLE
Fusion plugin 4.0.9 fails to mount HGFS.

### ISSUE THREAD

**Issue by ksquaredkey** [mitchellh/vagrant#7468]
### Vagrant version

key@Ogg vm (develop *%=)]$ vagrant -v
Vagrant 1.8.4
[key@Ogg vm (develop *%=)]$ vagrant plugin list
vagrant-cachier (1.2.1)
vagrant-share (1.1.5, system)
vagrant-vmware-fusion (4.0.9)

VMware Fusion 8.1.1

### Host operating system
OS X 10.11.5

### Guest operating system
CentOS 6.6.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?("vagrant-cachier")
    # if you've done a `vagrant plugin install vagrant-cachier`,
    #  your Yum fetches will be cached across provisioning
    config.cache.scope = :box
  end

  #
  # Bump our VM capabilities to run all this crap.
  #
  config.vm.box = "centos-6.6-minimal-81"
  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  #
  # This probably has to match values in cortext.cfg
  #
  config.vm.hostname = "vm.dev"

end
```
### Debug output
https://gist.github.com/ksquaredkey/bab346f0242ae347433de495242a56bf

### Expected behavior
The HGFS should mount /vagrant

### Actual behavior
It errors out with the command:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

vmhgfs-fuse -o uid=`id -u vagrant`,gid=500,allow_other '.host:/-vagrant' /vagrant
```

When I manually attempt the command, vmhgfs-fuse returns with status code 255.

### Steps to reproduce
1. Build a CentOS 6.6 Basebox (don't forget to clear out /etc/udev/rules.d/70network) using VMware Fusion 8.1.1, install vmware-tools from VMware.  (I have built these baseboxes under Fusion 8.0/fusion plugin 4.0.4 successfully, as well as under Fusion 7.x, last December.
2. Use my vanilla Vagrantfile above.
3. Vagrant Up

### References
My original problem was similar to:

  https://github.com/mitchellh/vagrant/issues/6775
  https://github.com/boxcutter/ubuntu/issues/48

Describes the issue I was having with my original Fusion 8.0 Basebox, Vagrant 1.8.1, Fusion Plugin 4.0.4.  As a result of that thread, I updated to Vagrant 1.8.4, plugin 4.0.9 and I went from having to rebuild HGFS to being dead in the water. (I use a much more complex Vagrantfile that leverages HGFS for our build/test environment - this simple Vagrantfile is replicates the problem without the cruft.

My current problem sounds identical to:

  https://github.com/wplib/wplib-box/issues/98

**Comment by ksquaredkey** [comment]
was able to uninstall the 4.0.9 and install the 4.0.8, add the automatic build of kernel modules to my basebox, and I'm moving forward.  Would be nice to be able to use future versions of the fusion plugin in this environment.

**Comment by mnatter** [comment]
Also experiencing this same vagrant-vmware-fusion 4.0.9 issue with centos 7.1/7.2 box (e.g. bento/centos-7.2), using VMware Fusion 7.1.3 and vagrant 1.8.4

**Comment by petercelentano** [comment]
I am also experiencing this issue across both centos 6 and centos 7 under ubuntu 1404 and centos 6 hosts. Using vagrant 1.8.1 and vagrant provider version 4.0.9

**Comment by sethvargo** [comment]
Let's track https://github.com/mitchellh/vagrant/issues/7381 please. Thanks!
