### ISSUE TITLE
Do Vagrant Push (FTP) Pushes All Files Or Only Modified Files?

### ISSUE THREAD

**Issue by otjutt** [mitchellh/vagrant#7471]
I'm not sure if I should be asking this question here. If I do not have SSH access to the server and I've to modify and push a huge site to the server via FTP then do `vagrant push` will push the whole directory (recursively) or just the modified files (recursively) in the directory?

**Comment by sethvargo** [comment]
Hi @otjutt 

It pushes the whole directory, recursively. Thanks!
