### ISSUE TITLE
Ubuntu short hostname is now set to full value of config.vm.hostname instead of first segment 

### ISSUE THREAD

**Issue by erhudy** [mitchellh/vagrant#7488]
### Vagrant version
1.8.4

### Host operating system
OS X 10.11

### Guest operating system
Linux (Ubuntu, 14.04)

### Vagrantfile
Vagrantfile is pretty long, please see: https://github.com/bloomberg/chef-bcpc/blob/master/bootstrap/vagrant_scripts/Vagrantfile

### Expected behavior
The expected behavior is what happens in Vagrant 1.8.1 and prior: if `config.vm.name` is set to something like **blah.example.com**, `hostname` in the VM should return **blah** and `hostname -f` should return **blah.example.com**.

### Actual behavior
Vagrant 1.8.4 (maybe 1.8.3 as well, not sure when the hostname stuff was refactored) will return **blah.example.com** for both `hostname` and `hostname -f` on Trusty guests, which breaks various things that expect the system hostname to not include the domain.

### Steps to reproduce
1. `vagrant init ubuntu/trusty64`
2. Set `config.vm.hostname` to some value that includes a domain name.
3. Launch VM and check the outputs of `hostname` and `hostname -f`.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
- I encountered the issue when working on https://github.com/bloomberg/chef-bcpc/pull/1000 after upgrading from Vagrant 1.8.1 to Vagrant 1.8.4. After seeing the FQDN appearing in unexpected places, I built the same branch again after reverting to 1.8.1 and did not encounter the problem.

**Comment by sethvargo** [comment]
Hi @erhudy 

Thank you for opening an issue on this, and I'm sorry it's causing you problems. The situation you describe seems to be the opposite of what some other users had requested. `hostname -s` should give you the short hostname, but most of the documentation I'm reading on the Internet indicates that the hostname should be set to the FQDN, not the short name.

**Comment by erhudy** [comment]
I see. I've always expected that `hostname` and `hostname -s` should return the same thing, i.e. the unique name of the system itself without the domain attached. We've always passed the FQDN as the value of `config.vm.hostname`. Modifying the application's behavior to explicitly seek out the short hostname is not really feasible since it's OpenStack, so I guess we will have to change our Vagrantfile to only set the short hostname and leave the domain off.

**Comment by sethvargo** [comment]
Hi @erhudy 

I'm going to do some research to figure out what the best approach is here. There's a lot of conflicting information about what a "hostname" should actually contain, so stay tuned.

**Comment by erhudy** [comment]
Got it, thanks.

**Comment by mihalis68** [comment]
I work with @erhudy ...

At least on Ubuntu, hostname is defined as returning the result of gethostname(2).

```
man 2 gethostname 
```

reveals that it will return a string up to 64 bytes, which is a big hint that it is the short name and not the FQDN, since the part before the first . in an FQDN can be up to 63 octets (FQDNs can be up to 255 octets).

Or to put it another way, some FQDNs are too long to be returned by hostname, for example if I were to make a VM in this domain  http://3.141592653589793238462643383279502884197169399375105820974944592.com

**Comment by sethvargo** [comment]
I will be _really_ impressed if you manually typed out that many digits of PI, just sayin'.

And yea - for debian/ubuntu, it seems that way. But for darwin, it seems like scutil wants the full fqdn.
