### ISSUE TITLE
VMWare plugin issue after upgrading to 1.8.4

### ISSUE THREAD

**Issue by themccallister** [mitchellh/vagrant#7494]
I recently upgraded vagrant from 1.7.4 (I believe) to 1.8.4. When trying to set the 

### Vagrant version
1.8.4

### Host operating system
OS X 10.11.5

### Guest operating system
Any

### Vagrantfile
N/A

### Debug output
https://gist.github.com/themccallister/c9259775e1b29757df32aac343990d0b

### Expected behavior
I can use the Vagrant command line tool.

### Actual behavior

> Vagrant output the following messsage after upgrading 
> An unexpected error occurred while loading the Vagrant VMware
> provider. Please contact support with the following
> error code: '7'.
> Vagrant failed to initialize at a very early stage:
> 
> The plugins failed to load properly. The error message given is
> shown below.
> 
> exit

### Steps to reproduce
1. Upgrade vagrant with VMWare fusion plugin?

**Comment by sethvargo** [comment]
Hi @themccallister 

This is a known issue, and unfortunately there's nothing we can do to prevent it. The fortunate thing is that there's an easy solution: uninstall and re-install the plugin:

```
$ vagrant plugin uninstall vagrant-vmware-fusion
$ vagrant plugin install vagrant-vmware-fusion
```

Please confirm that fixes your issue, and sorry about that!

**Comment by themccallister** [comment]
That did the trick, thank you very much!
