### ISSUE TITLE
Vagrant box from vmx created by Packer

### ISSUE THREAD

**Issue by DriveU** [mitchellh/vagrant#7497]
My issue is related to some customization.
Packer image created for Windows has some customizations which are totally post process meaning some custom files need to be dropped in the output folder and are referenced in the resulting vmx file.
After this the vmx file is used to create vagrant box but those custom files also should reflect in the Vagrant box and that is obviously not happening its a gray area for me too. 
So does anyone out here know how to manage this scenario that the vagrant box reflects meaning includes those custom files too when it builds the box?.

**Comment by sethvargo** [comment]
Hi @DriveU ,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄

**Comment by LukB4ULeap** [comment]
Sorry about this
