### ISSUE TITLE
How could I change the R software version in Vagrant?

### ISSUE THREAD

**Issue by s18692001** [mitchellh/vagrant#7498]
Hi there,

How could I change the R software version in Vagrant? After I google it, I really cannot find any answer for it.

Thanks!

Simon

**Comment by sethvargo** [comment]
Hi @s18692001 

Vagrant does not package R (assuming you mean the statistical software). You will likely need to use a [shell provisioner](https://www.vagrantup.com/docs/provisioning/shell.html) to install and manage that software.

The best place to get answers to these types of questions is on the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up).

**Comment by s18692001** [comment]
Hi,

I install Vagrant in Ubuntu following this manual :
https://github.com/tesseradata/install-vagrant
I already have R software in this Vagrant VM, but I want to change it to
the older one. How could I change it?

Simon

**Comment by s18692001** [comment]
Hi,

Sorry I'm new in this field.
How could I change a default version of R in Vagrant? I does install the
version I want in Vagrant.
When I input "R" in the Vagrant terminal, it's still not the version I need.


Thanks!
