### ISSUE TITLE
Support ~/.netrc for downloading boxes

### ISSUE THREAD

**Issue by stardust85** [mitchellh/vagrant#7500]
### Vagrant version
Vagrant 1.8.4

### Host operating system
Windows 7

### Guest operating system
any

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
 config.vm.box = "secret.box"
 config.vm.box_url =  "https://nonpublic.example.com/secret.box"
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Expected behavior
box downloads

### Actual behavior
401 Authentication required

### References
- Issue #4889

**Comment by sethvargo** [comment]
Hi @stardust85 

Thank you for opening an issue. Unfortunately we can't do this. You can read more in https://github.com/mitchellh/vagrant/issues/4889, which I see you already commented on, but we cannot allow arbitrary things in the netrc and curlrc files. You can configure proxy information directly in the Vagrantfile. If there are specific options you need us to support, please open a new issue and we will be happy to add that! Thanks! 😄
