### ISSUE TITLE
box-version is invalid option for vagrant init

### ISSUE THREAD

**Issue by chriscressman** [mitchellh/vagrant#7502]
### Vagrant version
Vagrant 1.8.1

### Host operating system
OS X El Capitan 10.11.4 (15E65)

### Expected behavior
According to the [online documentation for `vagrant init`](https://www.vagrantup.com/docs/cli/init.html), providing the `--box-version` option will add the specified version constraint to the Vagrantfile that is produced.

### Actual behavior
`--box-version` is an invalid option:

```
$ vagrant init --box-version '> 0.1.5' hashcorp/precise64
An invalid option was specified. The help for this command
is available below.

Usage: vagrant init [options] [name [url]]

Options:

    -f, --force                      Overwrite existing Vagrantfile
    -m, --minimal                    Create minimal Vagrantfile (no help comments)
        --output FILE                Output path for the box. '-' for stdout
    -h, --help                       Print this help
```

Either the option is unavailable due to a bug, or it was removed and the online documentation is out of date. If the option was removed, any insight into the reason? Any chance of restoring it?

**Comment by sethvargo** [comment]
Hi @chriscressman 

The documentation corresponds to the latest version of Vagrant (1.8.4). That particular option was added in 1.8.3. You need to upgrade to get the option. Thanks! 😄
