### ISSUE TITLE
`vagrant box remove` command does not accept range in 'box-version' parameter

### ISSUE THREAD

**Issue by VladRassokhin** [mitchellh/vagrant#7503]
### Vagrant version
`Vagrant 1.8.4`

### Host operating system
```
$ uname -a
Linux unit-421 4.6.2-gentoo #1 SMP Thu Jun 16 16:22:10 MSK 2016 x86_64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz GenuineIntel GNU/Linux
```

### Guest operating system
Non-applicable

### Vagrantfile
Non-applicable

### Debug output
[Gist with both simple and debug output](https://gist.github.com/VladRassokhin/91774e62c8f2a76a913d557deacd1a90)

### Expected behavior
Remove all boxes within specified range (all except latest)

### Actual behavior
Error output, nothing changed:

### Steps to reproduce
1. Have some history of updating outdated boxes
2. Try to remove them all-at-once with e.g. `vagrant box remove ubuntu/trusty64 --box-version '< 20160602.0.0'`

### References
N/A

**Comment by VladRassokhin** [comment]
There's simple workaround: `vagrant box list | grep ubuntu/trusty64 | awk '{print $3}' | sed 's/)$//' | grep -v 20160602 | xargs -n 1 vagrant box remove ubuntu/trusty64 --box-version`

**Comment by sethvargo** [comment]
Im gonna close this as it's closely related to https://github.com/mitchellh/vagrant/issues/4412.
