### ISSUE TITLE
Feature Request: Vagrant Unprovision

### ISSUE THREAD

**Issue by jimcurtis** [mitchellh/vagrant#7509]
I would like to request a Vagrant unprovision command that would run the unprovisioner specified in the Vangrantfile.  This would allow me to spin up a cluster of VMs with vagrant up and then I could leave the VMs up and instead of doing vagrant destroy, which destroys my VMs, I could do vagrant unprovision which would take my VMs back to the state they were before they were provisioned.

Many cluster-related ansible playbooks have a purge or delete cluster playbook that would be specified as the unprovisioner in the Vagrantfile.

**Comment by sethvargo** [comment]
Hi @jimcurtis 

You can use `vagrant snapshot` for this. "Undoing" a provision is really impossible, so you need to snapshot the VM before provisioning and then rollback.
