### ISSUE TITLE
Vagrant up hangs when using smb

### ISSUE THREAD

**Issue by Dimasdanz** [mitchellh/vagrant#7511]
`vagrant up` stuck when using synced folder type: smb on Windows 10 preview build 14367
It just hangs, not even exiting. Need to terminate manually with `ctrl+c`
The debug output just ended at powershell command

```
PS C:\Users\dimas\Scripts\Vagrant\ubuntu-xenial> 
```

Above is the last line on debug output even after waiting for hours.
### Vagrant version

1.8.4  
### Host operating system

Windows 10 Pro Insider Preview build 14367
### Guest operating system

Ubuntu 16.04 (ubuntu/xenial64)
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.synced_folder ".", "/vagrant", type: "smb"
end
```
### Debug output

[https://gist.github.com/Dimasdanz/776bc4c97b109f2adee587ceb852ed90](https://gist.github.com/Dimasdanz/776bc4c97b109f2adee587ceb852ed90)
### Expected behavior

Does not hang ;)
### Actual behavior

Just hangs, not even exiting. 
### Steps to reproduce
1. Just run vagrant up with smb setting

**Comment by aodhom** [comment]
:+1: exact same issue. Can't destroy either. 

I have to kill the Ruby processes. then remove smb as the folder mount type.

**Comment by Dimasdanz** [comment]
##### Additional info
It works on latest stable of Windows build 10586.420
##### Powershell version
Major | Minor | Build | Revision
---|---|---|---
5 | 0 | 10586 | 122
##### Debug output:
[https://gist.github.com/Dimasdanz/d18a0b28570fd18082c725f5ebf8329f](https://gist.github.com/Dimasdanz/d18a0b28570fd18082c725f5ebf8329f)
*I am aware of the exposed smb credential. It's okay, just local account ;)

The not working PowerShell version:

Major | Minor | Build | Revision
---|---|---|---
5 | 1 | 14367 | 0

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Comment by ldjamison** [comment]
Hello! I can open a new issue if you would prefer, but this hanging problem is plaguing me currently. I am trying to use debian/jessie64 on a Windows 7 Professional 64-bit host running Vagrant 1.9.5

**Comment by Inkering** [comment]
I'm also experiencing this error when running "vagrant up --provider=hyperv" after running "vagrant init debian/jessie64".

**Comment by mistermoses** [comment]
I'm experiencing this issue right now with a CentOS 6 x64 guest on Windows 10 64-bit host, Vagrant 2.0.2.

**Comment by pazoozooCH** [comment]
Can confirm that it's still an issue - VM starts up successfully, but quite soon, it starts hanging when trying to change the directory to the shared folder (cd /vagrant).
