### ISSUE TITLE
vagrant calling "C:\\Program Files\\Git\\usr\\bin/ssh.EXE" on windows 10

### ISSUE THREAD

**Issue by mimo-lukacka** [mitchellh/vagrant#7512]
Vagrant version 1.8.4, VM version 5.0.22, windows 10
### Vagrantfile

``` ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.gui = true
    vb.cpus = 2
  end


  config.vm.network :private_network, type: "dhcp"
  config.vbguest.auto_update = false

  config.ssh.insert_key = false

  config.vm.provision :shell, path: "bootstrap.sh"

end
```

When I do vagrant up, VM starts properly, but Vagrant is unable to connect. All it says is Warning: Remote connection disconnect. Retrying... When I try to connect via vagrant ssh, I get only ssh_exchange_identification: read: Connection reset by peer. 

I went to vagrant ssh --debug and found out that vagrant is trying to call command "C:\Program Files\Git\usr\bin/ssh.EXE", which doesn't exist, and then fail and time out. Followed by another unsuccessful call fo the command with wrong path.

I believe this is a bug.

**Comment by sethvargo** [comment]
Hi @mimo-lukacka 

You need an SSH client installed to connect to a linux-based VM on Vagrant. Do you have git-bash or cygwin installed?

**Comment by mimo-lukacka** [comment]
I have installed both git-bash and cygwin, also placed them in the PATH correctly. But Vagrant is obviously calling the wrong path, so the command is not run. When I go to --debug mode, vagrant is cycling on failing to execute this command.

**Comment by sethvargo** [comment]
Ah, so it's a path slash issue 😦 . Tagging

**Comment by mimo-lukacka** [comment]
@sethvargo can you maybe guide me to a place where could I simply fix the path slash issue? It's very minor bug and I need vagrant to work asap :/

**Comment by sethvargo** [comment]
@mimo-lukacka I have absolutely no idea, sorry. It's probably much deeper in the tubes of Vagrant than a "quick fix" as it may appear.

**Comment by r2qokk** [comment]
I cannot reproduce the issue with Vagrant 1.8.4, and VirtualBox 5.0.26 in Windows 10 64 bit.
However, the situation happens with Vagrant 1.8.5, and VirtualBox 5.1.2 with me.

**Comment by dragon788** [comment]
@mimo-lukacka If you can find references to the ssh.exe in the code you may be able to verify whether they are using the library that helps with pathing (which means the slashes WON'T matter) or if they accidentally hardcoded a path somewhere. Also, if you run `vagrant plugin list` do you have any other plugins installed that are working with paths?

**Comment by chrisroberts** [comment]
@mimo-lukacka Can you provide gists of debug logs showing this behavior on latest version of Vagrant?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by Bergur1** [comment]
Latest stable version of vagrant and git bash on windows. This is still happening! I'll open an issue when I have the time.
