### ISSUE TITLE
smb-password input not hidden

### ISSUE THREAD

**Issue by redshark1802** [mitchellh/vagrant#7513]
### Vagrant version
1.8.4

### Host operating system
windows 7

### Git bash
2.9.0

### Vagrantfile
```ruby
# only the mount-options could be relevant at this point
...   
config.vm.synced_folder "./", "/vagrant", id: "vagrant-root", type: "smb", :mount_options => ['mfsymlinks,nobrl,file_mode=0775,dir_mode=0775,gid=33']
...   
```
### Expected behavior
The password should be hidden when entering the samba-password.

### Actual behavior
The password is displayed when entering the samba-password.

### Steps to reproduce
1. Install vagrant 1.8.4 on windows 7
2. Install git bash 2.9.0
3. create a minimal vagrantfile with samba mount-option

**Comment by sethvargo** [comment]
Hi @redshark1802 

Thank you for opening an issue. Can you please elaborate a bit more on what is happening? What output do you see? What command are you running?

**Comment by redshark1802** [comment]
git bash 1.9.5 the password is hidden:   
![expected](https://cloud.githubusercontent.com/assets/321631/16336610/19e8d56a-3a0f-11e6-9a8e-6f7bc7c9d5cb.png)

git bash 2.9.0 the password is shown:   
![result](https://cloud.githubusercontent.com/assets/321631/16336631/2d41c978-3a0f-11e6-9cf3-157e049596af.png)

**Comment by sethvargo** [comment]
Hi @redshark1802 

Thank you for that. As you can see directly above, git bash 2.9.0 does not appear to support hiding input. There is nothing Vagrant can do here; the stdin pipe doesn't support masking. This could be a bug in git bash or an intentional breakage. This is not a bug in Vagrant. Sorry!
