### ISSUE TITLE
Provisioning CentOS 7 fail on Settings hostname / configuring network interfaces

### ISSUE THREAD

**Issue by jvanbrunschot-coolblue** [mitchellh/vagrant#7514]
Hi, 

Since updating to the latest version of Vagrant we notice the following issue. It happens when provisioning a new box (vagrant up). It looks like it can't configure network interfaces.

It worked on version =< 1.8.1

### Vagrant version
1.8.4

### Host operating system
Mac OS 10.11.3 (El Capitan)

### Guest operating system
Centos 7 (http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-Vagrant-1505-x86_64-01.box)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos7"
  config.vm.box_url = 'http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-Vagrant-1505-x86_64-01.box'
  config.vm.network "private_network", ip: '192.168.33.11'
  config.vm.hostname = "base-centos-7.vm"
end
```

This is a cleaner version of our Vagrantfile but it's failing on one of the config.vm.network or hostname lines.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://gist.github.com/jvanbrunschot-coolblue/472dd1badcddcb65eba8b099100c27e0

### Expected behavior
Adding a network interface

### Actual behavior
Provisioning stopped because of:
Job for network.service failed. See 'systemctl status network.service' and 'journalctl -xn' for details.

### Steps to reproduce
1. Download the box
2. Use the Vagrantfile to provision the box

**Comment by sethvargo** [comment]
Hi @jvanbrunschot-coolblue 

Thank you for opening an issue. What does `systemctl status network.service` contain?

```
Job for network.service failed. See 'systemctl status network.service' and 'journalctl -xn' for details.
```

It's possible this is a box bug - can you try `bento/centos-7.1`?

**Comment by jvanbrunschot-coolblue** [comment]
Hi systemctl contains the following:
```
[vagrant@base-centos-7 ~]$ systemctl status network.service
network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network)
   Active: failed (Result: exit-code) since Fri 2016-06-24 04:12:23 EDT; 30s ago
  Process: 8120 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=1/FAILURE)
```

I've tried bento/centos-7.1 and that seems to work. Probably something with the network configuration inside in the box.

**Comment by sethvargo** [comment]
Going to close as a box issue. If this becomes a more general issue, we can look into a fix in Vagrant.

**Comment by bendikro** [comment]
I encountered this issue and the problem was that the box had been provisioned with
`config.vm.network "private_network", type: "dhcp"` and then repackaged to a new box so that the VM contained two configured interfaces. When using the repackaged box later on with a Vagrantfile without any network configuration, the `network.service` service fails because virtualbox only provides one network card to the VM.

So setting the hostname only makes this error visible to the user during provisioning, but wasn't caused by the `change_host_name.rb` code.
