### ISSUE TITLE
Installing plugin from local gem package fails

### ISSUE THREAD

**Issue by fnordfish** [mitchellh/vagrant#7515]
While trying to debug #7495 I ran into this:

```
$ vagrant plugin install ~/vagrant_projects/plugin_dev/vagrant-dns/pkg/vagrant-dns-1.0.1.pre0.gem --plugin-clean-sources
Installing the '/Users/robertschulze/vagrant_projects/plugin_dev/vagrant-dns/pkg/vagrant-dns-1.0.1.pre0.gem' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not find gem 'vagrant-dns (= 1.0.1.pre0)' in any of the gem sources listed in your Gemfile or available on this machine.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
```

(this was run inside my normal vagrant binary installation, not a plugin development environment)

Looking at `~/.vagrant.d/gems/gems`, the gem and it's dependencies have been installed. But `~/.vagrant.d/plugins.json` does not contain it.

Debug log is at: https://gist.github.com/fnordfish/de3a69271541d083311e190ce63cf66c

**Comment by 141984** [comment]
getting the same issue

**Comment by jarrettchisholm** [comment]
Same issue here.

Some people in our office upgraded to 1.8.4, and suddenly installing their custom plugin (via a .gem file) fails.

Downgrading to 1.8.1 is a workaround for the issue.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/7493

**Comment by fnordfish** [comment]
Sorry for the double post. I've did a quick search and didn't find it.
