### ISSUE TITLE
Support sdl and seperate type

### ISSUE THREAD

**Issue by shibumi** [mitchellh/vagrant#7520]
Hello,
I wanted to start my virtualbox VM with VboxSDL.
So I have tried the following in the Vagrantfile:
```
vb.customize ["startvm", :id, "--type", "sdl"]
```
It's working now but when I up it I get the following error:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "18c27466-9ae8-4c3e-97d1-1513b6fbd5e0", "--type", "gui"]

Stderr: VBoxManage: error: The machine 'chris_win10_1466717201737_33256' is already locked by a session (or being locked or unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 589 of file VBoxManageMisc.cpp
```
The problem is: vb.gui. I will always get this because vb.gui can only be true or false. So it can just be "gui" or "headless"...

Why do you use a boolean value there? it would be easier to go with vboxmanage and use different types:
```
Oracle VM VirtualBox Command Line Management Interface Version 5.0.22_OSE
(C) 2005-2016 Oracle Corporation
All rights reserved.

Usage:

VBoxManage startvm          <uuid|vmname>...
                            [--type gui|sdl|headless|separate]


Syntax error: unknown option: --help
```
So I guess that seperate is also not supported?

**Comment by sethvargo** [comment]
Hi @shibumi 

I'm not familiar with sdl, but it sounds like a relatively new addition to VirtualBox. Vagrant is a developer tool designed to mask the idiosyncrasies in working directly with VirtualBox. Additionally, from the VirtualBox documentation:

> VBoxSDL is a simple graphical user interface (GUI) that lacks the nice point-and-click support which VirtualBox, our main GUI, provides. VBoxSDL is **currently primarily used internally for debugging VirtualBox and therefore not officially supported.** Still, you may find it useful for environments where the virtual machines are not necessarily controlled by the same person that uses the virtual machine. - [regfs](http://www.virtualbox.org/manual/ch09.html#vboxsdl)

I think we would gladly review a pull request that adding a new `type` option which allowed the user to specify this as an advanced option, but Vagrant's backwards-compatibility promise says that we cannot remove or deprecate the `gui` option until Vagrant 2.0.

Please let me know if you have any questions.

**Comment by shibumi** [comment]
@sethvargo And what about the 4th mode `seperate`?

**Comment by sethvargo** [comment]
> Starts a VM with detachable UI (technically it is a headless VM with user interface in a separate process). This is an experimental feature as it lacks certain functionality at the moment (e.g. 3D acceleration will not work).

The only two officially-supported options are `gui` and `headless`.

**Comment by jamesla** [comment]
+1
