### ISSUE TITLE
No digital signature for 1.8.3 or 1.8.4 Windows installer files

### ISSUE THREAD

**Issue by jeremyn** [mitchellh/vagrant#7522]
The `vagrant_1.8.3.msi` and `vagrant_1.8.4.msi` Windows installer files don't seem to have valid digital signatures. The SHA256 hashes for these files match your GPG-signed hash files. `vagrant_1.8.1.msi` does have a valid signature. The certificate for the 1.8.1 file says "Valid from 13-Feb-14 to 18-Apr-16". 1.8.1 was released in December 2015 and 1.8.3 and 1.8.4 were released in June 2016. Maybe your certificate has expired?

### Vagrant version
| File | SHA256 |
| ---- | ------ |
| `vagrant_1.8.3.msi` | ABF9FB6334816929935C9CCA2A6C7E39F6A98A90EC9F68692155621A99C03628 |
| `vagrant_1.8.4.msi` | 0202C3FF87FAAD36E33BC2808C42CE15EDF70187A375219FFF92875DA836371C |

### Host operating system
Windows 10.

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
The "Open File - Security Warning" box presented when running these files reports "Publisher: HashiCorp, Inc." with a clickable link to the signature, as in `vagrant_1.8.1.msi`.

### Actual behavior
The warning box reports "Publisher: Unknown Publisher".

### Steps to reproduce
Try to run either the 1.8.3 or 1.8.4 installer file.

### References
None.

**Comment by jeremyn** [comment]
Same problem with `vagrant_1.8.5.msi`:

| File | SHA256 |
| ---- | ------ |
| `vagrant_1.8.5.msi` | 28F30F1782B4AD790CD34544B762EE15DBDFB27807CBA91F6197529CDF8E43FE |

@sethvargo , I see you gave this issue a "bug" label. Does that mean you acknowledge this is a bug on your end? I'd like to confirm that this is expected, if undesired, behavior.

**Comment by jeremyn** [comment]
Also, a more reliable way to confirm the problem is to right-click the downloaded file, select "Properties", and observe the lack of a "Digital Signatures" tab. The "Open File - Security Warning" box may not appear depending on stuff external to the file itself such as system policy and how you received the file.

**Comment by chrisroberts** [comment]
Fixed as of 1.8.6. Thanks for the report!

**Comment by jeremyn** [comment]
Fix confirmed, thanks.
