### ISSUE TITLE
Vagrant multiple puppet master VM: NoMethod Error

### ISSUE THREAD

**Issue by arunsingh** [mitchellh/vagrant#7523]
### Vagrant version
1.8.4

### Host operating system
OSX

### Guest operating system
Debian Wheezy

### Vagrantfile
```ruby
nodes_config = (JSON.parse(File.read("nodes.json")))['nodes']

Vagrant.configure("2") do |config|
  config.vm.box = "debian/wheezy64"

  nodes_config.each do |node|
    node_name   = node[0] # name of node
    node_values = node[1] # content of node

    config.vm.define node_name do |config|
      # configures all forwarding ports in JSON array
      ports = node_values['ports']
      ports.each do |port|
        config.vm.network :forwarded_port,
          host:  port[':host'],
          guest: port[':guest'],
          id:    port[':id']
      end

      config.vm.hostname = node_name
      config.vm.network :private_network, ip: node_values[':ip']

      config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", node_values[':memory']]
        vb.customize ["modifyvm", :id, "--name", node_name]
      end

      config.vm.provision :shell, :path => node_values[':bootstrap']
    end
  end
end
```

### Debug output

$ VAGRANT_LOG=info vagrant up: http://paste.ubuntu.com/17965656/ 

https://gist.github.com/arunsingh/673d35ab9ead39c75bc24aebd1eb37fc

https://gist.github.com/arunsingh/eb11vi5e7f2d713f0dec217249be232c3a

### Expected behavior
What should have happened? 

-Using this https://github.com/arunsingh/multi-vagrant-puppet-vms/ I am trying to set up puppet master on debian wheezy environment, I am unable to get the error message, how to start debug by reading error when i do "vagrant up" / "vagrant ssh" 

-Puppet master and 2 nodes must have started

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-4467
- GH-4421

**Comment by sethvargo** [comment]
Hi @arunsingh 

Can you please uninstall all non-core plugins and see if this issue reproduces? For reference, you have the following plugins installed:

- vagrant-hosts
- vagrant-vbguest

You can uninstall these plugins by running:

```
$ vagrant plugin uninstall vagrant-hosts
$ vagrant plugin uninstall vagrant-vbguest
```

**Comment by arunsingh** [comment]
@sethvargo Thanks for the quick suggestion, I uninstalled the plugins. See this : http://paste.ubuntu.com/17972879/  still same problem persists. I guess error is due to provisioning machine.

**Comment by sethvargo** [comment]
Hi @arunsingh 

Can you please run in [debug mode](https://www.vagrantup.com/docs/other/debugging.html) and gist that output? You've only supplied info thus far.

**Comment by arunsingh** [comment]
Hello @sethvargo , find the debug mode info in gist here https://gist.github.com/arunsingh/caa8089c8f32ed517256e9a99bbfb622

**Comment by sethvargo** [comment]
Ah - what is in `/Users/aruns/vagrant_deb_wheezyenv/Vagrantfile`? Can you pate the contents of that please?

**Comment by arunsingh** [comment]
See this https://gist.github.com/arunsingh/8c534947ae0b668324724c577416325c , the error I caught was on vagrant.configure line, i was using "VAGRANTFILE_API_v2" which should be VAGRANTFILE_API_v2 without double quotes as it was treating as string rather than passing as an argument.

`VAGRANTFILE_API_v2 = "2"

Vagrant.configure(VAGRANTFILE_API_v2) do |config|`
