### ISSUE TITLE
Vagrant multi-vm configuration destroy is not working as expected

### ISSUE THREAD

**Issue by akamensky** [mitchellh/vagrant#7527]
### Vagrant version
1.8.4

### Host operating system
Mac OS X 10.11.5

### Guest operating system
Centos (any)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "centos7", autostart: false do |centos7|
    config.vm.box = "protodype/centos7"
    config.vm.provision "shell",
      inline: "ln -s /home/vagrant/sync/deleted /usr/bin/deleted"
  end
  config.vm.define "centos6", autostart: false do |centos6|
    config.vm.box = "protodype/centos6"
    config.vm.provision "shell",
      inline: "ln -s /home/vagrant/sync/deleted /usr/bin/deleted"
  end
end
```

### Debug output
Gist is not working in my location, thus here is a link to raw file in temp repo:
https://raw.githubusercontent.com/akamensky/vagrant-bug-report/master/debug.out

### Expected behavior
1. If there are multiple VMs started `vagrant destroy` should destroy all of them
2. If there is only one VM started `vagrant destroy` should destroy it and `vagrant destroy [name]` should also destroy it

### Actual behavior
1. In case of multiple VMs running doing `vagrant destroy` destroys all of them EXCEPT last one in the list showing error as on screenshot
2. In case of single VM running doing either `vagrant destroy` or `vagrant destroy [name]` will show error as on screenshot.

### Steps to reproduce
1. Create mult-vm setup
2. Start all or only one VM
3. Attempt to call either `vagrant destroy` to destroy all, or `vagrant destroy [name]` to destroy one (when only one is running)

### Additional notes
Seems this has something to do with how vagrant will iterate through the list of VMs as in every possible combination the last one always will return the error.

![screen shot 2016-06-28 at 12 58 27 pm](https://cloud.githubusercontent.com/assets/985805/16404563/bb48f4d2-3d32-11e6-80e4-b6b908d2ba66.png)

![screen shot 2016-06-28 at 1 21 30 pm](https://cloud.githubusercontent.com/assets/985805/16404630/5a057eec-3d33-11e6-8534-021b9399d923.png)

**Comment by akamensky** [comment]
### Addition
It actually never destroys when specify box name:

![screen shot 2016-06-28 at 1 27 31 pm](https://cloud.githubusercontent.com/assets/985805/16404734/30c18fc0-3d34-11e6-88a8-d5b9bf68c5ec.png)

**Comment by sethvargo** [comment]
Hi @akamensky 

I think this might be an issue with the way you've setup your Vagrantfile. The `config` block is not scoped, so I think you want something like this:

```ruby
Vagrant.configure(2) do |config|
  config.vm.define "centos7", autostart: false do |centos7|
    centos7.vm.box = "protodype/centos7"
    centos7.vm.provision "shell",
      inline: "ln -s /home/vagrant/sync/deleted /usr/bin/deleted"
  end

  config.vm.define "centos6", autostart: false do |centos6|
    centos6.vm.box = "protodype/centos6"
    centos6.vm.provision "shell",
      inline: "ln -s /home/vagrant/sync/deleted /usr/bin/deleted"
  end
end
```

Can you give that a try and see if that fixes your issue?

**Comment by akamensky** [comment]
Okay, seems this configuration is correct as it _fixes_ both issues.

I would suggest either forbidding to use `config.vm.` inside vm config scope when the VM was aliased to some other name, or expanding documentation by adding:

1 - information on the fact that |name| becomes alias and should be used within this vm config scope 

and

2 - adding sample configuration for multi-vm setup (there is none on this and this configuration was found from the Internet).

**Comment by sethvargo** [comment]
Hi @akamensky 

We can't do that. It's evaluated as Ruby, and `config` exists at the global scope (it's the nature of scopes). There are lots of examples on the Vagrant website on this page: https://www.vagrantup.com/docs/multi-machine/

I'll work on adding more and seeing if there's something we can do to make this clearer.
