### ISSUE TITLE
Vagrant fails to execute when there is a complex LS_COLOR environment variable on Git for Windows

### ISSUE THREAD

**Issue by javier-lopez** [mitchellh/vagrant#7530]
### Affected Vagrant versions

Vagrant 1.8.3
Vagrant 1.8.4
### Non affected Vagrant versions

Vagrant <= 1.8.1
### Host operating system

Windows 10
### Guest operating system

Ubuntu Linux 14.04
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "test"
end
```
### Debug output

https://gist.github.com/chilicuil/07bba4d326878aa295324e47099c887d
### Expected behavior

vagrant -v, vagrant up, etc should work
### Actual behavior

every time vagrant is invoked it returns the posted error about an invalid argument - ruby_setenv(LS_COLORS) (Errno::EINVAL)
### Steps to reproduce
1. Download and install git for windows, https://git-scm.com/download/win
2. Add the following bashrc file to ~/.bashrc
   https://gist.github.com/chilicuil/1ca4d4a378d81c248a2b4f947ccd29ee
3. Start git for windows bash
4. Run vagrant up

**Comment by gzhihao** [comment]
I have the same issue, it works in window command prompt but not in git-bash. Vagrant version 1.8.4

**Comment by briancain** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
