### ISSUE TITLE
Vagrant box started in Windows admin terminal shows as "poweroff" in non-admin terminal

### ISSUE THREAD

**Issue by jeremyn** [mitchellh/vagrant#7534]
On Windows 10, if I'm in an admin PowerShell terminal and run `vagrant up` and then `vagrant status`, it shows the box as `running`. However if I then run `vagrant status` from a non-admin PowerShell terminal, it shows the status as `poweroff`. In other words it is as if the non-admin terminal can't "see" that the box started in the admin terminal is running.

The use case is that I want to sync with `smb`, which requires admin access. I want to start the box in an admin PowerShell terminal and then access the box with `vagrant ssh` in a non-admin Git Bash terminal.

### Vagrant version
1.8.4.

### Host operating system
Windows 10.

### Guest operating system
Any(?), but try [ubuntu/trusty64](https://atlas.hashicorp.com/ubuntu/boxes/trusty64).

### Vagrantfile
Default from `vagrant init ubuntu/trusty64`, using VirtualBox.

### Debug output
Can provide if needed.

### Expected behavior
`vagrant status` in non-admin terminal shows `running` after `vagrant up` in admin terminal.

### Actual behavior
`vagrant status` in non-admin terminal shows `poweroff` after `vagrant up` in admin terminal.

### Steps to reproduce
1. `vagrant init ubuntu/trusty64` in either terminal
2. `vagrant up` in admin terminal
3. `vagrant status` in non-admin terminal

### References
None.

**Comment by sethvargo** [comment]
Hi @jeremyn 

This is the expected behavior. Vagrant cannot query the status of virtualbox as a non-admin unless you are running as privileged or give that user that permission.

**Comment by jeremyn** [comment]
Thanks for the quick response, Seth. Is that what "Start VirtualBox as a normal user or as an administrator will prevent you from using it in the opposite way." in the documentation under Providers > VirtualBox > Common Issues ([link](https://www.vagrantup.com/docs/virtualbox/common-issues.html)) means?

For the specific problem I had of wanting to `vagrant ssh`, is there a way to get that to work from a non-admin terminal to the admin-started box? Would that be a valid enhancement request? I know the box is accessible because `ssh -p 2222 vagrant@127.0.0.1` works.
