### ISSUE TITLE
Getting error '/sbin/ifdown: interface not configured' on vagrant up of trusty64 box

### ISSUE THREAD

**Issue by TrevorScheitrum** [mitchellh/vagrant#7537]
Getting error '/sbin/ifdown: interface not configured' on vagrant up of trusty64 box

### Vagrant version
I get the error on vagrant version 1.8.3 and 1.8.4.
1.8.1 runs fine.

### Host operating system
Both Linux Mint 17.3 and OSX El Capitan 10.11.5 (15F34)

### Guest operating system
Ubuntu 14.04 Trusty64 base box

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box

    config.cache.synced_folder_opts = {
      type: :nfs,
      # The nolock option can be useful for an NFSv3 client that wants to avoid the
      # NLM sideband protocol. Without this option, apt-get might hang if it tries
      # to lock files needed for /var/cache/* operations. All of this can be avoided
      # by using NFSv4 everywhere. Please note that the tcp option is not the default.
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
  end

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 8000, host: 8000
  config.vm.network :forwarded_port, guest: 8080, host: 8081
  config.vm.network :forwarded_port, guest: 8983, host: 18983
  config.vm.network :forwarded_port, guest: 3306, host: 13306
  config.vm.network :forwarded_port, guest: 1080, host: 1080
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 4444, host: 4444

  config.vm.network :private_network, ip: "10.11.12.14"

  # Add NFS
  if (RUBY_PLATFORM =~ /linux/ or RUBY_PLATFORM =~ /darwin/)
    synched_opts = { nfs: true, nfs_udp: false }
    nfs_exports = ["rw", "async", "insecure", "no_subtree_check"]
  
    if (RUBY_PLATFORM =~ /darwin/)
      nfs_exports += ["noac", "actimeo=0", "intr", "noacl", "lookupcache=none"]
      synched_opts[:bsd__nfs_options] = nfs_exports
    elsif (RUBY_PLATFORM =~ /linux/)
      nfs_exports += ["all_squash"]
      synched_opts[:linux__nfs_options] = nfs_exports
    end
  	
    config.vm.synced_folder ".", "/vagrant", synched_opts
    config.nfs.map_uid = Process.uid
    config.nfs.map_gid = Process.gid
  else
    # First, disable default vagrant share
    config.vm.synced_folder ".", "/vagrant", disabled: true
  	
    # Next, setup the shared Vagrant folder manually, bypassing Windows 260 character path limit
    config.vm.provider "virtualbox" do |v|
      v.customize ["sharedfolder", "add", :id, "--name", "vagrant", "--hostpath", (("//?/" + File.dirname(__FILE__)).gsub("/","\\"))]
      v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    end
    
    # Finally, mount the shared folder on the guest system during provision
    config.vm.provision :shell, inline: "mkdir -p /vagrant", run: "always"
    config.vm.provision :shell, inline: "mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant", run: "always"
    
    config.nfs.map_uid = 501
    config.nfs.map_gid = 20
  end
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1736"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.ssh.forward_agent = true
  config.vm.provision :shell, :path => "install.sh"
end

overrides = "#{__FILE__}.local"
if File.exist?(overrides)
   eval File.read(overrides)
end
```

### Debug output
https://gist.github.com/TrevorScheitrum/4a112c972797a32ad9e480297b0c1f7d

### Expected behavior
Vagrant should continue provisioning the box without errors

### Actual behavior
I get the error '/sbin/ifdown: interface not configured' on vagrant up of trusty64 box'

### Steps to reproduce
1. Install Vagrant 1.8.3 or 1.8.4
2. run 'Vagrant up' with the Vagrant file pasted
3. receive provided error.

### References
Yes, i think this is directly related to: the changes for surpressing the ifdown error in the changelog of 1.8.3
https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#183-june-10-2016
line:
"guests/debian: Do not return an error if ifdown fails [GH-7159, GH-7155, GH-6871]"

**Comment by sethvargo** [comment]
Hi @TrevorScheitrum 

The issue appears to be that the guest machine is not reporting its configured interfaces. We have had a ton of problems with the boxes published by canonical under the Ubuntu namespace. Could you please try `bento/ubuntu-14.04` and see if the issue persists please? Sorry about that. Thanks!

**Comment by TrevorScheitrum** [comment]
Hey, thanks for the quick reply! I just reinstalled Vagrant 1.8.4, an edited my vagrantfile like this:

-  config.vm.box = "ubuntu/trusty64"
-  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
+  config.vm.box = "bento/ubuntu-14.04"

and get the same error that i created the issue for.

**Comment by sethvargo** [comment]
Hi @TrevorScheitrum 

When you edited your Vagrantfile, did you destroy and re-create the VM? Could you send along the debug output again please?

**Comment by TrevorScheitrum** [comment]
Yup, just tested now!

On Vagrant 1.8.4, I did:
vagrant destroy
vagrant up

still get the same error i made the ticket about, here's the debug output:
https://gist.github.com/TrevorScheitrum/1ef04d2e62c4337db4e280b0fb63f493

**Comment by mtwentyman** [comment]
Changing https://github.com/mitchellh/vagrant/blob/v1.8.4/plugins/guests/redhat/cap/configure_networks.rb#L39

to

```ruby
            interfaces.push *stdout.split("\n")
```

fixes the issue for me.

**Comment by mtwentyman** [comment]
Ah! @nvwls [beat me to it](https://github.com/mitchellh/vagrant/issues/7539#issuecomment-232179314)
