### ISSUE TITLE
rsync__args cause rsync to not occur, does not cause run to fail

### ISSUE THREAD

**Issue by gravyboat** [mitchellh/vagrant#7541]
### Issue

When using `rsync__args` rsync'ing files does not work, the associated directory on the system is empty. When not using these arguments, all files are copied without issue.

I'll preface the rest of the details by saying that I am using `bundle exec vagrant XYZ` for all commands due to the way the repo is structure. This issue only occurs however if `rsync__args` are provided. If I drop the `rsync__args` values then the machine provisions perfectly fine. From what I see in the debug log there are no errors related to the rsync, the files simply are not being copied. I Have also tried multiple options for `rsync__args` such as simply including `--verbose` to keep things extremely simple and it still fails. Putting any value in for `rsync__args` causes files to not be copied.
### Vagrant version

1.8.4 via `vagrant -v`, and 1.8.5.dev via `bundle show`
### Host operating system

Ubuntu Linux 16.04
### Guest operating system

Ubuntu Linux 16.04
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require "dotenv"
Dotenv.overload(".env", ".env.local")

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-xenial64"

  config.vm.synced_folder ".", "/vagrant", type: :rsync,
    rsync__exclude: %w(.git/ .DS_Store boxes/),
    rsync__args: ["--verbose", "--rsh='trickle -u 256 ssh'"]

  config.vm.provider :aws do |aws, ovveride|
    config.ssh.pty = true

    aws.access_key_id       = ENV["AWS_ACCESS_KEY_ID"]
    aws.associate_public_ip = true
    aws.instance_type       = ENV["AWS_INSTANCE_TYPE"]
    aws.keypair_name        = ENV["AWS_KEYPAIR_NAME"]
    aws.region              = ENV["AWS_REGION"]
    aws.secret_access_key   = ENV["AWS_SECRET_ACCESS_KEY"]
    aws.security_groups     = Array(ENV["AWS_SECURITY_GROUP"])
    aws.subnet_id           = ENV["AWS_SUBNET_ID"]
    aws.user_data = "#!/bin/bash\nsed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers"

    override.nfs.functional = false
    override.ssh.username   = "ubuntu"
  end


  %i(test_system).each do |role|
    config.vm.define(role, autostart: false) do |machine|
      opts = { env:        { SUITE: role },
               keep_color: true,
               path:       "scripts/bootstrap.sh" }

      machine.vm.provision("shell", opts)
    end
  end
end

```
### Debug output

I've pasted what portion of the debug log I can without concerns for security that are related to this issue and have scoured the logs prior to this portion for errors and there are none. The output is nearly identical between the working version, and the failing version:

https://gist.github.com/gravyboat/16cb796944a8ef36b99c2d43be7e3d87
### Expected behavior

Files should have been rsynced to the AWS instance using the arguments I specified.
### Actual behavior

Files do not get rsync'd at all. The `vagrant up` quickly skips past the rsync stage.
### Steps to reproduce
1. `bundle exec vagrant up test_machine` while `rsync__args` exist within the Vagrantfile
### References

Are there any other GitHub issues (open or closed) that should be linked here?
- Not that I am aware of at this time.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Comment by gravyboat** [comment]
No worries, I swapped off using this functionality months ago because it wasn't working, if I circle back around at some point in the future and it still doesn't work I'll reopen this issue.
