### ISSUE TITLE
Ubuntu 16.04 xenial - no "/vagrant" directory

### ISSUE THREAD

**Issue by jazzfog** [mitchellh/vagrant#7544]
### Versions
- Vagrant 1.8.4
- Virtual box 5.0.20 r106931

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16.04 Xenial Xerus

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.100.143"
end
```

### Debug output
Host console output http://pastebin.com/YW0iqtY5
VM console output http://pastebin.com/xDxcNqnL

### Expected behavior
VM should have /vagrant mapped to hot machine dir

### Actual behavior
There is no /vagrant dir in the VM

### Steps to reproduce
1. Create vagrant VM with box ubuntu/xenial64

**Comment by sethvargo** [comment]
Hi @jazzfog 

Thank you for opening an issue. Can you please try `bento/ubuntu-16.04`? There have been numerous reported issues with the boxes under the "ubuntu" namespace, particularly 16.04. Namespaces do not guarantee canonical boxes! A common misconception is that a namespace like "ubuntu" represents the canonical space for Ubuntu boxes. This is untrue. Namespaces on Atlas behave very similarly to namespaces on GitHub, for example. Just as GitHub's support team is unable to assist with issues in someone's repository, HashiCorp's support team is unable to assist with third-party published boxes.

**Comment by jazzfog** [comment]
Thank you, I didn't realize that, Atlas description is confusing then

    ubuntu/xenial64 
    Official Ubuntu 16.04 LTS (Xenial Xerus) Daily Build

With image you provided the problem with missing /vagrant directory has gone!

**Comment by sethvargo** [comment]
Hi @jazzfog 

Atlas is like GitHub - it just hosts private boxes. Just like a user could create a GitHub project and say "official foo", so too can users of Atlas. The "ubuntu" namespace is owned by Canonical (the makers of Ubuntu), but the boxes do not follow the basic guidelines for building boxes. We call this out in the Vagrant documentation, but just like GitHub cannot remove repositories with buggy code, we cannot remove boxes that are non-functional. We merely recommend alternatives.
