### ISSUE TITLE
ssh connection dies on vagrant up/destroy when running multiple vmware fusion boxes locally

### ISSUE THREAD

**Issue by xh3b4sd** [mitchellh/vagrant#7545]
### Vagrant version

Vagrant 1.8.4
### Host operating system

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.5 (15F34)
      Kernel Version: Darwin 15.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      ...
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 days 18:22

```
### Guest operating system

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```
### Vagrantfile

``` ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "boxcutter/ubuntu1604"
  config.vm.hostname = "xenial"
  config.vm.network :forwarded_port, guest: 22, host: 2001, id: 'ssh'
  config.vm.network :private_network, ip: "172.17.8.201"
  config.ssh.forward_agent = true
end
```

``` ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "boxcutter/ubuntu1604"
  config.vm.hostname = "xenial"
  config.vm.network :forwarded_port, guest: 22, host: 2002, id: 'ssh'
  config.vm.network :private_network, ip: "172.17.8.202"
  config.ssh.forward_agent = true
end
```
### Debug output
- [tmp1/ VAGRANT_LOG=debug vagrant up](https://gist.github.com/xh3b4sd/f278605c486376d4f7314646fda47123)
- [tmp2/ VAGRANT_LOG=debug vagrant up](https://gist.github.com/xh3b4sd/63f300a87f6031b12ca0e4610e873345)
### Expected behavior

When having a ssh connection established to the tmp1 box, I would expect the ssh session not to be terminated when running `vagrant up` or `vagrant destroy` on the tmp2 box.
### Actual behavior

My established ssh connection to the tmp1 box gets terminated when running `vagrant up` or `vagrant destroy` on the tmp2 box.
### Steps to reproduce
1. Create two test directories containing the Vagrantfiles shown above: `/tmp1/Vagrantfile` and `/tm2/Vagrantfile`.
2. Bring up the tmp1 box: `vagrant up`.
3. Put the following in your ssh config. Note that this issue is not reproducible using `vagrant ssh`. In this case the connection is stable. The issue only occurs using plain `ssh tmp1`.

```
Host tmp1
  HostName 127.0.0.1
  Port 2001
  User vagrant
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /tmp1/.vagrant/machines/default/vmware_fusion/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes
```
1. Bring up the tmp2 box: `vagrant up`.
2. The ssh connection to the tmp1 box dies.

I am not sure if this helps, but my gut feeling is that the ssh connection is terminated when the debug output of the starting box shows the following log output. 

```
Started DHCP service on vmnet1
Enabled hostonly virtual adapter on vmnet2
Started DHCP service on vmnet2
Enabled hostonly virtual adapter on vmnet3
Started DHCP service on vmnet3
Started NAT service on vmnet8
Enabled hostonly virtual adapter on vmnet8
Started DHCP service on vmnet8
Started all configured services on all networks
```

**Comment by briancain** [comment]
Hey there!

This is indeed a bug, however it is something out of Vagrants control. What is happening here is when `vagrant up` or `vagrant destroy` is invoked, it has to modify a file `nat.conf` and apply changes to vmware which results in a vmnet restart. That restart is what is causing one of your SSH connections to be dropped. Unfortunately there isn't much that can be done about this. Apologies for the trouble you are having with this. I'm going to go ahead and close this issue.

Cheers!

**Comment by allanchau** [comment]
Hey @briancain I am experiencing a similar issue, is there still no workaround for this?
