### ISSUE TITLE
Feature REQ: Vagrantfile for vagrant plugin development

### ISSUE THREAD

**Issue by jhgorse** [mitchellh/vagrant#7548]
Greetings,

I have read a good portion of the documentation regarding the development of plugins and I am having issues with repeatability and, well, getting anything to work the way it ought to. To be frank, things barely work at all and it is likely entirely my fault for subtly ignoring a key warning from Vagrant.

This lead me to thinking, why isn't there a clean Vagrantfile for doing Vagrant plugin development? While the some developers may wish to live on the metal (as I often do), I believe this would be a useful tool for new developers who would like a jump start in productivity and in giving back to the Vagrant community.

So I am requesting that the good people of Hashicorp maintain a Vagrantfile for development of Vagrant and its plugins. Even if it comes through unofficial channels and is otherwise without support, I believe this would be of great value to me and the community at large.

Cheers,
Joe

**Comment by sethvargo** [comment]
Hi there,

There is a Vagrantfile, in the root of this repo, for developing on Vagrant. If you take a look at the Vagrant plugin development documentation on https://www.vagrantup.com, there are also sample Gemfile's for plugin development.

Please let me know if you have any questions. Thanks! 😄

**Comment by jhgorse** [comment]
Well I'll be... there it is.

Thanks. =)
