### ISSUE TITLE
Vagrant on centos 7

### ISSUE THREAD

**Issue by Klnder** [mitchellh/vagrant#7549]
Hi guys,
i try to install vagrant on centos 7.
the installation of virtualbox 5.0 and vagrant 1.8.XX are ok,
but when i install a box and i do a vagrant up on it it block at booting VM, and it literally crash
the centos.
If you now from where is the problem. Ty,
Sincerly,

**Comment by sethvargo** [comment]
Hi @Klnder 

Thank you for opening an issue. When you open an issue, a template appears. That template asks for key information we need to help diagnose your issue. Please open a new issue and complete all the required fields in the template. Thanks! 😄
