### ISSUE TITLE
Can we get a ubuntu1604-desktop box that works?

### ISSUE THREAD

**Issue by d3netxer** [mitchellh/vagrant#7563]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by sethvargo** [comment]
Hi @d3netxer 

Thank you for reaching out. I would recommend you try the boxes under the `bento` namespace. Namespaces do not guarantee canonical boxes. A common misconception is that a namespace like "ubuntu" represents the canonical space for Ubuntu boxes. This is untrue. Namespaces on Atlas behave very similarly to namespaces on GitHub, for example. Just as GitHub's support team is unable to assist with issues in someone's repository, HashiCorp's support team is unable to assist with third-party published boxes.

**Comment by d3netxer** [comment]
I checked out the bentu boxes @sethvargo https://atlas.hashicorp.com/boxes/search?utf8=%E2%9C%93&sort=&provider=&q=bento+

but they don't have desktop versions

**Comment by sethvargo** [comment]
Hi @d3netxer 

You can build your own boxes using [Packer](https://packer.io) or search in Atlas. Vagrant is a local development tool, so it's rare that one would want the desktop version.
