### ISSUE TITLE
Any way to install vagrant plugin globally?

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#7564]
Vagrant 1.8.1 on Ubuntu

It seems I have to install `vagrant-aws` for every user. Installing via root, it installs under `/root/.vagrant.d/`. The `vagrant plugin install -h` doesn't give any clues.

Is there any way to install plugin globally? So it's available for all users?

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/2457
