### ISSUE TITLE
vagrant-hostupdater failing to install (plugin issue?)

### ISSUE THREAD

**Issue by tom-smalls** [mitchellh/vagrant#7565]
### Vagrant version
Vagrant 1.8.4

### Host operating system
Linux fedora 4.4.8-300.fc23.x86_64

### Guest operating system
Linux fedora 4.4.4-301.fc23.x86_64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

def apply_default_config(config)
  config.vm.box_check_update = false
end


def install_python_dnf(config)
  config.vm.provision 'shell',
    privileged: true,
    run: 'once',
    inline: <<-SHELL
         echo "Installing python-dnf"
         dnf install python-dnf -y
         echo "----Done!----"
       SHELL
end

Vagrant.configure(2) do |config|
    install_python_dnf(config)
    apply_default_config(config)
    config.vm.network "private_network", ip: "192.168.33.11"
    config.vm.box = "akanto/fedora-23-server"
    config.vm.box_version = "0.8"
    config.vm.define :pairingstation do |t|
      end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/tom-smalls/d8c3468b13254b68751fb58c3fa45d80

### Expected behavior
The vagrant-hostupdater plugin should be installed

### Actual behavior
An error occurs around the installing of FFI

### Steps to reproduce
1. Run :
```
vagrant plugin install vagrant-hostsupdater
```

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/ffi/ffi/issues/510
- https://github.com/mitchellh/vagrant/issues/7493

**Comment by sethvargo** [comment]
Gonna wrap this up in https://github.com/mitchellh/vagrant/issues/6158. Thanks!

**Comment by tom-smalls** [comment]
Ok. That's quite a long running ticket with a lot of information, is there a resolution to the problem? I found it quite hard to digest all the information reading through it

**Comment by tom-smalls** [comment]
So our specific issue was that make was not available on Fedora. No idea what changed so that make was no longer available (change to how ffi is installed or Fedora image one must assume)
