### ISSUE TITLE
Network interface is not properly initialized if MAC addresses in Vagrantfile are specified in uppercase

### ISSUE THREAD

**Issue by uvsmtid** [mitchellh/vagrant#7566]
This Vagrant problem was originally identified during discussion of [this `vagrant-libvirt` issue](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/312).

As explained by @infernix in [his conclusive comment](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/312#issuecomment-229963533) there (which includes reference to Vagrant code snippets), this is a Vagrant issue when MAC address is specified in uppercase (instead of lowercase).
### Vagrant version

```
> vagrant -v
Vagrant 1.8.1

> rpm -qa | grep vagrant
vagrant-1.8.1-2.fc24.noarch
```
### Host operating system

Fedora 24 x86_64

```
> uname -r
4.6.3-300.fc24.x86_64
```
### Guest operating system

CentOS 7 x86_64

```
> uname -r
3.10.0-229.el7.x86_64
```
### Vagrantfile

The `Vagrantfile` is taken from [the comment under the original issue](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/312#issuecomment-227637698).

``` ruby
# Vagrant file to test this issue:
#   https://github.com/vagrant-libvirt/vagrant-libvirt/issues/312

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "libvirt"
  config.vm.provider :libvirt do |libvirt|

      libvirt.video_type = 'qxl'

  end

  config.vm.box_download_insecure = true

  config.vm.define "observer_client_1" do |observer_client_1|

    observer_client_1.vm.box = "uvsmtid/centos-7.1-1503-gnome"

    # See libvirt configuration:
    #   https://github.com/pradels/vagrant-libvirt
    observer_client_1.vm.provider :libvirt do |observer_client_1_domain|
        observer_client_1_domain.memory = 2048
        observer_client_1_domain.cpus = 2
    end

    observer_client_1.vm.provision "shell", inline: "true"

    # Based on Vagrant explanation, in the future they may support provider
    # per each VM. At the moment, it should only be configured per all
    # set of VMs (outside of individual configuration).
    #observer_client_1.vm.provider = "libvirt"

    observer_client_1.vm.network :private_network,
        :ip => '192.168.1.3',
        :libvirt__network_name => 'vagrant_internal_net',
        :mac => 'FA:16:3E:3D:C8:77',
        :libvirt__netmask => '255.255.255.0',
        :libvirt__forward_mode => 'nat',

        # Use DHCP to offer addresses to avoid too long initialization
        # of network interfaces during first boot (before static IP is
        # configured by Vagrant) on some OSes.
        # NOTE: At the time of coding IP range for DHCP server was not
        #       configurable. So, we hope that there will be no conflicts
        #       with IP addresses assigned statically.
        :libvirt__dhcp_enabled => true,

        # A syntactic dummy to allow every option above end with comma `,`.
        :whatever => true

  end

end
```
### Debug output

The debug output has already been pasted in [this comment under the original issue](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/312#issuecomment-227637698).
### Expected behavior

Specifically in [the original issue](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/312), the network interface for guest VM was not initialized with fixed IP address from `Vagrantfile`. Even though:
- Both MAC address and IP address were specified in the `Vagrantfile`.
- Guest VM network interface has exactly the same MAC address.
### Actual behavior

The assigned IP address appears to be random instead.
### Steps to reproduce
1. Use the `Vagrantfile` with specified host OS (all mentioned above).
2. Run `vagrant up`.
3. Check guest OS IP address assigned to the network interface matched by the MAC address in the `Vagrantfile`. It will likely be different from the fixed IP specified in the same `Vagrantfile`.
### References

Again: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/312

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
