### ISSUE TITLE
How to avoid printing 1 character per line?

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#7572]
I'm using Vagrant 1.8.1 with OS X as host and debian/jessie64 or anything else as guest.

I have a problem with buffering with Vagrant. During provisioning it's printing very often one character per each line. This is especially trouble when using with CI and long VM names, it generates huge sizes of meaningless logs. This not only happens for progress (such as curl, wget), but also for other tools such as ex/vim. See the example below.

Sample `Vagrantfile` (this happens on any Linux):

```
Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.provision "shell", inline: <<-SHELL
    echo Foo bar >&2
    ex +%p -scq! -V1 /etc/hosts
  SHELL
end
```

Output:

```
$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Foo bar
==> default: "
==> default: /
==> default: e
==> default: t
==> default: c
==> default: /
==> default: h
==> default: o
==> default: s
==> default: t
==> default: s
==> default: "
==> default:  
==> default: "
==> default: /
==> default: e
==> default: t
==> default: c
==> default: /
==> default: h
==> default: o
==> default: 127.0.0.1       localhost
==> default: 127.0.1.1       jessie.raw      jessie
==> default: ::1     localhost ip6-localhost ip6-loopback
==> default: sts" 7 lines, 197 characters
==> default: 
==> default: 
==> default: 
==> default: 
```

This is how above is printed on the host machine:

```
$ ex +%p -scq! -V1 /etc/hosts | cat -v
GetLatestVimScripts is not vi-compatible; not loaded (you need to set nocp) 
"/etc/hosts" 
"/etc/hosts" [readonly] 25 lines, 789 characters
```

There are no any special characters, no progress bar and lines (such as file path) are printed correctly when run on host.

What's the problem and how to fix it? Can't Vagrant print output on the line basis?

**Comment by kenorb** [comment]
This could be issue with vim/ex as it prints each characters separated by `\0` (e.g. `write_nocancel(0x2, "e\0", 0x1)`, see: vim/vim/issues/919), but I think it would be still worth to print each line separated by new line character when possible.

**Comment by sethvargo** [comment]
Vagrant does buffer - it just prints streams directly what the other process is sending. I think there's another issue tackling the idea of buffering on newlines. Thanks!

**Comment by phemmer** [comment]
Also having this issue. The hacky workaround I've come up with is to pipe any command which does this through `| grep --line-buffered '^'`

**Comment by kenorb** [comment]
Link to the other mentioned issue related to buffering on newlines would be great.
