### ISSUE TITLE
Vagrant can't find Virtual Box

### ISSUE THREAD

**Issue by tattva20** [mitchellh/vagrant#7575]
### Vagrant version
Vagrant 1.8.4

### Host operating system
OSX 10.11.15 El capitan

### Guest operating system
Ubuntu 14.04 Trusty

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
Vagrant.configure(2) do |config|
  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get --assume-yes install clang libicu-dev
    curl -O https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu14.04.tar.gz
    tar zxf swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu14.04.tar.gz
    sudo chown -R vagrant:vagrant swift-*
    echo "export PATH=/home/vagrant/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-ubuntu14.04/usr/bin:\"${PATH}\"" >> .profile
    echo "Swift has successfully installed on Linux"
  SHELL
end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://gist.github.com/tattva20/d137fa2579d7fb918a51f7b570d987b6 

### Expected behavior
1. Starts Vagrant

2. Downloads a disk image of Ubuntu LTS 14.04 (the latest version as published by Canonical, the Ubuntu company, whenever you are running the script). It will only perform this download once and then cache the image for later use. You will likely see an “Attempting to find and install…” message for the Box file, followed by a message about “Adding it directly…”.

3. Runs the downloaded disk image in virtualization.

4. Installs Apple’s C compiler clang and the internationalization library libicu, both components which the Swift compiler requires.

5. Downloads Swift (as distributed by swift.org on April 12th, 2016) and uncompresses it.

6. Adjust some file permissions needed to use the Swift Package Manager.

7. Configures the default user’s home PATH variable, so it can run the swift binary, REPL, and other tools.

8. If this completes successfully, the final message will say that “Swift has successfully installed on Linux”.

### Actual behavior
Got this error message:

No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

### Steps to reproduce

1. Install virtualbox 5.1.0-108711-OSX
2. Install vagrant_1.8.4
3. Go to /Users/tattvaworld/Documents and create the directory
/Users/tattvaworld/Document/vagrant-swift
4. Created a vagrant file in that directory
5. ran vagrant up in the /Users/tattvaworld/Document/vagrant-swift
6. got the error message
7. Tried uninstalling and then reinstalling both vagrant and virtualbox but no luck
8. Tried again and again but still stuck

**Comment by nunogt** [comment]
Confirmed, reverting to VirtualBox fixes this for me.

**Comment by tattva20** [comment]
I solved it in order to do it I just downloaded virtualbox 5.0.22-108108 and it is now working.

User [https://github.com/martinseener](url) suggested here [https://github.com/mitchellh/vagrant/issues/7573](url) a workaround to make 5.1 work but I just preferred to switch back to 5.0.22 hope this helps.

**Comment by vzabaznov** [comment]
I cannot understand why you close the issue, vagrant still cannot been running vs VM box 5.1.0

**Comment by sethvargo** [comment]
Hi @vzabaznov 

1. I did not close the issue, the author did.
2. This issue has been fixed on master, but there is no release yet
