### ISSUE TITLE
I am getting error while doing vagrant up

### ISSUE THREAD

**Issue by tadesushilgithub** [mitchellh/vagrant#7576]
I am getting below error 

I have installed VirtualBox on mac still why I am getting this error?

No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
vagrant up --provider=PROVIDER, which should give you a more specific
error message for that particular provider.

### Vagrant version
Vagrant 1.8.4

### Host operating system
MAC os x EI Captain

**Comment by sethvargo** [comment]
Hi there,

Looks like you are using VirtualBox 5.1 - that is not yet supported (it just came out today). Please use virtualbox 5.0. Thanks!

**Comment by joelhandwell** [comment]
For those who do not want to wait 1.8.5 come with 2016 September 1st, you can use VirtualBox 5.1 by:

1. Compile Vagrant from source 
2. Apply https://github.com/mitchellh/vagrant/commit/b57b0e0d48fe8b4196ca6b7e01bb6c1ecb4b69f9 by [changing Vagrant embedded files](https://github.com/mitchellh/vagrant/issues/7588#issuecomment-233035591) in your computer
