### ISSUE TITLE
Make Virtualbox 5.1 final version compatible

### ISSUE THREAD

**Issue by rbatllet** [mitchellh/vagrant#7578]
When I install the new Virtualbox, a warning message appears:

```
$ vagrant up
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.

```
### Vagrant version
My Vagrant version is:

```
Installed Version: 1.8.4
Latest Version: 1.8.4
```

### Host operating system
I'm using `MacOS El Capitan`

**Comment by nappa85** [comment]
Actually I've got it to work adding the association "5.1" => Version_5_0
on line 64 of file /opt/vagrant/embedded/gems/gems/vagrant-1.8.4/plugins/providers/virtualbox/driver/meta.rb

**Comment by daecks** [comment]
Issue is resolved by this commit: https://github.com/mitchellh/vagrant/commit/b57b0e0d48fe8b4196ca6b7e01bb6c1ecb4b69f9

**Comment by joelhandwell** [comment]
For those who do not want to wait 1.8.5 come with 2016 September 1st, you can use VirtualBox 5.1 by:

1. Compile Vagrant from source 
2. Apply https://github.com/mitchellh/vagrant/commit/b57b0e0d48fe8b4196ca6b7e01bb6c1ecb4b69f9 by [changing Vagrant embedded files](https://github.com/mitchellh/vagrant/issues/7588#issuecomment-233035591) in your computer

**Comment by rbatllet** [comment]
New version until `September, 1`? 
Seriously, are you kidding me?

**Comment by joelhandwell** [comment]
@rbatllet it's not me who decided the release due date and I'm one of user just found the date here: https://github.com/mitchellh/vagrant/milestone/17 @sethvargo has more idea about how the milestone was set.

**Comment by Tecktron** [comment]
I agree with @rbatllet, this is a backwards way of development. You're supposed to be ready for when the release of a product that your product depends heavily on is updated.  That's just a basic fundamental rule of development.
