### ISSUE TITLE
Vagrant 1.8.4 is not able to recognize provider VirtualBox 5.1.0 on OS X El Capitan.

### ISSUE THREAD

**Issue by franksort** [mitchellh/vagrant#7585]
Vagrant 1.8.4 is not able to recognize provider VirtualBox 5.1.0 on OS X El Capitan.  The previous version of VirtualBox (5.0.24) does work.

### Vagrant version
Vagrant 1.8.4

### Host operating system
OS X El Capitan Version 10.11.5

### Guest operating system
boxcutter/centos72-docker

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|                                              
  config.vm.box = "boxcutter/centos72-docker"                                   
end           
```

### Debug output
https://gist.github.com/franksort/f17bf80ce76fb205d060bd009d3ecea9

### Expected behavior
Expected Vagrant to provision the box using VirtualBox 5.1.0 as the provider.

### Actual behavior
```
$ vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```

I received the same message when running `vagrant up --provider=virtualbox` and `vagrant up --provider=VirtualBox`.

### Steps to reproduce
1. Install Vagrant 1.8.4: 
`$ brew cask install vagrant`
2. Install VirtualBox 5.1.0: 
`$ brew cask install virtualbox`
3. Create Vagrant directory: 
`$ mkdir vagrant-test; cd vagrant-test`
4. Create Vagrantfile as documented above.
5. `$ vagrant up`

**Comment by sethvargo** [comment]
This has already been fixed in master. https://github.com/mitchellh/vagrant/issues/7578
