### ISSUE TITLE
Error with mount_options dmode on synced folder using vmware_fusion plugin

### ISSUE THREAD

**Issue by kaplan** [mitchellh/vagrant#7586]
I'm hoping to use vhosts with an Ubuntu 14.04 LAMP stack running PHP-FPM. The goal would be to have the vhost get their own group/user and spec that in the pool.d and sites-available conf. If I try and use `dmode` and `fmode` on the synced folder in the `mount_options` I get an error: `fuse: unknown option dmode=777'`  

Having the files on the Host and synced to the Guest but with the unique group/user is the goal, but I'm unable to make changes to the ownership of the synced directory using the dmode and fmode `mount_option`. I am able to change the `owner` and `group` but only for existing users.
### Vagrant version

Vagrant 1.8.4
vagrant-vmware-fusion (4.0.10)
### Host operating system

OS X Yosemite version 10.10.5
### Guest operating system

Ubuntu 14.04.4
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "workalicious/ubuntu1404"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 7373
  config.vm.network "private_network", ip: "192.169.39.18"
  config.vm.network "public_network"
  config.vm.synced_folder "www", "/var/www", mount_options: ["dmode=777", "fmode=666"]
end
```
### Debug output

https://gist.github.com/kaplan/bcca284294c5b2dc2a4ff8c09bdfd529
### Expected behavior

I would like to change the permissions of the synced folder in order add a new user and assign ownership. My goal is to work on the files in the Host with a LAMP stack on the Guest that's using PHP-FPM pool configurations. I'm using the `ppa:ondrej/apache2` and `ppa:ondrej/php`. I can get it all working directly in the Guest, but it'd be handy to have the files on the host. Maybe I just need to stick with `www-data` and use that for all the vhost group/owners?
### Actual behavior

The Guest starts up, but I get an error,  
`vmhgfs-fuse -o uid=`id -u vagrant`,gid=1000,allow_other,dmode=777,fmode=666 '.host:/-var-www' /var/www`
...
`fuse: unknown option dmode=777'`

The Host folder I'm trying to sync doesn't take.

I'm using a VMware Fusion 8.1 built box from an ubuntu-14.04.4-server-amd64.iso file. I have the box on Atlas: https://atlas.hashicorp.com/workalicious/boxes/ubuntu-server-14.04.4

**Comment by davidfsmith** [comment]
I'm being affected by this issue at the moment, is there a work around until the fix is released ?

**Comment by Enchiridion** [comment]
I'm getting the same error `fuse: unknown option 'dmode=777'`, under a different setup when trying to setup shared folders:
Host: Windows 10 x64
Guest: Ubuntu 16.04 x64 (my same vagrant file works fine using Ubuntu 14.04 x64)
Vagrant 1.9.1
vagrant-vmware-workstation (4.0.15)

If I do a `vmhgfs-fuse --help`, neither dmode or fmode are supported options.

**Comment by chrisroberts** [comment]
Hi there. The options `dmode` and `fmode` are not supported by `vmhgfs-fuse`. However, it does support the `umask` option which can probably get you the behavior you're after. Cheers!
