### ISSUE TITLE
VirtualBox 5.1 not supported

### ISSUE THREAD

**Issue by gggeek** [mitchellh/vagrant#7588]

**Comment by yveslaroche** [comment]
This has already been fixed in master https://github.com/mitchellh/vagrant/pull/7574

**Comment by joelhandwell** [comment]
@gggeek @yveslaroche you can join discussion and give your opinion or +1 about releasing vagrant 1.8.4.1 with https://github.com/mitchellh/vagrant/pull/7574 before 1.8.5 scheduled in September 1, 2016

**Comment by joelhandwell** [comment]
For those who want to use VirtualBox 5.1 and package installed Vagrant 1.8.4 without building Vagrant from source in Windows, changing files in vagrant installation directory same as in PR https://github.com/mitchellh/vagrant/pull/7574 can be an workaround.

1. Edit driver\meta.rb file
```
notepad C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.4\plugins\providers\virtualbox\driver\meta.rb
```
add add ```"5.1" => Version_5_1, ``` under the line about 5_0

2. Edit plugin.rb file
```
notepad C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.4\plugins\providers\virtualbox\plugin.rb
```
add ```autoload :Version_5_1, File.expand_path("../driver/version_5_1", __FILE__)``` under the line about 5_0

3. Create driver\version_5_1.rb file
```
notepad C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.4\plugins\providers\virtualbox\driver\version_5_1.rb
```
The file content can be found here (https://raw.githubusercontent.com/mitchellh/vagrant/b57b0e0d48fe8b4196ca6b7e01bb6c1ecb4b69f9/plugins/providers/virtualbox/driver/version_5_1.rb)

I tested it in Windows 10, with VirtualBox 5.1 and Vagrant 1.8.4 and worked.

**Comment by mrummuka** [comment]
Tested with Fedora 24 (works) by changing the following files according to above instructions:
/usr/share/vagrant/plugins/providers/virtualbox/driver/meta.rb
/usr/share/vagrant/plugins/providers/virtualbox/plugin.rb
/usr/share/vagrant/plugins/providers/virtualbox/driver/version_5_1.rb
