### ISSUE TITLE
Vagrant not compatible with VirtualBox 5.1

### ISSUE THREAD

**Issue by Cysioland** [mitchellh/vagrant#7593]
### Vagrant version
1.8.4

### Host operating system
Antergos Linux

### Guest operating system
Any (tested with Homestead's Ubuntu 16.04 and base box)

### Vagrantfile
Shouldn't be relevant, but if it is, tested with Homestead and default file from `vagrant init`

### Debug output
https://gist.github.com/Cysioland/502ab8e380e4c372cde136670d8bcf08

### Expected behavior
Machine should have been started

### Actual behavior
Error was produced, that Vagrant is not compatible with VirtualBox 5.1

### Steps to reproduce
1. Update VirtualBox to version 5.1
2. Try to start machine with `vagrant up`

**Comment by celsocrivelaro** [comment]
Same for me on Mac + Homebrew

**Comment by ConnerStephens** [comment]
It's is fixed if you want to compile from source. Other than that, you have to wait for the next milestone to be released (Version 1.8.5), which should be soon. I have heard that 1.8.4 works on OS X if you use the Virtualbox 5.1 Beta version.

**Comment by celsocrivelaro** [comment]
@ConnerStephens Unfortunately 1.8.4 doesn't work with VB Beta. I'm going to try compiling from source until next release.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/pull/7574

**Comment by joelhandwell** [comment]
Work around for those who want to use VirtualBox 5.1 without compiling from source: https://github.com/mitchellh/vagrant/issues/7588#issuecomment-233035591

**Comment by ehongyu** [comment]
It happens again for the latest Virtualbox / Vagrant version when I tried to install them together today (10/28/2017). It sucks to see the same issue happening over and over again.

**Comment by Alexandre1202** [comment]
The uninstall of vagrant does not delete %HOME_DIR%\.vagrant.d but before install other version it is important you do it manually.
I also remove unused directories inside of %HOME_DIR%\VirtualBox VMs and %HOME_DIR%\.VirtualBox
