### ISSUE TITLE
synced_folder type "virtualbox" and excludes files / folders 

### ISSUE THREAD

**Issue by daviedR** [mitchellh/vagrant#7595]
This is actually a question, can the "virtualbox" `type` in `synced_folder` configuration exclude some files / folders?

I know the `rsync` type could do that. But I read that `rsync` is one-way sync. And I want two-ways sync in my environment. The `virtualbox` type seems to work really fine, but does it have `exclude` option?

**Comment by sethvargo** [comment]
No, sorry - it's a mount not a sync, so you can't exclude.
