### ISSUE TITLE
Symlinks break when using open-vm-tools on shared folders under the VMWare-fusion provider

### ISSUE THREAD

**Issue by zerotao** [mitchellh/vagrant#7599]
When creating symlinks to files in the same directory they work locally however in the host environment they now point to non-existent files.

This appears to be due to how the mount point is created (see the referenced Docker bug).

### Vagrant version
Vagrant (1.8.4)
vagrant-vmware-fusion (4.0.10)

### Host operating system
OSX 10.11.5

### Guest operating system
box-cutter/ubuntu1604

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.box = "box-cutter/ubuntu1604"
   if auto_correct_ports
    config.vm.networks.each do |network, settings|
      settings[:auto_correct] = true
    end
  end

   config.vm.synced_folder ".", "/vagrant"

   config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision :ansible do |ansible|
      ansible.playbook = "ansible/vagrant.yml"
  end
end
```

### Expected behavior
Symlink created in the guest should have been readable in the host

### Actual behavior
Symlink created in the guest pointed to a non-existant file

### Steps to reproduce
1. cd /vagrant
2. ln -s Vagrantfile test
3. ls -al (check in both guest and host)

### References
- https://github.com/docker/machine/issues/2050

**Comment by zerotao** [comment]
Everything works as expected if I manually unmount the /vagrant directory and then remount it as:

```
sudo mount --bind /mnt/hgfs/-vagrant/ /vagrant/
```

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/issues/5474, but keeping this open as well.

**Comment by chrisroberts** [comment]
Using the box defined within the given Vagrantfile I have been unable to reproduce the documented behavior. Everything works as expected.

My initial test used the `hashicorp/precise64` box as it was already locally available. Using that box, I _did_ have issues when creating creating symlinks within the guest. After creating the symlink, attempts to `cat` the link on the guest would fail with an error of no such file. Exiting out to the host, the symlink was valid and `cat` worked as expected. After a `vagrant reload`, I found the symlink on the guest now worked, and new symlinks would work on both the guest and host as well.

After some digging I found the the `vmware-tools` was auto-updating itself on `vagrant up` and the stopping and starting of the vmware-tools during this update was failing which resulted in the unexpected behavior.

If you are still experiencing this issue, please let me know the versions of all the things you are using, including the box. Thanks!

**Comment by chrisroberts** [comment]
New vagrant-vmware-plugin release includes fix for broken symlinks when vmhgfs-fuse (open-vm-tools) is in use:

https://github.com/hashicorp/vagrant-plugin-changelog/blob/master/vagrant-vmware-changelog.md#4014-october-14-2016
