### ISSUE TITLE
$vagrant up There was an error when attempting to rsync a synced folder.

### ISSUE THREAD

**Issue by Jetlum** [mitchellh/vagrant#7600]
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /j/Projects/idk-vagrant/projects/
Guest path: /home/vagrant/projects
Command: "rsync" "--verbose" "--rsync-path='sudo rsync'" "--archive" "-z" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/Users/ACERPC~1/AppData/Local/Temp/ssh.847 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'J:/Projects/idk-vagrant/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "--exclude" ".git/" "/j/Projects/idk-vagrant/projects/" "vagrant@127.0.0.1:/home/vagrant/projects"
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.1]

**Comment by Jetlum** [comment]
Any help regarding this problem

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
