### ISSUE TITLE
Support for Virtualbox 5.1.0 

### ISSUE THREAD

**Issue by basictheprogram** [mitchellh/vagrant#7601]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
$ vagrant -v
Vagrant 1.8.4

### Debug output
```
$ vagrant box update --provider virtualbox testing_trusty64
The provider 'virtualbox' that was requested to back the machine
'testing_trusty64' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
```

### Expected behavior
Update the virtualboxes 

### Actual behavior
Throws an error that Virtualbox 5.1.0 is not supported

### Steps to reproduce
1. Download vagrant 1.8.4
2. Download virtualbox 5.1.0
3. vagrant box update --provider virtualbox your-virtualbox

**Comment by sethvargo** [comment]
It's done. Already in master. https://github.com/mitchellh/vagrant/pull/7574

**Comment by icflorescu** [comment]
It may be hard to believe, but for me, a trusty64 guest is  now **running 10 times faster (!)** in a LinuxMint host in 1.8.5 + VirtualBox 5.1.

A big thanks for publishing the new version ahead of schedule! ;-)
