### ISSUE TITLE
Provider detection fails

### ISSUE THREAD

**Issue by thasmo** [mitchellh/vagrant#7602]
### Vagrant version
1.8.4

### Host operating system
Windows 10 64-bit (CYGWIN_NT-10.0 PC-NAME 2.5.2(0.297/5/3) 2016-06-23 14:29 x86_64 Cygwin)

### Guest operating system
Ubuntu 16.04 (boxcutter/ubuntu1604)

### Vagrantfile
```ruby
# Version
Vagrant.require_version '>= 1.8.0'

# Configuration
Vagrant.configure('2') do |config|

  # Base
  config.vm.box = 'boxcutter/ubuntu1604'
  config.vm.box_version = '>= 2.0'
  config.vm.hostname = 'boxtest'

  # Netwwork
  config.vm.network 'private_network', ip: '192.168.100.100'

  # VirtualBox
  config.vm.provider :virtualbox do |provider, config|
    provider.gui = false
    provider.name = 'boxtest'
  end
end
```

### Debug output
https://gist.github.com/thasmo/ea6bd8d56b71d4aa2387ccc88b272417

### Expected behavior
I expect Vagrant to use the VirtualBox provider. The Vagrantfile does not contain a VMware Workstation provider configuration. The [docs](https://www.vagrantup.com/docs/providers/basic_usage.html#default-provider) state that the Vagrantfile is checked for the provider configurations *before* it checks for installed plugins.

### Actual behavior
Vagrant wants to use the VMware Workstation provider. This may occur because I have the VMware Workstation plugin installed, but VMware Workstation is not installed. Still it should check for VirtualBox first, because it's configured in the Vagrantfile and it is installed on the machine. `VAGRANT_DEFAULT_PROVIDER` is not set.

### Steps to reproduce
Just run `vagrant up`.

**Comment by sethvargo** [comment]
If you have the VMware provider installed, Vagrant automatically picks the "best" provider based on performance. In this case VMware > Virtualbox. Unfortunately due to Vagrant's architecture, providers are chosen _before_ Vagrantfile parsing (since providers declare their own config). There's already an open issue tracking the requirements to change that functionality. Thanks! 😄
