### ISSUE TITLE
Sort snapshot list

### ISSUE THREAD

**Issue by Fuzzy-Logik** [mitchellh/vagrant#7604]
**Vagrant version: _1.8.4_**
**Host operating system: _not applicable_**
**Guest operating system: _not applicable_**

Currently, snapshots are sorted alphabetically when calling `vagrant snapshot list`.
This is cumbersome when there are many snapshots and the user is unsure which to roll back to.
It would be better to sort by and display the modification date along with the snapshot names.

In addition or perhaps instead of sorting by date, ideally the snapshots would be listed hierarchically in a tree format, akin to how they are listed in Virtualbox.

As it is now, the work-around is to name snapshots with an ID prefix to maintain chronological or hierarchical sorting.

Another nice-to-have would be the ability to add descriptions for greater insight as to the state of any given snapshot. With many boxes, many snapshots and an indeterminate amount of time passed, it's too easy to lose track of snapshot states. Long names can be used to include details directly in the name but this is also cumbersome when trying to manipulate these snapshots.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
