### ISSUE TITLE
The last version is not the latest

### ISSUE THREAD

**Issue by rbatllet** [mitchellh/vagrant#7609]
When I've updated to a new Vagrant version, the latest Version is still the previous:

### Vagrant version
Installed Version: `1.8.5`
Latest Version: `1.8.4`

### Host operating system
MacOS El Capitan

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue. I am update to reproduce this. What command are you running to generate this output? Can you please supply the [debug output](https://www.vagrantup.com/docs/other/debugging.html)?

**Comment by thasmo** [comment]
Got the same when running `vagrant version`.

**Comment by sethvargo** [comment]
Hi @thasmo,

Are you able to share the `debug output` when running this command? I cannot reproduce this locally.

**Comment by thasmo** [comment]
@sethvargo, yep:
https://gist.github.com/thasmo/e965af480c6a7240fb9de42e0855f0ae

**Comment by rbatllet** [comment]
@sethvargo My vagrant debug: https://gist.github.com/rbatllet/d1d5e1bc1a1fe48d4925a96571d0536c

**Comment by rbatllet** [comment]
Look at this issue: https://github.com/mitchellh/vagrant/issues/7444

**Comment by rbatllet** [comment]
I've uninstalled the old version with the uninstaller tool included in the .dmg

**Comment by sethvargo** [comment]
Ah - okay. So checkpoint caches the last result. You'll have to remove the cache file or just wait a few days for the cache to expire. More instructions in #7444
