### ISSUE TITLE
Bump Ruby version

### ISSUE THREAD

**Issue by Jetlum** [mitchellh/vagrant#7612]
RubyDep: WARNING: Your Ruby has security vulnerabilities! (To disable warnings, set RUBY_DEP_GEM_SILENCE_WARNINGS=1)
RubyDep: WARNING: Your Ruby is: 2.2.3 (insecure). Recommendation: install 2.2.5 or 2.3.1. (Or, at least to 2.2.4 or 2.3.0)
There are no paths to watch! This is either because you have no
synced folders using rsync, or any rsync synced folders you have
have specified `rsync_auto` to be false.

**Comment by kitsunde** [comment]
I'm seeing the same issue on OS X. rsync-auto remains broken despite https://github.com/mitchellh/vagrant/issues/7441 there's a workaround in the bottom.

**Comment by Jetlum** [comment]
Usage of cmd instead of git console.

**Comment by sethvargo** [comment]
Changed title to reflect action.
