### ISSUE TITLE
Canceling 'vagrant provision' doesn't clean up various shell scripts it pushes

### ISSUE THREAD

**Issue by dragon788** [mitchellh/vagrant#7615]
Old title: Script provisioner doesn't checksum if multiple inline script "files", invalid results when re-running without an expensive "vagrant destroy"

When rerunning provision after a cancel you will get strange results if you have changed the Vagrantfile or scripts because it only checks if they exist and re-runs them. Another part of the issue is that the processes may continue running in the background after you kill the provision which prevents another provision from working properly.

Vagrant: 1.8.4
Host: Windows 7
Guest: Windows 2012r2
### Vagrantfile

``` ruby
$script1 = <<SCRIPT
echo foo
SCRIPT

$script2 = <<SCRIPT
echo bar
REM Simulates a "hang" or a prompt for confirmation in an interactive process
timeout 1000000
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "mwrock/Windows2012R2"
  config.vm.provision "script1", type: "shell", inline: $script1
  config.vm.provision "script2", type: "shell", inline: $script2
end
```
### Expected behavior

Vagrant should have detected the Vagrantfile changed and either assume it needs to reupload the various script files (for inline blocks) or checksum the script file locally before upload and reverify the checksum when the Vagrantfile changes.
### Actual behavior

It never appears to upload new script files when using inline script blocks with HEREDOCs if the provision is canceled before it completes or if it hangs.
### Steps to reproduce

`vagrant up` (it then provisions, uploads script to box at C:\tmp\vagrant-shell.ps1 and runs with C:\tmp\vagrant-elevated-shell.ps1)
`notepad Vagrantfile` (alter inline script block to echo baz instead)
`vagrant provision` (it runs very quickly because it doesn't upload a new script file even if the block/Vagrantfile changes, therefore it will output foo still)
`type C:\tmp\vagrant-shell.ps1` and see the old contents of script.

**Comment by sethvargo** [comment]
Hi @dragon788 

Thank you for opening an issue. Can you please supply a complete Vagrantfile? The one you supplied only has a shell provisioner and does not list a specific box. Additionally, having the debug output for these various commands would be helpful.

**Comment by dragon788** [comment]
Updated the Vagrantfile with a bit more detail.

**Comment by DonRichards** [comment]
I'm having a similar issue. But to be honest I can't get this part to work. 
> config.vm.provision "**script2**", type: "shell", .... 

Did you try to run just this provision?
> vagrant reload --provision-with **script2**

Or would this even work?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
