### ISSUE TITLE
vagrant up fails with no meaningful message when no display is attached and gui = true is enabled

### ISSUE THREAD

**Issue by akoerner** [mitchellh/vagrant#7617]
### Vagrant version
vagrant 1.8.1
Virtualbox 5.0.26
### Host operating system
Ubuntu 14.04.4 LTS

### Guest operating system
Ubuntu 14.04.4 LTS

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.hostname = "myprecise.box"
  config.vm.network :private_network, ip: "192.168.0.1"

  config.vm.provider :virtualbox do |v, override|
    v.gui =true
  end
end
```

### Debug output
http://pastie.org/private/unttul2bma3brpsr6fbra

### Expected behavior
With no display attached to the host machine and virtualbox parameter "gui =true" vagrant up  results in an obscure error with no direct indication as to the source of the error.

I would expect either one of two things to happen: 

1. up fails with a message stating that there is no display attached and the gui parameter is enabled
1. up succeeds and "gui =true" is ignored with an appropriate warning message stating that you need a connected display

### Actual behavior
up fails with no meaningful message and no indication as to the cause.

### Steps to reproduce
1. create a vagrant file including the "gui = true" parameter for virtual box
2. Connect to the host machine remotely via ssh and run vagrant up

**Comment by sethvargo** [comment]
Hi there,

Can you please supply the [debug output](https://www.vagrantup.com/docs/other/debugging.html)?

**Comment by akoerner** [comment]
Added debug output as requested.

**Comment by sethvargo** [comment]
Hi @akoerner 

The error message is shown in the output:

```
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "e2cdb2e5-1111-492b-986d-cdf5c3951e27", "--type", "gui"]

Stderr: VBoxManage: error: The virtual machine 'Windows_default_1469059647041_78095' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
>
```

Unfortunately that is a known, long-running bug in VirtualBox (not Vagrant), which you can track here :https://www.virtualbox.org/ticket/7367
