### ISSUE TITLE
Crashing on single vm

### ISSUE THREAD

**Issue by jesse-cohen** [mitchellh/vagrant#7618]
Vagrant 1.8.1 becoming unresponsive to commands and won't halt or force halt. Happens when I need to setup a new project inside a VM. To resolve I need to restart the machine.

**Comment by akoerner** [comment]
Fix your post and provide the requested information from the template.  You have not given enough information.

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by jesse-cohen** [comment]
Hi @sethvargo - It's going to be challenging to get the debug information when it freezes any terminal command from being called. I'm aware the issue is somewhat verbose. Is this a known issue you are aware of?

**Comment by sethvargo** [comment]
Hi @jesse-cohen 

You can start Vagrant in [debug mode](https://www.vagrantup.com/docs/other/debugging.html) and send us up to the freeze. Additionally, you have supplied no system information, no guest information, no Vagrantfile, and no reproduction steps. The template that appears when you open a new issue is not just for show 😄 - we need that information to help diagnose the issue, reproduce it, and ultimately fix it.

**Comment by jesse-cohen** [comment]
Ok @sethvargo - i'll close this issue and when it reforms let you know :)
