### ISSUE TITLE
Please update online documentation

### ISSUE THREAD

**Issue by oleyka** [mitchellh/vagrant#7620]
As per the CHANGELOG, vagrant 1.8.5 supports VirtualBox 5.1, yet the online docs still say 4.0.x <= V <= 5.0 https://www.vagrantup.com/docs/virtualbox/

PS: Is there a chance that vagrant would have a versioned documentation, similar to [git](https://git-scm.com/docs/git-init)?  Asking for a friend...

**Comment by sethvargo** [comment]
We are working on versioned docs, but it's something we need to tackle across all the open source projects.
