### ISSUE TITLE
"Beware of system package managers!" in installation docs is FUD

### ISSUE THREAD

**Issue by vdh** [mitchellh/vagrant#7622]
The phrase ["Beware of system package managers!"](https://github.com/mitchellh/vagrant/blob/1f88a9737369eda3dede0d3aeb30928adf82a9f7/website/source/docs/installation/index.html.md#L32) in the [Installation documentation](https://www.vagrantup.com/docs/installation/) is very disingenuous towards package managers.

If one or more distros are known to have issues with bad packages, this docs warning should list them, and the distro's maintainers should be notified of their error. Claiming all package managers are unable to manage an installation without referencing the actual issues or problematic maintainers is needlessly bad-mouthing every other package manager.

[Homebrew Cask](https://caskroom.github.io/) on Mac for example, makes use of Vagrant's installer DMG directly. There are no issues with using this "package manager" to install Vagrant.

**Comment by sethvargo** [comment]
Hi @vdh 

We publish official installers and those are the only installers we are able to support at this time. I understand we may make a generalization, but it's impossible to list all the bad package managers, and that list may change over time. We do not support any installation methods other than those on https://www.vagrantup.com/downloads.html or those from releases.hashicorp.com.

The intention is certainly not to bash package managers - they are great! But getting the Ruby + Dependency situation correct is very difficult. This is also not unique to Vagrant - Chef and Puppet all publish their own packages. We have an issue tracking official apt/yum repos on mitchellh/vagrant-installers which you might be interested in following.

I totally hear your concerns, and we are working on making the installation a smoother experience. Until that time, we are warning users to stick with the official installers. Thanks and have a great day!
