### ISSUE TITLE
Update changelog for vagrant-vmware-fusion

### ISSUE THREAD

**Issue by jstortz** [mitchellh/vagrant#7628]
I recently updated my plugins and noticed vagrant-vmware-fusion plugin version 4.0.10, but the latest mentioned in the changelog is 4.0.8, located here:

https://github.com/hashicorp/vagrant-plugin-changelog

I don't see a place to record an issue over at that repo so I am doing so here asking that the changes be supplied.

Thanks,
Jason

**Comment by sethvargo** [comment]
Thanks! We'll get it updated on Monday.
