### ISSUE TITLE
Halt is broken for OpenBSD

### ISSUE THREAD

**Issue by toy** [mitchellh/vagrant#7634]
OpenBSD requires `-h` key alongside `-p` for shutdown. Breaking change was introduced in 5a372a9942f8c3e40a4987d54679bbd439727b82

### Vagrant version
1.8.5

### Guest operating system
OpenBSD 5.5

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'tmatilai/openbsd-5.5'
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
```

### Expected behavior
The machine is halted.

### Actual behavior
The machine is not halted and the output is:
```
==> default: Attempting graceful shutdown of VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/shutdown -p now

Stdout from the command:



Stderr from the command:

shutdown: switch -p must be used with -h.
usage: shutdown [-] [-dfhknpr] time [warning-message ...]
```

### Steps to reproduce
1. Given vagrant 1.8.5 and `Vagrantfile` as in example
2. `vagrant up`
3. `vagrant halt`

**Comment by chrisroberts** [comment]
Fixed via #7701. Thanks for the report!
