### ISSUE TITLE
reopen #2779

### ISSUE THREAD

**Issue by riotejas** [mitchellh/vagrant#7635]
Request to reopen https://github.com/mitchellh/vagrant/issues/2779
See comments since 2779 was closed 2 years ago

**Comment by sethvargo** [comment]
Hi @riotejas 

We generally do no re-open issues, especially ones that are two years old with many releases and changes between. If this is still an issue, we kindly ask that you open a new issue and supply the required information in the template that pops up. Thanks and have a great day! 😄

**Comment by v1k0d3n** [comment]
i understand wanting to keep an issues queue down, but t's really unfortunate that #2779 can't be _referenced_ as a still-outstanding issue.
