### ISSUE TITLE
Vagrant hangs when trying to use smb share

### ISSUE THREAD

**Issue by elricdesigns** [mitchellh/vagrant#7636]
Having trouble starting a vagrant SMB share on windows. (I need to use symlinks in my project.)  It hangs at "Selecting an IO". Below are the details, hoping someone has some hints how to get past this point.  Not specifying the synced_folder type starts vagrant ok.  For vagrant ssh communication I installed git.

SYSTEM:
Microsft surface pro 3
Windows 10 Insider Preview build 14372.rs1
Virtualbox 5.1.2
Vagrant 1.8.5
Ruby version: 2.2.3 / RubyGems version: 2.4.5.1
RUN IN:
PowerShell: PSVersion 5.1.14372

VAGRANTFILE:
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.network :forwarded_port, guest: 80, host: 8080
    config.vm.synced_folder "./", "/home/app", group: "www-data", type: 'smb', mount_options: ["mfsymlinks,dir_mode=0775,file_mode=0664"]
end

PARTIAL OUTPUT:
...
 INFO warden: Calling IN action: #VagrantPlugins::SyncedFolderNFS::ActionCleanup:0x4b13410
DEBUG host: Searching for cap: nfs_prune
DEBUG host: Checking in: windows
 INFO nfs: Host doesn't support pruning NFS. Skipping.
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::SyncedFolderCleanup:0x4abf2d8
 INFO subprocess: Starting process: ["C:\WINDOWS\System32\WindowsPowerShell\v1.0\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "$PSVersi
onTable.PSVersion.Major"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 5

-HANGS AT THIS POINT-

FULL DEBUG:

[vagrant_debug.log.txt](https://github.com/mitchellh/vagrant/files/382040/vagrant_debug.log.txt)

I already looked at these related bugs, but they did not resolve the issue:
https://github.com/mitchellh/vagrant/issues/3257
https://github.com/mitchellh/vagrant/issues/3894
https://github.com/mitchellh/vagrant/issues/4004

---

With vagrant 1.7.4:
...
 INFO host: Detected: windows!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: machine_action_up #Vagrant::Action::Builder:0x38fdc30
 INFO warden: Calling IN action: #VagrantPlugins::HyperV::Action::CheckEnabled:0x3d88a60
 INFO interface: output: Verifying Hyper-V is enabled...
 INFO interface: output: ==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is enabled...
 INFO subprocess: Starting process: ["C:\WINDOWS\System32\WindowsPowerShell\v1.0\/powershell.EXE", "-NoProfile", "-ExecutionPolicy", "Bypass", "&('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.4\plugins\providers\hyperv\scripts\check_hyperv.ps1')", "-ErrorAction", "Stop"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: ===Begin-Output===
{
    "result":  false
}
===End-Output===
- HANGS HERE -

**Comment by Dimasdanz** [comment]
I think we have [the same issue (#7511)](https://github.com/mitchellh/vagrant/issues/7511)  
Pretty sure it relates to the PowerShell version since it's working on PS 5.0.x

**Comment by sXe79** [comment]
I'm experiencing same issues with SMB shared folders, I'm on Windows 10 Anniversary Update (Hyper-V provider) that brings PowerShell 5.1. I can't even get the IP from the VM
Before the Anniversary update worked fine, I assume there's something wrong with PowerShell 5.1?

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
