### ISSUE TITLE
Vagrant provisioner running same script on all the vms

### ISSUE THREAD

**Issue by iam404** [mitchellh/vagrant#7638]
### Vagrant version
vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.5

### Host operating system
Description:	Ubuntu 16.04 LTS

### Guest operating system
Description:	Ubuntu 14.04 LTS

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 # Ubuntu 14.04 64 bit
  config.vm.define "app" do |trusty|
    trusty.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
    trusty.vm.box = "ubuntu/trusty64"
    trusty.vm.network "forwarded_port", guest: 80, host: 83
    trusty.vm.network "private_network", ip: "192.168.33.124"
    trusty.ssh.forward_agent = true
    config.vm.provision "shell", path: "script_1.sh"
  end

  config.vm.define "app2" do |trusty|
    trusty.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
    trusty.vm.box = "ubuntu/trusty64"
    trusty.vm.network "forwarded_port", guest: 80, host: 84
    trusty.vm.network "private_network", ip: "192.168.33.125"
    trusty.ssh.forward_agent = true
    config.vm.provision "shell", path: "script_2.sh"
  end
end
```

Above I am trying to spawn 2 vagrant instance app & app2. Now when `app` load it should run script_1.sh and when `app2` load it should run script_2.sh.
But every time when I do `vagrant up` .. script_1.sh and script_2.sh combine run on both the vms. Means script_1.sh and script_2.sh both runs on app (and also on app2 ).

Any idea ?

**Comment by sethvargo** [comment]
Hi @iam404 

Thank you for opening an issue, and sorry this is causing you troubles. This is the expected behavior, because you are running those scripts with `config.vm.provision` instead of `.trusty.vm.provision` or using [overrides](https://www.vagrantup.com/docs/providers/configuration.html).

**Comment by iam404** [comment]
Thank you @sethvargo  . That solved the purpose.
