### ISSUE TITLE
Minor: Confusingly mentioning `SSH` in the output when connector is set to `winrm`: Waiting for SSH to become available...

### ISSUE THREAD

**Issue by uvsmtid** [mitchellh/vagrant#7641]
### Vagrant version

Vagrant 1.8.5

### Host operating system

Fedora 24 x86_64

### Guest operating system

Windows Server 2012 R2

### Vagrantfile

This `Vagrantfile` can be used:
https://github.com/uvsmtid/vagrant-boxes/blob/develop/windows-server-2012-R2-gui/Vagrantfile
The Vagrant box is not published, however, it is not that relevant because it is reproducible with any `Vagrantfile` where `winrm` is used instead of `ssh`.

### Debug output

```
...
 INFO interface: info: Waiting for SSH to become available...
 INFO interface: info: ==> win_serv_2012R2_minion: Waiting for SSH to become available...
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: libvirt
DEBUG ssh: Checking key permissions: /home/uvsmtid/.vagrant.d/insecure_private_key
DEBUG winrmshell: initializing WinRMShell
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 192.168.121.253
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: Administrator
 INFO winrmshell:   - Transport: negotiate
DEBUG winrmshell: [WinRM] opening remote shell on http://192.168.121.253:5985/wsman
DEBUG winrmshell: [WinRM] remote shell E61B7680-AE95-40EC-8B41-199ACEB8FB4A is open on http://192.168.121.253:5985/wsman
DEBUG winrmshell: Output: {:data=>[{:stdout=>"WIN-O0603JH5D6C"}, {:stdout=>"\r\n"}], :exitcode=>0}
 INFO winrm: WinRM is ready!
...
```

### Expected behavior

It should mention `WinRM` if it is configured instead of `SSH`:
```
 INFO interface: info: Waiting for WinRM to become available...
```

### Actual behavior

It mentions `SSH`:
```
 INFO interface: info: Waiting for SSH to become available...
```

### Steps to reproduce

Just run `vagrant up` with `winrm` configured as communicator for Windows box.

### References

The confusing output always requires more steps to rule out case like misconfiguration of `winrm` (when it is actually fine). For example, only debug output in issue #4600 shows that Vagrant actually uses `winrm` internally while it still prints `SSH` by default.

**Comment by austinlparker** [comment]
@uvsmtid - This actually looks like it's a problem in your provider, not base vagrant. 

https://github.com/vagrant-libvirt/vagrant-libvirt/blob/a963ff4c70f5e6ce5bc2589b7e98c1c0671e2ccc/locales/en.yml

The locale file doesn't seem to differentiate between WinRM and SSH.

**Comment by uvsmtid** [comment]
@austinlparker , thank you! I've [re-opened it there](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/635).

**Comment by chrisroberts** [comment]
Closing as underlying issue is within libvirt plugin
