### ISSUE TITLE
Windows 10 : `mkdir': Invalid argument @ dir_s_mkdir

### ISSUE THREAD

**Issue by LR3my** [mitchellh/vagrant#7644]
### Vagrant version
Vagrant version :  1.8.5

### Host operating system
Windows 10 Family Edition

**When I run vagrant init cmd I get this error :** 
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Invalid argument @ dir_s_mkdir - C:/Users/Laetitia R?my (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:210:in `each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:771:in `block in setup_home_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:766:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:766:in `setup_home_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:129:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:165:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:165:in `<main>'

Any idea what should I do to solve this ?

**Comment by gtirloni** [comment]
I'm under the impression that non-ASCII characters in your path could be causing an issue under Ruby 2.2.0 that is used by Vagrant.

My suggestion as a fellow end user is to try to run `vagrant init` in a different directory outside our home folder (preferably one without non-ASCII characters).

**Comment by sethvargo** [comment]
Hi there,

This is a known issue and unfortunately there is nothing we can do. You have a special character (non-ascii) in your path such as an accent character or unicode symbol. This causes Ruby, the underlying programming language, to freak out. Sorry!

**Comment by valeriacavalcanti** [comment]
Add VAGRANT_HOME

**Comment by LR3my** [comment]
I manage to make it work with Vagrant 1.7.4 and Virtualbox 5.0.26. 
I wasn't running any vagrant cmd in my home directory, actualy I'm running it in D:\vm 

Anyway it work with an older vagrant version  :/
