### ISSUE TITLE
Backporting fix for #6775 to vmware_workstation ?

### ISSUE THREAD

**Issue by cournape** [mitchellh/vagrant#7652]
I see the exact same issue as reported in #6775, but using a linux host:

```
$ vagrant --version
1.8.1
$ vagrant plugin list
winrm (1.3.6)
vagrant-salt (0.4.0)
vagrant-share (1.1.5, system)
vagrant-vmware-workstation (4.0.7)
```

**Comment by sethvargo** [comment]
Hi @cournape,

vagrant-vmware-workstation 4.0.10 was released with the fusion version. Can you please try upgrading? https://gems.hashicorp.com/

**Comment by cournape** [comment]
Hi @sethvargo 

I should have specified: I did a `vagrant plugins update`, with vagrant telling me all plugins are up to date.

**Comment by sethvargo** [comment]
Hi @cournape 

That might be a separate bug, but can you try running `vagrant plugin update vagrant-vmware-workstation`?

**Comment by cournape** [comment]
I tried that as well, to no effect.

**Comment by sethvargo** [comment]
Hrm - are you behind a proxy or anything? Do you see the updated gems on gems.hashicorp.com in your browser? You might try uninstalling and re-installing it.

**Comment by cournape** [comment]
removing and reinstalling it did it. Am now testing a new VM w/ open-vm-tools installed

**Comment by cournape** [comment]
looks like rhel 7 open vm tools does not include the required vmhgfs-fuse after all, so this was all for nothing :( But this is not a vagrant issue anymore.

Do you want me to open an issue for the non-updating plugin ?

**Comment by chrisroberts** [comment]
Closing as the underlying issue was within open-vm-tools
