### ISSUE TITLE
Cat does not work when TMPDIR is set to syncfolder

### ISSUE THREAD

**Issue by Usha-Kuchibhotla** [mitchellh/vagrant#7660]
### Vagrant version
Vagrant 1.8.1

### Host operating system
OS X Yosemite v 10.10.5

### Guest operating system
Centos

### Expected behavior
If TMPDIR is set to syncedfolder, cat should work

### Actual behavior
If TMPDIR is set to synced folder, cat throws a "NO such file or directory" error

### Steps to reproduce
1. syncfolders to /home/bm
2. Run following 
> `
#!/bin/bash
TMPDIR=/home/bm
cat <<EOF
abc
EOF
`

3. Gives "cat: -: No such file or directory"

**Comment by sethvargo** [comment]
Hi @Usha-Kuchibhotla 

Thank you for opening an issue. Unfortunately there is not enough information here to reproduce the issue. Could you please share your Vagrantfile and the output in debug mode? It's unclear where you are setting TMPDIR and where you are running this command.

**Comment by Usha-Kuchibhotla** [comment]
Hi @sethvargo Please find the details below.

Vagrantfile 
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.8"
  config.vm.synced_folder "test", "/home/vagrant"
end

In the test folder I have the following file, test.sh
#!/bin/bash
TMPDIR=/home/vagrant
cat <<EOF
abc
EOF

ukuchibhot-wsm:test ukuchibhotla$ vagrant ssh
vagrant@127.0.0.1's password: 
-bash-4.1$ ./test.sh 
cat: -: No such file or directory

Expected output: abc

**Comment by Usha-Kuchibhotla** [comment]
Hi, We found https://www.virtualbox.org/ticket/12640, looks like a VB issue.

**Comment by sethvargo** [comment]
Closing as upstream
