### ISSUE TITLE
vagrant up fails to set IP address of CentOS 5.7 box

### ISSUE THREAD

**Issue by mpeters** [mitchellh/vagrant#7664]
### Vagrant version
Vagrant 1.8.3

### Host operating system
Mac OSX 10.10.5

### Guest operating system
CentOS 5.7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "hansode/centos-5.7-i386"

    config.vm.define "foo" do |foo|
        foo.vm.network "private_network", ip: "192.168.1.10"
    end
end
```

### Debug output
https://gist.github.com/mpeters/79ab371fa35d90081c7c33699e09fa45

### Expected behavior
It should bring up the vm without an error.

### Actual behavior
It errors out because the generated script that sets the IP address seems to not be able to find the device name to use when setting it. The `/sbin/ifdown '' || true` should have something in the quotes. It also fails in the same way if you try to use dhcp instead of making the IP static. If you comment out the line that sets the IP address it works, but that's not a workable solution with multiple vms.

### Steps to reproduce
1. vagrant up

**Comment by mpeters** [comment]
I just tried this in vagrant 1.8.5 and it seems to be fixed.

**Comment by chrisroberts** [comment]
Closing this up as issue is resolved.
