### ISSUE TITLE
Docker for Windows guest containers synced folders empty

### ISSUE THREAD

**Issue by royalaid** [mitchellh/vagrant#7672]
### Vagrant version: 
1.8.5
### Host operating system: 
Windows 10
### Guest operating system: 
Docker for Windows running [ nineseconds/docker-vagrant](https://github.com/9seconds/docker-vagrant)
### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
    config.ssh.username = "root"
    config.vm.provider "docker" do |d|
        # The name of the image to use
        d.image = "nineseconds/docker-vagrant"
		d.has_ssh = true
        d.force_host_vm = false
    end
    config.ssh.insert_key = false
    config.ssh.port = 2222
    config.ssh.host = "localhost" 
    config.vm.synced_folder ".", "/root/ta_done"
    config.vm.synced_folder "~/.m2", "/root/.m2"
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 3449, host: 3449
end 
```

### Debug output:
https://gist.github.com/royalaid/7bcff3cde40ced0dae0ef3739e8ad886

### Expected behavior
Folders should mount and have host folder contents

### Actual behavior
Folders appear in guest container but are empty

### Steps to reproduce
1. `vagrant up`
2. `vagrant ssh`
3. `ls /root/ta_done`

**Comment by fifthecho** [comment]
@royalaid: Do you have Shared Folders enabled in Docker for Windows?
I have this working with 

```
config.vm.define "core" do |v|
    v.vm.synced_folder "#{Dir.pwd}", "/srv/app/current"
    v.vm.provider 'docker' do |d|
      d.force_host_vm = false
      d.build_dir = '.'
      d.build_args = ['--tag=core']
      d.ports = ['3000:3000']
      d.link('core_redis:redis')
      d.link('core_mongo:mongo')
    end
```

And my C: drive shared in Docker.
<img width="620" alt="dockerconfig" src="https://cloud.githubusercontent.com/assets/1186580/17678770/8a8ce67e-6306-11e6-9f63-aed0f32e9665.png">

**Comment by chrisroberts** [comment]
@royalaid did https://github.com/mitchellh/vagrant/issues/7672#issuecomment-239921472 resolve the issue for you?

**Comment by royalaid** [comment]
Yup! Sorry I didn't reply earlier.

**Comment by chrisroberts** [comment]
Awesome. Thanks for the update!
