### ISSUE TITLE
Vagrant up Forcing shutdown and teardown of VM on first boot after sysprep reboots vm (possible bug?)

### ISSUE THREAD

**Issue by robbiepc30** [mitchellh/vagrant#7680]
### Vagrant version

Vagrant 1.8.5
### Host operating system

OS X El Capitan 10.11.5 running Parallels Version 11.2.1
### Guest operating system

Windows Server 2012R2
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "t"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
end
```
### Debug output

The complete debug log: https://gist.github.com/robbiepc30/6a1d061e16d8325380ee8d656bf7aedd

I think the problem is here 

```
WinRM starts to connect ... I think it starts to initialize a connection 

Lines 8774 - 8796

DEBUG winrmshell: initializing WinRMShell
 INFO interface: detail: WinRM address: 10.211.55.66:5985
 INFO interface: detail:     default: WinRM address: 10.211.55.66:5985
    default: WinRM address: 10.211.55.66:5985
 INFO interface: detail: WinRM username: vagrant
 INFO interface: detail:     default: WinRM username: vagrant
    default: WinRM username: vagrant
 INFO interface: detail: WinRM execution_time_limit: PT2H
 INFO interface: detail:     default: WinRM execution_time_limit: PT2H
    default: WinRM execution_time_limit: PT2H
 INFO interface: detail: WinRM transport: negotiate
 INFO interface: detail:     default: WinRM transport: negotiate
    default: WinRM transport: negotiate
 INFO winrm: Checking whether WinRM is ready...
DEBUG provider: Searching for cap: winrm_info
DEBUG provider: Checking in: parallels
 INFO subprocess: Starting process: ["/usr/local/bin/prlctl", "list", "37666a95-3704-4ac1-bfb4-ab523c550a05", "--no-header", "-o", "status"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: running
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0


I think this is when the vm reboots during its initial sysprep and causes the issue.. 
It looses its WinRM connection?

Lines 8935 - 8949

DDEBUG winrmshell: initializing WinRMShell
 INFO winrmshell: Attempting to connect to WinRM...
 INFO winrmshell:   - Host: 10.211.55.66
 INFO winrmshell:   - Port: 5985
 INFO winrmshell:   - Username: vagrant
 INFO winrmshell:   - Transport: negotiate
 INFO subprocess: Starting process: ["/usr/local/bin/prlctl", "list", "37666a95-3704-4ac1-bfb4-ab523c550a05", "--no-header", "-o", "status"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: running
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
ERROR warden: Error occurred: [WSMAN ERROR CODE: 1359]: <f:WSManFault Code='1359' Machine='10.211.55.66' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='C:\Windows\system32\WsmWmiPl.dll' provider='WMI Provider'><f:WSManFault Code='1359' Machine='VAGRANT-RV25QM9' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>HRESULT = 0x8004100A</f:Message></f:WSManFault><f:ExtendedError><p:__ExtendedStatus xmlns:cim='http://schemas.dmtf.org/wbem/wscim/1/common' xmlns:p='http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/__ExtendedStatus' xsi:type='p:__ExtendedStatus_Type' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'><p:Description xsi:nil='true' xsi:type='cim:cimString'/><p:Operation xsi:type='cim:cimString'>ExecQuery</p:Operation><p:ParameterInfo xsi:type='cim:cimString'>select version from Win32_OperatingSystem</p:ParameterInfo><p:ProviderName xsi:type='cim:cimString'>WinMgmt</p:ProviderName><p:StatusCode xsi:nil='true' xsi:type='cim:cimUnsignedInt'/></p:__ExtendedStatus></f:ExtendedError></f:ProviderFault></f:Message></f:WSManFault>
 INFO warden: Beginning recovery process...

 ... further down the log, forces the vm to shutdown and tears it down

 Lines 9177 - 9185

 INFO interface: info: Forcing shutdown of VM...
 INFO interface: info: ==> default: Forcing shutdown of VM...
==> default: Forcing shutdown of VM...
 INFO subprocess: Starting process: ["/usr/local/bin/prlctl", "stop", "37666a95-3704-4ac1-bfb4-ab523c550a05", "--kill"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: Stopping the VM...
DEBUG subprocess: stdout: The VM has been forcibly stopped
```
### Expected behavior

What should have happened?

I would expect the vm to be brought up, allowed to complete and finsh the sysprep process which may require a reboot or two and then connect via WinRM
### Actual behavior

What actually happened?

It seems like the vm is booted up for the first time and WinRM starts to connect. A reboots caused by the initial sysprep causes vagrant to loose WinRM connection.  Vagrant then forces the vm to stop and tears it down.
### Steps to reproduce

I would have to upload the box to Atlas to probably do this.
From my investigations this is caused on a windows vagrant box that needs to reboot during its initial sysprep. 
1. Vagrant establishes or (starts to establish, hard for me to read the verbose output of the log... new to vagrant) a WinRM connection during the initial boot
2. Sysprep then causes the vm to reboot, vagrant looses its connection and then tears down the vm.
This is my best guess for now.

**Comment by jpuskar** [comment]
+1; same steps to repro and error. Couple coworkers too. Problem is intermittent -- seems like a race condition with WinRM and the sysprep reboot.

**Comment by StefanScherer** [comment]
I have the same problem with Vagrant 1.8.5 + VMware Workstation Pro 12.1 on Windows 7 Enterprise Host spinning up a Windows 2012 R2 guest that uses `sysprep` for the packer shutdown command. This is needed to have different SID's for each VM if you build a Windows domain environment.

My next approach will be setting the WinRM service to startup type "automatic (delayed)" so the WinRM port will not be open on first boot until sysprep reboots the VM.
Only disadvantage is that the second boot after the sysprep also uses this delayed startup type, so provisioning will start after about 120 seconds.

**Comment by psprowls** [comment]
@Mwrock has a great solution for this issue in his latest 2016 chef template (Admittedly, I am just trying it right now on Win 10).  He has a bat file to run as the shutdown command.   It disables the firewall exception for WinRM:

'netsh advfirewall firewall set rule name="WinRM-HTTP" new action=block
 C:/windows/system32/sysprep/sysprep.exe /generalize /oobe /unattend:C:/Windows/Panther/Unattend/unattend.xml /quiet /shutdown`

Then he also creates "C:/Windows/setup/scripts/SetupComplete.cmd" that re-enables the firewall rule...

`netsh advfirewall firewall set rule name=\"WinRM-HTTP\" new action=allow`

Here are his comments...

On first boot, the WinRM and other services are starting
and stopping and restarting and somewhere in the middle of
all of that vagrant finds that WinRM is accessible but
something is shutdown in the middle of its connection attempt
sometimes resulting in an error.
 
To work around this we disable the WinRM firewall in the
shutdown command and turn it back on in SetupComplete.cmd
file. This way while the box is going through its first boot
cycles of restarting services, it cant get to WinRM.
Then once its fully up it runs SetupComplete and the WinRM
port is made accessible.

**Comment by cdaf** [comment]
Thanks, this was a key missing ingredient. I'm working on building a 2016 image and this was a big stumbling block. I'm guessing @Mwrock has created his own rule, I used the default rule as follows...

```
mkdir -Path $env:windir/setup/scripts/
Add-Content $env:windir/setup/scripts/SetupComplete.cmd 'netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-in)" new action=allow'
netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-in)" new action=block
```

**Comment by chrisroberts** [comment]
It looks to me like the approach defined in the last two comments are likely the best resolution to this issue. Any resolution that I can see within Vagrant itself would require detection implementation of the guest actually being ready when the winrm connection becomes available and then allowing it to drop and reconnect. It definitely seems not only much easier (implementation wise) but also much less error prone for winrm to not be available to Vagrant until the system is actually ready. And that is what these last two comments describe.

If I am mistaken in my assessment or if there is any other input on this, please feel free to open a new issue and we can re-investigate.

Cheers!

**Comment by sovetov** [comment]
Or:
```
echo winrm quickconfig -quiet -force > %WINDIR%\Setup\Scripts\SetupComplete.cmd
```
Rules and service are disabled by default, `quickconfig` might be done at this step.
