### ISSUE TITLE
Vagrant: The SSH connection was unexpectedly closed by the remote end.

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#7681]
I've Jenkins CI with a lot of tasks for provisioning separate fresh VM instances on AWS.

Usually I don't have problems when running jobs one by one, the error rarely happens.

However the more tasks I run at the same time, the more likely I've the failures. The SSH failures happens in the middle of provisioning script. E.g.

```
$ vagrant provision
...
00:58:36.903 ==> MT-aws: Checking logs (part of shell script)...
01:01:51.919 The SSH connection was unexpectedly closed by the remote end. This
01:01:51.919 usually indicates that SSH within the guest machine was unable to
01:01:51.919 properly start up. Please boot the VM in GUI mode to check whether
01:01:51.919 it is booting properly.
01:01:53.213 Build step 'Execute shell' marked build as failure
```

```
$ vagrant --version
Vagrant 1.8.1
kenorb@Ubuntu-1604-xenial-64-minimal:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```
- I'm expecting long builds like few hours.
- The error happens after a short while or after some period of time (like after 1h).
- I've VPS with 2 core CPU, 8GB RAM, SSD with high-speed network availability min. 99%, so the changes for network issues are very low.
- The server is used only for running vagrant instances.

See my: [`Vagrantfile`](https://github.com/EA31337/FX-MT-VM/blob/master/Vagrantfile)

Q: Is there any change that this issue may be on the Vagrant side and can be fixed there (like it should re-try 3-5 times after failure)? Or I've to reconfigure my SSH settings?

**Comment by chrisroberts** [comment]
Hi! Please add a keep_alive line to your configuration:

```ruby
config.vm.ssh.keep_alive = true
```

If that does not fix the issue, please feel free to reopen or create a new issue. Thanks!
