### ISSUE TITLE
Unable to use URL-based config.vm.box in Windows

### ISSUE THREAD

**Issue by mfenniak** [mitchellh/vagrant#7682]
### Vagrant version

Vagrant 1.8.5
### Host operating system

Windows Server 2008 R2
### Guest operating system

Ubuntu 16.04
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "https://s3-us-west-2.amazonaws.com/replicon-packer-artifacts/devvm/devvm-virtualbox-v4.box"
end
```
### Debug output

https://gist.github.com/mfenniak/2e373e51b943997145e20c796aa67b66
### Expected behavior

vagrant box should be downloaded from s3, and started up in VirtualBox
### Actual behavior

Error occurred while running 'vagrant up':

```
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:527:in `rename': No such file or directory @ sys_fail2 - (C:/Users/mathieu.fenniak/.vagrant.d/tmp/vagrant-box-add-temp-20160804-4956-1go8ap4/packer-ubuntu-16.04-amd64-disk1.vmdk, C:/Users/mathieu.fenniak/.vagrant.d/boxes/https-VAGRANTCOLON--VAGRANTSLASH--VAGRANTSLASH-s3-us-west-2.amazonaws.com-VAGRANTSLASH-replicon-packer-artifacts-VAGRANTSLASH-devvm-VAGRANTSLASH-devvm-virtualbox-v4.box/0/virtualbox/packer-ubuntu-16.04-amd64-disk1.vmdk) (Errno::ENOENT)
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:527:in `block in mv'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
    from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
...
```
### Steps to reproduce
1. Run 'vagrant up' with the provided Vagrantfile, which references a .box stored in S3.  The box is publicly accessible.

My guess is that the long path created for the .vagrant.d storage of the box is exceeding MAX_PATH; the file name involved in the rename ("C:/Users/mathieu.fenniak/.vagrant.d/boxes/https-VAGRANTCOLON--VAGRANTSLASH--VAGRANTSLASH-s3-us-west-2.amazonaws.com-VAGRANTSLASH-replicon-packer-artifacts-VAGRANTSLASH-devvm-VAGRANTSLASH-devvm-virtualbox-v4.box/0/virtualbox/packer-ubuntu-16.04-amd64-disk1.vmdk") is 260 characters long.

**Comment by dragon788** [comment]
You are probably right that the long path is breaking stuff, but you can also supply a box_name even when you supply the URL which may avoid this issue.

**Comment by mfenniak** [comment]
Thanks @dragon788; I wasn't aware of that option, and it does provide a functional workaround for this issue.

**Comment by chrisroberts** [comment]
Closing as fixed using `box_url` with `box` to define name.
