### ISSUE TITLE
Chef Solo does not install on precise32 box in Vagrant 1.8.5

### ISSUE THREAD

**Issue by semmypurewal** [mitchellh/vagrant#7689]
### Vagrant version
1.8.5. This issue does not repro with Vagrant 1.8.4 or prior

### Host operating system
MacOS El Capitan (10.11.5)

### Guest operating system
The provided "precise32" box.

### Vagrantfile
```ruby
Vagrant::Config.run do |config|
  config.vm.box = "precise32"

  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "apache"
  end
end
```
### Debug output
https://gist.github.com/semmypurewal/5795f2b280eb2ef80f2f359c838cdd43

### Expected behavior
The Chef Solo provisioner should run.

### Actual behavior
Chef doesn't install correctly. Vagrant exits with the following error message

```
error: Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.
```

Note that the 'apache' recipe is arbitrary. This reproduces with every recipe I've tried.

### Steps to reproduce
1. Run `vagrant up` with the provided VagrantFile.

### References

https://github.com/semmypurewal/LearningWebAppDev/issues/78

**Comment by chrisroberts** [comment]
Hi! This is a known issue with the ubuntu guest detection and has been fixed in #7524 which will be included in the next release. Downgrading to v1.8.4 will allow for proper detection until the next release is available. Thanks!
