### ISSUE TITLE
Vagrant cannot configure networks for Ubuntu Precise 12.04

### ISSUE THREAD

**Issue by singingwolfboy** [mitchellh/vagrant#7691]
It seems that the latest version of Vagrant is unable to configure networks on Ubuntu Precise 12.04 -- specifically, using the box file available at `http://files.vagrantup.com/precise64.box`. I've trimmed this down to a minimal, reproducible test case.

I'm running into this problem with the [Open edX Devstack](https://openedx.atlassian.net/wiki/display/OpenOPS/Running+Devstack), which uses Vagrant. The official recommendation from edX seems to be "use an older version of Vagrant", but I wanted to report this bug to make sure the Vagrant community was aware.

Vagrant version: 1.8.5
VirtualBox version: 5.1.2r108956
Host OS: Mac OS X 10.11.6
Guest OS: Ubuntu Precise 12.04
[Debug output as GitHub Gist](https://gist.github.com/singingwolfboy/75f4cbe9e1beb39499d9466a776ca1c9)

Vagrantfile:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box     = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :private_network, ip: "192.168.33.10"
end
```

Expected behavior: Vagrant successfully creates the virtual machine and configures the private network.
Actual behavior: Vagrant successfully creates the virtual machine, but when it tries to configure the private network, it claims that the guest OS doesn't have the 'configure_networks' capability, which causes the `vagrant up` process to fail.

### Steps to reproduce
1. Ensure you are running the versions of Vagrant and VirtualBox listed above
2. Create a new directory on your computer, and create a Vagrantfile with the contents listed above
3. Run `vagrant up` in that directory

Note: I just tried downgrading to Vagrant 1.8.1 with VirtualBox 5.0.26r108824, and I was able to get the test case to run without failures. I haven't tried any other versions.

**Comment by pwnage101** [comment]
confirming bug on my machine:

Vagrant version: 1.8.5
VirtualBox version: 5.0.24-dfsg-1~bpo8+1 (jessie-backports)
Host OS: Debian 8
Guest OS: Ubuntu Precise 12.04

`vagrant up` output: https://gist.github.com/pwnage101/976c3c846e38a508eb6cba2a10d7d80b

**Comment by chrisroberts** [comment]
Hi! This is a known issue with the ubuntu guest detection and has been fixed in #7524 which will be included in the next release. Thanks!

**Comment by singingwolfboy** [comment]
@chrisbaldauf: thanks for taking a look at this, but this fix doesn't actually work. For one thing, I just opened up the `/opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/guests/ubuntu/guest.rb` file on my computer, installed by Vagrant 1.8.5, and discovered that it _already_ includes the change from #7524 -- are you sure that the change isn't supposed to go out until the next release?

Another problem is that Ubuntu 12.04 doesn't actually have an `/etc/os-release` file. You can verify this by starting an Ubuntu 12.04 machine through Vagrant, letting it fail to configure properly, running `vagrant ssh`, and running `ls /etc/os-release`. I should point out that Ubuntu 12.04 is a LTS (long term support) release, and won't reach end of life until April 2017. As a result, I really hope that Vagrant would also continue to support it at least until it reaches end of life.

**Comment by chrisbaldauf** [comment]
@singingwolfboy, did you mean @chrisroberts?

**Comment by singingwolfboy** [comment]
@chrisroberts: After reverting #7524 locally, Vagrant was able to get past that error, but runs into a different problem: unable to mount VirtualBox shared folders. [Full output is here.](https://gist.github.com/singingwolfboy/ec8b84e3149ea542ae6a17094a21aee7)

**Comment by chrisroberts** [comment]
Hi @singingwolfboy. The error shown in your output is unrelated to this issue. The root of the issue in your output appears to be with the version detection of the virtualbox guest additions within the box you are using. You might try running a `vagrant down` after the error and then `vagrant up` to see if it properly detects the updated guest additions. 

Cheers!
