### ISSUE TITLE
Vargrant Down

### ISSUE THREAD

**Issue by NendoTaka** [mitchellh/vagrant#7692]
Vagrant Down needs to be a command since it is the opposite of Vagrant Up. This is only logical. Why would you name it Vagrant Halt?

**Comment by rquadling** [comment]
Also, `halt` sounds like it is a hard off. Not graceful. Though that is what it does. Or at least seems to.

**Comment by dragon788** [comment]
This is easily set up in your shell as an alias. 

Vagrant halt is named because if the machine does NOT gracefully shut down, Vagrant WILL pull the plug.

**Comment by scones** [comment]
@dragon788 No, it does not always do that. I had to interrupt the shutdown process after a few minutes and repair / destroy the machine(s) several times. Although this might be an issue itself.

As suggestion: make "down" an alias to "halt" within vagrant. Just for the symmetry (They do it with quarks, you can do it with commands ;) )

**Comment by dragon788** [comment]
Hi @scones do you have any custom logic inside your Vagrantfile or are you using a Windows VM? There are some cases where if the VM keeps SSH available and the shutdown timeout isn't set or is overridden it will hang, but typically it will timeout and force power off the VM unless it loses communication entirely with the virtualization software (I've seen this with Virtualbox quite a few times).

The problem with "down" is that vagrant supports "halt" as in "shut off" and "suspend" as in "pause to resume later", "down" is the opposite of "up" but it doesn't describe intuitively which way it is taking the VM down. Being more explicit is typically a better design, and it isn't hard to alias "down" within your shell or add a plugin that handles "vagrant down" and passes the appropriate "halt/suspend".

**Comment by chrisroberts** [comment]
Hi! Thank you for the suggestion but we will not be changing the core commands. As @dragon788 has pointed out https://github.com/mitchellh/vagrant/issues/7692#issuecomment-246015011 there is not a clear one to one relation between up and down. Creating a local alias for `vagrant down` to do what you expect it to do is likely the best solution here. Thanks!

**Comment by scones** [comment]
>  "down" is the opposite of "up" but it doesn't describe intuitively which way it is taking the VM down

In my experience "up" does not describe intuitively it's processes either. It can mean "construct the machine, boot it and provision it" or "boot the machine (optionally provision)".
Following your reasoning, there should be 2 replacements for up: "vagrant build XY" and "vagrant start XY".

Call me pedantic, but this is not clear either and "up" is called this way for convenience.
