### ISSUE TITLE
Vagrant Provision-with Not Running

### ISSUE THREAD

**Issue by DonRichards** [mitchellh/vagrant#7696]
### Vagrant version
1.8.5

### Host operating system
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31

### Guest operating system
Ubuntu 14

### Vagrantfile
```vagrant
VAGRANTFILE_API_VERSION = "2"

$cpus   = ENV.fetch("ISLANDORA_VAGRANT_CPUS", "2")
$memory = ENV.fetch("ISLANDORA_VAGRANT_MEMORY", "3000")
$hostname = ENV.fetch("ISLANDORA_VAGRANT_HOSTNAME", "trace")
$forward = ENV.fetch("ISLANDORA_VAGRANT_FORWARD", "TRUE")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  config.vm.provider "virtualbox" do |v|
    v.name = "TRACE Development VM"
  end

  unless  $forward.eql? "FALSE"
    config.vm.network :forwarded_port, guest: 8080, host: 8080 # Tomcat
    config.vm.network :forwarded_port, guest: 3306, host: 3306 # MySQL
    config.vm.network :forwarded_port, guest: 8000, host: 8000 # Apache
  end

  config.vm.hostname = $hostname
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "islandora/islandora-base"

  shared_dir = "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", $memory]
    vb.customize ["modifyvm", :id, "--cpus", $cpus]
  end

  config.vm.provision "modules", :shell, path: "./scripts/modules.sh", :args => shared_dir, :privileged => false
  config.vm.provision :shell, path: "./scripts/libraries.sh", :args => shared_dir, :privileged => false
  if File.exist?("./scripts/custom.sh") then
    config.vm.provision :shell, path: "./scripts/custom.sh", :args => shared_dir
  end
  config.vm.provision :shell, path: "./scripts/post.sh"

  if File.exist?("~/Desktop/traceCustomModule") then
    config.vm.synced_folder "~/Desktop/traceCustomModule", "/var/www/drupal/sites/all/modules/traceCustomModule", type: "rsync",
        rsync__exclude: ".git/"
  end
end
```

### Debug output
https://gist.github.com/52dd257d45940a2564c8f78b8d1355e1

### Expected behavior
Having a provision named and using this command would result in the provision being ran. 
> vagrant reload --provision-with **modules**

Also tried with the same result
> vagrant provision --provision-with modules

### Actual behavior
> Error, wrong number of arguments
> ...config/vm.rb:293:in `provision': wrong number of arguments (2 for 1) (ArgumentError)

### Steps to reproduce
1. vagrant up
2. vagrant reload --provision-with modules

### References
-- #5139

**Comment by dragon788** [comment]
You are mixing new and old syntax it appears. I don't think the `:shell` syntax is recommended anymore. I believe it should be type: "shell" instead, at least for the first instance where you are naming it "modules". You shouldn't need the additional ones as `:shell` either. See the link below and the example for current syntax.

https://www.vagrantup.com/docs/provisioning/shell.html

``

**Comment by DonRichards** [comment]
Made that change and still got the following. 
> provision': undefined method `to_sym' for #<Hash:0x000001038bda18> (NoMethodError)

**Comment by dragon788** [comment]
Can you try commenting out all but the first provision so we can isolate whether it is the file existence checks or something else? If you can also post an updated Vagrantfile snippet below your original it will make it easier to try and reproduce.

**Comment by DonRichards** [comment]
Trying to remove everything one item at a time to isolate the issue. As soon as I find it I'll post

**Comment by dragon788** [comment]
@DonRichards Something like this would be the most basic that should still work. I haven't tested, but the syntax is 98% right AFAIK.

```
VAGRANTFILE_API_VERSION = "2"
$cpus   = ENV.fetch("ISLANDORA_VAGRANT_CPUS", "2")
$memory = ENV.fetch("ISLANDORA_VAGRANT_MEMORY", "3000")
$hostname = ENV.fetch("ISLANDORA_VAGRANT_HOSTNAME", "trace")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  config.vm.provider "virtualbox" do |v|
    v.name = "TRACE Development VM"
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080 # Tomcat
  config.vm.network "forwarded_port", guest: 3306, host: 3306 # MySQL
  config.vm.network "forwarded_port", guest: 8000, host: 8000 # Apache

  config.vm.hostname = $hostname
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "islandora/islandora-base"

  shared_dir = "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", $memory]
    vb.customize ["modifyvm", :id, "--cpus", $cpus]
  end

  config.vm.provision "modules", type: "shell", path: "./scripts/modules.sh", args: shared_dir, privileged: "false"
  config.vm.provision "shell", path: "./scripts/libraries.sh", args: shared_dir, privileged: "false"
  config.vm.provision :shell, path: "./scripts/post.sh"
end
```

**Comment by DonRichards** [comment]
OK, thanks. I'll test it.

**Comment by DonRichards** [comment]
Worked thanks! 
There is no official documentation on using names instead of types? The help tickets are the only place I was able to find anything on this topic. Might be something worth adding to the documentation

**Comment by DonRichards** [comment]
In case someone comes to this feed, this is my [working version](https://github.com/utkdigitalinitiatives/TRACE/blob/master/Vagrantfile)

```Vagrantfile
VAGRANTFILE_API_VERSION = "2"

$cpus   = ENV.fetch("ISLANDORA_VAGRANT_CPUS", "2")
$memory = ENV.fetch("ISLANDORA_VAGRANT_MEMORY", "3000")
$hostname = ENV.fetch("ISLANDORA_VAGRANT_HOSTNAME", "trace")
$forward = ENV.fetch("ISLANDORA_VAGRANT_FORWARD", "TRUE")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.
  config.vm.provider "virtualbox" do |v|
    v.name = "TRACE Development VM"
  end
  
  unless  $forward.eql? "FALSE"  
    config.vm.network :forwarded_port, guest: 8080, host: 8080 # Tomcat
    config.vm.network :forwarded_port, guest: 3306, host: 3306 # MySQL
    config.vm.network :forwarded_port, guest: 8000, host: 8000 # Apache
  end
  
  config.vm.hostname = $hostname
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "islandora/islandora-base"
  
  shared_dir = "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", $memory]
    vb.customize ["modifyvm", :id, "--cpus", $cpus]
  end

  
  config.vm.provision "modules", type: "shell", path: "./scripts/modules.sh", args: shared_dir, privileged: "false"
  config.vm.provision "libraries", type: "shell", path: "./scripts/libraries.sh", args: shared_dir, privileged: "false"
  if File.exist?("./scripts/custom.sh") then
    config.vm.provision "custom", type: "shell", path: "./scripts/custom.sh", args: shared_dir
  end
  config.vm.provision "post", type: "shell", path: "./scripts/post.sh"
  
  if File.exist?("~/Desktop/traceCustomModule") then
    config.vm.synced_folder "~/Desktop/traceCustomModule", "/var/www/drupal/sites/all/modules/traceCustomModule", type: "rsync",
        rsync__exclude: ".git/"
  end
end
```

**Comment by dragon788** [comment]
Hi Don,
It is there, but it is under a subsection/page and not the main "Provisioner" if I remember right. I actually submitted a pull request to correct an example after the change from `:shell` type to `"shell"`, I'll take a look and see if I can find a better way to demonstrate the named/assumed types. What page of the documentation were you referencing when updating the Vagrantfile?

If you think this issue is resolved you can close it yourself or let @sethvargo know and he can close it for you with a note about the documentation.

**Comment by DonRichards** [comment]
If you're talking about this
---
## [SHELL PROVISIONER](https://www.vagrantup.com/docs/provisioning/shell.html)
### Provisioner name: "shell"
---
This looks like it's talking about shell not a arbitrary naming convention the user can create. 

[The first page I went to had the `:shell` instead of the `"shell"`](https://www.vagrantup.com/docs/cli/provision.html#_provision_with_x_y_z)
```text
--provision-with x,y,z - This will only run the given provisioners. For example, if you have 
a :shell and :chef_solo provisioner and run vagrant provision --provision-with shell, 
only the shell provisioner will be run.
```

I would assume this is closed. Just thought it could use more clarification on the documentation.
