### ISSUE TITLE
config/loader.rb - Message: TypeError: no implicit conversion of Pathname into String

### ISSUE THREAD

**Issue by danshumaker** [mitchellh/vagrant#7697]
vagrant version 1.8.5
host OS: OSX 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

guest: ailispaw-rancheros-lite 0.9.2

After upgrading to 1.8.5 I get this error when doing a vagrant up:
```
Path: /Users/dan/.vagrant.d/boxes/ailispaw-VAGRANTSLASH-rancheros-lite/0.9.2/virtualbox/Vagrantfile
Line number: 0
Message: TypeError: no implicit conversion of Pathname into String
 INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantfileLoadError", "There was an error loading a Vagrantfile. The file being loaded\nand the error message are shown below. This is usually caused by\na syntax error.\n\nPath: /Users/dan/.vagrant.d/boxes/ailispaw-VAGRANTSLASH-rancheros-lite/0.9.2/virtualbox/Vagrantfile\nLine number: 0\nMessage: TypeError: no implicit conversion of Pathname into String"]
```

### Vagrantfile
```ruby
# BUILD ALL WITH:
# vagrant up --no-parallel
require 'fileutils'

MYSQL_ROOT_PASSWORD="root"

unless File.exists?("keys")
  Dir.mkdir("keys")
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  File.open("keys/id_rsa.pub", 'w') { |file| file.write(ssh_pub_key) }
end

Vagrant.configure(2) do |config|

  config.vm.define "mysql" do |v|

    v.vm.provider "docker" do |d|
      d.vagrant_machine = "voyce-dockerhost"
      d.vagrant_vagrantfile = "./host/Vagrantfile"
      d.image = "mysql:5.7.9"
      d.env = { :MYSQL_ROOT_PASSWORD => MYSQL_ROOT_PASSWORD }
      d.name = "mysql-container"
      d.remains_running = true
      d.ports = [
          "3306:3306"
      ]
    end
  end

  config.vm.define "drupal" do |v|

    config.ssh.port = 2222
    v.vm.synced_folder "repo/build/html", "/var/www/html", type: "rsync",
        rsync__exclude: get_ignored_files(),
        rsync__args: ["--verbose", "--archive", "--delete", "--copy-links"],
        rsync__chown: false

    v.vm.provider "docker" do |d|
      d.vagrant_machine = "voyce-dockerhost"
      d.vagrant_vagrantfile = "./host/Vagrantfile"
      d.build_dir = "."
      d.name = "drupal-container"
      d.remains_running = true
      # Save the Composer cache for all containers.
      d.volumes = [
          "/home/rancher/.composer:/root/.composer",
          "/home/rancher/.drush:/root/.drush"
      ]
      d.ports = [
          "80:80",
          "2222:22"
      ]
      d.link("mysql-container:mysql")
    end
  end

end

def get_ignored_files()
  ignore_file   = ".rsyncignore"
  ignore_array  = []

  if File.exists? ignore_file and File.readable? ignore_file
    File.read(ignore_file).each_line do |line|
      ignore_array << line.chomp
    end
  end
```

### Debug output
https://gist.github.com/danshumaker/5ddc1e3dca6a9034144e464a8362351b#file-vagrant-syntax-error

### Expected behavior
three hosts should have spun up (drupal, mysql, dockerhost).

### Actual behavior
Vagrant did not start any of the machines.

### Steps to reproduce
1.  vagrant up --no-parallel

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/mitchellh/vagrant/issues/4705
- https://github.com/mitchellh/vagrant/issues/5123

**Comment by danshumaker** [comment]
A little update.  I downgraded to vagrant 1.8.3 and this error goes away.

**Comment by ailispaw** [comment]
@danshumaker Thank you for using ailispaw/rancheros-lite.
But ailispaw/rancheros-lite has been deprecated and doesn't work with Vagrant v1.8.4 and v1.8.5.
Please consider using ailispaw/barge instead.
https://atlas.hashicorp.com/ailispaw/boxes/barge

**Comment by chrisroberts** [comment]
@danshumaker does updating to a new box as suggested by https://github.com/mitchellh/vagrant/issues/7697#issuecomment-239651296 resolve the problems?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
