### ISSUE TITLE
cant start vagrant vm's

### ISSUE THREAD

**Issue by poshpaws** [mitchellh/vagrant#7700]
### Vagrant version

1.8.4
### Host operating system

Os x 10.11.6
### Guest operating system

centos 7 (actually the guest does not matter , it dies before )
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|

  config.vm.box = "centos7"



  config.vm.network "private_network", ip: "192.168.33.10"


  config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.host_name = 'chef.vm.lab'


end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.
### Debug output

https://gist.github.com/poshpaws/f3db7c79e9e50e76c9969a04a2ce7030
### Expected behavior

the vm should boot
### Actual behavior

vm will not boot , I can manually configure in virtualbox by changing interface 0 to "Nat Network" it will boot , but next vagrant run will override this
### Steps to reproduce

vagrant init centos7
vagrant up
### References

googlegroup thread - cant start up vagrant derived boxes in virtualbox

**Comment by poshpaws** [comment]
This may be due to being on a wireless network and NAT not working with WIFI
technically this is not a failure in vagrant per say , but I would have thought it could handle such an eventuality 

Manually selecting NAT Network , seems to allow the machines to boot.

or is there a way to force VB to use a specific interface to use for NAT?

**Comment by chrisroberts** [comment]
Vagrant defaults the interface and the way around that is to manually adjust it in the Vagrantfile. If you would like to try and add some logic around it, I'd be happy to review a PR. Thanks!
