### ISSUE TITLE
Vagrant not compatible with HyperV export from Windows 10 / Server 2016 + Extraction Bug

### ISSUE THREAD

**Issue by phawxby** [mitchellh/vagrant#7706]
### Description

**Updated**
This issue appears to cover two bugs:
1. Vagrant is not compatible with exports from HyperV on Windows 10 and Server 2016 after [changes to the config format by Microsoft](https://technet.microsoft.com/en-us/windows-server-docs/compute/hyper-v/what-s-new-in-hyper-v-on-windows#a-name-bkmk-config-a-virtual-machine-configuration-file-format). 
2. There is a problem with the version of bsdtar included with Vagrant causing boxes packaged with zip not to extract properly. This has previously been referenced in GH-7068

My rambling comments below show me figuring this out.

**Old**
~~Either there is a bug within the vagrant box unpackaging or the [instructions](https://www.vagrantup.com/docs/hyperv/boxes.html#packaging-the-box) on how to package a HyperV box are incorrect. I cannot find a way to package my box without it generating errors during unpackaging. I have also found other HyperV boxes with the same unpackaging issues.~~

```
paul@CRAZYIVAN:/mnt/s/Virtual Machines/Trusty-Tahr/Export$ tar cvzf ../Trusty-Tahr.box ./*
./metadata.json
./Vagrantfile
./Virtual Hard Disks/
./Virtual Hard Disks/Trusty Tahr.vhdx
./Virtual Machines/
./Virtual Machines/0FD24F92-0B85-45A9-A275-21CAAA2C822F.vmcx
./Virtual Machines/0FD24F92-0B85-45A9-A275-21CAAA2C822F.VMRS
paul@CRAZYIVAN:/mnt/s/Virtual Machines/Trusty-Tahr/Export$
```
### Vagrant version

```
C:\Users\z269cjbb\Documents\GitHub\xerox-drupal>vagrant -v
Vagrant 1.8.5
```
### Host operating system

Windows 10 Enterprise x64. Version 1607, build 14393.51
### Guest operating system

Ubuntu 14 x64
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
memory = 4096
cpus = 2

Vagrant.configure(2) do |config|
  config.vm.box = "phawxby/trusty64"
  # config.vm.box = "withinboredom/Trusty64" # A different broken box

  config.vm.provider "hyperv" do |hv|
    hv.memory = memory
    hv.cpus = cpus
  end
end
```
### Debug output

https://gist.github.com/phawxby/6a720025a4c00dc58a73cc205dbab924
Please note there are two different debug outputs in the same gist
### Expected behavior

Box should download, decompress and then be mounted
### Actual behavior

Various decompression errors. Please note these issues exist with other boxes and have been brought up previously:
https://github.com/mitchellh/vagrant/issues/7068
### Steps to reproduce
1. `vagrant up` the attached vagrant file on Windows
### References
- GH-7068

**Comment by phawxby** [comment]
Something I have just noticed. I based my box off [ericmann/trusty64](https://atlas.hashicorp.com/ericmann/boxes/trusty64/versions/1.0.0) and aside from system updates, and increasing the VHD maximum size considerably they are identical. However Ericmann's "Virtual Machines" directory contains a single xml file with the configuration data, the version I have exported from Windows 10 includes both a vmcx and VMRS file, neither of which are human readable. 

Have Microsoft changed the HyperV export format in Windows 10 meaning Vagrant is looking for xml files which are no longer created?

**Comment by phawxby** [comment]
https://atlas.hashicorp.com/phawxby/boxes/trusty64/versions/0.1.1 - **Broken**
Box created using export from HyperV on Windows 10

https://atlas.hashicorp.com/phawxby/boxes/trusty64/versions/0.1.2 - **Working**
Box created using export from HyperV on Windows 10 but with the XML machine configuration file ripped from [ericmann/trusty64](https://atlas.hashicorp.com/ericmann/boxes/trusty64/versions/1.0.0).  

Confirms this issue relates to machine config export format

**Comment by bbrala** [comment]
I'm currently making a PR for importing the binary format. Should have it ready soon, just testing right now.

**Comment by bbrala** [comment]
Just to note, the is PR is done.
