### ISSUE TITLE
vagrant powershell cannot access SMB share (c:\vagrant)

### ISSUE THREAD

**Issue by MartinSGill** [mitchellh/vagrant#7707]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

1.8.5
### Host operating system

Windows 10
### Guest operating system

Windows (2012R2) on HyperV
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "windows2012_r2"
  config.vm.box_check_update = false
  config.vm.communicator = "winrm"

  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'
  config.winrm.basic_auth_only = true

  config.vm.provider 'hyperv' do |h|
    h.differencing_disk = true
    h.cpus = 2
    h.memory = 4096
  end
end
```
### Expected behavior

When running `vagrant powershell` the `c:\vagrant` folder should be accessible.
### Actual behavior

``` powershell
==> default: Detecting if a remote PowerShell connection can be made with the guest...
    default: Creating powershell session to 10.xxx.xxx.xxx:5985
    default: Username: vagrant
[10.xxx.xxx.xxx]: PS C:\Users\vagrant\Documents> cd C:\vagrant\
[10.xxx.xxx.xxx]: PS C:\vagrant> ls
ls : Access to the path 'C:\vagrant' is denied.
    + CategoryInfo          : PermissionDenied: (C:\vagrant:String) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand
```

Using `vagrant rdp` and then going to explorer and opening the folder works as expected, also provisioning scripts using that share work correctly. It's just the powershell command that doesn't work.
### Steps to reproduce
1. `vagrant up`
2. `vagrant powershell`
3. `cd c:\vagrant`
4. `ls`

**Comment by mwrock** [comment]
This is an unfortunate weakness with winrm. Unless you configure auth token delegation, second hop authentication is not allowed which is required to authenticate to the smb share.

**Comment by mwrock** [comment]
I should mention that the winrm gem does not support the necessary authentication protocol (credssp) needed for 2nd hop auth.

**Comment by chrisroberts** [comment]
Closing this as limitation of winrm. Cheers!
