### ISSUE TITLE
Vagrant plugin should not install gems that aren't plugins

### ISSUE THREAD

**Issue by MartinSGill** [mitchellh/vagrant#7708]
### Vagrant version

1.8.5 (and others)
### Host operating system

Any
### Guest operating system

Any
### Vagrantfile

Any
### Debug output

n/a
### Expected behavior

```
vagrant plugin install docker-compose
ERROR: Not a vagrant plugin
```

The problem here is that people new to vagrant (or not having installed a plugin before) do not realise that `vagrant plugin install` is basically an alias for `gem install`. 

Users would expect `vagrant plugin install` to only install things that are actually vagrant plugins, especially as, depending on the gem that's actually installed, this can result in a broken vagrant install.

Even if it's not possible to accurately detect what is and isn't a plugin a confirmation might suffice, e.g.:

```
vagrant plugin install docker-compose
WARNING: Vagrant plugins are usually named vagrant-plugin-name; installing something that isn't a valid plugin may break your vagrant install.
Confirm: Proceed with plugin installation? (y/N):
```
### Actual behavior

``vagrant plugin install`
success.
### Steps to reproduce
1. vagrant plugin install docker
### References
- #7235

**Comment by chrisroberts** [comment]
Adding restrictions on plugin installs to being _vagrant plugins_ seems like it would be extremely error prone to implement. While there may be a convention for plugin names, there is no formal requirement. Installing non-vagrant plugin gems via the plugins system won't harm anything other than load time. If you have an implementation in mind, I'd be happy to review a PR. At this point in time, however, I don't feel like this feature makes sense.

Thanks for the feedback!
