### ISSUE TITLE
vagrant up "metadat.json" file can not be found

### ISSUE THREAD

**Issue by saqibmehmood199** [mitchellh/vagrant#7709]
when i run the vagrant up command in Git Bash 
i got  the following problem

$ vagrant up
The "metadata.json" file for the box 'ubuntu/trusty64' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

https://www.vagrantup.com/docs/boxes/format.html

**Comment by chrisroberts** [comment]
This suggests a problem with the packaged box. A known good trusty box: `bento/ubuntu-14.04`. If you have issues using that box, please open a new issue and include all the information requested. Thanks!
