### ISSUE TITLE
Vagrant UP Stuck at `default: Booting VM...`

### ISSUE THREAD

**Issue by imewish** [mitchellh/vagrant#7710]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.8.5

### Host operating system

Ubuntu 16.04 (Openstack VM)

### Guest operating system
Tried several boxes. 

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
config.vm.box = "precise32"
config.vm.network "private_network", ip: "192.168.33.10"
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
Boot VM

### Actual behavior

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'precise32'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: asd_default_1471022984343_5500
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...

```

### Steps to reproduce
1. VM on Openstack with Ubuntu 16.04
2.Latest VirtualBox
3.Latest vagrant
4.Vagrant init
5. Vagrant Box add
6. Vagrant Up

Helps would be appreciated

**Comment by chrisroberts** [comment]
Hi! Please run:

```
vagrant up --debug
```

and provide a gist of the output that is generated from the command. Thanks!

**Comment by vStone** [comment]
I had the same problem and it looks like the cable is not connected which results in the host not getting an ip addres.

 I patched `plugins/providers/virtualbox/driver/version_5_1.rb` to always include `"--cableconnected#{adapter[:adapter]}", "on"` and that seems to have fixed it. 

Still have to test with other adapter kinds (bridge, netonly, ...) and put it in a proper pull request though.

**Comment by karolpawlowski** [comment]
I have similar problem on Windows 10. I have VirtualBox 5.1.4 and Vagrant 1.8.5. For me it doesn't hangs out on default: Booting VM... but reboot my PC every time. I don't know if it is a known issue, but Google doesn't know anything about it.

**Comment by NicolaConnect** [comment]
Using vagrant 1.8.1 and VirtualBox 5.0.20, similar situation. It stucks at "Booting VM".
My log is available at https://gist.github.com/NicolaConnect/5d29288262dc4397811a1fa5660a07a2

**Comment by imewish** [comment]
can you guys try this setting on vagrant file this fixed my issue on openstack,

config.vm.provider :virtualbox do |vb| 
vb.customize ["modifyvm", :id, "--hwvirtex", "off"] 
end

**Comment by NicolaConnect** [comment]
@imewish 
It doesn't seem to fix the problem

**Comment by chrisroberts** [comment]
Closing as original issue is resolved: https://github.com/mitchellh/vagrant/issues/7710#issuecomment-242128095
