### ISSUE TITLE
 New-Partition : Not enough available capacity

### ISSUE THREAD

**Issue by aidygus** [mitchellh/vagrant#7714]
I'm getting a random problem creating a windows 2012 from the opentable/win-2012r2-standard-amd64-nocm box.  I don't think this is box related as I packaged a manually created server which I installed myself and getting the same random problem.  I'm attempting to create a like for like environment for production environments in a local VM and part of that is creating partitions for various software components.  Sometimes it creates the drives fine, but most of the time it fails with the following error :

> ==> windowserver: New-Partition : Not enough available capacity
> ==> windowserver:
> ==> windowserver: At C:\tmp\vagrant-shell.ps1:247 char:1
> ==> windowserver: + New-Partition -DiskNumber 1 -UseMaximumSize -AssignDriveLetter |
> ==> windowserver: Format-Volume - ...
> ==> windowserver: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ==> windowserver:     + CategoryInfo          : NotSpecified: (StorageWMI:ROOT/Microsoft/Windows
> ==> windowserver:    /Storage/MSFT_Disk) [New-Partition], CimException
> ==> windowserver:     + FullyQualifiedErrorId : StorageWMI 40000,New-Partition
> ==> windowserver:
> The following WinRM command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> powershell -ExecutionPolicy Bypass -OutputFormat Text -file c:\tmp\vagrant-shell.ps1
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> 

### Vagrant version
Vagrant 1.8.5

### Host operating system
Windows 7

### Guest operating system
Windows server 2012

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|


  config.vm.define "windowserver" do |wb|

    wb.winrm.username = "vagrant"
    wb.winrm.password = "vagrant"

    wb.vm.box = "http://local-web-server/vagrant/win2012r2.box"
#   wb.vm.box = "opentable/win-2012r2-standard-amd64-nocm "
    wb.vm.hostname = "jbossapp"

    wb.vm.network "private_network", ip: "10.42.0.20"
    wb.vm.network "forwarded_port", guest: 80, host: 8090
    wb.vm.network "forwarded_port", guest: 9990, host: 9991
    wb.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = "2"

      file_to_disk = 'data/d_drive.vdi'
      unless File.exist?(file_to_disk)
        vb.customize [
            'createhd',
            '--filename', file_to_disk,
            '--size', 40 * 1024
          ]
      end
      vb.customize [
            'storageattach', :id,
            '--storagectl', 'IDE Controller',
            '--port', 1,
            '--device', 1,
            '--type', 'hdd',
            '--medium', file_to_disk
      ]
    end


    wb.vm.provision "shell", path: "ConfigureRemotingForAnsible.ps1", privileged: false
  end

  config.vm.define "provisioner" do |provisioner|
    provisioner.ssh.username = "vagrant"
    provisioner.ssh.password = "vagrant"
    provisioner.ssh.insert_key = false

    provisioner.vm.box = "geerlingguy/centos7 "
    provisioner.vm.hostname = "ansible"
    provisioner.vm.network "private_network", ip: "10.42.0.21"

    provisioner.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "1"
    end
    provisioner.vm.provision "shell", inline: <<-SHELL
    if [ ! -f "/usr/bin/ansible" ]
    then
      yum update
      yum install ansible git-core bash-completion python-pip unix2dos -y
      pip install "pywinrm>=0.1.1"
    fi
    cd /vagrant
    ansible-playbook -i hosts main.yml
    #halt -p
    SHELL
  end
end
```

### Debug output
https://gist.github.com/aidygus/287853b99c8b116057548288ed8f8195

### Expected behavior
A new partition should be created and available to the VM

### Actual behavior
Intermittently the creation fails with the above Not enough available capacity error.

### Steps to reproduce
1. vagrant destroy -f
2. vagrant up

**Comment by chrisroberts** [comment]
Do you notice any pattern to the failure? For example, is it successful the first run, but fails on subsequent runs? Or only fail on subsequent runs? Or is it seemingly random when it is successful?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
