### ISSUE TITLE
[enhancement] make guest type and flavor available in vagrant files

### ISSUE THREAD

**Issue by cdloh** [mitchellh/vagrant#7715]
vagrant can detect what type of OS and flavor the Guest is. eg [detection here for debian](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/debian/guest.rb)

If we make that information available in vagrant files it's easier to do configuration with your global Vagrantfile

[Example usage case here that installs avahi-daemon on redhat for mDNS](https://github.com/asharpe/dotfiles/blob/master/link/.vagrant.d/Vagrantfile.avahi-hostname.rb#L36). If we know what the Guest OS is we can know what package manager to use easily within the guest and sometimes don't need to worry about running the script if it isn't compatible.

**Comment by shaleh** [comment]
Are you suggesting that if the box I am running Vagrant on runs <X> I want my vms to also run <X>? If so that is a very incorrect assumption for many, many people.

**Comment by cdloh** [comment]
Not quite.

Vagrant knows what type of OS the guest is. I want that information available to provisioning scripts and other parts.

That way I can detect whether or not the guest is a debian box or a redhat box and then action my scripts accordingly. 

Whilst it might not be handy for the provisioning scripts used in boxes by themselves, it would be handy to have available to the global Vagrantfile in your .vagrant.d folder. 

Does that make sense?

**Comment by chrisroberts** [comment]
As the Vagrantfile is loaded and evaluated prior to the creation of a new VM (using `vagrant up` for example), the guest detection can't be used at the time of evaluation. If you have some implementation ideas in mind to support a feature like this I'd be happy to look over a PR. Cheers!
