### ISSUE TITLE
OSX vagrant up failing with following error

### ISSUE THREAD

**Issue by ishandutta2007** [mitchellh/vagrant#7729]
vagrant up

> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> set -e
> mkdir -p /vagrant
> mount -o vers=3,udp,nolock,vers=3,noatime 192.168.33.1:/Users/dutishan/Documents/projects/discourse /vagrant
> if command -v /sbin/init && /sbin/init --version | grep upstart; then
>   /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant
> fi
> 
> Stdout from the command:
> 
> Stderr from the command:
> 
> mesg: ttyname failed: Inappropriate ioctl for device
> mount.nfs: Connection timed out

My os version is:
sw_vers

> ProductName:	Mac OS X
> ProductVersion:	10.10.5
> BuildVersion:	14F1909

I have read 
http://askubuntu.com/questions/671228/lost-network-device-on-upgrade-to-15-10-on-test-vm
and 
https://github.com/mitchellh/vagrant/issues/6871

This is the box I am using
https://www.dropbox.com/s/2132770g1e05c6d/discourse.box?dl=1

Version of the vagrant box:

> lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.1 LTS
> Release:	16.04

setting nfs to false works but it's too slow.

Netwok > wifi connection > advanced > DNS > DNS  Server 
is set to
8.8.8.8

**Comment by chrisroberts** [comment]
Hi! Would you please provide your Vagrantfile and the debug output from the failed run. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
