### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication when trying to vagrant up.

### ISSUE THREAD

**Issue by ejandra** [mitchellh/vagrant#7733]
### Vagrant version

1.8.5
### Host operating system

Ubuntu 16.04
### Vagrantfile

Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.100.47"

  config.vm.hostname = 'drupalwork.dev'

  config.vm.provider :virtualbox do |vb|
    vb.name = "drupalwork-vm"
    vb.memory = 2048
    vb.gui = true
  end

  config.ssh.forward_agent = true

  config.vm.provision "shell",
    inline: "apt-get install -y zsh && sudo chsh -s /usr/bin/zsh vagrant"

  config.vm.provision "shell",
    inline: "[ -e /home/vagrant/.zshrc ] && : || ln -s /vagrant/zsh/zshrc /home/vagrant/.zshrc"

  config.vm.provision "shell",
    inline: "[ -e /usr/local/share/zsh/site-functions/prompt_pure_setup ] && : || ln -s /vagrant/zsh/pure.zsh /usr/local/share/zsh/site-functions/prompt_pure_setup"

  config.vm.provision "shell",
    inline: "[ -e /usr/local/share/zsh/site-functions/async ] && : || ln -s /vagrant/zsh/async.zsh /usr/local/share/zsh/site-functions/async"

  if ENV['GITHUB_OAUTH_TOKEN']
    config.vm.provision "shell",
      inline: "sudo sed -i '/^GITHUB_OAUTH_TOKEN=/d' /etc/environment  && sudo bash -c 'echo GITHUB_OAUTH_TOKEN=#{ENV['GITHUB_OAUTH_TOKEN']} >> /etc/environment'"
  end

  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: "/vagrant/docker-compose.yml", run: "always", compose_version: "1.7.1"

  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder "./src", "/mnt/code", type: "rsync", rsync__exclude: [".git/", "src/vendor"]
end
### Debug output

https://gist.github.com/ejandra/68374e4350d7e861b9f800c877db2937
### Expected behavior

The vagrant up should have been successful after successfully installing this : https://github.com/bezhermoso/generator-docker-drupal-8 . I have also just freshly installed vagrant.
### Actual behavior

What happened is that I faced this error : Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.
### Steps to reproduce

npm install -g yo
npm install -g generator-docker-drupal-8
yo docker-drupal-8
vagrant up

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
