### ISSUE TITLE
vagrant up/destroy errors out on showvminfo with ID of several \x00

### ISSUE THREAD

**Issue by MasterKale** [mitchellh/vagrant#7737]
### Vagrant version
Vagrant 1.8.5

### Host operating system
Windows 10 1607

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.synced_folder ".", "/home/ubuntu/data"

  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "3072"
    vb.cpus = 1
    vb.customize ['modifyvm', :id, '--ostype', 'Ubuntu_64']
    vb.name = "DVD-R"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    # Typical system update
    apt-get update
    apt-get upgrade -y

    # Install prereqs for installing official Docker from Docker, not Ubuntu
    apt-get install -y apt-transport-https ca-certificates
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list
    apt-get purge lxc-docker
    apt-get update

    # Install linux-image-extra for aufs support, then Docker itself
    apt-get install -y linux-image-extra-$(uname -r) docker-engine

    # Add default ubuntu user to the docker group
    groupadd docker
    usermod -aG docker ubuntu
    
    # Start Docker
    service docker start

    # Install docker-compose
    curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
    
    # Add machine name to the bash prompt
    sudo -u ubuntu sed -i -e 's/${debian_chroot:+($debian_chroot)}/${debian_chroot:+($debian_chroot)}(DVD-R) /g' /home/ubuntu/.bashrc

    # Add a `dc` alias for `docker-compose`
    touch /home/ubuntu/.bash_aliases
    echo "alias dc=\"docker-compose\"" > /home/ubuntu/.bash_aliases

  SHELL
end
```

### Debug output
https://gist.github.com/MasterKale/31ef2494975032721371bfefcf835307

### Expected behavior
`vagrant up` and `vagrant destroy` should be able to manage VMs via the virtualbox provider

### Actual behavior
For some reason Vagrant requests from VirtualBox info on a VM with the ID `\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`.

This started after I suffered a BSOD from having VirtualBox and Hyper-V installed. I removed Hyper-V and tried again, at which point Vagrant reported that the crash corrupted some files it needed to manage VMs. I manually deleted `.vagrant.d\data\machine-index\index` and destroyed any existing VMs via VirtualBox. I also blew away both `.vagrant.d` and `.VirtualBox` folders in `C:\users\me\` for good measure.

### Steps to reproduce
1. Decide to switch from the Hyper-V provider to VirtualBox
2. Install VirtualBox, then BSOD on the next `vagrant up`
3. Remove Hyper-V, then reboot
4. Try `vagrant up`/`vagrant destroy`
5. Weep as Vagrant continually fails

**Comment by MasterKale** [comment]
Deleting the `.vagrant` folder in the `DVD-R` folder fixed the issue. I opened up the four files within, `creator_id`, `id`, `index_uuid`, and `action_set_name`, and they all contained values comprised solely of zeroes (0):

**creator_id:**
> 00

**id:**
> 0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 

**index_uuid:**
> 0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000

**action_set_name:**
> 0000 0000 0000 0000 0000 

I'm sure the BSOD is to blame for this.

**Comment by chrisroberts** [comment]
Looks like this is all sorted then.
