### ISSUE TITLE
vagrant plugin should display a warning if VAGRANT_NO_PLUGIN is set

### ISSUE THREAD

**Issue by roidelapluie** [mitchellh/vagrant#7742]
When trying to get a plugin to work, it did took me 15 minutes to see that I had in the past added `export VAGRANT_NO_PLUGIN=1` in my `~/.bashrc`.

I think that all the `vagrant plugin` subcommands should display a warning if that variable is set.

**Comment by chrisroberts** [comment]
The logger now issue notifications if plugins are disabled. Cheers!
