### ISSUE TITLE
Bridge doesn't work on Window

### ISSUE THREAD

**Issue by SavaNDragos** [mitchellh/vagrant#7744]
Hi guys,

I tried to set a bridge for HyperV and it didn't worked: 
  config.vm.network : ... , bridge: "hyperv-iso-bridge"
As a note this bridge exist and I am seeing it when it ask me to introduce one:
   default: Please choose a switch to attach to your Hyper-V instance.
   default: If none of these are appropriate, please open the Hyper-V manager
   default: to create a new virtual switch.
   default:
   default: 1) DockerNAT
   default: 2) hyperv-iso-bridge
   default:
Is there a problem in the code?

**Comment by mac2000** [comment]
Today did tried same thing and it works as expected

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "mwrock/Windows2016"
  config.vm.hostname = "vagrant2016"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "public_network", bridge: "External" # <- this is worked for me

  config.vm.provider :hyperv do |hv|
    hv.vmname = "vagrant2016"
    hv.differencing_disk = true
  end
end
```

In Hyper-V I also have two switches - one created by docker and "External" created by hands

**Comment by chrisroberts** [comment]
As this is reported working https://github.com/mitchellh/vagrant/issues/7744#issuecomment-245243936 I'm going to close this issue. @SavaNDragos If you are still encountering problems, please open a new issue and include all the information requested to help properly diagnose the problem. Thanks!
