### ISSUE TITLE
Vagrant not using existing docker installation

### ISSUE THREAD

**Issue by ericis** [mitchellh/vagrant#7749]
The latest releases of Docker now support Hyper-V directly instead of requiring boot2docker and VirtualBox. Vagrant is still searching for boot2docker under either its Hyper-V provider or the VirtualBox provider. Using VirtualBox requires a dual-boot with Hyper-V disabled and separate management of a Docker host. I'd like to use my existing Docker host on top of Hyper-V.

_I'd be happy to help test ideas if you help me to know what's possible._
### Vagrant version

1.8.5
### Host operating system

Windows 10 Enterprise
### Guest operating system

> "hello-world-nginx"
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "hello-world-nginx"
  end
end
```
### Expected behavior

Use existing docker installation on top of Hyper-V.
### Actual behavior

Vagrant attempts to create a new docker host using boot2docker in either Hyper-V or VirtualBox.

```
>vagrant up --provider=docker
Bringing machine 'default' up with 'docker' provider...
==> default: Docker host is required. One will be created if necessary...
    default: Vagrant will now create or start a local VM to act as the Docker
    default: host. You'll see the output of the `vagrant up` for this VM below.
    default:
    default: Verifying Hyper-V is enabled...
    default: Box 'hashicorp/boot2docker' could not be found. Attempting to find and install...
    default: Box Provider: hyperv
    default: Box Version: >= 0
    default: Loading metadata for box 'hashicorp/boot2docker'
    default: URL: https://atlas.hashicorp.com/hashicorp/boot2docker
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: hashicorp/boot2docker
Address: https://atlas.hashicorp.com/hashicorp/boot2docker
Requested provider: [:hyperv]

```
### Steps to reproduce

... on a Windows machine that supports Hyper-V...
1. Download and install the latest version of Docker for Windows (not the old Toolbox)
2. Download and install the latest version of Vagrant
3. Run a default `vagrant up` command with the docker provisioner

**Comment by Oliveiras** [comment]
I think the original title is more precise.
I also think the priority should be higher, because now Docker's site strongly encourages Windows users to use Docker for Windows. If they do (like me), they will have a working docker installation but unable to use the docker provider for vagrant. All that just because Vagrant think it must ensure there's a boot2docker VM.
A single configuration option would suffice.

**Comment by ntwb** [comment]
Have you tried setting `` to `false`?

See https://www.vagrantup.com/docs/docker/configuration.html#force_host_vm:
> _"`force_host_vm` (boolean) - If `true`, then a host VM will be spun up even if the computer running Vagrant supports Linux containers. This is useful to enforce a consistent environment to run Docker. This value defaults to `true` on Mac and Windows hosts and defaults to `false` on Linux hosts. Mac/Windows users who choose to use a different Docker provider or opt-in to the native Docker builds can explicitly set this value to `false` to disable the behavior."_

**Comment by chrisroberts** [comment]
This was updated in the 1.9.4 release and will use the native docker builds on Windows by default. Cheers!
