### ISSUE TITLE
vagrant doesn't change the proper permission to .ssh/authorized_keys, wants 600 but set to something else

### ISSUE THREAD

**Issue by dro-mendez** [mitchellh/vagrant#7753]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by dro-mendez** [comment]
Installed Version: 1.8.5
Latest Version: 1.8.5

**Comment by benofbrown** [comment]
I've hit this myself. After some further investigation I can see it's because the file isn't chmodded after the public key is removed. It's fixed in the current code by #7610, but that's not in a released version yet. I've fixed it manually on my local copy which now works fine, see https://github.com/mitchellh/vagrant/pull/7611/files for which files need to be changed.

**Comment by chrisroberts** [comment]
Fixed via #7611 and will be included in the next release. Thanks!

**Comment by dro-mendez** [comment]
When is the next released planned? This is kind of a big deal for me.


Thanks
