### ISSUE TITLE
[question] detect vagrant state in Vargrantfile

### ISSUE THREAD

**Issue by erickeller** [mitchellh/vagrant#7757]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version

Vagrant 1.8.4

### Host operating system

NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial

### Guest operating system
jessie libvirt

### Vagrantfile

```
# automatically restart dnsmasq in the right order
# this is a hack until libvirt do not mess-up with dnsmasq.service!
system('./restart_dns.sh --force')
...
normal multi-box vagrantfile
...
```

I would like to reset the dns only when calling vagrant up therefore I would like to know if I can detect the parameter with wich vagrant is called?

Any idea if this is possible

Cheers
--
Eric

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
