### ISSUE TITLE
Vagrant 1.8.5 - VirtualBox 5.1.2 on windows 10 - not enought arguments for import

### ISSUE THREAD

**Issue by lisi4ok** [mitchellh/vagrant#7759]
I had this problem.
Here is my Vagrantfile and my error:

http://i.imgur.com/svwh1Py.png

Any Ideas

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by chrisroberts** [comment]
Please upgrade vagrant to 1.8.6 for use with virtualbox 5.1
