### ISSUE TITLE
installing vagrant-scp gives NoMethodError

### ISSUE THREAD

**Issue by saisandeep** [mitchellh/vagrant#7761]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

Vagrant 1.8.5
### Host operating system

OSX el capitan
### Guest operating system

ubuntu-trusty tahr
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu1"
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.
### Debug output

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.
### Expected behavior

Successful installation of vagrant-scp
### Actual behavior

got an /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/resolver.rb:202:in `map': undefined method`to_specs' for nil:NilClass (NoMethodError)
### Steps to reproduce
1. Install vagrant 1.8.5
2. vagrant plugin install vagrant-scp
### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by saisandeep** [comment]
`$ vagrant plugin install vagrant-scp
Installing the 'vagrant-scp' plugin. This can take a few minutes...
/opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/resolver.rb:202:in `map': undefined method `to_specs' for nil:NilClass (NoMethodError)
       	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/resolver.rb:202:in `start'
       	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/resolver.rb:184:in `resolve'
       	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:200:in `resolve'
       	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:140:in `specs'
       	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
       	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:195:in `resolve_if_need'
       	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:70:in `run'
       	from /opt/vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler/installer.rb:22:in `install'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:230:in `block in internal_install'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:294:in `block in with_isolated_gem'
       	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/user_interaction.rb:45:in `use_ui'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:293:in `with_isolated_gem'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:229:in `internal_install'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/bundler.rb:102:in `install'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/manager.rb:72:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/action/install_gem.rb:37:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/base.rb:14:in `action'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/install.rb:32:in `block in execute'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/install.rb:31:in `each'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/install.rb:31:in `execute'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/plugin/command/root.rb:56:in `execute'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/cli.rb:42:in `execute'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:302:in `cli'
       	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:174:in `<main>'`

**Comment by thomdixon** [comment]
👍 Had to revert back to 1.8.0 to get it working.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
