### ISSUE TITLE
VMware HGFS provider shared folders not working

### ISSUE THREAD

**Issue by mattpollard** [mitchellh/vagrant#7763]
I'm unable to get shared folders working in my Red Hat Enterprise Linux box. I _thought_ this was related to [this issue](https://github.com/mitchellh/vagrant/issues/6775), but now I'm thinking it isn't. Also, perhaps this isn't the best destination for this report... so feel free to close this if I'm just dumping it in the wrong place. 

My environment: 
- OS X 10.11.6
- VMware Fusion 8.1.1
- Vagrant 1.8.5
- Vanilla `Red Hat Enterprise Linux Server release 7.2 (Maipo)` box offered by Red Hat as part of their Container Development kit, which you can find [here (free registration required)](http://red.ht/29FjHvh)

Here's what I did:
1. Created a new directory and ran `vagrant init`
2. Updated my `Vagrantfile`:
   - Changed the box to the Red Hat box
   - Added a line to create `/mnt/hgfs`:
     
     ```
      config.vm.provision "shell",
        inline: "mkdir /mnt/hgfs"
     ```
3. Ran `vagrant up`
4. `vagrant ssh`ed in:
   - Checked that `/mnt/hgfs` was created successfully
   - Installed `open-vm-tools`; ensured the service was enabled to start at boot
5. Ran `vagrant reload` (not sure if this was necessary or useful in any way)
6. `touch`ed `hello_world` in the Vagrant project path, then `vagrant ssh`ed in to see if the file was synced to `/vagrant` – it wasn't

Might be useful to know the `open-vm-tools` version, too:

```
[vagrant@rhel-cdk ~]$ vmtoolsd -v
VMware Tools daemon, version 9.10.2.48224 (build-2822639)
```

**Comment by mvermaes** [comment]
Just wanted to comment that I think we have the same issue. Our build environment is identical, except our box is CentOS 7.2 instead. I've tried with both the official CentOS box (https://atlas.hashicorp.com/centos/boxes/7 - admittedly only released a few days ago), as well as bento/centos-7.2 (rebuilt from the template including open-vm-tools - https://github.com/chef/bento/pull/638). Both eventually fail with:

```
HGFS was never found on the running virtual machine. This must be
installed either through VMware tools or Open VM Tools. HGFS is
required for shared folders to work properly. Please install either
the VMware tools or Open VM Tools and try again.
```

**Comment by dky** [comment]
+1

**Comment by ethier** [comment]
Seeing the same issue on CentOS 7.2. Odd thing is the original build process successfully enables shared folders, but subsequent reboots/reloads loses it.

Vagrant 1.8.6

vagrant-berkshelf (5.1.0)
vagrant-omnibus (1.5.0)
vagrant-share (1.1.5, system)
vagrant-vmware-fusion (4.0.14)

VMWare Tools daemon versions the same as dky above.

**Comment by terpsho** [comment]
I also see the same issue on CentOS 7.2. I tried to use config.vm.synced_folder ".", "/tmp" but received error msg as:
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:
**Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system**
My environment is:
Vagrant 1.8.5
CentOS 7.2.1511
vagrant-vmware-fusion: 4.0.14
vagrant-share 1.1.5

I also try to mount another shared disk manually through Fusion UI. Fusion UI does not report any error but when I use the shared_folder. Although I can see /mnt/hdfs inside the guest VM, the content is actually empty. The following log shows when I manually add a folder. 

2016-10-29T02:40:47.230+08:00| vmx| A100: ConfigDB: Setting sharedFolder0.present = "true"
2016-10-29T02:40:47.230+08:00| vmx| A100: ConfigDB: Setting sharedFolder0.enabled = "true"
2016-10-29T02:40:47.230+08:00| vmx| A100: ConfigDB: Setting sharedFolder0.readAccess = "true"
2016-10-29T02:40:47.230+08:00| vmx| A100: ConfigDB: Setting sharedFolder0.writeAccess = "true"
2016-10-29T02:40:47.230+08:00| vmx| A100: ConfigDB: Setting sharedFolder0.hostPath = "/Users/hos/Documents/VMware_Docs/Product/CNA_DevOps/SME"
2016-10-29T02:40:47.230+08:00| vmx| A100: ConfigDB: Setting sharedFolder0.guestName = "SME"
2016-10-29T02:40:47.230+08:00| vmx| A100: ConfigDB: Setting sharedFolder0.expiration = "never"
2016-10-29T02:40:47.230+08:00| vmx| A100: ConfigDB: Setting sharedFolder.maxNum = "1"

**Comment by dky** [comment]
Hello, just wondering if anyone made any progress on this issue? Still seeing the same.

**Comment by dky** [comment]
vagrant init geerlingguy/centos7; vagrant up --provider vmware_fusion seems to work for those struggling with the same issue.

**Comment by NathanKleekamp** [comment]
@dky After you `vagrant halt` + `vagrant up` or `vagrant reload` the vm, do the synced folders continue to mount?

**Comment by mvermaes** [comment]
For what it's worth, here is the procedure we use: https://github.com/mvermaes/centos-vmware-tools. Like @dky mentioned, using open-vm-tools, plus the HGFS driver from the proprietary tools for synced folder support is the best option we've found so far. vagrant reload/kernel update hasn't really been tested though.

This is for the official centos/7 box, but Bento's experiment with only relying only on open-vm-tools was also rolled back, see https://github.com/chef/bento/pull/638#issuecomment-250497781 and https://github.com/chef/bento/issues/667. RHEL/CentOS 7.3 brings in open-vm-tools 10.x, but from what I understand it will also need kernel 4.x to be able to use the vmhgfs-fuse support from OVT.

**Comment by mattpollard** [comment]
We moved to CentOS after Amazon introduced CentOS AMIs in EC2, so I'm no longer working with Red Hat Enterprise Linux boxes in Vagrant on my Mac. However, I just noticed this afternoon that synced folders are working for me now in Vagrant 1.9.1 with `bento/centos-7.3`.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of the vmware plugin so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
