### ISSUE TITLE
chef_solo recipe_url broken

### ISSUE THREAD

**Issue by tnaroska** [mitchellh/vagrant#7764]
chef_solo provisioner is broken when used with recipe_url option.

==> jenkins: Running provisioner: chef_solo...
    jenkins: Installing Chef (12.5.1)...
==> jenkins: Generating chef JSON and uploading...
==> jenkins: Running chef-solo...
==> jenkins: [2016-08-29T19:15:43-07:00] DEBUG: Cleanup path /tmp/vagrant-chef before extract recipes into it
==> jenkins: [2016-08-29T19:15:43-07:00] DEBUG: Creating path /tmp/vagrant-chef to extract recipes into
==> jenkins: [2016-08-29T19:15:43-07:00] DEBUG: Download recipes tarball from /vagrant/es_jenkins_package.tar.gz to /tmp/vagrant-chef/recipes.tgz
==> jenkins: [2016-08-29T19:15:44-07:00] FATAL: Cannot load configuration from /tmp/vagrant-chef/dna.json

The issue is due to the delete_entire_chef_repo code in chef_solo itself:
https://github.com/chef/chef/blob/master/lib/chef/application/solo.rb#L277-L280
This leads to chef deleting and recreating the whole /tmp/vagrant-chef directory, removing dna.json and solo.rb. 

Possible workaround configuration:
cookbooks_path = [[:vm, "folder/cookbooks"]]

Also related to https://github.com/mitchellh/vagrant/commit/1fd9aec493ee0a2f2f9b859734c8a99b7f024b2b
Before this change the default of [:vm, "cookbooks"] would have been mapped to [:vm, "cookbooks/cookbooks"]. That prevented chef from deleting /tmp/vagrant-chef but /tmp/vagrant-chef/cookbooks instead.
### Vagrant version

1.8.5
### Host operating system

Mac OSX

**Comment by briancain** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [chef_solo recipe_url broken](https://trello.com/c/f97TWyfm/23-chefsolo-recipeurl-broken)

**Comment by briancain** [comment]
Hey there!

I tried to reproduce this using the `chef_solo` provisioner with `recipe_url` set and it seems like Vagrant was able to properly download the remote recipe and configure the vagrant vm with nginx (see https://gist.github.com/briancain/1f84626ca4215c8e28bdf5a94e5a57cc for my attempt to reproduce the issue). If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
