### ISSUE TITLE
Can't use virtualbox shared folders with ubuntu 16.04 and VBoxGuestAdditions-5.1.4

### ISSUE THREAD

**Issue by IAmJulianAcosta** [mitchellh/vagrant#7766]
I upgraded my box from 14.04 to 16.04, but now I can't use virtualbox shared folders. Virtualbox version 5.1.4, if I run `lsmod | grep -i vbox`:

vboxpci                24576  0
vboxnetadp             28672  0
vboxnetflt             28672  0
vboxdrv               454656  3 vboxnetadp,vboxnetflt,vboxpci
vboxsf                 45056  0
vboxguest             282624  2 vboxsf

Virtualbox guest additions are working fine in guest, and the version matches, but I'm getting an error when trying to sync

### Vagrant version
1.8.5

### Host operating system
Windows 10 x64

### Guest operating system
Ubuntu 16.04.1 LTS 

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  Vagrant.require_version ">= 1.6.0"
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.gui = true
  end

  config.vm.network "public_network", ip: "192.168.1.128", bridge: "Marvell Yukon 88E8057 Family PCI-E Gigabit Ethernet Controller"
  #docker port
  config.vm.network "forwarded_port", guest: 2376, host: 2376
  config.vm.synced_folder ".", "/vagrant", id: "configuration", owner: "vagrant", mount_options: ['dmode=705', 'fmode=705']
```

### Debug output
```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attemped was:

set -e
mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group ubuntu | cut -d: -f3`,dmode=705,fmode=705 configuration /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g ubuntu`,dmode=705,fmode=705 configuration /vagrant
```

### Expected behavior
Synced folders

### Actual behavior
Error described in output, folders don't sync

### References
- https://bugs.launchpad.net/cloud-images/+bug/1565985

**Comment by ehernandez-xk** [comment]
I had the same problem, it looks like an incompatibility between Virtual-box and Vagrant with 1.8.5, try to use: 1.8.4 and 5.0.x

https://github.com/blinkreaction/boot2docker-vagrant/issues/83

**Comment by chrisroberts** [comment]
Hi! Please provide a gist of the full debug output. Thanks!

**Comment by gdbtek** [comment]
I have the same issue when using:

VirtualBox 5.1.6
VirtualBox Guest Addition 5.1.6
Ubuntu 16.04.1 LTS x64
Vagrant 1.8.5

**Comment by Sean-Brown** [comment]
Same issue from my Windows 10 machine:

VirtualBox 5.1.6
VirtualBox Guest Additions 5.1.6
Debian Jessie 3.16.0-4-amd64
Vagrant 1.8.5

**Comment by gdbtek** [comment]
does anyone have workaround for this bad bug?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by IngoSteinke** [comment]
Still occurs both on Windows 10 and Ubuntu 16.10!

**Comment by migaliza** [comment]
Check the version of vagrant you are using. If it is the the latest then the problem could be that the version is not compatible with the virtualbox version. So I had to upgrade virtualbox on windows. When I did vagrant up it worked!!!!!!!!!!!!!!!
