### ISSUE TITLE
No usable default provider could be found for your system-vagrant-1.8.4-virtualbox-5.1.4

### ISSUE THREAD

**Issue by HackToday** [mitchellh/vagrant#7767]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.8.4

### Host operating system
Centos 7.2

### Guest operating system
Centos 7.1

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
vagrant up should work

### Actual behavior
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

### Steps to reproduce
1. install vagrant 1.8.4 and virtualbox 5.1.4 (https://www.virtualbox.org/wiki/Downloads)
2. run vagrant init
3. run vagrant up --provider=virltualbox

**Comment by sublimino** [comment]
Same for me on Debian testing

```
Linux <redacted> 4.5.0-2-amd64 #1 SMP Debian 4.5.5-1 (2016-05-29) x86_64 GNU/Linux
```

Vagrantfile:

```
box = "ubuntu14.04"
url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
hostname = "iso-builder" 
domain = "builder.com" 
ip_address = "192.168.87.254"
ram = 2048

# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = box 
  config.vm.box_url = url
  config.vm.hostname = hostname + '.' + domain
  #config.vm.network "private_network", ip: ip_address 
  config.vm.network "public_network", ip: ip_address 

  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      'modifyvm', :id,
      '--memory', ram
    ]
  end

end
```

**Comment by chrisroberts** [comment]
Does it work properly if using vagrant 1.8.5? Or, if using vagrant 1.8.4 does it work if you install virtualbox version 5.0.x?

**Comment by HackToday** [comment]
I tried 1.8.4  because 1.8.5 have a bug https://github.com/mitchellh/vagrant/issues/7610

And 1.8.4 can not work with Virtualbox 5.1.* can be found here https://github.com/mitchellh/vagrant/issues/7411

So right now, I use virtualbox 5.0.*

**Comment by chrisroberts** [comment]
Vagrant 1.8.4 does not have support for Virtualbox 5.1.x. Vagrant 1.8.6 has been released. Can you please try that installation and see if it resolves your issue? Thanks!

**Comment by chulkilee** [comment]
Confirmed vagrant 1.8.6, virtaulbox 5.1.6, and `centos/7` box works well together.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
