### ISSUE TITLE
Support jsonpatch at build command

### ISSUE THREAD

**Issue by dploeger** [mitchellh/vagrant#7769]
On creating [Puppetdev](http://dennis.dieploegers.de/easy-puppet-testing-with-vagrant/) (https://github.com/dploeger/packer-puppetdev), I came around [JSONPatch](http://jsonpatch.com), a standardized format for modifying JSON documents.

Puppetdev is based on other Packer templates and modifies them heavily. It would be great, if the packer build-command could include support for JSONPatch files, which are applied (one after the other) to the original Packer template. Packer then would use the modified template.

This would enable a better workflow, if you like to rely on base images for specific features.

And: There's already a Go implementation for JSONPatch. 😉

**Comment by chrisroberts** [comment]
Hi! I think you meant for this issue to go here: https://github.com/mitchellh/packer

Cheers!

**Comment by dploeger** [comment]
Argh. Sorry, Yes.
