### ISSUE TITLE
vagrant box unable to update

### ISSUE THREAD

**Issue by penjing** [mitchellh/vagrant#7772]
Hi Guys
 
I have trying to update my ubuntu box but I keep getting this message 

==> web02: Checking for updates to 'ubuntu/trusty64'
    web02: Latest installed version: 20160818.0.0
    web02: Version constraints: 
    web02: Provider: virtualbox
==> web02: Updating 'ubuntu/trusty64' with provider 'virtualbox' from version
==> web02: '20160818.0.0' to '20160826.0.1'...
==> web02: Loading metadata for box 'https://atlas.hashicorp.com/ubuntu/trusty64'
==> web02: Adding box 'ubuntu/trusty64' (v20160826.0.1) for provider: virtualbox
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/version.rb:206:in `initialize': Malformed version number string temp (ArgumentError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/version.rb:198:in `new'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/version.rb:198:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_collection.rb:284:in `block (3 levels) in find'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_collection.rb:284:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_collection.rb:284:in `all?'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_collection.rb:284:in `block (2 levels) in find'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_collection.rb:283:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_collection.rb:283:in `block in find'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_collection.rb:436:in `block in with_collection_lock'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
....

I have managed to upgrade once to version 20160818 from 20160801, but after that I am still getting the message (Malformed version number string temp (ArgumentError))
I have version 1.8.5 of Vagrant on Linux Mint v18. I have tried to delete the ~/.vagrant/setup_version without any success. This file tells version 1.5. Is there a way to fix this?
Thanks for your help
Perry

**Comment by penjing** [comment]
I got the answer

**Comment by yanglidk** [comment]
I've encountered the same issue now, will you kindly share your knowledge of how to fix this issue?
