### ISSUE TITLE
`rsync` doesn't work on Vagrant 1.8.4

### ISSUE THREAD

**Issue by sakiyo** [mitchellh/vagrant#7773]
### Vagrant version
1.8.4

### Host operating system
windows 7 pro

### Guest operating system
CentOS-7-x86_64-Vagrant-1607_01.VirtualBox

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "d:/Server/WWW", "/home/www"
end
```

### Debug output
Administrator@TF-PC /cygdrive/d/Tools/Vagrant/vb
$ vagrant up
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /cygdrive/d/Tools/Vagrant/vb/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/d/Tools/Vagrant/vb/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/cygwin/tmp/ssh.673 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'D:/Tools/Vagrant/vb/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "/cygdrive/d/Tools/Vagrant/vb/" "vagrant@127.0.0.1:/vagrant"
Error: usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-e escape_char] [-F configfile]
           [-i identity_file] [-L [bind_address:]port:host:hostport]
           [-l login_name] [-m mac_spec] [-O ctl_cmd] [-o option] [-p port]
           [-R [bind_address:]port:host:hostport] [-S ctl_path]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]

See the "error usage SSH []".jesus!!!

i remove 77-79 line
#"-o ControlMaster=auto " +
#"-o ControlPath=#{controlpath} " +
#"-o ControlPersist=10m " +

but still error;

**Comment by ehernandez-xk** [comment]
@sakiyo Hi, What version of VB you are using?

you can use this plugin to try to install the missed Guest Addition 
https://github.com/dotless-de/vagrant-vbguest

**Comment by sakiyo** [comment]
@ehernandez-xk  Hi, i see.
VirtualBox_5.0.12 and VirtualBox-5.1.4.

i install Guest Addition,then output.

$ vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
[default] GuestAdditions 5.0.12 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /cygdrive/d/Tools/Vagrant/vb/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/d/Tools/Vagrant/vb/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/cygwin/tmp/ssh.386 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'D:/Tools/Vagrant/vb/.vagrant/machines/default/virtualbox/private_key' --exclude .vagrant/ /cygdrive/d/Tools/Vagrant/vb/ vagrant@127.0.0.1:/vagrant
**Error: rsync: Failed to exec ssh: No such file or directory (2)**
rsync error: error in IPC code (code 14) at pipe.c(85) [sender=3.1.1]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]


i add vagrantfile

config.vbguest.iso_path = File.expand_path("../../VirtualBox/VBoxGuestAdditions.iso", __FILE__)
config.vbguest.auto_update = false
config.vbguest.no_remote = true

Nothing Has Happened

**Comment by ehernandez-xk** [comment]
@sakiyo Do you have any requirement to use rsync? you can use the default synced_folder

Try to do this first, so you can see if the synced folder works correctly.
```
config.vm.synced_folder ".", "/vagrant"
```

Vagrant will automatically choose the best synced folder option for your environment.

`$ vagrant up`

go to the official doc and review the prerequisites for Windows. https://www.vagrantup.com/docs/synced-folders/rsync.html#prerequisites

Review the rsync problem, it looks like the path is incorrect.
**Error: rsync: Failed to exec ssh: No such file or directory (2)**

**Comment by chrisroberts** [comment]
@sakiyo can you please install the latest version of Vagrant (1.8.6) provide the result of https://github.com/mitchellh/vagrant/issues/7773#issuecomment-244947979 

Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
