### ISSUE TITLE
Vagrant fails to ssh to the ubuntu/xenial64 (asks for password) when env vars are used in Vagrantfile

### ISSUE THREAD

**Issue by x-yuri** [mitchellh/vagrant#7777]
### Vagrant version

1.8.4
### Host operating system

Arch Linux
### Guest operating system

ubuntu/xenial64 box
### Vagrantfile

``` ruby
Vagrant.configure('2') do |config|
  if ENV['B'] == 'ubuntu'
    config.vm.box = 'ubuntu/xenial64'
  else
    config.vm.box = 'centos/7'
  end
end
```
### Debug output

~~https://gist.github.com/x-yuri/ef4dd24dbf72a2e5ffa0f28bbd46c9d0~~
https://gist.github.com/x-yuri/4bbcf7cf8c37746627409e34f00ea2e1
### Expected behavior

It shouldn't ask for password when doing `vagrant ssh`.
### Actual behavior

It asks for password.
### Steps to reproduce
1. B=ubuntu vagrant up
2. vagrant ssh
### References

[This issue](https://github.com/mitchellh/vagrant/issues/7350) is related, but seems to be a separate one. The one I'm describing here looks like an issue with `vagrant`. With the following `Vagrantfile` it works:

``` ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
end
```

If you have a workaround in mind, you're welcome.
### More info

If you make ubuntu default box:

``` ruby
Vagrant.configure('2') do |config|
  if ENV['B'] == 'centos'
    config.vm.box = 'centos/7'
  else
    config.vm.box = 'ubuntu/xenial64'
  end
end
```

And do `vagrant up && vagrant ssh`, it logs in. So, it seems like something is grepping `Vagrantfile` and takes the last occurrence. Or the environment variable gets lost somewhere along the way.

**Comment by rap2hpoutre** [comment]
Same for me (on macOS). `vagrant up` always ask for password.

**Comment by nickescobedo** [comment]
👍 happens here as well. MacOS

**Comment by lekum** [comment]
Happens to me, also.

Host operating system: **Xubuntu 16.04**
Guest operating system: **ubuntu/xenial64 box**
Vagrant version: **1.8.6**
Virtualbox version: **5.0.26 r108824**

**Comment by encodia** [comment]
the same issue, happens to me.

Host operating system: **macOS Sierra**
Guest operating system: **ubuntu/xenial64 box**
Vagrant version: **1.8.6**
Virtualbox version: **5.0.26 r108824**

**Comment by Ryuno-Ki** [comment]
Affects me, too.

Host operating system: **Sabayon Linux**
Guest operating system: **ubuntu/xenial64** (box_version = "20161022.0.0")
Vagrant version: **1.8.5**
Virtualbox version: **5.1.6 r110634**

**Comment by NeuralSandwich** [comment]
+1

**Comment by SamuelMarks** [comment]
Same for me. I think this it the bug, so this issue should be closed here: https://bugs.launchpad.net/cloud-images/+bug/1569237

Host operating system: **Ubuntu**
Guest operating system: **ubuntu/xenial64 (box_version = "20170118.1.0")**
Vagrant version: **1.9.1**
Virtualbox version: **5.1.14r112924**

**Comment by chrisroberts** [comment]
Closing this as an upstream issue with box author. Cheers!
