### ISSUE TITLE
Vagrant plugin install fails with SSL Error

### ISSUE THREAD

**Issue by clubdeuce** [mitchellh/vagrant#7780]
```
vagrant -v
Vagrant 1.8.5
```

MacOSX 10.11.6

Recent upgrade from Vagrant version 1.7.?. Unfortunately, I cannot remember the last segment.

This happens when trying to install any plugin.

```
vagrant plugin install vagrant-vmware-fusion
Installing the 'vagrant-vmware-fusion' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not verify the SSL certificate for https://gems.hashicorp.com/quick/Marshal.4.8/bigdecimal-1.2.6.gemspec.rz.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
```

**Comment by chrisroberts** [comment]
Is this happening within a corporate network?

**Comment by clubdeuce** [comment]
@chrisroberts It is not.

**Comment by Coffee-fan** [comment]
Happens to me also in Windows 10, both the released version as well as the fast ring 14926, both vagrant 1.8.4 and vagrant 1.8.5. I submitted a ticket to hashicorp on this because I need to install vmware workstation plugin and thought the issue was unique to that plugin, but it is *any* plugin. Got no answer so far :-(.

**Comment by clubdeuce** [comment]
@Coffee-fan I have been waiting for two weeks for an answer.

@chrisroberts Is there any update on this?

**Comment by chrisroberts** [comment]
Related: #7793

**Comment by chrisroberts** [comment]
@clubdeuce Hi! I am attempting to replicate the behavior locally. Can you run the `vagrant plugin install` command with the `--debug` flag and toss the output into a gist? Thanks!

**Comment by clubdeuce** [comment]
@chrisroberts 

[Gist here](https://gist.github.com/clubdeuce/ca63c6573fe67960c8b8099a3cc81c99)

**Comment by chrisroberts** [comment]
Related for osx: #7747

**Comment by chrisroberts** [comment]
@clubdeuce Latest release has updates to how internal plugins are handled, and I believe it may resolve this. Can you please let me know if you are still experiencing this issue on the latest release. If so I'll work to get this fully reproducible locally so I can address it in the 1.9.1 release. Thanks!

**Comment by chrisroberts** [comment]
Noting that #8067 shows this is still an issue in 1.9.0

**Comment by clubdeuce** [comment]
@chrisroberts After downloading and installing `1.9.0`, I get the following:

````
vagrant plugin install vagrant-triggers
Installing the 'vagrant-triggers' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-triggers (> 0)'
````

**Comment by chrisroberts** [comment]
@clubdeuce Are you running via the installer? Can you toss a `--debug` on there and throw the output into a gist?

**Comment by clubdeuce** [comment]
@chrisroberts Yes, I ran the `1.9.0` installer. [Gist here](https://gist.github.com/clubdeuce/a4f593bbb8adc8c9126b15469ca23c90).

**Comment by mcqj** [comment]
Seeing the same error on with 1.9.1 on Linux. Using apt to install.

**Comment by TakayukiKando** [comment]
Seeing the same error on with 1.9.1 on Windows 10.

**Comment by TakayukiKando** [comment]
I tried to install bundler gem to Ruby of Vagrant's embedded, directly:
=+=+=+=
C:\home>C:\HashiCorp\Vagrant\embedded\bin\gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
=+=+=+=

**Comment by chrisroberts** [comment]
Closing this to track in #7787

**Comment by miamimanni** [comment]
I also had this issue, but for a very different reason. I left environment variable SSL_CERT_FILE pointing to a specific ca-cert pem chain. This was to resolve another issue but is not needed. I remove the environment variable and I was then able to install the plugin just fine. Just in case anyone has the same scenario as me.
