### ISSUE TITLE
Vagrant up, it's not downloading the virtual machine

### ISSUE THREAD

**Issue by alexandrubeu** [mitchellh/vagrant#7783]
### Expected behavior
It should download the virtual machine and then continue provisioning.

### Actual behavior
Receive an error:
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'puppetlabs/ubuntu-14.04-64-puppet;' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'puppetlabs/ubuntu-14.04-64-puppet;' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/puppetlabs/ubuntu-14.04-64-puppet;"]
Error:

### Steps to reproduce
1. vagrant init puppetlabs/ubuntu-14.04-64-puppet;
2. vagrant up

**Comment by ezekg** [comment]
Try dropping the semicolon from the init command.

**Comment by alexandrubeu** [comment]
Maybe the seed servers were down. I've tried one hour later and it worked perfectly.
Thanks
