### ISSUE TITLE
Vagrant removing comments from /etc/hosts

### ISSUE THREAD

**Issue by regilero** [mitchellh/vagrant#7794]
### Vagrant version

Vagrant 1.8.5
### Host operating system

Ubuntu 14.04
### Guest operating system

Ubuntu 16.04
### Actual behavior

After each restart the comments are removed. the code now contains several references to this sort of things:

```
     # Remove comments and blank lines from /etc/hosts
     sed -i'' -e 's/#.*$//' -e '/^$/d' /etc/hosts
```

Like in : https://github.com/mitchellh/vagrant/blame/master/plugins/guests/debian/cap/change_host_name.rb#L22-L23 from commit dbb2d992785c7f8cf23bd04f1dbc1e4c1dbe41f4
### Expected behavior

I use comments in /etc/hosts to manage dynamic blocks of entries in this file (with external provisioner).
I'd like my comments to stay there, so I could find back my entries in this file (and edit theses entries).

I do understand why, maybe, removing empty lines could be used, but removing comments seems a bit too much.

Theses comments can be used for provisioning, but also fro storing ready-to-use records, ot even other things. I would say it's not the responsibility of vagrant to ensure that the hosts file contains no comments.

**Comment by avoev** [comment]
- Just in case you decide to use a patch for it in the mean time:
     ```ruby
        Fixes a bug where Vagrant is removing comments in etc/hosts
        Index: /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/guests/redhat/cap/change_host_name.rb
        Usage: sudo patch /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/guests/redhat/cap/change_host_name.rb < patch.diff
        
        ===================================================================
        
        --- change_host_name.orig.rb	2017-02-09 14:26:25.000000000 -0800
        +++ change_host_name.rb	2017-02-09 14:29:56.000000000 -0800
        @@ -23,9 +23,6 @@
                         hostname -F /etc/hostname
                       fi
         
        -              # Remove comments and blank lines from /etc/hosts
        -              sed -i'' -e 's/#.*$//' -e '/^$/d' /etc/hosts
        -
                       # Prepend ourselves to /etc/hosts
                       grep -w '#{name}' /etc/hosts || {
                         sed -i'' '1i 127.0.0.1\\t#{name}\\t#{basename}' /etc/hosts
     ```
