### ISSUE TITLE
Error not shown with nested virtualization

### ISSUE THREAD

**Issue by Fantomatic** [mitchellh/vagrant#7800]
### Vagrant version

vagrant 1.8.1
### Host operating system

Fedora 24 on vm in windows 7
CoreOS

I found an error hidden behind vagrant when i tried to vagrant up a project. My Fedora used to launch vagrant was already a vm powered by virtualbox. 
When i launch my project, everything was fine, until the boot happen and vagrant hang till the timeout.  No error reported etc...
I found later that it was a problem with virtualbox, related to the nested vm which was in 64bits and wasn't supported. 
But shouldn't Vagrant have the knowledge of this error and report it ? Don't know if vagrant would be able to do that, but in the case it's possible, it would be a nice improvement.

**Comment by chrisroberts** [comment]
Attempting to surface that information would require much more involved inspection than is currently implemented in Vagrant. These errors are not that common, and can generally be found with some debugging. Cheers!
