### ISSUE TITLE
Ssh `~^Z` Suspend Broken

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mitchellh/vagrant#7801]
It seems this bug is back: #6645

If I try to use 'ssh suspend' `~^Z` then it just hangs and returns to the same guest prompt on pressing the enter key. (Although on Linux and _sometimes_ on Windows it'll hang the prompt indefinitely with no escape).

```
[root@centos7-1 vagrant]# ~^Z [suspend ssh]

[root@centos7-1 vagrant]#
```

Info:
### Vagrant version

1.8.5
### Host operating system

All (Windows [Cygwin, Git Bash], Linux, OSX])
### Guest operating system

Any *nix (CentOS and Ubuntu tested)
### Expected behavior

It should suspend ssh, just like normal `ssh` does.
### Steps to reproduce
1. Log into a linux machine with `vagrant ssh`
2. Try to use the normal 'ssh suspend' `~^Z`
3. It'll hang and just return to the same prompt on enter

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by ElvenSpellmaker** [comment]
I'll download the latest tonight and give it a try, thanks. =)
