### ISSUE TITLE
Issue with private network interface Vagrant >1.8.1

### ISSUE THREAD

**Issue by embano1** [mitchellh/vagrant#7808]
Hi,

discovered a weird behavior of Vagrant in versions >1.8.1 (1.8.1 working). vagrant up <node> (multi-node Vagrantfile) throws:

==> manager: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ifconfig eth1 192.168.33.101 **netmast** 255.255.255.0

Stdout from the command:

Stderr from the command:

**netmast**: Unknown host
ifconfig: `--help' gives usage information.

Note the misspelled "netmast" command here...

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
OSX 10.11.6

### Guest operating system
VMware PhotonOS 1.0 (GA)

### Vagrantfile
[...]
# Corresponding config.vm.network parameter
config.vm.network "private_network", ip: opts[:eth1]

### Expected behavior
Private network interface should be created as in Vagrant 1.8.1 

### Actual behavior
==> manager: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ifconfig eth1 192.168.33.101 netmast 255.255.255.0

Stdout from the command:

Stderr from the command:

netmast: Unknown host
ifconfig: `--help' gives usage information.

**Comment by chrisroberts** [comment]
Fixed via #7873. Thanks for the report!

**Comment by embano1** [comment]
thank you!
