### ISSUE TITLE
Insecure defaults.

### ISSUE THREAD

**Issue by vhakulinen** [mitchellh/vagrant#7815]
### Vagrant version

Vagrant 1.8.5
### Host operating system

Arch Linux (Kernel version 4.7.4-1-ARCH)
### Guest operating system

Ubuntu Trusty 64bit (16.04)
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision :shell, path: "bootstrap.sh", privileged: false # Sets up HTTP service
  config.vm.provision "shell", inline: "service apache2 restart", run: "always"
end

```
### Debug output

None.
### Expected behavior

That the virtual machine is accessable only on address `localhost:8080` (which it is) but its also accesable from the whole network on `<local-ip>:8080`. I've already searched for this issue and found #6133 and #4768 and noticed that you guys are not willing to changes this behavior. Its nice that you updated the documentation but atleast I missed that part when I first read it. I'd suggest that the `host_ip` would default to `127.0.0.1` (`localhost` didn't seem to work). If not that, then atleast in the default `Vagrantfile` add `host_ip` option by default to the example line which goes like `# config.vm.network "forwarded_port", guest: 80, host: 8080`.
### Actual behavior

Virtual machine is exposed to the whole network.
### Steps to reproduce
1. Setup vagrant box with `forwarded_port`
2. Access your new exposed virtual machine from the whole network.
### References
#6133
#4768

**Comment by chrisroberts** [comment]
As has been discussed in previous issues, I won't be changing the default behavior of vagrant for the reasons already previously covered. I am open to adding some information in the `Vagrantfile` generated by the `init` command to make it clear to the user when the forwarded port is enabled. This can include the existing `forwarded_port` line with a note of it being publicly open on the network, and a second version with the `host_ip` set to localhost and a note of it _not_ being publicly open.

Cheers!

**Comment by Rascaile** [comment]
Having at least the documentation would be great so it is clear to newer users, especially when they are under an obligation to protect their work! Thanks Chris.
