### ISSUE TITLE
SSH error in box debian/jessie64

### ISSUE THREAD

**Issue by VincentChataignier** [mitchellh/vagrant#7817]
### Vagrant version

1.8.5
### Host operating system

Ubuntu 16.04.1 LTS
### Guest operating system

debian/jessie64 (v8.6.0) with VirtuaBox 5.0.24
### Vagrantfile

``` ruby
vagrant init debian/jessie64; vagrant up
```
### Debug output

Full log : [vagrant.log.txt](https://github.com/mitchellh/vagrant/files/487702/vagrant.log.txt)
Small log : [vagrant-small.log.txt](https://github.com/mitchellh/vagrant/files/487703/vagrant-small.log.txt)
### Expected behavior

Connect to the box with SSH
### Actual behavior

Connection of box with SSH not working. Vagrant error at line `default: SSH auth method: private key`
### Steps to reproduce
1. vagrant init debian/jessie64;
2. vagrant up;

**Comment by GuillaumeG22** [comment]
Hello,

I have the same issue with Windows 7 !

**Comment by GuillaumeG22** [comment]
@VincentChataignier

Hi,

I found a temporary solution.
You must specify an older version of the box

Try `config.vm.box_version = "= 8.5.0"`

**Comment by ozanhazer** [comment]
same here on mac

**Comment by mpavkovic** [comment]
+1 Had to revert to an older version of the box (8.5.2).

**Comment by chrisroberts** [comment]
I believe this is an issue with the upstream box, not vagrant itself. I'll pull the box and inspect it when I have time, but I have had login issues with other `debian/` prefixed boxes.

**Comment by brokaw** [comment]
Related debian bug. There's a new 8.6.1 debian box.
 [Vagrant box inaccessible due to missing network cable (VirtualBox)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838999)

**Comment by VincentChataignier** [comment]
Thanks. Version 8.6.1 of debian box is working for me. @chrisroberts, you can close this issue if you want.

**Comment by nartamonov** [comment]
No luck with 8.6.0, 8.6.1 and 8.6.2 :cry:

VirtualBox 5.0.10 r104061
Windows 7 SP1

**Comment by chrisroberts** [comment]
Closing via https://github.com/mitchellh/vagrant/issues/7817#issuecomment-254448028
