### ISSUE TITLE
Vagrantfile looping is not working as documented

### ISSUE THREAD

**Issue by alop** [mitchellh/vagrant#7820]
### Vagrant version
1.8.5

### Host operating system
Mac OS X 10.12

### Guest operating system
Ubuntu 12.04

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.define 'admin' do |admin|
    admin.vm.hostname = 'admin'
    admin.vm.network 'private_network', ip: '172.24.0.5', intnet: true
  end

  (1..3).each do |i|
    config.vm.define "ceph#{i}" do |node|
      node.vm.hostname = "ceph#{i}"
      node.vm.network "private_network", ip: "172.24.0.#{i}", intnet: true
      config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
        v.customize ['createhd', '--filename', "ceph_disk_#{i}a.vdi", '--size', 8192 ]
        v.customize ['createhd', '--filename', "ceph_disk_#{i}b.vdi", '--size', 8192 ]
        v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "ceph_disk_#{i}a.vdi"]
        v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', "ceph_disk_#{i}b.vdi"] 
      end
    end
```

### Debug output
https://gist.github.com/alop/ec077117faf5f227f0fc64f72ab3d396

### Expected behavior
Each VM should have disks attached to it corresponding to the value of #{i}
e.g.
ceph-1 should get ceph_disk_1a and ceph_disk_1b
ceph-2 should get ceph_disk_2a and ceph_disk_2b ... etc

### Actual behavior
ceph-1 is getting ceph_disk_1a and ceph_disk_1b attached
Vagrant then attempts to create ceph_disk_1a again, and fails as it's already been created
 
### Steps to reproduce
1. git clone https://github.com/alop/vagrant-ceph
2. vagrant up --no-provision
3.

**Comment by chrisroberts** [comment]
Hi! Looks like this line might be causing your issue:

```ruby
      config.vm.provider "virtualbox" do |v|
```

Replace `config` with `node` see if that clears up the problem. Please let me know if you're still having problems. Thanks!

**Comment by alop** [comment]
Thanks, this was an old project that worked 'as-is' in a version version. You suggestion makes it work in 1.8.5 now
