### ISSUE TITLE
ubuntu apache virtual host

### ISSUE THREAD

**Issue by chomyeong** [mitchellh/vagrant#7825]
Uh,i have some questions,i have build php server in ubuntu in my windows with vagrant ant I have configure apache vitrual host,but how can i visit my virtual host on my windows?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
