### ISSUE TITLE
Why only retry on wql and not on powershell?

### ISSUE THREAD

**Issue by StefanSchoof** [mitchellh/vagrant#7828]
### Vagrant version
1.8.5

### Host operating system
windows

### Guest operating system
windows

### Expected behavior
config a max retries for winrm does respect this on every request, not only on the wql?

### Actual behavior
In the [winrm/shell.rb](https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/winrm/shell.rb) is only a retryable block on the [wql](https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/winrm/shell.rb#L67) method.
The [powershell](https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/winrm/shell.rb#L56)  and [cmd](https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/winrm/shell.rb#L62) do not retry.

Is this the indented behavior?

**Comment by StefanSchoof** [comment]
@mwrock If I see correct powershell did retry before f912a81362140a72e6be7c3dd85f48994ea6c4d6. It calls [execute_shell_with_retry](https://github.com/mitchellh/vagrant/commit/f912a81362140a72e6be7c3dd85f48994ea6c4d6#diff-2e2f3d17c9aa332b915aef891a03b55bL89). Is this a regression? 

I think sometimes the wait_for_reboot fails with a exception in [@@exceptions_to_retry_on](https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/winrm/shell.rb#L22).

**Comment by mwrock** [comment]
@StefanSchoof the retry logic was pulled into the winrm executor: https://github.com/WinRb/WinRM/blob/v1.8.1/lib/winrm/command_executor.rb#L71

**Comment by StefanSchoof** [comment]
Ah okey. I understand. Thanks for the info.

**Comment by StefanSchoof** [comment]
Today i got a error with a HTTPClient::KeepAliveDisconnected on a wait_for_reboot.

Is there a way to increase the retry count?
```
An error occurred executing a remote WinRM command.

Shell: run_powershell_script
Command: # Function to check whether machine is currently shutting down
function ShuttingDown {
    [string]$sourceCode = @"
using System;
using System.Runtime.InteropServices;

namespace Vagrant {
    public static class RemoteManager {
        private const int SM_SHUTTINGDOWN = 0x2000;

        [DllImport("User32.dll", CharSet = CharSet.Unicode)]
        private static extern int GetSystemMetrics(int Index);

        public static bool Shutdown() {
            return (0 != GetSystemMetrics(SM_SHUTTINGDOWN));
        }
    }
}
"@
    $type = Add-Type -TypeDefinition $sourceCode -PassThru
    return $type::Shutdown()
}

if (ShuttingDown) {
  exit 1
} else {
  # See if a reboot is scheduled in the future by trying to schedule a reboot
  . shutdown.exe -f -r -t 60

  if ($LASTEXITCODE -eq 1190) {
    # reboot is already pending
    exit 2
  }

  # Remove the pending reboot we just created above
  if ($LASTEXITCODE -eq 0) {
    . shutdown.exe -a
  }
}

# no reboot in progress or scheduled
exit 0

if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
Message: HTTPClient::KeepAliveDisconnected: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. @ io_fillbuf -
fd:11
```

**Comment by mwrock** [comment]
While they don't appear to be documented [here](https://www.vagrantup.com/docs/vagrantfile/winrm_settings.html), `retry_delay` and `max_tries` should be valid config settings you can use in your Vagrantfile.

**Comment by mwrock** [comment]
Also, its likely helpful to know the defaults are:`max_tries`: 20 and `retry_delay`: 2 (seconds). Also note tha tthe retry logic only applies to openning a shell. If the shell was already openned and this is raised from running the command, then that usually means that either the machine rebooted or the winrm service restarted in the middle of the command. If you run with `--debug`, the stacktrace can point to where the failure occured.

**Comment by StefanSchoof** [comment]
Thanks for this infos. Then the default timeout is 40 seconds. So I think I git the Exception while the command is running. Since this only ralely occurs, I will try to Build a vagrantfile with a reboot loop and see if I can get the debug output.

________________________________

Rechtliche Hinweise:

solutions direkt AG I Vorstand I Dipl.-Inform. Markus Breilmann I Dipl.-Kfm. Kai Lehmann I Aufsichtsrat (Vorsitz) I Dipl.-Inform. (FH) Nils Schultz I Sitz Hamburg I AG Hamburg HRB 140889 I USt-IdNr. DE305591694

Anschrift I Griegstrasse 75, Haus 26 I 22763 Hamburg

Diese elektronische Nachricht enthaelt vertrauliche Informationen, die nur fuer die im Text bezeichneten Personen bestimmt sind. Die Nachricht ist durch das Briefgeheimnis geschuetzt und unterliegt gegebenenfalls den Regeln zum Schutz der Vertraulichkeit. Jede Benutzung, Versendung, Herstellung von Kopien oder Veroeffentlichung durch andere Personen ist ohne Zustimmung des Absenders untersagt. Wenn Sie diese Nachricht irrtuemlich erhalten haben, bitten wir Sie hoeflichst, sie auf Ihren Systemen zu loeschen und den Absender umgehend zu benachrichtigen.

This electronic mail transmission contains confidential information intended only for the person(s) named. It is subject to the laws of mail secrecy and may be protected by legal privileges. Any use, distribution, copying or disclosure by another person is strictly prohibited without the consent of the sender. If this transmission has been received in error, you are kindly requested to delete it from your system and to contact the sender immediately.
?
