### ISSUE TITLE
running multpile vagrant guests at the same time

### ISSUE THREAD

**Issue by zoff99** [mitchellh/vagrant#7838]
### Vagrant version

Vagrant 1.8.5
### Host operating system

Ubuntu 14.04.3 LTS
### Guest operating system

provider: virtual box 4.3.36_Ubuntu
guest: https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04/versions/2.2.9
### Expected behavior

when multiple vagrant systems are running at the same time, there should be no interference between them
### Actual behavior

when running more than 1 vagrant at the same time, it seems the machines mix up the ports, and nothing works correctly. only when i run just 1 at a time, all works, without any config change.
feels like 1 vagrant is using the ssh port of an already running one. then things get bad

**Comment by briancain** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
