### ISSUE TITLE
vagrant version shows "Latest Version" that is outdated

### ISSUE THREAD

**Issue by gebailey** [mitchellh/vagrant#7841]
### Vagrant version
```
$ vagrant -v
Vagrant 1.8.6
```

### Host operating system
```
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```
(Same issue occurs on Windows 7)

### Guest operating system
N/A

### Vagrantfile
N/A

### Expected behavior
I would expect `Latest Version:` to state `1.8.6`

### Actual behavior
```
$ vagrant version
Installed Version: 1.8.6
Latest Version: 1.8.5
 
You're running an up-to-date version of Vagrant!
```

### Steps to reproduce
1.  Install Vagrant 1.8.6
2.  Run `vagrant version`

### References
N/A

**Comment by chrisroberts** [comment]
Latest version is registered. The value is cached locally, so it may not be immediately visible. Thanks for the report!
