### ISSUE TITLE
Docs don't explain how to provide sudo password for shell provisioner's privileged option

### ISSUE THREAD

**Issue by zharvey-welltok** [mitchellh/vagrant#7842]
### Vagrant version

1.8.4
### Host operating system

Mac OS 10.11.5 (El Capitan)
### Guest operating system

CentOS 7.0 (https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box)
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.provision "shell", path: "install.sh"

  config.vm.box = "centos7"
  config.vm.box_url = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box"

  config.vm.network "private_network", ip: "10.0.1.2"
  config.vm.network :forwarded_port, guest: 2181, host: 2181
  config.vm.network :forwarded_port, guest: 9092, host: 9092

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
```
### Expected behavior

My `install.sh` needs to do things on the CentOS machine that require `sudo` (privileged) capabilities. Normally, I would run it on a linux box with `echo blahRootPassword | sudo -S sh install.sh`. But I'm trying to figure out how to provide that password (say, `blahRootPassword`) via my `Vagrantfile` or perhaps via the `vagrant up` command. Docs don't explain this, only mentioning that there is the `privileged` flag that is `true` by default.

**Please update docs w/ instructions for how users can provide `sudo` password for shell provisioners and their scripts (both inline and path).**

**Comment by chrisroberts** [comment]
For reference: `config.ssh.password = 'value'`

**Comment by chrisroberts** [comment]
I read this initially incorrectly, as the password desired is for `sudo`. There are certainly more than one way to accomplish this. The most straightforward is likely providing it via environment variable to the script and allow the script to run the sudo.

**Comment by chrisroberts** [comment]
As the recommended way to configure a vagrant box is to allow the vagrant user to `sudo` without a password, I'm going to close this. If you would like to add some documentation around strategies for providing a password when using `sudo` I would be happy to review a PR. Thanks!
