### ISSUE TITLE
Error Composer install

### ISSUE THREAD

**Issue by GlauberF** [mitchellh/vagrant#7845]
### Error Composer install
I try to run the install composer in a laravel project with the vagrant environment and the same of me this error, however is windows and the machine is clean, does not have php, everything runs in Homested

![composer](https://cloud.githubusercontent.com/assets/11314585/18954821/10987e44-862b-11e6-856d-6375f15ca1d7.png)

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄
