### ISSUE TITLE
Vagrant Powershell on non-Windows

### ISSUE THREAD

**Issue by MikaelSmith** [mitchellh/vagrant#7846]
With Powershell open-sourced and running on Mac and Linux, it seems that `vagrant Powershell` could be extended to support Powershell tempting from those host platforms.

Has anyone looked into this? I've done a little hacking but so far didn'5 get anything working.

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. As this is more of a question/conversation the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up) would be a better place for this. Thank you and have a great day! 😄

**Comment by MikaelSmith** [comment]
It was intended as a feature request, with possible offer to help implement it. I can certainly take the 2nd part to the mailing list.

**Comment by chrisroberts** [comment]
If you want to create a new issue as a feature request, that would be great. Thanks!
