### ISSUE TITLE
Failed to redirect TCP 127.0.0.1:2222 -> 0.0.0.0:22 (Unknown error)

### ISSUE THREAD

**Issue by pl4yradam** [mitchellh/vagrant#7847]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
_$ vagrant version
Installed Version: 1.8.6
Latest Version: 1.8.5
You're running an up-to-date version of Vagrant!_
### Host operating system

This is the operating system that you run locally.
Windows 10 (anniversary)
### Guest operating system

This is the operating system you run in the virtual machine.
Ubunto 64bit
### Vagrantfile
# -_\- mode: ruby -_-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
end

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.
### Debug output

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.
**http://pastebin.com/LAPqS6g1**
### Expected behavior

What should have happened?
It resumed passed the ssh auth
### Actual behavior

What actually happened?
it stalled causing virtual box to report:
00:00:00.300329 SUP: Opened VMMR0.r0 (C:\Program Files\Oracle\VirtualBox\VMMR0.r0) at 0xfffff800d6e00000 loaded by the native ring-0 loader.
00:00:00.854069   Driver <string>  = "NAT" (cb=4)
00:00:00.953839 SUP: Loaded VBoxDDR0.r0 (C:\Program Files\Oracle\VirtualBox\VBoxDDR0.r0) at 0xfffff800d7060000 - ModuleInit at 0000000000000000 and ModuleTerm at 0000000000000000 using the native ring-0 loader
00:00:00.981328 NAT: Guest address guess set to 10.0.2.15 by initialization
00:00:00.983978 NAT: DNS#0: 188.120.239.115
00:00:00.983992 NAT: DNS#1: 8.8.8.8
00:00:01.004256 NAT: Failed to redirect TCP 127.0.0.1:2222 -> 0.0.0.0:22 (Unknown error)
00:00:07.079394 NAT: IPv6 not supported
00:00:07.099008 NAT: DHCP offered IP address 10.0.2.15
00:00:07.099215 NAT: DHCP offered IP address 10.0.2.15
00:00:09.815733 NAT: Link up
### Steps to reproduce
1. copied the scotchbox vagrant file
2. vagrant up
### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
**no**

**Comment by pl4yradam** [comment]
HI guys, been trying to sort this for the past few days, I have found a way to get the box to pass SSH but the box itself can not access the internet.

`# -*- mode: ruby -*-
# vi: set ft=ruby :




Vagrant.configure("2") do |config|
 
    config.vm.box = "scotch/box"

    config.ssh.host = '192.168.33.10'
    config.ssh.port = '22'
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www/", :mount_options => ["dmode=777", "fmode=666"]

    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
end
`

this will allow you to the box, but the box will not hit the internet, virtualbox are saying they dont support and wont help, hoping to find some guidance here

**Comment by chrisroberts** [comment]
@pl4yradam if you use the following Vagrantfile, do you experience the same problem:

```ruby
Vagrant.configure('2') do |config|
  config.vm.box = "scotch/box"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end
```

**Comment by pl4yradam** [comment]
Hi Chris,

Thanks for taking the time to read, I have just tried the vagrant recommendation and the same happened again unfortunately:

00:00:00.363458 SUP: Loaded VMMR0.r0 (C:\Program Files\Oracle\VirtualBox\VMMR0.r0) at 0xfffff802852f0000 - ModuleInit at fffff802853135d0 and ModuleTerm at fffff80285313ac0 using the native ring-0 loader
00:00:00.747181   Driver <string>  = "NAT" (cb=4)
00:00:00.976036 SUP: Loaded VBoxDDR0.r0 (C:\Program Files\Oracle\VirtualBox\VBoxDDR0.r0) at 0xfffff80285410000 - ModuleInit at 0000000000000000 and ModuleTerm at 0000000000000000 using the native ring-0 loader
00:00:01.013386 NAT: Guest address guess set to 10.0.2.15 by initialization
00:00:01.016891 NAT: DNS#0: 188.120.239.115
00:00:01.016899 NAT: DNS#1: 8.8.8.8
00:00:01.040077 NAT: Failed to redirect TCP 127.0.0.1:2222 -> 0.0.0.0:22 (Unknown error)
00:00:07.098590 NAT: IPv6 not supported
00:00:07.124216 NAT: DHCP offered IP address 10.0.2.15
00:00:07.124574 NAT: DHCP offered IP address 10.0.2.15
00:00:09.886273 NAT: Link up

The above is from the virtualbox log (filtering on nat)

**Comment by chrisroberts** [comment]
@pl4yradam can you try a different box and see if you still have the same problem? Perhaps use:

```ruby
  config.vm.box = "bento/ubuntu-14.04"
```

**Comment by pl4yradam** [comment]
Hi Chris:
`# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    config.vm.box = "bento/ubuntu-14.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end`

Still hanging at:
default: SSH address: 127.0.0.1:2222
default: SSH username: vagrant
default: SSH auth method: private key

VirtualBox:
00:00:00.308035 SUP: Loaded VMMR0.r0 (C:\Program Files\Oracle\VirtualBox\VMMR0.r0) at 0xfffff802853c0000 - ModuleInit at fffff802853e35d0 and ModuleTerm at fffff802853e3ac0 using the native ring-0 loader
00:00:00.666834   Driver <string>  = "NAT" (cb=4)
00:00:00.873157 SUP: Loaded VBoxDDR0.r0 (C:\Program Files\Oracle\VirtualBox\VBoxDDR0.r0) at 0xfffff802854e0000 - ModuleInit at 0000000000000000 and ModuleTerm at 0000000000000000 using the native ring-0 loader
00:00:01.047277 NAT: Guest address guess set to 10.0.2.15 by initialization
00:00:01.049740 NAT: DNS#0: 188.120.239.115
00:00:01.049747 NAT: DNS#1: 8.8.8.8
00:00:01.072530 NAT: Failed to redirect TCP 127.0.0.1:2222 -> 0.0.0.0:22 (Unknown error)
00:00:10.141534 NAT: IPv6 not supported
00:00:10.141551 NAT: DHCP offered IP address 10.0.2.15
00:00:10.141755 NAT: DHCP offered IP address 10.0.2.15
00:00:10.763439 NAT: Link up

**Comment by chrisroberts** [comment]
@pl4yradam can you run `vagrant up --debug` and copy all the output into a gist and paste the link in here? Thanks!

**Comment by pl4yradam** [comment]
No problem:
`Vagrant.configure('2') do |config|
config.vm.box = "bento/ubuntu-14.04"

config.vm.provider "virtualbox" do |v|
v.memory = 4096
v.cpus = 2
end
end`

Ran: vagrant up --debug
https://gist.github.com/pl4yradam/275e090f5ef6661936c0793814b3ffd6

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
