### ISSUE TITLE
Vagrant ignores the "disabled: true" for "config.vm.synced_folder"

### ISSUE THREAD

**Issue by techraf** [mitchellh/vagrant#7851]
### Vagrant version
Vagrant 1.8.6

### Host operating system
OS X El Capitan 10.11.6 (15G1004)

### Guest operating system
OS X El Capitan 10.11.6

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  config.cache.scope = 'machine' if Vagrant.has_plugin?('vagrant-cachier')
  config.vm.box = 'elcapitan-crafted'
  config.ssh.insert_key = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vbguest.auto_update = false

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 2
    vb.memory = 1024
  end

  config.vm.define 'test-osx' do |c|
    c.vm.hostname = 'test-osx'
    c.vm.network 'private_network', type: 'dhcp', auto_config: true
  end
end
```

### Debug output
https://gist.github.com/techraf/651cd1ef8cb488f81e3163ac87b71b21

### Expected behavior
Vagrant should obey the line forcing it to disable shared folders:
```
config.vm.synced_folder ".", "/vagrant", disabled: true
```

### Actual behavior
Vagrant ignores the line and tries to mount the shared folder:
```
==> test-osx: Mounting shared folders...
    test-osx: /tmp/vagrant-cache => /Users/macraf/devops/testground/osx/.vagrant/machines/test-osx/cache
Vagrant is not able to mount VirtualBox shared folders on BSD-based
guests. BSD-based guests do not support the VirtualBox filesystem at
this time.

To change the type of the default synced folder, specify the type as
rsync or nfs:

    config.vm.synced_folder ".", "/vagrant", type: "nfs" # or "rsync"

Alternatively, if you do not need to mount the default synced folder,
you can also disable it entirely:

    config.vm.synced_folder ".", "/vagrant", disabled: true

You can read more about Vagrant's synced folder types and the various
configuration options on the Vagrant website.

This is not a bug in Vagrant.
```

- The configuration was working for months with Vagrant 1.8.5.
- The problem started with 1.8.5, upgrade to 1.8.6 did not resolve
- Noticed it around the time of `brew upgrade` (the only noticeable component was the upgrade from Ruby 2.3.1 to 2.3.1_1, relinking to 2.3.1 did not solve)

### Steps to reproduce
1. `vagrant up`

**Comment by vhosakot** [comment]
When I did `vagrant up` with the box `centos/7 (virtualbox, 1703.01)`, `==> default: Rsyncing folder: /root/ => /vagrant` was stuck for me too, and adding
`config.vm.synced_folder '.', '/vagrant', disabled: true`
in Vagrantfile resolved the issue for me and rsync did not happen.
