### ISSUE TITLE
Error `Invalid argument - ruby_setenv (Errno::EINVAL)` on all vagrant command

### ISSUE THREAD

**Issue by marema31** [mitchellh/vagrant#7857]
### Vagrant version
1.8.6

### Host operating system
Windows 7 64bits / Cygwin

### Expected behavior
At least a clearer error message -like the one on this [commit](https://github.com/mitchellh/vagrant/commit/1405395d813159a998a64fb82f9bd375786fc154)

### Actual behavior
Since update to 1.8.6 (from 1.8.4), every vagrant command does the following:
vagrant box list
C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler.rb:18:in `replace': Invalid argument - ruby_setenv(BUNDLE_ORIG_PATH) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler.rb:18:in `<module:Bundler>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.12.5/lib/bundler.rb:15:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:69:in `<main>'

By removing some environment variables, this problem disapear (as in Issue #6017

### References
- GH-6017

**Comment by ArthurZ** [comment]
In my case the issue appeared after I installed an update or new software.
So I fixed it by removing some what I deemed un-necessary entries in the System Path Environment Variable, then when it became = 1,888 chars Vagrant was able to start.
