### ISSUE TITLE
Can't use NFS with hyperv provider

### ISSUE THREAD

**Issue by andyp1per** [mitchellh/vagrant#7868]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version

Vagrant 1.8.6

### Host operating system

Windows 10 Pro

### Guest operating system

Ubuntu 16LTS

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
# The key part is:
  config.vm.box = "kmm/ubuntu-xenial64"
  config.vm.boot_timeout = 600
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
```

### Debug output
https://gist.github.com/andyp1per/18501dda0f62c48876fbd3dc33dfc014

### Expected behavior

I am using the vagrant-winnfsd plugin
I am provisioning using the hyperv provider
I expect to get shared folders via nfs 

### Actual behavior

The provisioning aborts with the error
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.

### References
In https://github.com/mitchellh/vagrant/issues/4192 you say that it is the providers responsibility
to implement prepare_nfs_settings. As far as I can tell the hyperv plugin does not implement this.

**Comment by chrisroberts** [comment]
This is a dup of #7816 Thanks for the report!
