### ISSUE TITLE
Htop says “530G” in “VIRT” for “vagrant ssh”

### ISSUE THREAD

**Issue by rap2hpoutre** [mitchellh/vagrant#7870]
Running htop, I can see vagrant ssh process can use virtually 530G (in VIRT Column).

Is it the normal behavior of Vagrant? Should I panic? Is it "normal" to have virtually 530G on a mac with 120G of disk and 16G of RAM? Or maybe did I not understand the meaning of VIRT? The vagrant box runs on virtual box and has only 1G of RAM allocated.

### Vagrant version
Vagrant 1.8.6 (fresh install)

### Host operating system
MacOS 10.12

### Guest operating system
ubuntu 64 xenial 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.10"
end
```

### Expected behavior
Less VIRT memory for vagrant SSH

### Actual behavior
Htop says “530G” in “VIRT” for “vagrant ssh”

### Steps to reproduce
1. install vagrant on macos
2. install box unbuntu 64 xenial 16.04
3. run `vagrant ssh`

### References
Asked on stackoverflow with no response: 
https://stackoverflow.com/questions/39875367/htop-says-530g-in-virt-for-vagrant-ssh

**Comment by chrisroberts** [comment]
See here: https://github.com/mitchellh/vagrant/issues/7296#issuecomment-252373435
