### ISSUE TITLE
ansible_local documentation is missing galaxy instructions.

### ISSUE THREAD

**Issue by kitsunde** [mitchellh/vagrant#7871]
On: https://www.vagrantup.com/docs/provisioning/ansible_local.html

It's missing documentation for this behaviour:

``` yml
ansible.galaxy_role_file = 'requirements.yml'
ansible.galaxy_roles_path = '/home/vagrant/ansible_galaxy'
```

**Comment by gildegoma** [comment]
These two Galaxy settings are shared by `ansible` and `ansible_local` provisioners, and documented at

https://www.vagrantup.com/docs/provisioning/ansible_common.html#galaxy_role_file

Maybe adding a specifc example in _Tips and Tricks_ section of the `ansible_local` provisioner could help to make things more evident...

**Comment by gildegoma** [comment]
Closing per lack of feedbacks. Pull requests to improve the docs are always welcome ;-)
