### ISSUE TITLE
Error upgrading to 1.8.6 on ubuntu 14.04

### ISSUE THREAD

**Issue by mtbvang** [mitchellh/vagrant#7882]
### Vagrant version
1.6.5

### Host operating system
Ubuntu 14.04

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
/var/lib/gems/1.9.1/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:134:in `match': invalid byte sequence in UTF-8 (ArgumentError)
	from /var/lib/gems/1.9.1/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:134:in `match'
	from /var/lib/gems/1.9.1/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:134:in `block in find_vagrant'
	from /var/lib/gems/1.9.1/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:131:in `each'
	from /var/lib/gems/1.9.1/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:131:in `find_vagrant'
	from /var/lib/gems/1.9.1/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:153:in `exec_vagrant'
	from /var/lib/gems/1.9.1/gems/vagrant-wrapper-1.2.1.1/lib/vagrant-wrapper.rb:67:in `execute'
	from /var/lib/gems/1.9.1/gems/vagrant-wrapper-1.2.1.1/bin/vagrant:12:in `<top (required)>'
	from /usr/local/bin/vagrant:23:in `load'
	from /usr/local/bin/vagrant:23:in `<main>'

### Expected behavior
Vagrant works after upgrade to 1.8.6. I tried downgrading to 1.7.4 which did not work and then 1.6.5 which does work. I think I had vagrant 1.7.1 running before the upgrade which was installed over a year ago. I tried to upgrade to 1.8.1 first because of a typo which didn't work and then 1.8.6 and 1.7.4 which didn't work either until 1.6.5 finally worked. It looks like some other users were getting a similar error

### Actual behavior
I get the above vargrant wrapper error when running vagrant after the upgrade.

### Steps to reproduce
1. Downloaded vagrant_1.8.6_x86_64.deb file from https://www.vagrantup.com/downloads.html
2. sudo dpkg -i vagrant_1.8.6_x86_64.deb
3. Run any vagrant command.

### References
#6056 also was a similar encoding issue that was closed.

**Comment by chrisroberts** [comment]
Hi. From the error you provided above it looks like you have either a vagrant system package installed, or a gem installation in the system ruby that is being run. Ensure you have uninstalled any vagrant packages provided by the system, and uninstalling the `vagrant-wrapper` gem would likely be needed as well.

Cheers!

**Comment by mtbvang** [comment]
Doing a purge of vagrant from my system and reinstalling did the trick. Thanks.

**Comment by chrisroberts** [comment]
:+1: glad you got it fixed up!
