### ISSUE TITLE
Creating a VM from a custom Centos box, with a provisioning script, breaks the private_network setting

### ISSUE THREAD

**Issue by wfsaxton** [mitchellh/vagrant#7884]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

1.8.6
### Host operating system

Windows 10
### Guest operating system

Centos 7.1 & 7.2
### Vagrantfile (for creating the box)

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.provision :shell, path: "vagrant_bootstrap.sh"
  config.ssh.insert_key = false
```

Then, to create the box:

```
vagrant up
vagrant package --output elk.box
vagrant box add wsaxton/elk .\elk.box
```
### Vagrantfile (for using the new box)

``` ruby
Vagrant.configure("2") do |config|
  config.vm.define "elk" do |elk|
    elk.vm.box = "wsaxton/elk"
    elk.ssh.insert_key = false
    elk.vm.network "private_network", ip: "192.168.1.100"
    elk.vm.hostname = "elk.local"
  end
```
### Debug output

Debug output for creating the initial VM: https://gist.github.com/wsaxton/a169c444a16909480f2d4ac6aa288355

Debug output for creating the VM from the new box:
https://gist.github.com/wsaxton/2e5fc214f04df6c181be6e46e525e0fd
### Expected behavior

The network interface "enp0s8" should be plumbed up with the private network IP.
### Actual behavior

If the box is created with the provisioning script "vagrant_bootstrap.sh", the network interface is never set to the private_network IP.  If I remove the provision script, it works fine.  NOTE: The provisioning script itself can be empty!  (just #!/usr/bin/bash)
### Steps to reproduce
1. Create a VM from the first vagrant file
2. Package it up into a box
3. Create a VM from the box, both without a provisioning script (works) and with one (doesn't work).
### References

None that I'm aware of.

**Comment by chrisroberts** [comment]
I believe that #7866 fixes this from my initial read through. Need to repro it locally to validate.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
