### ISSUE TITLE
How can I connect to vm configured with private/public networking by ssh command.

### ISSUE THREAD

**Issue by buptmiao** [mitchellh/vagrant#7892]
when I ssh to the vm by the command below:

```
ssh vagrant@192.168.4.10
```

I encountered a timeout with the message below:

```
ssh: connect to host 192.168.4.10 port 22: Operation timed out
```

It seems it can't find that IP address. but vagrant ssh is OK.

So How can I login the vm by just ssh cmd.
### Vagrant version

Vagrant 1.8.5
### Host operating system

OSX 10.11.3
### Guest operating system

linux
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|

  config.vm.define "test" do |machine|
    machine.vm.box = "trusty-server-cloudimg-amd64-vagrant-disk1"
    machine.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    machine.vm.hostname = "test"
    machine.vm.network "public_network", ip: "192.168.4.10"
    machine.vm.provider "virtualbox" do |node|
        node.name = "test"
        node.memory = 4048
        node.cpus = 2 
    end 
   end 
end
```
### Debug output

[vagrant up output](https://gist.github.com/buptmiao/f3bb03d5af19db8597fde7c1b77ef91d)
### Expected behavior

ssh succeed
### Actual behavior

as described above
### Steps to reproduce
1. vagrant up
2. ssh vagrant@192.168.4.10

**Comment by buptmiao** [comment]
I change the networking setting of virtualbox from NAT(seems selected by default) to Host-Only and the interface to vboxnet3 where contains 192.168.4.10.  then I get it work.

**Comment by chrisroberts** [comment]
That information can be found in the networking documentation: https://www.vagrantup.com/docs/networking/

Cheers!
