### ISSUE TITLE
Vagrantup.com Site SSL Cert Is Revoked

### ISSUE THREAD

**Issue by jtwebman** [mitchellh/vagrant#7894]
The SSL cert on your site has been revoked because a cert in the trust chain was revoked. You need to get a new cert ASAP as the site is down for Chrome users unless they trust your revoked cert.

This is for https://vagrantup.com

**Comment by chrisroberts** [comment]
Hi! Thanks for letting us know about this. It is a known issue and is being tracked. You can see more here:

https://status.hashicorp.com/incidents/3pzzfz2z8w6k

Cheers!
