### ISSUE TITLE
rsync installation by vagrant broken on openbsd

### ISSUE THREAD

**Issue by ThomasWaldmann** [mitchellh/vagrant#7898]
### vagrant version
Vagrant 1.8.6 (from .deb package)

### Host
Ubuntu Linux 16.04

### Guest
OpenBSD 6.0 (but also affects 5.x)

### Vagrantfile (excerpt)
```ruby
...
Vagrant.configure(2) do |config|
  # use rsync to copy content to the folder
  config.vm.synced_folder ".", "/vagrant/borg/borg", :type => "rsync", :rsync__args => ["--verbose", "--archive", "--delete", "-z"]
  # do not let the VM access . on the host machine via the default shared folder!
  config.vm.synced_folder ".", "/vagrant", disabled: true
...
```

### Expected behavior:
vagrant should install rsync into the openbsd box.

### Actual behavior
vagrant silently fails installing rsync. leads to subsequent Error: sudo: rsync: command not found

```
$ vagrant up openbsd64
...
    openbsd64: Inserting generated public key within guest...
    openbsd64: Removing insecure key from the guest if it's present...
    openbsd64: Key inserted! Disconnecting and reconnecting using new SSH key...
==> openbsd64: Machine booted and ready!
==> openbsd64: Installing rsync to the VM...
==> openbsd64: Rsyncing folder: /home/tw/w/borg/ => /vagrant/borg/borg
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/tw/w/borg/
Guest path: /vagrant/borg/borg
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/tmp/ssh.252 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/home/tw/w/borg/.vagrant/machines/openbsd64/virtualbox/private_key'" "--exclude" ".vagrant/" "/home/tw/w/borg/" "vagrant@127.0.0.1:/vagrant/borg/borg"
Error: sudo: rsync: command not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
```

### References
https://github.com/borgbackup/borg/issues/1695 (this will soon be closed as a workaround can be done using a openbsd box with pre-installed rsync. nevertheless, installing rsync is a expected capability of vagrant and many vagrant boxes out there do not have preinstalled rsync.)

**Comment by ThomasWaldmann** [comment]
Maybe related to: #7901

**Comment by chrisroberts** [comment]
I have an openbsd 5.9 box that I am unable to reproduce this behavior on. Are you using a public box?

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/master/Vagrantfile#L445 yes, see there.

**Comment by chrisroberts** [comment]
Thanks!

**Comment by chrisroberts** [comment]
@ThomasWaldmann do you encounter the same error with just a simple Vagrantfile:

```ruby
Vagrant.configure('2') do |config|
  config.vm.synced_folder ".", "/tmp/vagrant", type: "rsync", :rsync__args => ["--verbose", "--archive", "--delete", "-z"]
  config.vm.box = 'kaorimatz/openbsd-5.9-amd64'
end
```

This has been working locally without issue. Thanks!

**Comment by ThomasWaldmann** [comment]
crap, I have trouble reproducing it. :-( I tried misc box version, our 1.0-maint and master branch - no failure right now.

ok, can we just accept that it failed to install rsync somehow (same see the netbsd ticket I also filed), which can be seen in the log output: "Error: sudo: rsync: command not found"

The main issue is not that rsync installation failed, but that:
- it failed silently, not allowing any further investigation
- it didn't detect the failure in that step, otherwise it could maybe just show stdout/stderr of the commands that failed
- only the error in the next step is visible, when it tries to use rsync, but that error is pretty useless (except for pointing to a box with pre-installed rsync as a workaround).

**Comment by chrisroberts** [comment]
I wrote out a long reply to this basically stating that without reproduction, a fix can't reasonably be proposed as the actual problem can't be identified. With the `pkg_add` command not failing, my hunch was that maybe the `PATH` got messed up, or the package was corrupt, or some other transient issue. Mainly, that it can't be accepted that vagrant failed to install rsync due to there being no error returned from `pkg_add`. The installation failure could only be caused if `pkg_add` was reporting success when it was in fact failing.

Before I commented and closed, I decided to just give a quick check to validate that `pkg_add` was acting as expected and this is what I found:

```
# uname -a
OpenBSD vagrantup.localdomain 5.9 GENERIC#1761 amd64
# pkg_add totally-fake-package; echo $?
quirks-2.197 signed on 2016-02-26T22:06:23Z
Can't find totally-fake-package
0
#
```
So that's fun! I whipped up a quick PR that does a validation after installation and will error if the rsync package doesn't get installed (#7929).

Thanks so much for the report! Quite the elusive issue :smile:

**Comment by ThomasWaldmann** [comment]
Haha. Will you file a bug to openbsd project? Guess this is something they should fix.

Not just for non-existing packages (because in my case, the package name was right), but maybe also for other failures that exit with 0.
