### ISSUE TITLE
How can I use proxy through Vagrant::Util::Downloader utility?

### ISSUE THREAD

**Issue by budhrg** [mitchellh/vagrant#7903]
Hi Folks,

I have a use case where I am using Vagrant native downloader to download a file from url to some location locally.

Now, I have requirement where my workstation doesn't have any internet access except to proxy server.

As I remember, curl support proxy as [ answered here ](http://stackoverflow.com/a/27837460/1120530) :
```
curl http://www.example.com --proxy http://125.119.175.48:8909
```

Can I achieve similar thing with `Vagrant::Util::Downloader` utility class?

Thanks

**Comment by budhrg** [comment]
Hi @sethvargo, any idea about it? Can we achieve this or I need to write my own customized downloader?

**Comment by chrisroberts** [comment]
The curl command will use the `http_proxy` and `https_proxy` environment variables when set. You should be able to set the `http_proxy` environment variable to your proxy which will allow curl to download. For more information you can see the curl man page. Towards the bottom of the page is a section titled **ENVIRONMENT**.

https://curl.haxx.se/docs/manpage.html

Cheers!
