### ISSUE TITLE
Vagrant 1.8.6 rsync does not escape "exclude" paths

### ISSUE THREAD

**Issue by asiebert** [mitchellh/vagrant#7910]
A colleague of mine just upgraded his Vagrant installation to 1.8.6, and his `vagrant up` or `reload` began to fail with a rsync error:
```
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /Users/NAME/PROJECT/ => /home/vagrant/PROJECT
==> default:   - Exclude: [".vagrant/", ".git", "/cache/*", ......]
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

find /home/vagrant/PROJECT -path /home/vagrant/PROJECT/.git -prune -o -path /home/vagrant/PROJECT/cache/* -prune ...... -o '!' -type l -a '(' ! -user vagrant -or ! -group vagrant ')' -exec chown vagrant:vagrant '{}' +

Stdout from the command:



Stderr from the command:

stdin: is not a tty
find: paths must precede expression: /home/vagrant/PROJECT/cache/apply
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]```



config.vm.synced_folder "../PROJECT" , "/home/vagrant/PROJECT" , type: "rsync", rsync__exclude: [".git", "/cache/*", ......]
``` 

Meta info:
* Vagrant v. 1.8.6
* OS affected: Mac OS X 10.12 (Sierra), Linux Ubuntu 16.04 (Xenial)
* Guest operating system: Linux Ubuntu 14.04 (Trusty) on VirtualBox 5.0.24+

Steps to reproduce: modify your Vagrantfile so `config.vm.synced_folder` uses rsync, and exclude paths with wildcards (`*`) having multiple existing matches in the shared folder (`cache/api` and `cache/apply` in our case).
Example config for the aforementioned output:
```ruby
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "../PROJECT" , "/home/vagrant/PROJECT" , type: "rsync", rsync__exclude: [".git", "/cache/*", ......]
  ...
end
```

I believe the following line, introduced in 1.8.6, is the source for this issue: https://github.com/mitchellh/vagrant/commit/185a7dfc2e89e7f72dbd33f548b60e4b08fa7a64#diff-db6f247c4ba86f770b1601c03e9a5e3cR35
Simply wrapping `#{exclude_base.join(ex_path)}` locally with single quotes is enough to prevent wildcards from being expanded before being passed to `find` and wrecking it.

**Comment by stuxcrystal** [comment]
It doesn't work on Windows 10, too.

**Comment by solidevolution** [comment]
Same here, please fix. We updated to 1.8.6 to solve this bug in 1.8.5: https://github.com/mitchellh/vagrant/issues/7610

Do you use a test framework?

**Comment by ksinghttam** [comment]
Same here.
