### ISSUE TITLE
Numeric username bigger than ulong gives error with -U option

### ISSUE THREAD

**Issue by AndreFelipeMachado** [mitchellh/vagrant#7911]
Hello,
The company I work for is using an Ubuntu 12.04 (soon 16.04) modified with very long UID (11 digits).
Vagrant is unable to correctly launch Origin All In One VM because of this. And other VirtualBox vm too.
There is an old Ubuntu report of exactly this issue containing a patch for an external program, a workaround.
https://bugs.launchpad.net/ubuntu/+source/procps/+bug/1478655
Is there a way of vagrant to be modified to not be limited by this?
Regards.

### Vagrant version
Vagrant 1.8.6

### Host operating system

Ubuntu Precise 12.04 LTS

### Guest operating system
OpenShift-all-in-One
https://vagrantcloud.com/openshift/boxes/origin-all-in-one

### Vagrantfile
```ruby

# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.2"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version. Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  #config.ssh.insert_key = true
  config.vm.box = "thesteve0/openshift-origin"
  config.vm.provider "virtualbox"
  #uncomment this line if you downloaded the box and want to use it instead
  #config.vm.box = "openshift3"
  config.vm.box_check_update = true
  config.vm.network "private_network", ip: "10.2.2.2"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #adding this in for debugging purposes. This should work even if the 10.2.2.2 virtual nic doesn't work
  config.vm.network "forwarded_port", guest: 8443, host: 8443




  config.vm.provider "virtualbox" do |vb|
#AFM 20161014 gui and memmory and vcpu
#     vb.customize ['modifyvm', :id, '--pae', 'on']
##     vb.customize ['modifyvm', :id, '--hwvirtex', 'off']
#     vb.customize ['modifyvm', :id, '--vtxvpid', 'off']
     vb.customize ["modifyvm", :id, "--usb", "on"]
     vb.customize ["modifyvm", :id, "--usbehci", "on"]
     
     vb.gui = true
     vb.memory = "2048"
     vb.cpus = 2

     vb.name = "openshift-origin"
     #commented out because of issues with F23
     #vb.customize ["modifyvm", :id, "--ioapic", "on"]
     #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo
    echo "Successfully started and provisioned VM with 2 cores and 5 G of memory."
    echo "To modify the number of cores and/or available memory modify your local Vagrantfile"
    echo
    echo "You can now access the OpenShift console on: https://10.2.2.2:8443/console"
    echo
    echo "Configured users are (<username>/<password>):"
    echo     "admin/admin"
    echo     "user/user"
    echo "But, you can also use any username and password combination you would like to create"
    echo "a new user."
    echo
    echo "You can find links to the client libraries here: https://www.openshift.org/vm"
    echo "If you have the oc client library on your host, you can also login from your host."
    echo
    echo "To use OpenShift CLI, run:"
    echo "$ oc login https://10.2.2.2:8443"
    echo
  SHELL

end
```

### Debug output

https://gist.github.com/AndreFelipeMachado/38c12ae01fbc9cee251eaf526a81374d

### Expected behavior
Openshift all in one should had start correctly. 

### Actual behavior
The VM started on GUI but openshift is unreacheable.
Machine entered an invalid state.

### Steps to reproduce
1. Have an Ubuntu using modified UID numbers beyond 11 digits.
2. Follow instructions at https://www.openshift.org/vm/

### References
This launchpad  bug report posted by other people contains a patch for an external program, instead of vagrant.
https://bugs.launchpad.net/ubuntu/+source/procps/+bug/1478655

**Comment by chrisroberts** [comment]
Hi! Thanks for opening an issue but after reviewing the setup and debug output, the root cause of the error is the inability of `ps` within the guest to properly handle the modified UIDs. Patching the `ps` utility on the guest box with the patch linked to above should properly resolve this issue.

Thanks!
