### ISSUE TITLE
config.vm.box_url does not handle space character in path.

### ISSUE THREAD

**Issue by sunnz** [mitchellh/vagrant#7912]
Other variations of box_url that I have tried but no avail are:
- "file:///Volumes/Our Share/Dev/boxes/mybase.json"
- "file:///Volumes/Our%20Share/Dev/boxes/mybase.json"
- "/Volumes/Our%20Share/Dev/boxes/mybase.json"

**Edit**: also tried:
- "/Volumes/Our\ Share/Dev/boxes/mybase.json" (as @thom8 suggested)
- "file://Volumes/Our\ Share/Dev/boxes/mybase.json"
- `"file://Volumes/Our\\ Share/Dev/boxes/mybase.json"` (double backslash)
- `"/Volumes/Our\\ Share/Dev/boxes/mybase.json"` (double backslash)
### Vagrant version

Vagrant 1.8.6
### Host operating system

OSX
### Guest operating system

Linux
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "mybase"
  config.vm.box_url = "/Volumes/Our Share/Dev/boxes/mybase.json"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2000"
  end
end
```
### Debug output

https://gist.github.com/sunnz/8d69ee5a1ad95c254ef3d350296c101c
### Expected behavior

Add box from config.vm.box_url.
### Actual behavior

File specified at config.vm.box_url not downloaded.
### Steps to reproduce
1. vagrant up

**Comment by thom8** [comment]
`Error opening archive: Unrecognized archive format`

@sunnz this error suggests that the URL is not a valid box file - https://www.vagrantup.com/docs/boxes/format.html

**Comment by sunnz** [comment]
It is not box file, it is box metadata JSON document. It currently works over http and on the local file system when there are no space in the path, vagrant just look inside the json object and downloads the box file from there. See more details at "BOX METADATA" section from that link. :-)

**Comment by thom8** [comment]
have you tried escaping the space?

`config.vm.box_url = "/Volumes/Our\ Share/Dev/boxes/mybase.json"`

**Comment by sunnz** [comment]
Just tried that, no dice :-(

Vagrantfile:

`config.vm.box_url = "/Volumes/Our\ Share/Dev/boxes/mybase.json"`

Output:

```
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'mybase' (v0) for provider: virtualbox
    default: Unpacking necessary files from: file:///Volumes/Our%20Share/Dev/boxes/mybase.json
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format
```

I also tried: `"file://Volumes/Our\ Share/Dev/boxes/mybase.json"`, same result, vagrant just converts it to `%20`.

Also tried:

- "file://Volumes/Our\\ Share/Dev/boxes/mybase.json"
- "/Volumes/Our\\ Share/Dev/boxes/mybase.json"

Triggers InvalidURIError:

- `/opt/vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in 'split': bad URI(is not URI?): file:///Volumes/Our/ Share/Dev/boxes/mybase.json (URI::InvalidURIError)`
- `/opt/vagrant/embedded/lib/ruby/2.2.0/uri/rfc3986_parser.rb:66:in 'split': bad URI(is not URI?): /Volumes/Our/ Share/Dev/boxes/mybase.json (URI::InvalidURIError)`

**Comment by sunnz** [comment]
From looking at

```
Box file was not detected as metadata. Adding it directly
```

I am suspecting that vagrant was able to load the file but didn't detect that it is box metadata, whereas over http this would be set to json in the http header?

But then it does work on the local file system.. anyway, just brainstorming..

**Comment by tokp** [comment]
I have the same issue with config.vm.box_url, I can load a .box from a SMB share with spaces in the path but I cant load a .json in the same manner.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by SquirrelAssassin** [comment]
bad close ... close without testing == failure
Installed Version: 2.1.2
config.vm.synced_folder "C:/Users/user.name/OneDrive - company name/Documents/vboxsharefolder", "/vagrant", smb_password: "<pwd>", smb_username: "<usr>", type: "smb"


Error:
Host path: C:\Users\user.name\OneDrive

Stderr: The name has already been shared.

More help is available by typing NET HELPMSG 2118.

error

Stdout: share path: C:\Users\user.name\OneDrive
