### ISSUE TITLE
dockerfile build failing when dockerfile parameter of the docker provider is set

### ISSUE THREAD

**Issue by jdwagnerjr** [mitchellh/vagrant#7914]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

both 1.8.1 and 1.8.6
### Host operating system

Linux Mint 18
### Guest operating system

Centos 6.8 but irrelevant in this case
### Vagrantfile
# -_\- mode: ruby -_-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.define "A" do |a|
        ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
        a.vm.provider "docker" do |d|
            d.build_dir = "."
            d.dockerfile = "Dockerfile"
        end
    end
end
### Debug output

https://gist.github.com/jdwagnerjr/123a847c76cdd9827934d6aa7ebc9b1c

key output

A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "build", "--file=\"/home/jdwagner/eraser_board/vagrant_issue/Dockerfile\"", "/home/jdwagner/eraser_board/vagrant_issue", {:notify=>[:stdout, :stderr]}]

Stderr: unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/jdwagner/eraser_board/vagrant_issue/": no such file or directory
### Expected behavior

expected a centos docker to be launched
### Actual behavior

docker build command fails due to being unable to parse the dockerfile path

while unconfirmed may be caused by a parsing issue which is letting a single quote through at the end of the line. this is based on the Stderr output from the docker build command having a single trailing quote
### Steps to reproduce
1. create a docker file
2. create a vagrant file using a docker provider
3. set the build dir to the dir where the dockerfile is located
4. set the dockerfile to the name of the dockerfile
5. run vagrant up

**Comment by beniwtv** [comment]
Same issue here, running the command in the debug output manually does work, so the Docket command line is being built correctly.

Still an issue in latest 1.8.7

**Comment by ckchow** [comment]
I still get this issue in 1.9.0, but my generated command line has more escaping backslashes in it. 

```
Command: ["docker", "build", "--file=\"/home/chris/projects/Drone/Dockerfile\"", "/home/chris/projects/Drone", {:notify=>[:stdout, :stderr]}]

Stderr: unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/chris/projects/Drone/": no such file or directory
```

**Comment by beniwtv** [comment]
Any fix for this issue? This makes it impossible to use vagrant with Docker!

**Comment by beniwtv** [comment]
I fixed it by temporarily hacking a file in vagrant:

(plugins/providers/docker/action/build.rb, line 46)

remove the extra quotes:

`args.push("--file=\"#{dockerfile_path}\"")`

like so:

`args.push("--file=#{dockerfile_path}")`
