### ISSUE TITLE
Vagrant 1.8.6 not compatible with latest ChefDK (0.19.6)

### ISSUE THREAD

**Issue by olbrich** [mitchellh/vagrant#7916]
### Vagrant version
1.8.6

### Chef version
Chef Development Kit Version: 0.19.6
chef-client version: ERROR
delivery version: master (802e801d920ea6b6d48db735aa7c6e7a6194bea4)
berks version: 5.1.0
kitchen version: ERROR

### Host operating system
Mac OSX Sierra

### Details

```
$ vagrant up

Bringing machine 'default' up with 'aws' provider...
The Berkshelf version at "/opt/chefdk/bin/berks" is invalid.
Vagrant Berkshelf requires ~> 4.0, but the current version is 5.1.0.

Please download and install the latest version of the ChefDK from:

    https://downloads.chef.io/chef-dk

and follow the installation instructions. Do not forget to add the ChefDK to
your PATH.
```

This looks like a conflict between the version of Berkshelf used by chefdk and Vagrant

**Comment by deancsmith** [comment]
Are you using the vagrant-berkshelf plugin @olbrich?

This might be related to this PR? https://github.com/mitchellh/vagrant/pull/7833

**Comment by olbrich** [comment]
Turns out I did have `vagrant-berkshelf` installed from a previous version.  After re-installing it, I can get `vagrant up` to work properly and provision correctly.
