### ISSUE TITLE
box-cutter/centos72 box file location

### ISSUE THREAD

**Issue by ighouri** [mitchellh/vagrant#7917]
Where do I find hashicorp box files ?

For example:
For hashicorp/precise64, here is the file location http://files.vagrantup.com/precise64.box

How about box-cutter/centos72 box ? I am unable to find the image *.box file.

Actual Problem: My server does not have the capability to talk outside world (https://atlas.hashicorp.com/box-cutter/boxes/centos72) and hence vagrant box add box-cutter/centos72 is not working. If I get the image file, I can host it privately in my org and then use it in VagrantFile like: config.vm.box_url = "http://repos.myorg.com/base/box-cutter/centos72.box"

**Comment by chrisroberts** [comment]
Hi! You can add the box locally, then repackage it to provide a local box file that can then be hosted internally. Relevant documentation for the `box repackage` command is here: https://www.vagrantup.com/docs/cli/box.html#box-repackage

Cheers!
