### ISSUE TITLE
Tries to assign VM wrong IP addresss

### ISSUE THREAD

**Issue by tleyden** [mitchellh/vagrant#7923]
### Vagrant version

Fails on 1.8.6
Works on 1.8.1
### Host operating system

OSX El Capitan
### Guest operating system

CentOS7
### Vagrantfile

``` ruby

Vagrant.configure(2) do |config|

  host_ip = {
    "couchbase-server" => "192.168.34.10",    
    "sync-gateway1" => "192.168.34.11",
    "sync-gateway2" => "192.168.34.12",
    "nginx" => "192.168.34.13",    
    "sync-gateway3" => "192.168.34.14",    
  }

  host_ip.each do |host_name, ip|
      config.vm.define host_name do |host|
        host.vm.box = "couchbase-mobile-training"
        host.vm.hostname = host_name
        host.vm.network "private_network", ip: ip
        host.vm.synced_folder ".", "/tmp/sync", disabled: true
        host.vm.provider "virtualbox" do |vb|
            # Customize the amount of memory on the VM:
            vb.memory = "2048"

            # Allow vm to send data via VPN
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
      end
  end

end
```
### Debug output

https://gist.github.com/a3269e1b9faed297887cf52ec86a37f9
### Expected behavior

It should start up the VM cluster without errors
### Actual behavior

The VM startup fails with this output:

https://gist.github.com/tleyden/ab07fc01f68dddc4db64de05d7387f2c#file-stdout

More logs from the VM available here: https://gist.github.com/tleyden/ab07fc01f68dddc4db64de05d7387f2c
### Steps to reproduce
1. `wget http://cbmobile-bucket.s3.amazonaws.com/training-virtual-machines/couchbase-mobile-training.box`
2. Save `Vagrantfile` listed in this ticket
3. `vagrant up`

**Comment by mikefaille** [comment]
@tleyden

**Comment by mikefaille** [comment]
@tleyden Could you upgrade Vagrant to 1.8.7 ?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
