### ISSUE TITLE
Vagrant docker provider link ordering

### ISSUE THREAD

**Issue by ascotan** [mitchellh/vagrant#7927]
When you run a Vagrantfile that has linked docker containers, the containers are spawned randomly even though there is a order dependency on the links.  Because links are not allow to be recursive (which i think is a different issue) there needs to be a launch order.  I would suggest that there are probably 2 ways to handle this.
1. Order dependent launching which entails scanning the Vagrantfile (good)
2. Allow circular linking by resolving links after launch (better)
### Vagrant version

Vagrant 1.8.5
### Host operating system

Mac OS Sierra
### Guest operating system

Centos 6 Docker container running on Docker native
### Vagrantfile

``` ruby
...
  config.vm.define "secondary"do |secondary|
    secondary.vm.provider :docker do |d|
      d.build_dir = "."
      d.name = "secondary"
      d.force_host_vm = false
      d.has_ssh = true
      d.link("ftp:ftp")
      d.link("other:other")
    end
    secondary.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/xxx.yml"
    end
  end
....
  config.vm.define "ftp"do |ftp|
    ftp.vm.provider :docker do |d|
      d.build_dir = "."
      d.name = "ftp"
      d.force_host_vm = false
      d.has_ssh = true
    end
    ftp.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/yyy.yml"
    end
  end
....
#more containers...
```
### Debug output

==> ftp: Machine booted and ready!
==> ftp: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> ftp: flag to force provisioning. Provisioners marked to run always will still run.
==> publisher: Machine booted and ready!
==> publisher: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> publisher: flag to force provisioning. Provisioners marked to run always will still run.

An error occurred while executing the action on the 'secondary'
machine. Please handle this error then try again:

A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "start", "1cbc75e9597db067759fe0fe97868d0137ccb4d172e7bf53c56d117cf0f97c4c", {:notify=>[:stdout, :stderr]}]

Stderr: Error response from daemon: Cannot link to a non running container: /ftp AS /secondary/ftp
Error: failed to start containers: 1cbc75e9597db067759fe0fe97868d0137ccb4d172e7bf53c56d117cf0f97c4c
### Expected behavior

The containers should launch and be linked
### Actual behavior

Containers are launched randomly and have to be manually launched in order.
### Steps to reproduce
1. Create a few docker containers in a Vagrantfile using the docker provider and give them names
2. Add links to one of the containers to the other containers
3. vagrant up
### References

Not that I know of
### Workaround

You need to vagrant up the containers in a specific order in combination with 'no-parallel'.  
i.e. vagrant up 1 2 3 4 --no-parallel
This issue with this is that it's not immediately clear to another developer how to launch a stack of containers.

**Comment by kikitux** [comment]
@ascostan Vagrant is not random, it does process top to bottom

if you need volume container first, please place them before the ones that consume the volume
