### ISSUE TITLE
Timed out while waiting for the machine to boot. This means that Vagrant was unable to communicate with...

### ISSUE THREAD

**Issue by oknixus** [mitchellh/vagrant#7930]
### Vagrant version

vagrant 1.8.5
### Host operating system

macOS Sierra 10.12
### Guest operating system

![image](https://cloud.githubusercontent.com/assets/4592706/19721539/3ff15500-9ba5-11e6-9f2c-9c6fc9506b10.png)
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "smallhadroncollider/centos-6.4-lamp"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
   config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
   config.vm.synced_folder ".", "/var/www/public"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```
### Actual behavior

**Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.**
### Steps to reproduce

1.vagrant up 

![image](https://cloud.githubusercontent.com/assets/4592706/19721459/de30cbc0-9ba4-11e6-8d8b-9c9afa992c81.png)

**This problem occurs once a month, how can I to do**

**Comment by kitsunde** [comment]
This happened to me after upgrading to `macOS Sierra 10.12.1`.

**Comment by kitsunde** [comment]
There are several reports about VirtualBox and VMWare not playing nice. Like so: https://communities.vmware.com/thread/543980?start=0&tstart=0

To fix it in my case (keeping VirtualBox):

```bash
1. Delete vmware from /Applications
2. Download the virtualbox dmg, open it and run the uninstall.
3. Install virtualbox
4. Reboot
```

Back to working.

**Comment by oknixus** [comment]
@kitsunde Thanks a lot. I have done and I will verify it for a while.😊

**Comment by oknixus** [comment]
sorry，it still dose not work

**Comment by chrisgoddard** [comment]
@oknixus did you ever find a solution? I'm having the exact same problem. Reinstall and update of virtual box and vagrant hasn't resolved it.

**Comment by chrisgoddard** [comment]
For others: was able to resolve by reinstalling virtual box (need to fully remove and download manually - auto update doesn't do major releases). Then I did vagrant destroy and then removed the box and then redownloaded it.

Also clear all the cache files, i.e. rm -rf ~/.vagrant.d/tmp/

**Comment by chrisroberts** [comment]
This looks to be a non Vagrant specific problem. If there is an issue with Vagrant that is contributing to this behavior, please feel free to reopen this issue or create a new issue. Thanks!

**Comment by oknixus** [comment]
I had given up vagrant.

**Comment by MartinGacheru** [comment]
Hey guys I had the same problem using virtualbox 5.0.26 when I updated to 5.1.4 it worked! am using vagrant version 1.9.1 gud luck

> oknixus

**Comment by cbcye** [comment]
I also use OSX 5.1.4 and vagrant 1.9.1 but still have this problem.

**Comment by MartinGacheru** [comment]
reinstall and try again... the more you do it the more the chances of getting it right
