### ISSUE TITLE
Uninstalling vmware makes causes vagrant to error on destroy and up.

### ISSUE THREAD

**Issue by kitsunde** [mitchellh/vagrant#7933]
I had to uninstall vmware because it was conflicting with VirtualBox. When I did so I ended up in an unrecoverable state (using only vagrant) and had to delete the `.vagrant` folder.
### Vagrant version

1.8.6
### Host operating system

macOS Sierra
### Expected behavior

A better error message instructing me to remove .vagrant on `vagrant destroy`. `vagrant destroy -f` could maybe do it.
### Actual behavior

What actually happened?

It complains the provider doesn't exist.
### Steps to reproduce
1. Provision a vmware VM.
2. Uninstall vmware.
3. run `vagrant destroy -f`

Example:

``` bash
$ vagrant up --provider virtualbox
The provider 'vmware_fusion' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
$ vagrant destroy -f
The provider 'vmware_fusion' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
```

**Comment by chrisroberts** [comment]
This is the expected behavior from Vagrant. Vagrant expects to halt the VM and remove it. To do that, it needs to have access to the configured provider. Cheers!
