### ISSUE TITLE
Installation of docker causes network failure after reboot

### ISSUE THREAD

**Issue by chingc** [mitchellh/vagrant#7935]
Hi, I'm experiencing a network connection issue when I have docker installed in the guest.  The problem is that I lost my network connection if I were to shutdown or reboot the guest.

I'm using Vagrant 1.8.6 on OS X 10.11.6 (El Capitan).

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network"
  config.vm.provision "docker"

end
```

### Steps to Reproduce
1. `vagrant up --provider=virtualbox` (when asked about the bridged network I choose the first option, for me it's `en0: Wi-Fi (AirPort)`
2. `vagrant ssh`
3. `ping google.com` (pings are successful)
4. Cancel ping and exit out of the VM
5. `vagrant halt`
6. `vagrant up` (when asked about the bridged network I choose the same option as before)
7. `vagrant ssh`
8. `ping google.com` (pings fail with `connect: Network is unreachable`)

### Expected
Ping should be successful both times.

### Debug output
1. [vagrant up (initial)](https://gist.github.com/chingc/e7fb0f80568763f24e8562ff58a58180)
2. [vagrant halt](https://gist.github.com/chingc/d0c4986ceb838b5c8f3fa9b31984770f)
3. [vagrant up](https://gist.github.com/chingc/466a080deb7c43e82fff5bbb9883bbc2)

### Notes
I've tried this using the latest debian/jessie64 as the base box and get similar results.

The issue seems to have something to do with the `public_network` setting since commenting out that line gives the expected results, but I need this machine to be using a bridged adapter.

**Comment by sgehrig** [comment]
Seems to be related to #7858, #7458 and/or #7876 and should be fixed with PR #7866.

**Comment by chingc** [comment]
Thanks for the update!  Looking forward to `1.8.7`.  I'll close the ticket.

**Comment by chingc** [comment]
Just tried `v1.8.7` and I can no longer reproduce this issue. 👍 👍
