### ISSUE TITLE
VMware Fusion + IPv6 = uninitialized constant Vagrant::Errors::VMNetNoIPV6 (NameError)

### ISSUE THREAD

**Issue by lost-theory** [mitchellh/vagrant#7936]
### Vagrant version

Vagrant 1.8.6
### Host operating system
- Mac OS X 10.11.6
- VMware Fusion 8.1.1
### Guest operating system

Any
### Vagrantfile

``` ruby
Vagrant.configure('2') do |config|
  config.vm.define "precise64-ipv6" do |cfg|
    cfg.vm.box = "hashicorp/precise64"
    cfg.vm.network "private_network", ip: "fd00::1"
  end
end
```
### Debug output

https://gist.github.com/lost-theory/0cfe3d36a10e7181fce319120cd6cac2
### Expected behavior

Either IPv6 should work or it should give an error message explaining the problem. I'm guessing the NameError is covering up the real error message that IPv6 is not supported? #7058.
### Actual behavior

Uncaught exception that I can't debug / google for because the code is closed source:

```
~/.vagrant.d/gems/gems/vagrant-vmware-fusion-4.0.14/lib/vagrant-vmware-fusion/action_farm.rb:774:in `hostonly_config': uninitialized constant Vagrant::Errors::VMNetNoIPV6 (NameError)
```
### Steps to reproduce
1. Use VMware Fusion.
2. Specify an IPv6 IP address in the Vagrantfile.
3. `vagrant up` throws an uncaught exception after "Verifying vmnet devices are healthy..." is logged.

**Comment by lost-theory** [comment]
Hmm.. I didn't add those labels. I can't change them either, but "provider/virtualbox" should be "provider/vmware".

**Comment by chrisroberts** [comment]
@lost-theory GH was mis-assigning who was adding labels earlier today. :smiley: Thanks for the heads up!
