### ISSUE TITLE
vboxfs: no such device

### ISSUE THREAD

**Issue by gmisura** [mitchellh/vagrant#7937]
### Vagrant version

Vagrant 1.8.6
### Host operating system

Windows 7
### Guest operating system

CentOS
Linux delmonte.vagrant 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.synced_folder "..", "/vagrant"
  config.vm.provision "shell", inline: "sudo yum update -y"
end
```
### Debug output

N/A
### Expected behavior

/vagrant should be mounted on the guest
### Actual behavior

mount.vboxfs: no such device
### Steps to reproduce
1. vagrant up (mounts fine the first time because the yum update hasn't run yet)
2. vagrant reload (/vagrant fails to mount)

This issue is resolved, but I wanted to share my findings/resolution.

Turned out the yum update was causing a problem (not entirely sure of the details as I was focused on the resolution). Adding 

``` ruby
config.vm.provision "shell", inline: "sudo yum install -y kernel-headers kernel-devel"
config.vm.provision "shell", inline: "sudo yum groupinstall -y 'Development Tools'"
```

before the 'yum update' added the gcc and other pieces necessary for a newer version of vboxfs to be built during provisioning.

Hopefully that saves someone some time.

**Comment by chrisroberts** [comment]
Closing this as it has been resolved. Cheers!
