### ISSUE TITLE
centos7 vagrant up not working - rsync not found - v1.8.6

### ISSUE THREAD

**Issue by ponarunkumar** [mitchellh/vagrant#7941]
### Vagrant version

Vagrant 1.8.6
### Host operating system

Windows 10
### Guest operating system

centos/7
### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end

```

### Debug output
https://gist.github.com/ponarunkumar/5b1361146626fb6fe835b2895f8f27c2 

### Expected behavior
vagrant to run the virtual machine successfully

### Actual behavior
vagrant did not run the virtual machine as vagrant up failed.

### Steps to reproduce
1. vagrant init
2.  vagrant file

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end

3. vagrant up

**Comment by chrisroberts** [comment]
Hi! The log you provided was just the error output from `vagrant up` not understanding the request. The `--debug` option just turns on debug output. It does not accept an argument to write a log file. You can have the output written to a log file using redirection. Can you please re-run and provide a gist of the failed `vagrant up`. Thanks!
