### ISSUE TITLE
Ubuntu 16.04 LTS box built with VMware 8.5 stuck at 'Waiting for machine to boot'

### ISSUE THREAD

**Issue by geerlingguy** [mitchellh/vagrant#7942]
### Vagrant version

`1.8.6` (using `vagrant-vmware-fusion (4.0.14)`)
### Host operating system

macOS Sierra 10.12.1
### Guest operating system

Ubuntu 16.04.1 LTS (running in VMware Fusion 8.5)

(Packer build here: https://github.com/geerlingguy/packer-ubuntu-1604)
### Vagrantfile

See: https://github.com/geerlingguy/packer-ubuntu-1604/blob/master/Vagrantfile
### Debug output

https://gist.github.com/geerlingguy/a30efed09f982a0c5bc755bbb1b75eae
### Expected behavior

The VM boots, and Vagrant connects and runs configured provisioner(s).
### Actual behavior

The VM boots, and Vagrant gets stuck on `Waiting for machine to boot. This may take a few minutes...`.

**Two important notes**:
1. If I either set `v.gui = true` in the config, or open VMware Fusion while Vagrant is waiting (e.g. double-click on it in Applications folder), then all the sudden Vagrant connects and continues through to provisioning.
2. Things _seemed_ to work fine with VMware Fusion 8.0 and 8.1... but might've broken with 8.5. This points slightly towards the possibility of the vmware plugin being at fault. But maybe not.
### Steps to reproduce
1. Build the minimal Ubuntu 16.04 LTS packer box in https://github.com/geerlingguy/packer-ubuntu-1604 following it's instructions.
2. Run `vagrant up vmware --provider=vmware-fusion
3. Wait...
### References
- https://github.com/geerlingguy/packer-ubuntu-1604/issues/13

**Comment by geerlingguy** [comment]
Note that changing the box to `vmware.vm.box = "geerlingguy/ubuntu1604"` (in the Vagrantfile), which tests with the last published/stable version of the box (which was built with Fusion 8.1 under 10.11) allows everything to work normally, without needing to open VMware Fusion or set `v.gui = true`.

**Comment by geerlingguy** [comment]
I've also built Ubuntu 12.04 and 14.04 base boxes with almost identical configurations in the past day and they seem to work fine.

**Comment by chrisroberts** [comment]
@geerlingguy Just to make sure I understand, are you seeing the issue only with ubuntu-16.04? Based on your last comment, it seems that new boxes of ubuntu-12.04 and ubuntu-14.04 are working as expected. Just want to confirm that is the case. Thanks!

**Comment by geerlingguy** [comment]
@chrisbaldauf - Based on earlier testing, I didn't have this issue (on my personal Mac). Today I booted things up on my work mac and am hitting the same problem on Ubuntu 14.04 with my latest public box build (1.1.4) - https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1404

Versions:

  - Vagrant 1.8.6
  - VMware Fusion 8.5.1
  - Plugin: `vagrant-vmware-fusion (4.0.14)`

**Comment by geerlingguy** [comment]
On my personal Mac, I had `vagrant-vmware-fusion (4.0.9)` installed (not 4.0.14 like I do on my work Mac). And 12.04/14.04 work fine. On my work Mac (with 4.0.14), none of the boxes work.

But 16.04 never boots without the GUI option or opening VMware in either case.

**Comment by geerlingguy** [comment]
So, further testing—I updated personal Mac to plugin 4.0.14, and that works fine still.

So then I noticed that I'm running VMware Fusion 8.5.0 on my personal Mac (works with any Ubuntu box but 16.04), but on my work laptop I have 8.5.1 (all Ubuntu versions are failing).

So it looks like it's definitely not the VMware Fusion Vagrant plugin version, but there are two bugs of some sort or another:

  - VMware Fusion 8.5.1 doesn't work with any of the Ubuntu base boxes.
  - VMware Fusion 8.5.0 works fine with my 12.04 and 14.04 base boxes, but not 16.04 (original issue).

**Comment by geerlingguy** [comment]
Ah, looks like the 8.5.1 issue is here: https://github.com/mitchellh/vagrant/issues/7948

The original issue still stands—with 8.5.0, only the Ubuntu 16.04 box won't connect. Let me know if you want me to build it and host a copy so you can download (to save the ~30 min setup and build time if you want to use the Packer config).

**Comment by chrisroberts** [comment]
Awesome, thanks for the updates! Don't worry about hosting the box, I'll just build it locally (but thanks!).

**Comment by zaiddabaeen** [comment]
Any updates on this? Did anybody get it to work for Ubuntu 16.04?

**Comment by zaiddabaeen** [comment]
Turns out it works with this packer script: https://github.com/cbednarski/packer-ubuntu

**Comment by geerlingguy** [comment]
I'm washing my hands of VMware for now. VirtualBox is about 90% as fast for what I need, and is surprisingly a lot more stable of late. The 10% performance gain is not worth the crazy amount of effort that has been required to get my boxes all working on VMware (not to mention the fact that I've probably spent 50-100 hours extra time working on a box for a plugin that costs money for software that costs even more money!).

I'd rather save 1/3 of my personal OSS donation budget for something that doesn't frustrate me and also doesn't benefit only free projects :)

**Comment by zaiddabaeen** [comment]
Washing my hands too!

**Comment by chrisroberts** [comment]
Hi there! I believe the underlying issue has to do with what is described in this issue: #8095. I've updated the vmware plugin to start warning about the pcislotnumber and will be transitioning it to _not_ make modifications in the future. Apologies for the frustration around this and please let me know if you are still encountering issues. Cheers!
