### ISSUE TITLE
Unable to run any version of vagrant past version 1.7.2. Tried upgrading several versions but always get same error.

### ISSUE THREAD

**Issue by ismael-rivera** [mitchellh/vagrant#7945]
Like the title of the post says; Every time I try to upgrade I get the same following update. True, my OS is severely old, but I would still like to be able to use vagrant for that very reason. If I can use the latest version, even better, but so far it seems I can't get past this error. 

See Below for GIST
### Vagrant version

Been trying to upgrade: 
~1.7.2 - seems to work fine but I could use an upgrade
Anything above and I get errors and am unable to run.
### Host operating system

OS X 10.6.8 Snow Leopard (Yes, I know it is ancient. No, I cannot upgrade)
### Guest operating system

Ubuntu Server 14.04. Not that it matters because I cannot seem to even be able to vagrant up my machine.
### Vagrantfile

``` ruby
# Copy-paste your Vagrantfile here

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 4567
  config.vm.network :private_network, ip: "192.168.68.8"

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.
### Debug output

https://gist.github.com/ismael-rivera/6ef8c7c863daa58d7c7844c8bc80ca11
### Expected behavior

What should have happened?
Hopefully, vagrant should have run without any hitch.
### Actual behavior

What actually happened?
It did not.
### Steps to reproduce
1. Install any version of Vagrant above 1.7.2
2. Try running it
3. Uninstall. Repeat .
### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- no, this is my first time with this issue.

**Comment by deancsmith** [comment]
This Gist looks like Vagrant 1.8.0 @ismael-rivera? Do you get exactly the same error with 1.8.6?

Also what version of Ruby do you have on your path? We noticed some strange issues - albeit on a later version of OS X - that went away when we upgraded from Ruby 2.0 to 2.3.1, despite the fact that Vagrant ships with it's own version of Ruby (this my have been a Chef issue).

**Comment by ismael-rivera** [comment]
Yes I got the same exact error with vagrant 1.8.6. My ruby version is ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin10.8.0].

**Comment by chrisroberts** [comment]
Hi! Vagrant packages for OS X are currently built on 10.9 and previous versions of OS X are not supported. If you need to run Vagrant on earlier versions of OS X you may be able to do so by installing Ruby locally and using bundler. Cheers!
