### ISSUE TITLE
vagrant rdp

### ISSUE THREAD

**Issue by Jamesking56** [mitchellh/vagrant#7952]
Hello,

Just a documentation question really. There isn't much documentation surrounding `vagrant rdp`.

Is there any way to specify the RDP login in the `Vagrantfile` and is there any way to set resolution?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
