### ISSUE TITLE
Using file provioner with windows host fails on big files

### ISSUE THREAD

**Issue by StefanSchoof** [mitchellh/vagrant#7953]
### Vagrant version
1.8.6

### Host operating system
windows 10 (1511)

### Guest operating system
windows 2016

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# linked clone feature requires 1.8
Vagrant.require_version ">= 1.8" 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "mwrock/Windows2016"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

  config.vm.provision "file", source: "14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO", destination: "C:\14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO"
end
```

### Debug output
https://gist.github.com/StefanSchoof/9dc34ecb613e51e9e22383c1247a7736

### Expected behavior
The big file (4,95 GB) should be uploaded or a message which is the maximal allowed file size for the file Provisioner.

### Actual behavior
A WMI Error:
```
The WS-Management service cannot 
process the request. This user is allowed a maximum number of 1500 concurrent operations, which has been exceeded. 
Close existing operations for this user, or raise the quota for this user.
```

### Steps to reproduce
1. Download win2016 eval iso http://care.dlservice.microsoft.com/dl/download/1/6/F/16FA20E6-4662-482A-920B-1A45CF5AAE3C/14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO
2. place iso next to vagrant file
3. `vagrant up`

**Comment by chrisroberts** [comment]
Fixed via #8102
