### ISSUE TITLE
Early Vagrant initialisation sorts box versions incorrectly.

### ISSUE THREAD

**Issue by phyber** [mitchellh/vagrant#7955]
### Vagrant version
`Vagrant 1.8.6`

### Host operating system
OS X Sierra

### Guest operating system
N/A

### Vagrantfile
N/A

### Expected behavior
Vagrant should choose the latest box version when performing `vagrant up`.

### Actual behavior
Vagrant incorrectly chooses an older version.

### Steps to reproduce
1. Have various versions of the same box available.
  - I got this behaviour by having `0.2.41` (old) and `0.2.114` (new) available.
2. Execute `vagrant up`.
3. Vagrant has now chosen to use the old `0.2.41` box instead of the newer `0.2.114` box.

I can reproduce this issue, know where the issue is occurring and will have a PR to fix the issue shortly.

**Comment by phyber** [comment]
To add to the above for anyone just reading the issue and not looking at the linked PR, this occurs because Vagrant was using string comparisons in the `#find` of `box_collection.rb`. Changing this to use `Gem::Version` comparisons corrects the issue.

Is anyone able to review this for merge? We're having to maintain a locally patched Vagrant because of this.

**Comment by sftim** [comment]
#7956 very much looks like it will fix this.

**Comment by MrPrimate** [comment]
This issue is also affecting my ability to use `vagrant up` as expected

**Comment by omahn** [comment]
I've just replicated the issue here after upgrading to the latest Vagrant 1.9.2. After a successful `vagrant box update`:

```==> server: Successfully added box 'example/centos6-testing' (v1.0.142) for 'virtualbox'!```

And then a `vagrant up`, vagrant continues to use the old version:

```==> server: Checking if box 'example/centos6-testing' is up to date...
==> server: A newer version of the box 'example/centos6-testing' is available! You currently
==> server: have version '1.0.94'. The latest is version '1.0.142'. Run
==> server: `vagrant box update` to update.```

**Comment by mbevc1** [comment]
This also affects `vagrant box update` since it's always trying to update and fails if box already exists: 
```
scalefactory/ubuntu12-testing (virtualbox, 1.0.142)
scalefactory/ubuntu12-testing (virtualbox, 1.0.82)

$ vagrant box update
==> client: Checking for updates to 'scalefactory/ubuntu12-testing'
    client: Latest installed version: 1.0.82
    client: Version constraints: > 1.0.0
    client: Provider: virtualbox
==> client: Updating 'scalefactory/ubuntu12-testing' with provider 'virtualbox' from version
==> client: '1.0.82' to '1.0.142'...
==> client: Loading metadata for box 'https://atlas.hashicorp.com/scalefactory/ubuntu12-testing'
==> client: Adding box 'scalefactory/ubuntu12-testing' (v1.0.142) for provider: virtualbox
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.

Name: scalefactory/ubuntu12-testing
Provider: virtualbox
Version: 1.0.142
```

**Comment by chrisroberts** [comment]
Closing as dup of #7582. Thanks!
