### ISSUE TITLE
Using a tilde in Vagrantfile is not expanded on Windows

### ISSUE THREAD

**Issue by nitrocode** [mitchellh/vagrant#7959]
### Vagrant version
1.8.6

### Host operating system
Windows 10

### Guest operating system
CentOS 6

### Vagrantfile
```ruby
  # reuse host keys
  config.ssh.private_key_path = ['~/.ssh/id_rsa', '~/.vagrant.d/insecure_private_key']
  config.ssh.forward_agent = true
```

### Expected behavior
Replace the tilda with the current user's home directory so the Vagrantfile is cross compatible with POSIX and Windows

### Actual behavior
Cannot find the insecure_private_key because the tilda does not seem to mean anything on Windows.

### Steps to reproduce
1. Use the Vagrantfile excerpt above
2. Vagrant up

### References
None

**Comment by nitrocode** [comment]
Workaround:

```ruby
  key_private = File.join(ENV['HOME'], ".ssh", "id_rsa")
  key_personal = File.join(ENV['HOME'], ".vagrant.d", "insecure_private_key")

  # check for windows
  if RbConfig::CONFIG['host_os'] =~ /mswin|mingw|cygwin/
    puts "yes"
    key_private.gsub! "/", "\\"
    key_personal.gsub! "/", "\\"
    puts key_private
    puts key_personal
  end
```

From CMD the above works but from Cygwin, it does not.

Cygwin output:

```
$ vagrant up
C:\tools\cygwin\home\user\.ssh\id_rsa
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

SSH:
* `private_key_path` file must exist: C:\tools\cygwin\home\user\.vagrant.d\insecure_private_key
```

**Comment by kikitux** [comment]
Tilde is converted to home directory by bash/sh and others.

Not sure the solution is to implement tilde in Vagrant as alias of home is the way to go.

**Comment by chrisroberts** [comment]
I agree with @kikitux that I don't believe Vagrant should be making these adjustments. I would be open to reviewing a PR that implements a proposed solution around this, but I don't think this should be something Vagrant handles.

Cheers!
