### ISSUE TITLE
from /Homestead/scripts/homestead.rb:109:in `block (2 levels) in configure'

### ISSUE THREAD

**Issue by hengsoheak** [mitchellh/vagrant#7962]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Host operating system
OSX EI Captitan
CPU: 2.2 GHX Intel Core I7
Dear Vagrant terms 
Please help to give me some idea about below error happen when I try to install Laravel homesteas on my Mac pro. as tows days of trying to find the best solution for get it o but finally I still meet the problem on mac pro (But in my Del computer work fine) I have try to istall more than 20 times in this computer but it still bad luck for me so what should I have to do for this errors.
Please help

![screen shot 2559-11-04 at 12 00 13 am](https://cloud.githubusercontent.com/assets/812528/19976285/b270d380-a221-11e6-97f7-993ae356f453.png)

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output

/Homestead/sudo scripts/homestead.rb:109:in `read': No such file or directory @ rb_sysopen - /var/root/.ssh/id_rsa (Errno::ENOENT)
	from /Homestead/scripts/homestead.rb:109:in `block (2 levels) in configure'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/kernel_v2/config/vm_provisioner.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/kernel_v2/config/vm_provisioner.rb:72:in `add_config'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/plugins/kernel_v2/config/vm.rb:324:in `provision'
	from /Homestead/scripts/homestead.rb:106:in `block in configure'
	from /Homestead/scripts/homestead.rb:105:in `each'
	from /Homestead/scripts/homestead.rb:105:in `configure'
	from /Homestead/Vagrantfile:30:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/loader.rb:107:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/loader.rb:107:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/loader.rb:104:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/config/loader.rb:104:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:746:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:746:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:492:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:479:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/lib/vagrant/environment.rb:728:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:177:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.6/bin/vagrant:177:in `<main>'
SOPHEAKs-MacBook-Pro:Homestead root#

**Comment by chrisroberts** [comment]
Hi. This looks to be a configuration problem with homestead. It is looking for an ssh key that does not exist. If you are unsure how to change that setting, refer to the homestead repository for questions or help. Thanks!
