### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication...

### ISSUE THREAD

**Issue by Saoirse1916** [mitchellh/vagrant#7963]
I started receiving this error message suddenly on my formerly functional VMs.  Nothing I tried would get the VMs to boot properly so I tried recreating them from scratch to no avail.  I then paid to upgrade both VMWare Fusion and the vagrant-vmware plugin and the errors persist.

### Vagrant version
1.8.6

### Host operating system
MacOS Sierra

### Guest operating system
CentOS 6.5

### Vagrantfile
```ruby
# -*- mode: ruby -*-

dir = File.dirname(File.expand_path(__FILE__))

require 'yaml'
require "#{dir}/puphpet/ruby/deep_merge.rb"
require "#{dir}/puphpet/ruby/to_bool.rb"
require "#{dir}/puphpet/ruby/puppet.rb"

configValues = YAML.load_file("#{dir}/puphpet/config.yaml")

provider = ENV['VAGRANT_DEFAULT_PROVIDER'] ? ENV['VAGRANT_DEFAULT_PROVIDER'] : 'local'
if File.file?("#{dir}/puphpet/config-#{provider}.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-#{provider}.yaml")
  configValues.deep_merge!(custom)
end

if File.file?("#{dir}/puphpet/config-custom.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-custom.yaml")
  configValues.deep_merge!(custom)
end

data = configValues['vagrantfile']

Vagrant.require_version '>= 1.8.1'

Vagrant.configure('2') do |config|
  eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}")
end

```

### Debug output
https://gist.github.com/Saoirse1916/053ff99725a567550140b20b384a5b82

### Expected behavior
The machine should boot.

### Actual behavior
I get the following error:
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

If I try to SSH I get this error:
The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.

### Steps to reproduce
1. Create a new VM
2. Run vagrant up
3. Run sudo vagrant up because vagrant up just quits working after a few dozen lines

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:

https://github.com/puphpet/puphpet/issues/2503
https://github.com/puphpet/puphpet/issues/2501

**Comment by chrisroberts** [comment]
From the debug output it looks like the vmware tools are not installed within the guest box. Can you reduce your Vagrantfile down to a simple implementation that just defines the box name, running a `vagrant up --debug` with it, and posting a gist of the new Vagrantfile and the debug output? Thanks!

**Comment by Saoirse1916** [comment]
Sure, how do I do that? I always use puphpet to create boxes like this.

**Comment by chrisroberts** [comment]
@Saoirse1916 Can you confirm if you are still experiencing this issue? If so, can you please provide a gist of the debug output. To do that, run:

```
$ vagrant up --debug
```

Copy the output and paste it into a gist here: https://gist.github.com and then provide the link here. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
