### ISSUE TITLE
Vagrant 1.8.6 with `private_network` duplicates eth0 instead of adding eth1 for WPLib Box

### ISSUE THREAD

**Issue by mikeschinkel** [mitchellh/vagrant#7964]
Vagrant 1.8.6 with `private_network` duplicates `eth0` instead of adding `eth1`  in `/etc/network/interfaces` for [WPLib Box](https://github.com/wplib/wplib-box/blob/master/Vagrantfile).  Vagrant `1.8.5` worked correctly.

### Vagrant version
`1.8.6`

### Host operating system
Mac OS X `10.11.6` - El Capitan

### Guest operating system
Ubuntu `14.04` LTS

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

    config.vm.box = "wplib/wplib"
    config.vm.hostname = "wplib.box"
    config.vm.network 'private_network', ip: "10.10.10.10"
    config.vm.synced_folder "www", "/var/www"
    config.ssh.forward_agent = true
    config.ssh.insert_key = false

end
```
See also: [Full Vagrantfile for WPLib Box](https://github.com/wplib/wplib-box/blob/master/Vagrantfile).

**NOTE:** I am the project lead for WPLib Box, and we started having reports of problems from our users once they started installing Vagrant `1.8.6`.

### Debug output
https://gist.github.com/mikeschinkel/5bffbf886f32a32f9a8c9ee7dae21ef1

### Expected behavior

The `/etc/network/interfaces` file should be written like this _(look for `auto eth1`):_

	# This file describes the network interfaces available on your system
	# and how to activate them. For more information, see interfaces(5).

	# The loopback network interface
	auto lo
	iface lo inet loopback

	# The primary network interface
	auto eth0
	iface eth0 inet dhcp
	pre-up sleep 2
	#VAGRANT-BEGIN
	# The contents below are automatically generated by Vagrant. Do not modify.
	auto eth1
	iface eth1 inet static
	      address 10.10.10.10
	      netmask 255.255.255.0
	#VAGRANT-END

### Actual behavior
The `/etc/network/interfaces` file is written like this _(look for `auto eth0` being duplicated):_

	# This file describes the network interfaces available on your system
	# and how to activate them. For more information, see interfaces(5).

	# The loopback network interface
	auto lo
	iface lo inet loopback

	# The primary network interface
	auto eth0
	iface eth0 inet dhcp
	pre-up sleep 2
	#VAGRANT-BEGIN
	# The contents below are automatically generated by Vagrant. Do not modify.
	auto eth0
	iface eth0 inet static
	      address 10.10.10.10
	      netmask 255.255.255.0
	#VAGRANT-END

### Steps to reproduce
1. Install Vagrant `1.8.6` 
2. `git clone git@github.com:wplib/wplib-box.git` 
3. `cd wplib-box`
4. `vagrant up`

### References
- [#7960](https://github.com/mitchellh/vagrant/issues/7960) _(maybe?)_

**Comment by jbisnardon** [comment]
I have the same behavior, eth0 is duplicated instead of adding eth1.
I also confirm that with the 1.8.5 version it works correctly. 

## Vagrant version

1.8.6

## Host operating system

Mac OS X 10.11.6 - El Capitan

## Guest operating system

Ubuntu 15.10

As a work-around, I had to modify <code>/etc/network/interface/</code> to insert eth1 manually before the \#VAGRANT-BEGIN statement. 
This way, when I reload the vagrant, eth1 is configured and works.

```
# The primary network interface
auto eth0
iface eth0 inet dhcp
pre-up sleep 2
# Work-around here: 
auto eth1
iface eth1 inet static
      address 10.10.10.10
      netmask 255.255.255.0
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth0
iface eth0 inet static
      address 10.10.10.10
      netmask 255.255.255.0
#VAGRANT-END
```

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
