### ISSUE TITLE
An error occurred in the underlying SSH library that Vagrant uses.

### ISSUE THREAD

**Issue by neilgee** [mitchellh/vagrant#7965]
#Vagrant 1.8.6
Mac OSX 10.11.6
VB - 5.1.8
Guest box - ubuntu/trusty64 (up to date)

Vagrantfile - https://gist.github.com/neilgee/3be45289c845133a321f5a7087281da0#file-vagrant-file-txt

This error just started happening for me, to my knowledge nothing changed in my local environment and I updated Vagrant & VB to latest to see if it would fix the issue (it didn't).

The error on `vagrant up`

```
==> default: Running provisioner: shell...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
```

The error on `vagrant halt` is also ssh related
```
neilg@[~/vdev]:(develop) vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c vagrant_halt"...
==> default: ssh_exchange_identification: Connection closed by remote host
==> default: Command execution finished.
The local command "vagrant ssh -c 'vagrant_halt'" returned a failed exit
code or an exception. The error output is shown below:

ssh_exchange_identification: Connection closed by remote host
```

And trying `vagrant ssh`
```
neilg@[~/vdev]:(develop) vagrant ssh
ssh_exchange_identification: Connection closed by remote host
```

Debug log - https://gist.github.com/neilgee/3be45289c845133a321f5a7087281da0#file-vagrant-debug-txt

SSH Config - https://gist.github.com/neilgee/3be45289c845133a321f5a7087281da0#file-ssh-config-txt

### References
#6812 #452 #301

I tried uninstalling and installing `vagrant-vbguest` which had been suggested - but didn't work for me.

**Comment by chrisroberts** [comment]
@neilgee Are you still experiencing this issue?

**Comment by neilgee** [comment]
Never resolved it, lost the MySQL db's, had to recreate new local environment.

**Comment by chrisroberts** [comment]
This isn't something I'm able to reproduce locally and seems like an issue within the VM itself. If it does happen again and can be easily reproduced, please reopen this issue or create a new one. Thanks!

**Comment by jtsternberg** [comment]
Having the same issue here. Have looked for solutions all over the place including #6812, https://github.com/net-ssh/net-ssh/issues/301, https://tomjn.com/2016/08/03/vagrant-provision-timeouts/, https://github.com/mitchellh/vagrant/issues/7306, https://github.com/geerlingguy/drupal-vm/issues/509, https://github.com/Varying-Vagrant-Vagrants/VVV/issues/375, https://github.com/mitchellh/vagrant/issues/6854, https://github.com/vagrant-libvirt/vagrant-libvirt/issues/452, https://github.com/vagrant-libvirt/vagrant-libvirt/issues/452. I'm at a complete loss, and I not ready to risk losing all my dev sites/DBs by wiping/reinstalling. Would love any/all input/help.

**Comment by michaelHeimes** [comment]
I was prompted to update SHH and now I'm getting these same errors. I'm new to Vagrant and have already wasted days trying it get it to work. SSH was getting closed during pushes so I thought up[dating could help. Not it's worse.

**Comment by jtsternberg** [comment]
@loreleiaurora walked me through getting my data backed up, wiping out the machine and reinstalling it. It turns out https://github.com/Varying-Vagrant-Vagrants keeps backups of the DB data on the host system, so I could just destroy it and reinstall it. If i'm wrong, I'm sure @loreleiaurora will correct any of the wrong statements I've made. :)

**Comment by neilgee** [comment]
Do you mean the dbs in _VVV/database/backups/*sql_

These are done via triggers and I find not always the latest especially if your VVV has been running for a while.

Would be great to get a mini documentation on how the issue was resolved.

**Comment by jtsternberg** [comment]
@neilgee no, I mean the `VVV/database/data/` files. Basically, we copied that directory out, then destroyed it all, re-upped, then put that data files back and re-provisioned. That's the super basic version.

**Comment by neilgee** [comment]
@jsternberg ok thanks will try that if it happens again, btw  I only have a text file in ```VVV/database/data/```

**Comment by jtsternberg** [comment]
@neilgee I think the key is this bit in the `Vagrantfile`:

![](http://b.ustin.co/CaKj+)

**Comment by neilgee** [comment]
@jtsternberg  Ok cool I see - will give it a spin on a test environment - was pulling my hair out when this happened to me and having to start again was a royal pain.

**Comment by jtsternberg** [comment]
@neilgee I'm surprised I have any hair left after the last couple days. But more importantly, I have my data ha ha.

**Comment by kirylpl** [comment]
Maybe someone found a solution?
VB 5.1
Vagrant 1.9.2

**Comment by numediaweb** [comment]
what worked for me was:
```
vagrant halt
vagrant up --provision
```

**Comment by YegorPo** [comment]
Hello

**Comment by good3n** [comment]
If you're not able to use `vagrant halt` you can power down the box itself via VirtualBox, then run `vagrant up --provision`

**Comment by defaultcontrarian** [comment]
I’ve been experiencing the following issues for the past few days.

Here a rundown of my set up and the issues.

Operating System:

macOS High Sierra Version 10.13.6

Current Virtual Machine Setup:

VirtualBox Version 5.2.18 (running Ubuntu 16.04.3)
VirtualBox Networking Settings
NAT with port forwarding: SSH, Host Port: 2020, Guest Port: 22
Vagrant 2.1.2 (latest version)

The Issues:

Issue #1: When I run ‘vagrant up’ I get the following error:

Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

Issue #2: When I run ‘vagrant provision’ I get the following error message:

An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating

I’ve tried the above and have reviewed the following but have not been able to resolve the issue(s).

https://github.com/hashicorp/vagrant/issues/5732

Thanks in advance.

**Comment by markhowellsmead** [comment]
This happened to me after I updated the machine via command line when I was in the SSH environment (`vagrant ssh`). Powering down the box off using Virtualbox, then using `vagrant box update` and then using `vagrant up --provision` didn't help. Hoping that I won't have to start afresh...

**Comment by h3ct0rjs** [comment]
@markhowellsmead  it happens to me today, When I was trying to create a cluster, After trying several couple of things that didn't solve  the situation I just destroy the las worker and then just run 
` vagrant up --provision` and it did work, so I guess you could try something similar.

**Comment by KingSila** [comment]
getting same issue
    master: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by mrtariqkhan** [comment]
Seems its connected to the memory? I increased the memory of homestead box in the homestead.yaml
**This works**: 
memory: 5048
cpus: 2

**This doesn't**:
#memory: 1700
#cpus: 1

I have some heavy services like rabbit mq / elastic search running on my machine.

**Comment by hassanwahsiss** [comment]
> Seems its connected to the memory? I increased the memory of homestead box in the homestead.yaml
> **This works**:
> memory: 5048
> cpus: 2
> 
> **This doesn't**:
> #memory: 1700
> #cpus: 1
> 
> I have some heavy services like rabbit mq / elastic search running on my machine.

Thanks a lot, you saved my week :D it worked for me

**Comment by xacaxulu** [comment]
+1

**Comment by Roman9961** [comment]
just enable virtualizatio technoplogy in cpu settings in BIOS solve the problem
