### ISSUE TITLE
Vagrant download page shows still version 1.8.6

### ISSUE THREAD

**Issue by tuxinaut** [mitchellh/vagrant#7966]
Download page shows still `Vagrant` version `1.8.6` (9cb7b7503af1fe66ba6bedf3d0f92a6a4f575c84)

See: 
- https://www.vagrantup.com/downloads.html

Expected behaviour:

See `Vagrant` download for version `1.8.7`

**Comment by johnjelinek** [comment]
No worries, `brew` already gets `1.8.7`.

**Comment by chrisroberts** [comment]
Downloads page shows correct version. Thanks!
