### ISSUE TITLE
winrm: provisioning executes the first .ps1 (or .cmd) script for the subsequent ones instead

### ISSUE THREAD

**Issue by dusek** [mitchellh/vagrant#7971]
### Vagrant version
Vagrant 1.8.7

### Host operating system
macOS 10.12.1 (16B2555)

### Guest operating system
Windows 7 Pro x32 Czech FPP

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "2048"

    # Add sound card (for synthesized speech)
    vb.customize ["modifyvm", :id, '--audio', 'coreaudio', '--audiocontroller', 'hda']

    # Clipboard sync (copying text is often needed)
    vb.customize ["modifyvm", :id, '--clipboard', 'bidirectional']
  end

  config.vm.define "linux", autostart: false do |linux|
    ...
  end

  config.vm.define "win" do |win|
    win.vm.box = ENV['VAGRANT_BOX_WIN'] || "someusername/win7x86-pro-cz"
    win.vm.boot_timeout = 15*60 # user interaction is required on first boot

    # set up provisioning prerequisities
    win.vm.provision "shell", path: "vagrant/fixnetwork.ps1" # strangely, network gets randomly set to Public on first box boot
    win.vm.provision "file", source: "vagrant/provutils.psm1", destination: "Documents/WindowsPowerShell/Modules/provutils/provutils.psm1"
    win.vm.provision "shell", path: "vagrant/sharedfolder.cmd"

    # now for the real work:
    win.vm.provision "shell", path: "vagrant/desktop.ps1"

    win.vm.provision "shell", path: "vagrant/bash.ps1"

    win.vm.provision "shell", path: "vagrant/choco.ps1"

    win.vm.provision "shell", path: "vagrant/java.ps1"

    win.vm.provision :reload
  end
end
```

### Debug output
https://gist.github.com/dusek/42617c076a582b2a4fed2c26e11a954f

### Expected behavior
These scripts should run in sequence:
- `fixnetwork.ps1`
- `sharedfolder.cmd`
- `desktop.ps1`
- `bash.ps1`
- `choco.ps1`
- `java.ps1`

### Actual behavior
What actually happened?
Based both on the linked "Debug output" and on the effect inside the VM afterwards, these scripts were run:
- `fixnetwork.ps1`
- `sharedfolder.cmd`
- `fixnetwork.ps1`
- `fixnetwork.ps1`
- `fixnetwork.ps1`
- `fixnetwork.ps1`

### Steps to reproduce
1. Run `vagrant up win` with the above Vagrantfile (you won't have access to the linked box though...)

### Notes
- VirtualBox 5.1.6
- The same problem is also for .cmd files - when second provisioning .cmd shell script is specified in Vagrantfile, it instead executes the first .cmd shell script.
- based on this, it looks like vagrant succeeds at uploading `c:\tmp\vagrant-shell.ps1` or `c:\tmp\vagrant-shell.cmd` file for the first time (i.e. when there is no previous such file and it is thus created), but all subsequent attempts to upload a new `.cmd` or `.ps1` file to overwrite the previous ones fail
- I have used the same Vagrantfile previously with older vagrant and VirtualBox versions and there `vagrant up win` worked fine (since it is quite some time - a few months - I no longer know which exact vagrant and/or VirtualBox version that was); the base box is 100% unchanged since then
- please disregard some wrongly encoded output of both scripts in the "Debug output", it was present already at times when things were working fine with vagrant (see previous point)

### References
- GH-7712

**Comment by dusek** [comment]
I was able to workaround this by specifying different `upload_path` for each script:

```ruby
    win.vm.provision "shell", path: "vagrant/fixnetwork.ps1", upload_path: "C:/tmp/vagrant-shell_01.ps1" # strangely, network gets randomly set to Public on first box boot
    win.vm.provision "file", source: "vagrant/provutils.psm1", destination: "Documents/WindowsPowerShell/Modules/provutils/provutils.psm1"
    win.vm.provision "shell", path: "vagrant/sharedfolder.cmd"

    # now for the real work:
    win.vm.provision "shell", path: "vagrant/desktop.ps1", upload_path: "C:/tmp/vagrant-shell_02.ps1"

    win.vm.provision "shell", path: "vagrant/bash.ps1", upload_path: "C:/tmp/vagrant-shell_03.ps1"

    win.vm.provision "shell", path: "vagrant/choco.ps1", upload_path: "C:/tmp/vagrant-shell_04.ps1"

    win.vm.provision "shell", path: "vagrant/java.ps1", upload_path: "C:/tmp/vagrant-shell_05.ps1"
```

This workaround was mentioned in GH-7712.

**Comment by jbarnett-r7** [comment]
I think the issue you are seeing is the same one as here: GH-7614

**Comment by dusek** [comment]
Thanks @jbarnett-r7 for the info, I did not find the issue when reporting this one. I added the info from this issue to the one you linked. So closing this one as a dupe.
