### ISSUE TITLE
Vagrant does not look to manage state of the host machine well

### ISSUE THREAD

**Issue by bitliner** [mitchellh/vagrant#7977]
### Vagrant version
1.5.8

### Host operating system
Mac OS Sierra

### Guest operating system
Ubuntu 16.04

### Expected behavior
after vagrant destroy, I expect that there are no ports ( specified in the port forwarding ) that are still in LISTEN mode

### Actual behavior
some port remains in LISTEN mode, even if the virtual machine have been destroyed

**Comment by segadora** [comment]
The vagrant version you use seems to be over 2 years old. Consider upgrading to the newest version?

**Comment by bitliner** [comment]
Even after the update, does not look that Vagrant manage it well.

I am stopping to use it, too slow and too many issues when using VMWare.

Currently I am on `Vagrant 1.8.7`

**Comment by chrisroberts** [comment]
If there is a specific problem that you are encountering with Vagrant, please feel free to open a new issue. Thanks!
