### ISSUE TITLE
curl binary shipped with vagrant broken in OS X 10.12

### ISSUE THREAD

**Issue by dallinwright** [mitchellh/vagrant#7984]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

Vagrant 1.8.7

### Host operating system
This is the operating system that you run locally.

Mac OS X 10.12 Sierra

### Guest operating system
This is the operating system you run in the virtual machine.

Any and all, tried ubuntu and centos versions, and just running curl itself packed with vagrant.

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end

### Expected behavior
What should have happened?

When I do vagrant init then the boxname it would pull the box from hashicorp and vagrant up would start it, just like the tutorial.

### Actual behavior
What actually happened? 

I simply type vagrant up

OUTPUT:

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/hashicorp/precise64"]
Error:

### Steps to reproduce
1. Install vagrant on osx 10.12
2. create a dummy project with vagrant init
3. run vagrant up

Here is the output when just running curl all by itself shipped with Vagrant 1.8.X

/opt/vagrant/embedded/bin > ./curl
dyld: Library not loaded: @rpath/libcurl.4.dylib
Referenced from: /opt/vagrant/embedded/bin/./curl
Reason: Incompatible library version: curl requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
[1]    12123 abort      ./curl

This is a brand new mac I just barely got. Installed vagrant and it does not work at all.

**Comment by dallinwright** [comment]
Workaround I got to work: symlink the OS's curl as the curl binary in /opt/vagrant/embedded/bin and  vagrant resumes normal operation. Curl shipped with .dmg is not working.

**Comment by kunxi** [comment]
Seeing the same issue in El Capitan, I think the bug is platform agnostic: the embedded curl uses the embedded dynlib:

```sudo dtruss /opt/vagrant/embedded/bin/curl
... ....
stat64("/opt/vagrant/embedded/bin/../lib/libcurl.4.dylib\0", 0x7FFF5FBFDD28, 0x7FFF5FBFDEE0)		 = 0 0
open("/opt/vagrant/embedded/bin/../lib/libcurl.4.dylib\0", 0x0, 0x0)		 = 3 0
pread(0x3, "\317\372\355\376\a\0", 0x1000, 0x0)		 = 4096 0
... ...
```

Clearly the packaged libcurl is incompatible with the packaged curl.

**Comment by blunckr** [comment]
Why is this issue closed? I'm still encountering it.

**Comment by zg** [comment]
I just installed vagrant from the website and encountered this exact issue. macOS Sierra 10.12.1. I put preference to `/opt/vagrant/embedded/bin` in my PATH, but I'm still encountering the issue.

**Comment by andypearson** [comment]
Just trying to get up and running with Version 1.8.7 on a Mac running El Capitan 10.11.6 and have hit into this problem as well.

I did what @dallinwright suggested and got things working again:

`sudo ln -sf /usr/bin/curl /opt/vagrant/embedded/bin`

This ticket probably needs re-opening though, it's not a fun new user experience :(
