### ISSUE TITLE
Consider adding macOS and Windows to your CI testing

### ISSUE THREAD

**Issue by zg** [mitchellh/vagrant#7991]
I notice that the vagrant repo is only testing against Ubuntu with Travis CI. Perhaps you should consider adding in macOS testing. You can accomplish macOS testing through some modifications to the .travis.yml file: https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

It's also important that you should test against Windows. For Windows testing, you could use [Appveyor](https://www.appveyor.com/).

**Comment by bbrala** [comment]
Would agree this would be awesome, I've fooled around with using appveyor to test vagrant but there are some issues with including the right libraries. Also one of the thing id want to test is the hyper v stuff and I didn't really see a way to do that on Appveyor.

**Comment by chrisroberts** [comment]
The testing framework is in the process getting an overhaul. Thanks for the suggestions!
