### ISSUE TITLE
Vagrant box add fails in version 1.8.7, succeeds in 1.8.1

### ISSUE THREAD

**Issue by romski** [mitchellh/vagrant#7993]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.8.7

### Host operating system
OS X 10.11.6 

### Guest operating system
Ubuntu 14.04 64bit

### Vagrantfile
n/a

### Debug output
See comments below

### Expected behavior
Box should be added

### Actual behavior
Error:
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'mybox' (v0) for provider:
    box: Unpacking necessary files from: file:///mybox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

### Steps to reproduce
I am using a private box created using Vagrant 1.8.1 
1. Install vagrant 1.8.7
2. Add box

### References
n/a

**Comment by andreabedini** [comment]
I seem to have the same problem. Here is the relevant part of the debug log

```
 INFO subprocess: Command in the installer. Specifying DYLD_LIBRARY_PATH...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: dyld: Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /opt/vagrant/embedded/bin/curl
  Reason: Incompatible library version: curl requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 6
 WARN downloader: Downloader exit code: 6
ERROR downloader: Exit code: 6
```

indeed

```
$ DYLD_LIBRARY_PATH=/opt/vagrant/embedded/lib/ /opt/vagrant/embedded/bin/curl
dyld: Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /opt/vagrant/embedded/bin/curl
  Reason: Incompatible library version: curl requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
zsh: abort      /opt/vagrant/embedded/bin/curl
```

```
$ otool -L   /opt/vagrant/embedded/bin/curl
/opt/vagrant/embedded/bin/curl:
	@rpath/libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
	@rpath/libssh2.1.dylib (compatibility version 2.0.0, current version 2.1.0)
	@rpath/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 2577.0.0)
```

Admittedly, I never really understood rpaths 😞

**Comment by andreabedini** [comment]
This has been already noticed in https://groups.google.com/forum/#!topic/vagrant-up/RdC6AXRWjQE

**Comment by romski** [comment]
@andreabedini Thanks for adding the debug/links. I'd already uninstalled and didnt have time to go bakc for the debug when raising the issue. This has saved me the job :)

**Comment by garystafford** [comment]
I had the exact same issue and debug results on OS X 10.11.6 as described above with v1.8.7, running any `vagrant up` or `vagrant box add` command (i.e. `vagrant box add hashicorp/precise64`). I downgraded to Vagrant [v1.8.6](https://github.com/mitchellh/vagrant/releases/tag/v1.8.6) from v1.8.7. I was then successful in adding the box (`box: Successfully added box 'hashicorp/precise64' (v1.1.0) for 'virtualbox'!`). The issue seems to be specific to v1.8.7 on Mac?

**Comment by chrisroberts** [comment]
Dup of #7969. Thanks for the report!
