### ISSUE TITLE
Vagrant provisioning rsync fails

### ISSUE THREAD

**Issue by stephenliberty** [mitchellh/vagrant#7999]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.8.6

### Host operating system
Ubuntu

### Guest operating system
OSX

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "OSX_10_11_XC_7_3_1"
    config.vm.box_url = "file:///mnt/external/OSX_10_11_XC_8.box"
    config.omnibus.chef_version = :latest
    config.vm.provision :shell, path: "vagrant/bootstrap.sh"
    config.vm.provision "chef_solo" do |chef|
      chef.add_recipe "recipe[vertafore_mobile_build::default]"
      chef.add_recipe "recipe[homebrew]"
      chef.add_recipe "recipe[vertafore_mobile_build::build_user]"
      chef.add_recipe "recipe[vertafore_mobile_build::build_machine_settings]"
      chef.add_recipe "recipe[vertafore_mobile_build::certificates]"
      chef.add_recipe "recipe[vertafore_mobile_build::development_environment]"
      chef.data_bags_path = "../data_bags"
      chef.cookbooks_path = ["../cookbooks"]
      chef.synced_folder_type = 'rsync'
      chef.encrypted_data_bag_secret_key_path = './secret'
    end
    config.berkshelf.enabled = true
#    config.vm.provision "file", source: "~/chef-solo.tar.gz", destination: "chef-solo.tar.gz"
#    config.vm.provision :shell, path: "vagrant/bootstrap.sh", run: 'always'
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/stephenliberty/6c416db223f46b29545227808805d8d0

### Expected behavior
The rsync should succeed, using the group that belongs to the vagrant user (assuming it has to know about the group?)

As an aside, I tried to add the 'vagrant/bootstrap.sh' which manually adds a group (incorrectly, but at least vagrant then sees it). But it doesn't run before the rsync, so it doesn't work. 

### Actual behavior
The rsync fails, saying that it could not find the vagrant group

```
==> default: Rsyncing folder: /home/XXXXX/.berkshelf/vagrant-berkshelf/shelves/berkshelf20161111-29855-5wwdp5-default/ => /tmp/vagrant-chef/d21e2c6d37623da977e7ca08c99ec5b1/cookbooks
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

find /tmp/vagrant-chef/d21e2c6d37623da977e7ca08c99ec5b1/cookbooks '!' -type l -a '(' ! -user vagrant -or ! -group vagrant ')' -exec chown vagrant:vagrant '{}' +

Stdout from the command:



Stderr from the command:

find: -group: vagrant: no such group


```

### Steps to reproduce
1. Run vagrant up with provisioning using the rsync folder type.

### References
I don't think so..

**Comment by stephenliberty** [comment]
(Updated comment, sorry, forgot to add actual output)

**Comment by kikitux** [comment]
On the guest, can you do:
`id`

and share the output of:
`vagrant ssh -c id`

T

**Comment by stephenliberty** [comment]
`id` output:

    uid=501(vagrant) gid=20(staff) groups=20(staff),701(com.apple.sharepoint.group.1),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),702(com.apple.sharepoint.group.2),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh-disabled)

`vagrant ssh -c id` output:

    uid=501(vagrant) gid=20(staff) groups=20(staff),701(com.apple.sharepoint.group.1),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),702(com.apple.sharepoint.group.2),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh-disabled)

**Comment by chrisroberts** [comment]
Hi! The problem appears to be that the box you are using does not include a `vagrant` group. Since there isn't a way to pass in custom options for the synced folder setup, you will likely need to just explicitly define the synced folders in your Vagrantfile (or update your base box to include the `vagrant` group). 

I will look into adding a configuration option to provide a default synced folder hash.

Cheers!
