### ISSUE TITLE
VHDX file being saved to .vagrant folder instead of default Hyper-V folder

### ISSUE THREAD

**Issue by BaldwinKoo** [mitchellh/vagrant#8001]
### Vagrant version
Installed Version: 1.8.7
Latest Version: 1.8.7

### Host operating system
Windows 10 Pro

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "hyperv" do |hv, override|
    override.vm.box = "nikel/xerus64"
    hv.memory = "1024"
  end
end
```
### Expected behavior
Save the Hyper-V (.VHDX) file into location specified by Hyper-V settings.
C:\Users\BB\Documents\Hyper-V\Virtual Hard Disks

### Actual behavior
Saved .vhdx file into .vagrant folder.
C:\BCC\\.vagrant\machines\default\hyperv\BB.vhdx

### Steps to reproduce
Start up a new vm using vagrant up command in powershell as administrator.

**Comment by bbrala** [comment]
Thus is pretty much by design, and would be hard to manage. What would happen if another box has the same vhd name? It would make things rather messy. Vagrant keeps it boxes in a central location so it is easier to manage and prevent weird collisions.

**Comment by chrisroberts** [comment]
That is correct, this is by design.
