### ISSUE TITLE
Cannot remove a box created with "vagrant up" and corrupted by system crash

### ISSUE THREAD

**Issue by alex75it** [mitchellh/vagrant#8006]
Hi,

during "vagrant up" operation I had a system crash (blue screen).
After a reboot I tried to start the box from VirtualBox.
It doesn't work due to a problem with some device, so I deleted it from VirtualBox 
and I tried to run "vagrant up" again but I had the error:
The metadata associated with the box 'ubuntu/trusty64' appears corrupted...[cut]

Then I tried "destroy", "remove", "halt", "box remove".. nothing work.

```
D:\m310-vagrant-env>vagrant destroy
The metadata associated with the box 'ubuntu/trusty64' appears corrupted.
This is most often caused by a disk issue or system crash. Please
remove the box, re-add it, and try again.

D:\m310-vagrant-env>vagrant box list
ubuntu/trusty64 (virtualbox, 20161109.0.0)
The metadata associated with the box 'ubuntu/trusty64' appears corrupted.
This is most often caused by a disk issue or system crash. Please
remove the box, re-add it, and try again.

D:\m310-vagrant-env>vagrant box remove ubuntu/trusty64
The metadata associated with the box 'ubuntu/trusty64' appears corrupted.
This is most often caused by a disk issue or system crash. Please
remove the box, re-add it, and try again.
```

I cannot run "vagrant init" because I already have vagrantfile.
"vagrant up" and "vagrant reload" return the same error as the other commands.
And I also removed the ".viagrant" folder and I tried to reboot...

It seems I'm stuck in this situation and the "help" or instructions from the output does not work.

What to do?

Windows 10, 64bit.
Latest VirtualBox version.
Vagrant version 1.8.7

Thanks,

Alessandro

**Comment by alex75it** [comment]
I uninstalled and reinstalled both VirtualBox and Vagrant. The error persists.
I tried to install Vagrant 1.8.6 (previous version). The error persists.

**Comment by bbrala** [comment]
Remove the .vagrant directory in the directory with the vagrant file and try again. That should fix the issue.

**Comment by alex75it** [comment]
Already tried. The error persists.
Thanks.

**Comment by kikitux** [comment]
the boxes are in

`[HOME]/.vagrant.d/boxes/[user]-VAGRANTSLASH-[box]`

Try `vagrant box remove ubuntu/trusty64`

or just deleting the folder in `[HOME]/.vagrant.d/boxes/`

**Comment by ZenanZha** [comment]
"just deleting the folder in [HOME]/.vagrant.d/boxes/" is a good sulotion for me. Thanks.
