### ISSUE TITLE
Plugin requiring a Ruby subshell requires a vagrant-gemfileXXXX-XXXX-XXXXX file

### ISSUE THREAD

**Issue by alpha01** [mitchellh/vagrant#8007]
Hello, 

I'm the maintainer of the plugin [vagrant-notify](https://github.com/fgrehm/vagrant-notify). At a high level, the plugin redirects `notify-send` from [guest](https://github.com/fgrehm/vagrant-notify/blob/master/files/notify-send.erb) to [host](https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb#L48) machine. The plugin works by spawning a [TCP server](https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb) on the host machine and binds it to a specific private network IP and useable port. The server runs as a daemon in the background listening to incoming text.  

After updating from Vagrant 1.7.5 to the current 1.8.7, I'm no longer able to communicate from guest to host using a Ruby `notify-send`  [wrapper script](https://github.com/fgrehm/vagrant-notify/blob/master/examples/osx/growl_for_mac/notify-send.rb) on the host system. 

### Vagrant version
Vagrant 1.8.7

### Host operating system
OS X Yosemite
10.10.5
Vagrant 1.8.7
VirtualBox Version 5.0.28

### Guest operating system
hashicorp/precise64
virtualbox 1.1.0

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end
```

### Debug output
vagrant up --debug https://gist.github.com/alpha01/f1f06ee476feaf6952e88e7f0c465278

### Expected behavior
Guest `notify-send` redirects stdin output to host [TCP Server](https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb), from there the host will [redirect](https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb#L48) the message to a `notify-send` [Ruby wrapper script](https://github.com/fgrehm/vagrant-notify/blob/master/examples/osx/terminal-notifier/notify-send.rb) on the host's $PATH. Effective mimicking the exact same command on the host. 

### Actual behavior
Vagrant is not creating a vagrant-gemfileXXXX-XXXX-XXXXX (VAGRANT_OLD_ENV_TMPDIR location) file that is needed to allow the guest VM to communicate with the host machine. 

For example, I have to manually touch the vagrant-gemfileXXXX-XXXX-XXXXX in order for communication between the guest and host to work.
Host Machine
```
$ touch /var/folders/48/xxswsy1n5g5g45pglv68087c0000gn/T/vagrant-gemfile20161114-3946-rp6hw4
```

Once the file has been touched, the corresponding vagrant-gemfile20161114-3946-rp6hw4.lock file is created by Vagrant when communication from the guest and host is established sucessfully. 
```
/var/folders/48/xxswsy1n5g5g45pglv68087c0000gn/T/vagrant-gemfile20161114-3946-rp6hw4
/var/folders/48/xxswsy1n5g5g45pglv68087c0000gn/T/vagrant-gemfile20161114-3946-rp6hw4.lock
```

The problem with this is that once I halt the guest, and start it back up again. I have to manually touch a vagrant-gemfileXXXX file all over again.
(From guest error)
```
vagrant@precise64:~$ /var/folders/48/xxswsy1n5g5g45pglv68087c0000gn/T/vagrant-gemfile20161114-8205-c6j6hj not found
```

I'm not sure if this a bug on my plugin or a bug with Vagrant itself given that the `vagrant-gemfileXXXX-XXXX-XXXXX.lock` file is automcatically created by Vagrant once the `vagrant-gemfileXXXX-XXXX-XXXXX` is manually created. Also this wasn't a problem before until now.

What makes me think this is a bug in Vagrant, is that it only affects if `notify-send` on the host is a Ruby script only. If `notify-send` on the host is anything else (python, bash, php, etc). Communication between guest and host does not seem to need a vagrant-gemfileXXXX-XXXX-XXXXX.

On older versions of Vagrant, this didn't seem to be an issue up till now.

If this is a bug in my plugin, what suggestions to suggest for this strange Ruby subshell behavior? Worse case, I can re-write both of our OS X host `notify-send` scripts in Python if need too.
https://github.com/fgrehm/vagrant-notify/blob/master/examples/osx/growl_for_mac/notify-send.rb
https://github.com/fgrehm/vagrant-notify/blob/master/examples/osx/terminal-notifier/notify-send.rb

### Steps to reproduce
1. On OS X host, install vagrant-notify.
2. On OS X host, setup customized `notify-send` run
```
printf '#!/usr/bin/ruby\n print "hello"' > /usr/local/bin/notify-send && chmod +x /usr/local/bin/notify-send
```
3. On guest, run  `echo "TEST" | nc 10.0.2.2 2250`

### References
https://github.com/fgrehm/vagrant-notify#demo
https://github.com/fgrehm/vagrant-notify/blob/master/lib/vagrant-notify/server.rb#L48

**Comment by alpha01** [comment]
I upgraded to Vagrant 1.9.0 and this is now longer an issue. I suspect this was fixed during the core Remove Bundler integration for handling internal plugins [GH-7793, GH-8000, GH-8011, GH-8031] changes that were.

Thanks! 🍻

**Comment by chrisroberts** [comment]
@alpha01 Hi! I wanted to test this out first before responding because I suspected that 1.9.0 would clean up the issue you were running into. Glad that it did and thanks for confirming!
