### ISSUE TITLE
The `puppet` binary appears not to be in the PATH of the guest...

### ISSUE THREAD

**Issue by kyledecot** [mitchellh/vagrant#8010]
### Vagrant version
Vagrant 1.8.7

### Host operating system
OS X Sierra 10.12.1 (16B2555)

### Guest operating system
CentOS release 6.8 (Final)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.provision "puppet"
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/kyledecot/52c10ec6b68dd3a66243b978d2100071

### Expected behavior
The puppet package should have been installed and a basic puppet node definition should have been applied.

### Actual behavior
The puppet package was not installed and thus `puppet` is not available in the path causing the provision to fail.

> The `puppet` binary appears not to be in the PATH of the guest. This
> could be because the PATH is not properly setup or perhaps Puppet is not
> installed on this guest. Puppet provisioning can not continue without
> Puppet properly installed.

### Steps to reproduce
1. Follow instructions under "BARE MINIMUM" on https://www.vagrantup.com/docs/provisioning/puppet_apply.html
2. `vagrant up`

**Comment by kikitux** [comment]
Hello

The documentation usully use hashicorp/precise64 as the base box.
This box have puppet installed.

I did check the provider files and didn't found anything that state puppet will be installed.

I will do a 2nd check, however I think is a documentation issue not listing `pre-requirement: install puppet`

**Comment by chrisroberts** [comment]
@kikitux :+1: puppet installation is not automatic. Adding a note in the documentation should suffice.

**Comment by kikitux** [comment]
https://github.com/mitchellh/vagrant/pull/8205
