### ISSUE TITLE
Openssl error on Vagrant 1.8.7 / MacOs Sierra

### ISSUE THREAD

**Issue by jkanschik** [mitchellh/vagrant#8013]
### Vagrant version
Vagrant 1.8.7

### Host operating system
MacOS Sierra 10.12.1

### Guest operating system
Not created.

### Vagrantfile
https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/vagrant/Vagrantfile

### Debug output
https://gist.github.com/jkanschik/db34fdac2da9aa3cc8a809f7458be6ad

### Expected behavior
Vagrant VMs should be created

### Actual behavior
On vagrant up, I get the following message (same for most other commands):

```
WARNING: can't open config file: /vagrant-substrate/staging/embedded/ssl/openssl.cnf
Generating RSA private key, 2048 bit long modulus
..............................................................................................................+++
...............................................................................................+++
e is 65537 (0x10001)
WARNING: can't open config file: /vagrant-substrate/staging/embedded/ssl/openssl.cnf
Unable to load config info from /vagrant-substrate/staging/embedded/ssl/openssl.cnf
failed generating SSL artifacts

```

### Steps to reproduce
git clone https://github.com/coreos/coreos-kubernetes.git
cd coreos-kubernetes/multi-node/vagrant
vagrant up

### References
GH-7747

**Comment by jkanschik** [comment]
FYI: Openssl has been installed via brew:
$ brew install openssl
Warning: openssl-1.0.1h already installed
$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016

**Comment by jkanschik** [comment]
The workaround to link the existing openssl as proposed in GH-7747 seems to work as well

`sudo ln -sf /usr/local/bin/openssl /opt/vagrant/embedded/bin/openssl`

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by roffe** [comment]
Problem exists on vagrant 1.9.1 with openssl from brew as well.

@jkanschik workaround solved it for me

**Comment by jorgecara** [comment]
Still happening on vagrant 1.9.4.
Also fixed with @jkanschik workaround but had to find out first where my openssl was installed (`whereis openssl`)

**Comment by cofyc** [comment]
Still happening on vagrant 1.9.5.

**Comment by chrisroberts** [comment]
@cofyc Running the ssl scripts using the bundled openssl works fine for me. Can you post a debug gist of the output from the failed run. Thanks!

**Comment by cofyc** [comment]
@chrisroberts 

`vagrant up --debug` output: https://gist.github.com/cofyc/fd74f1635cf7562eaea560ff156d8ce4

Mac OS version:

```
$ sw_vers -productVersion
10.11.6
```

**Comment by jerrac** [comment]
Just ran into this myself.

```
user@laptop  ~/dev/containerdev/coreos-kubernetes/multi-node/vagrant   master  vagrant up
WARNING: can't open config file: /opt/vagrant/embedded/openssl.cnf
Generating RSA private key, 2048 bit long modulus
.....................................................................................................................................................................................+++
.............................+++
e is 65537 (0x10001)
WARNING: can't open config file: /opt/vagrant/embedded/openssl.cnf
Unable to load config info from /opt/vagrant/embedded/openssl.cnf
failed generating SSL artifacts
```
```
sudo ln -sf /usr/local/bin/openssl /opt/vagrant/embedded/bin/openssl
```
Fixed it for me as well. Thanks @jkanschik !

Ubuntu 16.06
Vagrant 1.9.5

**Comment by stormbeta** [comment]
Ran into this today running vagrant 1.9.5. Problem is solved by manually linking brew'd version of openssl as others suggested.

**Comment by cringdahl** [comment]
Still happening in 1.9.8, symlink solution worked.

**Comment by jhalfmoon** [comment]
Using Vagrant 2.0.0-2 on Arch-Linux, same issue, symlink solution worked.
