### ISSUE TITLE
vagrant destory circumvented ?No errors output just the tips of vagrant command

### ISSUE THREAD

**Issue by X0o0Z** [mitchellh/vagrant#8015]
Recently, I have trouble using command `vagrant destory`. It doesn't work, and no error, just output the result as well as the command `command`. It disturbed me for a long time. Who can help? Tks

I checked the global-status as the following：

`$ vagrant global-status`
id       name    provider   state    directory
0813301  default virtualbox poweroff /Users/Xo_Oz/dev
5af9a9d  default virtualbox running  /Users/Xo_Oz/test_vagrant
ffa3f12  default virtualbox running  /Users/Xo_Oz/test_destory

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"

**----------------------------------------------------------------------------------------**

I've tried `vagrant global-status --prune` then `vagrant destory [args]` and `vagrant destory`，they have the same output as the following: 

_**Here is the output：**_
$ vagrant destory ffa3f12
Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     connect         connect to a remotely shared Vagrant environment
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     init            initializes a new Vagrant environment by creating a Vagrantfile
     login           log in to HashiCorp's Atlas
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     port            displays information about guest port mappings
     powershell      connects to machine via powershell remoting
     provision       provisions the vagrant machine
     push            deploys code in this environment to a configured destination
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configuration
     resume          resume a suspended vagrant machine
     share           share your Vagrant environment with anyone in the world
     snapshot        manages snapshots: saving, restoring, etc.
     ssh             connects to machine via SSH
     ssh-config      outputs OpenSSH valid configuration to connect to the machine
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     version         prints current and latest Vagrant version

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.

**----------------------------------------------------------------------------------------**

I have no idea why this happened。 So I tried `vagrant destory -h`，the output is as well as the following above。

**Version of Vagrant：**
Vagrant 1.8.7

**OS：**
macos Sierra 10.12.1

**[Here is the debug logs](https://gist.github.com/X0o0Z/0952ccd0d64f4db015f04e466adc1443)**

**Comment by kikitux** [comment]
@X0o0Z 

`vagrant destroy` is the command.

can you try  ?

check the word vs your command:
https://gist.github.com/X0o0Z/0952ccd0d64f4db015f04e466adc1443#file-vagrant_destory_debug-log-L249

Will leave close, please reopen if issue remains.

**Comment by X0o0Z** [comment]
@kikitux 
Yes. I have checked the word, the spelling is right. But the issue remains. What can I do for u about the issue?

**Comment by kikitux** [comment]
@X0o0Z can you share a new gist with `vagrant destroy` ?
