### ISSUE TITLE
Provision is executed also if it sets to "never" be run

### ISSUE THREAD

**Issue by Spamme1** [mitchellh/vagrant#8016]
### Vagrant version
1.8.6

### Host operating system
Ubuntu 14.04.5 LTS

### Guest operating system
Windows 2012 R2 (a-mcf/Win2012R2-WMF5-min)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "a-mcf/Win2012R2-WMF5-min"
  config.vm.network "public_network", bridge: "em1"

  config.vm.provider "virtualbox" do |vb|
    $name=File.basename(Dir.getwd)
    vb.name = $name+" "+Time.now.strftime("%a %d.%m.%Y %H-%M-%S")
    vb.linked_clone = true
    vb.memory = "4096"

    $port=5000
    for i in 0..$name.length-1
      $port+=$name[i].ord
    end
    vb.customize ["modifyvm", :id, "--vrdeport", $port]
  end

  config.vm.provision "Update", type: "shell", run: "never", inline: <<-POWERSHELL
    echo "This provision should never be run, if not explicit specified"
POWERSHELL
```

### Debug output
https://gist.github.com/Spamme1/06c8845fb9051f77a0987285147a7b56

### Expected behavior
In the documentation (https://www.vagrantup.com/docs/provisioning/basic_usage.html) is written:
"You can also set run: to "never" if you have an optional provisioner that you want to mention to the user in a "post up message" or that requires some other configuration before it is possible, then call this with vagrant provision --provision-with bootstrap."

I'm expecting that the "Update" provision is executed only if I explicit specify it, for example with:
```vagrant provision --provison-with Update```

### Actual behavior
The "Update" provision is executed anyway, also if it is configured to never be executed.
In both cases, "vagrant up" and "vagrant provision", the "Update" provision is executed.

### Steps to reproduce
1. Create a provision with the "run:never" attribute
2. Start the VM with "vagrant up"
3. Also "vagrant provision" executes again the "Update" provision

**Comment by bashofmann** [comment]
I can reproduce the same issue with Vagrant 1.8.7, macOS Sierra as host, Ubuntu 14.04 as guest

**Comment by bryantAXS** [comment]
Also having this issue

**Comment by imincik** [comment]
I also hit that issue now

**Comment by ibrmora** [comment]
I also hit that issue now. Vagrant 1.9.1, Ubuntu 16.04

**Comment by jvf** [comment]
Can confirm the issue on Host: OS X 10.11.6 (El Capitan), Guest: bento/debian-8.6 with Vagrant 1.8.6 and Vagrant 1.9.1.

**Comment by 0mp** [comment]
I've got the same issue. 

Host: Ubuntu 16.10 x86_64 running Vagrant 1.8.5. 

Guest box: ubuntu/xenial64.

**Comment by mjw-keenan** [comment]
+1, same issue.
Host: Fedora 25, Vagrant 1.8.5
Guest box: centos/7.

As an FYI, this discussion has a workaround that achieves the desired functionality (provision is only run when "--provision-with ABC" is specifed): [https://groups.google.com/forum/#!msg/vagrant-up/ogcSyB9VazM/c8MYWKtYBgAJ](https://groups.google.com/forum/#!msg/vagrant-up/ogcSyB9VazM/c8MYWKtYBgAJ)

**Comment by daks** [comment]
Same issue here on Debian testing, Vagrant 1.9.1

**Comment by errant-info** [comment]
+1
Darwin Kernel Version 15.6.0
Vagrant 1.8.6 
https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box

**Comment by scoobyshi** [comment]
I'm also experiencing this issue, hoping for a fix soon.
