### ISSUE TITLE
The error message said I should report this issue when I using vagrant share.

### ISSUE THREAD

**Issue by ghost** [mitchellh/vagrant#8023]
When vagrant sharing is on, suddenly it interrupted and gave the following message: 

*The sharing proxy exited with a non-zero exit status! This represents*
*an erroneous exit and likely a bug. Please report this issue.*

How can I get the detail of this error ?

**Comment by kikitux** [comment]
Hello.

There is a timer of 1 hour or so, so if this happen around the hour is expected.

To debug, set variable `VAGRANT_LOG=debug` before `vagrant share`

**Comment by X0o0Z** [comment]
Thank u. I've get the debug log. However I don't how to use the debug log.
