### ISSUE TITLE
Error on installing bindfs plugin

### ISSUE THREAD

**Issue by janw-oostendorp** [mitchellh/vagrant#8030]
When I try to install `vagrant-bindfs` I get an error, see below.
I did manage to install `vagrant-hostsupdater`

### Vagrant version
Vagrant 1.8.7
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]  (installed by vagrant)

### Host operating system
Ubuntu Mate fully updated

### Debug output
https://gist.github.com/janw-oostendorp/31c131631e9021eab346fca1039d788b

### Expected behavior
Installing a plugin

### Actual behavior
An error:

```
Installing the 'vagrant-bindfs' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing vagrant-bindfs (0.4.12), and Bundler cannot continue.
Make sure that `gem install vagrant-bindfs -v '0.4.12'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::InstallError: vagrant-bindfs requires Ruby version ~> 2.0.0.
```

### Steps to reproduce
1. `~$ vagrant plugin install vagrant-bindfs`
2. get error

**Comment by jhaakma** [comment]
I'm having the same issue. Looks like someone made a change to vagrant-bindfs which broke it:
https://github.com/gael-ian/vagrant-bindfs/commit/58de1ab3445776ba07aba649fed4bb457f9d66e3?_pjax=%23js-repo-pjax-container

**Comment by janw-oostendorp** [comment]
@jhaakma thanks that worked
