### ISSUE TITLE
"Vagrant up" on macOS returns empty error output

### ISSUE THREAD

**Issue by fcarran** [mitchellh/vagrant#8039]
### Vagrant version
Installed Version: 1.8.7
Latest Version: 1.8.7

### Host operating system
MacOS 10.12.1

### Guest operating system
ubuntu/trusty64
nrel/CentOS-6.5-x86_64

### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "acs" do |acs|
    acs.vm.box = "ubuntu/trusty64"
    acs.vm.hostname = "acs"
    acs.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "web" do |web|
    web.vm.box = "nrel/CentOS-6.5-x86_64"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.33.20"
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "db" do |db|
    db.vm.box = "nrel/CentOS-6.5-x86_64"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.33.30"
  end
end
```

### Expected behavior
Running "vagrant up", I expected for these 3 boxes to come up.

### Actual behavior
Received the following output
```
Bringing machine 'acs' up with 'virtualbox' provider...
Bringing machine 'web' up with 'virtualbox' provider...
Bringing machine 'db' up with 'virtualbox' provider...
==> acs: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    acs: Box Provider: virtualbox
    acs: Box Version: >= 0
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/trusty64"]
Error:
```

I was unable to find another issue opened about this issue with macOS.
Please let me know if I can assist with debugging further.

**Comment by ijaureguialzo** [comment]
I was having the same problem with new box downloads and updates, downgraded to 1.8.6 and it's working again.

**Comment by isabanin** [comment]
Same issue here with centos/7 box and Vagrant 1.8.7:

`$ vagrant init centos/7
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
$ vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos/7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'centos/7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/centos/7"]
Error: 
`

**Comment by fcarran** [comment]
Thanks for the tips.
Got around the issue as ijaureguialzo pointed out. I uninstalled using the recommended method (left my Vagrantfile as it was) and downloaded 1.8.6 from here: https://releases.hashicorp.com/vagrant/1.8.6/
I ran the installation, noticed that version still shows 1.8.7, but now running "vagrant up" works.
Hope this helps.

**Comment by fhenri** [comment]
check #7969

**Comment by hagay3** [comment]
Seems like embedded curl is the issue , just remove it
sudo rm -rf /opt/vagrant/embedded/bin/curl

**Comment by uhlissuh** [comment]
> downgraded to 1.8.6 and it's working again.

This worked for me too.

**Comment by chrisroberts** [comment]
Closing as dup of #7969
