### ISSUE TITLE
SSH times out with VMWare Fusion 8

### ISSUE THREAD

**Issue by dadgar** [mitchellh/vagrant#8078]
### Vagrant version
1.9.0
### Host operating system
macOS Sierra

### Guest operating system
Ubuntu 14.04

### Vagrantfile
https://github.com/hashicorp/nomad/blob/master/Vagrantfile

### Debug output
https://gist.github.com/dadgar/43f4c7541579899e742f335758a363bd
https://gist.github.com/dadgar/7e166d1b4e9aadf489e89b6553a1c266

### Expected behavior
What should have happened?
Should have SSH'd into the VM

### Actual behavior
What actually happened?
SSH times out. Appears to be using the wrong IP. If I ssh to the IP listed in vagrant up it works

### Steps to reproduce
1. vagrant up
2. vagrant ssh

**Comment by chrisroberts** [comment]
@dadgar Hi! Did this error start after an upgrade to VMware, Vagrant, or something else?

**Comment by dadgar** [comment]
Hey! So this is actually on a brand new laptop. Fresh install of everything and brand new license for Fusion 8

**Comment by chrisroberts** [comment]
@dadgar Okay, great. Hopefully that should make it easy to reproduce locally.

**Comment by dadgar** [comment]
@chrisroberts Great let me know if you need any more info as it happens every time!

**Comment by chrisroberts** [comment]
@dadgar one other thing, do you have virtualbox installed as well, or just vmware?

**Comment by chrisroberts** [comment]
@dadgar I also noticed that it looks like you are running just a plain `vagrant ssh` instead of `vagrant ssh NAME`. Are you experiencing the same issue if you provide the name of the instance you want to connect to?

**Comment by dadgar** [comment]
@chrisroberts I only have vmware installed. Also `vagrant ssh nomad-server01` results in the same thing

**Comment by dadgar** [comment]
To me this part is suspect:
```
Trying vmrun getGuestIPAddress...
 INFO subprocess: Starting process: ["/Applications/VMware Fusion.app/Contents/Library/vmrun", "getGuestIPAddress", "/Users/adadgar/Projects/go/src/github.com/hashicorp/nomad/.vagrant/machines/nomad-server01/vmware_fusion/c3649c37-df2e-4f43-a263-14bb21bdf5d8/ubuntu-1404-vmware.vmx"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 10.0.3.1
```

**Comment by chrisroberts** [comment]
@dadgar Just a note that I have this reliably reproducing locally and am chasing down a fix. VMware is grabbing the address from the wrong interface on the guest.

**Comment by dadgar** [comment]
Any update?

**Comment by chrisroberts** [comment]
Upstream issue: vmware/open-vm-tools#93

**Comment by chrisroberts** [comment]
@dadgar Fix for now that can be applied via Vagrantfile:

```ruby
Vagrant.configure(2) do |config|
  config.vm.provider :vmware_fusion do |vmware|
    vmware.enable_vmrun_ip_lookup = false
  end
end
```
