### ISSUE TITLE
Installer requires machine reboot

### ISSUE THREAD

**Issue by dorinlazar** [mitchellh/vagrant#8083]
It is unreasonable for the vagrant installer to require machine reboot.

### Vagrant version
1.9.0

### Host operating system
Windows 10

### Guest operating system
n/a

### Vagrantfile
n/a

### Debug output
n/a

### Expected behavior
No reboot after installation.

### Actual behavior
The installer requires reboot.

### Steps to reproduce
1. Run installer
2. Install
3. Reboot is required

### References
n/a

**Comment by chrisroberts** [comment]
The reboot is required to ensure the user has a correct setup. Reboot can be declined if desired.
