### ISSUE TITLE
Installer should ask for VAGRANT_HOME folder

### ISSUE THREAD

**Issue by dorinlazar** [mitchellh/vagrant#8084]
Since the Vagrant home folder size can become quite an issue, it should be asked at install time - even if it's under an „advanced” or „custom installation”.

### Vagrant version
1.9.0

### Host operating system
Windows 10 64 bit.

**Comment by chrisroberts** [comment]
The location of the vagrant home folder can be modified via the VAGRANT_HOME environment variable. If a different location than the default is required, a user can simply adjust their local working environment to set that environment variable to the desired path. Cheers!

https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_home

**Comment by dorinlazar** [comment]
I'm not saying that this isn't possible. I'm saying that the requirement to change VAGRANT_HOME might not be obvious to a normal (or advanced) Windows user, unless they really really read the whole documentation and try to understand from the start all the configurability options of vagrant and why they might change it.

An installer is meant to ease the installation of your application, such important option would be a must, from my point of view.
