### ISSUE TITLE
Vagrant 1.9 is not able to install local plugins

### ISSUE THREAD

**Issue by taliesins** [mitchellh/vagrant#8085]
When running `vagrant plugin install .\local-plugin.gem` you receive the following exception message:

```
C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2206:in `name_tuple': uninitialized constant Gem::NameTuple (NameError)
```

To fix this issue add `require 'rubygems/name_tuple'` to the top of `C:/HashiCorp/Vagrant/embedded/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb`

**Comment by chrisroberts** [comment]
Dup of #8069 and fixed in #8079. Thanks!
