### ISSUE TITLE
Missing 'faraday' gem

### ISSUE THREAD

**Issue by Andreabont** [mitchellh/vagrant#8088]
Hi, I installed Vagrant 1.9.0 from the official website and i try to install the follow plugins:

`
$ vagrant plugin install vagrant-librarian-puppet librarian-puppet
`

The install failed with this error:

`
Installing the 'vagrant-librarian-puppet' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/dependency.rb:315:in 'to_specs': Could not find 'faraday' (< 1.0, >= 0.7.4) among 45 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/opt/vagrant/embedded/gems', execute 'gem env' for more information
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1311:in 'block in activate_dependencies'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in 'each'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1300:in 'activate_dependencies'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1282:in 'activate'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:319:in 'block in activate_solution'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in 'each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:316:in 'activate_solution'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:244:in 'internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/bundler.rb:97:in 'install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:62:in 'block in install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:72:in 'call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/plugin/manager.rb:72:in 'install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/action/install_gem.rb:37:in 'call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in 'call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/builder.rb:116:in 'call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in 'block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/util/busy.rb:19:in 'busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in 'run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/base.rb:14:in 'action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:32:in 'block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in 'each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/install.rb:31:in 'execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/plugins/commands/plugin/command/root.rb:66:in 'execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/cli.rb:42:in 'execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/lib/vagrant/environment.rb:308:in 'cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.0/bin/vagrant:123:in '<main>'
`

I also try to install faraday:

`
$ vagrant plugin list 
`
`
faraday (0.10.0)
`

But it had no effect. Can you help me?

Thank you.

**Comment by mlt** [comment]
The patch in #8068 resolved this issue for me on Windows.

**Comment by chrisroberts** [comment]
Fixed via #8068. Thanks for the report!
