### ISSUE TITLE
Need a method, similar to chef.json that will provide the highest level of override

### ISSUE THREAD

**Issue by axos88** [mitchellh/vagrant#8101]
In the chef provisioner, I would like to see a method to define attributes at the highest level (maybe automatic, through the installation of an ohai plugin?), in order to be able to override things that are specific to the vagrant run:

The problem I am facing is that some wrapper cookbooks already have 'override'-s defined, and there seems to be no way to override those to fit the vagrant environment, as chef.json seems to operate on the normal level.

```
chef.automatic = {
  nginx: {
    user: 'vagrant'
  }
}
```

This could drop a file similar to dna.json into the ohai plugins directory, to make these attributes be on automatic level.

**Comment by chrisroberts** [comment]
This should give you what you're looking for:

https://www.vagrantup.com/docs/provisioning/chef_common.html#json

Cheers!

**Comment by axos88** [comment]
Please reopen, and read the issue more carefully. That option gives normal-level attributes, which are overridden by any overrides defined in a cookbook.

**Comment by axos88** [comment]
@chrisroberts

**Comment by axos88** [comment]
@chrisroberts
