### ISSUE TITLE
Vagrant attempts to destroy VM and drives too soon

### ISSUE THREAD

**Issue by gtirloni** [mitchellh/vagrant#8104]
### Vagrant version

1.9.1

### Host operating system

CentOS 7.2
VirtualBox 5.1.10

### Guest operating system

Fedora 24
VirtualBox 5.1.10 Guest Additions

### Debug output

```
vagrant destroy -f
==> fedora: Forcing shutdown of VM...
==> fedora: Destroying VM and associated drives...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["unregistervm", "55b1d781-d3d5-4732-96d3-94a8eed5bbc2", "--delete"]

Stderr: VBoxManage: error: Cannot unregister the machine 'gpii-pouchdb-lucene-tests_fedora_1481303873647_68219' while it is locked
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 155 of file VBoxManageMisc.cpp
```

### Expected behavior

VM gets deleted.

### Actual behavior

Vagrant proceeded to unregister the VM while shutdown has still not completed (the 'VirtualBox' process is still running).

Running `vagrant destroy -f` a few seconds later completes successfully.

### Steps to reproduce
1. vagrant up
2. vagrant destroy -f

**Comment by kikitux** [comment]
Hello.

Does this happens when you do `vagrant halt` first ?

If this only happen when the VM is on, perhaps we should add a higher wait between stop and delete.

If this does happen when VM is off, can you try manually couple of tims?

```
 $ vagrant halt
 $ VBoxManage list vms
"c7_host01_1481400784099_26895" {97bec202-de3a-4b06-b790-4aa742671dd0}
 $ VBoxManage unregistervm 97bec202-de3a-4b06-b790-4aa742671dd0 --delete
```

Thanks

**Comment by gtirloni** [comment]
It only happens when the machine is running. In fact, we added  `vagrant halt && sleep 10 && vagrant destroy -f` to our scripts with good results.

**Comment by gtirloni** [comment]
Maybe this is related (also seeing same issue with Packer): https://www.virtualbox.org/ticket/12477

**Comment by kikitux** [comment]
Yes, time by time you get that from VirtualBox.

Issue is still open on upstream, so I will close this ticket since you got a  workaround
