### ISSUE TITLE
VAGRANT_DOTFILE_PATH creates a "tilde" directory inside the local path

### ISSUE THREAD

**Issue by oleyka** [mitchellh/vagrant#8108]
### Vagrant version
1.9.1 (1.8.1 behaved as expected)

### Host operating system
macOS Sierra

### Guest operating system
not relevant

### Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/trusty32"
  end
end
```

### Debug output
not relevant

### Expected behavior
Setting:

```
export VAGRANT_DOTFILE_PATH="~/.vagrant"
```

should place all machine files in .vagrant/ relative to user's home.

### Actual behavior
Directory named "~" was created alongside the Vagrantfile.

### Steps to reproduce
1. export VAGRANT_DOTFILE_PATH="~/.vagrant"
2. vagrant up
3. ls

**Comment by marcindulak** [comment]
Isn't this related to the shell? Are you sure quoting is correct in this case?

    export VAGRANT_DOTFILE_PATH=~/.vagrant
    echo $VAGRANT_DOTFILE_PATH

**Comment by oleyka** [comment]
@marcindulak Unquoting sure changes the value (and the behavior), but both cases should be producing the same result. Numerous apps have no problem parsing quoted "~" within their envvars.

E.g., do the following:
```
export PATH="~:$PATH"
```
and create an executable `ls` in your home, then run:
```
$ ls
```
Which `ls` got executed?

**Comment by carlosefr** [comment]
@oleyka  `~` is a shell expansion character. In your example the shell itself is parsing the contents of the `PATH` variable, so it works.

In either case the proper way to refer to the user's home directory in quoted contexts is by using the `HOME` environment variable:
```
export VAGRANT_DOTFILE_PATH="${HOME}/.vagrant"
```

**Comment by oleyka** [comment]
@carlosefr Thank you for taking time to explain the fine details to me. Yet just like I said, multiple applications have no problem expanding tilde in their envvars and vagrant does not have to be an exception. I would not have filed the ticket if it was not a regression from a previously observed behavior.

**Comment by carlosefr** [comment]
I'm unsure on how that used to work. I submitted some changes to how that path is handled a while ago and there was no explicit parsing of `~` that I could see. Maybe that was some side effect somewhere else and, thus, undefined behavior.

I disagree that other tools parsing `~` by themselves is enough reason for vagrant to do the same. Even in the shell, `~` is mostly intended as an interactive shortcut.

**Comment by chrisroberts** [comment]
Looks like this should be an easy fix by including a `File.expand_path`
