### ISSUE TITLE
Output of inline script isn't displayed in real-time

### ISSUE THREAD

**Issue by kenorb** [mitchellh/vagrant#8110]
I'm running Vagrant AWS instances via Jenkins, however the output isn't properly displayed for inline scripts. The output is displayed after the inline script has been executed, but not during the execution (as it does for `config.vm.provision "shell"`). So if the command takes an hour, I'll see the results after that, which isn't very convenient.

E.g.

```
   script = "set -x;"
   script << %Q[/vagrant/scripts/my_script.sh]
   config.vm.provision "shell" do |s|
     s.binary = true # Replace Windows line endings with Unix line endings.
     s.privileged = false # Run as a non privileged user.
     s.inline = script
   end
```

So the output is like:

```
VM-aws: Running provisioner: shell...
VM-aws: Running: inline script
```

and the output is frozen until the script is done.

Vagrant version: 1.8.1

Host operating system: Ubuntu

It is an expected behaviour? Or I am missing some configuration?

**Comment by kenorb** [comment]
I had `config.ssh.pty` enabled, when disabled, it started to work fine (the progress is shown on the fly). Is that expected behaviour?

**Comment by chrisroberts** [comment]
This is the expected behavior when pty is enabled as the output must be parsed. I see that there is no note of the behavior in the documentation so I'll label this as such to include a note there.
