### ISSUE TITLE
Docker provider does not prompt for sudo password

### ISSUE THREAD

**Issue by JPvRiel** [mitchellh/vagrant#8111]
### Vagrant version
Vagrant 1.8.1 and 1.9.1 tested

### Host operating system
Ubuntu 16.04.1 LTS

### Guest operating system
docker 1.12.3 native (other providers libvirt and lxc also working)

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

### Debug output
N/A issue is obvious, vagrant is not promoting or using `sudo` when running docker commands (as provider, not provisioner)

```
vagrant up
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "ps", "-a", "-q", "--no-trunc", {:notify=>[:stdout, :stderr]}]

Stderr: Cannot connect to the Docker daemon. Is the docker daemon running on this host?


Stdout: 
```

### Expected behavior
Vagrant prompts for sudo password. I note other plugins like landrush and lxc do so.

### Actual behavior
Vagrant didn't use sudo or prompt for password when it lacked permission on docker socket
The workaround is to simply run `sudo vagrant up --provider docker`, but this runs more code with root privileges than is desirable?

The  workaround is not great. `.vagrant` or files within it end up getting owned by root.

**Comment by chrisroberts** [comment]
Hi there. `sudo` isn't required for docker. Just add the docker group to your user: `sudo usermod -aG docker $USER`. You'll need to log back in afterwards so you're groups are updated. Cheers!

**Comment by Mayeu** [comment]
I would love to see Vagrant supporting docker with sudo. Being part of the docker group is equivalent to running as root all the time. Docker is a priviledge daemon, and is able to mount and write every files of your system, thus being part of the `docker` group is pretty dangerous...

**Comment by pm98zz-c** [comment]
Hi, same here. 
Adding yourself to the docker group is a serious security issue ( details are there https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface ). On the other hand, using sudo to run vagrant commands themselves, does kind of work but makes a mess of files ownership/permissions with mounted volumes.

I currently use a wrapper script (see https://github.com/codeenigma/ce-vm/blob/4.x/scripts/vagrant-docker-sudo.sh) that adds my user to the docker group, run my vagrant command, and then removes me from the docker group again.

However, this is far from ideal, and I'd rather get rid of this ugly workaround and have a switch in Vagrant itself.

**Comment by gergelypolonkai** [comment]
I’m with the guys above on this. Having the docker group is a security hole that shouldn’t be forced on Vagrant users.
