### ISSUE TITLE
vagrant package --base --output Does Not Include vagrant_private_key

### ISSUE THREAD

**Issue by antonio-malcolm** [mitchellh/vagrant#8112]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.9.1

### Host operating system
Void Linux

### Guest operating system
Void Linux

### Vagrantfile
(Not sure why this makes any difference, in my case)
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "void-x86_64-v2016.12.11"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
N/A

### Expected behavior
When packaging a base box to another box, using `vagrant package --base <BASE-NAME> --output <OUTPUT-NAME>.box`, it should include the private key, same as calling `vagrant box repackage`

OR, it should overwite with an insecure key, so vagrant will automatically install a new private key, when the new box boots for the first time.

### Actual behavior
No private key is included with the new package, so we cannot `vagrant ssh` into guest

### Steps to reproduce
1. run `vagrant package --base <BASE-NAME> --output <OUTPUT-NAME>.box`
2. cd to new package directory, add box, init, up and ssh
3. See shiny error message telling you there's no private key, search file system, to see, indeed, there's no private key

### References
N/A

**Comment by antonio-malcolm** [comment]
Ok, so I notice there's no issue with renaming package.box to whatever you feel like, after using `vagrant box repackage`.

Is it then intentional that `vagrant package --base --output` does not include the private key, while `repackage` does? Is there some fundanmental difference, in intent, which requires it? I ask, because this wasn't an issue, just a few months ago, and I had a fairly specific workflow, for versioning and releasing updated shared boxes, and have changed it now, around this difference, which is fine, however, I want a better understanding of why, and, hopefully, with that, not need to change my workflow too often, else, I think I'd rather eat the extra hard drive space involved with cloning Virtualbox VMs, than attempt to constantly change my workflow around changes to Vagrant.

**Comment by antonio-malcolm** [comment]
https://github.com/mitchellh/vagrant/issues/5186

**Comment by antonio-malcolm** [comment]
OK, so I performed a complete reinstall of vagrant, and, now, when I use `package`, I get the following message (which is reaussuring, and probably how it _should_ work):

```
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
```

Will continue with my usual update process, and see if I can successfully finish it.

**Comment by antonio-malcolm** [comment]
OK, I've also found that restoring the insecure key **before** running `vagrant package` will result in vagrant generating a new key upon running `vagrant up` on the new package (see my previoous comment).

```
$ rm /home/vagrant/.ssh/authorized_keys

$ wget --no-check-certificate \
 https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub \
 -O /home/vagrant/.ssh/authorized_keys
```

**Comment by leereichardt** [comment]
@antonio-malcolm  I'm still having major issues with this and I'm on Vagrant 1.9.1.

I create a box based on the centos/7 from hashicorp (You know, the default thing). I set it up all, then I package it, and it all looks fine. I then add it as a box in another location on my computer, do the normal vagrant file to point to the right box, then I just get the authentication error. I tried your comment right above before packaging, but then I can't SSH back in to the template box that I'm packaging.

Any ideas?

**Comment by antonio-malcolm** [comment]
ACK! Sorry this is coming so many months late!
After replacing the secure key with the insecure key, runnning `vagrant up` on your template box should trigger vagrant to set another secure key (I would think). If not, you might need to remove or destroy the template box from your list, then add it again. Also, be sure to check your vagrant file.

**Comment by antonio-malcolm** [comment]
ADDENDUM:  I'm not sure which provider you're using, but, I just had a thought.

Instead of swapping the key in the template box, it might better serve us to use the provider to swap out the key in the newly packaged and added box. For example, if using a VirtualBox provider, package a new box from your template, start the new box, log in from VirtualBox, instead of from vagrant ssh, then replace the key. I will try this tonight or tomorrow, and I can't think of why it would not work.

I may have not noticed the behavior you're describing, due to the way I version my boxes.
Usually, for each new release, I have a barebones Linux base box (currently, I use Void), and a LAMP base box. Typically, I swap out the key in the most recent box, which is used as the template for the next, package, add, start, update, test, and swap out the key, before pushing to Atlas and using it as the template for the next LAMP box version. Because my barebones Linux boxes are so barebones, and I build my LAMP packages from source (meaning I don't need to trust anything to package managers, and can simply fix discrepancies before usage/release) I've not run into an issue, so I've never had to roll back, and, thus, have never hit your issue.

**Comment by antonio-malcolm** [comment]
Ok, so I tinkered a bit, this evening, and sorted out that I'd rather my template package retain the insecure key, even if it means I can't SSH into the box. I can update what little is in my base template box (Linux kernel, GRUB, ssh, ntp, etc.) from the Virtualbox UI, just fine, and all boxes packages from the template have a recognized insecure key on their first boot. The template box is used as baseline for all my other boxes, so this is the best-case scenario (with a better solution being that someone fixes vagrant).

**Comment by kikitux** [comment]
@antonio-malcolm 

So the best experience is:

from template use config.ssh.inset_key = false on the first box.

So when you repackage still use the insecure key that will be replaced on first boot on the packaged box.

If you would like to build a custom box with custom ssh key I would suggest use packer since offer more flexibility 

Thanks
