### ISSUE TITLE
[Microsoft/EdgeOnWindows10 box] Shell provisioner implicitly requires sudo (coreutils) to execute commands

### ISSUE THREAD

**Issue by mcandre** [mitchellh/vagrant#8113]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

```console
$ vagrant -v
Vagrant 1.9.1
```

### Host operating system
This is the operating system that you run locally.
macOS Sierra 10.12.1

### Guest operating system
This is the operating system you run in the virtual machine.

```console
$ vagrant box list
Microsoft/EdgeOnWindows10 (virtualbox, 1.0)
```

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "Microsoft/EdgeOnWindows10"

  # Default username, password tuple copied from https://gist.github.com/bugyt/445a7ef487ee9a5ad52f
  config.ssh.username = "IEUser"
  config.ssh.password = "Passw0rd!"

  config.vm.network "forwarded_port", host: 33389, guest: 3389, id: "rdp", auto_correct: true
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
  SHELL
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Expected behavior
What should have happened?

When I try to `vagrant up`, I get a few different oddities:

* Default username/password combination in base image is not the typical `vagrant/vagrant`, but `IEUser/Passw0rd!`, so `Vagrantfile` must be tweaked accordingly from a fresh `vagrant destroy -f; vagrant box destroy Microsoft/EdgeOnWindows10; vagrant init Microsoft/EdgeOnWindows10 && vagrant up` run.
* Unknown whether ssh, powershell, and/or rdp are preferred for entering into a guest terminal sessions for this image. Documentation is sparse on the Atlas page.
* The default SSH key configuration does seem to not work out of the box--a password prompt is often presented.
* `vagrant ssh` follwowed by the `Passw0rd!` password, lands the user in a strange `sh` environment, such that `sudo` is genuinely not found in the default `$PATH`, though that's as confirmed by `where`(.exe), as `which`, like `sudo` and other coreutils, does not appear to be available, or at least not in the default `$PATH`.
* And, the powershell provision does not appear to be available on macOS (?)
* This image presents difficulties with provisioning, as the `shell provisioner seems to implicitly call the configured commands inside of a `sudo` call, whereas this Windows image does not feature sudo, or does not have it in the default `$PATH` somehow.
* Could we get provisioners for `exec`, `cmd`, and/or `powershell` calls? Maybe that would work better than `sudo` for this image.
* Is there a `sudo.exe`-like binary that I configure my `Vagrantfile` to place into `$PATH` somewhere, in particular to do this before the implicit `mkfile -p /vagrant` call fails in the initial `vagrant up`?
* Finally, after the initial `vagrant up`, subsequent `vagrant up; vagrant ssh` calls ignore the earlier `mkdir -p /vagrant` error, resulting in a bad state.

### Actual behavior
What actually happened?

```console
$ vagrant destroy -f && vagrant up
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'Microsoft/EdgeOnWindows10'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'Microsoft/EdgeOnWindows10' is up to date...
==> default: Setting the name of the VM: karp_default_1481526091656_70614
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3389 (guest) => 33389 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: IEUser
    default: SSH auth method: password
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.0.2
    default: VirtualBox Version: 5.1
==> default: Mounting shared folders...
    default: /vagrant => /Users/andrew/go/src/github.com/mcandre/karp
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p /vagrant

Stdout from the command:



Stderr from the command:

sh: sudo: command not found
```

### Steps to reproduce

https://gist.github.com/mcandre/ddc03bf5c36720731345eeb408261911

**Comment by StefanScherer** [comment]
@mcandre The box is provided by Microsoft and not Hashicorp, so it has nothing to do with Vagrant itself and this repo. See https://atlas.hashicorp.com/Microsoft/ for details, but I've tried that email address shown there months ago without any reply.

PowerShell provisioning works from macOS with WinRM communicator, but don't know if that works with SSH.

There are better Windows boxes out there that are more up-to-date and have WinRM turned on by default etc. and default vagrant/vagrant login.

**Comment by mcandre** [comment]
Thanks for the details!

I wish Atlas promoted a more official, working example of a Windows guest, but I'll try out some of the community-maintained ones in the meantime.
