### ISSUE TITLE
Vagrant freezes at Vagrant insecure key has detected with CentOS 7.3 VM.

### ISSUE THREAD

**Issue by breisig** [mitchellh/vagrant#8114]
Hello,

I am running the latest Vagrant (1.9.1 and I tried with 1.8.7] trying to bring up a CentOS 7.3 Linux VM with the latest Virtualbox[5.1.10] running on Windows 10 and it seems the vagrant 'up' process never actually replaces the insecure ssh key and eventually times out.

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'virtualbox-centos73.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'virtualbox-centos73.box' (v0) for provider: virtualbox
    default: Downloading: https://mysite.com/vagrant/virtualbox-centos72.box
    default: Progress: 100% (Rate: 43.6M/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'virtualbox-centos73.box' (v0) for 'virtualbox'!
==> default: Importing base box 'virtualbox-centos73.box'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: localdevelopment
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 443 (guest) => 4443 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.

Even thought Virtualbox Vagrant session is running and I can connect to my VM, It seems with CentOS 7.3  (or 7.2 with all updates which will now upgrade you automatically to 7.3). This never happen with the regular CentOS 7.2 and updates (that didn't automatically upgrade you to 7.3). Eventually vagrant will time out and  say.

**Comment by gtirloni** [comment]
I've seen this happen when the permissions of the authorized_keys file are incorrect.

What's the output of `ls -la /home/vagrant/.ssh` ?

**Comment by breisig** [comment]
@gtirloni ls -la /home/vagrant/.ssh
total 12
drwx------  2 vagrant vagrant 4096 Dec 14 15:35 .
drwx------. 4 vagrant vagrant 4096 Dec 14 15:40 ..
-rw-------  1 vagrant vagrant  409 Dec 14 15:35 authorized_keys

**Comment by gtirloni** [comment]
Does it also happen with the official `centos/7` box?

**Comment by kikitux** [comment]
@breisig so this was an issue at some point but should be long fixed.

Can you update vagrant and virtualbox, try again and confirm all is working?

Thanks
