### ISSUE TITLE
Environment variables with 

### ISSUE THREAD

**Issue by johnament** [mitchellh/vagrant#8116]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

`vagrant 1.9.1`

### Host operating system
This is the operating system that you run locally.

`Windows 10`

### Guest operating system
This is the operating system you run in the virtual machine.

`CentOS 6.6`

### Vagrantfile
```ruby
  config.vm.provision "puppet", run: "always" do |puppet|
    puppet.temp_dir = "/tmp"
    puppet.options = ['--modulepath=/tmp/modules']
    puppet.manifests_path = ENV['DEV_HOME']+"/puppet/manifests"
    puppet.manifest_file = "default.pp"
  end

```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

The environment variable gets replaced correctly with "/value/of/variable"

### Actual behavior
What actually happened?

The variable is getting replaced with the value of "c:/value/of/variable"

### Steps to reproduce
1. Boot VM
2. See that the wrong variable is used.

### References
Are there any other GitHub issues (open or closed) that should be linked here?

None

**Comment by marcindulak** [comment]
'DEV_HOME' is the value on the Windows host, it seems reasonable to me that is starts with 'c:\'.
What is outputted from Windows by

     echo %DEV_HOME%

or if powershell

    $Env:DEV_HOME

**Comment by johnament** [comment]
Hi, sorry I wasn't clear on that part.  In this case, they're using cygwin to run vagrant, in which case c: isn't valid.

**Comment by marcindulak** [comment]
If I remember well `c:/` is valid on cygwin too, better explicitly verify the value with `echo $DEV_HOME` from cygwin.

**Comment by gtirloni** [comment]
Please add the debug output.

**Comment by chrisroberts** [comment]
Hi @johnament. Please include the debug output of the failed run. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
