### ISSUE TITLE
vagrant failed to up private network in Fedora 25

### ISSUE THREAD

**Issue by skvl** [mitchellh/vagrant#8120]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Linux

### Guest operating system
Fedora 25

### Vagrantfile
```ruby
boxes = [
  {
    :box  => "mybox",
    :name => "mybox",
    :net  => "192.168.17.10"
    ]
  }
]

Vagrant.configure("2") do |config|
  boxes.each do |opts|
    config.vm.define opts[:name] do |box|
      box.vm.box = opts[:box]
      box.vm.hostname = opts[:name]
      box.vm.network  "private_network", ip: opts[:net]
  end
end
```

### Expected behavior
`ifconfig` inside *mybox* should display *IP* from config.

### Actual behavior
Interface is down.

### Steps to reproduce
1. vagrant up mybox
2. vagrant ssh mybox
3. ifconfig

**Comment by chrisroberts** [comment]
Closing as dup of #8096
