### ISSUE TITLE
vagrant up fails with: Invalid argument - ruby_setenv() (Errno::EINVAL)

### ISSUE THREAD

**Issue by daveespo** [mitchellh/vagrant#8126]
When `Vagrant::Util::Env.with_original_env` is called, it horks a 

Invalid argument - ruby_setenv() (Errno::EINVAL)

I've tracked this down to https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/util/env.rb#L9 and when dumping the contents of `Vagrant.original_env` to the console, I see that it has a blank string key (the complete stack trace is in the gist linked below):

````
Vagrant.original_env
{""=>"ExitCode=00000000", "ALLUSERSPROFILE"=>"C:\\ProgramData", "APPDATA"=>"C:\\Users\\esposito\\AppData\\Roaming", "CommonProgramFiles"=>"C:\\Program Files (x86)\\Common Files", "CommonProgramFiles(x86)"=>"C:\\Program Files (x86)\\Common Files", "CommonProgramW6432"=>"C:\\Program Files\\Common Files", "COMPUTERNAME"=>"BLAH", "ComSpec"=>"C:\\WINDOWS\\system32\\cmd.exe", "FPS_BROWSER_APP_PROFILE_STRING"=>"Internet Explorer", "FPS_BROWSER_USER_PROFILE_STRING"=>"Default", "HerokuPath"=>"C:\\Program Files (x86)\\Heroku", "HOMEDRIVE"=>"C:", "HOMEPATH"=>"\\Users\\esposito", "JAVA_HOME"=>"c:\\jdk1.8.0_66", "LOCALAPPDATA"=>"C:\\Users\\esposito\\AppData\\Local", "LOGONSERVER"=>"\\\\BLAH", "NUMBER_OF_PROCESSORS"=>"8", "OS"=>"Windows_NT", "Path"=>"C:\\ProgramData\\Oracle\\Java\\javapath;;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;c:\\Users\\esposito\\Documents\\apache-ant-1.9.6\\bin;C:\\Program Files (x86)\\Heroku\\bin;C:\\Program Files (x86)\\git\\cmd;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files\\Amazon\\AWSCLI\\;C:\\nodejs\\;C:\\opscode\\chefdk\\bin\\;C:\\HashiCorp\\Vagrant\\bin;C:\\Users\\esposito\\AppData\\Roaming\\npm;%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps;", "PATHEXT"=>".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "PROCESSOR_ARCHITECTURE"=>"x86", "PROCESSOR_ARCHITEW6432"=>"AMD64", "PROCESSOR_IDENTIFIER"=>"Intel64 Family 6 Model 63 Stepping 2, GenuineIntel", "PROCESSOR_LEVEL"=>"6", "PROCESSOR_REVISION"=>"3f02", "ProgramData"=>"C:\\ProgramData", "ProgramFiles"=>"C:\\Program Files (x86)", "ProgramFiles(x86)"=>"C:\\Program Files (x86)", "ProgramW6432"=>"C:\\Program Files", "PROMPT"=>"$P$G", "PSModulePath"=>"C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\;C:\\opscode\\chefdk\\modules\\", "PUBLIC"=>"C:\\Users\\Public", "SESSIONNAME"=>"Console", "SystemDrive"=>"C:", "SystemRoot"=>"C:\\WINDOWS", "TEMP"=>"C:\\Users\\esposito\\AppData\\Local\\Temp", "TMP"=>"C:\\Users\\esposito\\AppData\\Local\\Temp", "USERDOMAIN"=>"BLAH", "USERDOMAIN_ROAMINGPROFILE"=>"BLAH", "USERNAME"=>"esposito", "USERPROFILE"=>"C:\\Users\\esposito", "VBOX_MSI_INSTALL_PATH"=>"C:\\Program Files\\Oracle\\VirtualBox\\", "windir"=>"C:\\WINDOWS"}
````

If I replace line 9 with:

`ENV.update(Vagrant.original_env.delete_if {|k,v| k.nil? || k == ""})`

My vagrant starts up just fine ... But since I have no idea what's going on here, I am open to other solutions

### Vagrant version
1.9.1

### Host operating system
Windows 10

### Guest operating system
Ubuntu 14 (trusty64)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "xxx-rails"
  config.ssh.port = 2299
  config.vm.network :forwarded_port, guest: 22, host: 2299, id: 'ssh'
  config.vm.network :forwarded_port, guest: 5432, host: 5499
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.synced_folder '.', '/home/vagrant/project'
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
  end

  #Install vagrant plugin:
  #https://github.com/schisamo/vagrant-omnibus
  config.omnibus.chef_version = '11.6.0'
  #Install vagrant plugin:
  #https://github.com/berkshelf/vagrant-berkshelf
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.roles_path = 'vagrant-chef-role'
    chef.add_role 'heroku'
  end

end

```

### Debug output
https://gist.github.com/daveespo/5735856cbb355546f18b6ae6c0e6a3ed

### Expected behavior
My VM should've started

### Actual behavior
My VM didn't

Are there any other GitHub issues (open or closed) that should be linked here?

I thought this was a vagrant-berkshelf plugin problem but it seems like Vagrant.original_env is becoming polluted with blank string key. I opened this but after debugging it looks like it belongs here

https://github.com/berkshelf/vagrant-berkshelf/issues/314

**Comment by joelhandwell** [comment]
Getting same issue. I'm also on Windows 10, with vagrant 1.9.1 and vagrant-berkshelf plugin. using chef-zero provisioner.
Getting error at [line 9 of the env.rb](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/util/env.rb#L9) 
Error comes when using chef provisioner with vagrant-berkshelf plugin and did not get error while just running ```vagrant init -m ubuntu/trusty64 && vagrant up```

Reproduced as following:

```
C:\Users\Joel\Code\oss\vbox\u14dk>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/env.rb:9:in `update': Invalid argument - ruby_setenv() (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/env.rb:9:in `with_original_env'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/env.rb:39:in `with_clean_env'
        from C:/Users/Joel/.vagrant.d/gems/2.2.5/gems/vagrant-berkshelf-5.1.1/lib/vagrant-berkshelf/helpers.rb:62:in `berks'
        from C:/Users/Joel/.vagrant.d/gems/2.2.5/gems/vagrant-berkshelf-5.1.1/lib/vagrant-berkshelf/action/check.rb:33:in `berkshelf_version_check!'
        from C:/Users/Joel/.vagrant.d/gems/2.2.5/gems/vagrant-berkshelf-5.1.1/lib/vagrant-berkshelf/action/check.rb:16:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

And this error was suppressed when I applied https://github.com/mitchellh/vagrant/pull/8127

**Comment by wstaples** [comment]
Everything was working fine until I installed `vagrant plugin install vagrant-vbguest` then I started getting this error. The above solution for #8127 works as a fix. I do use the vagrant-bershelf plugin. Windows 7, vagrant 1.8.7, Virtualbox 5.1.10 r112026 (Qt5.6.2)

**Comment by mlh758** [comment]
This also happens to me with the [Berkshelf](https://github.com/berkshelf/vagrant-berkshelf) plugin.

I'm using Vagrant 1.9.1 and Windows 7.

Virtual Box Version 5.1.12 r112440 (Qt5.6.2)

**Comment by apsolut** [comment]
**Win10, 
Vagrant 1.9.1, 
VVV 1.4.0 (branch:develop), 
Ubuntu 14 (trusty64),** 
using **vagrant-vbguest** also.. 
after vagrant up everything is loading fine, then when its almost  done I get:
`C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/json/common.rb:155:in `parse': 776: unexpected token at '' (JSON::ParserError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/json/common.rb:155:in `parse'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:236:in `cached_synced_folders'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:77:in `save_synced_folders'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/synced_folders.rb:129:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in call'...
- then I do again "vagrant up" - and my sites are up without issues... 

hm... Updated from vagrant 1.8.x

**Comment by gggeek** [comment]
Same issue as #7857 ?
The suggested fix did the trick for me.
Env: win 8.164bit, vagrant 1.9.1, vbox 5.1.14

**Comment by geekman7473** [comment]
I am also seeing this behavior with Vagrant 2.1.2 on Windows 10 Professional. The issue does not occur with Vagrant 2.1.1. Related section of Vagrantfile provided below.

Only the lines before `Vagrant.configure("2") do |config|` cause the issue.

`required_plugins = %w(vagrant-docker-compose vagrant-vbguest vagrant-disksize vagrant-timezone)`

`plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }`

`if not plugins_to_install.empty?`
`  puts "Installing plugins: #{plugins_to_install.join(' ')}"`
`  if system "vagrant plugin install #{plugins_to_install.join(' ')}"`
`    exec "vagrant #{ARGV.join(' ')}"`
`  else`
`    abort "Installation of one or more plugins has failed. Aborting."`
`  end`
`end`
`Vagrant.configure("2") do |config|`
`	...`
`end`

**Comment by Jaskaranbir** [comment]
@geekman7473 try uninstalling and reinstalling the Vagrant. Seriously, that's what fixed it for me. Tried making changes to PATH, but reverted since they didn't work; reinstalling worked though.

**Comment by tiffany-taylor** [comment]
I just tried uninstalling Vagrant then restarting, installing Vagrant again using the same msi in my Downloads folder then restarting, then tried `vagrant plugin install vagrant-hostmanager`, but I still receive the error.

I'm on Windows 10.

$ vagrant plugin install vagrant-hostmanager
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `<main>'
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `<main>'
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `<main>'
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `<main>'
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `<main>'
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `<main>'
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `<main>'
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `<main>'
