### ISSUE TITLE
NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.

### ISSUE THREAD

**Issue by user0007** [mitchellh/vagrant#8136]
### Virtualbox
5.1.10 (x64)

### Vagrant version
1.9.1

### Host operating system
Xubuntu 16.10 (xfce)

### Guest operating system
Ubuntu 16.04

### Vagrantfileu
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.box_version = "20161129.0.0"
  config.vm.hostname = "my-name"

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024
    vb.name = "my-name"
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080, protocol: "tcp"
  config.vm.synced_folder "./", "/home/ubuntu/www", owner: "ubuntu", group: "ubuntu"
  config.ssh.username = "ubuntu"
  config.ssh.forward_agent = true

  config.vm.provision "shell" do |s|
  s.inline = <<-'SHELL'
...
SHELL
  end
end
```

### Debug output

>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO ssh: Attempting SSH connection...
>  INFO ssh: Attempting to connect to SSH...
>  INFO ssh:   - Host: 127.0.0.1
>  INFO ssh:   - Port: 2222
>  INFO ssh:   - Username: ubuntu
>  INFO ssh:   - Password? true
>  INFO ssh:   - Key Path: []
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "4cab0d16-105a-4512-93ba-60c898c9ba3f", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO ssh: SSH not ready: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
> The error message is shown below. In many cases, errors from this
> library are caused by ssh-agent issues. Try disabling your SSH
> agent or removing some keys and try again.
> 
> If the problem persists, please report a bug to the net-ssh project.
> 
> timeout during server version negotiating>

### Expected behavior

>  INFO ssh: Attempting SSH connection...
>  INFO ssh: Attempting to connect to SSH...
>  INFO ssh:   - Host: 127.0.0.1
>  INFO ssh:   - Port: 2222
>  INFO ssh:   - Username: ubuntu
>  INFO ssh:   - Password? true
>  INFO ssh:   - Key Path: []
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "9927de0f-8d56-4c35-9e4c-e1ad7d59f044", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "9927de0f-8d56-4c35-9e4c-e1ad7d59f044", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "9927de0f-8d56-4c35-9e4c-e1ad7d59f044", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "9927de0f-8d56-4c35-9e4c-e1ad7d59f044", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO ssh: SSH is ready!
>  INFO ssh: Execute:  (sudo=false)

### Actual behavior
Reconnecting to ssh over 5-6 minutes.

### Steps to reproduce
1. vagrant up

Killing the ssh-agent (`$ killall gnome-keyring-daemon && ssh-agent -k`) do nothing.

**Comment by chrisroberts** [comment]
My suspicion is that the box is not properly configured. Have you tested new versions of the box? Do you see the same behavior if you use the `hashicorp/precise64` box?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
