### ISSUE TITLE
Provision script not being reuploaded on Windows guest with WinRM

### ISSUE THREAD

**Issue by gsingh93** [mitchellh/vagrant#8137]
### Vagrant version
Vagrant 1.9.1

### Host operating system
macOS 10.12

### Guest operating system
Windows 7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "windows_7"
    config.vbguest.auto_update = false

    config.vm.communicator = "winrm"
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.provision :shell, :path => "provision.ps1"
end
```

### Debug output
https://hastebin.com/ogepefumul.rb

### Expected behavior
The latest provision file should have been executed. This works on Linux (with SSH) but not on Windows (with WinRM).

### Actual behavior
The old provision file was executed.

### Steps to reproduce
1. Create a file named `provision.ps1` containing the contents `echo "before"`
2. Run `vagrant up`, using the config provided above with a windows_7 box (other Windows boxes might also be fine). I built my Windows box using https://github.com/joefitzgerald/packer-windows. You'll see that the provisioning script prints "before".
3. Modify `provision.ps1` to say `echo "after"`
4. Run `vagrant reload --provision`. The provision script will print "before", not "after".
5. Open the running VM (I opened it directly from VirtualBox), open powershell. Run `rm /tmp/vagrant-shell.ps1`. Now go back to the host terminal and run `vagrant provision`. The new provision file gets uploaded and everything works.

**Comment by mdtisdall** [comment]
I'm also having the exact same problem. This seems to impact .bat files being used as shell provisioners as well.

**Comment by countergram** [comment]
Also having this issue. It affects 1.8.7 as well as 1.9.1. Going back to 1.7.2 fixes it.

**Comment by chrisroberts** [comment]
Using Vagrant 1.9.3 and a Win10 guest I am unable to reproduce this behavior. It looks like the winrm updates probably fixed this issue. If you are still experiencing this issue after upgrading, please reopen this issue or create a new one. Thanks!
