### ISSUE TITLE
Failed to create the VirtualBox object

### ISSUE THREAD

**Issue by zhoujun165** [mitchellh/vagrant#8139]
E:\>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["list", "hostonlyifs"]

Stderr: VBoxManage.exe: error: Failed to create the VirtualBox object!
VBoxManage.exe: error: Code E_NOINTERFACE (0x80004002) - No such interface suppo
rted (extended info not available)
VBoxManage.exe: error: Most likely, the VirtualBox COM server is not running or
failed to start.

### Vagrant version
1.6.3

### Virtualbox version
4.3

### operation system
window7 64bit

**Comment by chrisroberts** [comment]
Hi there. The versions of Vagrant and VirtualBox are extremely old. Please update them to recent releases. If the error still persists, please create a new issue and fill out all the information requested by the template. Thanks!
