### ISSUE TITLE
 Vagrant user doesn't seem to natively have sudo/root permissions

### ISSUE THREAD

**Issue by hotmeatballsoup** [mitchellh/vagrant#8149]
I'm trying to determine if there's a bug in Vagrant or in nginx.

I have the following `Vagrantfile`:

    Vagrant.configure("2") do |config|
      config.vm.box = "hashicorp/precise32"
      config.vm.network "private_network", ip: "10.0.1.7"
      config.vm.network :forwarded_port, guest: 8080, host: 9005
    end

So I run `vagrant up && vagrant ssh` and the server provisions and spins up. I want to *manually* install nginx on my new VM, so (per [the instructions](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-14-04-lts) for installing nginx on Ubuntu 14.04) I then run:

    sudo apt-get update
    sudo apt-get install nginx

nginx installs. I run `mkdir ~/mysite` and then I change its `/etc/nginx/nginx.conf` file to:

    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        sendfile        on;

        keepalive_timeout  65;

        server {
            listen       8080;
            server_name  localhost;

            location / {
                root   /home/vagrant/mysite;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
        }
        include servers/*;
    }

And then I run `nginx -s reload`. The error I receive is:

    vagrant@precise32:~$ nginx -s reload
    nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
    2016/12/22 00:36:48 [notice] 1442#0: signal process started
    2016/12/22 00:36:48 [alert] 1442#0: kill(890, 1) failed (1: Operation not permitted)

My understanding is that `vagrant` should be a user on the VM with sudo access and root permissions. No? Can anyone reproduce this and figure out why I'm unable to reload nginx with my custom `nginx.conf` file? If it can be determined to *not* be a Vagrant issue I'll happily take it up with the nginx folks or possibly StackOverflow. Thanks!

**Comment by jenhsun** [comment]
@hotmeatballsoup use provision (shell, chef, puppet or ansible), please. That's what vagrant all about. After that, you won't need to worried about your client. If something wrong, you can just destroy it and rebuild back to your custom setting by just `vagrant up`. No need to change your client setting again and again.
By the way, default ssh name is `vagrant`.  The nginx configuration should be in your host provision dir, not your client.

**Comment by richard-scott** [comment]
Did you try using it via sudo??

```
$ sudo nginx -s reload
```

Otherwise your 'vagrant' user doens't have permissions for it.

**Comment by jenhsun** [comment]
@richard-scott without provision, vagrant is useless. It's the key to @hotmeatballsoup problem.

**Comment by chrisroberts** [comment]
@hotmeatballsoup As @richard-scott pointed out, you need to use `sudo` as the vagrant user does not have access reload nginx directly. It must be done as root, thus you must use `sudo`:

```
$ sudo nginx -s reload
```

That is the expected behavior and not indicative of an issue with vagrant or nginx. Cheers!
