### ISSUE TITLE
Machine name "b2" treated as "default"

### ISSUE THREAD

**Issue by neykov** [mitchellh/vagrant#8152]
### Vagrant version
Vagrant 1.9.1

### Host operating system
macOS Sierra

### Guest operating system
Any

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
    config.vm.box="centos/7"
    config.vm.define "b"
    config.vm.define "b2"
    config.vm.define "good"
end
```

### Debug output
https://hastebin.com/uhixekuwub

### Expected behavior
```
$ vagrant status
Current machine states:

b                         not created (virtualbox)
b2                        not created (virtualbox)
good                      not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

### Actual behavior
```
$ vagrant status
Current machine states:

default                   running (virtualbox)
default                   running (virtualbox)
good                      not created (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

### Steps to reproduce
1. Use the Vagrantfile above
2. Execute "vagrant status" on it

**Comment by chrisroberts** [comment]
@neykov Hi! I've tried to reproduce this locally and have been unsuccessful. It seems like there may have been VMs already running when you made your Vagrantfile modifications. If you move this Vagrantfile into a new directory, do you experience the same behavior?

**Comment by neykov** [comment]
Can't reproduce it now. I probably had some leftover state from previous runs. Still would be nice if I had an error/warning shown instead of this undefined behaviour.

Feel free to close.
