### ISSUE TITLE
vagrant/box_metadata.rb:35:in `[]': no implicit conversion of String into Integer (TypeError)

### ISSUE THREAD

**Issue by 321dh** [mitchellh/vagrant#8155]
当windows10执行vagrant box add --name laravel/homestead  metadata.json --provider virtualbox时，这个问题在vgrant 1.9.1、1.9.0、1.8.5都出现错误.

### Vagrant version
1.8.5

### Host operating system
windows10

### Guest operating system
VirtualBox-5.1.12-112440-Win

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "base"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Debug output
D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_metadata.rb:35:in `[]': no implicit conversion of String into Integer (TypeError)
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_metadata.rb:35:in `block in initialize'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_metadata.rb:33:in `each'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_metadata.rb:33:in `map'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/box_metadata.rb:33:in `initialize'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/box_add.rb:486:in `new'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/box_add.rb:486:in `block in metadata_url?'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/box_add.rb:479:in `open'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/box_add.rb:479:in `metadata_url?'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/box_add.rb:81:in `block in call'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/box_add.rb:79:in `map'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/box_add.rb:79:in `call'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/box/command/add.rb:78:in `execute'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/box/command/root.rb:61:in `execute'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/cli.rb:42:in `execute'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:302:in `cli'
	from D:/Vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:174:in `<main>'

### Expected behavior
 vagrant box add --name laravel/homestead  metadata.json --provider virtualbox

### Actual behavior
error

### Steps to reproduce
1.run ' vagrant box add --name laravel/homestead  metadata.json --provider virtualbox'

### References
- ...

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
