### ISSUE TITLE
WinRM fails to configuring and enabling network interfaces

### ISSUE THREAD

**Issue by skvl** [mitchellh/vagrant#8156]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Linux

### Guest operating system
Windows 8, Windows 10

### Vagrantfile
```ruby
boxes = [
  {
    :box  => "mybox",
    :name => "mybox",
    :net  => "192.168.17.12",
    :communicator => "winrm"
  }
]

Vagrant.configure("2") do |config|
  boxes.each do |opts|
    config.vm.define opts[:name] do |box|
      box.vm.box = opts[:box]
      box.vm.hostname = opts[:name]
      box.vm.network  "private_network", ip: opts[:net]
      box.vm.communicator = opts[:communicator]
    end
  end
end
```

### Debug output
[Log](https://gist.github.com/skvl/8192675cb1350bb9a9190defec647811)

### Expected behavior
Vagrant should not fail.

### Actual behavior
Vagrant fails this step.

### Steps to reproduce
1. `vagrant up mybox`

**Comment by chrisroberts** [comment]
The root cause of the problem is that it is not properly detecting the guest as a windows guest. You can set it explicitly in your Vagrant file using: `box.vm.guest = :windows`. Cheers!
