### ISSUE TITLE
Can't install Vagrant Plugins Ubuntu 16.04

### ISSUE THREAD

**Issue by devloprs** [mitchellh/vagrant#8161]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version

1.8.5

### Host operating system
Ubuntu 16.10

### Guest operating system

none yet

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
@devloprs/vagrant_error.txt

### Expected behavior
Plugin Installed
I am trying to set up VVV I have not gotten past this prerequisite.
### Actual behavior

See Gist plugin failed

### Steps to reproduce
run 

vagrant plugin install vagrant-hostsupdater

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by kikitux** [comment]
@devloprs wheres the gist ?
