### ISSUE TITLE
Error installing vagrant plugins

### ISSUE THREAD

**Issue by aairey** [mitchellh/vagrant#8164]
I cannot install the vagrant plugins `reload` and `hosts`. Ouput below.

### Vagrant version
1.8.5

### Host operating system
Fedora 25

### Debug output
https://gist.github.com/aairey/41da4af73d783a361292084dafa78233

### Expected behavior
Plugin should get installed.

### Actual behavior
Bundler throws an error.

### Steps to reproduce
1. Install vagrant from OS repository
2. run `vagrant plugin install hosts`
3. The above error is shown.

### References
- #6494
- #2402

**Comment by chrisroberts** [comment]
Older versions of the installer had an improperly built ffi gem. If you can't upgrade your vagrant installation, reinstalling the ffi gem may resolve the issue. This might help if the latter is the case: https://github.com/mitchellh/vagrant/issues/6721#issuecomment-166915255 Cheers!
