### ISSUE TITLE
Vagrant Up after Vagrant SSH remotely?

### ISSUE THREAD

**Issue by agrahamwd** [mitchellh/vagrant#8174]
How can someone ssh into my box and run `vagrant up`?

I have vagrant installed on my machine. My coworker connects to the websites on my machine by editing his hosts file like I do. Today he came in earlier than me and my vagrant box was halted. He was unable to start it back up until I came in.

I don't want my coworkers to `vagrant up` on their machine, as it will create a new box with new IPs, nor do I want them messing with any sort of boxes on their machine. My computer should be the only one running vagrant, and I'd love to find a way for them to SSH into my box and run `vagrant up` without me so they can start working.

How do I go about doing this in the easiest way without multiple boxes being installed on multiple machines?

I should note that I'm new to SSH in general. Any help would be appreciated!

**Comment by Tatsh** [comment]
Make it so your co-workers can SSH into your machine but only run `vagrant` or even `vagrant up` with a script. In your ~/.ssh/authorized_keys:

```
command="cd DIRECTORY_WITH_VAGRANTFILE; /full/path/to/vagrant up",no-port-forwarding,no-x11-forwarding,no-agent-forwarding PUBLIC_KEY_VALUE COMMENT
```

Instead of `/full/path/to/vagrant` you can use a different executable file, and put something like:

```sh
#!/usr/bin/env bash
cd DIRECTORY_WITH_VAGRANTFILE
vagrant up
```

to restrict the command to only `vagrant up`.

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
