### ISSUE TITLE
Ubuntu 16.04: vagrant up --no-parallel errors

### ISSUE THREAD

**Issue by islamhathout** [mitchellh/vagrant#8178]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Ubuntu 16.04

I was following scrapy book that uses vagrant, but after running vagrant up --no-parallel there was an error each time i ran it the last error's number is "104" Is there any solutions ?

Moreover, i decided to follow the link:
https://atlas.hashicorp.com/lookfwd/boxes/scrapybook/versions/1.0.0/providers/virtualbox.box
 and download the file manually and i successfully downloaded virtualbox.box manually, but i have no idea of how to do with it.!!

I successfully downloaded it how should i work with it ?

Here is the info after running vagran up--no-parallel:
    web: Vagrant will now create or start a local VM to act as the Docker
    web: host. You'll see the output of the `vagrant up` for this VM below.
    web:  
    docker-provider: Box 'lookfwd/scrapybook' could not be found. Attempting to find and install...
    docker-provider: Box Provider: virtualbox
    docker-provider: Box Version: >= 0
    docker-provider: Loading metadata for box 'lookfwd/scrapybook'
    docker-provider: URL: https://atlas.hashicorp.com/lookfwd/scrapybook
    docker-provider: Adding box 'lookfwd/scrapybook' (v1.0.0) for provider: virtualbox
    docker-provider: Downloading: https://atlas.hashicorp.com/lookfwd/boxes/scrapybook/versions/1.0.0/providers/virtualbox.box

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄
