### ISSUE TITLE
Missing Gem `logging` for Windows Vagrant 1.9.1

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mitchellh/vagrant#8185]
### Vagrant version
1.9.0
1.9.1

### Last Known Working Version
1.8.7

### Host operating system
Windows

### Debug output
```
Vagrant experienced a version conflict with some installed plugins!
This usually happens if you recently upgraded Vagrant. As part of the
upgrade process, some existing plugins are no longer compatible with
this version of Vagrant. The recommended way to fix this is to remove
your existing plugins and reinstall them one-by-one. To remove all
plugins:

    rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems

The error message is shown below:

Could not find gem 'logging (>= 1.6.1, ~> 1.6) x86-mingw32', which is required by gem 'vagrant (= 1.6.3) x86-mingw32', in any of the sources.
```

`--debug` give NO extra information, when using `VAGRANT_LOG=info vagrant --debug`

### Expected behavior
vagrant works.

### Actual behavior
vagrant complains about a missing gem even after using the command shown for removing files.

### Steps to reproduce
1. Install 1.9.1 on Windows
2. Try using `vagrant`

**Comment by kikitux** [comment]
Hello

Not sure from where, but its seem something hardcoded to vagrant 1.6.3 on that output.

Can you ensure you are on current version:

```
vagrant version
vagrant plugin list
```

And please try with precise64 box.

```
mkdir precise64
cd precise64
vagrant init -m hashicorp/precise64
vagrant up
```

**Comment by ElvenSpellmaker** [comment]
@kikitux Sorry I wasn't alerted of a reply to this, I decided to uninstall vagrant but noticed a _ton_ of files left by the installer, after clearing those the new version seems to start working... Perhaps the uninstaller isn't clearing everything?
