### ISSUE TITLE
Issues with VBOX and Windows Server Audio 

### ISSUE THREAD

**Issue by beaudryj** [mitchellh/vagrant#8186]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.9.1
### Host operating system
Windows Server 2016

### Guest operating system
Windows Server 2016 

### Notes

I have found that my `Vagrant Up`s have been getting locked being run as the system user due to an issue with the system user not having audio enabled on the host machine and then VBOX seems to error because it has issues with connecting to the host audio. Is there a way to get around this, or is there a way in my vagrant file to specify a way to disable audio ?

**Comment by kikitux** [comment]
Hello

The guest VM should not have USB/Audio, etc

If updating the base box is not an option, you can use Vagrant capability to run VBoxManage commands. Those are run before the machine is started, so can be used to configure the VM.

The process is a bit of trial error, so please use this as general instructions.

run `VBoxManage list vms`

get information about the VM you want to update, grab the uuid.

then run:
`VBoxManage showvminfo <uuid>`

That will show you all the configuration about the vm.

Then you can tune this like:
`VBoxManage modifyvm uuid <option>`

In your case:
`VBoxManage modifyvm eb0e3b14-df11-411e-8843-cdcaf7267ec0 --audio none`

this becames:

```ruby
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--audio", "none"]
end
```

**Comment by kikitux** [comment]
Feel free to open if you think this is a bug, otherwise, happy to follow up over the mailing list.

**Comment by beaudryj** [comment]
good to know 
```ruby
config.vm.provider "virtualbox" do |v|
  v.customize ["modifyvm", :id, "--audio", "none"]
end
```

Also the issue turned out to be I needed to force headless mode
