### ISSUE TITLE
Verify shell incorrectly uses host level shell for guest shell

### ISSUE THREAD

**Issue by taliesins** [mitchellh/vagrant#8189]
We are making a check to see that shell is available in ssh. When we make this check we are not setting a shell to use.
https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/ssh/communicator.rb#L139

This results in the following being called with `nil` parameter which results in us using `@machine.config.ssh.shell` for default shell on guest.
https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/ssh/communicator.rb#L461

So if I am on a Windows machine I should set the `config.ssh.shell` to something like `cmd`. Now when I connect to a vm running FreeBsd, the value that should be used is `sh` but we are currently using `cmd`.

This value needs to be exposed as another configuration property that can be declared at `config.vm.ssh.shell vm` level and not at `config.ssh.shell` host level. There are a few people that run multiple vms with different operating systems (different shells) in the same vagrant file.

My current hack work around is to use `if execute("", error_check: false, shell: " ") != 0` but this is not ideal, as it only tests the default shell.

**Comment by kikitux** [comment]
How are you connecting to Windows?

Vagrant use whats available once the connection happen.

ie. if you use ssh and gets into a cmd.exe

then bat works
if you want powershell you can wrap a call.

**Comment by taliesins** [comment]
@kikitux hi :)

I am on a Windows host connecting to FreeBsd guest.

When you ssh into FreeBsd you would expect to use sh shell via ssh. At the moment vagrant is sshing in and using the default shell then attempting to run cmd as I configured ssh.shell=cmd

It is a happy coincidence that this works in most places. Default is to use bash. So host will ssh into guest and use default shell of guest to run command via bash command wrapper.

There are other places where the variable is correctly used for settings on host. It should not be used on the guest for anything.

Am I missing something? Your statement above is that it uses default shell of guest and does not use a wrapper around commands. I thought wrapper adds bash (and sudo if it's specified) to your command, when nil is passed in for shell. See line 461 (linked above).

**Comment by kikitux** [comment]
hello.

Sorry, I went to assume you were referring to provisioning.

So, in vagrant you have:

```

config.ssh.shell - The shell to use when executing SSH commands from Vagrant. By default this is bash -l. Note that this has no effect on the shell you get when you run vagrant ssh. This configuration option only affects the shell to use when executing commands internally in Vagrant.
```

that is to tell vagrant what shell to use when vagrant connects to the guest.

Can you test with `sh -l` if the default is not working


For multi machine, can you share a sample Vagrantfile that shows the issue?

I personally haven't had the need to have a multi-os multi-machine setup, so a repro case will help.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
