### ISSUE TITLE
Bad SSL cert for atlas.hashi.co

### ISSUE THREAD

**Issue by nyov** [mitchellh/vagrant#8197]
While trying to figure out why `vagrant box add "hashicorp/precise64"` wouldn't work for me, I found through tcpdump that vagrant tries to access `atlas.hashi.co`, not `atlas.hashicorp.com`:

```
$ vagrant box add hashicorp/precise64
==> box: Box file was not detected as metadata. Adding it directly...
A name is required when adding a box file directly. Please pass
the `--name` parameter to `vagrant box add`. See
`vagrant box add -h` for more help.

$ vagrant -v
Vagrant 1.9.0
```

Opening that URL in a browser or through curl, I get a certificate error.

```
$ curl https://atlas.hashi.co/hashicorp/boxes/precise64
curl: (51) SSL: certificate subject name (*.hashicorp.com) does not match target host name 'atlas.hashi.co'
```

**Comment by chrisroberts** [comment]
@nyov Would you please create a gist of the output from:

```
$ vagrant box add hashicorp/precise64 --provider virtualbox --debug
```

Thanks!

**Comment by nyov** [comment]
Ah, that `--debug` command should be documented. That would have helped.

I had a curl wrapper enabled that didn't work out with the arguments vagrant called it with.
My fault entirely. And I noticed the url to hashi.co was only the IP reverse resolution of tcpdump.

Sorry for the noise.
(But adding that `--debug` command to the cli help output would be nice)
