### ISSUE TITLE
Checking for newer version of Vagrant and VirtualBox

### ISSUE THREAD

**Issue by szabgab** [mitchellh/vagrant#8199]
When running `vagrant up` it would be nice if we got a report about newer versions of Vagrant itself and if possible also newer versions of VirtualBox (or whatever provider is being used).

I used to have Vagrant 1.7.4 on OSX and while I was constantly reminded that I could upgrade 
the box to a newer version of 'ubuntu/xenial64' I just realized I have not upgraded either Vagrant of VirtualBox for a while. It would be nice to get a reminder for that too.

**Comment by kikitux** [comment]
Hello @szabgab 

`vagrant version` can be used to track that, but not for virtualbox.

Depending on your host os, you can use the OS features to track packages repos.

VirtualBox have repos available for RPM and DEB based linux.
ie:
http://askubuntu.com/questions/276661/how-i-can-properly-update-virtualbox-to-the-latest-version
