### ISSUE TITLE
Box not found

### ISSUE THREAD

**Issue by w9n** [mitchellh/vagrant#8203]
Hello,
i created a box but Vagrant keeps telling me it does not exist. I do not see any difference to other working boxes. I used this describtion to create a qcow2 box from the official coreos raw disk https://github.com/vagrant-libvirt/vagrant-libvirt/tree/master/example_box

### Vagrant version
Vagrant 1.9.1

### Host operating system
arch linux

### Guest operating system
coreos 

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "w9n/coreos"
  config.vm.box_url = "https://atlas.hashicorp.com/w9n/coreos"
end

### Debug output
https://gist.github.com/w9n/a19b17f53ca2d04d2f742e35a46da9b7

### Expected behavior
box should run.

### Actual behavior
box is not found.
-->
$ vagrant box list
w9n/coreos    (libvirt, 1)

### Steps to reproduce
https://atlas.hashicorp.com/w9n/boxes/coreos
vagrant init w9n/coreos

**Comment by kikitux** [comment]
Hello

Can you try like this:

```Vagrant.configure("2") do |config|
config.vm.box = "w9n/coreos"
end
```

**Comment by w9n** [comment]
Hi @kikitux, same output. I managed to work around by creating a new box from the coreos production iso and packer, but i still would like to know whats wrong here.

```
$ vagrant up --provider libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Uploading base box image as volume into libvirt storage...
The box 'w9n/coreos' does not exist. Please double check and
try again. You can see the boxes that are installed with
`vagrant box list`.

$ vagrant box list
w9n/coreos                    (libvirt, 1)
```
This is my deployment script
```
curl https://alpha.release.core-os.net/amd64-usr/current/coreos_production_qemu_image.img.bz2 >coreos_production_qemu_image.img.bz2

bzip2 -d coreos_production_qemu_image.img.bz2
qemu-img convert -f raw -O qcow2 coreos_production_qemu_image.img coreos_production_qemu_image.qcow2
tar cvf coreos_qemu.box ./metadata.json ./Vagrantfile ./coreos_production_qemu_image.qcow2
```
metadata.json
```
{
  "provider"     : "libvirt",
  "format"       : "qcow2",
  "virtual_size" : 16 
}
```
Vagrantfile
```
# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.connect_via_ssh = false
    libvirt.username = "root"
    libvirt.storage_pool_name = "default"
  end
end
```

**Comment by kikitux** [comment]
Hello @w9n
This does work me.

```
vagrant up --provider libvirt
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
Bringing machine 'test_vm' up with 'libvirt' provider...
==> test_vm: Box 'w9n/coreos' could not be found. Attempting to find and install...
    test_vm: Box Provider: libvirt
    test_vm: Box Version: >= 0
==> test_vm: Loading metadata for box 'w9n/coreos'
    test_vm: URL: https://atlas.hashicorp.com/w9n/coreos
==> test_vm: Adding box 'w9n/coreos' (v1) for provider: libvirt
    test_vm: Downloading: https://atlas.hashicorp.com/w9n/boxes/coreos/versions/1/providers/libvirt.box

```

Commands I did use on ubuntu xenial:

- enabled deb-src on sources.list

```
sudo apt-get update
sudo apt-get build-dep ruby-libvirt
sudo apt-get install qemu libvirt-bin 
sudo reboot
```


 vagrant plugin install vagrant-libvirt
