### ISSUE TITLE
Vagrant can't support non-ASCII name network interface in OSX

### ISSUE THREAD

**Issue by andrewwutw** [mitchellh/vagrant#8207]
In OSX, if I set static IP address in Vagrantfile, vagrant will ask me which network interface to use when running "vagrant up".
If I choose a network interface, whose name is not in ASCII (in my case, the interface name is in Traditional Chinese), vagrant will report error and quit.

Error message :

```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20160406.0.0'. The latest is version '20161214.0.1'. Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set network interfaces...
==> default: Available bridged network interfaces:
1) en4: Thunderbolt 乙太網路
2) en0: Wi-Fi (AirPort)
3) en1: Thunderbolt 1
4) en2: Thunderbolt 2
5) bridge0
6) p2p0
7) awdl0
==> default: When choosing an interface, it is usually the one that is
==> default: being used to connect to the internet.
    default: Which interface should the network bridge to? 1
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
/opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/subprocess.rb:28:in `encode': "\xE4" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```

(More messages are omitted, see Debug Output)

The first network interface is "1) en4: Thunderbolt 乙太網路". Its name is not ASCII. ("乙太網路" means ethernet.)

This is my screen capture of my OS X system preferences->network :

<img width="780" alt="2017-01-10 11 37 15" src="https://cloud.githubusercontent.com/assets/4443713/21993631/c8eb0a1c-dc56-11e6-9dfe-fc4a4ff9b9bc.png">

Vagrant version 1.6.5 doesn't have this problem. but newer version has.

### Vagrant version
Vagrant 1.9.1

### Host operating system
10.12.2 (macOS Sierra)

### Guest operating system
Linux. But it is not important here because this bug happens before loading guest OS.

### Vagrantfile

```
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  # static IP address.
  config.vm.network "public_network", ip: "192.168.0.197", netmask: "20"
end
```

### Debug output
https://gist.github.com/andrewwutw/43539c770429161234dcdd67b2b44a54

**Comment by chrisroberts** [comment]
Fixed via #8385
