### ISSUE TITLE
Unable to start vagrant on Win8.1 laptop 

### ISSUE THREAD

**Issue by jeremyliu123** [mitchellh/vagrant#8209]
I just start to use vagrant. I followed default installation in C:\HashiCorp\Vagrant on my laptop. After reboot, the Vagrant/bin folder just become empty. I'm not able to use vagrant.

I tried many times with different versions 1.9.1, 1.9.0, 1.8.1 and other installation path. But same issue. 

Anybody helps me please!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by chrisroberts** [comment]
Do you currently have any version of Vagrant installed? Is the entire directory empty, or just the bin directory? Did the installations complete successfully?

**Comment by jeremyliu123** [comment]
Thanks for your response Mitchellh.

I currently have vagrant_1.9.1 installed. Only bin folder is empty. I would say it’s successful since no error reported and it’s straightforward.

The computer is in a domain. Not sure whether it’s realted.

Regards,
Jeremy

**Comment by chrisroberts** [comment]
Do the rest of the installation files still exist within `C:\HashiCorp\Vagrant\embedded` ?

**Comment by jeremyliu123** [comment]
Yes, they are.

**Comment by chrisroberts** [comment]
I have not been able to reproduce this behavior on install. If you install the latest Vagrant release, do you still see the same behavior?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
