### ISSUE TITLE
vagrant plugin install not working properly in 1.9.1

### ISSUE THREAD

**Issue by amontalban** [mitchellh/vagrant#8210]
### Vagrant version
```
Andres-MacBook-Pro:vagrant-hostmanager andres$ vagrant version
Installed Version: 1.9.1
Latest Version: 1.9.1
 
You're running an up-to-date version of Vagrant!
```
### Host operating system
OSX El Capitan

### Expected behaviour
I want to install a custom plugin from custom location https://packagecloud.io/amontalban/vagrant-hostmanager:

`vagrant plugin install vagrant-hostmanager --plugin-clean-sources --plugin-source https://packagecloud.io/amontalban/vagrant-hostmanager --verbose`

### Actual behaviour
```
Andres-MacBook-Pro:vagrant-hostmanager andres$ vagrant plugin install vagrant-hostmanager --plugin-clean-sources --plugin-source https://packagecloud.io/amontalban/vagrant-hostmanager --verbose
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Fetching: vagrant-hostmanager-1.8.5.gem (100%)
Installed the plugin 'vagrant-hostmanager (1.8.5)'!
```

This installs the plugin successfully but from Vagrant official sources, not custom. Additionally the `--verbose` option doesn't seem to work. I'm thinking that maybe is not parsing options properly because installing the gem file locally works.

**This is working fine in Vagrant 1.8.5**

```
root@test:~# vagrant plugin install vagrant-hostmanager --plugin-clean-sources --plugin-source https://packagecloud.io/amontalban/vagrant-hostmanager --verbose
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Fetching gem metadata from https://packagecloud.io/amontalban/vagrant-hostmanager/..
Fetching version metadata from https://packagecloud.io/amontalban/vagrant-hostmanager/.
Resolving dependencies...
Using builder 3.2.2
Using bundler 1.12.5
Using ffi 1.9.14
Using erubis 2.7.0
Using hashicorp-checkpoint 0.1.4
Using httpclient 2.8.0
Using i18n 0.7.0
Using rb-fsevent 0.9.7
Using ruby_dep 1.3.1
Using little-plugger 1.1.4
Using log4r 1.1.10
Using multi_json 1.12.1
Using micromachine 1.1.0
Using mime-types 1.25.1
Using mini_portile2 2.0.0
Using mini_portile2 2.0.0
Using net-ssh 3.0.2
Using nori 2.6.0
Using rubyntlm 0.6.0
Using rubyzip 1.2.0
Using wdm 0.1.1
Using vagrant-cachier 1.2.1
Installing vagrant-hostmanager 1.8.5
Using vagrant-nfs_guest 0.1.8
Using gyoku 1.3.1
Using childprocess 0.5.9
Using gssapi 1.2.0
Using rb-inotify 0.9.7
Using rb-kqueue 0.2.4
Using logging 2.1.0
Using vagrant-vbguest 0.11.0
Using rest-client 1.6.9
Using nokogiri 1.6.7.1
Using net-scp 1.1.2
Using net-sftp 2.1.2
Using listen 3.1.5
Using winrm 1.8.1
Using vagrant-share 1.1.5
Using winrm-fs 0.3.2
Using vagrant 1.8.5
Installed the plugin 'vagrant-hostmanager (1.8.5)'!
```

### Steps to reproduce
1. Install Vagrant 1.9.1
2. Run `vagrant plugin install vagrant-hostmanager --plugin-clean-sources --plugin-source https://packagecloud.io/amontalban/vagrant-hostmanager --verbose`

**Comment by chrisroberts** [comment]
Hi! The `--debug` flag is likely what you're looking for, not `--verbose` to get more output on the install process. If you can link a gist of the output generated with the `--debug` flag, that would be great!

**Comment by amontalban** [comment]
Hi @chrisroberts,

Thanks for the reply, thanks for the `--debug` flag I guess the help for `vagrant plugin install` needs to be updated because in prior versions I used `--verbose` and gave me at list where it was downloading it from.

Here is the output: https://gist.github.com/amontalban/67983d91625b5ab56ef6647918fb624f

Thanks!

**Comment by amontalban** [comment]
Hi @chrisroberts,

Do you have any update on this?

Thanks!
