### ISSUE TITLE
Relative Synced Folders should  be relative to the Vagrantfile location

### ISSUE THREAD

**Issue by aidanharris** [mitchellh/vagrant#8211]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Antergos Linux

### Guest operating system
boxcutter/centos73

### Vagrantfile
N/A

### Debug output
https://gist.github.com/aidanharris/401426dc31483698edaf55aa53e6d74f

### Expected behavior
Relative synced folders should be relative to the Vagrantfile location

### Actual behavior
What actually happened? - See debug output

### Steps to reproduce
1. Create a Vagrantfile with relative synced folders
2. `Cd` to a different directory inside the directory your Vagrantfile resides.
3. Do a `vagrant up`

### References
I'm unsure if there are any existing issues relevant to this, as a search turned up empty.

**Comment by aidanharris** [comment]
Having just checked again, it was this line in my Vagrantfile that was causing the issue:

`config.vm.provision "file", source: "a/folder/another_folder/a-file.txt", destination: "/tmp/a-file.txt"`

It might not be related to synced folders at all...

**Comment by chrisroberts** [comment]
The error looks like the result of a temporary value used within the Vagrantfile for testing or as a place holder. I'm going to close this issue for now, but if you are still experiencing the problem, please feel free to re-open and include the Vagrantfile causing the problem and the full debug output using the referenced Vagrantfile. Thanks!
