### ISSUE TITLE
vagrant up (please help)

### ISSUE THREAD

**Issue by chipka777** [mitchellh/vagrant#8212]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Windows 7 x64

### Guest operating system
hashicorp/precise64

### Vagrantfile
https://gist.github.com/chipka777/5405fc939ba8a49fd0dda8c69da897dd

### Debug output
https://gist.github.com/chipka777/73c91fb1a5152bd418609f8593166016
### Expected behavior

first run Vagrant

### Actual behavior
Vagrant no downloads boxes.

### Steps to reproduce
1. `vagrant init hashicorp/precise64`
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
2. `vagrant up`
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorp/precise64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'hashicorp/precise64'
    default: URL: https://atlas.hashicorp.com/hashicorp/precise64
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: https://atlas.hashicorp.com/hashicorp/precise64
Error: Failed writing body (0 != 1063)

### References

I could not find in the search help.

**Comment by chrisroberts** [comment]
This looks to be an path encoding issue based on the username.

**Comment by chrisroberts** [comment]
Fixed via #8385
