### ISSUE TITLE
vagrant up get the issue "adduser: invalid user name 'vagrant" (Please help)

### ISSUE THREAD

**Issue by bichdieu110** [mitchellh/vagrant#8217]
Hello,
Please help me out this issue

### Vagrant version
Vagrant 1.9.1

### Host operating system
windows 8.1

### Guest operating system
centos-7.1

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
yaml = YAML.load_file('admin-tools/app-provisioning/config/config.yml')

Vagrant.configure(2) do |config|
  ## vagrant-vbguest
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  ## https://atlas.hashicorp.com/bento/
  config.vm.box = "bento/centos-7.1"
  ## Local IP
  config.vm.network :private_network, ip: yaml["env"]["dev"]["local_ip"]
  ## Public Network
  if RUBY_PLATFORM =~ /darwin/  ## Mac
    interface_list = %x(VBoxManage list bridgedifs)
    interface = /Name: +(.*#{"Wi-Fi"}.*)/
  elsif RUBY_PLATFORM =~ /i386-mingw/  ## Windows
    interface_list = %x("C:\\Program Files\\Oracle\\VirtualBox\\VBoxManage.exe" list bridgedifs)
    interface = /Name: +(.*#{"Wireless"}.*)/
  end
  if interface_list =~ interface
    config.vm.network :public_network, bridge: $1
  end
  ## DNS
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
  end
  ## Hostname
  config.vm.hostname = yaml["env"]["dev"]["nginx"]["vhost"]
  ## vagrant-cachier
  #if Vagrant.has_plugin?("vagrant-cachier")
  #  config.cache.scope = :box
  #  config.cache.enable :yum
  #end
  ## Synced Folder
  config.vm.synced_folder ".", "/vagrant",
    id: 'vagrant-root',
    create: true,
    disabled: false,
    mount_options: ['dmode=777' ,'fmode=777']
  ## Provision
  config.vm.provision "shell",
    path: "admin-tools/app-provisioning/run.sh",
    args: ["--env", "dev"],
    privileged: true
end

```

### Debug output
https://github.com/bichdieu110/vagrant/issues/1
This is the config.yml file: https://github.com/bichdieu110/vagrant/issues/2

### Expected behavior
vagrant up success!

### Actual behavior
'=> default: adduser: invalid user name 'vagrant
==> default: /tmp/vagrant-shell(133) "tee -a "${LOG_DIR}/provisioning.log""
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
