### ISSUE TITLE
Issues with vagrant box add laravel/homestead command on Ubuntu

### ISSUE THREAD

**Issue by goodnesskay** [mitchellh/vagrant#8221]
I have issues installing laravel homestead on my Ubuntu os.

`The box 'laravel/homestead' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/laravel/homestead"]
Error: Couldn't resolve host 'atlas.hashicorp.com'`

**Comment by chrisroberts** [comment]
This looks like a local DNS resolution error. Check your local networking configurations and validate you have proper DNS servers configured. Cheers!

**Comment by goodnesskay** [comment]
Thanks @chrisroberts
