### ISSUE TITLE
Vagrant with VMware workstation fails to mount a shared folder

### ISSUE THREAD

**Issue by jdonofrio728** [mitchellh/vagrant#8222]
I'm building a custom RHEL72 box for internal use, however I can't seem to get the shared folders working correctly so that vagrant up works. Any instructions would be appreciated!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

```
jdonofrio@jdonofrio-Precision-7710:~/workspace/base-image$ vagrant version
Installed Version: 1.9.1
Latest Version: 1.9.1
 
You're running an up-to-date version of Vagrant!
```

### Host operating system
Kubuntu 16.04 LTS

### Guest operating system
RHEL 7.2

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "rhel72-base"
#  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "vmware_workstation" do |v|
    v.gui = true
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

https://gist.github.com/jdonofrio728/e308d2a33d42931bffe271f13dfa0726

### Expected behavior
Vagrant up would exit without any errors and with the default shared directory mounted on the guest.

### Actual behavior
Vagrant threw an error with the filesystem not available on the guest OS:
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "/home/jdonofrio/workspace/base-image/.vagrant/machines/default/vmware_workstation/4c4a0809-334d-407d-a235-f2a68c826879/rhel72-base-1.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr:

### References
https://github.com/mitchellh/vagrant/issues/6775

**Comment by chrisroberts** [comment]
Is there any relevant error information in the system logs on the guest or within the vm logs on the host (found in the local .vagrant directory `./.vagrant/machines/default/vmware_workstation/UUID/vmware.log`)?

**Comment by jdonofrio728** [comment]
Here another gist with the contents of vmware.log

https://gist.github.com/jdonofrio728/c430b07d34803f0631752ad6e8cdd5ea

I didn't really notice anything revealing.

**Comment by vkranjith** [comment]
Hi @chrisroberts,

Even I have the same Issue. My Vagrant version is 1.9.1 and VirtualBox is 5.1.14. I am using CentOS 7.0 for the guest machine.

Following was the issue error thrown when trying the use `vagrant up` command.
```
==> default: Attempting graceful shutdown of VM...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/ranjith
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

Do you think it's an issue with incompatibility between the Vagrant and VirtualBox versions that I am using? If so can you suggest me which one I should be changing?

**Comment by chrisroberts** [comment]
@jdonofrio728 I wonder if the base box is not properly configured. Does it have the open-vm-tools installed? If you use the `bento/centos-7.2` box do you see the same error?

**Comment by jdonofrio728** [comment]
@chrisroberts Not sure. I followed the directions provided with no luck. The bento box does work correctly. One thing that I noticed between the two is the version of open-vm-tools.

My base image has this:
VMware Tools daemon, version 10.0.5.52125 (build-3227872)

The bento box has this:
VMware Tools daemon, version 10.0.10.3275 (build-4301679)

The centos repositories latest version is the one that I have installed. Not sure how the bento box is being built, but I suspect its manually installing a newer version. What do you think?

**Comment by chrisroberts** [comment]
@jdonofrio728 Perhaps check the logs on the guest and see if there is anything relevant? Perhaps an initialization error is causing the failure.

Are you using the latest version of the vagrant-vmware-workstation plugin? I'll see if I can throw something together similar to your box and try to repro the behavior.

**Comment by chrisroberts** [comment]
The centos setup process for images is still a bit of a pain. You can find more information about it in chef/bento#747

Cheers!
