### ISSUE TITLE
Constant error: box could not be found or could not be access in the remote catalog

### ISSUE THREAD

**Issue by dcarter53** [mitchellh/vagrant#8223]
### Vagrant version
PS C:\Windows\system32> vagrant -v
Vagrant 1.9.1
PS C:\Windows\system32>

### Host operating system
Windows 10

### Guest operating system
windows 2008 r2 (metasploitable)

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base configuration for the VM and provisioner
  config.vm.box = "metasploitable3"
  config.vm.hostname = "metasploitable3"
  config.vm.communicator = "winrm"

  config.vm.network "private_network", type: "dhcp"

  # Install Chocolatey
  config.vm.provision :shell, path: "scripts/installs/chocolatey.cmd"
  config.vm.provision :reload # Hack to reset environment variables

  # Install BoxStarter
  config.vm.provision :shell, path: "scripts/installs/install_boxstarter.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Install 7zip
  config.vm.provision :shell, path: "scripts/chocolatey_installs/7zip.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Adjust password policy
  config.vm.provision :shell, path: "scripts/configs/apply_password_settings.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Add users and add to groups
  config.vm.provision :shell, path: "scripts/configs/create_users.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - Unpatched IIS and FTP
  config.vm.provision :shell, path: "scripts/installs/setup_iis.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/setup_ftp_site.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - Setup for Apache Struts
  config.vm.provision :shell, path: "scripts/chocolatey_installs/java.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/chocolatey_installs/tomcat.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :reload # Hack to reset environment variables
  config.vm.provision :shell, path: "scripts/installs/setup_apache_struts.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - Setup for Glassfish
  config.vm.provision :shell, path: "scripts/installs/setup_glassfish.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/start_glassfish_service.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - Jenkins (1.8)
  config.vm.provision :shell, path: "scripts/installs/setup_jenkins.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - Wordpress and phpMyAdmin
  # This must run after the WAMP setup.
  config.vm.provision :shell, path: "scripts/chocolatey_installs/vcredist2008.bat" # Visual Studio 2008 redistributable is a requirement for WAMP
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/install_wamp.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/start_wamp.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/install_wordpress.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - JMX
  config.vm.provision :shell, path: "scripts/installs/install_openjdk6.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/setup_jmx.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - Rails Server
  config.vm.provision :shell, path: "scripts/installs/install_ruby.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/install_devkit.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/install_rails_server.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/setup_rails_server.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614
  config.vm.provision :shell, path: "scripts/installs/install_rails_service.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - WebDAV
  # This must run after the WAMP setup.
  config.vm.provision :shell, path: "scripts/installs/setup_webdav.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - MySQL
  config.vm.provision :shell, path: "scripts/installs/setup_mysql.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - ManageEngine Desktop Central
  config.vm.provision :shell, path: "scripts/installs/install_manageengine.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - Axis2
  # This must run after the Apache Struts setup.
  config.vm.provision :shell, path: "scripts/installs/setup_axis2.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - Common backdoors
  config.vm.provision :shell, path: "scripts/installs/install_backdoors.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - SNMP
  config.vm.provision :shell, path: "scripts/installs/setup_snmp.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Configure Firewall to open up vulnerable services
  case ENV['MS3_DIFFICULTY']
  when 'easy'
    config.vm.provision :shell, path: "scripts/configs/disable_firewall.bat"
  else
    config.vm.provision :shell, path: "scripts/configs/configure_firewall.bat"
  end

  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Vulnerability - ElasticSearch
  # This must run after the firewall rules, because it needs to make some HTTP requests in order to
  # set up the vulnerable state.
  config.vm.provision :shell, path: "scripts/installs/install_elasticsearch.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614

  # Configure flags
  config.vm.provision :shell, path: "scripts/installs/install_flags.bat"
  config.vm.provision :shell, inline: "rm C:\\tmp\\vagrant-shell.bat" # Hack for this bug: https://github.com/mitchellh/vagrant/issues/7614a
end

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
I am in the process of setting up metasploitable3.  However, I am having issues with getting the box to "add" correctly.  Getting same error:
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> vagrant box add .\windows_2008_r2_virtualbox.box --name=metasploitable3
The box '.\windows_2008_r2_virtualbox.box' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/./windows_2008_r2_virtualbox.box"]
Error: The requested URL returned error: 404 Not Found
PS C:\Windows\system32>

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
It looks like you are attempting to add a local box and are providing an incorrect path. Validate the path you are providing exists and is correct. If so, please include a gist of the output from the `vagrant box add` command with `--debug` enabled. Thanks!

**Comment by dcarter53** [comment]
[vagrant-error-output.txt](https://github.com/mitchellh/vagrant/files/728521/vagrant-error-output.txt)

I have attached the output after I changed the source

**Comment by chrisroberts** [comment]
The issue is that you have a space in the path which is not escaped causing an incorrect path to be used as for the download. Update your command to:

```
vagrant box add "c:\Users\D. Carter\metasploitable3\windows_2008_r2_virtualbox.box" --name=metasploitable3
```

Cheers!
