### ISSUE TITLE
Vagrant private_network eth1 down on startup

### ISSUE THREAD

**Issue by mlccapulong** [mitchellh/vagrant#8224]
Vagrant version: 1.9.1
Guest: CentOS 7
Host: Ubuntu 16.04
Virtualbox: 5.0.24

Hi. I'm having a problem setting a static IP on my vagrant machine. If I added a private_network and set an IP, the eth1 on the guest is down and eth2 is up with an IP(not the IP that I set). But when I remove private_network settings and just run the machine with a public_network, eth1 is up with a dynamic IP and eth2 is removed.

Here's my Vagrantfile:

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.10.10"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
  end

  config.ssh.insert_key = false
  config.ssh.private_key_path = "/home/marccaps/.vagrant.d/insecure_private_key"

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.githubusercontent.com/mlccapulong/61babbcc1dd11b98ebfb9cebb89b504c/raw/d8a4211c4542c3cf886da9425d456a253bd554a6/vagrant.log

**Comment by chrisroberts** [comment]
This is fixed on master via: #8148. Thanks for the report!
