### ISSUE TITLE
Vagrant 1.9.1 error in syncing folder

### ISSUE THREAD

**Issue by naumanbasheer** [mitchellh/vagrant#8227]
Hello, 

I seem to be having an issue when spinning up the vagrant box after updating my virtual box. The error occurs when vagrant tries to sync a folder from the host machine. 

It works if that part of the vagrant file is commented out. 

Host OS - Mac OSX 10.12.2
Vagrant - 1.9.1
Virtualbox -  5.0.32
Puppet  - 3.6.2
VM OS - https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

Gist for the error : https://gist.github.com/naumanbasheer/f33a0f78297aeb6ecd73d1de72197c8d

**Comment by kikitux** [comment]
@naumanbasheer 

does this happen with `hashicorp/precise64` ?

Please reopen if you can reproduce with our box.
