### ISSUE TITLE
vagrant ssh doesn't work with Reflection ssh

### ISSUE THREAD

**Issue by sprintfalcon** [mitchellh/vagrant#8228]
Unable to use Reflection ssh with vagrant due to invalid command line -o option 'IdentitiesOnly'
Reflection_14.1.411, SSH protocols 1.5/2.0, Reflection SSC Crypto Module 2.0.40

### Vagrant version
Vagrant 1.7.4

### Host operating system
Windows 7

### Guest operating system
RHEL 7.2

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "RHEL-7-2-x64"
  config.vm.boot_timeout = 600
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "vmware_workstation" do |vmw|
 # Customize the amount of memory on the VM:
     vmw.memory = "1024"
  end
end
```

### Debug output
DEBUG subprocess: Exit status: 95
 INFO ssh: Invoking SSH: ssh ["vagrant@192.168.169.156", "-p", "22", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentitiesOnly=yes", "-i", "C:/vagrant/vm/rhel/.vagrant/machines/default/vmware_workstation/private_key"]
error: Invalid command line -o option 'IdentitiesOnly'

### Expected behavior
ssh to the guest

### Actual behavior
throws error

### Suggestions
Allow specifying the -o options in the Vagrant ssh command string

**Comment by kikitux** [comment]
hello

vagrant requires a full ssh executable to work, it seems there is no way to override the command to be used.
