### ISSUE TITLE
vagrant scp not finding machine on windows

### ISSUE THREAD

**Issue by axelabs** [mitchellh/vagrant#8239]
When attempting to use the scp plugin on Windows and using a full path to a local file, vagrant errors with: "The machine with the name 'C' was not found configured forthis Vagrant environment."

### Vagrant version
1.9.1

### Host operating system
Windows 10 Home
git version 2.11.0.windows.1
GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)

### Guest operating system
bento/centos-7.2

### Debug output
https://gist.github.com/axelabs/13d797b812285974f8aeeedc221c1736

### Expected behavior
me@win10desktop MINGW64 ~/Vagrant/centos7
$ vagrant.exe scp /c/Users/me/Downloads/file.zip :/tmp/
file.zip                                                                   100%

### Actual behavior
me@win10desktop MINGW64 ~/Vagrant/centos7
$ vagrant.exe scp /c/Users/me/Downloads/file.zip :/tmp/
The machine with the name 'C' was not found configured for
this Vagrant environment.

### Steps to reproduce
Attempt to copy any file by full path into the VM.

### Workaround
I was able to copy the file.zip into the Vagrant machine's directory and use:
$ vagrant.exe scp ./file.zip :/tmp/

**Comment by kikitux** [comment]
Hi @axelabs 

I am afraid vagrant-scp is not a core plugin, so is not much what we can do here.

could you try use relative path, maybe is a escape issue, etc.

But will be better if you open an issue on the plugin repo.

Thanks
