### ISSUE TITLE
Creating a 3rd private network causes box not to properly boot

### ISSUE THREAD

**Issue by adamgoucher** [mitchellh/vagrant#8242]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

Adams-MacBook-Pro:ports adamgoucher$ vagrant -v
Vagrant 1.9.1

### Host operating system
This is the operating system that you run locally.

OSX 10.12.3

### Guest operating system
This is the operating system you run in the virtual machine.

ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20170119.1.0"

  config.vm.box_check_update = false
  config.vbguest.auto_update = true

  config.vm.network :private_network, ip: '192.168.33.10'
  config.vm.network :private_network, ip: '192.168.33.11'
  config.vm.network :private_network, ip: '192.168.33.12'
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

https://gist.github.com/adamgoucher/f3929ffb54ef441db5276e2774b959b4

### Expected behavior
Box would boot, listening to 4 ip addresses (192.168.33.1, 192.168.33.10 - 12)

### Actual behavior
Box hangs trying to ssh into itself

### Steps to reproduce
1. Using the above Vagrantfile, boot. <hangs>
2. Comment out the .12 section, boot. <success>

**Comment by kikitux** [comment]
@adamgoucher Can you try with:
```
"hashicorp/precise64"
```

I wasn't able to reproduce with our box.

Not sure where the problem may be on xenial, but seems to be related to the box configuration on the first boot.

**Comment by adamgoucher** [comment]
The 'hashicorp/precise64' box worked. As did 'ubuntu/trusty64'.

But 'ubuntu/xenial64', and 'ubuntu/yakkety64' did not.

'ubuntu/wily64' was 404-ing.

**Comment by kikitux** [comment]
Would you agree that is more a box issue rather than a vagrant box?

If you need a xenial one, I can suggest `cbednarski/ubuntu-1604`

Thanks
