### ISSUE TITLE
Unable to disable linked clone for VMware box

### ISSUE THREAD

**Issue by atombender** [mitchellh/vagrant#8249]
My `Vagrantfile` has this:

```
      node.vm.box = 'phusion/ubuntu-14.04-amd64'
      node.vm.provider 'vmware_fusion' do |p|
        p.linked_clone = false
      end
```

However, when the machine is created, it is cloned and linked to the original Ubuntu VM; the above line does not disable the linking.

This means that when I `tar` up the final VM from the VMware folder to create a box, it refers to a master VM, so nobody else can install the box. I haven't tried including the master VM files, though. but surely that should not be necessary. Not least because I'm using a script that has worked, literally, for years: It uses `vmrun list` to find the location of the VMware files, then creates a `.box` from it. This linked cloning stuff breaks that, because the location returned by `vmrun list` only returns the clone.

---

VMware Fusion 7.1.1 on macOS 10.12.2. 

```
$ vagrant -v
Vagrant 1.9.1
$ vagrant plugin list
vagrant-share (1.1.6)
  - Version Constraint: > 0
vagrant-vmware-fusion (4.0.15)
  - Version Constraint: > 0
```

**Comment by chrisroberts** [comment]
I have a fix for this staged in the next release. Will update this issue (and close) once it's released. Cheers!

**Comment by chrisroberts** [comment]
Hi @atombender. Thanks for reporting this. It has been fixed in the 4.0.17 release of the plugin and can now be properly disabled.

Cheers!

**Comment by atombender** [comment]
Thanks!

**Comment by allaire** [comment]
@chrisroberts I think it doesn't work when I use a combination of the settings bellow:

```
    v.enable_vmrun_ip_lookup = false
    v.whitelist_verified = true
    v.linked_clone = false
```

removing `enable_vmrun_ip_lookup` made it works, otherwise it was hanging.
