### ISSUE TITLE
Snapshot could not be created while using libvirt as provider

### ISSUE THREAD

**Issue by codevulture** [mitchellh/vagrant#8254]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

Installed Version: 1.9.1
Latest Version: 1.9.1
 
You're running an up-to-date version of Vagrant!

### Host operating system
This is the operating system that you run locally.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04
Release:	16.04
Codename:	Xenial

### Guest operating system
This is the operating system you run in the virtual machine.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

### Vagrantfile
# Copy-paste your Vagrantfile here
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  VM_MEMORY    = ENV.fetch('VAGRANT_KURYR_VM_MEMORY', 12144).to_i
  VM_CPUS      = ENV.fetch('VAGRANT_KURYR_VM_CPUS', 3).to_i
  RUN_DEVSTACK = ENV.fetch('VAGRANT_KURYR_RUN_DEVSTACK', 'true')

  config.vm.hostname = 'devstack'

  config.vm.provider 'virtualbox' do |v, override|
    override.vm.box = ENV.fetch('VAGRANT_KURYR_VM_BOX', 'ubuntu/trusty64')
    v.memory        = VM_MEMORY
    v.cpus          = VM_CPUS
  end

  config.vm.provider 'parallels' do |v, override|
    override.vm.box = ENV.fetch('VAGRANT_KURYR_VM_BOX', 'boxcutter/ubuntu1404')
    v.memory        = VM_MEMORY
    v.cpus          = VM_CPUS
    v.customize ['set', :id, '--nested-virt', 'on']
  end

  config.vm.provider 'libvirt' do |v, override|
    override.vm.box = ENV.fetch('VAGRANT_KURYR_VM_BOX', 'yk0/ubuntu-xenial')
    v.memory        = VM_MEMORY
    v.cpus          = VM_CPUS
    v.nested        = true
    v.graphics_type = 'spice'
    v.video_type    = 'qxl'
    v.driver        = 'kvm'
  end

  #config.vm.synced_folder '../../devstack/', '/devstack'
  # For CentOS machines it needs to be specified
  config.vm.synced_folder '.', '/vagrant'

  #config.vm.provision :shell do |s|
  #  s.path = 'vagrant.sh'
  #  s.args = RUN_DEVSTACK
  #end

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  end

  conf
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.
Output:
https://gist.github.com/codevulture/8237ccd85f0dbb2e816ccb75dc697ef2

### Expected behavior
What should have happened?
snapshot should be created

### Actual behavior
What actually happened?
does not allowed to create snapshot

### Steps to reproduce
1.vagrant snapshot push/save

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
Hi! The libvirt support is provided via a Vagrant plugin, not Vagrant itself. You can find the plugin repository here: https://github.com/vagrant-libvirt/vagrant-libvirt

Cheers!

**Comment by codevulture** [comment]
Thanks for the reply, for using libvirt i have already installled vagrant  libvirt plugin. :)

**Comment by benjaesq** [comment]
Perhaps this issue was overlooked, I am unable to do snapshots of libvirt vagrant boxes.
