### ISSUE TITLE
Error in import_vm_xml.ps1 (missing string terminator)

### ISSUE THREAD

**Issue by manofearth** [mitchellh/vagrant#8255]
`vagrant up --provider=hyperv`

Threw error at step  "Creating and registering the VM..."
I have fixed it by renaming my virtual switch: it had space in name (and Cyrillic symbols, but I think the problem was in space symbol).

Script: import_vm_xml.ps1
Error: missing string terminator: '.

I suppose it is a bug

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by jwfang** [comment]
still got this error on 2.0.1

**Comment by dalton-lee** [comment]
i have a same question, and i found a reason! if you have a non-english environment, the win10 with Fall Creators Update,it may have a default switch with your own language in Hyper-V setting and you can create new switch one with english name,It's useful to me！hope can help you~

**Comment by dalton-lee** [comment]
a better way is to rename the switch FriendlyName use regedit.exe :)

**Comment by jwfang** [comment]
thanks @dalton-lee , it works for me.

the registry key is located at
`HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\vmsmp\parameters\SwitchList\C08CB7B8-9B3C-408E-8E30-5E16A3AEB444\FriendlyName`

**Comment by websafe** [comment]
@chrisroberts Still got this error on v. 2.0.2 with a Polish version of Windows 10, where the default switch is named "Przełącznik domyślny".

**Comment by chrisroberts** [comment]
@websafe Hi. Can you please open a new issue and fill out the requested information in the new issue template so we can properly track the issue. Thanks!
