### ISSUE TITLE
Permission denied @ rb_sysopen (when project in Yandex.Disk cloud service)

### ISSUE THREAD

**Issue by albrin** [mitchellh/vagrant#8256]
When my project is located in a folder that is synchronized with the cloud (Yandex.Disk) when you stop ($ vagrant halt) and restart ($ vagrant up), I get an error. But when the project is not located in the cloud folder is all right.

### Vagrant version
Installed Version: 1.9.1
Latest Version: 1.9.1

### Host operating system
Выпуск: Windows 10 Pro
Версия: 1607
Тип системы: 64-разрядная операционная система, процессор x64
Яндекс.Диск: Версия 1.4.14 от 26.01.2017 Сборка 5242

### Guest operating system
CentOS 7 (https://atlas.hashicorp.com/centos/boxes/7)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
```

### Debug output
https://gist.github.com/albrin/cfe545d1964fd8665a1300fc7a4875c8 (3 files)

### Expected behavior
Starts and provisions the vagrant environment.

### Actual behavior
After the second run, I get an error
```ruby
...
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:100:in `initialize': Permission denied @ rb_sysopen - D:/Cloud/YandexDisk/Projects/test-centos7-delete/.vagrant/machines/default/virtualbox/synced_folders (Errno::EACCES)
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:100:in `open'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:100:in `open'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:100:in `save_synced_folders'
...
```

### Steps to reproduce
1. $ vagrant up
2. $ vagrant halt
3. $ vagrant up

### References
I did not find.

**Comment by chrisroberts** [comment]
The issue appears to be with the yandex application that's providing the local file system interface. This is not something that I can replicate locally, and I do not see any evidence that Vagrant is the cause. I would suggest running Vagrant from a local file system. If you do find that Vagrant is not doing something correctly, please feel free to either reopen this issue, or create a new one. Thanks!
