### ISSUE TITLE
Vagrant share stops responding after 5-8 requests

### ISSUE THREAD

**Issue by timbroder** [mitchellh/vagrant#8257]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

Vagrant 1.9.1

### Host operating system
This is the operating system that you run locally.

macOS 10.12.2 (16C68)

### Guest operating system
This is the operating system you run in the virtual machine.

Ubuntu 14.04.4 LTS

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/ubuntu1404"

  config.vm.network "forwarded_port", guest: 80, host: 8889, auto_correct: true
  config.vm.network "forwarded_port", guest: 8200, host: 8200

  config.vm.network "private_network", ip: "192.168.20.20"

   config.vm.synced_folder ".", "/home/kidfund/sites/kidfund/current", id: "vagrant-root",
       type: "nfs"
       #owner: "vagrant",
       #group: "www-data",
       #mount_options: ["dmode=775,fmode=664"]

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
   end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

https://gist.github.com/timbroder/4f221b49635e5acd53811c20b14d5e8e

### Expected behavior
vagrant share to always accept and serve connections

### Actual behavior
vagrant share starts timing out after 3-5 requests. curl will time out. browsers sits at waiting

### Steps to reproduce
1. This started happening after I upgrade from 1.8.* to 1.9.*
2. start with: vagrant share --http 8889 --debug
3. hit my admin in browser using share url a few times
4. hit api endpoint from ios device a few times
5. both stop responding

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- I Upgraded Vagrant because of the issue I was having in #7768

**Comment by aaronhipple** [comment]
Same issue, host macOS 10.12.3 (16D32), guest CentOS 6.8

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
