### ISSUE TITLE
Strange behavior trigger after destroy

### ISSUE THREAD

**Issue by albrin** [mitchellh/vagrant#8262]
### Vagrant version
Installed Version: 1.9.1
Latest Version: 1.9.1

### Host operating system
Выпуск: Windows 10 Pro
Версия: 1607
Тип системы: 64-разрядная операционная система, процессор x64
Яндекс.Диск: Версия 1.4.14 от 26.01.2017 Сборка 5242

### Guest operating system
CentOS 7 (https://atlas.hashicorp.com/centos/boxes/7)

### Vagrantfile
```ruby
...
  # TODO Run always even when confirmation "no"
  config.trigger.after :destroy do
    info "Removing .vagrant folder..."
    run "rm -Rf .vagrant"
  end
...
```

### Debug output
```bash
D:\Projects\vagrant-centos7-lemp>vagrant destroy
==> default: Running triggers before destroy...
==> default: Dumping the database before halting or destroying the VM...
==> default: Executing remote command "bash /vagrant/assets/dump_bases.sh"...
==> default:
==> default: /vagrant/assets/dump_bases.sh: line 13: mysql: command not found
==> default: Remote command execution finished.
    default: Are you sure you want to destroy the 'default' VM? [y/N] N
==> default: The VM 'default' will not be destroyed, since the confirmation
==> default: was declined.
==> default: Running triggers after destroy...
==> default: Removing .vagrant folder...
==> default: Executing command "rm -Rf .vagrant"...
==> default: Command execution finished.
```

### Expected behavior
I expect that the commands will fail if you enter "N".

### Actual behavior
```bash
...
==> default: Removing .vagrant folder...
==> default: Executing command "rm -Rf .vagrant"...
...
```

### Steps to reproduce
1. vagrant up
2. vagrant destroy

### References
—

**Comment by chrisroberts** [comment]
Hi! The origin of this error is within the vagrant-triggers plugin, not Vagrant itself. Issues with the plugin should be directed to the plugin author: https://github.com/emyl/vagrant-triggers

Cheers!
