### ISSUE TITLE
Installing Ansible from the official repository instead of a PPA with an Ubuntu guest

### ISSUE THREAD

**Issue by jeremyn** [mitchellh/vagrant#8266]
According to the [Ansible Local provisioner documentation](https://www.vagrantup.com/docs/provisioning/ansible_local.html), with an Ubuntu guest, the provisioner installs Ansible from a PPA instead of from the official repository. Is it currently (Vagrant v1.9.1) possible to tell Vagrant to install Ansible from the official repository with an Ubuntu guest? If not, would you consider a pull request to add this ability?

**Comment by gildegoma** [comment]
@jeremyn Thank you for asking. 

This is correct that at the moment you "only" have two _very_ easy options for the Ansible setup on an Ubuntu guest:
* install the latest release from [Ansible's official PPA](https://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-ubuntu), or
* install the Ansible version of your choice by using the `pip` install mode

If you do want to install Ansible from the Ubuntu release apt repository (e.g. [2.0.0.2-2 for Ubuntu 16.04](http://packages.ubuntu.com/xenial/ansible)), you can do it the following way:
* Use a basic `shell` provisioner script to run the `apt-get install ansible`, then
* Use your `ansible_local` provisioner with `install` option set to `false`

I think that the current feature set is flexible enough, and meet the most frequent use cases. For this reason, I'd like to refuse this feature request. If you disagree, could you please give us more details about your needs and why/how this would really help in the future. Thanks!

**Comment by jeremyn** [comment]
I agree the first two options are easy, because those are the two options you can already configure with `install_mode`.

The workaround of using two provisioners and setting `install` to `false` is easy enough if you think of it. I didn't, instead I used the Shell provisioner by itself to mimic the Ansible Local provisioner as I describe in https://github.com/mitchellh/vagrant/issues/6793#issuecomment-278213226. Luckily I didn't completely waste this time because I also decided to use an older version of Vagrant and ran into the problem that issue #6793 is about, which made my alternate approach useful anyway.

I don't agree with the PPA being the default for Ubuntu, or how it's implemented. The UI gives no indication that it's installing from a PPA instead of the system repositories, it just says:

```
==> default: Running provisioner: ansible_local...
    default: Installing Ansible...
    default: Running ansible-playbook...
```

For security reasons I don't like using non-system-repositories stuff. Also Ansible is a moving target, for example every module at https://docs.ansible.com/ansible/modules_by_category.html flagged as "preview" might break in a new version. It is not a feature to me to not know what Ansible version I'm installing or that I might get breaking changes with an update.

Anyway, thanks for the response. I hope you'll reconsider the default behavior of installing from PPA.

**Comment by gildegoma** [comment]
@jeremyn Thank you very much for the additional details.

> The UI gives no indication that it's installing from a PPA instead of the system repositories

I agree, this documented, but not self-explanatory when using the tool. This could be improved in the future.

For the security concerns that you're raising, I defer to @chrisroberts. Indeed, PPA and pip installation modes are not providing the security level at all, but these sources are officially encourage by Ansible project itself. I don't know which "security guidelines" are recommended in the Vagrant project in general.
