### ISSUE TITLE
How can i test if API needs https?

### ISSUE THREAD

**Issue by csimpi** [mitchellh/vagrant#8267]
Hi guys,
I've searched for a day, but i can't find the solution.
I would like to accept push notifications from google calendar.
I have to share an url, what can provide REAL https connection.
I have a lot of virtual domains within vagrant install.

localtunnel doesnt works with virtualhosts some reason. I have the newest version vagrant, and localtunnel. If I don't use -l parameter, localtunnel works, but i can't reach the required website :(

Vagrant share can't provide real https connection. I've generated an ssl key with openssl and i've made ssl virtualhost file for apache, but it doesn't works, i get Bad Request. If i use my localhost with https it works.

So what should i do? :))
I would like ti reach my local vagrant virtualhost with https. Can i? Or i can't work with google api on vagrant?

https://developers.google.com/google-apps/calendar/v3/push

Thanks,
Peter

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
