### ISSUE TITLE
The issue while installing yii2 using vagrant

### ISSUE THREAD

**Issue by jithu121212** [mitchellh/vagrant#8271]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.9.1

### Host operating system
Linux Mint 18.1 Serena

### Guest operating system
Ubuntu 16.04

### Vagrantfile
Ruby
/home/d4/yii/yii2-app-advanced/Vagrantfile
# Copy-paste your Vagrantfile here
```
require 'yaml'
require 'fileutils'

domains = {
  frontend: 'y2aa-frontend.dev',
  backend:  'y2aa-backend.dev'
}

config = {
  local: './vagrant/config/vagrant-local.yml',
  example: './vagrant/config/vagrant-local.example.yml'
}

# copy config from example if local config not exists
FileUtils.cp config[:example], config[:local] unless File.exist?(config[:local])
# read config
options = YAML.load_file config[:local]

# check github token
if options['github_token'].nil? || options['github_token'].to_s.length != 40
  puts "You must place REAL GitHub token into configuration:\n/yii2-app-advanced/vagrant/config/vagrant-local.yml"
  exit
end

# vagrant configurate
Vagrant.configure(2) do |config|
  # select the box
  config.vm.box = 'bento/ubuntu-16.04'

  # should we ask about box updates?
  config.vm.box_check_update = options['box_check_update']

config.vm.provider 'virtualbox' do |vb|
   vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
    # machine cpus count
    vb.cpus = options['cpus']
    # machine memory size
    vb.memory = options['memory']
    # machine name (for VirtualBox UI)
    vb.name = options['machine_name']
  end

  # machine name (for vagrant console)
  config.vm.define options['machine_name']

  # machine name (for guest machine console)
  config.vm.hostname = options['machine_name']

  # network settings
  config.vm.network 'private_network', ip: options['ip']

  # sync: folder 'yii2-app-advanced' (host machine) -> folder '/app' (guest machine)
  config.vm.synced_folder './', '/app', owner: 'vagrant', group: 'vagrant'

  # disable folder '/vagrant' (guest machine)
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # hosts settings (host machine)
  config.vm.provision :hostmanager
  config.hostmanager.enabled            = true
  config.hostmanager.manage_host        = true
  config.hostmanager.ignore_private_ip  = false
  config.hostmanager.include_offline    = true
  config.hostmanager.aliases            = domains.values

  # provisioners
  config.vm.provision 'shell', path: './vagrant/provision/once-as-root.sh', args: [options['timezone']]
  config.vm.provision 'shell', path: './vagrant/provision/once-as-vagrant.sh', args: [options['github_token']], privileged: false
  config.vm.provision 'shell', path: './vagrant/provision/always-as-root.sh', run: 'always'

  # post-install message (vagrant console)
  config.vm.post_up_message = "Frontend URL: http://#{domains[:frontend]}\nBackend URL: http://#{domains[:backend]}"
end
```

### Debug output
https://gist.github.com/jithu121212/6b7378ef82b8ffe4ae775e557142efe9

### Expected behavior
to run yii2 app installed using vagrant

### Actual behavior
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
Looks like the interface on the box is not connected. See this comment for adjustments you can make in the Vagrantfile to connect it:

https://github.com/mitchellh/vagrant/issues/7648#issuecomment-235282382

Cheers!

**Comment by jithu121212** [comment]
still shows another error
---------------------------------------------
d4@sujith ~/yii/yii2-app-advanced $ vagrant up
Bringing machine 'y2aa' up with 'virtualbox' provider...
==> y2aa: Updating /etc/hosts file on active guest machines...
==> y2aa: Updating /etc/hosts file on host machine (password may be
required)...
==> y2aa: Machine already provisioned. Run `vagrant provision` or use the
`--provision`
==> y2aa: flag to force provisioning. Provisioners marked to run always
will still run.
==> y2aa: Running provisioner: shell...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
