### ISSUE TITLE
`gsub': incompatible character encodings, directory with accents

### ISSUE THREAD

**Issue by aclarembeau** [mitchellh/vagrant#8276]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.8.5

### Host operating system
Fedora 25 Workstation (in French)

### Guest operating system
Debian Jessie

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  # We need 2 extra interfaces besides the one from
  config.vm.network "private_network", ip: "10.0.0.1", auto_config: false
  config.vm.network "private_network", ip: "10.0.0.2", auto_config: false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.synced_folder "./", "/home/vagrant/LINGI2142-setup"
  config.ssh.insert_key = "true"
  config.ssh.forward_x11 = "true"

  config.vm.provision "shell", path: "provision.sh"
end

```

### Debug output
When I do vagrant up, I have this error (look at the end). It seems to be an encoding problem. 
https://gist.github.com/aclarembeau/6a1f7414356782e69895d2a01b19104d

### Expected behavior
It's because I have an accent in the directory path (my Fedora is in French and I have an acute accent in the work Reseaux, which is spelled Réseaux in french). So to fix the bug, I need remove the accent from the directory, I have the good behavior (now, the error message is normal). 

https://gist.github.com/aclarembeau/a9692bc01fb7ef1f7e2e6c68cd46c8c3

It's strange that we can't have directory with accents; it seems to be a bug.

**Comment by usrme** [comment]
I'm having a similar issue with Vagrant 1.9.1 on Windows 8.1. Namely, I'm trying to execute Test Kitchen with Vagrant as the driver, but it fails with the following error message:

```
STDERR: C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/platform.rb:176:in `encode': U+FFFD to WINDOWS-1257 in conversion from UTF-8 to WINDOWS-1257 (Encoding::UndefinedConversionError)
```

This happens because my username contains an U with an umlaut (the letter Ü) and the Vagrantfile for my project is unable to store it properly:

```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-14.04"
  c.vm.hostname = "default-ubuntu-1404.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "D:/Failid/Code/Kitchen/test/.kitchen/sync/default-ubuntu-1404", "/tmp/instance_data", create: true
  c.vm.synced_folder "C:/Users/\xDCllar/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
  end
end
```

Removing the line or disabling creation does nothing as the file gets overwritten. This seems more like a limitation of Vagrant not supporting a wider range of alphabets. Should my issue belong in a separate thread?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
