### ISSUE TITLE
Vagrant provisioning fails after installing Ruby 2.3 and librarian-chef on guest machine

### ISSUE THREAD

**Issue by alex-tan** [mitchellh/vagrant#8290]
### Vagrant version

1.9.1

### Host operating system

Mac OS 10.12.3

### Guest operating system

ubuntu/trusty64

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
  config.vm.synced_folder '.', '/vagrant'

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  config.vm.provider 'virtualbox' do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = '3072'
  end

  config.vm.provision 'chef_solo' do |chef|
    chef.cookbooks_path = %w(cookbooks)
    chef.add_recipe 'ruby::default'
  end
end
```

Full demonstration repo with recipes can be found [here](https://github.com/alex-tan/vagrant-chef-librarian-failure).

### Debug output

[Gist](https://gist.github.com/alex-tan/f9b761f9385bb441cd6c07193c8a635e)

The provisioning with the recipe shown works but when trying to reprovision we get the error `cannot load such file -- yajl/yajl`

### Expected behavior

Reprovisioning should work.

### Actual behavior

Cryptic error message about `yajl`

### Steps to reproduce

1. Clone [this repo](https://github.com/alex-tan/vagrant-chef-librarian-failure).
2. Run provisioning with linked recipe installing Ruby 2.3 and librarian-chef: `vagrant up --provision`
3. Try to run `vagrant up --provision` again.

**Comment by chrisroberts** [comment]
Hi!

The root cause of the problem here is that the PATH needs to be adjusted so that the omnibus install is the preferred chef executable that is found. After the initial provision, the system ruby version has been updated and librarian-chef has been installed (which includes chef as a dependency). The chef dependency then writes out its own executable in locations that get searched before `/usr/bin` which is where the omnibus installation tosses symlinks. As you can see below on the machine after it has been provisioned, it is no longer picking up the "expected" executable:

```
vagrant@vagrant-ubuntu-trusty-64:~$ which chef-solo
/usr/local/bin/chef-solo
vagrant@vagrant-ubuntu-trusty-64:~$ cat /usr/local/bin/chef-solo
#!/usr/bin/ruby2.3
#
# This file was generated by RubyGems.
#
# The application 'chef' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

load Gem.bin_path('chef', 'chef-solo', version)
vagrant@vagrant-ubuntu-trusty-64:~$ ls -l /usr/bin/chef-solo
lrwxrwxrwx 1 root root 23 Feb 16 21:13 /usr/bin/chef-solo -> /opt/chef/bin/chef-solo
vagrant@vagrant-ubuntu-trusty-64:~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

Updating your PATH should get things fixed up as far as `vagrant provision` goes. Cheers!

**Comment by alex-tan** [comment]
@chrisroberts Thanks for your helpful response!

To clarify for anyone who comes across this issue, I adjusted the path by putting this in my Vagrantfile:

```ruby
config.vm.provision 'chef_solo' do |chef|
  chef.binary_path = '/opt/chef/bin'
end
```
