### ISSUE TITLE
provision is considered successful even if returns non-zero

### ISSUE THREAD

**Issue by jjb** [mitchellh/vagrant#8301]
### Vagrant version
 1.9.2

### Host operating system
macOS 10.12.3

### Guest operating system
ubuntu/trusty64

### Vagrantfile

```ruby
...
provision "shell", inline: "set -e; apt-get install -y missppellled-package"
...
```

### Expected behavior
Vagrant should not consider the machine as having been provisioned if the provision script return value is non-zero.

### Actual behavior
Vagrant thinks the provisioning is done.

### Steps to reproduce
1. vagrant up foo
2. wait for provisioning to fail
3. vagrant up foo ("...Machine already provisioned...")

### References

* http://stackoverflow.com/questions/41971258/

**Comment by chrisroberts** [comment]
Hi there. Vagrant does not keep state information on success/failure of provisioners. If the provisioner is not set to always run, it will only run when the state of the vm transitions from "not created" to "running".

Cheers!
