### ISSUE TITLE
Vagrant share is not a recognized command

### ISSUE THREAD

**Issue by mohnjatthews** [mitchellh/vagrant#8311]
It's pretty much all in the title, when I run `vagrant share` it just looks like it's not a recognised command. I can't find anywhere online about this command being taking out of Vagrant, and it's [still included in the docs](https://www.vagrantup.com/docs/share/http.html). Am I missing something?

### Vagrant version
1.8.1

### Host operating system
Ubuntu 16.04 64bit (Elementary OS)

### Guest operating system
Ubuntu 16.04

### Vagrantfile (standard [Scotchbox](https://github.com/scotch-io/scotch-box))
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end

```

### Expected behavior
The `vagrant share` command should be recognised and executed as [described in the docs](https://www.vagrantup.com/docs/share/http.html)

### Actual behavior
The command is not recognized (below):

```
~/dev$ vagrant share
Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     init            initializes a new Vagrant environment by creating a Vagrantfile
     login           log in to HashiCorp's Atlas
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     port            displays information about guest port mappings
     powershell      connects to machine via powershell remoting
     provision       provisions the vagrant machine
     push            deploys code in this environment to a configured destination
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configuration
     resume          resume a suspended vagrant machine
     snapshot        manages snapshots: saving, restoring, etc.
     ssh             connects to machine via SSH
     ssh-config      outputs OpenSSH valid configuration to connect to the machine
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     version         prints current and latest Vagrant version

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.

```

### Steps to reproduce
1. Run `vagrant share`

**Comment by chrisroberts** [comment]
If vagrant was not installed from the official installer the vagrant-share plugin will not be available. If for some reason the plugin was uninstalled or corrupted, https://github.com/mitchellh/vagrant/issues/8311#issuecomment-283105074 will get it installed again.

Cheers!

**Comment by mohnjatthews** [comment]
I think I must have installed Vagrant via `apt-get`. Reinstalling via the Vagrant website fixed the issue.

**Comment by Jing-King** [comment]
It also happened to me too. I am running windows and installed it from the vagrant website.

**Comment by diegoquintanav** [comment]
I've just installed it from the .deb file and ran into the same issue. After installing the vagrant-share plugin, I get this

```
Vagrant Share now defaults to using the `ngrok` driver.
The `classic` driver has been deprecated.

For more information about the `ngrok` driver, please
refer to the documentation:

  https://www.vagrantup.com/docs/share/

The executable 'ngrok' Vagrant is trying to run was not found
in the PATH variable. The 'ngrok' executable is required to
run Vagrant share. If 'ngrok' is currently installed in a
non-standard location, append that location to the PATH
variable and run this command again. If 'ngrok' is not
currently installed, it can be downloaded from the ngrok
website:

  https://ngrok.com/download
```

I'm downloading ngrok, but you may have to check again if `vagrant share` should be working out of the box as you say :+1:

**Comment by mattiasghodsian** [comment]
I'm having some trouble with ngrok and vagrant, i can't really figure out what to do next.

https://imgur.com/a/niNbEIo

ngrok in under my home dir / App

**Comment by diegoquintanav** [comment]
In my case I solved following these instructions https://gist.github.com/diegoquintanav/4875c3186dbdb2cc8822f849e499ce9e

Hope it helps!

**Comment by midingblk** [comment]
> @mattiasghodsian This error is mostly because the path to `ngrok` binary is not present in `$PATH`.
> 
> In my case I solved it following these instructions https://gist.github.com/diegoquintanav/4875c3186dbdb2cc8822f849e499ce9e
> 
> Hope it helps!


excuse me, @diegoquintanav . could you explain what is `usr/local/bin` mean and `$path` mean? idk just me or there are still people who don't understand too. thanks
