### ISSUE TITLE
Incorrect information about the last version

### ISSUE THREAD

**Issue by albrin** [mitchellh/vagrant#8318]
After installing the latest version, I get the following message.

```
C:\Users\Alexander>vagrant version
Installed Version: 1.9.2
Latest Version: 1.9.1

You're running an up-to-date version of Vagrant!
```
Message "Latest Version: 1.9.1" is not correct. Must be "Latest Version: 1.9.2"
```
C:\Users\Alexander>vagrant --version
Vagrant 1.9.2
```
```
C:\Users\Alexander>vagrant -v
Vagrant 1.9.2
```
### Host operating system
Windows 10 Pro

**Comment by chrisroberts** [comment]
Hi there. Thanks for taking the time to open an issue. The latest version information is cached locally on the system and only updated periodically. If checks occurred during the AWS outage yesterday then that cached value will persist until some time today. Cheers!
