### ISSUE TITLE
Overwrites authorized_keys with incorrect public key

### ISSUE THREAD

**Issue by strarsis** [mitchellh/vagrant#8319]
Vagrant inserts an incorrect public key or at least doesn't 
use its corresponding private key for logging in.

Disabling the automatic public key insertion allows the box to go up - 
but doesn't solve this underlying issue.

It may be that the newly generated keypair files can't be written because 
of permission issues, but this nowhere logged or indicated.

`vagrant ssh` after the error message with `vagrant up` results in 
password prompt (username + password 'vagrant' works).

In '~/.ssh/authorized_keys' a public key is found that is 
different to the public key of the vagrant insecure keypair:
````
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCtu0SZeVLnHo0gUGs5fWBh/0ecqEPELBLJ8kW5o6TKcRTlvaFt5b7aQrHa73sKKTsyCxE/KBUD0N1eg4sJgF8Be/XrBB/yYBQvVZs80HBBVrraeeSWuX8HcqEm8U5zx/f1DpXsnrLOP1oAMGrgQJKEwZngS/eFD6oMiSgp0AIC4xPL6SHHLO6CzRnbT0O7SoglEU5RYzngEJtJ4lZEAoWraReD83gMeKyKf42RGU/iFuAFwXvB9WltgfVFe9fNzHaObfV4j4THzJjfRDfjBZwxbmnQVvEmPOhZTQim4IzmPEvIcUlRxXC6dIHjrRghixxShoT9eHoNsu1+/IrXXB9V vagrant
````

### Vagrant version
Vagrant 1.9.1

### Host operating system
Ubuntu 16.04.2 LTS

### Guest operating system
Ubuntu 16.04.2 LTS (same)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"

end
````

### Debug output
https://gist.github.com/strarsis/8b1f538673f04dd16644b0b3f8ff225e

### Expected behavior
vagrant box goes up and ssh login works.

### Actual behavior
vagrant box fails to go up, ssh login doesn't work

### Steps to reproduce
1. Install vagrant
2. Add Vagrantfile
3. `vagrant up`

**Comment by ziaius** [comment]
some what the same issue on windows machine.

**Comment by strarsis** [comment]
I am able to bring the box up by adding this option to its Vagrantfile
````
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
end
````

But it doesn't fix this underlying issue.

**Comment by ziaius** [comment]
- I had to disable Hyper-V from features (windows 10) 
- Enabled virtualisation in my bios. 
- started box with provider specialised  `vagrant up --provider virtualbox`

one of these helped me to bring the box up and ssh into it. (note: fresh started each time)

**Comment by chrisroberts** [comment]
Hi there. I'm unable to reproduce the behavior you are experiencing locally. It appears that Vagrant is unable to establish a proper SSH connection to the VM and this is the reason the SSH key is not replaced. Using the original file, after the `vagrant up` fails, is the VM accessible via `vagrant ssh`? If you login to the VM via the GUI are the network interfaces up and connected? Is the SSH service running?

If you disable the ssh key insertion are you able to `vagrant ssh` after the VM is up?

**Comment by strarsis** [comment]
@chrisroberts: Yes, disabling automatic key insertions allows to access the box - but it doesn't solve the underlying issue.

**Comment by ziaius** [comment]
@chrisroberts, in my case i was neither able to ssh into nor open view from oracle vm virtualbox. :( but the symptoms were the same! in the end it said ssh timeout. nothing about the real issue!!

**Comment by chrisroberts** [comment]
@ziaius For your issue specifically I'm guessing the problem has to do with the VM having its cable disconnected. Try adding this in your Vagrantfile:

```ruby
config.vm.provider :virtualbox do |vb|
  bv.customize ['modifyvm', :id, '--cableconnected1', 'on']
end
```

**Comment by chrisroberts** [comment]
I have been unable to reproduce this issue locally. I'm unsure if it may have been the version of the box you were using or something else. If you still encounter this issue using the latest version of the box and the latest version of Vagrant, please feel free to re-open this issue or create a new one. Thanks!
