### ISSUE TITLE
embedded coreutils (for example rm) cannot handle long paths on Windows

### ISSUE THREAD

**Issue by PAStheLoD** [mitchellh/vagrant#8321]
### Vagrant version
1.9.2

coreutils in msysgit: 8.25
coreutils in vagrant: 5.97 (it's from 2006)

### Host operating system
Windows 10

### Guest operating system
N/A

### Steps to reproduce
1. install latest Vagrant (and msysgit, and ConEmu) and nodejs (npm -v = 4.2.0)
2. launch msysgit bash (via ConEmu)
3. npm install angular-cli
3. put vagrant's embedded/bin directory on the path (e. g. to be able to install plugins via gem) at the front
4. try to delete a directory containing node_modules with lots of nested node_modules directories

**Comment by chrisroberts** [comment]
The included coreutils are provided by the devkit for handling ruby gem installations. If you need more recent versions please install them directly. Cheers!
