### ISSUE TITLE
mount.nfs: access denied by server while mounting

### ISSUE THREAD

**Issue by lhridley** [mitchellh/vagrant#8332]
I'd reopen the previous issue but that doesn't appear to be possible

#5424 

This issue was closed prematurely, it is not resolved.  If you read the thread, Vagrant version 1.9.1 introduced a regression that causes issues with NFS file mounts.  There are numerous details included in the prematurely closed issue #5424 .

Correction:  Appears to be fixed in 1.9.2

**Comment by nervo** [comment]
Correction: Appends also in 1.9.2
