### ISSUE TITLE
Windows base box URLs aren't working

### ISSUE THREAD

**Issue by sphaugh** [mitchellh/vagrant#8335]
The Windows provided VMs don't appear to be working since they need to be decompressed first.

### Host operating system

NixOS

### Steps to reproduce
1. `vagrant box add win7/ie11 http://aka.ms/ie11.win7.vagrant`

**Comment by chrisroberts** [comment]
Hi there. Please provide a gist of the `--debug` output of the failure you are experiencing. Thanks!

**Comment by sphaugh** [comment]
https://gist.github.com/1294e5f42e6e6b872c4589e3fa85c2fd

**Comment by sphaugh** [comment]
https://gist.github.com/e85851f5b5f90ca463d6d6ef46d8152d

**Comment by sphaugh** [comment]
I _was_ able to work around this by using `http://aka.ms/vagrant-win7-ie11` instead. Maybe that name just needs to be updated on http://www.vagrantbox.es/?

**Comment by chrisroberts** [comment]
Glad you got it working. Cheers!
