### ISSUE TITLE
prune subcommand is missing from bash completion

### ISSUE THREAD

**Issue by senki** [mitchellh/vagrant#8339]
### Vagrant version
Vagrant 1.9.2 any host with bash shell

### Expected behavior
`vagrant box` after tab -> list with 'prune' included

### Actual behavior
`vagrant box` after tab ->missing prune

### Steps to reproduce
1. use bash and install completion
1. type `vagrant box`
2. hit tab
3. list appear: `add        help       list      remove     repackage`

**Comment by kikitux** [comment]
@senki 

Vagrant completion, perhaps is coming from your host os?

**Comment by kikitux** [comment]
@senki if you are using our completion.sh file, I just added a PR for it:

https://github.com/mitchellh/vagrant/pull/8806
