### ISSUE TITLE
1.9.2 mac installer isn't signed with an Apple Developer ID

### ISSUE THREAD

**Issue by pharaujo** [mitchellh/vagrant#8340]
### Vagrant version
1.9.2

### Host operating system
macOS Sierra

### Guest operating system
NA

### Vagrantfile
NA

### Debug output
```
# Vagrant 1.9.2 installer
$ pkgutil --check-signature /Volumes/Vagrant/Vagrant.pkg
Package "Vagrant.pkg":
   Status: no signature

# Vagrant 1.9.1 installer
$ pkgutil --check-signature /Volumes/Vagrant\ 1/Vagrant.pkg
Package "Vagrant.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: Mitchell Hashimoto
       SHA1 fingerprint: 9D 16 F7 36 D1 D9 9E A2 1D DE E3 8B 93 27 14 8C 2B CE 1C 32
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```

### Expected behavior
I should be able to install Vagrant without side stepping security measures.

### Actual behavior
<img width="532" alt="screen shot 2017-03-07 at 13 19 07" src="https://cloud.githubusercontent.com/assets/555927/23658033/cf09f210-0338-11e7-84ad-6b5196bd9793.png">

### Steps to reproduce
- Download Vagrant 1.9.2 .dmg file;
- Mount .dmg;
- Attempt to install Vagrant.pkg

**Comment by chrisroberts** [comment]
Hi there. This was noted at mitchellh/vagrant-installers#102 and will be fixed on the next release. Thank you for reporting the issue!
