### ISSUE TITLE
1.9.2: “Vagrant.pkg” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by georgevreilly** [mitchellh/vagrant#8345]
I downloaded `vagrant_1.9.2.dmg` from https://www.vagrantup.com/downloads.html. It won't install. Apparently, it's not properly signed. This didn't happen with 1.9.1 or earlier versions.

While I could work past this in the System Preferences, I prefer not to.

### Vagrant version
1.9.2

### Host operating system
macOS 10.12.3

![image](https://cloud.githubusercontent.com/assets/34297/23722794/968c02c0-03fb-11e7-8022-cf762ed46a02.png)

**Comment by chrisroberts** [comment]
Dup of #8340. Thanks for the report!

**Comment by jhriv** [comment]
This is still the case today, eight days after the issue was closed.

**Comment by FreshCapsule** [comment]
I am having the same issue.

**Comment by FreshCapsule** [comment]
Here is resource it might help you on this case: 

**How to run apps that are not from the App Store in macOS Sierra Public Beta**
[http://www.macworld.com/article/3094865/macs/how-to-run-apps-that-are-not-from-the-app-store-in-macos-sierra.html](http://www.macworld.com/article/3094865/macs/how-to-run-apps-that-are-not-from-the-app-store-in-macos-sierra.html)

Hope it helps!

**Comment by Erulezz** [comment]
@jhriv It is not fixed in 1.9.2 (still unsigned) but in the upcoming release;

https://github.com/mitchellh/vagrant-installers/issues/102#issuecomment-284791641

**Comment by stanwu** [comment]
I believed Vagrant.pkg should to solve this issue first before most of users to install it
