### ISSUE TITLE
[1.9.x] vagrant plugin install fails on Windows 10 (getaddrinfo: No such host is known.)

### ISSUE THREAD

**Issue by mitrpaka** [mitchellh/vagrant#8349]
After upgrading vagrant from version 1.8.7 to 1.9.2 on my Windows (64-bit) desktop, I am not able to install any of the plugins due to Vagrant/embedded/lib/ruby/2.2.0/resolv.rb:791:in `send': getaddrinfo: No such host is known.  (SocketError) -error.

Prior to 1.9.x release (1.8.7 or earlier) plugin installation succeeded without issues. Tried plugins: vagrant-cachier, vagrant-vbguest and vagrant-hostsupdater.

Debug log as follows:
https://gist.github.com/mitrpaka/9d6e61026bba4584ab066092e70cef79

**Comment by chrisroberts** [comment]
Hi there. The error you are encountering is a DNS lookup failure and is not something that can be fixed within Vagrant itself. This is likely a transient issue and will generally correct itself. If you are still experiencing problems, check your DNS settings and verify the nameservers you are using are returning proper results. 

Cheers!
