### ISSUE TITLE
openSUSE Network is managed by 'NetworkManager.service' -> skipping on vagrant up

### ISSUE THREAD

**Issue by midikem** [mitchellh/vagrant#8355]
I get this error on vagrant up on a openSUSE box that uses NetworkManager.service
If I change the openSUSE box used to use network.service then the network don't work at all. If I use NetworkManager.service and do a provision after up everything works good. But the up still gives me the problems below. 

I am using openSUSE leap 42.2, vagrant 1.9.2 and vb 5.0.14

=> opensuse: Machine booted and ready!
==> opensuse: Checking for guest additions in VM...
==> opensuse: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 'eth2' || true
mv '/tmp/vagrant-network-eth2-1489144358-0' '/etc/sysconfig/network/ifcfg-eth2'
/sbin/ifup 'eth2'

Stdout from the command:

Stderr from the command:

<13>Mar 10 12:12:38 vagrant: Network is managed by 'NetworkManager.service' -> skipping
<13>Mar 10 12:12:38 vagrant: Network is managed by 'NetworkManager.service' -> skipping

**Comment by kikitux** [comment]
@midikem 

Can you please update to latest vagrant, and if the issue remains, can you share a repro case including Vagrantfile ?

Thanks

**Comment by midikem** [comment]
@kikitux Hi this is still an issue! Updated to latest version today 2.0.2. When Centos has NetworkManager enabled it fails on vagrant up. The workaround is to do provision after vagrant up or to change the default NetworkManager to network service.

Installed Version: 2.0.2
Latest Version: 2.0.2
 
You're running an up-to-date version of Vagrant!

From: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/3/html/Installation_and_Configuration_Guide/Disabling_Network_Manager.html

"...The Network Manager service is currently enabled by default on Red Hat Enterprise Linux installations where one of these package groups was selected during installation:

    Desktop
    Software Development Workstation "
