### ISSUE TITLE
Vagrant should not try to install VirtualBox automatically

### ISSUE THREAD

**Issue by unixwitch** [mitchellh/vagrant#8356]
### Vagrant version
1.9.2

### Host operating system
Windows 10 Professional

### Expected behavior
Vagrant should not automatically install VirtualBox without asking the user.

I use Vagrant with Hyper-V, but whenever I forget `--provider=hyperv` in `vagrant up`, it tries to download and install VirtualBox - which is pointless, because VirtualBox doesn't work when Hyper-V is enabled on the host.  

I could set `%VAGRANT_DEFAULT_PROVIDER%` to prevent it, but in general, automatically trying to install something like VB doesn't seem right.  At the very least, it should ask "VirtualBox was not found; install it? [y/N]" beforehand.  Or, since I already have a working provider (Hyper-V), just detect that and use it.

### Actual behavior
Vagrant tried to install VirtualBox automatically.

### Steps to reproduce
Run `vagrant up` on a host without VirtualBox installed.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
