### ISSUE TITLE
Vagrant PowerShell does not work when using SSL

### ISSUE THREAD

**Issue by tmintner** [mitchellh/vagrant#8360]
The plugin located at vagrant/plugins/hosts/windows/cap/ps.rb does not account for Windows machines that are configured to use SSL in WinRM.  This means that vagrant powershell will not connect to a system that just has the SSL listeners enabled.

There are two ways to resolve this issue.  The first is to add a parameter for WinRM for SSL and then add the -USESSL to the end of the Enter-PSSession command.  The second method would be to change enter-psession -computername to enter-pssession -connectionURI and change the URI to either http or https based on the port that is configured.  

From the enter-pssession documentation:
-ConnectionUri

Specifies a URI that defines the connection endpoint for the session. The URI must be fully qualified. The format of this string is as follows:

<Transport>://<ComputerName>:<Port>/<ApplicationName>

The default value is as follows:

http://localhost:5985/WSMAN

If you do not specify a ConnectionURI, you can use the UseSSL, ComputerName, Port, and ApplicationName parameters to specify the ConnectionURI values.

Valid values for the Transport segment of the URI are HTTP and HTTPS. If you specify a connection URI with a Transport segment, but do not specify a port, the session is created by using standards ports: 80 for HTTP and 443 for HTTPS. To use the default ports for Windows PowerShell remoting, specify port 5985 for HTTP or 5986 for HTTPS.

**Comment by kikitux** [comment]
@tmintner 

Please updarte to latest version

review this page:
https://www.vagrantup.com/docs/vagrantfile/winrm_settings.html

Ensure you review that ssl need to be enabled, default to no ssl, check the cert part

if still fail, please share repro case, vagrantfile and a windows box with winrm/ssl enabled.

Thanks
