### ISSUE TITLE
Update to net-ssh 4.x to support ssh agents on windows

### ISSUE THREAD

**Issue by func0der** [mitchellh/vagrant#8367]
### Vagrant version
1.9.2

### Host operating system
Windows

### Guest operating system
Linux

### Vagrantfile
irrelevant

### Expected behavior
vagrant provision should consider the ssh-agent running.

### Actual behavior
It doesn't.

### Steps to reproduce
- Run an ssh-agent
- Try provisioning and use something where you need ssh-agent-forwarding for (for example: composer install)

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/mitchellh/vagrant/issues/1735
- https://github.com/net-ssh/net-ssh/issues/192

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by func0der** [comment]
This is still an issue. 
I am using Vagrant 2.1.1, which uses net-ssh 4.2.0.

It is not solved yet. The ssh agent is not forwarded.
