### ISSUE TITLE
How to download IE8 Windows 7 in Virtual Box

### ISSUE THREAD

**Issue by unicorncupcake** [mitchellh/vagrant#8369]
I pasted the bolded command below into my terminal

**curl -s https://raw.githubusercontent.com/xdissent/ievms/master/ievms.sh | bash**

I keep getting this error below...but i dont know what it means.

- [ ] VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg *)" at line 886 of file VBoxManageAppliance.cpp

**Comment by chrisroberts** [comment]
Hi there. This is a custom script that is installing a VM into virtualbox and is not a part of Vagrant. You will need to contact the author of the script for any questions. Cheers!
