### ISSUE TITLE
Vagrant fails to add guest additions for CentOS 7

### ISSUE THREAD

**Issue by starrychloe** [mitchellh/vagrant#8374]
https://superuser.com/questions/1188685/how-do-i-get-the-clipboard-to-work-in-centos-inside-virtualbox-on-windows/1188712

Vagrant mouse integration and clipboard doesn't work with CentOS 7 because guest additions aren't provisioned. Also the folder sync isn't working either. 

I have CentOS 7.3.1611 running with XFCE inside Oracle VirtualBox 5.1.16 on Windows 8.1. I set Devices > Shared Clipboard > Bidirectional, but nothing I copy in Windows is pasteable in CentOS, and nothing I copy in CentOS is pasteable in Windows. 

I used Vagrant to create the box. `vagrant init centos/7; vagrant up`

    ==> default: Checking for guest additions in VM...
        default: No guest additions were detected on the base box for this VM! Guest
        default: additions are required for forwarded ports, shared folders, host only
        default: networking, and more. If SSH fails on this machine, please install
        default: the guest additions and repackage the box to continue.
        default:
        default: This is not an error message; everything may continue to work properly,

I also manually added an optical drive and loaded `VBoxGuestAdditions.iso` from the VirtualBox folder, restarted, manually mount the CDROM, and manually ran the script, but:

    [vagrant@localhost ~]$ sudo mount /dev/sr0/ /mnt
    mount: /dev/sr0 is write-protected, mounting read-only
    [vagrant@localhost ~]$ cd /mnt
    [vagrant@localhost mnt]$ sudo ./autorun.sh
    Linux guest additions installer not found -- try to start them manually.
    [vagrant@localhost mnt]$ ls
    32Bit  AUTORUN.INF  cert  runasroot.sh            VBoxSolarisAdditions.pkg        VBoxWindowsAdditions.exe
    64Bit  autorun.sh   OS2   VBoxLinuxAdditions.run  VBoxWindowsAdditions-amd64.exe  VBoxWindowsAdditions-x86.exe

---

Here is the log from running `VBoxLinuxAdditions.run`.

    [vagrant@localhost mnt]$ sudo ./VBoxLinuxAdditions.run
    Verifying archive integrity... All good.
    Uncompressing VirtualBox 5.1.16 Guest Additions for Linux...........
    VirtualBox Guest Additions installer
    Removing installed version 5.1.16 of VirtualBox Guest Additions...
    Copying additional installer modules ...
    Installing additional modules ...
    vboxadd.sh: Building Guest Additions kernel modules.
    Failed to set up service vboxadd, please check the log file
    /var/log/VBoxGuestAdditions.log for details.
    [vagrant@localhost mnt]$ cat /var/log/VBoxGuestAdditions.log
    
    vboxadd.sh: failed: Look at /var/log/vboxadd-install.log to find out what went wrong.
    vboxadd.sh: failed: Please check that you have gcc, make, the header files for your Linux kernel and possibly perl installed..
    [vagrant@localhost mnt]$ cat /var/log/vboxadd-install.log
    /tmp/vbox.0/Makefile.include.header:97: *** Error: unable to find the sources of your current Linux kernel. Specify KERN_DIR=<directory> and run Make again.  Stop.
    Creating user for the Guest Additions.
    Creating udev rule for the Guest Additions kernel module.
    [vagrant@localhost mnt]$ gcc
    gcc: fatal error: no input files
    compilation terminated.
    [vagrant@localhost mnt]$

### Vagrant version
Vagrant 1.9.2

### Host operating system
Windows 8.1

### Guest operating system
CentOS Linux release 7.3.1611 (Core) 

### Vagrantfile
```ruby
$ grep -ve '^\s*#' Vagrantfile | cat -s

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

end
```

### Debug output
Log files above...

### Expected behavior
I would have expected that when I turn on bi-directional clipboard I could copy/paste. Also mouse integrations should have just worked. Also the /vagrant folder should sync (will enter separate ticket for that).

### Actual behavior
Clipboard didn't work. Had to press RIGHT-CTRL to uncapture mouse.

### Steps to reproduce
1. vagrant init centos/7
2. vagrant up
3. vagrant ssh
4. sudo yum groupinstall epel-release 'x window system' xfce
5. startxfce4
6. Open terminal, try to copy/paste back & forth or move mouse.
7. Try to view /mnt. Unmounted. Have to manually add optical drive to VirtualBox and manually select guest additions. Then manually mount with `sudo mount /dev/sr0 /mnt; cd /mnt`
8. The other steps to fix it are in SuperUser post.

**Comment by cheeseplus** [comment]
This isn't an issue with Vagrant so much as it is one with the base box you are using. Vagrant does have plugins like `vagrant-vbguest` for automatically updating virtualization drivers once installed but the process of installing these is part of baking a base box as with https://github.com/chef/bento or https://github.com/boxcutter/centos.

This isn't a bug, you'll need to install the tools yourself or use a base box that does so on your behalf.

**Comment by chrisroberts** [comment]
Hi there. @cheeseplus is correct, the base box is responsible for having these tools installed. See the links he provided for boxes that include the tools. Cheers!

**Comment by slugfish** [comment]
a little late to the came but
 https://seven.centos.org/2017/09/updated-centos-vagrant-images-available-v1708-01/

has the deets

**Comment by GuanHitam** [comment]
No matter what, you should still be able to add guestadditions yourself, if your box does not have it. Starychloe is doiing the tight thing: adding the guestadditions himself with command:
# sudo ./VBoxLinuxAdditions.run
That does not work which should. So anybody has some suggestion?

**Comment by goforgold** [comment]
Use this box for CentOS7. It has Guest Additions installed already

`config.vm.box = "geerlingguy/centos7"`

**Comment by adaroobi** [comment]
If anyone wants to manually install VBox guest additions to CentOS 7
[you may follow this](https://gist.github.com/adaroobi/fea2727be6ae3d9c446767f813146f93)

**Comment by sfed** [comment]
here is how I added Virtualbox Guest Additions to my centos7 box.
vagrant plugin install vagrant-vbguest 
vagrant vbguest --do install --no-cleanup

hope this helps
