### ISSUE TITLE
Vagrant does not synchronize folders on CentOS/Windows even with guest additions

### ISSUE THREAD

**Issue by starrychloe** [mitchellh/vagrant#8375]
https://superuser.com/questions/1189102/how-do-i-sync-vagrant-sync-folder-with-virtualbox-and-centos-windows

### Vagrant version
Vagrant 1.9.2

### Host operating system
Windows 8.1

### Guest operating system
CentOS Linux release 7.3.1611 (Core)

### Vagrantfile
```ruby
$ grep -ve '^\s*#' Vagrantfile | cat -s

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

end
```

### Debug output
https://gist.github.com/starrychloe/7c11e30934241f02e8cac54fd615da03

### Expected behavior
When you create a file in the guest, it should show up in the host. 

https://www.vagrantup.com/docs/getting-started/synced_folders.html

> By default, Vagrant shares your project directory (the one with the Vagrantfile) to the /vagrant directory in your guest machine.

### Actual behavior
It doesn't sync from guest to host, but it does sync from host to guest - only if I run `vagrant rsync` manually or `vagrant up` - and it deletes any new files in the guest. 

I tried to manually mount and it gave an error

    [vagrant@localhost vagrant]$ sudo mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant
    /sbin/mount.vboxsf: mounting failed with the error: Protocol error

### Steps to reproduce
```
$ vagrant ssh
Last login: Wed Mar 15 20:16:19 2017 from 10.0.2.2
[vagrant@localhost ~]$ touch /vagrant/tmp.txt
[vagrant@localhost ~]$ ls /vagrant
tmp.txt  Vagrantfile  vagrant.log
[vagrant@localhost ~]$ exit
logout
Connection to 127.0.0.1 closed.

Chloe@xps /cygdrive/c/Users/Chloe/Documents/server
$ ls
vagrant.log  Vagrantfile
```

### References
https://gist.github.com/starrychloe/7c11e30934241f02e8cac54fd615da03#file-vagrant-log-L11104

**Comment by chrisroberts** [comment]
Hi there. This is a bug in the version of VirtualBox you have installed. Upgrading VirtualBox will resolve the issue. See #8352 for more information.

Cheers!
