### ISSUE TITLE
Vagrant unable to mount shared folder (/vagrant)

### ISSUE THREAD

**Issue by multimac** [mitchellh/vagrant#8376]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.9.2

### Host operating system
Windows 10 Enterprise, using Virtualbox 5.1.16 r113841

### Guest operating system
Ubuntu 14.04 (ubuntu/trusty64)

### Vagrantfile
Default generated from running `vagrant init ubuntu/trusty64`

### Debug output
https://gist.github.com/multimac/3efbfbfd1a13d69db00a07264ff688ae

### Expected behavior
Vagrant should create the box and be able to mount the shared folder.

### Actual behavior
Vagrant errors, saying it mount failed due to ": No such file or directory"

### Steps to reproduce
1. vagrant init ubuntu/trusty64
2. vagrant up
3. ...
4. profit? well, error...

### References / Other Notes
I noticed that when Vagrant registers the shared folder with Virtualbox, it sends the path with "\\\\?\\" prepended to it. When I remove this, and manually attempt to remount the shared folder it works.

https://gist.github.com/multimac/3efbfbfd1a13d69db00a07264ff688ae#file-debug-log-L3059

**Comment by chrisroberts** [comment]
Hi there. The version of VirtualBox you have installed has a bug that causes it to not properly handle shared folders paths on Windows. Upgrading to 5.1.18 will resolve the problem.

Reference: #8352
