### ISSUE TITLE
Package for libvirt 

### ISSUE THREAD

**Issue by waldirio** [mitchellh/vagrant#8382]
### Vagrant version
Vagrant 1.9.2

### Host operating system
RHEL 7.3

### Actual behavior
Hi, I use only libvirt / kvm on my environment, then after create one new guest via libvirt, configure and prepare to be one new box, I got the message below when trying to create a new one box
---
[root@dvader BOX]# vagrant package --base base_rhel7
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
---

So then I was looking for how to *force* the provider and looking the help
---
--base NAME                  Name of a VM in VirtualBox to package as a base box (VirtualBox Only)
---

So my request is, just enable the libvirt to be one valid provider to create a new box without virtualbox necessity.

### Expected behavior
Be able to create new box directly via libvirt.

Thank you!
Waldirio

**Comment by chrisroberts** [comment]
Hi there. The package command support would be required to be implemented and supported by the libvirt provider which is part of the `vagrant-libvirt` plugin, not Vagrant itself. Cheers!

**Comment by waldirio** [comment]
Hi Chris,
Thanks for your reply.
