### ISSUE TITLE
Failed to mount Synced Folders

### ISSUE THREAD

**Issue by fleckiboy** [mitchellh/vagrant#8383]
### Vagrant version
Vagrant 1.9.2

### VirtualBox version
5.1.16 r113841
Guest Addtions on Guest OS: 5.1.16

### Host operating system
Windows 10 (current Verison is 1607)

### Guest operating system
CentOS 7

### Vagrantfile
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "php_56"

  config.vm.network :forwarded_port, guest: 22, host: 2201, id: "ssh", auto_correct: true

  config.vm.network "forwarded_port", guest: 80, host: 8083
  
  config.vm.synced_folder "C:/php", "/var/www/"

  config.vm.provider "virtualbox" do |v|
    v.name = "php_56"
  end

end

### Expected behavior
Host Folder C:/php should be mounted to /var/www in Guest.

### Actual behavior
Error when trying to mount the Shared Folder:

> Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

> mount -t vboxsf -o uid=1001,gid=1001 php /var/www

> The error output from the command was:
/sbin/mount.vboxsf: mounting failed with the error: No such file or directory

Obviously, the Guest System can't find the Directory which I would like to mount.

When looking at the Shared Folders in VirtualBox (generated by Vagrant), all Folders have preceding "\\\\?\\\". When this leading Char-Sequence is removed, the mounting process works again -> I altered the Code in  [vagrant/lib/vagrant/util/platform.rb](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/util/platform.rb)  at Line 206 to `path.gsub("/", "\\")` as a Workaround!

**Comment by chrisroberts** [comment]
Hi there. This is a bug in the version of VirtualBox you have installed. Upgrading VirtualBox will resolve the issue. See #8352 for more information.

Cheers!

**Comment by fleckiboy** [comment]
Thanks for the Info, the update to Version 5.1.18 of Virtual Box did it!
