### ISSUE TITLE
Unable to upgrade plugins after vmware upgrade

### ISSUE THREAD

**Issue by ngpestelos** [mitchellh/vagrant#8388]
### Vagrant version

```
1.9.2
```

### Host operating system

```
OS X 10.12.3
```

### Guest operating system

```
Ubuntu 14.04
```

### Vagrantfile

[gist](https://gist.github.com/ngpestelos/6f0e63d563ac4cc3191e38b60b9e1ab9)

### Debug output

[gist](https://gist.github.com/ngpestelos/e9392698e5064796fc8a1f082074918e)

### Expected behavior

- vmware plugin updated

### Actual behavior

- vmware plugin not updated

### Steps to reproduce

1. Update VMWare to 8.5.5
1. Update Vagrant to 1.9.2
1. Run `vagrant plugin repair`

**Comment by chrisroberts** [comment]
Hi there. A previous constraint on the gem repository in use only allowed a certain number of previous gems to remain in the repository. This restriction has been removed, and the version of the plugin attempting to be reinstalled will now be successful. You can also install a newer version as well. Cheers!
