### ISSUE TITLE
Docs are confusing about VAGRANT_DEFAULT_PROVIDER vs --provider flag

### ISSUE THREAD

**Issue by WyseNynja** [mitchellh/vagrant#8389]
### Vagrant version
Vagrant 1.8.7 and 1.9.2

### Host operating system
OSX, but likely everywhere

### Guest operating system
Irrelevant

### Document 1
https://www.vagrantup.com/docs/providers/basic_usage.html

> Vagrant Up
> Once a provider is installed, you can use it by calling vagrant up with the --provider flag. This will force Vagrant to use that specific provider. No other configuration is necessary!
> 
> In normal day-to-day usage, the --provider flag is not necessary since Vagrant can usually pick the right provider for you. More details on how it does this is below.
>
> If you specified a --provider flag, you only need to do this for the up command. Once a machine is up and running, Vagrant is able to see what provider is backing a running machine, so commands such as destroy, suspend, etc. do not need to be told what provider to use.Once you vagrant destroy existing environments, this will take effect.

### Document 2
https://www.vagrantup.com/docs/other/environmental-variables.html

> VAGRANT_DEFAULT_PROVIDER
> This configures the default provider Vagrant will use.
>
> This normally does not need to be set since Vagrant is fairly intelligent about how to detect the default provider. By setting this, you will force Vagrant to use this provider for any new Vagrant environments. Existing Vagrant environments will continue to use the provider they came up with. > Once you vagrant destroy existing environments, this will take effect.

### Vagrantfile

This should work with any Vagrantfile, but here is a bare-bones example
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
end
```

### Debug output

Buried in ~/.bash_profile or some place like that:
```
export VAGRANT_DEFAULT_PROVIDER=aws
```

Then run this command:
```
$ vagrant up --provider virtualbox
There are errors in the configuration of this machine. Please fix
the following errors and try again:

AWS Provider:
* An AMI must be configured via "ami" (region: #{region})
```

### Expected behavior
I expect the above command to override the default set by the environment variable and use the "virtualbox" provider. 

### Actual behavior
It used the default provider ("aws") as specified by the environment variable and failed

### Steps to reproduce
1. This errors: `VAGRANT_DEFAULT_PROVIDER=aws vagrant up --provider virtualbox`
2. This works: `VAGRANT_DEFAULT_PROVIDER=virtualbox vagrant up`

We have a large number of engineers that have set `VAGRANT_DEFAULT_PROVIDER=aws` in their dotfiles and would prefer not to force all of them to learn about this odd behavior.

**Comment by chrisroberts** [comment]
Temporary workaround to prevent the error: add `--no-install-provider` flag.
