### ISSUE TITLE
Hash Issue - Deb Package x64

### ISSUE THREAD

**Issue by ee-mm** [mitchellh/vagrant#8398]
It appears the hash for the current version download does not match your checksums:

$ sha256sum vagrant_1.9.3_x86_64.deb
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  

Whereas, the hash from https://releases.hashicorp.com/vagrant/1.9.3/vagrant_1.9.3_SHA256SUMS is the following:

faff6befacc7eed3978b4b71f0dbb9c135c01d8a4d13236bda2f9ed53482d2c4  vagrant_1.9.3_x86_64.deb

**Comment by chrisroberts** [comment]
Hi there. I just downloaded the deb package to validate this and I'm getting the expected checksum:

```
→ sha256sum vagrant_1.9.3_x86_64.deb
faff6befacc7eed3978b4b71f0dbb9c135c01d8a4d13236bda2f9ed53482d2c4  vagrant_1.9.3_x86_64.deb
```

It looks like there might be either an issue with your download, or the local file on your system has been modified. If you find there is still an issue after a fresh download of the package, please feel free to re-open this issue. Cheers!
