### ISSUE TITLE
Typo in SMB folder sync code

### ISSUE THREAD

**Issue by mcuma** [mitchellh/vagrant#8404]
Looks like I discovered a typo in the code that does SMB mount to sync folders between Windows host and Linux guest.

### Vagrant version
Vagrant 1.9.3

### Host operating system
Windows 10

### Guest operating system
Ubuntu 14.04

I'll save everyone going through all the other details, since the issue is quite simple.

In file
 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/guests/linux/cap/mount_smb_shared_folder.rb 
there is a typo on line 18.

Instead of
 detected_ids = detect_owner_group_ids(machine, guest_path, mount_options, options)
should be
 detected_ids = detect_owner_group_ids(machine, guestpath, mount_options, options)

After making the simple change, the SMB mount works. Before it, it was complaining that "guest_path" is missing.

Best,
MC

**Comment by Ratman9000** [comment]
Wow so funny, I was suffering from this yesterday and just found the same bug when I was looking at it this morning.  I logged back in tonight to submit and pull request for the fix, and saw this issue created on the same day.  We must have been on the same wavelength today :)  👍

**Comment by theocodes** [comment]
This is blocking me.. I run vagrant on windows 10 with vmware_workstation and smb for shared and so unfortunately can't use master as it needs to run in the installer..

Realistic speak, how long until this fix gets pushed to distribution and I can download it from https://www.vagrantup.com/downloads.html ?

thanks

**Comment by martixy** [comment]
@theocodes You can simply fix the typo. It worked for me on W10.

**Comment by theocodes** [comment]
@martixy I had't realised the filed was in /embedded.. Thanks!
