### ISSUE TITLE
Gentoo guests that use systemd do not provision using Virtualbox

### ISSUE THREAD

**Issue by gh2k** [mitchellh/vagrant#8406]
When using Virtualbox as a provisioner and a Gentoo guest, the guest doesn't come up properly if it uses systemd instead of OpenRC.

### Vagrant version
1.9.3

### Host operating system
Gentoo

### Guest operating system
Gentoo

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = # an internal box
  config.vm.box_url = #an internal URL
  config.vm.box_check_update = true

  # private network provides known IP addresses for the swarm master and
  # nodes
  config.vm.network "private_network", ip: '192.168.34.10'
  config.vm.network "private_network", ip: '192.168.34.12', gateway: '192.168.34.1'
  config.vm.network "private_network", ip: '192.168.36.12', interface: 1

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provider "hyperv" do |hv, override|
    override.vm.box = # an internal box
    override.vm.box_url = # an internal URL
    hv.memory = "1024"
    hv.cpus = 2
  end

  config.vm.provision 'shell',
    path: 'provision-master.sh',
    env: { SWARM: 'devbox', MASTER_IP: '192.168.34.10' }
end
```

Note, some networking garbage in there due to testing.

### Debug output
https://gist.github.com/gh2k/418e347427a2653876df08dc6d5bce88

### Expected behavior
My VM should have got to the end of the provisioning process successfully

### Actual behavior
Provisioning failed when it tried to set up the network

### Steps to reproduce
Create a gentoo guest which uses systemd, e.g. https://github.com/symbols-worldwide/gentoo-packer
Attempt to use with vagrant, and a virtualbox provisioner

**Comment by gh2k** [comment]
Closing this... The patch was accepted and it works.

**Comment by greister** [comment]
Why this path was throwed away on the vagrant2.0.1 version.
I have the same problem.
