### ISSUE TITLE
vagrant up fails when using machine id

### ISSUE THREAD

**Issue by kkharma** [mitchellh/vagrant#8408]
### Vagrant version
```
% vagrant -v
Vagrant 1.9.3
```

### Host operating system
macOS 10.12.3

### Guest operating system
CentOS 6.5

### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "myvm"
  config.vm.box_url = "file:///Users/kkharma/Library/Vagrant/myvm/myvm.box"
  config.vm.hostname = 'myvm'

  config.ssh.forward_agent = true
  config.ssh.default.username = "kkharma"
  config.ssh.insert_key = false

  config.vm.define "myvm" do |myvm|
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "myvm"
  end
end
```

### Expected behavior
vagrant up using machine id should start the VM.  other vagrant commands like halt work fine using the id.  running vagrant up in the Vagrantfile directory also works fine.

### Actual behavior
```
% vagrant up <machine-id>
The machine with the name 'myvm' was not found configured for
this Vagrant environment.
```

### Steps to reproduce
1. run vagrant up using machine id

### More info
```
% VBoxManage list vms
"myvm" {<vm-uuid>}
```

```
% vagrant global-status
id       name     provider   state    directory
------------------------------------------------------------------------------
<machine-id>  myvm virtualbox poweroff /Users/kkharma/Library/Vagrant/myvm
```

**Comment by chrisroberts** [comment]
Hi there. This is the expected behavior of Vagrant. When running a `vagrant up`, the Vagrantfile must be processed to properly configure the VM. Some commands (like `halt`) work fine with only the ID because at times it is necessary to stop a VM while not being able to easily identify the origin. For command like `up`, there is more involved than just starting the VM, which is why only providing an ID is not sufficient. 

Cheers!

**Comment by kkharma** [comment]
that's odd because earlier versions of vagrant supported this.  if the `global-status` command has awareness of the machine id, then why wouldn't `up`?

also:
```
% vagrant help up
Usage: vagrant up [options] [name|id]

Options:

        --[no-]provision             Enable or disable provisioning
        --provision-with x,y,z       Enable only certain provisioners, by type or by name.
        --[no-]destroy-on-error      Destroy machine if any fatal error happens (default to true)
        --[no-]parallel              Enable or disable parallelism if provider supports it
        --provider PROVIDER          Back the machine with a specific provider
        --[no-]install-provider      If possible, install the provider if it isn't installed
    -h, --help                       Print this help
```

notice that `id` is listed as a valid argument.  i think this issue should be reopened to at least fix the docs.
