### ISSUE TITLE
The 'reload' provisioner could not be found

### ISSUE THREAD

**Issue by njgwbn** [mitchellh/vagrant#8417]
When I use  metasploitable3.
Why still report error "* The 'reload' provisioner could not be found."?
Thanks

  virtualbox-iso (vagrant): Compressing: packer-virtualbox-iso-1490534292-disk001.vmdk
Build 'virtualbox-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> virtualbox-iso: 'virtualbox' provider box: windows_2008_r2_virtualbox.box
PS D:\VM\metasploitable3-master>

PS D:\vm\metasploitable3-master> vagrant --version
Vagrant 1.9.3

PS C:\Users\c> vagrant plugin install vagrant reload
Installing the 'vagrant' plugin. This can take a few minutes...
Installed the plugin 'vagrant (1.9.3)'!
Installing the 'reload' plugin. This can take a few minutes...
Installed the plugin 'reload (1.0.0)'!

PS D:\vm\metasploitable3-master> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'reload' provisioner could not be found.
* The 'reload' provisioner could not be found.
PS D:\vm\metasploitable3-master>

**Comment by chrisroberts** [comment]
Hi there. It looks like the command you ran to install the plugin was not quite correct. The command you ran:

```
PS C:\Users\c> vagrant plugin install vagrant reload
```

is instructing vagrant to install the plugins: `vagrant` and `reload`. The plugin you want to install is `vagrant-reload` so your command should look like this:

```
PS C:\Users\c> vagrant plugin install vagrant-reload
```

Cheers!

**Comment by njgwbn** [comment]
Thanks!
