### ISSUE TITLE
Vagrant does not pick the correct box version when multiple box versions available locally

### ISSUE THREAD

**Issue by gokhansengun** [mitchellh/vagrant#8420]
Note: This is a minor issue caused by string sorting in numbers (where `1.0.9` is considered greater than `1.0.10`) which I will send a PR shortly. This is to track the issue.

$ vagrant -v
Vagrant 1.9.0

Host:
Running os OS X

Guest:
Ubuntu LTS 16.04.1

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "gsengun/dev-box"
end
```

### Expected behavior
1. Vagrant should be able to use the latest version (`1.0.10`), when the box version is not specified in the Vagrantfile even when box versions `1.0.9` and `1.0.10` of the same box are available locally.

2. `$ vagrant box list` command should sort image versions correctly.

### Actual behavior
1. Vagrant does not pick the correct box version `1.0.10` to `up` the virtual machine with. Several box versions (`1.0.9`) available **locally** and the latest box version is `1.0.10` (or higher). Vagrant picks version `1.0.9` instead of `1.0.10`.

2. `$ vagrant box list` command does not sort image versions correctly.

```
$ vagrant box list
gsengun/dev-box                          (virtualbox, 1.0.10)
gsengun/dev-box                          (virtualbox, 1.0.8)
gsengun/dev-box                          (virtualbox, 1.0.9)
```

### Steps to reproduce
1. Download and register box `gsengun/dev-box` version `1.0.9` locally
2. Download and register box `gsengun/dev-box` version `1.0.10` locally
3. Create a new virtual machine with `vagrant init gsengun/dev-box --minimal`
4. Run `vagrant up` and see that version `1.0.9` is selected instead of `1.0.10`

**Comment by gokhansengun** [comment]
Seems to be the duplicate of #7582 and been fixed already. Though I think I found a small regression in `vagrant box list` command's output to which I send a small PR now.

**Comment by chrisroberts** [comment]
Yep, this has already been fixed and released. Cheers!

**Comment by gokhansengun** [comment]
Wait, I just send a PR #8422 for the output of `vagrant box list`.
