### ISSUE TITLE
vagrant static dependencies are a pain

### ISSUE THREAD

**Issue by oxitech239** [mitchellh/vagrant#8424]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
compiling vagrant from source

### Host operating system
Sabayon 16/Gentoo

### Guest operating system
N/A

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
bundle install should not have returned a dependency issue

### Actual behavior
$ bundle install
Fetching https://github.com/mitchellh/vagrant-spec.git
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    vagrant was resolved to 1.8.7, which depends on
      bundler (= 1.12.5)

  Current Bundler version:
    bundler (1.14.6)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (= 1.12.5)', which is required by gem 'vagrant', in any of the sources.

### Steps to reproduce
1. install vagrant from repo ( dependency issue on childprocess 0.5 while installed is 0.6
2. attempt to compile vagrant from source
3. possible others

### References
none found at this time

**Comment by oxitech239** [comment]
after changin dependency qualifiers to >= for ruby-version and bundler this it the new point of stuckness

bundle install
Fetching https://github.com/mitchellh/vagrant-spec.git
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    vagrant was resolved to 1.8.7, which depends on
      ruby (>= 2.2)

Could not find gem 'ruby (>= 2.2)', which is required by gem 'vagrant', in any of the sources.

**Comment by chrisroberts** [comment]
Hi there. These constraints have been either relaxed or removed in the latest version of Vagrant. 

Cheers!
