### ISSUE TITLE
Malformed version number string darwin

### ISSUE THREAD

**Issue by ngpestelos** [mitchellh/vagrant#8452]
### Vagrant version

1.9.3

### Host operating system

OS X 10.12.3

### Guest operating system

Ubuntu 14.04.5 (bento/ubuntu-14.04)

### Vagrantfile

https://gist.github.com/ngpestelos/34faf03bd7e2b8808f13b594ec87d501

### Debug output

https://gist.github.com/ngpestelos/f0cfd9540de88730a847cebbc119b744

### Expected behavior

Plugins detected and updated.

### Actual behavior

Shell returned an error.

### Steps to reproduce

1. run `vagrant plugin update`

### References

n/a

**Comment by chrisroberts** [comment]
Hi there. Can you please provide a gist of the full output from:

```
$ vagrant plugin update --debug
```

Thanks!

**Comment by ngpestelos** [comment]
https://gist.github.com/ngpestelos/5c326a0080d9c8437a146b7cc275c6d3
