### ISSUE TITLE
Error while trying to install plugin - 405 "Method Not Allowed"

### ISSUE THREAD

**Issue by TrayWeb** [mitchellh/vagrant#8455]
Hi,

I'm battling with this issue and can't find a trick to fix it.

### Steps to reproduce
I had my virtual machine launched and working.
Once installing other tool to the computer, I've accidentally erase my path but didn't notice it at the moment. Once the computer had rebooted, I couldn't launch my VM anymore, so I've tried to vagrant provision but it didn't work, neither vagrant up / halt / reload / destroy.

So I've decided to reinstall vagrant and I'm now stuck with the following issue... I then realized that I had deleted many things in my path, so It might come from there but I'm not really sure as I've reinstalled most of the tool needed.

Thanks for your help.

### Vagrant version
Vagrant 1.8.5
Same issue on agrant 1.9.3 but Trellis recommend 1.8.5

### Host operating system
Windows

### Guest operating system
Nothing set yet

### Vagrantfile
```ruby
Not sure which file is it ?
```

### Debug output
https://gist.github.com/TrayWeb/48d21fd46bc487cc256ce46c6523f19b

### Expected behavior
from previous successful attempts, I know this command should install the plugin !

### Actual behavior
```
$ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http/response.rb:119:in `error!                                          ': 405 "Method Not Allowed" (Net::HTTPServerException)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/net/http/response.rb:1                                          28:in `value'
       ........
       ........
```
Complete list of file available on the debug output

**Comment by kikitux** [comment]
@TrayWeb perhaps is an issue with the plugin?

https://github.com/devopsgroup-io/vagrant-hostmanager/issues/227

**Comment by TrayWeb** [comment]
Hi @kikitux thanks for the answer.
i've also tried to install other plugins and I get the same errors :(

**Comment by chrisroberts** [comment]
@TrayWeb Hi there. I have been trying to reproduce the error you are experiencing and have so far been unsuccessful. Are you working behind a network proxy?

**Comment by TrayWeb** [comment]
Hi @chrisroberts, thank you for taking time to look at it.

I was initially through a proxy but I've asked the network admin to put me off the time to work on it.
Also, I've previously managed to install this plugin and other ones before so I don't think the issue comes from there.

I've logged a ticket with ruby, I keep you posted if they find something on their side.

**Comment by chrisroberts** [comment]
@TrayWeb were you able to install the plugins once you were outside the proxy?

**Comment by TrayWeb** [comment]
Hi @chrisroberts Yes it worked before and not anymore, proxy or not.
I think the issue is more related to what I had on the path ? or maybe because I have uninstall and resinstall Vagrant ? I've tried to uninstall most of the new software installed and redo it from scratch but I still get the same issue. It works perfectly on my mac on the same network.

**Comment by chrisroberts** [comment]
Do you have ruby installed on this system? Do regular `gem install`s work?

**Comment by TrayWeb** [comment]
Thanks for the answer.
Indeed I have ruby installed however a gem install doesn't work:

`bezy-r@TI518 MINGW64 /
$ gem install rail
ERROR:  While executing gem ... (Net::HTTPServerException)
    405 "Method Not Allowed"
`

**Comment by chrisroberts** [comment]
@TrayWeb The 405 error you are getting looks suspiciously like a proxy issue (perhaps originating from a transparent squid proxy?). Would you please run:

```
$ gem install yard --no-document --verbose --debug
```

and paste in the output. Thanks!

**Comment by TrayWeb** [comment]
Hi, thanks for helping.
The network admin said that there is no transparent proxy once he put me out of the normal proxy.

Please see below what I got when running the command:

`$ gem install yard --no-document --verbose --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - The system cannot find the file specified.
Exception `Win32::Registry::Error' at C:/Ruby23/lib/ruby/2.3.0/win32/registry.rb:250 - No more data is available.
Exception `Net::HTTPServerException' at C:/Ruby23/lib/ruby/2.3.0/net/http/response.rb:120 - 405 "Method Not Allowed"
Exception `Net::HTTPServerException' at C:/Ruby23/lib/ruby/2.3.0/net/http.rb:950 - 405 "Method Not Allowed"
ERROR:  While executing gem ... (Net::HTTPServerException)
    405 "Method Not Allowed"
        C:/Ruby23/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
        C:/Ruby23/lib/ruby/2.3.0/net/http/response.rb:129:in `value'
        C:/Ruby23/lib/ruby/2.3.0/net/http.rb:920:in `connect'
        C:/Ruby23/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        C:/Ruby23/lib/ruby/2.3.0/net/http.rb:858:in `start'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request/http_pool.rb:43:in `setup_connection'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request/https_pool.rb:7:in `setup_connection'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request/http_pool.rb:39:in `make_connection'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request/http_pool.rb:20:in `checkout'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request.rb:86:in `connection_for'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request.rb:141:in `perform_request'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/request.rb:110:in `fetch'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/remote_fetcher.rb:372:in `request'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/remote_fetcher.rb:245:in `fetch_http'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/remote_fetcher.rb:283:in `fetch_path'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/source.rb:92:in `dependency_resolver_set'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:24:in `block in pick_sets'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each_source'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:23:in `pick_sets'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:29:in `find_all'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:152:in `find_all'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:55:in `add_always_install'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:239:in `install_gem'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
        C:/Ruby23/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
        C:/Ruby23/bin/gem:21:in `<main>'
`

**Comment by chrisroberts** [comment]
I'm unable to reproduce this error locally, and it looks very much like a transparent proxy issue. If you are able to reproduce this error on a different network, please feel free to re-open this issue or create a new one. Cheers!

**Comment by Tekover** [comment]
Hi @chrisroberts,

We have been able to install the plugin on a colleague's computer, part of the same network so It can't be a proxy issue. However, as it worked at a first stage, I do believe it has to be related to my PC.

I've uninstall everything and removed my vagrant user data but still the same.

Do you have any idea of what else I can try to reset a setting that would cause the issue ?

**Comment by Tekover** [comment]
Hi, Problem fixed.
While installing something else it gave me more details on the problem which came indeed from the proxy.
The solution for me was to run the command through the proxy with the env variable http_proxy set to :
http://user:pass@proxyurl:XXX, and the https_proxy variable deleted
However it's still a mistery why it didn't work when I was out of the proxy ? I guess the setting was expecting one ?
