### ISSUE TITLE
sudo is asking password very late

### ISSUE THREAD

**Issue by tncyysl** [mitchellh/vagrant#8460]
i want to manage paswordless and then i'm adding below lines in the sudoers file,

`Cmnd_Alias VAGRANT_HOSTS = /bin/cp /Users/Tuncay/.vagrant.d/tmp/hosts.local /etc/hosts`
`%sudo ALL=(root) NOPASSWD: VAGRANT_HOSTS`

but i've problems when i use `sudo` that almost get reaction 3-5 after minutes..

 if i add comment, it's work!

```
➜  ~ vagrant -v
Vagrant 1.9.3
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195
```

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by tncyysl** [comment]
Hello!

Thank you for assist this issue & information. But i fixed temporarily when i added in the line below.

`Defaults timestamp_timeout=5` 👍🏽
