### ISSUE TITLE
After removing the Vagrant file VMs are still running 

### ISSUE THREAD

**Issue by confisurya** [mitchellh/vagrant#8470]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.
Ubuntu 16.04

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?
after removing the Vagrantfile i should be able to stop/destroy the running the machine

### Actual behavior
What actually happened?
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ sudo vagrant destroy test_vm
The machine with the name 'test_vm' was not found configured for
this Vagrant environment.

### Steps to reproduce
1. Create and run vagrant up
2. remove the vagrant file 
3. Destroy the running VM

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
Hi there. Just removing the Vagrantfile will not stop or delete VMs that Vagrant has been managing. You must use `vagrant halt` to stop them and `vagrant destroy` to remove them. If the Vagrantfile is already gone, you can use `vagrant global-status` to help identify VMs that should be destroyed. Cheers!

**Comment by confisurya** [comment]
@chrisroberts yes Vagrantfile has gone and a i want to destroy the VM but they are still running.

**after running the destroy command i ran into this**

===========================================================================
ubuntu@openstack-nti-3:~/vagrantSetup$ 
ubuntu@openstack-nti-3:~/vagrantSetup$ 
ubuntu@openstack-nti-3:~/vagrantSetup$ vagrant global-status
id       name    provider   state    directory                                           
-----------------------------------------------------------------------------------------
e78b907  control libvirt    shutoff  /home/ubuntu/vagrantSetup/ubuntu-16.04-server-amd64 
e2eecbd  network libvirt    shutoff  /home/ubuntu/vagrantSetup/ubuntu-16.04-server-amd64 
c94317f  test_vm libvirt    running  /home/ubuntu/vagrantSetup/ubuntu-16.04-server-amd64 
c7434a6  storage libvirt    running  /home/ubuntu/vagrantSetup/ubuntu-16.04-server-amd64 
ec02cbe  kube1   virtualbox poweroff /home/ubuntu/halcyon-vagrant-kubernetes             
7662b3e  default libvirt    running  /home/ubuntu/vagrantSetup/Vm1                       
242f906  default libvirt    running  /home/ubuntu/vagrantSetup/Vm2                       
748a9a5  default libvirt    running  /home/ubuntu/vagrantSetup/Vm3                       
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
ubuntu@openstack-nti-3:~/vagrantSetup$ 
ubuntu@openstack-nti-3:~/vagrantSetup$ 
ubuntu@openstack-nti-3:~/vagrantSetup$ cd /home/ubuntu/vagrantSetup/ubuntu-16.04-server-amd64
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ pwd
/home/ubuntu/vagrantSetup/ubuntu-16.04-server-amd64
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ ls
Vagrantfile
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ vagrant destroy c94317f
The machine with the name 'test_vm' was not found configured for
this Vagrant environment.
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ sudo vagrant destroy c94317f
The machine with the name 'test_vm' was not found configured for
this Vagrant environment.
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ sudo vagrant destroy test_vm
The machine with the name 'test_vm' was not found configured for
this Vagrant environment.
ubuntu@openstack-nti-3:~/vagrantSetup/ubuntu-16.04-server-amd64$ 
==============================================================================
