### ISSUE TITLE
"vagrant ssh" not working while vm is running 

### ISSUE THREAD

**Issue by confisurya** [mitchellh/vagrant#8475]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.8.1

### Host operating system
ubuntu 16.04

### Guest operating system
ubuntu 16.04

### Vagrantfile
ubuntu@openstack-nti-3:~/vagrantSetup/Vm1$ cat Vagrantfile 
Vagrant.configure(2) do |config|
  config.vm.box = "peru/ubuntu-16.04-server-amd64"
  config.vm.hostname = "Vmachine1"
  config.vm.provider "libvirt" do |vb|
      vb.memory = "8192"
  end
end

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
Either VM should not be in running state or vagrant ssh should give proper message like "memory is full to log in"

### Actual behavior
not able to ssh into while VM is running

### Steps to reproduce
1. vagrant up 
2. Full the memory allocated in vagrant file
3. vagrant status
4. vagrant ssh

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by confisurya** [comment]
update the description tab, I thought updating current ticket would be enough. Thanks for comment though.

**Comment by chrisroberts** [comment]
The provider in use (libvirt) is not a supported provider of Vagrant. If you experience the same issue using a provider built into Vagrant, please open a new issue. Issues with the libvirt plugin can be directed to the project's GH repository: https://github.com/vagrant-libvirt/vagrant-libvirt

Cheers!
