### ISSUE TITLE
package box in suspend status not halt

### ISSUE THREAD

**Issue by skyscreen** [mitchellh/vagrant#8481]
### Expected behavior
What should have happened?
when suspend the vm with vagrant suspend，to package the box(vagrant package --base...)
should see vm the status still is suspend, and hot backup.
### Actual behavior
What actually happened?
see the vm status, halt,

**Comment by chrisroberts** [comment]
@skyscreen Hi there. Is the issue that the VM on the host machine is transitioning from `suspend` state to `halt` state after running `vagrant package` ?

**Comment by skyscreen** [comment]
yes, can it save the running all state for backup?

**Comment by chrisroberts** [comment]
Hi there,

The package command is not intended for "hot backup" style generation of boxes.

Cheers!
