### ISSUE TITLE
vagrant calling "C:\\Program Files\\Git\\usr\\bin/ssh.EXE" on windows 10

### ISSUE THREAD

**Issue by Bergur1** [mitchellh/vagrant#8483]
### Vagrant version
1.9.3

### Host operating system
Windows 10

### Guest operating system
Centos/7

### Vagrantfile
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder "D:\\", "/vagrant", type: "virtualbox"

 end

### Debug output
https://gist.github.com/Bergur1/352c3ed3820c3423d58df332aff455bf

### Expected behavior
What should have happened?
I should be able to SSH into the centos VM

### Actual behavior
What actually happened?
The console hangs until a timeout, then it exits. It looks like vagrant is incorrectly referencing the ssh executable.

There are workarounds but they are hacks that only work on older versions of vagrant or they require putty, neither of which are ideal.

### Steps to reproduce
1. Install Vagrant
2. Install Git Bash for Windows (2.1.2)
3. Set PATH variables for the SSH executable
4. vagrant up
5. vagrant ssh

### References
Are there any other GitHub issues (open or closed) that should be linked here?
- https://github.com/mitchellh/vagrant/issues/7512

**Comment by chrisroberts** [comment]
Hi there. I have reproduced your environment (Win10 + vbox + git bash + vagrant) and brought up the `centos/7` box without any issue. Looking at your debug output, there is no problem with calling the `ssh.exe` executable. While the path separators may not be consistent within the debug output, they are cleaned on execution. The debug also confirms that the ssh executable is found as it successfully responds to a test call here: https://gist.github.com/Bergur1/352c3ed3820c3423d58df332aff455bf#file-gistfile1-txt-L1263-L1266

This line in the debug output https://gist.github.com/Bergur1/352c3ed3820c3423d58df332aff455bf#file-gistfile1-txt-L1275 is the connection being attempted. As this is the last line of the debug output, I'm assuming it just hangs here. Can you confirm that the guest is properly accepting new SSH connections?

**Comment by Bergur1** [comment]
I tried to ssh in and couldn't which meant that my box wasn't being provisioned properly. It looks like it was having problems interacting with the provider. It couldn't interact with the provider because hyper-v was enabled. Disabling Hyper-v fixed or switching providers fixed the problem.
