### ISSUE TITLE
Windows provision not working with vagrant 1.9.3 and chef

### ISSUE THREAD

**Issue by athreyavc1** [mitchellh/vagrant#8484]
Hi, 

I am trying to setup a windows2012r2 VM(on virtual box). I was on vagrant 1.6.3 with VirtualBox 4.3 on a centOS Box and all worked fine. Recently I updated vagrant version to 1.9.3 and updated all the plugins and since then it just does not work. 

My Vagrantfile is here 

https://github.com/athreyavc1/multivm/blob/master/Vagrantfile

vagrant up results in Linux VM getting setup right. However for windows VM, I get the error

GuestMemoryBalloon=0
GuestOSType="Windows81_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.0.4 r102546"
GuestAdditionsFacility_VirtualBox Base Driver=50,1492346276243
GuestAdditionsFacility_VirtualBox System Service=50,1492346293202
GuestAdditionsFacility_Seamless Mode=0,1492346276241
GuestAdditionsFacility_Graphics Mode=0,1492346276239
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Recovery complete.
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x000000039cff38>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-8489c4c1e9cdf8e3c145edc3b65e2671
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000002bd38f8>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::Chef::Provisioner::Base::ChefError: Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.>
ERROR vagrant: Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
ERROR vagrant: /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/provisioners/chef/provisioner/chef_client.rb:108:in `run_chef_client'

**Comment by athreyavc1** [comment]
I am running Centos 7.2, vagrant 1.93, 4.3(I have also tried with 5.1) issue is same

**Comment by chrisroberts** [comment]
Hi there. From the log snippet provided it seems as though the chef provisioning is failing (likely due to an error from a cookbook). To confirm, please provide a gist of the entire debug output for the failed run. Thanks!

**Comment by athreyavc1** [comment]
Hi, Please find the full log here,

https://github.com/athreyavc1/multivm/blob/master/screen.log
there only one coobook assigned to windows, it is chocolatey. Linux works perfectly fine. 
Regards,

Athreya

**Comment by athreyavc1** [comment]
Intially I tried to setup a FQDN for the VM, that failed too.

**Comment by chrisroberts** [comment]
Looks you need to adjust how you set the path to your validation key as that's causing the error. From the output:

```
 INFO interface: info: [2017-04-16T09:44:56-07:00] FATAL: Chef::Exceptions::PrivateKeyMissing: I cannot read c:ef/validation.pem, which you told me to use to sign requests!
```

Fix up that path and you should be good to go. Cheers!

**Comment by athreyavc1** [comment]
Sorry It might be really a stupid question. Where should the validation.pem should be ?

if this is my code to provision a WIndows VM, 

  config.omnibus.chef_version = :latest
  config.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://api.chef.io/organizations/test-lab-athreya"
    chef.validation_key_path = "~/.chef/validation.pem"
    chef.validation_client_name = "test-lab-athreya-validator"
    chef.node_name = "server"
  end

I have place the validation.pem here,

ls -l ~/.chef/validation.pem 
-rw-r--r--. 1 learn learn 1679 Apr 16 16:19 /home/learn/.chef/validation.pem

This path is accessible by the user "learn" who is running the vagrant up

Regards,

**Comment by athreyavc1** [comment]
Hi, I think I finally made good progress on this, 

https://github.com/athreyavc1/testingchef/blob/master/Vagrantfile

This seem to working
