### ISSUE TITLE
The box failed to unpackage properly.

### ISSUE THREAD

**Issue by Cybs** [mitchellh/vagrant#8487]
### Vagrant version
1.9.3

### Host operating system
mac 10.11.6

### Guest operating system
unknow

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "v5vm"

  #config.vm.synced_folder "/Users/wangchao/Documents/MyWork/v5","/var/www/html", owner: "vagrant", group: "vagrant"
  config.vm.synced_folder "/Users/Cybs/Documents/companyDocs/V5-admin","/var/www/html", owner: "nginx", group: "nginx", :mount_options => ["dmode=0777","fmode=0777"]

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
 config.vm.network "private_network", ip: "192.168.33.139"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end
end
```

### Debug output
[https://gist.github.com/Cybs/c9492aa4a29d2840a40903468b34cadf](https://gist.github.com/Cybs/c9492aa4a29d2840a40903468b34cadf)

I tried to add a local box. But it failed. 

![image](https://cloud.githubusercontent.com/assets/2275676/25083145/f5487f9a-2387-11e7-8efc-8d427b44c8aa.png)

**Comment by chrisroberts** [comment]
Does the host machine have enough free disk space to unpack the box?

**Comment by Cybs** [comment]
I resolved it.  The box file is corrupted. I replaced it with a new one and it was ok. Thanks!
