### ISSUE TITLE
Update bundled ruby?

### ISSUE THREAD

**Issue by fnordfish** [mitchellh/vagrant#8490]
Would it be possible to update the bundled ruby (2.2.5)?
Upgrading to ruby 2.2.7 should probably give the least friction.

Background:

Beside the obvious, removing bugs in ruby, it would help developing plugins which depend on 3rd party ruby-gems. Most gems start to deprecate usage of older rubies, in particular requiring ruby >= 2.2.6. For a specific example see BerlinVagrant/vagrant-dns#48 / BerlinVagrant/vagrant-dns#49

**Comment by chrisroberts** [comment]
Updated in the installer repo. Next release will move to the 2.3.x tree.
