### ISSUE TITLE
Vagrant hangs indefinitely at : "Booting the VM" /"Selecting an IO"

### ISSUE THREAD

**Issue by ananya0631** [mitchellh/vagrant#8492]
Having trouble starting a vagrant share on windows.  It hangs at "Selecting an IO". Below are the details, hoping someone has some hints how to get past this point. 

### Vagrant version
Vagrant 1.9.1

### Host operating system
Windows10

### Guest operating system
Windows7 
BOX used: 
### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "inclusivedesign/windows7-eval-x64"

    config.vm.network :forwarded_port, guest:4444, host:5566
  config.vm.network "public_network"
  config.vm.provision "shell", path: "script.sh"
  config.ssh.insert_key = false		
  config.vm.provider :virtualbox do |vb|
    vb.gui = true
vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
  end
end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
.https://gist.github.com/ananya0631/3db1b93e24946834ab7e4bab4a841832 

### Expected behavior
The vagrant command should be succesfully compeleted

### Actual behavior
Stuck at ::""Selecting an IO" in debug mode and "Booting VM" in non-debug mode

### Steps to reproduce
1. vagarnt init "inclusivedesign/windows7-eval-x64"
2. vagrant up

- ...

**Comment by chrisroberts** [comment]
Hi there. This line in your Vagrantfile:

```ruby
vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
```

is likely causing the problem. This disables hardware virtualization and without that enabled 64bit guests will fail to properly boot. Cheers!
