### ISSUE TITLE
Vagrant up error.

### ISSUE THREAD

**Issue by krischal** [mitchellh/vagrant#8501]
Today suddenly i got the following error while doing vagrant up. Can some on please help me to fix this.

E:\csy2028\website>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'csy2028/current' is up to date...
==> default: A newer version of the box 'csy2028/current' is available! You currently
==> default: have version '1.8'. The latest is version '1.9'. Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 80 => 8080. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: You are trying to forward to privileged ports (ports <= 1024). Most
==> default: operating systems restrict this to only privileged process (typically
==> default: processes running as an administrative user). This is a warning in case
==> default: the port forwarding doesn't work. If any problems occur, please try a
==> default: port higher than 1024.
==> default: Forwarding ports...
    default: 80 (guest) => 2200 (host) (adapter 1)
    default: 80 (guest) => 80 (host) (adapter 1)
    default: 3306 (guest) => 3307 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "aa896d75-2bec-452f-833d-6a8a95ba125c", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'csy2028_default_1488103573183_8373' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

E:\csy2028\website>

**Comment by philippe-granet** [comment]
Look in VBox.log or VBoxHardening.log, you may have more informations about the error

**Comment by damienrave** [comment]
Hi there, did you upgrade to Windows 10 Creators Edition ? The same bug happened to me and the proposed fix on SO is to upgrade VirtualBox to the latest version : https://superuser.com/questions/1199354/virtualbox-no-longer-running-in-win10-creators-update

Not tested but worth trying

**Comment by thomthom** [comment]
@damienrave bingo! I was having the same issue on my machine after the Creators Update. My Laravel Homestead box was suddenly not booting. Installing the latest (5.1.22) instantly fixed it for me.

**Comment by chrisroberts** [comment]
@krischal Are you still experiencing this issue?

**Comment by Zmoki** [comment]
I still.
On my machine Windows 10 Creators Update and after last update (Windows 10 Insider Preview 16237.1001 (rs_prerelease)) VirtualBox doesn't start. I updated vagrant and virtualbox to latest. I tried destroy, boxes removing, still doesn't work.

```bash
λ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20170302.0.0'. The latest is version '20170619.0.0'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: uploadcare-widget_default_1499800494801_19042
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3000 (guest) => 6000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "6dbd09bc-882f-4af4-b2fe-f96205563974", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'uploadcare-widget_default_1499800494801_19042' has terminated unexpe
ctedly during startup with exit code 1 (0x1).  More details may be available in 'D:\VM\uploadcare-widget_default_1499800
494801_19042\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
```

**Comment by Zmoki** [comment]
I reverted to Windows 10 Insider Preview 16232 and it help

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by haotangio** [comment]
@thomthom Worked like a charm. Thanks!

**Comment by artnet** [comment]
I just had the same problem after the Windows 10 update. I solved it by installing the newest version of VirtualBox and Vagrant. Then I had to repair plugins with `vagrant plugin repair` and now it works again.

**Comment by thomthom** [comment]
@artnet is this after the latest Creator Fall update?

**Comment by webprogrammierer** [comment]
I have the same problem after the Window 10 update. I updated VirtualBox to 5.1.30.
Now I can can start my Drupal VM but at "vagrant up" I get the following info:

```
==> drupalvm: Checking for guest additions in VM...
    drupalvm: The guest additions on this VM do not match the installed version of
    drupalvm: VirtualBox! In most cases this is fine, but in rare cases it can
    drupalvm: prevent things such as shared folders from working properly. If you see
    drupalvm: shared folder errors, please make sure the guest additions within the
    drupalvm: virtual machine match the version of VirtualBox you have installed on
    drupalvm: your host and reload your VM.
    drupalvm:
    drupalvm: Guest Additions Version: 5.0.24
    drupalvm: VirtualBox Version: 5.1
```

What does this mean and what should I do to get rid of this message?

**Comment by jeversen** [comment]
Same problem here. Reinstalled VirtualBox (5.2.4) but still no go. Then reinstalled Virtualbox (5.1.30) and everything worked again.

**Comment by felipemarques** [comment]
after i install Windows updates my Vagrant and Virtualbox had problems. I had to reinstall Virtualbox and Vagrant ... and all works fine now.

**Comment by angelburov** [comment]
@artnet It was the same here... The problem happened after installing Windows 10 Creators update (1709).
Installing the newest version of VirtualBox and Vagrant and then repairing the plugins conflicts did the trick for me.

**Comment by ericdost** [comment]
FYI - I had the same issue recently and it was due to Cylance AV not liking VirtualBox.
