### ISSUE TITLE
vagrant ssh exits with status 0 when not running

### ISSUE THREAD

**Issue by agriffis** [mitchellh/vagrant#8508]
Running `vagrant ssh` exits with status 0 when the VM isn't running. This is a problem for scripts that call `vagrant ssh -- some command` and inspect the exit status to determine if the command executed successfully.

### Vagrant version
1.8.5

### Host operating system
Fedora

### Guest operating system
Debian

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.provider :docker do |docker, override|
    docker.image = ENV.fetch("VAGRANT_DOCKER_IMAGE", "jesselang/debian-vagrant:jessie")
    docker.has_ssh = true
  end
  config.ssh.forward_agent = true  # for github in VM
  config.vm.provision :shell, path: "provision.bash"
end
```

### Debug output
https://gist.github.com/agriffis/848d249b51a52153fadc6ac6e353eaf0

### Expected behavior
It should have returned a non-zero exit status, because it wasn't able to run the command. Compare to `ssh no-such-hostname.example.com echo hi` which returns exit status 255

### Actual behavior
It displayed an error (on stdout!) and returned a zero exit status

### Steps to reproduce
1. vagrant halt
2. vagrant ssh (or vagrant ssh -- echo hi)
3. echo $?

**Comment by chrisroberts** [comment]
Hi there. I'm not seeing this behavior currently with Vagrant and the vbox provider:

```
○ → vagrant ssh -- /bin/false; echo $?
VM must be running to open SSH connection. Run `vagrant up`
to start the virtual machine.
1
```

which leads me to believe this may be isolated to the docker provider. I'll get a repro going with that provider to confirm if this is still an issue currently.

**Comment by agriffis** [comment]
@chrisroberts Hey, thanks for looking into this. The two providers I have handy are docker and libvirt. It seems to be a problem on libvirt too.

```
$ vagrant status
Current machine states:

default                   shutoff (libvirt)

The Libvirt domain is not running. Run `vagrant up` to start it.

$ vagrant ssh ; echo $?
==> default: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
0

$ vagrant ssh -- /bin/false ; echo $?
==> default: Domain is not running. Please run `vagrant up` or `vagrant resume` first.
0
```

**Comment by chrisroberts** [comment]
@agriffis So after getting it reproduced locally and comparing the implementation difference between the docker provider and the virtualbox provider I see that where the virtualbox provider will raise an exception if the requested machine is not running, the docker provider only makes a note and allows continuation. This "note only" behavior is also implemented in the hyperv provider. I'll look at getting both the docker and hyperv providers updated to make the behavior expected and consistent.

**Comment by agriffis** [comment]
Thanks @chrisroberts!
