### ISSUE TITLE
Suggestion: Executing Vagrant without default providers

### ISSUE THREAD

**Issue by asadpiz** [mitchellh/vagrant#8509]
Hi, I just wanted to suggest the possibility of running "vagrant up" without any providers installed. My build server is an AWS EC2 instance. Which has to launch a few other EC2 instances for testing purposes. I'm trying to use Vagrant for it but it's failing because there is no default provider on the EC2 instance (I intend to launch EC2 instances so having virtualbox or any other provider shouldn't be a requirement).

I wanted to ask if it's possible to: 

- Run vagrant from inside Amazon EC2 instances without a hypervisor (I've tried adding the dummy box)
- If there's a better way, all use cases of AWS vagrant that i've come across involve using a physical server to launch EC2 instances. (I'm leaning towards using server configuration tools like Puppet, Chef instead).

### Vagrant version
Vagrant 1.9.3

### Host operating system
Ubuntu Server 14 (AWS EC2)
### Guest operating system
Ubuntu Server 14 (AWS EC2)

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|

  # Use dummy AWS box
  config.vm.box = 'aws-dummy'

  # Specify AWS provider configuration
  config.vm.provider 'aws' do |aws, override|
    # Read AWS authentication information from environment variables
    aws.access_key_id = ENV['ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SECRET_ACCESS_KEY']

    # Specify SSH keypair to use
    aws.keypair_name = 'keypairname'

    # Specify region, AMI ID, and security group(s)
    aws.region = 'us-east-1'
    aws.ami = 'ami-xyz'
    aws.security_groups = ['default']

    # Specify username and private key path
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = 'key.ppk'
  end
end

```

### Debug output
https://gist.github.com/asadpiz/80cf9ebbb3216e04c908ec9d24ba843e

### Expected behavior
vagrant up should work without requiring virtualbox (as the hypervisor is AWS)
### Actual behavior
Vagrant requires hypervisor
### Steps to reproduce
1. vagrant up --provider=aws
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
Hi there. It looks like the problem you are encountering is that you do not have the `vagrant-aws` plugin installed, which is what your Vagrantfile is expecting. Running:

```
$ vagrant plugin install vagrant-aws
```

should resolve your issue. Cheers!
