### ISSUE TITLE
ubuntu/xenial64 not installing the correct guest additions

### ISSUE THREAD

**Issue by parsemaestro63** [mitchellh/vagrant#8511]
### Vagrant version
$ vagrant -v
Vagrant 1.9.3

### Host operating system
Mac OS Sierra 10.12.4

### Guest operating system
Ubuntu 16.04 (Ubuntu/Xenial64 box)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "shell", path: "./bootstrap/scripts/bootstrap.sh"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.50.5"

  config.vm.synced_folder "myproject", "/var/www/myproject", nfs: true

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
	  v.cpus = 2
	end

end

```

### Debug output
https://gist.github.com/parsemaestro63/649be60448ecb349b884a21a4f1a11e5

### Expected behavior
I swapped ubuntu/trusty64 for ubuntu/xenial64, and experienced guest additions errors.

The host and VM report as having different guest additions versions. 

I eventually fixed the issue by symlinking mount.vboxsf to /sbin inside the VM. Ref: https://github.com/mitchellh/vagrant/issues/6769. This is not an optimal solution for me, as each time the VM is destroyed and created, the fix needs applying.

### Actual behavior
The provisioning come to the point to mount, then errors and quits.

Error output during guest additions installation:
"Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.36
VBoxService inside the vm claims: 5.1.20
Going on, assuming VBoxService is correct..."

Mount error:
"Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: wrong fs type, bad option, bad superblock on vagrant,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so."

### Steps to reproduce
1. ```vagrant up``` from a clean state

### References
https://github.com/mitchellh/vagrant/issues/6769

**Comment by chrisroberts** [comment]
Hi there. This was a bug in the VirtualBox guest additions and is a dup of #8502. The box needs to be rebuilt using the latest version of the guest additions. Cheers!
