### ISSUE TITLE
Default SSH port forward binding to 0.0.0.0, not 127.0.0.1 - vmware-workstation provider

### ISSUE THREAD

**Issue by pgrohe** [mitchellh/vagrant#8513]
Using the vmware_workstation provider,  Vagrants default SSH port forward of Guest 22 -> Host 2222 will occur on IP 0.0.0.0, not 127.0.0.1.

This allows any computer on the same LAN  as the Vagrant host access to the Vagrant guest VM via SSH and is not secure by default.

### Vagrant version
Vagrant 1.9.3
vagrant-vmware-workstation (4.0.18)

### Host operating system
Ubuntu GNOME 16.04.2LTS 64 bit

### Guest operating system
Ubuntu Server 16.04.2LTS 32 bit

### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-server-16.04.2-x86-32"
  config.vm.provision "shell", path: "vagrant_provision.sh"

  config.vm.provider :vmware_workstation do |vmware|
    vmware.vmx["ethernet0.pcislotnumber"] = "32"
  end

  config.vm.hostname="sandbox"
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
```

### Expected behavior
Port forwarding should default to 127.0.0.1 to ensure that your SSH port forward of 2222 is not publicly accessible

### Actual behavior
Port forwarding is on 0.0.0.0:2222.  Other hosts on same LAN can connect via SSH to port 2222 on your Vagrant hosts LAN facing IP address.

### Steps to reproduce
1. Configure vmware_workstation plugin
2. vagrant init 
3. Edit Vagrantfile as desired leaving SSH settings completely stock
4. vagrant up
5. netstat -nltp
6. Observe that there is a TCP socket listening on 0:0:0:0:2222
7. From another host on your LAN, try to SSH to vagrant_host_IP:2222
8. Observe ssh connection establish from external host to vagrant VM running on your vagrant host

### References
GH-4193
GH-1785

**Comment by pgrohe** [comment]
I've also tried using the 'host_ip'  parameter for forwarded ports but cannot get it to work on vmware_workstation provider.

Added these two lines to the Vagrant file in my original issue post above:

```
  config.vm.network "forwarded_port", guest: 22, host: 2222, disabled: true
  config.vm.network "forwarded_port", guest: 22, host: 2200, id: "ssh", host_ip: "127.0.0.1"
```

The change of port from 2222 to 2200 works but it always listens on "0.0.0.0:2200", not "127.0.0.1:2200"

**Comment by chrisroberts** [comment]
Hi there,

After digging through the vmware network service a bit and doing some trial and error, it turns out that the lack of host_ip support is a limitation of the vmware network service. I will add some warning output to the plugin to notify users that the `host_ip` setting has no affect when using the vmware plugin, but that's the best we can do from the Vagrant side. It will likely be best to just ensure public access is not allowed to any ports being used for port forwards locally.

Thanks for the report. Cheers!
