### ISSUE TITLE
Vagrant up forces shutdown of VM

### ISSUE THREAD

**Issue by bbkane** [mitchellh/vagrant#8520]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.9.4

### Host operating system
Windows 7

### Guest operating system
bento/centos-7.3

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"
end
```

### Debug output
https://gist.github.com/bbkane/8a207e5fd0a33e5ad9caca0e3ec3c230

### Expected behavior
I should have gotten a box

### Actual behavior
I got the error messages linked to above

### Steps to reproduce
1. Install Virtualbox from download.virtualbox.org/virtualbox/5.1.20/VirtualBox-5.1.20-114628-Win.exe
2. Install Vagrant from https://releases.hashicorp.com/vagrant/1.9.4/vagrant_1.9.4.msi
3. `vagrant up`

### Notes
- I can use Virtualbox to install an ISO manually as well as use the resulting machine
- I just downloaded both tools today.
- I tried messing with `config.vm.boot_timeout` but that didn't help
- I disabled my antivirus (Avast) but that didn't seem to make a difference

### Truncated Error
For Github searchability
```
vagrant.exe : C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:54:in `readpartial': An established connection was aborted by the software in your host machine. 
(Errno::ECONNABORTED)
At line:1 char:1
+ & vagrant up 2>&1 >> log.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:/HashiCorp/Va...::ECONNABORTED):String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
```

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-7832 look kind of similar (`read_nonblock` instead of `readpartial` and `vagrant share` instead of `vagrant up`)
- ...

**Comment by famod** [comment]
Same here on Vagrant 1.9.4, Windows 7 Home x64 and VirtualBox 5.1.20 with box ubuntu/xenial64 (v20170424.0.0).

**Comment by clamb** [comment]
I had the same error here (Vagrant 1.9.4, Windows 7 x64, VB 5.1.20 with box ubuntu/xenial64). It looks like an exception Errno::ECONNABORTED is raised if the guest is booting when vagrant tries to connect through ssh. 

As a workaround, I added `Errno::ECONNABORTED` in the array `exceptions` at line 356 of the file `communicators/ssh/communicator.rb` as well as a corresponding `rescue` at line 407.

**Comment by bbkane** [comment]
@clamb Did that work very well?

**Comment by Deaton64** [comment]
Same error for me. I've downgraded to 1.9.3. Works OK.

**Comment by eineving** [comment]
Same thing for me for both Vagrant 1.9.3 and 1.9.4, Win 7 and VirtualBox 5.1.20

**Comment by GhaziTriki** [comment]
Is any fix coming? I am stuck and can't launch any VM since tow days 😞

**Comment by clamb** [comment]
@bbkane I was able to provision my machine a couple of time, but I am unaware of side effects.

**Comment by GhaziTriki** [comment]
@clamb can you you please give more details about the quick fix? What changes needs to be done for which lines?

**Comment by bbkane** [comment]
@chrisroberts Thanks for fixing the issue! I noticed you put it on the 1.9.5 milestone. Pardon my ignorance, but how soon will this change be reflected on the [Downloads page](https://www.vagrantup.com/downloads.html)?

**Comment by joelhandwell** [comment]
Those who want to fix it now in your computer without waiting for 1.9.5 can replace 3 files changed in https://github.com/mitchellh/vagrant/issues/8526 in vagrant installation directory.

For example in windows, those files are located in 
* ```C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/templates/locales/en.yml```
* ```C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/errors.rb```
* ```C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/communicators/ssh/communicator.rb```

replace them with new [en.yml](https://raw.githubusercontent.com/chrisroberts/vagrant/2acded113c8f8915038b6230df1acfac43332c0c/templates/locales/en.yml), [errors.rb](https://raw.githubusercontent.com/chrisroberts/vagrant/2acded113c8f8915038b6230df1acfac43332c0c/lib/vagrant/errors.rb) and [communicator.rb](https://raw.githubusercontent.com/chrisroberts/vagrant/2acded113c8f8915038b6230df1acfac43332c0c/plugins/communicators/ssh/communicator.rb)

Then you are good to go. It worked on my Windows 10 machine.

**Comment by vainkop** [comment]
@joelhandwell Thank you!!!

**Comment by belcebus** [comment]
Me too, after replacing 3 files everything goes right. Thanks!

**Comment by mpaskal** [comment]
The same for me: Windows 10 x64, VirtualBox Version 5.1.22 , Vagrant 1.9.4. Thanks a lot!

**Comment by fofo13** [comment]
sorry i have windows 8 i can't fix this problem....can you hel me?

**Comment by fofo13** [comment]
This is my error


C:\lab>vagrant up
Bringing machine 'moloch' up with 'virtualbox' provider...
==> moloch: Importing base box 'ubuntu/xenial64'...
==> moloch: Matching MAC address for NAT networking...
==> moloch: Checking if box 'ubuntu/xenial64' is up to date...
==> moloch: Setting the name of the VM: lab_moloch_1493758359300_45989
==> moloch: Clearing any previously set network interfaces...
==> moloch: Preparing network interfaces based on configuration...
    moloch: Adapter 1: nat
    moloch: Adapter 2: hostonly
==> moloch: Forwarding ports...
    moloch: 22 (guest) => 2222 (host) (adapter 1)
==> moloch: Running 'pre-boot' VM customizations...
==> moloch: Booting VM...
==> moloch: Waiting for machine to boot. This may take a few minutes...
    moloch: SSH address: 127.0.0.1:2222
    moloch: SSH username: ubuntu
    moloch: SSH auth method: password
    moloch: Warning: Connection reset. Retrying...
==> moloch: Forcing shutdown of VM...
==> moloch: Destroying VM and associated drives...
C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/serv
er_version.rb:54:in `readpartial': Connessione interrotta dal software del compu
ter host. (Errno::ECONNABORTED)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:54:in `block (2 levels) in negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:52:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:52:in `block in negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:50:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:50:in `negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:32:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/session.rb:84:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/session.rb:84:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.r
b:233:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.r
b:233:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:397:in `block (2 levels) in connect'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `bloc
k in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `bloc
k in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catc
h'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catc
h'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `tim
eout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:371:in `block in connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/u
til/retryable.rb:17:in `retryable'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:370:in `connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:68:in `block in wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `bloc
k in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `bloc
k in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catc
h'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catc
h'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `tim
eout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:46:in `wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/a
ction/builtin/wait_for_communicator.rb:16:in `block in call'

**Comment by ranss** [comment]
I have too the same error with the current version 1.9.4 with `vagrant up` command.

_C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:54:in `readpartial': An established connection was aborted by the software in your host machine. (Errno::ECONNABORTED)_

**Comment by MarcusGabriel** [comment]
Same problem (Version 1.9.4)  
C:\vagrant-lamp-56>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: vagrant-lamp-56_default_1493903972602_43191
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8888 (host) (adapter 1)
    default: 3306 (guest) => 8889 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:54:in `readpartial': Uma conexÒo estabelecida foi anulada pelo software no computador host. (Errno::ECONNABORTED)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:54:in `block (2 levels) in negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:52:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:52:in `block in negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:50:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:50:in `negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/server_version.rb:32:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:84:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/session.rb:84:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:233:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.rb:233:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/communicators/ssh/communicator.rb:397:in `block (2 levels) in connect'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/communicators/ssh/communicator.rb:371:in `block in connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/retryable.rb:17:in `retryable'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/communicators/ssh/communicator.rb:370:in `connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/communicators/ssh/communicator.rb:68:in `block in wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/communicators/ssh/communicator.rb:46:in `wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'

**Comment by knusher** [comment]
I am getting the same error - 

C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/transport/serv
er_version.rb:54:in `readpartial': An established connection was aborted by the
software in your host machine. (Errno::ECONNABORTED)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:54:in `block (2 levels) in negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:52:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:52:in `block in negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:50:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:50:in `negotiate!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/server_version.rb:32:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/session.rb:84:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh/t
ransport/session.rb:84:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.r
b:233:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/net-ssh-4.1.0/lib/net/ssh.r
b:233:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:397:in `block (2 levels) in connect'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `bloc
k in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `bloc
k in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catc
h'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catc
h'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `tim
eout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:371:in `block in connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/u
til/retryable.rb:17:in `retryable'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:370:in `connect'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:68:in `block in wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `bloc
k in timeout'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `bloc
k in catch'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catc
h'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catc
h'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `tim
eout'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commu
nicators/ssh/communicator.rb:46:in `wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/a
ction/builtin/wait_for_communicator.rb:16:in `block in call'

c:\Tools\rkt\rkt>vagrant version
Installed Version: 1.9.4
Latest Version: 1.9.4

You're running an up-to-date version of Vagrant!

Windows Version 7

**Comment by fofo13** [comment]
to fix this kind of  problem you could replace 3 files like above:

For example in windows, those files are located in

C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/templates/locales/en.yml
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/errors.rb
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/communicators/ssh/communicator.rb
replace them with new en.yml, errors.rb and communicator.rb

and then try

vagrant halt

vagrant provision \ vagrant destroy

vagrant up

**Comment by ksunilsurya** [comment]
Thank you. The fix has worked in windows 8.1 pro.

**Comment by belcebus** [comment]
You can also back to 1.9.3 until 1.9.5 is out. Both solutions worked for me
on w7
Regards.

**Comment by NaruAna** [comment]
@joelhandwell Thank you so much! You really saved my day!

**Comment by joelhandwell** [comment]
@NaruAna all the credit should go @chrisroberts who fixed this issue with https://github.com/mitchellh/vagrant/pull/8526 . Thank you @chrisroberts, you saved my day, and all others who arrived this issue.

**Comment by szoghybe** [comment]
@joelhandwell  thank you! The 3 file substitution fix resolved my Vagrant issue with Hyperledger Fabric.

**Comment by DannyBen** [comment]
Still doesn't work for me.

Setup: Windows 10 + VirtualBox 5.1.22 + Vagrant 1.9.4

Tried:

1. Downgrading to 1.9.3
2. Replacing the 3 files
3. Replacing the entire contents of the vagrant-1.9.4 gem with the content of the master branch

Still getting errors. Any chance of an expedited fix or another workaround? This prevents me from being able to work.

**Comment by raulrotundo** [comment]
Thanks @joelhandwell ! the 3 files fix the problem.

**Comment by keshengjie** [comment]
Fixed by uninstalling v1.9.3 and installing v1.9.2.

**Comment by maikenunes** [comment]
Thank's @joelhandwell.

**Comment by elambro** [comment]
@chrisroberts Thanks! It worked for me on Win10, VM  5.1.18, Vagrant 1.9.4,

**Comment by sqfaru** [comment]
@joelhandwell Thank you so much! I have hearattack already comming ;)

**Comment by slavensaka** [comment]
@joelhandwell Replacing the three files fixed it. 
After all that 
`vagrant halt` 
`vagrant up`
and ran ok but had problems with `vagrant ssh`.
So i would also suggest after replacing the 3 files 
`vagrant destroy && vagrant up --provision` 
will fix all the issues. It did for me

**Comment by tiagodurante** [comment]
Thank's @joelhandwell <3
I'm using Windows 10 x64 + Vagrant 1.9.4 + VirtualBox 5.1.22 r115126 (Qt5.6.2)

**Comment by garabhato** [comment]
@joelhandwell Thank you so much!

**Comment by nivekze** [comment]
@joelhandwell Thank you so much man!

**Comment by blueyi** [comment]
Thank you! @joelhandwell

**Comment by javajon** [comment]
I had same problem of attempting to "vagrant up" with latest version of Vagrant v1.9.4 while attempting vagrant based setup of Mesosphere DC/OS with Windows 10 and VirtualBox.  The VM setup kept shutting down at these lines:

default: SSH auth method: private key
default: Warning: Connection reset. Retrying...
==> default: Forcing shutdown of VM...

Tried several times then found this report from "dnsmichi" at https://monitoring-portal.org/index.php?thread/40651-icinga2-vagrant-problem-up-ing-on-windows-10-machine/

Indeed reverting from Vagrant v1.9.4 back to v1.9.3 fixed the problem.

**Comment by deadstar1** [comment]
does 1.9.5 fix this?

**Comment by mwld** [comment]
Yes, it will: 

> communicators/ssh: Retry on aborted connections [GH-8526, GH-8520]
(https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md)

**Comment by puneetverma05** [comment]
@joelhandwell  Thank you!

**Comment by cklmercer** [comment]
I'm getting this issue after a fresh install of Windows 10, Virtual Box and Vagrant `1.9.5`. Any recommendations?

**Comment by slavensaka** [comment]
check @joelhandwell answer. Have the same setup and fixed it.

**Comment by claide** [comment]
@joelhandwell Yes it did solve the issue. Thanks man!

**Comment by PapaBearNZ** [comment]
Getting same issue with Win10, Vagrant 1.9.7 and Virtualbox 5.1.24

**Comment by johnnyvf24** [comment]
I'm getting the error as well on Vagrant 1.9.7 and VirtualBox 5.0.6 & 5.1.24 (tried upgrading)

**Comment by kalifg** [comment]
Windows 10, Vagrant 1.9.8 and VirtualBox 5.1.26 r117224 also having this issue
