### ISSUE TITLE
VMWare Workstation Plugin fails with gem loading error

### ISSUE THREAD

**Issue by BT-dschleich** [mitchellh/vagrant#8521]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Ubuntu 16.04.2 LTS (64)

### Guest operating system
Debian8_64

### Debug output
https://gist.github.com/BT-dschleich/6d9d7bc17c4f47d3160192849f644cd7#file-gistfile1-txt

### Expected behavior
vagrant init hashicorp/precise64
Inits a Vagrantfile

### Actual behavior
It does not:
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

There was an error while trying to load the gem 'vagrant-vmware-workstation'.

### Steps to reproduce
1. vagrant init hashicorp/precise64

**Comment by chrisroberts** [comment]
Hi there. It looks like you are running Vagrant outside the official installers. The `vagrant-vmware-workstation` plugins requires Vagrant to be installed via the official installers to access features that it bundles. Cheers!
