### ISSUE TITLE
Vagrant 1.9.4: Vagrant up hyperv error

### ISSUE THREAD

**Issue by michael-hearn** [mitchellh/vagrant#8527]
## Vagrant version
Vagrant 1.9.4

### Host operating system
Windows 10

### Guest operating system
Centos 7

### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos7-hyperv-26042017"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
```
This is a hyperv box that we have been testing. It does work with version 1.9.3

### Debug output
https://gist.github.com/michael-hearn/dc9ff618364c87302562c00be4f106dc

### Expected behavior
load and launch the Centos 7 server.?

### Actual behavior
When I do "vagrant up" with the new 1.9.4 update I get the below. 

```
vagrant up
The provider 'hyperv' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

The Hyper-V provider requires that Vagrant be run with
administrative privileges. This is a limitation of Hyper-V itself.
Hyper-V requires administrative privileges for management
commands. Please restart your console with administrative
privileges and try again.
```

**Comment by DrowningElysium** [comment]
For me I have also problems with it detecting admin permissions, I run the command from git bash that is opened as an admin and still it tells me it needs admin permissions to be able to open samba shares.

**Comment by sXe79** [comment]
Same here, powershell with admin privileges
```
No synced folder implementation is available for your synced folders!
Please consult the documentation to learn why this may be the case.
You may force a synced folder implementation by specifying a "type:"
option for the synced folders. Available synced folder implementations
are listed below.

docker, nfs, rsync, smb, virtualbox
```

Then I explicity added "smb" in the yaml
```
SMB shared folders require running Vagrant with administrative
privileges. This is a limitation of Windows, since creating new
network shares requires admin privileges. Please try again in a
console with proper permissions or use another synced folder type.
```

**Comment by DrowningElysium** [comment]
@sXe79 https://github.com/mitchellh/vagrant/pull/8510
This is the fix to that problem, it just means you will have to do it manually in your installation folder

**Comment by sXe79** [comment]
@DrowningElysium Thanks! 👍

**Comment by wickedviking** [comment]
Regarding the VMSwitch handling, unless this could be updated to handle mutli-homed scenarios, it would better to leave it as is or update the current network processes to handle mutliple adapters/switches.

User case, setting up a Router VM to bridge two networks (local host private and lab for example) to create an isolated environment that "borrows" internet access from another network.

**Comment by chrisroberts** [comment]
Fixed via #8548

**Comment by masaeedu** [comment]
@DrowningElysium Is there some workaround to this problem? The vagrant version I got seems to have been built into a single exe, so I can't apply the patch from the referenced issue. I also can't find any nightly builds for vagrant.

**Comment by DrowningElysium** [comment]
@masaeedu  its some folders deep, if you search in the folder for "vagrant-1.9.4" you should be able to find it
