### ISSUE TITLE
vagrant have a shell_early provisioner

### ISSUE THREAD

**Issue by stephencookefp** [mitchellh/vagrant#8534]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
Vagrant 1.9.3
### Host operating system
This is the operating system that you run locally.
OSX and ubuntu and RHE

### Guest operating system
This is the operating system you run in the virtual machine.
ubuntu and RHE

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
example idea

config.vm.provision "shell_early", path: "echo "pre synced_folder run shell"
config.vm.synced_folder "data", "/etc/puppetlabs/puppet/data", type: "rsync", create: true
config.vm.provision "shell", path: "echo 'post mount shell"


```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?
config.vm.provision "shell_early", path: "echo "pre synced_folder run shell"

would offer the ability to run a process before any custom shares are loaded, ( not the vagrant ones) 

### Actual behavior
What actually happened?
synced_folders are ran , then shell provisioners , then other provisioners like puppet
### Steps to reproduce
1. Setup an shell option
2. it will run post synced folder mount
3. this can fail as details don't exist on the base box

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- Many git hub issues exist around needing apache on the box before the synced folders set this to apache.

The workarounds that exist are , add a shell provision to undertake the remount or bake in a user to the box before you use it.

Seems to have a shell_premount would be very useful, as this can be used to also bootstrap stuff into a box before mounting shares.
- ...

**Comment by chrisroberts** [comment]
Marking as a duplicate #3849 as it would provide this functionality. Cheers!
