### ISSUE TITLE
File Provisioner not working after Vagrant Update 1.9.4

### ISSUE THREAD

**Issue by mondoshivan** [mitchellh/vagrant#8535]
When I install vagrant 1.9.4, I can not run .bat files as file provisioner configured in Vagrantfile. When I downgrade to 1.9.3 the file provisioner is working again. The bat file I use for provisioning is installing an application. For debugging I removed the installation routine and added a simple "echo hello" into the bat file. But even this is not logged by vagrant during the provisioning phase.

### Vagrant version
1.9.4

### Host operating system
OSX 10.9.5 and macOS 10.12.3

### Guest operating system
Windows 10 Pro 64-Bit in Virtualbox

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "some-name"        # we are using our own boxes build by packer
  config.vm.box_url = ""                    # we are using our own boxes build by packer

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096"
  end

  config.vm.provision "shell", privileged: true, path: "path/to/some-provisioner.bat"  # the bat file contains only a simple "echo hello"

end
```

### Debug output
The debug log is taken from a "vagrant provision" command.
https://gist.github.com/mondoshivan/a2bc2138b7f93a435840e3a04773bbff#file-file_provisioner_debug

### Expected behavior
File provisioner runs and "hello" is logged by vagrant

### Actual behavior
File provisioner does not run, "hello" not logged by vagrant

### Steps to reproduce
1. Just a "vagrant up" or "vagrant provision"

**Comment by chrisroberts** [comment]
@mondoshivan Thanks for the report! Please note that powershell files `.ps1` were not affected. Cheers!
