### ISSUE TITLE
Private network breaks "vagrant up" for debian/testing64

### ISSUE THREAD

**Issue by sayotte** [mitchellh/vagrant#8543]
### Vagrant version
```
$ vagrant -v
Vagrant 1.9.4
$ VBoxManage -v
5.1.20r114628
```

### Host operating system
```
$ lsb_release -ri
Distributor ID: Ubuntu
Release:        14.04
```

### Guest operating system
debian/testing64

Note that this works for debian/jessie64

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

allnodes = ["lb1","lb2"]

nodeIPs = {}
for i in 0..allnodes.length-1
    nodeIPs[allnodes[i]] = "172.16.0." + (2+i).to_s
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/testing64"
  #config.vm.box = "debian/jessie64"

  allnodes.each do |nodename|
    config.vm.define nodename do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "256"
      end
      node.vm.network "private_network", ip: nodeIPs[nodename]
    end
  end
end
```

### Debug output
https://gist.github.com/sayotte/3c3c43dd59e0fbb858c6b365be932212

### Expected behavior
Box should come up with private network interface configured.

### Actual behavior
Hangs at `    lb1: SSH auth method: private key`; eventually times out.

Restarting the box allows it to come up normally, at which point `vagrant ssh` works normally although the interface remains unconfigured.

Removing the private network config allows `vagrant up` to work normally (i.e the issue is not present).

Using the debian/jessie64 base box, `vagrant up` works even with a private network. I noticed debian/testing64 seems to have done away with the "ifconfig" CLI utility entirely, likely to push a transition to the "ip" CLI.

### Steps to reproduce
1. `vagrant up lb1`
2. Wait for timeout.

**Comment by sayotte** [comment]
I've confirmed that these commands do work to get the NIC configured in VirtualBox:
```
VBoxManage modifyvm vbox_lb1_1493649691904_83879 --nic2 intnet
VBoxManage modifyvm vbox_lb1_1493649691904_83879 --intnet2 marathon
VBoxManage modifyvm vbox_lb1_1493649691904_83879 --nictype2 virtio
VBoxManage modifyvm vbox_lb1_1493649691904_83879 --cableconnected2 on
```

If I boot the VM with VBoxHeadless and set up all the port forwarding etc., I can use it.

But if I add back in the `node.vm.network "private_network"` and try running `vagrant up`, it dies like so:
```
$ vagrant up lb1
Bringing machine 'lb1' up with 'virtualbox' provider...
==> lb1: Checking if box 'debian/testing64' is up to date...
==> lb1: Clearing any previously set forwarded ports...
==> lb1: Clearing any previously set network interfaces...
/opt/vagrant/embedded/lib/ruby/2.2.0/ipaddr.rb:475:in `initialize': address family must be specified (IPAddr::AddressFamilyError)
<...stack trace snipped...>
```

**Comment by sayotte** [comment]
Correction, that last failure was a syntax error on my part. Anyway I reintroduced the full original code like so:
```
      node.vm.network "private_network", ip: nodeIPs[nodename],
        virtualbox__intnet: "marathon"
```

Running `vagrant up` now results in an up + fully configured interface as I originally intended (but again only after halting the VM, running some VBoxManage commands, and then restarting it).

**Comment by sayotte** [comment]
....annnnd I'm gonna have to reel that one back too. Not sure what I did different, but I can't reproduce the workaround now as it hangs on `vagrant up` regardless of stopping/configuring/starting shenanigans.

**Comment by chrisroberts** [comment]
It looks like the box was built with a couple extra adapters. Overriding the `nic_type` made things work:

```ruby
node.vm.network "private_network", ip: nodeIPs[nodename], nic_type: "82540EM"
```

Cheers!

**Comment by sayotte** [comment]
@chrisroberts I think this may've been closed prematurely. I was able to bring the box up successfully twice after making that change, but it's now hanging again. This is what I've been seeing all day while trying to isolate the problem-- it appears to succeed and fail randomly.

I tried pulling Vagrant out of the loop (I was looking for a workaround, but also to isolate the problem if possible), and observed a similar failure. I was doing this:
```
vagrant up lb1 # <--- no second NIC configured
vagrant halt -f lb1
vmname=$(vboxmanage list vms | grep "vbox_${h}_" | cut -d' ' -f1 | cut -d\" -f2)
vboxmanage modifyvm $vmname --name $h
vboxmanage modifyvm $h --nic2 intnet
vboxmanage modifyvm $h --intnet2 'marathon'
vboxmanage modifyvm $h --nictype2 virtio
vboxmanage modifyvm $h --cableconnected2 on
vboxmanage modifyvm $h --natpf1 delete ssh
vboxmanage modifyvm $h --natpf1 delete ${h}_ssh
extport=2322
vboxmanage modifyvm $h --natpf1 ${h}_ssh,tcp,127.0.0.1,${extport},,22
vboxheadless --startvm $1 &
```

At that point I'd try running `telnet localhost 2322` to see if I got an SSH banner. The TCP connection would always be established, but most of the time I wouldn't get the SSH banner back. Running it with a console through the virtualbox GUI didn't seem to help, but sometimes going and touching the machine on the console would help-- logging in, restarting ssh, or even just giving input-focus to the console window-- and a subsequent telnet attempt would fetch the SSH banner. There was no rhyme or reason to it, though, and sometimes I'd get the SSH banner immediately (sometimes more than once in a row).

It smells like the problem probably *isn't* inside of Vagrant itself. But I'm not exactly sure how to isolate whether it's:
* kernel 4.9.13
* VirtualBox 5.1.20
* box debian/testing64
* an interaction between kernel 4.9.13 <-> VirtualBox 5.1.20
* an interaction between box debian/testing64 <-> kernel 4.9.13
* an interaction between box debian/testing64 <-> VirtualBox 5.1.20

**Comment by sayotte** [comment]
@chrisroberts update with good news, a hand-built debian/testing/amd64 box does work consistently, so it's at least not a weird between two things we can't control. I think that leaves:

* box debian/testing64 itself
* an interaction between box debian/testing64 <-> kernel 4.9.13
* an interaction between box debian/testing64 <-> VirtualBox 5.1.20

**Comment by chrisroberts** [comment]
@sayotte My assumption is that it is an issue with the nic types that are configured in the base box (as it has extra nics that are disabled until enabled via the Vagrantfile). If the types are consistent, everything seems to work without issue (I've been able to do multiple reloads as well as destroy/up's without errors). The underlying cause of that I'm not certain.
