### ISSUE TITLE
1.9.4 installs very old version of plugin

### ISSUE THREAD

**Issue by kivoli** [mitchellh/vagrant#8550]
For an unknown reason Vagrant 1.9.4 reproducible installs only a very old version of vagrant-libvirt (0.0.20) while 1.9.3 does pull the correct version, 0.0.40. Downgrading Vagrant for this purpose works, too.

### Vagrant version
```
Installed Version: 1.9.4
Latest Version: 1.9.4
```

### Host operating system
Ubuntu 16.04

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
```
Installed the plugin 'vagrant-libvirt (0.0.20)'!
```
### Expected behavior
Install newest version (0.0.40) of `vagrant-libvirt` plugin.

### Actual behavior
Installs very old version (0.0.20)

### Steps to reproduce
1. Set up Ubuntu 16.0.4
2. Install Vagrant 1.9.4 using the Debian 64 binary from vagrantup.com
3. Run `vagrant plugin install vagrant-libvirt`

**Comment by chrisroberts** [comment]
@kivoli Forcing the latest version (`vagrant plugin install vagrant-libvirt --plugin-version 0.0.40`) shows there is a dependency conflict with nokogiri. I've been looking at removing nokogiri from the shipped installer to prevent these conflicts, and it looks like I'll need to speed that up.

**Comment by kivoli** [comment]
@chrisroberts Okay, but I find the behaviour of Vagrant a bit confusing, too. Because it insisted on `vagrant plugin update` that 0.0.20 is the latest version. Other users may not have realised that there is a newer version available. Would it be possible to print a warning in such a case?
Anyway, thanks for finding the culprit! Didn’t think of forcing the new version; I’ll remember that for my next bug report.

**Comment by COLABORATI** [comment]
Please support libvirt right oob, this is the best virtualization option on Linux systems and it sux that vagrant still produces problems with that. It would help if your devs used Linux systems, then these kind of errors would never happen.
