### ISSUE TITLE
Docs: HyperV Configuration - Defaults for `key_value_pair_exchange` are wrong

### ISSUE THREAD

**Issue by GuyPaddock** [mitchellh/vagrant#8551]
The [docs for the Hyper-V Provider](https://www.vagrantup.com/docs/hyperv/configuration.html#vm_integration_services) provide this sample for the `vm_integration_services` setting:
```Ruby
config.vm.provider "hyperv" do |h|
  h.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: false,
      shutdown: true,
      time_synchronization: true,
      vss: true
  }
end
```

This is a bad example to follow, because Vagrant actually requires `key_value_pair_exchange` to be `true` to function properly. Otherwise, it cannot determine the IP address of the VM. I would like to recommend that the docs be updated to reflect that this should be `true`. Obviously, users are able to copy this sample and then customize what they put in their Vagrantfile, but as this documentation is mostly to the benefit of new Vagrant users, they might not realize why this configuration does not work out of the box.

**Comment by chrisroberts** [comment]
Updated via #8561. Thanks for the report!
