### ISSUE TITLE
vagrant ssh error: `ssh_info': undefined method `first' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by lookfwd** [mitchellh/vagrant#8552]
### Vagrant version
The issue started in 1.9.4 . It was fine in 1.9.3.

### Host operating system
Ubutntu xenial-16.04

### Guest operating system
Linux

### Vagrantfile

See [here](https://github.com/scalingexcellence/scrapybook/blob/master/Vagrantfile). The section around `dev` is what we're mostly interested in (last one).

### Debug output

https://gist.github.com/lookfwd/86b05602b2deaefb7f8d4465e2b046fa

### Expected behavior

`vagrant ssh` should work as usually.

### Actual behavior

There's a crash because in /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/providers/docker/provider.rb , around line 143. 

`network['Ports'] == {"6800/tcp"=>[{"HostIp"=>"0.0.0.0", "HostPort"=>"6800"}]}`

and

`port_name == 22/tcp`

causing the `nil` on access.

### Steps to reproduce
1. Create an image with Dockerfiles like [this](https://github.com/scalingexcellence/scrapybook-docker-web/blob/master/Dockerfile)
2. `vagrant up`
3. `vagrant ssh` should now fail while it used to work in the past

**Comment by externl** [comment]
Also experiencing this when I have ssh port forward disabled for Docker. Any temporary work arounds?
