### ISSUE TITLE
Windows 10 Home edition when script contains 0.0.0.0 address is not supported by windows in vagrant 1.9.3 fix it.

### ISSUE THREAD

**Issue by juslintek** [mitchellh/vagrant#8569]
Windows 10 Home edition when script contains 0.0.0.0 address is not supported by windows in vagrant 1.9.3 fix it.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
