### ISSUE TITLE
WinRM Gem bug in version 2.2.2 causing winrm delay on cleanup

### ISSUE THREAD

**Issue by rstallings** [mitchellh/vagrant#8574]
### Vagrant version
Vagrant 1.9.4

### Host operating system
Host Windows 7 Pro 64Bit

### Guest operating system
Guest Windows 7 Pro 32Bit -- PowerShell Version 2.0

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "testproj/win7-x86-base"
  config.vm.communicator    = "winrm"
  config.winrm.retry_limit  = 50
  config.winrm.retry_delay  = 20
  config.vm.network     "private_network", ip: "192.168.3.198"
  config.winrm.username      = "vagrant"
  config.winrm.password      = "vagrant"
end
```

### Debug output
```
DEBUG winrmshell: [WinRM] remote shell created with shell_id: 57C71070-1332-433F-92F6-885EE1460997
DEBUG winrmshell: [WinRM] Command created for ((test-wsman).productversion.split(" ") | select -last 1).split("\.")[0]

if (!$?) { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } } with id: 65E897E2-E14A-49CF-BCCC-29D6C1147DEF
DEBUG winrmshell: [WinRM] creating command_id: 65E897E2-E14A-49CF-BCCC-29D6C1147DEF on shell_id 57C71070-1332-433F-92F6-885EE1460997
DEBUG winrmshell: [WinRM] Waiting for output...
DEBUG winrmshell: [WinRM] Processing output
DEBUG winrmshell: [WinRM] cleaning up command_id: 65E897E2-E14A-49CF-BCCC-29D6C1147DEF on shell_id 57C71070-1332-433F-92F6-885EE1460997
 INFO winrmshell: [WinRM] Exception suppressed: [WSMAN ERROR CODE: 2150858843]: <f:WSManFault Code='2150858843' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message>The Windows Remote Shell cannot process the request; the selector value 57C71070-1332-433F-92F6-885EE1460997 specified in the request was not found. </f:Message></f:WSManFault>
DEBUG winrmshell: Output: #<WinRM::Output:0x556d2e0 @data=[{:stdout=>"2\r\n"}], @exitcode=0>
DEBUG guestnetwork: wsman version: 2
```

### Expected behavior
winrm commands should cleanup the connection quickly(< 20 seconds)

### Actual behavior
Mounting of c:/vagrant as well as other winrm commands take a long time (> 3 mins each).  This is due to a bug in the WinRM gem when combined with Windows7 and powershell 2.0.  Powershell 2.0 throws an error (SHELL_NOT_FOUND - 2150858843) on cleanup which WinRM catches and then retries on.  This error is expected and the WinRM gem should not retry.  See WinRb/WinRM#253    This has been fixed in version 2.2.3 of the WinRM gem.  In the next release of vagrant the new version should be used.

### Steps to reproduce
1. Use fresh win7 with powershell 2.0 in the guest os
2. Do vagrant up.  Mount command of c:/vagrant will take a long time and show error 2150858843

### References
- WinRb/WinRM#253 (Orginal error reported)
- WinRb/WinRM#269 (Fix of error in WinRM 2.2.3)

**Comment by chrisroberts** [comment]
Updated in latest release. Cheers!
