### ISSUE TITLE
ed25519 Host Key Failure

### ISSUE THREAD

**Issue by utkonos** [mitchellh/vagrant#8584]
### Vagrant version
Vagrant 1.9.4

### Host operating system
macOS Sierra 10.12.4 (16E195)

### Guest operating system
FreeBSD 11-RELEASE-p10

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.shell = "sh"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8081
  config.vm.box = "freebsd/FreeBSD-11.0-RELEASE-p1"
  config.vm.base_mac = ""

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "default"]
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--boot2", "none"]
  end

  config.push.define "ftp" do |push|
    push.host = ""
    push.username = ""
    push.secure = "true"
    push.destination = ""
    push.dir = ""
  end

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/utkonos/19c9fc89d52e324944f303fc6482f11b

### Expected behavior
Push the folder out to the production server.

### Actual behavior
Host key algorithm could not be negotiated. The only Host_Key algorithm on the server is ed25519.

### Steps to reproduce
1. Make sure ed25519 is the only host key algorithm available
2. vagrant push

### References
It appears that this is something that has been fixed upstream:
https://github.com/mozilla/ssh_scan/issues/93

**Comment by chrisroberts** [comment]
Related #8585

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
