### ISSUE TITLE
ed25519 Client Key Failure

### ISSUE THREAD

**Issue by utkonos** [mitchellh/vagrant#8585]
### Vagrant version
Vagrant 1.9.4

### Host operating system
macOS Sierra 10.12.4 (16E195)

### Guest operating system
FreeBSD 11-RELEASE-p10

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.shell = "sh"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8081
  config.vm.box = "freebsd/FreeBSD-11.0-RELEASE-p1"
  config.vm.base_mac = ""

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "default"]
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--boot2", "none"]
  end

  config.push.define "ftp" do |push|
    push.host = ""
    push.username = ""
    push.secure = "true"
    push.destination = ""
    push.dir = ""
  end

end
```

### Debug output
https://gist.github.com/utkonos/eaadb93e6fb24e264ce5e8fccfd74599

### Expected behavior
Push the folder out to the production server.

### Actual behavior
Client key type, ed25519, not supported due to missing gems. It seems like this can be fixed if the following gems are added to Vagrant's set of embedded gems: rbnacl, rbnacl-libsodium, bcrypt_pbkdf.

### Steps to reproduce
1. Make sure the ssh key being used is of type ed25519.
2. vagrant push

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
