### ISSUE TITLE
Vagrant will not operate outside the Windows Subsystem[...]

### ISSUE THREAD

**Issue by Log1x** [mitchellh/vagrant#8587]
![Screenshot](https://log1x.com/screenshots/2017-05-15_22-33-14_kY485.png)

Followed the docs, still unable to `vagrant up` outside of WSL (using CU, of course).

What am I doing wrong? It's a fresh box using Ubuntu 16.04 Xenial LTS (or more specifically, [Trellis](https://github.com/roots/trellis)).

Sorry in advance for clearing the issue template, I felt my screenshot answered most of the questions.

**Comment by chrisroberts** [comment]
Hi there. You should only need to export the access variable: 

```
$ export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
```

You shouldn't need to define any other environment variables unless you're using a non-standard setup. Relevant information is here: https://www.vagrantup.com/docs/other/wsl.html#windows-access

I'm going to close this up, but if you are still having issues, please feel free to open this back up. Cheers!

**Comment by Log1x** [comment]
Thanks. That should solve the issue. I must've been reading an outdated version of the docs from the initial PR as `/docs/other/wsl.html` wasn't up a moment ago.

**Comment by Log1x** [comment]
![Screenshot](https://log1x.com/screenshots/2017-05-15_22-52-19_ezkz9.png)

Having the same issue I had when attempting to do a "hacky" workaround prior to Vagrant 1.9.5 in attempt to get Vagrant to work inside of WSL.

Is this an issue with the box I'm using or something that needs to be addressed elsewhere?

Just so there's no confusion, I am indeed using `export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"`.

Semi-related: #1534

**Comment by chrisroberts** [comment]
@Log1x I'm not certain that nfsd works within the WSL. If you can confirm that it does indeed work, please feel free to open a new issue for it and I'll address it. Otherwise I'll have a look today and see if nfsd works and how it can be managed.

**Comment by JimiPedros** [comment]
@Log1x @chrisroberts bump

**Comment by Log1x** [comment]
@JimiPedros I have since switched to Hackintosh so I am no longer of any use on this issue.
