### ISSUE TITLE
Vagrant cannot load nokogiri

### ISSUE THREAD

**Issue by fatmcgav** [mitchellh/vagrant#8595]
I've gone to use Vagrant today, and it's suddenly started failing with:

```
$ vagrant status
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri (LoadError)
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/gavinw/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.4/lib/vagrant-parallels/driver/base.rb:2:in `<top (required)>'
        from /Users/gavinw/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.4/lib/vagrant-parallels/driver/meta.rb:4:in `require_relative'
        from /Users/gavinw/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.4/lib/vagrant-parallels/driver/meta.rb:4:in `<top (required)>'
        from /Users/gavinw/.vagrant.d/gems/2.2.5/gems/vagrant-parallels-1.7.4/lib/vagrant-parallels/provider.rb:16:in `usable?'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/vagrantfile.rb:138:in `machine_config'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/vagrantfile.rb:45:in `machine'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:669:in `machine'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/v2/command.rb:177:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/v2/command.rb:210:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/v2/command.rb:210:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/v2/command.rb:209:in `map'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/v2/command.rb:209:in `with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/status/command.rb:20:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:308:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/bin/vagrant:138:in `<main>'
```

It looks like my system has automatically installed Vagrant 1.9.5 this morning, and it's now not working... 

### Vagrant version
```
$ vagrant version
Installed Version: 1.9.5
Latest Version: 1.9.4
```

### Host operating system
MacOS 10.12.4

### References
- #8594 - Looks to be a similar issue with plugin installation.

**Comment by supernintendo** [comment]
Running into the same issue. #8594 did not solve this for me.

**Comment by tombensve** [comment]
In my case it is a new MacBook Pro and thereby a new installation of latest vagrant (1.9.5). I have MacOS 10.12.5. I get exactly the same error as @fatmcgav.

**Comment by fatmcgav** [comment]
Rolling back to 1.9.4 got me back and working...

**Comment by tombensve** [comment]
I thought to install the latest nokogiri, which of course required a fresher ruby, and .... well it got messy. I gave up and downloaded and installed 1.9.4 also. Now vagrant works for me too.

**Comment by kikitux** [comment]
@fatmcgav can you try again on current version please

**Comment by norelevance** [comment]
I am having the same issue on vagrant 1.9.7. I've also reinstalled the most recent Nokogiri version (1.8.0).

`vagrant@jessie:~/code/csone$ bin/rails s
/home/vagrant/.rvm/gems/ruby-2.4.0/bundler/gems/spyglass-c375308b56a2/lib/spyglass/super_admin/csone.rb:4:in `require': cannot load such file -- Nokogiri (LoadError)
	from /home/vagrant/.rvm/gems/ruby-2.4.0/bundler/gems/spyglass-c375308b56a2/lib/spyglass/super_admin/csone.rb:4:in `<class:CSOne>'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/bundler/gems/spyglass-c375308b56a2/lib/spyglass/super_admin/csone.rb:3:in `<module:SuperAdmin>'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/bundler/gems/spyglass-c375308b56a2/lib/spyglass/super_admin/csone.rb:2:in `<module:Spyglass>'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/bundler/gems/spyglass-c375308b56a2/lib/spyglass/super_admin/csone.rb:1:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/bundler/gems/spyglass-c375308b56a2/lib/spyglass.rb:10:in `require'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/bundler/gems/spyglass-c375308b56a2/lib/spyglass.rb:10:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `require'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler.rb:108:in `require'
	from /home/vagrant/code/csone/config/application.rb:7:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:129:in `require'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:129:in `block in perform'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `tap'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/commands/server/server_command.rb:126:in `perform'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	from /home/vagrant/code/csone/bin/rails:9:in `require'
	from /home/vagrant/code/csone/bin/rails:9:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /home/vagrant/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/vagrant/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/vagrant/code/csone/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

$ vagrant -v
Vagrant 1.9.7
`
