### ISSUE TITLE
Vagrant sets GEM_HOME and GEM_PATH and breaks Berkshelf plugin

### ISSUE THREAD

**Issue by gbonk** [mitchellh/vagrant#8612]
### Vagrant version
$ vagrant --version
Vagrant 1.9.5

### Host operating system
Windows 7

### Guest operating system
ubuntu/xenial64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.berkshelf.enabled = true

  config.vm.box = "ubuntu/xenial64"

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apache2"
  end
end
```

### Debug output
[https://gist.github.com/gbonk/d79e01aa2aef14bbc3c9035deb4cd8ef#file-debug-log](url)

### Expected behavior
I expected it to work.

### Actual behavior
Received the following error

```
The following berks command failed to execute:

    C:\opscode\chefdk\embedded\bin/berks.BAT --version --format json

The stdout and stderr are shown below:

    stdout:
    stderr: Ignoring wdm-0.1.1 because its extensions are not built.  Try: gem pristine wdm --version 0.1.1
C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem berkshelf (>= 0.a) (Gem::GemNotFoundException)
        from C:/opscode/chefdk/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
        from C:/opscode/chefdk/embedded/bin/berks:26:in `<main>'
```
### Steps to reproduce
1.  Clean windows 7 machine
2.  Installed Chocolately, 0.10.5
3.  Installed Chef DK via chocolatey 
> Chef Development Kit Version: 1.3.43
> chef-client version: 12.19.36
> delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
> berks version: 5.6.4
> kitchen version: 1.16.0
3.  Installed Vagrant, 1.9.5, via chocolatey
4.  Installed the vagrant berkshelf plugin, vagrant-berkshelf (5.1.1)
5. Performed `vagrant up`

 References
Are there any other GitHub issues (open or closed) that should be linked here?
https://github.com/berkshelf/vagrant-berkshelf/issues/318

**Comment by briancain** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
