### ISSUE TITLE
Syntax errors in Vagrantfile cause vagrant to completely become non-functional in WSL

### ISSUE THREAD

**Issue by jcherniak** [mitchellh/vagrant#8614]
If you are running the latest version WSL and have a syntax error in your Vagrantfile, you see a warning about vagrant versions not matching, instead of the source of the error.

### Vagrant version
1.9.5

### Host operating system
Ubuntu 16.04 under WSL on Windows 10 Creators Update

### Guest operating system
Ubuntu 14.04

### Expected behavior
Should have displayed the syntax error:
```$ vagrant.exe # shows:
Usage: vagrant [options] <command> [<args>]
...
.../Vagrantfile:46:in `block in <top (required)>': undefined local variable or method `owner' for main:Object (NameError)
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/v2/loader.rb:37:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/v2/loader.rb:37:in `load'
...
```

### Actual behavior
Showed:
```
$ vagrant
Vagrant cannot currently enable access to manage machines within the Windows
environment because the version of Vagrant installed on Windows does not
match this version of Vagrant running within the Windows Subsystem for Linux.
Please ensure both installation of Vagrant are the same. If you do not want
update your Vagrant installations you can disable Windows access by unsetting
the `VAGRANT_WSL_ACCESS_WINDOWS_USER` environment variable.

  Windows Vagrant version: unknown
  Windows Subsystem for Linux Vagrant version: 1.9.5
```

### Steps to reproduce
1. Create a Vagrantfile with a syntax error
2. Launch "vagrant" in bash
3. Rather than see syntax error, get message about WSL link not working.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-8570
- GH-8582

**Comment by jcherniak** [comment]
Duplicate of 8609

**Comment by strarsis** [comment]
FWIW, I had the same error message but a different reason.
I ran vagrant in normal Windows cmd (as normal exe in Windows, not in WSL) 
and got an error message about plugins that have to be repaired.
After plugin repair vagrant worked correctly in cmd - and also now in WSL (together with the vagrant installed there).

**Comment by strarsis** [comment]
@jcherniak: Thanks! I probably have the same issue and a syntax error in the Vagrantfile.
