### ISSUE TITLE
Improving consistency of CLI by aliasing existing commands

### ISSUE THREAD

**Issue by leesdolphin** [mitchellh/vagrant#8617]
### Vagrant version
`Vagrant 1.9.5`

### Host operating system
Ubuntu 17.04

Hi all,

I would like to propose additional aliases for vagrant commands. I think it would improve the consistency of the CLI API and make it easier for infrequent users to get the task done the first time.

I propose the following aliases(with room for extension):

 - `vagrant up` -> `vagrant start`
 - `vagrant halt` -> `vagrant down`, `vagrant shutdown`, `vagrant stop`
 - `vagrant suspend` -> `vagrant pause`(maybe?)
 - `vagrant reload` -> `vagrant restart`

## Why?

I think that the commands, as they currently stand, are not consistent. There is a `up` command without a reverse `down` command. There are `suspend` and `resume` without similar `start`, `stop`, `restart` commands. 

The `reload` command doesn't seem to 'fit' with the others and doesn't make much sense as an outsider(if that makes sense).

I am a new contributor; however I have used Vagrant for a while.

**Comment by chrisroberts** [comment]
Hi there,

Thanks you for the suggestions, however vagrant commands have long been in use and mirror the functionality which they are performing. If you would like to have different naming for commands, you can easily setup aliases in your local shell.

Cheers!

**Comment by leesdolphin** [comment]
I am not suggesting that Vagrant replaces them. I'm just suggesting that there is a less steep learning curve for users of vagrant if the commands were standardised.

Other commands use more standard names, and also alias slightly different names so that the CLI is easier to use.
For example:
 - `npm` aliases `remove` and `uninstall` because both describe the act of removing a package; but some package managers use `remove` and some use `uninstall`. It also documents the 'correct one' and list's it aliases.
 - `docker-compose` uses `up`, and `start` as a command to start the cluster, however each does perform a slightly different command.
 - `service`/`init.d` uses `reload` and `restart` to mean completely different things. Which was something that confused me when I started, because I assumed that `reload` reloaded the Vagrantfile's configuration instead of doing a restart of the service.

So to reiterate, this isn't a change for those who have used Vagrant for a while. It is most helpful for those who are coming from other applications/systems who are not yet used to the 'vagrant-way'. Trying to reduce that learning curve whilst keeping older users happy should be a very noble goal of any software project.

**Comment by NZSmartie** [comment]
Coming from Docker and experiencing similar issues. I had created myself a bash function to do that aliasing for me. Not sure if others may also find this useful, but it works well for me

```bash
# placed in $HOME/.bash_profile as this is intended for interactive sessions only
vagrant() {
  if [[ $@ == start || $@ == start\ * ]]; then
    command vagrant up $(echo "$@" | cut -c 7-)
  elif [[ $@ == down || $@ == down\ * \
       || $@ == stop || $@ == stop\ * ]]; then
    command vagrant halt $(echo "$@" | cut -c 6-)
  elif [[ $@ == pause || $@ == pause\ * ]]; then
    command vagrant suspend $(echo "$@" | cut -c 9-)
  elif [[ $@ == restart || $@ == restart\ * ]]; then
    command vagrant reload $(echo "$@" | cut -c 9-)
  else
    command vagrant "$@"
  fi
}
```
