### ISSUE TITLE
Vagrant guest and host cannot communicate (Ubuntu 17.04) 

### ISSUE THREAD

**Issue by chadfurman** [mitchellh/vagrant#8626]
### Vagrant version
Vagrant 1.9.5
VirtualBox Graphical User Interface Version 5.1.22_Ubuntu r115126

### Host operating system
Ubuntu 17.04

### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
## Run from anywhere:  $ vagrant plugin install vagrant-vbguest 
## Run from anywhere:  $ vagrant plugin install vagrant-triggers 

Vagrant::configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network :private_network, ip: "192.168.33.99"

  config.vm.provider :virtualbox do |v|
    v.memory = 8096
    v.cpus = 2
    v.customize ["modifyvm", :id, "--ioapic", "on" ]
  end

  config.vm.synced_folder '.', '/vagrant', type: 'nfs', map_uid: 0, map_gid: 0
  #config.vm.synced_folder './janus', '/home/vagrant/creativ-janus', :mount_options => ["dmode=777", "fmode=666"]
  config.vm.synced_folder './janus', '/home/vagrant/creativ-janus', type: 'nfs', map_uid: 0, map_gid: 0

  config.vm.provision 'ansible' do | ansible |
      ansible.playbook = 'ansible/playbook.yml'
  end
end

```

### Debug output
https://gist.github.com/chadfurman/4ddfdf0e5d5203ef8353db1a4955b16f

### Expected behavior
Guest and Host should be able to ping back and forth.  Guest should be able to mount NFS

### Actual behavior
Guest and Host cannot communicate. Both are on vboxnet0 with 192.168.33.* ip addresses.  Neither has a firewall.

### Steps to reproduce
1. Use above Vagrantfile, operating system versions
2. Attempt `vagrant up`
3. Note that NFS does not mount, ctrl-c
4. `vagrant ssh` into the box and then try to ping the host w/ `ping 192.168.33.1` -- ping will fail 
5. ping the guest from the host w/ `ping 192.168.33.99` -- ping will fail

### References
https://github.com/mitchellh/vagrant/issues/8177
https://github.com/mitchellh/vagrant/issues/8140
https://github.com/mitchellh/vagrant/issues/5802
https://github.com/wunki/vagrant-freebsd/issues/4
https://github.com/geerlingguy/drupal-vm/issues/245
https://github.com/scotch-io/scotch-box/issues/92

**Comment by chadfurman** [comment]
Solved.  

I had ran:

`ip a add 192.168.33.1/255.255.255.0 dev vboxnet0`

but I did not run

`$ ip link set vboxnet0 up`

**Comment by SimonErich** [comment]
I had the same problem with all vagrant boxes and found the solution to be:

**removing the second line in the /etc/hosts file**
just uncomment or remove the line containing:
```
     127.0.1.1 [computer-name]
```


**Installing net-tools:**
It seems like ubuntu 17.04 is not installing the package ``net-tools`` anymore.

So installing them via 
```
     sudo apt-get install net-tools
```

and it should work again.

**Comment by danepowell** [comment]
I'm having this problem on Ubuntu 17.04, and no combination of solutions mentioned in this thread has helped (I'm not able to ping the guest from the host or vice versa). Is there anything else that can be done to troubleshoot it?

**Comment by briancain** [comment]
@danepowell - If you can, please share your version of vagrant, Vagrantfile, a log of debug output from vagrant, and maybe version of virtualbox that you're using. Thanks!

**Comment by danepowell** [comment]
I figured out the issue and posted it here: https://github.com/geerlingguy/drupal-vm/issues/1480

Essentially, I needed to install the virtualbox-dkms package. I had installed Virtualbox 5.1.24 by downloading the package directly from virtualbox.org, but this package did not have a dependency on virtualbox-dkms like the version in the zesty repos does.

**Comment by yeongsheng-tan** [comment]
@danepowell installing virtualbox-dkms package for Debian Jessie VirtualBox 5.1.24 equivalent package did not solve the issue for me.

There is a known bug in VirtualBox 5.1.24 filed [here](https://www.virtualbox.org/ticket/16911)

Apparently, you need to manually bring up the vboxnet interface used by your guest OS.

Assuming your NIC interface used by your VM brought up by 'vagrant' is vboxnet0, just run the following to make the nfs mount go through w/o issues:
`ip link set vboxnet0 up`

**Comment by nomasprime** [comment]
Think this might need reopening: `net-tools` already installed on 17.04.

**Comment by darkn3rd** [comment]
@chadfurman you ran `ip a add 192.168.33.1/255.255.255.0 dev vboxnet0` on the host?

**Comment by edmunds22** [comment]
Try switching off the ubuntu UFW temporarily
