### ISSUE TITLE
Vagrant (with libvirt) creating strange networks and then failing to work

### ISSUE THREAD

**Issue by JacobCZ** [mitchellh/vagrant#8631]
When ```vagrant up``` is run, instead of creating the desired network, a ```centos6-guset0``` network is created and networking does not work in the VM.

### Vagrant version
1.8.5

### Host operating system
Fedora 25 (4.10.17-200.fc25.x86_64)

### Guest operating system
Centos 6

### Vagrantfile
https://gist.github.com/JacobCZ/0f85f0ffd455a3a886f379a494d83cb8

### Debug output
https://gist.github.com/JacobCZ/afbbbddb690ec705b975f1905a618ef6

### Expected behavior
Create network ```vagrant-libvirt``` and listen on it

### Actual behavior
```centos6-guest0``` network created and not working

### Steps to reproduce
1. Install Ansible plugin
2. Run ```vagrant up```
3. Wait...

**Comment by JacobCZ** [comment]
Bump?

**Comment by kikitux** [comment]
@jacobCZ are you using a plugin for libvirt?

Vagrant doesn't have libvirt/kvm support in core
https://www.vagrantup.com/docs/providers/

Could you check with the plugin part if they handle the network properly ?

Thanks

**Comment by kikitux** [comment]
@JacobCZ libvirt/kvm is not core provider.

Can you check with the plugin provider you are using?

Thanks
