### ISSUE TITLE
vagrant plugin Install failing with Ruby errors

### ISSUE THREAD

**Issue by gnosthi** [mitchellh/vagrant#8634]
### Vagrant version
vagrant -v
Vagrant 1.9.5

### Host operating system
Windows 10

### Guest operating system
N/A

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/gnosthi/0d0b817f9464142571ac243fa25d925e
### Expected behavior
Plugin should be installed

### Actual behavior
Ruby throws error

### Steps to reproduce
1.Install Vagrant on Windows 10 64bit maching
2.Reboot machine.
3.From console run vagrant plugin install <plugin-name>
4.Fail.

**Comment by gnosthi** [comment]
### Debug output
https://gist.github.com/gnosthi/0d0b817f9464142571ac243fa25d925e
### Expected behavior
Plugin should be installed

### Actual behavior
Ruby throws error

### Steps to reproduce
1.Install Vagrant on Windows 10 64bit maching
2.Reboot machine.
3.From console run vagrant plugin install <plugin-name>
4.Fail.

### References

**Comment by chrisroberts** [comment]
Hi there,

It looks like this is an upstream issue with Ruby. The latest version of Vagrant ships with a newer version of Ruby that does not include this bug. For more information on the bug itself see the links below:

* https://github.com/rubygems/rubygems/issues/1700
* https://bugs.ruby-lang.org/issues/13081

Cheers!
