### ISSUE TITLE
Nearly impossible to download boxes

### ISSUE THREAD

**Issue by akamensky** [mitchellh/vagrant#8640]
### Vagrant version
`1.9.5`

### Host operating system
`Mac OS X Sierra 10.12.4`

### Guest operating system
`irrelevant`

### Vagrantfile
`irrelevant`

### Expected behavior
Should be able to download

### Actual behavior
Connection breaks, speed drops to 0 and stays 0 forever

### Steps to reproduce
1. Be anywhere in Asia
2. Try to download a box from Hashicorp storage using `vagrant box add box/name`
3. ...
4. Profit

### Comments
This has been happening forever not sure why vagrant community ignores this. Attached screenshot shows two attempts, first just drops speed to 0 and keeps increasing ETA, second fails after about 5 minutes trying to connect to remote host.

![screen shot 2017-06-02 at 12 08 03 pm](https://cloud.githubusercontent.com/assets/985805/26710498/da088a3a-478c-11e7-9351-7bec38390e3b.png)

**Comment by dradetsky** [comment]
@akamensky no doubt you've managed to download a box by now, but: the first step would be to verify that it's not just that either your network or atlas's network isn't temporarily crappy. You can directly download a box like 

https://atlas.hashicorp.com/centos/boxes/7/versions/1704.01

from, e.g., the url

https://atlas.hashicorp.com/centos/boxes/7/versions/1704.01/providers/virtualbox.box

which you could then add by filepath.

if you can't get that with curl/wget/browser, complain to your isp or hashicorp's ops team. if you can, this is an actual bug.

**Comment by chrisroberts** [comment]
Closing as dup of #8434 with reference to this issue.
