### ISSUE TITLE
Port forwarding failing when no competing port

### ISSUE THREAD

**Issue by mbbroberg** [mitchellh/vagrant#8652]
Any use of `config.vm.network` results in an inability to boot the VM. I've attempted many combinations of ports on each side. 

### Vagrant version
Vagrant 1.9.5

### Host operating system
MacOS 10.12.5

### Guest operating system
Using virtualbox - Version 5.1.22 r115126 (Qt5.6.2)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_url = "measurebox"
  config.vm.network "forwarded_port", guest: 5601, host: 5601

  config.vm.provision 'shell', inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install elasticsearch -y
    sudo systemctl restart elasticsearch
    systemctl status elasticsearch
  SHELL
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Gist of [output is here](https://gist.github.com/mbbroberg/1af0b8c0634bcd1944f74b15cd6a1d64)

### Expected behavior
`vagrant up` succeeds with ports mapped 

### Actual behavior
`vagrant up` fails no matter which port I try

### Steps to reproduce
1. uncomment the `forwarded_port` section 
2. `vagrant reload` or `vagrant up`

Note that I checked for competing applications and see nothing hitting the same ports: 

```
> lsof -n |grep LISTEN
P72E3GC48 40537 mjbrende    9u     IPv4 0x858e01a82f8dd0d9        0t0      TCP 127.0.0.1:53857 (LISTEN)
SpotifyWe 61446 mjbrende    5u     IPv4 0x858e01a84ecdf4b9        0t0      TCP 127.0.0.1:4370 (LISTEN)
SpotifyWe 61446 mjbrende    6u     IPv4 0x858e01a84ec80db1        0t0      TCP 127.0.0.1:4380 (LISTEN)
DashlaneP 78863 mjbrende   11u     IPv4 0x858e01a82f5339d1        0t0      TCP 127.0.0.1:11456 (LISTEN)
Amazon    79236 mjbrende   18u     IPv4 0x858e01a84290edb1        0t0      TCP *:18800 (LISTEN)
VBoxHeadl 83623 mjbrende   15u     IPv4 0x858e01a83ef0c2c9        0t0      TCP 127.0.0.1:rockwell-csp2 (LISTEN)
```

### References
No related issues from what I see.

**Comment by chrisroberts** [comment]
Hi there. The debug output you have provided does not seem to match the configuration you have defined in your Vagrantfile. The debug output shows an error attempting to forward a guest port to 8080 on the host which is unavailable. Can you please provide the debug output for the given Vagrantfile? 

Thanks!

**Comment by mbbroberg** [comment]
Good catch @chrisroberts! My mistake. I reran after correcting the Vagrantfile and... of course.. it works without any issues. Updated the [log file](https://gist.github.com/mbbroberg/1af0b8c0634bcd1944f74b15cd6a1d64). Closing now that I can't reproduce it.
