### ISSUE TITLE
`docker-compose` not found in `PATH` although it exists

### ISSUE THREAD

**Issue by HarryWeppner** [mitchellh/vagrant#8660]
### Vagrant version

```bash
$ vagrant -v
Vagrant 1.9.5
```

### Host operating system

- macOS 10.12.5
- Docker for Mac
  ```
  Version 17.03.1-ce-mac12 (17661)
  Channel: stable
  d1db12684b
  ```

### Guest operating system

Docker container.

### Expected behavior

Docker provider should create container using `docker-compose`.

### Actual behavior

`vagrant up` fails with the error:
 
```
Vagrant has been instructed to use to use the Compose driver for the
Docker plugin but was unable to locate the `docker-compose` executable.
Ensure that `docker-compose` is installed and available on the PATH.
```

### Steps to reproduce
1. `vagrant up`

NOTE: can't include the exact `Vagrantfile` as it refers to internal resources, i.e. docker images from a private registry. The requirements to reproduce are to set `d.compose = true`, i.e. whenever using the Compose driver.

### References

- #8659 fixes the check for `docker-compose` rather than `vagrant-compose`

**Comment by chrisroberts** [comment]
Fixed via #8659. Thanks!
