### ISSUE TITLE
Audio driver gets reset to null for virtualbox boxes on boot

### ISSUE THREAD

**Issue by Neurrone** [mitchellh/vagrant#8671]
### Vagrant version
1.9.5

### Host operating system
Win10, x64

### Guest operating system
win10 x64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "inclusivedesign/windows10-eval"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Win10"
    vb.gui = true
    vb.linked_clone = true
  end
  
  config.vm.provision "shell", inline: <<-SHELL
     choco install nvda --no-progress -y
  SHELL
end
```

### Debug output

[Log output](https://gist.github.com/Neurrone/2920d6726967e7437ae1a2d075b4748a)

### Expected behavior
Audio output should work when starting up VMs with vagrant up

### Actual behavior
Vagrant automatically sets the audio driver to null when booting the VM. This line in the log stands out:
```
  INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "modifyvm", "7138b0f9-8016-4413-9270-fe70382d8326", "--audio", "null", "--audiocontroller", "hda"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
```

### Steps to reproduce

1. Use above vagrantfile, and do vagrant up.
2. Shut down the VM (in case the original virtualbox image has audio disabled), and configure the VM to enable audio and use DirectSound
3. vagrant up again. Audio should work. Instead it is automatically changing the VM on boot to reset the audio driver to null. However if you vagrant halt, enable audio and start it from the virtualbox gui, audio works.

Hoping this can be fixed, since I rely on audio working for my screen reader.

**Comment by Neurrone** [comment]
Bump

**Comment by kikitux** [comment]
Hello

Per our documentation, we suggest to disable usb and audio, however I am quite positive that Vagrant doesn't disable it.

If you vagrant up a different box, stop, add audio and then vagrant reload, you will notice vagrant doesn't remove the audio device.

So, I may suspect something in the included Vagrantfile of the box may be doing this.

~/.vagrant.d/boxes/inclusivedesign/*

you can search like 

```
find ~/.vagrant.d/boxes/inclusivedesign/ -name 'Vagrantfile*'
```

I would suggest try a different box.

I will close this issue, however please feel free to follow up in the mailing list:
https://groups.google.com/forum/#!forum/vagrant-up

Thanks
