### ISSUE TITLE
'check_version_conflict': can't activate ffi-1.0.11

### ISSUE THREAD

**Issue by thorr18** [mitchellh/vagrant#8675]
I'm getting an error when trying to install Vagrant plugin for VirtualBox. 

### Vagrant version
`Vagrant 1.9.5`

### Host operating system
```
ProductName:	Mac OS X
ProductVersion:	10.12.5
BuildVersion:	16F73
```

### Debug output
[vagrant_plugin_install.dbg on Gist](https://gist.github.com/thorr18/ab893760b42b6dbd043f46bd352b03e4)

### Expected behavior
Command runs without error
`vagrant plugin install virtualbox`

### Actual behavior
As seen in linked debug output: 

> /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate ffi-1.0.11, already activated ffi-1.9.18 (Gem::LoadError)

Followed by a stack trace. 

### Steps to reproduce
1. Install Vagrant 1.9.5
2. Run "vagrant plugin install virtualbox"
3. Observe gem error

**Comment by chrisroberts** [comment]
Strict constraints on builtin libs will be enabled on the next release. However, the gem you are attempting to install is not a vagrant plugin and will not function within Vagrant due to dependency constraint limitations. 

Cheers!

**Comment by thorr18** [comment]
OK, thanks. I was able to install it by downgrading Vagrant to 1.8.7 [(install debug log)](https://gist.github.com/thorr18/3318d18f526d1647b80292327868099b#file-plugin_install_virtualbox-dbg)
`vagrant plugin install virtualbox`
`Installing the 'virtualbox' plugin. This can take a few minutes...`
`Installed the plugin 'virtualbox (0.9.2)'!`
