### ISSUE TITLE
unable to mount shared folders after initial provisioning

### ISSUE THREAD

**Issue by jimbasilio** [mitchellh/vagrant#8683]
### Vagrant version
1.9.5
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
win7

### Guest operating system
OEL 7.3

### Vagrantfile
Appropriate section of file
```ruby
  # mounts the users home directory (ex. c:\users\<ntid>\)
  config.vm.synced_folder "#{ENV['USERPROFILE']}", "/windows_home"
 
  ## mount common folder to the vm
  config.vm.synced_folder "../", "/virtual-machines"
  
  ## mount common folder to the vm
  config.vm.synced_folder "../../../", "/dev"
```

### Debug output
https://gist.github.com/jimbasilio/aaca8adc751b458c7f4446b4116d5223

### Expected behavior
Shared folder should have been mounted.

### Actual behavior
Protocol error when running mount command

### Steps to reproduce
1. Provision machine
2. Halt machine
3. Vagrant up/reload .. can't mount shares anymore

### More Detail
I also tried downgrading to VB 5.1.18 - same result. If I run the mount command manually inside my VM I also receive the protocol error. 

```
[vagrant@localhost ~]$ sudo mount -t vboxsf -o uid=1000,gid=1000 dev /dev
/sbin/mount.vboxsf: mounting failed with the error: Protocol error

[vagrant@localhost ~]$ dmesg
...
[  516.979115] sf_read_super_aux err=-71
[  516.979247] sf_read_super_aux err=-71
[  516.979300] sf_read_super_aux err=-71
```

I adjusted my source locally for this file
https://github.com/mitchellh/vagrant/blob/master/plugins/guests/linux/cap/mount_virtualbox_shared_folder.rb#L22

To use ```mount.vboxsf``` instead of ```mount -t vboxsf``` and the problem is resolved.

Are you open to a patch to change the line referenced above to be
```
mount_command = "mount.vboxsf -o #{mount_options} #{name} #{guest_path}"
```
??

**Comment by jimbasilio** [comment]
Oh, didn't mention this was tried on VB 5.1.22 and on VB 5.1.18 with vagrant-vbguest 0.14.2 to ensure VB Guest Plugins are installed correctly (symlink exists, vboxsf module loaded, driver present).

**Comment by jimbasilio** [comment]
Of course 5 minutes after posting this I figure it out (after a day of trying things).

The problem is there is a symlink in my home directory for the vagrant user for 'dev' (that points to '/dev'. It was to help us in some other area.

I remove that symlink and the mount works correct.

I have NO IDEA why this works (or doesn't work to begin with). I also don't know why using the direct mount.vboxsf works when mount fails. Any help/advice there appreciated if you do know.

The patch still seems like a good idea since I've seen this problem in various forms over the years when trying to google a solution and using mount.vboxsf solves the problem as far as I can tell.

**Comment by chrisroberts** [comment]
Hi there. From the description this sounds like an issue with the box itself. The mount command generally fails when the box is not properly configured, or the guest tools have a bug. At this point I don't see the advantage of changing the mount command as it helps to mask underlying issues of the box itself.

Cheers!
