### ISSUE TITLE
remove the need for "-c" argument to execute command with vagrant ssh

### ISSUE THREAD

**Issue by brianjmurrell** [mitchellh/vagrant#8684]
### Vagrant version
Vagrant 1.8.5

### Host operating system
Fedora 25

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
N/A

### Actual behavior
N/A

### Steps to reproduce
N/A

It would be much more useful and compatible with regular ssh if the `vagrant ssh` command did not require the `-c` switch (and it's argument to be quoted) to specify the command such as one doesn't have to do with regular ssh.

IOW, `vagrant ssh node1 command` should work exactly like `ssh node1 command` would if node1 were a regular host.

**Comment by chrisroberts** [comment]
This can be done using `--`:

```
$ vagrant ssh node1 -- command
```

Cheers!

**Comment by brianjmurrell** [comment]
In fact `vagrant ssh-config >> .ssh/config` actually suits my needs much better.

Is there any thought about formalizing this as a function of `vagrant up` and `vagrant destroy` so that it just happens, most probably of course with some kind of switch in the _Vagrantfile_?
