### ISSUE TITLE
Restarting MacOS does not attempt to gracefully shutdown vagrant

### ISSUE THREAD

**Issue by Smtgr14** [mitchellh/vagrant#8696]
### Vagrant version
1.9.5
### Host operating system
MacOS Sierra 10.12.4

### Guest operating system
bento/ubuntu-16.04

### Vagrantfile
```ruby
Not Applicable
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?
Shutdown of the host operating system should gracefully shutdown the guest operating system or interrupt host shutdown.

### Actual behavior
What actually happened?
Upon booting up the host, vagrant reports the box was aborted.

### Steps to reproduce
1. run ```vagrant up``` on any valid vagrantfile.
2. Once the VM is running, press shutdown on the host operating system.
3. Boot up host and run ```vagrant status``` from directory of vagrantfile. Output will indicated machine was aborted.

**Comment by chrisroberts** [comment]
Hi there,

This behavior would fall under the responsibility of the provider in use, not Vagrant itself. Vagrant does not have a long running service and cannot know when a system shutdown is occurring. The provider should be properly handling a system shutdown and either halt or suspend VMs. 

Cheers!
