### ISSUE TITLE
ssh connection between multiple VM

### ISSUE THREAD

**Issue by richdia** [mitchellh/vagrant#8701]
### Vagrant version
Vagrant 1.9.5

### Host operating system
Windows 7 Ultimate

### Guest operating system
Debian 8

I have several machine that seeks to connect by ssh to one specific machine. 

I tried 
- configuring ssh on the main receiver machine to allow all ssh from 192.168.XX.XX
- creating a key and copying it to the givers machines
- adding ip to /etc/hosts.allow
- manually adding https://github.com/mitchellh/vagrant/tree/master/keys to every machine

Is there any way to allow ssh connection between multiple vm?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
