### ISSUE TITLE
Restoring from .box file has no affect

### ISSUE THREAD

**Issue by BentCoder** [mitchellh/vagrant#8709]
Hi,

I am trying to restore my box from `/Users/inanzzz/Webserver/php7/php7.box` file but I don't see any evidence of this file being read while running `vagrant up`. What I am missing or doing wrong? I backed it up with `vagrant package` command.

Thanks

**SYSTEM**

```
Host: MacOS 10.10.5
Guest: Ubuntu 16.04
Vagrant 1.9.5
Virtualbox 5.1.22
```

**VAGRANTFILE**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.box_url = "file:///Users/inanzzz/Webserver/php7/php7.box"

    config.vm.define :php7 do |php7_config|
        php7_config.vm.hostname = "php7"
        php7_config.vm.network "private_network", ip: "192.168.50.30"
    end

    config.vm.provider :virtualbox do |virtualbox_config|
        virtualbox_config.name = "Php7 - Ubuntu 16.04 - 50.30"
        virtualbox_config.memory = 2048
        virtualbox_config.cpus = 2
    end

    config.vm.synced_folder "", "/var/www/html", nfs: true, mount_options: ["actimeo=2"]
end
```

**OUTPUT**
[https://pastebin.com/LSmbqAiN](https://pastebin.com/LSmbqAiN)

**Comment by chrisroberts** [comment]
Hi there,

If the box has already been added (in this case, the `ubuntu/xenial64` box) it will not be added again. You can either remove the box:

```
$ vagrant box remove ubuntu/xenial64
```

and the next `vagrant up` will import the locally defined box, or you can forcibly add it:

```
$ vagrant box add ubuntu/xenial64 /Users/inanzzz/Webserver/php7/php7.box --force
```

You may want to use a different name for this box just to prevent confusion later that it's a customized box, not the upstream box.

Cheers!

**Comment by BentCoder** [comment]
Thanks, it has been solved now.

_Note:_ I've run into https://github.com/mitchellh/vagrant/issues/5186 problem but solved it by adding `config.ssh.username = "ubuntu"` to my Vagrantfile.
