### ISSUE TITLE
Files can be created in windows host mount with long filenames can't be seen by ls

### ISSUE THREAD

**Issue by robwiss** [mitchellh/vagrant#8712]
### Vagrant version
    $ vagrant -v
    Vagrant 1.9.5

### Host operating system
Windows 10 Pro Version	10.0.15063 Build 15063 (tested from WSL and from cmd)

### Guest operating system
ubuntu/trusty64 box

    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 14.04.5 LTS
    Release:	14.04
    Codename:	trusty

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
end
```

### Expected behavior
Created a file in the `/vagrant` mount with a filename of length 255. Expected to be able to see the file using `ls`.

### Actual behavior
`ls` did not show the file that was created. However, a terminal in the host OS was able to see the file and the file could be accessed by other tools, such as `cat` or even `ls` if the filename to was specified as an argument.

### Steps to reproduce
```
vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ echo "stuff" > $(python -c "print 'a'*255")
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls
Vagrantfile
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ cat aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
stuff
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ls aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
then check the same directory from the host:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ logout
Connection to 127.0.0.1 closed.
rob@ntel0001:/mnt/c/Users/robwiss/projects/vagrant_path_bug
$ ls
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Vagrantfile
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for this report, however this is not an issue within Vagrant. The mounted filesystem within the guest is provided via a VirtualBox module and the display limitation you are experiencing is a limitation within that module.

Cheers!
