### ISSUE TITLE
[Question] - Handling upgrades of softwares in Vagrant

### ISSUE THREAD

**Issue by vrenjith** [mitchellh/vagrant#8715]
We have been distributing a custom build vagrant box for developers which is used as a base box for all projects from our custom vagrant registry. 
It is becoming increasing difficult to ask teams to constantly do a `vagrant box update` to refresh the versions of various softwares installed. Are there any recommendations about how to handle this instead of publishing a new box everytime?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
