### ISSUE TITLE
Error in vagrant up on Windows 10 Ubuntu bash with ssh

### ISSUE THREAD

**Issue by midikem** [mitchellh/vagrant#8717]
I am using ssh in Windows bash mode and when I do "vagrant up windows" I get an error. It works if I do a "vagrant provision windows" after the "vagrant up windows" have failed. But it does not look so good with this huge error! 

### Vagrant version
vagrant version
Installed Version: 1.9.2
Latest Version: 1.9.5
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/mitchellh/vagrant/blob/v1.9.5/CHANGELOG.md

### Host operating system
cat /etc/*-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18
DISTRIB_CODENAME=sarah
DISTRIB_DESCRIPTION="Linux Mint 18 Sarah"
NAME="Linux Mint"
VERSION="18 (Sarah)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18"
VERSION_ID="18"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
UBUNTU_CODENAME=xenial

### Guest operating system
OS Name Microsoft Windows 10 Pro 
Version 10.0.14393 Build 14393

Bash: vagrant@WINDOWS10:~$ cat /etc/*-release                                                                                 DISTRIB_ID=Ubuntu                                                                                                       DISTRIB_RELEASE=14.04                                                                                                   DISTRIB_CODENAME=trusty                                                                                                 DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"                                                                                NAME="Ubuntu"                                                                                                           VERSION="14.04.5 LTS, Trusty Tahr"                                                                                      ID=ubuntu                                                                                                               ID_LIKE=debian                                                                                                          PRETTY_NAME="Ubuntu 14.04.5 LTS"                                                                                        VERSION_ID="14.04"                                                                                                      HOME_URL="http://www.ubuntu.com/"                                                                                       SUPPORT_URL="http://help.ubuntu.com/"                                                                                   BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"   

### Output
Bringing machine 'windows' up with 'virtualbox' provider...
==> windows: Clearing any previously set forwarded ports...
==> windows: Clearing any previously set network interfaces...
==> windows: Preparing network interfaces based on configuration...
    windows: Adapter 1: nat
    windows: Adapter 2: bridged
==> windows: Forwarding ports...
    windows: 22 (guest) => 2222 (host) (adapter 1)
==> windows: Running 'pre-boot' VM customizations...
==> windows: Booting VM...
==> windows: Waiting for machine to boot. This may take a few minutes...
    windows: SSH address: 192.168.29.156:22
    windows: SSH username: vagrant
    windows: SSH auth method: private key
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
    windows: Warning: Connection refused. Retrying...
==> windows: Machine booted and ready!
==> windows: Checking for guest additions in VM...
==> windows: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown '' || true
/sbin/ip addr flush dev ''
-# Remove any previous network modifications from the interfaces file
sed -e '/^#VAGRANT-BEGIN/,$ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces.pre
sed -ne '/^#VAGRANT-END/,$ p' /etc/network/interfaces | tac | sed -e '/^#VAGRANT-END/,$ d' | tac > /tmp/vagrant-network-interfaces.post

cat \
  /tmp/vagrant-network-interfaces.pre \
  /tmp/vagrant-network-entry \
  /tmp/vagrant-network-interfaces.post \
  > /etc/network/interfaces

rm -f /tmp/vagrant-network-interfaces.pre
rm -f /tmp/vagrant-network-entry
rm -f /tmp/vagrant-network-interfaces.post

/sbin/ifup ''

Stdout from the command:

Stderr from the command:

/etc/network/interfaces:19: too few parameters for iface line
/sbin/ifdown: couldn't read interfaces file "/etc/network/interfaces"
SO_SNDBUF: Invalid argument
/etc/network/interfaces:19: too few parameters for iface line
/sbin/ifup: couldn't read interfaces file "/etc/network/interfaces"

**Comment by chrisroberts** [comment]
Hi there,

Vagrant does not support Windows guest configuration via an sshd running within the WSL. Because the WSL emulates a Linux system, Vagrant will detect the guest incorrectly as Linux. The sshd process running within the WSL is in many ways isolated from the full Windows system which makes it ill suited to use for Vagrant's communication with the guest during the `up` phase as it's doing system setup tasks. It would be better to use an openssh install directly within Windows for Vagrant's communication.

Cheers!
