### ISSUE TITLE
vagrant package dont work with GetoptLong defined in Vagrantfile

### ISSUE THREAD

**Issue by midikem** [mitchellh/vagrant#8718]
I have defined GetoptLong in my Vagrantfile and this destroys "vagrant package --base asd". To get it to work I have to comment out the GetoptLong stuff in vagrantfile and then run "vagrant package --base asd" again.

opts = GetoptLong.new(
  [ '--branch', GetoptLong::OPTIONAL_ARGUMENT ],
).each do |opt, arg|
  case opt
    when '--branch'
      branch=arg
  end
end

vagrant package --base test_boxes_windows_1497864360998_15627 --output windows_10.box
/opt/vagrant/embedded/gems/gems/vagrant-1.9.2/bin/vagrant: unrecognized option `--base'
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: Vagrantfile
Line number: 0
Message: GetoptLong::InvalidOption: unrecognized option `--base'

**Comment by chrisroberts** [comment]
Hi there. This is not a bug with Vagrant, rather you are attempting to parse the command line options without properly defining all allowed options. The Vagrantfile is not a recommended place to parse command line options as Vagrant already parses the command line options. You may want to investigate using environment variables or some other approach to customize your Vagrantfile. 

Cheers!

**Comment by midikem** [comment]
Well i dont agree with you that this is not a bug in vagrant. I still think it is and I will try to explain why I think so. The Vagrantfile is basically the root of the user. If stuff the user want to do is not defined there it should not work. In this case we have different packeges we want to install depending on the user input. And the way to do that in ruby is the way we have done it. Its the simplest approach for the user to install diffrent stuff depending on what they write to the command. The way its done in package is probebly the same. But the package command is not the root of the user so to speek. Its no way to know potential stuff that could be destroyed here. So then i think the problem is in package. Because package is using stuff the user has to input. So what do I suppose then as a fix. One way to fix this is to auto generate an include for this from the package command to the Vagrantfile. Basically something adding the user commands of base and output that is used in the package command. But I dont think this is really the way to go. Its a pretty clumpsy approach. What should be done here is rather a redesign of package command. Package is not working as everything else in vagrant. Its the odd horse so to speak. The user should not write stuff that could be hard to know. Like the base. The base should be removed and replaced with the box name. Like if you write vagrant up windows. Then it should be vagrant package windows as well and not vagrant pagkage --base (a wierd number you have to lookup how to get that is basically genereted in vagrant). The output in package is basically not needed. It should use the name it has in the vagrantfile. So basically if you write vagrant package windows. Then the output should be windows.box. The problem here is that maybe the output location should be possible to change, but then its sufficiant to use a environment variable. If its done like this instead then vagrant would get more stable and everything works more as expected with the package command.
