### ISSUE TITLE
vagrant up crashes with "undefined local variable or method 'vagrant'"

### ISSUE THREAD

**Issue by yellowtomato8675** [mitchellh/vagrant#8721]
Vagrant crashes trying to `up` my box.
<mydir>/Vagrantfile:9:in `block in <top (required)>': undefined local variable or method `vagrant' for main:Object (NameError)

I suspect that there is some config or state missmatch somewhere, because:

- this Vagranfile previously built fine.  I've been working on developing a part of our CI which builds base boxes, and experimented with deleting / re-building things multiple times, possibly with the wrong order, and including machine renames.
- other Vagrantfiles on my machine continue to build fine

however, i have tried blowing away the .vagrant.d/ folder, as well as just cloning a new copy of my repo to my machine, and rebooting to clear any possible environment changes.

### Vagrant version
Vagrant 1.9.5

### Host operating system
xubuntu 16.04, 64b

### Guest operating system
debian9-based (I believe this is n/a for this issue)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
	config.ssh.insert_key = false

	config.vm.box = "debian/stretch64"
	config.vm.box_download_insecure = true # not recognizing installed corp root certs on linux
	config.vm.hostname = "MyCobase-deb"

        config.vm.synced_folder ".", "/vagrant", disabled: false
        config.vm.synced_folder "vagrant_vm_share/", "/vagrant_vm_share/", create: true, owner: vagrant
        
	# Configure micron proxy
	if Vagrant.has_plugin?("vagrant-proxyconf")
		config.proxy.enabled = true
		config.proxy.http = "http://proxy.MyCo.com:8080"
		config.proxy.https = "http://proxy.MyCo.com:8080"
		config.proxy.no_proxy = "localhost,127.0.0.1"
	end
	
	config.vm.provider :virtualbox do |vb|
		vb.name = "MyCobase-deb"
		vb.customize [ "modifyvm", :id, "--memory", "4096" ]
		vb.customize [ "modifyvm", :id, "--cpus", "2" ]
		vb.customize [ "modifyvm", :id, "--ioapic", "on" ]
	end
	
	config.vm.provision :ansible_local do |ansible|
		ansible.playbook = "ansible/playbook.yml"
		ansible.groups = {
			"all:vars" => {
				"http_proxy" => "http://proxy.MyCo.com:8080",
				"https_proxy" => "http://proxy.MyCo.com:8080",
				"no_proxy" => "localhost,127.0.0.0/8,::1"
			}
		}
	end
end 

```

### Debug output
Gist output. Two files:

- vagrant.log (the failure)
- vagrant2.log (an ~identical vagrant file, jut different path/name, works)
https://gist.github.com/anonymous/a36826c51fa9e5701b28db34290be791

### Expected behavior
Hopefully not crash :)   If there is a conflict in some config somewhere, it should at least provide some breadcrumb for the user to follow up on.

### Actual behavior
crashes with:
DEBUG loader: Loading from: root (evaluating)
<mydir>/Vagrantfile:9:in `block in <top (required)>': undefined local variable or method `vagrant' for main:Object (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/loader.rb:113:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/loader.rb:107:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/loader.rb:107:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/loader.rb:104:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/config/loader.rb:104:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:746:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:746:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:492:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:479:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:728:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/bin/vagrant:141:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/bin/vagrant:141:in `<main>'

### Steps to reproduce
none

**Comment by mboard182** [comment]
This crash persists even deleting the .vagrant (local) and .vagrant.d/ (in home) folders

**Comment by chrisroberts** [comment]
Hi there,

The error you are encountering is due to this line in your Vagrantfile:

```ruby
        config.vm.synced_folder "vagrant_vm_share/", "/vagrant_vm_share/", create: true, owner: vagrant
```

The `owner: vagrant` is what is causing the issue because `vagrant` is not a valid method nor is it a variable. It is likely you want it to be a string and look like this:

```ruby
        config.vm.synced_folder "vagrant_vm_share/", "/vagrant_vm_share/", create: true, owner: "vagrant"
```

Hope that helps. Cheers!
