### ISSUE TITLE
vagrant 1.9.5 impossible to use 'vagrant share --driver ngrok' to share SSH only access

### ISSUE THREAD

**Issue by taurus-forever** [mitchellh/vagrant#8726]
Hi,

Goal: share SSH ONLY access to Vagrant box with remote developers.

Atlas based way works well: vagrant login ; vagrant share mybox --ssh --disable-http

Unfortunately Atlas based 'vagrant share' is deprecated since today:
https://www.vagrantup.com/docs/vagrant-cloud/vagrant-cloud-migration.html

I have tried to migrate on 'vagrant share --driver ngrok' which created a lot of questions/usability/issue to be reported, IMHO.

Issue 1) ngrok errors/warnings are not visible without debugging (see line 70):
> https://gist.github.com/taurus-forever/fadd7c4f0473a0cae94823a3b5687fe5

It confuses new users a lot, as we do not know what to expect here, I believe debug error message should be shown to the end users:
> Vagrant was unable to detect an HTTP port for your machine.

Issue 2) calling ngrok with option '--disable-http' crashing vagrant:
 > vagrant share --driver ngrok --disable-http
...
> /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.8/lib/vagrant-share/activate.rb:2405:in `join': No live threads left. Deadlock? (fatal)

Full log with debug is here: https://gist.github.com/taurus-forever/8378109b0cad20d08697519882975d48
NOTE: the file /tmp/vagrant-share20170627-14842-gn1hji was not created at all which caused 'ngrok help' output and vagrant crashed to parse it.

Issue 3) adding option '--ssh' reports nothing without debug like 1) above, and debug shows error:
> vagrant share --driver ngrok --disable-http --ssh
...
> ERROR share: Unexpected error: NoMethodError - undefined method `setup_ssh_share' for #<VagrantPlugins::Share::Command::Share:0x00000001e28a50>

Full logs: https://gist.github.com/taurus-forever/6463173df4e227ce9fcba44648b284f3

I have tried all the combinations of available options for 'vagrant share' while was not able to make SSH ONLY work for me. Are there some special black magic necessary here?

Tnx in advance!

###############################

### Vagrant version:
1.9.5
### ngrok version:
2.2.4
### Host operating system:
Linux Mint 18 Sarah
### Guest operating system:
Debian 9 Stretch
### Vagrantfile:
default from public box file:
> vagrant init debian/stretch64; vagrant up --provider virtualbox

### Expected behavior
'vagrant share --driver ngrok' should tells me a command to be executed on remote side to connect VM.

### Actual behavior
'vagrant share --driver ngrok' reports nothing useful without debug.

### Steps to reproduce
1. cd /tmp/ ; vagrant init debian/stretch64; vagrant up --provider virtualbox
2. vagrant share --driver ngrok --disable-http --ssh

**Comment by chrisroberts** [comment]
This has been fixed in vagrant-share 1.1.9 which is included in the vagrant 1.9.6 release. Cheers!
