### ISSUE TITLE
Message: UncaughtThrowError: uncaught throw "VirtualBox version too old. Please upgrade to 5.1"

### ISSUE THREAD

**Issue by bbethell** [mitchellh/vagrant#8727]
Message: UncaughtThrowError: uncaught throw "VirtualBox version too old. Please upgrade to 5.1"

**Comment by chrisroberts** [comment]
Hi there,

This error is indicating that you need to upgrade your version of VirtualBox. If you have a larger issue to report, please fill out the template when creating a new issue. 

Thanks!

**Comment by bbethell** [comment]
hi,

the isue is virtual box is on thr latest version.

Thanks

-------- Original message --------
