### ISSUE TITLE
Source for Vagrant Share with ngrok?

### ISSUE THREAD

**Issue by rmccue** [mitchellh/vagrant#8766]
With the move from Vagrant Cloud to ngrok as the default provider for Vagrant Share, is it possible for the source for Vagrant Share to be released?

(As a plugin developer, it would be useful to see how it's working internally.)

**Comment by chrisroberts** [comment]
Hi there. At this point there are no plans for releasing the Vagrant share source. If that changes, it will be announced on the Vagrant mailing list.

Cheers!

**Comment by rmccue** [comment]
Thanks anyway! :)
