### ISSUE TITLE
Unable to start a machine using docker provider (container dies immediately)

### ISSUE THREAD

**Issue by sserbin** [mitchellh/vagrant#8769]
### Vagrant version
```
Vagrant 1.9.7
```
### Docker version: 
```
17.04.0-ce, build 4845c56
```
### Host operating system
```
Ubuntu 17.04 4.10.0-22-generic
```

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  #config.vm.box = 'ubuntu/xenial64'
  
  config.vm.provider "docker" do |d|
      d.image = "ubuntu"
      # d.has_ssh = true
  end
  config.vm.define "test" do |test|
  end
end
```

### Expected behavior
Docker container started.

### Actual behavior
Docker container does not start/starts and exits immediately (as indicated by the log below).
```
docker -ps a:
628548138f44        ubuntu              "/bin/bash"              3 minutes ago       Exited (0) 3 minutes ago                       vagrant-test_1499720762
```

`vagrant up` log:
```
Bringing machine 'test' up with 'docker' provider...
==> test: Creating the container...
    test:   Name: vagrant_test_1499720762
    test:  Image: ubuntu
    test: Volume: /home/serg/src/vagrant:/vagrant
>>docker-events: 2017-07-11T00:06:02.124568499+03:00 container create 628548138f448943d4541c1a0d9a48590b3739dd6efd8918e744cd371f744843 (image=ubuntu, name=vagrant-test_1499720762)
>>docker-events: 2017-07-11T00:06:02.153157536+03:00 network connect 3b5414855f3a11ee3fefb162dcb318078525c453d8ee785379af8aaaeb747286 (container=628548138f448943d4541c1a0d9a48590b3739dd6efd8918e744cd371f744843, name=bridge, type=bridge)
>> docker-events: 2017-07-11T00:06:02.414697165+03:00 container start 628548138f448943d4541c1a0d9a48590b3739dd6efd8918e744cd371f744843 (image=ubuntu, name=vagrant-test_1499720762)
    test:  
    test: Container created: 628548138f448943
>> docker-events: 2017-07-11T00:06:02.470738567+03:00 container die 628548138f448943d4541c1a0d9a48590b3739dd6efd8918e744cd371f744843 (exitCode=0, image=ubuntu, name=vagrant-test_1499720762)
>> docker-events: 2017-07-11T00:06:02.607717821+03:00 network disconnect 3b5414855f3a11ee3fefb162dcb318078525c453d8ee785379af8aaaeb747286 (container=628548138f448943d4541c1a0d9a48590b3739dd6efd8918e744cd371f744843, name=bridge, type=bridge)
==> test: Waiting for container to enter "running" state...
The container started either never left the "stopped" state or
very quickly reverted to the "stopped" state. This is usually
because the container didn't execute a command that kept it running,
and usually indicates a misconfiguration.
```

### Steps to reproduce
1. `sudo docker events&` # to capture container logs
2. `sudo vagrant up test`

Running same ubuntu container with docker directly produces expected results:
```
$ sudo docker run -it ubuntu
``` 
### Debug log:
https://gist.github.com/sserbin/a2e6864ee6e8bdd558f0d95e8b6db9e1

**Comment by briancain** [comment]
Hello @sserbin - I believe the issue here is vagrant runs this command with no other commands for the container, essentially it runs:

```
docker run --name vagrant_container_name ubuntu
```

The container does not stick around. The difference between that and what the command you have with the `-it` options is with `docker run -it ubuntu`, it logs you directly into the container in interactive mode with a tty shell, making that container stick around until you exit. You'll notice the same behavior with docker if you just run that same vagrant command above with no `-it` options.

Let me know if you have any other questions, thanks!

**Comment by sserbin** [comment]
Thanks, @briancain 

I must have missed this in the docs, but is there any configuration options to keep it active?
  
I get the same results when using `d.cmd = ["yes"]` or `d.cmd = ["sleep", "100"]` which presumably should have been keeping container working/active for a while?

**Comment by briancain** [comment]
@sserbin - this is unfortunately how `docker run -d` is designed. If there are no commands running in the foreground (or short lived commands like the ones you tried...), the container will immediately exit after being created since it's running in a `detached` state with no applications to keep alive. If you'd like the container to stick around, you should be able to give it some sort of command to stay alive. More information/reading can be found [here](http://kimh.github.io/blog/en/docker/gotchas-in-writing-dockerfile-en/#hack_to_run_container_in_the_background) on this blog post.

**Comment by sserbin** [comment]
> or short lived commands like the ones you tried
Well, the `yes` is an infinite loop so that shouldn't be the case. I've also tried it with `d.cmd = ["tail", "-f", "/dev/null"]` (as per the article you've linked) and get the exact same immediate die. 
I've also tried the `remains_running` with no difference. Is there anything else needs being configured?

Thanks

**Comment by briancain** [comment]
@sserbin hmm interesting, with the `tail` command, I am able to keep the container alive:

```ruby
  config.vm.define "docker"  do |vm|
    vm.vm.provider "docker" do |d|
      d.image = "ubuntu"
      #d.build_dir = "."
      d.cmd = ["tail", "-f", "/dev/null"]
    end
  end
```


```
brian@localghost:vagrant-sandbox % be vagrant up docker                                                 ±[●●][master]

Bringing machine 'docker' up with 'docker' provider...
==> docker: Creating the container...
    docker:   Name: vagrant-sandbox_docker_1500393852
    docker:  Image: ubuntu
    docker:    Cmd: tail -f /dev/null
    docker: Volume: /Users/brian/code/vagrant-sandbox:/vagrant
    docker:
    docker: Container created: d1fec427313daa38
==> docker: Starting container...
==> docker: Provisioners will not be run since container doesn't support SSH.
brian@localghost:vagrant-sandbox % docker ps                                                            ±[●●][master]
CONTAINER ID        IMAGE               COMMAND               CREATED              STATUS              PORTS               NAMES
d1fec427313d        ubuntu              "tail -f /dev/null"   About a minute ago   Up About a minute                       vagrant-sandbox_docker_1500393852
```

**Comment by mklemm2** [comment]
Any news on this issue? Because I have exactly the same problem. No matter what I specify as "cmd", docker ps always shows "/bin/bash" as command and the container dies after about 5 seconds.

**Comment by briancain** [comment]
@mklemm2 as I explained above [here](https://github.com/hashicorp/vagrant/issues/8769#issuecomment-315867283), this isn't an issue, it's how Docker works. If your container doesn't have anything to keep alive and run, it immediately gets destroyed.

**Comment by nqb** [comment]
Example provided by @briancain work with `ubuntu` image. 

I was unable to make it working with one of my image and I noticed that I have set `ENTRYPOINT /bin/bash` in my Dockerfile causing `tail -f /dev/null` to be run by `bash`.
