### ISSUE TITLE
`vagrant --help` fails after 1.9.7 update

### ISSUE THREAD

**Issue by Dispader** [mitchellh/vagrant#8773]
* data
  * version: `Vagrant 1.9.7`
  * Mac OS X El Capitan, 10.11.6
  * `Vagrantfile`/guest OS: Not Applicable
  * Debug output: https://gist.github.com/Dispader/dcf03986f8fb379803104fd5688498f5
* behavior
  * expected: `vagrant --help` should not explode
  * actual: `vagrant --help` explodes ( no input `Vagrantfile` required 😸 )

This seems like an angry plugin, and environment-specific, but I'm at a loss.

**Comment by chrisroberts** [comment]
Does a `vagrant plugin expunge --force` fix the issue?

**Comment by Dispader** [comment]
@chrisroberts Sorry it took so long to get back t'you on this.  From my notes, I believe so— I found an old post about plugin compatibility problems, and gave some `expunge` commands a try before reverting by brew version.  (To be double-sure, I'd like to upgrade and re-`expunge`, but it might take a couple days— I'm kinda lost if I don't have a functioning Vagrant during work-hours. 😸 ).
