### ISSUE TITLE
vagrant up hanging

### ISSUE THREAD

**Issue by amezarashi97** [mitchellh/vagrant#8779]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

vagrant -v

### Host operating system
This is the operating system that you run locally.

OS Name:                   Microsoft Windows 7 Ultimate
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. A11, 11/22/2016

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
ruby
# Copy-paste your Vagrantfile here
```# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fm
ode=666"]

    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmod
e=777","fmode=666"] }

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.
https://gist.github.com/amezarashi97/85c6c9d9308929da683c1f49ca1a7129

### Expected behavior
What should have happened?
  I don't know it's the first time I'm running both the process and vagrant.

### Actual behavior
What actually happened?
  Command line got hung

### Steps to reproduce
~~1. Read my mind~~
```
git clone https://github.com/scotch-io/scotch-box my-project
cd my-project
vagrant up
```

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- #7823

Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

Took me too much time to write this I recommend that you automatize this process some more thanks for the great stuff btw.

**Comment by hopoffbaby** [comment]
I am having the exact same issue today :(

https://github.com/mitchellh/vagrant/issues/8777

**Comment by pnedkov** [comment]
Same issue here. I am on Arch Linux. The problem started yesterday out of nowhere. After `vagrant up` it just hangs at `SSH auth method: private key` but the machine is up and running and accessible over the network. Upgrading from 1.9.6 to 1.9.7 did not make any difference. Any suggestions?

**Comment by amezarashi97** [comment]
Could you please either delete my issue or delete it whatever I don't feel like filling up my issues list with reports I spent hours writing and no one bothered even answering to it. Yes I am angry.
