### ISSUE TITLE
Vagrant share stops with 'No space left on device' error

### ISSUE THREAD

**Issue by sann3** [mitchellh/vagrant#8792]
### Vagrant version
1.9.7 (Same with 1.9.7 and 1.9.8)

### Host operating system
MacOS Sierra - 10.12.5

### Guest operating system
CentOS Linux release 7.3.1611 (Core)

### Vagrantfile
https://gist.github.com/sann3/a576ad4b6c1cadedc6c71df0e320eec3

### Debug output
https://gist.github.com/sann3/66f1cd16f4429b22790f8947343529bb

### Expected behavior
Should start vagrant share

### Actual behavior
Terminated with No space left on device error

### Steps to reproduce
1. Download the latest version of Vagrant
2. Install ngrok
3. vagrant up
4. vagrant share --ssh

**Comment by kikitux** [comment]
Hello

Please share df -Ph or equivalent from host and guest

From logs, this line:

```
ERROR warden: Error occurred: scp: /tmp/VBoxGuestAdditions.iso: No space left on device
````

Tell us:

- you may have vagrant-vbguest plugin, not important, but tell us the VM is not working as expcted.

I would suggest

Try to reproduce with a different box, without any provisioning

hashicorp/precise64

If issue happens with that box, please let us know.


Thanks
Alvaro

**Comment by sann3** [comment]
Hi
My VM working fine. While trying to run "vagrant share --ssh" command it trying to create new VM and trying  to copy VBoxGuestAdditions.iso to the newly created VM, that time only we are getting the above exception.

**Host machine:**

Filesystem      Size   Used  Avail Capacity  Mounted on
/dev/disk1     233Gi  112Gi  121Gi    49%    /
devfs          188Ki  188Ki    0Bi   100%    /dev
map -hosts       0Bi    0Bi    0Bi   100%    /net
map auto_home    0Bi    0Bi    0Bi   100%    /home

**Guest machine:**
Filesystem                                                     Size  Used Avail Use% Mounted on
/dev/mapper/centos-root                                         19G  4.7G   14G  25% /
devtmpfs                                                       910M     0  910M   0% /dev
tmpfs                                                          920M   76K  920M   1% /dev/shm
tmpfs                                                          920M  8.3M  912M   1% /run
tmpfs                                                          920M     0  920M   0% /sys/fs/cgroup
/dev/sda1                                                      497M  171M  326M  35% /boot
vagrant                                                        233G  112G  121G  49% /vagrant
tmp_vagrant-puppet_modules-d63a21852570f0945cb0dcc66f379617    233G  112G  121G  49% /tmp/vagrant-puppet/modules-d63a21852570f0945cb0dcc66f379617
tmp_vagrant-puppet_manifests-5058f1af8388633f609cadb75a75dc9d  233G  112G  121G  49% /tmp/vagrant-puppet/manifests-5058f1af8388633f609cadb75a75dc9d
tmpfs                                                          184M     0  184M   0% /run/user/1000

After removing the "hashicorp/precise64" also getting the same exception

**Exception:**
https://gist.githubusercontent.com/sann3/caf55988c205df8fe7ceb1d3e0200f6e/raw/fd0cb2f91ca2df1da0ef5527801b63285f06873d/vagarntsshexception
