### ISSUE TITLE
Vagrant up fails with VirtualBox 5.1.24

### ISSUE THREAD

**Issue by pnedkov** [mitchellh/vagrant#8793]
### Vagrant version
Vagrant 1.9.7

### Host operating system
Arch Linux

### Guest operating system
CentOS 6

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
end
```

### Expected behavior
The CentOS VM should be deployed successfully.

### Actual behavior
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/6'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/6' is up to date...
==> default: Setting the name of the VM: test_default_1500486941857_98327
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing 'VBoxManage', a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "8a33f87e-d917-49a3-a808-7b73bfda4f0c", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'test_default_1500486941857_98327' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

### Steps to reproduce
1. mkdir test
2. cd test/
3. vagrant init centos/6
4. vagrant up

### References

From the VirtualBox 5.1.24 changelog:
`API: return the correct error code if powering up a VM fails`

**Comment by dominikzogg** [comment]
Non of my machines can handle nfs since update:
==> default: Mounting NFS shared folders...

first i tough its cause kernel 4.12 (which made problems with older virtualbox than 5.1.24) but same for 4.11 (ubuntu, kernel ppa)

**Comment by dzschille** [comment]
I had the same problem, *vagrant up* stuck on "Mounting NFS shared folders" for too long.

I found the solution [here in the forum](https://bbs.archlinux.org/viewtopic.php?id=228365). On my host maschine the vboxnet0 interface was down. You can start it with 

`sudo ip link set dev vboxnet0 up`

**Comment by jayywolff** [comment]
On ArchLinux kernel 4.11.9 
virtualbox 5.1.24
vagrant 1.9.7

I don't have any issues starting vagrant but my port forwarding was not working.

 @dzschille thanks for referencing that forum post, that guy had my exact issue. Bringing up the vboxnet0 interface solved it for me.

**Comment by lbausch** [comment]
@dzschille solution worked for me (Debian testing, VirtualBox 5.1.24 r117012 (Qt5.7.1), Vagrant 1.9.7)

**Comment by pnedkov** [comment]
Never had problem with vboxnet0 not being up. As soon as I downgrade to VirtualBox 5.1.22 everything works.

```
ifconfig vboxnet0
vboxnet0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 0a:00:27:00:00:00  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by dominikzogg** [comment]
@dzschille thanks for your input, but i still hafe the nfs problem

**Comment by dzschille** [comment]
@dominikzogg when you have started the VirtualBox Manager GUI, and than enter on your host:

    ip link show dev vboxnet0

what is your output?
Also start the box with Vagrant debug mode:

    vagrant up --debug

This way you will perhaps get a hint what's wrong.

**Comment by dahousecat** [comment]
@dzschille solution works great, but I have to do this everything I restart my machine.
Why is this not being loaded automatically?
Is there a solution for a permanent fix?

**Comment by dzschille** [comment]
@dahousecat they are working on a fix: https://www.virtualbox.org/ticket/16911

**Comment by dominikzogg** [comment]
@dzschille thanks for the link, `ip link show dev vboxnet0` did not work. I've downgraded, so i will wait for virtualbox update

**Comment by kikitux** [comment]
not a vagrant issue

seems a virtualbox 5.1.24 on linux issue

use 5.1.22 in th meantime and check when parched version is out.

**Comment by mchojrin** [comment]
What has (somehow) worked for me was this update: https://www.virtualbox.org/wiki/Testbuilds. Following this thread https://www.virtualbox.org/ticket/16911 I upgraded vagrant to 1.9.7 and installed this build and it's working almost as before.

What's left for me to do is bring the vboxnetX interface up by hand... other than that everything is ok
