### ISSUE TITLE
Creating new vagrant VM box using vagrant cloud commands not working on 1.9.7

### ISSUE THREAD

**Issue by avmgan** [mitchellh/vagrant#8798]
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end

vagrant up command not working for new box creation

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄
