### ISSUE TITLE
NFS Sudoer file configuration

### ISSUE THREAD

**Issue by mrvkino** [mitchellh/vagrant#8801]
The documentation on how to setup the [sudoer](https://www.vagrantup.com/docs/synced-folders/nfs.html#root-privilege-requirement) file uses the admin group in OSX.

For some reason, with this setup, vagrant always ask for a password so it could setup the nfs mount. But if I change the last line:
```
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
```
for
```
%staff ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
```

It works as expected and does not ask me for a password.

I was wondering if the doc was out of date or if there is multiple setup depending on OSX version?

**Comment by kikitux** [comment]
If your user main group is admin, should work.

so is more a how the user was setup.

We can enhance the documentation here with a note.

**Comment by kikitux** [comment]
Submit https://github.com/mitchellh/vagrant/pull/8805 for review

**Comment by mrvkino** [comment]
Ha! Thanks. My first group seems to be staff. I would of thought that since I am in admin it would have worked anyway.

```
❯groups Shadow
Shadow : staff com.apple.sharepoint.group.1 everyone localaccounts _appserverusr admin _appserveradm _lpadmin com.apple.access_screensharing _appstore _lpoperator _developer com.apple.access_ftp com.apple.access_ssh
```
