### ISSUE TITLE
Can't access my vagrant (virtualbox) guest VM from my ubuntu 14.04 host 

### ISSUE THREAD

**Issue by asmaier** [mitchellh/vagrant#8802]
### Vagrant version
Vagrant 1.9.7

### Host operating system
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

### Guest operating system
hashicorp/precise64

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "private_network", ip: "33.33.33.10"
  config.vm.provision "shell", inline: "sudo apt-get -yqq install apache2"
end
```

### Debug output
https://gist.github.com/asmaier/15722bde53bc676de656c8be81c490af

### Expected behavior
I expected to see an output "It works" when doing

    curl http://33.33.33.10

on the host. 

### Actual behavior
Nothing happens. But when I run curl on the guest system I see that apache is running

```
curl http://33.33.33.10
<html><body><h1>It works!</h1>
<p>This is the default web page for this server.</p>
<p>The web server software is running but no content has been added, yet.</p>
</body></html>
```

### Steps to reproduce
1. `vagrant up`
2. `curl http://33.33.33.10`

On the host I see the adapter
```
ip addr show vboxnet1
9: vboxnet1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 0a:00:27:00:00:01 brd ff:ff:ff:ff:ff:ff
    inet 33.33.33.1/24 scope global vboxnet1
       valid_lft forever preferred_lft forever
```
and I can ping it
```
$ ping 33.33.33.1
PING 33.33.33.1 (33.33.33.1) 56(84) bytes of data.
64 bytes from 33.33.33.1: icmp_seq=1 ttl=64 time=0.058 ms
````
But I'm not able to connect to my guest machine with IP 33.33.33.10 in any way. 

### References
The Vagrantfile is taken from
https://github.com/mitchellh/vagrant/issues/7169

**Comment by asmaier** [comment]
Ok I figured out a workaround:
```
ip link set vboxnet1 up
```
brought the interface up and the curl command works as expected. But why is the vboxnet1 interface created but in a down state after running `vagrant up` ?

**Comment by kikitux** [comment]
@asmaier seems issue on vbox latest version when host is linux.
try one version behind.

https://www.virtualbox.org/ticket/16911
