### ISSUE TITLE
Feature - use Powershell Direct for Hyper-V Provider

### ISSUE THREAD

**Issue by anlx-sw** [mitchellh/vagrant#8810]
### Vagrant version
Vagrant 1.9.3

### Host operating system
Windows 10, Windows 2016

Hyper-V Provider

If you run Vagrant on Windows and want to provision (Windows) Guests there is a way with less dependencies to run your Powershell Scripts without any additional Setup using "Powershell Direct".
Powershell Direct is  way of running PowerShell commands inside a virtual machine from the host operating system.

https://blogs.technet.microsoft.com/virtualization/2015/05/14/powershell-direct-running-powershell-inside-a-virtual-machine-from-the-hyper-v-host/

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/powershell-direct

As the windows ways to pass on scripts to the guests using hyper-v (winrm, dynamically created smb v1 shares - which shouldn't be used any more for security reasons) are not optimal in my opinion this might be a viable alternative.

i don't know if Powershell Direct is also working (or planned to be supported) for Linux Guests running Powershell Core - but for the windows side this would be helpfull.

**Comment by kikitux** [comment]
@anlx-sw i think we are mixing the winrm remote requirements and powershell.

it looks to me you are proposing a new provisioner, lets say powershell-local, do you have any documentation to api calls or host calls where you can run a powershell from the host into the guest ?

Alvaro

**Comment by anlx-sw** [comment]
@kikitux  - yes -  a provisoner might be the right way - not only for scripting. but it can also be used to exchange with the guest without any network connectivity.

the second link in my initial post contains details on how to invoke the commands using powershell:
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/powershell-direct

you can invoke a command block with
`Invoke-Command -VMName <VMName> -ScriptBlock { cmdlet } `

to run a powershell interactively use:
`Enter-PSSession -VMName <VMName>`

there is also the possibility to create persistent sessions and the possilbity to copy files mentioned.

or - is there maybe a way to include shell commands on the host system in a vagrant file?
then this features might already be used calling the hosts powershell.exe with the right commands.
