### ISSUE TITLE
How to set envionment variables  and  /etc/hosts through Vagrantfile?

### ISSUE THREAD

**Issue by ouewqa** [mitchellh/vagrant#8811]
### Vagrant version
Vagrant 1.9.7

### Host operating system
Darwin bogon 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

### Guest operating system
istributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

In docker-composer,  set **environment** and **extra_hosts** 
In vagrant, how to do this?

**Comment by benyanke** [comment]
Env vars sounds more like a bootstrap script behavior on the guest side.


However, the hostsfile editing can be handily done with a plugin. Example Vagrantfile lines below.
https://gist.github.com/benyanke/ee70204bde5a5f45fb331071b050ec26

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
