### ISSUE TITLE
Vagrant Provisioning to Puppet

### ISSUE THREAD

**Issue by nama08** [mitchellh/vagrant#8812]
Hi,

Is it possible for someone to give an example of **/manifests/default.pp** to do the following:
***execute apt-get update**
**install curl**
**install nodejs****
**Note:** first need to execute the following line in order to install the correct version of node.js:
**curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -**

Checking the following articles but things are not sorted out yet:
http://www.jeroenreijn.com/2014/11/using_vagrant_with_puppet.html 
https://www.vagrantup.com/docs/provisioning/puppet_apply.html

So I am looking for example of manifests file and default.pp, ... possible?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
