### ISSUE TITLE
Vagrant Commands in Argument-Specified Path

### ISSUE THREAD

**Issue by benyanke** [mitchellh/vagrant#8813]
### Vagrant version
Vagrant 1.9.6

### Host operating system
Ubuntu 16.04.2 LTS

### Guest operating system
N/A

### Issue

Vagrant commands are great, but only if you're running in the proper directory. It gets much more awkward when trying to script vagrant commands or use in the host-system cron.

Currently, the only way I've found to run path-independent vagrant commands is by using subshells. For example, a section of my crontab

```
##################################
# Bring Up Vagrant VM at Set Times
##################################

# Note: vagrant box comes up in about six minutes

# 7:20am - before I arrive
20 7 * * 1-5 (cd /home/benyanke/vagrant-boxes/marketing-site/; /usr/bin/vagrant up) >/dev/null 2>&1

# 6:30pm - Destroy for the night
30 18 * * 1-5 (cd /home/benyanke/vagrant-boxes/marketing-site/; /usr/bin/vagrant destroy -f) >/dev/null 2>&1
```

Most other CLI programs handle absolute path specification (`make -C <directory>`, `git -C <directory> pull`).

Is there any plans to add this to vagrant, or is it perhaps there and I simply haven't found it? 

`vagrant -C '/home/benyanke/vagrant-boxes/marketing-site/' up`

**Comment by chrisroberts** [comment]
Hi there,

This can be accomplished using the `VAGRANT_CWD` environment variable:

https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_cwd

Cheers!

**Comment by benyanke** [comment]
I missed that, thank you! Vagrant is an amazing tool for development. It saves me countless hours and headaches.
