### ISSUE TITLE
bootstrap-salt.ps1: needs to handle py2/py3 in installer filenames

### ISSUE THREAD

**Issue by dafyddj** [mitchellh/vagrant#8816]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
`Vagrant 1.9.7`

### Host operating system
```
ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G29
```
### Guest operating system
`Windows 8.1`

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
```
PS C:\Users\vagrant> C:\tmp\bootstrap_salt.ps1 -version 2017.7.0
Service defaulting to run.
Downloading Salt minion installer Salt-Minion-2017.7.0-AMD64-Setup.exe
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\tmp\bootstrap_salt.ps1:56 char:1
+ $webclient.DownloadFile($url, $file)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Installing Salt minion...
C:\tmp\salt.exe : The term 'C:\tmp\salt.exe' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\tmp\bootstrap_salt.ps1:75 char:3
+   C:\tmp\salt.exe /S | Out-Null
+   ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\tmp\salt.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

C:\tmp\salt.exe /S
```

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
saltstack/salt-bootstrap#1119

**Comment by briancain** [comment]
Hi there @dafyddj - this seems to have been fixed. I was able to install salt with the vagrant provider on windows. I'm going to go ahead and close the issue. If it's still a problem for you please let us know and we'll re-open the issue, thanks!
