### ISSUE TITLE
vagrant share ngrox in `rescue in execute': No such file or directory 

### ISSUE THREAD

**Issue by wraycode** [mitchellh/vagrant#8818]
### Vagrant version
Vagrant 1.9.7

### Host operating system
ubuntu 17
### Guest operating system
ubuntu 14
### Vagrantfile
~# cat Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
   config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
   config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
   config.vm.synced_folder "/home/jbarton/Code", "/home/vagrant/Code",mount_options: ["dmode=775,fmode=777"]

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
   config.vm.provider "virtualbox" do |vb|
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
   end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  #    config.vm.provision "shell", inline: <<-SHELL
  #   sudo add-apt-repository -y ppa:ondrej/php
  #   sudo apt-get -y update
  #   apt-get install -y apache2
  #   sudo apt-get install php7.0
  # SHELL
end

```

### Expected behavior
get vagrant share
### Actual behavior
~# vagrant share
Vagrant Share now defaults to using the `ngrok` driver.
The `classic` driver has been deprecated.

For more information about the `ngrok` driver, please
refer to the documentation:

  https://www.vagrantup.com/docs/share/

==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:  
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:  
    default: Local HTTP port: 8080
    default: Local HTTPS port: disabled
    default: Port: 2222
    default: Port: 8080
==> default: Creating Vagrant Share session...
/opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/util/subprocess.rb:146:in `rescue in execute': No such file or directory - ngrok (Vagrant::Util::Subprocess::LaunchError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.7/lib/vagrant/util/subprocess.rb:139:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2451:in `block in start_ngrok_proxy'

### Steps to reproduce
vagrant login
vagrant share

**Comment by whglamrock** [comment]
I am having the same issue

**Comment by whglamrock** [comment]
Hi,

Why did you close the topic? Did you find your solution? If could, please share it thank you so much

**Comment by wraycode** [comment]
I just realized I didn't need to use vagrant share I can run ngrok and share any port with no problem
