### ISSUE TITLE
get error while vagrant up

### ISSUE THREAD

**Issue by KizBaolin** [mitchellh/vagrant#8829]
Hi, all,

I got an error while "vagrant up". Before I get back to the office, this works well. I don't know what have happend. I also have tried several answers in google, but they don't work well for me. I'd appreciate if someone could help. Here is the error information:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "f29376ab-db69-4b7e-8895-21394af959a0", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'supersmart_default_1494145933288_33527' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

$ VBoxManage -v
5.1.22r115126
$ vagrant -v
Vagrant 1.9.4
$ cat /proc/version
Linux version 3.10.0-327.el7.x86_64 (bui...@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015

Best Regards

**Comment by kikitux** [comment]
Hello

Error is coming from virtualbox

open virtualbox gui, stop start vm from there

it should help to see what the error is

have you tried to destroy and create the box again? or a new box?

**Comment by swayamraina** [comment]
I tried creating a new box but the error still persists.
