### ISSUE TITLE
Vagrant + VMware "No usable default provider could be found for your system" 

### ISSUE THREAD

**Issue by Montana** [mitchellh/vagrant#8834]
I have the Vagrant + VMWare combo , and anytime I run vagrant plugins list it says "no plugins installed" -- but in a non VMWare environment there doesn't seem to be a problem. So If I were to run 

<pre>sudo vagrant up --provider vmware_fusion</pre> 

I would just get this repeating error 

"No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

**Comment by chrisroberts** [comment]
Hi there,

The VMware provider for Vagrant is provided via a plugin. You can learn more about it here:

https://www.vagrantup.com/vmware/index.html

Cheers!
