### ISSUE TITLE
Reconcile sudoers advice

### ISSUE THREAD

**Issue by danepowell** [mitchellh/vagrant#8842]
Currently, the vagrant codebase has two recommendation for NFS sudoers files, at least for Ubuntu users.

The first version is in the website docs: https://github.com/mitchellh/vagrant/blob/master/website/source/docs/synced-folders/nfs.html.md#root-privilege-requirement

The second version is in the contrib directory:
https://github.com/mitchellh/vagrant/blob/master/contrib/sudoers/linux-ubuntu

These are very different, and currently only the version in the website docs seems to work.

We should consolidate these so that the documentation doesn't exist in two places and get out of sync again.

**Comment by boyloveboy5784** [comment]
โหลดหน่อย
