### ISSUE TITLE
Create a private DHCP network but assign a fixed IP to an instance

### ISSUE THREAD

**Issue by richbos** [mitchellh/vagrant#8848]
Hi, I am not sure if what I am trying to achieve is actually possible, but here goes. 

I am trying to create an instance within an extra private DHCP network, but allocate it a fixed IP (so that I know the IP to access from the host browser in advance).

It would seem that if I don't create a DHCP network that the instance isn't accessible from the host browser. I know that I could `vagrant ssh` after launch and `ip addr show`, but I'd like to know the IP for eth1 in advance.

### Vagrant version
1.6.2

### Host operating system
Ubuntu 16.04

### Guest operating system
CentOS7

### Vagrantfile
```
Vagrant.configure("2") do |config|
 config.vm.provider "virtualbox" do |vb|
   vb.customize ["modifyvm", :id, "--memory", "1024"]
 end
 config.vm.box = "centos/7"
 config.vm.hostname = "server"
 config.vm.network "private_network", type: "dhcp", ip: "192.168.50.50"
 config.vm.provision :shell, path: "../config.sh"
end
```

### Expected behavior
Instance launches in vboxnet0 DHCP network but with a static assigned IP as specified (192.168.50.50)

### Actual behavior
Instance launches in vboxnet0 DHCP network but with a dynamically assigned IP (192.163.50.3)

### Steps to reproduce
Run the vagrant file.

**Comment by ggeldenhuis** [comment]
Try changing type to static or just remove it all together. There is an example here of what you are trying to achieve.
https://www.vagrantup.com/docs/virtualbox/networking.html

**Comment by richbos** [comment]
Hi @ggeldenhuis , many thanks, we have removed the DHCP scope entry and behaviour is as expected. We can get by without DHCP.

```
Vagrant.configure("2") do |config|
 config.vm.provider "virtualbox" do |vb|
   vb.customize ["modifyvm", :id, "--memory", "1024"]
 end
 config.vm.box = "centos/7"
 config.vm.hostname = "rancher-srv"
 config.vm.network "private_network", ip: "192.168.50.50"
 config.vm.provision :shell, path: "../server.sh"
end
```
