### ISSUE TITLE
chmod not working

### ISSUE THREAD

**Issue by HanSon** [mitchellh/vagrant#8856]
![image](https://user-images.githubusercontent.com/10583423/29015996-0361cbd8-7b83-11e7-8829-efe8489718ce.png)

### Vagrant version
1.9.1

### Host operating system
windows 10

### Guest operating system
ubuntu

**Comment by briancain** [comment]
Hello @HanSon - It looks like you are mounting a non-POSIX style filesystem to ubuntu, which would explain why chmod'ing a directory that is on your host (windows) being shared to your guest (ubuntu) is not working. You might be able to use the work around from this issue, #7653, by using the mount_options through virtualbox. Thanks!
