### ISSUE TITLE
Launching vagrant as a subprocess in Python on Windows causes it to think it's running in WSL

### ISSUE THREAD

**Issue by pfaffle** [mitchellh/vagrant#8860]
I have some automation which is driven by Python and also makes use of Vagrant (among other things). Since the Vagrant 1.9.7 update, launching Vagrant as a subprocess within my Python scripts is broken on my system. Something about how Python launches the subprocess seems to make Vagrant think it's being run in the WSL environment, which is not my intention and I haven't set it up to be run that way. The reason I think it's trying to run in WSL is because running the same Vagrant command works in PowerShell (shown in my gist link), but if I run it in Bash on Ubuntu on Windows, I get the same error that Vagrant's output gives me in Python.

I see that there are new docs on the Vagrant website describing how to do it, but I don't have a need for that right now. I'd like to just have it run in the regular Windows environment like it used to.

Note that what I did in the gist works fine for me on Vagrant 1.9.6.

### Vagrant version
Vagrant 1.9.7

### Host operating system
Windows 10 Build 15063

### Guest operating system
n/a

### Vagrantfile
n/a

### Debug output
https://gist.github.com/pfaffle/cb1381b1ece7d31c02e4878ab7b06a08

### Expected behavior
Vagrant should have launched the vagrant.exe binary in a Windows shell.

### Actual behavior
Vagrant launched it in WSL Bash, and errored out.

### Steps to reproduce
1. Install Vagrant 1.9.7
2. Install the Creator's Update, WSL and Ubuntu on Windows 10
3. Install Python 3.4.3
4. Run the Python interpreter, import the subprocess module, and try to spawn Vagrant in a subprocess.

**Comment by pfaffle** [comment]
I've also tried changing the command line executed by Python to be `cmd /c vagrant -v`, and setting `Shell=False` which doesn't fix things either.

**Comment by robwiss** [comment]
I don't think vagrant is supposed to report `stdin is not a tty` when run from the WSL. This may be linked to #8858.

**Comment by robwiss** [comment]
I created this issue against BashOnWindows, perhaps some of the replies there could be helpful.

https://github.com/Microsoft/BashOnWindows/issues/2406

**Comment by chrisroberts** [comment]
I believe the 1.9.8 release should have resolved this issue. @pfaffle can you confirm if you are still seeing this issue or if it has been resolved with the latest release? Thanks!

**Comment by pfaffle** [comment]
@chrisroberts Yes, it works in Vagrant 1.9.8. Thank you!
