### ISSUE TITLE
Issues with settings on Windows 10

### ISSUE THREAD

**Issue by NaijaProgrammer** [mitchellh/vagrant#8861]
I am trying to use this to setup homestead_improved on my local system. When I run `vagrant up`, I get the following error:

> `Bringing machine 'default' up with 'virtualbox' provider...
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> shell provisioner:
> * The following settings shouldn't exist: name
> * The following settings shouldn't exist: name
> * The following settings shouldn't exist: name
> * The following settings shouldn't exist: name
> * The following settings shouldn't exist: name
> * The following settings shouldn't exist: name
> `

Here's my vagrant file: 

```
`require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION = "2"
confDir = $confDir ||= File.expand_path(".")

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exists? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
    end

    if File.exists? homesteadYamlPath then
        Homestead.configure(config, YAML::load(File.read(homesteadYamlPath)))
    elsif File.exists? homesteadJsonPath then
        Homestead.configure(config, JSON.parse(File.read(homesteadJsonPath)))
    end

    if File.exists? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath
    end
end`
```

Here are my environment details: 
OS: Windows 10
virtual box version: 4.3.40 (It wouldn't work with latest version of virtual box 5.*)
vagrant version: 1.7.2
![4](https://user-images.githubusercontent.com/11312413/29064969-925e7922-7c22-11e7-8e45-74761f8ac0dd.png)

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a simple Vagrantfile that reproduces the error state you are encountering. Due to your Vagrantfile using an unknown method to provide configuration:

```ruby
    if File.exists? homesteadYamlPath then
        Homestead.configure(config, YAML::load(File.read(homesteadYamlPath)))
    elsif File.exists? homesteadJsonPath then
        Homestead.configure(config, JSON.parse(File.read(homesteadJsonPath)))
    end
```

there is no way to easily reproduce the error you are currently experiencing. Please also include a gist of the `--debug` output to help in locating the root cause of the issue. Thanks!

**Comment by NaijaProgrammer** [comment]
Hello,

Finally located the cause. It wasn't an issue with Vagrant per se, it was from a file in Homestead, specifically `homestead.rb`. I traced the problem to the file, fixed it, and it's working fine now.
