### ISSUE TITLE
Ubuntu 16.04 Vagrant installation failure

### ISSUE THREAD

**Issue by AliYmn** [mitchellh/vagrant#8869]
Hi , 

    curl http://download.panamax.io/installer/ubuntu.sh | bash

Result ; 

       The guest machine entered an invalid state while waiting for it
	to boot. Valid states are 'starting, running'. The machine is in the
	'gurumeditation' state. Please verify everything is configured
	properly and try again.

	If the provider you're using has a GUI that comes with it,
	it is often helpful to open that and watch the machine, since the
	GUI often has more helpful error messages than Vagrant can retrieve.
	For example, if you're using VirtualBox, run `vagrant up` while the
	VirtualBox GUI is open.

	The primary issue for this error is that the provider you're using
	is not properly configured. This is very rarely a Vagrant issue.

NOT : 
Vagrant 1.6 or newer installed.
Virtualbox 4.3 or newer installed.

**Comment by chrisroberts** [comment]
Hi there,

> `curl http://download.panamax.io/installer/ubuntu.sh | bash`

This is not an official way to install or use Vagrant. For more information on installing Vagrant, please see the install page in the documentation:

https://www.vagrantup.com/docs/installation/

If you are still experiencing problems after properly installing Vargrant and the desired provider, please create a new issue and include all the information requested by the new issue template.

Cheers!

**Comment by skmaingi** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: download.panamax.io

**Comment by kikitux** [comment]
This is not an official way to install or use Vagrant. For more information on installing Vagrant, please see the install page in the documentation:

https://www.vagrantup.com/docs/installation/
