### ISSUE TITLE
How to configure IP and network on VMWARE vSphere using Vagrant?

### ISSUE THREAD

**Issue by ashokvaddevalli** [mitchellh/vagrant#8879]
I have created guest Windows VM on vsphere using Vagrant vsphere provider. In template it's already configured IP and network, using this template I need to create multiple VM's  and configure with different IP's. 
How to configure IP on guest VM using Vagrant?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
