### ISSUE TITLE
Please add documentation on accessing host from guest

### ISSUE THREAD

**Issue by george-norris-salesforce** [mitchellh/vagrant#8890]
Please add documentation on accessing a service running on the host machine from a browser running on the guest machine VM. The other way around (accessing web service on guest from host) seems well documented in your docs, but this use case is not.

Sorry if this is not the correct place to post this, but I can't seem to post in your G group. Thx!
https://groups.google.com/forum/#!forum/vagrant-up

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there.

Google has instructions on how to post a new message to google groups, hopefully that solves your issue! https://support.google.com/groups/answer/1046523?hl=en

Thank you and have a great day! 😄
