### ISSUE TITLE
Vagrant failed to load a configured plugin source. No such name (https://gems.hashicorp.com/specs.4.8.gz)

### ISSUE THREAD

**Issue by dagman** [mitchellh/vagrant#8893]
Hi! Need you help guys. 
I am on linux mint 18.1 Serena 32-bit(but unfortunately not yet linux guru though cannot spot issue)
vagrant version - 1.9.7

### Debug output
 [gist](https://gist.github.com/dagman/7993fb7aaa3397500b7bd780498bef8a)

### Expected behavior
The plugin should have been installed.

### Actual behavior
An error occured while installing.

### Steps to reproduce
1. Install linux mint 18.1 Serena on 32-bit system
2. install vagrant
3. vagrant plugin install vagrant-hostsupdater

**Comment by briancain** [comment]
Hi there @dagman -

Please try running the plugin install command just to be sure. If that still fails, are you able to manually fetch the file in question?

```
curl -v -O https://gems.hashicorp.com/specs.4.8.gz
```

**Comment by dagman** [comment]
@briancain sorry for late response(got hard few days). I can't say why it's happened, but all of a sudden a can fetch plugin(very strange). I wish someone explain it.

**Comment by briancain** [comment]
@dagman - ok thanks! Glad it works now :)

**Comment by estuart** [comment]
You might have run into a problem with your machine pulling an IPv6 address. I have observed that either the `vagrant plugin` command or the server at `https://gems.hashicorp.com/specs.4.8.gz` do not play well with IPv6.

On OSX 10.12.6 I disabled IPv6 for my network interface and was able to avoid this error and install plugins.

I'm not sure if this was your issue but I hope it helps someone!

**Comment by frenck** [comment]
Confirmed. Same issue on my end.
Seems to be an IPv6 issue. OSX 10.12.6 here as well.

`curl -6 -v -O https://gems.hashicorp.com/specs.4.8.gz` fails, while the ipv4 variant works.

Disabled ipv6 and everything works as expected.

```txt
* Hostname was NOT found in DNS cache
*   Trying 2600:9000:211b:4a00:b:36d6:3540:93a1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0* connect to 2600:9000:211b:4a00:b:36d6:3540:93a1 port 443 failed: Operation timed out
*   Trying 2600:9000:211b:dc00:b:36d6:3540:93a1...
  0     0    0     0    0     0      0      0 --:--:--  0:02:30 --:--:--     0* connect to 2600:9000:211b:dc00:b:36d6:3540:93a1 port 443 failed: Operation timed out
*   Trying 2600:9000:211b:ea00:b:36d6:3540:93a1...
```

**Comment by jmholla** [comment]
I know this is closed, but is there a related issue for this IPv6 stuff? I'm still seeing it myself.
