### ISSUE TITLE
vagrant commands freeze in git bash 

### ISSUE THREAD

**Issue by lbuyse** [mitchellh/vagrant#8896]
### Vagrant version
1.9.7

### Host operating system
Windows 10

Hello , 
vagrant commands in windows 10 in git bash completely freezes , no feedback , no more input possible.
This problem occurs in the 64-bit version of vagrant 1.9.7 since there are separated installers for 32 and 64 bit. I have tested with 1.9.5 (only one windows installer) and then the problem doesn't occur.

Kind regards,
Laurens

**Comment by mradcliffe** [comment]
I ran into something similar with the 1.9.7 64-bit on Windows 7, but I did not encounter the same issue on a separate Windows 10 using 1.9.7 64-bit installer. I do not know if the issue I encountered on Windows 7 is related to this issue or not, but I wanted to note that the behavior was similar.

**Comment by lbuyse** [comment]
Strange , i had the problem on windows 10 with 1.9.7 64-bit version. I reinstalled 1.9.5 version and it worked.

**Comment by BubbleSnap** [comment]
I have no problem with the combindation of Git bash 64bit and 1.9.7 or 1.9.8 64bit on Windows 10. Occasionally slow, but that's the limit of the issues I see. What version of git bash are you using?

**Comment by chrisroberts** [comment]
This may have been the result of the wintpy wrapping. It has been resolved in the 1.9.8 release. If you continue to experience problems after upgrading, please open a new issue. Thanks!
