### ISSUE TITLE
More documetation needed on the Default Provider page

### ISSUE THREAD

**Issue by monrealis** [mitchellh/vagrant#8905]
You write here https://github.com/mitchellh/vagrant/blob/master/website/source/docs/providers/default.html.md that 

> VirtualBox is the default provider for Vagrant

Is it really? This is not the first box I am experimenting with and VirtualBox is not the default for me. I did not configure anything about the default provider.

```shell
[vytenis@tunferas consul-course]$ rpm -qa | grep VirtualBox
VirtualBox-5.1-5.1.26_117224_fedora25-1.x86_64
[vytenis@tunferas consul-course]$ rpm -qa | grep vagrant
vagrant-libvirt-0.0.35-4.fc25.noarch
vagrant-1.8.5-3.fc25.noarch
[vytenis@tunferas consul-course]$ cat /etc/fedora-release 
Fedora release 25 (Twenty Five)
[vytenis@tunferas consul-course]$ set | grep -i vagrant
[vytenis@tunferas consul-course]$ ls -A
Vagrantfile
[vytenis@tunferas consul-course]$ cat Vagrantfile 
Vagrant.configure("2") do |config|
  config.vm.box = "wesmcclure/ubuntu1404-docker"
  config.vm.define "consul-server" do |cs|
      cs.vm.hostname = "consul-server"
      cs.vm.network "private_network", ip: "172.20.20.31"
  end
end
[vytenis@tunferas consul-course]$ vagrant up
Bringing machine 'consul-server' up with 'libvirt' provider...
==> consul-server: Box 'wesmcclure/ubuntu1404-docker' could not be found. Attempting to find and install...
    consul-server: Box Provider: libvirt
    consul-server: Box Version: >= 0
==> consul-server: Loading metadata for box 'wesmcclure/ubuntu1404-docker'
    consul-server: URL: https://atlas.hashicorp.com/wesmcclure/ubuntu1404-docker
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: wesmcclure/ubuntu1404-docker
Address: https://atlas.hashicorp.com/wesmcclure/ubuntu1404-docker
Requested provider: [:libvirt]
```
Is there some configuration file that I do not know of where the default provider is configured?

In any case either the documentation is not correct or more explanation would be welcome.

**Comment by briancain** [comment]
Hi there @monrealis - it looks like you have installed Vagrant through your distros rpm packages, rather than through a hashicorp installer. If I recall correctly, rpm does set something specifically to make `libvirt` the default. This would explain why you are finding that your install of vagrant is using a different default provider. Apologies for the confusion here. There are a couple of ways around this, if you don't feel like specifying the `--provider` flag when vagrant up'ing or setting the environment variable. For example, you can define which provider your vm should use within your Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "wesmcclure/ubuntu1404-docker"
  config.vm.define "consul-server" do |cs|
      cs.vm.hostname = "consul-server"
      cs.vm.network "private_network", ip: "172.20.20.31"
      cs.vm.provider :virtualbox
  end
end
```

Hope this helps, thanks! I'll go ahead and close this issue. Let me know if you have any more questions!

**Comment by monrealis** [comment]
Thanks! Maybe someone could mention in the documentation page that the default may be distribution specific.
By the way, do you have any idea in which configuration file the default could be specified?

**Comment by briancain** [comment]
More information can be found here for rpm and vagrant (released in Vagrant `1.9.7`): https://github.com/mitchellh/vagrant/pull/8558

However even with those changes in place, it looks like your system already has `vagrant-libvirt` installed, so I think it will still default to that provider?

I'm not sure where in rpm they would be specifying that array of providers, but I assume libvirt likely comes before virtualbox (if virtualbox is even in that list).

**Comment by monrealis** [comment]
Thanks, I found it.
```bash
[vytenis@tunferas ~]$ rpm -qf /usr/bin/vagrant 
vagrant-1.8.5-3.fc25.noarch
[vytenis@tunferas ~]$ grep -A 3 "# libvirt provider as a default" /usr/bin/vagrant 
# libvirt provider as a default
if [ -z $VAGRANT_DEFAULT_PROVIDER ]; then
  export VAGRANT_DEFAULT_PROVIDER=libvirt
fi
```

**Comment by monrealis** [comment]
By the way, that `cs.vm.provider :virtualbox` doesn't seem to have any effect, I need to use `--provider=virtualbox`.
