### ISSUE TITLE
Solus Linux Support

### ISSUE THREAD

**Issue by mattandersen** [mitchellh/vagrant#8907]
### Vagrant version
Vagrant 1.9.8.dev

### Host operating system
Solus Linux

### Guest operating system
Any

### Expected behavior
When starting a guest with NFS synced folders, the exports file should be modified correctly and the NFS service should be reloaded successfully.

### Actual behavior
The service is not reloaded, so exports are not available to the guest. This is due to using the fallback linux host which does not attempt to reload services through systemd.

### Proposed Change
Add support for the through a host plugin. See related PR for an implementation.

**Comment by chrisroberts** [comment]
Fixed via #8938. Cheers!
