### ISSUE TITLE
Proposed Changes: vagrant commands fail without FULL root access.

### ISSUE THREAD

**Issue by subs-comps-git** [mitchellh/vagrant#8919]
### Vagrant version
All versions
### Host operating system
Windows 8.1
### Guest operating system
Any Unix or Linux
### Vagrantfile
#-*- mode: ruby -*-
#vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "basebox-vbox-centos7"
    config.vm.communicator = "ssh"

    config.ssh.username = "vagrant"
    config.ssh.private_key_path = "/Users/<User>/.ssh/id_rsa_vagrant"
    
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
    config.vm.synced_folder ".", "/home/vagrant/synced", create: true, owner: "vagrant",
      group: "vagrant", mount_options: ["dmode=755", "fmode=644"]

    config.vm.provider :virtualbox do |v, override|
        v.gui = false
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", 1]
    end
end
### Expected behavior
‘Vagrant up’ should start the system and mount shared folders when provided proper permissions.
‘Vagrant halt’ should halt the system as expected. 
### Actual behavior
Without the following line in /etc/sudoers or /etc/sudoers.d/vagrant, ‘vagrant up’ and ‘vagrant halt’ fail and produce errors.

/etc/sudoers.d/vagrant
Vagrant		ALL=(ALL) NOPASSWD:ALL

‘vagrant up’ does not start the system properly and produces errors.
‘Vagrant halt’ does not shutdown system and an error is produced.
### Errors
https://gist.github.com/subs-comps-git/d6256b19d4b24dd6a6a49e54314829a5
### Reason for errors
All commands are run through a ‘bash –l’ shell which hides all commands run after its invocation and forces administrators to give root access, without a password, to the vagrant user for ALL commands. That is a very big security risk.
### Steps to reproduce
1.	Remove from /etc/sudoers or equivalent:            
 Vagrant	ALL=(ALL) NOPASSWD:ALL
2.	‘Vagrant up’ and ‘vagrant halt’ will no longer function correctly.

### Proposed Changes:
1.	Commands that require sudo should be run separately, allowing administrators to create a more secure installation.
2.	Administrators could then add each command separately to the sudoers file. Example:
Cmnd_Alias SHUTDOWN = /sbin/shutdown, /usr/sbin/shutdown
Cmnd_Alias MKDIR = /bin/mkdir, /usr/bin/mkdir
Cmnd_Alias MYCMDS = SHUTDOWN, MKDIR
vagrant ALL=(ALL) NOPASSWD:MYCMDS

**Comment by chrisroberts** [comment]
Hi there,

The changes you are proposing are incompatible with the purpose and functionality that Vagrant provides. The machine instances that Vagrant creates are not meant to be fully secured instances, rather they are intended to ease developer setup and tear down of development and test systems. Vagrant expects to have root access to the guest system which enables it to setup and provision the guest. This is detailed in the box setup documentation: 

https://www.vagrantup.com/docs/boxes/base.html#default-user-settings

If you intend to use a custom box that does not allow root access to the Vagrant user then most of the setup Vagrant provides will need to be disabled and an alternative means up setup will be required.

Cheers!

**Comment by subs-comps-git** [comment]
Hey Chris,

I was hoping for some clarification on your response. Specifically I'm not
sure how my proposed changes would be incompatible with either the purpose
or functionality of Vagrant. Allowing commands requiring sudo to run
individually rather than in a batch breaks nothing. Users could absolutely
run their systems exactly as they do now, nothing would change for them.

Making the change, however, would provide new functionality to Vagrant. It
would allow proper logging of commands run by sudo. Logging is important
for debugging problems and when you use a command like `sudo bash -l`
everything underneath is hidden making debugging difficult. The proposed
change would solve that issue. Logging is also important for catching bad
behavior, whither it's a process that should not be running or a system
that has been compromised.

A thought on security and I'll sign off, I know this is getting long,
thanks for getting this far. Sudo without limitations is simply a root
account. Why use sudo if the intention is to create a second root account?
Use the root account for Vagrant and you don't even have to maintain code
for sudo and users do not need to maintain or make changes to the sudoers
file. I have to think the choice to use sudo had a reason. The proposed
change would allow it's proper use without sacrificing functionality, in
fact it would add functionality.

Thanks for listening and regards, have a great day.

Jason

On Mon, Aug 28, 2017 at 9:46 AM, Chris Roberts [Masked] <
