### ISSUE TITLE
Tilde expansion not working in Vagrant 1.9.8

### ISSUE THREAD

**Issue by carlosefr** [mitchellh/vagrant#8922]
The following configuration, which previously would place the file in the user home directory, now places it in a directory explicitly called `~` inside the user's home directory.
```config.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig"```

### Vagrant version
Vagrant 1.9.8

### Host operating system
macOS 10.12.6 (Sierra)

### Guest operating system
CentOS 7.3

**Comment by briancain** [comment]
👋  hey @carlosefr - thanks for opening an issue! Apologies for the regression. This will be fixed in the next release of vagrant via https://github.com/mitchellh/vagrant/pull/8918. Thank you!
