### ISSUE TITLE
VIM 8.0 bug on Windows with vagrant ssh

### ISSUE THREAD

**Issue by julienkosinski** [mitchellh/vagrant#8942]
### Vagrant version
1.9.8

### Host operating system
Windows 10.0.15063

### Guest operating system
Archlinux

### Expected behavior
Vim 8.0 should work correctly

### Actual behavior
In Powershell or CMD in VIM we can't move the cursor with the arrows keys.
Moreover, it does not clear the screen so editing is melted with previous commands.
Some coloring are different from CMD to Powershell but behavior is the same.
![Bug VIM Powershell](https://i.imgur.com/9LL509d.png)
![Bug VIM CMD](https://i.imgur.com/2P10unA.png)

### Steps to reproduce
1. Use `config.vm.box = "terrywang/archlinux"`
2. Use vagrant ssh in CMD or Powershell
3. Just try to open a file with VIM

**Comment by schlueter** [comment]
This sounds like a Virtualbox issue, not Vagrant. What version of Virtualbox are you using?

Can you duplicate the issue with a different base box?

**Comment by julienkosinski** [comment]
@schlueter Hi! Thanks for you response. I'm using Virtualbox 5.1.26.
In fact everything is working great when I connect in SSH via PuTTy so it's a bug of vagrant ssh...

**Comment by julienkosinski** [comment]
Well, you were kind of right, I tested a more recent patch version of VIM 8.0 and it seems to work. Then I'm closing the issue. Seems to be a VIM bug :).
Thanks for all!
