### ISSUE TITLE
After the crash of macos sierra, it is time to start again

### ISSUE THREAD

**Issue by wakerman** [mitchellh/vagrant#8946]
搞了一个下午，搞好了....
直接删除换个issue吧

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄
