### ISSUE TITLE
vagrant ssh

### ISSUE THREAD

**Issue by liufeng11** [mitchellh/vagrant#8968]
### Vagrant version
1.9.8

### Host operating system
ubuntu16.04

### Guest operating system
linux4.9.9

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
config.vm.box = "hashicorp/precise64"



### Expected behavior
What should have happened?

### Actual behavior
 Permission denied (publickey).

### Steps to reproduce
1.vagrant init  hashicorp/precise64
2.vagrant up --provider=libvirt
3.vagrant ssh


What do i need to configure to make ssh successfully?

**Comment by briancain** [comment]
Hi there,

The box you are attempting to use does not support the provider you are using. If you'd like to use `hashicorp/precise64`, you need to pick a [supported provider](https://app.vagrantup.com/hashicorp/boxes/precise64). If you want to use the `libvert` provider, find a different box that supports that provider.

Thanks!

**Comment by liufeng11** [comment]
Thanks!
I change the box and use "ubuntu/xenial64" to try again. When I execute "vagrant up", the part result shows as belows. what  the "Vagrantfile" do I need to configure if I have this question?

==> default: Waiting for domain to get an IP address...
/root/.vagrant.d/gems/2.3.4/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:9:in `block in wait_for': The specified wait_for timeout (2 seconds) was exceeded (Fog::Errors::TimeoutError)
	from /root/.vagrant.d/gems/2.3.4/gems/fog-core-1.43.0/lib/fog/core/wait_for.rb:6:in `loop'

**Comment by briancain** [comment]
Hi @liufeng11 - if you are still using the libvirt provider, the box you selected does not support that provider. I recommend picking from one of these boxes here: https://app.vagrantup.com/boxes/search?provider=libvirt
